### ISSUE TITLE
Search should be reevaluated if entry is pasted

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1000]
JabRef 3.3dev--snapshot--2016-03-14--master--091b3c8
- Let JabRef search in the Float mode
- Search of a non existing entry in bib file A
- Search for that entry in bib file B (and find it)
- Copy the entry from B into A
- After pasting the entry in A, the search results do not change

Same when deleting an entry (?). Maybe here only the number of the found entries and the background of the search field should be updated: The table itself updates correctly when deleting an entry.

**Comment by lc9275** [comment]
Same thing happens when adding an item from doi (using the fantastic doi to bibtex function) after first having done a search for it. Would be good to update the search no matter what method is used to add an item (or remove an item for that matter).

**Comment by simonharrer** [comment]
We need an event system for this #1028

**Comment by stefan-kolb** [comment]
@simonharrer Can this be done now?

**Comment by simonharrer** [comment]
With the event API, it should be possible.

**Comment by lenhard** [comment]
If just tested this on the current master and it seems that it is working now.
