### ISSUE TITLE
Add the option to clear recent libraries

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#10003]
In the **File > Recent libraries** menu, it would be appropriate to provide, at the end of the list, the command “Clear Recent libraries,” as below

![image](https://github.com/JabRef/jabref/assets/21198231/d8184996-7905-42d8-aafd-dce1a39e1809)

*-- Posted by @Mattero339 in the discourse forum*

**Comment by demetres12** [comment]
hello @HoussemNasri, I would like to work on that.

**Comment by HoussemNasri** [comment]
Hi @demetres12, please make sure to get it as in the screenshot. There should be a [menu separator](https://docs.oracle.com/javafx/2/api/javafx/scene/control/SeparatorMenuItem.html) between the recent libraries and the "Clear recent libraries" menu item.

**Comment by demetres12** [comment]
@HoussemNasri As I see there is not a corresponding test class for the `FileHistoryMenu` class. So, do you think it's better to consider a *gui* test in reference to the aforementioned?

**Comment by HoussemNasri** [comment]
> A question here: Do you think is more proper after clearing the recent libraries,

I like the first approach too
