### ISSUE TITLE
Priority is not found in the drop-down list in library saving tab

### ISSUE THREAD

**Issue by ehehela** [JabRef/jabref#10010]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I cannot find _priority_ in the user specified order in library saving configuration (see figure below). But I can add _priority_ in .bib file and it works.
![屏幕截图 2023-06-13 092801](https://github.com/JabRef/jabref/assets/56829479/a0fa27bb-4f05-412a-9911-5a93f6eb5feb)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
JabRef returns only the common fields which do not include things like Priority.
