### ISSUE TITLE
Group order reset after adding a new group

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10017]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

mac os ventura

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a library
2. Add groups A, B, C
3. arrange groups to C, A, B
4. Add a new group D 
5. The groups are now back in A, B, C, D order

=> Expected order would be C, A, B, D

It seems to be that the default sort ordering A-Z is applied,
originally reported in the forum https://discourse.jabref.org/t/adding-new-group-changes-the-group-order-back-to-alphabetical-order/3855?u=siedlerchr

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by aqurilla** [comment]
Hi! I would like to take up this issue

**Comment by aqurilla** [comment]
For fixing this do we just remove the `sortAlphabeticallyRecursive` call here -

https://github.com/JabRef/jabref/blob/e991e8241e9a0c39b98d2be88aecb063cdf9249d/src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java#L179-L182

I wonder if maintaining the alphabetical order is a desirable feature for some users?

**Comment by Siedlerchr** [comment]
There's a right click menu option to sort the groups and subgroups

Nitin Suresh ***@***.***> schrieb am Di., 4. Juli 2023, 12:37:

**Comment by aqurilla** [comment]
Got it, thanks

**Comment by Siedlerchr** [comment]
So yeah just remove this for default on group adding and  and leave it to the user in the context menu

**Comment by aqurilla** [comment]
Default sorting also occurs when major edit modifications are carried out on a group. I am guessing that should also be removed, so as to have consistent behaviour?

**Comment by Siedlerchr** [comment]
Yes, that sounds like a good idea

Nitin Suresh ***@***.***> schrieb am Mi., 5. Juli 2023, 01:15:

**Comment by koppor** [comment]
Note that the behavior was introduced at a fix for https://github.com/koppor/jabref/issues/577 at https://github.com/JabRef/jabref/pull/9228. The PR, however, missed the requirement that groups should be added alphabetically only if they were sorted alphabetically before. -- Thinking longer, the requirement was not that good. We came up with a more sophisticated requirement at https://github.com/koppor/jabref/issues/577.
