### ISSUE TITLE
Type option for Bachelor's thesis

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#10029]
**Is your suggestion for improvement related to a problem? Please describe.**
A thesis can have different types, but right now, there is none for Bachelor's thesis.

**Describe the solution you'd like**
I want such a field, but not sure whether this also requires support for that in biblatex.

Do you know the best way to achieve this (or a good way, how to treat BA theses)?

**Comment by ThiloteE** [comment]
You could create your own custom entry type, but obviously biblatex based citationstyles will not adapt their style based on your custom type. For this reason, your best choice would have been to contact the biblatex project. You can find it here: https://github.com/plk/biblatex, but this is not necessary, as a quick search let me find following bachelor thesis related issue: https://github.com/plk/biblatex/issues/660

Looks like `bathesis` is a thing:

> The following keys are typically used in the \bibfield{type} field of \bibtype{thesis}, \bibtype{report}, \bibtype{misc}, and other entries:
> 
> \begin{keymarglist}
> \item[bathesis] An expression equivalent to the term <Bachelor's thesis>.
> \item[mathesis] An expression equivalent to the term <Master's thesis>.
> \item[phdthesis] The term <PhD thesis>, <PhD dissertation>, <doctoral thesis>, etc.
> \item[candthesis] An expression equivalent to the term <Candidate thesis>. Used for <Candidate> degrees that have no clear equivalent to the Master's or doctoral level.

But I am not sure what the \bibfield[type} field is about.

**Comment by claell** [comment]
Thanks for looking it up 🙂

So it seems the ball is now back in JabRef's field, as this type needs to be added to the dropdown field.

**Comment by ThiloteE** [comment]
1. I looked it up and the `type` field already exists.
   ![image](https://github.com/JabRef/jabref/assets/73715071/df43c108-bb68-46cc-b74e-640b04445763)

2. What could be better is the explanation of this required field:
   ![image](https://github.com/JabRef/jabref/assets/73715071/9a713330-0d6b-48ed-9cc8-7351c709541b)

   - [ ]  it should include examples.

3. If you feel like pushing it, you could request BachelorThesis to become a full type, just like MastersThesis or PhdThesis, but for this the ball is back in biblatex's garden.

**Comment by claell** [comment]
Maybe, I was not clear enough, or also misunderstood the concept in JabRef a bit.

I am aware that the field already exists in JabRef. I was talking about the dropdown for it. There, no option for Bachelor's thesis is shown:

![grafik](https://github.com/JabRef/jabref/assets/6171135/ec25f45a-f8f8-4f7f-98c3-c37dc2832f66)

So my suggestion is to add this to the dropdown.

**Comment by claell** [comment]
(I am not sure, where the data for the dropdown is currently coming from. Some options don't seem to make sense in that current scope (like `Technical report` or `Audio CD`. So maybe these dropdown suggestions are currently not dependent on the Entrytype.)

**Comment by claell** [comment]
(I am not sure, where the data for the dropdown is currently coming from. Some options don't seem to make sense in that current scope (like `Technical report` or `Audio CD`. So maybe these dropdown suggestions are currently not dependent on the Entrytype.)

**Comment by cmgoodall** [comment]
Hi, I am hoping this issue is still needing to be resolved. I would like to be assigned to the issue and work on it. Is someone able to please assign me the isuse? 

My proposed solution is to create another Entry Type to accomodate the choice of Bachelors Thesis. I have had a look at the code and believe this will be a manageable issue for me. Please let me know if you would prefer a different implementation.

**Comment by ThiloteE** [comment]
Thank you for your interest @cmgoodall

Please only add a "Type".
I know this is confusing, but a "type" is not the same as an "entry type".
Both, "types" and "entry types" should be compatible with either the Bibtex or the Biblatex standard, so if we introduce a new entry type, we should contact them. That said, BibTeX is dead and only the biblatex project is actively being worked on. We are lucky that the bathesis "type" already exists, so we do not need to contact them for it.

**Comment by Siedlerchr** [comment]
@ThiloteE PLease note that this is a documentation issue. Not a code issue.

**Comment by cmgoodall** [comment]
Hi @Siedlerchr, are you able to ellaborate by what you mean here? From my understanding, the issue was surrounding not having the appropriate Type to choose (Bachelor Thesis). If this is a documentation issue, that is fine, I'm just wanting to better understand what is required so I can have a positive impact on the repo.

**Comment by Siedlerchr** [comment]
Sorry ignore my comment, I confused the types here.

**Comment by cmgoodall** [comment]
Hi @ThiloteE, I've been looking through the code base to get a better understanding of where to add this 'Type'. 

From what I can see, the file the 'Types' are held are in [TypeEditorView.java](https://github.com/JabRef/jabref/blob/a97d8a9dddcb7837ee7fa1393f8fe08cc870a0e7/src/main/java/org/jabref/gui/fieldeditors/TypeEditorViewModel.java#L13). Are you able to confirm whether this is the correct place I need to edit? If it isn't I would very much appreicate some guidance.

**Comment by ThiloteE** [comment]
I am not good at coding (there are others here that can do that way better than me), but to me it looks like you could have found it. I would suggest to try to modify it on your fork of JabRef and try to run this new version and check if your new modified type will show in the UI ;-)

**Comment by cmgoodall** [comment]
I've implemented the new Type however, I'm now running into an issue when running the actual program. At first when JabRef[run] was executed, the app would open and I could see the changes I had made. However, now I get the following errors: 

`
Resetting customized entry types failed.: java.util.prefs.BackingStoreException: Synchronization failed for node '/org/jabref/customizedBibtexTypes/'

Resetting customized entry types failed.: java.util.prefs.BackingStoreException: Synchronization failed for node '/org/jabref/customizedBiblatexTypes/'
`

From here, run continues to execute however, even after 10 minutes, the program doesn't open. I've tried rebuilding the project as well as undoing any of the changes I made however, this doesn't seem to have worked. 

Does anyone know how to fix this?

**Comment by claell** [comment]
@cmgoodall thanks for working on this issue!

Regarding your error: If you search for one of the node names, there is a result: https://github.com/search?q=repo%3AJabRef%2Fjabref%20customizedBiblatexTypes&type=code

Possibly that helps you to further investigate. Similarly, you can probably also search for other parts of the exception, like "Resetting customized entry types failed" etc. to find the place in code where the Exceptions happen.

**Comment by Siedlerchr** [comment]
There's a command line argument for resetting your preferences. https://docs.jabref.org/advanced/commandline#reset-preferences--d-key

**Comment by cmgoodall** [comment]
@claell @Siedlerchr 

Thanks for helping me out with this one. 

The weird bit is that I've commented out all of my code that I've implemented and I'm still getting the same errors. I believe when I was able to first run the program from IntelliJ, I was able to to see 'Bachelor's Thesis' as an option. In the process I also changed my preferred library mode to 'biblatx'. I believe this is where the issue lies for some reason. 

Siedlerchr, I looked at the link you provided but cannot understand how to execute the commands. I am currently just trying to run the application through IntelliJ by executing JabRef[run] which is a gradle runner. If you know where I am going wrong with this step, please let me know!

**Comment by cmgoodall** [comment]
I've just recloned the whole repo as well and it's still happening. Anyone got any ideas?

**Comment by Siedlerchr** [comment]
You need to modify the run configuration and under program arguments you add that -d all

The things are stored in the preferences, you would have to reset or delete them. 
On mac They are stored in (~/Library/Preferences/). Look for jabref

**Comment by cmgoodall** [comment]
Thanks for that @Siedlerchr! Fixed my issue. No idea what was going on, cannot replicate the issue at all which is quite strange. Anyway, just submitted a merge reqest for this issue.

**Comment by Siedlerchr** [comment]
The error indicates that there is an issue in the preferences migration code, you should check that carefully:
	at org.jabref@100.0.0/org.jabref.migrations.PreferencesMigrations.upgradeStoredBibEntryTypes(PreferencesMigrations.java:180)

**Comment by cmgoodall** [comment]
Is it possible for my merge request to be reviewed?

**Comment by claell** [comment]
Thanks for fixing my issue!
