### ISSUE TITLE
Update Apache PDFBox from 1.8.11 to 2.0.0

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1004]
Apache PDFBox 2.0.0 has been released. There, [Jempbox has been replaced by Xmpbox](https://pdfbox.apache.org/2.0/migration.html). We internally use Jempbox for XMP handling. Thus, a simple update of the versions is not possible, but we should update the libraries to their most recent versions.

**Comment by Siedlerchr** [comment]
I'll look into that

**Comment by koppor** [comment]
Follow up at #1096.
