### ISSUE TITLE
Filelist does not show files without an extension

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#10075]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Fedora 38

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...Create a file without an extension e.g. "out" that contains bib entries
2. ...Open an existing library
3. ...From file menu choose "Import into current library", file selection menu shows "Any file" but the file "out" is not shown. If one renames out to have an extension it shows.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
@Siedlerchr Note that this is about GNOME / Linux, not macOS. It might happen that it is a GNOME issue.

@sambo57u In case the issue is NOT solved at your side, please provide more details about your desktop environment.
