### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by RJDan** [JabRef/jabref#10088]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

OS: Ubuntu Sway 23.04 x86_64,  Host: ASUSTeK COMPUTER INC. FA506IH, Kernel: 6.2.0-24-generic

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. run from terminal
2. fails to start with the following error
```
:$ jabref
/snap/jabref/2531/lib/runtime/bin/java: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/jabref/2531/lib/runtime/bin/java)
/snap/jabref/2531/lib/runtime/bin/java: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/jabref/2531/lib/runtime/bin/../lib/libjli.so)
/snap/jabref/2531/lib/runtime/bin/java: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/jabref/2531/lib/runtime/bin/../lib/libjli.so)
```

Started to do this after a recent snap update but I don't know which as I haven't used it in a while.

Problem occurs on 
latest/edge:      5.10.1111 2023-07-15 (2531) 225MB -
and      5.10.1108 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
can you manually install libc6 or check which version is installed on your OS?

**Comment by ThiloteE** [comment]
can reproduce with Linux Mint 20.3 using the portable version of the latest development version from today.
Christoph mentioned, maybe this is caused by a bug in the *not yet officially released* jdk21 we use for the development version.

**Comment by ThiloteE** [comment]
https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host

**Comment by RJDan** [comment]
> can you manually install libc6 or check which version is installed on your OS?
How do I check?

**Comment by RJDan** [comment]
libc6-i386/lunar,now 2.37-0ubuntu2 amd64 [installed,automatic]

**Comment by Siedlerchr** [comment]
Okay, thanks, this sounds indeed like a problem with the jdk then. I will try to prepare a  small reproducer project to test this and see if it occurs there as well

**Comment by Siedlerchr** [comment]
@RJDan  can you please tes thte latest beta version?  
`sudo snap install jabref --beta` 
we upgraded our build system and it should work again

**Comment by RJDan** [comment]
Hello
I used ``` sudo snap refresh jabref --beta```
since I am still actively using jabref.
The installation went fine.
It starts up now and seems to be ok. (I haven't used it yet). 

Here is the output from the terminal.
```
Picked up _JAVA_OPTIONS: -Duser.home=/home/rjd/snap/jabref/2624
Messages are not initialized before accessing key: Display help on command line options
Sep 03, 2023 7:13:53 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
/usr/share/libdrm/amdgpu.ids: No such file or directory

(java:18612): Gtk-WARNING **: 19:13:53.275: GTK+ module /snap/jabref/2624/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 19:13:53.275: Failed to load module "canberra-gtk-module"

(java:18612): Gtk-WARNING **: 19:13:53.276: GTK+ module /snap/jabref/2624/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 19:13:53.276: Failed to load module "canberra-gtk-module"
2023-09-03 19:13:53 [JavaFX Application Thread] org.jabref.preferences.JabRefPreferences.getFetcherKeysFromKeyring()
WARN: JabRef could not open the key store
2023-09-03 19:13:54 [JavaFX Application Thread] org.jabref.gui.StateManager.setActiveDatabase()
INFO: No open database detected
2023-09-03 19:13:54 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2023-09-03 19:13:54 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=CUSTOM, name='/home/rjd/JabRef/JabRef_themes/customDarkTheme_220128.css'} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
2023-09-03 19:13:54 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.addStylesheetToWatchlist()
INFO: Watching css /home/rjd/JabRef/JabRef_themes/customDarkTheme_220128.css for live updates
```

**Comment by Siedlerchr** [comment]
Great to there! I promoted the version now to the stable  and candiate channel as well

**Comment by ThiloteE** [comment]
Encountered similar error messages on Linux Mint 20.3, which is Ubuntu based, while trying JabRef 5.10's portable version. JabRef 5.9 works correctly.

In Linux Mint's application manager there is a JabRef flatpak. This one is described as version 5.3, but is actually JabRef 5.10 (!), which works fine.

My guess is, for JabRef 5.10 portable to work, that Linux Mint 20.3 would need to be updated to a newer version, which holds and is compatible with a newer version of glibc. Manually updating or installing a newer version of libgc is not advised and may break your operating system or other applications you have installed on your system.

**Comment by vkucera** [comment]
@Siedlerchr , I am experiencing the same problem with the latest deb package `jabref_5.10_amd64.deb` (5.10.60000). Is it supposed to be fixed there or do I have to wait for the next release?

**Comment by ThiloteE** [comment]
@vkucera could you please provide details about your operating system?

**Comment by vkucera** [comment]
> @vkucera could you please provide details about your operating system?

Same as yours: Linux Mint 20.3

**Comment by ThiloteE** [comment]
Can confirm: Linux Mint 21.2 can run JabRef 5.10

**Comment by Siedlerchr** [comment]
@vkucera  JabRef is built using Github's runner which uses Ubuntu 22.04 as base. And it seems like Minut 20.3 is still based on Ubuntu 20.
So either you update your system or you can try to use the flatpak as @ThiloteE tried out

**Comment by vkucera** [comment]
Thanks @Siedlerchr for the explanation. Since Ubuntu 20.04 LTS is supported until May 2025, I expected that a compatible deb package would be available for it.

**Comment by Siedlerchr** [comment]
Well, I think in this case we just weren't aware of this creating potential issues.  I think this must also have been something to do with the jdk 21 because 22.04 was already the base for 5.9

**Comment by nextchar** [comment]
Still facing the issue. WSL2, Ubuntu-22.04 LTS and Docker Desktop 4.26.1 (131620)
