### ISSUE TITLE
Fix spacing in Cleanup dialog

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10081]
**Is your suggestion for improvement related to a problem? Please describe.**
The cleanup dialog looks ugly!

**Describe the solution you'd like**
Add some spacing around (top, bottom, left, right). See other dialogs like manage study definition for an example. 

**Additional context**

![grafik](https://github.com/JabRef/jabref/assets/320228/ecf6307d-8aba-41f9-a292-6f125309514f)

CleanupDialog is the code related starting point 

Refs #https://github.com/JabRef/jabref-issue-melting-pot/issues/237

**Comment by pcabaniss** [comment]
Hi there, im a first-time contributor and would like to try my hand at this. Could you assign it to me please?

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/5)
