### ISSUE TITLE
add SublimeText to external programs

### ISSUE THREAD

**Issue by AdamWysokinski** [JabRef/jabref#10098]
Hi, this has been asked few years ago: could you add editor SublimeText to external programs?

**Comment by Siedlerchr** [comment]
I have never used sublime, but it seem this could be possible:
It offers a command line modus. https://www.sublimetext.com/docs/command_line.html

and I see there is an option to pass commands through the cli
https://docs.sublimetext.io/guide/extensibility/commands.html#from-command-line-cli

Text inserting seems to be the  the **append** command:
https://docs.sublimetext.io/reference/commands.html#commands

It would be very helpful if you could provide us a simple cli command for inserting text, that makes it easier for integration.

Codewise the related code is located here:
https://github.com/JabRef/jabref/tree/34ac6d1b872199adff80e75370deb1d2cd64b8c2/src/main/java/org/jabref/gui/push

**Comment by AdamWysokinski** [comment]
To insert text to an active tab at the cursor point, use the insert command. Using the CLI, this would be:

`subl --command 'insert {"characters": "\\cite{wysokinski_2023}"}'`

Note that the \ has to be escaped. I'm on Linux, subl is by default in the $PATH. On Mac and Window user might have to manually point JabRef to the executable.

**Comment by AdamWysokinski** [comment]
I'm not a Java programmer, but wouldn't this piece of code (`PushToSublimeText.java`) solve the issue:

```
package org.jabref.gui.push;

import org.jabref.gui.DialogService;
import org.jabref.gui.icon.IconTheme;
import org.jabref.gui.icon.JabRefIcon;
import org.jabref.preferences.PreferencesService;

/**
 * Class for pushing entries into SublimeText.
 */
public class PushToTexmaker extends AbstractPushToApplication {

    public static final String NAME = "SublimeText";

    public PushToSublimeText(DialogService dialogService, PreferencesService preferencesService) {
        super(dialogService, preferencesService);
    }

    @Override
    public String getDisplayName() {
        return NAME;
    }

    @Override
    public JabRefIcon getApplicationIcon() {
        return IconTheme.JabRefIcons.APPLICATION_SUBLIMETEXT;
    }

    @Override
    protected String[] getCommandLine(String keyString) {
        return new String[] {commandPath, "--command \'insert {\"characters\": \"\\", getCiteCommand() + "{" + keyString + "}\"\}\'"};

    }
}
```

**Comment by AdamWysokinski** [comment]
I've placed some backslashes incorrectly, I think the returned string should be:

`
return new String[] {commandPath, "--command \'insert {\"characters\": \"\\\\", getCiteCommand() + "{" + keyString + "}\"}\'"};
`
