### ISSUE TITLE
group properties not saving "regular expression/case sensitive" checkbox

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10108]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a new group
2. Give the group a name and select "free search expression"
3. Enter the search expression and enable "regular expression" and "case sensitive" checkbox
4. Click OK button
5. Open the group properties of the created group (in 1.) and see that "regular expression" and "case sensitive" checkbox is DISABLED (it should be enabled). So this checkbox is not saved

![afbeelding](https://github.com/JabRef/jabref/assets/139498085/6117286c-5527-41c3-8b6d-048af1e4740e)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
but does it find the entries without citationkeys? Could it be, only the menu in user interface resets itself once you click the "edit" button and otherwise stores the settings until that point?

**Comment by dino-girl** [comment]
> Confirmed, seems like the value is not stored/read from the prefs

We should test if everything works correctly when it's fixed. Where is the value for  "regular expression/case sensitive" read from then now (since it's not stored)? It seems to work fine but I don't understand how that's possible :)

**Comment by Siedlerchr** [comment]
@dino-girl  Group information is stored in the bib file itself as metadata at the end of the file. If you open the bib file with a text editor you see the group information. The checkboxes value is stored there was well:

```bibtex
@Comment{jabref-meta: grouping:
0 AllEntriesGroup:;
1 SearchGroup:asdfasdf\;0\;asdf\;1\;1\;1\;0x8a8a8aff\;\;asdf\;;
}
```

**Comment by DohaRamadan** [comment]
I want to work on this, 
Can someone please guide me on which files in the codebase are responsible for saving group properties and showing them?

**Comment by calixtus** [comment]
I see, after a quick look is, the setters for the selected prop was missing:
![grafik](https://github.com/JabRef/jabref/assets/50491877/78442fbb-0107-491e-bcee-f9e238cea6ea)

**Comment by calixtus** [comment]
In the GroupDialogView class

**Comment by the-dino-girl** [comment]
@DohaRamadan: I reported this bug, but I just found many more group properties not being saved...

Here are the related bugs:

https://github.com/JabRef/jabref/issues/10248

**Comment by DohaRamadan** [comment]
I will check it out
