### ISSUE TITLE
PDF export embedded bibtex not working

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10101]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.File -> Export All entries
2. embedded bibtex (pdf)
3. No file is saved where you have chosen to save it

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Can confirm with

JabRef 5.10--2023-04-10--e7f55d9
Windows 10 10.0 amd64 
Java 19.0.2 
JavaFX 20+19

**Comment by atdushi** [comment]
Maybe I understand something wrong, but the export should occur into an existing pdf file.

**EmbeddedBibFilePdfExporter.java**

```java
private void embedBibTex(String bibTeX, Path path) throws IOException {
   if (!Files.exists(path) || !FileUtil.isPDFFile(path)) {
      return;
   }
...
```

**Comment by atdushi** [comment]
Transfered some code from https://github.com/JabRef/jabref/pull/10361
