### ISSUE TITLE
question: Dutch translation of JabRef

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10109]
Hi developers!

I'm not a developer myself but I'm translating JabRef to Dutch language, my native language.

I made an account on Crowdin and can see the missing text.

I have some questions on how this works:

- Since I'm not a developer, how can I see the translation in the program? Will there be a new version released when I have completed the translation? I can't compile code :)

- Another question: is there a way to see where in the program the text to translate is located? (in what menu, window, ...)

- Is the only thing I need to do is Save the translation on Crowdin or is there something else needed?

Thanks
Lisa

**Comment by dino-girl** [comment]
At the moment I'm having troubles to find the following text in JabRef (and therefore can't translate it correclty):

- dotless
- shortest unique

If somebody can help, thank you!
Are all English text inside JabRef or could there be some unused text too?

**Comment by Siedlerchr** [comment]
Hi,

Thank you very much for your interest in translating!. 
To see the translation in JabRef, we can enable the sync between github and crowdin, so that the development version contains the translation. We usually do this only before a release to avoid noise with changing strings.

Unfortunately there's no way in crowdin to see where the text is located in jabref. You would need to search the code for the string to find the location. 

For the concrete strings, the first two refer to the journal abbreviation. 
You can also check the German translation in crowdin, that could probably help as well

**Comment by dino-girl** [comment]
Do I have to indicate duplicates here? I found some translation strings that are identical or sometimes ended with a "." and no further difference in the text itself.

**Comment by Siedlerchr** [comment]
Hi,
Can you give an example here? Otherwise you can also add a note in crowdin

**Comment by dino-girl** [comment]
> Hi, Can you give an example here? Otherwise you can also add a note in crowdin

I saw somebody who translated to German already made a note in Crowdin

**Comment by dino-girl** [comment]
I have a question about translating the text:

`Add timestamp to modified entries (field "modificationdate")`

Does `"modificationdate"` need to be translated too or is it some field that JabRef uses only in English?

**Comment by Siedlerchr** [comment]
Hi, the fields like modificationdate don't need to be translated. They are usually from the BibTeX/standard standard or jabref specific. They are always in English

**Comment by thedino-girl** [comment]
Thanks, I apply it in the translation! Watch this thread for more questions :)

**Comment by thedino-girl** [comment]
Does `--import` in the following line have to be translated?

`Same as --import, but will be imported to the opened tab`

**Comment by thedino-girl** [comment]
I found a spelling mistake in the following Dutch translation already existing in 5.9:

`Export selected entries` => `Exporteer geseleteerde records`
There is a 'c' missing and should be  `Exporteer geselecteerde records`

Is it enough to look up the existing translation, change it and save it or are more steps required?

**Comment by Siedlerchr** [comment]
Yes, you can simply edit the existing translation, the next sync with github will then change this as well.

**Comment by thedino-girl** [comment]
> Yes, you can simply edit the existing translation, the next sync with github will then change this as well in JabRef.

Ok! I corrected it!

**Comment by thedino-girl** [comment]
On crowdin I see there is a % of approved words.
Who approves it and do I need to wait for this until the new translation is added in the development version?

**Comment by Siedlerchr** [comment]
I can add you as proofreader, so you can approve it yourself. I think it's
that you can vote or dismiss other translations if there are multiple
people working on it.

Even if not approved, the translation still gets synced once a day.
When merged here on GitHub it will be available in the latest development
version that is built automatically

thedino-girl ***@***.***> schrieb am Mo., 14. Aug. 2023,
04:42:

**Comment by thedino-girl** [comment]
OK. Not needed to add me as proofreader. I use the Dutch translation myself and correct it where needed. 
I'm trying to translate it for 100% :)

**Comment by Siedlerchr** [comment]
I set you as proofreader in crowdin for Dutch, so you can approve the translations as well.

**Comment by thedino-girl** [comment]
> I set you as proofreader in crowdin for Dutch, so you can approve the translations as well.

How do I approve something? I don't find any button for doing this if I select the unapproved filter and click any string...

**Comment by thedino-girl** [comment]
I have some problems:

- How do I approve something? I don't find any button for doing this if I select the unapproved filter and click any string...

- strings with green checkmark are the approved ones, right?
I found completely wrong translated ones but trying to change them is not allowed. I get an error that 'voting is needed since there is already a translated string'

Can you help please?

**Comment by Siedlerchr** [comment]
>  How do I approve something? I don't find any button for doing this if I select the unapproved filter and click any string...

(I have a mac, so the keybinding is different) 
<img width="868" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/5bb7d9e8-d710-466c-96a7-6f7cbc600515">
 

> I found completely wrong translated ones but trying to change them is not allowed. I get an error that 'voting is needed since there is already a translated string'

You should be able to unapprove existing translation on the same button. Please let me know if this works

**Comment by thedino-girl** [comment]
Yes it works!

Is there a search somewhere? I need to find specific translated strings but I need to go manually through everything :(

**Comment by Siedlerchr** [comment]
Yes, in the top left corner oft the sidebar you can search and also filter for untranslated etc  (show hide left panel option at the top right=
<img width="726" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/c951a332-9199-4436-b7cf-695d98a41fc3">

**Comment by thedino-girl** [comment]
What has to be translated in this?

`Use [Edit]/[Track Changes]/[Manage] to resolve them first.`

**Comment by thedino-girl** [comment]
I think this English text to translate

`I cannot insert to the cursors current location.`

Should be

`I cannot insert to the cursor's current location.`

I translate it based on the second text because the first one makes no sense in Dutch

**Comment by thedino-girl** [comment]
I can't translate the remaining text so I stop here.

**Comment by Siedlerchr** [comment]
> What has to be translated in this? The text between [ and ] should stay English?
> 
> `Use [Edit]/[Track Changes]/[Manage] to resolve them first.`

This refers to a menu in Libre office. I would keep it as is. it's Outside of jabref.

Regarding the other things you mention, I will fix the English translation

**Comment by dinosaurgirl** [comment]
> I can't translate the remaining text so I stop here.

Trying final texts to translate before the new release!
Things I don't know for sure I leave in English until I have more experience with jabref.

**Comment by dinosaurgirl** [comment]
Thanks for fixing the texts, I have them translated.

I think something is missing in this

`If the work is a translation, a reprint, or something similar, the publication date of the original edition.`

**Comment by Siedlerchr** [comment]
Thanks for your efforts! I will try to sync the translations later. 

They are used as tooltips for the fields in the entry editor. As help texts to describe the meaning of the fields. 
They are coming from the biblatex manual https://ctan.org/pkg/biblatex
(Section 2)

**Comment by dinosaurgirl** [comment]
Thanks! I'm going for 100% now and then I will check the translation of the previous translator too and approve everything!

Can you give a screenshot where `dotless` and `shortest unique` is ?

**Comment by dinosaurgirl** [comment]
I don't understand what the following means

- Escape ampersands
- Escape dollar sign
- Push applications

**Comment by Siedlerchr** [comment]
>Can you give a screenshot where dotless and shortest unique is ? 
Refers to journal abbreviations in the preferences 
<img width="908" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/6f44402d-a04d-4b3b-a3db-09f36a82d757">


>    Escape ampersands
>    Escape dollar sign
=> If you want to use the bib file with a LaTeX Document,  these characters like % and & and $ are special control characters that need to be masked/escaped (here with a backslash, e.g. \%)

    Push applications
->  JabRef can send ("push") citations to other external programs/editors (Preferences .> External pograms) 

    Unprotect terms
=> Opposite of Protect terms. Protect terms means that you add another pair of curly braces around the term to keep the casing and e.g. to prevent company/corporations authors from being split up:

See the Preview on the right side for the author

Without protection:
<img width="836" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/1f668088-3299-4444-944b-0882d48cd094">

 
Right click menu: 

<img width="708" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/3deb758f-3d3d-4801-8321-710265344325">


With protection:
<img width="804" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/140d8f5b-6541-462d-8412-8c4050eca9b4">

**Comment by Siedlerchr** [comment]
About the other: Citations incoming/outgoing see the screenshot: https://user-images.githubusercontent.com/12078268/253776326-838cac72-23bc-454c-8c86-3a22647cf624.png
It's metadata from a journal

**Comment by dinosaurgirl** [comment]
> About the other: Citations incoming/outgoing see the screenshot: https://user-images.githubusercontent.com/12078268/253776326-838cac72-23bc-454c-8c86-3a22647cf624.png It's metadata from a journal

By "cite" they mean a bibtex citation to a paper?
I still don't understand what an "incoming" versus an "outgoing" cite is...

**Comment by Siedlerchr** [comment]
Sorry, can't help with that Maybe @aqurilla  can shed some light on this (he implemented this)

**Comment by dinosaurgirl** [comment]
Am I allowedto change the previous Dutch translation? Because the word 'terms' is wrongly translated everywhere

**Comment by Siedlerchr** [comment]
Sure, you have the rights for Dutch and are freely allowed to change it!

**Comment by dinosaurgirl** [comment]
It's corrected! I need to go through everything to check all the remaining text.

**Comment by dinosaurgirl** [comment]
Can you tell me where this is?
`Problem combining cite markers`

I don't understand what a 'marker' is for a cite...

**Comment by Siedlerchr** [comment]
It's a thing from the Open/LibreOffice integration. JabRef inserts citations paragraph/text marks in Writer documents ("Textmarke")  and can merge multiple citations with these marks together. If it fails, this error is shown.
In the German translation, they are translated more ore less literally:

`Problem bei der Kombination von Zitiermarkierungen`

**Comment by aqurilla** [comment]
> > About the other: Citations incoming/outgoing see the screenshot: https://user-images.githubusercontent.com/12078268/253776326-838cac72-23bc-454c-8c86-3a22647cf624.png It's metadata from a journal
> 
> By "cite" they mean a bibtex citation to a paper? I still don't understand what an "incoming" versus an "outgoing" cite is...

@dinosaurgirl Yes, here 'citations' are the usual References that we see in articles, books etc. 
'Cites Incoming' are the citations that a work receives from other works, while "Cites Outgoing" are the citations that a work includes within itself to reference other works. I hope that makes it clear!

**Comment by dinosaurgirl** [comment]
> > > About the other: Citations incoming/outgoing see the screenshot: https://user-images.githubusercontent.com/12078268/253776326-838cac72-23bc-454c-8c86-3a22647cf624.png It's metadata from a journal
> > 
> > 
> > By "cite" they mean a bibtex citation to a paper? I still don't understand what an "incoming" versus an "outgoing" cite is...
> 
> @dinosaurgirl Yes, here 'citations' are the usual References that we see in articles, books etc. 'Cites Incoming' are the citations that a work receives from other works, while "Cites Outgoing" are the citations that a work includes within itself to reference other works. I hope that makes it clear!

Maybe add a tooltip in jabref with this explanation?

**Comment by dinosaur-girl** [comment]
One text remaining but still can't find it

`dotless`

Can you please give me the right to (un)approve text? Sorry I deleted all my accounts again when getting angry at the themes ☺️
When 5.10 is released I'm going to check the translation of the previous person!
I'm now at 99% and 99% approved!

**Comment by Siedlerchr** [comment]
> Can you please give me the right to (un)approve text? Sorry I deleted all my accounts again when getting angry at the themes ☺️

I restored your right. I fully understand your frustration, especially when there is not much documentation. We really try to improve such things, but please keep in mind that we are all working on JabRef in our leisure time and that therefore some parts are not documented in detail.
Regarding the translation:

"dotless" is also used in the context of journal abbreviations. They can be abbreviated with dots, e.g. `Phys. Rev. Lett.` or without, e.g. `Phys Rev Lett`   This often depends on the citation style.

**Comment by dinosaur-girl** [comment]
Yes! I understand the developer's point of view too. Documentation is lowest priority.
But I now continue with themes and translation. I just try to find out things myself slowly by trying (for the themes).

But please understand it's extremely hard for people to contribute, unless you're a developer yourself!

**Comment by koppor** [comment]
Dutch translations are in. Thank you for your work @ghost :)
