### ISSUE TITLE
feature request: generate missing citation keys in database

### ISSUE THREAD

**Issue by dino-girl** [JabRef/jabref#10105]
**Is your suggestion for improvement related to a problem? Please describe.**
I'm always frustrated when I need to manually go through my database to find entries without citation keys, in order to generate the citation keys.
When the database is getting big, this takes a lot of time

**Describe the solution you'd like**
I would like to request a feature that loops through a whole database and generates the missing citation keys.
So it would do the same as the generate button for a citation key, for each entry found in the database that has NO citation key.

![afbeelding](https://github.com/JabRef/jabref/assets/139498085/c75e8db0-0e72-4796-87ba-2ce6b648f31f)

**Comment by ThiloteE** [comment]
hello dino-girl, I think there are multiple solutions to what you are looking for

1. The **search feature** allows you to find entry fields without content: https://docs.jabref.org/finding-sorting-and-cleaning-entries/search#searching-for-entries-with-an-empty-or-missing-field So if you enable regex and then type `citationkey != .+` you will find all entries without a citationkey. You then select all those entries and click generate keys.

2. ![image](https://github.com/JabRef/jabref/assets/73715071/c77ca3ac-1c0f-4bc4-a40d-ab20a143a0b8) generates keys for ALL selected entries
3. ![image](https://github.com/JabRef/jabref/assets/73715071/5f1731ae-3d4e-48e9-b2eb-957dabaa3cef) generates keys for ALL selected entries.
4. If you are lazy and do not want to use search over and over again, you could create a group with a free search expression (again, use `citationkey != .+`).

5. If all your entries have a similar citationkey pattern, you can simply go to the group "all entries", select all entries and then click one of the create citationkey buttons. Obviously the one from the entry editor is not sufficient.

**Comment by ThiloteE** [comment]
Closing, as this feature already exists

**Comment by dino-girl** [comment]
Thank you, it works!
But how to understand this line ?
`citationkey != .+`

**Comment by ThiloteE** [comment]
it is explained at https://docs.jabref.org/finding-sorting-and-cleaning-entries/search#searching-for-entries-with-an-empty-or-missing-field

In short:

`!` means "not"
`=` means "is"
`.` means "any character"
`+` means "(the previous character) one or more times"

**Comment by dino-girl** [comment]
Does a vertical line in front of an entry mean there is no citation key? (see last book here)

![afbeelding](https://github.com/JabRef/jabref/assets/139498085/c80a8880-e48a-4f8a-97a6-88d9e51328be)

**Comment by ThiloteE** [comment]
No, that's the colour of the group that holds the entry

**Comment by dino-girl** [comment]
Ok yes :)
My group was exactly the ones with an empty citation key.

Could you please look in JabRef: if I change a group color, the new color is not applied to this vertical line!
So I need to open the library again to see the changes...
A bug or is this how it should work?
