### ISSUE TITLE
HTML table export: choose fields

### ISSUE THREAD

**Issue by dino-girl** [JabRef/jabref#10103]
**Is your suggestion for improvement related to a problem? Please describe.**
We can export a bib database to HTML table, but the field "Journal/Proceedings" is always there.
For books this field doesn't make sense and is empty.

**Describe the solution you'd like**
I would like an option so we can choose what fields to export in the HTML table.

**Comment by Siedlerchr** [comment]
This is already possible, however this needs 
https://github.com/JabRef/jabref/tree/main/src/main/resources/resource/layout

Copy the layout files of the layout you want, e.g. `tablerefs` (simple html table)  to a new folder
Then you can freely modify the layout files.
You can also add files per entry type e..g `tablerefs.inbook.layout` 

See https://docs.jabref.org/collaborative-work/export/customexports for more information 

There is also a third-party tool which can assist in creation: 
https://github.com/teertinker/Export-Filter-Editor

**Comment by dino-girl** [comment]
Thanks for the explanation!
