### ISSUE TITLE
On close button press JabRef window is minimised to the dock

### ISSUE THREAD

**Issue by grzesiu** [JabRef/jabref#1011]
* JabRef version: 3.2
* Operating system and version: OS X El Capitan 10.11.3
* Steps to reproduce:
  1. Open JabRef
  2. Press the close button in the upper left corner of the window

It is not critical, but I dislike this behaviour as the minimise button is for this.

**Comment by stefan-kolb** [comment]
@chochreiner I thought we fixed this behavior? See #710

**Comment by chochreiner** [comment]
yes this is fixed for the next release
