### ISSUE TITLE
Non-responsive for importing by some ISBNs

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10126]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Try to create some entries by ISBN, e.g. 978-0-356-51058-3 or 978-0-316-44093-6
2. JabRef is no longer responsive, no errors are logged

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Probably side-effect of https://github.com/JabRef/jabref/issues/9979
The latest development version fixes the freeze, but ISBN import still fails, because the ebook.de API has been removed/turned off.

Closing this, because we now have multiple issues popping up refering to the same problem.

**Comment by ThiloteE** [comment]
(If you can still reproduce in the newest development version, feel free to open)
