### ISSUE TITLE
Add one or multiple new ISBN fetchers

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#10125]
**Problem:**

As of 2023-07 our old ISBN fetcher from ebooks.de is non-operational, because ebook.de has closed down their API. (See https://github.com/JabRef/jabref/issues/9979)

**Solution/Workaround:**

Explore alternative fetchers. For example:

- [ ] https://pypi.org/project/isbnlib/
- [x] https://openlibrary.org/dev/docs/api/books

Alternative fetchers, for which users would require an API key (One would have to pay for the API key or "somehow" aquire one):

- [ ] https://github.com/JabRef/jabref/issues/1065

**Comment by dino-girl** [comment]
I'm not a developer but know JabRef uses Java and I found this database (which I think is free):

https://isbndb.com/apidocs/v2

Please don't use paid keys! This will make JabRef loose its strength because some features will be not free anymore.

**Comment by tobiasdiez** [comment]
https://www.wikidata.org/wiki/Wikidata:Book_sources might be helpful as overview.

**Comment by Siedlerchr** [comment]
https://kvk.bibliothek.kit.edu/?kataloge=K10PLUS&kataloge=BVB&kataloge=NRW&kataloge=HEBIS&kataloge=HEBIS_RETRO&kataloge=KOBV_SOLR&kataloge=DDB&kataloge=STABI_BERLIN&kataloge=TIB&kataloge=OEVK_GBV&kataloge=VD16&kataloge=VD17&kataloge=VD18&kataloge=VOE&kataloge=ZDB&kataloge=LANDBIB_WLB&kataloge=LANDBIB_BAYERN&kataloge=LANDBIB_BERLIN&kataloge=LANDBIB_BRANDENBURG&kataloge=LANDBIB_HAMBURG&kataloge=LANDBIB_HESSEN&kataloge=LANDBIB_LBMV&kataloge=LANDBIB_NDS&kataloge=LANDBIB_NRW&kataloge=LANDBIB_RLB&kataloge=LANDBIB_SAARLAND&kataloge=LANDBIB_SACHSEN_ANHALT&kataloge=LANDBIB_SACHSEN&kataloge=LANDBIB_SHLB&kataloge=LANDBIB_THUERINGEN&kataloge=VTHK_ADV_E&kataloge=VTHK_AHS_NEUD&kataloge=VTHK_ARCHIV_N&kataloge=VTHK_BIB_EKHN&kataloge=VTHK_BIB_WUERTT&kataloge=VTHK_BIR_MOD&kataloge=VTHK_BIR_S&kataloge=VTHK_BMZ_HH&kataloge=VTHK_CAR_FR&kataloge=VTHK_COME_VERB&kataloge=VTHK_DIA_S&kataloge=VTHK_DIO_A&kataloge=VTHK_DIO_AC&kataloge=VTHK_DIO_BA&kataloge=VTHK_DIO_LM&kataloge=VTHK_DIO_M&kataloge=VTHK_DIO_MS&kataloge=VTHK_DIO_ROTT&kataloge=VTHK_EAB_PB&kataloge=VTHK_EDD_K&kataloge=VTHK_EFH_BO&kataloge=VTHK_EFH_FR&kataloge=VTHK_EFH_H&kataloge=VTHK_EFH_N&kataloge=VTHK_EFH_RT&kataloge=VTHK_EHB_VERB&kataloge=VTHK_EKD_H&kataloge=VTHK_EKI_DO&kataloge=VTHK_ERZ_FR&kataloge=VTHK_EZA_B&kataloge=VTHK_FTA_GI&kataloge=VTHK_IHL_LIEBENZELL&kataloge=VTHK_ITHF_HH&kataloge=VTHK_JAL_EMD&kataloge=VTHK_JAMI_PB&kataloge=VTHK_KFH_K&kataloge=VTHK_KHB_BI&kataloge=VTHK_KHS_B&kataloge=VTHK_KHS_W&kataloge=VTHK_KIRCHENKAMPF&kataloge=VTHK_KIVK&kataloge=VTHK_KTU_LINZ&kataloge=VTHK_LKA_BI&kataloge=VTHK_LKA_DD&kataloge=VTHK_LKA_H&kataloge=VTHK_LKA_M&kataloge=VTHK_LKI_HB&kataloge=VTHK_LKI_KA&kataloge=VTHK_LKI_KS&kataloge=VTHK_MARTINUS_MZ&kataloge=VTHK_MIKA_AC&kataloge=VTHK_OKR_S&kataloge=VTHK_OKR_SN&kataloge=VTHK_PRE_HOG&kataloge=VTHK_PRI_FD&kataloge=VTHK_PRI_IBRIX&kataloge=VTHK_PRI_TR&kataloge=VTHK_PTH_VALL&kataloge=VTHK_RPA_HB&kataloge=VTHK_THE_DT&kataloge=VTHK_UNIT_HERRNHUT&kataloge=VTHK_ZARCH_SP&kataloge=BIBOPAC&kataloge=LBOE&kataloge=OENB&kataloge=STEIERMARK&kataloge=SWISSCOVERY&kataloge=HELVETICAT&kataloge=GRAUBUENDEN&kataloge=CHZK_VAUD&kataloge=CHZK_SBT&kataloge=RERO&kataloge=NLAU&kataloge=VERBUND_BELGIEN&kataloge=DAENEMARK_REX&kataloge=EROMM&kataloge=ESTER&kataloge=NB_FINNLAND&kataloge=FINNLAND_VERBUND&kataloge=BNF_PARIS&kataloge=ABES&kataloge=COPAC&kataloge=BL&kataloge=NB_ISRAEL&kataloge=VERBUND_ISRAEL&kataloge=EDIT16&kataloge=ITALIEN_VERBUND&kataloge=ITALIEN_SERIALS&kataloge=NLS_CANADA&kataloge=VOILA_WORLDCAT&kataloge=LETTLAND_VERBUND&kataloge=LUXEMBURG&kataloge=NB_NIEDERLANDE&kataloge=BIBSYS_NORWAY&kataloge=NORWAY_BOOKSEARCH&kataloge=NB_POLEN&kataloge=VERBUND_POLEN&kataloge=PORTUGAL&kataloge=STAATSBIB_RUSSLAND&kataloge=VERBUND_SCHWEDEN&kataloge=BNE&kataloge=REBIUN&kataloge=NB_TSCHECHIEN&kataloge=VERBUND_TSCHECHIEN&kataloge=NB_UNGARN&kataloge=NLM&kataloge=WORLDCAT&kataloge=ABEBOOKS&kataloge=AMAZON_DE&kataloge=AMAZON_US&kataloge=ANTIQUARIAT&kataloge=BOOKLOOKER&kataloge=KNO&kataloge=ZVAB&kataloge=BASE&kataloge=DART_EUROPE&kataloge=DIGIBIB&kataloge=DFG_EBOOKS&kataloge=DFG_AUFSAETZE&kataloge=DOABOOKS&kataloge=DOAJ&kataloge=EROMM_WEBSEARCH&kataloge=EUROPEANA&kataloge=GOOGLE_BOOKS&kataloge=KUNST_HATHI&kataloge=ARCHIVE_ORG&kataloge=OAPEN&kataloge=ZVDD&kataloge=BHL&digitalOnly=0&embedFulltitle=0&newTab=0


Seems also a good idea

Tobias Diez ***@***.***> schrieb am So., 30. Juli 2023, 12:45:

**Comment by Siedlerchr** [comment]
Open library is already the default fetcher

**Comment by koppor** [comment]
Current discussion:

- There is https://lead.to/amazon/com/?op=bt
- https://www.xarg.org/tools/isbn-to-bibtex/
- https://zbib.org/

**Comment by Siedlerchr** [comment]
LOV gov https://lccn.loc.gov/2009019559/mods

**Comment by tobiasdiez** [comment]
Do we know where these services get their data from? Lead.to uses Amazon's API, zbib forwards to library of congress or worldcat (and a few other services). In either case, it would seem wise to cut the middle man and directly query these db's (or setup a small proxy at jabref.org if they need a central api key). In this way, we stay in control of the exact bibtex code generated and don't rely on fixes from third parties.

**Comment by calixtus** [comment]
Should be fixed by #10211
