### ISSUE TITLE
feature request: Markdown [@key] cite command

### ISSUE THREAD

**Issue by AdamWysokinski** [JabRef/jabref#10133]
I use Pandoc for processing Markdown manuscripts to ODT format. Markdown cite command is `[@key]` instead of LaTeX `\cite{key}`. In case of multiple citations this is `[@key1; @key2]`. Currently the preference for cite command does not include the `{` and `}` characters, making it impossible to change it to another cite command that does not use curly brackets. Also, the separating character (`,`) cannot be modified.

It would be great if this was more configurable:
1. cite command
2. surrounding characters
3. separating character

**Comment by Brandon-Lu737** [comment]
Hi Adam,

Do you mind providing a quick Minimum Working Example please?

Thank you!

**Comment by AdamWysokinski** [comment]
Hi Branon,
Here's one:
1. Go to menu: File -> Preferences
2. In the JabRef preferences window select "External programs" tab
3. There is "Cite command" preference with default value `\cite`

When you push citation(s) to an external application (e.g. Emacs/Vim/Sublime Text) it is being send as:
`\cite{wysokinski_2023}` if a single entry is selected or `\cite{wysokinski_2023,wysokinski_2022}` if two or more entries are selected.

The `{`, `}`, `,` characters that are used in the exported citation are hard-coded in the program and cannot be modified in Preferences.
For Markdown/Pandoc compatible citation the entries should be: `[@wysokinski_2023]` and `[@wysokinski_2023; @wysokinski_2022]`, respectively. The `\cite` is not used at all, curly brackets are replaced with `[` and `]` and the separating characters are `; `. All these parameters should be available in "Cite command" preferences to be modified by a user.

Hope this helps.
Adam

**Comment by HoussemNasri** [comment]
Sure

**Comment by ThiloteE** [comment]
@HoussemNasri, when you assign somebody, please also set the corresponding status for the project pages. Unless there is a pull-request, the status is "reserved".

**Comment by Siedlerchr** [comment]
@Brandon-Lu737  What is the status here? Are you still working on this?

**Comment by AdamWysokinski** [comment]
Could someone tell me why it is not present in the most recent 5.11 release?
