### ISSUE TITLE
Web search enters "Journal" field, which JabRef doesn't use

### ISSUE THREAD

**Issue by Bananach** [JabRef/jabref#1015]
* JabRef version: 3.3dev
* Operating system and version: Win7
* Steps to reproduce:
  1. Enter any article title in "Web Search->Google Scholar" (e.g. "Alexanderian mean-variance risk-averse optimal control"
  2. Import
  3. Try to edit typos in journal title: not possible because journal is stored in field "journal", which JabRef does not display

**Comment by oscargus** [comment]
Oh, I think this relates to the fact that a BibTeX-entry is generated upon search but you have a BibLatex database... 

To solve it for now (assuming that you want to have a BibLatex database) is to run a cleanup and tick the "Convert to Biblatex format". If you prefer BibTeX, select File -> Switch to BibTeX mode.

**Comment by Bananach** [comment]
do want biblatex. suggestion does work.

**Comment by stefan-kolb** [comment]
The next JabRef release will display all fields that are not required or optional in a new tab "other fields". In this way all fields will be editable (See #454).

Discussion on the root problem will continue in #1018.
