### ISSUE TITLE
Radio buttons shouldn't allow multi-selection

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#10161]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 100.0.0 Linux 5.14.21-150400.24.69-default amd64  Java 20.0.2  JavaFX 20+19

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to `File > Preferences > Autocompletion`
2. Try to select multiple Name format or First name options
3. That shouldn't be possible; if you select a new option the old one should get deselected automatically

### Appendix

*Originally posted in https://github.com/JabRef/jabref/issues/9952#issuecomment-1676387610*

![image](https://github.com/JabRef/jabref/assets/21198231/24bfcdca-cc1d-4ddb-af25-51f54b93b7f8)

**Comment by calixtus** [comment]
That really shouldn't happen. Looks like something went wrong with the togglegroup.

**Comment by calixtus** [comment]
too easy. Lucas should to some real work. This was just a quick distraction.

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/4)
