### ISSUE TITLE
Search with GVK / ISBN does not work properly

### ISSUE THREAD

**Issue by ds-sic** [JabRef/jabref#10160]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. the search via GVK and also via ISBN for a new book entry works only partially. -> In GVK only items are found that have been published until 2019.
2. Searched for example "Schadt digitalisierung" (2022/2023) or "Technologische Souveränität" (2023). Both are available at https://gso.gbv.de/ 
Searching for "Digitalisierung" alone yields only 50 results. According to this, there is a limit of 50 somewhere. Searching for "Digitalisierung 2023" only brings up 6 results for me. Could the internally set limit be the reason?
3. I have installed the current version 5.9 on Windows. However, I get the same result under Debian. Since the installation is fresh on Debian and no configurations have been made there, this seems to be a bug. The problem is with the latest development version 5.10. just checked and there the same result as described above.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
@ds-sic  Hi, yes the limit of 50 is set hard in JabRef. As we rely on the goodwill of the publisher/catalogs, we have limited the results. However, the GVK Fetcher also allows searching for year https://docs.jabref.org/collect/import-using-online-bibliographic-database#search-syntax

It might  be possible to implement pagination, so we don't have to fetch all the results in advance. But I am not that deep into the search options of the SRU interface.

**Comment by ds-sic** [comment]
@Siedlerchr Hej, thanks for the information, the limit is fine. And thanks for the fix. With Version 5.10 the GVP search is running again :-)
