### ISSUE TITLE
export preferences: use current table sort order not working

### ISSUE THREAD

**Issue by thedino-girl** [JabRef/jabref#10170]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to preferences -> import and export
2. Choose "use current table sort order"
3. Sort the attached bib file ascending on Title
4. Export a HTML table (included too)
5. See that the exported HTML table is not sorted according to the current table sort order (ascending on Title)

(no matter what table sort order you choose in JabRef, the exported HTML table never changes and never uses the current table sort order!)

[export.zip](https://github.com/JabRef/jabref/files/12337631/export.zip)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Using the latest development version from https://builds.jabref.org/main/   it looks fine for me:

(See the black triangle for ascending)   
![grafik](https://github.com/JabRef/jabref/assets/320228/cdb618a4-9c8c-43be-bb94-87ad8d5acb95)


<img width="1102" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/07be4c93-927f-4457-82b0-6535fd671519">

(Remove the .txt extension, github does not allow html extension)

[dinosAZ.html.txt](https://github.com/JabRef/jabref/files/12338023/dinosAZ.html.txt)

**Comment by koppor** [comment]
I tried on Windows on latest `main`. Works for me.

We will focus on getting v5.10 down the ramp!

**Comment by thedino-girl** [comment]
Yes, it's only a bug in 5.9
I close this!

**Comment by Siedlerchr** [comment]
You can always look into our changelog under the unreleased section to see all the bugs and issue we fixed since the latest release https://github.com/JabRef/jabref/blob/main/CHANGELOG.md
