### ISSUE TITLE
BibTeX vs BibLaTeX mode

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1017]
Currently, JabRef tries to guess the mode when opening files. I'm not sure about the logics behind it, but I notice that it often guess for BibLatex but I always use BibTeX.
1. This can probably be improved. I think that journal vs. journaltitle is probably the best single discriminant (and also something causing issues when trying to edit in the wrong format).
2. Wouldn't it be possible that the Default bibliography mode is used to guess? Unless it is really clear, go for the default (this doesn't seem to be the case now).

**Comment by stefan-kolb** [comment]
You can set the default mode in `Preferences - General tab`. If you use any entry types that are only available inBiblatex it might guess Biblatex tho. You need to change the type manually then.

**Comment by stefan-kolb** [comment]
From `BibDatabaseContex`:
```
            BibDatabaseMode inferredMode = BibDatabaseModeDetection.inferMode(database);
            if ((defaults.mode == BibDatabaseMode.BIBLATEX) || (inferredMode == BibDatabaseMode.BIBLATEX)) {
                return BibDatabaseMode.BIBLATEX;
            } else {
                return BibDatabaseMode.BIBTEX;
            }
```

**Comment by oscargus** [comment]
Ahh, OK! As an avid IEEEtran user, there are quite a few non-standard-BibTeX entries in my BibTeX-files... I think it would make sense to have a setting to determine if the IEEE-types should be included in the detection. Of course it is only a one time switch, but I think it may help quite a few users.

**Comment by stefan-kolb** [comment]
As `Biblatex` is a superset of `BibTeX` we choose Biblatex if it is the default or inferred. Otherwise, we choose BibTeX. For me this logic is fine. Suggestions?

**Comment by stefan-kolb** [comment]
`IEEE`types should be ignored by this decision. Only specific Biblatex types force a Biblatex setting?!

**Comment by oscargus** [comment]
The problem is that there is an overlap between IEEE types and Biblatex. Electronic, Patent, and Periodical. Where the two first ones are those causing my decisions to go wrong. (There's no Standard in Biblatex by the way, strange.)

**Comment by stefan-kolb** [comment]
Hm, I don't know a better (and as simple algorithm) for now. We already kicked the field-based detection because of such problems.

**Comment by stefan-kolb** [comment]
Hm, so what do you suggest?
I see the problem, but I think getting rid of the detection and solely basing the decision on the default setting gives away a lot of flexibility, if users are using both modes.
The question is, how often is this the case.
Another option would be to remove those three IEEE types from the algorithm which also seems like a hack to me...

@JabRef/developers What do you guys think?

**Comment by oscargus** [comment]
Regarding how often it is the case, I would say almost every time (for me). :-)

I see a few possible solutions:
* Show a small dialog every time a file without the type defined and ask the user to confirm of change the guess (including a "do not show this again" checkbox)
* Exclude the three types
* Exclude the three types when BibTeX is the preferred format (therefore making it slightly more likely to end up with BibTeX since that is what the user probably wants)
* Exclude the three types based on a preference setting

**Comment by tobiasdiez** [comment]
I would leave the algorithm as it is currently. In my opinion supporting BibLatex is more important then IEEE (no pun intended against IEEE users :smiley: ). 

Showing a dialog asking for confirmation is also disturbing in most cases. Moreover, it is really easy to switch the mode, so a wrongly-inferred mode is fixed easily.

**Comment by koppor** [comment]
BTW, there is [biblatex-ieee](https://github.com/josephwright/biblatex-ieee) :sunflower:

**Comment by stefan-kolb** [comment]
Ok, we decided to keep the logic as is for now. If there are more requests from user  that have problems with the current detection, we will reevaluate the decision!
