### ISSUE TITLE
feature request: translate 

### ISSUE THREAD

**Issue by thedino-girl** [JabRef/jabref#10173]
With google translate you can translate pdf files and the result is the same pdf with identical layout and almost perfect translation.

https://translate.google.com/?hl=nl&sl=auto&tl=en&op=docs

Would it be possible to add translation in jabref by using google translate so the translated pdf can be stored too?

**Comment by Siedlerchr** [comment]
You would need to do this manually as accessing the Google Translate API costs money. But you can also attach multiple documents to an entry.
PS. Thanks again for your ongoing translation work! 👍
