### ISSUE TITLE
Export of Preferences: User generated Export filter are duplicated

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#10176]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Win 10

### Checked with the latest development build

- [ ] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Have manually added export filters
2. Export Jabref Preferences
3. They get duplicated after export.

https://github.com/JabRef/jabref/assets/8830305/7990d439-801b-4b42-9054-31fa8cd2e042

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Can still reproduce this in the latest dev.

**Comment by papatekken** [comment]
Hi I am new to  open-source contribution, and looking for some good-first-issues.

May I try on this one? Thanks

**Comment by ThiloteE** [comment]
I am not sure if this is a good first issue. You can try to solve it, but if you feel like this is too hard for you or you are stuck, you probably should choose from our projects page "good first issues" instead: https://github.com/orgs/JabRef/projects/5

**Comment by papatekken** [comment]
Sure thanks, I noticed that not only "Custom Export Formats", but "External file types" is also repeated.

**Comment by Siedlerchr** [comment]
@calixtus  Any idea what this might be?

**Comment by papatekken** [comment]
I just check the code, after preferences export, function PreferenceDialogViewModel.setValues() was called, which duplicated the items of the TableView. I think the setValues() shouldn't be called because no value changes in preferences. But I will investigate the code more deeply later.

**Comment by calixtus** [comment]
setValues should initialize/reset the Viewmodel when opening the app or to ensure that the right values are used. Simply clearing the representing list before inserting the values in setValues should fix that problem.

**Comment by papatekken** [comment]
yes but for preferences export function it wont impact the Viewmodel, so I suggest not to call setValues for that.
Please correct me if my understanding is incorrect.

**Comment by papatekken** [comment]
for import preferences and reset preferences, same problem happened too. For these 2 cases I will follow @calixtus suggestion and clear the list before inserting the values again.

**Comment by calixtus** [comment]
setValues is called to ensure that the viewmodel is in sync with the backing preferencesService. So even it is not needed to call after export prefs, it should always work as expected! So please always call the clear function for the lists in the setValues method.
