### ISSUE TITLE
saving destroyed library: error when using a PDF file name with opening "{" or closing "}" ONLY inside file name

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10182]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new library
2. Create test PDF file with opening "{" or closing "}" ONLY inside file name
3. Add new library entry
4. Assign this PDF file to the "file" field of the entry
5. Save the library
6. Error occurs:

Opening `{` error:

![afbeelding](https://github.com/JabRef/jabref/assets/141878924/3932fa24-ad43-4236-b9ce-67281c38c2ac)

Closing `}` error:

![afbeelding](https://github.com/JabRef/jabref/assets/141878924/45fbbd6a-0c88-4cb3-a4b5-24aa30afebdb)

When you try to open the library file (after closing JabRef), the library file is destroyed somewhere and can't be opened anymore!!!

The following errors occur when opening the library file again

![afbeelding](https://github.com/JabRef/jabref/assets/141878924/5d7398a3-ce85-4378-8ea9-0e27ff2d6f5e)

![afbeelding](https://github.com/JabRef/jabref/assets/141878924/29a98a57-f11b-4a7f-a57b-fdf74d6ff4d5)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Uh yeah, that should not be allowed in the file field. Braces are bibtex' separators for the field values.
You can try to open it with a text editor (e.g. Notepad) and manually remove the offending braces, then it should be able to open again

**Comment by thedino-girl** [comment]
Should jabref give message box maybe if you use not allowed characters on the file?

**Comment by Siedlerchr** [comment]
[log.txt](https://github.com/JabRef/jabref/files/12371416/log.txt)
Bakup files is still present https://docs.jabref.org/advanced/autosave#where-can-i-find-the-backup-files

**Comment by Siedlerchr** [comment]
Solution would be to check the filename on adding and trying to rename it to allowed characters

**Comment by dinosaurgirl** [comment]
> Solution would be to check the filename on adding and trying to rename it to allowed characters

Yes! This is why I reported it. It **destroys** your library. It happened here by accident when inserting a "{".
I have restored using my backup
