### ISSUE TITLE
Make Show Preferences Window searchable

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1019]
It would be nice to have an incremental search field for searching through the Prerferences in the "Show Prefences" window

**Comment by koppor** [comment]
Refs #113, #268.

Think, we should really wait for the JavaFX port.

**Comment by stefan-kolb** [comment]
It's a nice idea however I'd rather have it in the preferences window itself than in the `Show preferences` view. Like in Intelij or Eclipse to find configuration options easier without knowing in which subsection to look for.

I'd close this issue though for know as this should be done when refstructuring the preferences tab #382.

**Comment by WtfJoke** [comment]
Is this still up for grabs? I would give it a try. 
Never contributed to your project, though. If I cant make it, I'll write here again.

**Comment by Siedlerchr** [comment]
Yes, this is still open. It would be really nice to have it integrated in the preferences window as a tab and to have it searchable

**Comment by koppor** [comment]
Good opportunity to learn and apply JavaFX. We welcome your contribution!
Happy #hacktoberfest!

Manuel <notifications@github.com> schrieb am Mi., 17. Okt. 2018, 10:50:

**Comment by tobiasdiez** [comment]
You might have a look at how the search is implemented in https://github.com/dlemmermann/PreferencesFX .

**Comment by paulKra** [comment]
Hi, we are two students looking for open source project to participate in and found this issue through the awesome beginners list.
Is this issue still open? Can we start working on it? 

Or is @WtfJoke still working on this?

**Comment by WtfJoke** [comment]
@paulKra I started working on it. Since I am limited on time, I am still in the beginning but still want to do it, hope you guys dont mind :)

**Comment by koppor** [comment]
Could you three join forces? This task is not that small and it would be a
pity if work was stopped in the half... If @paulKra would start working and
creating a WIP pull request, @wtfjoke could step in? Or you could have a
sync call? 😇

Manuel <notifications@github.com> schrieb am Fr., 26. Okt. 2018, 15:55:

**Comment by CaptainDaVinci** [comment]
I would like to work on implementing this, unless it's still being worked on by someone?

**Comment by Siedlerchr** [comment]
There is a PR from someone who started working on it,but not finished.
Maybe you can ask the authors or reuse some commits.
There is also another issue from me which is about the window showing all
preferences and searching in there.
That would be awesome if you could implement it

Yash Kothari <notifications@github.com> schrieb am Fr., 8. März 2019, 20:33:

**Comment by WtfJoke** [comment]
I didnt forget about the issue/pr (see https://github.com/JabRef/jabref/issues/4415) but still havent found time to progress.

 @CaptainDaVinci you can continue on my branch. I invited you to my repo. I did some  basics and the remaining part is about marking the found entries

**Comment by WtfJoke** [comment]
How is this related now to https://github.com/JabRef/jabref/pull/4759?

**Comment by Siedlerchr** [comment]
The show all preferences window (the table view). is now searchable . The preferences window itself not yet.

**Comment by tobiasdiez** [comment]
Thanks to @WtfJoke and @CaptainDaVinci this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by WtfJoke** [comment]
I took the latest master (JabRef-5.0-dev--snapshot--2019-03-28--master--a73167933.jar) and search looks fine for me.

I have however one note: 
If I search a term, which is not in the currently selected settings view (eg. I have opened Advanced View and search for something which is in General View), then the view doesnt switch. 

I think in terms of user experience, it would be great to switch to any (or the first) view, which contains the term, if there any hits.

Not sure if should create a separate issue for that.

**Comment by tobiasdiez** [comment]
@WtfJoke yes please open a new issue for it. It's a useful suggestion.

**Comment by CaptainDaVinci** [comment]
I have implemented the changes suggested by @WtfJoke , is it okay if I push the changes on the same branch where the search was implemented?

**Comment by WtfJoke** [comment]
Nice :) Probably you should create a separate branch for that (since it got already merged)

**Comment by CaptainDaVinci** [comment]
There is also an issue of buttons not being highlighted. 
Also, under _external programs_ tab the buttons _Settings for *_  are inside a grid pane and aren't considered when searching, which I think should also be fixed.
