### ISSUE TITLE
Localisation: wrong value displayed

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#102]
When you translate an entry such as `Marked_all_%0_selected_entries=`, the position of the variable %0 can be altered (depending on the grammar rules of the targeted language).
For example, the %0 may come first, such as:
`Marked_all_%0_selected_entries=%0_entrées_sélectionnées_étiquetées`.
In this case, i.e. **when %0 is placed just after the equal sign, the value displayed is always zero.**
Note: even if it does not make sense, the localization
`Marked_all_%0_selected_entries=entrées_%0_sélectionnées_étiquetées`
displays the proper value.

It is something which should be modified in the java code or in the localization file?

*Tested on current state of branch 2.11_dev*

**Comment by simonharrer** [comment]
Would a space before the %0 in the first case solve the issue?

**Comment by mlep** [comment]
Looking at it more closely, changing %O by %0 does the trick.
Arghh... sorry...

**Comment by stefan-kolb** [comment]
Fixed by 9866c5344f3b51f7bf8494a0d8134972ede2cc0a?
By the way @mlep: You should properly configure your Git and Github email settings (See ? next to your name in the linked commit).

**Comment by mlep** [comment]
Yes, this was the fix.
I have just configured my github email settings. The question marks is not there anymore. Solved?

**Comment by stefan-kolb** [comment]
Great :+1:
