### ISSUE TITLE
number of library items not fully displayed -> show as tooltip

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10208]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I have downloaded 2 databases in BibTeX format: one is an arcade game database (45974 items), the other a game console/computer database (134352)

Please look at screenshot. The number of items in the library is not fully displayed (see at the left). Only 4 digits are displayed, the rest in front of it is gone. Could it be fixed so I see the currect number of items? I know it are A LOT but it's possible to have such a big library :)

![afbeelding](https://github.com/JabRef/jabref/assets/142829350/918e39ed-526d-40fe-aaa1-47008f875dc6)

![afbeelding](https://github.com/JabRef/jabref/assets/142829350/38b20dd4-7a17-4a50-85dd-f6364f376d52)

Attached are the 2 bib files

[games.zip](https://github.com/JabRef/jabref/files/12431909/games.zip)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Fixed in 5.10 dev version
> We resolved an issue that cut off the number of group entries when it exceeded four digits. https://github.com/JabRef/jabref/issues/8797 

https://github.com/JabRef/jabref/blob/main/CHANGELOG.md#added

**Comment by dinosaur-girl** [comment]
Sorry!

**Comment by Siedlerchr** [comment]
I think a tooltip would be a good idea

**Comment by DohaRamadan** [comment]
Hello, I'm new to the open-source contributing community, Is this issue a good one for me to start working on?
Note: I'm still trying to understand the codebase.

**Comment by ThiloteE** [comment]
@DohaRamadan, yes it is. I will assign you to this issue and move it to reserved. Since I have seen you are interested in another issue also, just give a short notice, if you feel like you only want to continue to work on one of them, then I can unassign you and move the issue back to "free to take" in the projects pages.

**Comment by Siedlerchr** [comment]
@DohaRamadan  The code for displaying the number would need to be adjusted to additionally display the count as a tooltip:

https://github.com/JabRef/jabref/blob/908c389bb856f2e5895c81b2de1be1c309d8a407/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L276-L290

**Comment by the-dino-girl** [comment]
Can this also be done for each group?

**Comment by the-dino-girl** [comment]
Thanks a lot for making my feature request!

@DohaRamadan  I think this bug is easy to fix too.

https://github.com/JabRef/jabref/issues/10108

**Comment by DohaRamadan** [comment]
No problem! 
I will check it out

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/3)
