### ISSUE TITLE
feature request: add feature to let user choose NO group color

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10231]
**Is your suggestion for improvement related to a problem? Please describe.**
For a group we can choose no icon, but there is no option to choose no color for the entry list.

**Describe the solution you'd like**
If you make groups and you don't want a colored bar to appear in the entry list, this is currently not possible since we MUST choose a color. If there would be an option to choose no color, then we can only make colors of groups appear in the list we want to see there.

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/41330930-9e80-4618-af98-8a1c1b49dae7)

**Comment by the-dino-girl** [comment]
Or maybe a checkbox in group properties: "do not show color in entry list"

**Comment by u7229988-Rabie** [comment]
Hi, I am a first-time contributor, can I be assigned to this issue? I am a university student whose assignment requires me to contribute to open-source projects.

**Comment by ThiloteE** [comment]
@u7229988-Rabie 

The original author of this issue has deleted their github account and cannot give any feedback about the desired result.
There is also a workaroun: JabRef already chooses a default icon colour upon group creation and you can choose a colour that is similar to the ui theme, if you must.
There are also way more important issues around.
I will close this issue to reduce the amount of open issues.

As a first time contributor, please have a look at [good first issues](https://github.com/orgs/JabRef/projects/5). We collect them at our projects page. Koppor issues count too.

**Comment by koppor** [comment]
> "do not show color in entry list"

This can be achieved to not to show groups in main table

![image](https://github.com/JabRef/jabref/assets/1366654/f63399c1-e500-4ac2-abf0-efdafed6c704)
