### ISSUE TITLE
question: read status

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10232]
Hi

Trying the improve the previous Dutch translation, I found a fundamental error but want confirmation here.

The read status has 2 values:

- read (green)
- skimmed (orange)

Is it correct read means the entry 'has BEEN read completely' or does it mean 'BEING read'?
The previous translation translated it to 'being read' but I think it means 'has been read'

The 'skimmed' is translated wrong completely.

Can I get approve rights again for my account "dinogirl" on crowdin? (sorry I deleted it again)

**Comment by ThiloteE** [comment]
I think it is supposed to be 'has been read' too.

**Comment by Siedlerchr** [comment]
<img width="1239" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/7a57fd7f-a438-41d4-8232-002aeb502e4b">

read and skimmed are the value of the special field "readstatus" in the entry editor and are then used in the UI to mark the entry in the column
<img width="1055" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/3ca7e419-99db-46c0-841d-fb72fc61c5b0">

**Comment by the-dino-girl** [comment]
Yes, but can you confirm "read' means "has BEEN read"?
Because previous Dutch translation has translated it to 'being read' as if the entry is still not finished reading.

**Comment by the-dino-girl** [comment]
> Yes, that is the intention behind, to help you mark which paper you have read completely.

OK!
Fixed the translation.
The "skimmed" was translated as "skimmed" milk :-D

**Comment by Siedlerchr** [comment]
Hah! That is a funny translation ;)
