### ISSUE TITLE
feature request: add more group sorting options

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10249]
**Is your suggestion for improvement related to a problem? Please describe.**
There is only 1 group sorting option present: "sort subgroups A-Z"

**Describe the solution you'd like**
It's usefull to add some more sorting options, like the ones below:

- "sort subgroups Z-A": the reverse sort order of "sort subgroups A-Z"
- "sort subgroups by number of entries (ascending)": sort subgroups in ascending order by number of entries they contain
- "sort subgroups by number of entries (descending)": sort subgroups in descending order by number of entries they contain

**Additional context**

Screenshot where these options could be added:

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/42bdd4dd-a484-4eba-be09-2be927cc9958)

**Comment by Preetish-T** [comment]
Hello, I would love to have a try as I believe I can successfully implement this change. May I please have this issue assigned to me?

**Comment by ThiloteE** [comment]
I can confirm. It is currently not possible to sort from Z-A. Go ahead :-)
If you run into trouble, just comment here and I will unassign you. You can always choose from one of our good first issues.
