### ISSUE TITLE
feature request: add link to themes website

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10243]
I would like to request a small feature: see  screenshot 

![7f4e0e5cb655b165e34b6eb4011b69cafa0ba817](https://github.com/JabRef/jabref/assets/143431619/c4e457eb-94ae-4f7b-8e88-f6b64201f1e9)

Reasons:

- users can easily find the themes website, which they may have not heard of, from within jabref
- it can attract theme contributors

**Comment by Siedlerchr** [comment]
The link should point to themes.jabref.org

**Comment by the-dino-girl** [comment]
> The link should point to themes.jabref.org

Yes I agree!

**Comment by Jaovitosr** [comment]
Hello, I hope you're all doing well! I'm a newcomer, and I think I have the required habilites to solve this issue. Could you please confirm whether this issue has already been assigned to someone? If it hasn't it would be a pleasure to contribute to your project!

**Comment by Siedlerchr** [comment]
@Jaovitosr  I can assign you. It's free to take.

**Comment by Jaovitosr** [comment]
Thank you very much!

**Comment by the-dino-girl** [comment]
There is also the theme preview website but I'm not a programmer so it's impossible for me to make this.
Maybe if you're interested? All the themes and screenshots are on github.

https://github.com/JabRef/themes.jabref.org/issues/10

**Comment by the-dino-girl** [comment]
> Thank you very much!

Please note this is a screenshot of 5.9 and in 5.10 it's located in the first tabpage of jabref preferences.

**Comment by Jaovitosr** [comment]
> There is also the theme preview website but I'm not a programmer so it's impossible for me to make this. Maybe if you're interested? All the themes and screenshots are on github.
> 
> [JabRef/themes.jabref.org#10](https://github.com/JabRef/themes.jabref.org/issues/10)

Ok, I'll check this out! Thanks for the idea!

**Comment by Jaovitosr** [comment]
Hello, I hope you're doing well! I'm currently working on resolving this issue, and have run into a bit of a roadblock. I'm having trouble locating the specific directory where the file I need to modify is located. I've gone through the project structure, but I'm unable to pinpoint the exact location.
It would be greatly appreciated if you could provide some guidance or clarification on the directory structure or the file's location. Your assistance would be invaluable in helping me move forward with this issue. Thank you in advance for your support!

**Comment by the-dino-girl** [comment]
I'm not a developer so I can't help :-(

**Comment by Jaovitosr** [comment]
Hello everyone! I've located the directories I need to modify and have made the necessary changes. However, I'm encountering an issue where every time I click on the button that should open the browser to the 'themes.jabref.org' web page, the application crashes.
I've double-checked my code, and it seems to be correctly launching the web page, but the crash persists. I've also ensured that the URL 'themes.jabref.org' is valid. I'd appreciate any insights or assistance you can provide in troubleshooting this issue. If there are specific logs or error messages you'd like me to share, please let me know, and I'll provide them for further investigation.
Thank you for your help!

**Comment by Siedlerchr** [comment]
Hmm can you please open a pull request with you changes? JabRef desktop classes contains methods for opening links

**Comment by Jaovitosr** [comment]
Hello! I openned a pull request, but this is my first time ever making a contribution... If there are any mistakes in my pull request, I apologize in advance and would appreciate any feedback or guidance to improve.

**Comment by taliashark77** [comment]
Has this issue been completed?

**Comment by ThiloteE** [comment]
@Jaovitosr 

Since you asked for feedback, I would like to mention a nice little feature of github:

To ease organizational workflows it is possible to link the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue, which will close issues automatically, once the pull-request is merged.

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>
