### ISSUE TITLE
supergroup entries count (union/intersection) not updated when changing subgroups

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10247]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a new group, below called the supergroup, and set it to union or intersection
2. Drag-and-drop 1 or more subgroups to the supergroup
3. The entries count of the supergroup is NOT updated at all. If you close and reload the library file, the entries count is correct.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
closing as duplicate. We try not to have too many open issues, as this creates more workload checking if they are already fixed.
