### ISSUE TITLE
group properties (specified keywords) not saving radiobutton choice

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10248]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new group, by specified keywords
2. Choose 1 of the 2 radiobuttons and enter a value in the textbox
3. Click "OK"
4. Go back the to group's properties and see that the radiobutton selected was not saved (the textbox content is saved according to which radiobutton you have chosen)

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/587851d2-51fb-4f83-ac2b-bc5da7a99ef1)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by DohaRamadan** [comment]
I want to work on this.
