### ISSUE TITLE
Import from web search doesn't close dialog or update the database view.

### ISSUE THREAD

**Issue by XaraB** [JabRef/jabref#1024]
* JabRef version (available in the About box): 21/03 snapshot
* Operating system and version: Xubuntu trusty
* Steps to reproduce:
  1. Open Jabref. The simplest way to see the bug is to first make an empty database.
  2. Do a web search (I only tried google, most others don't work) and select the entry once
  3. A new dialog appears with a preview of the entry. Click OK to add it.
  4. Previously, the dialog would disappear, the entry would be added, and it would be possible to see the entry in the database.
      Now, this unchecks the box but doesn't close the dialog, there is no indication that the entry has been added in the database. However, it has actually been added. It cannot be seen from normal filter search or by scrolling in the entries, but the global search shows it, and if you close and re-open the database, it will then appear normally.

* Similar bug regarding the non-closing dialog :
  1. Keep the file open
  2. Edit it externally
  3. The dialog "the file ... has been modified externally!" appears. Click on "Review Changes"
  4. Click OK.
  5. Previously, the dialog would disappear. Now, the dialog stays. If you close it anyway, everything is as it should.

This is a pretty recent bug, but again, I don't know exactly when it was introduced. I liked the way the dialogs used to close themselves once we had given an answer. The new behavior resulted in me adding duplicate entries a few times, because I thought it hadn't added them.

**Comment by stefan-kolb** [comment]
Both described bugs are working as expected for me in the most recent dev version. Dialog is closing and entry is added. Can you please recheck http://builds.jabref.org

**Comment by XaraB** [comment]
Indeed, both are solved with JabRef-3.3dev--snapshot--2016-03-24--master--3d8cc32
(But it is definitely present in JabRef-3.3dev--snapshot--2016-03-21--master--0ff7f05).
Any idea what caused then solved this ?

**Comment by stefan-kolb** [comment]
I cannot tell as i didn't touch any of the related classes. Maybe @oscargus knows as he's doing quite a lot of refactoring. We could `git bisect` the reason but as long as it's fine right now this would be a waste of time I think.

**Comment by oscargus** [comment]
There is nothing that immediately strucks me causing this and looking briefly at the commits I cannot remind me of any bug that might have been fixed related to this.
