### ISSUE TITLE
web search: collection of computer science bibliographies error (network error?) 

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10258]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windws 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to web search
2. Select collection of computer science bibliographies
3. Enter any search term e.g. "dinosaur"
4. The following error occurs

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/9ee74ef6-7397-427b-808c-8c7f49472ff0)

I can't find the website anymore. Is this website offline or removed?

Offline website still being used in:

JabRef 5.10--2023-08-30--c303db5
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Yes, unfortunately the website is no longer online since August.

**Comment by the-dino-girl** [comment]
> Yes, unfortunately the website is no longer online since August.

OK! I think it should be removed then in 5.10

**Comment by koppor** [comment]
See https://en.wikipedia.org/wiki/Collection_of_Computer_Science_Bibliographies for a full history of CCSB.  I personally liked it and therefore also introduced a fetcher. Sad to see it going (mainly because of the rename of University of Karlsruhe to KIT - and a domain shutdown)
