### ISSUE TITLE
web search: GVK error (internal parser error?) 

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10259]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to web search
2. Select GVK 
3. Enter any search term e.g. "dinosaur"
4. The following error occurs

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/70a0111f-9909-4fa1-80df-32f613617c06)

If you go to the website http://sru.gbv.de you can see the message the service is no longer available. So I think GVK can be removed from jabref

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
GVK has been recently migrated in 5.10 to the new URL. Refs https://github.com/JabRef/jabref/pull/10189
Will be part of 5.10. We plan to releaes 5.10 this Friday

**Comment by the-dino-girl** [comment]
> GVK has been recently migrated in 5.10 to the new URL. Refs #10189 Will be part of 5.10. We plan to releaes 5.10 this Friday

Great! I'm going to find more bugs and continue improving Dutch translation!
