### ISSUE TITLE
No option is selected in group properties (specified keywords) 

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#10269]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 100.0.0 Linux 5.14.21-150400.24.69-default amd64  Java 20.0.2  JavaFX 20+19

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add subgroup
2. Collect by  "Specified keywords"
3. None of the generation methods is selected

### Appendix
![image](https://github.com/JabRef/jabref/assets/21198231/819b5c71-1a09-4ff6-9a58-6a3c01a1e55f)

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by DohaRamadan** [comment]
I want to work on this.
