### ISSUE TITLE
preferences: external file types duplicates

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10271]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to preferences
2. Go to external file types
3. I'm using Dutch translation and when using that translation there are duplicate file types (one written in English, one in Dutch). When the language of jabref is set to English, the same duplicate files types (**in Dutch even while English is selected**!) stay in the list

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/06271ba3-dcae-4c52-9cd4-1a4af0e93b34)

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/6312721a-b505-4d00-8208-94ca7b4cd30b)

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/b672a1e1-f29c-4094-a9dc-882918c285bd)

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/f7de3fae-94d1-4285-adcc-69cf95ed5a24)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by the-dino-girl** [comment]
I just saw clicking "reset to default" removes the duplicates.
But I still like to know how they could be inside the list, because I never added any file type there.
Maybe it's a small bug?

**Comment by Siedlerchr** [comment]
Might be related to https://github.com/JabRef/jabref/issues/10176 
But I wonder why it's using the language

**Comment by the-dino-girl** [comment]
> Might be related to #10176 But I wonder why it's using the language

Yes, in either case, when jabref is set to English, it would be impossible to see Dutch translation anywhere.

Update:

1. Clicking  "reset to default" removes the duplicates
2. Switch back to English/Dutch language (depending in what language you were) and the duplicates (in Dutch) are BACK!
3. Clicking  "reset to default" removes the duplicates AGAIN but another language change adds them again ...

**Comment by ThiloteE** [comment]
Low priority, as while this is confusing and not visually pleasing, it does not break any workflow or has any other negative effects.

**Comment by the-dino-girl** [comment]
> Low priority, as while this is confusing and not visually pleasing, i expect, it does not break any workflow or has any other negative effects.

Is it better not to report bugs like this that don't break anything?
Or is it OK to report them too?

**Comment by ThiloteE** [comment]
There is nothing wrong with reporting those. How could we ever have new features or enhancements otherwise? ;-) Some of these isssues could be a "good first issue" for somebody or somebody with the willingness and knowledge how to fix them **might** do it. SInce JabRef is open source, we never know if, or when somebody opens a pull-request. The beauty of open source is that everybody can come and propose a fix :-) Often people have their own particular itch they want scratched, so there are not too many that fix issues for others, but they do exist.

If you look at the issue tracker, you will see that it grows ever larger. Developers simply do not have the time to fix them all.

**Comment by papatekken** [comment]
Currently when the program starts, it loaded list of external file types from saved preferences, and compare with list of default file types in the application. If the name of default file types is not found the file type will added to the preferences file list.

Problem occurs when langauage changes, as the default file type names will be different. (e.g. GIF image vs GIF afbeelding)

Please assign this ticket to me, I can help to comparsion by name into comparsion by file extension(.GIF vs .GIF).
Then problem should can be solved.

**Comment by Siedlerchr** [comment]
thanks for looking into this! @papatekken  That seems a likely explanation

**Comment by papatekken** [comment]
Can I assume external file types list contains unique extension? 

In current codebase, I found that duplicate extensions are allowed.

**Comment by Siedlerchr** [comment]
@papatekken Sorry for the delayed response, yes, external file types should be unique extensions
