### ISSUE TITLE
user interface: small improvement request

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10285]
A column in this window is too small to see the text. Can it be made bigger? (it can't be made bigger with the mouse)

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/9b671913-3b9d-4e89-8e9c-bb86e9178e85)

**Comment by Siedlerchr** [comment]
Thanks we will adjust it. But you should be able to resize the column

the-dino-girl ***@***.***> schrieb am Sa., 2. Sept. 2023,
19:15:

**Comment by the-dino-girl** [comment]
> Thanks we will adjust it. But you should be able to resize the column the-dino-girl ***@***.***> schrieb am Sa., 2. Sept. 2023, 19:15:
It's not working here in this specific window. The size doesn't change. It is working in other parts of jabref.

**Comment by SomasekharSunkari** [comment]
I want to work on this Can you assign this to me ?

**Comment by the-dino-girl** [comment]
> I want to work on this Can you assign this to me ?

I want to tell you I can't enlarge this column with the mouse (Windows 10), but I can do this in the entry table and other places where there is a table. Very strange ... I don't know if this a related bug or what is causing this.
