### ISSUE TITLE
suggestion for more logical behavior on fixed issue

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10289]
Maybe it's better to replace a `{ `and `}` not by a `_` but just remove it from the file name?

https://github.com/JabRef/jabref/issues/10182

It requires you to rename the file yourself unless you want a `_` inside the filename.
So I don't understand the reason why you should put a `_` in place of the remove bracket. You can just remove it and don't put anything in place.

**Comment by Siedlerchr** [comment]
You can always rename it automatically to a defined pattern later. The underscore is a placeholder for all illegal characters.

**Comment by ThiloteE** [comment]
closing, as a placeholder is a good idea I think.
