### ISSUE TITLE
options menu is GONE!!!

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10283]
### JabRef version

Other (please describe below)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

The WHOLE options menu is GONE in 5.10!!!

I use 5.10 but it's not selectable on github here

JabRef 5.10--2023-09-01--779e555
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
Does the File menu appear at your side? Could you check?

![grafik](https://github.com/JabRef/jabref/assets/1366654/4277f87a-97a6-41c2-85ce-8f001537d68d)

**Comment by the-dino-girl** [comment]
Yes, I found preferences there but in "options" were 2 other things.
Are they removed and why?

**Comment by Siedlerchr** [comment]
See https://github.com/JabRef/jabref/pull/9768 
Content selectors turned out to be library specific and was moved to the library properties.

**Comment by the-dino-girl** [comment]
Ok
The docs are not up to date now

https://docs.jabref.org/advanced/contentselector
