### ISSUE TITLE
Autosetting links in infinite loop?

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#103]
This takes ages on my machine. When I cancel it, it still has some valid results set!

**Comment by koppor** [comment]
This seems to be [sf bug #1294](https://sourceforge.net/p/jabref/bugs/1294/)

**Comment by stefan-kolb** [comment]
Maybe @simonharrer can take a look at this.
We also need to backport this to 2.11 branch!

**Comment by simonharrer** [comment]
Steps to reproduce: DoubleClick on BibtexEntry. Go to tab General, click on Auto-Button. ProgressBar will never be closed.
