### ISSUE TITLE
Missing jabrefHost.py on 5.10/5.11 causing the browser extension to fail

### ISSUE THREAD

**Issue by allydunham** [JabRef/jabref#10308]
### JabRef version

5.10 (latest release)

### Operating system

macOS

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Install JabRef 5.10/5.11 on MacOS, either arm64 or intel.
2. jabrefHost.py is missing from JabRef.app/Contents/Resources/
3. Attempting to use the browser extension fails with error File at path "/Users/ad44/Applications/JabRef.app/Contents/Resources/jabrefHost.py" does not exist, or is not executable

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Thanks for the report. We totally missed this.  

The file jabref host.py and  https://github.com/JabRef/jabref/tree/main/buildres/mac/native-messaging-host  
the files need to copied over.
https://github.com/JabRef/jabref/blob/main/buildres/mac/jabrefHost.py

Unfortunately there is no easy fix now as this could break notarization. 
Refs https://github.com/adoptium/adoptium-support/issues/829 
File an issue with the project to the jdk.

**Comment by Siedlerchr** [comment]
Need to test this:

```

`--app-content additional-content[,additional-content...]

    A comma separated list of paths to files and/or directories to add to the application payload.

    This option can be used more than once.

```
https://docs.oracle.com/en/java/javase/20/docs/specs/man/jpackage.html

**Comment by Siedlerchr** [comment]
@allydunham I found a solution for the problem. Can you please test if this version works correctly?
https://builds.jabref.org/addAddContentToImage/  (It's arm64 only) 
You might need to use the pgk as it overwrites the old path files for the browser extension.

**Comment by allydunham** [comment]
I had to use the DMG because of admin permissions, but when I updated the plugin JSON manually this build works. Thanks for sorting it out.

**Comment by anteromontonio** [comment]
> Thanks for the report. We totally missed this.
> 
> The file jabref host.py and https://github.com/JabRef/jabref/tree/main/buildres/mac/native-messaging-host the files need to copied over. https://github.com/JabRef/jabref/blob/main/buildres/mac/jabrefHost.py
> 
> Unfortunately there is no easy fix now as this could break notarization. Refs [adoptium/adoptium-support#829](https://github.com/adoptium/adoptium-support/issues/829) File an issue with the project to the jdk.

Could you please provide instruction where to copy the linked files. So far I put 

bifehkofibaamoeaopjglfkddgkijdlh.json 
in 
/Library/Application\ Support/Google/Chrome/External\ Extensions/

and 

org.jabref.jabref.json in
/Library/Google/Chrome/NativeMessagingHosts/

And the extension is not working

**Comment by Siedlerchr** [comment]
Please use the latest development version  (the pkg) (not yet notarized, so you have to use `xattr -d com.apple.quarantine /Applications/JabRef.app`  afterwards 
We are planning a release shortly.

**Comment by Siedlerchr** [comment]
@anteromontonio  Here is also now a completely notarized version https://builds.jabref.org/buildnotarizedversion/

**Comment by koppor** [comment]
For reference: https://builds.jabref.org/buildnotarizedversion/ is not available any more, but release v5.11 contains the fix.

**Comment by Siedlerchr** [comment]
@MooersLab  Yes, the path has changed. The browser plugin config is updated as well by the installer.

**Comment by MooersLab** [comment]
@Siedlerchr Thank you for the clarification. The Plugin is now working for me! :) This documentation needs updating: https://docs.jabref.org/collect/jabref-browser-extension#installation-and-configuration

**Comment by Siedlerchr** [comment]
Feel free to update the docs
https://github.com/JabRef/user-documentation/blob/main/en/collect/jabref-browser-extension.md

Am Mo., 30. Okt. 2023 um 14:57 Uhr schrieb Blaine Mooers <
***@***.***>:

**Comment by Siedlerchr** [comment]
Have you tried the pkg installer? That should take care of the browser extension files

**Comment by felixschaumann** [comment]
> Have you tried the pkg installer? That should take care of the browser extension files

Yes, I had tried that, but it didn't help in my case. At least not by itself — I think I had fixed the issues for the .pkg version in the same way as I detailed for the .dmg version, but then JabRef always crashed after importing a reference, so I went back to .dmg. Either way, that is working fine now :)
