### ISSUE TITLE
Problem with adding elements to a group (subgroup).

### ISSUE THREAD

**Issue by NeymanDmitry** [JabRef/jabref#10317]
### JabRef version

5.10 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04 (64-bit)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

If you select several entries from the library and then right-click on a group (subgroup) to add these elements to the group, then the selection from the elements disappears and this group opens instead.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by the-dino-girl** [comment]
Yes I can confirm it's impossible to use the right click menu to do this. You can drag-and-drop entries from "all entries" to a subgroup.

If you right click a group (or subgroup) you get this menu:

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/25c70494-f975-4d64-a44f-ff6769c9b6f3)

The "remove selected entries from this group" works but the "add selected entries to this group" should better be placed in the right click menu of the entry table when you have any group selected.
Then you can select entries from the entry table and right click "add selected entries to group" which should show a submenu of all groups you currently have. You can then choose the group you want to add the selected entries too by using the submenu.

Also the "remove selected entries from this group" and "add selected entries to this group" are enabled if there are NO entries selected at all too. So it's very confusing.

So I think both improvements should be made to make this feature user friendly.

**Comment by Siedlerchr** [comment]
>  Then you can select entries from the entry table and right click "add selected entries to group" which should show a submenu of all groups you currently have. You can then choose the group you want to add the selected entries too by using the submenu.

Actually, this was once implemented in JabRef in older versions. After the migration to the new UI framework, we decided to use Drag and Drop instead as the old variant is just duplicating the whole group tree

**Comment by the-dino-girl** [comment]
> > Then you can select entries from the entry table and right click "add selected entries to group" which should show a submenu of all groups you currently have. You can then choose the group you want to add the selected entries too by using the submenu.
> 
> Actually, this was once implemented in JabRef in older versions. After the migration to the new UI framework, we decided to use Drag and Drop instead as the old variant is just duplicating the whole group tree

Maybe then both menu items should be removed completely?
And drag and drop should be used everywhere?

**Comment by NeymanDmitry** [comment]
There is one more problem. If the list of groups and subgroups is too large, which does not fit in the window and you need to use scrolling, then when adding using the drag-and-drop method, the list scrolls spontaneously to the very bottom (after adding). To cancel scrolling, you need to rotate the mouse roller, otherwise everything repeats.

**Comment by the-dino-girl** [comment]
> There is one more problem. If the list of groups and subgroups is too large, which does not fit in the window and you need to use scrolling, then when adding using the drag-and-drop method, the list scrolls spontaneously to the very bottom (after adding). To cancel scrolling, you need to rotate the mouse roller, otherwise everything repeats.

I can confirm this but know no solution (I'm no developer). 😊

**Comment by Siedlerchr** [comment]
Might be relatex to https://github.com/JabRef/jabref/issues/2869
