### ISSUE TITLE
feature request: download linked online files (without using browser extension)

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10327]
Hi

When entering a paper using a DOI for example https://doi.org/10.1126/science.aag1582
which is the URL https://www.science.org/doi/10.1126/science.aag1582
the following window is used:

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/48e7e8d5-7cfe-4bed-82ce-4a98de629ac4)

But when adding this paper using the browser extension, we can choose "download linked online files"

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/9ca8064a-a5dc-4dc6-93b8-8c95caf37c79)

Is it possible to download online files when NOT using the browser extension but adding a paper by DOI in jabreft itself (first window)? So can it be added in the first window?
If yes, I would like to request this as a feature.

An additional question: you can see this paper has Supplementary Information PDF (https://www.science.org/doi/suppl/10.1126/science.aag1582/suppl_file/matsumura-sm.pdf). Can this be downloaded too by using the same DOI ?

**Comment by Siedlerchr** [comment]
The key problem is here: If you search by ID in JabRef for DOI, the metadata does not contain any information about the fulltext pdf. So JabRef cannot download anything. 
For other fetchers, the file will be downloaded if the option in the preferences is set.
