### ISSUE TITLE
entry merge does not produce reliable result

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#10375]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.11--2023-09-12--a1e2283 Linux 6.4.14-200.fc38.x86_64 amd64  Java 21-internal  JavaFX 20+19

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. copy an entry in one library with citekey `abc:2000`
2. paste it into another library, in which a similar entry already exist, `abc`. Otherwise, the entries are the same,
3. select `abc:2000` for the merged entry
4. merge 

as a result, the merged entry is not using  `abc:2000`

### Appendix

...
<details>

<summary>Screencast File</summary>

https://hessenbox-a10.rz.uni-frankfurt.de/getlink/fi67mvr3136gw9SyxtfdQX/

</details>

**Comment by ilippert** [comment]
> Do you have autogenerate citation keys / overwrite keys activated?

yes

**Comment by Siedlerchr** [comment]
I think this is what happens here. After merging, a new key is generated for the entry.  This sounds like the issue here https://github.com/JabRef/jabref/issues/8644
