### ISSUE TITLE
entry merge UI: add option for treating all entries in the same way

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#10372]
**Is your suggestion for improvement related to a problem? Please describe.**
I'm always frustrated when I copy&merge many entries at once. It takes too long (performance issue)

**Describe the solution you'd like**
Say if I want to keep the old entry for all the new entries pasted into the library, I would love to set a check mark that indicates that all the old entries should be kept.

Of course, such a `treat the other entries like this one` check mark should also be useable for other options, like merge, keep left, keep right, etc.

**Comment by jlauber18** [comment]
Hello I'm new to open source contributing, I'd love to work on this issue.
@ilippert can you send me an image of what you want changed for me to understand how the check mark needs to work.

**Comment by ilippert** [comment]
> Hello I'm new to open source contributing, I'd love to work on this issue. @ilippert can you send me an image of what you want changed for me to understand how the check mark needs to work.

Hello, I am not a useful UI designer. I am thinking of a check box on the right hand of the five options. The label might be `recursive`, and a tooltip might tell `apply this decision on all other entries`.

![Screenshot from 2023-09-12 23-57-06](https://github.com/JabRef/jabref/assets/20518297/932f76e3-5ada-4311-a8a1-e026b95e31db)

If you want to make this complicated: only show this if actually several entries are pasted into a library.

**Comment by mengyaoXu2023** [comment]
Hi @ThiloteE , I am new to the project and exploring the project. Since it is a good-first-issue, can i give it a try?

**Comment by Siedlerchr** [comment]
@mengyaoXu2023  Sure. make sure to take a look at https://github.com/JabRef/jabref/pull/10386  That already did a good foundation. From what I remember it was mostly about the UI

**Comment by mengyaoXu2023** [comment]
@ThiloteE I'm trying to solve this problem. Can you assign it to me?

**Comment by mengyaoXu2023** [comment]
Hi! I found an issue. I'm writing a test for importHandler UI but it seems to be incompatible with my chip: Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError:,,,(mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by Siedlerchr** [comment]
Do you have an Intel or m1/m2 + mac? Seems like there's something wrong with your Java setup. Make sure to install the right Java for your architecture

**Comment by mengyaoXu2023** [comment]
I have added some JUnit test for importHandler.java

**Comment by Siedlerchr** [comment]
@ilippert  Happy New Year, we now implemented an option when copying and pasting to remember the duplicate resolving strategy. 
If you copy more than one new entry, you will be asked for the first only (if the option is activated) Can also be disabled in the preferences. The last used decision is remembered 
It would ne nice if you could test this and give some feedback
https://builds.jabref.org/pull/10741/merge

**Comment by ilippert** [comment]
Hi there, happy new year to you and all!

I just tested

```
JabRef 5.13-PullRequest10741.43--2024-01-03--fc8dc47
Linux 6.6.8-200.fc39.x86_64 amd64 
Java 21.0.1 
JavaFX 21+31
```

I generated a new library, pasted the same entries in twice. The second time, for each entry I am asked anew (that is I am presented anew with the merge dialogue UI).

In that sense, so far as I see, the proposed merge does not meet the requested UI change.

**Comment by Siedlerchr** [comment]
Sorry, forget to say: You need to first activate the option here 
![grafik](https://github.com/JabRef/jabref/assets/320228/07b04937-b976-4f57-9e64-a6c7f9e9b74e)
 
 Or in the Preferences

**Comment by ilippert** [comment]
merci.

does not work.

I do see the Options and marked the `Treat all ...`.

However, this does not achieve the desired effect. I am still asked n times for the entries pasted.

**Comment by Siedlerchr** [comment]
Hm, would it be possible to do a screen record or describe the steps? 

My testing was:
1. Select three different entries 
2. Copy and paste them in the same library
3. Click on Keep existing entry for the first one,,
4. Dialog is only shown once for the first entry

**Comment by ilippert** [comment]
Here you go


[Screencast from 2024-01-03 21-16-22.webm](https://github.com/JabRef/jabref/assets/20518297/5927f3d6-01a5-473d-b897-31c6d3827176)

I hope this helps.

**Comment by ilippert** [comment]
Two more details for my request:

- if only one entry is pasted, the `Option` `Treat`... does not need to be shown.
- could the `Options` also be separated by a |?

**Comment by Siedlerchr** [comment]
Okay, thanks I will look into it. If you keep the option "Treat all duplicates" activated and do the same steps again, does it work then?

**Comment by ilippert** [comment]
Hi there, I never deactivated "Treat all duplicates". In the screencast, I simply clicked on the options to show to the viewer that the option is still checked.

**Comment by Siedlerchr** [comment]
I found the problem. The chosen option was not correctly stored. Please try again with the latest version https://builds.jabref.org/pull/10741/merge
