### ISSUE TITLE
Typst-flavored (Hayagriva) YAML export

### ISSUE THREAD

**Issue by Enivex** [JabRef/jabref#10382]
The Typst typesetting system has it's own YAML format, described here:
https://github.com/typst/hayagriva/blob/main/docs/file-format.md
Note that this is _not_ the same as CSL YAML (which Jabref can target already)

It would be useful if Jabref could export to this format.

**Comment by Siedlerchr** [comment]
I think this could be done easily. The existing YAML exporter is based on our custom export layout format.
https://docs.jabref.org/collaborative-work/export/customexports 

Copy the 3 yaml related files to a new folder and modify them and then you can add them as new custom exporter. 
See the above linked documentation
https://github.com/JabRef/jabref/tree/main/src/main/resources/resource/layout

**Comment by JawadTUE** [comment]
Hi, can I be assigned to this issue?

**Comment by Siedlerchr** [comment]
@Enivex  Thanks to @JawadTUE  this feature is now implemented in the latest development version (it will be ready in roughly 30 minutes)  at https://builds.jabref.org/main/
