### ISSUE TITLE
Import bib files from BIbDesk and parse the groups + linked files

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10381]
**Is your suggestion for improvement related to a problem? Please describe.**
I want to switch from BibDesk (a reference manager on macOS which also uses BibTeX as basis) to JabRef and import my library in JabRef.

**Describe the solution you'd like**
I want to have the groups I used in BibDesk to be in JabRef.

Extra: Be able to parse the linked files

**Additional context**

JabRef should be able to parse the metadata and convert it to JabRef groups.

Groups In BibDesk are stored as metadata in the comment field. 
Entries in the group are identified by their citation key.

Extra: Be able to convert the linked files to format:
LInked files are stored in some kind of binary/base64 encoded file path. It's a mac os alias.

Decode the base64 data:

```
bdsk-file-1 = {YnBsaXN0MDDSAQIDBFxyZWxhdGl2ZVBhdGhZYWxpYXNEYXRhXxAbLi4vRG93bmxvYWRzLzIzMDkuMDY5MzIucGRmTxEBUgAAAAABUgACAAAMTWFjaW50b3NoIEhEAAAAAAAAAAAAAAAAAAAA4O/yLkJEAAH/////DjIzMDkuMDY5MzIucGRmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////hKRjCAAAAAAAAAAAAAQACAAAKIGN1AAAAAAAAAAAAAAAAAAlEb3dubG9hZHMAAAIAKy86VXNlcnM6Y2hyaXN0b3BoczpEb3dubG9hZHM6MjMwOS4wNjkzMi5wZGYAAA4AHgAOADIAMwAwADkALgAwADYAOQAzADIALgBwAGQAZgAPABoADABNAGEAYwBpAG4AdABvAHMAaAAgAEgARAASAClVc2Vycy9jaHJpc3RvcGhzL0Rvd25sb2Fkcy8yMzA5LjA2OTMyLnBkZgAAEwABLwAAFQACABH//wAAAAgADQAaACQAQgAAAAAAAAIBAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAGY},
```

with `base64 -D | plutil -p -`
 
That gives 

```
{
  "aliasData" => {length = 338, bytes = 0x00000000 01520002 00000c4d 6163696e ... 00020011 ffff0000 }
  "relativePath" => "../Downloads/2309.06932.pdf"
}
```

Example: 
```bibtex
@comment{BibDesk Static Groups{
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>group name</key>
		<string>testSammlung</string>
		<key>keys</key>
		<string>Kraljic:2023aa,Kovakkuni:2023aa,Pereira-Santaella:2023aa,Cooper:2023aa,Heyl:2023aa,Swain:2023aa</string>
	</dict>
</array>
</plist>
}}
```

Complete File:
[TestbIbDesk.bib.txt](https://github.com/JabRef/jabref/files/12612175/TestbIbDesk.bib.txt)

Implementation hint
Parse the metadata at 
https://github.com/JabRef/jabref/blob/2f5c51216f99e32a7453b169178564b429bdd68e/src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java#L292-L305

**Comment by foice** [comment]
[This](https://github.com/foice/pyXattr) tried to convert the group information of BibDesk into OS X tags over the files (metadata of the file that you see in Finder and search over) as well as try to create an independent database of keywords based on the groups of BibDesk. Maybe it can help with parsing. As far as I know this code was fully able to parse BibDesk groups and even to use the info on the date of last modification of the group (intended as the date at which a paper was added)

**Comment by Siedlerchr** [comment]
Wow, that's great!

**Comment by Frequinzy** [comment]
Hello, we (@Frequinzy @Tian0602 @annamaartensson @LottaJohnsson @filippanilsson) are a group of university students who would like to take an attempt at this issue if possible!
