### ISSUE TITLE
Improve layout of "Cleanup entries" dialog

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1038]
JabRef 3.3dev--snapshot-2016-0-24--master--3d8cc32 on Windows 10.

I have some usability remarks on the new "Cleanup entries" dialog:

- [ ] The position of the button `-`is unclear. When reading it, it removes the thing left of it, because this is the context. But that context doesn't change when selecting something different in the box of selected formatters. Proposal: Move below the box
- [ ] "Description": is always empty at current master
- [ ] The box of selected formatters should have a heading
- [ ] "Run field formatter:" should be "Run configured field formatters:"
- [ ] After removing an entry in the list, the next entry should be selected
- [ ] There should be a context menu for each enetry in the table. It should contain "Remove selected entry" (or similar)

As is dialog:

![grabbed_20160325-131223](https://cloud.githubusercontent.com/assets/1366654/14044196/e8d1e71e-f28d-11e5-94ca-07464a1befad.png)

Should be dialog - only the last part, the upper part is addressed in #959 

We are modifying a table somehow. However, it seems to be difficult to add a complete table editing. At the beginning, I thought about "Add", "Remove", and "Change" as buttons. That seemed to be too complicated. Therefore, I stick with the current way.

Possibly, we should add move-up and move-down buttons.

The text at "Description" should be updated either when an entry in the table is selected or the combo box for formatters is changed.

![grabbed_20160325-161018](https://cloud.githubusercontent.com/assets/1366654/14046815/16b97208-f2a4-11e5-8c1f-0feb2912fb34.png)

(Tool used for UI sketch: [Evolus Pencil](http://pencil.evolus.vn/))

**Comment by Siedlerchr** [comment]
There is also one thing I noticed during the changes in #999  which is not yet resolved.
When one item gets deleted/remoed the selection-focus should move to the next item in the list.
However, there have to be considered a few cases. E.g. 
OnRemoving:
- last item: Selection should go the prev one
- first item : Selection should go to the next one
- only item: No more selection
- "middle" item: Prev or Next one?

**Comment by Siedlerchr** [comment]
I'm onto that.

**Comment by tobiasdiez** [comment]
I would leave the bigger restruction to the javafx rework, so for the moment only fix the description field and maybe that the next item is selected on delete. In the long-term I would prefer a completely inline editing of the formatters without any buttons and no separation between addition and display of existing formatters.

**Comment by Siedlerchr** [comment]
See PR for more details
![cleanupentriesdialog](https://cloud.githubusercontent.com/assets/320228/14066092/668d0f94-f441-11e5-8fe4-3320697f4de2.png)

**Comment by koppor** [comment]
I close this issue as discussion goes on at #1050. I will reopen if something is not fixed. :innocent:
