### ISSUE TITLE
New "Journal Information" functionality does not work for entries where Journaltitle is specified instead of Journal.

### ISSUE THREAD

**Issue by evanhorn** [JabRef/jabref#10397]
### JabRef version

5.10 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a BibLaTeX entry in Entry Editor (make sure that journaltitle is defined but journal is not—see MWE below).
2. Click on _i_ next to Journaltitle field. Message appears stating "ISSN or journal name required for fetching journal information".
4. Switch to "biblatex source" tab.
5. Copy and paste journaltitle field, rename to "journal".
6. Switch to "Required fields", click on _i_ next to Journaltitle field. Popup with journal information opens.

### Appendix

<details>

<summary>MWE BibLaTeX File</summary>

```
@Article{Rayleigh1878,
  author           = {Rayleigh, John William Strutt},
  date             = {1878-07},
  journaltitle     = {Nature},
  title            = {The explanation of certain acoustical phenomena},
  doi              = {10.1038/018319a0},
  number           = {455},
  pages            = {319--321},
  volume           = {18},
  modificationdate = {2023-09-18T13:48:18},
}
```

</details>

**Comment by koppor** [comment]
A fix was made at https://github.com/JabRef/jabref/pull/10398, build should be available in 30 minutes (link will be put as comment in the PR), in the main branch in about 60 minutes at https://builds.jabref.org/main/.
