### ISSUE TITLE
JabRef icon on Ubuntu dock

### ISSUE THREAD

**Issue by Hosein-Rahnama** [JabRef/jabref#10407]
When you add JabRef to favorite apps then its icon appears on the Ubuntu dock. However, when you click on the dock icon to start JabRef, it adds another icon to the dock which is not the desired behavior. It should only show *one* icon with a red dot below it to indicate that an instance of JabRef is running. Generally, there should always exist one icon and the number of red dots below the icon indicates that how many instances of that program are running currently. See the following picture.

![Screenshot from 2023-09-21 20-16-57](https://github.com/JabRef/jabref/assets/88373622/71cbab45-9b6e-437a-b5a6-0701efdda3a5)

**Comment by teertinker** [comment]
Hello,
you have to change the "StartupWMClass" in the Jabref*.desktop file (located at: usr/share/applications/) to:
`StartupWMClass=org.jabref.gui.MainApplication`

see: https://askubuntu.com/questions/1155955/add-java-program-eclipse-jabref-maple-to-favorites/1506830#1506830

**Comment by Hosein-Rahnama** [comment]
> Hello, you have to change the "StartupWMClass" in the Jabref*.desktop file (located at: usr/share/applications/) to: `StartupWMClass=org.jabref.gui.MainApplication`
> 
> see: https://askubuntu.com/questions/1155955/add-java-program-eclipse-jabref-maple-to-favorites/1506830#1506830

I tried as you said but it was not fixed. Could you please write the full name of the file and include its entries completely for future readers?

**Comment by teertinker** [comment]
Hey that's great to hear. I don't know whether this is a thing that can be taken care of during installation. I had the problem several times in the past.

**Comment by Siedlerchr** [comment]
Hi, we provide a desktop file for the JabRef installer, so would it be necesary/should we change it?
 https://github.com/JabRef/jabref/blob/main/buildres/linux/JabRef.desktop

Should then be adjusted for the current dev version to point to https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/JabRefGUI.java

**Comment by Hosein-Rahnama** [comment]
> Hi, we provide a desktop file for the JabRef installer, so would it be necesary/should we change it? https://github.com/JabRef/jabref/blob/main/buildres/linux/JabRef.desktop
> 
> Should then be adjusted for the current dev version to point to https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/JabRefGUI.java

I am not sure, but most probably the issue is with `StartupWMClass=jabref`, which should be changed to `StartupWMClass=org.jabref.gui.MainApplication`.

**Comment by Siedlerchr** [comment]
@Hosein-Rahnama  Have you verified that this StartiupWMClass fixes it?
