### ISSUE TITLE
Problems adding citations to groups in 5.10 via right-click, as we could before

### ISSUE THREAD

**Issue by esteelpaz** [JabRef/jabref#10404]
### JabRef version

5.10 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Jabref 5.10 on Pop_OS 22.04

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.  Add a citation to the selected database.  Leave it highlighted
2. Go to the Groups >sub-group that is appropriate for that citation and right-click on the line item.
3. Menu box to "add selected entries to group" drops down, but that also switches from "All entries" into the "sub-group" and clicking on "add entry" does not add the entry . . . .

4. Haven't had time to mess with the developmental version.  I posted the problem on Discourse and the admin asked me to start this bug report.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

I tried to screenshot the problem but couldn't get the drop down menu to stay while trying to use the app in the laptop.

**Comment by Siedlerchr** [comment]
Thanks for the report, I could reproduce this. It seems like the right click triggers the focus to the group and creates /unselection of the entries. Probably a side effect of a fixed issue related to that

**Comment by esteelpaz** [comment]
@Siedlerchr 

Yep, that is what it is doing . . . or non-doing . . . .  I was able to follow the hint on the discourse thread and drag and drop the citation into the group . . . that works.  But the "work flow" has been the right-click on the group line item and select "add entries to group" . . . .

**Comment by Siedlerchr** [comment]
I think the issue is a side effect of https://github.com/JabRef/jabref/pull/9574
