### ISSUE TITLE
Fix "Protected Terms" formatting

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10415]
Test bib:

```bib
@Article{demo,
  title  = {BPMN4TOSCA rocks in BPMN and TOSCA},
}
```
1. Enable custom list "custom" in the preferences. Result:
     ![image](https://github.com/JabRef/jabref/assets/1366654/27e287a1-8d3e-41a4-8363-dc0df760da6a)
2. Open the entry editor of `demo` entry. Navigate to the `title` field.
3. Place the cursor to the beginning of `BPMN4TOSCA`.
4. Right click - go to Protected terms - Add selected text to list. (nothing can be selected)
  ![image](https://github.com/JabRef/jabref/assets/1366654/ee0533af-1289-4a04-8d44-7a7ebefd6b92)
5. Double click on `BPMN4TOSCA`
6. Add to list\
   ![image](https://github.com/JabRef/jabref/assets/1366654/b8318f24-8145-4f46-a141-5b624ef353e3)
7. List has space at the end\
    ![image](https://user-images.githubusercontent.com/1366654/236204305-8df041d9-c32b-4825-b5da-de64f8bef635.png)
8. Add BPMN (using a double click)
9. Add TOSCA (using a double click)
10. Execute "Protect terms"\
    ![image](https://user-images.githubusercontent.com/1366654/236204765-948a4926-c99c-463b-89df-66f82a150edd.png)
11. Result: `{}{BPMN}{}4TOSCA rocks in {}{BPMN}{} and {}{TOSCA}{}`
12. Modify `demo.terms` manually: Remove spaces at the end.\
    ![236204305-8df041d9-c32b-4825-b5da-de64f8bef635](https://github.com/JabRef/jabref/assets/1366654/fb06cc16-40f5-4556-b54f-25d8b28af055)
13. Execute "Protect Terms"
14. Result: `{}{BPMN}{}4TOSCA rocks in {}{BPMN}{} and {}{TOSCA}{}`

These points have to be fixed:

- [ ] Step 4: It should be possible to add the term to current word to the list - even if nothing is selected. A right click and then "Add text to selected list" should simply add the current word to the list
- [ ] Step 6: The selected text should be trimmed
- [ ] Step 14: There should be no `{}` contained. --> `{BPMN4TOSCA} rocks in {BPMN} and {TOSCA}`
- [ ] In general, longer terms should be treated first (to avoid substring issues)
- [ ] Reiterating on "Format field" should not lead to multiple {}: `{}{}{}{}{}{}{}{BPMN}{}{}{}{}{}{}{}4TOSCA rocks in {}{}{}{}{}{}{}{BPMN}{}{}{}{}{}{}{} and {}{}{}{}{}{}{}{TOSCA}{}{}{}{}{}{}{}`

Also add test cases.

**Comment by yuyan-z** [comment]
Hi, is anyone currently working on this issue? If not, we would like to have it as our course project.
We are 7 students from IMT Atlantique and we are expected to finish a contribution on the 19 December.
Best regards.

**Comment by Siedlerchr** [comment]
@yuyan-z  Thanks for your interest,  you are welcome! the issue is free to take. I will put it now on reserved and assign you

**Comment by yuyan-z** [comment]
Thank you so much! We will start working on it and create a draft pull request as soon as possible
