### ISSUE TITLE
Automatically focus on frequently used entries

### ISSUE THREAD

**Issue by ehehela** [JabRef/jabref#10418]
If attachments to an item have been opened frequently recently, they can be considered popular. I suggest that Jabref automatically display them at the front of the group, or highlight them.

**Comment by ilippert** [comment]
I guess, it might be possible for JabRef to be aware if an entry was engaged with - though I would want too disable it. For enabling it, an additional timestamp might be used that is updated whenever an entry is shown in the entry editor, or a click on it in the entry table happens.

**Comment by ehehela** [comment]
To be exact, JabRef should count the number of times that the entry is accessed in a period, e.g., the number of times the attachments (PDF files or others) were accessed in a month. 
Or perhaps, JabRef could add a new column named ViewCount to log the number of times in a period set by users. In this case, users can quickly find entries by sorting this column.

**Comment by jiahengguo123** [comment]
Hello, I am a new contributor. And I will carefully read the contribution guidelines. Could you please assign this issue to me?

**Comment by ThiloteE** [comment]
@ehehela could you please describe your workflow where you need this? Why do you want to know this information? Is this a shared library or do you work alone? Have you ever thought about simply adding frequently used entries to groups or labeleling them as important? We even have a priority label.

![image](https://github.com/JabRef/jabref/assets/73715071/28e7ef02-55f9-49c0-abfe-7a66fc028226)
You also could create automatic keyword groups that capture entries with certain keywords. E.g. 
![image](https://github.com/JabRef/jabref/assets/73715071/770c99a3-bff4-4d0c-9df2-2ed28d4a7ede)



If we were to implement what you suggest, would this not introduce performance issue for large libraries? Also, how to reset the counter? Where to store the counter? - on pc or in library file? What happens, if multiple users have access to the library? Do you want to have separate counters for each user or multiple counters for each? ....

**Comment by koppor** [comment]
@ThiloteE The idea is that JabRef automatically tracks readings - without any additional user input. Explanation of the general idea in German: https://de.wikipedia.org/wiki/Mylyn 

Scientific background:

* Focusing knowledge work with task context. PhD thesis. Available at: <https://www.researchgate.net/publication/235350419_Focusing_knowledge_work_with_task_context>
* What You See Is What You Need: [WYSIWYN: Using Task Focus to Ease Collaboration](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.99.3548). [[PDF](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.99.3548&rep=rep1&type=pdf)]
* [Beyond Integrated Development Environments: Adding Context to Software Development](https://doi.org/10.1109/ICSE-NIER.2019.00027). This paper reasons on an "Automated Assistant" and calls for a deeper investigation of the concept of "context". In contrast, the ContextSwitcher assumes that the user knows about his context and defines queries for the context by hirself.

**Comment by koppor** [comment]
> To be exact, JabRef should count the number of times that the entry is accessed in a period, e.g., the number of times the attachments (PDF files or others) were accessed in a month.

This is a nice thing. Implementation: Use a MVStore provided by [h2](https://github.com/h2database/h2database) stored in the directory retrieved with

```java
Path.of(AppDirsFactory.getInstance()
                                         .getUserDataDir(
                                                 OS.APP_DIR_APP_NAME,
                                                 "views",
                                                 OS.APP_DIR_APP_AUTHOR))
```

The database knows tracks for each citation key the number of views. Granularity: one hour (that means, if accessed at 10:05 and 10:43, it counts as one).

>  Or perhaps, JabRef could add a new column named ViewCount to log the number of times in a period set by users. In this case, users can quickly find entries by sorting this column.

This is the second thing to implement so that the data can be accessed.

8 years ago, we had explicitly writable fields (refs https://github.com/JabRef/jabref/issues/574). I think, we should have a `org.jabref.model.entry.field.FieldProperty` adding `INMEMORY` stating it should not be written and not be synchronized to a server.

Hints

- On load of the library the field `viewcount` has to be filled based on the `MVStore` content
- The MVStore is updated on each view
- Use the obersable JavaFX lists to "listen" to changes (personal remark: I like the event bus more, but we decided to focus on one technology)
- In case the citation key is renamed, it has to be renamed in the count, too

**Comment by ehehela** [comment]
I was struggling to articulate my thoughts, but thankfully, @koppor  accurately and professionally expressed what I wanted to say.

Take myself for instance, there are many literatures regarding one research topic. Unread and low-quality entries are automatically moved into "Inbox" group, in which priority is used to mark entries to be read and quality-improved first. Other entries are in specific groups according to their research fields. When I decide to do research in one certain direction, I usually first locate a group then scroll down and up to query related papers which may well be the key references and will be looked up many times in the future. However, these papers are scattered in different (sub-)groups. How to quickly get these needed and strongly correlated papers? Maybe Jabref could guess according to user behavior, e.g., times of opening attachments. Maybe some smart groups will promote this. Or like the following drafts (illustrative, not necessary). 
![屏幕截图 2023-10-17 165522](https://github.com/JabRef/jabref/assets/56829479/77732bff-84b0-4ff8-beec-9521d66149ce)
![屏幕截图 2023-10-17 181322](https://github.com/JabRef/jabref/assets/56829479/dd53fb2b-a6b0-4af1-89ca-b4defd296f3c)

**Comment by koppor** [comment]
A new intelligent group should be introduced. This is comparable to BibDesk's "Smart" groups.

- Add preference as outlined at screenshot at https://github.com/JabRef/jabref/issues/10418#issuecomment-1766132355
  - Use "enable internal user behavior analysis" (to indicate that no data is shared to an external server)
  - ![屏幕截图 2023-10-17 181322](https://github.com/JabRef/jabref/assets/56829479/dd53fb2b-a6b0-4af1-89ca-b4defd296f3c)
- Add group "Popularity"
  -  ![屏幕截图 2023-10-17 165522](https://github.com/JabRef/jabref/assets/56829479/77732bff-84b0-4ff8-beec-9521d66149ce)
  - Name: "Popularity" (capital "P")
  - Enabled only if above preference is enabled
  - Do not show "Ignore zero times of read". The group always shows entries with read > 0. For the other feature, we 
- The views need to be tracked in a `MVStore`
- Introduce new method `getOtherDataDir` in `org.jabref.gui.desktop.os.NativeDesktop`
- Store the `MVStore` in `tracking.mv` in `getOtherDataDir`. Hashtable `<BibEntry, Integer>`. Hashtable name: `hashCode()` of `fileName` of library (or `BackupFileUtil.getUniqueFilePrefix(file) + "--" + file.getFileName()`). In this way, each library tab has its own hash table
- Hook into `org.jabref.gui.LibraryTab#showAndEdit` to update the counter

**Comment by ExrosZ** [comment]
Hi! I am a university student looking to work on an issue in this repository, I've read the contribution guidelines and I think I can implement this feature, I'd love to be assigned to this issue.

**Comment by koppor** [comment]
In our DevCall, this raised huge discussions. If you still think, this is useful, please make a post at https://discourse.jabref.org/c/features/6
