### ISSUE TITLE
Smart Screen war

### ISSUE THREAD

**Issue by freibb** [JabRef/jabref#10429]
**Is your suggestion for improvement related to a problem? Please describe.**
As of September 30th, download of the Jabref 5.10 MSI installer raises SmartScreen Warnings in MS Edge. Also does launching the executable of the portable version.

**Describe the solution you'd like**
Try to remove SmartScreen warnings to improve User Experience.

**Additional context**
![image](https://github.com/JabRef/jabref/assets/60350129/789cfeb0-09b4-448b-ab8d-dff94bb5b441)

**Comment by Siedlerchr** [comment]
@freibb  This is a known problem and I outlined the arguments a while ago here in the discussion.
https://discourse.jabref.org/t/jabref-installation-windows-10-security-warning/2853/2
