### ISSUE TITLE
Add a new Fetcher for Isidore.science

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10423]
**Is your suggestion for improvement related to a problem? Please describe.**
As a user in the fields of social sciences I would like to have an integration of 
https://isidore.science
Your search assistant in Humanities and Social Sciences

**Describe the solution you'd like**
A new fetcher for https://isidore.science
It should include author, abstract (DOI/URL), date etc and any other related metadat
If available, it should include the fulltext 

**Additional context**
https://isidore.science/api 
It probably makes sense to filter the type of results to Documents or Publications like it's done on the website

**Comment by u7492883** [comment]
I am interested in working on this issue. Is it free to take?

**Comment by Siedlerchr** [comment]
Yes. This issue is available. Always check the status of the project on the right side
