### ISSUE TITLE
Display issues with fulltext search button

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10425]
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

In the entry editor, click the button for searching of fulltexts online. Once clicked, the button disappears.

https://github.com/JabRef/jabref/assets/5037600/6522dd2f-6169-499d-b257-45193d55bbd8

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by 1162706031** [comment]
Hello, I am very interested in this issue and thank you very much for assigning this issue to me.

**Comment by ThiloteE** [comment]
Thank you @1162706031. I don't know if this is a good first issue. If you have trouble solving this, please comment and I will unassign you. You then could check out https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22. Be aware, difficulty of good first issues varies too.
