### ISSUE TITLE
Import pdf - update DOI

### ISSUE THREAD

**Issue by thecaligarmo** [JabRef/jabref#10426]
**Is your suggestion for improvement related to a problem? Please describe.**
When importing pdf files, Jabref correctly is able to get the Eprint information. For example, it correctly puts "arXiv:1912.12449v1[math.CO]" as the Eprint information for a particular pdf file I have. Currently (as far as I can tell) no post-processing is done. It would be nice to have some post-processing

**Describe the solution you'd like**
It would be nice if Jabref notices that this Eprint entry starts with "arXiv" and automatically populates the DOI entry to the appropriate DOI (see https://github.com/JabRef/jabref/issues/9092)

**Additional context**
No other additional context needed.

**Comment by ThiloteE** [comment]
How exactly do you import the files? What method do you use? (There are multiple, that's why I ask).

**Comment by thecaligarmo** [comment]
I was using the "lookup"-> "Search for unlinked local files" option.
