### ISSUE TITLE
Keep entry highlighted after editing

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#10439]
I often lose my place in the entry table after editing an entry, because editing removes highlighting from the entry table.

Current:
1. Select an entry in the table => row turns blue*
2. Edit the entry (any field) through text entry or combo box => table row loses blue highlight

Desired:
1. Select an entry in the entry table => row turns blue*
2. Edit the entry => table row remains highlighted

*Default light theme

JabRef 5.10--2023-09-01--779e555
Linux 6.4.12-1-default amd64 
Java 21-internal 
JavaFX 20+19

**Comment by ryan-carpenter** [comment]
Entry editor file:

`src/main/java/org/jabref/gui/entryeditor/EntryEditor.java`

**Comment by ryan-carpenter** [comment]
This issue will need to be verified, because I was just editing entries and was surprised to discover the table row still highlighted afterward. I tested several different fields in several entries and the table row always remained highlighted after the edits.
I have not updated JabRef or my operating system. However, I did set up IntelliJ for JabRef last night. One of the configuration steps is to install Temurin via IntelliJ. I don't know if installing that could have fixed any errors or incompatibilities with my existing JavaFX setup. However, JabRef still shows exactly the same version information as in my original report.

**Comment by Siedlerchr** [comment]
Ah sorry, misunderstood this issue.  I cannot reproduce it here on mac with a recent version

**Comment by ryan-carpenter** [comment]
The issue returned after another UI problem and resolved when I restarted JabRef, the row highlighting appears to be a symptom of another problem.

The UI problem is one that happens often, where dropping entries into a group makes the groups tree scroll to the bottom and start flickering. When something like this goes wrong temporarily, I have residual issues such as the row highlighting and needing to double click (instead of single click) an entry to open it from the table. Like row highlighting, the double-click issue also resolves when I restart JabRef.

**Comment by ryan-carpenter** [comment]
I figured out what is going on. Row highlighting works as expected when the search box is empty and exhibits the unwanted behaviour when the search box is not empty. Restarting JabRef clears the search box, which makes row highlighting return to normal. If row highlighting is meant to behave the same regardless of the search box, then this issue is a bug rather than a suggested enhancement.

**Comment by Siedlerchr** [comment]
Does clearing the search manually return the desired. behavior?

**Comment by u7492883** [comment]
Is this issue available to work on? If so I would like to work on fixing this bug.

**Comment by ryan-carpenter** [comment]
> Does clearing the search manually return the desired. behavior?

Yes it does, and this is the same for plain or regex searches.

**Comment by ThiloteE** [comment]
@u7492883 thanks for your interest. Yes, I will assign you for now. If you feel this is a too difficult issue for you, please check out free to take [good first issues](https://github.com/orgs/JabRef/projects/5) at the projects page.

**Comment by koppor** [comment]
> One of the configuration steps is to install Temurin via IntelliJ. I don't know if installing that could have fixed any errors or incompatibilities with my existing JavaFX setup.

JavaFX dependencies are are handled via `build.gradle`, because JavaFX is not shipped with OpenJDK anymore.

Maybe there are side effects of the JRE. IDK.

> JabRef still shows exactly the same version information

If you start JabRef von IntelliJ, version `100` should be shown, without any commit information.

**Comment by koppor** [comment]
> into a group makes the groups tree scroll to the bottom and start flickering

Should be solved with https://github.com/JabRef/jabref/pull/10488

**Comment by AEgit** [comment]
I remember that keeping focus on selected items was an issue with JabRef in the early stages of version 5. Maybe the following problem (although related to the groups panel, rather than the entry view) has a similar underlying issue (?):
https://github.com/JabRef/jabref/issues/3436

**Comment by LoayGhreeb** [comment]
@ryan-carpenter, I can't reproduce the issue.

> Row highlighting works as expected when the search box is empty and exhibits the unwanted behaviour when the search box is not empty

If you have an active search query and select an entry that matches, then update that entry by removing text that matches the search term, the entry will no longer match. It will be removed from the table, and another entry (either above or below) will be selected.

**Comment by ryan-carpenter** [comment]
> @ryan-carpenter, I can't reproduce the issue.
> 
> > Row highlighting works as expected when the search box is empty and exhibits the unwanted behaviour when the search box is not empty
> 
> If you have an active search query and select an entry that matches, then update that entry by removing text that matches the search term, the entry will no longer match. It will be removed from the table, and another entry (either above or below) will be selected.

I am certain that I was not changing entries in a way that would prevent them from matching the search, and I recall testing with a variety of fields to be sure of this and to check different types of fields. However, I tested again today with and without regular expressions and I can no longer reproduce the issue (now on JabRef 5.16 from 2024-08-26), so it seems to be resolved.
