### ISSUE TITLE
Change bib file layout to match biber?

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1043]
I just discovered that biber has the ability to reformat an existing bib file.
Running `biber --tool --output_fieldcase=lower --output_align` results in a file layout which almost coincides with the current JabRef convention.
However, I noticed the following differences:
- [ ] `@article` is in lowercase instead of our `@Article`
- [ ] The fields are sorted by alphabet (we sort by ?)
- [x] The last field ends with a comma (see below; I think we already had a discussion about this)
- [x] The equal signs are also aligned, i.e.
````
@article{key,
  abstract     = {abstract},
  author       = {author},
  editor       = {editor},
````

I propose to adopt the changes marked with a tick. What is your opinion about this, @JabRef/developers ?

**Comment by oscargus** [comment]
Alphabetical sort makes it harder for version control.

, at the end makes it easier for version control, but as I recall it we didn't want it to avoid arguments with purists.

Alignment and casing: no opinion, both versions work for me (but I do not like ALLCAPS).

**Comment by stefan-kolb** [comment]
We discussed _all_ of the points several times in the dev calls. You can see the Minutes and issues on this for clarifications. Personally, I don't want to kick up a shindy again on this decisions. Although I voted differently on some of the decisions.

**Comment by tobiasdiez** [comment]
@stefan-kolb I didn't found anything concrete on these points in the Minutes (although there were of course other documented design decisions), this is why I opened this issue. But if you have already discussed all of this, then close.

**Comment by lenhard** [comment]
After some discussion during the devcall, we decided to:
 - To risk arguments with purists and always prepend `,` after every field for reasons of version-controllability
 -  To do as biber does and right-align the equals sign.

As of 0b7bea2f805b6827923644ff67a069a24e1895ad this is implemented.

**Comment by koppor** [comment]
Refs #481
