### ISSUE TITLE
feature request: choose whether exact or rounded group totals are displayed

### ISSUE THREAD

**Issue by colleenjg** [JabRef/jabref#10446]
**Problem**: For organization purposes, I rely on being able to quickly and easily see exactly how many references are in specific groups and subgroups of my reference library. However, with a recent update, previously exact numbers > 999 are now rounded (e.g., "1.3k" is displayed next to a group, instead of "1295"). This update is likely great for a lot of users who don't need exact numbers. But it means that to see the exact number of references in a group, you have to scroll to the bottom of the group and use the `#` column. 

**Solution:** Would it be possible to include this as a preferences option? Users could then choose whether they want exact or rounded numbers to be displayed in the groups panel.

**Version**: JabRef 5.10
![groups](https://github.com/JabRef/jabref/assets/26847334/b630b9a7-dc51-4618-bb63-e716f7fbdac9)

**Comment by ThiloteE** [comment]
There were scaling issues for people that changed the font size, which cut off the number of entries in a group for some people. The new implementation offers to show the exact number of entries by hovering with the mouse over the number. Would that be acceptable to you?

Also, what do you mean with scrolling to the bottom of the group and using the `#` number? Could you provide a screenshot?

**Comment by Siedlerchr** [comment]
@colleenjg  The latest development version shows a tooltip with the exact number

**Comment by colleenjg** [comment]
@ThiloteE thanks, I missed that! I didn't hover long enough.

And I just meant that as a workaround, I was adding a `#` column to the main view, and scrolled down to see the last number in a group, in order to know exactly how many items it had.

The hover feature is great - thanks for pointing it out!
![numbers](https://github.com/JabRef/jabref/assets/26847334/0c102510-5dc3-496a-87e4-9f0116b50685)
