### ISSUE TITLE
Add `git remote update` step to developer documentation

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#10448]
I forked and cloned the jabref repo, according to the instructions [here](https://github.com/JabRef/jabref/blob/main/docs/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/pre-03-code.md#clone-your-forked-repository-on-your-local-machine), then had an error at the last step.

```
> git branch --set-upstream-to=origin/main main
fatal: the requested upstream branch 'origin/main' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
hint: Disable this message with "git config advice.setUpstreamFailure false"
```

 I verified the connections and tried `git fetch` but still got the same error. Adding the following step resolved the error, so perhaps this should be added to the documentation.

```
> git remote update 
Fetching upstream
Fetching origin
From https://github.com/myusername/jabref
 * [new branch]      main       -> origin/main
```

Problem solved. I am not sure if this step is redundant after the previous one.

```
> git branch --set-upstream-to=origin/main main
branch 'main' set up to track 'origin/main'.
```

**Comment by iagocarmona** [comment]
Hello, I would like to work on this!

**Comment by koppor** [comment]
Thank you for pointing it out. I fixed it at https://github.com/JabRef/jabref/commit/24cc4cc75c64b9cb0e45bededd3faf0a72ffe539. I needed to put another fix at https://github.com/JabRef/jabref/commit/c8f5905183d254ea22c83009dfd2e6ca8dd5e704

Reason: On Linux, the directories are case-senstive.

@ryan-carpenter Thank you for reporting

@iagocarmona Sorry for "quickly fixing" it for our selves. I think, this back-and forth for three lines of markdown change is not worth the time. Please try to choose another issue. See https://docs.jabref.org/contributing our offerings.
