### ISSUE TITLE
Make it easier to enable journal information fetcher

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10458]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

In the entry editor, click the small "i" next to the journal name. It complains that one should enable the journal information fetching in the preferences.

Two bugs/inconveniences:
- It says the option is under "Web search", but it is actually under "Entry editor".
- Secondly, it should just ask the user directly whether he wants to enable it or not. It's pretty inconvenient to manually open the preferences to set the correct toggle. I feel like we talked about this in the implementation PR, but for me it doesn't make much sense to point the user to the preferences if the feature is disabled.

https://github.com/JabRef/jabref/blob/ca00d64af64cecc4a36a3a2219299bc86cc4ccee/src/main/java/org/jabref/gui/fieldeditors/JournalInfoOptInDialogHelper.java#L17-L24

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Zhouheng98** [comment]
Hi, I am a student, can I try to solve this problem?

**Comment by tobiasdiez** [comment]
Sure, go ahead!

**Comment by ThiloteE** [comment]
@calixtus since this is preferences related
