### ISSUE TITLE
Import by id: cancel doesn't really cancel the request

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10508]
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Import something by id, and click "cancel". The dialog disappears, so it looks like it canceled the request. But if the request actually times out (or fails for some other reason) you still get the error dialog shown. 

A proper fix would require to cancel/disconnect from the actual http request, and that might be a major refactoring. But at least the composite id fetcher should have a option to not ask the next id fetcher, and errors should be hidden from the users after cancel.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by SUPWEZZ** [comment]
Hi there, I would like work oaths issue, please assign it to me if possible!

**Comment by ThiloteE** [comment]
Is this a good first issue for somebody that is new to coding Tobias?
If not, @SUPWEZZ, please check out our [good first issues](https://github.com/orgs/JabRef/projects/5) collected at our projects board.

**Comment by SUPWEZZ** [comment]
Hi @ThiloteE , I've noticed the issue titled "Unchecked 'Do not ask again' does not work," and I'm very interested in attempting to resolve it. If it's not already assigned, may I take a stab at addressing this problem?

Thank you for your consideration.

**Comment by ThiloteE** [comment]
Well, if you insist and you are confident, then have a go at it.

**Comment by koppor** [comment]
@ThiloteE I think,  @SUPWEZZ meant https://github.com/koppor/jabref/issues/566. They is already assigned there. Thus, I unassign here.
