### ISSUE TITLE
Import by id: make button larger

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10507]
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Search something by id. Once you click on "Generate" the button text switches to "Searchi...". It would be better if the button would be slightly larger from the get-go to show the complete text.
![image](https://github.com/JabRef/jabref/assets/5037600/15bbf5c8-57fa-47c1-8f8a-b7dbaa8b3dfb)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by JMS063** [comment]
Hi there, I would like work oaths issue, please assign it to me if possible!

**Comment by JMS063** [comment]
Hi there,
I have updated the size of the button, have a look before I rise a PR :)



![Screenshot 2023-10-20 at 12 25 14](https://github.com/JabRef/jabref/assets/121246951/ba905322-df60-4e5d-a81e-6e6a83d34110)
![Screenshot 2023-10-20 at 12 25 19](https://github.com/JabRef/jabref/assets/121246951/529a117a-4457-4bff-8229-9bc9c9b613aa)

**Comment by DiamondMyK** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

**Comment by JMS063** [comment]
I have already solve this issue  :)

**Comment by ThiloteE** [comment]
@DiamondMyK , please have a look at our [good first issues](https://github.com/orgs/JabRef/projects/5) projects page. We usually only assign one student (or one group of students that know each ohter) per issue, as we don't know your grading requirements.
At the top right of an issue, you will see if that issue is already reserved and assigned to somebody.

![image](https://github.com/JabRef/jabref/assets/73715071/b3eff6da-bfd7-4521-bdb1-145605d49920)

**Comment by koppor** [comment]
> I have already solve this issue :)

I can't see anything athttps://github.com/JMS063/jabref/branches. Where do you share your progess? Looking forward!

**Comment by JMS063** [comment]
I haven't managed to make a push. I will push tomorrow and make a pull request as soon as possible
