### ISSUE TITLE
Entry sorting for Export

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#1051]
JabRef version 3.3dev--snapshot--2016-03-28--master--f9f6cec on Ubuntu 14.04.

When I try to export a database to a different format (I tried simpleHTML and my own implementation of Markdown), the sorting order of the entries is not used. It doesn't matter if I set the current sorting by clicking on the columns or if I'm using the default sorting accessed through Preferences -> Entry Table.

The only thing the error console shows is

```
Mar 28, 2016 6:02:58 AM net.sf.jabref.exporter.ExportFormat performExport
WARNING: []
```

I found similar issues that were reported some years ago where the solution always was to set the *default sorting*. It would be helpful if someone could confirm that this indeed works.

**Comment by Siedlerchr** [comment]
As there have been recently fixes with Entry exporting, did you try the latest version from master?
http://builds.jabref.org/master/

**Comment by halirutan** [comment]
Let me add some *official* example data. I'm using this [test.bib](http://mirror.unicorncloud.org/CTAN/biblio/bibtex/contrib/test/test.bib). I have set the default sorting to year (and title as second) and it looks good in the interface

![bibtex1](https://cloud.githubusercontent.com/assets/511683/14091836/d145a7a4-f542-11e5-94cf-62b4deccb67d.png)

When I choose `File` -> `Export` and export to simple html, then the ordering is destroyed:

![bibtex2](https://cloud.githubusercontent.com/assets/511683/14091859/f66baf92-f542-11e5-842d-cd6f2193e65f.png)

**Comment by halirutan** [comment]
@Siedlerchr Let me try the latest snapshot.

**Comment by halirutan** [comment]
@Siedlerchr Same behavior with the latest snapshot. I updated the version in the original issue description.

**Comment by Siedlerchr** [comment]
@halirutan  Thanks for your update and reproducing the issue.

**Comment by koppor** [comment]
@halirutan halirutan Just to double check: Did you choose "Export in current table sort order" in the preferences as shown in the screenshot?

![grabbed_20160330-085407](https://cloud.githubusercontent.com/assets/1366654/14134125/05b15dae-f655-11e5-8611-8e972b91630c.png)

**Comment by halirutan** [comment]
@koppor Thank you. Since this option was not available until recently (my ubuntu comes originally with 2.10beta) I did not notice this additional setting when testing version 3!

That solves the problem!
