### ISSUE TITLE
Re-introduce CitationKey column as default in the entry (main) table

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10510]
The main/entry table should show the column citation key by default.

internal issue for refefence: 
https://github.com/JabRef/jabref-issue-melting-pot/issues/305

Currently, this has to be manually activated using the preferences by adding the field "citationkey" (internal) 

<img width="788" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/9106272c-75d5-4182-b0ed-f89114f85483">

It should be added as default value in the preferences. It should be coming before entrytype and it should have a decent width.

https://github.com/JabRef/jabref/blob/c444c739d62737003fd1c178d3aeefb628fe78b1/src/main/java/org/jabref/preferences/JabRefPreferences.java#L606-L607 

To test, you can reset your preferences and restart JabRef. Then the column should be visible

**Comment by u7288020** [comment]
Hi there,

I am new to open source contribution and would love to contribute to this issue. Could you please assign it to me? I'll try my best to resolve the problem - If you have any specific information or steps you'd like me to follow, please feel free to share them.

Thank you!

**Comment by tobiasdiez** [comment]
I think we removed it since normally it doesn't contain any new information (by default it's authors + year) and users almost never need it (you don't want to copy the key manually but use right click, copy key).

**Comment by Siedlerchr** [comment]
@tobiasdiez please see the linked issue. @koppor made clear why it should be there

**Comment by ThiloteE** [comment]
I don't have a strong opinion on this. Our user-base is still largely bibtex/biblatex based, so whatever. It is now easier to remove unwanted columns from the entry table by right-clicking on the column, so this should be no biggy.
![image](https://github.com/JabRef/jabref/assets/73715071/f59bba8d-5194-44e5-af7b-617e26a84735)
Once we have more CSL styles, and hence a growth in users and contributors from OpenOffice/LibreOffice, this issue might become slightly more controversal, but for now, whatever.

**Comment by ThiloteE** [comment]
By the way, one should not have to refer to a non-open issue from "issue-melting-pot" to justify ones proposal. IMHO, all relevant info should be public.

For context, this was the original issue:

Default configuration:

![grafik](https://github.com/JabRef/jabref-issue-melting-pot/assets/1366654/6fe5e5a2-ce52-49d3-b561-b039c5760d59)

I get following warnings in `bibtex`:

```
Warning--empty journal in Hejda2023
Warning--empty journal in Veytsman2020
```

I could find the entry for searching the key. However, I could also sort the column. I can also use my eyes to follow the entry table. - In general, the entry table provides an overview of entries. My claim: i) Users are interested in a subset of the entries displayed in the entry table and ii) are using the citation keys in LaTeX and check these keys in the entry table. This makes the keys an integal part, which should be shown.

I agree that for "modern" interfaces (such as JabRefOnline or CiteDrive), other approaches might be taken. Our focus is still BibTeX and a unique key is a key part of BibTeX

After the change:

![grafik](https://github.com/JabRef/jabref-issue-melting-pot/assets/1366654/54cfa3ca-54b6-4b29-8708-169be52517dd)

---

Manual config:

![grafik](https://github.com/JabRef/jabref-issue-melting-pot/assets/1366654/f8978fee-25bc-464f-b267-85d37754130a)

**Comment by koppor** [comment]
I wrote more than 100 papers, my library is more than 1000 entries large. I lead research groups. I worked with dozens of LaTeX newcomers. I discussed with LaTeX experts at the TUG user group. This needs to be implemented. No work arounds

Research groups do not change their citation keys to something JabRef wants; they have their own way. - The sort order of the table is sometimes hard.

**Comment by Siedlerchr** [comment]
@ThiloteE Copying images fromt he private repo does not work, you need to reupload them

**Comment by tobiasdiez** [comment]
This is how the jabref looks like on a normal-sized laptop screen in fullscreen with the default config:
![image](https://github.com/JabRef/jabref/assets/5037600/ba30b0f2-7cde-4bfd-b78c-25bd80bdfd5c)

Already pretty full. Which column do you want to remove to make space for the citation key?

**Comment by tobiasdiez** [comment]
For context, the same arguments were brought forward in the PR that removed the citation key column: https://github.com/JabRef/jabref/pull/7286. And as far as I can see no user complained in the past 2.5 years.

**Comment by Siedlerchr** [comment]
What about adding this to the right click menu? as a simple option

**Comment by koppor** [comment]
Thank you for the link! https://github.com/JabRef/jabref/pull/7286

Hiding a column is possible via right-click menu, thus shrinking is easy. Enlarging is currently an issue. The default configuration should be good.  - I am talking to persons not using JabRef anymore or at all - and the confusion with BibTeX keys not shown in the UI is one reason.

**Comment by jiaxin0103** [comment]
Hello, I am a student at the Australian National University. For our team project, we need to contribute to an open-source project. May I be assigned to this task?

**Comment by koppor** [comment]
@jiaxin0103 Thank you for your interest. The code should be easy. You also need to add an ADR document to the folder https://github.com/JabRef/jabref/tree/main/docs/decisions outlining the pros and cons of showing/not showing the citation key column as default. With discusisons linked.

**Comment by koppor** [comment]
It is good to have this in the alpha/beta release to be enabled to gather user feedback.

**Comment by suftware** [comment]
Hi @koppor , I am part of the same group as @jiaxin0103 and am working on this issue - would I be able to be added as an assignee as well? Thank you!

**Comment by koppor** [comment]
@suftware @jiaxin0103 I assume, this is a one-line fix - and a line to the CHANGELOG.md. This issue guides you through the process to contribute to an open source project. Please complete this fast - and try to take another issue afterwards to really level-up your coding skills!
