### ISSUE TITLE
Add "reset to default" button for "Cite command"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10569]
We need a button "Reset to default" for the "Cite command". A user might put arbitrary strings there - and we need to support them to go back to the default easily. The default is `\cite{key1,key2}`.

![image](https://github.com/JabRef/jabref/assets/1366654/31c48b92-3cfd-4320-a542-d4f676d07584)

The icon and the label text can be found in "Citation key patterns":

![a](https://github.com/JabRef/jabref/assets/1366654/87f908b7-161f-40ea-9f76-22c95a6d7539)

Refs https://github.com/JabRef/jabref/issues/10568

**Comment by JonathanRech** [comment]
Hello @koppor , I would like to try work on this issue.

For clarification: I should add a Button to "Cite Command" that uses the icon and labeltext like in "Citation key patterns"

**Comment by SUPWEZZ** [comment]
Hi @koppor, since the previous two issues were unassigned, may I do this new issue?

**Comment by Siedlerchr** [comment]
@JonathanRech  was first
>  For clarification: I should add a Button to "Cite Command" that uses the icon and labeltext like in "Citation key patterns"

Not only the button but also the functionality needs to be implemented. The value of the pattern should be reset to the default value.

**Comment by calixtus** [comment]
Why an extra button to reset this? Maybe a tooltip or an example string on the right is better.
The reset functionality is provided by the preferences dialog itsellf and the current implementation with the defaults map is soon to be replaced anyways.

**Comment by Siedlerchr** [comment]
@calixtus You can reset the entry preview as well. Same for custom entry types. So this is totally fine. And button we mean a simple icon.

**Comment by koppor** [comment]
> Why an extra button to reset this? Maybe a tooltip or an example string on the right is better.

@calixtus Because we like **fine-grained** reset-to-defaults 😅. Moreover, this is a highly-needed work-around for https://github.com/JabRef/jabref/issues/10568. -- https://github.com/JabRef/jabref-issue-melting-pot/issues/323 is the longer solution, but we need an internal agreement to make that issue public.

**Comment by calixtus** [comment]
We had quick discussion about it. I'm fine with it.
