### ISSUE TITLE
The command "Push entries to external application" adds a "null" prefix and suffix to an existing Citationkey in LaTeX.

### ISSUE THREAD

**Issue by NeymanDmitry** [JabRef/jabref#10568]
### JabRef version

5.11 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04 (64-bit)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a new entry or use an existing one with Citationkey "CITATION_EXAMPLE" - for example in JabRef 5.11.
2. Open a LaTex document in TexStudio.
3. Click on the "Push entris to external application" button or use the command (ctrl+L) to add an entry to latex.

As a result, the following link with the following content will appear in the latex document:

\cite{nullCITATION_EXAMPLEnull}

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
Can you show to us, how your preference look like?

![image](https://github.com/JabRef/jabref/assets/1366654/31c48b92-3cfd-4320-a542-d4f676d07584)

(Side note: This might be a regression comming from https://github.com/JabRef/jabref/pull/10303)

**Comment by NeymanDmitry** [comment]
![Screenshot from 2023-10-24 17-17-42](https://github.com/JabRef/jabref/assets/144049425/23fe3323-14a7-4021-ae54-33bf366d9f8c)

**Comment by NeymanDmitry** [comment]
It looks like this (in my picture) but I tried it like this "\cite{key1,key2}" but the result is the same.

**Comment by koppor** [comment]
What happens if you change to `\cite{key1Xkey2}` and select two entries and press <kbd>Ctrl</kbd>+<kbd>L</kbd>?

Here, I get `\cite{Kopp2008bXDecker2008a}`, which is fine...

**Comment by NeymanDmitry** [comment]
> What happens if you change to `\cite{key1Xkey2}` and select two entries and press Ctrl+L?
> 
> Here, I get `\cite{Kopp2008bXDecker2008a}`, which is fine...

In this case I got a similar result. After which I put a comma instead of X and everything began to work correctly.

**Comment by hchuanqi** [comment]
I encountered the seem issue, and then got back to 5.10 as workaround.

**Comment by hchuanqi** [comment]
> @hchuanqi Does the reset button introduced in #10569 and available at https://builds.jabref.org/main/ help?

By this suggestion and reviewing the manual exactly, I reinstalled v5.11 and modified the `Cite command` from `\footcite` (working properly in and before v5.10) to `\footcite{key1,key2}`, then it works fine now...

In v5.11, with previous setting of `Cite command` by `\footcite` , the `push entries to external application (TeXstudio)` command generated something like `\cite{nullGross1995null}`, 
while the expected output was `\footcite{Gross1995}`.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by koppor** [comment]
This was even fixed at the latest release version 5.12. See the CHANGELOG at https://github.com/JabRef/jabref/blob/main/CHANGELOG.md#512--2023-12-24
