### ISSUE TITLE
shortDOI formatter is very slow

### ISSUE THREAD

**Issue by stertooy** [JabRef/jabref#10589]
In one of my libraries, which contains approx 100 DOI entries, having the shortDOI field formatter active noticeably slows down the time it takes to save the library.
It takes <1 second to save without said formatter, but 30-40 seconds with, during which JabRef becomes unresponsive. This happens on every save, even when all DOI fields are already in the shortDOI format.

https://github.com/JabRef/jabref/blob/d6a0e59d96520b7cff46556bf3d44937343946df/src/main/java/org/jabref/logic/formatter/bibtexfields/ShortenDOIFormatter.java#L28-L40

https://github.com/JabRef/jabref/blob/d6a0e59d96520b7cff46556bf3d44937343946df/src/main/java/org/jabref/logic/importer/util/ShortDOIService.java#L30-L35

If I interpret the above pieces of code correctly, the formatter always makes a request to the shortDOI service, even if the DOI is already shortened. Would it be possible to first check if the DOI is already shortened (i.e. starts with "10/"), and only make a request if it is not?

**Comment by Siedlerchr** [comment]
Thanks for the report and your analysis.  Sounds like a good idea.

Solution: check if the DOI starts with  the Pattern 10/[a-z]+ should be sufficient.


For future:
Ideally, the request should be executed in a background thread as well, but this would be a bit more complex from the current architecture and would require some major refactoring.

**Comment by michalfarago** [comment]
Hello, could I work on this?

**Comment by stertooy** [comment]
> Solution: check if the DOI starts with the Pattern 10/[a-z]+ should be sufficient.

Although the shortDOI website says that shortDOI's are "of the form 10/abcde", the "abcde" part often contains numbers as well (e.g. `10/grv3jv`). Also taking into account that DOI's are case insensitive, perhaps `10/[a-zA-Z0-9]+` would be better?
