### ISSUE TITLE
Refresh button for LaTeX citations

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10584]
The [LaTeX citations](https://docs.jabref.org/advanced/entryeditor/latex-citations) are NOT backed by our file monitor.

Quick win: Add a "refresh" button:

![a](https://github.com/JabRef/jabref/assets/1366654/fff5447d-5663-49c6-9598-b0744e940da1)

The button then first sets `latexParserResult` to `null` and then calls `org.jabref.gui.entryeditor.LatexCitationsTabViewModel#init`.

For the button implementation inspiration see https://github.com/JabRef/jabref/pull/10580

**Comment by taliashark77** [comment]
@koppor may I try this issue for my university assignment?

**Comment by taliashark77** [comment]
Hi @koppor thanks for assigning me this issue, I just have a few questions about this task, any answers would be great. Firstly, is the purpose of the refresh button to give a quick fix to problems caused by the LaTeX citations not having a file monitor? Secondly, for setting the latexParserResult to null would creating a private setter method (to set to null specifically) in LatexCitationsViewModel an acceptable approach? Lastly, for calling init on the model after this has been done I need the current BibEntry, is there a way of retrieving this information? Thanks

**Comment by koppor** [comment]
> Firstly, is the purpose of the refresh button to give a quick fix to problems caused by the LaTeX citations not having a file monitor?

Yes. (The "full" solution is https://github.com/JabRef/jabref/issues/10585. I think, that solution is very difficult; and we need something working the next days/weeks)

> Secondly, for setting the latexParserResult to null would creating a private setter method (to set to null specifically) in LatexCitationsViewModel an acceptable approach?

I analyzed `org.jabref.gui.entryeditor.LatexCitationsTabViewModel#searchAndParse`, which is called when the tab is displayed. -- If you come up with something better, please let us know.

> Lastly, for calling init on the model after this has been done I need the current BibEntry, is there a way of retrieving this information?

I don't understand the question. The current BibEntry is stored in the variable `currentEntry` in the method `init(BibEntry)`. Thus, you should have access in the class... -- Nevertheless, I do not know, why you need that -- You should have a ViewModel at hand at the button...

**Comment by taliashark77** [comment]
Thank you for your guidance, I have now implemented a button which when clicked refreshes. I have only tested it by adding entries to my libraries and then loading up the LaTeX citations tab, then when I click refresh it seems to reload. Would you be able to point me in the right direction for testing it more extensively? Would it be best to use a UI, mocking or JUNIT test?

**Comment by koppor** [comment]
Quick repy: have a .tex document ready. Add cite of entry1. Navigate to entry1 in JabRef. In .tex add cite to entry2. Save. In JabRef go to entry2. Check citations tab. Should be empty. Click on refresh, then the cite in the .tex should be shown.

entry1 and entry2 need to be created in JabRef.

I think, ChatGPT can generate you a .tex document if you are unware of LaTeX.

No need for a full tex installation since JabRef parses .tex in this case.

Automated tests: Difficult one. You can try with TestFX. Huge effort as we dont have good UI test examles. General testing hints are available at https://devdocs.jabref.org/code-howtos/testing.html

**Comment by AbdAlRahmanGad** [comment]
@koppor Hi, since I think the assignee is not working on this issue anymore, can I work on this issue?

**Comment by ThiloteE** [comment]
Yes @AbdAlRahmanGad, I will assign you.
