### ISSUE TITLE
Compilation error due to missing files

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#1059]
I wanted to have a look at [issue 1051](https://github.com/JabRef/jabref/issues/1051) myself and forked this repository. Unfortunately, there are 3 missing classes that are imported from `net.sf.jabref.logic.search.rules.GrammarBasedSearchRule` that I cannot locate anywhere:

```
import net.sf.jabref.search.SearchBaseVisitor;
import net.sf.jabref.search.SearchLexer;
import net.sf.jabref.search.SearchParser;
```

When I look at the class structure in the latest jar snapshot of jabref, these 3 classes are indeed located in the `net.sf.jabref.search` directory. Although looking at the [master branch in the repository](https://github.com/JabRef/jabref/tree/master/src/main/java/net/sf/jabref), this directory does not exist.

Am I missing something obvious or did someone forget to add this directory to the repo?

**Comment by koppor** [comment]
Thank you for your interest! Did you follow
https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace?
Especially the part with gradlew generateSources? :innocent:

**Comment by Siedlerchr** [comment]
I recommend running gradlew eclipse. Sets up the workspace as Eclipse
Project

2016-03-30 7:58 GMT+02:00 Oliver Kopp <notifications@github.com>:

**Comment by halirutan** [comment]
@koppor Thank you for your reply. I probably was confused by the line

> If you use IntelliJ: No extra setup is required

After running `gradlew generateSources` the missing sources were generated. I never worked with `gradle` so far and since the initialization procedure of the project took very long, I thought everything was already set up.

Another follow-up question: The sources compile fine but when I run `net.sf.jabref.JabRefMain` from inside IDEA by creating a new `Application` run configuration, the jabref window does not open. The application starts but I get an exception

```
Exception in thread "main" java.lang.ClassCastException: org.apache.logging.log4j.jcl.Log4jLog cannot be cast to org.apache.commons.logging.impl.Jdk14Logger
	at net.sf.jabref.JabRef.setupLogHandlerForErrorConsole(JabRef.java:173)
	at net.sf.jabref.JabRef.start(JabRef.java:111)
	at net.sf.jabref.JabRefMain.main(JabRefMain.java:8)
```

I'm using IDEA Ultimate 2016.1, Java 1.8, Ubuntu 14.04

**Comment by koppor** [comment]
Can any of the IntelliJ users of @JabRef/developers comment on that? - Maybe we need to refine https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace for IntelliJ ^^.

**Comment by matthiasgeiger** [comment]
Yeah... was already answering ;-)

For me starting JabRef from within IntelliJ works.

This problems should not occur if you import the project based on the gradle build. ("File" -> "Open.." -> select the `build.gradle` file in the JabRef folder)

If you have already done that, maybe refreshing the gradle project ("View" -> "Tool Windows" -> "Gradle" - Hit the "reload" button in the gradle view) might help.

**Comment by tobiasdiez** [comment]
Do you start JabRef with `Use classpath of module: JabRef_main` under the Run Configurations?
Attached you can find my run configuration, rename it to an xml file and put it in `.idea\runConfigurations` and it should work. 
[JabRef_Main.txt](https://github.com/JabRef/jabref/files/197139/JabRef_Main.txt)

**Comment by halirutan** [comment]
@matthiasgeiger Refreshing/Reloading the gradle project fixed the issue. As far as I can see the `log4j-jcl-2.5.jar` was removed. I am now able to start JabRef by either using Gradle->Tasks->run or using my original IDEA run configuration.

@tobiasdiez Yes, I had the same configuration as you have. It seems that refreshing the gradle project was the underlying issue.

I'm not sure if some of the discussion here should be put as small sentence in the documentation to help further users.

Thank you all for the comments!
