### ISSUE TITLE
Problem reading the RPM header

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#10603]
### JabRef version

5.11 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

openSUSE Tumbleweed WSL2

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download JabRef 5.11 RPM from https://www.fosshub.com/JabRef.html?dwl=jabref-5.11-1.x86_64.rpm 
2. Attempt to install with zypper
`> sudo zypper install jabref-5.11-1.x86_64.rpm` 
`Problem reading the RPM header of JabRef-5.11-1.x86_64.rpm. Is it an RPM file?` 
`No valid arguments specified.`
4. Download JabRef 5.12 RPM from https://builds.jabref.org/main/jabref-5.12-1.x86_64.rpm
5. Attempt to install with zypper
`> sudo zypper install jabref-5.12-1.x86_64.rpm`
`Problem reading the RPM header of JabRef-5.12-1.x86_64.rpm. Is it an RPM file?` 
`No valid arguments specified.`
6. Create a directory for RPMs (I used `~/.rpm`), according to the [instructions here](https://forums.opensuse.org/t/zypper-wont-install-local-rpms/135381) for installing local RPMs.
7. Add the directory as a repository (I used Yast in the terminal for this)
8. Try again, this time successfully, to install JabRef 5.11
`>sudo zypper in jabref-5.11-1.x86_64.rpm`
`Loading repository data...
Reading installed packages...
Resolving package dependencies...`
`The following package is going to be upgraded:
  jabref`
`1 package to upgrade.`
`Overall download size: 210.5 MiB. Already cached: 0 B. After the operation, additional 26.0 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y`

If this is an openSUSE issue, or not at issue at all -- I don't know how RPMs work -- then maybe specific instructions for openSUSE could be added to the JabRef installation instructions.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ryan-carpenter** [comment]
> Can you run `zypper info` on the terminal to check what version are you running?

I have upgraded my operating system since I submitted this issue and I am not sure how to look up the previous zypper version. However, I ran `sudo zypper install jabref-5.11-1.x86_64.rpm` in the `/opt` directory using the currently installed `zypper 1.14.66-1.1` and got the same error message as before.

I have not tested the rpm's checksum, but a corrupt file seems unlikely since I had the same error (previously) with JabRef `5.11. and `5.12` and because the installation succeeded when I started from the `~/.rpm` directory instead of `/opt`.

I suggest adding a line for openSUSE to the [JabRef Installation Guide](https://docs.jabref.org/installation). I was unaware until recently that I could install an rpm with zypper, and I was also unsure if the JabRef rpm was expected to work on openSUSE. Previously, I had JabRef `5.10` installed as a flatpak and wanted to make the browser extension work. Learning how to install the rpm was quickest and preferred solution for me.

**Comment by HoussemNasri** [comment]
>  I did not want to edit the documentation myself until I knew if zypper was, in fact, the 'right' way to do the installation and if there were other considerations to include.

I think `zypper install` should work, regardless of whether it is the best practice for installing RPMs or not. I'll create an issue in the user documentation repository and close this one.
