### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by Brutus11111** [JabRef/jabref#10639]
### JabRef version

5.11 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Arch

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

go to:

www.jabref.org
builds.jabref.org

Issued On	Tuesday, May 9, 2023 at 2:00:00 AM
**Expires On	Friday, November 10, 2023 at 12:59:59 AM**

That means I can't upgrade to 5.12 without disabling security. 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Thanks for the hint. We will fix this asap. Seems like the auto renew didn't work.

**Comment by koppor** [comment]
Should be working again.
