### ISSUE TITLE
Importer for Pubmed nbib format

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1063]
An importer for Pubmed nbib format would be a nice addition to the importers.
As an example, see http://www.ncbi.nlm.nih.gov/pubmed/23633646.
Also see #510.

**Comment by Siedlerchr** [comment]
At least for their XML fomat there is a simple XSL-Script:
https://github.com/gui11aume/starcode/blob/master/doc/pubmed2bibtex.xsl

And I found a kind of Reference-Field-List for the nbib-Medline Format and their meanings:
https://www.nlm.nih.gov/bsd/mms/medlineelements.html
Together with this table:
http://www.ncbi.nlm.nih.gov/books/NBK3827/table/pubmedhelp.T.medline_display/?report=objectonly

**Comment by stefan-kolb** [comment]
Hm, we got a Medline fetcher. Whats the difference between our Medline/Medline Plain and nbib?

**Comment by tschechlovdev** [comment]
Medline Plain is a subset of nbib. So every field of Medline Plain is also a field of nbib. But not every nbib field is in the Medline Plain format. I will prepare a PR, where I add the fields to the Medline Plain Importer.
After that I will take care of Medline and nbib.

**Comment by tschechlovdev** [comment]
I've added the nbib fields to Medline and MedlinePlain. So I think this issue can be closed now.
