### ISSUE TITLE
Build fail: name clash

### ISSUE THREAD

**Issue by linsui** [JabRef/jabref#10647]
### JabRef version

5.11 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

```
> Task :compileJava
/build/source/src/main/java/org/jabref/gui/autocompleter/AutoCompletionTextInputBinding.java:45: error: name clash: removeEventHandler(EventType<E#1>,EventHan
dler<? super E#1>) in EventTarget and removeEventHandler(EventType<E#2>,EventHandler<E#2>) in AutoCompletionBinding have the same erasure, yet neither overrid
es the other
public class AutoCompletionTextInputBinding<T> extends AutoCompletionBinding<T> {
       ^
  where E#1,E#2 are type-variables:
    E#1 extends Event declared in method <E#1>removeEventHandler(EventType<E#1>,EventHandler<? super E#1>)
    E#2 extends Event declared in method <E#2>removeEventHandler(EventType<E#2>,EventHandler<E#2>)
```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
5.11 requires JDK21, but **JavaFX 20**.

5.12 works with javafx 21 
The latest main is working with JavaFX 21 build again: 
Refs https://github.com/JabRef/jabref/pull/10627

**Comment by linsui** [comment]
Thanks!
