### ISSUE TITLE
Entry creation from DOI does not recognize URL encoding, but "get bibliographical data" does

### ISSUE THREAD

**Issue by DominikStiller** [JabRef/jabref#10648]
**Update** See below. It is now about the "Entry from Id" dialog!

### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.12--2023-11-16--85cd85f, Windows 10 Pro 22H2

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Find a DOI that contains URL-encoded characters such as %3C (<) or %3E( >). My example DOI: https://doi.org/10.1175/1520-0493(2002)130%3C1913:EDAWPO%3E2.0.CO;2
2. Add a new entry from the DOI.
Result: It fails.
![import_dialog](https://github.com/JabRef/jabref/assets/1486577/903b967b-102d-47b1-8288-87c466723b66)

3. Add an empty entry.
4. Enter the DOI in its DOI field.
5. Use the "get bibliographical data from DOI" function.
Result: It works.
![lookup](https://github.com/JabRef/jabref/assets/1486577/83249418-55a8-4c7f-bfd5-8b732b465c77)

**Comment by DEEPAM-KUMAR** [comment]
Hi @Siedlerchr can I work on this bug ?

**Comment by rahul-s-bhatt** [comment]
Hey @DEEPAM-KUMAR are you still working on this?

**Comment by Siedlerchr** [comment]
Seems like nobody is working on this issue

**Comment by randhirrkumar** [comment]
Hi @DominikStiller,
Actually the issue was in the URL which you are passing. You can pass ID. It will pick up the article and work properly.
I have attached 2 screenshots for your reference.
![Screenshot (309)](https://github.com/JabRef/jabref/assets/155938629/48a2b393-c6a7-40af-8f50-7be5453be24f)
![Screenshot (310)](https://github.com/JabRef/jabref/assets/155938629/2e3ee90a-82e9-4267-a37d-9ed312102230)

**Comment by DominikStiller** [comment]
@randhirrkumar, I did not realize that, thank you! That's a workaround at least.

Still the behavior is inconsistent because it is generally possible to pass a URL to the new entry dialog, just not one with URL-encoded characters. So there is still a bug to be fixed here.

**Comment by koppor** [comment]
Implementation steps:

1. Add test to `org.jabref.model.entry.identifier.DOITest`
2. Fix `org.jabref.model.entry.identifier.DOI` to urldecode URL before interpreting

**Comment by MashidAkhtar** [comment]
Hey @koppor, can you please elaborate a few on this "Fix org.jabref.model.entry.identifier.DOI to urldecode URL before interpreting"

**Comment by koppor** [comment]
@MashidAkhtar 

I meant: At org.jabref.model.entry.identifier.DOI#DOI, right after `trimmedDOI` normalize the URI using the answer at https://stackoverflow.com/a/61208742/873282. Please handline `null`s, too. Because the doi parameter might not be an URL

**Comment by KonstantinosChanioglou** [comment]
Hi. I would like to wotk on this issue. Could you assign this to me? Thanks in advance!

**Comment by koppor** [comment]
Issue not fully fixed by https://github.com/JabRef/jabref/pull/11036, missing:

"New entry from Id" is not fixed.

![Import](https://github.com/JabRef/jabref/assets/25669636/30f00779-1fae-442f-b082-5c8b0e79a121)

**Comment by subhramit** [comment]
Hi, I'd like to be assigned to this.

**Comment by koppor** [comment]
@subhramit This is kind of detective work to understand how JabRef treats Strings coming from there.

**Comment by subhramit** [comment]
> @subhramit This is kind of detective work to understand how JabRef treats Strings coming from there.

Yes, I finally got it, but it was extremely hard to debug. Many hours of breakpoint after breakpoint and turns out that the issue was because of a non-matching regex which was truncating the trailing ";2".
Will write a detailed analysis and create a PR soon.
