### ISSUE TITLE
Why did you remove fields for year and month?

### ISSUE THREAD

**Issue by edmundfo** [JabRef/jabref#10679]
In Jabref 5.10 several entry types (e.g. mastersthesis) have "Date" as a required field, but I cannot find year and month even among the optional fields. I don't understand this and it frustrates me. For many sources no exact date is provided; the only information available is the year and the month. Therefore I think these fields should be easily available, so that I don't have to invent an artificial publication date, which most likely is wrong.

**Comment by Siedlerchr** [comment]
You probably have biblatex mode enabled. In library properties you can change to Bibtex and year and month should be available again. 

Date is considered the successor of year and month in biblatex

**Comment by ThiloteE** [comment]
JabRef follows bibtex and biblatex standards closely. If you wish the biblatex standard were different, I suggest to open an issue at their repository. Closing this.
