### ISSUE TITLE
Freeze when GNOME keyring is not installed

### ISSUE THREAD

**Issue by linsui** [JabRef/jabref#10673]
### JabRef version

5.11 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

NixOS 24.05

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Uninstall GNOME keyring. Then open Jabref options. Freeze.

```
ERROR: Cloud not acquire a prompt.: org.freedesktop.secret.errors.NoSuchObject: /org/freedesktop/secrets/prompt/870bc57feddd44eb90b2e76d3b8621db
	at secret.service@1.8.1-jdk17/org.freedesktop.secret.Prompt.prompt(Prompt.java:41)
	at secret.service@1.8.1-jdk17/org.freedesktop.secret.Prompt.lambda$await$0(Prompt.java:63)
	at secret.service@1.8.1-jdk17/org.freedesktop.secret.handlers.SignalHandler.await(SignalHandler.java:144)
	at secret.service@1.8.1-jdk17/org.freedesktop.secret.Prompt.await(Prompt.java:62)
	at secret.service@1.8.1-jdk17/org.freedesktop.secret.Prompt.await(Prompt.java:80)
```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
Filed upstream - https://github.com/javakeyring/java-keyring/issues/96

**Comment by koppor** [comment]
@linsui Is there a (kind of) minimal NixOS configuration to work on? I am new to NixOS (using it now and then for a few hours) and have a mixed setup of Flake and Homemanager and stuff (based on https://nixos-and-flakes.thiscute.world/other-usage-of-flakes/the-new-cli), but it totally feels like a mess - and I am not sure if I will be able to replicate (I am on GNOME in NixOS)

```nix
  services.xserver.desktopManager.gnome.enable = true;
```

**Comment by linsui** [comment]
Here is a minimal flake.nix with minimal GNOME and jabref

<details>

```
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  outputs = { self, nixpkgs }: {
    nixosConfigurations.test = nixpkgs.lib.nixosSystem {
      modules = [
        ({ config, pkgs, lib, ... }: {
          users.users.test = {
            isNormalUser = true;
            password = "12345678";
          };

          services = {
            xserver = {
              enable = true;
              desktopManager.gnome.enable = true;
              displayManager.gdm.enable = true;
              xkb.layout = "us";
              excludePackages = [ pkgs.xterm ];
            };

            # Disable some services enabled by GNOME
            gnome = {
              tracker.enable = false;
              tracker-miners.enable = false;
              rygel.enable = false;
              gnome-online-accounts.enable = false;
              gnome-online-miners.enable = lib.mkForce false;
              gnome-keyring.enable = lib.mkForce false;
            };
            avahi.enable = false;
            dleyna-renderer.enable = false;
            dleyna-server.enable = false;
            geoclue2.enable = false;
          };
          environment.gnome.excludePackages = with pkgs.gnome; [
            adwaita-icon-theme
            gnome-backgrounds
            gnome-bluetooth
            gnome-color-manager
            gnome-control-center
            gnome-shell-extensions
            gnome-themes-extra
            baobab
            evince
            gnome-disk-utility
            file-roller
            epiphany
            gnome-clocks
            gnome-logs
            gnome-system-monitor
            nautilus
            yelp
            totem
            geary
            gnome-backgrounds
            gnome-characters
            gnome-weather
            gnome-maps
            simple-scan
            gnome-contacts
            gnome-calendar
            gnome-calculator
            gnome-font-viewer
            gnome-music
            gnome-shell-extensions
            seahorse
            pkgs.gnome-connections
            pkgs.loupe
            pkgs.gnome-text-editor
            pkgs.snapshot
            pkgs.gnome-tour
            pkgs.gnome-user-docs
            pkgs.orca
          ];

          environment.systemPackages = with pkgs; [ jabref ];

          nixpkgs.hostPlatform = { system = "x86_64-linux"; };
          system.stateVersion = "24.05";
        })
      ];
    };
  };
}
```

</details>

You can run it with `nix --extra-experimental-features flakes run .#nixosConfigurations.test.config.system.build.vm -- -m 4G`.

But I can't reproduce this problem on JabRef 5.13 so maybe it has been fixed somehow.

**Comment by Siedlerchr** [comment]
Thanks for the feedback @linsui  Did you encounter this issue again or is it still solved? Otherwise we would close this issue and reopen it if the issue persists

**Comment by linsui** [comment]
I thought it's solved somehow, thanks!

**Comment by koppor** [comment]
@linsui What would help nevertheless would be a `Vagrantfile` for a NixOS VM. I made some for Ubuntu and Fedora. (https://github.com/JabRef/jabref/tree/main/scripts/vms) 

NixOS could be easy, but IDK. Maybe, you have some time and energy for that?

**Comment by linsui** [comment]
I'm not familiar with vagrant and I don't know ruby. :shrug:

**Comment by koppor** [comment]
> I'm not familiar with vagrant and I don't know ruby. :shrug: 

Me neither 😅.

Just in case you have some time and want to accept that challenge. I know, this is not a task for minutes. I spend hours tk o create https://github.com/JabRef/jabref/tree/main/scripts/vms. The challenge was neither VirtualBox, nor Vagrant nor Ruby. It was to find out the right commands to setup the operating system. Example: https://github.com/JabRef/jabref/blob/eb16c330d87ea3b59ba2b1d0eb818b3ee5cda632/scripts/vms/ubuntu/Vagrantfile#L31

I was just thinking you maybe know the commands to setup it and could share them in a reusable way.

No worries though, was just an idea to offer some point of support for JabRef so that the developers gain time to work on something else. Its a free time project for all of us and should create joy or new knowledge! 💪🎉
