### ISSUE TITLE
Window "Open library error" too large for the screen

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#10674]
### JabRef version

5.11 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I open a large bib file with many errors in the citation keys, the window that pops up (Open library error) is larger than the screen.  I can press enter, to disregard the screen, but then I cannot see which entries were skipped. Would it be possible to make the popup window fit within the screen (with a scroll bar)? Note that I also cannot move the pop up window as the header of the window is also above the screen edge.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Interesting. What errors in citationkeys?
Could you give us an example entry that is erroneous?
Also, could you a screenshot of the dialogue?

**Comment by Siedlerchr** [comment]
Thanks for the screenshot, totally agree with you, makes it unusable.
