### ISSUE TITLE
DOI Lookup using CrossRef

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#107]
CrossRef allows DOI lookup using an XML query. 
For citations lacking a DOI, a lookup could be done automatically.
https://github.com/CrossRef/rest-api-doc

An existing DOI is very helpful for our PDF auto download feature, as we can identify the correct PDF more accurately than by title queries etc. (See #101)

**Comment by koppor** [comment]
Do we need [PDF Inspector](https://github.com/Docear/PDF-Inspector) for that?

**Comment by stefan-kolb** [comment]
Nope, it's a normal fetcher on CrossRef

**Comment by stefan-kolb** [comment]
We should add a button to the DOI field to resolve the DOI. Currently one can only follow the DOI inside the main table and only if no Url is present. If we want to add a action to retrieve the Doi it is crucial to be able to check if the DOI is correctly retrieved.

**Comment by koppor** [comment]
PDF Inspector in combination with that fetcher could be a nice addon or replacement for the PDFContentImporter. - First guess the title of the PDF using PDF Inspector and then fetch the data using the title and the CrossRef fetcher?
