### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by zWhdmB5T** [JabRef/jabref#10730]
Thank you!

Thank you for your project and software!

Thank you for maintenance in the past and in the future!

Kind regards and season's greetings!

**Comment by calixtus** [comment]
Thank you too for using JabRef, very nice for you season greetings, as we see, some people actually like what we are doing. :smiling_face_with_tear: I am closing the issue now. We appreciated it.

**Comment by koppor** [comment]
@zWhdmB5T Thank you so much - you can give back something if you want: https://docs.jabref.org/contributing
