### ISSUE TITLE
RIS import not working for journal title

### ISSUE THREAD

**Issue by herrschaftsseitn** [JabRef/jabref#1074]
JabRef version 3.2/2.10/ and earlier on Windows 7/Ubuntu 14.04

Steps to reproduce:

1. import a RIS file from Scopus into a *bib database
2. check for journal/booktitle
3. the title of the journal is imported as the book title

See attached two examples of RIS files from Scopus and Sciencedirect for the same article. In addition the bib-database with both imported. The import from ScienceDirect works fine, the one from Scopus needs to be edited for the journal. 

Hope it is repcoducible and one finds an explanation/solution. Since I'm using mainly Scopus, it would save tons of manual editting. 

[SC vs SD.zip](https://github.com/JabRef/jabref/files/199000/SC.vs.SD.zip)

**Comment by koppor** [comment]
Refs #817

**Comment by tschechlovdev** [comment]
When I see it right, then it's a problem from Scopus. Because in the RIS File form scopus the journal title is in the field T2, which is the field for the "second title". In Sciencedirect it is the field JO, which stands for the journal title. In JabRef the T2 field is the field "booktitle", which is misleading. So what we could do is change the field to second title, instead of booktitle. But this won't solve your problem since scopus is exporting the journal title as second title.

**Comment by herrschaftsseitn** [comment]
Yes, that äs basically true. 
What I don't understand is the exakt definition of the RIS-file format, i.e. is the Scopus or the ScienceDirect mode of export correct. So does Wikipedia [1] state that J2 would be correct for the journal title; similar the documentation at Thomson Reuters [2]. And thet would say that Scopus is the correct way how to use it. 
Since it is obvious that there exist different definitions for export, would it be an option to create a mapping that can be edited by the jabref user? But I have no idea how easy/complicated it would be to implement this. 

[1] https://en.wikipedia.org/wiki/RIS_%28file_format%29
[2] http://refman.com/sites/rm/files/m/direct_export_ris.pdf

**Comment by tschechlovdev** [comment]
This should be fixed in #2028. The journal title from a scopus file should now be imported as journal title.
So I think this can be closed now.

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master.
