### ISSUE TITLE
missing save button

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#10746]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.13--2024-01-03--bd92577 Linux 6.6.8-200.fc39.x86_64 amd64  Java 21.0.1  JavaFX 21+31

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. change something in a `Library`
2. close the `Library`

I get a window that tells me that something has changed, but I cannot click any button (cancel, save, etc).

### Appendix

![Screenshot from 2024-01-03 21-12-26](https://github.com/JabRef/jabref/assets/20518297/9d0ed1e0-0586-4a4b-bb40-5cff06e735e2)

**Comment by Siedlerchr** [comment]
For me it's there, so I guess it has something to do with the window size not being correct #10729

**Comment by ilippert** [comment]
fixed with
JabRef 5.13-PullRequest10747.27--2024-01-03--4828fd6
Linux 6.6.8-200.fc39.x86_64 amd64 
Java 21.0.1 
JavaFX 20+19
