### ISSUE TITLE
Crash 5.12 Mac when adding entry by DOI

### ISSUE THREAD

**Issue by jeroenvanzeeland211** [JabRef/jabref#10789]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download and install 5.12 (with pkg) on MacOS Sonoma (14.2.1 (23C71))
2. Open existing library .bib and add "new entry"
3. In "Select entry type" select ID type "DOI" and enter a DOI (like so: https://doi.org/10.1038/s41586-018-0637-6). 
4. JabRef crashes <see log below>

### Appendix

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               JabRef [9082]
Path:                  /Applications/JabRef.app/Contents/MacOS/JabRef
Identifier:            JabRef
Version:               5.12 (5.12)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-15 10:53:56.6834 +0100
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Anonymous UUID:        23BB1CF5-6843-EE9D-26AE-2535FD4D9C4A

Sleep/Wake UUID:       9A97213F-D604-4E65-9946-5046051AF3AD

Time Awake Since Boot: 19000 seconds
Time Since Wake:       9648 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x154C35A40)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [9082]

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x154C35A40)

**Comment by Siedlerchr** [comment]
Can you please try the latest development version 5.13? https://builds.jabref.org/main/
