### ISSUE TITLE
BibTextImporter - No encoding specified in importEntries

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1080]
While doing #1079  I noticed that there is an Encoding issue when running gradlew check from commandline in Windows. The specified line is the following in `BibtexImporter` where only default Charset is used for the Inputstreamreader.
However, I was not sure if I can change it  safely  to UTF8 or if this would create problems.

````java
    public List<BibEntry> importEntries(InputStream in, OutputPrinter status)
            throws IOException {
        ParserResult pr = BibtexParser.parse(new InputStreamReader(in));
  ParserResult pr = BibtexParser.parse(new InputStreamReader(in));
````

**Comment by lenhard** [comment]
Thanks for opening this issue. I often experienced the same problem, but did not follow it up.

In 312fc6f3465554d86d28cb129058bd80feca0dd8 I modified the `BibtexImporter` to use the default encoding set in the preferences, as other importers do. In a clean install, the default encoding is `UTF_8`. The commit fixed the problem for me, but if it persists for others, we could modify the preferences in `BibtexImporterTest` to be 100% sure it uses `UTF_8`.

Does it work for you @Siedlerchr ? If so, please close this issue.

**Comment by koppor** [comment]
Related: https://github.com/JabRef/jabref/pull/515#issuecomment-164766590 and #558

**Comment by stefan-kolb** [comment]
Whats the current status here?

**Comment by lenhard** [comment]
@stefan-kolb This is waiting for confirmation from @Siedlerchr

**Comment by Siedlerchr** [comment]
If you have tested it and it works then it's okay for me. 
Otherwise I will look at it by tomorrow.

**Comment by lenhard** [comment]
It is indeed working for me, but an additional check by someone else never hurts :) It is sufficient to check if there are no more encoding related test failures in your windows command line on current master.

**Comment by Siedlerchr** [comment]
@lenhard  Will check the current master now.

**Comment by Siedlerchr** [comment]
@lenhard  :+1:  
There is one thing more, that is the BibDatabaseWriterTest, it always failed for me in roundtrip
The problem is, the complex.bib uses a UNIX Line ending (\n), while on windows it should be \r\n.
The StringWriter and the BibTexWriter uses Globals.Newline, which is on windows \r\n.

This is not a big problem for me.

**Comment by simonharrer** [comment]
Closing this as the fix is conformed twice.
