### ISSUE TITLE
App crashing while loading the .bib data

### ISSUE THREAD

**Issue by GajendraBN** [JabRef/jabref#10802]
### JabRef version

5.12 (latest release)

### Operating system

macOS

### Details on version and operating system
Macbook air with M2 chip

_No response_

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Export literature files from the different system
2. Then import the exported library to the newly installed Jabref on Mac os
3. It loads perfectly but if you click on any file it will crash and need to reopen and all previous files are gone.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here

Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
Timeout while waiting for app reactivation
No open database detected
Unable to parse version 14.2 to a codename.
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Resource "" not found.
Resource "" not found.
Issue on GitHub successfully reported.
Log copied to clipboard.

</details>

**Comment by Siedlerchr** [comment]
Hm this is odd. Can you test with the 5.13 dev from here ? https://builds.jabref.org/arm64mactest/

**Comment by gajendraLUH** [comment]
This version working perfectly. Thank you
