### ISSUE TITLE
Export to MS Office 2007 (*.xml) of @electronic and @online records *mistakenly duplicates* BibTeX 'Title' to  MS Office 'Publicationtitle' field

### ISSUE THREAD

**Issue by balanco** [JabRef/jabref#10807]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11 (current)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

_One-sentence summary of the issue:_

JabRef `Export` to `MS Office 2007 (*.xml)` of BibTeX records of type `@Electronic` and `@Online` mistakenly _duplicates_ the content of the `Title` field to the MS Office `Publicationtitle` field in the exported XML file: it should _not_ do that (this issue does _not_ exist for other types, e.g., `@Book`)

_Steps to reproduce the behavior:_

1. In JabRef, allocate a new library and copy-paste this minimal BibTeX record:

> @Electronic{Author,
>   author  = {Some Author},
>   title   = {The Title},
>   url     = {https://somewhere.net/example/address},
>   urldate = {2024-01-19},
> }

2. `File` -> `Export` this record as type `MS Office 2007 (*.xml)` into a file `test.xml`

3. The exported file "test.xml" mistakenly contains _both_, a "Title" and a "Publicationtitle" field (highlighted in **_bolditalic_** in the following file dump):

> <?xml&nbsp;version="1.0"&nbsp;encoding="UTF-8"&nbsp;standalone="no"?>
> <b:Sources&nbsp;xmlns:b="http://schemas.openxmlformats.org/officeDocument/2006/bibliography"&nbsp;xmlns="http://schemas.openxmlformats.org/officeDocument/2006/bibliography"&nbsp;SelectedStyle="">
> &nbsp;&nbsp;&nbsp;&nbsp;<b:Source>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:BIBTEX_Entry>electronic</b:BIBTEX_Entry>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:SourceType>ElectronicSource</b:SourceType>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**_<b:Title>The&nbsp;Title</b:Title>_**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:Tag>Author</b:Tag>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:URL>https://somewhere.net/example/address</b:URL>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:YearAccessed>2024</b:YearAccessed>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:MonthAccessed>January</b:MonthAccessed>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:DayAccessed>19</b:DayAccessed>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:Author>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:Author>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:NameList>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:Person>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:Last>Author</b:Last>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b:First>Some</b:First>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b:Person>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b:NameList>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b:Author>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b:Author>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**_<b:PublicationTitle>The&nbsp;Title</b:PublicationTitle>_**
> &nbsp;&nbsp;&nbsp;&nbsp;</b:Source>
> </b:Sources>
> 

To illustrate the follow-up consequences of the bug in MS Word:

4. Open a blank MS Word document

5. Load the file "test.xml" via:<ol><li> `References` -> `Manage Sources` -> `Browse…` and then</li><li>select and `Copy ->` the loaded record from the `Sources available in test` pane into the `Current List` pane and</li><li>`Close` the "Source Manager" dialog window</li></ol> (the duplicate title is already displayed in the `Preview` pane of the dialog window)

6. Insert a bibliography into the empty document, via:<ol><li>`References` -> `Bibliography`</li><li>Select the first style, `Bibliography`, offered in the pop-up menu</li></ol>

7. The inserted bibliography consists of the following record:<br> Author, S. (n.d.). The Title. _The Title_. Retrieved January 19, 2024, from https://somewhere.net/example/address<br>&nbsp;<br>Note the _duplicate_ title.

As mentioned at the beginning, the same issue exists for records of type `@Online`, but _not_ for e.g., type `@Book`.

### Appendix

Related Source Code:

File `src/main/java/org/jabref/logic/msbib/MSBibConverter.java`:

<pre>
   108	        // TODO: currently only Misc can happen
   109	        if ("ElectronicSource".equals(msBibType) || "Art".equals(msBibType) || "Misc".equals(msBibType)) {
   110	            result.publicationTitle = entry.getFieldLatexFree(StandardField.TITLE).orElse(null);
   111	        }
</pre>

(addendum 2024-01-20):
In the meantime I verified that removing the first clause `"ElectronicSource".equals(msBibType)` indeed suffices to correct the behavior (kudos to the maintainers of https://devdocs.jabref.org/ ).
I have _not_ investigated the mapping of BibTeX `@misc` to MS&nbsp;Office `Misc` mentioned in https://docs.jabref.org/advanced/knowledge/msofficebibfieldmapping (visited 2024-01-20)).

So, the patched lines just read
(File `src/main/java/org/jabref/logic/msbib/MSBibConverter.java`, lines 108ff.):
<pre>
  // TODO: currently only Misc can happen
  // 2024-01-20 balanco@github: removed condition/case "ElectronicSource".equals(msBibType)
  //    that generated MS Office bibliographic records with
  //    _duplicate_ "Title" and "Publicationtitle" fields.
  if ("Art".equals(msBibType) || "Misc".equals(msBibType)) {
     result.publicationTitle = entry.getFieldLatexFree(StandardField.TITLE).orElse(null);
  }
</pre>

&lt;EOT&gt;

**Comment by Siedlerchr** [comment]
@balanco  Feel free to create a PR
