### ISSUE TITLE
Re-download missing linked files

### ISSUE THREAD

**Issue by ror3d** [JabRef/jabref#10848]
**Is your suggestion for improvement related to a problem? Please describe.**
At my work we share a bib file among 2-3 people that we keep updated to keep track of interesting papers, but due to policy, we can't share the actual PDFs.
Trying to overcome this, we realized that if a file is downloaded, the original URL it was downloaded from is removed from the entry, so the file can't be easily redownloaded by other people using that link. Moreover, downloading it after the entry has been added seems to require manually downloading and adding it to the entry, which is not ideal.

**Describe the solution you'd like**
Downloaded files should remember where they were downloaded from, and give a way to re-download them if they are missing from the directory.

**Additional context**
I am working on a possible solution for this, I will PR when ready.

**Comment by Siedlerchr** [comment]
That sounds indeed like a good idea, mabye move the file url to the url field after downloading?

**Comment by ror3d** [comment]
> That sounds indeed like a good idea, mabye move the file url to the url field after downloading?

I will do the PR on monday, but basically what I've done is add a `sourceUrl` field to the LinkedFile structure and when the file is downloaded the url is copied there, and the `link` is set to the file's path.
