### ISSUE TITLE
Support for (biblatex) langid field in entry editor

### ISSUE THREAD

**Issue by jspitz** [JabRef/jabref#10868]
JabRef 5.12

I might have overlooked it, but I do not find the rather central `langid` field in the entry editor. This field defines the principal language of the entry, which is important for hyphenation and whether (sentence) casing is applied. There is also `langidopts` for fine-tuning (with `polyglossia`)

The field is described in http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf at section 2.2.3

In my opinion, this should go to the "Optional" tab.

**Comment by Siedlerchr** [comment]
Thanks for the suggestion. In the meantime you can configure the field under Custome entry types. 
JabRef's Standard fiels are listed here https://github.com/JabRef/jabref/blob/13870d831e5d98d27127c4f8d9ec67f199d298be/src/main/java/org/jabref/model/entry/field/StandardField.java

**Comment by jspitz** [comment]
> Thanks for the suggestion. In the meantime you can configure the field under Custome entry types.

Thanks, that's what I've done.

**Comment by Skydrite** [comment]
Hello. Can I work on this issue? Thank you!

**Comment by Skydrite** [comment]
Hey, seeing this issue in more detail, it looks to me that the only thing needed to add the 'langid' field is to add it on the StandardFields. Next, I think I will have to work on the exporter so that it exports this info. However, I'm not sure whether I need to work on the importers as well (or which of them). Is there any maintainer who would be able to discuss this with me a bit?

**Comment by koppor** [comment]
@Skydrite Just start with the StandardField. No worries about importers. They will emerge gradually. -- Also depends on https://github.com/JabRef/jabref/pull/11013/.

**Comment by koppor** [comment]
Closed by https://github.com/JabRef/jabref/pull/11049

**Comment by jspitz** [comment]
If I am not missing something, the `langid` field still is not among the optional fields of any `biblatex` entry type in JabRef 5.13. #11049 just added it to the fields known by JabRef.

So this request is actually not fully addressed.

**Comment by koppor** [comment]
@jspitz Sorry that we did not review thoroughly at https://github.com/JabRef/jabref/pull/11049

Seems, the requirements were not clear.

**The field needs to be added as optional field to all biblatex entry types**

**Comment by mag-sun** [comment]
Hi, I am a student at the Australian National University. For one of our assignments, we are tasked with working in a group to contribute to an open-source project - and I would like to be assigned to this issue. While working, our group will cross-review our code and help each other out to have the most efficient progress. Thanks so much!

**Comment by koppor** [comment]
I copy from the PDF

![Image](https://github.com/user-attachments/assets/c1a327f8-b14c-4c22-96d0-ddde78c84a2c)

![Image](https://github.com/user-attachments/assets/f26fc553-7bb0-4b11-9346-6302a31b5f73)

In the entry editor, it should be a dropdown.

@jspitz Meanwhile, you can configure the [Field contgent selector](https://docs.jabref.org/advanced/contentselector) with values you need.

**Comment by mag-sun** [comment]
Hi, I was just wondering if 'langid' should be considered independently from the existing 'language' field or not? Any guidance around how to approach this issue would be greatly appreciated!

**Comment by jspitz** [comment]
Yes, the two fields are independent. In `biblatex`, `language` means "The language(s) of the work. Languages may be specified literally or as localisation keys" (from the manual, while langid is the language used for typesetting the entry.

**Comment by mag-sun** [comment]
Hello, I have successfully integrated 'langid' as an optional field with a dropdown menu in biblatex entry types. I have drafted a PR, but am unsure if I have completely solved this issue. The selected langid shows up correctly in the BibTex source tab, but I am uncertain as to if it actually changes the formatting of the entry/if that is something covered by importers/exporters. Thanks so much!
