### ISSUE TITLE
Replacing String Constants During Copy-Paste

### ISSUE THREAD

**Issue by ankitp94** [JabRef/jabref#10872]
**Is your suggestion for improvement related to a problem? Please describe.**
While copying an entry from the library using Ctrl+C, the string constants are not exported, and there is no automatic option to replace string constants.

**Describe the solution you'd like**
An option to copy the bib entry that replaces the string constants.

**Additional context**
Suppose the .bib file is the following:

```
@String{grl = "Geophys. Res. Lett."}

@article{claudepierre:20a,
    author = {Claudepierre, S. G.},
    journal = grl
}
```

When I copy it by using ctrl+C and then paste it into my editor, the journal name continues to be `grl`, whereas the desired behavior would be `Geophys. Res. Lett.`  Thus, I would really appreciate a feature, say by an option in the list below, that allows for copying bib entry while replacing string constants.
![image](https://github.com/JabRef/jabref/assets/4333418/033a2b58-9783-4ec3-8fdf-063300c07219)

**Comment by andersblomqvist** [comment]
Hi, we are a group of university students who want to work on this issue for a week if it's possible.

We are: @andersblomqvist, @real-darth, @JXNCTED, @hanstig, @BillGatesZero

**Comment by Siedlerchr** [comment]
To fix the issue you need to understand what BibTeX Strings are and how they work, this is explained here: 
https://docs.jabref.org/advanced/strings

**Comment by koppor** [comment]
When copying a BibEntry in the clipboard, also referenced @String constants should be put into the clipboard. On paste in JabRef, it should be checked, if there are @String constants contained. If yes, add them to the library. If a string constant already exists, ignore it (and log). One could also implement a "merge dialog" which offers choosing which @String content to take. Similar to the merge entriesd dialog (e..g, triggered when pasting the same entry twice).

**Comment by Siedlerchr** [comment]
@ankitp94  The feature is now available in the latest development version
https://builds.jabref.org/main/
