### ISSUE TITLE
Non-editable user comments

### ISSUE THREAD

**Issue by ror3d** [JabRef/jabref#10870]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I am unsure of the cause for this, as a peer doesn't seem to have this problem.
1. Open the Comments tab for an entry
2. Add a comment in the bottom text-field labeled as `Comment-<username>`
3. Save the database
4. Notice that the notification about the file being edited outside JabRef appears
5. Proceed to Review the changes and to Merge them
6. Notice duplicated `Comment-<username>` field:
   ![image](https://github.com/JabRef/jabref/assets/1844478/90ccc337-b0ec-4b4c-9bd3-7b71d032c685)
7. Accept the merge
8. Notice in the Comments tab, two text fields appear for the same user with the comment repeated:
   ![image](https://github.com/JabRef/jabref/assets/1844478/f12f9264-cc1c-49cc-8811-606ac7c36223)
9. Close the database (no need to save) and open it again
10. Navigate to the comments for entry where comment was added
11. Notice two comment fields there for the same user, the content only in the second one and not editable:
   ![image](https://github.com/JabRef/jabref/assets/1844478/dad7ba56-4f87-4b2c-b2a3-2b1e607f3d9b)

### Appendix

@Article{ArticleID,

  comment-roc = {Just a test comment},
  comment-roc = {Just a test comment},

}

**Comment by Siedlerchr** [comment]
can you please test the latest development version? I can no longer reproduce the issue
https://builds.jabref.org/main/

**Comment by ror3d** [comment]
I still can reproduce it, yes.
Reproduction step 4 is also still happening, which I feel like might be part of the problem.

**Comment by LoayGhreeb** [comment]
Hi @Siedlerchr, I would like to work on this issue.

**Comment by Siedlerchr** [comment]
Sure, you're welcome to take a look at this issue

**Comment by LoayGhreeb** [comment]
Hi @ror3d, can you tell me what exactly your username is? Is it `roc` or `Roc`?

**Comment by ror3d** [comment]
Hi,

Is that the setting where the name is taken from? it doesn't feel like it is, since the field is disabled unless the "Mark new entries" checkbox is selected. If that is indeed the setting, maybe it should be always editable and made more clear that it's what is used also for the personal comments. Maybe @Siedlerchr can weigh in on that.

Anyway, in that field I have it as `Roc`.

**Comment by Siedlerchr** [comment]
> If that is indeed the setting, maybe it should be always editable and made more clear that it's what is used also for the personal comments. Maybe @Siedlerchr can weigh in on that.

I agree with you. Originally, it's intended to be used for new entries to add the owner field. Now it's also used for comment fields. This allows sharing your bib files with others and everyone has it's own comment field. It should always be editable, independent of the checkbox
@LoayGhreeb  Can you fix this as well?

**Comment by LoayGhreeb** [comment]
> @LoayGhreeb Can you fix this as well?

Sure, I'll add this to the pull request

**Comment by koppor** [comment]
Is the original issue really fixed? 😅

**Comment by ror3d** [comment]
Indeed, the issue seems to be fixed with the latest code from main. It also fixes the problem where saving after editing the comment was detected as a different program modifying the file, which I guess was a side-effect of this issue.
Thanks!
