### ISSUE TITLE
Inconsistent Escape Action

### ISSUE THREAD

**Issue by wviechtb** [JabRef/jabref#10882]
When a field is focused in the entry editor, hitting the Escape key deletes the field entry. However, in the 'Date' field, hitting Escape closes the entry editor. Not sure if there are other fields where this behaves inconsistently. In any case, it would be good if the behavior across fields would be consistent.

Actually, I find the delete action on Escape super confusing, because if the field editor is focused but no specific field, then Escape closes the entry editor (which seems quite natural). But I often accidentally delete a field entry because I did not notice that a field was focused. And one cannot Undo this deletion, which makes this behavior even more frustrating.

Is there any way to simply switch off that Escape deletes field entries and always closes the entry editor?

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/8888.

**Comment by Siedlerchr** [comment]
Fixed by https://github.com/JabRef/jabref/pull/11190

@wviechtb  please try the latest dev version
https://builds.jabref.org/main/
