### ISSUE TITLE
Add more tests to ArgumentProcessor::processArguments()

### ISSUE THREAD

**Issue by Deadlica** [JabRef/jabref#10908]
Add more tests to ArgumentProcessor::processArguments() to increase code coverage as Jacoco currently only reports about ~44% code coverage for this method.

**Comment by koppor** [comment]
Thank you for using JabRef to level up your software engineering skills!

Unfortunately, this issue does not add any functionality to JabRef and does (directly) address any issue. JabRef is used by users. We have more than 100 bugs. Any contribution should in principle support to get one of these bugs to be fixed l. I did not see any issue regarding the argument processor. Thus closing as not planned.
