### ISSUE TITLE
Structure of imports

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1091]
As discovered in #1089 there might be a problem with IntelliJ restructuring the imports vs how Eclipse does it. I just run into the same problem with #1090, so I would like to discuss here what the correct preferences for IntelliJ are. The following settings produce a somewhat satisfying result, but there are still quite a few difference to some imports in some files.
![untitled](https://cloud.githubusercontent.com/assets/5037600/14232775/2cbbfa04-f9b5-11e5-80ee-4f9743df5431.png)
.

**Comment by Siedlerchr** [comment]
I just posted this at the PR:
Maybe you could evaluate that:
http://stackoverflow.com/questions/14716283/is-it-possible-for-intellij-to-organize-imports-the-same-way-as-in-eclipse
http://stackoverflow.com/questions/11704327/intellij-idea-how-to-optimize-imports-automatically-after-each-save

**Comment by simonharrer** [comment]
We need something like checkstyle which enforces it using gradle. 

We should maybe activate checkstyle for this, making the build fail if the imports are not in order.

**Comment by bartsch-dev** [comment]
I looked through some of the source files and have noticed that there is no clear order in which the classes are imported.

Thus I think we firstly need to decide on a proper order (like alphabetically with a blank line between).

Furthermore I prefer the fully qualified Imports over the generalized ones (*).

**Comment by simonharrer** [comment]
Checkstyle checks are now in place for forcing one to remove unused imports. We can add additional checks, e.g., for the import order, BUT, we should be careful not to add to much, and only add additional checks as an evolution of the code base. See 9e9fc8c

**Comment by simonharrer** [comment]
![image](https://cloud.githubusercontent.com/assets/375693/14459902/0597da6c-00bb-11e6-84e4-b0d4d978f2d1.png)

**Comment by simonharrer** [comment]
![image](https://cloud.githubusercontent.com/assets/375693/14459998/7aeb7026-00bb-11e6-96aa-0adb1564b97e.png)

**Comment by koppor** [comment]
In Eclipse automatically generated - use `gradlew eclipse`.

![grabbed_20160412-143351](https://cloud.githubusercontent.com/assets/1366654/14460040/9a9ce88c-00bb-11e6-83e7-52a482dad3d2.png)

**Comment by simonharrer** [comment]
![image](https://cloud.githubusercontent.com/assets/375693/14460173/5113c518-00bc-11e6-89b8-e1f221001a7d.png)

**Comment by koppor** [comment]
This is solved. Do we need to post the IntelliJ configuration at https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace?

**Comment by stefan-kolb** [comment]
Did we document this in the wiki?

**Comment by koppor** [comment]
It is now added at https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace#intellij.
