### ISSUE TITLE
Add CleanupJob for removing non-existent files

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10929]
(This is https://github.com/JabRef/jabref/issues/7288#issuecomment-1521347078)

As user, I have renamed files, but JabRef still has the old links. JabRef perfectly links the new files, but also keeps the broken links. I want to have them removed.

Implement `org.jabref.logic.cleanup.RemoveLinksToNotExistentFiles`.

That class is similar to `org.jabref.logic.cleanup.MoveFilesCleanup`, but uses `org.jabref.logic.externalfiles.LinkedFileHandler#findExistingFile`. Links with `org.jabref.model.entry.LinkedFile#isOnlineLink()` do not exist in the file system, but have to kept, too.

---

When testing, please make use of JUnit's `@TempDir` or let inspire yourself with org.jabref.logic.search.DatabaseSearcherWithBibFilesTest.

**Comment by WenJJ2000** [comment]
Hi, we (@karlsb @burcukilic @muchembledMartin @linusWallin) are a group of university students who would like to work on this issue if possible!

**Comment by karlsb** [comment]
Hi! We have implemented a cleanup job for removing non-existing files but do not know when to trigger it. Should there be a new field in the "cleanup entry" under "quality" in the app menu? Or should it be triggered automatically somewhere else? Is it in the scope of this issue?

**Comment by koppor** [comment]
1. Open Chocolate.bib
2. Select all entries
3. ![image](https://github.com/JabRef/jabref/assets/1366654/c4811828-87e9-48de-ad2b-0fa07c750228)
4. "Enable field formatters"

Add the cleanup to the checklist above. Place it Above "Convert to biblatex format".

If you want, you can improve the dialog to add some grouping to all file-related points (from "Upgrade external PDF/PS links" to your new entry"
