### ISSUE TITLE
Tooltip on main table cell should show full table cell content

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10925]
When I hover on a table entry, there appears nothing:

![image1](https://github.com/JabRef/jabref/assets/320228/3e83a8fe-568e-40b6-826b-e9f796ade28b)

There should be a tool tip:

- First line: Full content of the current cell
- Second line: empty
- Third line: rendered BibTeX entry (as shown in the Preview)

BibTeX source:

```bibtex
@Article{WarnettZdun2022,
  author   = {Warnett, Stephen John and Zdun, Uwe},
  journal  = {Computer},
  title    = {Architectural {Design} {Decisions} for the {Machine} {Learning} {Workflow}},
  year     = {2022},
  issn     = {1558-0814},
  month    = mar,
  number   = {3},
  pages    = {40--51},
  volume   = {55},
  abstract = {We conducted a qualitative investigation of architectural decisions faced by practitioners and modeled current practices in machine learning. We describe a subset of the architectural decisions that were modeled, discuss uses for the model, and outline areas in which further research may be pursued.},
  doi      = {10.1109/MC.2021.3134800},
  keywords = {Computational modeling, Machine learning, Computer architecture, Quality assessment},
}
```

The second and third line should be shown only if the (new) preference is activated:

![image](https://github.com/JabRef/jabref/assets/1366654/3cd00384-aaf9-48e6-b320-34688cc05bfd)

**Comment by azatyamanaev** [comment]
Can I work on this issue?
