### ISSUE TITLE
Markdown rendering should keep {}

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10928]
JabRef has internally a field marker that marks a field as `Markdown`. `org.jabref.model.entry.field.FieldProperty#MARKDOWN`

When that field is rendered in the preview, `{}` should be kept.

Example content of a Comment:

````markdown
# test

{ test }

```javascript
function hero() {
}
```
````

![307950652-09a3c1b5-dcb5-4553-bce6-766ca5775b84](https://github.com/JabRef/jabref/assets/1366654/797c1af9-90c7-41f5-bc78-0f40f40a5099)

![307951490-65d6369a-f775-4183-89d0-371cf46cc9c1](https://github.com/JabRef/jabref/assets/1366654/ecc18051-f12c-494b-bf79-51e786b8c825)

---

This issue is more about **code reading** and understanding JabRef's archictecture. The "real" fix should be a few lines of code: Checking for the field property `MARKDOWN` and passing the field value with plain latex (and not latex free).

**Comment by LoayGhreeb** [comment]
I would like to work on this issue

**Comment by LoayGhreeb** [comment]
Hi @koppor, I did my best for solving this issue, but I don't know how to solve it. I noticed that `comment` or `abstract` use both `Markdown` and `HTMLChars` formatters. However, the `HTMLChars` formatter always deletes any curly brackets in the string. I'm not sure if this is related to the issue or not.
Could you provide a hint or guide on how to proceed?

**Comment by koppor** [comment]
Related PR: https://github.com/JabRef/jabref/pull/10942?

Currently, I think, following lines in the HTMLChars should be removed

```java
            } else if (!incommand && ((c == '{') || (c == '}'))) {
                // Swallow the brace.
```

Adapt tests.

In `.layout` files, search for HTMLChars and check where to add `RemoveBrackets` before.

Thinking more, the LaTeX command handling in HTMLChars should be removed. In the `.layout` files, `LaTeXToUnicode` should be used. - I think, `HTMLChars` will be much smaller then. HTML5 default encoding is unicode, thus `LaTeXToUnicode` is the right formatter.

**Comment by koppor** [comment]
@LoayGhreeb Any progress here? 😅

**Comment by LoayGhreeb** [comment]
I've unassigned myself and am currently working on another issue. I'll come back to this one soon if nobody else takes it.

**Comment by JEANPRBT** [comment]
You can assign me on this one if you wish !

**Comment by JEANPRBT** [comment]
I've started to read up on architecture to be able to solve this problem. In the light of this additional comment, I think I understand the following, please tell me if I'm wrong. 

> Currently, I think, following lines in the HTMLChars should be removed
> 
> ```java
>             } else if (!incommand && ((c == '{') || (c == '}'))) {
>                 // Swallow the brace.
> ```

I need to remove the above line, this should potentially solve the problem by avoiding swallowing the `{` and `}` characters. 

> Adapt tests.
> 
> In `.layout` files, search for HTMLChars and check where to add `RemoveBrackets` before.

However,  I should add the formatter `[RemoveBrackets]` in `*.layout` files to maintain the previous behavior, except for those using the `[Markdown]` formatter.

> Thinking more, the LaTeX command handling in HTMLChars should be removed. In the `.layout` files, `LaTeXToUnicode` should be used. - I think, `HTMLChars` will be much smaller then. HTML5 default encoding is unicode, thus `LaTeXToUnicode` is the right formatter.

To go further, even if it not necessarily linked to this current issue, I should remove the latex formatting from `[HTMLChars]` formatter and add the `[LaTeXToUnicode]` formatter instead to maintain previous behavior. This could lighten the code, and even solve this problem if it had not been already solved.

Is this what on had in mind @koppor ?
