### ISSUE TITLE
Custom API keys should be a table

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10926]
The UI of our preferences for Custom API keys is not that good:

![image](https://github.com/JabRef/jabref/assets/1366654/3613bfbd-fe06-4100-ba93-be7fd6c9d1ac)

I would like to have a table. We have n < 10 fetchers with API keys, thus this is not a long list.

| Catalog | Key | Use Custom Key |
| -- | -- | -- |
| Biodiversity heritage | test | [x] |
| IEEE | other | [x] |
| Science direct | my | [x] |

I also renamed "Custom" to "Use Custom Key", to make clear that the given key should be used.

**Comment by AbdAlRahmanGad** [comment]
Hi, I would love to work on this issue. Can you assign it to me?
