### ISSUE TITLE
Document Viewer: PDF shows only in half of the window size

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10934]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

mac as well

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Attach a pdf to an entry 
2. Go to View -> Open document viewer
3. Maximize the view and see that the document content is not resized properly and there is free space at the bottom

=> The document should take up all space when resized

![documentViewer](https://github.com/JabRef/jabref/assets/320228/31865a3b-d82e-44fd-8da0-2606458a993d)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by cardionaut** [comment]
Hi @Siedlerchr 
This would be my first ever contribution and I am a bit of a Java noob still.
I would love to give this issue a shot if it isn't too urgent.
I work full-time and it might take me some time to get a hang of everything.
Let me know what you think, thanks!

**Comment by ThiloteE** [comment]
Sure, thank you @cardionaut 
This is an issue that might potentially be relevant to one of our Google Summer of Code (GSoC) projects, so it would be nice having it fixed or at least having somebody play a little with the UI settings in this part of the code, which would serve as a demonstration for what is possible.
