### ISSUE TITLE
JabRef performance issues with large bib file

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1094]
JabRef version 3.x on Windows 10

Steps to reproduce:

1. Create BibTeX file with 100000 entries. (automatically generated using a ruby script)
2. Open with JabRef
3. Wait for nothing to happen for a few minutes
4. JabRef opens but is very unresponsive.

[test.zip](https://github.com/JabRef/jabref/files/202001/test.zip)

**Comment by tobiasdiez** [comment]
Well, the loading time was acceptable for me (< 1 min) but JabRef uses 2 GB of memory :). Will have a look at it.

**Comment by stefan-kolb** [comment]
- Autocompletion performance is not optimized

**Comment by simonharrer** [comment]
You could try to profile it using jvisualvm which is shipped with Java. The script which generates the bib file is available since 1edd7d3bc85c0ebdf4eb1b3f8a82420921bc53a9

**Comment by Siedlerchr** [comment]
You could also try Java Mission Control (part of jdk)
http://www.oracle.com/technetwork/java/javaseproducts/mission-control/java-mission-control-1998576.html

**Comment by tobiasdiez** [comment]
I actually plan to write a few benchmarks using [JMH](http://openjdk.java.net/projects/code-tools/jmh/). So we have a reliable way to later gauge if some changes improve the performance or not.

**Comment by stefan-kolb** [comment]
For me, save as takes ages when selecting a crowded folder. Dunno if this is somehow related to JabRef or only Java in general.

**Comment by koppor** [comment]
The first benchmarks have been done in #1103.

**Comment by stefan-kolb** [comment]
Close this for now? We got significantly better on the major points didn't we?

**Comment by simonharrer** [comment]
There is still room for improvement. But as far as I know it is good enough at the moment.
