### ISSUE TITLE
Uncaught exception when closing a library that does not exists

### ISSUE THREAD

**Issue by martinctl** [JabRef/jabref#10948]
### JabRef version

5.12 (latest release)

### Operating system

macOS

### Details on version and operating system

Sonoma 14.2.1

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open JabRef
2. Do not create or open a library
3. Press cmd + w (ctrl + w) or File -> Close library

<img width="236" alt="Screenshot 2024-02-29 at 11 45 44" src="https://github.com/JabRef/jabref/assets/91327170/7b375c48-7ae9-403f-984a-4b2e4ff4c659">

### Appendix

<img width="1278" alt="Screenshot 2024-02-29 at 11 46 00" src="https://github.com/JabRef/jabref/assets/91327170/d2fbc988-3aa8-44c4-98c8-b78b6fa8f44d">

<details>

<summary>Log File</summary>

```
ERROR: Uncaught exception occurred in Thread[#29,JavaFX Application Thread,5,system]: java.lang.NullPointerException: Cannot invoke "org.jabref.gui.LibraryTab.requestClose()" because "libraryTab" is null
```

</details>

**Comment by Siedlerchr** [comment]
Can you please try the latest development version? If I remember correctly this should be fixed already
You can use the https://builds.jabref.org/main/ arm64 version

**Comment by koppor** [comment]
Related https://github.com/JabRef/jabref/issues/4795 (dplicate of https://github.com/JabRef/jabref/issues/4665)

**Comment by martinctl** [comment]
I have tested the latest development version on mac and Windows 11 and it does not seems to be fixed

**Comment by martinctl** [comment]
Also I would like to be assigned to this issue if you think it's fine for a first time code contribution
