### ISSUE TITLE
Store Citation Relations in an LRU cache

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#10958]
## Problem
The current implementation caches the related entries (references and citations) as soon as they are fetched after visiting the Citation Relations Tab. The fetched entries are held cached in RAM until JabRef is restarted. This approach unnecessarily bloats the computer memory and could result in an out-of-memory exception in special circumstances. 

## Suggested solution
Instead of caching all entries, we could cache the citation relations of the top N entries that are most likely to be visited in the future. The Least Recently Used (LRU) Cache operates on the principle that the data most recently accessed is likely to be accessed again in the near future.

## Implementation details
- You don't have to write an LRU cache from scratch, JabRef depends on a LOT of libraries, some of them provide an LRU cache already, so try to use that if possible.

**Comment by cardionaut** [comment]
I'd love to give this a shot!

**Comment by HoussemNasri** [comment]
@cardionaut, Sure go ahead, you're assigned.

**Comment by cardionaut** [comment]
@HoussemNasri Is there a large example .bib I could download from anywhere for testing purposes?
I assume the RAM effects are only visible for larger collections.

**Comment by Siedlerchr** [comment]
@cardionaut  We have a generator script `bib file generator` under the scripts directory

**Comment by cardionaut** [comment]
@Siedlerchr Thanks!
These dummy entries won't have any References or Citations though, right?

**Comment by HoussemNasri** [comment]
> Is there a large example .bib I could download from anywhere for testing purposes?
> I assume the RAM effects are only visible for larger collections.

If you're looking for examples of BibTeX libraries you can have a look at [testbib](https://github.com/JabRef/jabref/blob/54813e5938ea794b91901f42d049e0acfd74442c/src/test/resources/testbib/testjabref.bib). The problem could be observable when using a large library run on a low-end computer over a long period of time. So it's more of a small optimization that would only benefit a small number of users. Overall, I don't think you have to reproduce the issue to fix it. You can launch the debugger and observe the number of allocated citations/references in the cache over time, but it's up to you.

**Comment by koppor** [comment]
@cardionaut You are right, the generated libraries do not help here. https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/Chocolate.bib also does not help. - What I did: Query dblp for "Kopp", imported the 100 entires. Then I quiery "Breitenbücher", added 100 other entries - and then went through. OK, I got [http 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429), because of some API rate limits IMHO.
