### ISSUE TITLE
Add TexWorks icon

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10970]
Follow-up to https://github.com/JabRef/jabref/pull/10953/

See https://github.com/JabRef/jabref/pull/10447 and `org.jabref.gui.icon.JabRefMaterialDesignIcon` how it works.

**Comment by Siedlerchr** [comment]
https://github.com/JabRef/jabref/blob/84463e7fba930d2c44e7cfb4421826b9926e0dc0/docs/code-howtos/custom-svg-icons.md
