### ISSUE TITLE
Add support for parsing .lnk files for TeXworks

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10977]
(Follow-up to https://github.com/JabRef/jabref/pull/10953)

JabRef currently, doesn't find TeXWorks when MiKTeX is installed on Windows.

In the prefs we have some autodetect logic https://github.com/JabRef/jabref/blob/94928dd8e0811e962be8c7ccf7145835dbe969a7/src/main/java/org/jabref/preferences/JabRefPreferences.java#L545 

On my machine, the app can be found via the following steps:

1. Open `%APPDATA%\Microsoft\Windows\Start Menu\Programs\MiKTeX\TeXworks.lnk`
2. Read `Target` from it. On my machine: `C:\MiKTeX\miktex\bin\x64\miktex-texworks.exe`

Use the [mslinks library](https://github.com/DmitriiShamrikov/mslinks?tab=readme-ov-file#mslinks) for parsing the lnk file. The implementation should be implemented in `org.jabref.gui.desktop.os.Windows#detectProgramPath`.

Alternative:

However, when I click Save in the preferences, there should be a check. If the binary could not be found, user should be asked to navigate to the options.

**Comment by Jayachandra5** [comment]
I am Interested in contributing to this Issue.

**Comment by Jayachandra5** [comment]
Can Anyone tell me what does

**Comment by Jayachandra5** [comment]
That is a Java Inbuilt function. Here is the screenshot attached 

![image](https://github.com/JabRef/jabref/assets/89126550/0b23030a-ee13-4ff4-97a4-10cbe02cf634)

**Comment by Jayachandra5** [comment]
The method in  /src/main/java/org/jabref/preferences/JabRefPreferences.java#L946 is not returning the value stored by the defaults hashmap. 


![image](https://github.com/JabRef/jabref/assets/89126550/8e3e4fb0-6de6-4766-b4a9-0602f2de63db)

Printing Value is Different From Returning Value

**Comment by koppor** [comment]
@Jayachandra5 This is far away from this issue. You can submit a question at https://discourse.jabref.org/c/programming/44. 

Some words: Users can configure JabRef. What are the defaults if nothing is configured? The ones in the HashMap. Where are the configurations stored? In Windows registry. How to access? Using Java properties? How named in JabRef? "Preferences"?

**Comment by InAnYan** [comment]
Hello! I want to fix this issue.

I have a question: do I need to add any test for this bugfix?

**Comment by koppor** [comment]
@InAnYan I did not see any activity by @Jayachandra5 , thus I re- assign to you.

Tests are always good. Just give it a thought. Maybe with jimfs (https://github.com/google/jimfs), but could be too much effort...

**Comment by InAnYan** [comment]
Is it okay to solve this issue like this:
In `gui.desktop.os.Windows`:
```java
public String detectProgramPath(String programName, String directoryName) {
    if (programName == "texworks") {
        // Check if %APPDATA%\Microsoft\Windows\Start Menu\Programs\MiKTeX\TeXworks.lnk exists.
        // If it is, then extract the target from link.
    }
    ...
```

Or should I somehow generalize it?

I was thinking that the function `getProgramPath` would also test for links, not only executables. But then I ran into issue, that it appends `TeXworks` directory to the path, but the path `%APPDATA%\Microsoft\Windows\Start Menu\Programs\MiKTeX` does not have any special directory. Can I ignore the `directoryName` if it is equal to `TeXworks`?
