### ISSUE TITLE
Add a button "new from doi" next to "new entry"

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1098]
We should prominently feature this functionality to easily add a new entry based on a DOI.
This may not use the MergeDOIDialog at first, but only retrieve the new values.
We can discuss this when implementing the feature.
The "fetch from doi" inside the field editor currently opens the MergeDOIDialog.
We need a good icon for this preferably an overlay of the new button with DOI text.

**Comment by stefan-kolb** [comment]
Currently implemented directly inside the new entry dialog.

**Comment by lenhard** [comment]
@stefan-kolb: So this issue can be closed, right?

**Comment by matthiasgeiger** [comment]
Yes. 😉
