### ISSUE TITLE
Craft round-trip test for CFF importer/exporter

### ISSUE THREAD

**Issue by JEANPRBT** [JabRef/jabref#10993]
As mentioned in  [#10917 (comment)](https://github.com/JabRef/jabref/pull/10917#pullrequestreview-1902194126), it would be great to craft a round-trip test for the cff format, since we now have both an importer and an exporter.

The round-trip test should work importing https://github.com/JabRef/jabref/blob/main/CITATION.cff. 

The current problem is that the importer only parses imports to BibEntry `software` type, as it was primarily intended by the Citation-File Format. On the other hand, the exporter uses the field `preferred-citation` to parse entries to their actual type, even if it is different that `software`. Also, the exporter uses the `preferred-citation` field even when the type is Software, which is not the expected behavior according to the CFF format. 

There are four main things to implement in order for this round-trip test to work. 
- [x] make the importer parse the `preferred-citation` field, and in this case create **another** BibEntry for what is contained. 
- [x] make the exporter parse the BibEntry `Software` type, and in this case output a cff file **without** any `preferred-citation` field. 
- [x] parse the author's first name and last name separately, so that the exporter could use the fields `given-names` and `family-names` instead of the generic field `name` in the `authors` section. 
- [x] (more simple) parse all the fields from https://github.com/JabRef/jabref/blob/main/CITATION.cff in both importer and exporter

The exporter works using `org.jabref.logic.exporter.TemplateExporter` and the `src/main/resources/resource/layout/cff.layout` file. Importer is located in `org.jabref.logic.importer.fileformat.CffImporter`.

 Some work was done in #10957 but then abandoned, it may help.

**Comment by koppor** [comment]
@JEANPRBT Some GitHub knowledge: Please do not reference PRs in commits. The commits are assigned to a branch and the branch is connected to thr PR. Thus, they will appear hear. Otherwise, we have a long list of non-useful information here on https://github.com/JabRef/jabref/issues/10993

**Comment by JEANPRBT** [comment]
Sorry about that, thanks for noticing ! I won't reference PRs nor issues in commits anymore.
