### ISSUE TITLE
AuthorLastSeparator=" and " ends up as "&" and AuthorSeparator=", " as  ";"

### ISSUE THREAD

**Issue by brobr** [JabRef/jabref#10994]
### JabRef version

5.12 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create custom style by copying example from https://docs.jabref.org/cite/openofficeintegration
2. Change field `AuthorLastSeparator=` from `" & "` to `" and "`
3. 3. Load style and apply
4. Change is not happening; built-in style shows `" and "`
5. A similar issue with `AuthorSeparator=", " `, which shows as  `; ` 

Thius has been run on the 'mobile' version.

What am I doing wrong?

### Appendix

Image with internal style, shows ` and ` (throws error when trying to edit this with Libre Office):

![internal-style-with-and-Screenshot_2024-03-08_02-31-18](https://github.com/JabRef/jabref/assets/3693709/40b32aa7-9977-4c2a-aefe-bebc2b09ddd3)

Image of in-program display of loaded 'NAR' style, (note the `&` while `" and "` has been set in style):

![in-program-style-display](https://github.com/JabRef/jabref/assets/3693709/926faea9-540b-4956-84e3-6af66279ec09)

Image of `References` list in document  (with `&` plus jstyle file with `=" and "`:

![produced_style-differs-from-setting_2024-03-08_02-00-15](https://github.com/JabRef/jabref/assets/3693709/24b3a5a9-ed68-4fbe-bc24-3061f9a2d443)
<details>

<summary>Log File</summary>

...

Current style is 'NAR style file for JabRef-OpenOffice integration.'
Current style is 'NAR style file for JabRef-OpenOffice integration.'
Current style is 'Default [Author year] style file'
Current style is 'Default [Author year] style file'
Current style is 'Default [Author year] style file'
Current style is 'Default [number] style file.'
Current style is 'NAR style file for JabRef-OpenOffice integration.'```
Paste an excerpt of your log file here

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/8893 (which should make the whole configuration obsolete)

**Comment by Siedlerchr** [comment]
@brobr
seems like the preview is wrong here/not updated.  However setting the property it works in LO:


<img width="868" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/8fb4a670-ac49-4857-90e7-ba68d96eee82">

CITATION
AuthorLastSeparator=" asdfasdf "


1. All styles  and also JabRef's preview are based on the template engine/scheme for Custom Exports https://docs.jabref.org/collaborative-work/export/customexports 
2. For Open/LibreOffice they are extended with addtional properties:   https://docs.jabref.org/cite/openofficeintegration

> JabRef has (outdated) preview styles; can these not be exported/reimported as a .jstyle that works??

Can you be more specific here? What exactly is outdated?

**Comment by Siedlerchr** [comment]
@brobr  Thanks for the hint, the jstyles are not really maintained by us, we just have a collection of them here: They were contributed by users. And I would like to know where you found the style because I did a quick look and could not find it...
https://github.com/JabRef/jstyles.jabref.org 

You are welcome to submit your style there!
