### ISSUE TITLE
Add a method to create a new link manually

### ISSUE THREAD

**Issue by ror3d** [JabRef/jabref#11017]
**Is your suggestion for improvement related to a problem? Please describe.**
Currenty, the General tab > File entries can hold either paths to local files, or links to online URLs, but when creating them manually, only local files can be added there (either by selecting a local file with the file chooser, or by downloading a URL).

This makes it difficult to use that field for other information such as e.g. links to github repositories for code related to the article.

**Describe the solution you'd like**
It would be good if a method to create a new file entry manually was available -- open the file entry editor with blank entries, allow filling them up manually, and create the entry with the result of that operation.

**Comment by rahulsree** [comment]
Hi, I'm interested in contributing to this issue, I'd appreciate if you could provide me with the assignee role.

**Comment by koppor** [comment]
@rahulsree May I ask for progress?

**Comment by Kunal77689** [comment]
Hi, I'd like to start contributing to this issue,  Could you please assign it to me?

**Comment by koppor** [comment]
As screenshot:

<img width="422" alt="2024-07-26_00-19" src="https://github.com/user-attachments/assets/d4621e46-3d6a-42f8-a6db-2e51faaa735b">

- Instead of directly opening the file browse dialog, the linked file dialog should be opened
- The dialog has a different heading and a different finish button (see screenshot)
- The old logic directly opening a file browser is to be removed -> this dialog is the only thing shown.

We accept that for attaching files, now three clicks are necessary. We gain the benefit that the user can directly add a description.

**Comment by Kunal77689** [comment]
> As screenshot:
> 
> <img alt="2024-07-26_00-19" width="422" src="https://private-user-images.githubusercontent.com/1366654/352304060-d4621e46-3d6a-42f8-a6db-2e51faaa735b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NDg0NTAsIm5iZiI6MTcyMTk0ODE1MCwicGF0aCI6Ii8xMzY2NjU0LzM1MjMwNDA2MC1kNDYyMWU0Ni0zZDZhLTQyZjgtYTZkYi0yZTUxZmFhYTczNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMjI1NTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTA5NGQ3MDdhNmNkYzQxODMzNmQ4MmZmMDM5NGM5ZGQwNTc0YTIyZWM4OGVjMDhhMGVmZTgwZjk1YzczYjkzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.spKelv1zJnJHeE159q1xmDgtAHlSZ5IA0mWfbnf4-wM">
> * Instead of directly opening the file browse dialog, the linked file dialog should be opened
> * The dialog has a different heading and a different finish button (see screenshot)
> * The old logic directly opening a file browser is to be removed -> this dialog is the only thing shown.
> 
> We accept that for attaching files, now three clicks are necessary. We gain the benefit that the user can directly add a description.

Great, thanks for the clarification

**Comment by Kunal77689** [comment]
@koppor What all file types can we expect for the combo box?

**Comment by koppor** [comment]
> @koppor What file types can we expect to be available in the combo box?

The whole dialogue including the combobox is already available. One "just" needs to adapt it to cover two cases: add (new), edit (existing)

**Comment by koppor** [comment]
@Kunal77689 please open jabref, create a new library, drag and drop a PDF into it. Hold the ctrl key, otherwise it will be moved. Then go to "General" tab, Files. There you will see the pdf. Then click the edit button on the right. You will see the dialog.
