### ISSUE TITLE
Add support for BibLatex special fields

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1101]
In the BibLatex manual there are a number of special fields listed in Section 2.2.3 which we currently do not have support for. It would be nice to have that. I think an extra tab "Special fields" (which is maybe not the best name considering that we have our own special fields... "BibLatex special fields"?) would be an easy solution and add a new class of fields to each entry type?

There will be a duplication of some fields, e.g., keywords and crossref but maybe that is OK?

**Comment by mlep** [comment]
This may be a valuable feature in the short term (and there are already duplications of some fields anyway).

However, and maybe for a future redesign, I believe the tabs in the entry editor are already too numerous, making the UI complex.
As a suggestion for further discussion, we could have an small label along with each field name showing if the field is related to BibTeX, BibLaTeX, JabRef, Deprecated, Unknown, User-defined, etc.
Do we already have an issue related to the entry editor design? (I could not find an opened one...)

**Comment by lenhard** [comment]
Regarding a restructuring of the entry editor, this refs #2790

**Comment by lenhard** [comment]
We have broadened the discussion in #2790 and hence I am closing this issue in favor of the other one. Design and restructuring ideas should be taken over there.
