### ISSUE TITLE
Library is marked as unsaved (*) after accepting changes from the file

### ISSUE THREAD

**Issue by ror3d** [JabRef/jabref#11027]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

This is visible when someone edits the file with jabref while you have the same library open. I don't know of a good way to reproduce other than that, maybe by editing the file in a text editor, or having two instances of jabref open (I don't know if easily done).

1. Open any library file with at least one entry
2. Edit the bib file in a text editor, remove one entry (leave a single line between entries to match jabref output format) and save
4. Notice that in the main instance, a notification about changes being made by another program appears.
5. Select Review changes
6. Accept the change
7. Notice that the library appears as modified, even though it should match exactly the contents of the file saved to disk

**Comment by koppor** [comment]
> Notice that the library appears as modified, even though it should match exactly the contents of the file saved to disk

Is it because of an asterisk or another library changed dialog? If the latter, which content?

**Comment by amrithdas** [comment]
@koppor can I work on this? I'm thinking of making it save the library when Accept button is clicked in review changes page.

**Comment by koppor** [comment]
Please remember to test manually and also think about UI tests.

**Comment by amrithdas** [comment]
@koppor please review

**Comment by koppor** [comment]
@ror3d Your initial question was about to remove the asterisk if all external changes were applied. Not to remove it, if there is a mix of accepted and rejected changes? Then, the asterisk should stay (if the user has autosave disabled)

**Comment by ror3d** [comment]
Yes, precisely. I have autosave turned off (because we share the file in a shared drive among a couple of people) so as you say, if the issue was just saving after, that wouldn't be a problem.

**Comment by amrithdas** [comment]
@koppor @ror3d I have modified the code to not show the asterisk and save changes pop up when external changes are accepted and to show both when denied. please review.

**Comment by koppor** [comment]
@amrithdas Thank you for the follow up. I commented at the PR.

Current JabRef behavior:

1. Modify file externally

![image](https://github.com/JabRef/jabref/assets/1366654/a2fbd550-4d9d-43c6-8f63-00976072d686)

2. Press "Review changes"

![image](https://github.com/JabRef/jabref/assets/1366654/c40b412c-d84d-491f-bf31-495a9b2c49d5)

3. Press "Deny"

Dialog closes and NO asterisk:

![image](https://github.com/JabRef/jabref/assets/1366654/c25e7811-4ef5-4d78-91c4-c579fa1c3497)

I think, the logic is just inversed in JabRef. One "just" needs to find the place.

**Comment by amrithdas** [comment]
@koppor upon further inspection I found that when accepting external changes JabRef is creating a new entry to the database even though its inserting the same data in the disk hence the changedProperty gets set to True. thats why its appearing as unsaved. similarly when denying its just removes the selected change. the logic is inversed as you mentioned but I'm not sure whether this will be a small change. would it be better to try finding a new approach or continue to refine the logic which I already did?

**Comment by koppor** [comment]
@amrithdas I think, it is a completely new approach! Maybe, test cases can also be crafted.

**Comment by amrithdas** [comment]
@koppor I have updated the PR, please review.

**Comment by koppor** [comment]
> @koppor I have updated the PR, please review.

@amrithdas Updates on the PR have more todo with the PR than with the issue. Hard to navigate from the issue to the PR on mobile... If you insist on pinging, please do that on tbe PR...
