### ISSUE TITLE
MacOS crash when launching the launcher

### ISSUE THREAD

**Issue by Almar0001** [JabRef/jabref#11035]
### 

### Operating system

macOs

### Details on version and operating system

macOs 10.15.7 catalina

### Checked with the latest development build (copy version output from About dialog)

- [ ] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I threw an error at startup from below

Process:               java [1115]
Path:                  /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
Identifier:            java
Version:               1.0 (1.8.0_401)
Code Type:             X86-64 (Native)
Parent Process:        Jar Launcher [1114]
Responsible:           Jar Launcher [1114]
User ID:               501

Date/Time:             2024-03-16 23:26:21.421 +0300
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        E663AB17-BB99-A5ED-E3FD-BE919F514F3B

Time Awake Since Boot: 1100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

VM Regions Near 0x8:
--> 
    __TEXT                 0000000102065000-0000000102075000 [   64K] r-x/r-x SM=COW  /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Dyld Error Message:
  Symbol not found: _pthread_self_is_exiting_np
  Referenced from: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/libjfxwebkit.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x0000000107e7305e __abort_with_payload + 10
1   dyld                          	0x0000000107e9c6ed abort_with_payload_wrapper_internal + 80
2   dyld                          	0x0000000107e9c71f abort_with_payload + 9
3   dyld                          	0x0000000107e99d74 dyld::halt(char const*) + 463
4   dyld                          	0x0000000107e21bc3 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 140
5   libdyld.dylib                 	0x00007fff70dc7692 dyld_stub_binder + 282
6   ???                           	0x00000001207c7000 0 + 4839993344
7   libjfxwebkit.dylib            	0x000000011e3fcabd bmalloc_allocate_impl_impl_slow(__pas_heap_ref*, unsigned long, unsigned long) + 45
8   libjfxwebkit.dylib            	0x000000011e3f1300 bmalloc_allocate_impl_casual_case(unsigned long, unsigned long) + 528
9   libjfxwebkit.dylib            	0x000000011e381404 WTF::ThreadGroup::create() + 20
10  libjfxwebkit.dylib            	0x000000011e3e568d void std::__1::__call_once_proxy[abi:v15006]

**Comment by Siedlerchr** [comment]
Hi,
Sorry to inform you but
JabRef 5.12 requires at least macOS 11 due to Javafx

This was written in our blog post
https://blog.jabref.org/2023/12/24/JabRef5-12/#important-information

Almar0001 ***@***.***> schrieb am Sa., 16. März 2024, 21:29:

**Comment by koppor** [comment]
macOS Big Sur (version 11)  as released to the public on November 12, 2020, thus 3.5 years ago. Therefore, we took the risk to force that as minim version for JabRef.
