### ISSUE TITLE
Import from bibtex on clipboard to a custom group 

### ISSUE THREAD

**Issue by jiewangjs** [JabRef/jabref#11085]
Hi, all. In scenarios decribed in the title, I expect the imported entried to appear under the custom group rather than the default "all entries" group. 
But what I found is when there is only one entry on clipboard, it works well. When the number of entries on the clipboard are two or more, only the last one will appear under custom group, the others will appear under "all entries" group.
Please fix or make improvements. When I import multiple entries from zotero using bibtex, I want paste them under custom group. If they get scattered into "all entries" group, it is very time-consuming to find them one-by-one and recollect them to custom group.
Thanks!

**Comment by CongLuanTran** [comment]
I wonder if this has been fixed, because I can't reproduce it. All paste to a custom group got placed into that group.

**Comment by koppor** [comment]
> I wonder if this has been fixed, because I can't reproduce it. All paste to a custom group got placed into that group.

Did you try multiple entries? Both the bug report and your reproducing report miss concrete steps. Think of a "Use Case description" (https://en.m.wikipedia.org/wiki/Use_case; especially read the Example!)

**Comment by CongLuanTran** [comment]
> Did you try multiple entries? Both the bug report and your reproducing report miss concrete steps. Think of a "Use Case description" (https://en.m.wikipedia.org/wiki/Use_case; especially read the Example!)

Yes, I tried with multiple entries. Recently I tried in both the dev version (from Github) and the msi installer version, and here is where it went weird. Two cases happened:

**Case 1:** Pasting multiple entries into custom group while using Jabref installed with .msi installer

**Version:** 
- JabRef 5.12--2023-12-24--4233bad
- Windows 11 10.0 amd64 
- Java 21.0.1 
- JavaFX 21.0.1+6

**Result:** It works as expected, all entries from the clip board is placed into the custom group.

**Case 2:** Pasting multiple entries into custom group while using Jabref from Github fork (as per the instruction from https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/)

**Version:**
- JabRef 100.0.0
- Windows 11 10.0 amd64 
- Java 21.0.2 
- JavaFX 22+30

**Result:** The reported bug happens, only the first entry is placed into the custom group, the rest only go to "All Entries" group

I hope this help clarify the issue a bit.

**Comment by ADm1n766** [comment]
I would work on this issue, specifically on this task:

> **Case 2**: Pasting multiple entries into custom group while using Jabref from Github fork (as per the instruction from https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/)
>Version:
>JabRef 100.0.0
>Windows 11 10.0 amd64
>Java 21.0.2
>JavaFX 22+30
>Result: The reported bug happens, only the first entry is placed into the custom group, the rest only go to "All Entries" group
>I hope this help clarify the issue a bit.

**Comment by ThiloteE** [comment]
@CongLuanTran Please provide some entries you try to copy, so that we can reproduce.

**Comment by ThiloteE** [comment]
I am not completely sure, but your issue sounds like a symptom caused by https://github.com/JabRef/jabref/issues/8836. Fixing this is not trivial, not a good first issue and requires lots of thought and a well crafted design for our groups feature. (Btw. JabRef's groups feature is currently actually a "tags" feature. We just call it groups).

**Comment by CongLuanTran** [comment]
> @CongLuanTran Please provide some entries you try to copy, so that we can reproduce.

So this is a small set that I tried to paste, larger set shows no difference though.

```
@book{wals,
  address   = {Leipzig},
  editor    = {Matthew S. Dryer and Martin Haspelmath},
  publisher = {Max Planck Institute for Evolutionary Anthropology},
  title     = {WALS Online},
  url       = {https://wals.info/},
  year      = {2013}
}

@incollection{wals-9,
  address   = {Leipzig},
  author    = {Gregory D.S. Anderson},
  booktitle = {The World Atlas of Language Structures Online},
  editor    = {Matthew S. Dryer and Martin Haspelmath},
  publisher = {Max Planck Institute for Evolutionary Anthropology},
  title     = {The Velar Nasal},
  url       = {https://wals.info/chapter/9},
  year      = {2013}
}

@article{labrune2021word,
  title={Word-initial rhotic avoidance: a typological survey},
  author={Labrune, Laurence},
  journal={Glossa: a journal of general linguistics},
  volume={6},
  number={1},
  year={2021},
  publisher={Open Library of Humanities}
}
```

**Comment by ThiloteE** [comment]
Thank you. Those entries do not seem out of the ordinary.
@CongLuanTran Is there a possibility you could provide a screenshot of the settings of one of the groups that this happens with?

**Comment by Siedlerchr** [comment]
I can reproduce the issue now
