### ISSUE TITLE
Allow to right-click to copy log content from Help → View Event log

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11100]
**Is your suggestion for improvement related to a problem? Please describe.**
When I want to report an issue and I would like to copy the log content, I cannot copy it via right click.

**Describe the solution you'd like**
I would like to copy the log entry by right click -> Copy

**Additional context**
![log](https://github.com/JabRef/jabref/assets/320228/008520e4-78e7-473e-9a02-205199dd9db9)

**Comment by subhramit** [comment]
I want to take this.
