### ISSUE TITLE
Add a value selection (like for month) for content selectors in custom entry types

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11109]
**Is your suggestion for improvement related to a problem? Please describe.**
When I create content selectors for a field, I would like to choose them from a list of values and not having to remember the value.

**Describe the solution you'd like**
A value selection like for the month field: 
<img width="371" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/1bf76548-5cff-45b4-a364-e1988cee79d0">

**Additional context**
1. Create a new library
2. Go to Preferences -> Entry types -> Add a new custom field to an entry type e.g. Misc, for example, name it "mycustom"
3. Save and restart Jabref
4. Right-click on the library-> Library properties -> Content selectors ->  Add as in the screenshot below
<img width="600" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/e04955cf-4fa3-489f-a4c4-31ab4a5f4b34">
5. Add an new entry "Misc"  into the library
6. See the new custom field
7. you have to type a letter e.g. "k" to get the value suggested

**Comment by azatyamanaev** [comment]
Hello. Can I work on this issue?

**Comment by azatyamanaev** [comment]
This issue is still open, so I created a pull request for it.
