### ISSUE TITLE
Allow selecting content of other user's comments

### ISSUE THREAD

**Issue by ror3d** [JabRef/jabref#11106]
**Is your suggestion for improvement related to a problem? Please describe.**
In the Comments panel, when a different user writes a user-specific comment (showing as `Comment-name`) it appears as a disabled textarea to other people reading that entry so it can only be edited by the original author, but it also makes it disabled for selection. That makes is so that if someone adds e.g. a link in their comment, it can't be selected to be copied to the browser.

**Describe the solution you'd like**
It would be nice if text in the user-specific comments could be selected, while maintaining the un-editability of the field.

**Additional context**
I've had a bit of a look around to see how easy it would be to hack this functionality into the current implementation, but I wasn't able to find the right point in the code (in the javafx library) where the disabled state affects selectability.

I see 3 easy possibilities to implement this:
- It is possible that there's some easy way to solve this by overriding some method in the textarea which would make it allow the text be selectable while the textarea is disabled
- The textarea could be left as enabled and override the other input methods to disable editing instead, but leaving it selectable
- Using a different field instead of a textarea, such as the html display field or similar, which would make the entry selectable

Of the three, I believe second or third option might be best (and third might be easier to implement, maybe?), since they would also make the text more readable, as the greyed-out text of the default disabled fields is not ideal to read.

**Comment by lllllllittlesun** [comment]
Hi@koppor ,may I ask to contribute for this issue?

**Comment by koppor** [comment]
@lllllllittlesun Sure. Please create a minimal JavaFX application (maybe based on https://github.com/Siedlerchr/javafxreproducer) to reproduce the issue. Then, you can check whether an issue needs to be files to JavaFX team or if we did something wrong in JabRef. -- In other words: This issue is more on reproducing than on writing much code.

**Comment by lllllllittlesun** [comment]
@koppor Okay, I'll try this. But May I please be assigned this issue?
