### ISSUE TITLE
error Input byte array has wrong 4-byte ending unit

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#11117]
### JabRef version

Other (please describe below)

### Operating system

Other (please describe below)

### Details on version and operating system

JabRef 5.13--2024-03-31--0d97382 Linux 6.7.9-200.fc39.x86_64 amd64  Java 21.0.2  JavaFX 22+30

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. open my library file, provided upon request ;)

suggestion: provide more intelligible error message

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
	at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
	at java.base/java.util.Base64$Decoder.decode(Unknown Source)
	at java.base/java.util.Base64$Decoder.decode(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.fileformat.BibtexParser.parseField(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.fileformat.BibtexParser.parseEntry(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.fileformat.BibtexParser.parseAndAddEntry(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.fileformat.BibtexParser.parseFileContent(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.fileformat.BibtexParser.parse(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.fileformat.BibtexImporter.importDatabase(Unknown Source)
	at org.jabref@5.13.326/org.jabref.logic.importer.OpenDatabase.loadDatabase(Unknown Source)
	at org.jabref@5.13.326/org.jabref.gui.importer.actions.OpenDatabaseAction.loadDatabase(Unknown Source)
	at org.jabref@5.13.326/org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openTheFile$1(Unknown Source)
	at org.jabref@5.13.326/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.13.326/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.13.326/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by koppor** [comment]
Please send the bib file to me

**Comment by Siedlerchr** [comment]
Can you please send the file to ***@***.***

Can you check the file encoding in another editor? Seems like an issue with
Byte Order Mark (bom)


Ingmar Lippert ***@***.***> schrieb am So., 31. März 2024,
15:59:

**Comment by Siedlerchr** [comment]
Possible error could be related fo the check for bibdesk field https://github.com/JabRef/jabref/blob/61120e40516312949e33b08f644077cbba166f31/src/main/java/org/jabref/logic/importer/fileformat/BibtexParser.java#L745-L749

**Comment by ilippert** [comment]
yes, many `bdsk-file` :)

**Comment by Siedlerchr** [comment]
Yes, JabRef is now able to parse BibDesk files and group(s)

**Comment by ilippert** [comment]
> Yes, JabRef is now able to parse BibDesk files and group(s) Improved the error handling to show the related issue #11118

Sorry if I misuse the ticket for this. Does this BibDesk reading by the way extend to Skim's skim note files?

**Comment by Siedlerchr** [comment]
> Sorry if I misuse the ticket for this. Does this BibDesk reading by the way extend to Skim's skim note files? 

Never heard of this program before, I have no idea how this work, but if it's creating annotations (e.g highlighting text or comments)  in pdf files, JabRef can read these (Tab File Annotations)

<img width="1347" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/1846ee12-8e10-4e52-9311-1993640efe09">

MacOS Preview pdf: 

<img width="638" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/275fc331-09e5-4b2d-a171-67871445db63">

**Comment by ilippert** [comment]
Hah, as wiki might say it, once upon a time, Skim was a PDF reader, that featured non-pdf compliant annotations :(

Skim was/is developed by the BibDesk team and together it worked very well.

<https://en.m.wikipedia.org/wiki/Skim_(software)>

--

**Comment by Siedlerchr** [comment]
According to their FAQ they save the notes in the extended file attributes on the file system (crazy), so even transferring them to a different computer would lose the info... However, seems like you can export it somehow

https://sourceforge.net/p/skim-app/wiki/FAQ/ 
> How can I save the PDF so that notes are visible in other viewers, such as Preview and Acrobat?

> Save a copy of the file with the notes included in the PDF. Choose Export... from the File menu and select PDF from the File Format popup button and select the With Embedded Notes option. Notes and highlights are now visible in other viewers, such as Preview and Acrobat Reader. Alternatively, you can Print to a file. Go to the print dialog window (command+P) and choose Print to PDF. However with both techniques, you won't be able to edit the notes and highlights in the exported copy.

**Comment by ilippert** [comment]
Thanks, yeah. Was never able to automate that. And transitioned away from osx a decade ago. 

Maybe relevant as a usecase story: I keep the `bdsk` file references in the entry just as an indicator that I know there might be old notes left. And if these promise a nice secret, I power on my legacy Mac to access these files. But otherwise the `bdsk` file references are quite nonfunctional for me.

Am so happy I switched to JabRef and plain text annotations.
--

**Comment by ilippert** [comment]
Here is another line that causes an error

```
  bdsk-file-1 = {////=},
```

**Comment by Siedlerchr** [comment]
You can use this version https://builds.jabref.org/pull/11118/merge It will print out all more warnings/errors

**Comment by ilippert** [comment]
Several things "wrong" with my data in this version

JabRef 5.13-PullRequest11118.330--2024-03-31--0c344a9
Linux 6.7.9-200.fc39.x86_64 amd64 
Java 21.0.2 
JavaFX 22+30


```
Please check your library file for wrong syntax.

Error occurred when parsing entry: 'Error in line 64104: Expected { or ( but received s'. 

JabRef skipped the entry.
```

this seems to be caused by the `@` in this line
```
annote       = {read ... E.g. @supermarket: shopper learns about a new class of products in a supermarket visit. this alters the setting when she visits the supermarket next time. 152: supermarket is physically designed (by actors with specific intentions); paths of shoppers related to their expectations on how the supermarket is structured. },```

Though, this seems to be unrelated to this issue.

**Comment by ilippert** [comment]
> You can use this version https://builds.jabref.org/pull/11118/merge It will print out all more warnings/errors

In fact, no, it does not print out more warnings/info. I tried to copy into an empty library my round 7k entries, and only round 0.5k are imported; without any notice, the other 6.5k entries are seemingly ignored.

**Comment by ilippert** [comment]
However, the original file does generate these messages

```
Please check your library file for wrong syntax.

Error occurred when parsing entry: 'Could not parse Bibdesk files content (bdsk-file..) for entry @article{Haluza-delay,
  abstract = {Research on social movements has looked primarily at activists involved in campaigns. Since the environmental movement has maintained that the everyday lifestyle of the citizen is part of the environmental problem and part of the solution, we would do well to examine also these lifestyle practices and what generates them. Using tools from Bourdieu's sociological method, this ethnographic study considers how environmental ``logic of practice'' is informed by habitus. A logic of practice is the ``feel'' for living (sens pratique) generated by internalized and ``pre-logical'' dispositions (habitus) and the social field. Another approach to explaining the operations of social movements, particularly for members, is that of ``cognitive praxis.'' In this formulation by Eyerman and Jamison, social movements create new knowledge systems. This research assesses the environmental habitus of environmentally-active persons in a region, finding several common dispositions amidst the great variety of ways of being environmentally active. These individuals tried to live in environmentally responsible ways, but were keenly aware of their inconsistencies. Being different than the dominant ways of being in contemporary society, they engaged in a variety of practices to ``self-dispose'' or non-cognitively support their environmental dispositions. However, their place in contemporary society where a routinized environmental sensitivity is contrary to the dominant or mainstream logic of practice, led to increased self-awareness. Thus, an environmental habitus could be said to include reflexivity, which appears to contradict the ``pre-logical'' description of the habitus. Reflexivity is a core part of being environmentally active, and participates in developing movement identity. The paper concludes by explaining the link between sens pratique and cognitive praxis, thereby advancing social movement theory.},
  annote = {in http://disccrs.org/dissertation_abstract?abs_id=1507},
  author = {Randolph Haluza-DeLay},
  title = {Habitus and cognitive praxis among environmentalists},
  _jabref_shared = {sharedId: -1, version: 1}
}'. 

JabRef skipped the entry.
Error occurred when parsing entry: 'Could not parse Bibdesk files content (bdsk-file..) for entry @article{Anonymous:2001p1756,
  author = {Marjolein van Asselt},
  subtitle = {From Problem to Challenge},
  title = {UNCERTAINTY IN DECISION-SUPPORT},
  _jabref_shared = {sharedId: -1, version: 1}
}'. 

JabRef skipped the entry.
Error occurred when parsing entry: 'Could not parse Bibdesk files content (bdsk-file..) for entry @article{Gusterson1997,
  abstract = {recommended by Rachel Aug 2019 re Studying up & ethics},
  author = {Hugh Gusterson},
  date = {1997-05},
  doi = {10.1525/pol.1997.20.1.114},
  journaltitle = {PoLAR: Political and Legal Anthropology Review},
  number = {1},
  pages = {114--119},
  title = {Studying up revisited},
  volume = {20},
  _jabref_shared = {sharedId: -1, version: 1}
}'. 

JabRef skipped the entry.
```

**Comment by ilippert** [comment]
the seemingly final culprit

```
  bdsk-file-1 = {YnBsaXN0MDDUAQIDBAUGJCVYJ HZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKgHCBMUFRYaIVUkbnVsbNMJCgsMDxJXTlMua2V5c1pOUy5vYmplY3RzViRjbGFzc6INDoACgAOiEBGABIAFgAdccmVsYXRpdmVQYXRoWWFsaWFzRGF0YV8QOC4uLy4uLy4uL1BhcGVycy8yMDAxQXNzZWx0VW5jZXJ0YWludHlEZWNpc2lvblN1cHBvcnQucGRm0hcLGBlXTlMuZGF0YU8RAfAAAAAAAfAAAgAADE1hY2ludG9zaCBIRAAAAAAAAAAAAAAAAAAAAM6T/wtIKwAAACI+9B8yMDAxQXNzZWx0VW5jZXJ0YWludCMyMjQxNkQucGRmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIkFtuUDgXgAAAAAAAAAAAAMAAgAACSAAAAAAAAAAAAAAAAAAAAAGUGFwZXJzABAACAAAzpPw+wAAABEACAAAuUDEPgAAAAEAEAAiPvQAIjTXACHV2wAHw2AAAgBQTWFjaW50b3NoIEhEOlVzZXJzOgBpbGlwcGVydDoARG9jdW1lbnRzOgBQYXBlcnM6ADIwMDFBc3NlbHRVbmNlcnRhaW50IzIyNDE2RC5wZGYADgBSACgAMgAwADAAMQBBAHMAcwBlAGwAdABVAG4AYwBlAHIAdABhAGkAbgB0AHkARABlAGMAaQBzAGkAbwBuAFMAdQBwAHAAbwByAHQALgBwAGQAZgAPABoADABNAGEAYwBpAG4AdABvAHMAaAAgAEgARAASAEhVc2Vycy9pbGlwcGVydC9Eb2N1bWVudHMvUGFwZXJzLzIwMDFBc3NlbHRVbmNlcnRhaW50eURlY2lzaW9uU3VwcG9ydC5wZGYAEwABLwAAFQACAA///wAAgAbSGxwdHlokY2xhc3NuYW1lWCRjbGFzc2VzXU5TTXV0YWJsZURhdGGjHR8gVk5TRGF0YVhOU09iamVjdNIbHCIjXE5TRGljdGlvbmFyeaIiIF8QD05TS2V5ZWRBcmNoaXZlctEmJ1Ryb290gAEACAARABoAIwAtADIANwBAAEYATQBVAGAAZwBqAGwAbgBxAHMAdQB3AIQAjgDJAM4A1gLKAswC0QLcAuUC8wL3Av4DBwMMAxkDHAMuAzEDNgAAAAAAAAIBAAAAAAAAACgAAAAAAAAAAAAAAAAAAAM4},
```

thanks Christoph for the build with the warnings. helped a lot.

**Comment by ilippert** [comment]
I consider this closed with the https://github.com/JabRef/jabref/pull/11118 fix as it helps the user to locate the error

**Comment by Siedlerchr** [comment]
Thanks for your feedback. We will check the annote field parsing as well. I guess JabRef expects the at belongs to a cite key but the field should be parsed as verbatim probably. Will need to check the spec as well.

We will check the copy pasting as well. Seems like there is a different parsing logic/error handling involved

A bit of background, the bibdesk file fields are base64 encoded plist-files
