### ISSUE TITLE
Validate Username Parameter in UserSpecificCommentField

### ISSUE THREAD

**Issue by hossamP10** [JabRef/jabref#11129]
**Is your suggestion for improvement related to a problem? Please describe.**
"I encountered an issue when creating a `UserSpecificCommentField` instance without providing a valid username."

**Describe the solution you'd like**
"I've added validation to the `UserSpecificCommentField` constructor to ensure that the `username` parameter is neither null nor empty."

**Comment by koppor** [comment]
This is not a user-facing issue. Please discuss code-related issues in the [gitter channel](https://app.gitter.im/?updated=1.11.58#/room/#JabRef_jabref:gitter.im) or [use our forum](https://discourse.jabref.org/c/programming/44)

Please make yourself familiar with recent developments in the Java eco system, such as [JSpecify](https://jspecify.dev/)
