### ISSUE TITLE
Add an exporter for Endnote XML

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#11137]
JabRef has an exporter for the legacy format of Endnote (similar to [refer](https://www.wikiwand.com/en/Refer_(software))). Although we have an importer for Endnote XML, an exporter is yet to be implemented.

## Useful Links
- [Zotero Endnote XML translator (Exporter)](https://github.com/zotero/translators/blob/db2771d52d89d1480ff98efbd6968565893f2184/Endnote%20XML.js#L239C35-L239C35)
- [EndNote: XML Document Type Definition](https://support.clarivate.com/Endnote/s/article/EndNote-XML-Document-Type-Definition?language=en_US)
https://github.com/JabRef/jabref/blob/748b0eeaa8dedc07c872fe535bef3bf31298f1b1/src/main/java/org/jabref/logic/importer/fileformat/EndnoteXmlImporter.java#L49

**Comment by subhramit** [comment]
This will require UI additions as well, correct?
If so, where should the changes be?

**Comment by Siedlerchr** [comment]
No UI addtions needed. It will be simply available in the list of exporters to choose from.

**Comment by subhramit** [comment]
I want to try this, but am only concerned about how to write a working test for it. If anyone wants to work together on this, let me know.

**Comment by Siedlerchr** [comment]
You can take a look at the other Exporters and tests for example.
1. Test the correct export of an endnote file. Here you maybe create a sample library in endnote, export/save it and then use that as base to check against.
2.  Rountrip Test Importing + Exporting should result in the same library 


 https://github.com/JabRef/jabref/blob/748b0eeaa8dedc07c872fe535bef3bf31298f1b1/src/test/java/org/jabref/logic/exporter/MSBibExportFormatFilesTest.java

**Comment by subhramit** [comment]
While exporting, these are the options that are available:
![Screenshot (226)](https://github.com/JabRef/jabref/assets/74734844/ccca426a-7e07-455f-9cf9-94639b6f15fa)

How to add Endnote (*.xml) to it?

**Comment by Siedlerchr** [comment]
Go the class of one Exporter, right-click on the class name ->  find usages. Then you will find out where it is called and where the other exporters are added.

Tip: Most stuff in jabref is grouped logically. e.g. all exporter stuff and importer stuff etc are under their corresponding packages.
