### ISSUE TITLE
Wrong warning message when importing duplicate entries

### ISSUE THREAD

**Issue by juanerasmoe** [JabRef/jabref#1115]
JabRef version 3.2 on Ubuntu 15.04

When importing duplicate entries, the warning message reads "There are possible duplicates (marked with a 'D' icon) that haven't been resolved. Continue?". However, the 'D' icon was replaced in the jabref 3.x+ and the message should be updated.

Steps to reproduce:
1. Create a new file and import an entry using the DOI to BibTeX feature in the web search.
2. Import the same entry

![jabref](https://cloud.githubusercontent.com/assets/12270743/14311538/c37cbac4-fbdf-11e5-8706-a692d331df03.png)

**Comment by stefan-kolb** [comment]
Thanks for our report!
