### ISSUE TITLE
mainStage is not transparent

### ISSUE THREAD

**Issue by AdamWysokinski** [JabRef/jabref#11150]
### JabRef version

5.13 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I think there is a problem with main stage transparency, causing white, non-transparent background to be visible under popups and the main window, see screenshot:
![scrot](https://github.com/JabRef/jabref/assets/42808557/70c07add-44cc-4ed3-ab6d-2d683453eba2)

I don't find myself competent enough to solve the problem, but my investigation has led to a potential conclusion that setting
```
mainStage.initStyle(StageStyle.TRANSPARENT);
```
in `openWindow()` in `JabRefGUI.java` could help. Could someone please check it a build a Linux binary for me to test it?

**Comment by Siedlerchr** [comment]
This is how your theme now looks on mac
<img width="686" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/41c63dda-e000-4fd5-92a2-ca1459152d4f">

I tried your stage style transparent, but this just removes the window decorated style:
e.g.
<img width="1601" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/c03b332a-df3a-4752-8edb-3c7354d16ce4">
 
Normal style
<img width="1614" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/1a7fa6bd-c1fe-4102-bbc9-dc5ae29aebe1">

**Comment by AdamWysokinski** [comment]
Thank you for the attempt and time spent on this problem. Seems like it's a Linux-related issue on my side. Will investigate further.

**Comment by AdamWysokinski** [comment]
I'll solved the problem. compton (xorg compositor was not running), hence there was no transparency. It works fine now.
