### ISSUE TITLE
Drag and dropping entries create a shallow copy

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#11160]
### JabRef version

5.13 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Drag and drop an entry E from library A to library B.
2. Modify entry E in library A.
3.  Select the entry that you just dropped in library B.
4. The entry in library B is changed even though we never modified it.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by JEANPRBT** [comment]
I'd like to tackle that issue, but when I try to drag and drop an entry **E** from library **A** to library **B** which is in another tab, nothing happens. Is this feature only available on GNU/Linux ? 

Maybe I do it the wrong way, can you tell me if I should drag and drop as follows ? 

https://github.com/JabRef/jabref/assets/66010389/1bae59ee-56b0-4d2f-8d2a-0edf9c50f5f5

**Comment by Arshadpd** [comment]
Hi, hope you are doing good!
Is this issue specific to Linux? I am trying to reproduce this in windows.

**Comment by HoussemNasri** [comment]
Hi, it should work on both Windows and Linux. I think there is another bug. I tried to drag and drop an entry and it doesn't always work. I'm trying to find the conditions where a drag-and-drop succeeds and when it fails.
