### ISSUE TITLE
Global Search - keep search term in Dialog window

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#11171]
Jabref has a very good option to keep the search term across different libraries:
If I search for "Klenk" I can search across libraries.
![Bildschirmfoto vom 2024-04-09 08-21-18](https://github.com/JabRef/jabref/assets/8830305/d392db26-561e-48a4-8b93-fda063d3b0ff)
.
.
.
.
However, if a user opens the global search dialog, the search term "Klenk" is erased and Jabref shows all results:
![grafik](https://github.com/JabRef/jabref/assets/8830305/eef8d8dd-b936-49d1-b6eb-79ef0d132149)

From a user perspective this is not straightforward. 

Are there any reasons that keep JabRef from using the search term that is already present in the search field?

Thanks

**Comment by Siedlerchr** [comment]
Refs https://github.com/JabRef/jabref/pull/11032 and https://github.com/JabRef/jabref/issues/11024 
@LoayGhreeb  Was it on purpose to clear the search term?

**Comment by LoayGhreeb** [comment]
After making this change, double-clicking on the global search becomes confusing (#11010). Here's what's happening:

When double-clicking on the global search, it clears the library search to ensure the entry gets selected.

1. Open the global search dialog.
2. Search.
3. Double-click on an entry:
	- The global search dialog closes.
	- The library search query gets cleared (if any).
	- The entry gets selected in the main table.
4. Reopen the global search.
5. The previous search query is lost - it should still be there.
