### ISSUE TITLE
Keywords: Keywordseparator is not recognized properly

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#11178]
### JabRef version

5.13 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Enter keywords and separate them by the keywordseparator
2. the keywords are handled as one long keyword including the separator
3. a proper behavior would be that after the separator is entered a new keyword is being presented.
4. In the sreen record, I enter two keywords that are in my keywordlist and separate the by a comma
[Bildschirmaufzeichnung vom 10.04.2024, 09:51:20.webm](https://github.com/JabRef/jabref/assets/8830305/bfbb0684-d607-4a99-b27e-9381ed8d0edf)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Behavior is correct. You don't need to enter the keyword separator. If you look at the bibtex source it will be automatically inserted
Enter first keyword -> Pres enter -> Enter next keyword -> Press enter

**Comment by teertinker** [comment]
Thank you very much for your response. This is indeed not a bug but a small usability issue. 
- The UX suggests, that I separate keywords by enter
- In Settings, however, I can enter a specific keyword separator
- The UX suggests that the string "Internet, Ethik" is one keyword (and the user did something wrong)
- In fact Jabref interprets the comma correctly and assigns the keywords "Internet" & "Ethik"
  - When I close the entry and open it again, Jabref makes "Internet, Ethik" to "Internet" & "Ethik" automatically
- From my point of view UX and handling of keywords should be in sync
  -  The best way from my point of view is to handle the char for the keywordseparator the same way as an enter. After entering a "," the string should be rendered as a complete keyword. In many Email programs is is handled this way. 
 
But afterall I have to admit, this "bugreport" is of very low priority, because it won't hurt after all.

**Comment by koppor** [comment]
@LoayGhreeb Can you investigate if the suggestion of the last bullet point is possible.
