### ISSUE TITLE
Missing right-click context menu in editor on secondary displays

### ISSUE THREAD

**Issue by pcdi** [JabRef/jabref#11174]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

macOS Sonoma 14.4.1 (23E224) / JabRef 5.14--2024-04-09--beb6ece

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

```
JabRef 5.14--2024-04-09--beb6ece
Mac OS X 14.4.1 aarch64 
Java 21.0.2 
JavaFX 22+30
```

1. Open the entry editor
2. Right-click into an entry field
3. No context menu shows. Previously, a context menu was available, showing "normalize to BibTeX name format" in author/editor fields or different capitalization options for title fields.

**Comment by Siedlerchr** [comment]
Just upgraded to macOS 14.4.1 and cannot reproduce with 5.13 release
Did you install the arm64 variant?

**Comment by pcdi** [comment]
After checking again, I found that the problem is apparently related to multiple displays: It occurs only if the JabRef window is not on the main display (as per macOS's display settings).

If the JabRef window is moved to a screen that is set to "extend desktop", then no context menu is shown. If the same JabRef window is moved to the "main display", however, then the context menu shows normally.

I tested with the dev version mentioned above as well as with
```
JabRef 5.13--2024-04-01--6bdcf63
Mac OS X 14.4.1 aarch64 
Java 21.0.2 
JavaFX 22+30
```
Both are arm64 (`aarch64`) variants.

**Comment by koppor** [comment]
I have issues with the main menus. They are positioned off the menu bar:

![grafik](https://github.com/JabRef/jabref/assets/1366654/8e2e8c52-7ffa-497e-a0a0-4b520fc0507e)

I can get it to work if I resize JabRef:

![grafik](https://github.com/JabRef/jabref/assets/1366654/ab5a6582-922b-4560-bf86-4fc1db1b9654)

Reproduce:

1. Windows 10
2. Have FancyZones (PowerToys) active
3. Have two monitors
4. Have 150% scale on monitor 1
5. Have 100% scale on monitor 2
6. Start JabRef. Move it to monitor 2.
7. Move JabRef Window to monitor 1 using drag and drop. Let FancyZones highlight the area. Pay attention that the window does not resize to 150% zoom while dragging
8. Drop
9. See 100% scaling kept for the window and the menus being off screen.

Workaround: Maximize JabRef and then drop it into the Zone of monitor 1. It keeps 150% scaling.

**Comment by koppor** [comment]
Related: https://github.com/JabRef/jabref/issues/10729

**Comment by Siedlerchr** [comment]
@pcdi  I was finally able to reproduce it and provide a fix. Can you test this version?
https://builds.jabref.org/pull/11324/merge 
Note that the build is not notarized (we only do this for releases) so you need to allow it to start in the security settings

**Comment by pcdi** [comment]
In version
```
JabRef 5.14--2024-06-03--109600b
Mac OS X 14.5 aarch64 
Java 21.0.2 
JavaFX 22.0.1+7
```
this is fixed for me.
