### ISSUE TITLE
Include good ideas of forks of JabRef

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#112]
Currently, the only active fork seems to be https://github.com/magsilva/jabref/commits/master

A first check revealed that following commits seem to be worth to be ported to JabRef
 * https://github.com/magsilva/jabref/commit/9bb2074de7a42765843ad3628c60d54a906e29c6
 * https://github.com/magsilva/jabref/commit/9475df8f90d4d9da5bf9f11223f635ae095067c3
  * Not everything can be taken: Generated code is included, special field "Quality" is removed

**Comment by lenhard** [comment]
I am not sure if these commits can be so easily ported, given the recent amount of changes in the upstream.

Otherwise this is fine by me. Just go ahead and merge anything you consider worth!

**Comment by lenhard** [comment]
I am closing this issue, since it is very vague and there is no current strategy for tackling it.

If there are concrete things to be done or ported, as in https://github.com/koppor/jabref/issues/44, this should be discussed in a separate issue.
