### ISSUE TITLE
Group selection underline not immediate

### ISSUE THREAD

**Issue by HainesB** [JabRef/jabref#1122]
In  older versions, when I put a new entry into a group, the group name was immediately underlined. Now to get the underline and thus assurance the item was in fact entered into the group, I have to click on that group and then All Entries. The older behavior is much preferable.

**Comment by simonharrer** [comment]
Ah, I think mistook it as a duplicate of #934, but I now think this was wrong. 

Steps to reproduce this issue
1. add an entry to a group
2. groups window does not show membership (is not being updated)
