### ISSUE TITLE
http exception should come with text

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#11223]
The UX when a network error occurs, should be improved.

Currently:

1. Create a new library
2. Select "Springer" in "Web search"
3. Search for "test"
4. Result: ![315947758-7a55a0b3-4c64-4301-bc3e-12436e175e69](https://github.com/JabRef/jabref/assets/1366654/3e473e1d-8ba3-4359-b85f-662f1c4e47e5)

Expanding the error results in 

![315948534-a3895c30-3c71-4479-98a3-ce5d5af502ed](https://github.com/JabRef/jabref/assets/1366654/9aeb4192-83c3-4b95-ac37-2ce611bc87d7)

## Tasks

- [ ] Expected output:

      HTTP error 403 occurred when fetching from {URL}.
- [ ] The secrets should be removed from the URL. (Currently, the key is shown. See screenshot; the blurred part)

---

Other place, where it works as expected (!)

1. I create an entry
2. Navigate to "General"
3. In the "File" field, "Download from URL"
    ![315949023-4486ff9a-dbd4-4955-b6b4-3a80489cea96](https://github.com/JabRef/jabref/assets/1366654/e6434ab4-ed4b-4f1d-a43f-e94fec143a3d)
7. I paste <https://www.researchgate.net/profile/Joanna-Kosinska-3/publication/344415012_Autonomic_Management_Framework_for_Cloud-Native_Applications/links/5f73246a458515b7cf567d65/Autonomic-Management-Framework-for-Cloud-Native-Applications.pdf>
8. Output
    ![315950767-9109ecde-af82-400d-abd6-d0a94edde851](https://github.com/JabRef/jabref/assets/1366654/e98a7d26-e691-44ff-815e-08687138aad8)

- [ ] If possible, also add the API key removal, here, too.

The log file of JabRef shows the full exception:

![315950983-aca228ed-2075-406e-814a-e9dc9b65dd39](https://github.com/JabRef/jabref/assets/1366654/16f711cd-9cc3-4020-9bf8-94a92500aa1a)

---

- Another example <https://www.researchgate.net/profile/Giuseppe-Muntoni-2/publication/344494377_Mining_the_Architecture_of_Microservice-Based_Applications_from_their_Kubernetes_Deployment/links/5f7c7b0b458515b7cf6a51bd/Mining-the-Architecture-of-Microservice-Based-Applications-from-their-Kubernetes-Deployment.pdf?origin=publication_detail>
- Discourse discussion: https://discourse.jabref.org/t/a-network-error-when-i-use-the-jabref-to-manage-my-references/4274

**Comment by RehanChalana** [comment]
I'd like to work on this issue, but I don't have a detailed plan yet. Could someone provide some guidance on the best way to approach this?

Thanks!

**Comment by koppor** [comment]
@RehanChalana I am not sure how I can help you. Could you reproduce the output? If yes, then search in the code where the output is generated, how it flows through the code. And where the HTTP error message is shown. If not, please explain at which step you could not follow.

**Comment by RehanChalana** [comment]
Yes i was able to reproduce the output and yes i am following the stack trace to understand the flow and the source of HTTP error.

Thanks for assistance

**Comment by RehanChalana** [comment]
I am able to change the output to 
![image](https://github.com/JabRef/jabref/assets/139042983/c82d838f-9e14-4bdf-8f74-8f221f654c96)

by implementing this small change in the org/jabref/logic/importer/SearchBasedParserFetcher.java while catching IOException


`  throw new FetcherException((e.getCause().getMessage() + " while fetching from " + `
 `  urlForQuery).replaceAll("api_key.*","api_key=REDACTED"), e);`
   
 Is this approach correct? Are there any potential issues or side effects I should be aware of?

**Comment by Siedlerchr** [comment]
Just check through the fetcher implementations, there might be other
parameters for api key

Rehan Chalana ***@***.***> schrieb am Sa., 6. Juli 2024,
15:41:

**Comment by RehanChalana** [comment]
They did , thank you for pointing this out.

In this case we can use a more general regular expression to check for potential parameters of api_key
` throw new FetcherException((e.getCause().getMessage() + " while fetching from " + urlForQuery).replaceAll`
`("(?i)(api[_-]?key)=.*","[REDACTED]"), e);`

This will make sure api is not exposed with different cases and formats (e.g., "api_key", "ApiKeY", "API-KEY", etc.) 

I was able to reproduce the issue with other fetchers by selecting "Use Custom Key" and setting it to random value 

![image](https://github.com/JabRef/jabref/assets/139042983/eb5dea81-2ee6-4efc-b98d-03453e869786)
 

Output: 
![image](https://github.com/JabRef/jabref/assets/139042983/e648fd52-42b0-4a37-83dc-193e05ff5514)

![image](https://github.com/JabRef/jabref/assets/139042983/c440d4c4-8b14-435d-9287-92a3461a6730)
