### ISSUE TITLE
the latest release 5.13 can't running on MacOS Mojave

### ISSUE THREAD

**Issue by lihongweimail** [JabRef/jabref#11226]
### JabRef version

5.13 (latest release)

### Operating system

macOS

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. the latest release 5.13 can't running on MacOS Mojave, it is only the release 5.11 can running. 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Since Version 5.12 JabRef requires macOS 11 or later
This was written in our blog post https://blog.jabref.org/2023/12/24/JabRef5-12/#important-information
