### ISSUE TITLE
 Make External Changes Resolver dialog scrollable

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#11220]
The box in the "External Changes Resolver" should be scrollable

1. Create a new library with a few groups and assign some entries to them
2. Outside of JabRef, open the bib file in a text editor, scroll down to the end of JabRef and modify the group structure, e.g., change the group name or add new group by copy and paste
3. Wait for the dialog "This library has been modified by another program"
4. Click on Review Changes
5.  See the metadata like in the screenshot

![image](https://github.com/JabRef/jabref/assets/1366654/fde6d2b8-c813-4f18-9215-b7697de9133e)

**Comment by aaronphilip19** [comment]
Hey, @sambujangfofana and I are students from the University of Michigan. We are currently working on a project wherein we have to contribute to a Github repository(https://eecs481.org/hw6.html). We are pretty interested in this issue and would want to work on it. We hope to submit a pull request this week. Could we be assigned this issue?

**Comment by ThiloteE** [comment]
@aaronphilip19 are you still on it or can I unassign you?

**Comment by abimael-turing** [comment]
@ThiloteE Can I work on this issue?

**Comment by aaronphilip19** [comment]
> @aaronphilip19 are you still on it or can I unassign you?

Hi, we weren't able to solve it so you can unassign me.

**Comment by alexandre-cremieux** [comment]
Hello @koppor and @ThiloteE . Is help still wanted for this issue ? If so, could you please assign it to me ?

I made some investigation and was able to make the `Metadata change details` view scrollable and to wrap the text in the `Group change details` view.

I also see a **_TODO_** in the `DatabaseChangeREsolverFactory` concerning pattern matching. As Java 21 is now proposing it, would you like me to give it a try by the same way (for instance, I split the work in two commits for the review).

**Comment by ThiloteE** [comment]
Thanks for your interest. Yes, two separate commits/pull-requests are fine.

**Comment by alexandre-cremieux** [comment]
Thanks for you answer @ThiloteE. Just to be clear about what you would like :

* two separate commits in same pull request
* or two different pull-requests (one for this issue, the other one for the **TODO** related to pattern matching)

**Comment by ThiloteE** [comment]
To be honest, I think either one is fine. As long as you have a good commit message that summarizes and lists both features it should be fine, if its in one PR, but obviously in case the pull-request becomes rather large, then disentangling the two might be better for debugging and reviewing. Also, two distinct features will be introduced, thereby having two separate commits is fine. I don't have a strong opinion on this. Your choice.

**Comment by alexandre-cremieux** [comment]
Okay, then I will open one PR and let you comment it. If needed, I will split it later. Thanks.
