### ISSUE TITLE
Keep search string across library shows "No results found" even there are entries in the other library

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11267]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

mac os 14.4.1 latest jabref dev version 

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create or open a new empty 
2. Open jabref-authors bib file
3. Search for e.g. "Kopp"  
4. Activate option "Keep search string across library" (the globe icon)
5. Search results say "No results found" 
6. Switch tabs and see that there are many results in the second library

Switching back and forth does not change 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by LoayGhreeb** [comment]
Oh, that was my fault in #11032.

```diff
- this.stateManager.activeDatabaseProperty().addListener((obs, oldValue, newValue) -> stateManager.activeSearchQueryProperty().get().ifPresent(this::updateSearchResultsForQuery));

+ this.searchQueryProperty.addListener((obs, oldValue, newValue) -> searchQueryProperty.get().ifPresent(this::updateSearchResultsForQuery));

```
