### ISSUE TITLE
Selected group loses focus after paste doi

### ISSUE THREAD

**Issue by Yery** [JabRef/jabref#11269]
JabRef 5.14--2024-04-30--4f87740
Windows 11 10.0 amd64 
Java 21.0.2 
JavaFX 22.0.1+7

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select a group
2. Copy a doi from somewhere 
3. Click anywhere in the table and paste, jabref will correctly create a new entry with the selected group assigned
4. Copy another doi from somewhere
5. Click anywhere in the table and paste, jabref will create a new entry but not assigned to the group. In fact it will not show up in "all entries" immediately, and one needs to click a few random groups back and forth, until that works. But still, the new entry is not assigned to the group that was selected first.

Note: 
This is related to issue #8933, it seems that after the first copy-paste in both instances, the group is somehow "deselected", even though it is still shown as selected.
Issue  #11085 might be related too

**Comment by Siedlerchr** [comment]
Thanks for the report, will be fixed by https://github.com/JabRef/jabref/pull/11271

**Comment by Yery** [comment]
Great thanks a lot! Does it fix issue #8933 too?

**Comment by Siedlerchr** [comment]
You can test this version https://builds.jabref.org/pull/11271/merge

**Comment by Yery** [comment]
I just tried it and can confirm that it fixes all three related issues #8933, #11271 and #11085! Thanks again.
