### ISSUE TITLE
No links to PDF since 3.2 upgrade

### ISSUE THREAD

**Issue by instantname** [JabRef/jabref#1129]
I am unable to have my entries autolinked by their BibTeX key. For instance, the file with name "test16.pdf" will not be found for the entry with name "test16", although the 
"Main file directory" is set correctly.

The problem appeared when upgrading from 2.10 to 3.2.

It can also be reproduced on a clean installation of Jabref 3.3 or Jabref 3.3dev--snapshot--2016-04-06--master--6488cf7, by following the steps below. The OS is Windows 10.

1. Delete old preferences by deleting the following registry key:

  HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\net\sf\jabref

2. Create a database with an entry:

@Article{test16,
  author  = {Smith},
  title   = {Title},
  journal = {Jour},
  year    = {2016},
}

3. Save database to C:\Users\User\Documents\database.bib

4. Create folder C:\Users\User\Documents\pdf and put there a test16.pdf file.

5. In the Preferences, under the "External programs" section, set the Main file directory to the pdf folder above, and click on "Autolink only files that match the BibTeX key".

6. Here is the unexpected behaviour: When right-clicking on the entry, "Open file" stays disabled as if no PDF has been found.

**Comment by stefan-kolb** [comment]
You need to search for these files first and link them before trying to open them in step 4.
Either via `Quality-Synchronize file links` for all entries. Or select an entry and `Quality- Automatically set file links`. The same is also available when you use the `Auto` button next to the file field inside the general tab of the entry editor view.

**Comment by instantname** [comment]
Yes, this work. This was just a change of behaviour between the two versions, which I assume is expected.
