### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#113]
This issue is used to collect requirements to the new UI. I will incorporate updates in this text. To keep the comment list small, I will delete the comment if it is included fully in this text.

If someone volunteers, I would suggest to draft a UI using [Pencil](http://pencil.evolus.vn/).

## General idea
* Ribbon-based UI based on use cases: information collection, paper writing, making camera ready version

## Different types of BibTeX files
See #160

## Nicer table layout
sci [suggests](http://sourceforge.net/p/jabref/mailman/message/34519834/) two have the journal title rendered in two lines [similar to Mendeley](http://img.informer.com/screenshots/4373/4373562_1.jpg).

## Should also work at unusual setups
* JabRef should present clean colors when using [High Contrast White color scheme](https://sourceforge.net/p/jabref/bugs/653/)
* [11in tablet](https://sourceforge.net/p/jabref/bugs/1255/)
* 3840x2160 pixels under Gnome 3; HiDPI. See also [thread about HiDPI support on jabref-users](
https://sourceforge.net/p/jabref/mailman/jabref-users/thread/CAPMKG4CoXgAPXTKtnSwxWvXAKrCHQy8oXk0NetXVYiZVZS46Ag%40mail.gmail.com/#msg34472086).

## Implementation
* It should be implemented using JavaFX.
* For icons see #230.

**Comment by tobiasdiez** [comment]
Some libraries which might be helpful:
[Undecorator](https://github.com/in-sideFX/Undecorator) Get rid of the window border
[FXRibbon](https://github.com/dukke/FXRibbon) Ribbon

**Comment by kubovy** [comment]
One idea: What about HTML + CSS + JS. JavaFX application with ribbon and other modern elements, where some elements (e.g. main sidebar, main table, ...) are browsers and the content is done using HTML technologies. There is WebView with WebKit engine in JavaFX. In the future JabRef may provided as a webapp and accessible using tablets, etc. On desktop the user may not notice the difference if done correctly.
