### ISSUE TITLE
Improve arxiv parsing

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#11306]
### JabRef version

5.13 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Have an entry with fields `note: arXiv: 1503.05173 version: 1` and `institution: arxiv` and `eid: arXiv:1503.05173`
2. Run cleanup entries with "Move preprint information from 'URL'  and 'journal' field to the 'eprint' field"
3. Entry is not changed.

Instead, one would expect that the information in these fields is also moved to the correct information in the `eprint*` fields.

![image](https://github.com/user-attachments/assets/ca408a35-b818-4e40-a2ee-5d9dfdfb2b10)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by narasimhareddyputta94** [comment]
Hi @tobiasdiez, I would like to work on this issue. Could you please assign it to me? Thanks!

**Comment by koppor** [comment]
One needs to adapt `EprintCleanup`.

**Comment by 18bce133** [comment]
Hi @koppor  I have made the necessary changes to address this issue in my forked repository. Could you please assign this issue to me? I would like to raise a pull request for the changes.  Thank you!

**Comment by koppor** [comment]
> Hi @koppor I have made the necessary changes to address this issue in my forked repository. 

Deep link: https://github.com/JabRef/jabref/compare/main...18bce133:jabref:fix-11306

> Could you please assign this issue to me? I would like to raise a pull request for the changes. Thank you!

You can submit a PR without being assigned.

I think, the eprint field needs to contain more information.

**Comment by koppor** [comment]
@tobiasdiez Can you please detail which information you expect in the `eprint` field? Is there any description of the syntax?

The current proposal just sets `1503.05173` and drops institution and version. I don't think, this is expected. Is it?

**Comment by tobiasdiez** [comment]
> @tobiasdiez Can you please detail which information you expect in the `eprint` field? Is there any description of the syntax?
> 
> The current proposal just sets `1503.05173` and drops institution and version. I don't think, this is expected. Is it?

Eprint should be just the id perhaps with the version (e.g. `1503.05173v2`), "arxiv" should be in eprinttype. See https://tex.stackexchange.com/questions/49757/what-should-an-entry-for-arxiv-entries-look-like-for-biblatex

**Comment by 18bce133** [comment]
Hello @tobiasdiez and @koppor,
I've implemented the requested changes to ensure the Eprint field contains the ID along with the version. I've submitted a pull request with these modifications. Could you please review the PR and the code changes? I'm open to any feedback or suggestions for further improvements if needed.
Thank you for your guidance on this issue.
