### ISSUE TITLE
Context menu in entry editor displayed on primary screen (jfx 23)

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#11323]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.14--2024-05-20--7dce65a Linux 6.1.0-21-amd64 amd64  Java 22.0.1  JavaFX 23-ea+18

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I'm using i3 and saw that the context menu in the entry list is shown on the same screen as JR. But, interestingly, the context menu for a field in the entry editor is shown on the primary screen, not on the one where JR resides, see the attached screenshot. 
![jr-fx23-screen-menu](https://github.com/JabRef/jabref/assets/25365609/ea24549d-f282-4c65-9646-8cca3812aa54)

1. Open JR, move it to an external screen.
2. Create an entry and open the context menu of the entry in the list: should be shown next to the mouse pointer.
3. Click into, e.g., the title field and open the context menu: it is shown in a bottom corner of the primary screen, but not next to the mouse pointer.
4. Click into the search field at the top and open a context menu: should again be shown next to the mouse pointer.

I wonder whether this is a JavaFX GUI framework issue, or whether the rendering of context menus can be individually controlled by the programmer. In the latter case, there could perhaps be an easy fix.

**Comment by Siedlerchr** [comment]
Okay, I think I found the issue, at least under mac it's working now....

Back in the early days we introduced this in  https://github.com/JabRef/jabref/pull/5352

**Comment by Siedlerchr** [comment]
Can you test this version? https://builds.jabref.org/pull/11324/merge
Note that this only fixes the context menus for the entry editor and still uses the older javafx

**Comment by ytzemih** [comment]
Moin @Siedlerchr, great, that one works: Context menus are at the right place. Sometimes, evil workarounds have their rationale ;)
