### ISSUE TITLE
Jabref does not use font size stored in user preferences $HOME/jabref.xml on startup

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#11344]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04 with Gnome

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Jabref does not remember user font size selected in the File --> Preferences --> General  `Override default font Size` box on new startup.

Version:
 JabRef 5.14--2024-05-27--e1da33d
Linux 5.15.0-107-generic amd64 
Java 21.0.2 
JavaFX 22.0.1+7

Steps to replicate behavior:
1. File --> Preferences --> General  `Override default font Size` with say 15 and save preferences.
2. User preferences in Jabref.xml stored in $HOME/Jabref.xml switches the following line:
` <entry key="mainFontSize" value="15"/>` to 15 and in Jabref itself the font size becomes larger as expected.
3. On restart I would expect the font size to be 15.  However, Jabreft defaults to a smaller font size of 12 and ignores the font size stored in $HOME/Jabref.xml
4. Opening File --> Preferences --> General  still shows font Size of 15 stored in $HOME/Jabref.xml but Jabref seems to ignore that.
5. If user wants to have larger font, you have to repeat the process:  File --> Preferences --> General  `Override default font Size` with say 14 or 16 and save preferences in order for Jabref to increase the font. On restart, this setting is lost again.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
@juejung It seems you have portable mode activated, because `jabref.xml` is only written in that case. (See https://github.com/JabRef/user-documentation/issues/489 for a link to the documentation and the current UI)

**Comment by juejung** [comment]
@koppor You are correct but the same behavior happens if I am not in portable mode. I just got desperate and tried other options. 
Another issue (probably a separate one) is that if I change the preferences to the larger font and then export these preferences to a file. A subsequent import of these user preferences (with the larger font) is also ignored. On import of the user preferences it simply shows the message that "You must restart JabRef for this to come into effect." But on restart we are back to the small font?
So for some reason the font settings are ignored on restart. I noticed it first when the Groups window size setting kept being ignored as well. On restart it now always occupies 50% of the screen. It seems to me that these might all be related issues where Jabref just ignores saved user preference settings on restart.

**Comment by Siedlerchr** [comment]
This is weird, I have overriden font size on mac enable as well and it seems to work fine

**Comment by Siedlerchr** [comment]
I could reproduce it now

**Comment by Siedlerchr** [comment]
The issue is now resolved in the latest dev version!

**Comment by juejung** [comment]
@Siedlerchr Can confirm it is now fixed. That was quick, thank you much.

**Comment by Siedlerchr** [comment]
Thanks for your generous donation and thanks for reporting.
