### ISSUE TITLE
Unable to import *.ris file

### ISSUE THREAD

**Issue by AlexanderZ11234** [JabRef/jabref#1134]
JabRef version "JabRef_windows-x64_3_3dev--snapshot--2016-04-06--master--6488cf7" on Windows 10

I cannot import *.ris files with the message in the lower left corner: "Status: Could not find a suitable import format".

But I remember that version 3.2 is free of this problem.

**Comment by oscargus** [comment]
Try the latest master available in 15-20 minutes or so. Sorry about that.

**Comment by purplewakanda** [comment]
The same issue exists in the current version
