### ISSUE TITLE
Devdocs don't have favicon

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#11369]
**Is your suggestion for improvement related to a problem? Please describe.**
There is no favicon on [devdocs](https://devdocs.jabref.org). 

**Describe the solution you'd like**
Put JabRef logo on devdocs website?

**Comment by InAnYan** [comment]
Hmm, I've run the docs project with jekyll local server, and it seems it has a favicon

**Comment by koppor** [comment]
Please provide a screenshot of your locl development version.

Our framework is https://github.com/just-the-docs/. One needs to check the configuration of the favicon https://just-the-docs.com/docs/configuration/#site-favicon.
