### ISSUE TITLE
Rebuild fulltext search index not working

### ISSUE THREAD

**Issue by amaxi99** [JabRef/jabref#11374]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

macOS 14.5 (also in Windows 11)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

- trigger "Rebuild fulltext search index" from the menu
- dialog "Rebuild fulltext search index for current library?" pops up
- confirm
- nothing happens, no index is built (empty directory ~/Library/Application Support/jabref/lucen/99/) 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
@LoayGhreeb

**Comment by koppor** [comment]
Please start JabRef in debug mode and check the log.Maybe something useful is contained.

https://docs.jabref.org/advanced/commandline

**Comment by amaxi99** [comment]
here is the debug-logfile

[log_2024-06-13_17-06-23.txt](https://github.com/user-attachments/files/15822736/log_2024-06-13_17-06-23.txt)

**Comment by koppor** [comment]
Issue https://github.com/JabRef/jabref/issues/11378 seems to contradict this one.

**Comment by koppor** [comment]
Also happens with v5.13:

```
ERROR: Could not initialize the IndexWriter: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: C:\Users\koppor\AppData\Local\org.jabref\jabref\lucene\99\35eb99eb--koppor-bibliography.bib\write.lock
        at org.apache.lucene.core@9.10.0/org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:126)
        at org.apache.lucene.core@9.10.0/org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43)
        at org.apache.lucene.core@9.10.0/org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44)
        at org.apache.lucene.core@9.10.0/org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:953)
```
