### ISSUE TITLE
(FR) Please provide official FlatPak for JabRef

### ISSUE THREAD

**Issue by zWhdmB5T** [JabRef/jabref#11372]
Dear all,

there is a [JabRef FlatPak](https://flathub.org/apps/org.jabref.jabref) available. Unfortunately, it is not officially maintained like others (e.g. [Firefox FlatPak](https://flathub.org/apps/org.mozilla.firefox), [LibreOffice FlatPak](https://flathub.org/apps/org.libreoffice.LibreOffice) or [digiKam FlatPak](digiKam)).

I would appreciate that very much. I expect high security as well as an up-to-date release (including all used libraries and such) of an official package.

Thank you!

**Comment by zWhdmB5T** [comment]
Because one could counter that the examples of officially maintained FlatPaks mentioned above are not _community driven_ (i.e. a single persons or just a few ones) but maintained by an organisation resp. a company, here are other examples:

- [KeePassXC](https://flathub.org/apps/org.keepassxc.KeePassXC) (community)
- [Strawberry Music Player](https://flathub.org/apps/org.strawberrymusicplayer.strawberry) (solo)
- [fre:ac](https://flathub.org/apps/org.freac.freac) (solo)
- [FSearch](https://flathub.org/apps/io.github.cboxdoerfer.FSearch) (solo)
- [Qalculate! (GTK UI)](https://flathub.org/apps/io.github.Qalculate) (solo)
- [Metadata Cleaner](https://flathub.org/apps/fr.romainvigier.MetadataCleaner) (solo)

**Comment by ThiloteE** [comment]
How do you know it isn't officially published by JabRef?

But you are right, the flatpak is nowhere linked to in the official documentation, nor on JabRef's website.
At https://docs.jabref.org/installation you can see the flatpak is mentioned:

![image](https://github.com/JabRef/jabref/assets/73715071/7607c232-4bef-413c-9896-9c40224cc9b5)

**Comment by Siedlerchr** [comment]
As far as I know, @LyzardKing is more or less the maintainer of the flatpak.

**Comment by zWhdmB5T** [comment]
Er, well, I actually don't know it. But I have assumed it. [JabRef FlatPak](https://flathub.org/apps/org.jabref.jabref) looks significantly different from [KeePassXC FlatPak](https://flathub.org/apps/org.keepassxc.KeePassXC)
![Bildschirmfoto_2024-06-13_12-35-04](https://github.com/JabRef/jabref/assets/143814533/d5d4ff7d-1f38-49b4-8d6d-00ca6052c044)
![Bildschirmfoto_2024-06-13_12-35-15](https://github.com/JabRef/jabref/assets/143814533/c696e816-71b3-4c64-a5bb-b9b1e8af1d4b)

**Comment by ThiloteE** [comment]
I know flathub prefers it, if flatpaks are published and maintained by the original authors/organisations of an app.
@LyzardKing wanna join one of our devcalls to talk about attribution?

**Comment by zWhdmB5T** [comment]
@ThiloteE Thank you for asking @LyzardKing!

**Comment by LyzardKing** [comment]
I'm not sure what would make the flatpak (or the snap for that matter) official or not. I built and roughly maintain both, and I worked on the jabref web extension. All the work I did was in contact (and collaboration) with members of the jabref team, and everything lives under the jabref github group (although the flatpak was moved to the flathub repo for publishing).
I'm happy to join a devcall and discuss anything else that can/should be done on this.

**Comment by Siedlerchr** [comment]
Thanks, I think we just need to follow the steps here  https://docs.flathub.org/docs/for-app-authors/verification  and link it with our website to mark it as verified. 
When I see this right, you should be able to do this and we have to put the token into the web root of our website...

**Comment by LyzardKing** [comment]
@Siedlerchr
As far as I can tell all that is needed is to create a page at `https://jabref.org/.well-known/org.flathub.VerifiedApps.txt` with a token that I can request.

**Comment by LyzardKing** [comment]
The PR on the website should be enough for the verification.

**Comment by LyzardKing** [comment]
I pushed the button on the flathub website, so it should be verified now.
It might take some time to update

**Comment by Siedlerchr** [comment]
Seems to have worked now 
![Screenshot_2024-06-15-12-39-54-877_org mozilla firefox-edit](https://github.com/JabRef/jabref/assets/320228/43b643ff-dea5-40aa-9e0b-dd0c3bac9113)

Thanks for the quick action @LyzardKing

**Comment by zWhdmB5T** [comment]
Goody! Thank you for your effort!

**Comment by ThiloteE** [comment]
Thanks! That was fast 👍
