### ISSUE TITLE
Number of indexed files grows after reindexing action

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#11378]
### JabRef version

5.13 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Look at the background tasks. There will be status of full-text indexing. In this status you will see "N of M files were added to the index".
2. Perform "Rebuild full-text search indexing" action (through main menu -> Tools -> "Rebuild full-text search indexing")
3. Now, the `N` number will be zeroed, but `M` will be greater than it was.

As I understand, `M` should stay either constant or get bigger or smaller if the user added or removed entry from library.

### Appendix

I don't have a big library with linked files to test it thoroughly.

But I found this bug, when I was implementing my own "linked file processing" logic. I was copy-pasting (not exactly true) from `PdfIndexer` code (and other classes), and I have found that the variable `numOfIndexedFiles` in `IndexingTaskManager` class was never decremented or unchanged when calling the `rebuildIndex` method.

**Comment by koppor** [comment]
Will be fixed in https://github.com/JabRef/jabref/pull/11326
