### ISSUE TITLE
Good resource if we want to add more search engines

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1141]
http://guides.lib.berkeley.edu/information-studies/apis

Several can be rather directly realized, e.g., Nature.

**Comment by tobiasdiez** [comment]
And here is an overview of some important reference databases: http://www.biochem.mpg.de/en/facilities/ivs/AccessDB

**Comment by lenhard** [comment]
As part of housing keeping, I am moving this rather open ended list of things to the forum: http://discourse.jabref.org/t/resources-for-search-engines/95

Feel free to bash me for it :-)
