### ISSUE TITLE
Activated menus ==> no text displayed

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1145]
JabRef-3.3dev--snapshot--2016-04-07--master--b40a0d2.jar
on Linux Mint
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

When activating "View -> Toggle group interface", the text "Toggle group interface" is not displayed anymore (or text and background have the same color?).
Same behavior for similar menu items: "View -> Toggle group interface" and "Groups -> Disable highlight group matching entries".

![ifselectednotextdsiplayed](https://cloud.githubusercontent.com/assets/6931104/14367263/41312314-fd17-11e5-8c3f-f534233be8c5.png)

Occurs with the default look and feel only (com.sun.java.swing.plaf.gtk.GTKLookAndFeel), not with the others (com.sun.java.swing.plaf.motif.MotifLookAndFeel, javax.swing.plaf.metal.MetalLookAndFeel and com.jgoodies.looks.plastic.Plastic3DLookAndFeel). 

Nothing in console.

**Comment by simonharrer** [comment]
Seems to be a bug on Linux of this specific look and feel. I am unsure whether we can really solve this without giving up the toggle feature and creating platform specific code. I would suggest that we ignore this.

**Comment by stefan-kolb** [comment]
Is this also on OpenJDK and GTK L&F? Maybe we can close this then.
