### ISSUE TITLE
The update available in https://www.fosshub.com/JabRef.html?dwl=JabRef-5.14.pkg# is not for Macbook with Intel processor

### ISSUE THREAD

**Issue by cpsychal** [JabRef/jabref#11468]
### JabRef version

5.14 (latest release)

### Operating system

macOS

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Can you give some more details please? Do you get an errro message?
Can you test the version from github? https://github.com/JabRef/jabref/releases/tag/v5.14

**Comment by Siedlerchr** [comment]
Thanks, I now found the issue, github changed the default runner image to macos-latest on arm64 argh!
We will do a new release shortly 

I have triggered a build with notarization so you can try the latest dev version roughly in half an  hour https://builds.jabref.org/main/

**Comment by Siedlerchr** [comment]
We will make a new release tomorrow probably

**Comment by cpsychal** [comment]
Perfect!Many thanks for resolving this issue. All the best Costas10 Ιουλ 2024, 00:29, ο χρήστης «Christoph ***@***.***>» έγραψε:﻿
We will make a new release tomorrow probably
