### ISSUE TITLE
MacOS Intel download 5.14 contains ARM binary

### ISSUE THREAD

**Issue by suschizu** [JabRef/jabref#11475]
### JabRef version

5.14 (latest release)

### Operating system

macOS

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

`file /Volumes/JabRef/JabRef.app/Contents/MacOS/JabRef `

`/Volumes/JabRef/JabRef.app/Contents/MacOS/JabRef: Mach-O 64-bit executable arm64`

the download https://github.com/JabRef/jabref/releases/download/v5.14/JabRef-5.14.dmg contains an ARM binary

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Sorry for the inconvenience, will be fixed by #11474
We will release a new version shortly!

**Comment by Siedlerchr** [comment]
I have triggered a build with notarization so you can try the latest dev version roughly half an  hour https://builds.jabref.org/main/

**Comment by suschizu** [comment]
hey @Siedlerchr - many thanks for the fast fix <3

**Comment by Siedlerchr** [comment]
Thanks for reporting that issue, as I have an arm mac it totally slipped through 🤦 
It turned out that GitHub now uses arm runner by default for macOS-latest instead of the intel ones...
