### ISSUE TITLE
Include PMID in PubMed imports

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#11488]
The MEDLINE importer does not include PubMed IDs (PMID) when importing from PubMed text files.

This is problematic for two reasons:
1. PMID is an important identifier
2. JabRef includes PMID when importing via API, so the behavior is inconsistent

PubMed records also have an NLM unique identifier that JabRef imports, but this is not the same as the PMID and does not substitute for it. MEDLINE records produced by sources other than PubMed tend to include the PMID and not the NLM identifier, so the PMID is more useful for merging and deduplicating entries in JabRef. The PMID can also be used to visit the record on PubMed, fetch additional data, and so on.

The MEDLINE importer should include the `PMID` element from pubmed/medline files.

See [MEDLINE/PubMed Data Element (Field) Descriptions](https://www.nlm.nih.gov/bsd/mms/medlineelements.html) for information about the elements included in PubMed text files.

**Comment by ryan-carpenter** [comment]
https://github.com/JabRef/jabref/blob/7e4e7d3fba39ed6c1813a522c3fac3e454165c8b/src/main/java/org/jabref/logic/importer/fileformat/MedlinePlainImporter.java#L145-L168

**Comment by ryan-carpenter** [comment]
Is this all it would take to resolve the issue?
```
hashMap.put("PMID", new UnknownField("pmid")); 
```

**Comment by Siedlerchr** [comment]
Yes, that should be enough. You can do it through the github UI (just click on Edit File). You might need  to adjust the MedlinePlainImporterTest as well if it fails but CI will tell you that :)
