### ISSUE TITLE
Blank lines between required and optional fields

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#115]
JabRef 2.10 introduced a new serialization format, where there is a line break between required and optional field. That is strange for some users. Should we keep that behavior, make it configurable or drop it? Should we generally rethink the serialization?

Bug reports at sourceforge: 
* https://sourceforge.net/p/jabref/bugs/1260/ (blank lines always added)
* https://sourceforge.net/p/jabref/bugs/1173/ (blank line sometimes added, not always)

**Comment by stefan-kolb** [comment]
1. Hm, personally I don't see any real benefit by introducing a blank line to separate mandatory and optional fields. This should be solely managed by JabRef. Therefore, I vote for a removal of this behaviour.

2. About serialization: I don't know if we have any other arguments to change the serialization. If not I would just revert the empty line behaviour.

**Comment by johanvanr** [comment]
1. I agree with stefan-kolb.
As an additional argument (may be quite personal):
The "required" fields in a reference as printed in a journal (for example) may well differ from those used in JabRef, making the latter somewhat arbitrary. For practical use in the JabRef GUI, the current approach is nice. In the *.bib files (etc.), I would prefer one block of lines per entry instead of blank lines at "arbitrary" locations.

2. I have no opinion, except maybe: Keep it simple.

**Comment by koppor** [comment]
@johanvanr What about the ordering of the fields within the entry? They might be perceived as arbitrary, too? We currently write out the title, then the required fields in alphabetical order, and then the optional fields. For me, that was always OK. Without a blank line inbetween, it might get confusing.

**Comment by johanvanr** [comment]
@koppor: At this moment, the current approach for the field ordering seems fine to me. I do not mind a blank line and then an alphabetic restart. However, I would not like it if, for example, the (relatively long) "Abstract" comes before the "author", "year", etc. Apart from that, an alphabetic order has never been required by any *.bib-file processing code as far as I know (but my experience is too small to make a generically valid statement about that).

**Comment by lenhard** [comment]
4330d94044a4dbc1d4e035a2895dd0ca380452e4 removes the blank line between required and optional fields.

@koppor: You can close the bug reports on source forge. Further discussion can carry on here.

**Comment by stefan-kolb** [comment]
Fixed by 4330d94044a4dbc1d4e035a2895dd0ca380452e4.
Please refer to #116 for discussion about the serialization format.
