### ISSUE TITLE
Minimal support for biblatex data annotations

### ISSUE THREAD

**Issue by odneill** [JabRef/jabref#11505]
Biblatex defines [data annotations](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf#subsection.3.7), which allow extra information to be added to fields i.e. adding corresponding author marks.

E.g.
```bibtex
@Article{
  author     = {Joe Doe and Mary Jane},
  author+an  = {1=corresponding; 2=highlight},
}
```
can be used to produce "Doe*, J. & **Jane, M**", given appropriate formatters for the various annotations.

Currently using `\author+an` in a `.layout` results in "Joe Doe and Mary Jane+an" rather than "1=corresponding; 2=highlight".

Minimal support (to access annotation during exports):
- Support in the `.layout` definitions to handle fields with special characters `+:`. 

Full support would need a scheme for parsing and using this information for formatting in custom `.layout` files.

**Comment by koppor** [comment]
@odneill Thank you so much for posting the issue and providing a fix!

Seeing that you work with .layout files, may I ask for your take regarding https://github.com/koppor/jabref/issues/392 😅

**Comment by odneill** [comment]
Hi @koppor, I'll be honest I currently only use layouts in one specific case, which is a bit of a hack anyway - filtering an existing .bib into a "cleaned" .bib with extra fields/ metadata removed. As such I don't have any experience with using the custom formatting/ awareness of the historic choices in the layout system.

From working on this PR I would definitely agree that an established templating engine would improve ease of use and stability. My fix here would break in the case of someone writing a layout which "looks like" a data annotation i.e. something like `month=\month:year=\year` would look up field `month:year`. I don't currently have a good solution to this which doesn't break existing layouts, other than relying on it being unlikely syntax.

At minimum in the current system, having a lookup function `\lookup{author}` as opposed to `\author` would make parsing more robust. This could be opt in for backwards compatibility, and revert my changes here so you would be required to use the lookup function for fields with special characters, like data annotations.

**Comment by odneill** [comment]
@koppor Thanks, all great references. #160 seems like exactly what I mean. I already use JabRef and it was just the quickest way I could get the result I wanted, and it's nice that export filters are scriptable through the CLI. I'm sure there are more elegant methods - always impressed by the rate at which new functionality is added here.
