### ISSUE TITLE
Black text in Dark mode inside "Citation information"

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#11512]
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Set theme to "Dark".
2. Select a bib entry.
3. Open "Citation information" tab

![изображение](https://github.com/user-attachments/assets/63905f11-87a7-427f-9f29-a9c6b9a267fc)

**Comment by InAnYan** [comment]
I wonder, what is the CSS class for text color?

I couldn't find it neither in `Base.css`, nor in `Dark.css`.

Then, how `Dark.css` make some text white?

**Comment by InAnYan** [comment]
To anyone who will resolve this issue, here is a little hint:

Try to determine, when text is colored properly and when it's not

**Comment by ankur-kalita** [comment]
Hi  @InAnYan  @Siedlerchr ,

I'd like to work on this issue. Could you please assign it to me?

**Comment by shivenducs1136** [comment]
Hi @InAnYan, 

This pull request is related to issue [#11578](https://github.com/JabRef/jabref/pull/11578). 

I've implemented the requested changes and would appreciate your review.

Thank you!
