### ISSUE TITLE
 HTML to LaTeX formatter should do proper escaping

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11531]
**Is your suggestion for improvement related to a problem? Please describe.**
When I use the HTML to LaTeX formatter, certain "forbidden" symbols like e..g % sign are not escaped. 

**Describe the solution you'd like**
In:

    Nutrition &amp; Metabolism

Out

    Nutrition &amp; Metabolism

Expected

    Nutrition \& Metabolism

**Additional context**

See the LateXCleanupFormatter for an inspiration
Write tests
https://github.com/JabRef/jabref/blob/1b35f8cb0040fdfb515974e78532598f07e11af2/src/main/java/org/jabref/logic/formatter/bibtexfields/LatexCleanupFormatter.java#L54

**Comment by AlessioBugetti** [comment]
Hi @Siedlerchr , I'd like to start contributing to the project.
```java
HtmlToLatexFormatter formatter = new HtmlToLatexFormatter();
formatter.format("Nutrition &amp; Metabolism");
```
the output is:
```
Nutrition \& Metabolism
```

Furthermore:

```java
formatter.format("Nutrition &amp; Metabolism");
```

the output is:
```
Nutrition \% Metabolism
```

I can't figure out what the issue is. Could you help me understand what needs to be fixed?

Thank you in advance!

**Comment by Kunal77689** [comment]
Hi @Siedlerchr, I can start working on it if it's still open

Thank you

**Comment by Siedlerchr** [comment]
Oh okay, thanks for testing and verfiying! Maybe I had sth wrong elsewhere. I close that issue.
