### ISSUE TITLE
aCESSBILTI BUG

### ISSUE THREAD

**Issue by Uchswas** [JabRef/jabref#11601]
### JabRef version

Other (please describe below)

### Operating system

macOS

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...DHDHD
2. ...DHDRH
3. ...DRHRHRDH

### Appendix

...
<details>

<summary>Log File</summary>
DRHDRHRH
```
Paste an excerpt of your log file here
```

</details>

**Comment by Uchswas** [comment]
MISTAKELY SUBMITTED

**Comment by koppor** [comment]
Background on accessibility and our used framework JavaFX: https://download.jonathangiles.net/downloads/presentations/2015/Accessibility.pdf
