### ISSUE TITLE
Use CircleCI only for building the binaries

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1164]
At the moment, gradle has issues with executing the tests on CircleCI due to 4GB RAM limit. I propose to use travis ci for testing and coverage analysis, and CircleCI for building the binaries only. 

The downside is that CircleCI can show test failures much better (travis ci only uses a textual representation whereas CircleCI parses the result xml and provides a nice result page).

**Comment by stefan-kolb** [comment]
#1169
