### ISSUE TITLE
"Save" button for preferences not functioning

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#11663]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.16--2024-08-20--6b8c5a3 Linux 6.8.0-40-generic amd64  Java 21.0.2  JavaFX 22.0.2+4

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.16--2024-08-20--6b8c5a3
Linux 6.8.0-40-generic amd64 
Java 21.0.2 
JavaFX 22.0.2+4

1. Open preferences
2. Change some stuff
3. Press "save".  Nothing happens.  Preferences are not saved.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by LoayGhreeb** [comment]
Fixed today: https://github.com/JabRef/jabref/pull/11661

**Comment by InAnYan** [comment]
@wujastyk Hi! Did you also have agreed to the AI privacy policy?

**Comment by wujastyk** [comment]
> @wujastyk Hi! Did you also have agreed to the AI privacy policy?

The change I made to preferences was in Preferences/Entry Editor , deselecting the two "Show AI ..." tickboxes.

**Comment by wujastyk** [comment]
JabRef 5.16--2024-08-22--4ab11ca
Linux 6.8.0-40-generic amd64 
Java 21.0.2 
JavaFX 22.0.2+4

PS Unticking the "Show AI Prefs" box doesn't stick.  See attempts below.

https://github.com/user-attachments/assets/8e190504-4839-49b4-9666-fb054a7936ab

**Comment by InAnYan** [comment]
Oh, I see, so turning off "Show AI Summary" button doesn't work.

Thank you for pointing this out! I'll fix it right away

**Comment by ThiloteE** [comment]
@wujastyk @InAnYan The issue is not yet fixed. We found another cause for it.
When you change the language settings from English to another language (e.g. German), some values in the AI settings are not transformed to the new language's grammar and then fail to have a default setting.

This is what is in my log:

```
C:\Prog\Development\JabRef_JabRef-JabRef\JabRef-JabRef\jabref>gradle run

> Configure project :
Project : => 'org.jabref' Java module

> Task :run
WARNING: Using incubator modules: jdk.incubator.vector
Messages are not initialized before accessing key: Display help on command line options
2024-09-02 20:44:08 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.addStylesheetToWatchlist()
INFO: Watching css C:\Prog\Development\JabRef_JabRef-JabRef\JabRef-JabRef\jabref\build\resources\main\org\jabref\gui\Base.css for live updates
2024-09-02 20:44:08 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2024-09-02 20:44:08 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=EMBEDDED, name='Dark.css'} with base css StyleSheet{file:/C:/Prog/Development/JabRef_JabRef-JabRef/JabRef-JabRef/jabref/build/resources/main/org/jabref/gui/Base.css}
2024-09-02 20:44:08 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.addStylesheetToWatchlist()
INFO: Watching css C:\Prog\Development\JabRef_JabRef-JabRef\JabRef-JabRef\jabref\build\resources\main\org\jabref\gui\Dark.css for live updates
2024-09-02 20:44:09 [pool-2-thread-1] org.jabref.logic.ai.models.UpdateEmbeddingModelTask.call()
INFO: Downloading embedding model...
2024-09-02 20:44:10 [JavaFX Application Thread] org.jabref.gui.StateManager.setActiveDatabase()
INFO: No open database detected
2024-09-02 20:44:12 [pool-2-thread-2] org.jabref.gui.JabRefDialogService.notify()
INFO: ´┐¢ffne: 'C:\server-t-150\Jabref & LatexTests\OneMillionEntries.bib'
2024-09-02 20:44:13 [pool-2-thread-2] org.jabref.gui.JabRefDialogService.notify()
INFO: ´┐¢ffne: 'C:\server-t-150\Jabref & LatexTests\test-Files.bib'
2024-09-02 20:44:13 [pool-2-thread-3] org.jabref.gui.JabRefDialogService.notify()
INFO: ´┐¢ffne: 'C:\server-t-150\Jabref & LatexTests\Chocolate.bib'
2024-09-02 20:44:14 [pool-2-thread-1] ai.djl.pytorch.engine.PtEngine.newInstance()
INFO: PyTorch graph executor optimizer is enabled, this may impact your inference latency and throughput. See: https://docs.djl.ai/docs/development/inference_performance_optimization.html#graph-executor-optimization
2024-09-02 20:44:14 [pool-2-thread-1] ai.djl.pytorch.engine.PtEngine.newInstance()
INFO: Number of inter-op threads is 12
2024-09-02 20:44:14 [pool-2-thread-1] ai.djl.pytorch.engine.PtEngine.newInstance()
INFO: Number of intra-op threads is 6
2024-09-02 20:44:15 [pool-2-thread-1] ai.djl.util.Platform.detectPlatform()
INFO: Found matching platform from: jar:file:///C:/Users/Thilo/.gradle/caches/modules-2/files-2.1/ai.djl.huggingface/tokenizers/0.29.0/edd38326d16523f2b8c2b1e360b896e7ae48a1fa/tokenizers-0.29.0.jar!/native/lib/tokenizers.properties
2024-09-02 20:44:17 [JavaFX Application Thread] org.jabref.logic.ai.models.JabRefEmbeddingModel.lambda$startRebuildingTask$0()
INFO: Embedding model was successfully updated
2024-09-02 20:45:14 [JavaFX Application Thread] org.jabref.logic.l10n.Localization.lookup()
WARN: Warning: could not get translation for "RAG min score must be greater than 0 and less than 1" for locale de
2024-09-02 20:45:15 [JavaFX Application Thread] org.jabref.logic.push.CitationCommandString.from()
INFO: Wrong indexes -1 -1 for completeCiteCommand \parencite. Using default delimiter and suffix.
```

Below are the missing defaults:
![image](https://github.com/user-attachments/assets/78ec693f-77dd-47e3-9a2c-4ed836e7f414)

Even when filling the settings, it does not accept what I enter, namely `0,3` and `0,7`. In German language, the comma is used as building blocks to [real numbers](https://en.wikipedia.org/w/index.php?title=Real_number&oldid=1242268041) (with the exception of integers, which are a subset of real numbers). In English language, one uses a dot (.).

![image](https://github.com/user-attachments/assets/b9673a89-2fff-4c09-af8b-860b1f0e00b6)

**Comment by InAnYan** [comment]
@ThiloteE thank you very much for finding the bug!

OMG, you even probably found the root cause - commas and dots!

That's probably is the problem with `DoubleTextField` component (it's thirdparty), it might not support the numbers...
