### ISSUE TITLE
Add search bar for filtering keyboard shortcuts

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#11686]
JabRef allows users to customize keyboard shortcuts but does not provide a convenient way of searching and filtering the default settings and custom assignments. This makes it hard to identify unused key combinations and choose new shortcuts that fit with the existing ones.

Other applications that allow custom keyboard shortcuts provide a search bar for searching/filtering the existing assignments. As a JabRef user, I expect to find a search bar for this in "Preferences > Keyboard shorcuts". The search bar should accept actions or shortcuts and filter the current settings accordingly.

A search bar could be added above the keyboard shortcuts, like some other applications and matching the precedent in JabRef under "Preferences > Journal abbreviations".

### Suggested location for new search bar
![image](https://github.com/user-attachments/assets/89187edc-1c0d-4bed-90fc-638e3d2de263)

### Precedent already in Preferences > Journal abbreviations
![journalsearch](https://github.com/user-attachments/assets/1c43ec9a-96e8-43c8-bda3-8f2c9744c067)

**Comment by heyitsdross** [comment]
Would like to implement, but currently hindered by [Issue#11766](https://github.com/JabRef/jabref/issues/11766)

**Comment by heyitsdross** [comment]
#11766 is solved, will implement, assuming nobody else is already on it.

**Comment by heyitsdross** [comment]
Do we want a simple text search where users have to type the names of the characters in to filter their keys? Or should we have this feature function in IntelliJ style, where clicking on the search bar prompts the user to input a Key Combination, which then is used to filter the list of shortcuts? 

I find the latter would be more user friendly, but seems incompatible with `CustomTextField` at a glance.

**Comment by ryan-carpenter** [comment]
> Or should we have this feature function in IntelliJ style, where clicking on the search bar prompts the user to input a Key Combination, which then is used to filter the list of shortcuts?

The important thing to me is being able to search key-bindings or actions. For example "Show me all the shortcuts that use <Ctrl>" or "What is the shortcut for Copy".

**Comment by heyitsdross** [comment]
My laptop containing my partial implementation died after overheating, if anybody else is itching to implement this and can do it in the next few weeks, feel free. 

Otherwise, I should have a working laptop again and will finish at that time.

**Comment by Siedlerchr** [comment]
Sorry to hear that. @heyitsdross  Hope you get around to a new laptop soon

PS: ![Image](https://github.com/user-attachments/assets/38e1637b-b649-46be-921b-dfabda23aacc)

**Comment by KumaLuo** [comment]
Hello @Siedlerchr, is this issue still available to take? We have an assignment in which we have to contribute to an open source project , and I would like to contribute to this project.
Thank you!

**Comment by HoussemNasri** [comment]
@aleeraudales @KumaLuo are you on the same team?

**Comment by KumaLuo** [comment]
@HoussemNasri exactly not

**Comment by HoussemNasri** [comment]
We have a first come, first served policy, so we need confirmation from @aleeraudales that they are not interested in the issue before we can assign it to someone else. 

@aleeraudales please confirm your interest in working on the issue.

**Comment by aleeraudales** [comment]
Switching off this issue.

Best,
Alejandro Raudales
________________________________

**Comment by aleeraudales** [comment]
Free to take

Best,
Alejandro Raudales
________________________________

**Comment by JasonXuDeveloper** [comment]
@Siedlerchr @HoussemNasri I am in the same team as @KumaLuo and would like to take over this issue.
