### ISSUE TITLE
Add an option to add "Cited on pages" in JStyle bibliography

### ISSUE THREAD

**Issue by subhramit** [JabRef/jabref#11691]
There exists a mechanism in JabRef to add "Cited on pages: ..." to bibliography entries when using JStyle citations.
However, this is presently not accessible to the user to be triggered, thus rendering the feature useless.

Suggestion would be to provide an option to the user to use this feature.

## Solution
The solution is simple, albeit will have multiple parts - will require work both on the UI and the backend.
### Frontend:
Add an option to use this feature **ONLY when a JStyle is selected**, maybe somewhere in the OpenOffice Panel Settings:

![image](https://github.com/user-attachments/assets/6b1b0e9a-33ab-4a86-bbce-6a03168a37d8)

Hint: Use a listener for style type
### Backend:
In the `OOBibBase` class, we have a boolean `alwaysAddCitedOnPages`, which is presently always set to `false`:
https://github.com/JabRef/jabref/blob/70d7c9ca869420ad57261d0b534fd8b3c81016a8/src/main/java/org/jabref/gui/openoffice/OOBibBase.java#L74-L75

Use this to convey the selected option through `syncOptions`.
**Refs. TODO comments added in https://github.com/JabRef/jabref/pull/11690**

### Additional:
It would be even better if this can be added as a user preference.
Hint: As an example, see how `getOpenOfficePreferences().getSyncWhenCiting()` is used to store a similar preference selected from the OO Panel settings.

**Comment by subhramit** [comment]
This is a very good issue for anybody fairly well-versed with Java, who wants to get versed with many aspects of JabRef development.

**Comment by subhramit** [comment]
Was this resolved? @Siedlerchr

**Comment by Siedlerchr** [comment]
Oh no that was accidentally

**Comment by heyitsdross** [comment]
Will implement
