### ISSUE TITLE
File format importer

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#117]
We got quite a lot of importers for various file formats.

See `net.sf.jabref.importer.fileformat.*`

- [ ] Biblioscape
- [x] BibtexImporter
- [ ] BibteXMLImporter
- [x] BiomailImporter (removed)
- [ ] CopacImporter
- [x] CsaImporter (removed)
- [ ] EndnoteImporter
- [ ] FreeCiteImporter
- [ ] InspecImporter
- [ ] IsiImporter
- [x] JstorImporter (removed)
- [ ] MedlineImporter
- [ ] MedlinePlainImporter
- [ ] MsBibImporter
- [ ] OvidImporter
- [ ] PdfContentImporter
- [ ] PdfXmpImporter
- [ ] RepecNepImporter
- [ ] RisImporter
- [ ] ScifinderImporter
- [ ] SilverPlatterImporter
- [ ] SixpackImporter

1. Most of them are __NOT__ tested.
2. I don't know how many of them are relevant for users.

This is a nice package for students or anyone to work on. The same holds for any exporters & web fetchers we have.

**Comment by mlep** [comment]
We could had a question about the use of those import filters to the survey.

**Comment by stefan-kolb** [comment]
Stupro takes care of this.
