### ISSUE TITLE
BibTex KeyGenerator Layout in Preferences looking weird

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1174]
Latest development version, freshly installed  on Win10 using installer with default settings

![keygenerator](https://cloud.githubusercontent.com/assets/320228/14455796/b6550326-00a1-11e6-81e5-bdfc28a70433.png)

**Comment by koppor** [comment]
2016-04-06--master--6488cf7 works

**Comment by stefan-kolb** [comment]
newest dev version works for us. Can you please recheck?

**Comment by Siedlerchr** [comment]
JabRef_windows-x64_3_3dev--snapshot--2016-04-12--master--1c5dcf1
It was a blank system, "virgin" installation of JabRef

**Comment by stefan-kolb** [comment]
Reproduced the bug. It occurs when no Database is open, i.e., when no BibDatabaseMode is present. The UI seems to be based on the current mode which is not reasonable here. Probably we need two tabs or anything to display patterns for both types.

**Comment by stefan-kolb** [comment]
`LabelPatternPanel.java`

```java
        // check if DB is open
        if(panel != null) {
            for (EntryType type : EntryTypes.getAllValues(panel.getBibDatabaseContext().getMode())) {
                textFields.put(type.getName().toLowerCase(), addEntryType(pan, type, y));
                y++;
            }
        }
```

**Comment by koppor** [comment]
Refs #1130

**Comment by matthiasgeiger** [comment]
Quickfix in 5b3985bc94eea80d7b567e9bcfafd87da835ed54 - however a better solution should be developed to handle the distinction between BibTeX and BibLaTeX better.
