### ISSUE TITLE
Attempts to open preferences pane causes application freeze

### ISSUE THREAD

**Issue by heyitsdross** [JabRef/jabref#11766]
### JabRef version

Latest development branch build

Commit hash `3dd1f86db2a7cf469e4bf10268c510fa68cb3c32`, built on September 16th, 2024.

### Operating system

GNU / Linux

### Details on version and operating system

`uname -r: 6.10.6-10-MANJARO`
Desktop Environment: sway (Wayland)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Tested on commit `3dd1f86db2a7cf469e4bf10268c510fa68cb3c32` via IntelliJ.

1. Start JabRef
2. Click on `File > Preferences`

**Expected Behavior**: Preferences Pane opens
**Actual Behavior**: Application freezes and ceases responding to user UI Inputs

**Note:** Cannot reproduce with `jabref-5.16-portable` on `https://builds.jabref.org/main`, the issue seems to only affect IntelliJ.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
Can you do a `git bisect` run please? 😅

**Comment by Siedlerchr** [comment]
Can you try to reset your preferences using the commandline options? https://dev.azure.com/silab-de/SIP/_build?definitionId=161
 `-d all`
Does it work then again? My guess it has something to do with the keyring accessing library (at least that is a thing I noticed when I ran jabref)

**Comment by heyitsdross** [comment]
I ran a git bisect, which was inconclusive, and also dug a bit into possible problems on my end. 

Configuring my [XDG Desktop Portal](https://wiki.archlinux.org/title/XDG_Desktop_Portal) to use  [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr) seems to have fixed the problem, I get a password prompt even on the `3dd1f86db2a7cf469e4bf10268c510fa68cb3c32` commit I mentioned above as broken.

Seems to happen quite frequently when one uses an install from one DE (in my case, Gnome) and attempts to install a second alongside it.

@Siedlerchr is this worthy of updating developer documentation with?

**Comment by Siedlerchr** [comment]
Ah great you found the issue. Yeah updating the devdocs is indeed helpful. In case anybody else encounters the problem
