### ISSUE TITLE
Unify logos

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1177]
JabRef currently has two logos:

MacOS X: https://github.com/JabRef/jabref/blob/master/src/main/resources/images/icons/JabRef-icon-mac.svg
other plattforms: https://github.com/JabRef/jabref/blob/master/src/main/resources/images/icons/JabRef-icon.svg

We should use one logo. In the devcall, we decided for the "other" logo.

Refs  #655
## Logo update

Should we do a logo contest such as http://99designs.de/logo-design/contests/create-cool-open-source-project-logo-219415 (https://www.docker.com/brand-guidelines) - http://99designs.de/pricing

**Comment by mlep** [comment]
My first thought was that creating a new logo was a good opportunity to involve the community of users. And this could be free ;-)

**Comment by stefan-kolb** [comment]
We need designs for #655 #482

**Comment by mlep** [comment]
@koppor could you get in touch with the potential contributor to this issue? (my email on April 17)

**Comment by simonharrer** [comment]
And the designs must be flat :)

**Comment by stefan-kolb** [comment]
Logos are unified for OSX and Windows right now. We will replace them with the new one in the future. This is tarcked in another issue.
