### ISSUE TITLE
Unicode Names not displayed correctly

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1178]
JabRef_windows-x64_3_3dev--snapshot--2016-04-12--master--1c5dcf1  on Win10

![aboutjabref](https://cloud.githubusercontent.com/assets/320228/14460208/89f54618-00bc-11e6-84af-4feb3e37ef17.png)

**Comment by koppor** [comment]
Duplicate of  #682.

**Comment by stefan-kolb** [comment]
Gradle issue is merged but we cannot see that it is working for us. Reinvestigate this for v3.7.

**Comment by grimes2** [comment]
File AUTHORS is encoded in UTF-8 without BOM. All other files are encoded in ANSI. What is the reason for the different encoding?

**Comment by koppor** [comment]
What are "all other files"? Language files are encoded in UTF-8. Source
code also in UTF-8. I'm currently not in ANSI encoding. Is it ISO ...-15?
Windows CP 8..? Or 7bit only?

**Comment by grimes2** [comment]
"all other files" is for example CHANGELOG.md. Here are the screenshots in notepad++, that demonstrates the different encoding of the files:
![authors_in_notepad](https://cloud.githubusercontent.com/assets/15456836/18403735/e1a46858-76e6-11e6-909a-36f014da2ec8.png)
![changelog_in_notepad](https://cloud.githubusercontent.com/assets/15456836/18403741/ea0a4e54-76e6-11e6-9d04-d3ed7116c552.png)
The file were loaded from my local master.

**Comment by Siedlerchr** [comment]
My changelog is in UTF8...like all other files


2016-09-09 23:43 GMT+02:00 Jürgen Lange <notifications@github.com>:

**Comment by grimes2** [comment]
I've now cloned the upstream master again, to exclude that it is an problem introduced by me. Same result: AUTHORS still has another encoding than all the other files.
System: windows 10, Notepad++

**Comment by Siedlerchr** [comment]
Fixed with #1954

**Comment by koppor** [comment]
@grimes2 I think your observation has something to do with the default charset of Notepad++. I assume if you [change the default encoding to UTF-8](http://superuser.com/questions/292086/how-can-i-enforce-so-notepad-uses-utf-8-every-time-i-create-a-new-file). I opened the CHANGELOG.md in notepad++, converted it to ANSI, saved. Nothing changed according to git. I also searched for `[^\x20-\x7E\t\n\r]` (based on http://stackoverflow.com/a/8845405/873282) and there were no hits in CHANGELOG.md.
