### ISSUE TITLE
Add a visible notice when user opens more than one JabRef instance

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#11783]
**Is your suggestion for improvement related to a problem? Please describe.**

I wanted to run a portable version of JabRef, but I already had running JabRef in IntelliJ.

When I double clicked on the executable file in portable version, nothing happended. I didn't give up, and started it from terminal. In terminal there was:

```
Messages are not initialized before accessing key: Display help on command line options
2024-09-18 08:10:49 [main] org.jabref.Launcher.handleMultipleAppInstances()
INFO: Arguments passed on to running JabRef instance. Shutting down.
```

I couldn't understood this at the beginning, but then I finally understood that I had another instance of JabRef running.

`Arguments passed on to running JabRef instance` - WTF is this? 1) I didn't pass any arguments, and 2) I was certain that exactly this executable wasn't run before.

**Describe the solution you'd like**

1) Refactor the message when user starts JabRef a second time.
2) Make a dialog with that message

**Additional context**
-

**Comment by InAnYan** [comment]
I think this could be a good first issue :)

**Comment by koppor** [comment]
This issue needs refinement!

The JabRef CLI is also used by the browser extension. There should not be any dialog when the extension passes something to JabRef. 

Maybe if no arguments are passed, a small dialog is OK. 

See https://github.com/JabRef/jabref/issues/8653 for some more info on the feature!

**Comment by koppor** [comment]
Code is at https://github.com/JabRef/jabref/blob/604896c67e2bc0b7af799be1211c12f9f92c87be/src/main/java/org/jabref/Launcher.java#L184

Add an if statement.

```
If 0 arguments available
    open dialog saying Localization.lang("Another JabRef instance is already running. Please switch to that instance.")
else
     old code (remoteclient. sendCommandLineArguments ( args ) )
```

**Comment by leaf-soba** [comment]
Can I take this issue? Since I have done one of `good first issue`, I don't know I could do more of them or not.

**Comment by ThiloteE** [comment]
Yes, you can. Eventually, if you are more confident in your abilities and you got a feel for the code base, you can move over to other projects pages from https://github.com/orgs/JabRef/projects, but for now it is fine :-) If you are a student and need a small project, I recommend https://github.com/orgs/JabRef/projects/3

**Comment by koppor** [comment]
When we compare the code WTFs with the user beneift, it turned out, that the code WTFs are more. Thus, we close this as won't fix. Sorry for the efforts!
