### ISSUE TITLE
Cannot use tab to jump to next field in some single-line fields

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#11785]
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go into the URL field in the entry editor
2. Press `Tab`.

Empty space is inserted instead of jumping to the next field.

### Appendix

The reason is that https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/fieldeditors/EditorTextArea.java is used over https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/fieldeditors/EditorTextField.java in some fields that sholud be normal single-line fields: Url, Identifier, Owner, Issn

**Comment by ryan-carpenter** [comment]
> in some fields that sholud be normal single-line fields: Url, Identifier, Owner, Issn

It is not uncommon for applications not to allow use of Tab key to insert a Tab character, even with multi-line text. I think it would be suitable for Tab to behave the same (move to next field) in single-line and multi-line fields. Alternatively, consider adding default or custom shortcuts to for moving forward and backward through the fields.

Note that <Shift + Tab> moves backward, regardless of the current field type but forward navigation using <Tab> is interrupted by the multi-line fields.

**Comment by tobiasdiez** [comment]
The only real multi-line fields would be comment and abstract, right? These are usually on their own tab, so it's not important to have `Tab` as a navigation between fields in this case.

**Comment by ryan-carpenter** [comment]
> The only real multi-line fields would be comment and abstract, right?

Good point, but remember that standard fields can be configured as multi-line in preferences and that non-standard fields can be added and configured as multi-line.

**Comment by juliusalberto** [comment]
Hi, I would like to work on this issue. Can I be assigned to this issue? Thanks!
