### ISSUE TITLE
search for key does not always work

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#11798]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.16--2024-09-17--ed0e90e Linux 6.10.10-200.fc40.x86_64 amd64  Java 21.0.2  JavaFX 23+29

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Given a library that contains inter alia entries with the keys  `Law:2009The` and `acker1990hierarchies`

I am puzzled:

1. search for `Law:2009The`
2. does not deliver results

However

1. search for `acker1990hierarchies` 
2. does deliver results

why is that?

**Comment by ryan-carpenter** [comment]
Try escaping the colon using `Law\:2009The`

**Comment by ilippert** [comment]
> Try escaping the colon using `Law\:2009The`

yes, thanks, that works.

But I think still that a user should be able to copy and paste a key into the search field and find the result.

**Comment by ryan-carpenter** [comment]
> But I think still that a user should be able to copy and paste a key into the search field and find the result.

I feel the pain. Most of my group names are structured like Clojure keywords with the form `:group/subgroup`. Colons and slashes are both special characters in Lucene syntax, so I need to search for `\:group\/subgroup`.

Also note that according to the documentation, Lucene searches using regular expressions must match the _whole field_.

**Comment by LoayGhreeb** [comment]
> But I think still that a user should be able to copy and paste a key into the search field and find the result.

The search syntax has been updated to use [Lucene syntax](https://lucene.apache.org/core/9_11_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html). 

Searching for `Law:2009The` is interpreted as searching in the `law` field for the value `2009The`. With the new syntax, `:` is used instead of `=`.

To search for the value `Law:2009The`, you can use either `"Law:2009The"` or escape the colon with `Law\:2009The`.
