### ISSUE TITLE
Rename packages from net.sf.jabref to org.jabref

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1179]
We move away from SourceForge. Thus, the packages should also be renamed, too.

This could make #152 harder, but strengthens that we are independent of sourceforge.

Refs #111 

Possibly also reorganize the imports in this change.

**Comment by Siedlerchr** [comment]
> We move away from GitHub
I think you meant SF.  Renaming the packages would be a huge step, I am not sure what to think about that.

**Comment by simonharrer** [comment]
Downsides
- as the package of the preferences would change, all old preferences would be lost (maybe something for a major break, e.g., 4.0?)
- grammar (search, bst) must be changed and regenerated
- files could go missing as changing the package requires to change the folder structure

**Comment by koppor** [comment]
Implemented in https://github.com/JabRef/jabref/pull/2558
