### ISSUE TITLE
Change file header

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#118]
Currently, JabRef adds following header to each BibTeX file

    % This file was created with JabRef <version>
    % Encoding: UTF8

If users use different versions of JabRef, this causes problems. Therefore, I propose to just remove the first header line.

I'm not sure about the second line. Should we guess the encoding from the file or keep the encoding information?

Other JabRef settings such as the group information or the save order is stored in BibTeX `@comment` entries. Maybe we should require the encoding also be stored as `@comment`? Possibly, this interferes with the parser and we have to first check existence of a encoding comment entry and then fire up the parser.

**Comment by stefan-kolb** [comment]
1. The first line doesn't really add any benefit for the user so it could be removed. The only argument against it is that it is an implicit advertisment for our tool, so we could just change it to `Created with JabRef bibliography manager´ or alike.

2. We should get the encoding of the file directly from the file header if possible.

**Comment by koppor** [comment]
As new user in the BibTeX world one might think that this line is important that JabRef can deal with it. Since all most pages about latex and bibtex recommend JabRef, I vote for completely dropping the line - even though some completely new users are not directly guided to JabRef.

**Comment by mlep** [comment]
Specifically for new users thinking such a line is important, I suggest to add
`% Go to  <http://> and give money to JabRef`
;-)

**Comment by lenhard** [comment]
I'll vote for dropping the line completely as well.

**Comment by bluebirch** [comment]
Add the first line as

-*- coding: utf-8 -*-

which actually makes sense in many text editors.

mån 24 aug 2015 11:59 Jörg Lenhard <notifications@github.com> skrev:

**Comment by lenhard** [comment]
Ok, @bluebirch has a point. We could just switch to a standard notation for specifying the encoding.

I don't really know what the most widely used notation for specifying the encoding is, so if no one objects, `-*- coding: utf-8 -*- ` would be fine by me.

**Comment by koppor** [comment]
* [TeXstudio](http://tex.stackexchange.com/a/154292/9075): `% !TEX encoding = UTF-8 Unicode`
* [AUCTeX](http://tex.stackexchange.com/a/21212/9075): `%%% coding: utf-8`

I don't know about Zotero and [other bibtex managers](https://github.com/JabRef/jabref/wiki/Alternatives#bibtex-based).

@bluebirch Could you name some of the "many text editors"? Would be nice to have a justified decision as we don't want to change that line the next years. :grinning:

**Comment by stefan-kolb** [comment]
`-*- coding: utf-8 -*-` think this is only [Emacs](http://www.gnu.org/software/emacs/manual/html_node/emacs/Specify-Coding.html) and [Python](http://stackoverflow.com/questions/4872007/where-does-this-come-from-coding-utf-8). As far as I know there is no standard way of defining file encodings.

**Comment by bluebirch** [comment]
You might be right. As a former Emacs user, I see the world differently.
But I'm slowly adapting to a new reality with Sublime Text. ;-)

mån 24 aug 2015 17:10 Stefan Kolb <notifications@github.com> skrev:

**Comment by stefan-kolb** [comment]
See also http://stackoverflow.com/questions/90838/how-can-i-detect-the-encoding-codepage-of-a-text-file

**Comment by koppor** [comment]
I really like some auto-detection, which frees the user to configure its programs.

**Comment by koppor** [comment]
We can also go for supporting UTF-8 only to have the `.bib` file really portable across different systems. Other encodings can be converted to UTF-8 by JabRef while loading.

**Comment by matthiasgeiger** [comment]
Just stumbled over [this](https://github.com/JabRef/jabref/blob/997cc9abfbe2327bcf54fb549ac4c8cad5ac9d6d/src/main/java/net/sf/jabref/importer/BibtexParser.java#L1041) - However, I don't have the time to dig deeper in the matter, but the first line seems to have some purpose ;-)

**Comment by stefan-kolb** [comment]
Yes there is still one migration based on the JabRef version.
We can remove the file header though.
We just need to keep the logic for parsing the old header possibly...
See `FileLinksUpgradeWarning.java`

**Comment by stefan-kolb** [comment]
This commit 4558fb644330b5dc0120332979fd7871420be049 removes the JabRef version file header.
We need to come up with a good solution for the encoding though.
Backwards compatibility is tested and retained in this commit. We could remove quite some code if this can be made obsolete.

**Comment by lenhard** [comment]
The encoding name is now written as "UTF-8", see also #155 
The old "UTF8" is automatically overwritten when the file is saved.

**Comment by lenhard** [comment]
How about settling with the current status quo for now:
```
% Encoding: UTF-8
```
 and closing this issue? Any objections?

**Comment by koppor** [comment]
Fine with me. The other encoding strings are not convincing.

**Comment by matthiasgeiger** [comment]
:+1:
