### ISSUE TITLE
Remove listeners in `RedoAction` for memory efficiency

### ISSUE THREAD

**Issue by subhramit** [JabRef/jabref#11809]
Context: PR #11758 
Based on the TODO comment:
https://github.com/JabRef/jabref/blob/8412e651b671a427c828924ce5698eb4c32f269d/src/main/java/org/jabref/gui/undo/RedoAction.java#L24-L28

Refs. https://github.com/JabRef/jabref/pull/11758#discussion_r1759739748

**Comment by subhramit** [comment]
Some hints:
- Remove the listeners based on `activeLibraryTab`.
- Alternatively, [WeakChangeLIsteners](https://docs.oracle.com/javase/8/javafx/api/javafx/beans/value/WeakChangeListener.html) can also be used.

**Comment by melisolmez** [comment]
Hi, can ı work on this issue ?

**Comment by subhramit** [comment]
> Hi, can ı work on this issue ?

Sure.

**Comment by ThiloteE** [comment]
@subhramit when assigning students, you also have to manually change the issue from "free to take" to "reserved" in the project. I tried to automate this, but GitHub Projects isn't capable of doing so, the last time I checked.
![grafik](https://github.com/user-attachments/assets/3bc134a6-3626-40c3-b1f6-022b78856204)

**Comment by subhramit** [comment]
> @subhramit when assigning somebody, you also have to manually change the issue from "free to take" to "reserved" in the project. I tried to automate this, but GitHub Projects isn't capable of doing so, the last time I checked.

Hey, I tried to change it, but I think only maintainers can do that.

**Comment by melisolmez** [comment]
Hello @subhramit, while I solve this isue I noticed this error:
![error](https://github.com/user-attachments/assets/3972dcea-666f-44af-9209-8cc4c006ff5b)

Can we solve this problem with an if statement that checks for null in the RedoAction.excecute method?

**Comment by subhramit** [comment]
> Can we solve this problem with an if statement that checks for null in the RedoAction.excecute method?

Did this error exist before? (if yes, then could you elaborate the steps to reproduce it?)
 
Else, if this was triggered after your changes, submit a PR so that we can review and make suggestions.

**Comment by melisolmez** [comment]
> > Can we solve this problem with an if statement that checks for null in the RedoAction.excecute method?
> 
> Did this error exist before? (if yes, then could you elaborate the steps to reproduce it?)
> 
> Else, if this was triggered after your changes, submit a PR so that we can review and make suggestions.

yes this exist before, not beacufe of my changed. If you want you are try on your local.

**Comment by subhramit** [comment]
> yes this exist before, not beacufe of my changed. If you want you are try on your local.

Yes, please write down the steps to reproduce the exception. It is also okay if you want to open another issue regarding it for more visibility, and then solve both the issues together.

**Comment by melisolmez** [comment]
> > yes this exist before, not beacufe of my changed. If you want you are try on your local.
> 
> Yes, please write down the steps to reproduce the exception. It is also okay if you want to open another issue regarding it for more visibility, and then solve both the issues together.

When I run jabref, the redo and undo buttons become active. When you press them directly without doing anything, this error occurs.

**Comment by Siedlerchr** [comment]
The buttons should be disabled if no library is opened that is probably the issue here

**Comment by melisolmez** [comment]
> The buttons should be disabled if no library is opened that is probably the issue here

Yes but there are not disabled. If you want,You can open an issue about this error

**Comment by koppor** [comment]
> > The buttons should be disabled if no library is opened that is probably the issue here
> Yes but there are not disabled. If you want,You can open an issue about this error

Do you refer to https://github.com/JabRef/jabref/issues/463? Does this issue need to be reopened? If yes, please refine the issue. Make a screenshot and point out which actions should be disabled.
