### ISSUE TITLE
"New entry from plain text" gives strange results

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#11805]
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

Linux Mint 22 (XFCE)

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Use "New entry from plain text"
2. Enter this entry:

```
Dominici, Massimiliano. 2014. “An Overview of Pandoc.” TUGboat 35 (1): 44–50.
```

The result is:

```bibtex
@Article{Dominici2014,
  author    = {Dominici, Massimiliano},
  journal   = {International Journal of Business and Management},
  title     = {From Marketing Mix to e-Marketing Mix: a literature overview and classification},
  year      = {2014},
  number    = {9},
  pages     = {44--50},
  volume    = {4},
  date      = {2014},
  doi       = {10.5539/ijbm.v4n9p17},
  publisher = {Canadian Center of Science and Education},
}
```

While I was expecting something like:

```bibtex
@article{dominici2014overview,
  title={An Overview of Pandoc},
  author={Dominici, Massimiliano},
  journal={TUGboat},
  volume={35},
  number={1},
  pages={44--50},
  year={2014}
}
```

**Comment by Siedlerchr** [comment]
we are using grobid for New entry from Plaintext https://github.com/kermitt2/grobid

**Comment by ThiloteE** [comment]
It's based on machine learning technology. Sometimes there will be confabulations. I recommend to manually cross-check any data obtained this way and make use of "import by ID". If you can find the DOI of an entry, then that's probably best. "New entry from plaintext" can speed up your workflow, but it's imprecise.

**Comment by koppor** [comment]
This is solved with https://github.com/JabRef/jabref/pull/11831? Maybe, we just missed to close this issue (and add a link to this issue in the CHANGELOG.md entry)?

**Comment by InAnYan** [comment]
Let me check quickly

**Comment by InAnYan** [comment]
With LLM parsing everything is all right! I'll close the issue.

Moreover, we also added a warning in the plain citations parser window
