### ISSUE TITLE
"Normalize to BibTeX name format" should help when manually importing entries.

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1181]
JabRef as of 2016-04-12, 39f7ed7

Steps:
1. Use ISBN to BibTeX fetcher with 978-3-642-02373-6
2. Go to required fields
3. Editor is empty
4. Go to http://www.springer.com/us/book/9783642023736
5. Copy the editors string `Ali Babar, M., Dingsøyr, T., Lago, P., van der Vliet, H.`
6. Right click in the editors field and select "Normalize to BibTeX name format"
7. Result: `Ali Babar, M., Dingsøyr T. Lago P. van der Vliet H.`

Expected: `Babar, Ali and M. and Dingsøyr, T. and Lago, P. and van der Vliet, H.`

JabRef 3.2: `Babar, Ali and M. and Dingsøyr and T. and Lago and P. and van der Vliet and H.`

Refs #318 and  #950

**Comment by tobiasdiez** [comment]
The comma as a separator of author names was removed in https://github.com/JabRef/jabref/pull/1149. It is just not clear how to consistently guess the right naming schema. Just replace the commas separating authors by semicolons and everything should work as expected.

**Comment by koppor** [comment]
Ah, great hint. Then, the implementation is easy:

Check
 - only `, ` (no `; `, no ` and `)
 - even number of `,`

Then, convert every second `,` to `;` and then run the implemented algorithm.

**Comment by tobiasdiez** [comment]
But then `Name, della, first` would be recognized as two names although it is valid BibTeX syntax for one name with vonPart = della.

**Comment by koppor** [comment]
Oh, I see it at http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html, section "Names specifications". According to that explanation `della` would be the `Jr` part, not the `von` part. Reading that and also assuming that I never saw three commas, I would accept that this "helper" formats 1% of the cases wrong.

**Comment by matthiasgeiger** [comment]
Please check whether your improvement also solves #1504 by adding the example as an additional test case.

Thanks!

**Comment by koppor** [comment]
Fixed by #1470
