### ISSUE TITLE
Add warning about confabulations to "New entry from plain text"

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#11825]
### Description of Problem:
"New entry from plain text" is based on the Grobid project, which uses machine learning techniques. Results are probability based, therefore not always 100% accurate.

We have had users that are confused by this and think the resulting data is or always should be true.

### Solution:
Add a warning about confabulations or hallucinations in the GUI. It could be phrased similar to the warning that is shown to users that make use of the AI Chat or AI Summarization feature. 

**Additional context**
- https://github.com/kermitt2/grobid
- https://github.com/JabRef/jabref/issues/11805
- https://discourse.jabref.org/t/shortcuts-for-get-bibliographic-data-from-doi-and-look-up-doi/4468/6

**Comment by koppor** [comment]
Follow-up: Use the openAI API to create BibTeX. Has much better results. @InAnYan Can you "unzip" this feature wish? - Which code to use in JabRef to interact with openAI etc. Prompt is like "Please convert the following bibliography entry to a well-formatted high-quality BibTeX entry".

**Comment by ThiloteE** [comment]
can you provide statistics about "much better results"?

**Comment by koppor** [comment]
> are there statistics about "much better results"?

I tried with the example of our homepage - https://docs.jabref.org/collect/newentryfromplaintext


In: O. Kopp, A. Armbruster, und O. Zimmermann, "Markdown Architectural Decision Records: Format and Tool Support", in 10th ZEUS Workshop, 2018.

Out 1:

```bibtex
@Article{Kopp_2018abc,
  author       = {Kopp, O and Armbruster, A and Zimmermann, O},
  date         = {2018},
  journaltitle = {Communications},
  title        = {Le gigantisme architectural en Union soviétique},
  doi          = {10.3406/comm.1985.1625},
  number       = {1},
  pages        = {45-67},
  volume       = {42},
  publisher    = {PERSEE Program},
}
```

Out 2:

```bibtex
@inproceedings{kopp2018markdown,
  author    = {Oliver Kopp and Andreas Armbruster and Olaf Zimmermann},
  title     = {Markdown Architectural Decision Records: Format and Tool Support},
  booktitle = {Proceedings of the 10th ZEUS Workshop},
  year      = {2018},
}
```

Guess which output is from which tool!

I know that both are wrong. - Anita will go crazy.

Refined prompt:

> Please convert the following bibliography entry to a well-formatted high-quality BibTeX entry. Do not invent additional information (such as full first names). Keep as close as possible to the input.

```bibtex
@inproceedings{kopp2018markdown,
  author    = {O. Kopp and A. Armbruster and O. Zimmermann},
  title     = {Markdown Architectural Decision Records: Format and Tool Support},
  booktitle = {Proceedings of the 10th ZEUS Workshop},
  year      = {2018}
}
```
