### ISSUE TITLE
Unexpected behaviour of the new search feature

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#11823]
### JabRef version

JabRef 5.16--2024-09-20--5ac788c

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint/Debian

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open database with an entry A containing the string "xyz-abc" (choose as appropriate)
2. Search for _xyz AND abc_
3. Entry A does not appear in the results although it should (it did before the search feature update).
4. Entry A will appear in the search results when using _xyz abc_ (which in Lucene implies an OR used).

Hope anybody can reproduce this issue. I found the issue when looking for strings in the "comments" field but I tested that the issue should occur with the title field and perhaps other fields as well. **The issue does not occur when using "xyz abc", so it seems the new search now expects strings to occur as substrings in separate words.** I'm using search groups a lot and found that behavior today only because some entries where missing after the search-group migration.

**Update:** It also seems that the new search **does not recognise** string occurrences in the **keywords** anymore.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ytzemih** [comment]
This is perhaps a matter of taste, but the new search feature exposing Lucene syntax directly to the user feels surprisingly counterintuitive. I'm more familiar with regular expression syntax. But I'm sure I'll adapt. Is there a corresponding update of the JR help website?

**Comment by ytzemih** [comment]
Regarding the keywords, it seems to work, if the search string is part of the first keyword. But if there are more keywords and the string is only occurring in one of the keywords later in the list, search does not find it anymore. I wonder whether there is something strange happening when combining the keywords for Lucene's search?

**Comment by koppor** [comment]
We will revert the syntax to the old one in https://github.com/JabRef/jabref/pull/11803. The build of that PR does not cover all features yet. We are in the middle of migrating.

We are also working in bringing back the old search test cases

- https://github.com/JabRef/jabref/blob/v5.15/src/test/java/org/jabref/model/search/rules/GrammarBasedSearchRuleTest.java
- https://github.com/JabRef/jabref/blob/v5.15/src/test/java/org/jabref/logic/search/SearchQueryTest.java

I think, we can add your description as test case. Maybe you could even post a modified test to cover your case. 😅

**Comment by koppor** [comment]
Side question: Did you migrate your search groups? Would it be OK for you to migrate them back to the v5.x syntax manually - or should we work on a converter? ^^

**Comment by ytzemih** [comment]
Thanks for clarifying the development roadmap. I see, well, it was hopefully worth a try.

No worries, it is just over a handful of groups. I can migrate them back manually by removing the "any:" and the slashes and perhaps replacing AND and OR, AFAIS.

**Comment by ryan-carpenter** [comment]
> This is perhaps a matter of taste, but the new search feature exposing Lucene syntax directly to the user feels surprisingly counterintuitive. I'm more familiar with regular expression syntax. But I'm sure I'll adapt.

I agree. Lucene search will find match the entry of interest if you search for  `xyz AND *abc`. I have found that the asterisk is necessary for partial matches preceded by a non-word-boundary. I don't know why and I can't explain why the union search works but the intersection does not, unless you use the asterisk. However, the union ("OR") work with or without the asterisk.

**Comment by ryan-carpenter** [comment]
> **The issue does not occur when using "xyz abc", so it seems the new search now expects strings to occur as substrings in separate words.**
> 

This is correct, except that the unit of analysis is not words, _per se_, but "tokens" that happen to contain separate words. The string `xyz abc` is interpreted as two tokens whereas "xyz-abc" is interpreted as one token.

> **Update:** It also seems that the new search **does not recognise** string occurrences in the **keywords** anymore.

Keywords exhibit the same behaviour as other fields, so you need to add a wildcard to match the beginning of the token to match a target that occurs anywhere other than the beginning of the token. For example, `keywords:*abc`.

Note: The documentation at https://lucene.apache.org/core/2_9_4/queryparsersyntax.html states that "You cannot use a * or ? symbol as the first character of a search." but the results in JabRef contradict this. Searching for `*abc` or ?yz-abc` matches "xyz-abc" whether it occurs in the title, keywords, or comment field.

**Comment by ytzemih** [comment]
Thanks, @ryan-carpenter, for figuring all this out. It is now also important for the user to know how Lucene is integrated in JR. Unfortunately, all this sounds rather complicated for a user-exposed search feature, and may reduce JR's UX. Anyway, let's see how this feature develops. It seems, however, from what @koppor said, that the original search (which, IMHO, was quite alright) might be restored.

**Comment by koppor** [comment]
We are working at https://github.com/JabRef/jabref/pull/11803 to bring back the „old“ syntax. RegEx supported via =~.

Please do not learn Lucene. It is in the dev build only and will be dropped

**Comment by ryan-carpenter** [comment]
I think the Lucene experiment has clarified that users expect deterministic searching, and that the current (old) model of interpreting queries to mean "contains" meets this expectation. For those of us that rely on it, regex is priceless.
