### ISSUE TITLE
Add a "view as BibTeX" option before importing an entry from the citation relation tab

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#11826]
When importing entries from the citation relation tab, a preview of entries to import is displayed, but it doesn't include all the information. It would be useful to click a button and display a dialog showing the full BibTeX of that entry.

![image](https://github.com/user-attachments/assets/4dcd8a1a-0a54-4a4f-9445-c74d255df2dc)

## Motivation 
Could be useful for deciding whether to import a "duplicate" (record that may contain new data about an existing entry)

Refs https://github.com/JabRef/jabref/issues/10869

## Hint
- Given that `SourceTab` exists this should be a fairly simple task.

## Implementation options
- Click a button, show a dialog with BibTeX
- Expansion of the entry would be nice. You know accordion and "v"/">" button

**Comment by JamseBonde007** [comment]
Hi! I'd love to give this issue a go. Could I please be assigned to it?

**Comment by JamseBonde007** [comment]
Is this a satisfactory solution?
![img1](https://github.com/user-attachments/assets/075882c3-e14b-492b-96b1-48e1dd6a4462)
![img2](https://github.com/user-attachments/assets/1ccc1aa3-e9c0-4753-8be9-a96fd2550f80)

**Comment by HoussemNasri** [comment]
The UI looks good so far. Please open a draft pull request so we can begin reviewing the code changes.

The code doesn't need to be complete before the review starts. It's always better to catch potential issues early, as fixing them is easier before they compound.
