### ISSUE TITLE
redo and undo buttons are active without open library 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11837]
Hello @koppor , I noticed an error yesterday. Maybe, You want to examine. the error is like this:

redo and undo buttons become active when the project is up and running:
![redo undo](https://github.com/user-attachments/assets/c179bdfd-0e31-42a0-8445-8062dc812e15)

When you click on these buttons, an error message appears like this: 
![image](https://github.com/user-attachments/assets/d2f8527b-d94a-47e2-b351-4a02310ffdc7)

_Originally posted by @melisolmez in https://github.com/JabRef/jabref/issues/463#issuecomment-2376639604_

**Comment by HoussemNasri** [comment]
I like it when Java throws an exception at line 53 in a class having 42 lines of code :)

**Comment by faresbouzayen** [comment]
Hi @Siedlerchr! I'm interested in fixing the redo and undo buttons being active without an open library.

Plan:
Investigate how the button state is managed.
Implement logic to enable buttons only when a library is open.
Test thoroughly to ensure correct behavior.
Update documentation as needed.
I'll start looking into this and reach out if I have questions. Thanks!

**Comment by koppor** [comment]
I think @melisomez is already on it at https://github.com/JabRef/jabref/pull/11839

**Comment by Siedlerchr** [comment]
It's related but not the same. we need to integrate an additional check e.g.
`         this.executable.bind(needsDatabase(stateManager) `

**Comment by melisolmez** [comment]
> I think @melisomez is already on it at #11839

Actually I am not. I am working on listener just.

**Comment by subhramit** [comment]
> Hi [@Siedlerchr](https://github.com/Siedlerchr)! I'm interested in fixing the redo and undo buttons being active without an open library.
> 
> Plan: Investigate how the button state is managed. Implement logic to enable buttons only when a library is open. Test thoroughly to ensure correct behavior. Update documentation as needed. I'll start looking into this and reach out if I have questions. Thanks!

Hey @faresbouzayen, are you actively working on this? I see that you have not even forked the repository yet. Do you need any help? If busy, you can also pass this on to other students.

**Comment by subhramit** [comment]
@maintainers shift this to free-to-take.

**Comment by damgam0288** [comment]
Hi @Siedlerchr
I'm part of a group of five students looking to contribute to this project.

Our plan for this issue:
- [ ] Understand how the Undo/Redo buttons enabled/disabled state is managed, specifically what causes the state to change.
- [ ] Investigate the use of "libraryTab" referring to the posted stacktrace.
- [ ] Implement logic between button state and library's open/closed state.
- [ ] Write tests and documentation.
- [ ] Submit a PR if we appear to have solved the issue.

We plan to focus on this for the next 1-2 weeks if assigned. We will engage through the comments, and state if we cannot solve this issue so that it is available to others promptly. Thanks!

**Comment by subhramit** [comment]
I was going to assign @melisolmez as her comment expressing interest (https://github.com/JabRef/jabref/pull/11839#issuecomment-2391241938) is older, but final call on you guys as it's a university assignment for @damgam0288.
You guys can also suggest any other good first issue to them, if that works.
@Siedlerchr @koppor @ThiloteE @calixtus

**Comment by Siedlerchr** [comment]
As this is a oneliner it does not make senes to address it with a lot of people so chose any other issue
