### ISSUE TITLE
 Rename "Search selected" to "Search pre-configured"

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11866]
![selected](https://github.com/user-attachments/assets/ae7015c1-2fd0-436a-930b-0711463fdb74)

**Is your suggestion for improvement related to a problem? Please describe.**

Selected is confusing should be renamed to pre-configured

**Comment by xDido** [comment]
image is not available. could you please re-upload?

**Comment by Siedlerchr** [comment]
@xDido Thanks for the hint, uploaded it

**Comment by plvzfq-rit** [comment]
Hello! Could I perhaps work on this issue? I am quite new to contributing to open-source code but since it is just a rename, I think it should not be too much of a hassle.

**Comment by plvzfq-rit** [comment]
Thanks! I'll try to finish this as soon as I could.
