### ISSUE TITLE
Change entry color when dragging files (highlight row again)

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11898]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Follow-up to: https://github.com/JabRef/jabref/pull/11579

Currently, when dragging a file to an entry:
![Image](https://github.com/user-attachments/assets/e883a5c4-0328-4e52-b45d-7f75fe81aa6d)

Before this PR:
![Image](https://github.com/user-attachments/assets/5f26dec8-c397-4174-b242-faca61414167)

Row should be highlighted again
Should be tested with Light theme and Dark theme  (base.css and dark.css) 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Nicholas-An** [comment]
Hello @Siedlerchr! If this issue is still free I'd love to tackle it as my first contribution.

**Comment by AdiAr11** [comment]
Hello @Siedlerchr, is this issue still available to take? We have an assignment in which we have to contribute to an open source project , and I would like to contribute to this project. 
Thank you!

**Comment by Siedlerchr** [comment]
It's already assigned, however you can check https://github.com/orgs/JabRef/projects/5
For issues that are not assigned

**Comment by AdiAr11** [comment]
@Siedlerchr, I'll check that. Thank you!

**Comment by ar-rana** [comment]
Hello @Siedlerchr, Since this issue is currently unassigned, could you assign it to me.
