### ISSUE TITLE
Add support for CitationStyles

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#119]
As user, I quickly want to copy and paste an entry rendered in a specified format. Either, because I want to paste a reference in a review, I work with Microsoft Word managing the references by hand, or I just quickly send around a reference to users not using BibTeX as serialization format. Currently, JabRef cannot be configured quickly to render Springer or IEEE styled entries: One has to use a combination of HTML and the formatters to get the desired result.

[CitationStyles](http://citationstyles.org/) is the new way to offer rendering of bibliographic data. Currently JabRef offers following two possibilities to format BibTeX entries

 - Through [JabRef's formatters](http://jabref.sourceforge.net/help/CustomExports.php), which are used at the export or at the preview panel
 - Through bibtex (`bst`) and biblatex ([biblatex-styles](https://de.sharelatex.com/learn/Biblatex_citation_styles)) - when using in a latex document

I am aware that another options causes more trouble. Nevertheless, the available formats of CitationStyles is huge (over 7500) and we can't keep maintaining all of them in a JabRef / [OpenOffice style](http://jabref.sourceforge.net/OOPlugin-styles.php) variant.

Possibly, we drop JabRef's formatters? If we decide against support of CitationStyles, we should enable displaying/exporting references formatted by bibtex (and eventually biblatex). As far as I understood, JabRef offers a [bibtex VM](https://github.com/JabRef/jabref/blob/v_2.11b3/src/main/java/net/sf/jabref/bst/VM.java), which interprets `bst` files and generates text output. Meaning: We have a bibtex program implemented in Java, dont' we?

## Background information
* [mapping from BibTeX to CSL](http://www.docear.org/2012/08/08/docear4word-mapping-bibtex-fields-and-types-with-the-citation-style-language/)
* With [citeproc-java](http://michel-kraemer.github.io/citeproc-java/) it should be fairly easy to implement the feature. It also offers a [bibtex importer](http://michel-kraemer.github.io/citeproc-java/using/bibtex-converter/).

**Comment by mlep** [comment]
CitationStyles looks impressive! If programming-wise, this is relevant and efficient, I vote for this feature.

**Comment by koppor** [comment]
With [citeproc-java](http://michel-kraemer.github.io/citeproc-java/) it should be fairly easy to implement the feature. It also offers a [bibtex importer](http://michel-kraemer.github.io/citeproc-java/using/bibtex-converter/).

**Comment by stefan-kolb** [comment]
:+1:

**Comment by koppor** [comment]
Comment: JabRef has a bibtex VM, which supports rendering using `bst` files (`net.sf.jabref.bst.VM`). This functionality should be used for the preview dialog, too. See also #110.

**Comment by Olifair** [comment]
I have been trying to use the visual CLS editor on the web-page to create a new style : it's horrible, really not something that the average user could easily get a hang off. But if there would be a way to just import these styles into JabRef ...

**Comment by tobiasdiez** [comment]
As discussed in #647 it would be nice to use CitationStyles in the following places:
- Entry preview
- Export to clipboard
- Export (maybe)

Moreover, we should consider providing a editor for citation styles.

**Comment by koppor** [comment]
@Olifair Sure, jabRef will offer importing any existing CitationStyle. This is the core idea of CitationStyles. IMHO, this covers 99% of all use cases.

If that does not fit your need, you can currently reconfigure the output. See http://jabref.sourceforge.net/help/PreviewHelp.php. Would that also fit your needs?

![grabbed_20160125-124352](https://cloud.githubusercontent.com/assets/1366654/12550013/4d1b5888-c361-11e5-8085-58d7db2a5ddd.png)

**Comment by tobiasdiez** [comment]
Can this be closed now with #1928?

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version.
Please use a development build from http://builds.jabref.org/master
The feature will be included in the next release.

**Comment by hao203** [comment]
CitationStyles is popular !
