### ISSUE TITLE
Renaming a file should re-add the extension if missing

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#11903]
**Is your suggestion for improvement related to a problem? Please describe.**
When I rename a file, the extension is not kept

**Describe the solution you'd like**

1. I add a file to an entry.  I want to rename the file For that, I press Ctrl+R
2. The rename dialog appears - the whole filename is selected:\
    ![image](https://user-images.githubusercontent.com/1366654/225427814-214732cb-9636-4fe2-b695-776d76186d48.png)
3. I can type a new file name (e.g., `demo`
4. I press <kbd>Enter</kbd>

- Expected result: The file is named `demo.pdf`
- Actual result: The file is named `demo` (without extension)

JabRef should check whether the user removed the extension. If JabRef cannot find a new extension, it should put the old one (and not just keep the file as is)

Other implementation possibility: The dialog should select the filename only - without extension.

**Comment by ivobubenko** [comment]
Hi, I would like to work on this issue, please assign it to me.

**Comment by Kaven668** [comment]
Sir, can I work on this issue?
