### ISSUE TITLE
Refine FileNameCleanerTest a parameterized JUnit test

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#11911]
Some filenames are invalid on some file systems. JabRef has a filename fixer for that. This fixer should be more properly tested.

1. Convert test cases in `org.jabref.logic.util.FileNameCleanerTest` to [`@CsvSource`](https://mikemybytes.com/2021/10/19/parameterize-like-a-pro-with-junit-5-csvsource/)
2. Add more test cases for Linux (as our CI only executes on Linux)

---

If you have more time/energy, work on  https://github.com/JabRef/jabref/pull/9992 and add test cases for Windows and MacOS to `FileNameCleanerTest`.

**Comment by adambash12** [comment]
I have opened a PR for this issue: https://github.com/JabRef/jabref/pull/12014. Please check it out
