### ISSUE TITLE
Disable irrelevant context menu options for unsaved libraries

### ISSUE THREAD

**Issue by LoayGhreeb** [JabRef/jabref#11920]
1. Create a new library.
2. The "Reveal in file explorer" and "Open terminal here" options should be disabled, as the library is not yet saved to disk.

![Image](https://github.com/user-attachments/assets/f1269b9e-3756-4eca-91d7-a1d65c5da3c7)

**Comment by vaifai** [comment]
Hey, I am new and would like to make an attempt and contribute to this issue.

**Comment by vaifai** [comment]
Starting out to work on this.

**Comment by koppor** [comment]
See https://github.com/JabRef/jabref/pull/11941 for an inspiration how this could work. Note that the conditions are differently in this case.

**Comment by vaifai** [comment]
Hi @koppor , while trying to setup my environment, I was facing a certain issue. I followed exactly the steps mentioned in the local workspace setup section.
```Unsupported Java. 
Your build is currently configured to use Java 21.0.4 and Gradle 8.10.2.

Possible solution:
 - Use Java 19 as Gradle JVM: Open Gradle settings 
 - Open Gradle wrapper settings, change `distributionUrl` property to use compatible Gradle version and reload the project```

I did research about some of the potential ways about how can I resolve this but couldn't fix it. Also, the build is successful but the run isn't.

**Comment by koppor** [comment]
> while trying to setup my environment, I was facing a certain issue. I followed exactly the steps mentioned in the local workspace setup section.

The guide is pretty long and I do not know at wich step you are facing this issue.

I think, you did not paste the line "Unspported Java".

Somewhere in your IntelliJ, another Java version is configured. Could you try: https://stackoverflow.com/a/76574494/873282. Maybe also https://stackoverflow.com/a/75782695/873282.

**Comment by kjswaruph** [comment]
@koppor can i take up this issue, if the issue isnt resolved

**Comment by koppor** [comment]
@vaifai Are you going to finish the issue?

**Comment by kjswaruph** [comment]
@koppor the issue is fixed should i create pr

**Comment by koppor** [comment]
@kjswaruph There are multiple persons available for reviewing. Please submit a pull request. All other ways create much effort for us - and this is still a free time project for us...
