### ISSUE TITLE
Disable some actions when no libraries are open

### ISSUE THREAD

**Issue by LoayGhreeb** [JabRef/jabref#11923]
When no libraries are open in JabRef, some actions remain active but should be disabled, as they depend on an open library to function.

## Actions to disable:
- [ ] File → Save all
  ![Image](https://github.com/user-attachments/assets/e46cd492-e1ad-4c6d-b53f-49130cf93f94)
- [ ] Library → New entry from plain text
  ![Image](https://github.com/user-attachments/assets/4566dc0c-3844-4caf-a642-ef5830490daf)
- [ ] Global search button
  ![Image](https://github.com/user-attachments/assets/f7370299-d8d2-4e72-913c-6c07ec71dc2b)
- [ ] New article button
  ![Image](https://github.com/user-attachments/assets/caaa52ed-e4e1-40d0-b6e5-dee8656956ff)

**Comment by lzmmxh** [comment]
Hey, I am new and would like to make an attempt and contribute to this issue.

**Comment by lzmmxh** [comment]
Hey, I am new and would like to make an attempt and contribute to this issue.
