### ISSUE TITLE
Identifier paste should work with Unicode REPLACEMENT CHARACTER

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#11986]
Clicking on the quick import with a "strange" DOI, JabRef does not find anythign.

![Image](https://github.com/user-attachments/assets/2326d572-d331-49fc-84ba-dc28ffcec701)

To repdoce:

1. Open test PDF `src/test/resources/pdfs/test-doi.pdf` in Acrobat Reader (not SumatraPDF)
2. Select the DOI ` https://doi.org/10.1007/978-3-662-65004-2_3` including the end of line (put the mouse to the next line to include the line break)
3. Copy the selected text
4. Go to JabRef
5. Click the button "Import by ID"
6. Paste
7. Click on the button to import the ID.
8. See that nothing is imorted.

The method to fix is `org.jabref.model.entry.identifier.DOI#findInText`.

Add test to `org.jabref.model.entry.identifier.DOITest#testData`. I assume duplicating a test case and adding [Unicode replacement character](https://simple.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) should be a good start for test-driven development.

**Comment by MadDingzhen** [comment]
Hi! May I work on this issue? I'm new here, thank you!
