### ISSUE TITLE
Click on entry at "Check integrity" should focus the entry and field

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#11997]
1. Open file: `src\test\resources\pdfs\IEEE\ieee-paper.bib`
2. Click on Quality -> Check Integrity
3. See popup\
    ![Image](https://github.com/user-attachments/assets/a2bcd0bf-09c2-4ae0-972f-47e11c9601af)
4. Double click on "Kopp2012"
5. Entry `Kopp2012` is focused, but field in entry editor not focused.

Expected: 

1. Window stays opened
2. Entry is focused in the main table
3. The tab where "Title" is contained is opened in the entry editor
4. The field "Title" is focused in the Entry Editor.

**Comment by mulla028** [comment]
Hello, @koppor! 

Your project interested me, and I would like to work on this issue! Please assign me!

**Comment by koppor** [comment]
Method do call is `org.jabref.gui.entryeditor.EntryEditor#setFocusToField`.
