### ISSUE TITLE
When clicking on a file icon in the extra column, the file should be opened.

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#12005]
1. Create a bib entry
2. Attach a Markdown (`.md`) file to it (via drag and drop)
3. Configure an extra entry table column to show Markdown files as described at https://github.com/JabRef/user-documentation/pull/526
4. The entry table now has a Markdown column\
    ![Image](https://github.com/user-attachments/assets/bfa85eaa-8000-4663-9251-974da34e5827)
5. Click on the icon
6. See that nothing happens

Expected behavior: Markdown editor opens.

Double check: If clicking on the file column, the editor opens

![Image](https://github.com/user-attachments/assets/35db8c60-c9cb-4df9-82c9-a903c18407ce)

**Comment by gabenogu** [comment]
Hello, my name is Gabriel. I am working with a group of student developers from FIU and we would love to work on this issue. Thank you!

**Comment by gabenogu** [comment]
Good morning, so me and my group were looking at the issue and came up with some ideas but we were wondering where specifically to look in the IDE or repository in general to write the logic. Thank you for the help!

**Comment by Siedlerchr** [comment]
@gabenogu  as a starting point I would look here in the MainTableColumnFactory 
https://github.com/JabRef/jabref/blob/175acb390ff225e690ea54aef8d5a610c6f8387a/src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java#L107-L112
