### ISSUE TITLE
Rewrite handleStringData to use CompositeIdFetcher

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#12004]
`org.jabref.gui.externalfiles.ImportHandler#handleStringData` should be rewritten to use `org.jabref.logic.importer.CompositeIdFetcher#performSearchById`. One could first call `org.jabref.logic.importer.CompositeIdFetcher#containsValidId`. If this returns false, then continue at `tryImportFormats` else call `performSearchById`.

Remove unsued methods then.

**Comment by Red12138-java** [comment]
Hi, Koppor! I am really interested in this issue! I want to try my best to solve this issue.Could you assign this issue to me?thank you so much!!
