### ISSUE TITLE
JabRef saves file that break its own parser

### ISSUE THREAD

**Issue by mkaut** [JabRef/jabref#1204]
JabRef version 3.2 on Windows 10.

Steps to reproduce:
1. start the bib-file with the following:
```
% Encoding: windows-1252
@PREAMBLE{ {\providecommand{\noopsort}[1]{}} }
@STRING{annalsofor = {Annals of Operations Research}}
```
2. open in JabRef (should open fine)
3. save the file
4. open again .. here, I either get an "Error opening file" if opening a new instance, or nothing happens (no file get opened, no error) if opening from a running instance.

When I open the .bib-file in a text editor, I see that the first line was changed to:
```
% Encoding: windows-1252@PREAMBLE{ {\providecommand{\noopsort}[1]{}} }
 
 
 
@STRING{annalsofor = {Annals of Operations Research}}
```
i.e., there is a missing line break before the preamble (and extra line breaks after).
This happens also if the preamble is after all string definitions.

Note that the bug in the parser has been reported before  #(b2a9631), but this is more serious since JabRef itself saves the file in a format that it cannot open.

In addition, the fact that I do not even get an error when opening the file from a running instance (i.e., nothing happens) is most likely also an error.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by mkaut** [comment]
I can confirm that it is fixed in the master (tested the .jar file).

As a side node, I see that there is a small change in the output formatting again (Preamble vs. PREAMBLE and Comment vs. comment). Is there any plan to make the formatting stable by some version?
(We are a group sharing a .bib file via SVN and currently sit on v.2.9.2, since after that the formatting has changed with almost every release, creating problems with version control..)

**Comment by koppor** [comment]
We are really heading to get these things table. See #116.

The current decision is that we rewrite entries only if they are changed. This should enable working with different versions easily.

The thing is, that it seems that this is not implemented for `@String` and `@Comment`.
