### ISSUE TITLE
Dropping multiple PDFs leads to a wrong file field

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#12098]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a new library
2. Have 10 PDFs
3. Drag'n'drop them into JabRef to be added
4. See that **each** BibEntry has **all** files attached

See https://github.com/JabRef/jabref/pull/12072#issuecomment-2439768295 for screenshots etc.

**Comment by Siedlerchr** [comment]
That was fixed in https://github.com/JabRef/jabref/pull/12297  by @InAnYan
