### ISSUE TITLE
make default word searches AND searches (not OR)

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#12095]
**Is your suggestion for improvement related to a problem? Please describe.**
Searching for, say "`<author>`" and "`<title word>`" finds many irrelevant entries matching one or the other, not both.

**Describe the solution you'd like**

When I type multiple search texts into the search bar, it would be great if one could set the default search mode to an automatic AND search.

**Comment by koppor** [comment]
With the latest development version, this should work?

**Comment by koppor** [comment]
Note that with the latest development version, the fulltext search might stop working.

**Comment by wujastyk** [comment]
I did try today's build, 2024-10-26, but there's something wrong with the cursor control.  When typing in a data field, the cursor would jump up to the search bar.  So I gave up on today's release and went back to Monday 21 so I can get work done.

JabRef 6.0--2024-10-21--ca4e9bb
Linux 6.8.0-47-generic amd64 
Java 22.0.2 
JavaFX 24-ea+14

Bothj 2024-10-26 and 6.0--2024-10-21--ca4e9bb continue to demonstrate the difficulty I'm describing (multi-word searches are OR not AND).

**Comment by koppor** [comment]
Ah, it happend, what should not happen - the last version of Lucene-based search does not work (Boolean operator issue) - and Postgres does not work either (focus issue). We will try to fix soon. -> Filed https://github.com/JabRef/jabref/issues/12099 to track.

**Comment by koppor** [comment]
@wujastyk Your blocking issue (described at https://github.com/JabRef/jabref/issues/12095#issuecomment-2439783464) seems to be solved. Since we use "AND" for the search, I close the issue.

Please reopen if you encounter strange behavior regarding "AND".
