### ISSUE TITLE
Search field is focussed too often

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#12099]
> When typing in a data field, the cursor would jump up to the search bar.

From: https://github.com/JabRef/jabref/issues/12095#issuecomment-2439783464

This could ref https://github.com/LoayGhreeb/jabref/issues/9.

Maybe because of https://github.com/JabRef/jabref-issue-melting-pot/issues/583?

**Comment by wujastyk** [comment]
I'm on 

JabRef 6.0--2024-12-02--1a803a7
Linux 6.8.0-49-generic amd64 
Java 23.0.1 
JavaFX 23.0.1+4

and I don't have the problem.
