### ISSUE TITLE
Dropping a PDF on an entry should be consistent

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#121]
When one wants to attach a PDF to an entry **and** move the PDF to the local data base folder, this is only possible by dropping the PDF into the preview pane or the "File" field (in the tab "General"). Then, the dialog "link to file" (call it "link dialog") is shown. When one drops the PDF onto the entry in the table, another dialog ("Import Metadata from PDF", call it "import dialog") is shown.

The import dialog offers "only attach PDF", which is one option of the link dialog. Thus, the options offered at the import dialog are incomplete. Therefore, the options of the link dialog should be included in the import dialog, too.

**Comment by koppor** [comment]
# drop on table

![drop on table](https://cloud.githubusercontent.com/assets/1366654/23759286/948b286a-04ec-11e7-820f-c95c7e5705cd.gif)

# drop on preview

![drop-on-preview](https://cloud.githubusercontent.com/assets/1366654/23759355/d8dac32c-04ec-11e7-843c-6d7349f6246b.gif)

**Comment by tobiasdiez** [comment]
I always found it confusing that I can't simply drag and drop a pdf file to the main table in order to import it (I think dropping on the tab header works). What do you think about:
- drop on table: always import as new entry
- drop on preview or entry editor: link

**Comment by koppor** [comment]
## drop on table

![grafik](https://cloud.githubusercontent.com/assets/1366654/24362840/4992d882-130e-11e7-9b03-09ee90a0f6dc.png)

## drop on preview

![grafik](https://cloud.githubusercontent.com/assets/1366654/24362856/5515aba8-130e-11e7-98c1-8c433e224cbb.png)

![grafik](https://cloud.githubusercontent.com/assets/1366654/24362864/5d97be1a-130e-11e7-9ba5-fdd9037e3f3a.png)

**Comment by koppor** [comment]
Idea: When creating a new entry, JabRef should parse the PDF using both the PDF Content importer and the XMP. Then, using the merge entries dialog, the resulting BibTeX entry should be offered.

**Comment by Siedlerchr** [comment]
Although we talked at this during JabCon, I have problems remembering all decisions: 
But I think we should show that dialog for MainTable + Preview 
Only if the files is dropped to the File Listview under General it should be linked to the entry without further notice

**Comment by tobiasdiez** [comment]
The decision was as far as I remember:
- Drop on maintable -> new entry (show merge dialog if information from xmp and PDF content are different)
- Drop on maintable with Shift held-> link file to target entry
- Drop on preview/entry editor -> link file

To distinguish the first two different drop behaviors for the maintable, the process there should be visual feedback, i.e., display "add as new entry" vs "link file" under the cursor [java code](https://docs.oracle.com/javafx/2/drag_drop/jfxpub-drag_drop.htm#BABFACBF).

**Comment by koppor** [comment]
I have following forces:

- Be consistent with Windows shortcuts, where <kbd>Alt</kbd> is link and <kbd>Shift</kbd> is move
- Being able to easily move files from the Downloads-Directory to the file directory

Thus, I propose to refine that with

- Drop on maintable -> new entry (show merge dialog if information from xmp and PDF content are different)
- Drop on maintable with <kbd>Alt</kbd> held: link file to target entry
- Drop on maintable with <kbd>Shift</kbd> held: move the file to file directory and link file to target entry
- Drop on preview/entry editor: link file to target entry
- Drop on preview/entry editor with <kbd>Alt</kbd> held: link file to target entry
- Drop on preview/entry editor with <kbd>Shift</kbd> held: move the file to file directory and link file to target entry

Thereby, I accept that:
- I have to push the "Cleanup button" afterwards to rename the file to the "correct" filename

**Comment by tobiasdiez** [comment]
What about always move and rename the file if you hold the shift key?

**Comment by koppor** [comment]
Yeah, sounds great: Updated the comment

**Comment by Siedlerchr** [comment]
Unfortunately this is a bit problematic. I can't really detect if the drag and drop is coming from external if a key is pressed.  I tried to use a combination with a KeyEventFilter but that does not work reliable,.

**Comment by tobiasdiez** [comment]
These modifiers are handled by javafx automatically and are available through [getTransferMode](https://docs.oracle.com/javafx/2/api/javafx/scene/input/DragEvent.html#getTransferMode()). The different [tarnsfer modes](https://docs.oracle.com/javafx/2/api/javafx/scene/input/TransferMode.html) are MOVE (no modifier), COPY (Ctrl) and LINK (Shift + Ctrl). The modifier might no be correct (and may actually vary by OS).

**Comment by Siedlerchr** [comment]
Yeah, thanks for the hint! I absolutely did not know that these TranserModes represent the 
modifier/drag & drop combination. I must admit, I also did not know about the alt/shift keys for drag and drop in Windows.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by Siedlerchr** [comment]
Dropping on entry editor is now handle in #4408

**Comment by koppor** [comment]
Follow-up discussion at https://discourse.jabref.org/t/prevent-jabref-from-auto-renaming-and-moving-files/2596/9?u=koppor
