### ISSUE TITLE
Parsing of "distributed systems online" paper does not work

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#12135]
Follow-up to https://github.com/JabRef/jabref/pull/12018

PDF from https://www.computer.org/csdl/magazine/ds/2002/02/o2001/13rRUEgs2Q8

Attention! The PDF must not checked in to JabRef while fixing. One can use it for local development though.

The tests could be written in a way that they are executed if the file exists ( `assumeTrue`) - and skip if it does not exist. Then the JAvaDoc says where to download the PDF and where to place.

```bibtex
@InProceedings{Distributed2002,
  author    = {Fundamentals of Distributed and Computing: and A Practical and Tour of Vector and Clock Systems and Roberto Baldoni • Universita di Roma and Italy and Michel Raynal • IRISA and France},
  booktitle = {IEEE Distributed Systems Online Published by the IEEE Computer Society},
  title     = {Vector Clocks},
  year      = {2002},
  publisher = {IEEE},
  file      = {:- Vector Clocks.pdf:PDF},
  groups    = {Vector Clocks},
}
```

![Image](https://github.com/user-attachments/assets/acd800aa-22d4-498b-91a3-fc029a6a46af)

@leaf-soba Can you have a look?

**Comment by leaf-soba** [comment]
OK, I'll try to solve it as soon as possible.
