### ISSUE TITLE
Cannot load any jstyle file

### ISSUE THREAD

**Issue by messiem** [JabRef/jabref#12131]
### JabRef version

5.15 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 24.04.1

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download the example jstyle file at https://docs.jabref.org/cite/openofficeintegration (saved as UTF-8, and my old jstyle that used to work don't anymore)
2. In the OpenOffice/LibreOffice integration panel, click "Select style" then "Add style file" and select the jstyle file
3. The error "Invalid style detected" occurs with description "You must select a valid style file. Your style is probably missing a line for the type "default"." [default is correctly defined in jstyle file].

Note - tested with 5.15 and latest development version:
JabRef 6.0--2024-10-30--e22f2fd
Linux 6.8.0-47-generic amd64 
Java 21.0.2 
JavaFX 23.0.1+4

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
> 3\. The error "Invalid style detected" occurs with description

Does not happen here.

It is added:

![Image](https://github.com/user-attachments/assets/ad3e7abc-73fb-429f-b5ab-4258e1728bb0)

The content of `example.jstyle`:

```text
NAME
Example style file for JabRef-OpenOffice integration.

JOURNALS
Journal name 1
Journal name 2

PROPERTIES
Title="References"
IsSortByPosition="false"
IsNumberEntries="false"
ReferenceParagraphFormat="Default"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
AuthorField="author/editor"
YearField="year"
MaxAuthors="3"
MaxAuthorsFirst="3"
AuthorSeparator=", "
AuthorLastSeparator=" & "
EtAlString=" et al."
ItalicEtAl="true"
YearSeparator=" "
InTextYearSeparator=" "
BracketBefore="["
BracketAfter="]"
BracketBeforeInList="["
BracketAfterInList="]"
CitationSeparator="; "
UniquefierSeparator=","
GroupedNumbersSeparator="-"
MinimumGroupingCount="3"
FormatCitations="false"
CitationCharacterFormat="Default"
MultiCiteChronological="false"
PageInfoSeparator="; "

LAYOUT
article=\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\author}
(<b>\year\uniq</b>). <i>\title</i>, \journal \volume\begin{pages} :
\format[FormatPagesForHTML]{\pages}\end{pages}.

book=\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\author}\begin{editor}
\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\editor} (Ed.)\end{editor},
<b>\year\uniq</b>. <i>\title</i>. \publisher, \address.

incollection=\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\author}
(<b>\year\uniq</b>). <i>\title</i>. In: \format[AuthorLastFirst,
AuthorAbbreviator,AuthorAndsReplacer]{\editor} (Ed.), <i>\booktitle</i>, \publisher.

inbook=\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\author}
(<b>\year\uniq</b>). <i>\chapter</i>. In: \format[AuthorLastFirst,
AuthorAbbreviator,AuthorAndsReplacer]{\editor} (Ed.), <i>\title</i>, \publisher.

phdthesis=\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\author}
(<b>\year\uniq</b>). <i>\title</i>, \school.

default=\format[AuthorLastFirst,AuthorAbbreviator,AuthorAndsReplacer]{\author}
(<b>\year\uniq</b>). <i>\title</i>, \journal \volume\begin{pages} :
\format[FormatPagesForHTML]{\pages}\end{pages}.
```

**Comment by Siedlerchr** [comment]
Works here on mac as well. Did you maybe miss the last line while copying the style code? That is what the error message is indicating

**Comment by messiem** [comment]
I attach both the jstyle I am trying to load, and the screenshot of what I get. I had to rename .jstyle to .txt[exemple.txt](https://github.com/user-attachments/files/17578020/exemple.txt)
 because GitHub refuses that extension...

![Image](https://github.com/user-attachments/assets/34dedb98-48ab-4c0a-99bb-70661375b760)

**Comment by Siedlerchr** [comment]
Hm,, I also tried with your uploaded jstyle and it's perfectly fine.

**Comment by messiem** [comment]
Yeah I don't have an explanation - as I mentioned, I used to have several jstyle files loaded and working, and I can't reload them (but they still work in the app for the ones that were previously loaded). 

Is there some configuration file I could try to delete for instance, where something might have gotten corrupted? I tried  
```
sudo apt remove --purge jabref
sudo apt install ./jabref_5.15_amd64.deb
```
but that didn't solve the problem. Any suggestion appreciated :)

**Comment by messiem** [comment]
Nevermind. I finally figured it out. 
It turns out you cannot reload a file that was already loaded. In my screenshot only the first few jstyle files were visible, and I didn't see there was an example.jstyle already there. Since the error message was suggesting something was wrong with the file instead of mentioning the file was already loaded, this didn't cross my mind.

Sorry abut this! I am closing this but would suggest to update the error message if possible.  

Thanks again for looking into it!
