### ISSUE TITLE
adding file with illegal character does not proceed

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#12212]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-17--572c823 Linux 6.11.7-300.fc41.x86_64 amd64  Java 23.0.1  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ... I have a pdf with a `?` in the filename. I think that is illegal.
2. ... I attach it to the entry.
3. ... it is displayed :whitecheckmark:
4. JabRef does not allow me to open iot with a double click

I would have expected that JabRef asks me whether it should rename the file (I think that worked in the past).

**Comment by Siedlerchr** [comment]
Root cause is the PR https://github.com/JabRef/jabref/pull/11539  which no longer does a check
