### ISSUE TITLE
Customize save order in .layout

### ISSUE THREAD

**Issue by calixtus** [JabRef/jabref#12222]
As discussed in #12220 the .layout subsystem could provide some way to override the preferences save order.

**Comment by koppor** [comment]
Documentation: https://docs.jabref.org/collaborative-work/export

If we have more use cases than single exports, we can discuss further.

The idea refs https://github.com/JabRef/jabref/issues/8701 somehow. There, all settings concerdings a library were wished to be contained in the library itself - to make it portable. -- However, I see the `.layout`s differently.

**Comment by koppor** [comment]
Related (follow-up) issue: https://github.com/JabRef/jabref-issue-melting-pot/issues/700?notification_referrer_id=NT_kwDOABTafrMxMzU0NjgxMTQ2ODoxMzY2NjU0
