### ISSUE TITLE
Improve translation system

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1222]
We have issues with the translation. Is the way that we are doing it, really the right way? Self-written python scripts? [popeye](https://github.com/JabRef/popeye) with code and UI from the 2000s?

This issue collects some pointers and alternatives. It is not yet complete, but will be updated. Feel free to edit this text.

## Code aspects
 * [gettext-commons](https://code.google.com/archive/p/gettext-commons/wikis/Tutorial.wiki). Seems to be cool, but not maintained any more
 * Switch to JavaFX internationalization
  * http://stackoverflow.com/q/10143392/873282
  * https://blogs.oracle.com/naoko/entry/javafx_localization

## Translator aspects

 * Translation server: http://jabylon.org/. Has to be hosted by our own.
 * [Transifex](https://www.transifex.com/) (SaaS offering): 
  * [GitHub integration](http://docs.transifex.com/integrations/github/). Has to be hosted by our own.
  * [free for open source projects](https://www.transifex.com/pricing/) - scroll down at that page to read the text "Haben Sie ein Open Source-Projekt? Sie können kostenlos Übersetzungen für Ihr Open Source-Projekt crowdsourcen."

**Comment by oscargus** [comment]
I somehow share the feeling, but let me point out a few things:

* The Python script are not needed, but really convenient
* Java properties files is a standard way to do this
* Popeye is not strictly required although it is a bit surprising that there are no (other) well-maintained plug insurance for this, the Eclipse plugins I've tried claim to offer similar functions but I haven't really succeeded to use them properly
* It may be simpler to not use unencoded UTF-8 as more tools support that automatic conversion but somehow you select what problems you face

**Comment by oscargus** [comment]
Also, see http://stackoverflow.com/questions/7768997/software-for-managing-java-lang-properties-files-for-translation

**Comment by oscargus** [comment]
I also found http://attesoro.org/ (feel free to edit the original post, being lazy from the phone now...)

**Comment by Siedlerchr** [comment]
I know that owncloud is using transifex, but I haven't worked with it before.
On Stackoverflow some people recommend 
http://zanata.org/
Or PoEditor (also Github integration and free for OS)
https://poeditor.com/pricing/

**Comment by simonharrer** [comment]
Why I do like the current system:

- Everything is already in the repository (and not stored in the cloud from which it has to be retrieved at some point in time)
- The format is very simple (property files) with the english language on the left and the translation on the right hand side (cloud provider normally use keys like "preferences.proxy.hostname" instead which requires that the translator has to look up the english translation in the english file and then is able to do the translation in his own language file)
- We have a lot of checks in place so that everything is sound (no duplicates, no missing entries, ...)
- It is very simple to use when using a text editor and having an understanding of git or the github ui (but I accept that it is hard to use if one does not want or know how to use the github ui or edit text files)

We should try not to loose too many of the advantages our current system has.

**Comment by mlep** [comment]
Editing of a text file is quite convenient: easy to use for advanced users, but also for beginners. Of course, beginners may make mistake in the syntax, but the difficult part is to have the translated sentence; it is usually easy to correct the syntax afterward.
Popeye is easy to use, but its features do not help me much in getting the work done. In fact it is kind of feature-poor (no suggestion, no dictionary).
About tools, there is http://pootle.translatehouse.org/. I know it is used for LibreOffice, but I have not used it, and I do not know if it could be suitable for JabRef.

**Comment by koppor** [comment]
## singular / dual / plural handling

We should also think about singular/plural handling. [Some languages also have a dual form](https://en.wikipedia.org/wiki/Dual_%28grammatical_number%29).

Example from the code (https://github.com/JabRef/jabref/blob/ad5a683/src/main/java/net/sf/jabref/gui/FindUnlinkedFilesDialog.java#L610):

```java
"The import finished with warnings:\n" + "There " + (errors.size() > 1 ? "were " : "was ")
    + errors.size() + (errors.size() > 1 ? " files" : " file")
    + (errors.size() > 1 ? " which" : " that") + " could not be imported.",
```

## untranslated strings

Example from the code (
https://github.com/JabRef/jabref/blob/ad5a68318c1869be83c68678d2bc838060826b5d/src/main/java/net/sf/jabref/importer/EntryFromFileCreatorManager.java#L143)

```java
importGUIMessages.add("Problem importing " + f.getPath() + ": Unknown filetype.");
```
(and the subsequent lines)

**Comment by oscargus** [comment]
That untranslated string is never used as far as I remember. It is only checked if there are some messages...

I've spent some time to try to search for such cases, but sometimes I still find an odd string.

**Comment by koppor** [comment]
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.
