### ISSUE TITLE
Add "Release" page to Github project page

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1223]
It would be nice to have a "Releases" page at the project page.
@koppor 
See https://help.github.com/articles/creating-releases/
How it looks like:
https://github.com/blog/1547-release-your-software

**Comment by tobiasdiez** [comment]
I think this is already actively used, see https://github.com/JabRef/jabref/releases

**Comment by koppor** [comment]
We want do drive our traffic to FossHub.com to avoid high load on the GitHub servers.

The CHANGELOG is linked at http://www.jabref.org/#help. Maybe, that is not too obvious?

**Comment by Siedlerchr** [comment]
@tobiasdiez Ah okay, but it is not directly visible (for me) as a  Tab.
@koppor  No problem with that.  Maybe it is helpful to have a link at the FossHub DL page to the Changelog.

**Comment by simonharrer** [comment]
@Siedlerchr do you mean as a tab on jabref.org or as a tab on github?

**Comment by Siedlerchr** [comment]
@simonharrer  As a tab at the github project:; 
![githubreleases](https://cloud.githubusercontent.com/assets/320228/14613528/14a52abe-059d-11e6-8be0-bda9bf436a21.png)

**Comment by simonharrer** [comment]
I think you are mistaken: the tab is only available under code in the second hierarchy layer.

**Comment by Siedlerchr** [comment]
Oh, yes that is what I was searching for.

2016-04-18 19:55 GMT+02:00 Simon Harrer <notifications@github.com>:
