### ISSUE TITLE
Can't link to an external file.

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#12236]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 6.0--2024-11-25--6b59c55 Linux 6.8.0-49-generic amd64  Java 23.0.1  JavaFX 23.0.1+4

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 6.0--2024-11-25--6b59c55
Linux 6.8.0-49-generic amd64 
Java 23.0.1 
JavaFX 23.0.1+4

1. Go to the General tab
2. Try to link to a file (PDF)
3. Doesn't work.  You can select a file, but its name doesn't come up on the file window, and the file name isn't added to the biblatex record.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Thanks for the report. Overlooked the else case while working on it 🤦 .  Next main build will have the fix
