### ISSUE TITLE
Use Markdown in AI Summary tab

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#12233]
**Is your suggestion for improvement related to a problem? Please describe.**

Currently, summary is formatted in a `TextArea`. This allows text to be selected, but the formatting is ugly. Markdown is a de-facto standard for chat LLMs.

**Describe the solution you'd like**

Use Markdown in summary window.

**Additional context**

There is a long-standing problem with JavaFX: you cannot select `Text` or `Label`. Only text in `TextField` or `TextArea` can be selected. However, text in `WebView` can be selected, and it is already used in JabRef in entry preview!

Thus, you have 2 options:

1. Implement Markdown using `Text` or `Label`s and add a button `Copy` somewhere at the end.
2. Implement Markdown using `WebView`.

Option 1 is, I think, easier to implement, however option 2 is preferred

**Comment by Siedlerchr** [comment]
Implementation hint: Look at the `MarkdownEditor`

**Comment by mulla028** [comment]
@koppor, Hello!
I would like to take a shot here 😄

**Comment by ThiloteE** [comment]
I don't think we should force Markdown. It should be toggleable. Sometimes I want to copy the unformated markdown somewhere else. Sometimes I want to copy the Markdown.

**Comment by koppor** [comment]
> I don't think we should force Markdown. It should be toggleable. Sometimes I want to copy the unformated markdown somewhere else. Sometimes I want to copy the Markdown.
> 
> But yes, Markdown should be the default.

I think, you are requesting a context menu with two copy options as available in the context menu of an entry

![Image](https://github.com/user-attachments/assets/92ebac34-ee7f-407e-976b-f0f9d602cafd)

Note: this is not avaialble in the context menu of the preview (yet)

![Image](https://github.com/user-attachments/assets/4d9fbff7-c64a-483e-8f4d-8c671017c23d)

**Comment by mulla028** [comment]
@InAnYan @koppor could you provide more description and what idea is about. Thank you!

**Comment by ThiloteE** [comment]
@koppor

No, I am explicitly talking about a toggle. Can be a tab or dropdown too.

<reason> Reason: Eventually, html or other formatting could be added as well to the list. Not only do I argue that being able to copy the raw text is important, also in the mid / long term, we want to be be able to edit responses directly in the JabRef UI, which will enable having longer conversations, even when the model responded with an inadequate response. Finally, being able to look at the source, just like in biblatex source tab is important, otherwise we will have users that raise issues like these: https://github.com/nomic-ai/gpt4all/issues/864 </reason>

**Comment by ThiloteE** [comment]
@mulla028 

When you start JabRef and open the entry editor (by clicking on an entry), you can go to the AI summary / AI chat tab. Copying is already possible and it should still be possible, even with the markdown feature.

IMHO, if my proposal to use a toggle, tab, dropdown, right-click menu to switch between normal and markdown view gets implemented, then copying should work for both views (also via ctrl + c).

### Related documentation:

- https://docs.jabref.org/ai
- https://www.markdownguide.org/basic-syntax/

**Comment by mulla028** [comment]
@ThiloteE
So the Idea is to add the toggle which will convert the `AI Summary` into markdown format right, but If toggle is off it should be just normal text, am I getting it right?

**Comment by InAnYan** [comment]
Hi, @mula! Is there anything specific you want to ask about my issue?

I might've formulated it wrong. By "use Markdown" I meant, that LLM models typically generate output not just in plain text, but in markdown (rich text), and we need a way to display a Markdown not in its source, but to apply it and stylize the text.

By "1. Use Text or Labels for Markdown" I meant to render Markdown as several Text elements with different CSS styles. For that you need a Markdown parser.

By "2. Use WebView" I mean using a web view component in summary tab. In this option you need to convert Markdown to HTML (I think JabRef already has something like that).

Thilo has proposed a new feature: toggling. It will allow you to switch between styles: one using TextArea (this is what we already have) and Markdown rendering (two options I told above). This will be a great plus if you implement option 1. If you implement option 2, then there would be no need to show Markdown source in TextArea, as users are able to copy from WebView

**Comment by mulla028** [comment]
@koppor @Siedlerchr
How do you guys prefer it to be implemented?

**Comment by koppor** [comment]
@mulla028 Use WebView. See org.jabref.logic.layout.format.MarkdownFormatter#format of how to transform Markdown to HTML.

WebView component is OK, because it is only one. Similar to the EntryPreview, where we also use one.

Reason: The user experience with WebView is better than having multiple copy buttons. Nearly no other app has that...

---

@InAnYan 

This is [ADR-0036](https://github.com/JabRef/jabref/blob/main/docs/decisions/0036-use-textarea-for-chat-content.md)?

Can you link "only one package" in the ADR (you will find the text in the ADR itself)

Your option 2 here is option "Use a Markdown parser to convert content into HTML and use a WebView for one message" in that ADR? Wasn't that considered bad? What has changed now?

**Comment by InAnYan** [comment]
1. This is ADR for chat history (yeah, I haven't written an ADR for summarization).
2. Because `WebView` is only one, I think it is okay (rather than having 10 `WebView`s for 10 chat messages)

**Comment by mulla028** [comment]
> [@mulla028](https://github.com/mulla028) Use WebView. See org.jabref.logic.layout.format.MarkdownFormatter#format of how to transform Markdown to HTML.
> 
> WebView component is OK, because it is only one. Similar to the EntryPreview, where we also use one.
> 
> Reason: The user experience with WebView is better than having multiple copy buttons. Nearly no other app has that...
> 
> [@InAnYan](https://github.com/InAnYan)
> 
> This is [ADR-0036](https://github.com/JabRef/jabref/blob/main/docs/decisions/0036-use-textarea-for-chat-content.md)?
> 
> Can you link "only one package" in the ADR (you will find the text in the ADR itself)
> 
> Your option 2 here is option "Use a Markdown parser to convert content into HTML and use a WebView for one message" in that ADR? Wasn't that considered bad? What has changed now?

Sounds good 👍

**Comment by koppor** [comment]
> 1. This is ADR for chat history (yeah, I haven't written an ADR for summarization).

@InAnYan Can you craft a new (short) ADR for chat summarization and reference that ADR? Moreover, fix that ADR by adding the link to the markdown framework?

**Comment by InAnYan** [comment]
https://github.com/JabRef/jabref/issues/12233#issuecomment-2523107137

https://github.com/JabRef/jabref/pull/12277

Made a PR :)

**Comment by InAnYan** [comment]
> > 1. This is ADR for chat history (yeah, I haven't written an ADR for summarization).
> 
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/13097618?s=64&amp;u=1332a861d7bcd983ccbf29e0b85a04157e349765&amp;v=4">@InAnYan](https://github.com/InAnYan) Can you craft a new (short) ADR for chat summarization and reference that ADR? Moreover, fix that ADR by adding the link to the markdown framework?

https://github.com/JabRef/jabref/pull/12277

Made a PR :)
