### ISSUE TITLE
Place "AI chat" and "AI summary" in one tab "AI"

### ISSUE THREAD

**Issue by InAnYan** [JabRef/jabref#12241]
**Is your suggestion for improvement related to a problem? Please describe.**

JabRef already has a lot of tabs in Entry Editor. AI functionality adding +2 more.

**Describe the solution you'd like**

What if we could make a single "AI" tab with sub-tabs for chatting and summarization?

IMHO, it will save space + will allow other features to be integrated (what if there will be new kind of analysis with +1 more tab, I plan to do something like that)?

**Additional context**

What do you think? If we agree, then this will be an easy good-first-issue 😄 

Steps to implement:

1) Introduce single component "AI tab".
2) Add tabs node to that component.
3) In Entry Editor setting leave only 1 option for "Show AI tab".
4) In "AI tab" component show tabs that are only allowed (chatting and summarization are distinct features and one of them might be turned off).

**Comment by ar-rana** [comment]
Hello maintainers,
Could you please assign me this issue.

**Comment by InAnYan** [comment]
@koppor How Entry Editor settings will be changed here?

My guess:

1. Show "AI" tabs
  1.1. Show "AI Chat" tab
  1.2. Show "AI Summary" tab

Couple of questions:

1. Does it look okay?
2. What will happen if 1 is on, but both 1.1 and 1.2 are off?
   Oh, maybe we can add a notice there like: "No features are enabled. Etc., etc.".
3. Should they be named "AI Chat" and "AI Summary" or "Chat" and "Summary"?

**Comment by koppor** [comment]
This issue wants to introduce sub tabs? Ik think, it could be OK, if the "sub tabs" are on the left side - similar to the preferences.

If you have something else in mind, please prepare UI sketches and share different options. Just use PowerPoint or draw.io (PlantUML's salt does not offer vertical tabs - https://plantuml.com/salt)

We should decide in the JabRef AI group.

> Oh, maybe we can add a notice there like: "No features are enabled. Etc., etc.".

We already have that for the current tabs. Maye, a slight modification is needed, but the concept is there.

**Comment by InAnYan** [comment]
I didn't label this issue as "Good First Issue", because I wanted your (core developers) feedback first. But it seems users also like this idea 😄.

No, there is no need for UI sketches, it's super simple. Just another level of tabs.

Initially, I thought about placing sub-tabs in upper side. But the left side is much better!

Let me refine the issue to address this point and find a notice for "No features" in JabRef

**Comment by InAnYan** [comment]
@ar-rana Let me summarize our view:

In entry editor:

1. Make single "AI" tab.
2. If AI features are not enabled, then show "Privacy Policy" dialog that Oliver linked.
3. If AI features are enabled, then show tabs "Chat" and "Summary".
4. But show "Chat" and "Summary" only if they are enabled. Take a look at JabRef Preferences -> Entry editor preferences.
5. If no chatting or summarization is enabled, then show an informative message that 1) tells users that no features are enabled, 2) tell them to go to AI preferences to enable them. (I think you can reuse component `ErrorState` in `ai` package for this purpose).

In Entry Editor preferences:
1. Make a new option "Show AI tabs".
2. Indent existing preferences for chatting and summarization.
3. If "Show AI tabs" is unticked, then disable options for chatting and summarization (remember, disabling - doesn't mean turning off).

**Comment by ar-rana** [comment]
Understood, thank you for simplifying the issue.

**Comment by koppor** [comment]
@ar-rana We had an internal discussion: Please do not implement this issue. The majortiy of the team does not like the approach. - Thus, please choose another "good first issue". We are sorry for the inconvenience caused.
