### ISSUE TITLE
Keywords should be separable by newline

### ISSUE THREAD

**Issue by davidcbenson** [JabRef/jabref#1226]
Jabref 3.0 and 3.2 (as I have done it)

Regardless of the separation you initially use, all 'new lines' get removed once the bibiography reloads. On a related issue, it would be really nice if a newline could be used as part of the automatic addition of keywords.

**Comment by mlep** [comment]
About 
> Regardless of the separation you initially use, all 'new lines' get removed once the bibiography reloads.

This is indeed the default behavior. However, you can instruct JabRef not to remove the new lines in the keywords field as follow: 
- Options -> Preferences
- Select "File" on left panel
- In "Do not wrap the following fields when saving:", add "keywords"

**Comment by oscargus** [comment]
Related #705

**Comment by davidcbenson** [comment]
Thanks. I never would have figured that out.

**Comment by simonharrer** [comment]
Thank you for raising this issue. I think it is already solved with the current functionality of JabRef. Hence, I close it for now.
