### ISSUE TITLE
Replace BibTexParser & Writer

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#123]
The class `BibtexParser`should be replaced or rewritten if possible. Currently, it is quite a mess. Also, it only does the parsing of the files and not the writing. 

We need to investigate if we can replace it by some external library like [jBibTex](https://github.com/jbibtex/jbibtex) or need to rewrite it properly. The same probably holds for the writing process which should be aligned with the reading process.

Any information appreciated.

**Comment by koppor** [comment]
Maybe we should check all Java-based [BibTeX-based managers](https://github.com/JabRef/jabref/wiki/Alternatives#bibtex-based) how they do it?

**Comment by koppor** [comment]
jBibTex should be checked if arbitrary keys are supported. The commit https://github.com/S-Shimotori/jbibtex/commit/da1bb9eae13dc399fe775245fedb38aae67ffb33 indicates that the keys are are hardcoded. Another option is to drop support of customized entries completely and only support hard-coded ones.

**Comment by koppor** [comment]
The [ANTLRv3 Grammar](http://stackoverflow.com/a/7597864/873282) could be a good start. If we use it, we have to ask @bkiers if he is willing to relicense it GPLv2+ or any other GPL-compatible license.

**Comment by bluebirch** [comment]
Erathostenes (https://bitbucket.org/mkmatlock/eratosthenes/wiki/Home) use
jBibTeX and arbitrary keys are supported, as far as I am aware since I use
it.

mån 24 aug 2015 21:27 Oliver Kopp <notifications@github.com> skrev:

**Comment by koppor** [comment]
We should generate test cases for it. I started to collect publicly available bibtex files at [the wiki](https://github.com/JabRef/jabref/wiki/Publicly-available-BibTeX-files). Should we include them using git submodules? I think, that is too much overhead.

**Comment by lenhard** [comment]
[jBibTex uses some weird proprietary license](https://github.com/jbibtex/jbibtex/blob/master/LICENSE.txt). I don't think we can use it on that basis.

**Comment by koppor** [comment]
Why? The README.md states: "JBibTeX is licensed under the BSD 3-Clause License." And the text seems to be the BSD 3 licensed. Or do you think, he mixed in a strange statement?

**Comment by lenhard** [comment]
My Bad! I just did not recognize the text of BSD. So jBibTex is fine.

**Comment by koppor** [comment]
Comments in the file before all entries and after all entries should be kept.

Example (from http://shelah.logic.at/eindex.html)

```
%  a sample bibliography file
%  

@article{small,
author = {Freely, I.P.},
title = {A small paper},
journal = {The journal of small papers},
year = 1997,
volume = {-1},
note = {to appear},
}

@article{big,
author = {Jass, Hugh},
title = {A big paper},
journal = {The journal of big papers},
year = 7991,
volume = {MCMXCVII},
}

%  The authors mentioned here are almost, but not quite,
%  entirely unrelated to Matt Groening.
```

**Comment by vruusmann** [comment]
The JBibTeX library has full support for inline comments. In JavaCC terminology, they are part of the class model object as special tokens (attached to normal tokens).

**Comment by koppor** [comment]
The library needs a deeper invesitagation. Just browsing https://github.com/jbibtex/jbibtex/blob/master/src/main/java/org/jbibtex/LaTeXPrinter.java makes the impression that strings are somehow replaced with unicode chars at some writing. But I can't see how this class is used just by browsing. (Comments missing :innocent:)

There are some forks like
 * https://github.com/manoelcampos/jbibtex/ (code refactorings)
 * https://github.com/psiotwo/jbibtex (support for czech characters)
which are not integrated. I asked @vruusmann via email.

**Comment by oscargus** [comment]
Note that everything outside of `@xxx{ }` is a comment in BibTex. Hence, just make sure that you support anything, not just lines starting with `%`.

**Comment by vruusmann** [comment]
The JBibTeX parser (which is auto-generated after JavaCC grammar file) skips all content that doesn't start with `%` or `@`.

Currently, normal and special tokens are created, but they are not added to the resulting high-level class model objects (eg. the `org.jbibtex.StringValue` instance that is returned by `org.jbibtex.BibTeXComment#getValue()` does not provide method `getToken()`). However, this kind of API would be easy to introduce if necessary.

**Comment by lenhard** [comment]
This resolution of this issue heavily depends on our decision for  #116

If we decide to maintain configuration options (and therefore custom formats), it is highly likely that we cannot use a third party library, but have to implement serialization on our own. Having said that, I a very much for completely rewriting the serialization as it currently stands.

**Comment by lenhard** [comment]
`BibtexParser` and `BibtexEntryWriter` have already been changed significantly in our endeavour to standardize writing and parsing. See #116

With the customizations we want to keep and implement, using an external API is really not an option. Therefore, I am closing this issue. If there are more things to discuss, we can defer to #116, or for specific aspects open a new issue.
