### ISSUE TITLE
Unable to set custom application path for external file types

### ISSUE THREAD

**Issue by mkdjr** [JabRef/jabref#12311]
### JabRef version

5.15 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11 Enterprise Version 23H2; OS build 22631.4460; Windows Feature Experience Pack 1000.22700.1047.0

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a library in JabRef.
2. Select `File `-> `Preferences` -> `External file types`
3. For a document of your choice (`.md`, for example), click on the edit icon (see Figure 1 in Appendix).
4. Select `Custom` from the `Application` radio selection (see Figure 2).
5. In the file explorer modal that appears, select the desired binary path (selected path shown in Figure 3).
6. Click `OK`.

Bug: The chosen application is not saved for the selected file type (see Figure 4).

### Appendix

Figure 1:
![Image](https://github.com/user-attachments/assets/e8d1fbe4-1c85-4db1-b5c6-30f3de02efc5)

Figure 2:
![Image](https://github.com/user-attachments/assets/843d747a-17ec-49a1-97f8-cf565a070474)

Figure 3:
![Image](https://github.com/user-attachments/assets/20eaa84f-5c7f-48ff-8450-3c5210311d11)

Figure 4:
![Image](https://github.com/user-attachments/assets/290f1479-8ad1-45da-b6e0-d0f861545371)

**Comment by Siedlerchr** [comment]
Thanks for reporting this issue, it's now fixed in the latest dev version https://builds.jabref.org/main/
