### ISSUE TITLE
Groups sidebar element does not scale automatically with window height

### ISSUE THREAD

**Issue by tillschaefer** [JabRef/jabref#1233]
JabRef version 3.2 on Gentoo Linux

The sidebar element "Groups" has a fixed height. This is problematic for larger displays as it wastes a lot of space and one looses the overview over the categories (see screenshot). It should scale with the remaining vertical space available in the sidebar. 

As this dynamic scaling is sometimes a bit problematic using multiple sidebar elements (form a programmer perspective) it would also be helpful (as an alternative solution), if the sidebar height could be configured.

![groups](https://cloud.githubusercontent.com/assets/3009428/14637866/716f2a50-0634-11e6-8d1f-3d56bb008f84.png)

**Comment by matthiasgeiger** [comment]
Thanks for your report.

It is already possible to increase/decrease the size of the Group list manually by using the buttons beneath the list of groups next to "settings".

**Comment by tillschaefer** [comment]
wow, thank you for the fast answer.

The settings are still somewhat suboptimal, because the buttons move with each resize operation.

**Comment by tillschaefer** [comment]
I will leave this ticket open as a feature request for automatic scaling

**Comment by matthiasgeiger** [comment]
Yes, we are also not happy with the current solution and the used icons :wink:

However, as you pointed out automatic scaling might be troublesome if more than one sidebar is used - but as the search sidebar was moved to the top of each tab this should not be a big issue.

**Comment by tobiasdiez** [comment]
It is implemented in the latest development version, which should be available in a few minutes under http://builds.jabref.org/master/. Thanks for suggesting this improvement.

**Comment by tillschaefer** [comment]
wow again for the speed :-) thank you, too.

**Comment by simonharrer** [comment]
JabRef is powered by donations ;-)

**Comment by tillschaefer** [comment]
done :-)
