### ISSUE TITLE
Modified Key bindings do not work correctly

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#1235]
JabRef version 3.2, 3.3 on Windows 10 with German Keyboard

Steps to reproduce:
  1. Default Key-Binding for "Delete Entry" is `DELETE`
  2. Change key-binding for "Delete Entry" using the "grab" functionality and hit `Entf` key on a german keyboard. Save changes and restart jabref.
  3. Select and entry in the main table and hit "Entf" key
  4. nothing happens...

**Comment by simonharrer** [comment]
@matthiasgeiger will you have a look here? Otherwise, move it to the milestrone 3.5

**Comment by matthiasgeiger** [comment]
I don't think I'll have to time to investigate this week... so: moved to 3.5

**Comment by stefan-kolb** [comment]
@koppor Did StuPro look at this when they reimplemented the hotkeys?

**Comment by koppor** [comment]
@mairdl and @Braunch did not look at it during #1525 and do not know the reason why this causes issues. There, however, seems to be https://github.com/mairdl/jabref/pull/2, but I think, this code is lost somewhere in the git universe. @Braunch Can you have a look?

**Comment by Braunch** [comment]
Fixed by #1815
