### ISSUE TITLE
Differences in merge entries dialog: slow scrolling

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1242]
JabRef-3.4dev--snapshot--2016-04-19--master--990b0e5.jar on Linux Mint LMDE.

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
Steps to reproduce:

In the window "Merge entry with DOI information" (#1022), mouse scrolling is very very slow for the top part of the window (while it works as expected on the lower part --- both right and left sides).

**Comment by stefan-kolb** [comment]
@JabRef/developers Can you reproduce this? @performance team @simonharrer @tobiasdiez WDYT?

**Comment by matthiasgeiger** [comment]
Yes, I also noticed this behavior. I'm not sure whether this is actually a performance issue or whether this is caused by some strange Swing configuration for this scrollpane.

**Comment by koppor** [comment]
@oscargus You had a look at the dialog recently. Can you have a look whether there is a strange implementation? Maybe we can discuss in our next devcall.
