### ISSUE TITLE
Jstyle files - improper handling of quotation marks

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#1245]
JabRef version 3.3 on Windows 10

Steps to reproduce:

1. .Use the Citation file below/ rename to .jstyle
[test.txt](https://github.com/JabRef/jabref/files/226348/test.txt)

2. Have a look at:
BracketBefore=""
BracketAfter=""

They are defined with quoutation marks according to the example at: http://jabref.sourceforge.net/OOPlugin-jabref.php 

2. create an empty LO document and cite some entries
3. The following happens: ""DOE 1998""...

Expected was an entry without "brackets" before and after: DOE 1998
I know, the expected behavior can be triggered by the following code:
BracketBefore=
BracketAfter=

but for other cases quotation marks are needed, leaving me with inconsistent property definitions

**Comment by oscargus** [comment]
You should be able to try out a fixed version at https://builds.jabref.org/fix1245 in ten minutes or so. I haven't tried it myself (no OO on the computer I'm sitting at), but the fix was quite straightforward so it should be OK...

**Comment by teertinker** [comment]
Great! It works.
