### ISSUE TITLE
Jstyle file suggestion to improve error handling of formatting properties

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#1247]
JabRef version 3.3 on <Windows 10>

Steps to reproduce:
1. Use the following jstyle file
   [test.txt](https://github.com/JabRef/jabref/files/226384/test.txt)
2. connect it to a writer document
3. cite some random entries
4. compile list of reference
5. An error is raised stating that the format "test" is not specified within "ReferenceParagraphFormat" or "ReferenceHeaderParagraphFormat"
   -> no list of reference appears

Expected behavior:
-> raise a similar error message but use the default values specified for "ReferenceParagraphFormat" and "ReferenceHeaderParagraphFormat" in http://jabref.sourceforge.net/OOPlugin-jabref.php as a fallback mode, in order to get the list of references compiled.
# Explanation:

I have several style files and often i switch between them. Furthermore I work with different documents, often I have to compile a small list of references. Compiling a list of reference for a new document often raises the error message above, because I forgot to import the reference format in LibreOffice. Even though JabRef is pretty clear what is wrong, it would be much more convenient from a user perspective, if the list of reference is compiled anyways, so they don't have to adapt the jstyle-file for each and every occasion.

**Comment by oscargus** [comment]
Makes sense. How do you think it should work on practice? Still show the dialog, but add: Using default format? Show it every time the references are updated?

**Comment by oscargus** [comment]
I had a look at the code and since it is based on throwing exceptions the fix is not straightforward (or at least not quick). What about two buttons in the warnings saying "Use default format next time" (which sets the format to the default in the program instance, so you will have to reload the style file to get the original one back) and "Use style file format" (which is maybe a bad name)?

**Comment by teertinker** [comment]
Your two button solution would be definitely an improvement. From my perspective, a rephrased dialog with "using default format" that pops up at refreshing the database (everytime) would be the most convenient solution. Thereby, I don't have another option, I have to think about and choose. Its just a warning, that something is not correct, but the program keeps working. Furthermore the "Use default format next time" would probably require additional explanation (you have to reload the jsyle file to get the "Paragraph Format" defined in jstyle again ) which makes the warning as such more bloated.
