### ISSUE TITLE
Date formatter

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#1249]
Using more and more biblatex format, I would like to have the possibility to have a date formatter. 
Could be similar to already existing one : \format[CurrentDate]{yyyy.MM.dd}

**Comment by tobiasdiez** [comment]
So if I understand you correctly, you want a formatter which formats the date field to a specific form (say yyyy/mm/dd)?

**Comment by melTr** [comment]
Yes exactly! 
For now date field is output as yyyy-MM-dd but I would like the possibility to use at MM/yyyy for my document's needs. Thanks.

**Comment by Siedlerchr** [comment]
@melTr Biblatex explicitly needs the Date format in ISO, from the BibLaTeX reference manual: 
http://tug.ctan.org/macros/latex/exptl/biblatex/doc/biblatex.pdf
2.3.8 Date Specifications 
> The date fields date,origdate,eventdate, and urldate require a date
specification in yyyy-mm-dd format. Date ranges are given as yyyy-mm-dd/yyyy-mm-dd.[...]

The formatted display of the date in the citation/bibliography is depending on the biblatex style and language you use and of couse if you provide the arguments:
See 3.1.1 Load-time Options for an example

**Comment by oscargus** [comment]
@Siedlerchr : @melTr is talking about a LayoutFormatter to export the .bib-file to some other suitable format (or to use with OpenOffice/LibreOffice).

**Comment by Siedlerchr** [comment]
Ah now I get it :) It was a bit confusing for me.
