### ISSUE TITLE
Reuse bibers data file for Latex to Unicode conversion

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1252]
Biber has a nice list mapping latex commands to their unicode equivalent: https://github.com/plk/biber/blob/dev/lib/Biber/LaTeX/recode_data.xml. 
After a quick look, this list seems to be more extensive than our map. Moreover, I like the xml format.

Thus I propose to switch to XML and reuse Biber's file (maybe with some additions which we can hand back to the biber team). The XML format has also the advantage that a help file listing all the conversations can be easily created .

@oscargus you worked a lot on this stuff. Are you willing to work on this issue too?

**Comment by oscargus** [comment]
There's also the HTML and the capitalization thing. And the need for  ✎. So for me: no.

**Comment by oscargus** [comment]
And Unicode to LaTeX (which basically includes the capitalization thing).

**Comment by koppor** [comment]
This is

**Comment by Siedlerchr** [comment]
The code how biber does the Transformation is there too https://github.com/plk/biber/blob/dev/lib/Biber/LaTeX/Recode.pm

**Comment by Siedlerchr** [comment]
The code how biber does the Transformation is there too https://github.com/plk/biber/blob/dev/lib/Biber/LaTeX/Recode.pm

**Comment by lenhard** [comment]
We decided to go for a conversion with latex2unicode instead, which is integrated into JabRef with #2532. So, there is no more need for reusing biber and this issue can be closed.
