### ISSUE TITLE
Databae type information gets duplicated

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1254]
I just updated a BibTeX file that was obviously edited with a dev version of 3.3 before and the databaseType gets duplicated:
```
+@Comment{jabref-meta: DATABASE_TYPE:BibTeX;}
 
+@Comment{jabref-meta: databaseType:bibtex;}
```

Should we care about this?

**Comment by matthiasgeiger** [comment]
I think we decided that we ignore this as it only affects the small number of users who used a dev version during a limited time period - but I can't find the corresponding issue...
