### ISSUE TITLE
Easier contribution help for translaters and help files

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1255]
What about such a description for non-Coders?
https://github.com/wsargent/docker-cheat-sheet#contributing

**Comment by matthiasgeiger** [comment]
Good idea!

**Comment by mlep** [comment]
Quite clear!

One thing missing is a link describing the markdown syntax.

**Comment by matthiasgeiger** [comment]
Follow up @https://github.com/JabRef/help.jabref.org/pull/16
