### ISSUE TITLE
Sciencedirect (Elsevier) Fetcher implementation

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1258]
At the moment the ScienceDirect Fetcher in Jabref is not used because it does not work.
The code needs to be reworked.
The question would be:  Do we rework the code or do we delete the fetcher?

If yes, they provide a Search API:
http://dev.elsevier.com/index.html

**Comment by mlep** [comment]
To me, ScienceDirect is a major provider of papers, so I would prefer the fetcher to be reworked.

**Comment by ChristopherHackett** [comment]
Debugging the code it seems a url is scraped from the site and then accessed. From this URL in the browser a redirect happens to the pdf but in the full text fetcher the redirect does not happen. Might require cookies or some user agent tweaking.

**Comment by ChristopherHackett** [comment]
It looks like pre-flighting the request with HEAD is the issue as the response comes back with text/html content type not application/pdf. Looking at the HTTP spec it say

"The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request."

Which means the behavior is different but not incompatible with the sepc given its only a SHOULD.

Interesting the URL the Elsevier API works as expected with HEAD.

**Comment by Siedlerchr** [comment]
@ChristopherHackett  Thanks for your effort. We are currently in "negotiations" with Elesevier regarding the usage of an API key. So, until we have the okay from them..we wait.
