### ISSUE TITLE
GoogleUrlCleaner

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#126]
Imho the benefits of `GoogleUrlCleaner.java` are not clear. 

There is an extra action on rightclick context menu for cleaning Google URLs. I don't see why many of us will benefit from this feature, at least not in this way. 

**If we keep this action it should automatically be used when pasting a link and clean the link instantly.**

The detection is flawed though, as we should only use this on URLs from Google domains.

**Comment by koppor** [comment]
A reason for the tool is made there: https://sourceforge.net/p/jabref/patches/204/

I think, the original author wanted to have this functionality at the paste action.

**Comment by stefan-kolb** [comment]
The auto correction functionality is now working for the context menu paste action. 
We still need to bind this functionality to the key action ctrl-v (`KeyEvent.VK_P`) for all textFields!

**Comment by stefan-kolb** [comment]
Maybe we also need to properly configure an Undo action for this. But this look sinconsistent and broken on various ends.

**Comment by stefan-kolb** [comment]
Should be working now for both `CTRL-V` and context menu :bowtie: Also thanks to @matthiasgeiger :+1:

**Comment by stefan-kolb** [comment]
There is still a paste icon in the toolbar that calls a different action! We need to rethink how many entry points for the same action we need...

**Comment by koppor** [comment]
I don't know, how the users use it. Should we have a voting or just remove it? The UI gets redesigned nevertheless (#113).

**Comment by stefan-kolb** [comment]
The real problem is to keep all the different actions consistent. We should also make a document where all functions of JabRef are documented including entry points for these actions. This is vital for anyone (students etc.) redesigning the GUI (and also for a good feature documentation).

**Comment by koppor** [comment]
Should we convert the help files first to markdown :smile:? (#133)

**Comment by matthiasgeiger** [comment]
> I vote for removing copy, cut,paste actions in the toolbar. This is either done by a shortcut or via the context menu - but not the toolbar?!

I don't think users will accept this. Pasting using icons in a toolbar is the standard way of pasting for lots of users (e.g., my parents :wink:). Although the standard JabRef user might be more technophile I suppose the removal of those buttons would be one of the first issues reported...
