### ISSUE TITLE
Delete temporary files after saving a database

### ISSUE THREAD

**Issue by adessec** [JabRef/jabref#1270]
JabRef version 3.3 on Linux 3.16.7-35-default (openSuSE 13.2)

Steps to reproduce:

1. Activate autosave.
2. Autosave files not wriiten into the same directory as the *.bib file but to /tmp.
3. Even after saving, autosave files persist.

**Comment by adessec** [comment]
I don't think this behaviour is an enhancement but rather a bug. A version of a database that has been edited is written to /tmp every five minutes by default as long as you don't save it to the working directory. Quite annoying if it's large.

**Comment by Siedlerchr** [comment]
@adessec When it's always the same temp file that is updated than it is totally okay and totally consistent behavior. 
However, it would be nice to configure the autosave to the working directoy.

**Comment by adessec** [comment]
Unfortunately it is not always the same temp file - they just multiply. At the moment, I have one small +-JF*.tmp, one small jabref*.tmp, one large jabref*.tmp, and nine large jabref*save.bib. Nothing has been updated.

**Comment by tobiasdiez** [comment]
According to the [help](http://help.jabref.org/en/Autosave/)
> The autosave file will be deleted whenever you actively save the database, and if you quit JabRef normally.
So if this does not work, then it is indeed a bug. Moreover, according to the same help page, the auto save file should actually be named `$file$` (so extra dollar signs) and be put in the same folder (and I get same expression reading the code).

Moreover, I can't find anything in the code which would suggest that a file is written to a `/tmp` folder...

**Comment by tobiasdiez** [comment]
Ok, I think I found the problem. Should be fixed with #1277.

**Comment by adessec** [comment]
Thank you for fixing this.

**Comment by simonharrer** [comment]
Thank you for reporting the bug and helping JabRef. 

PS: Donations keep us going. ;-) http://www.jabref.org/#donations
