### ISSUE TITLE
bibtex key entry rejects ( and )

### ISSUE THREAD

**Issue by wbmacleod** [JabRef/jabref#1272]
JabRef version 3.3 Linux
Hint: If you use a [development version](http://builds.jabref.org/master/), ensure that you use the latest one.

Steps to reproduce:

1. Try to enter a bibtex key with parenthesis in it - eg: Kaur(2014)
2. Invalid bibtex key is returned

Also this implies that the automatic bibtex key generator with parenthesis no longer works (I have 4000 keys with parenthesis...)

Work around - enter key manually in bibtex tex window.

I checked and ( and ) ARE valid in a bibtex key.

This bug was introduced between 3.2 and 3.3.

**Comment by wbmacleod** [comment]
With some checking it seems that biber does not allow for parentheses. See:

http://tex.stackexchange.com/questions/96454/using-bibtex-keys-containing-parentheses-with-biber

A solution would be to allow parentheses in bibtex mode, and then in bibalatex mode add an IDS field that would move offending keys to IDS field and remove offending characters.  Many of us have thousands of references with parenthesis in the keys, so changing our bibtex files would be lots of of work....

**Comment by oscargus** [comment]
Introdced in d505452d04b421818dd966a85121468138de8ff3 

@lenhard : comments?

**Comment by lenhard** [comment]
The reason for this was #631 

Hard to say what the right path of action is here. If brackets are allowed in bibtex keys, we should support such keys in JabRef. I guess we could use different key checking functionality depending on the mode, but I am strongly against workarounds such as the one described by @wbmacleod If one uses brackets in keys and switches to biblatex, it should be sufficient to display an error. But I have no strong opinion here. @koppor?

The most simple solution would be to just revert the commit.

As a side note: Removing brackets in thousands of bibtex keys is not too hard with some automation.

**Comment by wbmacleod** [comment]
I would agree that the workaround is not a good idea - a better solution might be to use the flag of bibtex vs bibalatex/biber in jabref to also affect the syntax checking - in bibtex mode any bibtex allowed citation could  be permitted.

With regards to changing the cite key, this is very non-trivial - I have dozens of co-authors and RAs that use a common bibtex file, so this requires changing dozens of bibtex files and keys in latex papers - it would cause several years of problems as the changes propagate through the teams all over the place.

Also, I have been trying to get Columbia students to use jabref, and I think killing backwards compatibility in this way is not helpful to getting jabref more widely used.  A better way would be to allows full compatibility with bibtex (which is a very stable system...).

**Comment by tobiasdiez** [comment]
What about:
- Allow everything in the key (as long as JabRef itself can handle it)
- But only generate keys without braces
- Move the check to the Integrity Check functionality (and make it mode dependent)

**Comment by wbmacleod** [comment]
Well I am still using parentheses and have moved to old version of jabref
which I guess I will have to stick to.

At the moment bibalatex is too buggy and I have several book projects so I
am stuck in my ways... The keys with parentheses are easier to read for me
so will use jabref 3.2 for now. It is a great program. Bm

W Bentley MacLeod

**Comment by wbmacleod** [comment]
For what it is worth, I attach three python programs to remove braces from cites in bibtex file, directory tree where linked files live and in lyx.
[RemoveBraces.zip](https://github.com/JabRef/jabref/files/248674/RemoveBraces.zip)
