### ISSUE TITLE
Jabfox does not finish

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#1275]
JabRef version 3.3 on Windows 7

I have the signed version of Jabfox running on an actual firefox 45.0.2. When in a Pubmed result window I can use the jabfox button to import the bibliographic data into JabRef. This works nicely. However the jabfox does not open the import window of JabRef, nor does it finish that one could work on with firefox. 

Steps to reproduce:

1. Do a search in firefox on Pubmed, select some entries and show them on a separate window 
2. press the jabfox button, a small window will open saying "importing into jabref"
3. When the import is finished you can use alt-tab to have the import dialog, firefox has to be close it will no longer react to any typing or mouse action.

If applicable, excerpt of the bibliography file, screenshot, and excerpt of log (available in the error console)
![screenshot_jabfox](https://cloud.githubusercontent.com/assets/9216487/14738216/ad147e22-0880-11e6-87e2-75761e560f8a.png)

**Comment by tobiasdiez** [comment]
Ok, I can confirm the problem, for example on http://www.ncbi.nlm.nih.gov/pubmed/?term=sexually+dimorphic. Will have a look at it.

**Comment by bernhard-kleine** [comment]
Am 22.04.2016 um 19:36 schrieb Tobias Diez:
>
> Ok, I can confirm the problem, for example on
> http://www.ncbi.nlm.nih.gov/pubmed/?term=sexually+dimorphic. Will have
> a look at it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JabRef/jabref/issues/1275#issuecomment-213522646>
>
Do you have found a solution and will it become available?
Regards Bernhard Kleine

--
spitzhalde9
79853 lenzkirch
bernhard.kleine@gmx.net
www.b-kleine.com, www.urseetal.net
-
thunderbird mit enigmail
GPG schlüssel: D5257409
fingerprint:
08 B7 F8 70 22 7A FC C1 15 49 CA A6 C7 6F A0 2E D5 25 74 09

**Comment by tobiasdiez** [comment]
I think I finally found the origin of this bug and just pushed a new version to the Mozilla rep. It should be reviewed in the next days and then become officially available. Until then you might want to try it out under https://addons.mozilla.org/en-US/firefox/addon/jabfox/versions/?page=1#version-1.0.2

Let me know if this fixes the bug for you.

**Comment by bernhard-kleine** [comment]
This is strange, I thought you have already found it two weeks ago,
since that time firefox no longer crashed, as far as I know.

Thanks for you efforts

Bernhard.


Am 25.06.2016 um 09:51 schrieb Tobias Diez:
>
> I think I finally found the origin of this bug and just pushed a new
> version to the Mozilla rep. It should be reviewed in the next days and
> then become officially available. Until then you might want to try it
> out under
> https://addons.mozilla.org/en-US/firefox/addon/jabfox/versions/?page=1#version-1.0.2
>
> Let me know if this fixes the bug for you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JabRef/jabref/issues/1275#issuecomment-228520962>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIyh55QrSGYe5mxr04b7OShwGLgXuDtFks5qPN4QgaJpZM4INdxj>.
>

-- 
--
spitzhalde9
79853 lenzkirch
bernhard.kleine@gmx.net
www.b-kleine.com, www.urseetal.net
-
thunderbird mit enigmail
GPG schlüssel: D5257409
fingerprint:
08 B7 F8 70 22 7A FC C1 15 49 CA A6 C7 6F A0 2E D5 25 74 09
