### ISSUE TITLE
Newly opened bib-file is not focused

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#1288]
JabRef version 3.3

Steps to reproduce:
Prerequisite: JabRef is registered as the default application for *.bib files
1. Close all JabRef instances
2. Open a bib file from the file system
3. JabRef is opened, the file used least recently is selected - and not the newly opened bib file

(Side note: If remot ops are activated and JabRef is already running, the newly opened file is focused correctly)

**Comment by stefan-kolb** [comment]
Should be a focus thing inside `JabRefGUI.java` near line 108.
