### ISSUE TITLE
Remove old Authors formatters

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1289]
According to http://jabref.sourceforge.net/help/CustomExports.php a lot of Author formatters (like [AuthorLF_FF](https://github.com/JabRef/jabref/blob/511a1c3ab2fd1b36b23774ab0774a8f0acf3f169/src/main/java/net/sf/jabref/logic/layout/format/AuthorLF_FF.java)) are depreciated and are replaced by [Authors](https://github.com/JabRef/jabref/blob/511a1c3ab2fd1b36b23774ab0774a8f0acf3f169/src/main/java/net/sf/jabref/logic/layout/format/Authors.java).

> Authors : this formatter provides formatting options for the author and editor fields; for detailed information, see below. It deprecates a range of dedicated formatters provided in versions of JabRef prior to 2.7.

Should we just remove these old formatters?

**Comment by oscargus** [comment]
I'd say that maybe we should output some deprecation warning for a few versions and then remove them. Or just remove them (and be prepared to come up with correct Authors-parameters to emulate the removed ones if someone complains).

**Comment by simonharrer** [comment]
From code complexity, it does not really matter as removing them will not simplify the structure. I don't have a strong opinion of this.
