### ISSUE TITLE
Encode more Best Practices as part of Integrity Checks

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1291]
Possible checklist to build upon see http://serialmentor.com/blog/2015/10/2/Bibtex/

I think we should gather best practices here and discuss whether we can derive an integrity check from them.

**Comment by tobiasdiez** [comment]
Good idea. Biber also contains some integrity checks (by running biber --tool).
For dates: https://github.com/plk/biber/blob/a13871c32321934dc4914c55a9357568fa1adfe7/t/dm-dateformats.t
Hidden as biber_warn statements: https://github.com/plk/biber/blob/ed9f87b599027130272b8d34d4f3e71039613177/lib/Biber/Input/file/bibtex.pm

**Comment by oscargus** [comment]
Some relevant points and I think we cover quite a few of them. However, the things listed under "Superfluous issue numbers, publication months, or other elements" I do not agree with. First, the behaviour is research filed dependent, so in my area it is simply not true. Second, that is the whole purpose of the .bst. If the journal actually doesn't use number it will not show it given that the correct .bst-file is used...

**Comment by oscargus** [comment]
I'd be more towards adding a checker that actually does check that volume, number and month is actually not empty, if anything.

And, of course, allow to enable and disable the checkers.

**Comment by melTr** [comment]
When I run integrity check on my database, it's full (more than hundred) "errors" about pages not in valid format. But they are ok, but it doesn't seems to be taken in account:
S52--S53 (in supplement)
e87160 (used in PlosOne and many electronic only journal)
CD000551 (Cochrane journal)
G305--G314 (some journals used that, never understand what it mean)

**Comment by Siedlerchr** [comment]
@melTr  Do you use Bibtex or Biblatex mode?

**Comment by melTr** [comment]
Biblatex

**Comment by simonharrer** [comment]
I think the constrains for the `pages` field was derived from the bibtex standard. Can you shed some light on it @stefan-kolb 

I am unsure what to do here, should we lessen the constrains or are other constraints regarding biblatex to be used for `pages`?

**Comment by stefan-kolb** [comment]
Pages constraints are from BibTeX

**Comment by simonharrer** [comment]
Are there any Biblatex specifications for the pages field?

**Comment by mlep** [comment]
In the doc of the biblatex package (http://mirrors.ircam.fr/pub/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf), the definition of the field "pages" reads (on page 21):
```
pages     field (range)
One or more page numbers or page ranges. If the work is published as part of another
one, such as an article in a journal or a collection, this field holds the relevant page
range in that other work. It may also be used to limit the reference to a specific part
of a work (a chapter in a book, for example).
```

So, it is of type "range" and a range is defined (on page 14):
```
Range fields
consist of one or more ranges where all dashes are normalized
and replaced by the command \bibrangedash . A range is something
optionally followed by one or more dashes optionally followed by some
non-dash (e.g. 5--7). Any number of consecutive dashes will only yield
a single range dash. A typical example of a range field is the pages
field. See also the \bibrangessep command which can be used to
customise the separator between multiple ranges. Range fields will be
skipped and will generate a warning if they do not consist of one or more
ranges. You can normalise messy range fields before they are parsed
using \DeclareSourcemap (see § 4.5.3).
```

**Comment by simonharrer** [comment]
But it is left open what is the right and left side of a range field, isn't it?

**Comment by tobiasdiez** [comment]
Yeah it is not really specified. According to https://github.com/plk/biber/blob/d4c27bab2acc2fa2d209cc982bdf6a619ff55f52/t/utils.t#L142 even unicode representations of roman page numbers are supported. Also multiple page ranges like `1--14, 20--30` are valid (I think, JabRef might complain here). 
The following code handles all the range fields in biber: https://github.com/plk/biber/blob/ed9f87b599027130272b8d34d4f3e71039613177/lib/Biber/Input/file/bibtex.pm#L809 and probably can be incorporated as a integrity check.

**Comment by stefan-kolb** [comment]
@simonharrer Link is dead. Maybe we can close this if we have no further ideas for additions right now?
