### ISSUE TITLE
Page number with DOI to BibTex for APS

### ISSUE THREAD

**Issue by supernano** [JabRef/jabref#1292]
JabRef version 3.3 on Windows 7 64-bit

When importing references from APS journals using DOI to BibTex, the pages field does not get imported.

Steps to reproduce:

1. Fetch a reference from an APS journal using DOI to BibTex (e.g. 10.1103/physrevlett.107.230501).
2. Click ok in the search results window to add the reference to your database.
3. Double-click on your newly added reference, to look at all the available fields.
4. The field pages, under the 'Optional fields' tab is empty. It should contain the APS journal page reference (in the case of my reference example 230501).

**Comment by stefan-kolb** [comment]
We directly retrieve the BibTeX entry via the DOI resolver page by setting the `Accept`header of the HTTP request to `application/x-bibtex`. The data just does not include the `pages` field, so there is not much I can do about that.

Data:
```tex
@article{_lvarez_2011,
	doi = {10.1103/physrevlett.107.230501},
	url = {http://dx.doi.org/10.1103/physrevlett.107.230501},
	year = 2011,
	month = {nov},
	publisher = {American Physical Society ({APS})},
	volume = {107},
	number = {23},
	author = {Gonzalo A. {\'{A}}lvarez and Dieter Suter},
	title = {Measuring the Spectrum of Colored Noise by Dynamical Decoupling},
	journal = {Phys. Rev. Lett.}
}
```
