### ISSUE TITLE
New Icon set

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#130]
Do you now any good icon sets that can be used for JabRef? It's an easy change to be more design consistent and it gives us a quick new look :smirk:

- http://icondock.com/
- http://famfamfam.com/lab/icons/silk/

**Comment by koppor** [comment]
See [JabRef's resources page](http://jabref.sourceforge.net/resources.php): [PrettyJabRef](https://github.com/theyate/PrettyJabRef). The [Clear Theme](https://github.com/theyate/PrettyJabRef/tree/master/Clear) looks good. That is a good starting point, isn't it?

**Comment by koppor** [comment]
List of free icon sets: https://commons.wikimedia.org/wiki/Comparison_of_icon_sets

**Comment by simonharrer** [comment]
https://useiconic.com/open/ is MIT license + vector graphics. 

glyphicons is only free with png graphics and CC license, and their payed offer cannot be used in open source project.

**Comment by simonharrer** [comment]
An interesting solution can be using an icon font according to http://stackoverflow.com/questions/9639894/add-icons-to-jbutton-using-custom-font-from-awesomefont-and-unicode-characters-i because this allows to color the icons the way we want it by simply stating the icon color.

**Comment by koppor** [comment]
[Font Awesome](http://www.fontawesome.io) is really a popular icon set. According to the [FAQ](https://fortawesome.github.io/Font-Awesome/community/#requesting-new-icons), one can request new icons. I did not make an evaluation regarding the coverage of Font Awesome.

**Comment by stefan-kolb** [comment]
I use it quite often, coverage should be realy high.

**Comment by matthiasgeiger** [comment]
Using a Font instead of pngs will lead to major changes in the Java code (see stackoverflow example above) - you are aware of this?

**Comment by stefan-kolb** [comment]
https://github.com/encharm/Font-Awesome-SVG-PNG
https://github.com/odyniec/font-awesome-to-png

**Comment by matthiasgeiger** [comment]
:+1:

**Comment by tobiasdiez** [comment]
If we use the PNG converter, then we would also loose the advantage that one can easily change the icon color, right? So then any other icon set is as good as the Font Awesome...

**Comment by stefan-kolb** [comment]
This would be just a woraround until we change the GUI code.

**Comment by simonharrer** [comment]
I did a prototype yesterday evening. It requires approx. 80 LoC to use font icons. I will push this in a branch tomorrow. 

We only have to modify the IconTheme class and can leave every other part of JabRef as it is.

**Comment by matthiasgeiger** [comment]
Great!

**Comment by simonharrer** [comment]
Have a look at https://github.com/JabRef/jabref/tree/icon-font-prototype and try it out.

**Comment by koppor** [comment]
I tried 869e5bbd840303. Are the black folders intended?

![first result](https://cloud.githubusercontent.com/assets/1366654/10216141/33892426-6827-11e5-921c-7a8d03dcd519.png)

**Comment by matthiasgeiger** [comment]
Yes. It's just a really quick hack showing "something" instead of anything sensible ;-)

**Comment by simonharrer** [comment]
All symbols are black. I randomly assigned these three symbols (plus + green, minus + red, folder) to all places where the icons are used. 

But somehow all the icons look pixelish, as @matthiasgeiger also pointed out. I tried the iconic font before and it did look much clearer.

**Comment by matthiasgeiger** [comment]
Just pushed some more test icons and activated anti aliasing...

**Comment by matthiasgeiger** [comment]
Looks much better now: 
![jabref_screenshot](https://cloud.githubusercontent.com/assets/676652/10216535/1bef829e-682a-11e5-97cb-1ea6cdc15683.png)

**Comment by stefan-kolb** [comment]
Hm, looks ok but i expected it to be really sharp...

**Comment by matthiasgeiger** [comment]
You can play around with the various options described [here](http://docs.oracle.com/javase/8/docs/api/java/awt/RenderingHints.html#KEY_TEXT_ANTIALIASING) - I'm no "swing text anti-aliasing" expert and had no time to read the API what is the difference between those options.

**Comment by stefan-kolb** [comment]
We can do a lot of styling stuff also: http://www.jensd.de/wordpress/?p=692

**Comment by simonharrer** [comment]
https://github.com/griffon-plugins/griffon-fontawesome-plugin has all the classes there already, including an enum to select all the icons from. 

But we are currently relying on ImageIcon which is a sub-class of Icon from Swing. This plugin, however, only provides an Icon implementation.

**Comment by stefan-kolb** [comment]
These look nice too https://www.google.com/design/icons/

**Comment by simonharrer** [comment]
The google icon set is even better as android apps have similar icons as
desktop apps. May be this works better for our use case with the font.

Am Donnerstag, 1. Oktober 2015 schrieb Stefan Kolb :

**Comment by matthiasgeiger** [comment]
![jabref_screenshot-materialicons](https://cloud.githubusercontent.com/assets/676652/10241251/b38d3896-68e6-11e5-8b83-7fc93bb168c6.png)

25, 20 and 16px

I would prefer FontAwesome - or a mix of both ;-)

**Comment by stefan-kolb** [comment]
Looks great :+1:

**Comment by simonharrer** [comment]
I think we should try to stick a a single icon set instead of using multiple ones at first. If it is not enough, we can still add another one.

**Comment by matthiasgeiger** [comment]
I started to look for potential replacements for the currently used icons.

Still WIP - can be seen here: https://github.com/JabRef/jabref/blob/new_iconset/src/main/resources/images/crystal_16/IconList.html

**Comment by matthiasgeiger** [comment]
https://materialdesignicons.com/ - some more icons which might be useful

**Comment by koppor** [comment]
And an awsome list: [Awesome list of icon fonts / packages](https://github.com/mrzmyr/awesome-icons). Feel free to contribute if something is missing there.

See also [The definitive list of lists (of lists) curated on GitHub](https://github.com/jnv/lists).

**Comment by stefan-kolb** [comment]
Archiving for reference, https://materialdesignicons.com/ seems to be the way to go for now.

**Comment by koppor** [comment]
Follow up at #260.
