### ISSUE TITLE
Auto link pdf

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#1305]
Big issue (at least for me), linking of pdf doesn't work. Either in JabRef 3.3 or JabRef-3.4dev--snapshot--2016-04-26--master--baef229.jar

1- Instead of linking local files (my bibkey and document folder are correctly set), its seems to try to download.
2- After a while, received a dialog saying "Fail to download cited document" (my translation, I don't use english interface).
3- Try with different types of documents, entrytypes or differents database.
4- Even entry having an url failed. (but I never used this functionnality, so maybe my University network is not allowing this).
5- Doesn't work in either bibtex or biblatex mode.

Thanks

**Comment by stefan-kolb** [comment]
Thank you for your report :+1: 

I just tried to reproduce this issue on `master`. It is working as expected for me. I need more information and maybe files to reproduce your issue. Did you try to reset your preferences?

**Comment by melTr** [comment]
ok. This is strange. I try on my home computer and it works as expected. I used "fresh" pref and also the same pref than my other computer. It was the same database. 
I will try again on my work computer tomorrow.

**Comment by melTr** [comment]
So. Still didn't working on WinXP computer, even with default preference.
As you can see in the video, the focus seems to "jump" to dowload instead. Others buttons didn't react like this.
https://www.dropbox.com/s/byldn34avufhhpz/2016-04-27%2018.39.25.mp4?dl=0

**Comment by stefan-kolb** [comment]
@JabRef/developers I cannot reproduce this issue. Can anybody of you? Maybe a problem with Windows XP?

**Comment by lenhard** [comment]
Do we have a misunderstanding here? @stefan-kolb correct me if I'm wrong, but as far as I recall the "Auto" button is supposed to do an automatic search on the Internet and try to download a pdf for the entry. It is not supposed to link local files. 

For me (Win10), the auto button works as expected.

As a side note: WinXP has reached end of life more than 2 years ago. I do not see any reason to maintain support for it.

**Comment by mlep** [comment]
I am able to reproduce it:
JabRef 3.3 , java 1.7 and winXP
But also JabRef 3.3, java 1.8 and Linux

Clicking several times in a row on "Auto" for a reference without URL or DOI, I got a window stating "Full text document download failed". Several such windows were displayed (one after the other).
Nothing in the console; no exceptions.
At some point, the window was not about download failure: it was the actual window trying to download the reference. In the console, I got stuffs like:
'''
21:36:19.296 [Spin-18] INFO  net.sf.jabref.logic.fulltext.GoogleScholar - Fulltext PDF found @ Google: https://hal-insu.archives-ouvertes.fr/docs/00/55/55/62/PDF/Darboux99.pdf
21:36:19.760 [Spin-19] INFO  net.sf.jabref.logic.fulltext.GoogleScholar - Fulltext PDF found @ Google: https://hal-insu.archives-ouvertes.fr/docs/00/55/55/62/PDF/Darboux99.pdf
'''

**Comment by mlep** [comment]
@lenhard Really? The first thing I see after clicking on Auto: the files in the repository are added to the field 'files'. This is the way I have been using it (and I did not expect the files to be found on the web).

**Comment by stefan-kolb** [comment]
@lenhard It first looks for a local file, then tries to download it.

**Comment by stefan-kolb** [comment]
@mlep So where is the problem? That's expected. As far as I get the problem here is that it does not find the local file and then tries to download. A failing download is no error. This could happen if no file is found.

**Comment by stefan-kolb** [comment]
He says:
> Instead of linking local files (my bibkey and document folder are correctly set), its seems to try to download.

That's what I cannot reproduce

**Comment by mlep** [comment]
@stefan-kolb  The issue I saw is that the file was existing, and already appearing in the field (it was added by JabRef a few clicks earlier).
The thing I do not understand now is: why did it go to look on the web?

**Comment by lenhard** [comment]
And again I learned something about JabRef :-) 

Anyway, like @stefan-kolb local linking works fine for me.

**Comment by stefan-kolb** [comment]
@mlep That's maybe a small glitch, i can reproduce that!

- [ ] link after download and unclosed Jabref
- [ ] move to file folder when already there.
- [ ] open folder

**Comment by melTr** [comment]
Thanks everyone!  i used since years "auto" to link local files and it never search over web. Maybe it something new added. I will try on my Win7 to see if it's the same. I also try the button on the side or shortcut (Alt+F) and it's the same behavior.
@lenhard I know XP is really old, but it's my work computer, I have to live with what my IT departement give me. I try on the computer besides me, Win7, but Java is still version 7 and can't run Jabref...

**Comment by stefan-kolb** [comment]
@melTr Can you try a recent version from http://builds.jabref.org/master/? Maybe this fixes your issue.

**Comment by melTr** [comment]
For me, it doesn't work. But I still have to try in Windows7 to compare. Will do it soon. Anyway, for now, my linux computer could autosolve this issue... ;-)

**Comment by mlep** [comment]
@stefan-kolb The issue I reported is now fixed in JabRef-3.4dev--snapshot--2016-04-29--master--694840a.jar  . Thank you!

**Comment by simonharrer** [comment]
@melTr could you please also confirm that it is working so we can close this issue? Thank you. :)

**Comment by melTr** [comment]
Ok. Just found what was my problem. I played so much with my prefs between my win and linux system that I can't remember what was the original. But if I choose a path specific to win (C:\...article...) it works fine. I was just confused by this new behavior. Maybe the dialog should be change to be explicit to this error : No document found (instead of download fail)?
