### ISSUE TITLE
Auto cleanups/ Sensible defaults

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#131]
This issue should be a collection of things that should be auto monitored and corrected.
Some of the features can possibly be extracted from the existing `CleanupAction.java`.

The decisions are open for discussion :smiley:

__AUTO__
- [x] page ranges in the form num--num
- [x] convert 1st, 2nd to real superscrips
- [ ] convert umlauts etc. to BibTex format
- [ ] bibtex month format #month#

__MANUAL__

**Comment by koppor** [comment]
Regarding option 3: I would NOT do that. The user should decide whether he wants UTF-8 encoded files (with all umlauts etc. encoded) or plain ASCII files. The former is possible without isses with [biblatex-biber](http://biblatex-biber.sourceforge.net/), while the latter is [required for bibtex users](http://wiki.lyx.org/BibTeX/Tips).

I would even go further and have the setting "convert BibTeX encoded characters to UTF-8 characters" as default (and offer it as option at the clean up dialog).

We're at the discussion of having a main bibtex file for collecting and editing and a bibtex file for using in papers, aren't we? (#113, UC1 and UC2 in [CloudRef](https://github.com/JabRef/cloudref/wiki))

**Comment by koppor** [comment]
Regarding option 4: biblatex recommends the usage of numbers as they are most portable. Therefore, I would object that, too. Or do a conversion based on the type of the file (see #167).

Minor comments: Maybe referencing an issue at a commit which will probably be rebased is not a good idea :innocent:

**Comment by stefan-kolb** [comment]
Haha true :dancers:

**Comment by simonharrer** [comment]
But do the numbers start from zero or from one? :hamburger:  :)

**Comment by stefan-kolb** [comment]
Should be adressed in separate PR and issues.
