### ISSUE TITLE
Update CONTRIBUTING localization information

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1312]
See https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md#when-adding-a-new-localizationlang-entry.
Should use the gradle task for now.

**Comment by Siedlerchr** [comment]
In my other PR  #1304   already changed the error/info text output of the consistency output to the new gradle task name.

**Comment by koppor** [comment]
@Siedlerchr Wrong PR referenced?

**Comment by Siedlerchr** [comment]
@koppor  Oh, yers, I meant #1265
