### ISSUE TITLE
Relative file links do not work anymore - Preferences are not saved

### ISSUE THREAD

**Issue by 2bein** [JabRef/jabref#1313]
JabRef version 3.3 on Windows 7 64 bit

Just updated from 3.2 to 3.3, but existing external file links (relative to bib-file) are not working anymore. Found out that in Preferences... File.. "Allow file links relative...." was not ticked anymore. But changing the tick box has no effect!? And when restarting Jabref, the tickbox is deactivated, so preferences are actually NOT SAVED!

Can anyone reproduce?

Additional comment:
Ok, there is obviously a conflict with the Database properties - a special path was given here as a general file directory to override the preferences. It was set as a relative path, but only absolute path is obviously possible here, nevertheless what the preferences tick box say.

However: Still without the path set in database properties, the tick box  "Allow file links relative...."  does not work anymore and is not saved with the preferences!

**Comment by matthiasgeiger** [comment]
Yes. This option seems not be saved correctly.

However, relative links are working for me (even without this option).

Please post an example BibTeX entry with further information where the bib-file and the referenced file is located.
Are there any messages in the different tabs of the Error Console (Help -> Show error console)?

**Comment by 2bein** [comment]
Sorry for the delay... 
Relative links are working, I agree. Errors console shows no erros. So I think we agree there is a bug with option saving and hope this will be solved in next version.
(Another bug is more serious for us - I will add a new ticket: Sorting of entries is always after YEAR, despite setting in database properties is "save entries in their original order")

**Comment by simonharrer** [comment]
Since 3.3: "Removed configuration option to use database file directory as base directory for attached files and make it default instead"

It was just not removed from the UI, but the logic underneath was optimized and simplified. I will remove the UI option so this will not confuse users further.

**Comment by simonharrer** [comment]
Okay, the facts:

- There are two check boxes at Options - Preferences - File: "Allow file links relative to the bib-files location" (A) and "Use the bib file location as the primary file directory" (B)
- The option A has been removed from the preferences in 8825dd7270faf4ec05dbaa09a5d5cb1f3296a33e, hence, it cannot be saved anymore, but the check box is still there
- Checkbox B is only activated by checking Checkbox A
- Checkbox B is saved in the pereferences and used in the code

At the moment, the code always allows relative links to the bib files location. Hence, the checkbox A can be removed from the UI, and checkbox B should always be enabled (usable).
