### ISSUE TITLE
No "Customize entry types" under Options

### ISSUE THREAD

**Issue by dewulf** [JabRef/jabref#1315]
JabRef version 3.3 on Windows 7, Java 1.8.0_66-b18 64-bit

There disappeared the menu entry for Options –> Customize entry types

**Comment by simonharrer** [comment]
Moved to "BibTeX" menu as it is about defining the types for bibtex.

**Comment by dewulf** [comment]
Thanks. Maybe you should update the manual for this

**Comment by koppor** [comment]
Could  you point us to the concrete manual you are referring to?
Alternatively, could you submit a PR to help.jabref.org? :innocent:

**Comment by dewulf** [comment]
I've made a PR))

**Comment by matthiasgeiger** [comment]
:+1:
