### ISSUE TITLE
My preferences got reset

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#132]
While trying the newest development build, JabRef reset my preferences. Did this happen to anyone else?

Two options:
 * ignore
 * add hint to README.md that this might happen and if yes, the users should comment here. Then we can fix it with the subsequent beta version.

**Comment by lenhard** [comment]
The only point where I did something with preferences that I can think of is this: 87d25f2dfa42411cd6087f57829aa854ba5954f3

Although it seems unlikely that a `getInstance` causes this behavior. But I'll keep an eye open.

**Comment by koppor** [comment]
...and again... Don't know, what I did. No one else experiencing this?

**Comment by koppor** [comment]
Is it possible that `gradlew test` resets the preferences and doesn't restore the original preferences?

**Comment by matthiasgeiger** [comment]
Yes. :wink:

`JabRefPreferencesTest` imports `src/test/resources/net/sf/jabref/customPreferences.xml` without backing up the user preferences.

**Comment by koppor** [comment]
We should add a save of the preferences at `@BeforeClass` and a restore at `@AfterClass`, shouldn't we? The saved preferences should be deleted after the test is finished. Currently no time for that :cry:

**Comment by lenhard** [comment]
Implemented in 5afc7e178b8cac4ae06633dd4b71d7d0e7185df2

I'm closing this for now. Feel free to reopen if your preferences are reset again.
