### ISSUE TITLE
Fetch arxiv preprint

### ISSUE THREAD

**Issue by JohannesBuchner** [JabRef/jabref#1322]
This is a easy bug.

BibTex contains sometimes indication for which arXiv ID is associated with it:

archivePrefix = "arXiv",
eprint = {1501.02805},

The fetcher should take these and follow them to arxiv.org (http://arxiv.org/abs/1501.02805) and download the pdf from there. LocalCopy did that, and offered to choose latest version or another version (I only was ever interested in the latest version). At the moment it just fails.

These bibtex keys are produced by ADS, which all astronomers/astrophysicists use. Here is an example bibtex:
http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2015ApJ...802...89B&data_type=BIBTEX&db_key=AST&nocookieset=1

JabRef version 3.2 on Gentoo Linux

**Comment by lenhard** [comment]
Refs #152 #430

@JohannesBuchner Since you consider this easy, could you please provide a pull request that implements an arxiv fetcher?

**Comment by JohannesBuchner** [comment]
I will have to decline :)

**Comment by simonharrer** [comment]
Could be made part of the auto downloader?

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be already present in version v3.3. See #1023.
