### ISSUE TITLE
"Look up full text document" shortcut; download all

### ISSUE THREAD

**Issue by vogler** [JabRef/jabref#1323]
"Quality > Look up full text document" is great, but what if I want to do this for all entries?
It has no shortcut and it is not in the list of key bindings.
Also, if I have multiple entries selected, it only processes the first one.

Version 3.3

**Comment by Siedlerchr** [comment]
I fully agree with you, that would be a great enhancement :+1:  .  Stumbled across this a couple of days ago, too.

**Comment by stefan-kolb** [comment]
Good enhancement indeed! Although we need a completely new workflow for it.
My suggestion:

Easy:
- progress bar downloading all stuff in the background, auto renaming and linking files, just a message dialog how many files could be linked.

Downsides: A lot of wrong downloads could be there.

Advanced:
- Big window like `merge dialog`
- On the left list of all entries (key, author, title)
- On the right possibility for a larger PDF preview to judge if the download is correct
- Download is triggered in the background
- Some options to correct/delete wrong files

**Comment by envhyf** [comment]
I have the same issue. Is there any alternative methods to achieve that?(I mean downloading full text for all the entries I selected)

**Comment by stefan-kolb** [comment]
Not right now, but we are working on it :+1:

**Comment by stefan-kolb** [comment]
@oscargus This was implemented by you a few weeks ago right? Inside the main menu `quality - lookup full text document`? If so, we should rename the description to `Retrieve full text documents for the whole library` or anything alike.

**Comment by stefan-kolb** [comment]
@vogler @envhyf You can find the functionality under `quality - lookup full text documents`. Just select multiple documents (but not to many 😄 )

**Comment by koppor** [comment]
Follow up at #2344 

There is no shortcut. Maybe <kbd>Ctrl</kbd> + <kbd>F7</kbd> as <kbd>F7</kbd> is "Automatically set file links" and <kbd>Shift</kbd> + <kbd>F7</kbd> is "Find unlinked files"?
