### ISSUE TITLE
PDF cleanup changes order of linked pdfs

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1327]
As reported in https://github.com/JabRef/JabFox/issues/23:

> I always get both the PDF and the snapshot link. After running the automatic cleanup, the PDF is placed second in the list of document links (I assume the cleanup first deletes the file link, moves the file, and then adds a new file link last in the list). This means that after running cleanup, pressing the PDF icon opens the snapshot HTML file, and not the PDF, requiring me either to manually reorder the two items, or delete the snapshot.

**Comment by simonharrer** [comment]
@tobiasdiez can you please verify that this solves the issue completely, especially in conjunction with JabFox?
