### ISSUE TITLE
Migrate help files (html) to a new format suitable for editing (markdown?)

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#133]
The current help files are created using HTML. They should be converted to a format more suitable for editing. Should we use markdown?

**Comment by mlep** [comment]
Fine with me.
And this is something I may contribute to, later on.

**Comment by matthiasgeiger** [comment]
As @koppor pointed out here https://github.com/JabRef/jabref/issues/111#issuecomment-145997322 [pandoc](http://www.pandoc.org) might be useful to convert HTML to markdown. 

We should check this out for our help files.

A very quick check [using the online tool looks promising](http://pandoc.org/try/?text=%3Chtml+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22%3E%0A%3Chead%3E%0A%3Clink+rel%3D%22stylesheet%22+type%3D%22text%2Fcss%22+href%3D%22jabref_help.css%22%2F%3E%0A%3C%2Fhead%3E%0A%0A%3Cbody%3E%0A%0A++++%3Ch1%3EPDF%2FPS%2FURL%2FDOI+links+in+JabRef%3C%2Fh1%3E%0A%0A++++%3Cp%3E%3Cb%3ENote%3A%3C%2Fb%3E+JabRef+2.3%0A++++and+later+versions+offer+an+%3Ca+href%3D%22FileLinks.html%22%3Eimproved%0A++++system+for+external+file+links%3C%2Fa%3E.%3C%2Fp%3E%0A%0A++++%3Cp%3EJabRef+lets+you+link+up+your+entries+with+PDF+or+PS+files%0A++++stored+on+your+system%2C+as+well+as+links+to+the+document+on+the%0A++++web+in+the+form+of+an+URL+or+a+DOI+identifier.%3C%2Fp%3E%0A%0A++++%3Ch2%3ESetting+up+external+viewers%3C%2Fh2%3E%0A%0A++++%3Cp%3EThe+program+has+to+know%0A++++which+external+viewers+to+use+for+PDF%2C+PS+and+web+pages.+These%0A++++are+by+default+set+to+values+that+probably+make+sense+for+your%0A++++operating+system%2C+so+there%27s+a+fair+chance+you+don%27t+have+to%0A++++change+these+values.%3C%2Fp%3E%0A%0A++++%3Cp%3ETo+change+the+external+viewer+settings%2C+go+to+%3Cb%3EOptions%0A++++-%26gt%3B+Preferences+-%26gt%3B+External+programs%3C%2Fb%3E.%3C%2Fp%3E%0A%0A++++%3Ch2%3EOpening+external+files+or+links%3C%2Fh2%3E%0A%0A++++%3Cp%3EThere+are+several+ways%0A++++to+open+an+external+file+or+web+page.+In+the+entry+editor%2C+you%0A++++can+double+click+on+the+text+field+containing+the+file+name%2C%0A++++DOI+or+URL.+In+the+entry+table+you+can+select+an+entry+and+use%0A++++the+menu+choice%2C+keyboard+shortcut+or+the+right-click+menu+to%0A++++open+the+file+or+web+page.+Finally%2C+you+can+click+on+a+PDF%2C+PS%2C%0A++++URL+or+DOI+icon.%3C%2Fp%3E%0A%0A++++%3Cp%3EBy+default+the+entry+table+will+contain+two+columns+with%0A++++icons+for+those+entries+that+link+to+external+files+and+URLs.%0A++++You+can+disable+any+of+these+in+%3Cb%3EPreferences+-%26gt%3B+Table%3C%2Fb%3E.%0A++++The+second+column+of+the+entry+table+shows+icons+for+PDF+or+PS%0A++++files+%28only+PDF+if+both+are+present%29%2C+and+the+third+column%0A++++shows+icons+for+URL+or+DOI+%28only+URL+if+both+are+present%29.+You%0A++++open+the+file+or+web+page+by+clicking+on+an+icon.%3C%2Fp%3E%0A%0A++++%3Cp%3E%3Cb%3ENote%3A%3C%2Fb%3E+If+the+PS+field+does+not+appear+in+the+entry%0A++++editor+%28in+the+%27General%27+panel%29%2C+you+may+have+to%0A++++%3Ca+href%3D%22GeneralFields.html%22%3Ecustomize+the+entry+types+of+the%0A++++general+fields%3C%2Fa%3E.%3C%2Fp%3E%0A%0A++++%3Ch2%3EThe+main+PDF+and+PS+directories%3C%2Fh2%3E%0A%0A++++%3Cp%3EJabRef+makes+it+easy+to%0A++++link+PDF+and+PS+files+to+your+entries.+To+take+advantage+of%0A++++this%2C+you+have+to+indicate+in+%3Cb%3EOptions+-%26gt%3B+Preferences%0A++++-%26gt%3B+External+programs%3C%2Fb%3E+your+main+PDF+and+PS+directories.%0A++++All+PDF+and+PS+files+that+are+stored+in+or+below+each+of+these%0A++++directories+will+be+referred+to+with+a+relative+path+by+JabRef%2C%0A++++making+it+easy+for+you+if+you+need+to+move+the+PDF+and+PS%0A++++directories%2C+or+if+several+users+use+the+same+database+from%0A++++different+network+places.%3C%2Fp%3E%0A%0A++++%3Cp%3EAdditionally%2C+if+you+give+your+PDF+and+PS+files+names+that%0A++++correspond+to+the+relevant+entry%27s+bibtex+key+%28plus+%27.pdf%27+or%0A++++%27.ps%27%29%2C+JabRef+will+be+able+to+search+your+main+directories+and%0A++++its+subfolders+for+the+correct+PDF+and+PS.+Once+the%0A++++correctly-named+PDF+or+PS+is+in+place+you+access+this+function%0A++++by+clicking+the+%27Auto%27+button+next+to+the+PDF+and+PS+fields+in%0A++++the+entry&from=html&to=markdown)

**Comment by stefan-kolb** [comment]
Help files now available at https://github.com/JabRef/help.jabref.org
