### ISSUE TITLE
Jabref performance issues (database: >6000 entries; >900 groups)

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#1332]
JabRef version 3.3 on Windows 10

A relatively large database (>6000 entries) with several explicit groups (>900 groups) leads to major performance issues in Jabref. Adding another group and/or changing an existing group name and/or adding a new entry to a group takes several seconds (~35 s).

System:
- Core i7-4702MQ (4+4HT cores; 2.2 GHz)
- 16 GB RAM
- Samsung SSD 850 EVO (1 TB)
- Java 1.8.0_91

This problem might be related to:
https://sourceforge.net/p/jabref/bugs/1110/
https://github.com/JabRef/jabref/issues/763
https://github.com/JabRef/jabref/issues/1094

Steps to reproduce:
1. Create a large database (>6000 entries) with many explicit groups (>900 groups)
2. Add another group/entry (or change group name)
3. Wait approx. 35 s for the task to complete

P.S.: If possible, I would prefer not to upload my bibtex file (as the structure of the database itself represents a lof of my work). If necessary, however, I can send it to people who are willing to help.

**Comment by stefan-kolb** [comment]
Thank you for your report :smile: !
That might be one for you @simonharrer @tobiasdiez :wink:

**Comment by AEgit** [comment]
Maybe I should add, that I had this problem also with previous Jabref versions (even with Jabref 2.10), so it's not something, that has just recently been introduced in the code.

**Comment by koppor** [comment]
Quick idea: is counting of contained entries on or off?

**Comment by AEgit** [comment]
If you are referring to counting contained entries in groups:
It was on - I've deactivated it now, but there was no performance improvement.

**Comment by simonharrer** [comment]
@AEgit what kind of groups do you use? Search, keyword or contains-based groups? How deep is your group tree? Also, what operations are slow? What would be an acceptable time for you for these operations?

**Comment by AEgit** [comment]
I'm only using static groups. The max. depth of my group tree is 17.
The following operations are slow:
1) Adding another static group
2) Assigning database entry to a new group
3) Changing a group name

Considering the specifications of my system (the complete database is loaded from a SSD!), these operations should be executed "immediately" or with a max. delay of 1 (maybe 2) sec. Definitely not 35 sec - just think about it: For every entry that I want to (re-)assign to a group I have to wait more than half a minute. For ten entries, this means I already have to wait more than 5 min. As I'm dealing with many more entries, this obviously is quite inconvenient.

BTW: If it helps, I can send you the database. It's just that I would prefer not to make it directly publicly available.

**Comment by AEgit** [comment]
Just to add: I have the same problem with Jabref under Ubuntu - so it's also not related to the operating system.

Thanks for all the comments so far!

**Comment by simonharrer** [comment]
Hm, static groups should be quite simple, as they do not issue any search queries. I will have a look.

**Comment by AEgit** [comment]
Thank you very much! @simonharrer : I've sent you the .bibtex file, that is causing the mentioned problems.

**Comment by simonharrer** [comment]
Cannot reproduce in current master with your example file - everything is really fast here. Can you please try http://builds.jabref.org/master/

**Comment by AEgit** [comment]
@simonharrer 
Great! Indeed, with the current master everything runs smooth - the only issue I have is that number of contained entries is no longer displayed (but I guess this is due to the fact how groups are treated in Jabref 3.4).

Amazing and thanks a lot! When can we expect to see the new release of Jabref 3.4? This solves my problem so I would be glad to use the final version as quickly as possible.

**Comment by simonharrer** [comment]
You can still display the number of contained entries per group using an option in the groups dialog, as far as I know. 

The release is not yet determined, but feel free to use the current development build.

**Comment by AEgit** [comment]
Hmmm, yes you can do that, but it will show "0" as the number of entries, i.e. it is no longer able to count the number of entries. Might be somehting to consider before the final release (?).

Anyway, thank you very much for the quick help!

**Comment by simonharrer** [comment]
Then this is a bug. Can you please report this separately? Thank you. :)

**Comment by AEgit** [comment]
Ok, I will ;)

**Comment by ivan866** [comment]
I have the same issue, and I know that it was cured by turning off the group count in version 3.9 or smth.
Also, I already had a big database and it never was a problem for a version that was current in 2014.
Then, hell followed.
@koppor, how can I turn off the counting of entries in groups in version `4.1`?
