### ISSUE TITLE
Option to search in title only

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#1333]
It would be useful, especially in large databases, to limit the search to "title only", rather than the whole of BibTex source. A checkbox beside "regex" and "case sensitive" buttons (in version 3.3) would be handy.

**Comment by simonharrer** [comment]
You can type `title="asdf asdfa asdfa"` for a title only search - it does a contains check. Is this sufficient enough?

**Comment by anassal** [comment]
Oh, yes! I just forgot about this feature. For me it's more than fine. Thanks!
