### ISSUE TITLE
Bug in Jabref 3.4dev: "Number of elements contained in each group" always shown as "0"

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#1334]
JabRef version 3.4dev--snapshot--2016-05-01--master--212201a on Windows 10

Bug in current master branch of Jabref (this bug is not found in Jabref 3.3):

Steps to reproduce:

1. Create a new .bibtex file with a few entries and groups
2. Turn on: "Show number of elements contained in each group"
3. Every group in your database is shown to have 0 entries

**Comment by simonharrer** [comment]
This is only related to the static groups. The dynamic ones work fine.

**Comment by AEgit** [comment]
Ah, yes - I've just tested it for static groups.

**Comment by AEgit** [comment]
The following issue might be related to this:

"Highlight groups matching any selection" does not work. You can turn it on in the "Groups" menu, but the groups containing a certain entry are NOT highlighted. Again, this has only been tested for static groups.

**Comment by AEgit** [comment]
This problem might be related to this one (?):
https://github.com/JabRef/jabref/issues/1320
