### ISSUE TITLE
corrupt BibTeXML export

### ISSUE THREAD

**Issue by thomaszumbrunn** [JabRef/jabref#1337]
JabRef version 3.3
(the issue is still present in 3.4dev--snapshot--2016-05-01--master--71eca69)

Steps to reproduce:

1. Export a BibTeX file with "File > Export" to BibTeXML format.

An author field entry of the form

    Burri, Emanuel and Beglinger, Christoph and von Felten, Stefanie and Lehmann, Frank Serge

is exported to

    <bibtex:author>Burri&#44 and Emanuel and Beglinger&#44 and Christoph and von Felten&#44 and Stefanie and Lehmann&#44 and Frank Serge</bibtex:author>

instead of (as in version 3.2)

    <bibtex:author>Burri&#44; Emanuel and Beglinger&#44; Christoph and von Felten&#44; Stefanie and Lehmann&#44; Frank Serge</bibtex:author>

**Comment by koppor** [comment]
Nice to see that someone is using BibTeXML. We are discussing its future at #938. What is your usecase of BibTeXML?

I feel that the author field of BibTeXML is underspecified. Maybe the ideas of docbook (http://www.docbook.org/tdg/en/html/author.html) or biblatex, which [(as default) distinguishes between](http://mirror.unl.edu/ctan/macros/latex/exptl/biblatex/RELEASE) `prefix,family,suffix,given`. - If xml elements such as `given-name` were used, one could improve XSLT scripts to provide different output formats.

**Comment by thomaszumbrunn** [comment]
To me, the use of BibTeXML is not imperative. In the usecase at hand, I export a JabRef library to BibTeXML and process it with XSLT to generate XHTML. I'm happy with any other XML dialect.

**Comment by tobiasdiez** [comment]
@koppor Something for the @JabRef/stupro ?

**Comment by stefan-kolb** [comment]
Isn't this an author parser problem?

**Comment by tschechlovdev** [comment]
I will rewrite the exporter with jaxb, since the importer is already written with jaxb. This should also fix the bug.

**Comment by koppor** [comment]
@thomaszumbrunn Please use a development build from http://builds.jabref.org/master
The fix will be included in the next release.

**Comment by thomaszumbrunn** [comment]
Thanks a lot. Works like a charm.
