### ISSUE TITLE
Feature request: Clickable crossref field.

### ISSUE THREAD

**Issue by domhardt** [JabRef/jabref#1338]
Click on BibTeX-Key in crossref field should lead to parent. Parent should indicate existing children (BibTeX-Keys, also clickable).

**Comment by oscargus** [comment]
There is now a PR in #1563 which adds a button in the entry editor for the crossref field and that the crossref column is clickable. Regarding linking between entries in general this is discussed in https://github.com/koppor/jabref/issues/14 .
