### ISSUE TITLE
The function of synchronize pdf doesn't work

### ISSUE THREAD

**Issue by raycth** [JabRef/jabref#134]
Please have a check, it happens in both v2.10 and v2.11b.

**Comment by koppor** [comment]
What does "doesn't work" exactly mean? Could you try with the latest development version? Execute `gradlew run` on your checkout.

You are not talking about https://sourceforge.net/p/jabref/bugs/1193/, are you? Do you refer to https://sourceforge.net/p/jabref/bugs/1115/?

**Comment by raycth** [comment]
I am in the same situation as  https://sourceforge.net/p/jabref/bugs/1193/. Could that latest development version V2.80 be work now？

**Comment by stefan-kolb** [comment]
Should be realted to #103

**Comment by lenhard** [comment]
#103 is fixed. I just tried to reproduce this bug in the current development branch and everything seems fine. Can a second person please double-check? If it works, we can close this issue.

**Comment by stefan-kolb** [comment]
@raycth please recheck the current master.

**Comment by koppor** [comment]
@raycth Please try https://circle-artifacts.com/gh/JabRef/jabref/500/artifacts/0/home/ubuntu/jabref/build/releases/JabRef-2.80dev--snapshot--2015-09-22--8b2821d.jar

**Comment by lenhard** [comment]
We can close this issue, as it seems to be fixed and @raycth is not interested anymore.
