### ISSUE TITLE
Enhancement Request: Indicator for Broken File Links

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#1341]
JabRef version 3.3 on OSX 10.11.4.

Installing version 3.3 and using global entry generators/cleanup/renaming, I seem to have fallen into a situation where some files were renamed with "--" in page-number indicators.  This lead to a break in the filename-entry relationship where now some file links are broken.  I don't think I did anything foolish as a user in the workflow to cause this, but I hesitate to spend the time to reproduce this effect.

Regardless, it would be nice if there were a way for entries with assigned file(s) to indicate if the file(s) exists at the path specified.  Perhaps by marking the entry or causing a change in the PDF icon?

**Comment by simonharrer** [comment]
You can use the "Quality" -> "Integrity Check" function to check any broken file links.

**Comment by jkulesza** [comment]
@simonharrer I discovered that after submitting the ticket and hunting around further.  I didn't close the ticket because I thought there might still be value in an initialization check / passive report of broken links.  

I really like using JabRef, but the recent upgrade to 3.3 and how the "clean-up" works has me concerned about breaking previously-created databases.  

Now I feel like my workflow after adding some entries is select-all, cleanup, generate BibTeX keys (to recognized cleaned-up fields), cleanup again (to rename files according to the new keys), save.  I'm concerned that I now need to add another step of integrity checking and manually remedying any broken links.

**Comment by tobiasdiez** [comment]
Thanks @jkulesza for your suggestions. I split them in separate issues so that they are easier to keep track of:
- Report broken links in entry editor: http://discourse.jabref.org/t/show-warnings-of-integrity-checker-directly-in-entry-editor/
- Improve cleanup workflow (i.e. recreate bibtex keys and fix order): https://github.com/JabRef/jabref/issues/1441
