### ISSUE TITLE
Enhancement Request: Representative Change Case Entries

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#1342]
Version/OS Agnostic.

Recommend changing the right-click, change case entries as follows:

1. Lower case -> lower case
2. Upper case -> UPPER CASE
3. Sentence case -> Sentence Case
4. Capitalize -> Capitalize (All First Letters)
5. Title Case -> Title Case (the Key Words)
6. Protect Terms -> Protect Terms

Hopefully these new entries will better communicate the effect of each (where upper case, capitalize, and title case are not immediately obvious).

**Comment by simonharrer** [comment]
This was supported in a previous JabRef version, but was changed to have standardized names due to  the save actions

**Comment by jkulesza** [comment]
In that case, will the right-click menu be disappearing from the interface?  I like the idea of consistency applied through save actions / clean-up.  However, if a user is interactively using the feature when entering text in a box, it would seem better to have context immediately provided.

**Comment by simonharrer** [comment]
We add a tooltip with the description what the formatter does when hovering over the action in the right-click menu. This should suffice. :)

**Comment by jkulesza** [comment]
A tooltip would be great, thanks!
