### ISSUE TITLE
Open URLs does not work

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1347]
JabRef version: dev on Windows 10
<Hint: If you use a [development version](http://builds.jabref.org/master/), ensure that you use the latest one.>

Steps to reproduce:

1. Create entry with url field `http://books.google.de/books?id=0yaM63MuqckC&lpg=PA153&ots=0H7EqpbM79&lr&hl=de&pg=PA153#v=onepage&q&f=false` simpler urls like `http://books.google.de` work as expected.
2. Click on the open button next to the url field
3. Windows Explorer opens (at some folder) instead of the browser. Sometimes you have to press the button multiple times before something happens.

<If applicable, excerpt of the bibliography file, screenshot, and excerpt of log (available in the error console)>

**Comment by stefan-kolb** [comment]
Confirmed. Links are opned via explorer.exe which seems to have problems with the url.

**Comment by stefan-kolb** [comment]
See https://github.com/rauschma/openurl/issues/2
`cmd -c start` seems to be better for URLs.
@Siedlerchr Why did you move from cmd to explorer.exe? There was a reason as far as i remember!
cmd could not handle anything what explorer.exe could...

**Comment by Siedlerchr** [comment]
@stefan-kolb  Yes, cmd start did not work as expected. 
It seems like the explorer has a problem with query strings.
You could try this one (2nd answer, omitting the explorer)
http://stackoverflow.com/questions/14585709/openning-a-url-containing-a-query-string

````
explorer  "http://books.google.de/books?id=0yaM63MuqckC&lpg=PA153&ots=0H7EqpbM79&lr&hl=de&pg=PA153#v=onepage&q&f=false" 
````

**Comment by stefan-kolb** [comment]
So we will try to quote the `filePath`String.
But do you remember the exact reason or edge case why you choose explorer.exe - just for the record.
