### ISSUE TITLE
Inconsistent { } / Protected Term Behavior

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#1351]
JabRef version 3.3 on OSX 10.11.4

Steps to reproduce:

1. Create new BibTeX database. Add Article entry with "A Library Based on {ENDF/B-VII.0} Using the {CPXSD} Methodology" for author/title/journal/year.  Generate bibkey.
2. Cleanup with settings in screenshot below.  Note that the title is preserved as it stands.
3. Save database.
5. **Quit** JabRef and re-open, open previous database.  Notice that the title is now missing {}s around CPXSD but they are still present around ENDF/B-VII.0.
6. Cleanup with the settings below.  This will now cause CPXSD to go to Title Case (i.e., Cpxsd).

I would expect that the {}s be either universally preserved (preferred) or universally removed.

Please let me know if you would like to see my preferences; however, I cannot find anything that would provoke this behavior.

<img width="714" alt="screen shot 2016-05-04 at 6 13 28 pm" src="https://cloud.githubusercontent.com/assets/9939059/15031026/f4d33882-1223-11e6-95fc-8224b2fc46f5.png">

**Comment by jkulesza** [comment]
Can a developer please weigh in on whether this is expected behavior?

**Comment by tobiasdiez** [comment]
I can't reproduce the problem with the latest developer build available under http://builds.jabref.org/master/. On save `"A Library Based on {ENDF/B-VII.0} Using the {CPXSD} Methodology` gets written to the bib file and is correctly read if I open the file again. 

(Your last step 5 is expected behavior.)

**Comment by jkulesza** [comment]
@tobiasdiez Thanks for taking a look at this!  Indeed, when I save the file with {CPXSD} in the title using 3.4dev, and re-open, the {}s have disappeared.  I do not have any save actions enabled.  

See attached minimum database.

Looking at it with a text editor, I see {CPXSD} but when I load it in 3.4dev, I see CPXSD as shown below.

<img width="845" alt="screen shot 2016-05-09 at 9 40 22 am" src="https://cloud.githubusercontent.com/assets/9939059/15114887/1686b9c8-15ca-11e6-9392-6632f6bde109.png">

[jabref.bib.zip](https://github.com/JabRef/jabref/files/255078/jabref.bib.zip)

**Comment by simonharrer** [comment]
Very strange, I cannot reproduce on my machine either using the latest master build.

**Comment by simonharrer** [comment]
Could you post your settings? Options -> Preferences -> Export preferences

**Comment by jkulesza** [comment]
Please see attached, as exported from 3.4dev.
[jkulesza_settings.prefs.zip](https://github.com/JabRef/jabref/files/255157/jkulesza_settings.prefs.zip)

**Comment by simonharrer** [comment]
Can confirm this is a preferences issue. 

1. Load your prefs
2. Load your file
3. Title shows the false version (but Bibtex source shows the correct one still)
4. save it, and the thing from the title is saved on the disk

The issue is "Store the following fields with braces around capital letters: "title"" This is somehow broken. If you remove this setting, the title field will be loaded correctly.

**Comment by jkulesza** [comment]
Excellent, thanks for the quick diagnostics, can confirm that fixed it.  

Should I leave this issue open to track the broken preference behavior?

**Comment by simonharrer** [comment]
I am kind of in favor of deleting this function as it performs too much magic and does not work correctly. It is also somewhat replaced with save actions, as they can handle the escaping with brakets as well. @JabRef/developers what do you think?

Advantages
- parsing a bib file is getting simpler
- on load, we just use the contents of the field
- on save, we can add brakets around capital letters using save actions
- less magic, more transparency
- as we aim to move towards having a latex free version of each field, this can also help as well
- I do not see any other use case what seems to be an issue here

**Comment by tobiasdiez** [comment]
:+1: for removing this preference option.

**Comment by jkulesza** [comment]
@simonharrer Please note that there is a website FAQ entry on this that will need to be modified/removed.

http://www.jabref.org/faq/

> Q: BibTeX converts uppercase characters to lowercase in my title field. I know this can be prevented by wrapping uppercase letters in braces, e.g. {T}he life cycle of {A}tlantic salmon, but this is too much work. Can JabRef help?

> A: JabRef has a setting that will automatically wrap all capital letters for certain fields in { } - this will make sure they are preserved in the LaTeX output. Under Options -> Preferences -> File -> “Store the following fields with braces around capital letters”, make sure the title field is included. To do this for several fields, write e.g. title;abstract. This setting automatically adds braces when saving the bib file, but you won’t see the braces within JabRef.

**Comment by lenhard** [comment]
@jkulesza: Thanks for following up on this. Since the preference option is gone, we should also remove the FAQ entry.

**Comment by matthiasgeiger** [comment]
Removed.
