### ISSUE TITLE
Update BbTex key key in Fetch dialog is not displayed

### ISSUE THREAD

**Issue by vkoroteev** [JabRef/jabref#1353]
JabRef version 3.3 and 3.4-master-2016-05-03 on Windows 10 x64 doen't update displayer BibTex key in DOI fetch dialog is not updated after clicking "Generate Now". 

Steps to reproduce:
1. Open Jabref
2. Fetch Information by DOI
3. Press "Generate now" button to update BibTex key
4. Displayed BibTex Key should be updated to generated according to user preferences, but it's not. If the entry is saved now, it would contain updated key

**Comment by Siedlerchr** [comment]
I can not reproduce this in the current master 1023c50c7cfc293811761a01afa3211e4eb88672
As far as I know there have been no recent changes on it.
Did you check the BibTexKey Generator Settings if they are correct?

I tried is using the following DOI: `10.2753/mis0742-1222280402`:
 1. Fetch->DOI2BibTex
 2. 
![jabreffetchdoi](https://cloud.githubusercontent.com/assets/320228/15053729/3592b8ee-1304-11e6-93d1-f3cfa2b07ae0.png)

The BibTex Key is in incorrect format `Vlas_2012` 
3. Generate now 
4. Save
The correct  generated BibTex Key is displayed both in step 3 and step 4
![jabreffetchdoi_correctkey](https://cloud.githubusercontent.com/assets/320228/15053769/64d45130-1304-11e6-9aee-2a1f71a595ac.png)
And importing the entry again, it is generated as `Vlas2012a`

**Comment by vkoroteev** [comment]
I didn't notice that Bibtex key field. Please see red frames in attachments, the values there a a bit inconsistent.
Fetch

![untitled](https://cloud.githubusercontent.com/assets/7648791/15055035/c5816a62-130a-11e6-83af-78bb795b4fe3.png)

Generate now
![untitled1](https://cloud.githubusercontent.com/assets/7648791/15055103/11fdc34a-130b-11e6-8a11-09b6d575f3b5.png)

**Comment by Siedlerchr** [comment]
@vkoroteev  Thanks for the information and the screenshots. So it is actually that the rendered preview does not get updated. I just confirmed your problem.

**Comment by vkoroteev** [comment]
Hope this is easy to do :)

**Comment by Siedlerchr** [comment]
@vkoroteev  I just created a PR for this. 2 lines of code. Just a missing call to update the preview panel after generating the key.

**Comment by stefan-kolb** [comment]
@Siedlerchr This one can be closed now?!

**Comment by Siedlerchr** [comment]
@vkoroteev This fix has been included int he master, so it should be included in the most recent snapshot: http://builds.jabref.org/master/

@stefan-kolb  Yes.
