### ISSUE TITLE
Show assigned groups in custom entry preview

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#1354]
JabRef version 3.3 on Windows 8.1

I enabled: _Highlight groups matching any selected entry_, but highlighting by underlying group names is not easy to see, plus there are matching groups not shown down a long tree of groups.

Therefore, it could be more convenient to show the matching groups in the entry preview. Is this possible?

**Comment by stefan-kolb** [comment]
Thank you for your report :smile:
We will consider adding this feature in later versions of JabRef, however, we cannot yet give you an estimation when we will find the time. What about contributing by yourself? See https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md if you are interested. We are always looking for new developers!

**Comment by derTimme** [comment]
Just in case someone is still interested: Here is an easy workaround/solution, if you use the default entry preview.
Just add the following to the entry preview configuration (`Options` - `Preferences` - `Entry preview`, the text field at the bottom):
```
\begin{groups}<BR><BR><b>Groups: </b>\format[HTMLChars]{\groups}\end{groups}
```
You can also adjust that line to your needs: The `<BR>`s are line breaks, `<b>` enables bold font until `</b>`.

This will just display the group names (no colors or icons), but that's enough for my needs.
If an entry isn't assigned to any group, nothing will be displayed (you can change that by removing `\begin{groups}` and `\end{groups}`).

**Comment by anassal** [comment]
@derTimme A great idea! I have done that for groups and keywords and important custom fields, and made title and year larger and bold, etc. You can use `<font color="green>...</font>`..

One might also add a column for `groups` in the entry table (this may need shorter group names and hiding unnecessary fields).

**Comment by derTimme** [comment]
@anassal You're right, but what I meant were the colors which you can define in the groups interface - I updated my comment to clarify that. But the idea of using colors in the entry preview is interesting, never thought of that - thanks for that hint.
