### ISSUE TITLE
Save sort order

### ISSUE THREAD

**Issue by 2bein** [JabRef/jabref#1357]
#JabRef version 3.3 on Windows 7 64 bit

The option "Save entries in their original order" in database properties does not apply. When saving the database, all entries are re-sorted by the field "YEAR"! It worked in 3.2!

**Comment by simonharrer** [comment]
Did you try the most recent development build? Is is reproducible there?

Could you provide an example bib file, along with your preferences?

**Comment by 2bein** [comment]
Sorry I'm too busy at the moment and installed back to 3.2...

I only can say that the database properies UI is buggy: If you do a  change in any field (in our case we changed the standard file path) the sort order of the primary criteria is applied (standard = "abstract") although we have activated "sort by original order" (its not YEAR as I claimed false before).

I have no capacity for more feedback or tests, hope you can reproduce the bug...I'm happy with 3.2 at the moment and we need it working at our institute. I might be able to help later this month.

**Comment by benni0815** [comment]
@simonharrer Please try the attached bib file:
```
% Encoding: UTF-8

@Article{MacKenzie1967,
  title     = {Temperature Dependence of Positron Mean Lives in Metals},
  author    = {MacKenzie, I. K. and Khoo, T. L. and McDonald, A. B. and McKee, B. T. A.},
  journal   = {Phys. Rev. Lett.},
  pages     = {946--948},
  volume    = {19},
  year      = {1967},
  doi       = {10.1103/PhysRevLett.19.946},
  month     = {Oct},
  url       = {http://link.aps.org/doi/10.1103/PhysRevLett.19.946},
  issue     = {17},
  numpages  = {0},
  owner     = {Vorlage},
  publisher = {American Physical Society},
  timestamp = {2015.10.27},
}

@Article{Hotz1968,
  title     = {Measurement of Positron Annihilation Line Shapes with a Ge(Li) Detector},
  author    = {Hotz, H. P. and Mathiesen, J. M. and Hurley, J. P.},
  journal   = {Phys. Rev.},
  pages     = {351--355},
  volume    = {170},
  year      = {1968},
  doi       = {10.1103/PhysRev.170.351},
  month     = {Jun},
  url       = {http://link.aps.org/doi/10.1103/PhysRev.170.351},
  issue     = {2},
  numpages  = {0},
  owner     = {Vorlage},
  publisher = {American Physical Society},
  timestamp = {2015.10.27},
}

@Comment{jabref-meta: databaseType:biblatex;}
```
[test.bib.txt](https://github.com/JabRef/jabref/files/259866/test.bib.txt)

When I open it in JabRef, open the file properties dialog and click OK without changing anything and then save the file, the order of the entries is reversed.
Besides that the following line is added to the file:
`@Comment{jabref-meta: saveOrderConfig:original;abstract;false;abstract;false;abstract;false;}`
When I add this line with a text editor to the original bib file, open it with JabRef and just save the file, then the order has also been changed.

**Comment by koppor** [comment]
> I only can say that the database properies UI is buggy: If you do a
change in any field (in our case we changed the standard file path) the
sort order of the primary criteria is applied (standard = "abstract")
although we have activated "sort by original order" (its not YEAR as I
claimed false before).

Same here.

**Comment by stefan-kolb** [comment]
@2bein @benni0815 
This should be fixed in current `sort-order`. Please try the latest build from http://builds.jabref.org/sort-order.

**Comment by benni0815** [comment]
Looks very good, order stays the same now. Thanks a lot!
