### ISSUE TITLE
Collect usage statistics

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1359]
Automatically (and of course anonymously) collect usage statistics, for example about:
- changed preferences (to determine better default values)
- number of open databases, size of db, ...
- used functionality (to extract main use cases)

Maybe also occasionally ask questions about the way users use JabRef and/or what they want (a lite version of the recent survey).

Of course, the should have to option to opt out of this data collecting.

**Comment by simonharrer** [comment]
We could leverage Google Analytics for this which allows to send arbitrary events to the cloud for analysis.

**Comment by tobiasdiez** [comment]
In this case, we may use https://github.com/siddii/jgoogleanalytics or some related project.

**Comment by Siedlerchr** [comment]
As an alternative we could use Piwik:
https://github.com/piwik/piwik-java-tracker 
It can be self-hosted and would be a bit more user-privacy-friendly

**Comment by simonharrer** [comment]
I do not like this self-hosted stuff, as it draws developer resources away from the more important things - improving JabRef :)

**Comment by tobiasdiez** [comment]
Decision from devcall: use google.

**Comment by Siedlerchr** [comment]
Google analytics no longer works. There is no actual version which can be used.

**Comment by lenhard** [comment]
This can be closed as it has been implemented in #2283 with Microsoft Azure.
