### ISSUE TITLE
Extract and unify all GUI actions

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#136]
The question is how can we reduce the cluttering caused by those inline classes.

The class `gui.action.ParseAction.java` is a good example for proposing a possible solution.
The exact same behaviour is needed different classes.

Even with a controller-like class we will have some code duplication as one controller should not serve multiple views...

**Comment by matthiasgeiger** [comment]
> The question is how can we reduce the cluttering caused by those inline classes.

Java 8, FTW! :wink:

```
        actions.put("selectAll", new BaseAction() {

            @Override
            public void action() {
                mainTable.selectAll();
            }
        });
```
Would be: 
```
actions.put("selectAll", (BaseAction) mainTable::selectAll);
```
Is it less cluttering? Yes. Is it more understandable for outsiders starting coding for JabRef? Depends highly on Java 8 knowledge :wink:

**Comment by koppor** [comment]
:+1: for the new code. Although, I don't understand the cast, is there a quick howto? Can this be added to [the wiki](https://github.com/JabRef/jabref/wiki/Code-Howtos)?

**Comment by matthiasgeiger** [comment]
Signature of the put-Method is ```put(String key, Object value)``` - as Object is no functional interface the type of the Object (i.e., the functional interface to be used) must be set explicitly by the "cast".
However the example showed the best case regarding simplification as it was even possible to use the method reference only.
If there is more than one method call the difference is not as impressing :wink: :
```
        actions.put("editPreamble", (BaseAction) () -> {
            if (preambleEditor == null) {
                PreambleEditor form = new PreambleEditor
                        (frame, BasePanel.this, database, Globals.prefs);
                Util.placeDialog(form, frame);
                form.setVisible(true);
                preambleEditor = form;
            } else {
                preambleEditor.setVisible(true);
            }
        });
```

**Comment by stefan-kolb** [comment]
I think we can close this for now, the transition is an ongoing process...

**Comment by matthiasgeiger** [comment]
Agreed.
