### ISSUE TITLE
impossible to recognize JabRef in the Windows registry

### ISSUE THREAD

**Issue by donovaly** [JabRef/jabref#1362]
Since years i bundle JabRef as default BibTeX editor with the program LyX. Now I want to bundle JabRef 3.3 but failed for the following reason:

If JabRef was installed only for the current user I can no longer check if it is still installed. For JabRef 2.x I could simply look in the registry under
"HKEY_CURRENT_USER\Software\JabRef" "Path"
and then check if the jabref.exe exists in this path.

Now all one finds in the registry is
"HKEY_CURRENT_USER\Software\ej-technologies\install4j\installations" "instdir0034-7691-1464-4754"

But of course this random name is different on every installation. Could you therefore please also add a registry entry
"HKEY_CURRENT_USER\Software\JabRef"
where you store the installation directory?

Please do the same if JabRef is installed as admin. With JabRef 2.x one gets the install patch at
"HKEY_LOCAL_MACHINE\Software\JabRef" "Path"
while there also only a random name for JabRef 3.x.

**Comment by stefan-kolb** [comment]
@donovaly I implemented your request in #1370. Can you please try a version from http://builds.jabref.org/win-install

**Comment by donovaly** [comment]
> Can you please try a version from http://builds.jabref.org/win-install

Done.
Works perfect! Many thanks.
