### ISSUE TITLE
wrong default installation directory for non-admin installations

### ISSUE THREAD

**Issue by donovaly** [JabRef/jabref#1364]
If JabRef 3.3 is installed on Windows only for the current user (without admin privileges) the default installation folder proposed by JabRef is
C:\Users\<username>\JabRef
this is incorrect, according to the Windows guidelines it must be
C:\Users\<username>\AppData\Local\JabRef

All other programs I know respect this default installation folder for current users.

**Comment by stefan-kolb** [comment]
Are you sure this shouldn't go to `APPDATA\Roaming` so the user profile data gets synched when in a Domain? Could you provide links where this best practice is specified?

**Comment by stefan-kolb** [comment]
We can discuss this in this context:https://msdn.microsoft.com/en-us/windows/uwp/app-settings/store-and-retrieve-app-data

**Comment by donovaly** [comment]
> Are you sure

Sure ;-)
The default installation folder for local users is available via teh %LOCALAPPDATA% variable.
It points you automatically to
 	%USERPROFILE%\AppData\Local
reference:
https://blogs.msdn.microsoft.com/patricka/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions/

**Comment by stefan-kolb** [comment]
Why not use the Roaming folder to keep JabRef synchronized for users inside domains?

**Comment by donovaly** [comment]
> Why not use the Roaming folder to keep JabRef synchronized for users inside domains?

Because Roaming is for installations for all users on a PC. A local installation (only for the current user) cannot be synced with others - that's the concept of the local installation.

**Comment by donovaly** [comment]
> Can you please try a version from http://builds.jabref.org/win-install

Done. This does not solve the problem because it tries now to install in the same folder where the installer was started from. So when I execute the installer from C:\Test it proposes C:\Test\JabRef as install folder.
So this bug is not fixed. Please reopen this bug report.

**Comment by stefan-kolb** [comment]
Thanks for pointing this out :+1: 
I incidentally used the wrong method to retrieve the environment variable :blush: 
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by donovaly** [comment]
> Please try the latest build

Done. Many thanks! The bug is now correctly fixed. So from my point of view all install issues are solved. I am looking forward for JabRef 3.4 to use its installer.
