### ISSUE TITLE
Cannot view the custom entry type

### ISSUE THREAD

**Issue by leilou13** [JabRef/jabref#1366]
Hi everyone,
I need some help as i would like to add my own entry type to jabref. I followed the instruction and made the layout file. However, after i add everything, i cannot see it as an option when i add a new entry.

Am i doing something wrong??

**Comment by matthiasgeiger** [comment]
Can you please tell us which version of JabRef you are using and to which instructions you refer to?

Thanks!

**Comment by leilou13** [comment]
Hi! i use the latest version 3.3 for windows

**Comment by leilou13** [comment]
i am referring to the "manage custom export" layout file. There is also part of the script that add a custom entry type for the publications that are imported

**Comment by tobiasdiez** [comment]
You can add entry types under BibTeX -> Customize entry types. The types you add there appear under BibTeX -> New Entry. 
The layout file for exports is only required if you want to write to a new file format, say a customized HTML export.

Does this solves your problem?

**Comment by leilou13** [comment]
yes it does!! All good and working now :) 
Thanks a lot guys!
