### ISSUE TITLE
Add Jabref to app stores

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1371]
- [x] Windows: Chocolatey (https://chocolatey.org/packages/JabRef)
 - [ ] Windows: App Store - see https://dzone.com/articles/java-developers-can-finally-target-windows-uwp
 - [x] Mac App Store - impossible http://alvinalexander.com/mac-os-x/mac-app-store-java-apps-supported-deprecated
 - [ ] Ubuntu - see https://github.com/JabRef/jabref/issues/3121
 - [x] Arch Linux: https://aur.archlinux.org/packages/jabref/
 - [ ] self-made deb and rpm packages: https://github.com/JabRef/jabref/issues/3122

**Comment by tobiasdiez** [comment]
Chocolatey: https://chocolatey.org/packages/JabRef (version 3.2)

**Comment by simonharrer** [comment]
- Ubuntu store https://shop.canonical.com/index.php?cPath=19

**Comment by tobiasdiez** [comment]
Looks like it is (relatively?) easy to include normal apps in the Windows Store: http://www.hanselman.com/blog/PuttingMyVB6WindowsAppsInTheWindows10StoreProjectCentennial.aspx

**Comment by Siedlerchr** [comment]
@tobiasdiez  At least not Java apps, only supported are .NET or native Windows Apps when I read it correct.

For Mac App store it is also not possible:
http://alvinalexander.com/mac-os-x/mac-app-store-java-apps-supported-deprecated

**Comment by stefan-kolb** [comment]
@JabRef/developers  Any idea if we can add it to the Ubuntu store? If not, we should close this issue for now.

**Comment by koppor** [comment]
The idea is outlined at https://github.com/JabRef/jabref/pull/2345. Please follow up there.

**Comment by tobiasdiez** [comment]
Windows Store is still open, as I believe Java-Apps are possible there.

**Comment by Siedlerchr** [comment]
@tobiasdiez  Windows App Store is theoretically possible, however the only possible option is using the commercial toolkit CodenameOne:
https://dzone.com/articles/java-developers-can-finally-target-windows-uwp

**Comment by tobiasdiez** [comment]
According to [this answer](https://stackoverflow.com/questions/39005244/can-a-java-swing-desktop-application-be-converted-to-a-uwp-centennial-app-appx) it is possible to add Java apps to the Windows Store. See also https://github.com/crramirez/uwp_bridge_java.

**Comment by koppor** [comment]
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [freeze label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Afreeze+) and closing the issue for now.
