### ISSUE TITLE
<< entry not opening >>

### ISSUE THREAD

**Issue by icamps** [JabRef/jabref#1392]
JabRef versions: 2.11, 3.3 32bits, 3.3 64bits, 3.4dev--snapshot--2016-05-12--master--bab82ab
Windows 10, 64bits
Java 1.8.0_91 (32&64 bits)

Hello,

After loading the bib file without complain, when clicking twice over any entry, the entry is not "opened" or expanded as in previous versions (2.9).

Regards,

Camps

**Comment by Siedlerchr** [comment]
Thanks for your report.
Just to get sure we mean the same: You are referring to double clicking on an entry in the "Main Table"?
Do you get any errors/(information in the log?
Does selecting an entry and then clicking "Edit entry" in the toolbar works?

I can't reproduce this.  Please check this with a new test-bib file with a few entries.

**Comment by icamps** [comment]
@Siedlerchr 
* You are referring to double clicking on an entry in the "Main Table"? YES
* Does selecting an entry and then clicking "Edit entry" in the toolbar works? Half. It create the entry in the "Main Table", but I can not edit it.
* Do you get any errors/(information in the log? Where are the logs? I look in the Jabref folder and in the bib folder.

Here are two bib files with different number of entries with the same problem.

Thanks.

[misc.zip](https://github.com/JabRef/jabref/files/263832/misc.zip)

**Comment by icamps** [comment]
@Siedlerchr @stefan-kolb 

I did a registry clean with three programs, restart my PC and everything is working now.

I thing the problem was "a mix" of JabRef version information in the windows registry.

Thank you for your support.

**Comment by matthiasgeiger** [comment]
Thanks for the feedback!

Might have been related to #1450.
