### ISSUE TITLE
New personal journal list can't be created 

### ISSUE THREAD

**Issue by boceckts** [JabRef/jabref#1394]
A new personal journal list can't be created in the journal abbreviations dialog.
JabRef 3.4dev
mac os x 10.11.1 x86_64 
Java 1.8.0_77

Steps to reproduce:

1. Click the "Manage journal abbreviations" menu item in the "Options" menu
2. In the journal abbreviations dialog make sure the "New file" checkbox is selected and choose a new path and file name
3. Click the "+" Button and add a test entry
4. Click the "OK" button of the journal abbreviations dialog
5. You should see the error message "Error opening file: <yourFilePath>"

![screen shot 2016-05-13 at 10 31 34](https://cloud.githubusercontent.com/assets/15340757/15242991/5f373968-18f9-11e6-893b-72c341eb52e0.png)

**Comment by simonharrer** [comment]
Also the UI does not look that nice on OSX with the white and gray background changing in between.

**Comment by Siedlerchr** [comment]
Thanks for your report. I will try to reproduce it on other systems as well.
Could you please check if the Error Log contains further information?

2016-05-13 11:00 GMT+02:00 Tobias Boceck <notifications@github.com>:

**Comment by boceckts** [comment]
@Siedlerchr I just checked, there is no output on the error console regarding this issue.

**Comment by boceckts** [comment]
@simonharrer any suggestions to the ui of the dialog can also be discussed at #1396

**Comment by Siedlerchr** [comment]
@boceckts Coud you please upload the test file you used, too?

**Comment by boceckts** [comment]
As the steps show I`m trying to create a new file rather than using a existing one. So there is no test file I used. Or did I miss understand what the "new file" checkbox does?

**Comment by Siedlerchr** [comment]
Confirmed on Win. Will prepare a fix PR.

**Comment by Siedlerchr** [comment]
Can be closed
