### ISSUE TITLE
export to html: html code is not well-formed

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#1399]
JabRef 3.4dev--snapshot--2016-05-13--master--f28466e
windows 7 6.1 amd64 

Steps to reproduce:

1. Take any bib file, and press export to html
2. Open the html in a texteditor, there will be no < / body > or < / htm l>

Also a custom export I have been using seems to suffer (as if the end.layout is not used).

Thanks in advance for looking into it!

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
What do you expect?
Can you give a minimal example of your problem? I tried it with the the current `master` and exported 2 entries and couldn't see what's missing.

**Comment by Yery** [comment]
thanks for your reply! I see now that the html codes did not show up in my original message (should have checked sorry). Basically, to clarify < / body > and < / html  >  are not there (without the spaces). The last line is < / div> - and for the custom export I have also other stuff that is part of end.layout and is not there.

**Comment by lc9275** [comment]
thanks for your reply! I see now that the html codes did not show up in my original message (should have checked sorry). Basically, to clarify < / body > and < / html > are not there (without the spaces). The last line is < / div> - and for the custom export I have also other stuff that is part of end.layout and is not there.

**Comment by stefan-kolb** [comment]
Ah ok, so all the entries are there but HTML code is missing!

**Comment by stefan-kolb** [comment]
````html
<!DOCTYPE HTML>
<html>
<head>
<title>JabRef references</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style type="text/css">
body { font-size: 12px; font-family: Arial, sans-serif; }
dt { margin-top: 1em; font-weight: bold; }
@media print {
	dt { page-break-after: avoid; }
	dd { page-break-before: avoid; }
}
</style>
</head>
<body>
<dl>
<dt>article <a name="Hotz1968">(Hotz1968)</a></dt>
<dd>Hotz, H. P., Mathiesen, J. M. and Hurley, J. P.</dd>
<dd><i>Measurement of Positron Annihilation Line Shapes with a Ge(Li) Detector</i></dd>
<dd>Phys. Rev., American Physical Society, <b>1968</b>, Vol. 170, pp. 351-355</dd>
```

**Comment by stefan-kolb** [comment]
Problem is here:
```java
            // Write footer
            if ((endLayout != null) && (this.encoding != null)) {
```
encoding == null

**Comment by stefan-kolb** [comment]
@JabRef/developers Does anyone have experience with these formatters?

**Comment by curtcorum** [comment]
This is potentially a similar issue???

https://github.com/JabRef/layouts.jabref.org/issues/4
