### ISSUE TITLE
JabRef 3.3 on windows 10 cannot call texstudio.exe to push entries

### ISSUE THREAD

**Issue by tianlema** [JabRef/jabref#1400]
JabRef 3.3 on Windows 10

Steps to reproduce:
1. Ctrl-L: Push entries to external application (TexStudio)

Error: cannot call the executable C:\Program Files\TexStudio\texstudio**\**.exe

The executable file should be C:\Program Files\TexStudio\texstudio.exe
But JabRef 3.3 added a slash "\" before ".exe", which I believe caused the problem.
Reinstall JabRef 3.2, it works fine.

**Comment by stefan-kolb** [comment]
Thank you for your report :smile:
I can reproduce the behavior and we will work on a fix for this issue. Stay tuned.

**Comment by stefan-kolb** [comment]
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by matthiasgeiger** [comment]
@stefan-kolb CHANGELOG 😉

**Comment by tianlema** [comment]
Great! I am amazed by how quickly an issue could be fixed. Thank you for your great work!

**Comment by michaelemery** [comment]
Having the same problem on macOS Sierra
Path set to: /Applications/texstudio.app   (selected using browse button)
Selecting texstudio from menu gives error:
Could not call executable '/Applications/textstudio.app'

**Comment by stefan-kolb** [comment]
@michaelemery This seems like a different issue as it's on OSX. Feel free to open a separate issue.

**Comment by matthiasgeiger** [comment]
@michaelemery Before opening a new issue please check #2613 as this seems to cover exactly your problem. Thanks!

**Comment by rosaverlag** [comment]
Hi! I have the same issue and I downloaded the latest release of TexStudio, can someone help me?
