### ISSUE TITLE
Synchronize file links default folder look-up

### ISSUE THREAD

**Issue by tb77phd** [JabRef/jabref#1402]
JabRef version 3.3 on Windows 10.

When I want to find broken links (e.g., if I have moved a PDF from one folder to another), I click on "Synchronize file links..." under the Quality menu and then check the "Check existing file links" box. In addition, I choose "Do not automatically set" file links. After this, a dialog pops up titled "Broken link", and I can now choose "Assign new file".

When I do that, the dafault folder is always C:\Users\"Name"\Documents. This is pretty annoying if one doesn't have their PDFs stored there. It becomes cumbersome to pick the correct folder, find the PDF, move one, get the next broken link, click on "Assign new file", again come to the default C:\Users\"Name"\Documents, locate the correct folder, etc.

Nowhere (as far as I know) in my JabRef settings do I have this folder set up, my default folder is something easier (C:\Library).

Is it possible to set the default Broken link search folder to something else than C:\Users\"Name"\Documents? Preferrably the Main file directory that is set in the Preferences. If not, is it possible for JabRef to at least remember the last location?

Thanks.

**Comment by stefan-kolb** [comment]
Thank you for your report :smile:
I can reproduce the behavior and we will work on a fix for this issue. 
I can both set the default file directory and the last location. I tend to favor the last location over the file directory, as sometimes it might be not the best guess if someone tries to link files from other folders.

**Comment by stefan-kolb** [comment]
Behavior now is:
If linked file is present goto file dir.
If linked file is not present goto last working directory.
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
