### ISSUE TITLE
Journal autocompletion

### ISSUE THREAD

**Issue by tb77phd** [JabRef/jabref#1406]
JabRef version 3.3 (and JabRef_windows-x64_3_4dev--snapshot--2016-05-17) on Windows 10.

I use autocompletion frequently for authors and also for journals. My issue is this: while for authors, autocompletion autocompletes from authors I already have entries for, this is not the case for journals. Instead, journal autocompletion seems to use a master list of journals with (probably) a huge amount of journals in a wide variety of fields. Most users only work in a few fields and won't need many of the autocomplete suggestions.

Example:
If I want to enter the journal name "Journal of Applied Physics", I have to type all the way to "Journal of Applied Phys" before it autocompletes to the correct name. The other intermediate steps in this particular example are:
"Jou" suggests "Journal - American Water Works Association"
"Journal o" suggests "Journal of  Circadian Rhythms"
"Journal of A" suggests "Journal of AAPOS"
Journal of Ap" suggests "Journal of Apicultural Research"
and so on. You get the idea. I have no entries in my database with these journals, and therefore the suggestions are irrelevant to me.

Can the autocompletion for journals work the same as for authors, i.e., only autocomplete if the journal name already has been used in the database? Or would I need to create my own "master" list of journals?

Thanks!

**Comment by stefan-kolb** [comment]
Thank you for your report :smile:
We are currently reworking the autocompletion and will consider your request.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. 
Now you can also use for "Applied physics" and thus find the desired journal very quickly. Moreover, we use a dropdown box now so that it should be even easier.
Could you please check the build from http://builds.jabref.org/master/. Thanks!
