### ISSUE TITLE
Problem removing group with long names

### ISSUE THREAD

**Issue by juniorcaemj** [JabRef/jabref#1407]
JabRef version 3.2 on Windows 10

User Interface Problem

If a group with a long name been removed, the JOptionPane box is created too large, vanishing "Yes" and "No" buttons.

Steps to reproduce:
1. Create a group with a long name
2. Try remove group

![1](https://cloud.githubusercontent.com/assets/17187418/15323642/6ec92f58-1c19-11e6-863d-e982b50b2b90.jpg)
![2](https://cloud.githubusercontent.com/assets/17187418/15323643/6ed08b54-1c19-11e6-9f18-da8d28d4bef0.png)

**Comment by matthiasgeiger** [comment]
Thanks for your report.

If this is a real problem for you, simply delete the group just hit "enter" as "Yes" is preselected.

However, this seems to be only a theoretical problem, so we might fix this in a later version but first concentrate on other more important aspects.

**Comment by juniorcaemj** [comment]
Hello @matthiasgeiger, I report this problem because it's a work (especifically UI Tests) for a Software Testing course, and we utilize JabRef as a case study. So I found interesting report it to the community.

**Comment by simonharrer** [comment]
Thanks for the info. We welcome that JabRef is used in testing case studies. :+1: 

What would be the expect solution? Truncate the group name after a specific number of letters?

We also have UI tests in place at https://github.com/JabRef/jabref/tree/master/src/integrationTest/java/net/sf/jabref/gui - you could also have a look there. They are only the tip of the iceberg, and need further improvements. :)

**Comment by matthiasgeiger** [comment]
Nice to hear, that JabRef is used in a practical Software Testing course. :+1: 

Hopefully not only as a bad example :wink:  We already know that the test coverage of our code should be improved, and we are already working on it. But especially on the field of UI testing there are only a few tests present - as Simon just mentioned.

If you are implementing practical, executable tests in your course we'd love to integrate them into our tests - if this is possible!

If you have other findings, or tips for us to improve JabRef just contact us!

**Comment by juniorcaemj** [comment]
@simonharrer I thinking in this solution too, limit the size of group name, doesn't make any sense a group with a very very long name..

@matthiasgeiger I will read the documentation and submit my tests (and maybe a solution), as soon as I can.

**Comment by stefan-kolb** [comment]
I just tried this and it's really a theoretical problem because the message box is just sized as big as the group name. If you move the mbox or you have two monitors it's still there for you. This is such a small improvement and will probably never happen so that we defer it to the UI rework.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
