### ISSUE TITLE
Save action protect terms protects unecessarily

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1412]
JabRef version JabRef 3.4dev--snapshot--2016-05-19--master--ed638e2
windows 10 10.0 amd64 Java 1.8.0_92

Steps to reproduce:

1. `title = {{BPEL}}`
2. enable `protect terms` for `title`
3. `title = {{{BP}EL}}`

Expected: `title = {{BPEL}}`

**Comment by stefan-kolb** [comment]
The formatter itself passes this test!
