### ISSUE TITLE
Groups -> Settings -> Select Matches seems to do nothing

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1413]
I vote to remove this feature, as it is not explained in the help, and I have no clue what it does, and I can see no effect whatsoever. @tobiasdiez can you help here?

**Comment by tobiasdiez** [comment]
No, I have no idea what the effect of this option is...

**Comment by mlep** [comment]
Here are some clues:
<https://sourceforge.net/p/jabref/mailman/message/1369311/>
<https://sourceforge.net/p/jabref/discussion/318825/thread/c3e6c71f/>
It seems to be not working for a very long time...

**Comment by simonharrer** [comment]
Ah ok. But still, this feature should be removed as it does not make too much sense to me.

**Comment by mlep** [comment]
Sounds reasonable! ;-)

**Comment by tobiasdiez** [comment]
So this is something like the `incremental search`, which in my opinion makes absolutely no sense for groups.
