### ISSUE TITLE
Filename format pattern is unintuitive

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1416]
Is hard to understand and no help is provided. Needs to be simplified so users can change the pattern.

`\bibtexkey\begin{title} - \format[RemoveBrackets]{\title}\end{title}`

Why not `\bibtexkey - \format[RemoveBrackets]{\title}`

It was also hard to find the preference under import. I assumed it to be somewhere inside the file preferences.

**Comment by simonharrer** [comment]
This format is also used for the entry preview. This may be the reason why as it contains so many selectors for bibentry data.

**Comment by oscargus** [comment]
The `\begin{title}...\end{title}` is to make it optional based on the existence of a non-null `title` field.

**Comment by Siedlerchr** [comment]
This has recently been adapted to a new pattern. So I close this
