### ISSUE TITLE
Improve DOI auto retrieval

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1424]
Compare with original entry title:
- [x] remove latex and compare a-z0-9
- [x] remove stuff and use a edit distance threshold
- [ ] distinguish between missing words at the end (inaccurate data) and different words at the start or in between
- [ ] Does not remove braces like, e.g., `Enhancing {BPMN} 2.0~{S}upport for Service Interaction Patterns`
- [ ] LaTeX command may fail the algorithm, e.g., `SCE\textsuperscript{MT}: A Multi-tenant Service Composition Engine`
- [ ] Only logging failure to status bar is strange for user clicking on the button
- [ ] Techreps and thesis are sometimes wrongly assigned as a different paper with the same name exists
- [ ] Lookup doi not identical status in bar! Override current value?

Use a large Bibtex file with valid DOIs (e.g. Simon's) to compare the diff and accuracy of the algorithms.
- [x] Reject DOIs that do not suffice the check algorithm
- [ ] Implement a bulk action for getting all DOIs for several entries

**Comment by wilthan** [comment]
Also,
when I look up a DOI and then click into another tab, the DOI is gone when I go back to the general-tab. ( in 3.3)

**Comment by matthiasgeiger** [comment]
@wilthan I think has alread been solved (as this should be related to #1234) - you can use a development build from http://builds.jabref.org/master/ which should work correctly.

**Comment by wilthan** [comment]
Thx - it is indeed. 
I checked the 3.4 dev and there it's fixed already.

**Comment by stefan-kolb** [comment]
See #518

**Comment by stefan-kolb** [comment]
Closing for now.
