### ISSUE TITLE
Importer open dialog improvements

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1431]
![image](https://cloud.githubusercontent.com/assets/2141507/15421447/9e12e31a-1e73-11e6-950c-0037dc4708c0.png)

The open dialog of the importer `import into...(new | current) db` needs several improvements:
- [ ] the file type selection must filter the view based on suppported types
- [ ] the file type selection should display supported file endings for each type, e.g., medline|Pubmed? (*.nbib, ...)

**Comment by tobiasdiez** [comment]
Some of the backend code required for this improvement is available with https://github.com/JabRef/jabref/pull/1207.

**Comment by Siedlerchr** [comment]
Regarding file filters, I recently added the code for this in the BrowseAction.
Have a look at this commit: #1304 
The whole code for file opening will be finally reworked in #1336 (Atm I don't have time for that)
