### ISSUE TITLE
Sorting changes between fields bibtex <-> biblatex mode

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1439]
JabRef 3.4dev--snapshot--2016-05-23--master--4aa51a3
windows 10 10.0 amd64 
Java 1.8.0_92

Example:

```diff
 @Article{Emer2011FaultBasedTest,
   author  = {Emer, Maria Claudia Figueiredo Pereira and Nazar, Igor Fabiano and Vergilio, Silvia Regina and Jino, Mario},
   title   = {{Fault-Based Test of {XML} Schemas}},
-  journal = {Computing \& Informatics},
   year    = {2011},
   volume  = {30},
   number  = {3},
   pages   = {531--557},
+  journal = {Computing \& Informatics},
 }
```

Holds for several other fields: publisher, journal, pages, address, month, title, ...

**Comment by matthiasgeiger** [comment]
I'm not sure whether this is really a bug... as we defined the order as "*mandatory fields* followed by *optional fields*" this has to change if you are switching the modes...

**Comment by simonharrer** [comment]
Hm, true - but still was annoying for me at first.
