### ISSUE TITLE
Integrity check for possibly wrong DOIs

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1445]
- [x] syntactically wrong DOIs
- [ ] semantically wrong DOIs false assignment, not the correct DOI (has influence on PDF retrieval!)

**Comment by simonharrer** [comment]
:+1: 

Could be a performance issue. 

Maybe we should make the integrity check asynchronous based on events of database changes, so that all integrity violations are always kept in sync eventually. But this would require a lot of code.

**Comment by stefan-kolb** [comment]
A maybe I meant Cleanup not integrity check?!

**Comment by simonharrer** [comment]
@stefan-kolb is the solution of the integrity check sufficient for you? Can this be closed then?

**Comment by stefan-kolb** [comment]
Uhm, well this was not meant to be a check for syntactically wrong DOIs but more for DOIs that do not fit the current entry, i.e., not the correct DOI for an entry.

**Comment by matthiasgeiger** [comment]
> No description provided.

There's a reason for this description field. 😜

**Comment by simonharrer** [comment]
@stefan-kolb ah ok. But this would require to change the architecture of the integrity checks. At the moment, the integrity checks are fast as they use only local knowledge. If you want to use global knowledge from the internet, this would introduce considerable delays. Not sure if this is feasible without investing a lot of time.

**Comment by stefan-kolb** [comment]
Yes, we already discussed this before. Probably we should implement such a check but only call it when a full text PDF is queried or the BibTeX auto completion is called. If this check fails we should alert the user that the DOI is possibly wrong.

**Comment by stefan-kolb** [comment]
I thought about several ideas how to validate if the DOI is the correct DOI for an entry, but I think we just have to accept the DOI right now if there is one given. Algorithms to check if it is the right DOI for the entry may also fail quite often so we have to trust the user and he has to find out by himself that he put the wrong DOI. Another option would be to put a manual validate DOI functionality with warnings but I think this is not useful enough right now to be justified.
