### ISSUE TITLE
Better default for saving files

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1446]
If the preferences are reset, and I want to download a file, JabRef suggests that I store it under `C:\`. I would prefer to use a more sophisticated location, e.g., relative to the current bib file perhaps. As normally, one does not have access rights to save directly on `C:\`, wwhich can leave to strange behavior.

**Comment by Siedlerchr** [comment]
If in a file save/open dialog no folder is given, it points default to the user directory (Eigene Dateien) (at least under windows) 
This could be done with #1336

**Comment by stefan-kolb** [comment]
@simonharrer For me this exactly behaves like you want it to right now. Can you confirm?

**Comment by simonharrer** [comment]
Nope. Still broken.

**Comment by simonharrer** [comment]
@stefan-kolb Maybe just enable the flag that files are stored alongside the bib file by default? This would definitely improve matters.

**Comment by Siedlerchr** [comment]
Currently the value from  Globals.prefs.get(JabRefPreferences.PREFS_EXPORT_PATH is used/stored
in PreferencesDialog.java

**Comment by Siedlerchr** [comment]
@stefan-kolb 
Okay, I looked into it a bit, it simply checks all possible file Directories from the settings., and would return the first found.
Could you please report what kind of directories are set as default? 

https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/gui/externalfiles/FindFullTextAction.java#L76

**Comment by stefan-kolb** [comment]
See `BibDatabaseContext.java` `getFileDirectory()`:
1. metadata user-specific directory
2. metadata general directory
3. preferences directory
4. BIB file directory

**Comment by Siedlerchr** [comment]
Yeah, when the settings are resetted one of the dirs is chosen, from first to last. ( I know that code piece) 
So  it would be nice to see where the "root" dir comes from.

**Comment by stefan-kolb** [comment]
I have no idea.

**Comment by stefan-kolb** [comment]
Funny enough, I now get the following error:
![image](https://cloud.githubusercontent.com/assets/2141507/21010013/1f7e7598-bd4a-11e6-8db8-5226e2df6e18.png)
