### ISSUE TITLE
Improve workflow after adding new entries

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1456]
After adding or importing a new entry, my workflow usually looks like this:
1. "Lookup DOI"
2. "Get fulltext" 
3. "Get BibTeX data from DOI"
4. Cleanup (automatic and manual)
5. Compare bibtex data with data contained in the pdf (Journal, pages etc pp)

It would be fantastic if all these steps could be reduced to one step:
Click a button "Complete entry data", which then gets the doi, the fulltext and additional bibtex data, runs some predefined cleanups on the received data and then finally compares the result in the merge dialog to the original entry, enriched with the downloaded pdf view as a third pane.

**Comment by stefan-kolb** [comment]
Get fulltext now tries to find a DOI first if none exists. However, it does not write this DOI as the user might not want it inside the entry. So you can skip this step if you just want the full text.
