### ISSUE TITLE
Bug in the conversion of \emph{...} in RTF export?

### ISSUE THREAD

**Issue by bvdalen** [JabRef/jabref#1457]
JabRef version 3.3 on Windows 7 64bit

Steps to reproduce:

% BEGIN OF BIBLATEX file:
% Encoding: UTF-8

@Article{article:0000,
  author       = {A. Author},
  title        = {An article title with \emph{a book title} emphasized},
  journaltitle = {Journal},
  volume       = {1},
  date         = {2016},
  pages        = {1-10},
}

@Comment{jabref-meta: databaseType:biblatex;}
% END OF BIBLATEX file

1. Open the file, select the only entry and click on File, Export selected entries
2. Select any of the RTF formats (DIN 1505, Harvard, MIS Quarterly) and save
3. In the resulting RTF file only "a" is in italics, not "book title".
The same problem does not seem to appear in the HTML exports.

Extract from the RTF file for the Harvard RTF conversion:
{\scaps Author, A.}
: An article title with {\i a} book title emphasized}
. In: {\i Journal} {1} (2016), S. 1-10 \par

Attachment: Wordpad screen shot
[harvard-test](https://cloud.githubusercontent.com/assets/19624893/15628199/7f6f207a-24fb-11e6-82ae-a3b98a9bc771.jpg)

**Comment by stefan-kolb** [comment]
Thank you for your report :smile:
I can reproduce the behavior and we will work on a fix for this issue. Stay tuned.

**Comment by bvdalen** [comment]
Many thanks. Meanwhile a friend of mine looked at the problem and sees a solution. He will prepare a Pull request in the coming days.
