### ISSUE TITLE
urldate date format

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#1458]
JabRef version 3.3  on Linux Mint 17.3

Steps to reproduce:

1. In editor, move to "urldate" field. 
2. click popup date selector
3. select date (doesn't always work)
4. Inserted date has the format 2016.05.28
But with Biblatex, the format needs to be 2016-05-28, i.e., hyphens not points.

**Comment by simonharrer** [comment]
Could be a localization issue?

**Comment by wujastyk** [comment]
I'm not sure how to evaluate this, but it  could be a biblatex problem.

**Comment by simonharrer** [comment]
You should be able to change it in the preferences -> general tab using the timestampformat field. By default it is yyyy-MM-dd

**Comment by simonharrer** [comment]
I close this as it can be prevented through changing the preferences. Detecting which field the date selector is used and applying a format based on the specific field seems not that much of an improvement of the current situation.

**Comment by wujastyk** [comment]
Many thanks for pointing out how to use preferences to work around this
issue.

Best,
Dominik

--
Professor Dominik Wujastyk* <http://ualberta.Academia.edu/DominikWujastyk>
Singhmar Chair in Classical Indian Society and Polity
Department of History and Classics <http://historyandclassics.ualberta.ca/>
University of Alberta, Canada
