### ISSUE TITLE
Fetched DOI gets lost

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#1478]
JabRef version 3.3 on Windows 10

Steps to reproduce:

1. Having an entry without DOI. 
2. Edit entry, go to "General" click on "search DOI"
3. DOI is fetched properly and appears in the DOI field
4. Move Mouse Pointer to Entry-Table and click on a different entry
5. Go back to the Entry the DOI was fetched
6. The DOI is gone.
-> it seems to get saved only, if i click either the DOI field or another field of the entry after step 3.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in the latest version 3.4. Please try the latest build from http://jabref.org.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
@teertinker This should be fixed in the latest version 3.4. Please try the latest build from http://jabref.org.

**Comment by teertinker** [comment]
Thanks solved in 3.4! Next time I will check the most recent version first.
