### ISSUE TITLE
Build artifacts: JabRefSetup.exe should also contain version information

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#148]
Other build artifacts such as JabRef-2.80dev--snapshot--2015-09-09--b4302aa.jar have the version information in their name. That should also be done for the installer. Most software package installers have the version in the file name (see e.g., [syncthing](https://github.com/syncthing/syncthing/releases)).

**Comment by simonharrer** [comment]
copy {
            from("$buildDir/nsis/JabRefSetup.exe")
            from("$buildDir/nsis/JabRef.exe")
            into("$buildDir/releases")
        }

In the `build.gradle` file we have to reflect the change as well.

**Comment by stefan-kolb** [comment]
Correct, I was just testing this via CircleCI as I have no NSIS installation here :+1:

**Comment by stefan-kolb** [comment]
@simonharrer Is this working for ya?

**Comment by simonharrer** [comment]
Looks awesome! :-)
Am 15.09.2015 6:24 nachm. schrieb "Stefan Kolb" <notifications@github.com>:

**Comment by stefan-kolb** [comment]
:joy:
