### ISSUE TITLE
Mac OS X binary seems broken for JabRef 3.4 release

### ISSUE THREAD

**Issue by kojiyokota** [JabRef/jabref#1481]
I downloaded JabRef 3.4 binary from JabRef homepage and  tried to start Application by double click on El Capitan with java 1.8. The leftmost menu "JabRef" appears, but other menus don't appear and the program cannot be quitted.

At this stage, running 'ps ax | grep JabRef' gives 'path/to/JabRef.app/Contents/MacOS/JavaApplicationStub' so I tried to run it from the command line. Then it emits following stderr:
> JavaApplicationStub[3373:64431] Apple AWT Startup Exception: Cannot lock focus on image <NSImage 0x11bf59070 Size={0, 0} Reps=()>, because it is size zero.
> JavaApplicationStub[3373:64431] Apple AWT Restarting Native Event Thread

The program runs successfully if it is run manually by "java -jar path/to/JabRef.app/Contents/java/app/JabRef-3.4.jar".

**Comment by stefan-kolb** [comment]
@chochreiner Could you please have a look if you have some time?

**Comment by chochreiner** [comment]
the problem is most likely this commit 327b16452a83377e24e7966fedc1d3fc87d2b224 - I may find some time have a more detailed look at it later this week

**Comment by burkesquires** [comment]
I tried downloading the latest release and the development version and had the same problem. Run-in Mac OS 10.10.5. Both seemed to install fine but when opening no windows appears. it also would not quit and required a Force Quit.

**Comment by ryanpepper** [comment]
Have same problem on OS X 10.11.5

**Comment by chochreiner** [comment]
@koppor do you have a license for install4j so that I can test the build on OSX?

**Comment by simonharrer** [comment]
I sent you the JabRef license code.

**Comment by matthiasgeiger** [comment]
This issue should be fixed now. You can use a development Version from http://builds.jabref.org/master/ which should be working as expected.

**Comment by ryanpepper** [comment]
Great, thanks! New dev version works fine :)
