### ISSUE TITLE
Wrong number in groups

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#1482]
JabRef version 2.4 on WindowsXP (I know, I know..., but same thing happen in Ubuntu)

Some groups (not all) display a wrong number of entries. In my example, it's written 577 but it should be 38 (and 38 entries are well displayed). 
It also have error in "summer student", "International", "congrès-chris", "international"...

They are both dynamic groups, but many other dynamic groups are fine. I think is related to a regular expression with != 
(in this case, it is Note!=. )

![jabref](https://cloud.githubusercontent.com/assets/1063951/15828471/6954c112-2bdd-11e6-9e01-83a47de439a7.gif)

I could send the file, but in private, since it contains a lots of confidential information.

**Comment by melTr** [comment]
Thanks! Works perfectly in the dev version!

**Comment by bernhard-kleine** [comment]
Obviously not yet! I encountered the following this morning:
![grafik](https://user-images.githubusercontent.com/9216487/51669571-0dad7280-1fc5-11e9-9172-d3da3e79d954.png)
The entry was dragged to the group, the change to the library was properly saved, but the count remained zero.
JabRef 5.0-dev--snapshot--2019-01-23--master--c6a1fcbe3
Windows 7 6.1 amd64 
Java 1.8.0_201
