### ISSUE TITLE
HTML export handles some UTF characters wrong

### ISSUE THREAD

**Issue by ThomasA** [JabRef/jabref#1484]
JabRef 3.4 on Ubuntu 16.04

Steps to reproduce:

1. Copy and paste the following test entry into a new database in JabRef.
2. Make sure the database is stored as UTF-8 encoded (should be default).
3. Export the database and select the file type 'HTML (*.html)'
4. In the resulting HTML file, the character 'Ø' is displayed wrong in the Firefox browser.
![jabref](https://cloud.githubusercontent.com/assets/971307/15898282/f2d15c32-2d97-11e6-8242-70cb735d5b6a.png)
![firefox](https://cloud.githubusercontent.com/assets/971307/15898291/fef25d7c-2d97-11e6-8c51-415865b4759c.png)

This does not happen when exporting to 'Simple HTML', 'HTML list', 'HTML table', or 'HTML table (with Abstract and BibTeX)'.

**Comment by lenhard** [comment]
Thanks for the report!

@oscargus: What do you think about it?

**Comment by oscargus** [comment]
Sorry for late reply. My guess is that the export filter does not run the Unicode to HTML converter for unknown reasons, since it works for the other HTML variants. I will not have time this week to look more into it.

**Comment by Siedlerchr** [comment]
I tested a bit around and a simple workaround would be to set the charset in the html documents. When no one is set, it is treated default as ASCII (at least in FF)
For UTF8 it would be enough to add:
`<meta charset="utf-8" /> `
directly after the html open tag.
Then no escaping is necessary. 

Despite that, it seems that on Export no Formatter is run.

**Comment by oscargus** [comment]
I checked this a bit more now and @Siedlerchr is completely correct. The missing thing is the charset definition.

JabRef does not have a Unicode to HTML converter, only Unicode to/from LaTeX and HTML to/from LaTeX.

I'll soon be committing a fix, adding the charset.

**Comment by oscargus** [comment]
Ideally one should add the charset actually used for the file. However, this is not possible with the current export functionality as far as I can tell.
