### ISSUE TITLE
Export to MS Office 2007 (.xml) - ShortTitle missing

### ISSUE THREAD

**Issue by mafanie** [JabRef/jabref#1485]
JabRef version 3.4 on Windows 10

When exporting to MS Office 2007 (.xml) the short title information is missing in the generated xml file. As both bib files and MS Word when importing xml files support that information, this should be exported when available.

Steps to reproduce:
1. Input short title in bib file (`shorttitle = {...}`)
2. Export to MS Office 2007 (.xml)
3. Short title is missing in export (no `<b:ShortTitle> ... </b:ShortTitle>`)

**Comment by matthiasgeiger** [comment]
Thanks for your report!

JabRef is rather flexible in importing bib files with customized entries, i.e., you can define arbitrary fields (such as `shorttitle`) and they will be handled by JabRef. 
However, the exporters to a specific format can not deal with all information but generally stick to the default standard entry types with its standard (required and optional) fields as described in ftp://ftp.ctan.org/tex-archive/biblio/bibtex/contrib/doc/btxdoc.pdf.

**Comment by koppor** [comment]
Isn't shorttitle a feature of biblatex? : innocent:

**Comment by matthiasgeiger** [comment]
... yes it is mentioned in the biblatex reference http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf. But as `shorttitle` is not part of any entry type as "required" or "optional" is not supported as one of the standard types by JabRef. :wink:

But I just had a look in the code - the export of `shorttitle` to MsBib is intended to work - but only if the filed is prefixed as `msbib-` to `msbib-shorttitle`. So a quickfix for you @mafanie would be to change the field name to `msbib-shorttitle`.

**Comment by stefan-kolb** [comment]
There's obviously a standard field ShortTitle in Word, so we should map this to the biblatex field shorttitle if present?!

**Comment by matthiasgeiger** [comment]
@mafanie @stefan-kolb fixed the issue. You can download a development version from http://builds.jabref.org/master to test whether the problem is solved.

**Comment by mafanie** [comment]
Works as favored. Thanks a lot for the fast solution.
