### ISSUE TITLE
Currently broken on Mac OS X?

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#149]
A SF.net user seems to have problems with a build based on the master branch (see [here](https://sourceforge.net/p/jabref/bugs/1285/#39e3/a044)).

Should be definitely checked before the release of 2.80 **and** 2.11

**Comment by domwass** [comment]
I couldn’t even open the linked snapshot build for OSX (https://circle-artifacts.com/gh/JabRef/jabref/441/artifacts/0/home/ubuntu/jabref/build/releases/JabRef-2.80dev--snapshot--2015-09-08--ba867e8-OSX.zip). I am on Yosemite, 10.10.5. There is no warning, but JabRef does not open any file, and I only get the JabRef menu, but nothing more – and it is not possible to quit JabRef (only by killing the process). See attached Screenshot.
![Screenshot](https://cloud.githubusercontent.com/assets/2708770/9762318/fed2dd06-5702-11e5-9d74-44d30de1073d.jpg)

**Comment by koppor** [comment]
We tested on 10.10.4 with `Java(TM) SE Runtime Environment (build 1.8.0_20-b26)` and everything works fine. @domwass Which Java version do you run?

**Comment by koppor** [comment]
What is the command line result of executing `java -cp "JabRef.app/Contents/Java/*" net.sf.jabref.JabRefMain`?

**Comment by domwass** [comment]
java -version gives 

    java version "1.6.0_65"
    Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
    Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

But, strangely, in System Preferences it says that I have version 1.8.0_31.

Here is the output of 'java -cp "JabRef.app/Contents/Java/*" net.sf.jabref.JabRefMain':

    Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/jabref/JabRefMain : 
    Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by koppor** [comment]
Based on: http://superuser.com/a/555749/138868: `/usr/libexec/java_home -V` should ouput all Java versions. If you exec `/usr/libexec/java_home -v 1.8`, `java -version` should also point to 1.8.

**Comment by domwass** [comment]
'/usr/libexec/java_home -V' gives
   
    1.6.0_65-b14-466.1, x86_64:	"Java SE 6"	/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-466.1, i386:	"Java SE 6"	/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

Version 1.8 is not found on my machine. Has this maybe something to do with dropped Java 6 support on OSX? See https://support.apple.com/en-us/HT202643

**Comment by koppor** [comment]
It is very strange, that both the 32bit and the 64bit version are installed in the same directory.

As 8u50 is the current version, may I ask to install the most recent JRE from Oracle? The download should be available at http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html (Discovered starting from http://www.java.com/)

**Comment by domwass** [comment]
Still the same. It seems to me as if the newer Java version is somehow hidden from the system.

**Comment by matthiasgeiger** [comment]
There is a statement in the [general installation notes](https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jre.html):
> Installing a JRE from Oracle will not update java -version symlinks or add java to your path. To be able to do this, you need to install the JDK.

So you might install the **JDK** instead of the **JRE** (as `/usr/libexec/java_home -V`lists only JDKs) - the JDK is available here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Or as an alternative for using the JRE [there are some hints in the installation notes from Oracle](https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_preferences.html#BABHEJEC) what might help if you are still using Java 6.

**Comment by domwass** [comment]
Okay, I installed the JDK and now java 8 works. 

	java -version
	java version "1.8.0_60"
	Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
	Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

But still, opening JabRef does not give a main window. There are a lot of warnings (see below). Does this information help?

	Sep 23, 2015 2:55:35 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "MIS Quarterly" for locale de
	[Information on opening bib files snipped]
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Open %0 file" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "JabRef Hilfe" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Hilfe - Inhalt" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Über JabRef" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Eintrag bearbeiten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Tastatur-Fokus auf die Tabelle setzen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Datei speichern" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Datei speichern unter ..." for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Auswahl speichern unter ..." for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Ausgewählte Einträge als reines BibTeX speichern …" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Rückgängig" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Wiederholen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Vor" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Zurück" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Löschen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Einträge markieren" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Markierung aufheben" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Relevanz ein-/ausschalten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Qualität ein-/ausschalten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Druckstatus umschalten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Weitersuchen (bei direkter Suche)" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Suchen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Suchdialog ein-/ausblenden" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Inhalt einer BibTeX-Datei an die aktuelle Datei anhängen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Präambel bearbeiten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Strings bearbeiten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Gruppenansicht ein-/ausblenden" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Eintragsvorschau ein-/ausblenden" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Gruppen markieren, die mindestens einen der selektierten Einträge enthalten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Gruppen markieren, die alle selektierten Einträge enthalten" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "BibTeX-Keys automatisch generieren" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Schreibe XMP-Metadaten in die PDFs, die mit den ausgewählten Einträgen verlinkt sind." for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Ordner öffnen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Datei öffnen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "PDF oder PS öffnen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "URL oder DOI öffnen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "SPIRES-Eintrag öffnen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Zeitschriftentitel der ausgewählten Einträge abkürzen (MEDLINE-Abkürzung)" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Zeitschriftentitel der ausgewählten Einträge abkürzen (ISO-Abkürzung)" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Abkürzung der Zeitschriftentitel der ausgewählten Einträge aufheben" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Mit externer SQL-Datenbank verbinden" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Export in externe SQL-Datenbank" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Einträge aufräumen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Einträge zusammenführen" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Finde und entferne doppelte BibTeX-Keys" for locale de
	Sep 23, 2015 2:55:36 PM net.sf.jabref.logic.l10n.Localization lang
	WARNUNG: Warning: could not get translation for "Sucht nach nicht verlinkten PDF-Dateien im Dateisystem" for locale de

**Comment by stefan-kolb** [comment]
Maybe it is a problem with the Mac extensions not working with Java 8?

**Comment by matthiasgeiger** [comment]
At least the warnings can be ignored as they are just localization issues.

**Comment by domwass** [comment]
Could I do some further tests that might help?

**Comment by koppor** [comment]
We tried at another machine with the same Java version. Changing the language resulted in
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
 at net.sf.jabref.gui.preftabs.AdvancedTab.storeSettings(AdvancedTab.java:229)
 at net.sf.jabref.gui.preftabs.PreferencesDialog$OkAction$1.run(PreferencesDialog.java:263)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at spin.Invocation.evaluate(Invocation.java:175)
 at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
 at java.lang.Thread.run(Thread.java:745)
```
but this was not reproducible.

We tried to delete JabRef's preferences (following the [hints on stackoverflow](http://stackoverflow.com/questions/675864/where-are-java-preferences-stored-on-mac-os-x), but did not succeed yet).

i don't know, how much effort it is to create another account on your machine to ensure that JabRef starts with empty preferences. I currently don't know about other ways to reset the preferences.

**Comment by matthiasgeiger** [comment]
You could try to reset the preferences by calling Jabref the following way:
`java -jar JabRef-2.11b4.jar --prdef all -n`

And than start it normally again.

**Comment by domwass** [comment]
Thanks for the suggestion, I’ll try it later. I am trying to start the snapshot of 2.80 mentioned above, though. But I can test with 2.11b4 as well.

**Comment by matthiasgeiger** [comment]
Great! The most recent build is https://circle-artifacts.com/gh/JabRef/jabref/507/artifacts/0/home/ubuntu/jabref/build/releases/JabRef-2.80dev--snapshot--2015-09-23--0020692-OSX.zip - which should produce much less warnings ;-)

**Comment by domwass** [comment]
After opening with the command 'java -cp "JabRef.app/Contents/Java/*" net.sf.jabref.JabRefMain  --prdef all -n' it worked with the snapshot of 2015-09-08 as well as with the newer one of 2015-09-23. With both versions, it took a couple of seconds for the window to show up, though – with no bib files open as well as with a small one (only 1 entry) open.

**Comment by matthiasgeiger** [comment]
Glad to hear it is working again!
We should keep this in mind if other users have problems after updating to 2.11 or later versions.

@koppor Should we close this issue as you and also @domwass were able to run the latest JabRef builds on Mac OS X?

**Comment by stefan-kolb** [comment]
This doesn't solve the root cause of this problem, tho?

**Comment by koppor** [comment]
No, it does not. And now, we destroyed the bogus preferences. :see_no_evil:

**Comment by domwass** [comment]
As a follow up: It seems that I cannot store preferences anymore. What exactly does `--prdef all -n` do?

**Comment by matthiasgeiger** [comment]
It restores the default preferences. 

Is an exception showing up if you try to save your preferences?

**Comment by domwass** [comment]
Whenever I click on OK in preferences, nothing happens. There is no warning or error message. I can change the language setting, though, since there is no need to click on OK.

**Comment by domwass** [comment]
How can I get my old preferences back? I copied my backup of the file `net.sf.jabref.plist` to `./Library/Preferences` and started JabRef, but still the preferences are gone (i.e., the default preferences are used).

**Comment by matthiasgeiger** [comment]
I'm afraid if restoring does not work that you have to set the preferences manually :unamused: - is this still working for older JabRef versions?

**Comment by domwass** [comment]
No, unfortunately the preferences are also set to default for older versions. I will take this opportunity to clean up my preferences then … :wink:

**Comment by domwass** [comment]
@matthiasgeiger I would set my preferences manually, if it would work. But unfortunately, I can not change any preferences except the language setting. As I said, whenever I click on OK in the preferences pane, nothing happens. This is also the case with version 2.11b3. Any hints?

**Comment by matthiasgeiger** [comment]
Ahh... that is crap :disappointed: 

Unfortunately we cannot reproduce this issue as no one of the current developers is using a Mac. 

A weird workaround might be to use v2.10 to set the preferences which than can be used in v2.11bX

**Comment by koppor** [comment]
@domwass Could you start it using the terminal and `java -jar`? Then we might see some exceptions popping up. Alternatively, you could open "Help" -> "Show Errror Console" and then have a look at the Exceptions tab.

**Comment by domwass** [comment]
@matthiasgeiger I will try v2.10 later.
@koppor Error console says:
 
    Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.sf.jabref.AdvancedTab.storeSettings(Unknown Source)
	at net.sf.jabref.PrefsDialog3$OkAction$1.run(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Thread.java:695)

**Comment by matthiasgeiger** [comment]
Okay... I think I got it. 

There is no "default look and feel" set for Mac OSX, therefore the (not visible for Mac OS X) dropdown box for selecting the LookAndFeel is empty and the NullPointerException is caused by the `toString()` call in `preferences.put(JabRefPreferences.WIN_LOOK_AND_FEEL, className.getSelectedItem().toString());`

What is the lookAndFeel to be used on a mac? 
`UIManager.getSystemLookAndFeelClassName()` or `UIManager.getCrossPlatformLookAndFeelClassName()` (== metal)?

**Comment by matthiasgeiger** [comment]
I just added `UIManager.getSystemLookAndFeelClassName()` as the default value in the prefs.

@domwass It would be great if you would check whether this solves the problem using this snapshot build: https://circle-artifacts.com/gh/JabRef/jabref/655/artifacts/0/home/ubuntu/jabref/build/releases/JabRef-2.80dev--snapshot--2015-10-08--2da8161-OSX.zip

**Comment by domwass** [comment]
Yes, this works – thanks. I can now change the preferences – and it also works in 2.11b3 again. 

Another problem that I encountered using the snapshot, though: I enabled the biblatex mode and left everything else as is. After closing and re-opening JabRef, the table is blank (white), although the data is there. (I attached a screenshot.) With 2.11b3 everything is fine.
![biblatex-mode](https://cloud.githubusercontent.com/assets/2708770/10366945/d5ba039a-6dcd-11e5-9366-e4a5d9cf2ca4.jpg)

**Comment by stefan-kolb** [comment]
@matthiasgeiger Can you backport your fix to 2.11 with reasonable effort? Trying to close the last issues for 2.11 final release on 10/31/15.

**Comment by matthiasgeiger** [comment]
Yeah, should be possible.

**Comment by matthiasgeiger** [comment]
Merged into master (https://github.com/JabRef/jabref/commit/7d07e3921fcae5326744de1152e67e88895055aa) and backported to dev2.11 in https://github.com/JabRef/jabref/commit/11d486cf477d39261a7375cb9854b8b1bb73e158.

**Comment by koppor** [comment]
@domwass The build can be retrieved from http://ge.tt/9Idc446

**Comment by domwass** [comment]
@koppor Thanks, I just did a quick test and it seems to work.

**Comment by matthiasgeiger** [comment]
Glad to here ;-) 
So let's try to close this issue again...
