### ISSUE TITLE
Broken When Open on Mac OS X

### ISSUE THREAD

**Issue by juanqinyang** [JabRef/jabref#1492]
After install the package download from [http://www.fosshub.com/JabRef.html](), It's blank! I only get the JabRef menu, and it is not possible to quit JabRef (only by killing the process). 

I am on Yosemite 10.10.5., and the java version is 1.8.0_91.
`java version "1.8.0_91"`
`Java(TM) SE Runtime Environment (build 1.8.0_91-b14)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
`

And I check my System Preferences, the version is also 1.8.0_91.

**Comment by matthiasgeiger** [comment]
Thanks for your Report! 

This issue has already been reported in #1481 and has been fixed. Please use a development build from http://builds.jabref.org/master

**Comment by matthiasgeiger** [comment]
Thanks for your Report! 

This issue has already been reported in #1481 and has been fixed. Please use a development build from http://builds.jabref.org/master

**Comment by juanqinyang** [comment]
@matthiasgeiger Thanks so much!! It works now!!
