### ISSUE TITLE
Broken JabRef 3.4 OSX Installer

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#1493]
JabRef version 3.4 on OSX 10.11.5

Steps to reproduce:

1. Download Version 3.4 Installer for OSX from http://www.fosshub.com/JabRef.html.
2. Install on "clean" system with no pre-existing JabRef installation.  Install to /Users/jkulesza/JabRef (default location proposed by installer).  Deselect "Create a desktop icon", keep "Add to the dock" selected. Deselect association with .bib files. Keep "Run JabRef" selected.
3. Installation appears to complete successfully.  

However, the icon that is added to the dock has the default icon (see below).  Upon launch, only a basic application menu is shown (see below).

Note that through the application menu JabRef cannot be quit, nor does Command-Q work.  The application must be "force quit" through the activity manager.

Note also that following the same process for the 3.3 installer works as expected.

<img width="113" alt="screen shot 2016-06-12 at 9 16 00 am" src="https://cloud.githubusercontent.com/assets/9939059/15991960/4f1207ec-307e-11e6-9093-241d68ec97ee.png">

<img width="228" alt="screen shot 2016-06-12 at 9 16 25 am" src="https://cloud.githubusercontent.com/assets/9939059/15991964/5f413a48-307e-11e6-9efd-e63dff66aaf8.png">

**Comment by stefan-kolb** [comment]
Thanks for your report! Please see #1492. The issue has been fixed lately.
