### ISSUE TITLE
"3rd" in Filename Gets LaTeX-corrected, Causes File Rename to Fail

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#1494]
JabRef version 3.3 on OSX 10.11.5

Steps to reproduce:

1. Create a new database.
2. Create a Book entry.
3. Add a file named "test 3rd edition.pdf" to General->File.
4. Specify Required Fields -> Title of "Test 3rd Edition".
5. Create BibTeX key of Book____Test3rdEdition (or similar).  
6. Perform cleanup with options shown below.

The file in the Fields -> Title will be changed to specify a superscript for 3rd.  **The file on the filesystem is not renamed in any way.**  Neither of these behaviors is expected.

Note that I attempted this with 3.4; however, I ran into installer problems (see https://github.com/JabRef/jabref/issues/1493).

![screen shot 2016-06-12 at 9 25 11 am](https://cloud.githubusercontent.com/assets/9939059/15992041/e1866a22-307f-11e6-9687-5ffe36dcb66a.png)

<img width="265" alt="screen shot 2016-06-12 at 9 25 48 am" src="https://cloud.githubusercontent.com/assets/9939059/15992044/ec6fc87a-307f-11e6-83cc-d73c4cdbb9b7.png">

<img width="534" alt="screen shot 2016-06-12 at 9 25 54 am" src="https://cloud.githubusercontent.com/assets/9939059/15992046/f21d6e9e-307f-11e6-9f43-8f129afed290.png">

**Comment by jkulesza** [comment]
Testing with 3.5, this appears to be fixed.

**Comment by simonharrer** [comment]
Thanks for documenting this fix. :+1:
