### ISSUE TITLE
FullText Download Dialog only shows doc for latest selected entry if multiple times triggered

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1496]
JabRef 3.4
windows 7 6.1 amd64 
Java 1.8.0_74

Steps to reproduce:
1. Database with 2 different entries
2. Hit Get Fulltext on entry 1 (e.g. ABC)  -> Searching for Fulltext starts
3. Hit Get Fulltext on entry 2  (e.g. DEF) -> Searching for Fulltext starts 
4. Download Dialog appears: PDF is named after the second entry
5. Download Dialog appears a second time: PDF is named after the second entry
6. If you rename the second pdf, e.g. _2.pdf and look at its content: Different files

**Comment by stefan-kolb** [comment]
Hm, yeah this is expected. Is a thread problem...

**Comment by oscargus** [comment]
I happened to solve this (I think), when trying to enable full text search for multiple files. Please see #1869

**Comment by tobiasdiez** [comment]
@stefan-kolb, @oscargus what is the status of this bug? Is it indeed fixed with #1869?

**Comment by stefan-kolb** [comment]
I don't think so. If so only for the multi downloader action and not in general?!

**Comment by koppor** [comment]
The CHNAGELOG of 3.6 says it is fixed: https://github.com/JabRef/jabref/blob/master/CHANGELOG.md#changed-1

Maybe the changelog entry is too optimistic?

**Comment by Siedlerchr** [comment]
I think this is fixed, it now kinda queues the dls

Am 23.11.2016 1:49 vorm. schrieb "Oliver Kopp" <notifications@github.com>:

**Comment by Siedlerchr** [comment]
Solved. Works.
