### ISSUE TITLE
 { } braces in author/editor names are not treated correctly

### ISSUE THREAD

**Issue by mafanie** [JabRef/jabref#1499]
JabRef version 3.4 on Windows 10

Having a corporate as author (editor) and inputting it in Jabref in curly braces (as mentioned in Section 2.3.3. of the manual of the biblatex package) Jabref should recognise this and display it in the entry table accordingly.

For normal entries (forename and surname) there is already some recognition, because only the surname is shown. This should be expended to corporates.

This bug is related to #1497, which concerns the export of such corporates, while here the display inside Jabref is concerned.

![image](https://cloud.githubusercontent.com/assets/19827673/16057666/69b2fddc-327b-11e6-909a-e0a6a39a0bf4.png)

**Comment by matthiasgeiger** [comment]
Thanks for your report! 

I just confirmed that this is not working as expected. It was working in earlier versions of JabRef (might be introduced by #1282 - but have not checked it, yet).

A kind of workaround: In *Options* > *Preferences* > *Entry Table* the author display style for the entry table can be configured. Using one of the first three option "Show names unchanged" or "Show firstname lastname" in combination with "Do not abbreviate names" displays the corporate author correctly - but of course this also has an impact on displaying all other authors, too.

**Comment by matthiasgeiger** [comment]
Same problem also for other names which are using braces - see #1528

**Comment by oscargus** [comment]
Just a minor note: `AuthorList` seems to parse this as well as `\relax` properly. I wonder where it goes wrong...

**Comment by oscargus** [comment]
There is a working version to be tested at http://builds.jabref.org/fix1499/

Turned out that the problem was very simple to solve. So simple that it was hard to find...
