### ISSUE TITLE
Rename a static group: Group entries are not updated accordingly

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#1500]
JabRef-3.4dev--snapshot--2016-04-29--master--694840a
on Windows 10

If you rename a static group, the group entries are not updated accordingly. Their "group" field will still contain the old group name (and NOT the new one).

Steps to reproduce:

1. Rename a static group
2. Articles/group entries won't be updated accordingly and are still assigned to the old (obsolete) group name

(might be related to this one: https://github.com/JabRef/jabref/issues/1434#event-691424400 ?)

**Comment by matthiasgeiger** [comment]
Thanks for your report!

I can confirm this behavior for JabRef 3.4 and also the current development versions: In the UI grouping still works (i.e., although the new group name is displayed, internally it is still searched for the old term and therefore the group entries are still found correctly) - however, in the serialization the old name of the group is used in the `groups` field.

**Comment by tobiasdiez** [comment]
Thanks for your report. The bug should be fixed now with https://github.com/JabRef/jabref/pull/1539.

**Comment by AEgit** [comment]
I can confirm: This bug has been fixed in the newest build "2016-07-13--master--304d280".

**Comment by tobiasdiez** [comment]
Thanks for the feedback!

**Comment by AEgit** [comment]
Thanks for the quick fix!
