### ISSUE TITLE
Newline deleted in JabRef 3.4 (but not JabRef 2.10)

### ISSUE THREAD

**Issue by gianlucabaldassarre** [JabRef/jabref#1502]
JabRef version JabRef 3.4 (not in JabRef 2.10) on Debian 8 Jessie

Steps to reproduce the problem:

1. Set JabRef so to have the field ''comment'' for the entrytype ''article''
2. Add to JabRef Options-->Set up general fields the following:
Additional-abstract:abstract
Additional-comment:comment
so you can easily read/edit the ''abstract'' and ''comment'' fields
2. Write text in the field ''comment'', and use some newline character (pressing the ''enter'' button on the keyboard)  to have a new line started, or empty lines
3. The newline (or empty lines) are regularly shown when you insert them
4. Problem: when you save and close the database, after you open it again the newlines are substituted with a space character
5. Also, if you insert a newline within the tab "Additional-comment:comment", and then look at the tab ''BibTex source'', the newline is not shown (for the field comment). Similarly, if you insert a newline within ''BibTex source'' tab, the newline is not shown if you look at the tab ''Additional-comment:comment''. This *without* saving the file: basically, inserting new line characters within the ''Additional-comment:comment'' tab deletes the newlines within the ''BibTex source'' tab, and viceversa.

Other tests I did, that are maybe useful to identify the bug:
1. The problem persists with the three options of Options-->Preferences-->File-->Newline separator (i.e., CR, CR/LF, CR)
2. The problem is not there using JabRef 2.10 (but is there also with JabRef 2.11.1)
3. Newline characters are treated normally without problems if you use them within the field ''abstract'' (within the tab ''Additional-abstract:abstract''); i.e. they correctly do not disappear from this field after saving, closing, and re-opening the database
5. If you insert newline characters in the database file using another text editor, they are shown regularly in JabRef. However, if you save, close, and reopen the file in JabRef they again are erroneously deleted.

Please help me with this problem, or suggest how to go around it, as I use JabRef to store comments on papers, and also other work activities, several time during the day and I am stuck to JabRef 2.10!    : (

I attach a file with 1 entry that can be used to see the problem (to use it, change the extension from .txt to .bib).

Thanks!
[JabrefNewlineBug.txt](https://github.com/JabRef/jabref/files/320249/JabrefNewlineBug.txt)

Gianluca

**Comment by lenhard** [comment]
Thanks for your detailed report!

Although I did not try to reproduce this (yet), it sounds very much like the problem originates from the [FieldContentParser](https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/bibtex/FieldContentParser.java). `abstract` and `review` are the only predefined fields that allow for newline content, but you can define more in your preferences.

Your problem might be solved by marking the new field explicitly as a non-wrapable field. Could you try to add your newly defined field `comment` in the preferences? Go to Preferences -> File -> Do not wrap the following fields when saving: -> Add `comment` (and don't forget to separate if from other fields via `;`).

**Comment by lenhard** [comment]
Related: #186

**Comment by gianlucabaldassarre** [comment]
Hello Lenhard,

Thanks a lot for your very useful indications on the use of newline ( new-line , new line , line ending , end of line , EOL, line break) in JabRef.

I confirm that in JabRef 3.4 if you set:
Preferences -> File -> Do not wrap the following fields when saving: --> Add  comment  (separated from other fields with a ; ) 
then the newlines are no more deleted from the comment field by JabRef, so the ``formatting'' of my notes is kept nice.

Also, thanks a lot for indicating that not only the ``abstract'' field but also the ``review'' field is a predefined field that allows the use of newline (i.e., newlines are not deleted from it): this allows the use of ``review'' instead of ``comment'' to write notes while avoiding to ask co-workers/students to do the manual setting above. 

I can now finally enjoy the new JabRef 3.4, wow! : )

Gianluca
