### ISSUE TITLE
Protect terms formatter not working when cleaning up entries

### ISSUE THREAD

**Issue by giacomociani** [JabRef/jabref#1503]
JabRef version 3.4 on Windows 10 64 bit

Hi all. This may just be me non understanding how the following is supposed to work. When I run "cleanup entries" with "run field formatter" enabled and "title: protect terms", it doesn't seem to work.

Steps to reproduce:

1. open new database and create an article with an unprotected  all capital letter in the title. For example "The LIGO detector"
2. run the entry cleanup with "run field formatter" enabled and "title: protect terms" listed.
3. LIGO doesn't get protected with braces.

Is this a bug or an expected behaviour?

**Comment by matthiasgeiger** [comment]
This is more or less expected behavior. The implementation of "Protect Terms" is currently not the best as it relies on an internal list of "terms" and is not automatically detecting things to protect. 

Therefore in a lot of cases the terms to protect have to be enclosed manually in curly braces.

**Comment by giacomociani** [comment]
I see... I misunderstood its functionality. Thanks for the prompt answer!

Giacomo
