### ISSUE TITLE
Normalize bibtex acts strangely

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#1504]
JabRef  version 3.3 or 3.4 Ubuntu 14.04
I use "normalize to Bibtex" quite often on manual entries. Before, the result was almost often correct. But in this version, I can't get it.

Paste those authors:
Cristina Bosoi, Mariana Oliveira, Rafael Ochoa Sanchez, Mélanie Tremblay, Gabrie TenHave, Nicoolas Deutz, Christopher F. Rose, Chantal Bemeur

Normalize to bibtex give : Cristina Bosoi, Mariana Oliveira, Rafael Ochoa Sanchez Mélanie Tremblay Gabrie TenHave Nicoolas Deutz Christopher F. Rose Chantal Bemeur
which make no sense and I have to add "and" between each name.

In version 2.10 or 3.2. It gave :
Bosoi, Cristina and Oliveira, Mariana and Sanchez, Rafael Ochoa and Tremblay, Mélanie and Gabrie TenHave and Deutz, Nicoolas and Christopher F. Rose and Bemeur, Chantal

**Comment by matthiasgeiger** [comment]
Thanks for your report!

I can confirm this behavior in JabRef 3.4 and the current development versions.

We are currently working on an improvement of the "Normalize to BibTeX" functionality (see #1181 and #1470).

**Comment by bruehldev** [comment]
I've added the possibility to normalize the comma separated names. Also i trimmed spaces of the names and separated the different syntax cases to enable more stability.
The related tests are in the test file.

**Comment by tobiasdiez** [comment]
@bruehldev is this fixed now?

**Comment by stefan-kolb** [comment]
What's the status here? This was never merged?!

**Comment by lenhard** [comment]
I just tested this in the current development version and the string:
```
Cristina Bosoi, Mariana Oliveira, Rafael Ochoa Sanchez, Mélanie Tremblay, Gabrie TenHave, Nicoolas Deutz, Christopher F. Rose, Chantal Bemeur
```
turns into 
```
Bosoi, Cristina and Oliveira, Mariana and Sanchez, Rafael Ochoa and Tremblay, Mélanie and TenHave, Gabrie and Deutz, Nicoolas and Rose, Christopher F. and Bemeur, Chantal
```
which is the desired result, as far as I can see. There is also a test case for exactly that in `NormalizeNamesFormatterTest`.

So this can be closed.
