### ISSUE TITLE
Keywords management works only with the comma as a delimiter

### ISSUE THREAD

**Issue by rvb-033** [JabRef/jabref#1507]
I am running V3.3 under windows 8 on an I5 computer.
For convenience and practical reasons I am using the semicolon (;) as a delimiter in the keywords list.
I specified it in the options/preferences/groups menu.
When I use the Keywords Management Tools, keywords are modified as instructed but the resulting keywords lists are re-compiled with a comma (,) instead of the semicolon (;).
Additional query : I feel strange to be prompted to specify the keywords delimiter every time I generate a group and to find the comma as a default value there. As it has been input in the options/etc., it should be "remembered" by the software...
Regards

**Comment by rvb-033** [comment]
Hello, tobiasdiez,
A I understand it, you modified the code to fix the issue. When and where will the patch be available, or would you like me to test it ?
Regards

**Comment by tobiasdiez** [comment]
Yes, I tried to fix it. It would be really helpful if you could try it out. The preliminary test build is available under http://builds.jabref.org/fix1507/.

**Comment by rvb-033** [comment]
I tested it. It works fine. Just one remark : the keywords lists are recompiled without the space that comes after the semicolon, but this does not seem to cause problems.
This version is still too slow due to the group management issue (my database is 7000 records and has tree groups). Suggestion : if you can, try to update the groups upon operator request instead of automatically. It is less elegant but would be more efficient.
Thanks for your help,
Regards

**Comment by tobiasdiez** [comment]
Thanks for testing. Yes you have to specify the semicolon as well as the space as a separator, i.e. `>; <`.

Will try to further improve the group performance.
