### ISSUE TITLE
On duplicate group names

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#1508]
In JabRef version 3.4:

If you create a group structure like this:
```
Asthma
    Treatment
Diabetes
    Treatment
```
And then assign an article to the group _Treatment_ under _Asthma_ it will also appears in the other _Treatment_ group. 

I guess this is a bug? 

If group names should be unique (regardless of the hierarchy), the above structure could be renamed like this:
```
Asthma
    Asthma.Treatment
Diabetes
    Diabetes.Treatment
```
However, I suggest that:

- Each group is identified by both its name and lineage, so that duplicate names are not allowed among sibling groups but are allowed elsewhere (just like file systems, so validation is needed when a group is created or moved). This would allow having simpler names in the above example without conflicts/ambiguity when assigning articles. 

- The [bibtex groups field](https://github.com/JabRef/jabref/issues/629) to include the complete-lineage name of every group, e.g.
`groups = {Asthma/Treatment, Diabetes/Treatment}`.

**Comment by lenhard** [comment]
Thanks for spelling this out so nicely, but the bug has already been reported in #1495.

So, I am closing this as a duplicate.
