### ISSUE TITLE
Autocompletion based on frequency of previous occurrences

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#1510]
Does it make sense to introduce autocompletion logic to suggest entries ranked by number of previous occurrences?  In this way, more common terms will be suggested ahead of alphabetically superior ones.  

For example, assume I have two Journals in my database: Journal of Medical Physics (50 Entries), Journal of Medical Biophysics (2 Entries).  As I type Journal...of...Med... the Biophysics journal will be suggested for autocompletion due to its alphabetic superiority; whereas it is much more likely I'll be entering that of Physics and so it should come up first.

**Comment by stefan-kolb** [comment]
Autocompletion needs a complete rewrite. We will consider your request when working on this topic.

**Comment by tobiasdiez** [comment]
If we would want to implement your suggestion, we would need to completely rewrite the logic underlying the autocompletion. Right now we only track possible solutions but not how many occurrences it has. 

With the recent changes to the autocompletion feature, it should be easier to select between multiple suggestions. Moreover, your suggestion is probably only really useful for journals.

Thus, although I really like your feature suggestion, I have to mark it as "wont-fix".
