### ISSUE TITLE
Global search broken in 3.4

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#1512]
JabRef version <3.4> on <Ubuntu 16.04>  OpenJDK

Steps to reproduce:

1. Have multiple bib files open
2. go to file 2 search for a term that is also present in file 1  (no special options)

the following happens usually - either using filtered or highlighting mode : 
![image](https://cloud.githubusercontent.com/assets/8830305/16331961/a815ca1c-39f3-11e6-8b7d-78caddea08ee.png)

closing the window and just do a second global search gives the correct results:

![image](https://cloud.githubusercontent.com/assets/8830305/16331972/be4be794-39f3-11e6-96bf-2042592e7847.png)

sometimes even a second search does not work, so i have to go to each bib file and enter the search term every time.

**Comment by simonharrer** [comment]
Does JabRef 3.3 work correctly?

**Comment by matthiasgeiger** [comment]
Thanks for your report.

I cannot reproduce this behavior with JabRef 3.4 (on Win10). 

In your first screenshot the title of the opened search window indicates that no global search has been performed but a search in a single bib file. 

What is your exact workflow? 
After entering the search term you click on "Global suchen" (or "Search globally")? Or are you using a shortcut?

**Comment by teertinker** [comment]
Thank you very much @matthiasgeiger! Its a bit embarrassing, since I am using JabRef for so long. Apparently, I was clicking the "Pop search out" symbol from time to time and didn't realise that its not for global search. A careful read of the window title would have directed me to the failure.
