### ISSUE TITLE
Autocompletion not updated after import

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1514]
JabRef version latest dev on Windows 10

Steps to reproduce:
1. Import an entry (via --importToOpen), say with "test" as author
2. Author information in this entry is not used to update the search autocompletion. That is, searching for `tes` does not provide the autocompletion option `test`.

**Comment by stefan-kolb** [comment]
I'd vote for removing the autocompletion entirely for now...

**Comment by koppor** [comment]
I partially like it. Disabling is OK for me, but I'd like to keep it!

Am 09.02.2017 11:37 schrieb "Stefan Kolb" <notifications@github.com>:

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
