### ISSUE TITLE
broken umlauts in "about JabRef" window

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#1515]
JabRef version 3.4 on Gentoo Linux

Steps to reproduce:
Open About Jabref in the menu.
see screenshot
![2016-06-26_jabref3 4_about](https://cloud.githubusercontent.com/assets/298682/16362751/0933965c-3bb7-11e6-9d9f-a9dfd1072f51.png)

**Comment by koppor** [comment]
This is a dublicate. Maybe you can find it when searching for gradle in the
issuea.

(excuse brievety, using FP2 on the road)

**Comment by jonasstein** [comment]
@koppor thank you. I found it in #1178 I close the bug here.
