### ISSUE TITLE
typo Isbn -> ISBN

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#1516]
JabRef version 3.4

Isbn should be ISBN (https://en.wikipedia.org/wiki/International_Standard_Book_Number)
Doi should be DOI (https://en.wikipedia.org/wiki/Digital_object_identifier)

see screenshot
![2016-06-26_jabref3 4_isbn](https://cloud.githubusercontent.com/assets/298682/16362770/a670ac98-3bb7-11e6-96d9-03abe133ba93.png)

**Comment by koppor** [comment]
URL, URI, ISSN are also candidates for other casing.

Maybe we should display the fields as we currently write them out:
everything in lower case.

Would that also be fine with you?

isbn, doi, url

**Comment by jonasstein** [comment]
Why not write it in their correct spelling? I am not in the development team, so I do not have the right to decide about spellings, but to my understanding it would be very logical to write things as they are written. Please correct me, if I miss some obvious point here. Best regards, Jonas

**Comment by lenhard** [comment]
Implemented and merged with #1589
