### ISSUE TITLE
ISBN2BibTex  adds the word "Seiten"  in Biblatex pagetotal number 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1519]
JabRef version 3.4  Windows 7 x64

ISBN2BibTex fetcher includes the word "Seiten" in pagetotal.

Sample ISBN:
978-0131873216

In the pagetotal field, I get "988 Seiten".
It should be only the number.
Quote from BibLaTeX manual:

> pagetotal
> field (literal)
> The total number of pages of the work

**Comment by simonharrer** [comment]
Hm, maybe this is related to the external service.

**Comment by Siedlerchr** [comment]
Yeah, that seems to be related to  the Ebook.de API.
I maybe find some time to look into that.

**Comment by Siedlerchr** [comment]
Like I thought, it is already included in the Bib(la)tex response from the ebook.de API.
@koppor  Do you know who is responsible for the API from ebook.de?

**Comment by koppor** [comment]
I contacted Oliver from @freiheit-com. Let's see.

**Comment by stefan-kolb** [comment]
@koppor Any news on this topic?

**Comment by koppor** [comment]
I wrote them a reminder email just now.

**Comment by oscargus** [comment]
If it is not solved externally, I would suggest adding a simple replace before 3.6 is released.
