### ISSUE TITLE
Promote discourse.jabref.org

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1521]
- [x] README ~~with a badge~~
  - badges for discourse seem not to be available
- CONTRIBUTING.md as we would like users to participate there
- [x] Alter issue-template so that features and enhancements can be discussed in "To propose new features and enhancements please use http://discourse.jabref.org/c/features"
- Add label for issues which have a discourse thread attached?

**Comment by mlep** [comment]
I have just noticed that the mailing lists are still mentioned in http://www.flosscoach.com/index.php/communication-jabref#mailing-lists

**Comment by matthiasgeiger** [comment]
@koppor can you edit this information?

**Comment by koppor** [comment]
@igorsteinmacher Can you take care?

**Comment by matthiasgeiger** [comment]
Should we integrate a link "Online forum" in the "Help" menu?

**Comment by simonharrer** [comment]
With the icon https://materialdesignicons.com/icon/forum?

**Comment by matthiasgeiger** [comment]
Potentially... but I don't think this is really needed in the menu if it is not used anywhere else. But using the icon doesn't hurt, though ;-)

**Comment by stefan-kolb** [comment]
Any more work to do here or are we good for now?
