### ISSUE TITLE
Localisation: 

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#153]
### About Persian localization:
Persian files are currently in the directory <https://github.com/JabRef/jabref/tree/master/src/main/resources/resource>.
They should be in the directory <https://github.com/JabRef/jabref/tree/master/src/main/resources/l10n>.

### About Chinese localization:
There was a recent update of 2 files in the master branch:
<https://github.com/JabRef/jabref/blob/master/src/main/resources/l10n/JabRef_zh.properties>
and
<https://github.com/JabRef/jabref/blob/master/src/main/resources/l10n/Menu_zh.properties>
Could this update could be "copied" to branch dev_2.11, so as to be included in the next beta release?

**Comment by matthiasgeiger** [comment]
Done. :wink:

**Comment by mlep** [comment]
Thanks!
