### ISSUE TITLE
Translation for JabRef 3.5

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1533]
@JabRef/translators @oscargus

JabRef 3.5 is planned for release in a few days.
So, it is time for us to tidy up the localizations!

I have just updated the translation status of each file (https://github.com/JabRef/jabref/wiki/Translating-JabRef), so you can quickly grasp which files you should pay attention to (https://github.com/JabRef/jabref/tree/master/src/main/resources/l10n). 

Thanks for keeping JabRef multi-lingual!

**Comment by lenhard** [comment]
I guess since v3.5 is release now, we can close this issue.
