### ISSUE TITLE
Automatic update without inet connection freezes JabRef

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1540]
As explained in https://github.com/JabRef/jabref/issues/1425#issuecomment-229128390 and https://github.com/JabRef/jabref/issues/1425#issuecomment-229157628 there might be a problem with the new automatic update functionality if the user has no connection to the internet.

**Comment by koppor** [comment]
Tested on Win10 with a JabRef without large Groups. No freeze.

**Comment by matthiasgeiger** [comment]
I'll close here as the problems mentionend in  #1425 are not caused by the update mechanism.
