### ISSUE TITLE
Bad web search error messages 

### ISSUE THREAD

**Issue by Braunch** [JabRef/jabref#1542]
The web search gives inconsistent, wrong or no feedback, when trying to fetch without being connected to the internet. 

Steps to reproduce:

1. Disconnect from the internet
2. Enter something into the web search text field
3. Press fetch 
4. Enjoy flickering windows and exceptions depending on the selected search portal

The error messages should be consistent and tell the user what went wrong.

**Comment by Siedlerchr** [comment]
Maybe some of the Localised Error Messages from the Update-Checker can be reused here..

**Comment by Siedlerchr** [comment]
Further improvement  idea: Display HTTP Error Code (e.g. 403 Forbidden). That came up in #1583

**Comment by bartsch-dev** [comment]
As I just noticed #1523 addresses the same issue.
Therefore this or the other one should be closed and reference to the other one.
