### ISSUE TITLE
JabRef should focus opened file on startup

### ISSUE THREAD

**Issue by stachch** [JabRef/jabref#1547]
JabRef 3.4, windows 7 6.1 amd64, Java 1.8.0_92

Steps to reproduce:

1. Start empty JabRef
1. Open `publications.bib`
1. Close JabRef
1. Double click on `bibliography_c1.bib` in Windows Explorer
1. JabRef focuses `publications.bib`

![image](https://cloud.githubusercontent.com/assets/15067652/16564845/0e293104-420a-11e6-9f07-97f644545c85.png)

JabRef should focus `bibliography_c1.bib` instead

**Comment by matthiasgeiger** [comment]
Thanks for your suggestion. 

Just remembered that I also proposed this improvement in #1288. Thus, I'll close this as a duplicate.
