### ISSUE TITLE
Groups edit mode still present after restart

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1550]
JabRef version latest dev on Windows 10

Steps to reproduce:

1. Activate Groups Edit mode (under Groups Settings)
2. Deactivate it again, everything looks fine
3. Restart JabRef and edit mode is active again

By the way, what is the purpose of this edit mode??

**Comment by koppor** [comment]
[The help](http://help.jabref.org/en/GroupsHelp) talks about double clicking for edit mode.

What does your edit mode describe? Maybe, it is an ancient feature? Does git blame or a `gitk --all` on the Java class implementing that edit mode give some hints?

**Comment by lenhard** [comment]
This is just some rather old way of assigning entries to groups.

Will be removed with the migration to the new group feature in JavaFx. We have drag and drop functionality for assigning entries to groups.

**Comment by matthiasgeiger** [comment]
Additional note regarding usability: For assigning multiple entries sequentially in one group using "ctrl" while clicking on the entries to add allows for multiple selection.

**Comment by koppor** [comment]
Refs #1438

**Comment by m-rasheed** [comment]
I'm a windows user. I installed Jabref version 3.8.1 from the website https://www.fosshub.com/JabRef.html couple of days ago. I have the same problem described in the question above. What is the solution for this?

**Comment by tobiasdiez** [comment]
There is no real solution for the moment. We plan to rewrite the groups interface and in the process fix this issue. You might have luck and resetting the preferences may fix it for you.

**Comment by m-rasheed** [comment]
@tobiasdiez  Reseting the preferences solved the problem for me!

**Comment by tobiasdiez** [comment]
The edit mode is now completely removed.

**Comment by zhangkmsjtu** [comment]
I have the same problem described in the question above. 
Jabref 3.8.2
win7 64

Steps to reproduce:

    Activate Groups Edit mode (under Groups Settings)
    Deactivate it again, everything looks fine
    Restart JabRef and edit mode is active again

**Comment by lenhard** [comment]
@zhangkmsjtu Have you tried to reset the preferences as suggested above? Also, as written above, the mode is removed in the next version.
