### ISSUE TITLE
Add Fieldformatter for splitting title on Colon in title and subtitle

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1553]
JabRef 3.4

It would be nice to have a formatter which splits the Title on Colon into title and subtitle.
Example: 
`  title         = {Thumbs Up?: Sentiment Classification Using Machine Learning Techniques},
`
should become:
 ```bibtex
 title         = {Thumbs Up?},
 subtitle      = {Sentiment Classification Using Machine Learning Techniques},
 ```

**Comment by lenhard** [comment]
Just a thought on that: This suggestion goes somewhat beyond what formatters can do at the moment. Currently, formatters take a string (typically a field value) and transform it into another string. Your suggestion would need to operate on a complete entry, not just a single field.

We would have to rework the current formatter framework to get this working (some work, but might be worthwhile).

**Comment by Siedlerchr** [comment]
This is not that important for me. I think it is more related to the biblatex-style formatting.
I would therfore close that issue.

**Comment by oscargus** [comment]
But it can be added as a cleanup action.

**Comment by nkralpy** [comment]
A remark just in case this is ever re-opened again. Several journal article titles have colon in their title. So if at all this feature is added, there should be an escape option to use a colon when necessary.
