### ISSUE TITLE
Import dialog hidden behind main window

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1554]
JabRef version latest dev (but also previous versions) on Windows 10

Steps to reproduce:

1. Open JabRef
2. Open another program which is now in the front
3. Import some entry into JabRef using the cmd line option (e.g. using JabFox)
4. JabRef gains focus. However, the opened import dialog is hidden behind the main window.

**Comment by Siedlerchr** [comment]
Same applies when using the fetcher.

2016-07-07 20:18 GMT+02:00 Tobias Diez <notifications@github.com>:

**Comment by matthiasgeiger** [comment]
http://stackoverflow.com/questions/309023/how-to-bring-a-window-to-the-front

**Comment by matthiasgeiger** [comment]
As the fix is even simpler I won't open a PR for this but directly fix it in master.

The ImportInspectionDialog has not set the JabRefFrame as its owner...
