### ISSUE TITLE
OSX: A meaningful error message should be displayed if the wrong JRE is installed.

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#157]
If the user has not yet installed the JVM from Oracle, JabRef just displays a dialog saying “JRELoadError”, which is not really explicit about the problem.

**Comment by stefan-kolb** [comment]
I don't think we can handle this in our application. Looks like it is OSX-specific.
What we can do is add an entry to the Wiki/FAQ for OSX.

**Comment by stefan-kolb** [comment]
We can possibly prevent this if we bundle the JRE with install4j.

**Comment by simonharrer** [comment]
Install4j would also print a message that it cannot find a jre when it has no bundle and the system has no jre installed
