### ISSUE TITLE
JabRef app hangs on startup

### ISSUE THREAD

**Issue by sirpercival** [JabRef/jabref#1578]
JabRef version 3.4 on Mac OS X 10.11.5

Steps to reproduce:

1. Download and install JabRef 3.4 for Mac.
2. Double click on the JabRef application icon, or attempt to open a .bib file by double-clicking.

When I do this, JabRef doesn't open any windows. It just sits there, and doesn't respond to anything. I have to force quit.

If I run the .jar file from the command line with `$ java -jar JabRef-3.4.jar` it opens fine.

In my console, I get the following Java-related events:

    JavaApplicationStub[7632]: Apple AWT Startup Exception: Cannot lock focus on image <NSImage 0x1001ee730 Size={0,0} Reps=()>, because it is size zero.
    JavaApplicationStub[7632]: Apple AWT Restarting Native Event Thread

Any suggestions? I'd like to be able to run this the normal way... I can make an Automator script to run it via the shell, but I think that hurdle shouldn't be necessary.

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that it is #1481 and is already fixed.
Please use a development build from http://builds.jabref.org/master

We leave this issue open until the next release to keep other users reporting the same issue.

**Comment by catasaur** [comment]
Just to let you know - I had the same problem with the same versions of Jabref and Mac OS X, and the following development build starts successfully for me:

JabRef_macos_3_5dev--snapshot--2016-07-13--master--190497d .dmg
