### ISSUE TITLE
Improve installer

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1580]
After using the installer for the first time since ages, I noticed few points which could/should be improved:
- [ ] One needs to grant admin rights to the installer two times: directly at the start and also for running the uninstaller of the previous version
- [x] the "install4j" text near the dark gray rule in the picture below should be replaced by JabRef (or remove it completely)
- [ ] maybe decrease installer size by removing (unnecessary) libs

![untitled](https://cloud.githubusercontent.com/assets/5037600/16814127/b5d03afc-4934-11e6-9cb8-b6bef528f1a5.png)

**Comment by stefan-kolb** [comment]
I don't know if your first bullet point cannot be solved. We need to request (or want to) the same privileges for the uninstaller as for the installer. This is handled by the uninstaller, so we can probably not pass this on.

I removed the install4j watermark completely in both installer and uninstaller.

**Comment by simonharrer** [comment]
To reduce size, we could remove unused .class files, as we mostly only use a few classes from our dependencies. This requires some work with gradle, and as JabRef only requires 25 MB, I do not see the point in investing the time.

**Comment by stefan-kolb** [comment]
I don't see any real possibility to resolve the remaining two items.
For a) I don't think install4j supports this as installer and uninstaller are two separate entities in the chain
and b) decreasing installer size can only be achieved reasonably by removing some dependencies completely. If this is possible this can be done on a per item basis in a concrete PR.

Therefore, I vote for closing this issue if none of the @JabRef/developers has any further ideas.
