### ISSUE TITLE
LibreOffice: wrong numbers in citation labels

### ISSUE THREAD

**Issue by dliessi** [JabRef/jabref#1592]
JabRef version 3.5 on Mac OS X 10.11.5.
LibreOffice 5.1.4.2.

Steps to reproduce:

1. Connect to LibreOffice text document.
2. Select style Default [number].
3. Insert twice the same citation.
4. Click on the update button.

Expected result:
> [1] [1]

Actual result:
> [1] [1; 2]

Example bibliography:
```
@Article{A,
  author  = {A},
  title   = {A},
  journal = {A},
  year    = {2016},
}
```

Screenshot:
![testjabref](https://cloud.githubusercontent.com/assets/5209500/16888553/0bc9600c-4ae1-11e6-8672-8ae4602e4795.png)

**Comment by oscargus** [comment]
There is a version that should fix this at http://builds.jabref.org/fix1592/ (in 15 minutes or so). Please try it out.

**Comment by dliessi** [comment]
It works as expected now.
Thanks for fixing it so quickly!
