### ISSUE TITLE
Database export in MySQL and PostgreSQL

### ISSUE THREAD

**Issue by Goldfinger2007** [JabRef/jabref#1598]
I have issues with the SQL exports under JabRef version 3.5

For PostgreSQL the steps to reproduce are:

1. I created groups in the groups interface
2. I used "file->connect to external SQL database" and connected successfully to PostgreSQL version 9.4 server localhost, username postgres serverType PostgreSQL
3. There are no entries exported in the table "entry_group". The table "entries" is filled, though.

For MySQL, the steps to reproduce are:

1. I connected with user: root, again localhost mySQL version 5.7.
2. It says: SQL connection established.
3. I click on File->Export to SQL database it says:

Could not export to SQL database for the following reason:
All parts of a PRIMARY KEY must be NOT NULL; If you need NULL in a key, use UNIQUE instead.

Any advise?

The bibliography file is here:

% Encoding: UTF-8

@Article{Hello2000,
  author  = {Testauthor},
  title   = {Blabla},
  journal = {Testjournal},
  year    = {2016},
  groups  = {Testgruppe},
}

@Comment{jabref-meta: databaseType:bibtex;}

@Comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:Testgruppe\;1\;;
}

**Comment by koppor** [comment]
We are reworking our completely database support at #1451 to support synchronization with different users at the same time. Thus, the import/export functionality will be gone and thus this issue too.

Please try the recent build available at http://builds.jabref.org/SharedDatabaseSupport/ and provide feedback at #1451. Would that be possible?

**Comment by Goldfinger2007** [comment]
Will do. You can close this issue.
