### ISSUE TITLE
Support decoding and encoding of LaTeX characters

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#161]
There is [latex2utf8](https://metacpan.org/pod/distribution/LaTeX-Decode/bin/latex2utf8), which source is https://github.com/fc7/LaTeX-Decode. The opposite is `LaTeX::Encode`.

We should think of including this in JabRef. Possible in the cleanup functionality.

See also  #160.

**Comment by koppor** [comment]
This is related with [sf bug #721](https://sourceforge.net/p/jabref/feature-requests/721/). It seems that this functionality is done during import and not at "Cleanup entries". The existing functionality should be checked with the one of `latex2utf8`. Then, one of it should be chosen and integrated at "Cleanup entries".

**Comment by oscargus** [comment]
I've browsed the code and (having written most of the current JabRef converter, in HTMLConverter), I'd say that the current one supports more characters (although there may be some missing which are worthwhile adding). Also, the current implementation supports converting from HTML.  I would assume that it should be possible to use the same table to do the reverse conversion.

**Comment by oscargus** [comment]
I started merging the missing characters that were present in latex2utf8 and will provide a PR in a few days.

**Comment by oscargus** [comment]
There's a huge list at http://www.w3.org/Math/characters/unicode.xml

**Comment by koppor** [comment]
The Unicode converter converts from Unicode to LaTeX and not vice versa, does it? Furthermore, it seems that it doesn't treat the `author` field

**Comment by oscargus** [comment]
Correct. It should be possible to do it the other way around as well similar to the export formatters XMLChars, RTFChars, and HTMLChars.

Especially, one would like to use the huge list in HTMLConverter for HTMLChars (and maybe XMLChars) as well. I think one major issue here is how to deal with `{\"{a}}` vs `\"{a}` vs `\"a` vs `{\"a}`, but looking at e.g. HtmlCharsMap, it seems like there is a solution for that in HTMLChars, so probably only a matter of converting the LaTeX commands in HTMLConverter to the same format as in HtmlCharsMap.

This is something that I have been thinking about, but so far not succeeded to find the time/motivation to do.

**Comment by oscargus** [comment]
There is also a class FormatChars that does Latex to Unicode, which could be extended to cover everything in HTMLConverter.

**Comment by oscargus** [comment]
With #841 there's a huge step towards having quite good conversion in both directions.

**Comment by koppor** [comment]
Refs #160

**Comment by koppor** [comment]
Refs #1013.

**Comment by tobiasdiez** [comment]
What is the status of this issue? It seems like both conversation direction are present as cleanup operations.

**Comment by oscargus** [comment]
Agreed. Of course, it can always be improved, but I believe it is one of the better conversions (apart from LaTeX).

**Comment by lenhard** [comment]
This issue can be closed thanks to the cleanup operations
