### ISSUE TITLE
Groups Panel closes when selecting different database

### ISSUE THREAD

**Issue by Braunch** [JabRef/jabref#1610]
JabRef version JabRef build from master 21.07.2016 on Ubuntu 14.04 and on Windows 8

Steps to reproduce:

When I...
1. Have two databases opened
2. I open the groups panel in the first one
3. I switch to the second db and open the groups panel too
4. I switch back to the first one (groups panel is still opened)
5. I switch to the second db
...then the groups panel closes without being manually closed by me.

**Comment by oscargus** [comment]
Have you checked the groups preferences? There may be some combinations there which causes the problem.

**Comment by Braunch** [comment]
I think I found the cause of the behaviour. The groups pane closes when the database that is opened has no groups defined. Makes kind of sense, since the user does not use groups in that db. But it does look weird and results in the entry table jumping around on the screen, although the user didn't intentionally close the groups panel. I even can imagine the use-case that a user did not use groups so far but now wants to group all his entries. When clicking to the next database to change it, the groups pane should not disappear.

**Comment by Braunch** [comment]
I just saw that this is an option you can set in the preferences:
![image](https://cloud.githubusercontent.com/assets/15339195/17101117/07d15448-5273-11e6-8041-fbe265546893.png)

So not really a bug, only a questionable option IMHO.

**Comment by simonharrer** [comment]
I would simplify this by removing these two options and either the group window is shown, or it isn't, depending on the group toggle status.
