### ISSUE TITLE
MedlinePlain Importer throws StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zellerdev** [JabRef/jabref#1612]
While trying to solve #1267 I found a bug in the MedlinePlain Importer. When I import a Medline .txt file a StringIndexOutOfBoundsException occurs.

JabRef version 
JabRef 3.5
linux 4.4.0-31-generic amd64
Java 1.8.0_92

Steps to reproduce:
1. Select more than one entry from the [PubMed](http://www.ncbi.nlm.nih.gov/pubmed) site .
2. Select "Send to File" and then choose "Medline" Format.
3. Open Jabref and select "Import into new database".
4. I get a StringIndexOutOfBoundsException shown on the console and no entries are imported.

**Comment by boceckts** [comment]
#1611
