### ISSUE TITLE
Installer adds install4j instead of JabRef icon for installed app

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1613]
![image](https://cloud.githubusercontent.com/assets/375693/17036002/9c3b8f04-4f8a-11e6-934f-9bb3a6a44545.png)

**Comment by Siedlerchr** [comment]
Confirmed on Win7, too.

2016-07-21 21:33 GMT+02:00 Simon Harrer <notifications@github.com>:

**Comment by stefan-kolb** [comment]
Is this in Apps& features?

**Comment by simonharrer** [comment]
There as well.

**Comment by stefan-kolb** [comment]
So also in the "Startmenu"?

**Comment by Siedlerchr** [comment]
@stefan-kolb  Nope. The icon in the start menu is the correct logo, both on Win7 and Win10

**Comment by simonharrer** [comment]
Hm, not fixed with the current master. Is probably something else that has to be set.

**Comment by simonharrer** [comment]
Sorry, I am mistaken. Was fixed.
