### ISSUE TITLE
Jabref websearch: Google Scholar shows no results on second pop-up menu

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#1639]
JabRef 3.5
windows 10 10.0 amd64 
Java 1.8.0_101

The Jabref websearch with Google Scholar does not show any results on the second pop-up menu
Steps to reproduce:

1. Set Web search in Jabref to "Google Scholar"
2. Copy "On the relationship between tooth shape and masticatory efficiency: a finite element study" into the Web search field
3. Fetch
4. One article is found
5. Tick the "Keep" box and click on "OK"
6. The second menu turns up: No entry to select is shown. The "Select all", "Deselect all", "Delete", "Generate now", "OK" and "Cancel" buttons are all shown as activable.

I guess this is the exact same problem as described in:
https://sourceforge.net/p/jabref/mailman/message/32485880/

I haven't had this problem with an earlier development version of Jabref 3.5 (JabRef-3.5dev--snapshot--2016-06-28--master--a24b544), but since I've upgraded I've encountered it now a couple of times. Can you confirm this issue?

**Comment by oscargus** [comment]
I can confirm it. Probably related to the email you found in that it is a consequence of Google Scholar changing format on the web page. Here it seems like they changed relative links to full links as the error message reads:

```

12:20:11.696 [JabRef CachedThreadPool] WARN  net.sf.jabref.importer.fetcher.GoogleScholarFetcher - Cannot download entry from Google scholar
java.net.UnknownHostException: scholar.google.comhttp
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_101]
```
so what was earlier a relative link `/...` is now a full link `http://...`.

**Comment by oscargus** [comment]
There will be a fix at http://builds.jabref.org/fix1639 in five or so minutes that you can try out.

**Comment by AEgit** [comment]
Thank you very much! Man, Jabref and its developers are just great - the more I'm using it, the happier I am I haven't switched to a (commercial) alternative!

**Comment by AEgit** [comment]
I can confirm that the bug has been fixed in:

JabRef 3.6dev--snapshot--2016-07-29--fix1639--e838541
windows 10 10.0 amd64 
Java 1.8.0_101

**Comment by oscargus** [comment]
Great! Thanks for the positive words and for reporting and checking it! Not always that it is solvable in five minutes/one line though. :-)

**Comment by AMHurrell** [comment]
Indeed thanks to everyone on the Jabref team for geting this very useful feature back up and running.  Nice one guys :-) 👍
