### ISSUE TITLE
Removal of layout-extension field in CustomExport 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1653]
While working on #1336 I noticed that in my opinion the extension field is not necessary.
In the code there are some checks to make sure we have` .layout`  field and that the field is not empty.
However, while one can theoretically enter text there, it does not make any sense as the extension is normally set by the selected layout file.
Before removing it, I just wanted to ask if there is maybe a (historical) reason for its existence...

![customexportextensionfield](https://cloud.githubusercontent.com/assets/320228/17279316/467d3ff6-5771-11e6-9c26-71a3b2553ecd.png)

**Comment by tobiasdiez** [comment]
Isn't the extension of the file I want so save? So for example if I create a custom BibToHTML exporter, then the extension will be `html`.

**Comment by Siedlerchr** [comment]
@tobiasdiez I guess you are right, it is obvious. I totally did not think about it :facepunch: :wink: (github has no facepalm emoticon)
