### ISSUE TITLE
Importing an entry, that were exported with BibTeXML format failed. 

### ISSUE THREAD

**Issue by tschechlovdev** [JabRef/jabref#1665]
JabRef version
JabRef 3.5
windows 8.1 6.3 amd64
Java 1.8.0_25

Steps to reproduce:

1. Select an entry in JabRef
2. Go to "File" and then select "Export"
3. Use "BibTeXML" as export format.
4. Import the exported entry into a new database

I get hte following warning:
"1. The character reference must end with the ';' delimiter."

And after that no entries were imported.

**Comment by tschechlovdev** [comment]
I think the reason for this is, that by the authors, the "," gets exported as "and &#44 ". So for example ``von Hippel, Eric`` gets exported as ``von Hippel and &#44 Eric ``. And then a SAXParser Exception is thrown, because after ``&#44`` is a ';' missing.

**Comment by boceckts** [comment]
I think the authors aren't escaped at all because with my test file I also found out that &#45, &#34 and &#39 are not escaped in the authors field. After adding a";" after each of these codes I was able to import my xml file.

**Comment by matthiasgeiger** [comment]
I think the field gets generally escaped correctly, but the `;` which marks the end of an HTML entity such as `&#44;` is stripped or interpreted as an delimiter between different authors.

**Comment by stefan-kolb** [comment]
Related to #1337?!

**Comment by matthiasgeiger** [comment]
Not only related but a duplicate ;-)
