### ISSUE TITLE
libreoffice inserting empty citation modifies following characters

### ISSUE THREAD

**Issue by lorenzolan** [JabRef/jabref#1667]
JabRef version <2.10> on <Ubuntu 16.04> with LibreOffice 5.1.4.2

Steps to reproduce:

1. Working on a LibreOffice document (with LibreOffice 5.1.4.2), with JabRef openoffice/libreoffice connection.

2. Insert empty citation (using button from the panel on the left) correctly inserts an empty citation at the cursor location; citation appears in the bibliography by clicking the "update" button, as expected.

3. However, the "empty citation" messes with the characters following it: (a) it is followed by a blank space (not a big issue); (b) it changes several characters further right to italics -- not the characters immediately following the empty citation, but leaving ca. 8 characters unmodified (this is really annoying).

4. NB this issue is not new to the recent versions of JabRef/Ubuntu/LibreOffice, I used to have the same problem with earlier versions. I use the "empty citation" as a workaround for unusual references (e.g. institutional authors which don't fit easily in the name-year pattern).

**Comment by matthiasgeiger** [comment]
Thanks for your Report! 

You said that you are using JabRef 2.10. Can you please check whether this is still an issue with the most recent Version 3.5?

**Comment by stefan-kolb** [comment]
@lorenzolan Can you please check whether this is still an issue with the most recent Version 3.5?

**Comment by lorenzolan** [comment]
The problem seems to be solved with Jabref 3.5
