### ISSUE TITLE
Biblatex mode should be a per-file setting

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#167]
Currently, a global setting controls whatever JabRef uses biblatex mode or not. It is however usual to use biblatex files parallel with older bibtex files. Thus I would suggest that the biblatex mode can be activated just for certain files (i.e. should be an option under the database settings).

Moreover, it would be nice to recognize the file type automatically when the file is opened. That is, instead of showing the "The following entry types are unknown"-dialog when biblatex entries are present, it would be better to ask the user if JabRef should activate biblatex mode for this file.

**Comment by bluebirch** [comment]
biblatex format can also be discovered based on certain fields (e. g. subtitle, journaltitle, location, etc), not only entry types.

**Comment by stefan-kolb** [comment]
An auto detection per file would also be good :+1:
