### ISSUE TITLE
Submission of a pull request: help file updated?

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1679]
Currently, when a pull request is submitted, default check boxes are included:

````
[ ]    Change in CHANGELOG.md described
[ ]    Tests created for changes
[ ]    Screenshots added (for bigger UI changes)
[ ]    Manually tested changed features in running JabRef
````

To better maintain JabRef, I suggest to add one more:
````
[ ]    Help file updated
````

**Comment by matthiasgeiger** [comment]
I generally agree with you - but I fear that this is seen controversial by my fellow @JabRef/developers :wink:

Writing/Updating documentation is a hard and time-consuming task not really liked by developers. (Moreover, developers are always writing eays to understand and easy to use self-explanatory stuff :wink:)

Adding the bullet point to the template could be done easily, but enforcing the update of help pages will be harder.

**Comment by oscargus** [comment]
I also think it makes sense, but maybe one shouldn't enforce it. Still good as a reminder though.

A related question: how are the translations synchronised? I mean, I can edit the English one, but how can we make sure that the translators are at least informed that there is something to change?

**Comment by oscargus** [comment]
Meaning: we can add the bullet, but maybe shouldn't enforce ticking it for the sake of continuing the development. Also, sometimes you do something, get some feedback and change it a bit, so writing documentation is something that you do not want to do in the first version anyway. And once you're done with the feature you just want to merge it...

**Comment by mlep** [comment]
Yeah: writing doc is boring, and the developers are not in the best position to write it.

Any idea for a mechanism to signal PRs that affect the doc?

@oscargus : currently, translations are not synchronized. To my knowledge, only the English help is maintained at the moment.

**Comment by matthiasgeiger** [comment]
Good idea! 

I'll create a new "label" `doc-update-needed` and add another bullet point to the PR template:
```
<!- indicate if documentation has to be updated using the label `doc-update-needed`, 
just tick this checkbox if no update is necessary/update has been performed -->
- [ ] Documentation status checked 
```

**Comment by matthiasgeiger** [comment]
Decision during DevCall: Developers should check whether documentation is affected. If documenation is outdated due to a PR an issue should be opened at the [help.jabref.org](https://github.com/JabRef/help.jabref.org) repo.

**Comment by matthiasgeiger** [comment]
Done in 8ea1ee0.
