### ISSUE TITLE
ooplugin: it shouldn't be permitted to cite a publication that doesn't yet have a bibtex key

### ISSUE THREAD

**Issue by jdpipe** [JabRef/jabref#1682]
When using Jabref with LibreOffice, I can insert a reference to an entry before assign a bibtexkey to the entry. When I do so, I get "[??]" in my document. If I then click the refresh (circular arrow) icon in the ooplugin sidebar, then I get a popup message in Jabref saying "your OpenOffice/LibreOffice document references the BibTexKey 'null', which could not be found in the current database".

I think it would be more helpful if such citations were barred from being inserted in the first place, since that is the best time for the user to fix the problem. Later they can only wonder pointlessly what the [??] was referring to.

Better still, a BibTexKey could auto-generated (and again every following time, if the user desired it)

"You are citing a publication with an empty BibTexKey. A key will automatically generated [OK] [Cancel]  [x] always do this in future"

Version:
JabRef 3.6dev--snapshot--2016-07-29--extractoobibdatabase--fba22d9
linux 4.4.0-31-generic amd64 
Java 1.8.0_91

**Comment by oscargus** [comment]
When working on another (code) enhancement related to the keys (#1676), I realized that in quite a few cases JabRef simply assumed that the key is set. This is clearly one of the cases causing actual issues. I'll have a look at it.

**Comment by oscargus** [comment]
You can try a test build in five minutes at http://builds.jabref.org/fix1682 (I'm usually not this quick, but now I was looking for a small thing to fix and this fit well.)

**Comment by oscargus** [comment]
Although the check box is a really good idea, it was a bit too much of a hassle to fix it right now.

**Comment by jdpipe** [comment]
I tried it, worked fine. Thanks, Oscar!

**Comment by oscargus** [comment]
Fixed in #1683
