### ISSUE TITLE
"Month" field ascending/descending sorting swapped

### ISSUE THREAD

**Issue by giacomociani** [JabRef/jabref#1687]
JabRef version 3.5 on Windows 10 64-bit

When sorting according to "month", "ascending"/"descending" are switched.

For "year", for example, descending order results in later years at the top, as expected.
For "month", however, descending order results in January at the top, and December at the bottom, which is inconsistent.

This affects both the main view and the order in which the entries are saved (if a custom save order based on the "month" filed is specified in the database properties).

**Comment by oscargus** [comment]
Looking at the code it reads:

``` Java
        if(fieldType == FieldType.MONTH) {
            /*
             * [ 1598777 ] Month sorting
             *
             * http://sourceforge.net/tracker/index.php?func=detail&aid=1598777&group_id=92314&atid=600306
             */
            multiplier = reversed ? 1 : -1;
        } else {
            multiplier = reversed ? -1 : 1;
        }
```

so something special is happening for month. However, that link is not leading anywhere as the sourceforge bug tracker is disabled for JabRef.

Should be quite easy to fix though.

**Comment by stefan-kolb** [comment]
Link just says that month sorting was not working. I also tested it and my month sorting doesn't work at all...

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `month-sorting`. Please try the latest build from http://builds.jabref.org/month-sorting.

**Comment by giacomociani** [comment]
Works fine now! Thanks.
