### ISSUE TITLE
Improve shared database feature

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1703]
Follow up of #1451

- [x] Database properties dialog:
  - [x] Do not show "Save sort order" - database sorts arbitrarily :innocent: 
  - [x] Do not show "Database protection" - makes no sense in a shared database setting
- [x] Session restore: JabRef should open all `[shared]` tabs after startup
- [x] Store last used connection in the "open remote database dialog"
- [x] "open remote database dialog": "Connect" button should be disabled an label change to "Connecting...". Reason: Connection may take longer and pressing the button multiple times leads to error message dialogs. (You know, http://www.freemysqlhosting.net/ latency)

**Comment by Siedlerchr** [comment]
- [ ] Use `AssumeTrue(DevEnvironment.isCIServer())`  switch to disable database tests locally. Prevents failing tests, if no db is running locally.

**Comment by koppor** [comment]
Alternative solution: #1705 to make it explicit when to call the database tests. I know that one can also run the tests using the ide, but I would like to keep the consistency with our integration tests. Please follow up at #1705.

**Comment by obraliar** [comment]
This issue could be closed.
