### ISSUE TITLE
Improve ProtectedTermsFormatter

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1708]
As a follow up to https://github.com/JabRef/jabref/pull/1620 and https://github.com/JabRef/jabref/pull/1706, the ProtectedTermsFormatter code should be further improved:
- Remove usages of `setProtectedTermsLoader`. The loader is essential for the formatter to work and thus should be injected as a dependency through the constructor.
- Remove ProtectTermsFormatter from CleanupPreset. Protected terms should be handled similar to JournalAbbreviations by inserting the `ProtectedTermsLoader` into the constructor of the `CleanupWorker`. Reason: the `ProtectedTermsLoader` does not influence _which_ cleanup operations should be invoked (CleanupPreset) but _how_ these operations are executed (CleanupWorker).

**Comment by oscargus** [comment]
OK, then you can tell me how to do that considering the static initializer in https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/formatter/Formatters.java

**Comment by oscargus** [comment]
I'm sure you mean something else with CleanupPreset than https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/cleanup/CleanupPreset.java but I cannot figure out what right now. 

And I cannot really say that I still think the injection of JournalAbbreviationLoader in lots and lots of methods and classes is a good idea as such. For CleanupWorker it is injected in case someone would like to create a filename pattern using the journal abbreviation layout formatter. Removing support for that formatter will remove 80% of all the uses...

As long as we do not want to deal with that formatter explicitly in the code, I do not actually see how the second part should be done. So, again, please inform me (or solve it, I just removed a bug that practically rendered the Manage content selectors dialog useless for almost four months, which I correctly could have assigned you).

**Comment by tobiasdiez** [comment]
Regarding your questions:
- Simply don't use static fields. `List<Formatter> getConverters(arguments required to initialized them)` and similar for the other types. Static fields work great for static thinks, but the formatters can depend on the state (preferences) and thus are not static.
- I can't find the code I was thinking about. Can you please point me to the location where the ProtectTermsFormatter is initialized from SaveActions or when one runs a cleanup action?

**Comment by tobiasdiez** [comment]
The methods in question are marked as deprecated and thus hopefully their usage dies out over time.
