### ISSUE TITLE
Dragging entry into group

### ISSUE THREAD

**Issue by hudcap** [JabRef/jabref#171]
When I drag an entry into a group, the group window jumps to the top.

**Comment by matthiasgeiger** [comment]
Hi hudcap,
 I just tried to understand your problem but don't really get it...
The group view is a column in the left of the main window - so there is no explicit "group window" which can jump to the top.
Could please describe your problem in more detail?
Thanks!

**Comment by koppor** [comment]
Can't reproduce here. I opened the group view (which is probably meant by "group window"). I created a new group with static assignment. I dropped an entry on that group. The group view did not move to the upper part. The other views opened are "Search" and "Web search".

**Comment by hudcap** [comment]
Sorry it wasn't clear.
I'm referring to the group view.
I have several groups and many subgroups, all static, making the list longer than the "view" and giving me a scroll bar.
After playing around with it a little, I realized that when I drag an entry from "All Entries" into a group, there is no issue.
However, if I drag an entry from one group into another, and the group view is scrolled down, it will jump to the top.
Hope this is clearer.
Thanks!

**Comment by matthiasgeiger** [comment]
Okay thank you!

I can reproduce it now somehow... If (and only if!) there are expanded sub-groups the hierarchy view jumps after dropping some lines to the top.

**Comment by stefan-kolb** [comment]
@tobiasdiez You are rewriting the group logic at the moment, right? Could you please take a look at this bug, too?

**Comment by tobiasdiez** [comment]
Yes, I will try to fix it.
