### ISSUE TITLE
Big undo/redo text in status bar

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1726]
The more advanced undo/redo messages are quite nice (I think), but now I realized that they are also shown in the status bar on undo/redo. I think that easiest (and best?) solution is simply to remove the update of the status bar on undo/redo.

**Comment by stefan-kolb** [comment]
I'm not sure whats the point here. Can you explain a little bit more please?

**Comment by oscargus** [comment]
It is just a heads up that I have realized that the following can happen:

<img width="794" alt="capture16" src="https://cloud.githubusercontent.com/assets/8114497/17637408/994d3990-60e3-11e6-8cf4-7b119811e822.PNG">

Just so no one have to write upset issues about it. :-)

**Comment by stefan-kolb** [comment]
Oh ouch ok...
