### ISSUE TITLE
When saving some entries are only partially saved but the completely saved entries follow the uncomplete ones.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#1727]
JabRef version JabRef 3.6dev--snapshot--2016-08-10--fix1609--6aaeee5
windows 7 6.1 amd64 
Java 1.8.0_66

Steps to reproduce:

1. Save a bib file and run biber with that file
2. Biber encounters errors 
3. Check with the .blg file which line is errorneous
4. Correct i.e. delete the incomplete entries with Notepad++.

I have encountered this now twice. First one was with one of about 2000 entries, the next times with three incomplete entries. When it happens again, I will add screenshots and the respective entries.

```
Put the excerpt of the log file here
```

**Comment by oscargus** [comment]
Can you please try the latest dev build? We corrected an issue which sounds similar to this (at least if the incomplete entry ends just before an @) in #1717 .

**Comment by stefan-kolb** [comment]
@bernhard-kleine Can you please try the latest dev build?

**Comment by lenhard** [comment]
This issue has been fixed and I am closing it to inactivity. Feel free to reopen if the problem reappears
