### ISSUE TITLE
JabRef 2.11b4 failed to start if more than 3 files are open

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#174]
I downloaded and installed the latest Beta 4, 
But it failed to start, but all other versions run flawlessly ( 2.10, 2.11beta3 etc.)
The OS is Windows 7, X64, JRE 7U45, 8U40.
Also tested under Windows XP, 32 Bit, JRE7U79.
In both systems, the Beta4 cannot start.

**Comment by matthiasgeiger** [comment]
Thanks for your report!

Are there any error messages shown?

Could you please tell us, which version you are trying to execute:
- JabRef-2.11b4.jar or
- JabRef-2.11b4-setup.exe - Does the installer not work? Or was it possible to install JabRef but calling to program does not work?

**Comment by g10996694** [comment]
The installer installation OK.
when clicking either JabRef-2.11b4.jar or jabref.exe, nothing happened.
no error message

**Comment by g10996694** [comment]
Under WIN7, X64, I see the javaw.exe is running, just no JabRef window.

**Comment by matthiasgeiger** [comment]
Could you please open the windows command prompt in the installation folder and run the command `java -jar JabRef-2.11b4.jar` and paste the log messages here?

**Comment by g10996694** [comment]
Here you have the message, it seemed that jabref is stopping when reading the third .bib file.
But this file is quite basic .bib file, beta 3 can open it normaly.
I tried also, beta 4 window opens when only one or two lib file are started.
Once at start, there is a third file, no window is shown then.
=======================================================
java -jar JabRef-2.11b4.jar
Sep 21, 2015 10:16:13 AM org.java.plugin.registry.xml.ManifestParser <init>
INFO: got SAX parser factory - com.sun.org.apache.xerces.internal.jaxp.SAXParser
FactoryImpl@6fffcba5
Sep 21, 2015 10:16:13 AM org.java.plugin.registry.xml.PluginRegistryImpl configu
re
INFO: configured, stopOnError=false, isValidating=true
Sep 21, 2015 10:16:13 AM org.java.plugin.registry.xml.PluginRegistryImpl registe
r
INFO: plug-in and fragment descriptors registered - 2
Sep 21, 2015 10:16:13 AM net.sf.jabref.plugin.PluginCore initialize
INFO: Found 2 plugin(s):
  - net.sf.jabref.export.misq (jar:file:/D:/User/Documents/JabRef-2.11b4.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)
  - net.sf.jabref.core (jar:file:/D:/User/Documents/JabRef-2.11b4.jar!/plugins/net.sf.jabref.core/plugin.xml)

Sep 21, 2015 10:16:13 AM org.java.plugin.standard.StandardPluginManager activate
Plugin
INFO: plug-in started - net.sf.jabref.core@2.0.0.4b1 (active/total: 1 of 2)
Sep 21, 2015 10:16:13 AM org.java.plugin.standard.StandardPluginManager activate
Plugin
INFO: plug-in started - net.sf.jabref.export.misq@1.0.0 (active/total: 2 of 2)
Sep 21, 2015 10:16:18 AM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\User\Documents\mylib.bib
Sep 21, 2015 10:16:18 AM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\User\Documents\mylib_book.bib
Sep 21, 2015 10:16:18 AM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\User\Documents\mylib_article.bib

**Comment by g10996694** [comment]
Here is the message when running beta 3 from command line : 
C:\Program Files (x86)\JabRef>java -jar JabRef-2.11b3.jar
Found 2 plugin(s):
  - net.sf.jabref.export.misq (jar:file:/C:/Program%20Files%20(x86)/JabRef/JabRe
f-2.11b3.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)
  - net.sf.jabref.core (jar:file:/C:/Program%20Files%20(x86)/JabRef/JabRef-2.11b
3.jar!/plugins/net.sf.jabref.core/plugin.xml)

Opening: D:\User\Documents\mylib.bib
Opening: D:\User\Documents\mylib_book.bib
Opening: D:\User\Documents\mylib_book.bib

**Comment by matthiasgeiger** [comment]
This is weird... 
The output looks okay - and I am able to load more than 3 files at startup. 
Is it always the "mylib_article.bib" file which causes startup problems? Or is the behaviour independent from the actual files you try to open?

**Comment by g10996694** [comment]
Yes, It is independent, 
when starting with any two of the three, beta 4 starts, 
adding one more, beta 4 no longer starts.

**Comment by g10996694** [comment]
Here is the comparison of beta 4 and beta 3 launching from command line:

![2015-09-21 10_45_52](https://cloud.githubusercontent.com/assets/14541017/9988113/06ee92ba-604e-11e5-97ca-6f04b15fc92b.png)

**Comment by matthiasgeiger** [comment]
Sorry, I can not reproduce this problem here.

(One side note: Why is mylib_book.bib opened twice in beta3?)

**Comment by g10996694** [comment]
it is not open twice, juste a copy error ..

**Comment by g10996694** [comment]
I tried with other bib files, it confirmed that <3 bib files, beta 4 runs with ui,  when bib files number >= 3, javaw runs, no jabref ui.
now, I'm under beta 3, no similar problem.
I cannot see any problem, except beta 4 launching is different from beta 3, perhaps it is the new starting behavior changed everything ?

**Comment by matthiasgeiger** [comment]
As I already said: Works fine for me... 
I will dig later into the matter and check whether other persons can reproduce this issue.

**Comment by g10996694** [comment]
could you please tell us that the jre version you used ?
perhaps it is the jre version which brings problems.

**Comment by matthiasgeiger** [comment]
Newest Java 8 JRE on Win7:
` C:\Program Files (x86)\JabRef>java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
`

**Comment by g10996694** [comment]
Thank you !
JabRef not woking any more under XP ?
I tried jabref in a freshly installed xp, nothing happened, neither 2.11 beta 3, nor beta 3.
2.10 stable works fine.
![2015-09-21 11_16_09](https://cloud.githubusercontent.com/assets/14541017/9988601/3db480f8-6052-11e5-9325-d8e604afd586.png)

**Comment by g10996694** [comment]
anyway, it is not a big problem, my xp is a virtual machine for testing.

**Comment by koppor** [comment]
Could you try our latest development snapshot https://circle-artifacts.com/gh/JabRef/jabref/498/artifacts/0/home/ubuntu/jabref/build/releases/JabRef-2.80dev--snapshot--2015-09-18--d9cd640.jar?

**Comment by g10996694** [comment]
For the latest snapshot, it did not start neither.
Here, you have the message :
Did you see something wrong ?
<pre>
F:\>java -jar JabRef-2.80dev--snapshot--2015-09-18--d9cd640.jar
Sep 21, 2015 12:34:53 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "MIS Quarterly" for locale en
Sep 21, 2015 12:34:53 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\User\Documents\mylib.bib
Sep 21, 2015 12:34:57 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\User\Documents\mylib_book.bib
Sep 21, 2015 12:34:57 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\User\Documents\mylib_article.bib
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Toggle relevance"
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Toogle quality assure
d"
Sep 21, 2015 12:34:57 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Toggle print status"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Open SPIRES entry"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Synchronize file link
s"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Bibtex key patterns"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Article"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Book"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Phdthesis"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Inbook"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Mastersthesis"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Proceedings"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Inproceedings"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Conference"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Incollection"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Booklet"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Manual"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Techreport"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Unpublished"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Misc"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Other"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "Push entries to exter
nal application (LyX/Kile)"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ADS from ADS-DOI"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "INSPIRE"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "INSPIRE"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "INSPIRE"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "INSPIRE"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ArXiv.org"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ArXiv.org"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ArXiv.org"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ArXiv.org"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ADS from ADS-DOI"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "SPIRES"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "SPIRES"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "SPIRES"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "SPIRES"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "INSPIRE"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ArXiv.org"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ADS from ADS-DOI"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ADS from ADS-DOI"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "ArXiv.org"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "INSPIRE"
Sep 21, 2015 12:34:58 PM net.sf.jabref.logic.l10n.Localization menuTitle
WARNING: Warning: could not get menu item translation for "SPIRES"
</pre>

**Comment by g10996694** [comment]
if I remove any third file, it will start, 
so, it should not be the problem of bibtex file.

**Comment by stefan-kolb** [comment]
I also cannot reproduce this. Opens all files >= 3 as expected.

**Comment by g10996694** [comment]
It's hard to know :)
But beta 3 works fine, only the 4th has problem.
Perhaps the beta 4 changed its starting parameters ?

**Comment by koppor** [comment]
@g10996694 Are you familiar with git? If yes, a [git bisect run](http://git-scm.com/docs/git-bisect) with `gradlew run` at each checkout would really help to identify the bogus commit.

**Comment by g10996694** [comment]
@koppor I know very little about programming, I will give a try.

**Comment by koppor** [comment]
@g10996694 You can write me a private mail (see my github profile) and we can do a screen sharing session. We need to install a JDK and git.

**Comment by matthiasgeiger** [comment]
Another potential problem could be some legacy preferences which infer with the current version. 
You could try to reset the preferences by calling Jabref the following way:
`java -jar JabRef-2.11b4.jar --prdef all -n`

And than start it normally again.
