### ISSUE TITLE
Program output symbol

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1742]
JabRef version 3.5 on Windows 10, HiDPI 125%
Steps to reproduce:

1. Help | Show error console
2. The red symbol is cut (not full visible)

Remark: The name error console and the red alert symbol is misleading, because it is simply the progam output.
![output](https://cloud.githubusercontent.com/assets/15456836/17666276/cc439506-62ff-11e6-9edb-77556cd2593d.png)

**Comment by Siedlerchr** [comment]
Thanks for your report. 
 We are aware of the bad design of the error console and are currently redesigning the error console using the new GUI Technology JavaFX. Additionally it will have some more features, e.g. with the possibility to create an issue.  See #1383 for the work in progress.

Therefore I will close this issue.

**Comment by grimes2** [comment]
The cut symbol appears everywhere in JabRef:
![cut](https://cloud.githubusercontent.com/assets/15456836/17721589/9d4e7b62-642b-11e6-80e8-466aabcecb45.png)
125% HiDPI, 120 DPI

![uncut](https://cloud.githubusercontent.com/assets/15456836/17721600/b394df24-642b-11e6-8598-627083edb6f4.png)
100%  HiDPI, 96 DPI

So it is a HiDPI issue of Java/JabRef.

**Comment by oscargus** [comment]
The cropped symbol is a Java issue (since the latter examples are one-liners calling a standard Java notification dialog).

**Comment by grimes2** [comment]
I found this: http://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display
dpiAvare=true in java.manifest?

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
