### ISSUE TITLE
Weird editing in empty entries

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1745]
JabRef version latest master

Steps to reproduce:

1. Create empty database (not really required)
2. Create two empty entries of the same type
3. Mark one of the entries and open entry editor
4. Add some text in a field and mark another field
5. The text appears in the other entry!

Selecting entries back and forth gives that the information is added to both entries. However, saving and loading only the actual entry is loaded with the new information.

**Comment by koppor** [comment]
This seems to be solved in the course we removed the entry editor cache. Refs #2166
