### ISSUE TITLE
Describe migration from JabRef 2.11 to 3.6

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1747]
Setting:

 * User uses JabRef 2.11 to work with an external database
 * User uses JabRef 3.6dev and connects to external database
 * User sees no entries
 * User switches back to JabRef 2.11.
 * User sees no entries (to be confirmed)

Desired: The old entries should be shown in both cases.

Is that possible? Should the user use JabRef 2.11 to rescue his data?

@mtecfred

**Comment by obraliar** [comment]
This issue is solved and can be closed.
