### ISSUE TITLE
Check import .bib file

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1748]
Setting connecting to database written by JabRef 2.11.

 * User uses JabRef 2.11 to work with an external database
 * User uses JabRef 3.6dev and connects to external database
 * User sees no entries
 * User imports `bib` file with entries "Import into current database"
 * JabRef shows "Aktualisierung verweigert. Den Eintrag, den Sie zur Zeit bearbeiten, ist auf der geminsam genutzen Datenbank nicht mehr vorhanden." for each entry.
 * After the import, all entries appear twice.

@mtecfred

Refs #1747

**Comment by obraliar** [comment]
This issue is solved and can be closed.
