### ISSUE TITLE
Preview not updated properly

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#1760]
JabRef 3.6dev--snapshot--2016-07-29--fix1639--e838541
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. Select an entry. The entry preview (correctly) appears at the bottom of Jabref.
2. Now select several entries, e. g. the first two entries below the entry you had intially selected. I've done this by holding SHIFT and clicking onto the last entry I want to select.
3. Three entries are now selected. The entry preview of the initially selected entry is still visible. So far, so good.
4. Now select another entry among the three entries that you selected beforehand. This is now the only entry that is selected (indicated in "blue" by Jabref). The entry preview, however, is not updated properly. It still shows the entry preview of the entry that you had selected at the start.
5. If you select now another entry and then go back to the entry selected in 4), the entry preview will be updated correctly.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by AEgit** [comment]
I can confirm that this issue has been fixed in:
JabRef 3.6dev--snapshot--2016-08-23--master--9ac0e67

It seems now, however, that the default for the groups interface has changed. Beforehands, the groups interface was automatically toggled on. Now, even if I toggle on the groups interface, save the database, close it and then reopen it the groups interface won't appear automatically. I have to toggle it on again, manually. Can you confirm this or is it just that I don't find the respective setting under preferences?

**Comment by stefan-kolb** [comment]
@AEgit This is a different issue. Can you please open a new one for this? I think this should be saved between interactions.

**Comment by AEgit** [comment]
Alright, I just wanted to check, whether it's not just me who has missed a change in the settings/preferences.
