### ISSUE TITLE
File-Save/Save as should already suggest .bib ending

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1763]
Currently it is set on All files.

![image](https://cloud.githubusercontent.com/assets/2141507/17738393/5e607f48-6491-11e6-94f0-1d5393bdfc8a.png)

**Comment by grimes2** [comment]
Same issue with Open database, Save selected (.bib), Export/Import preferences (.xml) etc.

**Comment by Siedlerchr** [comment]
@stefan-kolb My idea was to (only) use setFilter when we have a single ext.
See #1764

**Comment by stefan-kolb** [comment]
@Siedlerchr Could be an option, but maybe this is not what we want in every dialog? So I just made it explicitely.

**Comment by stefan-kolb** [comment]
@grimes2 Thanks for pointing this out, I'll take care of this.

**Comment by grimes2** [comment]
For open dialogs with multiple extensions is would be nice to have "All supported types (*.bibx, *.bib, *.txt, ...)" as default.

**Comment by stefan-kolb** [comment]
Can you please open a new issue for this?

Am 18.08.2016 12:19 nachm. schrieb "grimes2" <notifications@github.com>:

**Comment by grimes2** [comment]
Another two cases:

AUX: Tools > New subdatabase based on AUX files > Browse
CLASS: Options > Manage custom imports > Add from folder

**Comment by grimes2** [comment]
LAYOUT: Options > Manage custom exports > Add new > Browse

**Comment by Siedlerchr** [comment]
@grimes2  You do not need to mention all dialogues here. That are probably all dialogs that use a single file extension to filter (much easier to search for in the code)
