### ISSUE TITLE
Open dialog: All supported types as default

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1771]
For open dialogs with multiple extensions is would be nice to have "All supported types (*.bibx, *.bib, *.txt, ...)" as default. (File > Import into new database)

**Comment by stefan-kolb** [comment]
Could you specify which actions are affected? This would tremendously help us to get this consistent :smile:

**Comment by grimes2** [comment]
File > Import into new database
File > Import into current database

Both actions support same extensions (around 10 database format extensions).

**Comment by stefan-kolb** [comment]
This should be fixed in current `import-dialogs`. Please try the latest build from http://builds.jabref.org/import-dialogs.

**Comment by grimes2** [comment]
It works. But I tested only with a few import formats. Thanks. Much better now.

**Comment by grimes2** [comment]
Another case:

JAR/ZIP: Options > Manage custom imports > Add from JAR
