### ISSUE TITLE
Inconsistency in dialogs DIRECTORY_ONLY: open and select directory

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1788]
![_2016-08-19_20-01-36](https://cloud.githubusercontent.com/assets/15456836/17829962/5c9bb634-66bf-11e6-8216-fdb726afecd0.png)

![_2016-08-20_10-05-56](https://cloud.githubusercontent.com/assets/15456836/17829964/61042a94-66bf-11e6-8444-f75012858147.png)

**Comment by stefan-kolb** [comment]
Can you please post where you open those dialogs?

**Comment by grimes2** [comment]
Select directory: Quality > Find unlinked files > Browse
Open: File > Database properties > Browse (only one example)

**Comment by stefan-kolb** [comment]
Only the dialog Quality > Find unlinked files > Browse uses the Choose Directory button?!

**Comment by grimes2** [comment]
Yes, it is much more easy to change that dialog title/button, but semantically Select directory is correct. (Open is for open files)

**Comment by stefan-kolb** [comment]
I used the default JFileChooser description for now, which is `Open`

**Comment by oscargus** [comment]
I think something stating directory is preferable.

**Comment by grimes2** [comment]
My proposal:
For the window title: Select directory
For the button: Set directory

**Comment by grimes2** [comment]
I' ve tested JabRef 3.6dev--snapshot--2016-08-21--more-file-dialogs--d1d0572:

Quality > Find unlinked files > Browse: Pressing "Select" is not updating the directory field with new path. A refresh problem?

**Comment by stefan-kolb** [comment]
@grimes2 Thanks for pointing this out, I pushed a fix right now.

**Comment by grimes2** [comment]
Another issue: Preferences > File > Main file directory: Button cropped

Apart from that: LGTM. Thanks.

**Comment by stefan-kolb** [comment]
@grimes2 Also fixed this. Thanks a lot for your detailed testing! :+1:
