### ISSUE TITLE
Get bibtex data from DOI -  UI Thread blocks if http request is long running

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1799]
JabRef version 3.6dev latest
Steps to reproduce:
1.  Entry with DOI  `10.13140/2.1.3259.2169`
2.  GetBibTex Data from entry 
3. UI blocks because of long running request (atm the download returns a 405 Gateway timed out, therefore long running).

=> Download/Request should be made in Backround Thread

**Comment by oscargus** [comment]
This would be a good situation to start using https://docs.oracle.com/javase/7/docs/api/javax/swing/SwingWorker.html
