### ISSUE TITLE
Improve sharing: Store serialization settings within the bibtex file

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#180]
JabRef is able to sort the `.bib` file according to a configuration. When users with different configuration options check in their `.bib` file into version control, the files have textual diffeences without any content difference.

I propose that JabRef writes its serialization settings into the bibtex file at each save. This ensures that the serialization options are always met. The other option is that JabRef asks the user whether he wants to prepare the `.bib` file for sharing. If not, JabRef stores the filename in its preferences and never asks the user again.

This covers at least
* entry sorting (alphabetically using the author, sorting by the bibtex key, or no sorting, just adding entries at the end)
* format of each entry (see #116)

## Related discussions
* This issue is closely related to the discussion going on at #116 - especially https://github.com/JabRef/jabref/issues/116#issuecomment-133311604.
* https://sourceforge.net/p/jabref/feature-requests/892/
* https://sourceforge.net/p/jabref/feature-requests/854/

**Comment by lenhard** [comment]
But then the file contains text that is not bibtex and probably not in bibtex syntax. Might this not be a problem if the `.bib` file is shared with someone who uses a different editor?

Apart from that, I am all for file purity and against putting additional stuff into the `.bib` file. I'd prefer to define a fixed serialization format as in #116 :)

**Comment by koppor** [comment]
Currently, JabRef uses standardized `@comment` entries, e.g. `@comment{jabref-meta: groupsversion:3;}`. The only exception is the encoding (see #118).

Maybe it would be good to
A) Have one defined serialization format (see your comment https://github.com/JabRef/jabref/issues/116#issuecomment-134121807)
B) Have the file sorting options not stored as setting, put as Tool to call explicitly. New entries are sorted in after the first alphabetical match. Only ONE sorting setting, not a configurable one.

Maybe, both things should but into our survey. @mlep (I'll write a private mail)

**Comment by mlep** [comment]
Waiting for your input!  :-)

**Comment by lenhard** [comment]
Fixed in master
