### ISSUE TITLE
Working directory is set to full path including filename

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1803]
JabRef 3.5
windows 10 10.0 amd64 
Java 1.8.0_101

1. File > Open database, open a bib file
2. Show preferences, string working directory
3. string is a full path (with bib file) not a directory

"Save database as" works correct.

**Comment by Siedlerchr** [comment]
Confirmed in the dev version.

**Comment by oscargus** [comment]
I haven't found any consequences after a quick check. Can be fixed by replacing all `file.getPath()` by `file.getParent()` when setting the preference.
