### ISSUE TITLE
Url field vanishes after running "Check integrity" 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1804]
Originally reported by Sait_Umar in the forum:

http://discourse.jabref.org/t/check-integrity-removing-my-url-fields/123/4

 

JabRef 3.5 and Jabref 3.6dev
windows 7 6.1 amd64 
Java 1.8.0_102 

Tested both biblatex and bibtex entries:

Steps to reproduce:
1.  Create a new bib database (In file.bib some entries contain url fields)
2.  Enter entry with url content http:://www.google.de 
2.  Run "check integrity..."
3.  Make a small correction at  some place, e.g. change the title
4.   save database
5.   See if url fields are still there.

=> After saving the url field is completely vanished 

No errors, no info in log file

**Comment by oscargus** [comment]
Caused by:

``` java
            // the url field should not be checked for hashes, as they are legal in this field
            fields.remove(FieldName.URL);
```
