### ISSUE TITLE
import inspection window not working with fetched entries

### ISSUE THREAD

**Issue by mariofiorini** [JabRef/jabref#1805]
JabRef version 3.5 
I am having trouble with the import inspection window not working with fetched entries. Below I include a specific paper that I was looking for using Google Scholar "Risk selection and heterogeneous preferences in health insurance markets with a public option" (but the result would the same with another paper). I find the paper but then the import inspection window is still empty. (see screenshots) Is this a bug?
![screen shot 2016-08-22 at 1 46 22 pm](https://cloud.githubusercontent.com/assets/21165723/17843276/5f660034-686f-11e6-84cc-ce70bd9e2ec7.png)
![screen shot 2016-08-22 at 1 46 34 pm](https://cloud.githubusercontent.com/assets/21165723/17843277/5f66ca32-686f-11e6-914b-40ac4cbb0b03.png)

Steps to reproduce:

1. Fetch "Risk selection and heterogeneous preferences in health insurance markets with a public option" using google scholar
2. Select entry (there's only one) and click ok
3. import inspection window is empty

```
Put the excerpt of the log file here
```

**Comment by oscargus** [comment]
Google changed the structure so that the actual bib-files were on a different server, see https://github.com/JabRef/jabref/issues/1639 . This should be fixed in the current master. Please try it out at http://builds.jabref.org/master and report back if it is the same issue.

**Comment by mariofiorini** [comment]
I tried the master and it works fine there! thanks for this.

**Comment by oscargus** [comment]
Great!
