### ISSUE TITLE
Wrong Database properties encoding

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1806]
JabRef 3.6dev--snapshot--2016-08-22--master--74afbb7
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. File > Database properties > Database encoding > Big5 (was/is windows-1252)

**Comment by stefan-kolb** [comment]
Probably relates to #1790

**Comment by stefan-kolb** [comment]
@oscargus I don't know if its good to make encoding optional. This might cause a lot of problems? Maybe just return a default encoding UTF-8 if no encoding was set?

**Comment by oscargus** [comment]
The alternatives are to

a) always provide it in the constructor
b) have an unremovable Globals dependency in MetaData

Earlier it was set to `Globals.prefs.getDefaultEncoding()` upon construction. Now it is set to the same value upon access, so probably slightly better even, in case it is changed, so I doubt that it actually has to do with #1790. Of course, another way would be to fall back to UTF-8, but I cannot really oversee the consquences.

(The other main suspect is #1411)

@grimes2 : do you by any chance have 3.5 installed and can try if the same thing happens there?

**Comment by stefan-kolb** [comment]
@oscargus I already got the problem in the code:
```
DatabaspropertiesDialog, l.178
```

**Comment by oscargus** [comment]
Ahh, I thought I had searched for all `getEncoding()` and handled it... Thanks!
