### ISSUE TITLE
Import Preferences don't set font size

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1808]
JabRef 3.6dev--snapshot--2016-08-22--master--74afbb7
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. Change Preferences > Appearance > Set table font to font size 14
2. Export preferences (xml)
3. Change Preferences > Appearance > Set table font to font size 10
4. Import preferences (xml)
5. fontsize is still 10 (should be 14)

Remark:
font size is saved in xml:
`<entry` key="fontSize" value="14"/>

**Comment by oscargus** [comment]
I do not know if it is related, but if one just does the following:

1. Press "Set table font" and change something. Press "OK".
2. Press "Set table font" and everything is back to before the change in 1.

I guess this is related to the preference change not actually happening before pressing "OK" in the Preferences dialog and the font dialog is initialized from `GUIGlobals.currentFont`.

**Comment by grimes2** [comment]
Import Preferences also doesn't import "push to application Lyx/Kile", it is set to "push to Emacs" instead.

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master.
