### ISSUE TITLE
Request: Import/Export preferences dialog with working directory as default

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1813]
The current default directory is user-dir. I think, the correct place for the xml file is the working directory (or a subdirectory of it). The working directory variable should work now.

Talking about this dialog:
![image](https://cloud.githubusercontent.com/assets/2141507/17858466/264fed2a-6886-11e6-9dd0-dbec9591ae3c.png)

**Comment by stefan-kolb** [comment]
@JabRef/developers We got a few different working dirs. Maybe we should discuss if we really need them or just use one working dir for all dialogs:
```
    public static final String FILE_WORKING_DIRECTORY = "fileWorkingDirectory";
    public static final String IMPORT_WORKING_DIRECTORY = "importWorkingDirectory";
    public static final String EXPORT_WORKING_DIRECTORY = "exportWorkingDirectory";
    public static final String WORKING_DIRECTORY = "workingDirectory";
```

**Comment by stefan-kolb** [comment]
Especially `FILE_WORKING_DIRECTORY` is debatable. used for external file type application selection and in the file dialog of the general tab of an entry.

**Comment by Siedlerchr** [comment]
Working Directory is clear, it is always the location of the bib file (if not otherwise set).
Yeah, I  think File_Working_Directory is confusing, especially for adding a file to an entry. There I would expect  to open the dlg in the Working_Directory.  However, some may prefer having two different dirs for that. No idea. Ask the users.

**Comment by stefan-kolb** [comment]
It's not really about the user right now it's about the concept because it's inconsistent at the moment.

**Comment by grimes2** [comment]
My user opinion regarding `FILE_WORKING_DIRECTORY`: You can remove the variable, text field, browse button in the preferenes. And also remove the checkbox below and set `WORKING_DIRECTORY` as default for the entry editor dialog.

**Comment by grimes2** [comment]
I want to work on this issue. But I need your ok, that this change from user-dir to working-dir for the preferences xml is useful.

**Comment by Siedlerchr** [comment]
@JabRef/developers  Any comments on this? From my point of view it's okay to change it to working-dir

**Comment by stefan-kolb** [comment]
Issue not closed yet, see my comment on file prefs.

**Comment by koppor** [comment]
@grimes2 Where is the text field for `FILE_WORKING_DIRECTORY`? And the checkbox? I see only the screenshot with Export Preferenes.

In the preferences, I see:

![grabbed_20160908-052540](https://cloud.githubusercontent.com/assets/1366654/18336081/b7a49018-7584-11e6-88e4-50470cd353c9.png)

In the context menu of a database, I see:

![grabbed_20160908-052617](https://cloud.githubusercontent.com/assets/1366654/18336097/c9f3a470-7584-11e6-96ac-4b875afe970f.png)

The different directories are explained at https://github.com/JabRef/jabref/pull/459#issuecomment-161817966 - IMHO not yet in the documentation

Is it possible that I am on the wrong track? But "checkbox" sounds like GUI.

**Comment by grimes2** [comment]
I was wrong. It is the textbox for the 'FILE_DIRECTORY' and the checkbox below (Use tie BIB file location as primary file directory) toggles between `FILE_DIRECTORY` and `WORKING_DIRECTORY`. This is ok, but I don't know the purpose of `FILE_WORKING_DIRECTORY` and I doubt it's working properly, because the variable is set to a full path (with file name). It is really confusing. I mixed up the directories.

**Comment by stefan-kolb** [comment]
We remove `FILE_WORKING_DIRECTORY` and use `WORKING_DIRECTORY` instead.

**Comment by koppor** [comment]
@grimes2 Do you mean "Main file directory" and "Use the BIB file location as primary directory"?

**Comment by grimes2** [comment]
Yes. I think this layout is not intuitive. Default "Main file directory" should be the working directory. The checkbox "Use the BIB file location as primary directory" should be replaced by radio buttons: a) Use custom main file directory, b) Use BIB file directory. (This are just some ideas)

**Comment by grimes2** [comment]
@stefan-kolb Can you explain? I thought, `FILE_WORKING_DIRECTORY` is essentially the same as `FILE_DIRECTORY`.
