### ISSUE TITLE
Globals.pref dependency in BibEntryAssert

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1820]
I just add another case here, I found out in #1765  which needs some special care:

In `MsBibImporterTestfiles` it is theoretically not needed, but if I remove it fails with an NPE, reason is 
`getListFromInputStream(InputStream is)`  in `BibEntryAssert` loads prefs from Globals.prefs

@oscargus  As you are currently reworking that globals stuff, just one thing I noticed. Maybe you can add fix, this one, too.

**Comment by oscargus** [comment]
Included in #1819. :-)

**Comment by oscargus** [comment]
But I haven't touched the tests for specific importers (yes).

**Comment by oscargus** [comment]
Now I touched the importers...
