### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1824]
@mlep We are doing a feature freeze for 3.6 right now. It would be great if you can take over the localization stuff for the next release :smile:

**Comment by mlep** [comment]
I am not sure I understand you: by "take over the localization stuff", do you mean version 3.6 or 3.7?

**Comment by mlep** [comment]
@JabRef/translators @oscargus :
JabRef 3.6 is scheduled for release this Friday (August 26), it is time for us translators to wrap up the localization.
Please, find below the current status for each localization file.
*Watch out*: some strings waiting for translation have been added in the middle of the file (and not at the bottom.




src/main/resources/l10n/Menu_in.properties: 5 empty values. 
src/main/resources/l10n/Menu_tr.properties: 3 empty values. 
src/main/resources/l10n/Menu_zh.properties: 5 empty values. 
src/main/resources/l10n/Menu_vi.properties: 22 empty values. 
src/main/resources/l10n/Menu_ja.properties: 4 empty values. 
src/main/resources/l10n/Menu_fr.properties: ok
src/main/resources/l10n/Menu_sv.properties: 2 empty values. 
src/main/resources/l10n/Menu_fa.properties: 5 empty values. 
src/main/resources/l10n/Menu_nl.properties: 5 empty values. 
src/main/resources/l10n/Menu_ru.properties: 5 empty values. 
src/main/resources/l10n/Menu_de.properties: 1 empty values. 
src/main/resources/l10n/Menu_es.properties: 5 empty values. 
src/main/resources/l10n/Menu_da.properties: 5 empty values. 
src/main/resources/l10n/Menu_pt_BR.properties: 5 empty values. 
src/main/resources/l10n/Menu_no.properties: 5 empty values. 
src/main/resources/l10n/Menu_it.properties: 5 empty values. 

src/main/resources/l10n/JabRef_ja.properties: 102 empty values. 
src/main/resources/l10n/JabRef_vi.properties: 717 empty values. 
src/main/resources/l10n/JabRef_de.properties: 9 empty values. 
src/main/resources/l10n/JabRef_no.properties: 585 empty values. 
src/main/resources/l10n/JabRef_fr.properties: ok
src/main/resources/l10n/JabRef_es.properties: 157 empty values. 
src/main/resources/l10n/JabRef_ru.properties: 389 empty values. 
src/main/resources/l10n/JabRef_tr.properties: 16 empty values. 
src/main/resources/l10n/JabRef_it.properties: 388 empty values. 
src/main/resources/l10n/JabRef_fa.properties: 1553 empty values. 
src/main/resources/l10n/JabRef_pt_BR.properties: 342 empty values. 
src/main/resources/l10n/JabRef_da.properties: 584 empty values. 
src/main/resources/l10n/JabRef_nl.properties: 907 empty values. 
src/main/resources/l10n/JabRef_in.properties: 317 empty values. 
src/main/resources/l10n/JabRef_sv.properties: 215 empty values. 
src/main/resources/l10n/JabRef_zh.properties: 325 empty values.

**Comment by Siedlerchr** [comment]
To search for empty lines, open the the files in an editor which supports RegEx (e.g. Notepad++ on Windows)  and search for:
`.=\r\n`  On Windows and on Unix/Mac
`.=\n`

German translation is now complete.

**Comment by mlep** [comment]
@Siedlerchr : is it possible to carry out the same kind of search through the edit mode of gitHub? (i.e. in the browser)

**Comment by Siedlerchr** [comment]
@mlep  Yes! Just hit Strg+F in the Editor window and click the (first option?`) titled RegExp search:
`.=\n` should work

![regexgithub](https://cloud.githubusercontent.com/assets/320228/17923053/728b19dc-69e2-11e6-97cc-0111ca8f3e11.png)

**Comment by oscargus** [comment]
=$ also works where $ is the regex for end of line.

**Comment by mlep** [comment]
Well, it does not work for me  :cry: , as show by the red rectangle around the search string...
![capture du 2016-08-24 10 21 01](https://cloud.githubusercontent.com/assets/6931104/17923470/970648de-69e4-11e6-8353-4f2091a6e53e.png)
It does not find anything for .=\n  ,  =\n  or even just \n
(tested with Chromium and Firefox)

**Comment by matthiasgeiger** [comment]
Using the search @oscargus proposed should work.

**Comment by mlep** [comment]
Indeed, it does! (I was testing the \n solution while he wrote its comment, and sent mine without noticing it). Thanks for your help!

**Comment by mlep** [comment]
**Status update**

We now have full menus for Turkish, French, Swedish and German.
For the other menus, it is about 5 strings to translate (only). A short way to go!

Messages are full for Turkish and German (French is under way).

src/main/resources/l10n/Menu_in.properties: 5 empty values. 
src/main/resources/l10n/Menu_tr.properties: ok
src/main/resources/l10n/Menu_zh.properties: 5 empty values. 
src/main/resources/l10n/Menu_vi.properties: 22 empty values. 
src/main/resources/l10n/Menu_ja.properties: 4 empty values. 
src/main/resources/l10n/Menu_fr.properties: ok
src/main/resources/l10n/Menu_sv.properties: ok
src/main/resources/l10n/Menu_fa.properties: 5 empty values. 
src/main/resources/l10n/Menu_nl.properties: 5 empty values. 
src/main/resources/l10n/Menu_ru.properties: 5 empty values. 
src/main/resources/l10n/Menu_de.properties: ok
src/main/resources/l10n/Menu_es.properties: 5 empty values. 
src/main/resources/l10n/Menu_da.properties: 5 empty values. 
src/main/resources/l10n/Menu_pt_BR.properties: 5 empty values. 
src/main/resources/l10n/Menu_no.properties: 5 empty values. 
src/main/resources/l10n/Menu_it.properties: 5 empty values. 

src/main/resources/l10n/JabRef_ja.properties: 104 empty values. 
src/main/resources/l10n/JabRef_vi.properties: 719 empty values. 
src/main/resources/l10n/JabRef_de.properties: ok
src/main/resources/l10n/JabRef_no.properties: 587 empty values. 
src/main/resources/l10n/JabRef_fr.properties: 4 empty values. 
src/main/resources/l10n/JabRef_es.properties: 159 empty values. 
src/main/resources/l10n/JabRef_ru.properties: 391 empty values. 
src/main/resources/l10n/JabRef_tr.properties: ok
src/main/resources/l10n/JabRef_it.properties: 390 empty values. 
src/main/resources/l10n/JabRef_fa.properties: 1555 empty values. 
src/main/resources/l10n/JabRef_pt_BR.properties: 344 empty values. 
src/main/resources/l10n/JabRef_da.properties: 586 empty values. 
src/main/resources/l10n/JabRef_nl.properties: 909 empty values. 
src/main/resources/l10n/JabRef_in.properties: 319 empty values. 
src/main/resources/l10n/JabRef_sv.properties: 148 empty values. 
src/main/resources/l10n/JabRef_zh.properties: 327 empty values.

**Comment by mlep** [comment]
@JabRef/translators @oscargus 
**A new string has just been added**
It is `Connecting...`
Easy to translate!

**Comment by Siedlerchr** [comment]
German is already done. Good.

2016-08-25 15:58 GMT+02:00 MLEP <notifications@github.com>:

**Comment by mlep** [comment]
Italian menus are now fully translated (thank you @ambro2!)
So, menus are now complete for five languages: Turkish, French, Swedish, German and Italian.

**Comment by stefan-kolb** [comment]
Great, thank you @JabRef/translators for all your efforts :+1:

**Comment by oscargus** [comment]
I added Norwegian menu translations in #1821 . Unfortunately also a few more Menu translations (although very simple ones).

**Comment by mlep** [comment]
Done for the French.
@oscargus : I did not have the right to directly modify the files. I am afraid you are going to have to copy-paste my comments...
