### ISSUE TITLE
Default of groups interface has changed? Groups interface doesn't appear automatically anymore.

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#1825]
JabRef 3.6dev--snapshot--2016-08-23--master--9ac0e67
windows 10 10.0 amd64 
Java 1.8.0_101

It seems as if the default for the groups interface has changed (see also https://github.com/JabRef/jabref/issues/1760#issuecomment-241671690).
Before updating to the current version (JabRef 3.6dev--snapshot--2016-08-23--master--9ac0e67), the groups interface was automatically toggled on (JabRef 3.6dev--snapshot--2016-07-29--fix1639--e838541).
Now, even if I toggle on the groups interface, save the database, close it and then reopen it, the groups interface won't appear automatically. I have to toggle it on again, manually. Can you confirm this or is it just that I don't find the respective setting under preferences?

This might be related to changes between the versions:

JabRef 3.6dev--snapshot--2016-07-29--fix1639--e838541
and
JabRef 3.6dev--snapshot--2016-08-23--master--9ac0e67

(see also here: https://github.com/JabRef/jabref/issues/1760#issuecomment-241671690)

**Comment by stefan-kolb** [comment]
The groups interface doesn't toggle automatically anymore if there are groups inside the database, this is expected #1610. 
However, we should still save the current state of the groups interface if it is opened or not and reopen it after closing JabRef or opening a new database.

**Comment by AEgit** [comment]
Thanks for the explanation: So it is just the current state of the groups interface that needs to be saved.

**Comment by stefan-kolb** [comment]
See #2201

**Comment by AEgit** [comment]
I can confirm that this problem has been fixed in:
JabRef 3.7-dev--snapshot--2016-11-03--master--9928179

Thank you very much!
