### ISSUE TITLE
Strange group undo code

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1827]
Consider the following code in `GroupChange`:

```
        final GroupTreeNode root = panel.getBibDatabaseContext().getMetaData().getGroups();
        final UndoableModifySubtree undo = new UndoableModifySubtree(
                new GroupTreeNodeViewModel(panel.getBibDatabaseContext().getMetaData().getGroups()),
                new GroupTreeNodeViewModel(root), Localization.lang("Modified groups"));
```

Clearly both the old and the new version of the groups are identical. 

I do not know what the consequences are, but I would guess it is hard to undo certain group changes....

I traced the source backwards but it was like this (from a functional perspective) when the source was moved to GitHub.

**Comment by stefan-kolb** [comment]
@tobiasdiez probably one for you to explain.

**Comment by tobiasdiez** [comment]
I have no idea, sorry. The code is also at least 2 years old: https://github.com/JabRef/jabref/blob/8dee2af2379dc80e8bba486fb81dbf5dd480daac/src/main/java/net/sf/jabref/collab/GroupChange.java

**Comment by Siedlerchr** [comment]
I think with the rework of the Group Editor this issue can be closed.
