### ISSUE TITLE
Fetch from google scholar

### ISSUE THREAD

**Issue by cdvanlangenberg** [JabRef/jabref#1833]
I have issues with fetching from google scholar (I use version 3.5)
It is the exact same issue as in https://github.com/JabRef/jabref/issues/1639

from log:
[JabRef CachedThreadPool] WARN  net.sf.jabref.importer.fetcher.GoogleScholarFetcher - Cannot download entry from Google scholar
java.net.UnknownHostException: scholar.google.comhttp
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_73]
	at java.net.PlainSocketImpl.connect(Unknown Source) 

I tried to install dev version from http://builds.jabref.org/master/ (for windows), this cannot be installed issue with the installer.

**Comment by koppor** [comment]
Which issue with the installer do you have?

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version. Please try downloading the `jar` from http://builds.jabref.org/master/ and test it with that until we sorted out the issues with the installer.

**Comment by cdvanlangenberg** [comment]
I tired the above dev exe let me try the jar

**Comment by cdvanlangenberg** [comment]
cannot install the dev version
internal error occurred:  error code 34

**Comment by cdvanlangenberg** [comment]
I used dev 3.6 and it works fine, Thanks for the update.
