### ISSUE TITLE
Error setting bibtex field

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#185]
Steps to reproduce:
1. Choose an arbitrary non-multiline field
2. Enter `text` and line breaks AND an EMPTY line
3. Save database

Error: 
`Error setting field: bad position`

**Comment by lenhard** [comment]
For the record: The error seems to be thrown in the inner class `StoreFieldAction` of [EntryEditor](https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/gui/entryeditor/EntryEditor.java#L1298). It seems likely that it is triggered by this line:

```
new LatexFieldFormatter().format(toSet, fieldEditor.getFieldName());
```

This would probably a good time to write tests for `LatexFieldFormatter` :-)

**Comment by matthiasgeiger** [comment]
Note for me: Check whether this was introduced by #143
