### ISSUE TITLE
Ms Office 2007 xml Import/Export

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1851]
Follow up from  #1750  and #1765 

TODO:
- [x] Export Company/Author as Corpoate #1497
- [x] Language to LCID mapping
- [x] Support for Custom Entry types (http://discourse.jabref.org/t/customize-word-2007-xml-export-filter/149/4)

**Comment by Mattri** [comment]
Hello Christoph,

in the meantime, I've been testing MS Office 2007 XML export of version 3.6. Integration of custom entry types as `<b:BIBTEX_entry>` seems to be a good idea and can be used for generating appropriate citations in Word. I noticed one more problem, though: the "Location"-field of BibTex is not exported correctly. Say, you have set "Location" to "Berlin". Then, in the MS-Bib XML this is converted to 

<b:City>Berl</b:City>
<b:StateProvince>i</b:StateProvince>
<b:CountryRegion>n</b:CountryRegion>`

**Comment by Siedlerchr** [comment]
Hello Mattri,
thanks for your report! I will check it.
` Integration of custom entry types as <b:BIBTEX_entry> seems to be a good idea `
Yeah, I thought the same and theoretically it should already be there, because the field is just calling `entry.getType()` But I will check for custom entry types,too.

In the meantime I created a help page with all entry and field mappings between JabRef and MsOffice.
It is not yet public, but I will try to get it done this afternoon/evening.

**Comment by Siedlerchr** [comment]
@Mattri  I fixed the location bug.  When only one "word" is present (e.g. Berlin) it is threated as city.

**Comment by Siedlerchr** [comment]
@Mattri  I  just merged the fix for the location export bug. You soon could try the latest master from here: 
http://builds.jabref.org/master/

**Comment by Siedlerchr** [comment]
@Mattri I just tested to export a custom entry type. The entrytype is corectly set in the
`<b:BIBTEX_entry>` field 
And in the xml file:
```
<b:Source>
<b:Year>2016</b:Year>
<b:BIBTEX_Entry>mycustomentrytype</b:BIBTEX_Entry>
<b:SourceType>Misc</b:SourceType>
<b:Tag>CustomAuthor2016</b:Tag>
```

Sample Bib file:
[CustomEntryType.bib.txt](https://github.com/JabRef/jabref/files/454005/CustomEntryType.bib.txt)

**Comment by Mattri** [comment]
@Sidlerchr I tried the dev snapshot. However, the .exe throws a Java-Error during initialization. I ran the .jar and did the MS-Bib Export. The issue with broken exports of "Location" is still there, works only randomly, e.g. "Södertälje" is exported correctly, while "Tokyo" isn't.

**Comment by Siedlerchr** [comment]
@Mattri  I just see that the master build did not get updated correctly (still from 02.09). I will build an upload it manualy

**Comment by Siedlerchr** [comment]
@Mattri  I just uploaded the most recent version to my personal cloud 
https://siedlerchr.owncube.com/index.php/s/NaXpmdT0ZatFD5H
[Uploading JabRef-3.7dev.zip…]()

**Comment by Mattri** [comment]
@Siedlerchr thanks for the fixed version. There are a few more issues from my side: since I organize my references with custom entry types (necessary corporate rules) source type is set to "Misc" for all of my entries with "BIBTEX_Entry" added for the custom entry type. This is OK. However, some fields are ignored and do not show up in the MS-Bib-XML. For example, I use a custom type for reports which includes a field "key". This tag is not exported. Same thing with a custom patent-like type containing the field "number".
Would it be possible for the source type "Misc" to treat **every** field encountered in the *.bib-file, export it to an appropriate MSBib-XML-tag OR apply  `<b:BIBTEX_unknown-field`. In any case, fields should not be omitted

**Comment by Siedlerchr** [comment]
Yeah, that should be possible. If you could provide me some sample bib file (if you do not want it public here, send it to developers@jabref.org), I wil test it and check the possibilites.

**Comment by Mattri** [comment]
I generated a sample file containing a set of custom entry types. All fields should be exported

[sample_file_Mattri.zip](https://github.com/JabRef/jabref/files/456583/sample_file_Mattri.zip)

**Comment by Siedlerchr** [comment]
@Mattri  I just fixed the problems with the key and the number export.  Key is now exported as `<b:BIBTEX_Key>` . Number gets exported as `number `field if the entry type is not patent and the field issue is not present.

In the meantime I would like you to check if all fields are listed here in the help file (except the things mentioned above). 
http://help.jabref.org/en/MsOfficeBibFieldMapping

I will check further if it possible to export all fields which are not yet present in the manual mapping.

**Comment by mew1033** [comment]
@Siedlerchr I'm running into the problem with corporate authors not being parsed correctly. Is there anything I can do to get that working? I've got sample .bib and .xml files if needed.

**Comment by PeterMinin** [comment]
Regarding LCID, the current default value of 0 does not seem to correspond to English, neither by [the docs](https://msdn.microsoft.com/en-us/library/cc233982.aspx) (which don't list a 0x0000 value at all), nor in practise (Word imports such entries with the language set to Default). Shouldn't the default value be changed to 1033 (0x0409)?
