### ISSUE TITLE
Filename generation for PDF download includes URL query if no access

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1859]
Steps to reproduce:

1. Download paper information using DOI 10.1007/978-3-642-36926-1_23
2. Fetch PDF
3. `...vdAW2013 - The P2P Approach to Interorganizational Workflows.8153&rep=rep1&type=pdf` is offered as file name

Changing the filename leads to a file of 1kb.

**Comment by stefan-kolb** [comment]
This is an error of `SpringerLink.java`?! I cannot reproduce it right now, as I have access to this article...

**Comment by stefan-kolb** [comment]
Please check the log which fetcher found the "PDF".

**Comment by koppor** [comment]
Oh, I'm just relocating and won't be in  [Dagstuhl](http://www.dagstuhl.de/de/programm/kalender/semhp/?semnr=16341) the next time. I'll try to reproduce in Stuttgart on September, 5th. I'll reopen as soon as I can reproduce.
