### ISSUE TITLE
Studies of JabRef: something to learn?

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1864]
@JabRef/developers :
I have just updated the list of papers citing JabRef: https://github.com/JabRef/jabref/wiki/JabRef-in-the-media

Now that JabRef 3.6 is out, I thought you may lack of activities :smile: .
Suggestion: look at these papers to find out new ideas about usage and programming in JabRef.

**Comment by matthiasgeiger** [comment]
#Wow... I wasn't aware that JabRef has been analyzed this much :wink: 
Thanks for collecting the information!

However, at least my time is limited so I can't promise to have a look at the papers immediately. :disappointed: 

I'll close this, as it isn't an "issue" in the real sense.

**Comment by mlep** [comment]
I did not know where to put it...

**Comment by matthiasgeiger** [comment]
No problem ;-)

You can send such stuff to the developers@jabref.org mailing list.
