### ISSUE TITLE
File name generation preferences

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1871]
In the `Import` preference tab there is a setting `File format pattern` under the heading `Default PDF file link action`. However, the result of this field is used for any automatic file name generation, so maybe it makes sense to move it to the `File` tab?

As far as I can tell there is no information in the help files related to this either.

Related: in #1869 I included some code so that if the generated file name from the layout is empty, the BibTeX key is used as fall back and if that is empty, `"default"` is used. This to avoid file names of the type `".pdf"`.

**Comment by oscargus** [comment]
Relates to #1416 and #1092

**Comment by Siedlerchr** [comment]
Yeah, I always wondered about this, too. Would make sense to move it to files tab.  See #1092  for my idea of having either one common field or two separate ones.

**Comment by stefan-kolb** [comment]
Thanks for your report.! We recently migrated the UI of JabRef to JavaFX. Therefore, we need to reevaluate all issues targeting the old Swing UI. Feel free to reopen, if the problem persists with the new JavaFX UI.
Download the current development version at http://builds.jabref.org/master/
