### ISSUE TITLE
Group names are matched wrong

### ISSUE THREAD

**Issue by cogsys-michael** [JabRef/jabref#1873]
JabRef version 3.6 (also 3.5) on Ubuntu 14.04

Group membership of entries is stored in the groups-field. Groups are identified by their name. Multiple groups are separated by commas. It seems that during matching (for marking group memberships in the groups interface), group names are split at commas and spaces. These facts lead to the following undesired behaviours:
1. If an entry's group field contains 'a b' it is considered a member the groups 'a', 'b', and 'a b'.
2. If an entry's group field contains 'a' it is considered a member of the groups 'something'/'a' and 'anything'/'a'.
3. If an entry's group field contains 'a b', you can remove it from group 'a'. Resulting in the entry being considered a member of 'b' (in combination with 2., possibly in some other branch of the group tree).

This behaviour might completely break the group-entry relations.

Steps to reproduce:
1. download and open [jabref_bug.bib.txt](https://github.com/JabRef/jabref/files/440689/jabref_bug.bib.txt)
2. Add the entry 'demo' to the group 'some rating'/'very good'
3. Observe, that the entry now belongs to all four (leaf) groups
4. Remove the entry from group 'some rating'/'good'
5. Observe that the entry now only belongs to group 'other rating'/'very'

**Comment by cogsys-michael** [comment]
Possible duplicate of #1495.

**Comment by matthiasgeiger** [comment]
Hi Michael!
Thanks for your report. I can confirm the behavior - and yes, you are right this a quite serious problem (and also related to #1495 but not exactly a duplicate).

Regards
Matthias

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
