### ISSUE TITLE
Citations in Libreoffice can't be copied to another part of the same document.

### ISSUE THREAD

**Issue by ph0boss** [JabRef/jabref#1878]
JabRef version  on 

Actually I'm not sure if that is a problem with libreoffice or jabref. There was a thread discussing the issue on https://sourceforge.net/p/jabref/mailman/message/34627238/ but I found no bug reported. There was also a bug reported in LO, I'm not sure if it is the same.
https://bugs.documentfoundation.org/show_bug.cgi?id=63553&redirected_from=fdo
Steps to reproduce:
1. Insert a citation somewhere in the text
2. Copy text and citation
3. Paste in another part of document
4. No formatting is preserved. Text is pasted as plain text, loosing citation formatting

When text is cut-pasted formatting is preserved, but only for the first paste.
When text is copy-pasted to another document the formatting is preserved, but only for the first paste.
Versions tested: Jabref 3.6, LO 5.1.4.2 , LO 5.2.0.4, Fedora 24 64bit.

```
Put the excerpt of the log file here
```

**Comment by stefan-kolb** [comment]
I can reproduce the issue, even still with LibreOffice 5. However, I'm not sure what can be done here because this seems to be an Office issue rather than a JabRef one. If we do not use these citations fundamentally wrong it is a (still present) problem of LibreOffice.

**Comment by stefan-kolb** [comment]
@JabRef/developers Maybe we should file another bug report at LibreOffice?!

**Comment by ph0boss** [comment]
Done.
https://bugs.documentfoundation.org/show_bug.cgi?id=106599
