### ISSUE TITLE
Installer Code Signing

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#1879]

**Comment by stefan-kolb** [comment]
@koppor Any news?

**Comment by stefan-kolb** [comment]
We are just targeting Windows code signing with this certificate? Install4j says we need a Developer ID Application something from Apple to sign the code...

**Comment by stefan-kolb** [comment]
This certificate will only work for Windows? As we don't have an Apple code signing certificate?!

**Comment by stefan-kolb** [comment]
https://docs.travis-ci.com/user/encrypting-files/

**Comment by koppor** [comment]
Note that only one encryption key can be stored per time: https://docs.travis-ci.com/user/encrypting-files/#Encrypting-multiple-files

**Comment by stefan-kolb** [comment]
```
 travis login --org --github-token $ && travis encrypt-file jabref-2016.p12 --add
```

**Comment by stefan-kolb** [comment]
http://stackoverflow.com/questions/6654543/how-to-create-pfx-with-my-chain-of-certificates

**Comment by stefan-kolb** [comment]
http://charles-blog.appspot.com/2012/11/Export-Private-Key-from-pkcs12-file

**Comment by koppor** [comment]
Thanks to @stefan-kolb, a test build is available at https://builds.jabref.org/cert/

**Comment by matthiasgeiger** [comment]
Is working only partially...:

![grafik](https://cloud.githubusercontent.com/assets/676652/20681115/62d9c8d8-b5a2-11e6-97ec-3dc3c838a016.png)

The UAC dialog shown after clicking "Trotzdem ausführen" looks good (except that only `Oliver Kopp, Open Source Developer` is mentioned but not directly JabRef 😕

**Comment by koppor** [comment]
Mentioning me instead of JabRef is the condition of the [Certum Open Source Code Signing](https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml).

Quoting from their conditions, I received via Email:

> OPEN SOURCE CODE SIGNING CERTIFICATES MAY BE ISSUED ONLY TO PRIVATE INDIVIDUALS !

> When issuing a certificate the "Open Source Developer"  term is automatically added to the "CN" (Common Name) field. This is a necessary condition to obtain a certificate.

**Comment by stefan-kolb** [comment]
Yeah, I don't see why this means it is only partially working. The name is intentional.
