### ISSUE TITLE
CHANGELOG Merge Issues

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#188]
Merging almost always causes conflicts with the CHANGELOG file. This article proposes two solutions: https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/

Should we implement one of them? @koppor @stefan-kolb @lenhard @matthiasgeiger

**Comment by stefan-kolb** [comment]
`CHANGELOG merge=union`
