### ISSUE TITLE
New database is marked as changed

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1881]
If a completely new database is created there should be no confirmations required to close it.

**Comment by matthiasgeiger** [comment]
This is already the case? 

*File* -> *New Database* 

*- do nothing - *

*File* -> *Close Database*

No message is shown.

**Comment by oscargus** [comment]
Not in my development version... Just noticed it, so I think it is something quite recent.

**Comment by Siedlerchr** [comment]
I can confirm this behaviour in the dev version on Windows, to

**Comment by oscargus** [comment]
My bad. I'll add a PR fixing this in a minute.
