### ISSUE TITLE
Integrity check should report year not consisting of 4 numerals

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1897]
Field year should consist of four numerals (year = {1986}). Other formats are allowed (year = {about 1986}), but should be reported by Check integrity.
EDIT: Because these formats are allowed, it should be not reported by Check integrity.

**Comment by Siedlerchr** [comment]
Yeah, but the official bibtex spec defines it a bit more detailed bibtex spec: http://ftp.fernuni-hagen.de/ftp-dir/pub/mirrors/www.ctan.org/biblio/bibtex/base/btxdoc.pdf

> Generally it should consist of four numerals, such as 1984, although the stan-
dard styles can handle any year whose last four nonpunctuation characters are
numerals, such as ‘(about 1984)’.

**Comment by grimes2** [comment]
Interesting, but then this is not allowed: '(1984 but I am not sure)' or '(1984a)'

**Comment by grimes2** [comment]
My interpretation is: The Year Checker should check for "last nonpunctuation character should not be an alphabetic character". I would like to implement this.

**Comment by Siedlerchr** [comment]
You're welcome :) should be relatively simple to check if the last 4 chars of the field string are numeric.
Go for it :+1:
