### ISSUE TITLE
Improve consistency of file related actions in menus and entry editor

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#190]
Dear Jabref team,

I worked a bit with the most recent beta version 2.11b4 and one thing that struck me was the fact that the menu items related to external files are still a bit of a mess. Currently there are no less than 8 menu items dedicated to files:

1. Search > Synchronize File Links (Ctrl + F4)   [also allows to check if files exist)
2. Tools > Open Folder
3. Tools > Open File
4. Tools > Open PDF or PS
5. Tools > Find unlinked files
6. Tools > Automatically set file links
7. Tools > Legacy Tools > Synchronize PDF
8. Tools > Legacy Tools > Synchronize PS

I'd suggest:
- [x] Removing option 4 (since it is covered by 3).
- [x] Removing option 7 and 8
- [x] Move synchronize file links to a group with option 1, 5 and 6. 

All these suggestions are cosmetic, but in my opinion they would make for a cleaner and more user friendly interface.

**Comment by matthiasgeiger** [comment]
Hi lc9275,

thanks for your feedback! 

Your suggestions are reasonable and partly we are already working on some points for the next major release (v2.80). However there are some aspects we have not yet thought about, which we will discuss.

Regards,
Matthias

**Comment by simonharrer** [comment]
Option 7 and 8 are removed in master.

**Comment by matthiasgeiger** [comment]
Additional aspects in entry-editor:
- Action triggered by icon: "Automatically set file links" (left side always visible)
- "Auto" and "Download" Buttons for "file" field
