### ISSUE TITLE
Newline character should be set in database properties

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#1902]
Currently, the newline character is set in the preferences. However, the original reason for allowing this was to ease the use of version management systems, see https://sourceforge.net/p/jabref/feature-requests/857/ (commented in the code). Unfortunately, it means that the current solution is user (or even computer) dependent, rather than database dependent. Hence, it would make sense to have an override setting in the database properties tab.

Also see the (brief) discussion at https://github.com/JabRef/help.jabref.org/pull/64

I know that these things are also possible to handle in the version management system, but not exactly how. It would be excellent if someone with more knowledge could add a few line to the corresponding help page (again, see https://github.com/JabRef/help.jabref.org/pull/64 ).

Unfortunately, the impact on the code may be quite significant as this is now handled through `OS.NEWLINE`. Instead, it would be a database-specific property handled through `MetaData`(?) in some cases.

**Comment by stefan-kolb** [comment]
This can/should be managed by the settings in the version control system not on the side of JabRef.
