### ISSUE TITLE
Main table non updated properly when newly assigning an article to a group

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#1903]
JabRef 3.7dev--snapshot--2016-08-31--master--4913665
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:
1. Start with a database that contains a few articles and a few groups
2. Assign an article to a group, to which it had not been assigned previously
3. The article is assigned to the new group (confirmed by checking the respective bibtex field), but it is not displayed properly in the "main table/database view" of Jabref. Usually, all entries of a group have a white background, while those which do not belong to the group, have a grey background. Furthermore, all entries of a group are shown at the top of the "main table/database view", while non-members are shown below the group members. The new entry, however, is not displayed in such a way - instead, it is still treated as a non-member, i. e. it has a grey background and it is not grouped together with other group members at the top of the "main table/database view".
4. If another group is selected and then again the previous group, the newly assigned article is displayed correctly as the member of the group with white background and on top of non-group members.

**Comment by lenhard** [comment]
The issue still persists in 4.0, as reported here: #2974

**Comment by lenhard** [comment]
I think it's time that this issue gets more attention. We have a few duplicate reports, which means that it does annoy people.

I'll add it to the 4.0 milestone now (since that gives attention), although it might be the case that it will be moved to 4.1.

**Comment by lenhard** [comment]
@AEgit I think I have fixed this. 

Can you please try out the version available here http://builds.jabref.org/maintable-update/ and let me know if the group update works for you now_

**Comment by AEgit** [comment]
@lenhard: Thank you very much, this does indeed fix the problem.

JabRef 4.0-dev--snapshot--2017-08-16--maintable-update--69f717336
Windows 10 10.0 amd64 
Java 1.8.0_141

There's only a minor issue left (but I think it's not related to this bug fix): When selecting an item in the main table, the associated group (or rather the number giving the number of associated items) should be coloured. This is not the case with newly assigned items. It does appear, however, that this feature is generally buggy - also items that have not been newly assigned to a group are not always coloured in the group panel (sometimes it works, sometimes it does not). Should I open a new bug report for this?

**Comment by lenhard** [comment]
@AEgit Thanks, I am glad to hear that :-)

Regarding coloring: It also occurred to me that this doesn't work reliably. We should track this in a different issue, so please open a new one. And it would be perfect if you could report one or two ways to reproduce a coloring error.

**Comment by AEgit** [comment]
Cheers ;)

The new bug report can be found here:
https://github.com/JabRef/jabref/issues/3112
