### ISSUE TITLE
Shortcut for Check Integrity

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1908]
For my workflow "Check integrity" gets more and more important. I wish I could have a (default) shortcut (keybinding) for that action.

**Comment by lenhard** [comment]
The keybindings have recently been reworked by @JabRef/stupro Maybe this is something that can easily be added?

Do you have a suggestion for which keys would be appropriate for such a binding?

**Comment by stefan-kolb** [comment]
@koppor talks to @JabRef/stupro for a sensible hotkey.

**Comment by mairdl** [comment]
I suggest a shortcut like `CTRL + F8`.

F8 is currently used to `Cleanup entries`. These 2 functions seem to be related so it would make sense to combine them. What do you think about my idea?

**Comment by koppor** [comment]
:+1:

**Comment by matthiasgeiger** [comment]
Fixed with #2198
