### ISSUE TITLE
More features when right clicking in text field

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#191]
Now it is possible to access the case changers when right clicking in a text field. Would there be an obvious drawback if one could access "HTML -> LaTeX" and "Unicode -> LaTeX" (and eventually the reverse process) from a separate sub menu?

**Comment by oscargus** [comment]
Seems like I had a bit of time tonight, so I implemented this: https://github.com/JabRef/jabref/pull/200

**Comment by lenhard** [comment]
#200 is merged, so we can close this issue.
