### ISSUE TITLE
Integrity Check: check for field edition

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1912]
Official bibtex spec:
The edition of a book - for example, “Second”. This should be an ordinal, and should have the first letter capitalized.
A check for "should have the first letter capitalized" in the field edition should be added. I would like to implement this.

**Comment by Siedlerchr** [comment]
You could also check if the biblatex spec says something related forthe  fields:
https://www.ctan.org/pkg/biblatex?lang=de

**Comment by Siedlerchr** [comment]
You have to treat bibtex and biblatex mode different. (there should be a flag or whatever to indicate this somewhere related to the bib database code)
Especially for the edition field, biblatex says  in section   2.2.2

> field (integer or literal)
The edition of a printed publication. This must be an integer, not an ordinal. Don’t say edition={First} or edition={1st} but edition={1}. The bibliography style converts this to a language dependent ordinal. It is also possible to give theedition as a literal string, for example “Third, revised and expanded edition”.

**Comment by grimes2** [comment]
I think, this issue can be closed.
