### ISSUE TITLE
Refactor Integrity Checker

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#1916]
Follow up from #1914 
As we have a nice functional interface (checker ) we could use lambdas instead of the private static class things... Would clean up the code, for example it would look like this:

```java
  Checker myTypeChecker = (BibEntry entry)->{
        Optional<String> value = entry.getField(FieldName.PAGES);
        if (!value.isPresent()) {
            return Collections.emptyList();
        }

        if ("proceedings".equalsIgnoreCase(entry.getType())) {
            return Collections.singletonList(new IntegrityMessage(
                    Localization.lang("wrong entry type as proceedings has page numbers"), entry, FieldName.PAGES));
        }

        return Collections.emptyList();
    };
```

**Comment by tobiasdiez** [comment]
You are right, checker as private static classes are ugly. 
In my opinion, all these checker should live in separate files (accompanied with their own test files). Otherwise Checker.java gets to big.

Most of these checker only work on one field and thus it may be worthwile to introduce a new abstract class:
````java

abstract class FieldChecker implements Checker {

        FieldChecker(String field) {...}

        abstract List<IntegrityMessage> checkValue(String value);

        @Override
        public List<IntegrityMessage> check(BibEntry entry) {
                Optional<String> value = entry.getField(field);
                if (!value.isPresent()) {
                    return Collections.emptyList();
                } else {
                    return checkValue(value.get());
                }
        }
}
````

**Comment by Siedlerchr** [comment]
Yeah I already thought about that, too. A dedicated class for each checker would have been my idea, too.

**Comment by stefan-kolb** [comment]
+1 for extracting them to separate classes with explicit tests!

**Comment by oscargus** [comment]
Separate classes has been the decision for a few months, yes.

**Comment by grimes2** [comment]
> Yeah I already thought about that, too. A dedicated class for each checker would have been my idea, too.

> @grimes2 Would you be interested in doing this?

Yes, I'll open a new issue for that.

**Comment by Siedlerchr** [comment]
- [ ] Create StartsWitchUpperCaseChecker with Fields to check  as parameter
- [ ] Look for other checkers to unify

Linking follow up issue from here: https://github.com/JabRef/jabref/pull/1930#issuecomment-246172096

**Comment by stefan-kolb** [comment]
@Siedlerchr Will you work on the remaining two bullet points? Kind of gets lost here in the thread so either we extract them to a new issue or they get resolved in time.

**Comment by Siedlerchr** [comment]
@stefan-kolb  Better extract them to a new issue.  Atm I am still busy finalizing #1899, so I do not know if I find time for it in the next days.
