### ISSUE TITLE
Importer/Exporter for MODS format

### ISSUE THREAD

**Issue by tschechlovdev** [JabRef/jabref#1920]
Since JabRef has an exporter for the MODS format, it would be nice to have also an importer for this format.
There is a XML schema available [here] (http://www.loc.gov/standards/mods/mods-3-6-announcement.html), so I think it would be the best to write the importer with a JAXB parser.
But then it could happen, that exporting in MODS format and importing in MODS format are not working correctly. So I think the exporter should also be rewritten with a JAXB parser.

If there are no arguments against it, I would take care of this.

**Comment by koppor** [comment]
+1

**Comment by boceckts** [comment]
I will close this as everything seems to be done.
