### ISSUE TITLE
# in file names is now escaped with \\

### ISSUE THREAD

**Issue by ajbelle** [JabRef/jabref#1936]
JabRef Ver 3? (not sure when JabRef made the changes) on Win7.

per issue #1188 and @tobiasdiez I understand code has been added to escape # within the bib file  to avoid JabRef crashing. I unfortunately have **#** in the legacy filesnames I inherited from Endnote (example follows)

`  file        = {://wu caltech 1961 #97-2-1400983301/wu caltech 1961 #97-2.pdf:PDF},`

has been changed by JabRef to  
`  file        = {://wu caltech 1961 \\#97-2-1400983301/wu caltech 1961 \\#97-2.pdf:PDF},`

Obviously this now prevents the links being followed :-(  I would not use # in filespecs myself but there are at least a hundred in my .bib file.

These links (of strange format to me) link to the _legacy_ pdf directory. These still work when the links are correct, which is great.

**Comment by oscargus** [comment]
A note to whoever tries to solve this. There is a `FieldProperty` called `VERBATIM` which among others are used to avoid checking for an odd number of `#`. This probably should be used here as well to not escape the field (same thing with e.g. the url field which may contain `#`).

**Comment by koppor** [comment]
This somehow refs  #574.

**Comment by Siedlerchr** [comment]
Probably refs #1970 , too.
@oscargus  Is the file field marked as verbatim already?

**Comment by oscargus** [comment]
@Siedlerchr yes, I think so. Check InternalBibtexFields (unless it was added in the big refactoring PR not yet merged...).

**Comment by Siedlerchr** [comment]
I close this for the moment due to inactivity... :zzz:
