### ISSUE TITLE
Help pointing on wrong web pages

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#1937]
JabRef version 3.6 on Debian 8 Jessie
Steps to reproduce:

1. click on Help inside Jabref
2. A browser opens at [https://help.jabref.org/it/](https://help.jabref.org/it/)

Obviously, this depends on the fact that my operating system is in Italian and that there is no documentation in this language.
Could you make sure that, in the absence of documentation in a particular language, Jabref points to the documentation in, for ex., English?

Thank you very much for your attention,
Domenico

**Comment by lenhard** [comment]
Thanks for reporting! Your suggestions of using the english localization as default for help pages sounds reasonable.

**Comment by Siedlerchr** [comment]
Refs: https://github.com/JabRef/help.jabref.org/issues/41
Maybe it would be nice to create a redirect to the default eng page as 404 page 
https://help.github.com/articles/redirects-on-github-pages/

**Comment by lenhard** [comment]
To implement redirection, we would have to add redirect statements for all unavailable localizations to all english help pages, am I right?

Sounds pretty doable, overall.

**Comment by Siedlerchr** [comment]
@lenhard  Two step solution: First copy all english pages to all languages (don't replace existing ones). 
So when you click a link from an japanese hel file about exports and the target pages does not yet exist, it automatically shows up the english page. 

2nd step: Additionally just modding the 404 error file to set up a redirect to the english index.

I will look into that. I also wanted to check some css things.

**Comment by Siedlerchr** [comment]
@bartsch-dev  Could you add a redirect for that case, too? Or should we link to default en index in help?

**Comment by bartsch-dev** [comment]
If you create an empty `it` directory and run the python script it will create the index and all the redirects for to English pages.
Currently you have to create the includes for new languages manually.
The main index you also have to edit yourself.

**Comment by koppor** [comment]
Done in https://github.com/JabRef/help.jabref.org/commit/e0a9ba70c99289f87018914eef944d7c6cda38e8 and also added an initial [README.md](https://github.com/JabRef/help.jabref.org/blob/gh-pages/_scripts/README.md). Currently, I get page build failures, but I get

> A file was included in `/_layouts/default.html` that is a symlink or does not exist in your `_includes` directory. For more information

Currently, no idea, how to solve that

This is only a quick hack. We should tell JabRef to direct to localized help pages only if the help page is available during development time of that JabRef version. Reason: There will surely no new languages added that quickly the next months/years. Thus, I vote for taking back the quick fix and to fix JabRef (@matthiasgeiger?).

**Comment by bartsch-dev** [comment]
You have to add `link-to-main-it.html` and `link-to-toc-it.html` in the `_includes` folder (just copy and rename the English one).

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version.
Please try a development build from <http://builds.jabref.org/master>
The fix will be included in the next release.

@Doc73 I assume, you have no time to provide (and eventually maintain) the Italian help (help.jabref.org/it/)? Neverthelss, may I ask for translations for our user interface? It is currently not that well translated in Italian: https://github.com/JabRef/jabref/wiki/Translating-JabRef-Interface#italian - More information about the translation is available at https://github.com/JabRef/jabref/wiki/Translating-JabRef-Interface.

**Comment by Doc73** [comment]
@koppor 
I'm very sorry, but I have no time and, above all, I'm not a programmer and I do not really know how to contribute to the translation. I simply do not know where to start. :cry:

**Comment by koppor** [comment]
You don't need to be a progammer! - Nearly all of our translators are no programmers! :innocent: 

For the huge help, we have a howto at : https://github.com/JabRef/help.jabref.org/blob/gh-pages/CONTRIBUTING.md

For translating the menus, it is very easy:

1. Click on https://github.com/JabRef/jabref/blob/master/src/main/resources/l10n/Menu_it.properties
2. Click on the pencil
3. Edit directly in the browser
4. Click on "propopose file change" (as shown at https://github.com/JabRef/help.jabref.org/blob/gh-pages/CONTRIBUTING.md#saving-the-changes)
5. Then, click on "create pull request"

**Comment by Doc73** [comment]
Ah, ok! It's not so difficult.
I can not promise anything, but I put in my bookmarks the pages of the localization.

Thank you very much! :+1:
