### ISSUE TITLE
Rework syncLang.py

### ISSUE THREAD

**Issue by bartsch-dev** [JabRef/jabref#1939]
After #1933 has been finished & merged I want to rework `syncLang.py`.
E.g. when there are unambiguous Duplicates (e.g. one has no or both have the same Value) I want to solve them automatically.

I plan to have a Gradle task which fixes obsolete, missing, and unambiguous  duplicate properties and sorts all Properties in all language files the same order as they are in the English File.
A task which prints all empty properties and one which prints a Summary of how many empty properties are in one file (`checkTranslationsSummary`).

Do you need a Task which prints all problems but doens't solve them?

@JabRef/developers Which Gradle tasks do you need?

**Comment by oscargus** [comment]
It would be great if a task could generate the summary in md table format and automatically update a suitable Wiki page and that this is executed on the master.

**Comment by mlep** [comment]
Like the table on this wiki page: https://github.com/JabRef/jabref/wiki/Translating-JabRef-Interface

**Comment by bartsch-dev** [comment]
I just wrote a script for the help pages including a status output, something like this for the localization files? 
(jabref/help.jabref.org#77 in the first post, just scroll down a little)
