### ISSUE TITLE
Wrong error message for No File Directory 

### ISSUE THREAD

**Issue by ChristopherHackett** [JabRef/jabref#1949]
JabRef version JabRef 3.6 on Mac OX X 10.11.6

Steps to reproduce:

1. Ensure that "Main file directory" is empty under File in preference 
2. Attempt to download file using "get full text"
3. Note that the message tells you to go to the wrong location (see screen shots) as this setting is not under external programs

<img width="550" alt="screen shot 2016-09-11 at 00 09 50" src="https://cloud.githubusercontent.com/assets/1075126/18414067/e2d2b30a-77b4-11e6-9a92-c0c152e663ea.png">

<img width="1033" alt="screen shot 2016-09-11 at 00 09 58" src="https://cloud.githubusercontent.com/assets/1075126/18414069/ef9be2f0-77b4-11e6-865e-96b192685a75.png">

**Comment by koppor** [comment]
Related: https://github.com/JabRef/jabref/pull/1921
