### ISSUE TITLE
URL with encoded html characters is shown as a violation regarding the integrity check

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1958]
JabRef version 3.7dev (latest) on Windows 10

Steps to reproduce:

1. Have an entry with url field `http://www.thinkmind.org/index.php?view=article&amp;articleid=cloud_computing_2013_1_20_20130`
2. Check integrity
3. As url has `&amp;` inside it, an integrity check violation is shown. But the url is perfectly valid and no integrity check violation should be shown.

**Comment by Siedlerchr** [comment]
Integrity check for url should be disabled generally. At least in biblatex all URL related fields are treated as verbatim

**Comment by oscargus** [comment]
There is `FieldProperty.VERBATIM` that can be used as there are more fields which are verbatim in BibLatex.

**Comment by stefan-kolb** [comment]
Like this? ` if (!InternalBibtexFields.getFieldProperties(field.getKey()).contains(FieldProperty.VERBATIM)) {`
