### ISSUE TITLE
Improve JavaFX about dialog

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#1959]
Follow up of #1947

- [x] clicked link should stay blue (see screenshot below)
- [x] is it possible to link https://github.com/koppor/keep-a-changelog/blob/master/CHANGELOG.md#unreleased instead of CHANGELOG.md. During a release, we will replace that by something like `https://github.com/JabRef/jabref/blob/master/CHANGELOG.md#36---2016-08-26`
- [x] Spell "Used libraries" instead of "Used Libraries".
- [x] Prefix "MIT License" by "License:" and remove the year or change to " - Copyright (c) 2003 - 2016"
- [x] Add a dot (`.`) after "get involved" as this is a complete sentence and the question before ends with a question mark.

![grabbed_20160912-133251](https://cloud.githubusercontent.com/assets/1366654/18434450/7779b01a-78ed-11e6-825c-eddd28d46b7b.png)

I know, I might be picky, but the about dialog is seen by many users and should be good.

**Comment by grimes2** [comment]
For authors and developers it is important to know the actual snapshot version (latest commit hash) of JabRef.
![about](https://cloud.githubusercontent.com/assets/15456836/18435241/50a98226-78f2-11e6-862c-a8310b796d82.png)
Here the version is truncated. An idea is to add the complete version as a tooltip.

**Comment by koppor** [comment]
Why not just simply in the next line with normal font size?
"dev info: snapshot--2017..."

The tool tip is too hidden for me.

**Comment by boceckts** [comment]
@koppor discussion moved to #1962 with new screenshots and new way to find the link to the changelog of the used version.
