### ISSUE TITLE
UTF8 text decoding issue in About dialog

### ISSUE THREAD

**Issue by cr333** [JabRef/jabref#1963]
The About dialog shows some names incorrectly (see screenshot). It looks like the UTF8 bytes are not interpreted correctly.

![jabref-3 6-about](https://cloud.githubusercontent.com/assets/8134692/18440697/0453ad9c-7902-11e6-8ad4-d0c477bd97b3.png)

This is with JabRef 3.6 on Windows 10 with Java 1.8.0_101.

**Comment by Siedlerchr** [comment]
Thanks for your report. Fortunately this issue has been already resolved in the latest development version.
You can try out the latest development version from here: http://builds.jabref.org/master/
Refs #1954
