### ISSUE TITLE
JabRef on OS X hangs when use Magic Wand to generate BibTeX key

### ISSUE THREAD

**Issue by murrayE** [JabRef/jabref#1966]
JabRef version3.6 on Mac OS X 10.11.6 is frequently, but not always, freezing when, after entering required fields and some optional fields, I return to Required fields and click the "Magic Wand" to try to generate a BibTeX key. Int freezes to the point that I cannot even bring up the OS X Dock.

I'm new to JabRef (please be gentle!) and so don't know where the log file is stored.

Note: I did see the discussion at http://tex.stackexchange.com/questions/327128/jabref-3-6-impossible-to-generate-bibtex-keys, which is evidently for a Windows version, whereas my platform is OS X. And I see no preference allowing  "automatic generation of BibTex keys when they are empty", such as is mentioned in that post.

**Comment by koppor** [comment]
@chochreiner @steimlfk Can you have a look?

Can you send us an example entry and your BibTeX key generator pattern?

**Comment by alexandre-a-denis** [comment]
I've got the same problem with exactly the same setup and found out it was coming from this entry: [http://dblp.uni-trier.de/rec/bib2/conf/ijcai/DingZLD15.bib](http://dblp.uni-trier.de/rec/bib2/conf/ijcai/DingZLD15.bib)

**Comment by grimes2** [comment]
> JabRef 3.7dev--snapshot--2016-09-13--master--952ca8e
> windows 10 10.0 amd64 
> Java 1.8.0_101

Confirmed.

DBLP conf/ijcai/2015 is an invalid BibTeXkey, because of the whitespace.

**Comment by bertvv** [comment]
I have a similar (the same?) issue on Linux, JabRef 3.6, openjdk version "1.8.0_102"

What I see is that the user interface becomes unresponsive when the Bibtexkey field has the focus and a non-default key pattern (in my case `[authEtAl][year]`) was chosen.

**Comment by koppor** [comment]
@bertvv In any database or a certain one? Does it also happen at [complex.bib](https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/complex.bib)?

**Comment by grimes2** [comment]
JabRef 3.7dev--snapshot--2016-09-14--master--560a545
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. File > New Bibtex database
2. Bibtex > New entry > Article
3. author: a, year: 2000, crossref: a
4. Save database
5. Restart Jabref
6. Mark entry
7. Ctrl-G (Autogenerate Bibtexkey)
8. Freeze

**Comment by bertvv** [comment]
@koppor It happens in any BibTeX file. I reproduced the error with complex.bib, but also special-fields.bib (2 entries, author field filled out), and articlewithtitle.bib (1 entry, author field entry empty).

I've attached a full thread dump while Jabref was frozen: [jabref-issue-1966-thread-dump.txt](https://github.com/JabRef/jabref/files/474455/jabref-issue-1966-thread-dump.txt)

**Comment by lenhard** [comment]
I can reproduce the bug with the instructions from @grimes2 

From the thread dump by @bertvv, this looks very much like a deadlock of the event dispatch thread (Swing) and the Guava event bus. That means it might be the fault of the newly added event system (which would totally not surprise me).

@JabRef/stupro should have a look at this.

**Comment by Braunch** [comment]
@bartsch-dev  asked me to test if the bug would occur on my machine. I followed the steps described in https://github.com/JabRef/jabref/issues/1966#issuecomment-247287933 on Ubuntu, but I was not able to reproduce.

**Comment by meneguzzi** [comment]
Autogeneration of bibtex keys seems to continue being a problem in MacOS, even if it does not crash, whenever I try to do this in more than one entry, it basically stops after one or two entries:

<img width="500" alt="image" src="https://github.com/JabRef/jabref/assets/4698576/701e9f80-ef98-419d-a74f-eb5a3307e735">

**Comment by meneguzzi** [comment]
Should I create a new issue for this?

**Comment by ThiloteE** [comment]
@meneguzzi a new issue would be good. JabRef 3.6 is ancient.

**Comment by koppor** [comment]
@meneguzzi You can reference this issue when creating a new one. Thus, we have some back-references. Moreover, it woiuld be nice if you could provide an example bib entry where it does not work - or is it "random" and "all" entries seem to cause issues?

**Comment by koppor** [comment]
No worries. For all of us this is kind of a hobby project. -- I could craft JabRef debug Versions so that bibtex keys are put in the debug log so that tracing is simpler. No need to spend time on a minimum example. I know that crafting MWEs is very hard. I once spend 10 hours only to learn that I used an older development Version of minted 🙈

**Comment by meneguzzi** [comment]
Done, if anyone has another OS to try my bibfile, please go ahead.

**Comment by koppor** [comment]
There was no new issue created. I reopen this issue and modify it to match the new input.

**Comment by meneguzzi** [comment]
So, I did create issue #9996 , and in this case, the failure is silent rather than hanging JabRef.

**Comment by Siedlerchr** [comment]
This issue was about a very old JabRef version and the follow up issue is closed already

**Comment by koppor** [comment]
@meneguzzi and @murrayE - We assume the issue is really solved. If not, please report back.

**Comment by meneguzzi** [comment]
Hi everyone, I can confirm that the problem is no longer showing up.

**Comment by meneguzzi** [comment]
Just for reference, here is one library that caused the problem, in case anyone wants to do regression. 
[testlib.txt](https://github.com/JabRef/jabref/files/14916308/testlib.txt)
