### ISSUE TITLE
Reuse query parser

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1975]
Instead of parsing a search query using a custom grammar we should reuse some existing query parser. For example, [Lucene's query parser](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) with [QueryParser.parse](https://lucene.apache.org/core/4_0_0/queryparser/org/apache/lucene/queryparser/classic/QueryParserBase.html#parse%28java.lang.String%29).

Triggered by https://github.com/JabRef/jabref/issues/1633#issuecomment-238762667. 
- Description of Lucene's syntax: http://www.solrtutorial.com/solr-query-syntax.html and https://lucene.apache.org/core/2_9_4/queryparsersyntax.html
- Lucene provides a few classes which let us modify the search syntax: https://lucene.apache.org/core/4_1_0/queryparser/index.html?org/apache/lucene/queryparser/flexible/core/parser/SyntaxParser.html
- Or we use the default Lucene syntax: https://lucene.apache.org/core/4_0_0/queryparser/org/apache/lucene/queryparser/classic/QueryParser.html

**Comment by simonharrer** [comment]
Be aware that a lot of groups rely on the current search query grammar, and they will break if this is changed.

**Comment by Le-wi** [comment]
So introducing the new parser would require to migrate all the old queries as well?

**Comment by tobiasdiez** [comment]
The only groups effected are the "search based groups". I doubt that many users use them (and then probably only experienced users). Thus, I would say that displaying a warning dialog of the kind "some groups need to be updated by hand to work properly" is sufficient. @JabRef/developers opinions?

**Comment by koppor** [comment]
Steps:

1. Dive into our powerful search syntax: https://docs.jabref.org/finding-sorting-and-cleaning-entries/search
2. Compare with lucene
3. Evaluate whether a switch is possible
4. Get rid off ANTLRv4
5. Add an ADR

**Comment by koppor** [comment]
@DominikVoigt implemented a lucene parsing at https://github.com/JabRef/jabref/pull/6799. This could be a good basis to solve this issue.

**Comment by koppor** [comment]
The follow-up ticket https://github.com/koppor/jabref/issues/341 should also be linked here.

**Comment by koppor** [comment]
Decision note: During GSoC 2024 we found out that JabRef's search syntax covers more than existing search syntax. Moreover Apache Lucene syntax was strange. --> https://github.com/JabRef/jabref/pull/11803
