### ISSUE TITLE
OS X 10.11: 2.11b4 app broken

### ISSUE THREAD

**Issue by ddauer** [JabRef/jabref#199]
On OS X v10.11 El Capitain with 
`$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)`

v2.11b3: Launch via double click: works fine
v2.11b4: Launch via double click: does not work. Console shows error: `10/1/15 21:44:49.036 com.apple.xpc.launchd[1]: (jabref.JabRef.204512[793]) Service exited with abnormal code: 1`
v2.11b4: Launch via `java -cp "JabRef.app/Contents/Java/*" net.sf.jabref.JabRefMain`: works fine.

So, my guess is that app packaging is somehow broken.

**Comment by koppor** [comment]
We are well aware of that. See #149. I tested on a Mac machine with Java 8 installed. 2.11b4 does not work, but 2.80 does. 2.80 will be released shortly after 2.11. Therefore, we are not going to fix the 2.11. I know, that sounds hard, but you know, limited resources etc.

I will leave the issue open until v2.80 is released to prevent further duplicates.
