### ISSUE TITLE
Unnecessary other field tab

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1996]
JabRef 3.7dev--snapshot--2016-09-16--master--629c3f0
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. File > New Bibtex database
2. Bibtex > New entry > Article
3. Entry editor optional field volume: a
4. Save database
5. File > Switch to Biblatex mode
6. File > Switch to Bibtex mode
7. Unnecessary "other field" tab (with doublet field volume)

**Comment by Siedlerchr** [comment]
Fixed with #2002
