### ISSUE TITLE
Standard look and feel doesn't work

### ISSUE THREAD

**Issue by NikoKrause** [JabRef/jabref#2003]
Hey,

I'm using JabRef 3.6 on Linux Mint 18 Cinnamon.

The Standard look and feel doesn't work. 
Here is a screenshot, with `Standard look and feel: com.sun.java.swing.plaf.gtk.GTKLookAndFeel` enabled
![bildschirmfoto vom 2016-09-17 11-53-01](https://cloud.githubusercontent.com/assets/8415124/18607490/29ce0da4-7cce-11e6-99e9-5d824002eff0.png)

And here is a screenshot with `use other look and feel: com.sun.java.swing.plaf.gtk.GTKLookAndFeel` enabled, which is the same as the Standard version:
![bildschirmfoto vom 2016-09-17 11-54-21](https://cloud.githubusercontent.com/assets/8415124/18607505/73cf0b56-7cce-11e6-9178-539409522ced.png)

It looks different.

**Comment by Siedlerchr** [comment]
Did you restart JabRef after changing the look and feel?


2016-09-17 12:02 GMT+02:00 NikoKrause <notifications@github.com>:

**Comment by NikoKrause** [comment]
Also I can't scroll to the color choosers, when I `use other look and feel: com.sun.java.swing.plaf.gtk.GTKLookAndFeel `

See red arrows at the bottom of this picture:
![bildschirmfoto vom 2016-09-17 12-04-38](https://cloud.githubusercontent.com/assets/8415124/18607540/69decbda-7ccf-11e6-82e9-7d0cf09a161e.png)

**Comment by NikoKrause** [comment]
@Siedlerchr 
Yes, I restarted JabRef. Before and after checking the box

**Comment by Siedlerchr** [comment]
@JabRef/developers  Anyone of you using Linux Mint and can confirm this?

**Comment by mlep** [comment]
About "can't scroll to the color choosers": I can confirm this under Mint LMDE Cinnamon, both with the default Look&Feel and the javax.swing.plaf.metal.MetalLookAndFeel
And it is not only limited to the color chooser: same with other items (e.g. Entry table columns, BibTeX key generator)

**Comment by stefan-kolb** [comment]
I think GTK look and feel might be disabled if you use linux and openjdk. There was a problem which urged us to skip it as default L&F. Maybe this is related. The code for this is somewhere in the JabRef startup class.

**Comment by stefan-kolb** [comment]
```java
              if (System.getProperty("java.runtime.name").contains("OpenJDK")) {
                    // Metal L&F
                    lookFeel = UIManager.getCrossPlatformLookAndFeelClassName();
                    LOGGER.warn(
                            "There seem to be problems with OpenJDK and the default GTK Look&Feel. Using Metal L&F instead. Change to another L&F with caution.");
                }
```
