### ISSUE TITLE
Merging and moving conversion files

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#201]
I've started to look into the Unicode and HTML converters (and some related String conversion methods) and found some things which I will discuss here to see if you have any opinions or good ideas.

* My general plan is to move all this into https://github.com/JabRef/jabref/tree/master/src/main/java/net/sf/jabref/logic/util/strings

* The main file would be https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/importer/HTMLConverter.java . Any reason not to move it to the above location?

* In https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/util/strings/StringUtil.java there are two methods capitalizeFirst and toUpperFirstLetter which appears to do the same thing as UpperCaseChanger in https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/logic/util/strings/CaseChangers.java . Any reason to keep the first two?

* https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/exporter/layout/format/FormatChars.java and https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/openoffice/OOPreFormatter.java are very similar. Main different is that the latter can convert {\emph} etc to italic and bold. Is there really a use case for this? I would guess that it may be used for particular style files in OpenOffice and will look more into this, but does anyone know?

Probably more to follow...

**Comment by simonharrer** [comment]
- Location package is fine.
- No objections. Good idea. But you will have to move the LayoutFormatter interface as well. As our goal is that the logic Package does not have any imports from the GUI package. GUI --> LOGIK, but not the other way round. 
- Good view: toUpperFirstLetter and capitalizeFirst are completely the same. So we can merge them. But the CaseChangers are not related as they now work on Latex Strings whereas the other methods do work on simply strings only. I would leave them apart.
- I have no opinion on this.

**Comment by oscargus** [comment]
Just a small update:

I started moving some of the needed files to logic.string and extracted the huge conversion map from HTMLConverter with #806.

**Comment by lenhard** [comment]
@oscargus What is the status of this issue?

**Comment by oscargus** [comment]
I think it can be closed. With the recent improvements in many related areas, at least everything stated above is obsolete. :-)
