### ISSUE TITLE
Add cleanup for escaping comments

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2011]
JabRef 3.6
windows 7 6.1 amd64 
Java 1.8.0_66

Steps to reproduce:
1. import from pubmed the ID 27623067:
2. run pdflatex with a file where this used
3. failure to compile due to % sign in the abstract: error message ! File ended while scanning use of \field.

files to reproduce the error can be found here:
http://b-kleine.com/technical/tex_20160918/

edit: this error must have happened very recently since files imported on 2016-09-14 imported correctly.

**Comment by Siedlerchr** [comment]
Thanks for your report! As this is not only a pubmed related thing, but a more general problem. 
So, I suggest creating a CleanUpAction to automatically encode %-signs.

**Comment by koppor** [comment]
This CleanUpAction should also be included in the `doPostCleanup` method of all fetchers. Refs https://github.com/JabRef/jabref/pull/1929#r78319240 @tobiasdiez

**Comment by tobiasdiez** [comment]
Note that biber writes on this topic

> [P]lease note that biber will not attempt to sanitise the content of bibtex data sources. That is, don’t expect it to auto-escape any TeX special characters like ‘&’ or ‘%’ which it finds in, for example, your TITLE fields. It used to do this in earlier versions in some cases but as of version 0.9, it doesn’t because it’s fraught with problems and leads to inconsistent expectations and behaviour between different data source types. In your bibtex data sources, please make sure your entries are legal TeX code.

I think JabRef should not escape special characters, especially not always on writing. The cleanup operation is ok because then the user has to decide what he wants to do. For the same reason as above, I would not include it in the `doPostCleanup` operation of the pubmed fetcher.

**Comment by lenhard** [comment]
I strongly support @tobiasdiez on this. A long time ago, we decided the following development rationale for JabRef: "If in doubt, do as biber does". 

Moreover, this cleanup should go into `LatexCleanupFormatter`, I think. This formatter already takes care of escaping and fixing LaTeX-related stuff.

**Comment by bernhard-kleine** [comment]
Has this issue been resolved? With JabRef 3.7dev--snapshot--2016-09-25--medlineutf8--95f7f84, windows 7 6.1 amd64, Java 1.8.0_66 I still ran into the % trap.

**Comment by lenhard** [comment]
@bernhard-kleine As there are no other comments here since my last one seven days ago: no, it has not.

Also, we will not do this automatically for importing pubmed entries (since the error is really on the side of pubmed which produces broken bibtex).
