### ISSUE TITLE
Rework used encodings

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2013]
I think JabRef sometimes uses encodings which are a bit counter-intuitive or where a better alternative might be available. Triggered by https://github.com/JabRef/JabFox/issues/33.

In this issue, I try to collect the current usage of encodings so that we get an overview. Feel free to edit this list.

| Operation | Currently used | Suggestion |
| --- | --- | --- |
| Import from cmd (`--importToOpen`) | File -> Default | Argument -> File -> DB -> UTF8 |
| Fetcher | ? | Fetcher decides -> File -> UTF8 |
| Export | ? | ? |
| ? | ? | ? |

Legend:
- File: as JabRef comment %Encoding: ....
- Default: JabRefPreferences.getDefaultEncoding()
- Argument: via the command line or by asking the user
- DB: the encoding of the DB where the entries are imported to / exported from

**Comment by lenhard** [comment]
One thing that we talked about earlier with regard to the `BibtexParser`: The encoding supplied in the bib file (%Encoding) is currently completely ignored by JabRef. The parser explicitly ignores it upon reading a file and it is stored nowhere. On writing the file, the encoding set in the preferences is used.

I want to note that this is nothing we "broke", JabRef has always done that as far as I can recall.

**Comment by tobiasdiez** [comment]
Its ignored by the parser but not by the importer: https://github.com/JabRef/jabref/blob/ee08252a495c8951206201829651a2c320893735/src/main/java/net/sf/jabref/logic/importer/fileformat/BibtexImporter.java#L43

**Comment by lenhard** [comment]
I see. My knowledge seems to be confined to the deeper parts of our parsing stack ;-)

**Comment by tobiasdiez** [comment]
I don't think that we currently have open issues related to the encoding. Although the used encoding is still sometimes a bit mystic, I will close this issue now.
