### ISSUE TITLE
Several variables are not passed to the NSIS installer

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#202]
e.g. ${COMPANY}, ${URL}, ${REGKEY}
This might cause problems with uninstallation?!

We just pass VERSION in build.gradle:
`                commandLine project.ext.nsisExec, "-DVERSION=${version}", "${projectDir}/buildres/nsis/setup.nsi"`

**Comment by matthiasgeiger** [comment]
uninstallation works for 2.11b4

**Comment by stefan-kolb** [comment]
Found the definitions, my bad!

**Comment by koppor** [comment]
Maybe this should be commented somehow somewhere that someone else doesn't fall in the same trap? Maybe https://github.com/JabRef/jabref/wiki/Code-Howtos?
