### ISSUE TITLE
Quality-> Integrity does not accepted ranges R56-70 or S45-46

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2025]
JabRef 3.6
windows 7 6.1 amd64 
Java 1.8.0_66

Steps to reproduce:

1. Import from medline PMID 24791920
2. Run Check Integrity
3. S87--96 (S stands for supplement) is labelled as "should contain a valid page range"

Likewise PMID 24928941 which is a review R75--96 is labelled as "should contain valid page range"
"päpstlicher als der Papst" I dare not translate that but I know people will understand. There is some hypercritical algorithm in the integrity checker.

**Comment by mlep** [comment]
Well, BibTeX-wise, the message is true becauxe, according to BibTeX reference manual (http://distrib-coffee.ipsl.jussieu.fr/pub/mirrors/ctan/biblio/bibtex/base/btxdoc.pdf): 
```
**pages** One  or  more  page  numbers  or  range  of  numbers,  such  as 42--111
or 7,41,73--97 or 43+ (the `+' in this last example indicates pages following
that don't form a simple range).  To make it easier to maintain Scribe-compatible  databases,  the  standard  styles  convert  a  single  dash  (as  in 7-33)  to  the  double  dash  used  in  TEX  to  denote  number  ranges  (as  in 7--33).
```
See issue https://github.com/JabRef/jabref/issues/416
