### ISSUE TITLE
JabRef locks up and hangs after clicking Generate BibTeX button

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#2026]
JabRef version 3.6 on Ubuntu 16.04, using Oracle java 1.8.0_45. Running on the Mate desktop. 

This only happens sometimes, but it already happened several times to me, I could not figure out a pattern of what may cause it.

I entered the authors, title, journal name and year in a new article entry, then clicked the "Generate BibTeX"  button. This made JabRef become unresponsive: no interaction with either the mouse or the keyboard was possible, closing the window also did not work. However, the window was repainted when dragging it around the screen. 
The only way to get out of this was to kill the process and restart JabRef. 

I looked at jconsole and the program seemed to be active: there was a constant allocation of memory and garbage collection going on without the heapsize increasing noticably overall. Also no deadlocks were detected.

**Comment by Siedlerchr** [comment]
Thanks for your report! Could you please test with the current master version from here? http://builds.jabref.org/master/
There have been some fixes regarding freezes lately so it might be that your problem is alredy resolved.

PS: You should update your java version, for ubuntu I can recommend using the webupd8 ppa:
http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

**Comment by johann-petrak** [comment]
Is there a way to get pre-compiled development snapshots? 
The link on the downloads page leads to an error page:
https://builds.jabref.org/master/

**Comment by lenhard** [comment]
Probably related: #1892

**Comment by lenhard** [comment]
@johann-petrak What is the status here? Does your problem still appear when you use the most recent development version of jabref?

**Comment by lenhard** [comment]
I am closing this, since @johann-petrak seems to have lost interest and we expect the problem to be solved in master.

Feel free to reopen if the problem re-appears.

**Comment by johann-petrak** [comment]
Sorry for the late feedback - I do not use generate key that often because I usually paste an existing bibtex entry for the papers I add. I did use generate a few times and never had any problem, so this may be fixed.
However, this time I always saved the database directly before generating the key which also may have an influence. 
Thanks!

**Comment by johann-petrak** [comment]
I am still/again getting rather frequent freezes but without using the generate key feature. I cannot really figure out what action the freeze may be related to, but it is always in the context of editing/adding entries (I frequently paste raw bibtex into the Bibtex source tab). This happens with version 3.8.2 under Ubuntu, using java 1.8.0_45.

**Comment by johann-petrak** [comment]
Have not got this since I am using version 5.0-dev.
However I think there may be an explanation for the "freeze": if bibtex key already exists, a modal dialog pops up. It could have happened on my dual monitor setup on Ubuntu that the dialog pops up BEHIND one of the other windows so it does not get noticed. The main window would then appear unresponsive.
