### ISSUE TITLE
Add deprecated JavaDoc

### ISSUE THREAD

**Issue by bartsch-dev** [JabRef/jabref#2032]
Add to each deprecated field/method/class a deprecated tag in the JavaDoc (additionally to the annotation) with a hint to which field/method/class to use instead.
#### Background:

The Annotation is for the compiler, javadoc for the developer and I do not want to dive into the code to find a replacement for the deprecated code.

**Comment by jfilhoGN** [comment]
Hi @stefan-kolb , my name is João and I am a student of Computer Science - Brazil.

We have a free software development discipline and would like to be contributing to JabRef, I'm reading about the issue and the general idea is to put annotation on classes that are obsolete?

**Comment by stefan-kolb** [comment]
I did not create this issue, but as far as I know it is about annotating old JabRef methods that are replaced by new ones but not migrated entirely yet.

**Comment by koppor** [comment]
The current state of the Java code is that some methods are marked with `@deprecated`, but the JavaDoc does not contain information about what to do. This requires in-depth knowledge of the code.

@jfilhoGN Depending on the goals of your project, we can shape something. We have starting pointers at https://help.jabref.org/en/FAQcontributing#i-am-a-programmer

Besides that, we have a variety of tasks to choose from:

- increase test coverage to ~40%
- rewrite the GUI using JavaFX and the MVP pattern
- fix minor issues listed at https://github.com/koppor/jabref/issues
- work on something with high impact: https://github.com/jabref/jabref/issues?q=is%3Aissue+is%3Aopen+label%3Aasking-for-a-pull-request

**Comment by matthiasgeiger** [comment]
Regarding the topic of this issue: What @bartsch-dev meant is that we also should use additional JavaDoc comments for deprecated methods: 
```java
/**
* @deprecated This methode is deprecated; use {@link someOtherMethod()} instead
**/
@Deprecated
public void someDeprecatedMethod() {
//...
}
```

**Comment by jfilhoGN** [comment]
right. Thanks @stefan-kolb @koppor and @matthiasgeiger , I will be researching issues in the links that you have passed.

At first I thought the solution would be to add @SuppressWarnings ("deprecation") on classes and methods that were obsolete (eclipse recommends me to do this), but I was wrong.

**Comment by Siedlerchr** [comment]
Thanks for your interest in JabRef! Please consider creating a branch
instead of working on the master branch. That makes things a whole lot
easier for your and us.
More information on how to setup your workspace can also be found here :
https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

2016-12-06 14:00 GMT+01:00 João Martins Filho <notifications@github.com>:

**Comment by tobiasdiez** [comment]
I think most deprecated methods are now properly annotated -> closed.
