### ISSUE TITLE
Cannot download from Medline

### ISSUE THREAD

**Issue by stevenlbressler** [JabRef/jabref#2036]
JabRef version  on 

Steps to reproduce:

1. ...
2. ...
3. ...

```
Put the excerpt of the log file here
```

**Comment by stevenlbressler** [comment]
I am using JabRef 3.6 on a mac (os x version 10.8.5). I have been downloading references from Medline for years without any issues, but now I get the following message in response to any web search fetch:
No references found

and the JabRef status remains as:
Fetching Medline by term

even after the search. This problem occurs even for fetches that I know should produce a reference list.

**Comment by Siedlerchr** [comment]
Thanks for your report! 
There has been some work on the Medline fetcher a while ago, But I did not know if it was merged into 3.6 @zellerdev  Could you please check that?

**Comment by stevenlbressler** [comment]
Thanks for responding so quickly. Are you a jabref developer? I am a
long-time jabref user, and it has been great to me overall. Anyway, I don't
know how to check the Medline fetcher in 3.6, but it started to work for me
after my posting. This leads me to think that the problem somehow had to do
with my university internet connection (although other web-based
applications were still working).

Steven L Bressler, PhD
Interim Director and Professor
Director of Ph.D. Program
Center for Complex Systems & Brain Sciences
Florida Atlantic University

**Comment by Siedlerchr** [comment]
@stevenlbressler Good to know that it works again! Maybe it was a temporary problem at the server side of Medline. So I'm closing this here.
Yes, I am one of the Developers (since a couple of months).

**Comment by stevenlbressler** [comment]
#2038 pertains to the same issue and should also be closed.

Steven L Bressler, PhD
Interim Director and Professor
Director of Ph.D. Program
Center for Complex Systems & Brain Sciences
Florida Atlantic University
