### ISSUE TITLE
JabRef Web search fetch

### ISSUE THREAD

**Issue by stevenlbressler** [JabRef/jabref#2038]
I am using JabRef 3.6 on a mac (os x version 10.8.5). I have been downloading references from Medline for years without any issues, but now I get the following message in response to any web search fetch:
No references found

and the JabRef status remains as:
Fetching Medline by term

even after the search. This problem occurs even for fetches that I know should produce a reference list.

Steps to reproduce:

1. open jabref
2. enter keyword in web search box
3. click Fetch

Log file:
![screen shot 2016-09-22 at 11 41 34 am](https://cloud.githubusercontent.com/assets/22373634/18755438/3a8e4dbc-80ba-11e6-8eef-0f0ed4fe8d2d.png)

**Comment by Siedlerchr** [comment]
I close this one here and we continue discussing the problem in #2036
