### ISSUE TITLE
Automatic text replacement while typing second author's name

### ISSUE THREAD

**Issue by Fjanks** [JabRef/jabref#2049]
JabRef version 3.6 on openSUSE 13.2

Steps to reproduce:

This happens only if the name of the first author already exists in another article of the same database. Lets assume there is an article with the author "J. Borges". 
Then I create a new BibTex entry and start typing in the author-field "J. Borges and J. Wilkins". At the moment I arrive at "J." some text before is automatically replaced and the final result is "J. BorJ. Borges. Wilkins".

**Comment by Siedlerchr** [comment]
Thanks for your report! I think you refer to the autocompletion  feature of authors. 
And I could reproduce the behaviour in the actual dev version.
As a workaround you can disable/change the behaviour of the autocompletion in Settings -> Entry Editor.

**Comment by AEgit** [comment]
I can confirm this bug - it has been around for a while, but I was never sure, whether I could reproduce it, so I did not report it.

**Comment by stefan-kolb** [comment]
Autocompletion is a bit of a problem right now. I tried to fix it a while ago but this needs a rewrite. Dunno the issue number right now but this was reported earlier I think.

**Comment by stefan-kolb** [comment]
I'd suggest to disable autocompletion for now. @JabRef/developers Also, we should probably do this by default?!

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by Fjanks** [comment]
Yes, I just tried the latest development version with activated autocompletion and I can confirm that the bug is fixed. Thank you!

**Comment by AEgit** [comment]
I also think that the bug is fixed now (although I'm not completely sure, as it was always difficult to trigger it in a reproducible way). Thanks!
