### ISSUE TITLE
Paste localization strings fails

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2058]
> EXECUTE gradlew -b localization.gradle generateMissingTranslationKeys TO
> PASTE THIS INTO THE NON-ENGLISH LANGUAGE FILES

Task "generateMissingTranslationKeys" not found in root project jabref.
What am I doing wrong?

**Comment by koppor** [comment]
Thank you for your report. This is a duplicate of  #2029 and is fixed, because we merged #2031.

Could you update to latest master and execute `gradlew localizationUpdate`?
