### ISSUE TITLE
Regression with Unnecessary other field tab (#2002)

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2064]
I've observed a regression with #2002. Under certain conditions other fields are not displayed. It's better to undo the commit. Should I add a new pull request to revert the changes?

**Comment by Siedlerchr** [comment]
Okay, I would say: First create a new PR. Then you could investigate this issue in more detail. Maybe you find the conditions and can add a check then for it.

**Comment by grimes2** [comment]
Steps to reproduce:

1. File > New Biblatex database
2. Bibtex > New entry > Article (First entry)
3. Bibtex > New entry > Article (Second entry)
4. (Second entry) language field: a
5. File > Switch to Bibtex mode
6. Restart Jabref
7. Doubleclick on First entry
8. Click on Second entry
9. No other field tab with language field

**Comment by Siedlerchr** [comment]
Okay, I merged your undo PR in. Would you like to investigate if you could find a solution for the problem?

**Comment by grimes2** [comment]
Investigating the issue shows, that this is a more general problem. Selecting another entry in main table doesn't update the Entry Editor properly. A similar problem as in Invalid field content lost when selecting different entry #1866.

**Comment by grimes2** [comment]
I found no solution for the problem. But I have a proposal for the "other fields" tab in Bibtex mode. This tab could show all the pure Biblatex fields of a given type. So the "other fields" tab has many fields. A common case is, that some fetched entries contain Biblatex fields. In this case, these fields are reliably displayed also in Bibtex mode.
> An entry can also contain other fields, which are ignored by standard bibliography styles.

(Bibtexing - official spec)

**Comment by grimes2** [comment]
This issue can be closed. The incorrect cache mechanism was removed in #2075. Other fields are now displayed correct.
