### ISSUE TITLE
Website for development snapshots is down

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2073]
The website used to distribute development snapshots appears to be down. I think it has been down all day long, as I had seen this issue already a couple of hours ago but initially thought that it was just something temporary:

https://builds.jabref.org/master/

**Comment by Siedlerchr** [comment]
Is a https problem, use the http version just remove the https and it works
fine.
@koppor

2016-09-26 23:28 GMT+02:00 AEgit <notifications@github.com>:

**Comment by AEgit** [comment]
Ah yes, thanks indeed!

**Comment by koppor** [comment]
I've setup [Let's Encrypt](https://letsencrypt.org/) using [this](https://certbot.eff.org/all-instructions/#debian-8-jessie-nginx) and [this](https://loune.net/2016/01/https-with-lets-encrypt-ssl-and-nginx/) howto. Now, it works again with end-to-end encryption thanks to the [Electronic Frontier Foundation](https://www.eff.org/) and [ScaleWay](https://www.scaleway.com/).

**Comment by AEgit** [comment]
Thank you very much! Now https is again available.
