### ISSUE TITLE
Java bug on macOS sierra

### ISSUE THREAD

**Issue by barefeg** [JabRef/jabref#2076]
There is a scrolling bug specific to macOS 10.12:

https://bugs.openjdk.java.net/browse/JDK-8166591
https://youtrack.jetbrains.com/issue/IDEA-158500

Not sure if there's an official fix. Just wanted to let you guys know.
In case you want to try some solutions I can verify if it works as I'm having the issue.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
Looks like we cannot really do a lot about this but wait for a JDK fix.

**Comment by AEgit** [comment]
@barefeg: Can you confirm that the updated JDK solved this issue? In that case we could close this issue.

**Comment by barefeg** [comment]
@AEgit Is this in the pre bundle of a new build of JabRef? I don't have a separate JDK installed on my system.

**Comment by AEgit** [comment]
Oh, I've only been checking the links you provided and it seems that the issue that was reported there was solved in the new version of the OpenJDK (8u122):

https://bugs.openjdk.java.net/browse/JDK-8166591

See also here:
https://youtrack.jetbrains.com/issue/IDEA-158500

**Comment by barefeg** [comment]
It might. But I'm using the bundled version of Java that comes in JabRef so this has to be updated with the fix. I checked the latest snapshot of JabRef and it still has the problem.

**Comment by AEgit** [comment]
I see.
@stefan-kolb: Can you do something about this? It appears you only need to update the bundled version of Java and this problem should be solved,

**Comment by stefan-kolb** [comment]
Will be done with the next release!

**Comment by stefan-kolb** [comment]
I just uploaded the new `112` patch updates of the JRE.
Please try the latest build from http://builds.jabref.org/master.

**Comment by barefeg** [comment]
It didn't solve the issue.

**Comment by stefan-kolb** [comment]
We cannot do anything about this because it's a JDK issue. It is solved for v9 but not backported to v8. Maybe this will be done in the future. Unfortunately, we just have to wait.

**Comment by Siedlerchr** [comment]
@stefan-kolb  I just looked at it seem like it will be included in  8u121/8u122 
https://bugs.openjdk.java.net/browse/JDK-8166591

**Comment by stefan-kolb** [comment]
Also IntelliJ released an updated Java JDK: https://youtrack.jetbrains.com/issue/IDEA-158500

**Comment by sebroeder** [comment]
Since nobody posted the actual error log, yet, this is what I am seeing for JabRef 3.7 on macOS 10.12.1:

```
2016-12-01 18:46:55.685 JavaApplicationStub[3406:428707] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
2016-12-01 18:46:55.687 JavaApplicationStub[3406:428671] -[AppDelegate download:didFailWithError:] [Line 199] Download failed! Error - The resource could not be loaded because the App Transport Security policy requires the use of a secure connection. http://files.jabref.org/jres/macosx-amd64-1.8.0_112_unpacked.tar.gz
```

Apple forces SSL/TLS for network connections in many parts of their networking frameworks since macOS 10.12. Since the resource `http://files.jabref.org/jres/macosx-amd64-1.8.0_112_unpacked.tar.gz` is also available over `https`, this error could probably be fixed easily by changing the download URL to `https://files.jabref.org/jres/macosx-amd64-1.8.0_112_unpacked.tar.gz`.
