### ISSUE TITLE
Namespace in jaxb should not rely on internal java com.sun classes

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2078]
Follow up for the problem in #1989 
@tschechlovdev 

Atm the commit was reverted in #2077 

I found this discussion here: 

http://stackoverflow.com/questions/2326107/what-happened-to-jaxbs-namespaceprefixmapper-in-jdk6u18

**Comment by tschechlovdev** [comment]
So if I get it right, I should not use the NamespacePrefixMapper any more. There is an interface for an [JAXBNamepsacePrefixMapper](http://mvnrepository.com/artifact/com.googlecode.jaxb-namespaceprefixmapper-interfaces/JAXBNamespacePrefixMapper/2.2.4). Can this be used?

**Comment by Siedlerchr** [comment]
Hm, from what I see you are using a very old version of jaxb and when I see it correctly, since several versions it is already included in java8 
https://docs.oracle.com/javase/8/docs/api/javax/xml/bind/JAXB.html

And also have a look here,https://jaxb.java.net/2.2.11/docs/release-documentation.html#a-2-2-11 
There seems to be a sample somewhere which inlcudes some namespace stuff

Look also here, this is a newer gradle plugin

https://github.com/ewerk/gradle-plugins/tree/master/jaxb2-plugin

**Comment by tschechlovdev** [comment]
Hm ok. If I see right then it's the easiest way is to add a ``@XmlNs`` to the package-info.java.
That would look like the following:
```    
// Package level annotation
    @javax.xml.bind.annotation.XmlSchema (
      xmlns = {
        @javax.xml.bind.annotation.XmlNs(prefix = "po",
                   namespaceURI="http://www.example.com/myPO1"),

        @javax.xml.bind.annotation.XmlNs(prefix="xs",
                   namespaceURI="http://www.w3.org/2001/XMLSchema")
      )
    )
```
This seems to work for me. 
I've also found a [maven-plugin](https://java.net/projects/jaxb2-commons/pages/Namespace-prefix) that seems to do this. But I coulnd't find one for gradle.

**Comment by Siedlerchr** [comment]
Yeah, I would go with the Namespace annoation, if it works, its's good.

**Comment by tschechlovdev** [comment]
@Siedlerchr This can be closed now, right?
