### ISSUE TITLE
Unify Import/Open and Export/Save

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2080]
Currently JabRef has four different menu options for saving and opening files.
- open / save as: bib files
- import/export: other files

And then there are even more for saving/exporting only the selected entries.
I think this is more confusing than helpful. I would propose one "open" and one "save as" regardless of the file format (with a checkbox in the dialog to only save the selected entries).

Triggered by http://discourse.jabref.org/t/export-a-part-of-my-database/220/4.

**Comment by grimes2** [comment]
I prefer the current save/export in Jabref.
A detailed discussion about save/export in gimp:
http://gui.gimp.org/index.php/Save_%2B_export_specification

**Comment by stefan-kolb** [comment]
After reading the Discourse link, I think this user is an exception with near no knowledge of computer programs 😄 I would also keep it the way it is at the moment. Clear open/save for bib files and import/export logic for other file types.

**Comment by Siedlerchr** [comment]
I agree with @stefan-kolb  and @grimes2  We should let it to have the clear semantics. Therefore I would close this atm.
