### ISSUE TITLE
Integrate new EN help pages in the GUI

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2083]
New help pages where created (see https://github.com/JabRef/help.jabref.org/pull/94 and https://github.com/JabRef/help.jabref.org/pull/98). Help buttons should now be added to allow for direct access.
The help pages are related to:
- [ ] Edit -> Set/clear/rename fields (file: SetClearRenameFields.md)
- [ ] Search -> Replace string (file: ReplaceString.md)
- [ ] BibTeX -> Customize entry types (file: CustomEntryTypes.md)
- [ ] Quality -> Check integrity... (file: CheckIntegrity.md)
- [ ] Quality -> Cleanup entries... (file: CleanupEntries.md)
- [ ] Quality -> Merge entries... (file: MergeEntries.md)
- [ ] Quality -> Synchronize file links... (file: SynchroFileLinks.md)
- [ ] Quality -> Find unlinked files... (file: FindUnlinkedFiles.md)
- [ ] Tools -> New subdatabase based on AUX file (file: NewBasedOnAux.md)
- [ ] Options -> Manage external file types (file: ExternalFileTypes.md)
- [ ] Options -> Manage protected terms (file: ProtectedTerms.md)
- [ ] Options -> Customize key bindings (file: CustomKeyBindings.md)

**Comment by stefan-kolb** [comment]
I quickly checked the PRs. All (most?) of them are just stubs indicating that a documentation is missing for these features. I'm not sure if we want to direct users to missing pages...

**Comment by matthiasgeiger** [comment]
Was more or less "decided" in https://github.com/JabRef/help.jabref.org/issues/88 - which is fine for me, too.

**Comment by stefan-kolb** [comment]
Ok, if you think so. It just doesn't help the user.

**Comment by koppor** [comment]
IMHO pressing on "edit" is a lower border than creating an md file on the
right place.I hope, more users will contribute...

**Comment by lenhard** [comment]
Just that I understand this correctly: So, we want to add GUI elements at several places that open a particular help page? Kind of like the help button now, but at many positions and with particular pages as targets?

What kind of UI elements should that be? An additional button? Maybe a tool tip?

**Comment by mlep** [comment]
My suggestion is to do as in https://github.com/JabRef/jabref/issues/1767 : Adding an help button to each pop-up window, pointing to the relevant help page. 12 help pages ==> 12 help buttons

**Comment by koppor** [comment]
@lenhard Yes, that was the idea. Not sure whether and how we did it. The idea is to direct the users to the help pages and that one of them will start editing. Maybe, this issue can be flagges as "on-hold", because no one will currently work on that, but it is a good idea.
