### ISSUE TITLE
Glitch in main menu edit

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2090]
JabRef 3.7dev--snapshot--2016-09-28--master--6ba3b9a
windows 10 10.0 amd64 
Java 1.8.0_101

Two consecutive separators (case: special table fields not checked in preferences)

![glitch](https://cloud.githubusercontent.com/assets/15456836/18938876/39836302-85fc-11e6-9227-c0e8a1ca738b.png)

**Comment by Siedlerchr** [comment]
Fixed with #2093
