### ISSUE TITLE
Timestamp: "Today" and "None" not clickable

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2092]
JabRef version 3.6 on Linux Mint LMDE

In the entry editor, right next to the timestamp field, an icon triggers the pop-up of a calendar. 
Under the calendar, `today` and `none` are displayed:

![timestampnone](https://cloud.githubusercontent.com/assets/6931104/18946904/37bbff40-8631-11e6-8c81-99c22b9f1127.png)

I believe these were clickable (to input today's date, or to clear the field).

**Comment by matthiasgeiger** [comment]
Yes. They are clickable on Windows...

**Comment by lenhard** [comment]
@mlep: Which JRE are you using?

**Comment by mlep** [comment]
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by lenhard** [comment]
@mlep: Thanks! Is this OpenJDK or Oracle?

**Comment by matthiasgeiger** [comment]
I think this output is generated by Oracle ;-)

**Comment by mlep** [comment]
I confirm: Oracle

**Comment by lenhard** [comment]
@matthiasgeiger As far as I know, that output is also generated by OpenJDK? But maybe this has changed. How should the output by OpenJDK look like?

Back to topic: Darn, I was hoping we could blame this on OpenJDK...

**Comment by Siedlerchr** [comment]
Tested under Ubuntu 16.04 with Xfce Desktop and oracle jre
Also it says it's `javax.swing.plaf.metal.MetalLookAndFeel`, it should be GTk looks.

They are clickable, and clicking on today works correctly. Clicking on none does nothing

**Comment by mlep** [comment]
Checking again:
**Correction:** only click on `none` does nothing.
Like @Siedlerchr, using `javax.swing.plaf.metal.MetalLookAndFeel`

**Comment by matthiasgeiger** [comment]
Mhmm okay. "none" is also not working as it is to be expected in windows: It closes the Calendar, but a date previously set is not removed.
