### ISSUE TITLE
Empty modal error box when saving database with parsing error

### ISSUE THREAD

**Issue by giacomociani** [JabRef/jabref#2104]
JabRef version 3.6 on Windows 10

Steps to reproduce:

1. Open Jabref
2. Create a database
3. Add an entry (I used article)
4. Save the database (if you skip this step, the problem does not occur. See later.)
5. Open the "{} Bibtex Source" editing tab
6. Insert an extra comma just after the last one (the one closing the last field). Other mistakes may work as well; I have not tried.
7. Click on the "save" button on the toolbar.

At this point, in addition to a "legitimate" error box signaling the inconsistency, another empty one appears that prevents any further action (see attached graphics). Jabref must be terminated forcefully.
Note that, as mentioned in step 4, if the database has not been saved before, the "save as" dialog box appears instead of the empty error box, and the user can proceed regularly by saving the database first, and responding to the error message then.
![jabreferror](https://cloud.githubusercontent.com/assets/3365569/18994837/a094ea1a-86f7-11e6-9e05-48f12bdbc85e.PNG)

**Comment by grimes2** [comment]
Confirmed. I try to fix this.
