### ISSUE TITLE
Entry preview not updated properly

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2105]
JabRef 3.7dev--snapshot--2016-09-30--latex-free-fields--0ee1d17
windows 10 10.0 amd64 
Java 1.8.0_101

Select a group that contains articles
1. Perform a search
2. One of the articles within that group is found by the search and is selected (indicated in blue)
3. The entry preview of the selected article is displayed
4. If we select now another article in the same group that is also found by the search, the entry preview is not shown - it still shows the previous article. This behaviour doesn't seem to happen in a repoducible way. It could be that only newly created entries (indicated in green) are affected by this, i. e. if you switch over to a newly created entry, the entry preview of this entry won't be shown. Instead it will show the entry preview of the previous entry,
5. This does not apply to articles that are not part of the same group (indicated in grey)

This issue was first mentioned here:
https://github.com/JabRef/jabref/issues/1993#issue-177367050

Similar (but different) problems have been mentioned here:
https://github.com/JabRef/jabref/issues/1760
https://github.com/JabRef/jabref/issues/1903

**Comment by koppor** [comment]
@bartsch-dev Maybe you have time to have a look at the end of next week?

**Comment by AEgit** [comment]
Ok, so it appears that newly created entries and entries that are newly assigned to a group are affected by this behvaiour.

To reproduce it, the following steps need to be taken:

1. Select a group that contains articles/items
2. Create a new article/item in this group or assign an existing article from another group to this group
3. Select another article that is or is not part of the group: The entry preview of that article is correctly displayed.
4. Now select the newly created/assigned article: The entry preview is NOT updated properly. Instead of showing the entry preview of the selected article, the entry preview of the previously selected article is still shown.
If you select another article and then select again the newly created/assigned article, the problem persists: The entry preview of the selected newly created/assigned article is not shown. Instead, the entry preview of the article that you just selected previously is shown.
5. If you create/assign another new article to the group, it exhibits the same problems. The "old new article" (i. e. the one, that we crated at step 2) behaves now properly and shows the entry preview when selected.

**Comment by AEgit** [comment]
This bug is also present in the current master build:
JabRef 3.7dev--snapshot--2016-10-03--master--565676c

**Comment by bartsch-dev** [comment]
The issue can be reproduced even easier.

1. have at least 2 entries
-  open the entry editor and close it 
  - the preview will be rendered correctly
- select the other entry 
  - the preview will be rendered correctly
- select the first entry (the one you opened the editor with)
- the preview will not be updated

**Comment by AEgit** [comment]
I can confirm that this bug has been fixed in the following master build:
JabRef 3.7dev--snapshot--2016-10-07--master--03bc4a3

Thanks a lot!

It seems, however, that another bug was introduced. See here:
https://github.com/JabRef/jabref/issues/2136
