### ISSUE TITLE
Changing group metadata in file does not trigger warning

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2111]
master on Win 10

Steps to reproduce:
1. Open a bib file (for example complex.bib)
2. Change the name of a group in the file directly
3. Expect: message in sidebar which informs about the changed metadata (as it is the case for other metadata). Result: nothing happens

```
Put the excerpt of the log file here
```

**Comment by lenhard** [comment]
I just tested this on the recent build and when I change group naming in the file, the external changes dialog in JabRef pops up and notifies me of a "Modified groups tree".

I take it that this issue is solved and that's why I am closing it. Feel free to reopen if you disagree.

**Comment by tobiasdiez** [comment]
Wooohoo. Its nice when improvements in the general event handling fix bugs on the other end of the spectrum. I thinks its a good sign that JabRef moves in the right direction, if not every action has to handle every case but there are specialized listeners for every edge case.
