### ISSUE TITLE
Entry-based fetchers should respect BibTeX key pattern of JabRef

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2117]
JabRef 3.7dev--snapshot--2016-10-03--master--565676c
windows 10 10.0 amd64 
Java 1.8.0_101
1. Set default pattern for Bibtex key generation to [auth][year]
2. Generate a new item/article using the DOI (Ctrl+N --> DOI: mydoi --> Generate)
3. The generated bibtex key, has the following format: [auth]_[year], i. e. there's an underscore between the author's name and the year; but there shouldn't be an underscore

EXAMPLE:
Use the following doi: 10.1671/0272-4634(2007)27[316:psgesn]2.0.co;2

It generates "Huttenlocker_2007" as Bibtex key, but you would expect "Huttenlocker2007".

This behaviour only appeared after the changes made to the DOI import, which is now no longer part of the Web search. Is there another option that I haven't set or is this a bug?

**Comment by zellerdev** [comment]
I will have a look at this

**Comment by koppor** [comment]
Could you also set the focus on the input field after CTRL n - or is this
already done? 😇

**Comment by AEgit** [comment]
@zellerdev: No, it appears to be restricted to the DOI fetcher. At least the Google Scholar one doesn't show this unexpected behaviour.

**Comment by stefan-kolb** [comment]
Actually this is no bug. It is the standard behavior. The reason is that the fetcher does not use the BibTeX key pattern to generate a key but just uses the key that is fetched from the web!

**Comment by stefan-kolb** [comment]
Problem here is, if we use the BibTeX key pattern from the preferences we introduce a new dependency or tighter coupling of the fetcher with the preferences...

**Comment by tobiasdiez** [comment]
I think we need to implement a second layer around the fetcher which after-processes the fetched entries (correct cite key, apply cleanup operations, etc. pp).

**Comment by AEgit** [comment]
@stefan-kolb: But how comes this was not the case in earlier versions of Jabref? Furthermore, I'm not sure, whether it is just the key, that is fetched from the web - if I use the DOI fetcher, I ALWAYS get the abovementioned BibTex key format. If I download the BibTex entry for an article manually and then import it into Jabref, the BibTex can be the same as the one fetched by JabRef but it can also differ from it. Is that to be expected?

**Comment by stefan-kolb** [comment]
1. I don't know if this was any different before.
2. The current fetcher grabs the whole BibTeX document from the web.
3. If you download it from a different source than our fetcher it is expected. The fetcher directly gets the BibTex from the DOI url via the header `"Accept", "application/x-bibtex"`

**Comment by AEgit** [comment]
Hmmm, when downloading manually BibTex files, I usually use the website of the Journal, in which the article was published. But, who knows, it might be different from what the DOI fetcher grabs (?).

But, I'm sure, that it was different in previous versions, as I did not have to remove the underscore from, e.g. "Huttenlocker_2007", to get my preferred BibTex format, i. e. "Huttenlocker2007", when using the DOI fetcher of JabRef.

**Comment by stefan-kolb** [comment]
Actually I see that the fetcher still needs the preferences:
`return BibtexParser.singleFromString(cleanupEncoding(bibtexString), preferences);`
The implementation did not change, however.

**Comment by AEgit** [comment]
Ok, I have just checked it. When I use the following doi with JabRef 3.6, the BibTex key Huttenlocker2007 is generated (actually it is Huttenlocker2007a, as this entry is already part of my database):

10.1671/0272-4634(2007)27[316:psgesn]2.0.co;2

When I use the same DOI with JabRef 3.7dev--snapshot--2016-10-14--master--fb0990d the BibTex key Huttenlocker_2007 is generated.

Note, that in JabRef 3.6 the DOI fetcher was still part of the Web fetcher, i. e. after searching for the DOI with "DOI to BibTex" you still had accept the import of the entry. Indeed, when that menu pops up, Huttenlocker_2007 is shown as BibTex key. I guess, that is the key, that is downloaded from the web. But when I accept the import, the key is correctly modified according to my preferences.

With the new DOI fetcher, you do not longer have to accept an import - it either works, or it does not. If it does, you get the "underscore" in the BibTex key, no matter your preferences.

**Comment by stefan-kolb** [comment]
"when I accept the import, the key is correctly modified according to my preferences." Probably there was an inetrmediate step between the addition and the fetching back then. I just checked the logic of the fetcher in the Git history.

**Comment by AEgit** [comment]
Yes, I suspect that as well.

**Comment by stefan-kolb** [comment]
We need to introduce/change an intermediate class that uses the fetcher that needs to apply expected JabRef functionalities like generating the BibTeX key. The fetcher should just fetch the stuff and not apply any specific configuration changes.

**Comment by koppor** [comment]
net/sf/jabref/logic/importer/SearchBasedParserFetcher.java:63 ?

**Comment by AEgit** [comment]
JabRef 5.3--2021-01-04--10180ed
Windows 10 10.0 amd64 
Java 14.0.2

The issue appears to be now slightly different (some might consider it solved?). In an empty database the following DOI will generate the bibtex key `Huttenlocker2007`as expected:

`10.1671/0272-4634(2007)27[316:psgesn]2.0.co;2`

But if the database already contains the item `Huttenlocker2007`, then the new item `Huttenlocker_2007` is generated. That does not match the setting for keys that are generated for duplicates. Instead of `Huttenlocker_2007` the key `Huttenlocker2007a` should be generated.

So the problem is not fully solved, but is now triggered slightly differently.

**Comment by nfkruska** [comment]
I believe I am experiencing similar behavior based on using the DOI to fetch entries. I have a single, default citation key generator that follows the form `[auth]_[year]`, when I import the above DOI (pasting the DOI into my table) `10.1671/0272-4634(2007)27[316:psgesn]2.0.co;2`, jabref generates a key that contains only the year, `2007`. 

The only fix I have tried so far is to reset my jabref preferences.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
JabRef 5.6--2022-04-08--a6489cb
Windows 10 10.0 amd64 
Java 17.0.2 
JavaFX 18+12

I can confirm - the remaining issue reported in https://github.com/JabRef/jabref/issues/2117#issuecomment-754010095 appears to be fixed in the current dev version.
