### ISSUE TITLE
New Command Line Option -g

### ISSUE THREAD

**Issue by brownberry** [JabRef/jabref#212]
#### New Command Line Option -g

Offer a new command line option "-g" / "--generatebibtexkeys" that re-generates all bibtexkeys in a loaded bib-file according to the set settings. (This is ```CTRL+g``` in the GUI.)

##### Example application 

```jabref -g -i input.bib -o output.bib``` 

The new option will simplify batch-processing.

**Comment by ThomasA** [comment]
I suppose the command should be `jabref`, not `bibtex`?

**Comment by brownberry** [comment]
@ThomasA: thanks!

**Comment by lenhard** [comment]
Is implemented in master as described above. Please try out the latests build at http://builds.jabref.org/ and see if it fits your needs.
