### ISSUE TITLE
Empty error message when using DOI to Bibtex

### ISSUE THREAD

**Issue by giacomociani** [JabRef/jabref#2123]
JabRef 3.6
windows 10 10.0 amd64 
Java 1.8.0_101

Steps to reproduce:

1. open "DOI to BibTex"
2. insert the url https://doi.org/10.1364/AO.55.008256 (or just the DOI)
3. hit "fetch"
3. the result windows come up with showing continuous activity (green bar sliding left to right at the bottom) and an error message... with no message. Just a "Message" title and an "OK" button.

The paper linked by the DOI appears in the upcoming issue of Applied Optics. I did a limited number of trials with other DOIs, and the issue seems to only be coming up on some of the entries of that issue (https://doi.org/10.1364/AO.56.0000B5, for example, fetches correctly).

Not sure what the error is, and it may not be dependent on Jabref, but the issue here is the empty message box.

**Comment by matthiasgeiger** [comment]
The underlying problem is not at the side of JabRef but the crossref.org service which provides the BibTeX information for DOIs returns an error.

Using the [current development builds](https://builds.jabref.org/master) the error dialog is no longer empty but display "Invalid URL" - which still might be improved.

**Comment by stefan-kolb** [comment]
@matthiasgeiger Was this a 503 problem on CrossRef? Example is working for me.

**Comment by matthiasgeiger** [comment]
I don't remember.. it might have been an error like "unknown DOI" but I'm not Sure...

**Comment by lenhard** [comment]
Since this seems to be working again and we have a, somewhat, better error message, I am closing this now.

Feel free to reopen if the problem persists.
