### ISSUE TITLE
Usage JabRefExceptions for localized error message to be shown to the user

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#2128]
If the `getMessage()` or `getLocalizedMessage()` methods of an exception are used to show information to the user, a [`JabRefException`](https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/JabRefException.java) should be used which provides the necessary implementation to actually have localized messages.

An example are the `FetcherException`s which are thrown and caught in the various fetchers. (refs #1542)

I just commited the needed changes in the FetcherException to master (see 8db90db) - correct usage is still todo.

**Comment by lenhard** [comment]
Could you have a look at https://github.com/JabRef/jabref/wiki/Code-Howtos#throwing-and-catching-exceptions and see if this should be extended/changed? It seems that the necessary information has already been there.

**Comment by matthiasgeiger** [comment]
Yes. I've added this last fall but it was not really enforced yet. 

In most cases it is also not that relevant, but if the message of an Exception is directly shown to the user it should be localized. I'll clarify this.
