### ISSUE TITLE
New Command Line Option -f

### ISSUE THREAD

**Issue by brownberry** [JabRef/jabref#213]
#### New Command Line Option -f

Offer a new command line option "-f" / "--filelinks" that links all bibtex-entries with the bibtex-named PDFs that are found in the respective directory. (this is ```ALT+f``` for a single entry in the GUI.)

##### Example application 

```jabref -f -i input.bib -o output.bib``` 

The new option will simplify batch-processing. 

#### Feature Generalization 

Enable ```ALT-f``` not only for single entry, but for a selected subset of entries (as ```CTRL-g```).

**Comment by ThomasA** [comment]
I suppose the command should be `jabref`, not `bibtex`?

**Comment by brownberry** [comment]
@ThmoasA: thanks!

**Comment by lenhard** [comment]
Is implemented in master. However, `-f` is already taken for the `fetch` command, so I implemented it as `-asfl`: `--automaticallySetFileLinks`.

Implementing `ALT+f` for a set of entries is still open.

**Comment by lenhard** [comment]
We'll close this for now, since implementation of the remaining functionality is unlikely. If this is really wanted by multiple users, we can reopen it.
