### ISSUE TITLE
groups appear,BUT if i click on the group names, the articles don't show up.

### ISSUE THREAD

**Issue by cavonsto** [JabRef/jabref#2130]
Hi, So today i opened my XX.bak database with 700 articles, and 30 groups. 
the groups appear, and articles have the group assigned oh the BibTeX source BUT when I click on the group names, the respective articles don't show up...
This on my work computer, windows.
Two days ago I updated the jabref version on my mac. But the groups work fine there..
Any idea? 
cheers

**Comment by AEgit** [comment]
1. Could you report whicj Jabref version you are using?
2. Why are you opening the .bak (backup) file and not the .bib file?
3. What do you exactly mean by "the respective articles don't show up"? Could you describe this further and/or post a screenshot?

**Comment by stefan-kolb** [comment]
@cavonsto Can you please provide us with more details by answering the questions from @AEgit

**Comment by lenhard** [comment]
I am closing this, as @cavonsto seems to have lost interest.

Feel free to reopen if the problem persists.

**Comment by cavonsto** [comment]
@AEgit Hi, I am using the v3.8.1. Mac OS X.
So it looks like this:
when I got to the BibLatex it shows that that article belongs to a group "Groups  = {SINTHESIS}, BUT  the field GROUPS" on the left, is empty! since october this happened on my PC at work, but now also on the MAC. 
I´m really freaking out because it´s taking me forever to find the articles because it was prety much based on the groups..
I really would appreciate any help
cris

![screen shot 2017-01-25 at 19 08 13](https://cloud.githubusercontent.com/assets/22658243/22305024/e17b5b04-e331-11e6-932c-0e1b4706ad87.png)

**Comment by tobiasdiez** [comment]
You need to create a group with the name "SINTHESIS" to make use of the `groups` field. Just press the "plus" button on the left groups pane and create an static group with the correct name. Afterwards, all entries with a matching value in the `groups` field should be assigned to this new group. 

By the way, how did you created the `groups = {SINTHESIS}` field without using the groups interface?

**Comment by AEgit** [comment]
@tobiasdiez: Could the problem be related to an upgrade from an old JabRef version (e.g., v. 2.11) to a new one, as the old JabRef stored groups quite differently from newer versions (I'm just guessing)?

On a sidenote:
@cavonsto: Why are you opening the .bak file instead of the .bib file?

**Comment by cavonsto** [comment]
@AEgit I´m opening the .bak file (the database) That´s all i have. .bib i have for some individual articles. should I have both for the database?
![screen shot 2017-01-25 at 19 34 30](https://cloud.githubusercontent.com/assets/22658243/22306080/bfb14d18-e335-11e6-988b-8a5e474be98f.png)
@tobiasdiez I CREATED the groups, on the "GROUPS"field on the left (I´ve been adding groups to this for the last 4 years). but as a last resort if a go through ALL the articles and find out all the groups and re-create them, would that work? but I have sub-groups, and sub sub...
cheers

**Comment by AEgit** [comment]
Ahh, I see - you renamed your database file as .bak file. Usually you would save it as a .bib file, as the .bak file is the backup of it (that's why you have a .bak.bak file in your directory). Well it doesn't really matter (especially not on Unix systems like the Mac, that don't care much about file extensions) - this way it is just a bit confusing (at least to me).

**Comment by AEgit** [comment]
Just to be sure - You are using the release version of Jabref 3.8.1, not any other build, like e.g., the one with the revamped interface http://builds.jabref.org/groupsRework/. Because with that build (which uses JavaFX) I had similar problems.

**Comment by cavonsto** [comment]
@AEgit I just downloaded and installed again :  "Download JabRef Mac OS X - 34.36 MB | version: 3.8.1 | MD5/SHA1 signature " from https://www.fosshub.com/JabRef.html - just to be sure
- problem persists ..

**Comment by AEgit** [comment]
Hmmm ok - could you open your .bak file in a text editor, scroll to the bottom of it and make a screenshot of what you see there? If the group structure is still there, there might be ways to recover it. There should be something like "1 ExplicitGroup:Myawesomegroup\;0\;;".
If there's none, I'm afraid, I guess you would have to rebuild the groups in JabRef as @tobiasdiez explained.

**Comment by cavonsto** [comment]
![screen shot 2017-01-25 at 20 03 40](https://cloud.githubusercontent.com/assets/22658243/22307039/6d47909c-e339-11e6-80d4-0c404ef09c9d.png)
 i did a ctrlF, no ExplicitGroup... So i should get to work right?

**Comment by AEgit** [comment]
Hmmm, yes - unless you have a Backup where the groups were still present/working.

**Comment by cavonsto** [comment]
hum..but so hat changed since october was the jabref version right? my .bak looks the same, I have the info of the groups in the. bak for each article:
![screen shot 2017-01-25 at 20 08 50](https://cloud.githubusercontent.com/assets/22658243/22307264/37c54314-e33a-11e6-8668-8d227d90bb6d.png)
or you think that I lost some info here as well?

**Comment by AEgit** [comment]
Yes, the group assignment is in there - but the group structure is stored separately at the bottom of the .bib/.bak file. There should be something like (assuming that you were using explicit groups, i. e. not dynamically generated groups):

@Comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:mygroup1\;0\;;
2 ExplicitGroup:mygroup2\;0\;;
3 ExplicitGroup:mygroup3\;0\;;
4 ExplicitGroup:mygroup4\;0\;;
4 ExplicitGroup:mygroup5\;0\;;
5 ExplicitGroup:Basal_mygroup6\;0\;;
5 ExplicitGroup:mygroup7\;0\;;
6 ExplicitGroup:mygroup8\;0\;;
7 ExplicitGroup:mygroup9\;0\;;
7 ExplicitGroup:mygroup10\;0\;;
7 ExplicitGroup:mygroup11\;0\;;
}

where "mygroupx" just stands for your group names. If that's not there, then this part has been somehow lost - but I've no idea, how that could have happened

**Comment by cavonsto** [comment]
yap, statically groups manually generated. but the "funny" thing is that it stopped working on the Mac in october, and this week on the PC..
but @AEgit thank you

**Comment by AEgit** [comment]
Hmmm, yea sorry to hear that - I've no idea how that could have happened. Fortunately, you still have the group assignment, so with some work you should get back your database to how it was before. Good luck with it!

**Comment by cavonsto** [comment]
to be honest i was doubting what you said about losing info..so I got a backup from a year ago, and voila!
but since then Ive added 200 articles and created 3 groups, so this doesn't help right?
![screen shot 2017-01-25 at 20 30 15](https://cloud.githubusercontent.com/assets/22658243/22308049/4d6fbfac-e33d-11e6-8fe9-b05afac81f18.png)

**Comment by AEgit** [comment]
Ahhh, this is how JabRef stored its groups before the change to the new format. @tobiasdiez : Could cavonsto import the old groups, convert them to the new group format and then add the new groups manually to the database file? If so, cavonsto could at least save some time when adding the groups.

Just one question, however: How many groups did you have? Because, if it is just 30 groups, as you said at the beginning, then it is probably quicker to just recreate those groups manually in JabRef as tobiasdiez explained. The articles will all be automatically assigned to the groups, as the group assignment is still stored (it is just the group structure, that was lost). You just have to make sure, that the group names you now create are EXACTLY the same as the ones stored in your database.

**Comment by cavonsto** [comment]
@AEgit you're right, I should just do it. I´m just concern about of the sub-groups..i guess the articles won´t "know" if a group is a sub group..so I´ll have 30 groups PLUS all the sub groups, probably. but it´s a start.

**Comment by AEgit** [comment]
In the description of every article probably there will be only one group, so if you had groups and subgroups, the articles will most likely only be assigned to the subgroup. As long as you remember where you had your subgroups, you can completely recover your original group structure.

**Comment by tobiasdiez** [comment]
Yes, you should be able to copy and paste the group tree in the new file. Just copy everything after `@Comment{jabref-meta: groupstree:` from you backup into the new file. Hopefully this is enough. If this doesn't work, then you have to recreate everything by hand again. Sorry. 

Do you have an idea why the groups disappeared? Was there an error message?

**Comment by cavonsto** [comment]
I copy pasted the last part from my backup to my .bak file, and it kind of worked. 
![screen shot 2017-01-25 at 21 07 21](https://cloud.githubusercontent.com/assets/22658243/22309236/4d653406-e342-11e6-9c5b-0864eb513fd8.png)
should I change the extension when I save it now? or .bak is ok?

**Comment by cavonsto** [comment]
@tobiasdiez no error message. and I´m cheking, the new articles I added recently in existing folders "went" to the right groups. so now is just a matter of finding out what groups are missing.

**Comment by tobiasdiez** [comment]
Glad it kind of worked. Normally `.bib` is the right ending but anything should work.

**Comment by cavonsto** [comment]
thank you very much, I was getting ready to pull an all nighter! 
greetings from Lisbon
