### ISSUE TITLE
Flag private/public database

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2134]
I have some databases, that I don't want to share with the public (because of private data etc.). On the other hand there are bib files, that can be published. It would be nice to have a flag for each database: private/public.

**Comment by Siedlerchr** [comment]
Wouldnt a simple custom field be enough~?

Am 07.10.2016 4:36 nachm. schrieb "Jürgen Lange" <notifications@github.com>:

**Comment by koppor** [comment]
I think, the intention is to have a metadata for that. I.e., not on per
entry basis.

I assume the wish is for a highlight in the tab. [private]

**Comment by grimes2** [comment]
@koppor A metadata for the whole database would be nice (If it is possible). The main window title could be: Jabref - path/database.bib (BibTeX mode, private)

**Comment by stefan-kolb** [comment]
What is the use case for that? Just to remind the user that he has private data in his DB and not to share it? I don't see a necessity for something like that in JabRef as long as we don't share DBs via a cloud service or anything alike.

**Comment by koppor** [comment]
We think, the implementation effort is not worth the benefit. If we have sharing functionality, we can put this back on the table. Meanwhile, please use `-private` as filename suffix.
