### ISSUE TITLE
search field does not keep focus on search field

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#2137]
As reported at http://discourse.jabref.org/t/search-brings-up-edit-mode-cursor-skips-out-of-search-in-to-field/251/2 when clicking on the search field, the focus does not reliably stick to the search field. This can cause unintended entry of data whereever the focus then shifts to.

**Comment by koppor** [comment]
You wrote that you also used the latest development snapshot from https://builds.jabref.org/master/. Could you perhaps make a video showing situations where the focus gets lost? We all use it differently and I did not encounter issues with lost focus.

@bartsch-dev maybe you have some idea?

**Comment by bartsch-dev** [comment]
I too cannot reproduce this.

**Comment by ilippert** [comment]
please see at this [link](https://owncloud.itu.dk/index.php/s/iW9dNUSu2WBSw3A)

**Comment by AEgit** [comment]
This is a duplicate of the bug reported here:
https://github.com/JabRef/jabref/issues/1938

It was also mentioned there, that it is difficult to reproduce (might have to do with the autocompletion feature?).

**Comment by ilippert** [comment]
ok, yes, I agree that this bug report is a duplicate. Thanks for the link!
