### ISSUE TITLE
Value delimiters: configuration of using quotes or force always curly braces?

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#214]
@kubovy introduced configration of value delimiters in 4f9fb0b9fbbdb5db15c60ef24f57cc661f7983e9, @mortenalver removed the configuration option in 74e7296b7b330536. I remember that there was an issue regarding escaping the `"` in Strings delimited with `""` and therefore the choice was just disabled.

The user had the choice between `"..."` and `{...}` as value delimiters. Currently, only `{...} ` are used.

Regarding our discussion at #116 and that `"` is really seldomly used in the wild, I would propose to remove `net.sf.jabref.JabRefPreferences.VALUE_DELIMITERS2` and all transitive dependencies.

**Comment by stefan-kolb** [comment]
:+1:

**Comment by simonharrer** [comment]
:+1: for deleting code :-)

**Comment by oscargus** [comment]
See [this](http://tex.stackexchange.com/questions/109064/is-there-a-difference-between-and-in-bibtex) for a discussion. The only examples given support that `{...}` is the better choice (or at least not worse).

However, it can be noted that [Tame the BeaST  --  The B to X of BibTeX](http://www.ctan.org/tex-archive/info/bibtex/tamethebeast) uses `"..."` in all their examples (except the one talking about the two alternatives).

Google Scholar generates entries with `{...}`.

Still, I guess that it would be good if JabRef can read .bib-files that use `"..."` and possibly warn that they will be written back using `{...}`. 

I would vote for completely removing support for `"..."` too. I do not see any use case where it would be beneficial to use `"..."` compared to `{...}`.

**Comment by kubovy** [comment]
:+1:

**Comment by lenhard** [comment]
Parsing works with quotes instead of curly braces as well (see the test implemented in 4a93387f00e1ab359cacc95f9b079f225e331611).

I think there is a consensus here, so I am closing this issue.
