### ISSUE TITLE
New entry is not focused when search is active

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2142]
1. open `complex.bib`
2. sort by `author/editor`
3. search for `bard`
4. double click on "Boström" (which is not a search hit) -> entry editor opens
5. BibTeX -> New entry
6. Press "Article"

Expected: Entry editor for the new article opens
Behavior: First search hit is focused.

**Comment by bartsch-dev** [comment]
Will be fixed by https://github.com/JabRef/jabref/pull/2129.
