### ISSUE TITLE
"Save all" cancels last changes

### ISSUE THREAD

**Issue by cdupont** [JabRef/jabref#2144]
JabRef version 2.10b2

Steps to reproduce:
- Open a database twice
- modify the first
- click on "save all"
- A warning window opens with "File have changed externally". Click "Save"
- the changes are cancelled

**Comment by cdupont** [comment]
I often open my databases on the command line with an argument:
```
$ jabref mydb.bib
```
This has the effect of opening several time and lead to the non intuitive behavior when saving.
I suggest to either:
- detect and prevent opening a db twice 
- opening only one db when it is passed as an argument

**Comment by matthiasgeiger** [comment]
Hi cdupont!
Thanks for your report. However, as the affected version is years old and the problem no longer present in more recent versions I'll close this issue.

Please use a newer version available at https://www.jabref.org - or here at the [releases section](https://github.com/JabRef/jabref/releases).

Regards
Matthias

**Comment by koppor** [comment]
It seems that @cdupont uses Debian. Plesae support us in packaging JabRef 3.6 for debian. See https://github.com/koppor/jabref/issues/135 for details.

Refs #1371
