### ISSUE TITLE
Performance decrease in recent master build when manually changing group structure?

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2148]
JabRef 3.7dev--snapshot--2016-10-07--master--03bc4a3
windows 10 10.0 amd64 
Java 1.8.0_101
1. Create a new group
2. Unlike in previous versions, you have to wait up to 1 second for the new group to appear
   (this also happens when a group is deleted, moved and/or other changes to the group structure are made)

Size of the database: >9000 entries, several hundred static groups.
System specs:
Core i7-4702MQ (4+4HT cores; 2.2 GHz)
16 GB RAM
Samsung SSD 850 EVO (1 TB)

I think this problem was not present in the following version:
JabRef 3.7dev--snapshot--2016-10-03--master--565676c

but did appear here:
JabRef 3.7dev--snapshot--2016-10-07--master--03bc4a3

Can you confirm this performance decrease in changes to the group structure? Or is it just me?

**Comment by stefan-kolb** [comment]
@JabRef/developers Any comments on this?

**Comment by tobiasdiez** [comment]
@AEgit Thanks for reporting this issue. In the recent releases, we tried to improve the performance of groups as much as possible. I think, right now the performance is acceptable and further improvements are probably only possible with a complete rewrite of the groups code. Thus I will close this issue now. Of course, we will keep an eye on the performance and try to improve it further.

**Comment by AEgit** [comment]
Ok ;)
