### ISSUE TITLE
DOI to BibTex not finding some new articles

### ISSUE THREAD

**Issue by supernano** [JabRef/jabref#216]
I'm trying to add an article using DOI to BibTex, but JabRef returns "Unknown DOI" eventhough dx.doi.org is able to resolve it fine.
The DOI I'm currently having this issue with is 10.1126/sciadv.1500214

**Comment by koppor** [comment]
Can reproduce here with latest `master`.

**Comment by koppor** [comment]
Could track it down to following. When doing a normal `GET` with the browser on http://doi.org/10.1126/sciadv.1500214, the web site is opened. When doing a `GET` with `Accept:application/x-bibtex`, the request is redirected to http://data.crossref.org/10.1126%2Fsciadv.1500214, which is a 404. A manual search at cross.org finds the article: http://search.crossref.org/?q=10.1126%2Fsciadv.1500214. If I click on "Actions" and then Cite, all results are empty. I am contacting the support of @CrossRef. Let's see, what they say.

**Comment by koppor** [comment]
Meanwhile, you could try our "Parse with FreeCite" feature.BibTeX: New entry from plain text, choose "article", paste the bibliographic data and push "Parse with FreeCite".

**Comment by supernano** [comment]
I was able to get the BibTex code from the journal website and add it directly as a new entry. I was just wondering why the fetch wasn't working, but I can see now that it's not a JabRef issue. Thanks for following it up!
