### ISSUE TITLE
DOI not always imported for Medline (Pubmed) searches

### ISSUE THREAD

**Issue by heseber** [JabRef/jabref#2172]
JabRef version JabRef-3.7dev--snapshot--2016-10-16--master--38fe410 on Windows 7

Steps to reproduce:
1. Use "Medline" internet search for pubmed id 27703962
2. Import into bibliography
3. No DOI was imported, although it is contained in the XML file from Pubmed:

[pubmed.txt](https://github.com/JabRef/jabref/files/532749/pubmed.txt)

For some other Pubmed IDs, the DOI is successfully imported, e.g. for pubmed id 27734608.

_Remark: Even if the DOI is successfully imported, the URL field remains empty. In previous versions the URL was automatically set to http://dx.doi.org/DOI. Not sure whether this was an intended change. Would be better to use https anyway._

**Comment by matthiasgeiger** [comment]
Thanks for your report! 

The Medline fetcher is currently internally rewritten - we'll check whether this problem still persists in the new version which should be available soon in the dev builds.

**Comment by matthiasgeiger** [comment]
Regarding the remark:  This is intentionally. As the DOI implicitly defines a URL we do no longer store the URL information. However, using the JabRef user interface it is still possible to directly open the webpage for the entry using the "barcode" icon in the table, or the the "open" button next to the DOI field in the entry editor.

**Comment by tschechlovdev** [comment]
This should be fixed in #2066.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by stefan-kolb** [comment]
Hm, well at least not that I know of. Can you please open an issue so the others can invest this?

**Comment by heseber** [comment]
Will do

**Comment by heseber** [comment]
I can confirm that this is working now. Thank you for fixing it, and thank you for all your work (JabRef is really making my work life a lot easier).
