### ISSUE TITLE
Refactor Integrity Checkers

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2180]
Followup from #1916 
- [ ] Create StartsWitchUpperCaseChecker with Fields to check  as parameter
- [ ] Look for other checkers to unify

**Comment by tobiasdiez** [comment]
And maybe: https://github.com/JabRef/jabref/issues/1916#issuecomment-244558079

**Comment by simonharrer** [comment]
I do not think this is necessary. To me, the current structure with a file per check is really convenient.
