### ISSUE TITLE
Switch Jar-Signing from MD5 to other one 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2182]
> Important planned change for MD5-signed JARs
> The next scheduled JRE update, planned for January 2017 will treat JARs signed with MD5 as unsigned. Learn more and view testing instructions.
> For more information on cryptographic algorithm support, please check the JRE and JDK Crypto Roadmap.

http://www.oracle.com/technetwork/java/javase/downloads/index-jsp-138363.html

**Comment by koppor** [comment]
Refs #1879
