### ISSUE TITLE
Unexpected behaviour when assigning an article to a group using drag'n'drop

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2184]
JabRef 3.7dev--snapshot--2016-10-14--master--fb0990d
windows 10 10.0 amd64 
Java 1.8.0_111

1. Start with a couple of groups and items/articles within them
2. Reassign one of the articles to a group it had not been assigned to previously. Do this by drag'n'dropping it onto the "new" group
3. Check the "Groups" field of the article: Previous/older group assignments are separated from each other with comma+space, but the newly assigned group is separated from the older ones by just the comma (no space)

When assigning an item/article to a group using drag'n'drop an unexpected behaviour is detected. Previously, when you reassigned an item/article to a new group, the format of the added lines in the "Groups" field would be as follows:

OldGroup_1, OldGroup_2, NewGroup_1, NewGroup_2

Currently, the new groups NewGroup_1 and NewGroup_2 are added as follows:

OldGroup_1, OldGroup_2,NewGroup_1,NewGroup2

i.e., there's no space between the commas separating the new entries.

This behaviour has been introduced in the following version:
 JabRef 3.7dev--snapshot--2016-10-14--master--fb0990d
(this was a fix of another bug, that prevented the use of the drag'n'drop feature for group assignments). See also here:
https://github.com/JabRef/jabref/issues/2098#issuecomment-255267055

**Comment by ilippert** [comment]
i use JabRef 3.7dev--snapshot--2016-10-24--master--7d6ee2b
linux 4.7.9-200.fc24.x86_64 amd64 
Java 1.8.0_111
and I can assign entries via drag and drop.

**Comment by AEgit** [comment]
Hmmm yes, but the problem I'm describing is different - the issue with being able to assign entries via drag'n'drop has indeed been fixed in one of the more recent snapshots.

**Comment by ilippert** [comment]
ok, sorry, now I see how the problem you point to is indeed different. sorry!

**Comment by AEgit** [comment]
@ilippert: No worries ;)

**Comment by AEgit** [comment]
I can confirm that this problem has been solved in;
JabRef 3.7-dev--snapshot--2016-11-03--master--9928179
