### ISSUE TITLE
Help Button for Timestamp field

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2190]
The help button is missing for the TimeStamp field (entry editor, tab General fields).
Help file is: http://help.jabref.org/en/TimeStamp

Somehow related to: https://github.com/JabRef/jabref/issues/2083

**Comment by lenhard** [comment]
Just to clarify if this is a bug or an enhancement: Has the button been there before and got lost, or was it never there and should now be added?

**Comment by mlep** [comment]
An enhancement by adding a button

**Comment by matthiasgeiger** [comment]
The help is already accessible in the Preferences dialog. 

As the timestamp is disabled by defaul I would omit to add another button next to the timestamp field in the entry editor, as someone who has activated this feature should already know about it (or at least should know where it can be activated - and here he can find the help button :wink:)

**Comment by matthiasgeiger** [comment]
... but something else is weird: I just activated the feature and I can't see the "timestamp" field at all in the entry editor 🙈 

Is this working for someone?!

**Comment by lenhard** [comment]
I agree with your reasoning about the help button. It is not really necessary to duplicate it imho.

Having said that, I also get do not get a timestamp field in the entry editor ;-)

**Comment by matthiasgeiger** [comment]
Okay after resetting my preferences the timestamp field is there in the entry editor...

**Comment by stefan-kolb** [comment]
Can we close this? Or do you want to investigate the preferences problem? 😉
