### ISSUE TITLE
Backup manager error

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2192]
On my local installation I get the following error after compilation:

```
ERROR net.sf.jabref.logic.autosaveandbackup.BackupManager - Error while deleting the backup file.
java.nio.file.NoSuchFileException path/database.bib.swp

```

This error is maybe not relevant for a "normal" installation, but shouldn't this be fixed?

**Comment by matthiasgeiger** [comment]
Thanks for the report. The problem is already being investigated by @koppor and @obraliar.
