### ISSUE TITLE
Add Set/Clear/rename fields action to Quality Menu

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2204]
More prominent location to cleanup fields, e.g., remove old legacy fields like owner, timestamp etc.

**Comment by matthiasgeiger** [comment]
Your examples are no legacy fields :wink:

**Comment by tobiasdiez** [comment]
There is also a "remove field" cleanup action.

**Comment by stefan-kolb** [comment]
Ah names clear...now I found it :D
