### ISSUE TITLE
Author parser has problems with fetched bibtex author list

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2205]
```
@Book{
  title     = {{Measurement and evaluation of transportation system effectiveness}},
  publisher = {RAND Corporation},
  year      = {1969},
  author    = {Pardee F., Kirkwood T., MacCrimmon K., Miller J., Phillips C., Ranftl J., Smith K. and Whitcomb D.},
}
```

Key gets `PardeeF.1969`

And Bibtex reports 
`Too many commas in name 1 of "Pardee F., Kirkwood T., MacCrimmon K., Miller J., Phillips C., Ranftl J., Smith K. and Whitcomb D." for entry PardeeF.1969`

Actually the format is wrong if I see correctly, but maybe we can handle this somehow?

**Comment by koppor** [comment]
"Normalize to BibTeX name format" seems to be your friend.

IMHO, this describes a missed case in #1470. The heuristics could be to count `,` (more than "?) and to check, whether the third last word is the only `and` appearing in the string.

**Comment by tobiasdiez** [comment]
I think this is resolved now, right?

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by koppor** [comment]
- "Normalize tot BibTeX name format" is not available anymore in v4.0: https://github.com/JabRef/jabref/issues/3136
- Your string is normalized to "Pardee F., Kirkwood T., MacCrimmon K. Miller J. Phillips C. Ranftl J. Smith K. and Whitcomb, D.", which is surely not that what you intended. OMG, we have to touch **that** algorithm again --> https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/model/entry/AuthorList.java#L170. Maybe, the condition `!authorsContainAND` has to be tweaked somehow. Maybe more the sum of commas and the sum of ANDs has to match somehow.

**Comment by koppor** [comment]
Algorithm fix ideas: I remember the discussions that there could be "Junior" parts and therefore, my quick assumptions are not valid. Maybe, we could add a check for exactly your case: more than 4 commas (thus more than two names, each of them might have a Jr. part) and exactly one and.

**Comment by koppor** [comment]
This issue is still open

`Recker, Jan; Indulska, Marta; Michael; and Green, Pete` is another case, I hit --> http://aisel.aisnet.org/cgi/viewcontent.cgi?article=1075&context=ecis2006
