### ISSUE TITLE
DOI to Bibtex failing to catch journaltitle from sciencedirect

### ISSUE THREAD

**Issue by jdpipe** [JabRef/jabref#2209]
When attempting to import the following DOI to Jabref 3.6 (release), the journal title is not picked up. This has occurred for a number of DOIs; I suspect there is some problem in general for papers coming from the ScienceDirect site. FWIW there is already a Bibtex export feature in ScienceDirect, so perhaps that can be reused in some way.

Here is the DOI that gave problems:
http://dx.doi.org/10.1016/j.renene.2016.04.033

**Comment by koppor** [comment]
Refs #1603

## Information exported by ScienceDirect

```
@article{Giostri2016449,
title = "Microalgae cofiring in coal power plants: Innovative system layout and energy analysis ",
journal = "Renewable Energy ",
volume = "95",
number = "",
pages = "449 - 464",
year = "2016",
note = "",
issn = "0960-1481",
doi = "http://dx.doi.org/10.1016/j.renene.2016.04.033",
url = "http://www.sciencedirect.com/science/article/pii/S0960148116303147",
author = "A. Giostri and M. Binotti and E. Macchi",
keywords = "Renewable energy",
keywords = "Biomass",
keywords = "Bioenergy",
keywords = "Microalgae",
keywords = "Raceway pond",
keywords = "Cofiring "
}
```

## Information retrieved by JabRef
```
@article{Giostri_2016,
	doi = {10.1016/j.renene.2016.04.033},
	url = {http://dx.doi.org/10.1016/j.renene.2016.04.033},
	year = 2016,
	month = {sep},
	publisher = {Elsevier {BV}},
	volume = {95},
	pages = {449--464},
	author = {A. Giostri and M. Binotti and E. Macchi},
	title = {Microalgae cofiring in coal power plants: Innovative system layout and energy analysis},
	journal = {Renewable Energy}
}
```

## Comments

In both bibtex entries, the field `journal` exists. Could you elaborate more what you think is missing?

**Comment by koppor** [comment]
I think, it's the typical issue with bibtex vs. biblatex:

![grabbed_20161101-113108](https://cloud.githubusercontent.com/assets/1366654/19887073/b7ad217a-a026-11e6-81f1-ca3830285667.png)

You could execute the cleanup operation "Convert to BibLatex format", which fixes the journal field:

![grabbed_20161101-113146](https://cloud.githubusercontent.com/assets/1366654/19887082/c7667e40-a026-11e6-8631-95fa7f5de383.png)

**Comment by koppor** [comment]
When #521 is solved, this is solved, too. #521 is, however, very hard to solve.

**Comment by Siedlerchr** [comment]
I think it would be sufficient to allow cleanup after import automatically

**Comment by koppor** [comment]
We now show both journal and journaltitle. Should be working, if not, please report back to us.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
