### ISSUE TITLE
Improve error console

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2210]
JabRef 3.7dev--snapshot--2016-10-27--javafx--e489a53
windows 10 10.0 amd64 
Java 1.8.0_101

The error console (see #1383) displays as follows:

![grabbed_20161029-154956](https://cloud.githubusercontent.com/assets/1366654/19830016/b452b2ee-9def-11e6-8e37-7fae6c7add7b.png)

When scrolling down, it displays as follows:

![grabbed_20161029-155309](https://cloud.githubusercontent.com/assets/1366654/19830023/d1bc40c0-9def-11e6-93fd-ed605196807a.png)

I see following issues:
- [x]  When starting, the last line should be displayed, not the first one
- [ ] The colors should be consistent
- [ ] The dialog should allow copy and paste.

Especially, the last point is important to me as I don't want to copy the whole log if something goes wrong, but only the relevant parts.

**Comment by koppor** [comment]
Right click on a single line and copy does not work, because there is no context menu.

When having many errors "Copy Log" does not help:

![grabbed_20161213-134010](https://cloud.githubusercontent.com/assets/1366654/21140669/ad6b4b5e-c139-11e6-875a-aefda21aaf7e.png)

Does someone disagree that the following is not easy to work with for a user?

13:19:10.027 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.importer.OpenDatabase - Opening: C:\git-repositories\jabref\jabref\src\test\resources\testbib\complex.bib
13:19:10.120 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.importer.OpenDatabase - Opening: C:\git-repositories\jabref\jabref\src\test\resources\testbib\crossref.bib
File: errorconsole.fxml not found, attempting with camel case
File: errorconsole.css not found, attempting with camel case
File: errorconsole.fxml not found, attempting with camel case
File: errorconsole.css not found, attempting with camel case
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Dec 13, 2016 1:38:57 PM com.sun.javafx.scene.control.skin.VirtualFlow addTrailingCellsINFO: index exceeds maxCellCount. Check size calculations for class net.sf.jabref.gui.util.ViewModelListCellFactory$1
Dec 13, 2016 1:38:57 PM com.sun.javafx.scene.control.skin.VirtualFlow addTrailingCellsINFO: index exceeds maxCellCount. Check size calculations for class net.sf.jabref.gui.util.ViewModelListCellFactory$1
Dec 13, 2016 1:38:57 PM javafx.scene.CssStyleHelper calculateValueWARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jre1.8.0_111/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
File: errorconsole.fxml not found, attempting with camel case
File: errorconsole.css not found, attempting with camel case
File: errorconsole.fxml not found, attempting with camel case
File: errorconsole.css not found, attempting with camel case

**Comment by tobiasdiez** [comment]
You can select the interesting messages and copy them via `Ctrl + V` which should suffice for most cases.
