### ISSUE TITLE
Import pdf by content

### ISSUE THREAD

**Issue by mpele** [JabRef/jabref#2214]
JabRef version 3.6 on Windows 10 and Windows 7

Steps to reproduce:

1. Import pdf by content
2. Import pdf by content.

When I try to import pdf by dragging file to JabRef it works only first time. The first time is always successful, but after second import JabRef doesn't respond anymore - it could be shouted down only by Task Manager. 
The second attempt is the same as the first: after Creating entry based on content the new entry could be seen on the list while the dialog for linking file is open. After linking (with renaming and moving to directory) file is renamed and moved but JabRef is not responding anymore.

**Comment by koppor** [comment]
Could you please try the latest development version from http://builds.jabref.org/master/?

What does the error log/error console say?

**Comment by mpele** [comment]
With development version it works as expected.
Thanks
