### ISSUE TITLE
Metadata lost on reconnect to a shared database

### ISSUE THREAD

**Issue by har-wradim** [JabRef/jabref#2219]
JabRef 3.7dev--snapshot--2016-10-24--master--7d6ee2b
linux 3.13.0-100-generic i386 
Java 1.8.0_91

When dealing with shared databases (Postgres at least) metadata other then databaseType get lost on reconnect. No exceptions.

Steps to reproduce:

1. Create a (local Postgres) database
2. Populate it with JabRef
3. Change e.g. "general file directory" in the database properties dialogue
4. Without disconnecting, check that the METADATA table contains a record for fileDirectory and that it is respected by JabRef
5. Disconnect, connect again. fileDirectory is gone

**Comment by obraliar** [comment]
I'm unfortunately not available until November 17th.

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by har-wradim** [comment]
OK, fixed in the current build, thanks.

**Comment by g-mos** [comment]
I agree. Problem seems fixed on Ubuntu 16.04 also.
