### ISSUE TITLE
Entry editor freeze

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2220]
JabRef 3.7-dev--snapshot--2016-11-01--master--458ee79
windows 10 10.0 amd64 
Java 1.8.0_111

Steps to reproduce:

1. open entry editor
2. change entry
3. Freeze. 50% CPU

**Comment by koppor** [comment]
Can you do a git bisect run to determine which commit is the cause?

**Comment by grimes2** [comment]
The last commit 458ee7999699b3489684178605c3f8f55294fd63 seems to be bad.

**Comment by lenhard** [comment]
I can confirm the behavior on current master. This renders JabRef completely unusable and is a blocker for a release of 3.7.

**Comment by koppor** [comment]
The commit points to https://github.com/JabRef/jabref/pull/2199. I contacted @bartsch-dev

**Comment by stefan-kolb** [comment]
I cannot reproduce this. After entering something inside the entry editor it should automatically freeze the program? I can edit and change between entries with no problems. When I add a new entry afterwards I get kind of a freeze. But some things are still functional in Jabref. i just cannot enter things in the entry editor or select different entries.

**Comment by koppor** [comment]
When I edit an exiting entry, I have following issues:

1. Open entry
2. Edit "title" field: Add three letters "abc"
3. Click textfield of "journaltitle".
4. Field does not get focus
3. Click textfield of "journaltitle".
4. Field gets focus

**Comment by bartsch-dev** [comment]
I tried to fix it, can you please try it out?
I also have to say that with #2075 the entry editor has become noticeable slower.

**Comment by grimes2** [comment]
Can you provide a build? I want to test it also.

@stefan-kolb: No. Open the entry editor by double-click on an entry in main table. Go to another entry in the main table. You don't need to edit or change a field in the entry editor at all.

**Comment by koppor** [comment]
The PR is #2225. I (manually) mirrored the branch ``fixEditorFreeze` at the JabRef repo. It doesn't build as we have [issues with the Medline test on the master branch](https://travis-ci.org/JabRef/jabref/builds/172742443). The latter refs https://github.com/koppor/jabref/issues/181

You can just checkout the branch or add [bartsch's fork](https://github.com/bartsch-dev/jabref) as additional git remote for fetching.

**Comment by grimes2** [comment]
JabRef 3.7-dev--snapshot--2016-11-02--fixEditorFreeze--d1c1801
windows 10 10.0 amd64 
Java 1.8.0_111

Thanks for the build. With the tested build the bug is fixed. Thanks for the fix and the improvement of the entry editor code.
