### ISSUE TITLE
Look up full text ArXiv broken

### ISSUE THREAD

**Issue by barefeg** [JabRef/jabref#2222]
The functionality added in https://github.com/JabRef/jabref/issues/1023 is broken in the current build. Namely it fails to fetch the pdf file. It generates an empty file without extension. 

Also by default when adding an entry from the ArXiv web search it includes the online link. I would like to deactivate that or a way to order that last with respect to the local PDF copy.

**Comment by matthiasgeiger** [comment]
@stefan-kolb Can you investigate this again?

**Comment by lenhard** [comment]
For me, it works as expected on current master with the reference mentioned in #1023, which is this one: https://arxiv.org/abs/1603.06570v1

@barefeg Could you please provide your JabRef and Java versions, as well as an entry that fails? Maybe it is not JabRef, but your machine that is being blocked for some reason.

**Comment by barefeg** [comment]
@lenhard the example you gave also fails to fetch the pdf.

JabRef 3.7-dev--snapshot--2016-11-01--master--458ee79
mac os x 10.12.1 x86_64 
Java 1.8.0_66

**Comment by stefan-kolb** [comment]
Problem is probably in `DownloadExternalFile.java` because it does not follow redirects. The current arxiv fetcher returns a URL that will be redirected. 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://arxiv.org/pdf/1603.06570v1">here</a>.</p>
<hr>
<address>Apache Server at arxiv.org Port 80</address>
</body></html>
```

**Comment by barefeg** [comment]
But are you saying that the output from the API changed? or how did it work previously?

**Comment by stefan-kolb** [comment]
It's just a problem of our downloader in my opinion. It doesn't follow the HTPP redirect.

**Comment by Siedlerchr** [comment]
I think it is enough to set the redirect header

Am 02.11.2016 11:54 vorm. schrieb "Stefan Kolb" <notifications@github.com>:

**Comment by lenhard** [comment]
@barefeg: Please note that you still get the PDF if you hit the "Get fulltext" button instead of the "Download from URL". This might be a workaround for you at the moment.

**Comment by stefan-kolb** [comment]
@lenhard No, its just a file containing the text i posted before.

**Comment by lenhard** [comment]
@stefan-kolb That is really strange, because for me it is the actual pdf.

**Comment by barefeg** [comment]
@lenhard are you using the  same version? I don't see any of the buttons you mention. There is only "Look up full text document" under quality.

**Comment by lenhard** [comment]
@barefeg: If you open the entry editor for a particular entry, you will find those buttons next to the file field in the "General" tab

@stefan-kolb @barefeg: I stand corrected, it was working for another entry of almost the same name by the same authors that I accidently imported with the arxiv web fetcher. For the actual entry, I get the same result by the downloader.

**Comment by stefan-kolb** [comment]
This should be fixed in current `follow-redirects`. Please try the latest build from http://builds.jabref.org/follow-redirects.

**Comment by barefeg** [comment]
Thank you it's working as expected now.
