### ISSUE TITLE
Fetching from Medline no longer works as HTTPS is enforced

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2228]
See this issue for details:
https://github.com/JabRef/help.jabref.org/issues/130

**Comment by matthiasgeiger** [comment]
Was about to fix that, too ;-)

Changing the URLs in `MedlineFetcher.java` is sufficient.

Please also provide a Changelog entry as this change will break previous JabRef versions.

**Comment by Siedlerchr** [comment]
We should also make an announcement, since: 

> After November 9, 2016, NCBI HTTP servers will redirect or reject all HTTP requests.

https://www.ncbi.nlm.nih.gov/home/develop/https-guidance.shtml
