### ISSUE TITLE
'Save Database' or 'Save Database As' not preserving field removal

### ISSUE THREAD

**Issue by cmharwood-UI** [JabRef/jabref#2232]
Several entries in my .bib file have duplicate "journal" fields. After removing duplicate fields and saving the database, the duplicate fields are added back into each entry.

I am only encountering this problem with large .bib files (>300 entries).

JabRef 3.6
windows 10 10.0 amd64 
Java 1.8.0_102

Steps to reproduce:

1. In attached .bib file, use BibTeX Source pane to remove duplicate 'journal' field from YoungBaker2010 entry. 
2. Save database
3. De-select and re-select edited entry. Duplicate field is present again.

```
[ThesisTest.zip](https://github.com/JabRef/jabref/files/569985/ThesisTest.zip)

```

**Comment by matthiasgeiger** [comment]
Thanks for your report!

I can reproduce the behavior in 3.6 and current master builds. 
However, this is quite an edge case: 
We are storing internally the textual representation of the bibentry to facilitate version control (i.e., each entry which is not changed will be written exactly as it is parsed). If you change a field value than the entry is marked as changed and rewritten in the "JabRef-style". 
The problem in your case is, that the change in the source is not detected as a change of the entry as the value of the field "journal" has not changed - and thus, the old stored entry will be written character by character...

To remove the duplicates of journal I propose you to add a single space or another letter at the end of the field value, e.g., "Composite StructuresX", save the database (Ctrl-S), remove the "X" and save again.

**Comment by matthiasgeiger** [comment]
@lenhard Perhaps a check would be sensible for cases like this? If a field is stored twice in an entry the stored source should not be used but the data in the internal model (and a warning should be displayed to the user). 
But this would be rather hard to accomplish, I suppose?

**Comment by stefan-kolb** [comment]
I came up with an easy solution for this edge case:
1. use `set/clear/rename` functionality. e.g. under `edit`
2. select `all entries` and set a unique field for all entries, e.g., `myuniquefield92782` to `1`
3. All entries will be rewritten - the duplicates should be gone.
4. use `set/clear/rename` functionality. e.g. under `edit` to `clear` the unique field again
5. We end up with the database as before except for the duplicates.

**Comment by stefan-kolb** [comment]
Therefore, I tend to mark this as wont-fix if @lenhard also says so.
