### ISSUE TITLE
When adding a pdf the folders do not open left aligned

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2237]
JabRef 3.7-dev--snapshot--2016-11-04--master--949ca17
windows 7 6.1 amd64 
Java 1.8.0_66

Steps to reproduce:

1. In the file field I klick the "+" "new file link" button, the folder opens from where to choose subdirs
2. Clicking the subdir, this is opened. However the view does not show a the beginning of entries, but a part more to the right. (see JabrefFolderScreenshot2
3. It should be left aligned like in JabrefFolderScreenshot3.

![jabreffolderscreenshot2](https://cloud.githubusercontent.com/assets/9216487/20036480/c0b96a4e-a409-11e6-9e04-1dcfc9b9254c.PNG)
![jabreffolderscreenshot3](https://cloud.githubusercontent.com/assets/9216487/20036479/c0b83dea-a409-11e6-9c3d-9899a9101e97.PNG)

**Comment by Siedlerchr** [comment]
We don't have any control over this, as we only call the jFileChooser component to open a file/folder.Is either a windows or Swing specific issue.
Therefore I suggest closing this, as we can't do anyhting about it.
