### ISSUE TITLE
Add Ottobib as alternative ISBN fetcher

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2238]
Our current fetcher relies on the data from www.ebook.de
However, sometimes entries are not found. 
Therefore I suggest using Ottobib.com (relies on worldcat and is also listed in wikipedia )  as a secondary (or primary source) if lookup fails.
The fetcher implementation is plain simple and could be easily integrated:
http://www.ottobib.com/about
=> ISBN in url
`http://www.ottobib.com/isbn/0195117972/bibtex`

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/684#issuecomment-173368833

**Comment by stefan-kolb** [comment]
Wishes for fetchers will be collected at #2581.
