### ISSUE TITLE
Localization of upcoming release 3.7

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#2239]
Dear @JabRef/translators ,

we are about to release the next version of JabRef.

It would be great if you find the time to translate all, or some :wink: of the missing translations.

The current status is:

### Localization files status (2016-11-07 08:52 - Branch `master` `dd7a757`)

| Property file | Keys | Keys translated | Keys not translated | % translated |
| ------------- | ---- | --------------- | ------------------- | ------------ |
| JabRef_en.properties | 1576 | 1576 | 0 | 100 |
| JabRef_da.properties | 1576 | 956 | 620 | 60 |
| JabRef_de.properties | 1576 | 1564 | 12 | 99 |
| JabRef_es.properties | 1576 | 1368 | 208 | 86 |
| JabRef_fa.properties | 1576 | 5 | 1571 | 0 |
| JabRef_fr.properties | 1576 | 1564 | 12 | 99 |
| JabRef_in.properties | 1576 | 1210 | 366 | 76 |
| JabRef_it.properties | 1576 | 1565 | 11 | 99 |
| JabRef_ja.properties | 1576 | 1554 | 22 | 98 |
| JabRef_nl.properties | 1576 | 642 | 934 | 40 |
| JabRef_no.properties | 1576 | 953 | 623 | 60 |
| JabRef_pt_BR.properties | 1576 | 1189 | 387 | 75 |
| JabRef_ru.properties | 1576 | 1143 | 433 | 72 |
| JabRef_sv.properties | 1576 | 1394 | 182 | 88 |
| JabRef_tr.properties | 1576 | 1560 | 16 | 98 |
| JabRef_vi.properties | 1576 | 961 | 615 | 60 |
| JabRef_zh.properties | 1576 | 1207 | 369 | 76 |

| Property file | Keys | Keys translated | Keys not translated | % translated |
| ------------- | ---- | --------------- | ------------------- | ------------ |
| Menu_en.properties | 108 | 108 | 0 | 100 |
| Menu_da.properties | 108 | 93 | 15 | 86 |
| Menu_de.properties | 108 | 108 | 0 | 100 |
| Menu_es.properties | 108 | 93 | 15 | 86 |
| Menu_fa.properties | 108 | 93 | 15 | 86 |
| Menu_fr.properties | 108 | 108 | 0 | 100 |
| Menu_in.properties | 108 | 93 | 15 | 86 |
| Menu_it.properties | 108 | 108 | 0 | 100 |
| Menu_ja.properties | 108 | 108 | 0 | 100 |
| Menu_nl.properties | 108 | 93 | 15 | 86 |
| Menu_no.properties | 108 | 102 | 6 | 94 |
| Menu_pt_BR.properties | 108 | 93 | 15 | 86 |
| Menu_ru.properties | 108 | 93 | 15 | 86 |
| Menu_sv.properties | 108 | 103 | 5 | 95 |
| Menu_tr.properties | 108 | 108 | 0 | 100 |
| Menu_vi.properties | 108 | 108 | 0 | 100 |
| Menu_zh.properties | 108 | 93 | 15 | 86 |

I'll take care of the German translations.

Please notify us if you are working on a submission, so that we can potentially reschedule the release.

Regards,
Matthias

**Comment by mlep** [comment]
@matthiasgeiger I am working on the French localization.

**Comment by mlep** [comment]
@JabRef/translators, please note that, in the file JabRef_XX.properties:
- some untranslated keys _are not at the bottom of the file_ ,but are scattered through the file (i.e. some searching required).
- some keys look translated, but are, in fact, _localized in English_. They are located close to the file bottom. These are:

    -  `Backup_found=Backup_found`
    - `A_backup_file_for_'%0'_was_found.=A_backup_file_for_'%0'_was_found.`
    - `This_could_indicate_that_JabRef_did_not_shut_down_cleanly_last_time_the_file_was_used.=This_could_indicate_that_JabRef_did_not_shut_down_cleanly_last_time_the_file_was_used.`
    - `Do_you_want_to_recover_the_database_from_the_backup_file?=Do_you_want_to_recover_the_database_from_the_backup_file?`

**Comment by matthiasgeiger** [comment]
Thanks @mlep!
I removed the wrong translations from the files directly in `master`.

**Comment by ThomasA** [comment]
I would like to contribute to the Danish translation again, although I might not quite make it for the next release. It has got quite a bit behind...
However, I have a problem setting up Popeye to encode the resource files properly. I downloaded the JAR from the latest release of JabRef/popeye on GitHub and despite my attempts to replicate the character encoding used in the upstream resource files, Popeye seems to encode the characters wrong on my computer. Here is a snippet of the main Danish language file diff after saving it with Popeye on my computer:
    
    diff --git a/src/main/resources/l10n/JabRef_da.properties b/src/main/resources/l10n/JabRef_da.properties
    index 69777af..0db900c 100644
    --- a/src/main/resources/l10n/JabRef_da.properties
    +++ b/src/main/resources/l10n/JabRef_da.properties
    @@ -1,24 +1,24 @@
     #!
    -#! created/edited by Popeye version 0.55 (github.com/JabRef/popeye)
    +#! created/edited by Popeye version 0.55 (https://github.com/koppor/popeye)
     #! encoding:UTF-8
     
    -%0_contains_the_regular_expression_<b>%1</b>=%0_indeholder_regulærudtrykket_<b>%1</b>
    +%0_contains_the_regular_expression_<b>%1</b>=%0_indeholder_regulÃ¦rudtrykket_<b>%1</b>

As you can see, my version does not alter the encoding *stated* at the beginning of the resource file, but the character 'æ', for example, is obviously encoded differently in my version anyway. It seems the PopEye version I downloaded is a bit different from the one @matthiasgeiger used when last saving this resource file - @koppor?
It looks as if Popeye claims to be writing UTF-8 but really is writing ISO-8859-1?

**Comment by matthiasgeiger** [comment]
Yes, I can reproduce the problems with popeye @koppor.

However, as I'm not using popeye for editing those files I cannot provide you a working version. But as a workaround, it is possible to directly edit the files here at GitHub (see https://help.jabref.org/en/TranslatingGUI#directly-in-your-web-browser).

**Comment by ThomasA** [comment]
Editing the files directly is, to put it mildly, a very unattractive solution since typing underscores for spaces is a royal pain in the ....

**Comment by Siedlerchr** [comment]
You could also edit the files locally in your favorite editor, e.g. notepad++ on windows

**Comment by koppor** [comment]
I saw users using IntelliJ quite successfully. I never used popeye for
myself 🙈. Could you file the issue at the popeye repo at the JabRef
organization?

**Comment by mlep** [comment]
Here is an update:

### Localization files status (2016-11-13 15:22 - Branch `master` `d1702bb`)

| Property file | Keys | Keys translated | Keys not translated | % translated |
| ------------- | ---- | --------------- | ------------------- | ------------ |
| JabRef_en.properties | 1577 | 1577 | 0 | 100 |
| JabRef_ja.properties | 1577 | 1550 | 27 | 98 |
| JabRef_vi.properties | 1577 | 961 | 616 | 60 |
| JabRef_de.properties | 1577 | 1577 | 0 | 100 |
| JabRef_no.properties | 1577 | 949 | 628 | 60 |
| JabRef_fr.properties | 1577 | 1577 | 0 | 100 |
| JabRef_es.properties | 1577 | 1552 | 25 | 98 |
| JabRef_ru.properties | 1577 | 1515 | 62 | 96 |
| JabRef_tr.properties | 1577 | 1562 | 15 | 99 |
| JabRef_it.properties | 1577 | 1572 | 5 | 99 |
| JabRef_fa.properties | 1577 | 1 | 1576 | 0 |
| JabRef_pt_BR.properties | 1577 | 1185 | 392 | 75 |
| JabRef_da.properties | 1577 | 952 | 625 | 60 |
| JabRef_nl.properties | 1577 | 638 | 939 | 40 |
| JabRef_in.properties | 1577 | 1206 | 371 | 76 |
| JabRef_sv.properties | 1577 | 1390 | 187 | 88 |
| JabRef_zh.properties | 1577 | 1272 | 305 | 80 |

| Property file | Keys | Keys translated | Keys not translated | % translated |
| ------------- | ---- | --------------- | ------------------- | ------------ |
| Menu_en.properties | 107 | 107 | 0 | 100 |
| Menu_in.properties | 107 | 93 | 14 | 86 |
| Menu_tr.properties | 107 | 107 | 0 | 100 |
| Menu_zh.properties | 107 | 107 | 0 | 100 |
| Menu_vi.properties | 107 | 107 | 0 | 100 |
| Menu_ja.properties | 107 | 107 | 0 | 100 |
| Menu_fr.properties | 107 | 107 | 0 | 100 |
| Menu_sv.properties | 107 | 103 | 4 | 96 |
| Menu_fa.properties | 107 | 93 | 14 | 86 |
| Menu_nl.properties | 107 | 93 | 14 | 86 |
| Menu_ru.properties | 107 | 102 | 5 | 95 |
| Menu_de.properties | 107 | 107 | 0 | 100 |
| Menu_es.properties | 107 | 102 | 5 | 95 |
| Menu_da.properties | 107 | 93 | 14 | 86 |
| Menu_pt_BR.properties | 107 | 93 | 14 | 86 |
| Menu_no.properties | 107 | 102 | 5 | 95 |
| Menu_it.properties | 107 | 107 | 0 | 100 |
