### ISSUE TITLE
Check integrity: Valid ISBN - Incorrect format

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2244]
JabRef 3.7-dev--snapshot--2016-11-07--master--e310379
windows 10 10.0 amd64 
Java 1.8.0_111

Steps to reproduce:

1. Insert the (valid) ISBN-13: 978-1-60558-012-X
2. Check integrity
3. Problem found: isbn, incorrect format

**Comment by stefan-kolb** [comment]
Is this really a valid ISBN? In my opinion it is not. The X should be the checksum. See https://de.wikipedia.org/wiki/Internationale_Standardbuchnummer, https://en.wikipedia.org/wiki/International_Standard_Book_Number. Most checkers also reject this ISBN, while after googling around I saw examples for such ISBNs...

**Comment by stefan-kolb** [comment]
Ok, ISBN-10 seems to allow a checksum of 10 which is represented as X. https://en.wikipedia.org/wiki/Check_digit#ISBN_10

**Comment by stefan-kolb** [comment]
However, the ISBN-13 number you gave is not correct. The checksum for ISBN-13 is mod 10 so this cannot be 10.

**Comment by stefan-kolb** [comment]
We also got a test for such an issue `assertCorrect(createContext("isbn", "0-9752298-0-X"));` which passes.

**Comment by stefan-kolb** [comment]
https://de.wikipedia.org/wiki/Internationale_Standardbuchnummer#ISBN-13 Looks like the Null Rule is not respected in your ISBN.

**Comment by grimes2** [comment]
You are right. The correct number is 978-1-60558-012-8. The wrong number is from our complex.bib (entry Kostakos2008). Compliment, the integrity checker works perfect. Can be closed.

**Comment by grimes2** [comment]
Well, we should correct `complex.bib`. It's probably not a good idea to spread this wrong references around the world.

**Comment by stefan-kolb** [comment]
@grimes2 Thanks for reminding me!
