### ISSUE TITLE
Shortcut F8 not working

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2251]
JabRef 3.7-dev--snapshot--2016-11-08--master--fffad83
windows 10 10.0 amd64 
Java 1.8.0_111

The shortcut `F8` for `Cleanup entries...` is not working for me.

**Comment by stefan-kolb** [comment]
Thank you for your report :smile:
I can reproduce the behavior.

**Comment by koppor** [comment]
@mairdl @Braunch Can you have a look?

**Comment by Braunch** [comment]
I will have a look.

**Comment by Braunch** [comment]
I think it has something to do with the mainTable selecting the authors row when pressing F8. It's a JTable functionality. I tried adding this line `inputMap.put(KeyStroke.getKeyStroke("F8"), "none");` in the `MainTable` constructor. But this didn't override the F8 functionality. Does someone have any ideas how to fix this?

**Comment by matthiasgeiger** [comment]
Just noticed, that <kdb>F7</kbd> for "Automatically set file links" seems to work. Can you investigate the differences between these two functionalities?

**Comment by grimes2** [comment]
http://www.java-forum.org/thema/f8-im-jtable.70666/

Why not use <kbd>Alt</kbd>+<kbd>F8</kbd>?

**Comment by Braunch** [comment]
We should try to evade the alt key since it often is reserved for OS specific keybindings. I found that link before and I read the KeyBindings Javadoc what brought me to my attempt. But it does not work and I don't know why. @matthiasgeiger same for F9, it's just because the F8 key is used by the JTable.

**Comment by koppor** [comment]
I think, the decision is to change both <kbd>F8</kbd> and <kbd>F9</kbd> to include the <kbd>Alt</kbd> key.

**Comment by koppor** [comment]
<kbd>F9</kbd> works perfectly here, so I change only <kbd>F8</kbd>
