### ISSUE TITLE
Some tabs in entry editor steal focus from the main table

### ISSUE THREAD

**Issue by shitikanth** [JabRef/jabref#2254]
When the keyboard focus is in the main table, I expect to be able to move around using arrow keys (up/down) and the entry editor should just show the same tab for the next article. This is what happens if the current tab in entry editor is "Required fields" or "BibLaTeX source", but other tabs steal focus from the main table.

Using latest master build  on Ubuntu 16.04 

Steps to reproduce:

1. Open a bibliography in JabRef.
2. Double click on entry to open the entry editor.
3. Select "Optional fields" tab (for example) in the entry editor.
4. Click on any entry in the main table to put focus back on the table.
5. Press down arrow key. The next item in the bibliography is selected but JabRef automatically gives the keyboard focus to the first text field in the current tab of entry editor.

**Comment by grimes2** [comment]
JabRef 3.7-dev--snapshot--2016-11-10--master--a1cce42
windows 10 10.0 amd64 
Java 1.8.0_111

Confirmed.

**Comment by lenhard** [comment]
#2397 is related, I think, and more or less contradictory to this one. In #2397, the OP wants to avoid a change in the entry editor when right-clicking in the main table (and a right-click will definitely trigger a focus event, I think)

**Comment by stefan-kolb** [comment]
@JabRef/developers Is this still valid for the JavaFX implementation or can we close this?

**Comment by Siedlerchr** [comment]
Resolved in the current 4.0 version
