### ISSUE TITLE
Reset preferences & Import preferences not working for custom entry types.

### ISSUE THREAD

**Issue by Schnet** [JabRef/jabref#2261]
JabRef 3.6
windows 7 6.1 amd64 
Java 1.8.0_111

Reset preferences and Import preferences does not work for custom entry types.

Steps to reproduce the reset issue:
1. Customize entry types, e.g. by adding new entry types and/or by removing and/or adding fields
2. Close/Start JabRef
3. Watch preferences in JabRef preferences -> custom entry types can be found there -> ok
4. Reset preferences
5. Close/Start JabRef
6. Watch preferences in JabRef preferences -> custom entry types can still be found there 

Steps to reproduce the import issue:
1. Customize entry types, e.g. by adding new entry types and/or by removing and/or adding fields
2. Close/Start JabRef
3. Export preferences
4. Import preferences in JabRef installed on a different system (Win 7 as well in my case)
5. Watch preferences in JabRef preferences -> imported custom entry types can not be found

**Comment by koppor** [comment]
Could you try the latest dev build from https://builds.jabref.org?

**Comment by Schnet** [comment]
JabRef 3.7-dev--snapshot--2016-11-10--master--2441675
windows 7 6.1 amd64 
Java 1.8.0_111

I tried the reset & import issue with the above version. Unfortunately still the same behavior.

**Comment by matthiasgeiger** [comment]
Hi!
A global reset of type customizations is not possible at the moment. 
To reset changes in standard types and to remove custom types you have open the "BibTeX" -> "Customize Entry Types" dialog and to reset/remove each customized type manually.

And you are right, importing custom types is currently not possible.

**Comment by Mattri** [comment]
Hi!
The same issue has been around for a while:

[ https://github.com/JabRef/jabref/issues/772](url)

Fixing would be greatly appreciated, especially for cases where many users share one database and need to exchange preferences.
