### ISSUE TITLE
Entry editor steals focus from search bar

### ISSUE THREAD

**Issue by ziggystar** [JabRef/jabref#2268]
# Summary

When having an entry in edit mode, and using the quick search to find another entry (to edit), then while typing into search bar, focus jumps to editor, and you begin editing some entry instead.

## Version 
 - JabRef 3.6
 - linux 4.4.0-45-generic amd64 
 - Java 1.8.0_101

## Steps to reproduce:

1. select an entry, to have it in edit mode
2. begin typing in the quick search bar
3. observe how focus jumps, usually after 1-2 characters, to the editor where you instantly begin to change an entry. The edited entry is the first found entry using the typed characters so far.

## Solution

Focus should stay in search bar, at least until enter is hit, or something sane.

**Comment by koppor** [comment]
Thank you for the nicely formatted and detailed report. We think, that is already fixed with #1961 and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master.

**Comment by ziggystar** [comment]
I can confirm that the bug is not present with the current devel build of d1702bb.
