### ISSUE TITLE
When the entry editor is focused, the entry should be focused in the entry table

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2270]
JabRef 3.7 on Windows

When I click the entry editor, the entry should be focused in the main table.

Similar: When pressing next/previous entry in the entry editor, the selected bar should not leave the visible area.

**Comment by shitikanth** [comment]
Same issue as #2254?

**Comment by koppor** [comment]
Here, it's the other way round. I created a new entry, the entry editor is shown, but the entry is not in the focus of the main table. As far as I understood your issue #2254, you want to have the arrow keys working as expected in the main table.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
