### ISSUE TITLE
Gradle Task.leftShift is deprecated 

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2276]
Gradle complains about
> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at eclipse_7q9m579etzxu4ha3zcvflgicy.run(D:\Programming\Projects\Jabref\eclipse.gradle:7)

**Comment by koppor** [comment]
Should be fixed in https://github.com/JabRef/jabref/commit/4d1761cb7c8034f8a067226c89e60cd49e38bddc - see https://travis-ci.org/JabRef/jabref/builds/177294243
