### ISSUE TITLE
Proposal for CHANGELOG format

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2277]
I just came across [the release notes of the Win 10 Preview](https://blogs.windows.com/windowsexperience/2016/11/09/announcing-windows-10-insider-preview-build-14965-for-mobile-and-pc/#9wESO6lViedJqYgY.97) and noticed that their changelog entries look like
> - We fixed an issue where deleted files might reappear in File Explorer with a 0 byte size.
> - We fixed an issue resulting in a Windows Default Lock Screen window sometimes appearing after logging in.
> - We fixed an issue resulting in File Explorer crashing after right-clicking an app in Task Manager and selecting “Open File Location”.
> - We’ve updated our migration logic so that going forward from Build 14965, preferred UAC settings, startup shortcuts, and File Explorer folders that had been pinned to the Start menu will all now be preserved across upgrades. 

I like the style to start the entries with "We fixed / We've updated / We improved" since it leads to readable sentences as opposed to our sometimes cryptic messages. Thus I would propose the following layout:
- We fixed an issue ... `[#1111](link to github)`
- We changed ... `[kooper-#10](link to Olly's rep)`
- We added ... `[feature-request #311](link to discource forum)`

What do you think?

**Comment by koppor** [comment]
Does that mean, we'll stop believing in http://keepachangelog.com/?

Possibly, because we already removed the section "Added". We did not want
to discuss the difference between changed overall functionality and added
functionality each time...

**Comment by tobiasdiez** [comment]
No, the aim of the proposed changed was to follow
> It’s made for humans, not machines, so legibility is crucial.
even more!

We can of course keep the sections `Changed`, `Removed` etc., I was more concerned about the way we formulate each log entry.

**Comment by stefan-kolb** [comment]
I'm not sure if the prefix `We fixed/changed/added` alone changes the current situation. In my opinion we should just make sure we formulate meaningful sentences in the changelog so everyone can understand the case. Imho this is not dependent on a `we fixed/added/changed` template.

**Comment by tobiasdiez** [comment]
You are right @stefan-kolb. Summary: every format is fine as long as it results in understandable sentences.
