### ISSUE TITLE
Cannot paste formatted text

### ISSUE THREAD

**Issue by cr333** [JabRef/jabref#2280]
One regression I found in JabRef version 3.7 on Windows 10 is that pasting formatted text (e.g. copying some text from Chrome) doesn't work any more. It used to work fine in 3.6 and before, where it would just paste the text and discard the formatting.

Steps to reproduce:

1. Copy some text from a website in Chrome or some text from Word. (This text has formatting attached somehow.)
2. Try to paste it into JabRef. No text appears.
3. Paste the same text into Notepad (this pastes only the text and discards any formatting).
4. Copy the same text from Notepad.
5. Paste into JabRef => works fine this time.

**Comment by tobiasdiez** [comment]
Thanks for your report, but I cannot reproduce the issue. I tried to copy this webpage and some formatted text from a Word document into the Abstract and Review fields in JabRef and everything works. Can you please give a link to a non-working webpage / text. Where and how do paste the text into JabRef?

**Comment by cr333** [comment]
For example, when I create BibTeX entries from an arXiv paper website (such as this one: [https://arxiv.org/abs/1604.00449](https://arxiv.org/abs/1604.00449)), and want to copy the abstract into the entry, no text is pasted into the Abstract field.

However, copying the URL from the address bar works fine, presumably because it doesn't carry any formatting information.

I don't think it's just a Chrome issue, as Word (2013) shows the same problem for me.

**Comment by matthiasgeiger** [comment]
Sorry, but this works for me without problems using Firefox and/or Chrome. Copying and pasting from Word (2010) is also no problem.

You might upload your preferences here for investigation but I don't think that there is any configuration option which might cause this trouble... 😕

**Comment by grimes2** [comment]
JabRef 3.7
windows 10 10.0 amd64 
Java 1.8.0_111

I can not reproduce. Is the string really copied to the clipboard? I recommend the clipboard caching utility CLCL for better control of copy & paste.

**Comment by cr333** [comment]
Thanks for taking the time to look into this. The problem has now suddenly disappeared, and I have no idea where it came from in the first place or why it's now gone again.
