### ISSUE TITLE
Port is blocked - Remote operations an issue on multi-user systems

### ISSUE THREAD

**Issue by larsvilhuber** [JabRef/jabref#2282]
JabRef version 3.7 on CentOS6 as downloaded from https://www.fosshub.com/JabRef.html on Nov 17, 2016. 

When launching JabRef on multi-user (linux) system, the default setting to test whether there is a JabRef instance listening on a hard-coded port (https://help.jabref.org/en/Remote) does not work/is a security issue/leads to the second user not being able to run JabRef

Suggestions: 

- Change the default to have The default should be to NOT listen/attempt to connect
- Document a command line option to ENABLE the listening/connection attempt
- Randomize the port (store in preferences) when the setting is first enabled.

Steps to reproduce:

1. User 1 launches JabRef, makes no special option settings
2. User 2 launches Jabref
3. Error message upon launch:

```
19:10:05.773 [AWT-EventQueue-0] WARN  net.sf.jabref.logic.remote.server.RemoteListenerServerLifecycle - Port is blocked
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387) ~[?:1.8.0_111]
	at java.net.ServerSocket.bind(ServerSocket.java:375) ~[?:1.8.0_111]
	at java.net.ServerSocket.<init>(ServerSocket.java:237) ~[?:1.8.0_111]
	at net.sf.jabref.logic.remote.server.RemoteListenerServer.<init>(RemoteListenerServer.java:26) ~[JabRef-3.7.jar:?]
	at net.sf.jabref.logic.remote.server.RemoteListenerServerThread.<init>(RemoteListenerServerThread.java:18) ~[JabRef-3.7.jar:?]
	at net.sf.jabref.logic.remote.server.RemoteListenerServerLifecycle.open(RemoteListenerServerLifecycle.java:42) ~[JabRef-3.7.jar:?]
	at net.sf.jabref.JabRefMain.start(JabRefMain.java:91) ~[JabRef-3.7.jar:?]
	at net.sf.jabref.JabRefMain.lambda$main$0(JabRefMain.java:39) ~[JabRef-3.7.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_111]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_111]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) [?:1.8.0_111]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_111]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_111]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_111]
19:10:05.787 [AWT-EventQueue-0] INFO  net.sf.jabref.JabRefMain - Arguments passed on to running JabRef instance. Shutting down.
```

**Comment by matthiasgeiger** [comment]
Hi,
and thanks for your report!

We intentionally made this option enabled by default as this reflects the use case of most Users: opening a second bib database should not open a second instance of JabRef.

However, this option can be disabled in the Preferences -> Advanced dialog. And as you can see here also the port can be changes to another one (which also should be solve the Problem in a multi-user setup, as the preferences are stored per user by default)

**Comment by larsvilhuber** [comment]
Is there a command line option to disable it? Using the Preferences dialog implies that you actually succeed in opening it, and that individual users on multi-user systems must be reminded to do this.

My focus here is on security and practicality on multi-user systems, but I am not a programmer. Couple of thoughts.

- If the goal is to prevent a second instance from being opened, wouldn't a check of lock file (within the Jabref-specific preferences in $HOME/.java/.userPrefs/net/sf/jabref/prefs.xml, or something of the kind) achieve a similar goal?
- A randomization of the port (on first start) and subsequent storing in the Jabref specific $HOME/.java/.userPrefs/net/sf/jabref/prefs.xml prevent this clobbering part?
- In the same vein, generating an authentication key, readable from $HOME/.java/.userPrefs/net/sf/jabref/prefs.xml, prevent spoofing of a different user's jabref if  it is sitting on the same port (unlikely but possible)

those wouldn't seem to be particularly hard to implement, since they only change how it is being checked, not that somethign is being checked. But again, I'm not a Java programmer.

Lars

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD
lars.vilhuber@cornell.edu |  +1.607-330-5743
Assistant: ldi@cornell.edu | +1.607-255-2744

http://www.vilhuber.com/lars/
GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by matthiasgeiger** [comment]
Disabling via command line is not possible. And yes, this might be problematic in a scenario where another user on the same system in currently running JabRef. 

However, I honestly don't see that this would be happening in practice. 
If one person is using one machine with more than one user account one can just close the other instance and change the settings ONCE and it will be fine for further sessions. 
If it is really a machine shared by various physical users in a public environment the normal use case would be that upon switching users will be signed off before another user is able to log in.

What exactly is your use case? Or is this more a academic discussion that it MIGHT be troublesome?

In the latter case we would opt for not implementing your suggestions as this would complicate our code for some (imho) rather seldom edge cases.

**Comment by larsvilhuber** [comment]
It is an academic discussion, but the discussion is not academic...

We run a university linux server (cluster frontend) with graphical logon. At any point in time, there are a dozen users logged on, simultaneously. Our university Windows cluster would have ~50 users logged on at any one time. The secure linux cluster that I occasionally consult for will have ~100 simultaneous users. In all of these environments, (a) the likelihood (if we deployed Jabref) of multiple users using it at the same time is positive and significant (b) requiring users to manually modify settings is not feasible (will never work...) (c) some of these environments are "secure" so that anything that opens a port by default would fail security review and might fail to launch.

(c) is a bit of speculation, (a) I encounter regularly while trying to deploy this and (b) is based on extensive experience.

for the Linux system, I'm working on a work-around using the shell launcher. I'll send my version around. I see the current use case of not opening multiple instances as valid as well, so I'll start by simply randomizing the port upon first start. that should solve most of the problems. That might also be easy to include in your code, since (as far as I can tell) the prefs file starts out mostly empty when initialized.

I'll repost my workaround script once I have it. However, it will only work in shared Linux environments, not in shared Windows environments.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD
lars.vilhuber@cornell.edu |  +1.607-330-5743
Assistant: ldi@cornell.edu | +1.607-255-2744

http://www.vilhuber.com/lars/
GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by larsvilhuber** [comment]
Here's the script that for now will work around the issue. I have not deployed it yet, but in testing, it sets the right parameters.

https://build.opensuse.org/package/view_file/home:cornell_vrdc/jabref3/jabref3.startup.sh?expand=0

RPM package for most RPM-based Linux systems (typically with some delay to your latest versions) are here:

https://build.opensuse.org/package/show/home:cornell_vrdc/jabref3

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD
lars.vilhuber@cornell.edu |  +1.607-330-5743
Assistant: ldi@cornell.edu | +1.607-255-2744

http://www.vilhuber.com/lars/
GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by Siedlerchr** [comment]
@larsvilhuber  Thanks for your contribution with the Suse builds! 
Just one thing I noticed, since Version 3.6 JabRef is under the MIT Licence, in your spec script, you still have 

Regarding the port, I could think about a setting/checkbox to randomize the port. @JabRef/developers  Do we have a common opinion here?

**Comment by larsvilhuber** [comment]
SUSE, CentOS, Fedora, and RHEL builds.

Fixed the license, as well as URL and description. Thanks for pointing it out.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
U.S. Census Bureau - CES - LEHD
lars.vilhuber@cornell.edu |  +1.607-330-5743
Assistant: ldi@cornell.edu | +1.607-255-2744

http://www.vilhuber.com/lars/
GnuPG Fingerprint:
0D7D 527F 9268 F693 74BB
A666 FD01 37F0 3362 7346


________________________________________

**Comment by matthiasgeiger** [comment]
Quick fix would be not to define 6050 as hard coded port as default but using `defaults.put(REMOTE_SERVER_PORT, 6000+((int) Math.random()*1000);` for a range between port 6000 and 6999

Another, (additional) option would be to create a command line switch not only to reset specific preferences (-d, --prdef according to http://help.jabref.org/en/CommandLine) but also allow to SET prefs by key.

@JabRef/developers WDYT?

**Comment by Siedlerchr** [comment]
Could be an  option

Am 14.12.2016 9:16 vorm. schrieb "Matthias Geiger" <notifications@github.com

**Comment by koppor** [comment]
+1 for SET prefs by key.

I am not sure how often JabRef is used in multi user setups. Maybe we should really introduce the randomization. However in the range `38001 to 39999` - Source: https://de.wikipedia.org/wiki/Liste_der_standardisierten_Ports (which differs from https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)
