### ISSUE TITLE
Show proper error message for uncaught exceptions

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2288]
JabRef latest version  on Win 10

Steps to reproduce:

1. Add somewhere a `throw new NPE()` (for example, when showing the AboutDialog)
2. Perform the action which invokes this code
3. Nothing happens (e.g. no AboutDialog appears) but also no error message is displayed. (Although an error is logged in the error console.)

With https://github.com/JabRef/jabref/pull/2287 the uncaught error is logged properly, but still no error message is displayed to the user. However, the code in `FallbackExceptionHandler` can easily be adapted to show a message to the user, see e.g. http://www.javaspecialists.eu/archive/Issue196.html.
As there is an [ExceptionDialog](http://controlsfx.bitbucket.org/org/controlsfx/dialog/ExceptionDialog.html) for JavaFX, I mark this issue as after-javafx.

**Comment by Le-wi** [comment]
Hi, I'd like to take this one :)

**Comment by tobiasdiez** [comment]
Happy new year! Feel free to work on this issue and also have a look at our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md). Moreover, feel free to drop by in our [developer chat](https://gitter.im/JabRef/jabref) if you have questions!

**Comment by Le-wi** [comment]
Happy new year as well :+1:

**Comment by Siedlerchr** [comment]
Thanks to @Le-wi  this issue should be fixed in the latest master now!

**Comment by Le-wi** [comment]
This is so exciting, thanks for tagging beginner issues!

**Comment by tobiasdiez** [comment]
@Le-wi we have to thank you for your help! Looking forward to review the next PR from you ;-)
