### ISSUE TITLE
Paste of Id should result in fetched BibEntry

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2292]
After an ID (e.g. arxiv-id) is copied to the clipboard and pasted into JabRef, the IdBasedFetcher should automatically fetch the bibliographic information and create a new BibEntry.
(inspired by https://github.com/JabRef/jabref/issues/1993#issuecomment-250569808)

**Comment by Siedlerchr** [comment]
Currently only works with a DOI.
