### ISSUE TITLE
JavaFX better interface for ListViewTemplates

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2293]
It would be nice to specify the item template for ListView and Table in fxml instead of the ugly CellFactory.
Something similar to
````xml
<cellFactory>
  <TemplateCellFactory>
    <template>  (simply stored as a string-property) with @DefaultProperty (so that this line is not necassy)
      <Label text = "…" />
    </template>
  </TemplateCellFactory>
</cellFactory>
````

Some ideas how to implement this:
- File-based solution: https://github.com/sialcasa/mvvmFX/wiki/ListView-containing-mvvmFX-views
- File-based solution: http://stackoverflow.com/questions/36388527/custom-control-fxml-in-listview-cell-in-javafx-8
- File-based solution: http://stackoverflow.com/questions/19588029/customize-listview-in-javafx-with-fxml
- Load fxml from string: http://stackoverflow.com/questions/16548925/how-to-load-fxml-from-string-in-javafx
- Celll factory in fxml: http://stackoverflow.com/questions/27667749/set-checkboxtablecell-in-fxml and https://rterp.wordpress.com/2013/07/08/using-a-custom-tablecell-factory-to-format-a-javafx-table-in-fxml/
- Documentation of cell factory: http://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/ListView.html#cellFactoryProperty--
- Example for cell factory: http://fxexperience.com/2012/05/listview-custom-cell-factories-and-context-menus/
- Example for cell factory: https://www.turais.de/how-to-custom-listview-cell-in-javafx/
- Same question but without answer: http://stackoverflow.com/questions/24967553/javafx-coding-item-template-cell-factory-in-fxml?rq=1 and http://stackoverflow.com/questions/31643463/what-is-the-equivalent-to-wpf-listview-itemtemplate-in-javafx-listview and http://stackoverflow.com/questions/29042109/javafx8-list-bindings-similar-to-xaml

**Comment by koppor** [comment]
@tobiasdiez May I ask if this is still relevant? Please add "hacktoberfest" or remove "freeze".

**Comment by tobiasdiez** [comment]
Well, it would improve the code but is a lot of work (and should probably be a series of PRs directly against the javafx repository).
