### ISSUE TITLE
DOI to Bibtex is vanished in Jabref 3.7

### ISSUE THREAD

**Issue by thorstenwagner** [JabRef/jabref#2308]
Hi,

in the latest Jabref (3.7) there is no "DOI to Bibtex" websearch entry.

Best,
Thorsten

**Comment by koppor** [comment]
Just try to create a new entry. Press CTRL+n

**Comment by Siedlerchr** [comment]
Hello,

it is not vanished. It was moved to New Entry -> ID-Based Entry fetcher

2016-11-22 10:03 GMT+01:00 Thorsten Wagner <notifications@github.com>:

**Comment by AEgit** [comment]
The DOI retrival has been moved.
Go to Bibtex --> New Entry 
and select "DOI" as ID type. Then copy the doi into the ID field.

To speed this up a little bit, you can do the following:
a) Either use Ctrl+N (replaces the "Bibtex --> New Entry" step
or
b) Select an article in your database and just Ctrl+V your doi there. If the doi is valid, it will immediately create the respective bibtexs entry.

**Comment by thorstenwagner** [comment]
Ah, thanks!
