### ISSUE TITLE
The same subgroups' name in two different groups

### ISSUE THREAD

**Issue by j65ej** [JabRef/jabref#2313]
JabRef version 3.7

Steps to reproduce:

1. The same subgroups' name in two different groups, such as groups1name/subgroupsname and groups2name/subgroupsname
2. Clicking "groups1name/subgroupname ", the subgroup "groups2name/subgroupsname
" is also selected.

**Comment by matthiasgeiger** [comment]
Hi! 
This is a known issue already tracked here: https://github.com/JabRef/jabref/issues/1495

Thus I close this as a duplicate.

Regards
Matthias
