### ISSUE TITLE
Customizing the entry types freezes Jabref

### ISSUE THREAD

**Issue by Dellu** [JabRef/jabref#2318]
JabRef version JabRef 3.7
mac os x 10.11.5 x86_64 
Java 1.8.0_111 on 

Steps to reproduce:

1. BibTex-->Customize Entry Types
2. ...Change one of the entries
3. ...click "apply"

```

```

**Comment by koppor** [comment]
Could you please provide the concrete modification you are doing in step 2? If I add "aspeical" to the list of optional fields for an "article", everything works fine.

File tested with: https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/complex.bib

Can you confirm the issue on your side with the latest development build available at https://builds.jabref.org/master/?

**Comment by melTr** [comment]
Just to mention I also had the same problem but didn't had time to explore why. The new build seems a little bit better but it's not fluid as before. 
The more entries you have on the bibtextype you want to modify, the longer it hangs. It's finishing to resolve, but there no way to know what's happening, it just taking long time (15 seconds on my last trial) when you click ok. 

JabRef 3.7 or JabRef 3.8-dev--snapshot--2016-11-29--master--9d797f2
windows 7 6.1 x86 
Java 1.8.0_111

**Comment by Dellu** [comment]
Yes, it is like MelTr explained. I modify the Required fields: and, hangs for a couple of seconds: between 5-20. Clicking on Apply seems to make it worse. 

I have Jabref 2.8 alongside: that one is fluid and super fast

**Comment by Dellu** [comment]
I cut it out; too long; I can send you if want to see it all..

**Comment by matthiasgeiger** [comment]
Hi there!
I'm currently working on an improvement of the whole entry customization. 
What I can already tell you that the behavior is more or less intended: Upon clicking "apply" or "ok" all entries in all open databases are modified and checked whether all required elements are present or not.

This might require some time - but potentially this process can be optimized (have not checked this yet). At least a status bar or something else should indicate that this is not a problem but JabRef is actually still working in the background.

Workaround: Close the open databases before modifying the custom entry types and open them after the modification.

**Comment by Dellu** [comment]
> Workaround: Close the open databases before modifying the custom entry types and open them after the modification.


Ok, thank you. I will do so. and, you are right, the freezing should be due to the size of my library: as I reduced my  library, the freezing is ameliorated now.

**Comment by matthiasgeiger** [comment]
Hi @Dellu and @melTr!
I was working on the entry type customization in the last week (details of all changes can be found here: #2331) and now new version is ready to be tested which should behave better than the current version.

You can find the test version here: http://builds.jabref.org/improve-entrytype-customization/

Can you please test (after backing up your bibfile and preferences) whether the "freezing" is still an issue for you? 
Thanks!

**Comment by lenhard** [comment]
#2331 is now merged into master, so I am closing this issue. Please reopen if the problem persists.

**Comment by Dellu** [comment]
Dear @matthiasgeiger: it is  working perfectly now: much faster; smoother. Thank you for the fix.
