### ISSUE TITLE
Could not export file : null  Export *.bib file error in headless mode

### ISSUE THREAD

**Issue by bks2005** [JabRef/jabref#2323]
JabRef version <3.7> on <Ubuntu 16.10>, headless mode

Steps to reproduce:
Export *.bib file  to other formats.
for example
1. java -jar JabRef-3-7.jar -n -i 1.bib,bibtex -o 1.csv,oocsv
Importing 1.bib
Exporting 1.csv
Could not export file 1.csv: null
The issue is because of this code  (file net.sf.jabref.cli. ArgumentProcessor.java)
388                try {
389                    format.performExport(pr.getDatabaseContext(), data[0],
390                           pr.getDatabaseContext().getMetaData().getEncoding()
391                                    .orElse(Globals.prefs.getDefaultEncoding()),
392                            null);
393                } catch (Exception ex) {
394                    System.err.println(Localization.lang("Could not export file") + " '" + data[0] + "': "
395                            + ex.getMessage());

Patch: change line 392 
392 - null);
392 + pr.getDatabase().getEntries());

The corrected code:
               try {
                   format.performExport(pr.getDatabaseContext(), data[0],
                           pr.getDatabaseContext().getMetaData().getEncoding()
                                    .orElse(Globals.prefs.getDefaultEncoding()),
                            pr.getDatabase().getEntries());
                } catch (Exception ex) {
                    System.err.println(Localization.lang("Could not export file") + " '" + data[0] + "': "
                            + ex.getMessage());

**Comment by har-wradim** [comment]
Already discussed here: https://github.com/JabRef/jabref/issues/2273 and fixed here: https://github.com/JabRef/jabref/pull/2316

**Comment by matthiasgeiger** [comment]
Thanks for your proposed patch!

But as @har-wradim already said, there is already a PR in the pipeline (#2316)

Thus, I'll close this as a duplicate.
