### ISSUE TITLE
"Remove entry selection from this group" removes entries from similarly named groups

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2334]
JabRef 3.7
windows 10 10.0 amd64 
Java 1.8.0_111

Steps to reproduce:

1. Create a Bibtex file with the groups "mygroup" and "mygroup_alternative". Assign a few entries to both of the groups.
2. Select the entries in "mygroup" and remove them from the group using "Remove entry selection from this group".
3. The entries have been removed from both "mygroup" and "mygroup_alternative". Indeed, if you check the group assignments of the entries they now contain "_alternative" as group assignment, i. e., the first part of the group name has been deleted. As no group "_alternative" exists, the items appear to not be assigned to any group.

Note that this bug is related to a workaround/solution to the issue of group hierarchy in JabRef:
https://github.com/JabRef/jabref/issues/1495

If someone was to use

Asthma
    Asthma treatment
    Asthma diagnosis

as proposed in https://github.com/JabRef/jabref/issues/1495, I suspect that the same problem would arise (?).

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by AEgit** [comment]
I can confirm that this bug has been fixed in JabRef 3.8-dev--snapshot--2016-12-12--master--59d9e35.
Thank you very much for your hard work!
