### ISSUE TITLE
Jabref online instance

### ISSUE THREAD

**Issue by cdupont** [JabRef/jabref#2342]
What about having an online jabref instance?
The idea would be to use the online instance to communicate on your bibtex.
The bibtex file can be hosted on github for instance.
For example one could visualize his database like that:
```
http://online.jabref.org#source=https://raw.githubusercontent.com/Waziup/central-bibliography/master/bibliography.bib
```

**Comment by koppor** [comment]
Please see https://github.com/JabRef/JabCloud. Please follow up the discussion there.

How much are you willing to pay per month or per bibentry? If you find 1000 people paying 10€/month for flat access, we are in and will develop JabCloud. In case this is unrealistic, please join our development of JabCloud. We will support you with our knowledge of JabRef and BibTeX as much as we can.

**Comment by cdupont** [comment]
Nice to know about JabCloud.
While I like it, I think this is overkill.
My need is just to share a list of papers in a visual way. For editing the file, I can use normal jabref and/or vi...

**Comment by tobiasdiez** [comment]
If displaying bibtex is your aim, you can write your own solution in a few minutes using javascript and [bibtex-js](https://code.google.com/archive/p/bibtex-js/).

**Comment by matthiasgeiger** [comment]
... or even more simple: Export the bibtex entries using JabRefs HTML-export abilities. However, this of course would still require some manual effort to publish the HTML files at GitHub and to keep them in sync with the original file.
