### ISSUE TITLE
Cleanup entries: Unicode to Latex

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2351]
JabRef 3.8-dev--snapshot--2016-12-08--master--1371834
windows 10 10.0 amd64 
Java 1.8.0_111

The field formatter in cleanup entries does not work as expected. The formatter "title: Unicode to Latex" does not preserve capital letters with braces.

**Comment by stefan-kolb** [comment]
Can you please add a concrete example.

**Comment by grimes2** [comment]
1. File > New BibTeX database
2. BibTeX > New entry > Article
3. Field title: Capital Letters
4. Quality > Cleanup entries > Recommended for BibTeX > OK
5. Capital Letters instead of {C}apital {L}etters

**Comment by koppor** [comment]
Isn't that the functionality of "protect terms"? Refs https://github.com/JabRef/jabref/pull/1013

**Comment by stefan-kolb** [comment]
I also don't see why there must be braces around the capital letters. We have protect terms for that. One could say it is expected that capital letters get wrapped with {} when transforming to Latex, but as we have the functionality extra one can chose and use protect terms additionally.

**Comment by grimes2** [comment]
What does "protected term" means? `title: protected term` is doing nothing. The problem is that plain style results in a pdf with title "Capital letters" not "Capital Letters"

**Comment by koppor** [comment]
Protect terms protects terms where the casing should be kept. BPMN, BPEL, OASIS, ...

I think, your request goes in the direction of https://github.com/koppor/jabref/issues/126, doesn't it?

**Comment by grimes2** [comment]
No. I mean: First letter is capital letter. For example: "This Is A Test" results in a pdf with title: "This is a test". The braces are needed to preserve the capital letters in bib file title field. This is because the bibliographystyle interprets the title field in this way.

**Comment by koppor** [comment]
Therefore I suggested in https://github.com/koppor/jabref/issues/126 that JabRef just creates 

> title = {{This Is A Test}}

as this is the most common way to protect the casing.

The way we do it in JabRef with Protect Terms is the one where one believes that bib styles such as the one of [LNCS](https://github.com/latextemplates/LNCS) is the right one and that the editors want to have as much as possible lower case letters.

**Comment by stefan-kolb** [comment]
yeah sry, protect terms behaves differently i forgot about that

**Comment by Siedlerchr** [comment]
@koppor  Wrapping whole titles or authors in braces is not recommended!
See discussion here and afaik 
http://tex.stackexchange.com/questions/10772/bibtex-loses-capitals-when-creating-bbl-file

**Comment by tobiasdiez** [comment]
I feel like we already had this discussion about adding braces. There is no way to decide in full generality which words needs to be surrounded by braces and which need no braces. Thus the only practical solutions are to protect certain abbreviations and words (which is what "protect term" does) or surround the whole field in braces (which is tracked by kopper#126). Thus I close this as not-fixable. If somebody has an idea for a good automatic algorithm, please feel free to reopen the issue.
