### ISSUE TITLE
InternalBibtexFields

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2353]
@JabRef/developers  Which of them do we actually use?
I found some that I have never heard of and never seen them, please help 😄 

- [ ] FieldName.RELATED

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/574

**Comment by Siedlerchr** [comment]
Rrelated field (separated values)
Citation keys of other entries which have a relationship to this entry. The relationship
is specified by the relatedtype
field. Please refer to §3.4 for further details.

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/pull/1637
