### ISSUE TITLE
F4 should open currently selected file

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2355]
<kbd>F4</kbd> opens the first attached file. When in the General tab another file is selected, this should be opened.

![not-functioning](https://cloud.githubusercontent.com/assets/1366654/21022964/db19a334-bd7e-11e6-8cbc-acaf6f090e7f.gif)

This is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=445301

**Comment by stefan-kolb** [comment]
F4 is hooked to the mainTable but not the file table in the general tab that's why it opens another PDF all the time.
`mainTable.getSelectedEntries();`
