### ISSUE TITLE
F4 (Open file) greyed out / no BibTeX key to filename search

### ISSUE THREAD

**Issue by dtexwang** [JabRef/jabref#2365]
I am using JabRef **version 3.7** on Windows 7.  When a reference that does not have PDF(s) linked to it is highlighted in the entry table, pressing F4 does nothing.  The corresponding menu item Tools > Open file is greyed out:

![untitled37](https://cloud.githubusercontent.com/assets/5307733/21082103/2b918398-bfa2-11e6-8cda-5b7253a2bdd3.png)

In previous versions (e.g., **version 3.5**), pressing F4 while a line is highlighted in the main Entry Table would either open the linked PDF file, or search the main directory and its subfolders for a file whose filename begins with/contains the BibTeX key.  In JabRef version 3.5, this feature can also be accessed under Tools > Open file (not greyed out):

![untitled35](https://cloud.githubusercontent.com/assets/5307733/21082060/3e02506c-bfa1-11e6-8154-9fa5a5355300.png)

Relevant excerpt from the [JabRef online help file](https://help.jabref.org/en/ExternalFiles):
> ## The main PDF and PS directories
> 
> JabRef makes it easy to link PDF and PS files to your entries. To take advantage of this, you have to indicate in Options -> Preferences -> External programs your main PDF and PS directories. All PDF and PS files that are stored in or below each of these directories will be referred to with a relative path by JabRef, making it easy for you if you need to move the PDF and PS directories, or if several users use the same database from different network places.
> 
> Additionally, if you give your PDF and PS files names that correspond to the relevant entry’s BibTeX key (plus ‘.pdf’ or ‘.ps’), JabRef will be able to search your main directories and its subfolders for the correct PDF and PS. Once the correctly-named PDF or PS is in place you access this function by clicking the ‘Auto’ button next to the PDF and PS fields in the entry editor. If the PDF or PS is found, the field will immediately be set.
> 
> If you name a PDF or PS file as mentioned, you can also open the file without setting the PDF or PS field of the entry at all. The downside is that the PDF or PS icon will not appear in the table unless you do (manually or with the ‘Auto’ button).

I use JabRef almost exclusively as described in the last paragraph.  That is, I do not set the PDF or PS fields of any entries, and rely on JabRef matching the BibTeX key to the filename to open the correct PDF upon hitting F4.  Can this function be restored?

Possibly related issue: #2355

**Comment by stefan-kolb** [comment]
Please use `Quality -> Automatically set file links` or F7 once to auto link the files . After that you should be able to use the F4 approach as expected.

**Comment by dtexwang** [comment]
Thank you for your response.  In previous versions, there was no need to use <kbd>F7</kbd> or `Quality -> Automatically set file links` to auto-link first before pressing <kbd>F4</kbd>.  As long as the [RegEx search](https://help.jabref.org/en/ExternalFiles#a-href-idregularexpressionsearchusing-regular-expression-search-for-auto-linkinga) on `**/.*[bibtexkey].*\\.[extension]` could find the correct PDF file, <kbd>F4</kbd> would open it.  This was a very convenient feature because I frequently move PDF files between subdirectories of the main PDF directory.  Is there any way for this feature to be restored in a future release?

**Comment by stefan-kolb** [comment]
We had a quick discussion between developers and concluded that while the former behavior was convenient, it was really unexpected as it did find PDFs but di not link them properly afterwards. Therefore, I changed the documentation for this now to behave like I explained before. If none of the developers and or more users have a different opinion here, it will stay as is for the nearer future at least.

**Comment by koppor** [comment]
The documentation currently says that JabREf automatically finds the file - see https://help.jabref.org/en/ExternalFiles#the-database-specific-pdf-and-ps-directories

I will try to investigate to bring back the old behavior as I personally also find it very convenient.
