### ISSUE TITLE
Manage tex glossaries

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2366]
Issue for the feature request

http://tex.stackexchange.com/questions/342544/is-there-a-program-for-managing-glossary-tags?noredirect=1#comment842701_342544

General idea: 
Import/Export tex format (Serialization)
Similar to journal abbreviations, but more complex definitions possible
Plural, short/long forms
Plural - Yes/No option

**Comment by simonharrer** [comment]
Idea: create JabTex, like JabRef, but the functionality targeted for the latex files. Could incorporate ideas and code from https://github.com/simonharrer/textools

**Comment by Siedlerchr** [comment]
See also  https://github.com/nlct/bib2gls

**Comment by tobiasdiez** [comment]
I think this can be closed now as I don't see anybody working on this in the foreseeable future.
