### ISSUE TITLE
cannot close auto backup

### ISSUE THREAD

**Issue by songhuadan88** [JabRef/jabref#2378]
JabRef version 3.7 on Win 10

Steps to reproduce:

1. Opinions->Preferences->File->General Uncheck "backup old file when saving"
2. Press OK
3. Opinions->Preferences->File->General, the item is still checked

**Comment by koppor** [comment]
Confirmed with latest master

**Comment by songhuadan88** [comment]
@koppor thanks for your consideration.
I have checked your development version and it also works for me too.
