### ISSUE TITLE
Medline ID ==> PubMed ID?

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2379]
In BibTeX -> New entry..., it is possible to generate an entry based on its ID. One of the ID type is "Medline".

At https://www.nlm.nih.gov/pubs/factsheets/medline.html, a sample record is given. It displays a PMID
equal to 23817699. Entering this ID into JabRef fetches the sample record.
Hence, what JabRef calls "Medline ID" is in fact the content of the "PMID" field.

PMID stands for the "PubMed Unique Identifier" (see https://www.ncbi.nlm.nih.gov/books/NBK3827/#pubmedhelp.Search_Field_Descrip )
As explained at https://www.nlm.nih.gov/bsd/mms/medlineelements.html#pmid , "Since 2004 [...] The PMID has become the unique identifier for the MEDLINE record".

PubMed identifier is well-known (e.g. wikipedia recognizes it: https://en.wikipedia.org/wiki/Wikipedia:PMID), while Medline ID is not (and is now defunct).

Hence, I suggest renaming Medline ID into PubMed ID

**Comment by matthiasgeiger** [comment]
Hi!
I agree that this is currently not the best naming in case of Medline. However, changing this is not as easy as it seems to be: The name "Medline" is used for both, the id-based and the normal web fetcher. Thus, renaming it to "PMID" would also rename the web fetcher.

I'm not really a domain expert and I don't know we actually using "Medline" or whether the whole fetcher should be named "Pubmed" (which seems to be a superset of Medline + additional resources; see https://www.nlm.nih.gov/pubs/factsheets/dif_med_pub.html)

**Comment by kanasimi** [comment]
I noticed that the Medline ID for some articles do not match their PubMed ID.

Acute TNF-induced repression of cell identity genes is mediated by NFκB-directed redistribution of cofactors from super-enhancers (Q40795476)

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&retmode=json&id=26113076

**Comment by koppor** [comment]
> I noticed that the Medline ID for some articles do not match their PubMed ID.

Could you open a new issue? Maybe describing the expected behavior?

**Comment by kanasimi** [comment]
Sorry. Since the Medline ID has been discontinued, I just wanted to note that these two IDs may differ.
