### ISSUE TITLE
Move file to file directory can overwrite files

### ISSUE THREAD

**Issue by davydden** [JabRef/jabref#2385]
JabRef version  on 

Steps to reproduce:

1. Have two different files attached to the paper of the same type (i.e. `.pdf`)
2. Do "Move file to file directory" twice and observe that one file is overriden by another

**Comment by Siedlerchr** [comment]
I am having problems to reproduce the error and need some more details on your setup:

I have a database-specific General file directory C:\XXXX\asdfasdf
I have an entry with 2 different pdf files.  Both pdf files are in C:\YYYY\
Bib filie lies in C:\YYY\biblocation 

I execute **only** Cleanup: Move files to file directory + make links relative 
The cleanup moves the files to the target directory (ignoring fiileDirPattern atm)  correctly, but reports that no entry needed a cleanup. 

Did you execute Rename PDF Cleanup, too?

**Comment by davydden** [comment]
> I execute only Cleanup: Move files to file directory + make links relative

cleanup is fine, i was doing it manually in `General` tab of the the entry by right clicking on each .pdf and the `Move file to file directory`.

**Comment by Siedlerchr** [comment]
I think I found one of the problems: When you do a right click in the EntryEditor int he General Tab on the the FileList, it does not correctly move the file nor does it respect  the fileDirPattern. I just figured out, that the EntryEditor ist in fact using a **copy** (!) of the code in cleanup.  When implementing #1899  I was not aware of this fact.... 👊 😕

**Comment by Siedlerchr** [comment]
@davydden  It's been some time, but I finally implemented a solution. The GUI code in the Entry Editor now uses the same functionality as the normal Cleanup does. This means, files are no longer overwritten.
You can test the development version here:
http://builds.jabref.org/moveFileDir/

I tested following cases:
A.pdf
B.pdf
=> Both get moved to fileDir (also respecting fileDir Pattern)
So with `fileDirPattern=\EntryType `you have `\Article\A.pdf and \Article\B.pdf`

Renaming works the same:
Article Author = Some Author 
Year 2011
=> First file selected will be renamed to bibtexkey
=> Second file selected will be just moved to directory 

I  now only have to implement some Preview  GUI dialog, but the core functionality works.

**Comment by davydden** [comment]
@Siedlerchr thank you very much, i will try to test it soon...

**Comment by lenhard** [comment]
We think this is fixed in current master, hence I am closing it.

Feel free to reopen if the problem reappears.
