### ISSUE TITLE
JabRef and the X Window clipboard/selections

### ISSUE THREAD

**Issue by gregoa** [JabRef/jabref#2389]
[JabRef version 3.8~pre2+ds-1 from Debian/experimental. But the issue is not specific to this version.]

The X Window System has usually three "selections": primary/XA_PRIMARY - copying by highlighting with the first mouse button, pasting by clicking the third (middle) button; secondary/XA_SECONDARY (never seen this in action); and clipboard/XA_CLIPBOARD which acts like the clipboard on e.g. Windows (Ctrl-C, Ctrl-V and copy/paste menu items or buttons).

It seems that JabRef only supports the last version (the "clipboard"). This can be seen e.g.
- in the "Copy DOI URL" function which copies the URL into the XA_CLIPBOARD selection (and not (also) into XA_PRIMARY);
- in the "New entry from plain text" dialog, where (first of all neither middle-clicking/XA_PRIMARY nor Ctrl-V/XA_CLIPBOARD in the text box does anything but) using the "Paste" button pastes the contents of the XA_CLIPBOARD selection.

I don't know how to make Java under X11 use the XA_PRIMARY selection as well but I'm sure this is not the first time in the history of Java that this question comes up :)

Cheers,
gregor

**Comment by Siedlerchr** [comment]
Thanks for your report, this seems to be a java problem. I found some info
about in this German java book which states that java currently can not use
the secondary clipboard

http://openbook.rheinwerk-verlag.de/javainsel9/javainsel_19_025.htm

Am 16.12.2016 11:07 nachm. schrieb "gregor herrmann" <
notifications@github.com>:

**Comment by Siedlerchr** [comment]
However, primary is supported (can't edit my comment on mobile)

**Comment by koppor** [comment]
With JavaFX it seems to be impossible (?): [How can I read the X11 clipboard from a JavaFX application?](http://stackoverflow.com/q/21844255/873282). So strange that this seems not to be discussed on stackoverflow... I am now playing around with `Toolkit.getDefaultToolkit().getSystemSelection()`.

**Comment by koppor** [comment]
@snisnisniksonah found https://bugs.openjdk.java.net/browse/JDK-8088117:

> Using JavaFX-8 with Java8u45 on SUSE11, there is no possibility to copy/paste using mouse selection or using a click on the scroll. See details here: http://stackoverflow.com/questions/30032290/javafx-mouse-clipboard-does-not-work-in-unix

The solution won't satisfy you:

> Lowering the priority to P4. I note that this is more of an unimplemented feature than a bug (it has never been supported in FX). We will look at it for JDK 9.
> Workaround: use copy/paste (CTRL-C / CTRL-V) 

Reading @glaubitz (https://lists.debian.org/debian-java/2017/08/msg00024.html), I have the hope, there could be someone "just" implementing that.

**Comment by koppor** [comment]
Since this is not possible to implement, I close the issue.

Having the hope that JDK9 or JDK10 can solve that, I added [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and close the issue for now.

**Comment by koppor** [comment]
I rechecked the issue on openjdk and it is still not implemented.

**Comment by koppor** [comment]
There is a SO answer from Feb 2019: https://stackoverflow.com/a/54530538/873282. Needs to be checked.

**Comment by davidemdot** [comment]
Hey! I would like to work on this issue, if it is available :"D

**Comment by koppor** [comment]
Go ahead! 👍

**Comment by koppor** [comment]
@gregoa We worked on it and think, we fixed it. Could you try the latest build at https://builds.jabref.org/master and report back if it works for you.

**Comment by gregoa** [comment]
On Sun, 27 Oct 2019 07:31:16 -0700, Oliver Kopp wrote:

> @gregoa We worked on it and think, we fixed it. Could you try the
> latest build at https://builds.jabref.org/master and report back if
> it works for you.

I tried with the linux portable version, and I can confirm that it
works, i.e. I can both Ctrl-C/Ctrl-V and
select/paste-with-middle-click.

Thanks for implementing this feature!


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: Maryse Nicolai: n/a
