### ISSUE TITLE
Erratic behavior when clicking on "Get fulltext"

### ISSUE THREAD

**Issue by avaucher** [JabRef/jabref#2391]
JabRef development version on Linux (and probably other platforms)

In some cases, the behavior when clicking on "Get fulltext" is erratic or, at least, unexpected and/or misleading.
Two cases are explained below.

## Steps to reproduce:

First, in "File -> Database properties", set "General file directory" to the directory with your files to link. 

### Case A: When multiple entries are selected.

1. Have two bibtex entries with Bibtexkeys "a" and "b"
2. Create corresponding files "a.pdf" and "b.pdf" in the directory chosen before.
3. Double-click on "a" to select it and show the editor view
4. In the editor view, go to the "General" tab.
5. With Ctrl, click on the entry "b" so that both "a" and "b" are selected, and the editor view still shows entry "a"
6. Click on "Get fulltext"

Result: Both "a.pdf" and "b.pdf" are added to entry "a" !!

### Case B: When adding an entry after performing a search.

0. Create corresponding files "a.pdf" and "b.pdf" in the directory chosen before.
1. Have a bibtex entries with Bibtexkeys "a", containing the text "AAA"
2. Select entry "a"
3. Perform a search for "AAA". Only the entries containing "AAA" are listed.
4. Create a new entry. In the editor view, give it the bibtexkey "b"
5. Under the "General" tab, click on "Get fulltext"

Result: Instead of linking the file "b.pdf", it will link the file "a.pdf" !!

**Comment by koppor** [comment]
When #2270 is solved, this issue also gets solved.

**Comment by koppor** [comment]
The fix provided by @avaucher at https://github.com/JabRef/jabref/issues/2392 also provides a solution, which works, because the action of the button is local to the entry editor.
