### ISSUE TITLE
Blank Windows

### ISSUE THREAD

**Issue by PUKK** [JabRef/jabref#2393]
I am using JabRef on OpenSuse 42.1 with KDE  (JabRef 3.8.1-dev--snapshot--2016-12-17--master--31c5277,
linux 4.1.36-38-default amd64 , Java 1.8.0_111). 
Sometimes I get blank/empty windows when opening (sub) windows from JabRef. The simplest example is the "About JabRef" page. Only the header "About JabRef" is shown, the rest of the text beneath is missing. If, however, I resize the window slightly, the text suddenly appears. This finding depends on the size of the main window. For some sizes, this bug appears, for others not.  The same issue is there with other windows such as the Import window. 

I tested if there is a dependence on the  "Look and Feels" but the this issue is there with the "Look and Feels"
com.sun.java.swing.plaf.gtk.GTKLookAndFeel
javax.swing.plaf.metal.MetalLookAndFeel
com.jgoodies.looks.plastic.Plastic3DLookAndFeel

BTW, I cannot  use
com.jgoodies.looks.windows.WindowsLookAndFeel
("Unable to find the requested look and feel and thus the default is used")

Anway, Jabref is a great tool! Thanks a lot for the excellent work on JabRef!!

**Comment by koppor** [comment]
Does this happen also with old versions (e.g., 3.7)?

I tried to downgrade our swingx library from 1.6.4 to 1.6.3 at https://builds.jabref.org/downgrade_swingx/. JabRef 3.7 and before use 1.6.1. If you test these two versions, we can check whether this library is the issue.

**Comment by PUKK** [comment]
Unfortunately, the problem is still there with the downgraded library. Actually, I once in a while had this issue with previous versions. But since it only appears for certain sizes of the main JabRef window, one does not constantly run into this problem.

**Comment by koppor** [comment]
Could you try https://builds.jabref.org/javafx/? At least the About dialog should properly render there.

**Comment by PUKK** [comment]
With that build I unfortunately get
Error: Could not find or load main class net.sf.jabref.JabRefMain

**Comment by koppor** [comment]
You need to install support for JavaFX. The normal OpenJDK JRE does not come with JavaFX support. We have installation hints for Ubuntu, Debian, and CentOS at <http://help.jabref.org/en/Installation>, but not for SUSE.

I googled a bit and it seems, that you have to switch to Oracle's JDK: http://tutorialforlinux.com/2014/03/20/how-to-install-oracle-jdk-8-on-opensuse-12-x-13-x-32-64bit-easy-guide/

Maybe you have more experience than us regarding SUSE and provide hints how to get javafx running there.

**Comment by PUKK** [comment]
To get the JavaFX support under OpenSuse (at least for those version for which the package below is available):

download (unofficial) package from
https://software.opensuse.org/package/java-1_8_0-sun
install package for the respective OS version using "sudo rpm -Uvh"
 
Set alternatives: 
sudo update-alternatives --config java  (choose Sun/Oracle version)

Then the JavaFX version of JabRef works and the "About" dialog indeed works (but looks different from the non-JavaFX version). Unfortunately, the problem with the "Import" window persists.

When determining the size of the "Import" and the "About" dialog, these sizes seem to depend on the size of the main window. My guess is, that you should allow only window sizes which are multiples of 2 , 8 or something like this (at the very least integer). With "strange" window sizes, the text apparently is not shown.

**Comment by koppor** [comment]
@PUKK Thank you for the information on the installation. Could you update http://help.jabref.org/en/Installation? This would help us!

**Comment by stefan-kolb** [comment]
It looks like this is an issue that is independent from JabRef. Maybe even graphics driver related. At least we cannot do anything right now as noone of @JabRef/developers can reproduce this issue 😞
