### ISSUE TITLE
Group names including brackets and spaces do not filter group anymore in v3.8

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#2394]
In version 3.7 is organized static groups with names like:
[a] Group1
     [aa] Subgroup1
     [bb] Subgroup2
[b] Group2
     [aa] Subgroup1
     [bb] Subgroup2

The letters in brackets are part of the group or subgroup name. I use this to achieve alphabetical ordering of my groups. This worked fine in v3.7
In version 3.8 names of groups/subgroups that contain brackets and spaces do not work anymore. Clicking on the subgroup names does not filter the group members. 
This happens under Windows 7 as well as under Ubuntu 16.04.

**Comment by tobiasdiez** [comment]
Thanks for reporting this issue. It should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by juejung** [comment]
Thanks, works perfectly.
