### ISSUE TITLE
The group function requires lower case field names

### ISSUE THREAD

**Issue by soerendip42** [JabRef/jabref#240]
Using jabref  2.9.2 the name of the field used for dynamic groups have to be lower case. 
E.g. "comments" instead of "Comments". Although the fields name is actually "Comments".
If I use "Comments" dysfunctional groups and subgroups are generated. 
Would be nice to have a hint or automatically set it to the required format.

**Comment by stefan-kolb** [comment]
Does this also apply to 2.11beta?

**Comment by soerendip42** [comment]
I use the version that is in the repository of fedora which is 2.10 at the moment.
Apparently, it is fixed in 2.10 though.
