### ISSUE TITLE
Assigned entries to static group dose not work: count and highlight broken

### ISSUE THREAD

**Issue by sehlstrom** [JabRef/jabref#2408]
JabRef version 3.8 on Windows 10

Steps to reproduce:

1. Create static group "Mechanics of Bar Frameworks"
2. Select some entries
3. Drag and drop selected entries to newly created static group.
4. The line ``groups    = {Mechanics of Bar Frameworks},`` is added to all selected entries.

Then you would expect that (1) the number of entries in the group would change from [0] to [n] and (2) that when you select the group you would have your added entries highlighted. Non of (1) and (2) happens in my case. 

![image](https://cloud.githubusercontent.com/assets/3474084/21353259/7ed5e272-c6c5-11e6-999a-cf523494cf4e.png)

**Comment by tobiasdiez** [comment]
I think this is fixed in the latest development version. Could you please try the build from http://builds.jabref.org/master/ and report back if the problem still persists. Thanks!

**Comment by sehlstrom** [comment]
Thanks

Version 3.8.1-dev--snapshot--2016-12-20 works.

**Comment by matthiasgeiger** [comment]
Thanks for the feedback!

**Comment by lenhard** [comment]
Let us leave this open until the next release and mark it as fixed-in-dev-builds to make sure that google shows it to people who run into the problem.

**Comment by lenhard** [comment]
Since 3.8.1 has been released, we can close this now.
