### ISSUE TITLE
Add Group - dialog: width is to small for text/font

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#2419]
I am using JabRef 3.8 (linux 4.9.0-towo.1-siduction-686 i386 Java 1.8.0_111) on Debian GNU/Linux _unstable_ (Siduction Linux) with XFCE as desktop environment. The version of the deb-package is `3.8+ds-2`.

The "Add Group" dialog has a fixed width (what is a bug for itself) and it is to small to show all text. Please see the screenshot and look at "Hirarchical context".

![jab1](https://cloud.githubusercontent.com/assets/11861496/21419949/164492b4-c82b-11e6-8fda-48b34d76d459.png)

My appearance settings look like this

![japb2](https://cloud.githubusercontent.com/assets/11861496/21419956/23cf5752-c82b-11e6-813a-c28d8475757d.png)

I can not say which font is used in that dialog. I haven't modified any font settings in XFCE.

I first discussed that topic in the [Forum](http://discourse.jabref.org/t/add-group-width-of-the-dialog-to-smal/385) where I was told to open a bug report here.

**Comment by matthiasgeiger** [comment]
Just again verified on my windows machine: Not a problem here - neither for standard windows look-and-feel, nor for `MetalLookAndFeel` - seems to be dependent on Linux - or even a more specific problem.

**Comment by buhtz** [comment]
I agree and think the same that it depends on the used desktop environment or window manager.

But I think at this point the view direction should be modified. JabRef use a plattform independent programming language. But the GUI (is it swing?) is use a way that it break this independency.

I would recommend a two-point solution.

1. Make the dialog resizable like the other dialogs (e.g. Preferences), too.
2. Make the text in the dialog wrapping automaticly.

btw: The Preference dialog doesn't wrap text, too. Does this behaviour depend on Swing?

**Comment by matthiasgeiger** [comment]
`JLabel`, which is the standard Swing component for this, does not wrap texts which are too long.

**Comment by buhtz** [comment]
I see. Then it is a "bug" there. But it is oracle and it would waste of time to open a bug report about that.

Alternativly you could cut the strings in that two JLabels. It is to much. Add the extra (explaining) text into tool tips.

**Comment by koppor** [comment]
JavaFX?

**Comment by buhtz** [comment]
An easie solution would be to make the dialog itself resizable.

**Comment by noMICROSOFTbuhtz** [comment]
Part of the problem is fixed in 5.* dev version. All strings (in english and german) are completly fit to the dialog.

But the dialog itself is not resizable.

**Comment by Siedlerchr** [comment]
The dialog needs to be converted to javafx as well. Tracked in #3861

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
