### ISSUE TITLE
Automatic file link settings crashes if key contains specific characters

### ISSUE THREAD

**Issue by Uiske** [JabRef/jabref#2423]
JabRef version 3.8 on OpenSUSE 

1. Have a bibtex key entry with special characters in it like NA(ME_JOURNAL
2. Start "automatically set file link" F7
3. Box appears, but process never finishes and nothing happens even when entries with valid bibtex-keys are selected also
4. No error message is issued

**Comment by lenhard** [comment]
Possibly related #2309

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
