### ISSUE TITLE
Backslashes are repeatedly escaped on save in Content-Selectors

### ISSUE THREAD

**Issue by universal** [JabRef/jabref#2426]
Hello,

JabRef version: JabRef 3.8; linux 4.4.0-57-generic amd64; Java 1.8.0_111 on Ubuntu 16.04
Steps to reproduce:

1. Create a new, empty database (bibtex mode)
2. Add a keyword under manage content selectors for journal: Test {\"U}mlaut
3. Hit Save
4. Check comment in editor: ... Test {\\"U}mlaut ...
5. Restart Jabref
6. Hit Save
7. Check comment in editor: ...Test {\\\\"U}mlaut

So with every save each Backslash is escaped again and again. 

### 1. Save
```
% Encoding: ISO-8859-1

@Comment{jabref-meta: databaseType:bibtex;}

@Comment{jabref-meta: selector_journal:Test {\\"U}mlaut;}
```

### 2. Save
```
% Encoding: ISO-8859-1

@Comment{jabref-meta: databaseType:bibtex;}

@Comment{jabref-meta: selector_journal:Test {\\\\"U}mlaut;}
```

I hope this provides all necassary and relevant information. I hope I haven't missed something. :-)

**Comment by lenhard** [comment]
Thanks for your report! This sounds like something that is hopefully not too hard to fix. I will have a look at it after new year.

**Comment by lenhard** [comment]
@universal In a few minutes, a dev version of JabRef that fixes this issue should be available here: http://builds.jabref.org/contentselector-escaping/ Can you please try it out?

Please note that meta data information in JabRef has to be escaped. Thus, if you enter a new selector keyword `{\"U}mlaut` in the UI, it should be written into the bibfile on save as `{\\"U}mlaut`, but upon parsing `{\"U}mlaut` should be displayed in the UI and written into an entry if you select it.
