### ISSUE TITLE
JabRef-2.11b5-setup.exe broken?

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#243]
I have just tried to install JabRef2.11beta5 on windows xp.

JabRef-2.11b5-setup.exe looks broken: installation crashes.
Note: the exe file is only 6.2 Mb, while JabRef-2.11b4-setup.exe was 18 Mb

**Comment by matthiasgeiger** [comment]
Confirmed..

**Comment by stefan-kolb** [comment]
@koppor Please consider yanking the beta5 release asap as it seems to be severly broken.

**Comment by koppor** [comment]
Yanked.
