### ISSUE TITLE
Launching JabRef by opening a file from Windows 10 explorer does not make it the focused tab when other files were re-opened per preference

### ISSUE THREAD

**Issue by fuhrmanator** [JabRef/jabref#2430]
JabRef version 3.1 on Windows 10

Steps to reproduce:

With **Preferences > File > Open last edited databases at startup** enabled,
1. Open a bib file "A.bib" in JabRef.
2. Quit JabRef
3. Double-click a bib file "B.bib" to launch JabRef
4. The tab for "B.bib" is open, but the focus is on "A.bib" tab, which had focus prior to step 2 above. 

Note: if step 2 is skipped (JabRef is not quit), everything seems to work properly.

Since Windows apps typically put focus on the tab of the file that was just opened, this is a usability bug (I have myself added new references to the wrong database many times before I realized this was happening).

**Comment by Siedlerchr** [comment]
I can not reproduce this with JabRef Version 3.8 on Windows 10.
The focus is always on the correct B.bib file tab. 
I would sugget you try upgrading to 3.8.

**Comment by fuhrmanator** [comment]
Indeed, 3.8.1 doesn't have this problem. Sorry for the noise (and being so far behind...)
