### ISSUE TITLE
Can download article by DOI but not title

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2431]
If I click the New Bibtex Entry button, paste this DOI:

    http://dx.doi.org/10.1016/j.engappai.2016.01.001

into the ID field, and then click the Generate button, then Jabref successfully downloads the article's BibTeX entry.

But if I instead paste the article's title into the ID field, change the ID Type to Title, and then click Generate, I get the error shown in this screenshot:

![image](https://cloud.githubusercontent.com/assets/3851891/21470766/0d0087c4-ca5d-11e6-8aa2-0fd1e2bbfb01.png)

I'm using the title string:

    Traffic flow optimization: A reinforcement learning approach

This is with: 

    JabRef 3.8.1 windows 7 6.1 amd64  Java 1.8.0_111

**Comment by Siedlerchr** [comment]
Hi, yes it's a bit confusing. 
The ID-based fetcher is the prefered way. You enter an unique identifier, e.g. a DOI, an ISBN or another identifier. Then the bibtextdata is pulled from that identifier.

The title based fetcher works the other way round: It searches www.crossref.org for the title and tries to get a doi for it. If a doi is found, the bibtexdata is pulled from it. 
Also a manual search at Crossref with the title revealed the article with a doi, it might be a problem with the CrossRef api.

**Comment by stefan-kolb** [comment]
It is a problem of the Crossref API. For some reason it only lists the entry as second result, but we only check the best result inside the CrossRef fetcher:
https://search.crossref.org/?q=Traffic+flow+optimization%3A+A+reinforcement+learning+approach

**Comment by stefan-kolb** [comment]
Ok, I relaxed the Crossref fetcher a bit. It checks more results now, in case the Crossref API does some wierd things like in that case.
You can try a build from http://builds.jabref.org/crossref-fetcher.
