### ISSUE TITLE
Can't update bibliographic information from the web

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2432]
If I generate an entry from this DOI:

    http://dx.doi.org/10.1016/j.engappai.2016.01.001

delete the journal title, and click the "Update bibliographic information from the web" button, and select either MathSciNet or SAO/NASA..., then Jabref can't restore the title, and there's a message in the lower left corner saying it couldn't find any bibliographic info:

![image](https://cloud.githubusercontent.com/assets/3851891/21470847/f2ffb59a-ca5f-11e6-81bc-9bd060b0b6ab.png)

Am I using the feature correctly?

This is on:

     JabRef 3.8.1 windows 7 6.1 amd64  Java 1.8.0_111

**Comment by lenhard** [comment]
I just tried this and both databases return a result (with a wrong incorrect, but anyway...).

Could you try again? Maybe the failure was due to connection issues on the side of the databases or your access network? If the problem persists, can you have a look at the error console (Help -> Show error console) and see if there are any problems reported?

**Comment by notuntoward** [comment]
Hmm, still doesn't work for me.  Maybe my explanation was lacking:  I'm clicking the icon on the left side of the screenshot just above the trashcan.  After clicking it and selecting either of the sources, nothing happens.

**Comment by lenhard** [comment]
@notuntoward No worries, your explanation was fine. I was clicking the exact same button. Strangely, it works for me. 

Let us see if one of the other developers manages to reproduce the issue.

**Comment by tobiasdiez** [comment]
Your example entry is not included in MathSciNet (see [result for a manual search](http://www.ams.org/mathscinet/search/publications.html?pg4=ALLF&s4=&co4=AND&pg5=TI&s5=%CC%81%CC%80Traffic+flow+optimization%3A+A+reinforcement+learning+approach&co5=AND&pg6=PC&s6=&co6=AND&pg7=ALLF&s7=&co7=AND&dr=all&yrop=eq&arg3=&yearRangeFirst=&yearRangeSecond=&pg8=ET&s8=All&Submit=Search) ) and also not published on the arXiv. Thus you can't expect that these services give you proper information.

**Comment by notuntoward** [comment]
OK, but I think this is still a bug, or a feature request.  

First, I didn't look at MathSciNet or arXiv but instead, MathSciNet and SAO/NASA.

Second, I populated that entry with JabRef's own DOI lookup but JabRef is then unable to find the same information (the title I deleted) when I use JabRef's "Update bibliographic information from the web" button.  

JabRef found it once; it seems like it should be able to find it again.

**Comment by lenhard** [comment]
@notuntoward So if I understand you correctly, you want another option for the "Update bibliographic information from the web" button, namely something like "From DOI" that replicates the functionality of the DOI-based entry generator? In this case, have a look at the button "Get BibTeX data from DOI" that is next to the DOI field in the entry editor :-)

Providing the functionality also for the "Update bibliographic information from the web" button would be more consistent UI-wise. That would be a new feature, so I'll reopen this as a feature request.

**Comment by notuntoward** [comment]
Sounds good.  Thanks.

**Comment by tobiasdiez** [comment]
The "update from DOI" feature is now implemented. Thanks for the suggestion!
