### ISSUE TITLE
Hangs forever when saving file with a key with {\"u} in it

### ISSUE THREAD

**Issue by karyon** [JabRef/jabref#2439]
JabRef 3.8.1
windows 10 10.0 amd64 
Java 1.8.0_111

loading this file
```
@ARTICLE{Biguen.etal-1991,
  pdf = {Big{\"u}n - some title.pdf}
}
```

jabref will ask something about updating pdf links. when clicking yes, and then saving the file, jabref just says "saving database..." forever and never finishes. when closing jabref, it says something like "waiting for saving operation to finish".

**Comment by lenhard** [comment]
Might be a bug in the deprecated field conversion logic. Actually, the pdf field is deprecated since quite some years already. It is also a little strange that you have LaTeX-encoding in file names, given the fact that no operating system supports such characters in file names.

**Comment by jannuc** [comment]
I actually have the same problem. It started couple months ago when I installed a newer Jabref version in a new computer I got. I couldn't figure out what was triggering it; thanks for finding out @kayron. Now unfortunately I guess I have to go through each of the 500+ references in my database to find which one(s) have such encoding

**Comment by karyon** [comment]
i actually binary searched them, commenting out half of the remaining comments each time.

**Comment by stefan-kolb** [comment]
Seems to be an ancient serialization problem. 
It must be something like 
```
@ARTICLE{Biguen.etal-1991,
  pdf = {Big{\\"u}n - some title.pdf}
}
```
See the double slash.

But probably easier and more safe to also change all `pdf` fields to `file` fields.
```
@ARTICLE{Biguen.etal-1991,
  file= {Big{\\"u}n - some title.pdf}
}
```

Or just delete the field and link it to the pdf again.
