### ISSUE TITLE
2.11beta5 & xp: does not start...

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#244]
Hello, 

On my xp virtual machine, JabRef-2.11b5 does not start. No window is displayed.
Here are  the messages:

C:\test>java -jar JabRef-2.11b5.jar
Oct 16, 2015 9:04:31 AM org.java.plugin.registry.xml.ManifestParser <init>
INFO: got SAX parser factory - com.sun.org.apache.xerces.internal.jaxp.SAXParser
FactoryImpl@132ca2b
Oct 16, 2015 9:04:31 AM org.java.plugin.registry.xml.PluginRegistryImpl configur
e
INFO: configured, stopOnError=false, isValidating=true
Oct 16, 2015 9:04:31 AM org.java.plugin.registry.xml.PluginRegistryImpl register

INFO: plug-in and fragment descriptors registered - 2
Oct 16, 2015 9:04:31 AM net.sf.jabref.plugin.PluginCore initialize
INFO: Found 2 plugin(s):
  - net.sf.jabref.core (jar:file:/C:/Documents%20and%20Settings/fdarboux/Bureau/
JabRef-2.11b5.jar!/plugins/net.sf.jabref.core/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/C:/Documents%20and%20Settings/fdarboux/
Bureau/JabRef-2.11b5.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)

Oct 16, 2015 9:04:31 AM org.java.plugin.standard.StandardPluginManager activateP
lugin
INFO: plug-in started - net.sf.jabref.core@2.0.0.4b1 (active/total: 1 of 2)
Oct 16, 2015 9:04:31 AM org.java.plugin.standard.StandardPluginManager activateP
lugin
INFO: plug-in started - net.sf.jabref.export.misq@1.0.0 (active/total: 2 of 2)
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up func
tion 'SetCurrentProcessExplicitAppUserModelID': La procÚdure spÚcifiÚe est intro
uvable.

        at com.sun.jna.Function.<init>(Function.java:208)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:536)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:513)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:499)
        at com.sun.jna.Native.register(Native.java:1509)
        at com.sun.jna.Native.register(Native.java:1396)
        at com.sun.jna.Native.register(Native.java:1156)
        at net.sf.jabref.gui.nativeext.WindowsExtensions.<clinit>(Unknown Source
)
        at net.sf.jabref.JabRef.start(Unknown Source)
        at net.sf.jabref.JabRefMain.main(Unknown Source)

C:\test>java -version
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b20)
Java HotSpot(TM) Client VM (build 23.0-b21, mixed mode, sharing)

**Comment by matthiasgeiger** [comment]
Has been fixed in master but **not** backported to 2.11 (see #194 and #197)

**Comment by matthiasgeiger** [comment]
Correction: has been backported in a9c168cb2a9213c0329a312969e01ef9bf0bc784

**Comment by g10996694** [comment]
I have the same problem, it does not start in Windows XP.
I had also starting problem in Windows 7, this problem has been reported. We all see something wrong,  but not confirmed/identified by others.

**Comment by stefan-kolb** [comment]
Hm, the native function should not be called on Windows XP. I need to investigate if it gets a lookup tho.

**Comment by koppor** [comment]
We removed the beta 5 release. Sorry, I was too quick :scream:

**Comment by stefan-kolb** [comment]
@mlep @g10996694 The latest master release should work correctly now. Try http://ge.tt/5UUPRGQ2

**Comment by mlep** [comment]
@stefan-kolb: With windows xp, I get an error message.
Java 1.8.0 seems required. I am still using 1.6.0...

C:\Documents and Settings\user\Bureau>java -jar JabRef-2.80dev--snapshot--20
15-10-19--b900de9.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/jabref
/JabRefMain : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by stefan-kolb** [comment]
Ah I'm sorry I sent you the link to the latest master builds. 2.11 has no automatic build artifacts.

**Comment by koppor** [comment]
@mlep You can try the latest 2.11 build available at http://ge.tt/9Idc446. I maintain that repo manually.

**Comment by mlep** [comment]
Starting and seems to work properly!
A few messages displayed (see below


C:\Documents and Settings\user\Bureau>java -jar "JabRef-2.11dev - 2015-10-1
 17.20.51 - 0ac5129430ef75d00b14f57fc79f8c3f6428add5.jar"
oct. 19, 2015 11:23:38 PM org.java.plugin.registry.xml.ManifestParser <init>
Infos: got SAX parser factory - com.sun.org.apache.xerces.internal.jaxp.SAXPars
rFactoryImpl@176ed77
oct. 19, 2015 11:23:38 PM org.java.plugin.registry.xml.PluginRegistryImpl configure
Infos: configured, stopOnError=false, isValidating=true
oct. 19, 2015 11:23:38 PM org.java.plugin.registry.xml.PluginRegistryImpl register
Infos: plug-in and fragment descriptors registered - 2
oct. 19, 2015 11:23:38 PM net.sf.jabref.plugin.PluginCore initialize
Infos: 2 greffon(s) trouvÚ(s):
  - net.sf.jabref.core (jar:file:/C:/Documents%20and%20Settings/user/Bureau
JabRef-2.11dev%20-%202015-10-19%2017.20.51%20-%200ac5129430ef75d00b14f57fc79f8c
f6428add5.jar!/plugins/net.sf.jabref.core/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/C:/Documents%20and%20Settings/user
Bureau/JabRef-2.11dev%20-%202015-10-19%2017.20.51%20-%200ac5129430ef75d00b14f57
c79f8c3f6428add5.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)

oct. 19, 2015 11:23:38 PM org.java.plugin.standard.StandardPluginManager activatePlugin
Infos: plug-in started - net.sf.jabref.core@2.0.0.4b1 (active/total: 1 of 2)
oct. 19, 2015 11:23:38 PM org.java.plugin.standard.StandardPluginManager activa
ePlugin
Infos: plug-in started - net.sf.jabref.export.misq@1.0.0 (active/total: 2 of 2)
oct. 19, 2015 11:23:38 PM net.sf.jabref.JabRef openBibFile
Infos: Ouverture en cours: C:\Documents and Settings\user\Bureau\biblio.bib

**Comment by matthiasgeiger** [comment]
Thats just the normal clutter, so it seems to work again normally on WinXP.

**Comment by mlep** [comment]
FYI, out of 78 questionnaires, nobody has checked winxp as their OS... Too bad we did not conducted the pool before... ;-)

**Comment by stefan-kolb** [comment]
It's not too bad :wink: it still has to work on XP and Vista which is now the case.
