### ISSUE TITLE
Timestamp settings might break EntryEditor

### ISSUE THREAD

**Issue by Zhengguo-Xu** [JabRef/jabref#2447]
JabRef version 3.8.1 portable (.jar file) on  Windows 7 Pro and Ubuntu 16.04

To summarise, I can view large database (>1000 references, bib file > 2.5 MB) but cannot edit it with version 3.8.1. The same database can be edited with version 3.8. 

Version 3.8.1 can only edit small database. 

Steps to reproduce:

1. create large database (mine is 2.52 MB bib file containing 1080 references of articles)
2. open the file with JabRef 3.8.1 portable (.jar executable)
3. I can view the references but cannot enter edit mode (hit enter key, click Edit Entry button in toolbar, double click any entry, ... Nothing works). But the same database can be edited with version 3.8 portable. 
4. create small database (mine is bib file with 14 KB containing 32 articles.)
6. version 3.8.1 portable works perfectly. 

If it helps,  I also tried version 3.8.1 (.exe file) installed in Windows 7 Pro. Same problem for large database.

**Comment by Zhengguo-Xu** [comment]
Thanks koppor, but I don't think that's the same issue.  1094 is about the performance for large file which I assume they can still edit it though the response time is long. Mine is that you cannot edit any entry with 3.8.1 but you can edit with 3.8.. The loading time is slow but acceptable. So I assume we are talking about the different bugs (if what 1094 describes can be called bug).

**Comment by tobiasdiez** [comment]
There might be a problem with your preferences. Can you export them using Preferences -> Export and upload the file here so that we can investigate the problem. Probably, a reset (Preferences -> Reset) already solves the issue.

**Comment by Zhengguo-Xu** [comment]
You are absolutely right about preferences, tobiasdiez. I messed quite a lot the repreferences and to be reproducible, I did the following:

1. To have a clean start, I deleted all jabref preference .xml files and I also deleted in Windows registry [HKEY_CURRENT_USER\Software\JavaSoft\Prefs\net\sf\jabref] where previous preferences has been kept.
One question here by the way: why preferences has been stored in Windows registry? Shouldn't the java runnable file be a portable application?

2. Open jabref-3.8.1.jar  --> Options --> Preferences  --> enable memory stick mode and biblatex as default bibliography mode --> export preferences as jabref-v3.8.1_ini01.xml (attached) --> OK to close option. --> open the large bib file that couldn't be edited previously and now I can edit it. I noticed the slightly quick loading time also. --> close jabref and jabref.xml is generated automatically which is very similar to the initial one attached. (I also export the jabref in windows registry as ini.reg to be used to compare the preferences later.)

3. open jabref-3.8.1.jar again and make some modification in options --> preferences and click OK to exit. Now I **cannot** edit the bib file. So the problem lies indeed in the preferences. --> close jabref  --> jabref.xml is automatically updated. I renamed it as jabref_with.error.xml and attached it here as well. 
(preferences in windows registry has been updated as well. I also exported and compared to the initial one)

4. I'll try to eliminate one by one the modified preferences to see where the problem is. 

----
It seems xml file is not supportted. I renamed it to txt to upload them. 

[jabref_v381_ini01.txt](https://github.com/JabRef/jabref/files/687184/jabref_v381_ini01.txt)
[jabref_with.error.txt](https://github.com/JabRef/jabref/files/687185/jabref_with.error.txt)

**Comment by koppor** [comment]
Refs https://github.com/koppor/jabref/issues/166 and #2176 

Thank you for the test. We really need to find out, why `yyyy.mm.dd` is sometimes set as timestamp.

**Comment by mlep** [comment]
`yyyy.mm.dd` is given as an example in in help, while the default timestamp (`yyyy-mm-dd`) is not specified. See http://help.jabref.org/en/TimeStamp

**Comment by matthiasgeiger** [comment]
... might be caused by some changes of me in the context of introducing `LGoodDatePicker`... I'll investigate...

**Comment by matthiasgeiger** [comment]
I found the problem and fixed it. A development build with a fixed version is available here: http://builds.jabref.org/another-datepicker-fix/
