### ISSUE TITLE
customize entry type leads to error when JabRef reopens next time

### ISSUE THREAD

**Issue by Zhengguo-Xu** [JabRef/jabref#2448]
JabRef Runnable JAR version 3.8 and 3.8.1  on  Windows 7 Pro and Ubuntu 16.04

I enabled memory stick mode in option to load the save preferences from/to jabref..xml (which was located in the same folder as JabRef.jar runnable file). bibliography mode is BibLaTeX.

Issue: 

When I  made small modification using customize entry types (article or book) in Optional fields, after closing and reopening Jabref, all fields in "Optional fields 2" tab are disappeared. The original default fields in "optional fields 2" are moved to "optional fields" tab so it appeared very crowded. 

Check the jabref.xml,  I found out that <node name="customizedBiblatexTypes"> has been changed incorrectly (see below).

Steps to reproduce:

1. use jabref.jar, enable biblatex and memory stick mode in option --> close jabref.jar. jabref.xml will be saved in the save folder as your runnable jar file automatically. 
2. create any bib file with a few entries and go to "BibTex" --> "Customize entry types"
3. Choose book entry type and add "keywords" field in "Optional fields" and click Apply and OK.
4. The changes can be viewed and it seems it's correct.
5. close jabref and reopen it
6. all fields in Optional fields 2 tab are gone and many appeared in optional fields.
7. check jabref.xml, changes are in <node name="customizedBiblatexTypes"></node> (see below for an example). There're "req[fileds]" and "opt[fields]" with correspond required and optional fields but there no, say, opt2, for optional fileds 2 tab. This makes optional fields tab too crowded. Before modification, the node is empty.
8. in addition, if I only modify one entrytype, some other entrytypes got modified as well, which is not my intention. e.g., modifying type article will cause type book being modified. 

```
          <node name="customizedBiblatexTypes">
            <map>
              <entry key="Article" value="jabref-entrytype: Article: req[author;title;journal/journaltitle;year/date] opt[subtitle;editor;series;volume;number;eid;issue;pages;note;issn;doi;eprint;eprintclass;eprinttype;url;urldate;translator;annotator;commentator;titleaddon;editora;editorb;editorc;journalsubtitle;issuetitle;issuesubtitle;language;origlanguage;month;version;addendum;pubstate]"/>
              <entry key="Book" value="jabref-entrytype: Book: req[author;title;year/date] opt[editor;subtitle;titleaddon;maintitle;mainsubtitle;maintitleaddon;volume;edition;publisher;isbn;chapter;pages;pagetotal;doi;eprint;eprintclass;eprinttype;url;urldate;keywords;editora;editorb;editorc;translator;annotator;commentator;introduction;foreword;afterword;language;origlanguage;part;volumes;series;number;note;location;addendum;pubstate]"/>
            </map>
          </node>
```

**Comment by matthiasgeiger** [comment]
Thanks for your report! I can confirm the behavior, however, fixing it will require some time and discussions :wink:

@JabRef/developers We must talk about this and decide what to do with "optional fields2" as this is primary a UI thing that should not be reflected in the model...

**Comment by matthiasgeiger** [comment]
We decided that we will drop the support for the distinction of "optional fileds" and "optional2 fields" in the long run. Thus we won't fix this issue.
