### ISSUE TITLE
Strange ordering of files after using "Look up full text documents"

### ISSUE THREAD

**Issue by vsht** [JabRef/jabref#2453]
JabRef 3.8.1
linux 4.8.15-300.fc25.x86_64 amd64 
Java 1.8.0_51

Steps to reproduce:

1. Add any arXiv preprint, e.g. 1604.06709
2. Click on Quality -> Look up full text documents
3. The online link is still listed primary, so when clicking on the sheet icon in the bibliography list, you get redirected to https://arxiv.org/pdf/1604.06709v1.pdf, although a local PDF is present.

In my view this behavior is incorrect. Once the full text document has been fetched, it should become primary, not the online link. Currently I have to change ordering by hand for every new entry, which is a lot of extra work.

![bildschirmfoto von 2017-01-10 15-08-27](https://cloud.githubusercontent.com/assets/7283188/21809322/7dd8e53a-d747-11e6-881e-5eb4dca8b975.png)

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `file-links`. Please try the latest build from http://builds.jabref.org/file-links.

**Comment by vsht** [comment]
Danke, this change really improves my workflow.
