### ISSUE TITLE
"Move linked files" moves files in App directory when set to .bib directory

### ISSUE THREAD

**Issue by rkrug** [JabRef/jabref#2454]
JabRef version 3.8.1 on Mac OS X 10.12.2

Steps to reproduce:

1. Create bibliography with linked pdf in file field - absolute path
2. set all file directories (database properties and JabRef settings) to ```.``` to get attached files in same directory as the bib file
3. save the database
4. Cleanup Entries and enable ```Move linked files to default directory```
5. attached files get copied into "JabRef.app/Contents/java/app

Have I forgotten something or is this a bug?

I can move them into the directory with the database, but this is not that nice.

**Comment by Siedlerchr** [comment]
Thanks for your report. 
Please try again removing the . settings in the database properties settings and only click the checkmark: Set Bib location as primary directory. Just to be sure restart JabRef after this setting.

Then it should work. I think the problem here is that JabRef or in fact the file system interprets the "." relative directory from the binary where JabRef is started from.

**Comment by rkrug** [comment]
OK - done it. But now, the tick box "Move linked files to default directory" in the Cleanup entries" dialog box is greyed out.

**Comment by Siedlerchr** [comment]
Okay, I could reproduce the problem. A workaround would be to use the rename PDF feature, it moves the files, too.

**Comment by rkrug** [comment]
Thanks - that works.

**Comment by Siedlerchr** [comment]
Hi,

I fixed this: When you have Bib location as primary dir in settings, it overwrites the db specific settings, e.g. Cleanup will move the files now to that directory. 
And the checkbox is now active again. 
Could you please test it with this development version?
http://builds.jabref.org/moveFileDir/

**Comment by lenhard** [comment]
We think this is fixed in current master, hence I am closing the issue.

Feel free to reopen if the problem reappears.
