### ISSUE TITLE
"Move linked files" does not move files from user-specific to general file directory

### ISSUE THREAD

**Issue by julianprester** [JabRef/jabref#2456]
JabRef version 3.8.1 on Windows 7

Steps to reproduce:

1. Create bibliography with linked pdf in file field - relative path
2. Pdf must be located in the user-specific file directory
3. General and user-specific file directories must be set in database properties
4. Cleanup Entries and enable `Move linked files to default file directory`
5. Attached files do net get moved from the user-specific to the general file directory

I tested this bug with older JabRef versions and I can confirm Cleanup Entries does correctly move the files in versions 3.7 and lower. It seems the issue got introduced with version 3.8.

**Comment by Siedlerchr** [comment]
Thanks for your report! I recently reworked some of the move files code, could you please test if this bug is still present in this dev version?
http://builds.jabref.org/moveFileDir/

**Comment by julianprester** [comment]
The bug is not present in the dev version anymore. Thank you for your report.
