### ISSUE TITLE
Fix publishing of development builds

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#247]
We decided to use @gett for automatically publishing development builds as ge.tt offers a [REST API](http://ge.tt/developers/rest) and the manual publishing at http://ge.tt/9Idc446 worked perfectly. However, we encounter issues (**timeout, not all files uploaded**), when automatically publishing to ge.tt (at http://ge.tt/5UUPRGQ2). I contacted the support and they replied:

> We have requests limit implemented. Our system is built not for such usage. That is why he can get connection timeout.

Therefore, we intend to switch to another system.

Currently, we see following options:

* use @dropbox
  * It seems to be possible using @Cloudpipes (https://www.cloudpipes.com/integrations/circleci/dropbox), but we are approx waiting position 47.000 for geetting access to the beta
  * The [dropbox python sdk](https://github.com/dropbox/dropbox-sdk-python) isn't available per se and has to be installed manually
* use scp to publish a privatly hosted server
* use [bintray](https://bintray.com/) - see https://github.com/JabRef/jabref/issues/247#issuecomment-149475783
* use Amazon S3

Feel free to add comments. I'll keep this issue updated.

**Comment by ThomasA** [comment]
Could you use Travis CI and its ability to deploy built files back to 
GitHub?

**Comment by simonharrer** [comment]
Dropbox has a REST api https://www.dropbox.com/developers-v1/core/docs#files_put

**Comment by koppor** [comment]
The decision to use Python instead of the REST API results from the experience with the usage of the REST API of ge.tt. See [upload-to-gett.sh](https://github.com/JabRef/jabref/blob/master/scripts/upload-to-gett.sh). It is really a mess to handle REST in bash with [jq](https://stedolan.github.io/jq/) is really a mess. Especially when wanting to delete files having a certain file name.

**Comment by matthiasgeiger** [comment]
Regarding bintray the relevant documentation is here: https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org

**Comment by koppor** [comment]
TravisCI can upload to S3 automatically: http://docs.travis-ci.com/user/deployment/s3/. I don't know, how costly this will be.

@ThomasA As far as I understood the docs at http://docs.travis-ci.com/user/deployment/releases/, it is only possible to publish tagged versions automatically. What we want is to publish all builds.

**Comment by koppor** [comment]
With the command line tool of AWS, it should also be possible to deploy to S3 using CircleCI: http://benlopatin.com/deploying-static-sites-circle-ci/

**Comment by oscargus** [comment]
How much space is required? I have a (yet to start up) start up with a 15 GB web hotel solution. Even when it is up and running, I won't need all of that. Of course, it isn't that much space, but if we only keep, say, the 100 latest builds or so (based on the 88.5 MB that all 2.11 beta 4 versions at SF sum up to) it could be one solution. In this case, I believe scp to be the feasible option.

On the other hand, registering jabref.org and paying for a dedicated web hotel may be a just as good idea (apart from the paying issue).

**Comment by koppor** [comment]
@oscargus This is option 2 from above. Thank you for your offer. Let's discuss privately! :smiley:

**Comment by stefan-kolb** [comment]
@koppor You implemented this in 7f45681e08d773cc0cf2be05d41a54112cf038d5?!

**Comment by koppor** [comment]
Yes, I did. Doing it on my private server and learned much about [OpenSSH SFTP](http://www.debian-administration.org/article/590/OpenSSH_SFTP_chroot_with_ChrootDirectory).

Let's see, how it works out. Especially, traffic and load on the server.

URL of the snapshots: http://builds.jabref.org/
