### ISSUE TITLE
SAO/NASA ADS Bibcode Web Search

### ISSUE THREAD

**Issue by insnana** [JabRef/jabref#2471]
JabRef version 3.8.1 on Windows 7

After version 3.6; ADS Bibcode fetcher returns abstract text as left-aligned. However, v3.6 was returning abstract text as justified. It was more readable previous version 3.6 than now it has.

**Comment by Siedlerchr** [comment]
We could also take this as a chance to implement the new API 
Refs https://github.com/adsabs/adsabs-dev-api/issues/30
