### ISSUE TITLE
jboss server

### ISSUE THREAD

**Issue by jp5400** [JabRef/jabref#2479]
Hallo,
I could not find if there is any working version of JabRef for any version of jboss. Does anyone have any experience in JabRef server?
jp

**Comment by koppor** [comment]
You can convert JabRef to a web application, if you

1. Rewrite the user interface using HTML5
2. Convert the backend code to TypeScript. For instance using http://www.jsweet.org/.

Pull requests welcome.


Did you mean that?

**Comment by jp5400** [comment]
Thank you
Sorry: "in english please". This mean I need more time for comprehention.
jp

**Comment by koppor** [comment]
Just describe the aim you want to achieve.

Currently, JabRef is written in Java using SWING as user interface. Thus, it cannot be run on any JBoss or Tomcat server.

**Comment by jp5400** [comment]
Thank you for suggestion
jp
