### ISSUE TITLE
Jabref 3.8.1 can't connect to open office 4.1.3

### ISSUE THREAD

**Issue by eduardkareletc** [JabRef/jabref#2484]
JabRef version 3.8.1 on Mac OS X 10.9.5

connecting to OpenOffice 4.1.3 fails with a message that the file /Applications/OpenOffice.app/Contents/Resources/java/unoil.jar cannot be found.

In the OpenOffice application folder the Resources/java folder is missing. The jar file is located in /Applications/OpenOffice.app/Contents/MacOS/classes/

A workaround seems to be in 'repairing' the OpenOffice application on the disk by using Terminal as follows:
_$ cd /Applications/OpenOffice.app/Contents/Resources
$ ln -sf ../MacOS/classes/ java_

After this workaround JabRef connected to the running instance of OO, correctly reporting the file that was open.

As a caveat, I have not tried using this beyond establishing connection.

A better solution would be for JabRef to look for jar files in both the Macos/classes and Resources/java folders.

**Comment by stefan-kolb** [comment]
@chochreiner Maybe you can have a look when you have some time (it is not that urgent).
All the preferences should be stored inside `OpenOfficePreferences.java`. 
```
    public static final String DEFAULT_OSX_PATH = "/Applications/OpenOffice.org.app";
    public static final String OSX_EXECUTABLE_SUBPATH = "/Contents/MacOS/";
    public static final String OSX_EXECUTABLE = "soffice.bin";
    public static final String OSX_JARS_SUBPATH = "/Contents/Resources/java";
```
Maybe, the `OSX_JARS_SUBPATH ` is obsolete for OO 4.x.

**Comment by stefan-kolb** [comment]
@eduardkareletc I'm trying to refactor the OO logic. Maybe you can try a build from https://builds.jabref.org/openoffice and give me feedback.

**Comment by eduardkareletc** [comment]
Hello Stefan,

These are rather chaotic times for me right now, but I may be able to 
look at it this Friday.

What is it you want feedback on?
As I recall, I found a work around by creating a symbolic link in the OO 
bundle which made the jar files accessible at two  different loactions.
  I am not sure I understand how the issue relates to refactoring, and 
what you expect me to do.

Cheers
Eduard



Stefan Kolb wrote:

**Comment by stefan-kolb** [comment]
@eduardkareletc I just want to know if it fixes your problem and if it's still working in general for you.

**Comment by eduardkareletc** [comment]
I'll have a look later this week.

Stefan Kolb wrote:
