### ISSUE TITLE
Correct capitalisation of 'biblatex'

### ISSUE THREAD

**Issue by josephwright** [JabRef/jabref#2493]
The name of  LaTeX `biblatex` package has always been written all-lowercase except at the start of sentences, _i.e._ it follows normal capitalisation rules in English. Currently, JabRef calls it 'BibLaTeX' both on the website and in the program: please can this be corrected.

**Comment by koppor** [comment]
Refs https://github.com/koppor/jabref/issues/73 - I update it accordingly.

**Comment by lenhard** [comment]
@josephwright Could you also correct the spelling on CTAN: https://www.ctan.org/pkg/biblatex?lang=de ?

It is this page that led us to think that 'BibLaTeX' was correct.

**Comment by koppor** [comment]
![grabbed_20170127-135020](https://cloud.githubusercontent.com/assets/1366654/22371491/a7c7a054-e497-11e6-80b7-9f3903e4f1a8.png)

Please note there are no news since 5 years on CTAN on biblatex.

**Comment by josephwright** [comment]
@lenhard  I'll talk to CTAN about their text: the official documentation has always had all-lowercase.

**Comment by josephwright** [comment]
@koppor I know there have been lots of releases! I guess something odd it the way they've added this stuff (it did not used to be there).

**Comment by koppor** [comment]
Minor comment for CTAN: Even worse, there is biblateX --> https://www.ctan.org/ctan-ann/id/mailman.307.1473360229.1426.ctan-ann@ctan.org
