### ISSUE TITLE
"New entry from plain text..." shows the same dialog as "New entry..."

### ISSUE THREAD

**Issue by duelle** [JabRef/jabref#2494]
**JabRef version** 
JabRef 3.8.1
linux 4.9.6-1-arch amd64 
Java 1.8.0_121

**Steps to reproduce**
1. Open: BibTeX -> "New entry from plain text..."
2. Same dialog as "New entry..." appears.

I was looking for a way to directly insert a bibtex entry from the clipboard into JabRef and found the "New entry from plain text..." option but it seems to behave similar to the "New entry..." option.
In both cases the dialog for selecting the type of bibtex key appears.

Is this behavior intended or may this be some kind of bug?

**Comment by tobiasdiez** [comment]
But this behavior is indeed a bit confusing...
Proposal for improvement:
- Always create articles by default in both dialogs (or make the default customizable?)
- Provide facility to easily change entry type in entry editor (i.e. drop-down box)

-> Less clicks necessary to create a new entry and this overwhelming dialog with (gefühlt) 100 different entry types is no longer needed.

**Comment by koppor** [comment]
Entry type can already be changed. Click in the type...

Am 27.01.2017 18:20 schrieb "Tobias Diez" <notifications@github.com>:

**Comment by duelle** [comment]
Ok, I didn't expect that to be a different dialog..
I would have expected just an empty text field to paste the bibtex key into without that immediate step.
That's why I thought it would be the same dialog.

Is the selection of the type necessary? 
Before I found that option I always just created a random type in the "New entry..." dialog and pasted the text from the clipboard in the BibTeX source tab. And it did not matter whether the type I previously chose was the correct one or not.

**Comment by Siedlerchr** [comment]
@duelle  The easiest option to paste a bibtex entry from the clipboard is just by doing STRG+V in the maintable. Then the entry is directly created. I do this all the time. Very handy feature

**Comment by duelle** [comment]
@Siedlerchr Interesting, thank you for the hint! Didn't know of that feature.

**Comment by stefan-kolb** [comment]
Probably the `Entry from plain text dialog` should be able to recognize if it really is plain text or a ready to use BibTeX entry and insert it if possible?!

**Comment by lenhard** [comment]
As far as I understand, the problem has been solved by clarifying the intended functionality. Hence, I am closing

**Comment by koppor** [comment]
Regarding the dialog, we added two new issues https://github.com/koppor/jabref/issues/225 and https://github.com/koppor/jabref/issues/226 to improve the UI.

**Comment by koppor** [comment]
Yes, the selection of the type is necessary as the plain text import cannot know which type it is and we wanted to have the entry be correct.

Maybe, we should use "misc" as type and let the user change it afterwards?
