### ISSUE TITLE
Inspire Fetch

### ISSUE THREAD

**Issue by bulmust** [JabRef/jabref#2497]
JabRef version 2.10b2 on Linux Mint 17.3

Hi,

INSPIRE fetch does not work properly. For example, It does not work for searching a bibtex name of articles like "Rowson:1985xh".

I think you should change " jabref/src/main/java/net/sf/jabref/gui/importer/fetcher/INSPIREFetcher.java " file a little bit.

At the line 64, It should be

 .append("/search?ln=en&ln=en&p=").append(identifier)

I think, this solve the problem. (Comparing the old version SPIRE, INSPIRE does not need a "find" command.)

**Comment by koppor** [comment]
I just see, that there is no test coverage for the INSPIRE. The current help page is http://help.jabref.org/en/INSPIRE

Would you mind pushing the edit button at https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/gui/importer/fetcher/INSPIREFetcher.java and propose the file change? That would be easier for us to follow up.

Example queries would also be helpful. We now have `Rowson:1985xh`, but some more would be helpful.

**Comment by bulmust** [comment]
I propose the file change. But I want to say that I have no experience with the java codes. 

For example, following searches give results: (BibTeX keys: Rowson:1985xh, Penati:2009sw, Maldacena:1997re, Weinberg:1967tq)

1. http://inspirehep.net/search?ln=en&ln=en&p=Rowson:1985xh
2. http://inspirehep.net/search?ln=en&ln=en&p=Penati:2009sw
3. http://inspirehep.net/search?ln=en&ln=en&p=Maldacena:1997re
4. http://inspirehep.net/search?ln=en&ln=en&p=Weinberg:1967tq

**Comment by Siedlerchr** [comment]
I just tested all your examples. They all work fine in the current version of JabRef, 3.8.2 and the 4.0.0 development version.
Nonetheless, we are missing a test for the fetcher. I will add one

**Comment by bulmust** [comment]
I use JabRef version 2.10b2 on Linux Mint 17.3. I will explain with picture.

**1)** Search bibtex key: Rowson:1985xh

![s1](https://cloud.githubusercontent.com/assets/19466488/22686122/f93c0a52-ed33-11e6-964c-6e7e1ef1ab2d.png)

**2)** It gives nothing

![s2](https://cloud.githubusercontent.com/assets/19466488/22686175/1f196328-ed34-11e6-997e-0f1cf965cbc6.png)

**Problem**: The fetcher can not find the bibtex keys.

By the way, I recognize that both of the searching method (with "find+" and without "find+" gives result:

- http://inspirehep.net/search?ln=en&ln=en&p=Rowson:1985xh
- http://inspirehep.net/search?ln=en&ln=en&p=find+Rowson:1985xh

)

**Comment by Siedlerchr** [comment]
@bulmust  JabRef Version 2.10 is outdated and no longer supported. Please install the current actual version 3.8.2
