### ISSUE TITLE
Cleanup window: no possibility to resize

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2501]
JabRef >= 3.7 (including  JabRef-4.0.0-dev--snapshot--2017-01-29--masr--7191a7055.jar)
on Linux LMDE Betsy

The cleanup window cannot be resized, which makes impossible to add a custom field formatter.
See picture.

![cleanup-noresize](https://cloud.githubusercontent.com/assets/6931104/22422727/3db90848-e6ee-11e6-8166-eb91cfdeab79.png)

**Comment by Siedlerchr** [comment]
I tried to fix the layout stuff in #2415. I could not really test it, so I would ask you to test that version http://builds.jabref.org/moveFileDir/ as soon as the tests run through

**Comment by mlep** [comment]
No resize for cleanup window using ````JabRef-4.0.0-dev--snapshot--2017-02-03--moveFileDir--07a1c4477.jar````.

**Comment by matthiasgeiger** [comment]
This has been fixed with #2614 - and is now included in the dev builds.
