### ISSUE TITLE
Export changes "institution" to "school"

### ISSUE THREAD

**Issue by ebiverson** [JabRef/jabref#2505]
JabRef 3.8.1; linux 4.9.5-100.fc24.x86_64 amd64 ; Java 1.8.0_121; Fedora 24

"Export selected entries" as "HTML table" or "HTML Table with Abstract and BibTex" on items of type techreport replaces keyword "institution" with "school".  All other fields remain unchanged (number, year, title, author, etc.).  Many such institutions are NOT schools, and the tech report entry style is, in my understanding, required to have an institution field. 

Steps to reproduce: 
1: Highlight TechReport-style entry
2: "Export selected entries" to any of the HTML styles, e.g., HTML Table with Abstract and BibTex."
3: Open resulting HTML file - all "institution" fields have been changed to "school" fields, and appear listed as such in some bibliographic styles.

Expected behavior: Export of existing records should not change entry types.

**Comment by Siedlerchr** [comment]
Hello, 
thanks for your report! Do you use biblatex or bibtex format and could you provide a sample entry which definitely is wrong? That would help us reproducing the problem

**Comment by ebiverson** [comment]
Sure.  I have verified the same behavior whether using the BibLaTeX mode or the BibTex mode.  I've got bib files saved in each mode, and HTML files created using the "Export as HTML with Abstract and BibTex" export setting. I've added all four in the attached zip file. 
[demo.zip](https://github.com/JabRef/jabref/files/743619/demo.zip)

In each case, the brackets enforcing case were stripped out, and the "institution" keyword was changed to "school" (others seem to be the same, except for things like category, timestamp, etc. that are supposed to be stripped out in the export process).

**Comment by Siedlerchr** [comment]
Okay, I found out this is just the field and the name defined in the style layout file. Can be simply edited. 

The simplest change would be for you to copy the .layout files to a custom folder, change school to institution (field an tag)  and then define a custom Export style with these. 

The layout files are inside the jar (open with an archiver) unde`r \resource\layout\tableref ` (you need all three)
Then copy them into a new folder somewhere.

Options -> Manage custom exports -> Add new -> Enter a name for your custom exporter ->  Select the .layout and as extension html
If you then go to Export -> You can choose your Custom exporter -> et voila instution.

BTW: School is an alias for institution from the [biblatex manual](http://ftp.fau.de/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf) 
```
school list (literal)
An alias for institution, provided for BibTeX compatibility. Te institution
feld is used by traditional BibTeX for technical reports whereas the school feld
holds the institution associated with theses. Te biblatex package employs the
generic feld name institution in both cases. See §§ 2.2.2 and 2.3.4.
```

**Comment by lenhard** [comment]
Since @Siedlerchr outlined the solution to this problem and there was no more reaction since then, I guess this issue can be closed.
