### ISSUE TITLE
Localization files: anomalous string

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2513]
The files ````master/src/main/resources/l10n/JabRef_*.properties```` (````JabRef_en.properties```` excepted) end with the following line:

````Unhandled_exception_occurred.````

The  ````=```` sign is missing.

**Comment by Siedlerchr** [comment]
Hm, that is mysterious, because I remember fixing that yesterday or so. And in my local repo it is correct.
I will check that. 
And btw thanks for your translation again!

**Comment by Siedlerchr** [comment]
Fixed in master.
