### ISSUE TITLE
'APOSTROPHE' (U+0027) not well displayed in the main table

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#2516]
JabRef version 3.8.1 on Debian 8 Jessie AMD64

Steps to reproduce:
1. Insert this code in the bib file:
```
@Incollection{Mengaldo2007,
  author       = {Mengaldo, Pier Vincenzo},
  booktitle    = {L'età contemporanea},
  title        = {«L'opera in versi» di Eugenio Montale},
  date         = {2007},
  volume       = {15},
  keywords     = {italian},
  booksubtitle = {Le opere (1921-1938)},
}
```

2. Give a look to the title field in the main table
3. You should see this:
![mengaldo](https://cloud.githubusercontent.com/assets/1306260/22600791/65cbb0dc-ea3c-11e6-977e-a3627562ce9a.png)

Many thanks,
Domenico

**Comment by AEgit** [comment]
Might be a duplicate of this:

https://github.com/JabRef/jabref/issues/2498

But to be honest I can't replicate this behaviour on JabRef 3.8.2. Have you changed your entry preview preferences for the field "title" from `HTMLChars `to `LatexToUnicode `or viceversa (see also here: http://discourse.jabref.org/t/change-of-default-of-entry-preview/446)?

**Comment by Doc73** [comment]
I modified my preferences accordingly, but the issue still persists. :-(

However, my issue is not in the preview, but in the main table, as in above screenshot.

**Comment by Doc73** [comment]
Another screenshot:

![mengaldo](https://cloud.githubusercontent.com/assets/1306260/22606674/f632b590-ea54-11e6-992e-53f7a6b74226.png)

**Comment by AEgit** [comment]
Ooohhh, sorry - my bad. Indeed, in the main table I get the same behaviour. Yes, this has nothing to do with the preview settings. I guess this might be solved, once the latex2unicode lib is implemented (see here: https://github.com/JabRef/jabref/issues/2465).
@lenhard: Any thoughts on this?

**Comment by Doc73** [comment]
Ah! It seems that the bug was already fixed. Please, see: #2500 and #2507.

If so, you could close this bug report.

**Comment by AEgit** [comment]
You could test the current master build to see whether the bug has actually been fixed for you:
https://builds.jabref.org/master/
(you might want to make a backup of your bibtex-database first, before trying the new build)

If the the new build does not contain the bug you can either keep the current master or go back to the old (bugged) version and wait for the release version.

You can then close the bug report (I'm afraid I cannot do that, as I'm not part of the JabRef development team).

**Comment by Doc73** [comment]
Sorry, but I'm not able to launch the jar, probably due to migratio to JavaFX. Here is the terminal output:
```
$ java -jar JabRef-3.8.2-dev--snapshot--2017-01-26--javafx--6adfd4c61.jar

Error: Invalid or corrupt jarfile JabRef-3.8.2-dev--snapshot--2017-01-26--javafx--6adfd4c61.jar
```

**Comment by Doc73** [comment]
Yes, it works!
I close this issue.

**Comment by AEgit** [comment]
Good to hear!
