### ISSUE TITLE
Apostrophe is interpreted as an accent

### ISSUE THREAD

**Issue by wgrundlingh** [JabRef/jabref#2518]
JabRef version 3.8.2 on Windows.

![image](https://cloud.githubusercontent.com/assets/1776164/22624388/a83a2ff4-eb2f-11e6-8967-4cbe65da68a2.png)

`Chv\'atal's` should be interpreted as `Chvátal's`, not `Chvátalś`. It shows correctly in the "entry preview", but not in the database.

Here is an example bibliography entry:

```
@Article{fisk,
  Title                    = {A short proof of Chv\'atal's watchman theorem},
  Author                   = {S Fisk},
  Journal                  = {Journal of Combinatorial Theory, Series B},
  Year                     = {1978},
  Pages                    = {374},
  Volume                   = {24}
}
```

**Comment by Siedlerchr** [comment]
Hello, this bug should be fixed in the latest development version.  Please try again with the version from here: http://builds.jabref.org/master/
Refs #2500 #2507

**Comment by lenhard** [comment]
Since this is the third report coming in for the exact same problem, I think we should leave it open and mark as fixed-in-dev-builds so that people see that this has been fixed.

**Comment by wgrundlingh** [comment]
Indeed, the dev version fixes this as far as I can see. Thanks!

**Comment by pirlite2** [comment]
Could you confirm that this fix also applies to the author field? The apostrophe in names such as O'Neill display incorrectly as an acute accent over the 'N' in much the same way as above.

**Comment by lenhard** [comment]
@pirlite2 Yes, this also applies to the author field. I just tried it out in the dev version I have installed locally and O'Neill displays as it should and not as an acute accent.

You can get a dev version here http://builds.jabref.org/master/ Note that it changes a lot of things related to groups, so if you use groups, make a backup of your bib file.
