### ISSUE TITLE
Replace SnapCI

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2523]
SnapCI will be shut down. PR tracking will stop in May 2017. See https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/.

SnapCI recommends GoCD, but this is self-hosted: https://www.gocd.io/download/

In parallel, we could try out CircleCI 2.0 - see: https://discuss.circleci.com/t/getting-started-configuration/8088/1 -- **Attention** This requires a complete new configuration

See https://github.com/JabRef/jabref/wiki/CI for our current CI setup.

**Comment by stefan-kolb** [comment]
What is currently running on SnapCI? Why not just remove it and stay with Travis and Circle?

**Comment by stefan-kolb** [comment]
Ok I found the information isnide the Wiki. I'm still not too happy with the overhead. Lets discuss this @ JabCon

**Comment by stefan-kolb** [comment]
Changed and parallelized Travis CI instead.
