### ISSUE TITLE
cleanup rename according to format moves the files since 3.8

### ISSUE THREAD

**Issue by napseis** [JabRef/jabref#2526]
hi,
Since JabRef 3.8, I have a problem renaming files: they are move from their directories.

My folder structure is like this:
-> Base directory
   - mydatabase.bib
   ->papers
      -> A (folder)
         - list of pdf files...
      -> B(folder)
         - list of pdf files...
      etc....
    -> books(folder)

Description and steps:
1- Select entries, and then click on Cleanup.
2- Tick "rename pdf according to filename format pattern" (relative or not makes no difference)

3- I expect, as with previous version, that the file will be renamed but will stay in its directory
But now, it it renamed and moved to the same location as my bib file.

Is this normal?

Thanks

**Comment by koppor** [comment]
No. I also saw this, but I did not recall if it was always like this. Thank you for pointing out the version since this appears.

**Comment by napseis** [comment]
hi. Until 3.7 it was ok.
Versions 3.8.1 and 3.8.2 both has this bug

**Comment by Siedlerchr** [comment]
Yeah that is really weird. I will look if I can add a setting for not moving the files in my PR #2415

**Comment by Siedlerchr** [comment]
@napseis  I now splitted the logic of the Cleanup actions a bit: Rename Files now only renames files  and move files cleanup now only moves the file.
If you want to rename + move to default file dir then just check both cleanup action 
You can test the version here: http://builds.jabref.org/moveFileDir/

There is only still a problem with the `file directory pattern`, which I need to find a solution for (it would create a new subdirectory each time)

**Comment by lenhard** [comment]
We think this is fixed in current master, hence I am closing the issue.

Feel free to reopen if the problem reappears.

**Comment by napseis** [comment]
hello,
Is it included in 3.8.2 available for download ?
thanks

**Comment by Siedlerchr** [comment]
Hi, no, I think it is included in the 4.0.0 version. I recommend trying the latest 4.0.0 snapshot
Please be aware that the new version is still beta. 
http://builds.jabref.org/master/
