### ISSUE TITLE
Main window: author: compound names cut off even using {}

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2534]
Using JabRef-4.0.0-dev--snapshot--2017-02-10--master--2b886cb71.jar,
if the author is set as
````  author   = {Franck {Taboado Varia}},````
it is displayed in the main window as 
````Varia````

I.e., the output is the same as for 
````author={Franck Taboado Varia},````
It means the additional {} (used to group the compound last name) are not taken into account.

**Comment by Siedlerchr** [comment]
Can confirm this, however, it is only in the MainTable, the preview dialog shows it correctly.
Probably refs #2532

**Comment by Siedlerchr** [comment]
I just tested this with 3.8.2 and there the bug is, too.
In the entry preview I get: `Taboado Varia, F.`

**Comment by lenhard** [comment]
This is not related to #2532, but to the unicode conversion in the main table as whole. A fix is provided in  #2536 and a working version should be available at http://builds.jabref.org/maintable-authors/

@mlep Can you please try this out and check if it solves the issue for you?

**Comment by mlep** [comment]
It looks it is fixed. Thanks!
