### ISSUE TITLE
Add JabRef Icon to FileChooser Dialog

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2535]
Currently it shows the java icon. 

![jabrefopen](https://cloud.githubusercontent.com/assets/320228/22823374/95be21de-ef83-11e6-893e-93459f6e7fb0.png)
Fix idea in:
http://stackoverflow.com/questions/35271071/set-application-icon-for-filechooser-in-javafx

**Comment by stefan-kolb** [comment]
Is this only for the FX Dialogs or also the old FileDialog?

**Comment by matthiasgeiger** [comment]
Have not checken the code but setting JabRefFrame as parent should be enough to solve this.

**Comment by Siedlerchr** [comment]
Seems like this is currently not possible as javafx filechooser requires a Stage to pass. Although JabRefFrame is passed, it is a) not used and b) can not be used because it is no javafx stage/window. So this would only work until we have a scence/stage in JabRefFrame.

**Comment by Siedlerchr** [comment]
No longer shown with a separate icon in the current master.
