### ISSUE TITLE
Call for function: export the pdfs of all the selected entrys to a new folder

### ISSUE THREAD

**Issue by Vaver** [JabRef/jabref#2539]
some times, i want share some of the literature pdfs to friends, it is very easy to select the wanted entrys from the Jabref, but hard to pick out the seleted pdfs.

I hope there is a function to export the pdfs of the selected entrys to a new folder.

thanks

**Comment by AEgit** [comment]
I agree, that would a very nice feature to have. I guess, it is also already somewhat implemented in JabRef, as JabRef is already able to move files from one folder to another. Just copying (instead of moving) the files from one folder to another, user-specified folder would probably already do the trick, I guess.

**Comment by Siedlerchr** [comment]
@Vaver  @AEgit  I have implemented the export functionality that works for all linked files:

http://builds.jabref.org/exportPDF/
You can use it like any other export function. Select the entries then choose  Export -> Files Exporter 
However there is currently one thing I can not change: You have to enter an arbitrary string in the save dialog as "filename".  The entered name is ignored, it is just needed to get the directory.

**Comment by AEgit** [comment]
@Siedlerchr : Thank you very much! I can confirm that this feature works in the posted build!

And immediately a warning or potential improvement against (my) typical noob behaviour. I went for "Export" instead of "Export selected". This lead to JabRef copying over all linked files (in my case ~100 GB) - even when you stop JabRef, it will continue copying over those files. Only by killing the relevant process I was able to stop the copy process.
To prevent this, it might be helpful to add a warning or something along the lines (or let the noobs be noobs ;)).

Thanks again!

**Comment by Siedlerchr** [comment]
Thanks for reporting. I will try to see if I can add a break to stop the process.

**Comment by Siedlerchr** [comment]
@Vaver  @AEgit  I recently finished an improved functionality of this feature. Could you please test and give feedback on it?
http://builds.jabref.org/exportPdf/

**Comment by AEgit** [comment]
JabRef 4.1-dev--snapshot--2017-10-26--exportPdf--88faa7ce3
Windows 10 10.0 amd64 
Java 1.8.0_151

@Siedlerchr This looks really good! Thank you very much!

I think the only thing that could be improved is the visual feedback during the copying process. Currently, if files of many entries are copied over to another folder, JabRef does not show, how long it will take to copy all the files. As far as I can tell, it is therefore currently also not possible to stop the copying process at a certain point in time, unless the relevant process is killed (copying over the files will continue even when JabRef is stopped - see https://github.com/JabRef/jabref/issues/2539#issuecomment-291973170).

But overall this is a massive improvement - I especially like the final table showing the results of the copying process including the full path. I also appreciated that files are not overwritten, when found in the same folder - you could add the possibility to ask the user whether she/he wants to overwrite preexisting files, but I don't think this is a big issue at all. After all, this can be sorted out before starting the copying process by the user with the folder manager of choice.

**Comment by Siedlerchr** [comment]
Thank you very much for your feedback, regarding Cancel, have you tried clicking cancel on the progress dialog? It should cancel the whole copying process. Regarding the duration, I will see if there is a way to calculate time

**Comment by AEgit** [comment]
Hmmm I didn't see any progress dialog, to be honest - if there's one, that would probably solve all my issues.

**Comment by Siedlerchr** [comment]
@AEgit I noticed that the progess dialog was not shown during progress due to the execution order, Changed that now. You can try it out in a couple of minutes, if the tests succed https://github.com/JabRef/jabref/pull/3147

**Comment by AEgit** [comment]
Ok, I'll do that once the updated build is available.

**Comment by AEgit** [comment]
Is this fix already part of the master?
Because with this version the PDF copying does not work anymore: only some, but not all of the selected items are copied and no final results table is shown.

JabRef 4.1-dev--snapshot--2017-11-01--master--d5f0b695f
Windows 10 10.0 amd64 
Java 1.8.0_151

**Comment by Siedlerchr** [comment]
Ah shit I now got it, too. I will fix it asap

**Comment by Siedlerchr** [comment]
Okay, I found the issue. Now both Progessdialog + result table are shown:  ac723bf
Regarding the copying: I did not change any of that. It iterates over all selected entires and gets the files for each entry

**Comment by AEgit** [comment]
JabRef 4.1-dev--snapshot--2017-11-01--master--ac723bf6d
Windows 10 10.0 amd64 
Java 1.8.0_151

Ok, progress dialog and result table work now.
Regarding the copying: I'll see whether I can reproduce this behaviour (so far it has happened 2 times, but afterwards things worked flawlessly).

The "Cancel" button on the progress button seems to have no effect - JabRef continues copying over files (only the progress bar is no longer shown).
