### ISSUE TITLE
Menu Open folder does not work

### ISSUE THREAD

**Issue by Vaver** [JabRef/jabref#2540]
JabRef version 3.8.2 on  Windows 10 

Steps to reproduce:

1. select a entry and right click, call "open folder" menu
2. it only open the explorer of the windows, not the folder of the pdf of the entry
![image](https://cloud.githubusercontent.com/assets/12092857/22920391/d2987c9a-f2cf-11e6-9826-532d306d065a.png)

3. the main fire directory setting in the options/preference
![image](https://cloud.githubusercontent.com/assets/12092857/22920297/5ae84888-f2cf-11e6-9b47-c39a360e8fc4.png)

**Comment by Siedlerchr** [comment]
Hi, could you please test if the problem still exists in the latest development version? You can get it here:
http://builds.jabref.org/master/

There have been some fixes regarding file choosing/opening

**Comment by stefan-kolb** [comment]
@Vaver This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
