### ISSUE TITLE
Replace commons collections by Google guava

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#2546]
We currently use both, Apache commons collections and Google guava. Google guava is seen as the replacement of commons collections. 

At the moment, only a single class, namely, LRUMap is used from the commons collections package. This should be replaced with the corresponding Google guava Cache.

This is a good start for someone who wants to start helping JabRef! :)

**Comment by lynyus** [comment]
this can be closed now, fixed in #2554
