### ISSUE TITLE
Make it easier to remove obsolete localizations

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2562]
Currently the localization consistency test gives me a list of obsolete keys, e.g.

> java.lang.AssertionError: Obsolete keys found in language properties file: [Automatically_create_groups_for_library., Automatically_created_groups, Characters_to_ignore, Created_groups., Generate_groups_for_editor_last_names]

Then one has to go through the English language file and remove these by hand, and finally sync the changes to the other languages. Suggestion for improvement:
- The test returns a statement ala
> gradlew localizationRemove [Automatically_create_groups_for_library., Automatically_created_groups, Characters_to_ignore, Created_groups., Generate_groups_for_editor_last_names]
- Then one just needs to copy and invoke the command (and the script takes care of the rest)....tada!

**Comment by stefan-kolb** [comment]
Not sure if this is a good idea to make it even easier. Currently there is a risk of false positives (I had this one earlier some month ago) So the String should be manually checked before removal. See #1985
