### ISSUE TITLE
ArXiV fetcher returns wrong entries when DOI is not in catalog

### ISSUE THREAD

**Issue by ph2545** [JabRef/jabref#2570]
Every time I am using the quality -> lookup full text documents I get a pdf which is completely irrelevant
Any suggestions ?

I am using jabref 3.8.2 , java-runtime 8, antergos os , gnome 3.22.2

**Comment by stefan-kolb** [comment]
Can you give us a concrete example please? Everytime makes no sense. This should only happen in rare occasions.

**Comment by ph2545** [comment]
Of course, here are a couple of examples:

1) Wess and Zumino, Superspace formulation of Supergravity, Phys.Lett. 1977 ----> 
     
  T. Altherr, E. Petitgirard, T. del Rı́o Gaztelurrutia, Photon Propagation in Dense Media,
  arXiv:hep-ph/9212264

2) Stelle, K.S. and West, Peter C., Minimal Auxiliary Fields for Supergravity, Phys.Lett. 1978  ------>

Gregory W. Anderson and Tomáš Blažek, E 6 unification model building II.Clebsch-Gordan coefficients of 78⊗78, arXiv:hep-ph/0006017

For full details look at the picture attached. For every single one of these entries the "Look for full text documents" downloaded a pdf file which is completely unrelated.
![screenshot from 2017-02-20 09-40-52](https://cloud.githubusercontent.com/assets/13489663/23117614/dcecfa1a-f750-11e6-8408-ea04834dd78f.png)

Also, I have a couple observations that may be useful to CSI the problem.
I) The same wrong pdf was downloaded for many different entries,
II) All of them are downloaded from arXiv,
III) The wanted-to-download-pdfs are available at Sciencedirect and I have access to them

**Comment by stefan-kolb** [comment]
Thanks for reporting this. It is a problem of the Arxiv API. It just returns an entry for a correct DOI that is incorrect. Apparently the `doi:*` query string does not work as expected. Will look into that!

**Comment by stefan-kolb** [comment]
http://export.arxiv.org/api/query?search_query=all:10.1016/0370-2693(77)90015-6
https://arxiv.org/help/api/user-manual#search_query_and_id_list

**Comment by stefan-kolb** [comment]
@JabRef/developers We need to ask if they can fix this behavior in the arXiV API or we need to remove the fetching by DOI from the ArXiV fetcher!

**Comment by Siedlerchr** [comment]
This seems like a bug from Arxiv and has already been reported:
  https://groups.google.com/forum/#!msg/arxiv-api/ew7nadnvAxw/uOwSok-ACQAJ;context-place=forum/arxiv-api
