### ISSUE TITLE
Cannot change file folder of download fulltext file

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2572]
![image](https://cloud.githubusercontent.com/assets/2141507/23121265/0c23f7e8-f760-11e6-855c-2e51361e7bf5.png)

Not possible to select different folder.

**Comment by Siedlerchr** [comment]
Do you get an error when clicking opening like "no valid folder"?
Maybe similar to #2527

**Comment by stefan-kolb** [comment]
No, I just cannot select a folder but only a file.

**Comment by stefan-kolb** [comment]
Actually, also the add file link and edit file link behave nearly the same and have wrong titles but should be dependent on the use case:
- add: select a file (not title=save file)
- fulltext download (change directory only and append file name)
- edit entry: select a file (not save file)
