### ISSUE TITLE
Integrate github plugins for automatic bug report

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2573]
Issues made with JabRef directly result in very short issues (see #2571). Is it possible to show the issue template (https://github.com/JabRef/jabref/blob/master/.github/ISSUE_TEMPLATE.md) in the JabRef UI to force the user to fill that out?

**Comment by lenhard** [comment]
Told you it is a bad idea to make bug reporting so very easy :-P

I expect that we will get spammed by useless reports now...

**Comment by clccc** [comment]
But it is a true errors . Maybe the automatic bug report is too simple.
