### ISSUE TITLE
Editing keywords clears priority, ranking, quality and relevance

### ISSUE THREAD

**Issue by frdrk-jhnssn** [JabRef/jabref#2580]
JabRef version 3.8.2 on Windows 10

Editing keywords clears the fields priority, ranking, quality and relevance

Steps to reproduce:

__Write values of special fields as separate fields to BiBTeX__ enabled!
1. Add a value to any of the fields: priority, ranking, quality and relevance
2. Edit the keyword field
3. Save or change focus from the keywords field in the entry editor

The fields priority, ranking, quality and relevance are now removed.

No events reported in the log

**Comment by lenhard** [comment]
Please have a look at your preferences: Options->Preferences->Entry table columns.

Do you have "synchronize with keywords" enabled by any chance? In this case, the fields you describe above are synchronized with your keywords. Thus, if you enter something else in the keywords field and no information regarding these fields is present, they are cleared.

**Comment by frdrk-jhnssn** [comment]
No, I have "Write values of special fields as separate fields to BiBTeX" enabled. (And I can see these special fields in the .bib file, and they are removed when editing keywords)

**Comment by lenhard** [comment]
Ok, thanks. I can confirm this. It seems that the keyword synchronization kicks in for the special fields even though it should not.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `sync-special-fields`. Please try the latest build from http://builds.jabref.org/sync-special-fields.
