### ISSUE TITLE
Wishes for new fetchers

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2581]
Issue to collect wishes for new fetcher implementations. We should also add a prioritization here.

Fulltext:
- [x] https://oadoi.org/: Implemented with #3581 
- [x] American Physical Society (APS) #818

Entry-based:
- [x] Worldcat.org #1065 

ID-based:
- [x] Ottobib #2238 

Search-based:
- [x] Crossref.org #2455: Implemented with #2645

**Comment by CfKu** [comment]
By the way, ottobib is worldcat.org based
Worldcat API manual: http://xisbn.worldcat.org/xisbnadmin/doc/api.htm#schema and example http://kitchingroup.cheme.cmu.edu/blog/2015/01/31/Turn-an-ISBN-to-a-bibtex-entry/

**Comment by r0light** [comment]
Is there currently a need for new fetchers? Since all the issues are closed, it seems like this issue could also be closed

**Comment by Siedlerchr** [comment]
@r0light  This issue is still valid, it was created to have a central list of fetcher wishes and not an issue for each fetcher to keep the better overview

**Comment by allisonsampaio** [comment]
I developed the option to use ottobib based on the chimbori, then after it try the ebook.de and chimbori.com is made the requisition for ottobib.

I'm not sure if the method returns the expected ottobib bibtex. I'm putting here the IsbnViaOttoBibFetcher code and the part of the IsbnFetcher code that makes the request for ottobib.

`
        HttpResponse<String> postResponse;

        String BASE_URL = "https://www.ottobib.com/isbn/" + identifier + "/bibtex";

        try {
            postResponse = Unirest.post(BASE_URL)
                    .asString();
        } catch (UnirestException e) {
            throw new FetcherException("Could not retrieve data from ottobib.com", e);
        }
        if (postResponse.getStatus() != 200) {
            throw new FetcherException("Error while retrieving data from ottobib.com: " + postResponse.getBody());
        }`

`if (!bibEntry.isPresent()) {
            LOGGER.debug("No entry found at ebook.de and chimbori.com try ottobib");
            IsbnViaOttoBibFetcher isbnViaOttoBibFetcher = new IsbnViaOttoBibFetcher(importFormatPreferences);
            bibEntry = isbnViaOttoBibFetcher.performSearchById(identifier);
        }`

**Comment by allisonsampaio** [comment]
I developed the option to use ottobib based on the chimbori, then after it try the ebook.de and chimbori.com is made the requisition for ottobib.

I'm not sure if the method returns the expected ottobib bibtex. I'm putting here the IsbnViaOttoBibFetcher code.



        String BASE_URL = "https://www.ottobib.com/isbn/" + identifier + "/bibtex";

        try {
            postResponse = Unirest.post(BASE_URL)
                    .asString();
        } catch (UnirestException e) {
            throw new FetcherException("Could not retrieve data from ottobib.com", e);
        }
        if (postResponse.getStatus() != 200) {
            throw new FetcherException("Error while retrieving data from ottobib.com: " + postResponse.getBody());
        }

        List<BibEntry> fetchedEntries;
        try {
            fetchedEntries = getParser().parseEntries(postResponse.getRawBody());
        } catch (ParseException e) {
            throw new FetcherException("An internal parser error occurred", e);
        }
        if (fetchedEntries.isEmpty()) {
            return Optional.empty();
        } else if (fetchedEntries.size() > 1) {
            LOGGER.info("Fetcher " + getName() + "found more than one result for identifier " + identifier
                    + ". We will use the first entry.");
        }

        BibEntry entry = fetchedEntries.get(0);

       
        entry.setField("isbn", identifier);

        doPostCleanup(entry);

        return Optional.of(entry);`

**Comment by Siedlerchr** [comment]
Chimbori was removed, and ottobib was added. Ottobib uses worldcat for searching ISBN

**Comment by GlennOlsson** [comment]
Looking at the Worldcat fetcher at the moment. The Worldcat API would require an API key, is that something you are able to provide for testing? And how would that be added in the production code?

**Comment by augustjanse** [comment]
I'm working on the APS fetcher. Not sure what your stance is on API keys, but I'll just implement it for the open access papers.

**Comment by koppor** [comment]
@GlennOlsson Thank you for your intested.

1. Get a key for yourself
2. Work on the fetcher
3. Add the API key as constant
4. Add a preference that a user can add a key for himself. Include a link to the page where the key can be added
5. For the test cases, expect the key in an environment variable. (Can also be in the JabRef code itself that the fetcher checks JabRef's preferences and as fallback the environment variable. And then as fallback the constant).

Note that in the SpringerLink fetcher we did not implement the preference and the environment variable, but only the constant 😇

**Comment by koppor** [comment]
There are now PRs for each fetchers listed above. Thus, I close this issue. Thanks to everybody involved.
