### ISSUE TITLE
Camel key doesn't seem to be working

### ISSUE THREAD

**Issue by traversc** [JabRef/jabref#2589]
Hi, I can't get the camel key in the key pattern to work for some reason.  I'm using the latest release: 

Here is my key pattern: 
[auth][year][camel]

Here is my bibtex file: 

> % Encoding: UTF-8
> 
> @Article{Trapnell2009,
>   author  = {Trapnell, Cole and Pachter, Lior and Salzberg, Steven L.},
>   title   = {TopHat: discovering splice junctions with RNA-Seq},
>   journal = {Bioinformatics},
>   year    = {2009},
>   volume  = {25},
>   number  = {9},
>   pages   = {1105-1111},
>   issn    = {1367-4803, 1460-2059},
>   doi     = {10.1093/bioinformatics/btp120},
>   type    = {Journal Article},
>   url     = {http://bioinformatics.oxfordjournals.org/content/25/9/1105
> http://www.ncbi.nlm.nih.gov/pubmed/19289445
> http://bioinformatics.oxfordjournals.org/content/25/9/1105.abstract},
> }
> 
> @Comment{jabref-meta: databaseType:bibtex;}
>

**Comment by lenhard** [comment]
Hi @traversc 

What exactly is the error? Looking at the description here http://help.jabref.org/en/BibtexKeyPatterns I would say that the key `Trapnell2009` is exactly what I would expect from the key pattern `[auth][year][camel]`. 

Do you expect more author names? Then you should use `[authors][year][camel]`.

**Comment by traversc** [comment]
Apologies if I misunderstood the documentation.  

It says: 

>[camel]: Capitalize and concatenate all the words of the title. For example, An awesome paper on JabRef will become AnAwesomePaperOnJabref

So following that pattern when I use just [camel], shouldn't it output: TophatDiscoveringSpliceJunctionsWithRnaseq?  However, I just get a blank.  

Thanks

**Comment by Siedlerchr** [comment]
@traversc You have to use` [title][camel]` to generate the key
`TopHat:discoveringsplicejunctionswithRNA-Seq`

**Comment by Siedlerchr** [comment]
I took a look at the code and interestingly there is no check for the [camel] option.  I will provide a fix

**Comment by matthiasgeiger** [comment]
Hi! 
Thanks to @RolfStarre the problem should be fixed in the recent development builds. 
You can check out fixed versions at: https://builds.jabref.org/master
