### ISSUE TITLE
Adding an entry to a group by dragging no longer possible

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2590]
JabRef version JabRef 4.0.0-dev--snapshot--2017-02-24--master--83219486e
Windows 7 6.1 amd64 
Java 1.8.0_121

Steps to reproduce:

1. Open any library
2. Select an entry
3. Try to drag the entry to a group

This is not possible: If you use the mouse in the last stable version, once you drag the entry to a group, the STOP icon changes to a window with an error indicator, when you arrived over any group. In all the version of 4.0.0-dev I tested so far, the STOP icon does not change any longer and the counting of the group is not increased by one. When selecting the group the respective entry is not included.

```
Put the excerpt of the log file here: There is no entry in the log file about this.
```

**Comment by tobiasdiez** [comment]
Thanks to the work of @Siedlerchr drag and drop should work again. https://github.com/JabRef/jabref/pull/2632
