### ISSUE TITLE
Gradle does not work according to documentation.

### ISSUE THREAD

**Issue by TRvanRossum** [JabRef/jabref#2595]
Using Windows 7 and Windows 10. Running `gradlew clean check generateSource` in the main folder of a cloned project results in the following error:

* What went wrong:
Error resolving plugin [id: 'com.gradle.build-scan', version: '1.3']
> The response from https://plugins.gradle.org/api/gradle/3.3/plugin/use/com.gradle.build-scan/1.3 was not a valid response from a Gradle Plugin Resolution Service: content type is 'text/html; charset=utf-8', expected 'application/json' (status code: 503)

Reproduction steps:

1. Run cmd.
2. Go to main folder of your JabRef clone.
3. execute `gradlew clean check generateSource`.

**Comment by Siedlerchr** [comment]
Works fine for me on Windows 10, the Error 503 is probably coming from the global AWS outage today 
http://bgr.com/2017/02/28/internet-outage-amazon-web-services/

**Comment by TRvanRossum** [comment]
Thanks for the answer. I tried it again today, and it downloads a lot of the necessary JARs, but I still get this error:

* What went wrong:
Execution failed for task ':compileJava'.
> Could not initialize class net.ltgt.gradle.errorprone.ErrorProneCompiler$SelfFirstClassLoader

Any idea how I could fix this?

**Comment by TRvanRossum** [comment]
Also I tried to fix it by setting my JAVA_HOME variable to the main folder of JDK 1.8_121, and I get this:

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.ExceptionInInitializerError (no error message)

**Comment by Siedlerchr** [comment]
I alwayss execute ./gradlew eclipse and ./gradlew eclipse from the git bash

**Comment by Siedlerchr** [comment]
Another thing it could be that your local repo is out of sync, you could try the --refresh option: https://docs.gradle.org/current/userguide/dependency_management.html#sec:cache_command_line_options

**Comment by TRvanRossum** [comment]
Tried `./gradlew clean check generateSource` and `./gradlew clean check generateSource --refresh-dependencies` from the Git bash, both don't work. Current error message is:

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///C:/Users/Tim/Documents/Uni/JabRef/jabref/build/reports/test/index.html

The report can be found here:
[Test results - Test Summary.pdf](https://github.com/JabRef/jabref/files/810979/Test.results.-.Test.Summary.pdf)

Also, `gradlew eclipse` does actually work, and I can open the project in Eclipse, but running JabRefMain gives the following stack trace:

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
15:09:04.851 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.StackOverflowError: null
	at java.lang.Exception.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.lang.RuntimeException.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.MissingResourceException.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.ResourceBundle.throwMissingResourceException(Unknown Source) ~[?:1.8.0_111]
	at java.util.ResourceBundle.getBundleImpl(Unknown Source) ~[?:1.8.0_111]
	at java.util.ResourceBundle.getBundle(Unknown Source) ~[?:1.8.0_111]
	at org.jabref.logic.l10n.Localization.createResourceBundles(Localization.java:49) ~[bin/:?]
	at org.jabref.logic.l10n.Localization.setLanguage(Localization.java:40) ~[bin/:?]
	at org.jabref.logic.l10n.Localization.setLanguage(Localization.java:44) ~[bin/:?]
	at org.jabref.logic.l10n.Localization.setLanguage(Localization.java:44) ~[bin/:?]
	at org.jabref.logic.l10n.Localization.setLanguage(Localization.java:44) ~[bin/:?]
	at org.jabref.logic.l10n.Localization.setLanguage(Localization.java:44) ~[bin/:?]

**Comment by matthiasgeiger** [comment]
Could you try to check whether `./gradlew run` starts a JabRef instance? 

Failing tests may occur locally, especially the fetcher tests are not as stable as they are supposed to be...

Regarding the Eclipse problem, there seems to be a misconfiguration affecting the resources needed for the execution. @Siedlerchr Can you assist here?

**Comment by Siedlerchr** [comment]
Okay that looks good. Ignore the failing tests. Sometimes they won't really work on Windows when executed from gradle. Directly as junit test in Eclipse they work.
You don't need to run a clean. When you run a clean, all generated sources will be deleted. 

In Eclipse you have to refresh the workspace, right click on the project -> Refresh workspace. Then you should be able to start JabRef.

**Comment by TRvanRossum** [comment]
Starting JabRef in Eclipse works now. Thanks!

**Comment by Siedlerchr** [comment]
Glad to hear that it works now 🥇 . If you encounter further problems just let us know.  I would close this issue then for the moment.

When you fetch and merge updates from the master branch just execute the ./gradlew eclipse afterwards in case of new versions of libs (for example citation styles lib is updated often). Refresh the project in Eclipse and you are up to date.

We should definitely update the wiki page. https://github.com/JabRef/jabref/wiki/Guidelines-for-setting-up-a-local-workspace
