### ISSUE TITLE
New Iconset: Discussion on used icons

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#260]
I had a look around to see if there are some new icons we can add. I'm not really sure that I want to dig into the practical aspects of it, but the following could be used:

- [x] External file types: (9c42b0c30d94244bc23039e5698f399a36859b5c)
 - file.word: Word and Word 2007+
 - file-excel: Excel and Excel 2007+
 - file-powerpoint: PowerPoint and PowerPoint 2007+
 - file-document: Text

Menus:
 - [x] code-equal: Find duplicates (ee16876af4a6b2e6bcae77704e9f5e40276d71f1)
 - ~~console: Show error console~~
 - ~~palette: Mark specific color (also right-click menu)~~
 - ~~server-plus: Add to group~~
 - ~~server-minus: Remove from group~~
 - [x] keyboard: Customize key bindings (ee16876af4a6b2e6bcae77704e9f5e40276d71f1)
 - ~~select-all: Select all~~
 - [x] Change icon for groups to `view-list` (026d0529c35c0a14ec2630789c9053aacb6c572c)

Various:
 - [x] Fix icon issues in ExternalFileTypes dialogs
 - [x] Use graphical icon `files-multiple` for multiple files (d77acd8a2ef4764cda315ad8d90f70732300764c)

**Comment by simonharrer** [comment]
:+1: for the external file types.

For the ones of the menu, I am for the keyboard icon. Regarding the other ones, I am not sure as they do not fit perfectly from my point of view.

**Comment by matthiasgeiger** [comment]
Yes. I'll add the icons for the external file types.

Regarding the menus: At the moment only those menu entries should have icons which are permanently visible in the iconbar, indicating that both actions are the same. (Although, there might be some inconsistencies (e.g. in the "Help" menu).)
I'm not sure whether it is sensible to introduce more icons in the menus which aren't visible in the menu bar. It might help users to find a certain action quicker- but the relation to the iconBar is missing.

**Comment by simonharrer** [comment]
Good point. 

I would still make exceptions when the fit is perfect, e.g., for the keyboard short cuts.

**Comment by oscargus** [comment]
I see your points, but as Mathias says, it is not completely consistent
now. I also think the palette is a quite good match for arbitrary entry
coloring. Some of the others may indeed be less intuitive though...

A related question: would it make sense to have a configurable toolbar? I
know the stand point on fewer things in preferences, but now I'm not
talking switching things on and off, rather having a general way to form
your own toolbar (which is rather common).

(I can imagine that people may want to have commonly used menu choices in
the toolbar and instead remove those not so commonly used. I'm one for
sure. With the exception of the donate button of course, which should
always be there. :-) )

**Comment by simonharrer** [comment]
- [ ] use "file-multiple" instead of "file" + "m"
- [ ] remove button in preferences for external file types
- [ ] icons for external file types for office products
- [ ] view-list instead of "server" for toggle groups

**Comment by koppor** [comment]
Regarding the toolbar, I would propose to postbone that until the Java-FX UI is developed (see #113)

**Comment by simonharrer** [comment]
The toolbar may be changeable in the far future, I agree.

I think we do not have to be fully consistent, but only choose icons that fit and describe the whole functionality of a button/action. 

From my point of the, the palette is very misleading as one would expect only to select a color, not selecting a color AND marking the currently selected entries with this. What is more, the selected color is not stored any where for the next standard marking of an entry, the standard marking always uses the same color. This makes this feature even more strange. We will talk about this marked entry feature in the next dev call because there is also a preference option to disable the pinning feature of this marking, making this feature very hard to understand.

**Comment by matthiasgeiger** [comment]
I inserted the icons for "Keybindings", "Find duplicates" and added the Office-Icons for the external file types. 
As @simonharrer said above we will not include the other icon proposals as they do not fit in our opinion.

I'll leave this issue open (but rename it) to collect potential further proposals regarding the new iconset.

**Comment by koppor** [comment]
@matthiasgeiger Could you `<s>...</s>` in the description of the issue to guide readers what already has been handled?

**Comment by mlep** [comment]
The page https://github.com/JabRef/jabref/wiki/Donations mentions that donations are used for the
"Design of new icons for Material Design Icons." and send to this discussion.

Do we already know how much it will cost for these new icons?

If it is the right time to pay for these new icons, shouldn't we advertise it on the users mailing list?
