### ISSUE TITLE
User specific file directory not working for moving linked pdf files

### ISSUE THREAD

**Issue by eeenilsson** [JabRef/jabref#2602]
JabRef version 3.8.2 on  ArchLinux 4.9.8-1.

Jabref fails moving linked pdf from folder "A" to folder "B" through _clean > move linked files_.

Steps to reproduce:

1. Create item with linked pdf file in folder "A" (i use jabfox which stores the pdf in a zotero subdirectory). Check that clicking to open linked pdf works.
2. Set "Main directory" in _Options > preferences_ to folder "B" (this is same folder as .bib file)
3. Set _File > database properties > general file directory_ to folder "B".
4. Select item then cleanup entries, check the box "move linked files to default directory".
5. Clicking to open pdf now fails ("Status: unable to open link").

```
Warning at start (probably unrelated to the problem above):
9:55:16.518 [AWT-EventQueue-0] WARN  net.sf.jabref.JabRefGUI - There seem to be problems with OpenJDK and the default GTK Look&Feel. Using Metal L&F instead. Change to another L&F with caution.
```

**Comment by Siedlerchr** [comment]
Hi,
thanks for your report! Could you please try the latest development version here https://builds.jabref.org/moveFileDir/

**Comment by lenhard** [comment]
We think this is fixed in current master, hence I am closing.

Feel free to reopen if the problem reappears.
