### ISSUE TITLE
BibTeX Key Pattern results don't match with expectations

### ISSUE THREAD

**Issue by RolfStarre** [JabRef/jabref#2604]
Hi!

I encounterd some unexpected behaviour in the creation of keys, I'm using JabRef 3.8.2 on windows 10 10.0 amd64 Java 1.8.0_121.  

Steps to reproduce:

1. In Preferences -> BibTeX key generator set the Default pattern field to [title][shorttitle]
2. Generate the key, for example for the document in the screenshot

Based on the documentation on http://help.jabref.org/en/BibtexKeyPatterns I was expecting the following output:
For [title]: HeuristicsandUsabilityGuidelinesfortheCreationandEvaluationofFuninVideogames
For [shorttitle]: Heuristicsandusability 

Intead I got Heuristicsandusabilityguidelinesforthecreationandevaluationoffuninvideogames
and Heuristicsusabilityguidelines.  

![image](https://cloud.githubusercontent.com/assets/5969100/23546773/6e02e358-0001-11e7-97b5-d3da4b69be9b.png)

```
Put the excerpt of the log file here
```

**Comment by lenhard** [comment]
Related to #2589

Since this is the second report regarding key patterns in a short time, maybe there are some general issues with key patterns at the moment.

**Comment by RolfStarre** [comment]
Hey, thanks for the response :)

I was working on it but I noticed afterwards that @Siedlerchr was already working on it as well in this [pull request](https://github.com/JabRef/jabref/pull/2597), so I wasn't sure if I should continue.

Fixing the [shorttitle] option shouldn't be too hard, but I was unable to find where the [title] option is handled in the function makeLabel in the class BibtexKeyPatternUtil.

**Comment by Siedlerchr** [comment]
@RolfStarre  Thanks for your interest, as I had not yet the time to investigate why the Google Guava solution does not really work as expected, you could take a look at it. Or we could use your solution, I saw that you already added a test for it... Feel free to propose your PR here.
We are always looking contributors...;)

Regarding the [title] option, it is handled implicity in the else-part where just the field content is returned:
` return entry.getFieldOrAlias(val).orElse("");`

**Comment by RolfStarre** [comment]
Cool thanks, I'll continue working on it then :)

I'm going to try to fix the shortTitle and title cases as well then before I create the pull request. 
I'll try to see what the Google Guava does and if I can use it.

**Comment by Siedlerchr** [comment]
This can be closed right?

**Comment by RolfStarre** [comment]
Yup 👍
