### ISSUE TITLE
URL/DOI field opens a blank page in the browser (Chrome)

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#2605]
On JabRef 3.8.2, Ubuntu 16.04, Java 1.8.0_111
DOI: 10.1109/SOSE.2014.26

**Comment by lenhard** [comment]
Sorry, but based on this description we cannot reproduce or fix anything.

At the very least, we need to know the content of your doi field that does not work as desired.

**Comment by anassal** [comment]
You are right, sorry!

Well, on Ubuntu it seems to work fine on Firefox but not on Chrome (56.0.2924.87) whatever the URL/DOI. So could it be a bug in Chrome?

**Comment by lenhard** [comment]
Thanks, this makes it more clear. I only have Windows and there the open functionality works with firefox and chrome. Hence, I'll categorize this as linux. Someone with a ubuntu system will have to look into it.

**Comment by stefan-kolb** [comment]
@anassal Do you say this also affects Windows?

**Comment by anassal** [comment]
It does seem to work on Windows (8.1 and 10)! Apologies!

**Comment by stefan-kolb** [comment]
@anassal I cannot reproduce this issue here on Ubuntu with Chrome. Opens as expected. Chrome is set as default browser.

**Comment by stefan-kolb** [comment]
Probably Chrome is not correctly installed on your Ubuntu?!

**Comment by Siedlerchr** [comment]
I can not reproduce this , Xubuntu 16.04, latest JabRef version and Chrome. Therefore it seems like you have a problem with your browser

**Comment by anassal** [comment]
It seems to be an issue with the content of `googl-chrome.desktop` in Ubuntu, where `exec` doesn't pass the URL argument to `xdg-open`.

http://askubuntu.com/questions/540939/xdg-open-only-opens-a-new-tab-in-a-new-chromium-window-despite-passing-it-a-url

So you might want to close this issue as not related to JabRef. Apologies again!
