### ISSUE TITLE
RisImporter.java doesn't import RIS

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#2609]
I was looking into the code of
 jabref/src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java

The head comment (line 22-27) points to the documentation of a "Biblioscape Tag File".
The link there is dead. The new one is [](http://biblioscape.com/download/Biblioscape.pdf) (page 180).
The file format described there is **not RIS** (from the company [Research Information Systems](https://en.wikipedia.org/wiki/RIS_(file_format)))!

The correct documenation of the RIS-format can be found (here)[http://referencemanager.com/sites/rm/files/m/direct_export_ris.pdf].

Please clear up this situation because this affect some other bugs. e.g. #2607

**Comment by Siedlerchr** [comment]
Thanks for the investigation!
Maybe  @koppor  has an idea what kind of RIS format this in JabRef is

**Comment by koppor** [comment]
@zellerdev @tschechlovdev @Braunch @bartsch-dev Can you comment?

We also have a comparison table at http://help.jabref.org/en/MedlineRIS

@buhtz Can you comment on our help page? We don't use RIS here, just bibtex. Maybe you can submit an update to a) the importer, b) test cases, c) documentation?

**Comment by tschechlovdev** [comment]
You're right that the Ris importer originally was made of the biblioscape specification. But when working with the Ris importer I added more and more fields. So you're right, the ris importer doesn't have all fields of the ris specification, but many of them should be supported. Maybe it would make sense to look which fields are missing and add them. 

But I couldn't find the field L2 in the [ris specification](http://endnote.com/sites/rm/files/m/direct_export_ris.pdf). There are only the fields L1 and L4. So first of all it should be decided to take the fields from the [specification](http://endnote.com/sites/rm/files/m/direct_export_ris.pdf) or from [wikipedia](https://en.wikipedia.org/wiki/RIS_(file_format)) (wikipedia seems to have more fields).

**Comment by buhtz** [comment]
Firt of all I would recommend to update the comment in the source file to the current state. What kind of "RIS" is implemented here and where to find the original reference/specification used.

I am sorry, I am out of ressources and not able to invest more in that Issue because I have canceled using RIS. But JabRef is quit high on my TODO list. ;)

**Comment by lenhard** [comment]
Reviewing this issue again, I think it is a bit to unspecific to be of help. Instead of one "RIS import is not complete" issue, we should have separate smaller issues that track a specific part of import that is missing, like it is already the case with: #2607

So, I'll close this issue now and we should open new issues when we can reference specific fields that are missing.
