### ISSUE TITLE
Importing/appending database

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#262]
Currently there are three different menu items for importing/appending.
- Append database -> Imports a .bib-file and one can select if strings, entries, group definitions, and/or word selector definitions should be imported, before the file is selected. Once executed everything is imported (duplicate strings are ignored, duplicate entries are imported).
- Import into new database -> Imports entries from any supported file format into a new database.
- Import into current database -> Import entries from any supported file format into current database. Opens an import inspection dialog for selecting which entries to import.

Suggestion: Make a single import menu item using an import inspection dialog all the time. Ideally, the import inspection dialog should also have tabs for strings, group definitions, and word selector definitions when importing a .bib-file, as well as being able to import into a new database (which would then also be available for web searches).

It may be that it is better to wait with this until the JavaFX conversion (if it is a good idea).

**Comment by simonharrer** [comment]
:+1:

**Comment by stefan-kolb** [comment]
We will integrate this in our new JavaFX menu.
