### ISSUE TITLE
Opening a file with an unspecified encoding silently fails if default encoding does not match

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#2620]
Latest master on Win10

Steps to reproduce:

1. Export citation from http://link.springer.com/chapter/10.1007/978-3-540-27755-2_1
(Will create a UTF-8 encoded file with this content:
```
@Inbook{vanderAalst2004,
author="van der Aalst, Wil M. P.",
editor="Desel, J{\"o}rg
and Reisig, Wolfgang
and Rozenberg, Grzegorz",
title="Business Process Management Demystified: A Tutorial on Models, Systems and Standards for Workflow Management",
bookTitle="Lectures on Concurrency and Petri Nets: Advances in Petri Nets",
year="2004",
publisher="Springer Berlin Heidelberg",
address="Berlin, Heidelberg",
pages="1--65",
isbn="978-3-540-27755-2",
doi="10.1007/978-3-540-27755-2_1",
url="http://dx.doi.org/10.1007/978-3-540-27755-2_1"
}
```
)
2. Open the file in JabRef - which is configured to use `UTF-16BE` as default encoding.
3. Library is just empty - no log output regarding any problems.

The problem is not caused by the escaped `{\"o}` - but I have not found out what might have caused the trouble here...

@lenhard As our bib parser expert... can you have a look? 

*// Edit: adjusted steps to reproduce to refer to the encoding problem (see comments below)*

**Comment by matthiasgeiger** [comment]
... interestingly creating a new entry by simply pasting the exact entry posted above works flawlessly. 🙄

**Comment by lenhard** [comment]
Could this be an encoding problem? When I copy this text in a file and try to open this file in JabRef, during debugging every char the parser comes across is a chinese symbol. This is also the reason why it can't create an entry from it.

**Comment by matthiasgeiger** [comment]
Yes. It's an encoding problem... I don't have a glue why, but my JabRef was configured to use "UTF-16BE" as default encoding - the encoding of the Springer export is UTF-8 - and thus the opening fails.

Switching the default encoding to UTF-8 (or Windows-1251) the file can be opened...

So this is no bug, but it would be cool if a warning could be displayed (or at least logged). Isn't there another issue open regarding this?

**Comment by lenhard** [comment]
No other issue, JabRef is just desperately looking for an `@` that it can parse and since it doesn't find a single one, it just ignores the whole file. An idea would be a warning if the result of a parsing run is empty. Similar aspects are discussed in #2552

As a side note:

> I don't have a glue why

made my day :D

**Comment by Siedlerchr** [comment]
@matthiasgeiger  The UTF-16 is the default of Java, so maybe some test or whatever changed the setting in your JabRef instance
