### ISSUE TITLE
Right-click behaviour in grid

### ISSUE THREAD

**Issue by nhamilton1980** [JabRef/jabref#2627]
I use macbook air, when I right-click on a line-item in the grid (two-finger click on the touchpad) to open the menu, the next line-item is selected (moving the selection down 1 item) before the menu opens. This makes it next-to impossible to open the intended menu for the intended record.

**Comment by stefan-kolb** [comment]
@chochreiner WDYT?

**Comment by chochreiner** [comment]
I cannot reproduce this with 3.8.2 and the current master on a MacBook Pro (Retina, 13-inch, Mid 2014)

**Comment by chochreiner** [comment]
Same with 3.8.2 and 4-dev on a MacBook Air (13-inch, Late 2010)

**Comment by koppor** [comment]
@nhamilton1980 Please post your Mac config. OS version, Java version.

**Comment by stefan-kolb** [comment]
We cannot reproduce it here on a Mac Pro 2016. Seems like user-specif problem. Closing for now.
