### ISSUE TITLE
Removing from selected group does unselect the group

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2629]
JabRef 4.0.0-dev--snapshot--2017-02-24--master--83219486e
Windows 7 6.1 amd64 
Java 1.8.0_121

Steps to reproduce:

1. Have several groups
2. add an entry to a group
3. select the group in the group panel, only the selected entries are shown, and select the entry
4. Right click on the entry and remove from the selected group
5. while the group selection is still active in the group panel, in the entries list now all entries of the database are shown.

```
Nothing strange in the log
```

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
