### ISSUE TITLE
New Add Group Dialog

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2630]
Idea for a new javafx styled Group Dialog: 
@tobiasdiez  WDYT?
(My first try with the scence builder)

[CreateGroups.fxml.txt](https://github.com/JabRef/jabref/files/834089/CreateGroups.fxml.txt)

![grafik](https://cloud.githubusercontent.com/assets/320228/23797712/6c53c162-05a1-11e7-804b-84afe219ce10.png)

**Comment by tobiasdiez** [comment]
Looks definitely better than the old dialog, good job.
- I would move "Group definition" to the top. For edit, I would even compress it into a drop-down and for "Add group" make it a wizard 2-step process where on the first page the user decides upon the type of group (and there is some description what each type can do) and the second page is the normal edit dialog. What do you think about this idea?
- "General" is not really necessary / doesn't really provide additional information. I'm also not sure if we should really separate the options into groups "General" and "Type-specific". Maybe just have a list of options and a bigger space after the "general options"?

Thanks that you attack this "Baustelle" 😄

**Comment by Siedlerchr** [comment]
Found a nice idea for a Wizard like thing:
http://www.guigarage.com/2014/05/datafx-tutorial-3/

**Comment by Siedlerchr** [comment]
I have now separated the dialog in two parts

![grafik](https://cloud.githubusercontent.com/assets/320228/23834158/f45145e2-0751-11e7-904d-56f77166af68.png)

![grafik](https://cloud.githubusercontent.com/assets/320228/23834161/01f64d64-0752-11e7-82bc-397a3829e8a3.png)

**Comment by tobiasdiez** [comment]
I like it! Maybe still move the "Options" to the second page...not sure through. @JabRef/developers what you do you think?

In my opinion the icon and color can be put on the same line (with the icon first).

**Comment by Siedlerchr** [comment]
Regarding Icon I had the idea to integrate an ImageView component with a File Chooser, so that user direclty can open the icon/image from their file system

**Comment by tobiasdiez** [comment]
Right now the icon only allows a string (the identifier in the materialdesigns font) and not a path. Thus it is probably preferable to show a list of (predefined) icons instead of a file chooser.

**Comment by Siedlerchr** [comment]
Yes, I will take this into account and maybe probide a list with images/icons to browse from

**Comment by Siedlerchr** [comment]
So, my current idea is to use an auto complete text box (and I hope it will work) for searching the icons like it is possible on the website 
http://fontawesome.io/icons/
![grafik](https://cloud.githubusercontent.com/assets/320228/23872356/4eebf7c2-082e-11e7-82c1-05ef9182d911.png)

**Comment by matthiasgeiger** [comment]
Is this Icon stuff really worth the effort?

I would also prefer to have only a single dialog with the ability to switch from one type to another during creation of a group...

**Comment by Siedlerchr** [comment]
@matthiasgeiger  That icon stuff is just some nice to have stuff. 
My idea is that when you add a group this wizard is shown and when you right click on the group -> Edit defintion (name etcs ) and switch group type. Which then just would select the right dialog page of the wizard - with the ability to go back/forward to the other page.

In my opinion this is useful as I sometimes just want to edit the name of a group or the type.

**Comment by tobiasdiez** [comment]
As soon as the new javafx dialog is ready, the swing compatibility workaround introduced in https://github.com/JabRef/jabref/pull/2727/files#diff-6c6d2c1a2528d4dc593f3844f5c680d2R129 should be removed again.

**Comment by Clarke92** [comment]
Hi guys, is this one still available? I would love to fix some issues for you!

**Comment by Siedlerchr** [comment]
@Clarke92  Hey, thanks for the interesting in contributing! Yes, you can surely take my PR where I added the fxml files as a starting point: https://github.com/JabRef/jabref/pull/2643

To get started, have a look at our [Contributing guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md).

**Comment by tobiasdiez** [comment]
Since this dialog is now converted to JavaFX, there is no real urge to redesign it (PRs in this direction are of course welcome).
