### ISSUE TITLE
Show proper information message when OpenJFX is not installed

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2642]
As reported in https://github.com/JabRef/jabref/issues/1711#issuecomment-285991831 without the OpenJFX packages on linux a cryptic message "Error: Could not find or load main class org.jabref.JabRefMain" is displayed. 

It would be nice if instead a proper error message referring to `apt-get install openjfx` is shown. Not sure if this exception is "catchable". Or maybe we should indeed create a installer for linux that also installs openjfx in the process. Alternatively, we could create a [self-contained application](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html) that also includes a private JRE, [gradle plugin](https://github.com/FibreFoX/javafx-gradle-plugin).

**Comment by Siedlerchr** [comment]
Seems like you could simply check for a ClassNotFoundException:
http://stackoverflow.com/questions/12213929/how-to-detect-javafx-2-2-runtime-availability

**Comment by stefan-kolb** [comment]
We definitly need to fix this. If I just double click the Jar nothing happens and I don't even see an error message.

**Comment by Siedlerchr** [comment]
I will try around with it. Maybe we can show a simple Swing Message/Alert when the class is not found.

**Comment by Siedlerchr** [comment]
I searched a bit further and there is no real solution to this. 
If we get the 4.0.0 release in one of the debian packages, we can maybe mark the openjfx package as required. Otherwise we have to explicit inform the user before installation and should add a thing in the release notes. (We already documented this in the installation docs https://help.jabref.org/en/Installation )

**Comment by tobiasdiez** [comment]
Ok, if it is not possible then it is not possible...

**Comment by ilippert** [comment]
I also encounter this on Fedora 25 (the beta version 4.0 stops with "Error: Could not find or load main class org.jabref.JabRefMain"). If I interpret the issue correctly, OpenJFX will [not be installable easily soon on Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1145303) - and [building it](https://github.com/gferon/openjfx-fedora) seems tricky (I did not yet succeed)

**Comment by Siedlerchr** [comment]
You should then install the oracle jdk/jre, here seems to be an guide:
https://ask.fedoraproject.org/en/question/59412/sticky-how-do-i-install-oracle-java/

**Comment by koppor** [comment]
Can you check if
http://help.jabref.org/en/Installation#fedora-23-and-oracle-java does
provide enough support?

Am 27.04.2017 16:39 schrieb "ilippert" <notifications@github.com>:

**Comment by ambro2** [comment]
I recently had the same problem on Fedora 25. I had to install the Oracle Java JRE and configure the alternatives to set the Oracle version the default.
The Oracle JRE is available from here: [http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html](url) as rpm file.
The links on the Help site point to the Java Development Kit (JDK) which is not required unless you are developping programs in Java.

**Comment by ilippert** [comment]
Thanks @Siedlerchr @ambro2  @koppor. @Siedlerchr's link sufficed to get it work. Cheers
