### ISSUE TITLE
Jabref icon barely visible on dark backgrounds

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2648]
![screenshot from 2017-03-15 10-51-45](https://cloud.githubusercontent.com/assets/2141507/23963310/0a60bffc-096e-11e7-936b-3210b83c2b61.png)

**Comment by lynyus** [comment]
![manjaro_cinnamon](https://cloud.githubusercontent.com/assets/1254003/24054867/2cae94e0-0b3e-11e7-9af4-3b84c444d32f.png)

Also not really perfect on Manjaro Linux with Cinnamon. Think we need some contrast for dark backgrounds.

**Comment by tobiasdiez** [comment]
Similar problems happen also on Windows in certain cases (originally reported in #2856 ):
![jabrefscreenicon](https://cloud.githubusercontent.com/assets/9216487/26251425/80cc18ae-3cad-11e7-85f0-d6b9febe1428.PNG)

**Comment by stefan-kolb** [comment]
@JabRef/developers @halirutan Can we do something about that without changing our logo color?

**Comment by Ede123** [comment]
What about simply stroking the logo?

Doesn't look ugly, but solves the issue pretty much:

![grafik](https://user-images.githubusercontent.com/904570/38100897-f644c568-337e-11e8-882e-aa0b1cecebce.png)

[jabref.zip](https://github.com/JabRef/jabref/files/1861010/jabref.zip)

**Comment by halirutan** [comment]
Well, too late but anyway. 

![img](http://i.imgur.com/9m47KGO.png)

and

![img](http://i.imgur.com/OgXliZy.png)

**Comment by Ede123** [comment]
I like the blur, but I'm afraid it only works well at larger icon sizes.

Even in my examples (with thicker and fully opaque white border) the line is getting really thin and visibility decreases. However also did not want to make it any thicker, as that would close the thin gaps between the shapes...
