### ISSUE TITLE
Backup extension name

### ISSUE THREAD

**Issue by ekleinod** [JabRef/jabref#2653]
JabRef 3.8.2 linux 4.8.0-42-generic amd64  Java 1.8.0_121

In the settings I can choose to backup the old file when saving, but I cannot choose the extension to do so.

The chosen extension is ".bak", I would prefer "~" as this is standard on Linux systems.

Example: `literatur.bib` -> `literatur.bib~` would be my choice.

Thanks for the great work.

**Comment by koppor** [comment]
It was `.bak` for ages. 😇 

We currently have no money to pay someone for that. Thus, it depends on the availability of our free time. - If you can spend some more time, we would like to encourage you to check https://help.jabref.org/en/FAQcontributing - especially the part asking for improvement of our help pages <https://help.jabref.org/en/>. We have plenty of open issues there: https://github.com/JabRef/help.jabref.org/issues/

😇 🎉

**Comment by koppor** [comment]
Maybe, we should also think about `.sav`.

- Emacs uses `#literatur.bib#` (https://www.emacswiki.org/emacs/AutoSave)
- Vi uses `literatur.bib~` (http://stackoverflow.com/a/607475/873282)

**Comment by Siedlerchr** [comment]
Just a Simple setting where you can define extension/format ?

Am 16.03.2017 2:14 nachm. schrieb "Oliver Kopp" <notifications@github.com>:

**Comment by koppor** [comment]
In the devcall, we are currently trying to focus on other things. :fire:

We won't offer to be configurable.

In case you have time, you can make it OS-aware. PRs welcome.
