### ISSUE TITLE
Latex2Unicode Formatter: Captial letters after an underscore are wrapped in braces

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2664]
While checking the problem with the Underscores in the groups from  #2599, I noticed it's a problem of the Latex2Unicode formatter:  

Create a new entry with title `Underscore_Underscore`
Save
In the main table the entry is shown as `Underscore_(U)nderscore`

**Comment by koppor** [comment]
Is it possible to file an issue at https://github.com/tomtung/latex2unicode/issues?

**Comment by tomtung** [comment]
Hmm I think the behavior of determining subscript is consistent with latex (although if not in the math environment a compile error would be thrown). In other words, I guess latex2unicode is doing its job as intended?

Maybe JabRef can add some extra logic to determine when latex2unicode should kick in?

**Comment by koppor** [comment]
When interpreting `_` with LaTeX, the `_` command is a command stating that the following character should be go to subscript. If one does not want that, one has to load the [underscore](https://www.ctan.org/tex-archive/macros/latex/contrib/underscore) package. See http://tex.stackexchange.com/q/48632/9075.

Maybe, JabRef should escape the underscore when doing the conversion (this assumes that the user loads the underscore package)? Or warn the user?

**Comment by koppor** [comment]
Solution idea: `_` is only converted if followed by `_{...} `. - IDEA: replace _ by ARBITRARYSTRING, then convert to unicode and then convert back.

**Comment by tobiasdiez** [comment]
@tomtung probably text_u should convert the u to subscript letter in unicode and show it as textᵤ

**Comment by tomtung** [comment]
@tobiasdiez yeah that's the current behavior. Also I use `_(whatever)` to represent subscript when there are no corresponding Unicode subscript characters available.
