### ISSUE TITLE
Underscores are removed from citation keys

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#2671]
JabRef version: 4.0.0-dev
Mac OS X 10.12

Steps to reproduce:
1. Write/load citation key with underscore

### Update

See https://github.com/JabRef/jabref/issues/2671#issuecomment-292544849 for the issue remaining

**Comment by Siedlerchr** [comment]
Probably related to #2664

**Comment by j0hannes** [comment]
Could be. Two underscores followed by 1 result in (1).

**Comment by lenhard** [comment]
We recently fixed this in current master. Single underscores are now longer converted by the LaTeX to unicode conversion, but are preserved instead.

**Comment by j0hannes** [comment]
The "bibtexkey" available as column for the entry list now differs from the content of the field "Bibtexkey". If you have a key with an underscore, the underscore does not appear in "bibtexkey", which is somewhat misleading.

**Comment by koppor** [comment]
The latex2unicode converter should not be fired for bibtex keys.

**Comment by lenhard** [comment]
To be honest, when I try out the current master and enter the key `__1`, then it displays as `__1`. Also the display for other keys with an underscore works just as it should. So, I cannot reproduce the problem, but anyway....

#2720 removes unicode conversion for the bibtexkeyfield.

@koppor @j0hannes Please give it a try: http://builds.jabref.org/unicode-conversion-bibtexkey/

**Comment by j0hannes** [comment]
@lenhard It works 👍
