### ISSUE TITLE
Filename field in file annotations tab is too small when filename exceeds length of field

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2676]
Happens when filename is too long for the default field length.

![image](https://cloud.githubusercontent.com/assets/2141507/24149841/3427b61c-0e44-11e7-93b6-c544b2f805db.png)

**Comment by stefan-kolb** [comment]
We should just not show the full name before clicking on the dropdown field if possible.

**Comment by lynyus** [comment]
I guess it would be better to show only the filename without the path.

**Comment by stefan-kolb** [comment]
Would also be ok. Potentially the easiest way to bypass the length problem. But still, the field should be able to abbreviate this automatically?!

**Comment by koppor** [comment]
can't we use the magic being done for the labelling of our tabs of opened
libraries?

Am 21.03.2017 14:59 schrieb "Stefan Kolb" <notifications@github.com>:

**Comment by lynyus** [comment]
I have created a PR for this (https://github.com/JabRef/jabref/issues/2684). In my opinion it was easier to show only the file than to fiddle around with the internals of the JComboBox of Swing.
