### ISSUE TITLE
File annotations highlight vs annotation

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2677]
The file annotations tab shows two fields on the right for `Content`and `Marking`.
as far as I understand, a highlight can only have a marking and an annotation only content?
So we should only display one field with the value here if I am not mistaken!

![image](https://cloud.githubusercontent.com/assets/2141507/24150235/7b1a8c92-0e45-11e7-98a7-6057864dfa9a.png)

**Comment by lynyus** [comment]
Nope, if you click on a highlighted/underlined marking you can add a comment to the marked area. In this case both fields will be used.

**Comment by matthiasgeiger** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/676652/24150790/14cf78b0-0e47-11e7-9b69-73ec878c2852.png)

![unbenannt](https://cloud.githubusercontent.com/assets/676652/24150863/4eb67092-0e47-11e7-9075-9c144b273311.png)

:wink:
