### ISSUE TITLE
Removing a file from the File field needs two clicks on the minus button, not one click as before

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2679]
JabRef 4.0.0-dev--snapshot--2017-03-17--master--44f666ed2
Windows 7 6.1 amd64 
Java 1.8.0_121

Steps to reproduce:

1. have a library
2. select an entry with e.g. a pdf linked
3. goto General and select the File
4. now press minus, nothing happens, press it again and the linked file is gone.

This is different from earlier behaviour where one click was sufficient to remove the file. Single click on plus opens the file dialog, BTW.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`.

**Comment by bernhard-kleine** [comment]
You are correct, it is back to one click.

**Comment by bernhard-kleine** [comment]
in the JabRef 4.0.0-dev--snapshot--2017-03-22--master--7bb55f6d9
Windows 7 6.1 amd64 
Java 1.8.0_121

sometimes I still need to two clicks. Strange!

**Comment by Siedlerchr** [comment]
Hm, in the latest master version on Win10 this works for me correclty

**Comment by bernhard-kleine** [comment]
When I started with the mentioned snapshot, it worked. But now, importing a file via Jabfox, I want to remove the pdf, I select the File and press minus, nothing happens. A second click removes the file. Since I have already reacted to "the last version works for me", this is somehow strang.

**Comment by tobiasdiez** [comment]
Did you properly installed the new version or just copied the jar file? JabFox opens the JabRef executable specified in the Add-on preferences and this might be the older JabRef version.

**Comment by koppor** [comment]
Could you make a screencast using [ScreenToGif](http://www.screentogif.com/)?

**Comment by bernhard-kleine** [comment]
With the snapshot of today it worked with one click. Sorry. But will see whether that behaviour is stable when week goes on.
BTW I always install the win64 version not copying the jar file.

**Comment by lynyus** [comment]
Thanks, feel free to reopen it if it fails again.
