### ISSUE TITLE
The generated BibTeX keys of  two different imported entries are not unique?!!

### ISSUE THREAD

**Issue by alshehab211** [JabRef/jabref#2687]
JabRef version 3.8.2 on Windows 7

Steps to reproduce:

1. Import these three articles with different DOI
10.1103/PhysRevB.87.195439
10.1103/PhysRevB.87.205427
10.1209/0295-5075/102/27001
2. check the BibTeX keys of them, they are the same
3. Now, can not use Latex editor to cite them separately.

**Comment by lynyus** [comment]
Thank you for your report, I can confirm this with current master 9205a024e04955abb43e28ef29b62e438e9caf06.
Indeed this should not happen.

**Comment by lynyus** [comment]
I had a look in the code and infact JabRef does not enforce unique bibtex keys for entries.

Possible fix: [org.jabref.gui.Basepanel](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/BasePanel.java).insertEntry() (line 1180) should check for duplicate keys and automatically append a letter to the bibtex key.

Other fix: When importing entries using a fetcher automatically generate a key with the JabRef Key generator.

@JabRef/Developers what do you think about this matter?

**Comment by tobiasdiez** [comment]
I would say that the fetcher should automatically generate a new key, since the key delivered from the fetchers is often meaningless / adheres to the convention of the provider not the user. 
Maybe this can be combined with https://github.com/JabRef/jabref/issues/1283.

**Comment by bernhard-kleine** [comment]
I did the import with a snapshot from 7 days ago. It work well using the new entry->DOI ->generate way.
No duplicates. Maybe you should explain where you import from?

**Comment by koppor** [comment]
I tried http://dx.doi.org/10.1103/PhysRevB.87.195439 and http://dx.doi.org/10.1103/PhysRevB.87.205427. The BibTeX there offeres different keys. @alshehab211 could you state how you imported the entries, please?

**Comment by lynyus** [comment]
@koppor uhm? Have you tried to download them via the new entry dialog? For me this is still as @alshehab211 reports it.

**Comment by alshehab211** [comment]
@koppor using the New BibTex entry in Jabref with ID type: DOI

**Comment by Siedlerchr** [comment]
I can confirm the issue in the latest master:

![grafik](https://cloud.githubusercontent.com/assets/320228/24515276/6793c722-1577-11e7-8baa-dc33df7a0011.png)

**Comment by alshehab211** [comment]
@bernhard-kleine Yes, the two entries are not identified as duplicates but JabRef import them with the same BibTeX keys.

**Comment by lynyus** [comment]
So short poll which solution from https://github.com/JabRef/jabref/issues/2687#issuecomment-289283811 should be used:

* Check for duplicates and append a letter such that the second entry would be Vand_Duppen2013a
* Automatically generate a key with the JabRef Key generator.

**Comment by alshehab211** [comment]
This problem is arising when the first author has more than an article in the same year?!

**Comment by lynyus** [comment]
@alshehab211 Not particularly. We use a fetcher which at the moment just copies the key from the database which is queried. If this database contains any duplicate keys they are imported as they come.

**Comment by alshehab211** [comment]
@lynyus which database? if you can see the pages also are not imported for the mentioned entries?! (10.1103/PhysRevB.87.195439 & 10.1103/PhysRevB.87.205427) although the pages no. present in the BibTex in the journal database?!

**Comment by lynyus** [comment]
@alshehab211 it's from doi.org, nevertheless, when we call the download method in [DoiFetcher#55](https://github.com/JabRef/jabref/blob/79be111cff51adc355f9990df3074c5695856143/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java#L55), the entry already has the other key format.

**Comment by alshehab211** [comment]
When will the updated version of jabref be released where this error is fixed?

**Comment by tobiasdiez** [comment]
We have not yet a clear roadmap for the release of 4.0. Since a lot has changed in the new version, we will probably release an alpha / beta version first. Until then you may try out the latest development version from http://builds.jabref.org/master/, but please be aware that this version might have some issues and prepare accordingly with backups of your bib files etc.
