### ISSUE TITLE
SQL database: exporting and groups

### ISSUE THREAD

**Issue by JHoahg** [JabRef/jabref#2689]
Hi everybody,
we want to move our network file based bibliographic database (.bib-file,  ~20 contributors, 1600 entries ) to a MySQL database.
We are running JabRef version 3.82 on Fedora 23 on the clients and the server runs MySQL 14.14 on CentOS 6.8.
The creation of the MySQL database worked without problems also connecting to the database worked fine.
Now when you want to cite something you obviously need a local (or maybe read-only network) .bib -file.
We tried 2 Versions to get this file:
1st: when connecting to the shared database, you can save a local copy. a local copy never showed up.
if the auto save works, would it be always the latest version to work with latex?
2nd: we tried to export the loaded database, but the save operation never finishes.

for the groups:
after importing all the entries in the network database we still have the group-key in the bibtex-source, but the groups do not show up in the side panel.
creating the the group again from the side panel, yields again a group with all corresponding entries, that's cool. but after quitting jabref and reconnecting to the database these groups are gone. Is there a way to fix this?

Thanks for your help and all the work you put into developing.
-johannes

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/2647

**Comment by henbus** [comment]
i've the same problem with groups in a sql-database after the import from a bibtex-file. In my bibtex-file was the  block "@Comment{jabref-meeta: groupstree: ...} at the end, but there isn't anything of them in the table METADATA; only the KEY "databaseType" with the VALUE "bibtex;"

**Comment by tobiasdiez** [comment]
I think this issue was fixed with the release of JabRef 4.0, thus I'll now close it. Feel free to reopen the issue if I was wrong and the problem persists.
