### ISSUE TITLE
Groups tree of wrong bibfile is displayed

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#2690]
JabRef version 4.0.0-dev on Windows 7

Steps to reproduce:

1. Open JabRef with a single bibfile and the groups panel opened
2. Open a second bib file via the menu: File->Recent Libraries
3. The new bib file is displayed in the main table, but the groups panel still displays the groups tree of the other library
4. When switching back the original library, the groups panel switches to the groups tree of the library that was opened via recent libraries.

Note that both libraries for which I observe this behavior only contain the "All Entries" group. However, I can see the fault in the number of entries that are displayed in the groups panel. Also, the library I open via recent libraries contains a warning and there is no entry in the event log that it has been opened.

So, maybe this is a very weird setting, but someone from @JabRef/developers  should at least try to reproduce it.

**Comment by lynyus** [comment]
Just had the same error.

**Comment by tobiasdiez** [comment]
I can't reproduce this anymore and thus assume it is fixed. Feel free to reopen if the problem reappears.

**Comment by lenhard** [comment]
Sorry, this still is the case for me. I can't give you a surefire way of reproducing it unfortunately and there are no messages in the log.

I have noticed that when cycling through several bib files, it takes a few seconds for JabRef to compute the numbers in the group and eventually they show up. At some point, this "breaks": I am waiting at a bib file for the number to show up, but nothing happens. Then, I switch to another bib file. There the numbers are there instantly without any delay, but they belong to the bib file I just came from.

**Comment by tobiasdiez** [comment]
I tried to reproduce it, but failed...the computation of the numbers may take a while but for me the group tree is always the correct one. Can you please try to debug it (when you find time, of course). For the moment I remove this issue from the 4.0 milestone since this problems apparently occurs only sometimes and thus is no blocker in my opinion.

**Comment by lenhard** [comment]
Sure, no problem. This shouldn't be a blocker for 4.0. Let us just keep the issue open and maybe someone else, who is better at reproducing than me, runs into it.

**Comment by koppor** [comment]
I tried the steps @lenhard stated, but without success: Everything working fine.

**Comment by lenhard** [comment]
Let's just close this. I just use groups for testing the group feature, but I don't actually need them. If there really is a bug, then eventually one of our group power users will report it (and maybe with a better suggestion for reproduction).
