### ISSUE TITLE
Export to MS Office xml - date should be parsed to include year, month, and day

### ISSUE THREAD

**Issue by mew1033** [JabRef/jabref#2691]
JabRef version 3.8.2 on  Windows 10.

Steps to reproduce:

1. Create a source in JabRef.
2. Add a value to the date field. For example: `2014-10-18`.
3. Export source to xml. The month and year are included, but the day is not. In the BibLaTeX file, I have both the `year` field AND the `date` field. It's possible the year is being pulled from the `year` field, not the `date` field. Regardless, the `date` field should be processed to include year, month, and day.

This is what the XML currently looks like:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<b:Sources SelectedStyle="" xmlns="http://schemas.openxmlformats.org/officeDocument/2006/bibliography" xmlns:b="http://schemas.openxmlformats.org/officeDocument/2006/bibliography">
	<b:Source>
		<b:Year>2014</b:Year>
		<b:BIBTEX_Entry>www</b:BIBTEX_Entry>
		<b:SourceType>Misc</b:SourceType>
		<b:Title>The title</b:Title>
		<b:Tag>TheTag</b:Tag>
		<b:URL>http://theurl</b:URL>
		<b:Author>
			<b:Author>
				<b:NameList>
					<b:Person>
						<b:Last>lastname</b:Last>
						<b:First>Joe</b:First>
					</b:Person>
				</b:NameList>
			</b:Author>
		</b:Author>
		<b:Month>10</b:Month>
	</b:Source>
</b:Sources>
```

**Comment by Siedlerchr** [comment]
Hi,

In biblatex year and month are specified as alias fields for date and the
export should work correctly if you delete the contents of the year and
month field.

The only thing I can check, if the date field gets checked first and then
the other two fields. The code already handles alias fields

I am not sure regarding day, I will Check that

Am 29.03.2017 8:27 vorm. schrieb "Chandler" <notifications@github.com>:

**Comment by Siedlerchr** [comment]
I jut see that day is not exported and that month and year are considered before date. Will work on that.

**Comment by tobiasdiez** [comment]
The day part is now exported and thus this issue should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
