### ISSUE TITLE
"General file directory" is ignored when add PDFs

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#2694]
Using JabRef 3.8.1 from Debian unstable.

The "database properties" have as "General file directory": `/home/user/Dokumente/Library/MyJabRef-BIB/Files`

But when I add a new entry by DOI (10.1093/pubmed/fdr015) and then click on "Get full text" the resulting PDF is stored here: `/home/user/Dokumente/Library/MyJabRef-BIB/Armstrong_2011 - _textquotesingleScoping the scope_textquotesingle of a cochrane review.pdf`.

The `File` directory is missing. It looks like that the root directory of the bib-file is used here.

But there is some more mystic behaviour. I download the PDF manualy with my browser and stored it to my Files-directory. Then I added it to the entry with the `+` symbol. Then the file path is `File/armstrong2011.pdf`. But it should be `armstrong2011.pdf` because `File` is part of the default file directory for that database/bib-file.
I am not able to open then file with the document symbol. It is not found.
But when I manual remove the `File/` from the path and then click on the document-symbol the PDF is well opened. So when opening the correct default file directory is used.

Mystic....

**Comment by Siedlerchr** [comment]
Hi,
as there has been some major rework of the file and path handling stuff, I would suggest to try the latest development version.

http://builds.jabref.org/master/
Please note that if you use the openjdk you need the openjfx package to be installed.

**Comment by buhtz** [comment]
How do I use a jar-file in Debian unstable?

**Comment by buhtz** [comment]
With the OpenJDK and the current snapshot: I can reproduce that behaviour.

There is just one difference. When opening the PDF file it doesn't matter if there is `File/`in the path or not. It always use the correct PDF file (which definitly exist only one time under `File/`).

**Comment by Siedlerchr** [comment]
I can not reproduce that behavior with the latest snapshot. I am using Ubuntu.
Bib location is `/home/user/test.bib`
General file dir is ` /home/user/documents`

Did you make sure that the setting "Bib location as primary directory?" is **not** checked?
Because if that is checked it ignores  all other file directory settings.


Add a pdf (either via drag and drop or the Add dialog) from the default file dir.
In the General tab `A.pdf` is correclty shown.

**Comment by buhtz** [comment]
`Use the BIB file location as the primary file directory` was the cue. It was checked in my case. Thanks.

But maybe we should "overthink" that (to) many file-location-settings. But I think currently there is enough other and more important work.

**Comment by buhtz** [comment]
Another case:
I get this message on console and in the gui

`12:43:44.776 [AWT-EventQueue-1] WARN  org.jabref.logic.importer.OpenDatabase - Empty BibTeX key: N/A: "Euromaxx-Dein\_Freund,\_der\_Social... (Grouping may not work for this entry.)`

In the console it is ok. But in the gui it makes no sense because the entry is well added to a static group. It doesn't matter if there is key or not. This is a bit to much "warning" for a normal user and could be checked. This message should only appear in the gui when there is no bibtex-key AND no group-entry.

**Comment by buhtz** [comment]
Please see http://discourse.jabref.org/t/jabref-build-snapshot-killed-my-stable-jabref-3-8-1/550
