### ISSUE TITLE
GUI flashes when resizing

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#271]
In its current state on master, the GUI window of JabRef flashes when resizing the window. This effect is quite annoying (at least to my eye).  It's hard to capture the flash in screenshot, but to reproduce it, it is sufficient to start up the GUI and resize the window by dragging at its borders.

OS: Win 7
JRE: Oracle 1.8.0_60

**Comment by simonharrer** [comment]
This is a regression as this issue is not present in JabRef 2.10.

**Comment by simonharrer** [comment]
And it is not present in the current dev2.11 branch.

**Comment by simonharrer** [comment]
After doing `git bisect` and running `rm -r src/main/gen/ && gradlew clean run` for each commit the culprit seems to be f24233f86c8d26a95a1aa2d563ac1a0051949d1b

**Comment by lenhard** [comment]
That was an awesome roundtrip time for a bug fix. Great work!

**Comment by simonharrer** [comment]
:trophy:
