### ISSUE TITLE
Check integrity action freezes UI

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2717]
Takes kinda long even with small databases ~200 entries.
Should be run in a separate thread.

**Comment by PJozeph** [comment]
Shall I work on this ? If yes, can you can give some hint where and what to look?

**Comment by tobiasdiez** [comment]
Oh, I think this is already fixed in the current version. At least when I run the integrity check a small progress bar appears and the ui no longer freezes. @stefan-kolb ?
