### ISSUE TITLE
Check integrity action filter should have an option to select none and all

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2718]
It is tedious to deselect all of the issues first to select a single one after that to fix it

**Comment by Andrew-Lev** [comment]
I can take this one on.  Any suggestions on things to look into before starting?

**Comment by Siedlerchr** [comment]
Hi,

thanks for your interest in working at this!  For contributing just have a look at our Contributing guide:
https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

The code is structured into gui, logic and model. 
If you have any further questions, don't hesistate to ask
