### ISSUE TITLE
Set/clear/rename fields: append to a field

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#2721]
The dialog in `Quality -> Set/clear/rename fields` has no way to append a value to a field.

**e.g.** I want to add a new `keyword` to multiple entries without losing the existing keywords.

There is a [workaround](http://discourse.jabref.org/t/add-hyphenation-german-to-each-some-entries/493/7?u=buhtz) for that:

> Create a keyword-based group containing the expression you want to add and drag the entries onto this new group.

This works but is not the usual way of a user I think.

**Comment by Anirudh257** [comment]
Hey, I am a newbie and I would love to help you out.

**Comment by koppor** [comment]
@Anirudh257 Thank you for offering your help. Have you seen https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md? We hope that you have IntelliJ in place. This will help you much.

**Comment by tobiasdiez** [comment]
@Anirudh257 As a starting point have look at the class https://github.com/JabRef/jabref/blob/7a1b15abb58016b40e21a72124edf9da17cd08f2/src/main/java/org/jabref/gui/actions/MassSetFieldAction.java that handles the "Set/clear/rename fields" functionality. If you need further help, just ask here (or create a PR with your initial ideas).

**Comment by Anirudh257** [comment]
Sure, i will take a look into it.
