### ISSUE TITLE
Consistent methodology to signal that service is not available for fetchers

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2729]
It might occur (even often with Crossref) that a fetcher is not available right now or the error is on their end 500, 503, 504.
We need a consistent method to pass this information to the user. Now for example the user only sees a DOI not found message but in fact we couldn't look for a DOI in reality.

**Comment by Siedlerchr** [comment]
We already catch the Network related Exceptions, we should only forward them to the end user

**Comment by stefan-kolb** [comment]
See #1974

**Comment by Siedlerchr** [comment]
I think as we already converted all fetchers to the same interface now there is an error printend
