### ISSUE TITLE
Saving database: freeze when a new imported entry has unallowed characters (JabRef 3.8.1)

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#2738]
This is on JabRef 3.8.1 on Debian unstable GNU/Linux. I cost me some time to reproduce this.

When I import a bib-file with "special" characters into a database I can observe two things.

1. I am not able to double click on the imported entry to see the tabs with the fields. Just no reaction, no error.
2. When I try to save the database JabRef freeze with "Saving database..." in the status bar. Then I only can `kill` JabRef.

This is the bib-file causing the problem (btw: Exported from Zotero).

```

@online{_space_????,
	title = {Space und {ToDoNotes}: {\textbackslash}reserved@a has an extra \} .:. {goLaTeX} - Mein {LaTeX}-Forum},
	url = {http://golatex.de/viewtopic,p,92193.html#92193},
	urldate = {2017-04-14},
	file = {Space und ToDoNotes\: \\reserved@a has an extra \} .\:. goLaTeX - Mein LaTeX-Forum:/home/user/.mozilla/firefox/myprof/zotero/storage/GEKFXBRP/viewtopic,p,92193.html:text/html}
}
```

You see some "special" characters. I am not sure which one of them causing the problem. But this modified file works fine.

```
% Encoding: UTF-8

@online{_space_????,
	title = {Space und {ToDoNotes}: reserved a has an extra:. {goLaTeX} - Mein {LaTeX}-Forum},
	url = {http://golatex.de/viewtopic,p,92193.html#92193},
	urldate = {2017-04-14},
	file = {:/home/user/.mozilla/firefox/myprof/zotero/storage/GEKFXBRP/viewtopic,p,92193.html:text/html}
}
@Comment{jabref-meta: databaseType:biblatex;}

```

The diff is

```
0a1
> % Encoding: UTF-8
3c4
< 	title = {Space und {ToDoNotes}: {\textbackslash}reserved@a has an extra \} .:. {goLaTeX} - Mein {LaTeX}-Forum},
---
> 	title = {Space und {ToDoNotes}: reserved a has an extra:. {goLaTeX} - Mein {LaTeX}-Forum},
6,7c7,9
< 	file = {Space und ToDoNotes\: \\reserved@a has an extra \} .\:. goLaTeX - Mein LaTeX-Forum:/home/user/.mozilla/firefox/myprof/zotero/storage/GEKFXBRP/viewtopic,p,92193.html:text/html}
< }
\ Kein Zeilenumbruch am Dateiende.
---
> 	file = {:/home/user/.mozilla/firefox/myprof/zotero/storage/GEKFXBRP/viewtopic,p,92193.html:text/html}
> }
> @Comment{jabref-meta: databaseType:biblatex;}

```

From the point of view as a user it doesn't matter what the biblatex specification allows or not. JabRef should check if the data to be imported fits the specifications or not. My opinion.
And no matter if the data is corrupt or ot: JabRef shouldn't go to a freezed state while saving. There should be a error message.

**Comment by matthiasgeiger** [comment]
Can't reproduce this in current dev builds.

Can you please check whether the problem still persists?

**Comment by buhtz** [comment]
Correct. Not reproducible with current dev snapshot.
