### ISSUE TITLE
Translation for 4.0.0. version beta

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2741]
Dear @JabRef/translators, we are planning to release a 4.0.0. beta version tomorrow 🐣 

We know that this is a bit short for you, we nonetheless hope that you could help us in completing some of the missing translations.

If you can't make it for tomorrow, it's not a problem, but it would be nice if you could nonetheless help providing some of the missing translations. 
Please be aware that not all new translations are at the end.

@mlep  I would like you to ask to coordinate this again.

**Comment by koppor** [comment]
Please be aware that we changed "database" to "library" in the English wording (i) to avoid confusion with [SQL databases](https://help.jabref.org/en/SQLDatabase) and (ii) to be in line with [other bibliography management tools](https://github.com/JabRef/jabref/wiki/Alternatives).

Current status: The German translation is getting updated (https://github.com/JabRef/jabref/pull/2747), Italian and French are following (in case I am right).

See https://github.com/JabRef/jabref/issues/2095 for a discussion.
