### ISSUE TITLE
Blank key where name ends with 'and' and is followed by word 'and'

### ISSUE THREAD

**Issue by jbadham** [JabRef/jabref#275]
Under very specific conditions:
(1) Entering author names in Lastname, Firstname
(2) One of the authors has a Firstname ending in the characters 'and' (such as Roland)
(3) That author is not the last in the list (so there is the word 'and' after the text 'and' in the author's name)

Autogenerating the bibtexkey will generate a blank key, at least if [auth][year] is being used. It can be worked around by using Firstname Lastname for that author.

Note that the same problem occurs in Firstname Lastname if the author's Lastname ends with the characters 'and'

I don't have sufficient permission to attach an example file, but email me if this is not clear

**Comment by matthiasgeiger** [comment]
Can you simply post the BibTeX source of an example entry directly here in the comment field?

Thanks!

**Comment by jbadham** [comment]
This is the file I was using to experiment and isolate the problem


% This file was created with JabRef 2.10.
% Encoding: Cp1252


@Article{Alpha1290,
  Title                    = {test1},
  Author                   = {Alpha, Beta and Gamma, Delta and Eps, Gar},
  Year                     = {1290}
}

@Article{Alpha21960,
  Title                    = {test2},
  Author                   = {Alpha2, Beta and Gamma, Delta and Roland Smith and Eps, Gar},
  Year                     = {1960}
}

@Article{bad1,
  Title                    = {test3},
  Author                   = {Alpha3, Beta and Gamma, Delta and Smith, Roland and Eps, Gar},
  Year                     = {1960}
}

@Article{bad2,
  Title                    = {test4},
  Author                   = {Alpha Betand and John Smith},
  Year                     = {1990}
}

**Comment by mlep** [comment]
Seems related to http://sourceforge.net/p/jabref/bugs/1220/ and https://sourceforge.net/p/jabref/bugs/1224/

**Comment by jbadham** [comment]
Yes, sorry I didn't find that in the bug list

**Comment by matthiasgeiger** [comment]
Just checked it. This is already fixed in the current 2.11 beta version and in the master branch.
So please [upgrade to JabRef 2.11b4](https://sourceforge.net/projects/jabref/files/jabref/2.11%20beta%204/).
