### ISSUE TITLE
One author only + Compound last name + multiple initials => parsed incorrectly.

### ISSUE THREAD

**Issue by KennethJohnKelly** [JabRef/jabref#2750]
JabRef versionJabRef 3.8.2 on mac os x 10.11.6 x86_64 

JabRef interprets the author string "Van Deux, A. Z." as equivalent to "Van Deux and Z A".
 "van Deux, A. Z. and Elk, A." is handled correctly. More pertinently, so is "Van Deux, A."

Evidently, JabRef is bending over backwards to cater to the defective string "Ann Elk, Another Elk", which is too bad. But so long as that is the case, I think it is a bug not to identify "A. Z" in such cases as initials, just as JabRef already does with "A.".

[vandeux.txt](https://github.com/JabRef/jabref/files/924466/vandeux.txt)
<img width="292" alt="vandeux" src="https://cloud.githubusercontent.com/assets/26528092/25073141/0a9072c0-22ae-11e7-98fd-baea747149d1.png">

**Comment by Siedlerchr** [comment]
Thanks for your report. The issue is known and there is already discussion about it: See #2652 and 
See https://github.com/JabRef/jabref/pull/2669

**Comment by KennethJohnKelly** [comment]
Thanks for your response. I'm pleased to see the direction that was agreed upon. I'll check the open bugs more carefully next time!
