### ISSUE TITLE
Report of breaking LGoodDatePicker bug, only under the new Java 8 update 121. 

### ISSUE THREAD

**Issue by BlakeTNC** [JabRef/jabref#2755]
I thought your devs might want to see this LGoodDatePicker bug report. (Since you seem to have a wider user base I thought it might affect your project.) I don't have a Mac OSX (or linux) machine to reproduce the reported bug but I thought a developer here might. The reported bug does -not- appear on windows 8.1, with a compile and run under Java 8 update 121.

https://github.com/LGoodDatePicker/LGoodDatePicker/issues/49

Warm regards,
-Blake

**Comment by chochreiner** [comment]
I can reproduce this issue on MacOS 10.12.4 and Java 8 u 121

**Comment by tobiasdiez** [comment]
Thanks for the heads-up. The newest development now uses the built-in JavaFX date picker. Thus users having issues with the date editor are advised to upgrade to the built available from https://builds.jabref.org/master/

**Comment by BlakeTNC** [comment]
Nice solution, I should learn how to use JavaFX.

**Comment by BlakeTNC** [comment]
FYI: I know that JabRef is not using  LGoodDatePicker at the moment, but I still wanted to let you know that this bug has been fixed and a new release was published. For more details, see the closing comments on  https://github.com/LGoodDatePicker/LGoodDatePicker/issues/49

@chochreiner You mentioned being able to reproduce this issue. If interested, please let me know if the new release  is working for you. You can download the LGoodDatePicker executable demo jar at https://github.com/LGoodDatePicker/LGoodDatePicker/releases

**Comment by chochreiner** [comment]
The new release works fine 👍

**Comment by BlakeTNC** [comment]
@chochreiner Thanks!
