### ISSUE TITLE
NullPointerException in FileDialog

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2756]
As reported by Azure

Event time: 4/18/2017, 1:46:10 AM
Exception type: java.lang.NullPointerException
Failed method: java.nio.file.Files.provider
FileName: FallbackExceptionHandler.java
JabRef version: 4.0.0-beta
Java version: 1.8.0_121-b13
LineNumber: 22
Operating system: 10.12.5
SDK version: java:1.0.7
ThreadName: AWT-EventQueue-0

Call Stack:

java.lang.NullPointerException
java.nio.file.Files.provider
	
Files.java
	
97
[external code]
	
	
org.jabref.gui.util.FileDialogConfiguration$Builder.withInitialDirectory
	
FileDialogConfiguration.java
	
76
org.jabref.gui.FileDialog.<init>
	
FileDialog.java
	
67
org.jabref.gui.FileDialog.<init>
	
FileDialog.java
	
51
org.jabref.gui.FileDialog.<init>
	
FileDialog.java
	
42
org.jabref.gui.importer.actions.OpenDatabaseAction.actionPerformed
	
OpenDatabaseAction.java
	
97
[external code]
	
	
java.awt.EventDispatchThread.run
	
EventDispatchThread.java
	
82
<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortal?subscriptionId=47cf7e0e-fb38-4184-aa27-6bd33822da55&resourceGroup=JabRef&componentName=JabRef%20application&bladeDetails=SearchResultExceptionDetailBlade%2Fid%2F%257B%2522id%2522%253A%25220bda59a7-23c8-11e7-b5f8-89a1bcd88558%2522%252C%2522name%2522%253A%2522java.lang.NullPointerException%2522%252C%2522eventTime%2522%253A%25222017-04-17T23%253A46%253A10.591Z%2522%252C%2522eventType%2522%253A2%252C%2522componentId%2522%253A%257B%2522SubscriptionId%2522%253A%252247cf7e0e-fb38-4184-aa27-6bd33822da55%2522%252C%2522ResourceGroup%2522%253A%2522JabRef%2522%252C%2522Name%2522%253A%2522JabRef%2520application%2522%257D%252C%2522timeContext%2522%253A%257B%2522durationMs%2522%253A2678400000%252C%2522endTime%2522%253A%25222017-04-19T00%253A00%253A00.000Z%2522%252C%2522createdTime%2522%253A%2522Tue%2520Apr%252018%25202017%252010%253A46%253A54%2520GMT%252B0200%2520(W.%2520Europe%2520Standard%2520Time)%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522context.device.type%2522%253A%255B%2522PC%2522%255D%257D%257D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortalFeature?subscriptionId=47cf7e0e-fb38-4184-aa27-6bd33822da55&resourceGroup=JabRef&resourceName=JabRef%20application&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522java.lang.NullPointerException%2520at%2520java.nio.file.Files.provider%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222017-04-18T11%253A46%253A10.591Z%2522%252C%2522createdTime%2522%253A%25222017-04-18T08%253A47%253A21.982Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D" target="_blank">View similar exceptions in this time range<\a>

**Comment by Siedlerchr** [comment]
Seems to be using still the deprecated FileDIalog and not the new Service Dialog

**Comment by Siedlerchr** [comment]
Should be resolved with #2767
