### ISSUE TITLE
Using $\dagger$ math symbol in article title does not work

### ISSUE THREAD

**Issue by mcspritz** [JabRef/jabref#2757]
JabRef 3.8.2
linux 4.4.59-1-manjaro amd64 
Java 1.8.0_121

Hi, I tried to insert this article into jabref DOI: 10.1021/jp9013493 but the dagger symbol does not show off when using LaTeX sintax which should be $\dagger$
I don't know if this is a local problem or has to be solved by you.

Cheers

**Comment by tobiasdiez** [comment]
Can you please recheck if this problem this persists with the recently released 4.0 beta version. We made some changes to the way latex symbols are converted to unicode. Thanks.

**Comment by lenhard** [comment]
I just tested this on the recent master branch and for me `$\dagger$` is correctly displayed as †

**Comment by lynyus** [comment]
I can confirm this issue on the current master. The $\textdagger$ is just ommited.
Linux Manjaro 17.0.1-1
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by jonasstein** [comment]
![selection_309](https://user-images.githubusercontent.com/298682/27770650-cb313e44-5f42-11e7-95ff-ba41bb605340.png)

`Test with title = textdagger: "$\textdagger$" and dagger: "$\dagger$"`

```
JabRef 4.0.0-dev--snapshot--2017-06-29--master--7e50e84a1
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131
```

**Comment by tobiasdiez** [comment]
Should be fixed in one of the next versions; as soon as https://github.com/tomtung/latex2unicode/pull/5 is merged and a new version of the unicode conversion library is released.

**Comment by lynyus** [comment]
This has happened now. For me this is working fine now. Check the latest master build from https://builds.jabref.org/master/

**Comment by jonasstein** [comment]
I confirm, that it works as expected in

```
JabRef 4.0.0-dev--snapshot--2017-07-03--master--6897b10fb
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131
```
