### ISSUE TITLE
How to customize the cite command for emacs

### ISSUE THREAD

**Issue by zhixing2017** [JabRef/jabref#2769]
JabRef 3.8.2   windows 7 6.1 amd64      Java 1.8.0_121

Hi, thanks for your job.
Here is my question. When I push a citation to emacs, it inserted `\cite{bibtexkey}`.
How to just insert `cite:bibtexkey` by customize the option of `cite command`?
I do not know how to customize the option. Can you help me?

**Comment by lynyus** [comment]
Hi,
can you elaborate more on the use case for this?
Why would you like JabRef to push such a string (`cite:bibtexkeydy`) into your document instead of a LaTeX command?

**Comment by zhixing2017** [comment]
I used the `org-ref`. It insert and recognize citation in this format `cite:bibtexkey` in org files. Normally, I take notes in `org files` instead of the `LaTeX files`.

**Comment by koppor** [comment]
![grafik](https://cloud.githubusercontent.com/assets/1366654/25214934/9b22a0a8-259a-11e7-8a19-677669a17ce4.png)

Does that work?

**Comment by zhixing2017** [comment]
It is the right place. But it insert `{}` around the bibtexkey. I do not know how to git rid of it.

**Comment by stefan-kolb** [comment]
@zhixing2017 You say your format would be `cite:bibtexkey`. How would a citation with multiple keys look like? Or is this even possible? Like `\cite{a, b, c}`

**Comment by stefan-kolb** [comment]
Ok I see it is `cite:a,b,c` then.

**Comment by stefan-kolb** [comment]
For me, the question is how many use cases do we have for such customizations? Currently, the use case is probably just about using different cite commands, which comply to the BibTeX standard format `{}`, e.g., https://www.sharelatex.com/learn/Natbib_citation_styles

**Comment by zhixing2017** [comment]
I think it is better that the cite command can be customized by users, like the bibtexkey for journal, book, et al.
