### ISSUE TITLE
Font size doesn't (seem to) affect tables

### ISSUE THREAD

**Issue by kaimast** [JabRef/jabref#2770]
Hey,

I'm (trying to) use JabRef on a high DPI screen under Linux. Ideally, I'd expect it to use the desktop environments scaling factor, but for now setting the font size to someting larger than 11 seems to work.

However, some UI elements, e.g. tables, seem to ignore the font size setting, making JabRef more or less unusable. 
(see the attached screenshot)]

![jabref](https://cloud.githubusercontent.com/assets/4525445/25195656/4da89320-250c-11e7-8549-9084e2e1e021.png)

-Kai

**Comment by lynyus** [comment]
Hi Kai,
we are currently migrating the UI technology from Swing to JavaFX. Presumably, the high-DPI support will improve in the course of action.
However, I think adjusting the table font should be sufficient to make you happy for the time being:
have you tried `Options -> Preferences -> Appearance -> Set table font`?

In the other news, we also accept pull requests to make JabRef great again!

**Comment by lynyus** [comment]
Seems like currently nobody has time to fix these issues.

**Comment by tobiasdiez** [comment]
For Windows 10, there is work-around to get a workable resolution (I wouldn't call it nice through):

- Find and Right click `JabRef.exe` in the installation folder -> Properties
- Go to `Compatibility` tab
- Check `Override high DPI scaling behavior.`
- Choose `System` for `Scaling performed by`
