### ISSUE TITLE
ExportFormats: Use FileExtension enum

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2772]
Export Formats should use the FileExtensions Enum (analog to import), too

**Comment by PJozeph** [comment]
Can I have this issue ?

**Comment by tobiasdiez** [comment]
@PJozeph sure! Let us know if you need help on the way (either ask here in this issue or open a PR with your preliminary code).

**Comment by PJozeph** [comment]
okay, i'm on it

**Comment by PJozeph** [comment]
Do I understood it right that in the ExportFormats class  the EXPORT_FORMATS map needs to hold FileExtensions values ? @tobiasdiez

**Comment by tobiasdiez** [comment]
Yes. The extension in `ExportFormat`
https://github.com/JabRef/jabref/blob/07652a93fb10ef5115e1346fd68576aa2e4cea36/src/main/java/org/jabref/logic/exporter/ExportFormat.java#L41
should not be a string but an instance of `FileExtensions`.

**Comment by PJozeph** [comment]
im done, is there a documentation how to proceed push ? I did not find it on wiki. @tobiasdiez

**Comment by tobiasdiez** [comment]
Nice, that was quick! We have some general comments in https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md but in the end it boils down to the typical steps to contribute code: you push the changes to your own branch and create a pullrequest here on github.

**Comment by tobiasdiez** [comment]
Implemented by #3565
