### ISSUE TITLE
Losing hyphens between prefix and last name

### ISSUE THREAD

**Issue by KennethJohnKelly** [JabRef/jabref#2775]
JabRef version JabRef 3.8.2
mac os x 10.11.6 x86_64 
Java 1.8.0_121

JabRef normalizes "ul-Somewhere, Someone" to "ul Somewhere, Someone" (undesirable). This is presumably a side-effect of the (desirable) behaviour of  normalizing "Someone-ul-Somewhere" to "ul-Somewhere, Someone". IOW, the hyphen between first name and prefix should be lost on normalization, but hyphens between prefix and last name should be preserved.

Obviously, there are more prosaic examples. "Someone le-GrandAuthor" should normalize to "le-GrandAuthor, Someone" not "le GrandAuthor, Someone".

[If there is already a bug report on this then I will need guidance on how to use the search field!]

**Comment by stefan-kolb** [comment]
Cannot work on this because of a9e20660e07992b7f5739ce53c9156ae45623abf

**Comment by lynyus** [comment]
We think, this is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by KennethJohnKelly** [comment]
Works fine, thank-you!
