### ISSUE TITLE
Extract and provide preview templates

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#278]
Options -> Preferences -> Entry preview

Render via *.bst files or html templates, e.g. IEEE, Chicagostyle, ...

**Comment by stefan-kolb** [comment]
#119

**Comment by koppor** [comment]
Especially see https://github.com/JabRef/jabref/issues/119#issuecomment-152326777 regarding our BibTeX VM, which supports rendering using `bst` files.
