### ISSUE TITLE
Jabfox not working with 4.0.0-beta

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2782]
Steps to reproduce:

1. open jabref, control that the tick is set in Options->Advanced : listen to remote operation on port 6050
2. start pubmed in firefox with PMID: 27916456
3. import the entry with zotero/jabfox 
4. you wait ... nothing happens

no new issue in the event log

Edit: fetching with the PMID in medline/pubmed fetcher works

**Comment by stefan-kolb** [comment]
See #2792
