### ISSUE TITLE
Automatic insertion of keyword according to group

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#2783]
JabRef version 4.0-beta on Debian 8 AMD64

Steps to reproduce:

1. Select a dynamic group based on keywords field
2. Add bibliographic item
3. Expected result: the bibliographic item has already the keyword of the group (as in previous versions of Jabref)
4. Real result: the bibliographic item has _not_ already the keyword

The option in preference to add the new item to selected group is regularly checked.

Many thanks in advance,
Domenico

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by Doc73** [comment]
Many thanks!
Works very well.
