### ISSUE TITLE
Allow resorting of groups using drag & drop

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2785]
Resort groups by drag and drop as raised in https://github.com/JabRef/jabref/issues/2656#issuecomment-287402637 and further discussed in https://github.com/JabRef/jabref/issues/2599.

**Comment by AEgit** [comment]
To add upon this: When a group is assigned as subgroup to another group, the focus on this group is lost. Instead the group that was found below the initial group is selected.

1. Selected a group
2. Drag'n'drop onto another group, to reassign it as respective subgroup
3. The focus on this subgroup is lost in the groups panel - Instead the group that was initially found below the reassigned group is selected

**Comment by AEgit** [comment]
I can confirm that the resorting of groups using drag'n'drop works in:
JabRef 4.0.0-dev--snapshot--2017-05-25--master--4c87dde9c
Windows 10 10.0 amd64 
Java 1.8.0_131

The issue I reported above, however, persists. Every time you assign a group to a new subgroup, the focus on your selected group is lost after the assignment. I will open a new ticket for this.
