### ISSUE TITLE
Allow selection of multiple groups

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2786]
It was previously possible to select more then one group. 

Related group settings:
- "Intersection",
- "Union",
- "Inverted",

**Comment by AEgit** [comment]
I'm using this feature quite often, so I would heavily be in favour to it being readded.

**Comment by lenhard** [comment]
This is implemented in #2845

**Comment by AEgit** [comment]
I can confirm that this works in:
JabRef 4.0.0-dev--snapshot--2017-05-18--master--018173ebd

I do notice, however, that the group selection is somewhat slower compared to 3.8.2 - every time I select a group in the groups panel, it takes ~1-2 sec to show the group entries. In 3.8.2 this selection happened in an instant. This might be related to https://github.com/JabRef/jabref/issues/2837 or https://github.com/JabRef/jabref/pull/2588

**Comment by lenhard** [comment]
Too bad. At least now much of the duplicated code is gone and I was hoping for a better performance. We should try to improve this some more before a final release.

**Comment by AEgit** [comment]
I might have to take it back. Today the performance issue I reported here, does not seem to appear. The group entries are shown immediately, when a group is selected. The only performance issue that remains is the one reported here:
https://github.com/JabRef/jabref/pull/2588#issuecomment-302629336

BTW: Can someone tell me, what the green colour around the item number reported next to each group in the groups panel means? Does it mean, that a selected entry is part of the group indicated in green? If so, I might have found another bug.

**Comment by tobiasdiez** [comment]
@AEgit Yes, green = all selected entries are contained in this group, brownish green = at least one selected entry belongs to this group.

**Comment by AEgit** [comment]
@tobiasdiez : Thank you very much - I think I found the bug, I mentioned (it just took me a while to find out, how to replicate it): see https://github.com/JabRef/jabref/issues/2857
