### ISSUE TITLE
Changes to groups and edits in entry editor no longer mark database as dirty

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2787]
For groups raised in https://github.com/JabRef/jabref/issues/2599#issuecomment-291474696 and also occurs in the current development build for changes in bibentries. 
Possible solution: main table should listen to changes to database + maintable (instead of the old push-notification).

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/2946
