### ISSUE TITLE
IEEEXplore fetcher seems to be broken

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#2789]
JabRef version 4.0.0-beta on Windows 10

Steps to reproduce:

1. Perform a web search using the "IEEEXplore" fetcher
2. result is always "Invalid search term"

no more logs shown...

**Comment by Siedlerchr** [comment]
Seems like a problem with IEEE on their side, when I manually try to search for a term, e.g information retrieval, I always get empty results "Unable to find results for".

**Comment by matthiasgeiger** [comment]
[Works for me...](http://ieeexplore.ieee.org/search/searchresult.jsp?queryText=information retrieval)

**Comment by stefan-kolb** [comment]
@jeff-kerr Can you take a look at this, please? Where did you get the initial information for the API when you first wrote the code?
