### ISSUE TITLE
Once again: Jabfox not working

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2792]
JabRef 4.0.0-dev--snapshot--2017-04-24--master--4e25cc642
Windows 7 6.1 amd64 
Java 1.8.0_131

Steps to reproduce:
1. open jabref and assure that Options->Advanced->Listen to remote operation is checked
2. select PMID: 8001151 on Pubmed
3. run jabfox on this single entry
 nothing happens

```
Put the excerpt of the log file here
```

**Comment by AEgit** [comment]
Cannot confirm for:
JabRef 4.0.0-dev--snapshot--2017-04-22--master--059f805e6
and
JabRef 4.0.0-dev--snapshot--2017-04-24--master--4e25cc642
Windows 10 10.0 amd64 
Java 1.8.0_131

The combination JabFox and JabRef DOES work with this versions (I haven't changed any options in JabRef). What I do note, however, is that the imported entry is NOT assigned to the initially selected group. In fact, it is not assigned to any group.

**Comment by bernhard-kleine** [comment]
firefox 53 updated yesterday. I didnot change anything in jabfox. I am now working with JabRef 3.8.2
windows 7 6.1 amd64, Java 1.8.0_131 and still no  import. Maybe something which is not jabref changed.

**Comment by AEgit** [comment]
I'm running Firefox 53.0 (64 bit) as well, so it's probably not related to Firefox.

**Comment by bernhard-kleine** [comment]
It was the pathname of the jabref.exe which was changed. Jabfox could no longer find it. Sorry for the noise.

**Comment by koppor** [comment]
How did you discover it? Was there an error message somehow?

**Comment by bernhard-kleine** [comment]
After seeing that the jabref was not the culprit I looked into the jabfox add-on and immediately saw that the path was not the one where I had installed the latest snapshot and the beta. Changing the path allowed Jabfox to communicate again with jabref.
