### ISSUE TITLE
Default ID type in the ID-based entry generator

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#2796]
The default ID type in the ID-based entry generator dialog box is currently ArXiv (because of alphabetical order),

I suppose some users mainly use specific ID types other than ArXiv.

For usability, it would be helpful to set a default choice based on the user preference or the most recently used ID type.

**Comment by tobiasdiez** [comment]
Even better: Jabref should recognize the type based on the inserted ID (for example, arXiv ids look completely different from DOI or PMIDs)

**Comment by stefan-kolb** [comment]
The default type has been changed to DOI recently.

**Comment by cerrisantos** [comment]
I have created a pull request @ #3712
