### ISSUE TITLE
regex search & apostrophes in author field

### ISSUE THREAD

**Issue by KennethJohnKelly** [JabRef/jabref#2797]
JabRef 3.8.2
mac os x 10.11.6 x86_64 
Java 1.8.0_121

Steps to reproduce:

1. Create an entry with "O'Brian" or the like in author field. No consecutive caps in entry
2. enable regex searching, case-sensitive
3. enter author=\b[A-Z][A-Z]. Entry is matched.
4. remove "author=".  Entry is no longer matched.

I suspect is this is related to the odd treatment of apostrophes in the author field - they are swallowed in entry display table. Guessing this is a Latex-related. "O'B" is OK in other fields, however.

**Comment by Siedlerchr** [comment]
Could you please test this with the current 4.0.0 beta as we switched to a new library for handling the covnersion between latex and unicode

**Comment by KennethJohnKelly** [comment]
Tested on: JabRef 4.0.0-beta
Mac OS X 10.11.6 x86_64 
Java 1.8.0_121

Appears to be fixed.
