### ISSUE TITLE
Attach file scrambled

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2800]
JabRef 4.0.0-dev--snapshot--2017-04-26--master--4a0f6cd14
Windows 7 6.1 amd64 
Java 1.8.0_131

1. in the General tab of the edit-dialogue the + and - button are missing
2. if using the context menu of an entry to attach a file the selected directory is not opened.
3. these are inacceptible regressions

This has changed in the last few days. 

```
Put the excerpt of the log file here
```

**Comment by stefan-kolb** [comment]
@tobiasdiez is reworking the whole entry editor at the moment.

**Comment by tobiasdiez** [comment]
Yes, the file editor will be reimplemented with #2798. You can try out the version from http://builds.jabref.org/fileEditor/.

**Comment by bernhard-kleine** [comment]
This I can accept. I reverted for working with Jabref to 3.8.2 with all the missings of that version.
