### ISSUE TITLE
Generate Bibtex Key does not use Date information

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#2801]
JabRef 4.0.0-beta
Linux 4.10.11-200.fc25.x86_64 amd64 
Java 1.8.0_131

probably not specific to this version, but still: it seems strange to me that the automatic generation of a bibtex key is impossible when not supply a Year information even though a full Date information is present.

**Comment by Siedlerchr** [comment]
This already works for me in 4.0.0 current master:

Default pattern `[auth][year]`
Date field has a value like `2013-01-02`
Generate bibtexkey now succesfully generates it using  `MyAuthor_2013`

But be aware that the date editing field is currently a bit buggy as I noted in #2806

**Comment by ilippert** [comment]
I confirm that this works now.

I guess this closed. I experience related issues and will open more specific issues.
