### ISSUE TITLE
cite command is not employed

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#2802]
JabRef 4.0.0-beta
Linux 4.10.11-200.fc25.x86_64 amd64
Java 1.8.0_131

Maybe I got something wrong: I opened the preferences | External Programmes and specified "Cite command" as \autocite. But Ctrl+K still gets me \cite. I would have assumed, Ctrl+K should get my specified cite command now.

**Comment by lynyus** [comment]
Well actually Ctrl+K is just the shortcut for putting \cite{bibtexkey} into your clipboard. At the moment this cannot be customized.
If I get it right, the preferences concerning external programs is about pushing bibtex keys into the auto-completion of the external editors.

@JabRef/Developers: what do you think about this use case: should we merge this functionality, such that CTRL+K can be customized?

**Comment by koppor** [comment]
It should use the same (!) setting. Not two different settings

Am 04.05.2017 14:03 schrieb "Linus Dietz" <notifications@github.com>:

**Comment by ilippert** [comment]
thanks @simonharrer 

my status is: running JabRef with  ./gradlew run does not change the behaviour that I originally reported

JabRef 4.0.0-dev
Linux 4.13.8-200.fc26.x86_64 i386 
Java 1.8.0_144

**Comment by Siedlerchr** [comment]
@ilippert  You have to use the latest dev version: http://builds.jabref.org/master/

**Comment by ilippert** [comment]
sorry, yes, it works wonderfully! (forgot git updating)
