### ISSUE TITLE
Review changes does not accept "ok"

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#2807]
JabRef 4.0.0-beta
Linux 4.10.12-200.fc25.x86_64 amd64 
Java 1.8.0_131

The bibtex file has been altered externally. Correctly, Jabref asks me ""Review changes". In the dialog, whatever I do/mark towards accepting, "ok" does not effect any change. "Cancel" works.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. Can you please try the latest build from http://builds.jabref.org/master.
Also, please provide a minimal example to reproduce the issue if possible.

**Comment by ilippert** [comment]
Ok, checked again and cannot reproduce anymore
