### ISSUE TITLE
entry editor and main table view not updated

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#2812]
JabRef 4.0.0-dev--snapshot--2017-05-01--master--fcac52707
Linux 4.10.12-200.fc25.x86_64 amd64
Java 1.8.0_131

as noted in the opening post of #2808, in my version the timestamp is not updated. also, when changing bibtex keys, the view is not immediately updated.

I seem to be able to see some of the the updates  in the biblatex source. and I can see some timestamp changes after restarting jabref and changed bibtexkeys after switching between the entry editor and the entry preview.

**Comment by AEgit** [comment]
This is just a guess, but it could be a general problem with entry/main table preview. See also this issue (still appears in JabRef 4.0.0-dev--snapshot--2017-04-24--master--4e25cc642): https://github.com/JabRef/jabref/issues/1903

**Comment by tobiasdiez** [comment]
Can you please describe exactly where you change what and what the expected/current outcome is. I just tried to change a few information in the entry editor and the maintable as well as the bibtex source where updated immediately.

**Comment by ilippert** [comment]
JabRef 4.0.0-dev--snapshot--2017-05-09--master--78185153b
Linux 4.10.14-200.fc25.x86_64 amd64 
Java 1.8.0_131 
hmm, just checking - but in this version I am only shown the biblatex code and the File annotations, and all other fields do not work. Maybe this is related to #2829?

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
