### ISSUE TITLE
biblatex fields and the import function

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2822]
I work with BibLaTeX and I have JabRef set to support biblatex fields.  When bringing a bibliographical entry into JabRef through GVK or ISBN etc., the date and place of publication are inserted into the fields "year" and "address" instead of "date" and "location."  

There may be other mismatches of this type; I haven't checked systematically.  But these two are quite prominent, occurring in every entry.

Thanks!

JabRef version

JabRef-4.0.0-dev--snapshot--2017-05-03--master--a16e6123d.jar

running with Linux Mint 18.1, with file manager Nemo 3.2.2

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by tobiasdiez** [comment]
This is a special case of https://github.com/JabRef/jabref/issues/1283
