### ISSUE TITLE
JabRef does not export, either in Ubuntu or in Pclinux [solved]

### ISSUE THREAD

**Issue by DoctorSubtilis** [JabRef/jabref#2823]
JabRef version 3.8.1 on KUbuntu 17.04 and PcLinuxOs

Steps to reproduce:

1. File
2. Export in any format
3. does not export

No permission problem (nothing change changing folder where save).

Thank you

**Comment by koppor** [comment]
Can you try the latest dev version from https://builds.jabref.org/?

Am 06.05.2017 12:10 schrieb "DoctorSubtilis" <notifications@github.com>:

**Comment by DoctorSubtilis** [comment]
Solved: the problema was tha *name*: selecting a new name the export is OK. Before I used the same name of previous database, changing only the date, and so the export was not working.
Thank you
Just onother thing: how export as sql with the 3.8.1 ?

**Comment by Siedlerchr** [comment]
@DoctorSubtilis  SQL Export was dropped in Version 2.6 in favor of the new collaborative SQL Databse integration: http://help.jabref.org/en/SQLExport
