### ISSUE TITLE
Incorrect sorting of authors with multiple surnames in the author/editor column

### ISSUE THREAD

**Issue by bvdalen** [JabRef/jabref#2828]
JabRef version:
JabRef 4.0.0-dev--snapshot--2017-05-07--master--4832e5d86
Windows 7 6.1 amd64 
Java 1.8.0_92
With all options reset to default values.

**Steps to reproduce:**
1. Open the below BibLaTeX file.
2. Sort by the entry column "author".
3. Problem: item:2, with the name entered as "José María {Rodriguez Fernandez}" is apparently sorted in under F instead of under R (as item:1).

**Comment:**
I have not yet received confirmation whether the above format of the name of item:2 is supposed to be a valid alternative for "Rodriguez Fernandez, José María", but it used to work correctly in earlier versions (both for displaying the names in the author/editor column and for sorting them) and, since #2652 has been resolved, it again works correctly in displaying the name in the author/editor column in the current developer version.

**BibLaTeX file:**
% Encoding: UTF-8

@Article{Item:1,
  author    = {Rodriguez Fernandez, José María},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:2,
  author    = {José María {Rodriguez Fernandez}},
  title     = {L'arc du ciel},
  date      = {2016},
}

@Article{Item:3,
  author = {José Martinez},
  title  = {Jabref's Issues},
  date   = {2017},
}

@Comment{jabref-meta: databaseType:biblatex;}

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.
