### ISSUE TITLE
Run "Abbreviate journal names" in parallel

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2831]
JabRef 3.8.2
windows 10 10.0 amd64 
Java 1.8.0_131

As far as I can tell, the "Abbreviate journal names" function in JabRef is currently run serially. While this is fine for smaller databases, it can pose a serious performance problem when dealing with large (>10,000 entries) databases. I propose to run this function in parallel - this should speed up things quite a lot, I guess.

**Comment by lynyus** [comment]
Sounds like an good idea. Not having checked the code it should be easy to delegate this work to the JabrefExecutorService.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version thanks to a contribution by @Brainsucker92. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by Siedlerchr** [comment]
There is also a koppor issue related to that

**Comment by AEgit** [comment]
I can confirm that the "Abbreviate journal names (ISO)" is run in parallel on:

JabRef 4.2-dev--snapshot--2018-02-15--master--36e4f0e56
Windows 10 10.0 amd64 
Java 1.8.0_161

There appear to be some issues (?), though: Even when the abbreviation process is technically finished (i. e. all possible abbreviations have been carried out) as indicated by the status message, JabRef continues to use all the cores (at max. load) for quite some time afterwards. Eventually, JabRef will stop using all the cores and the CPU load drops again. Is this behaviour intended?

**Comment by Brainsucker92** [comment]
Well, I can confirm the abbreviation process is definitely running parallel. I tested abbreviating 30.000 entries  which takes about 90 seconds to process at nearly 100% load on my computer. After the abbreviation is done it drops back to normal load.
