### ISSUE TITLE
JabRef crashes in Debian 

### ISSUE THREAD

**Issue by omendezmorales** [JabRef/jabref#2832]
This is the context  when crashing:
Java Version: 1.7.0_121
Java Vendor: Oracle Corporation
Operating System: Linux (3.16.0-4-amd64)
Hardware Architecture: amd64
Window manager: GDM3

```
The rest of the verbose goes here:

The following error occurred while running JabRef:
java.lang.NoClassDefFoundError: com/jgoodies/common/internal/StringLocalizer at net.sf.jabref.oo.OpenOfficePanel.initPanel(OpenOfficePanel.java:385) at net.sf.jabref.oo.OpenOfficePanel.init(OpenOfficePanel.java:164) at net.sf.jabref.JabRefFrame.fillMenu(JabRefFrame.java:1401) at net.sf.jabref.JabRefFrame.initLayout(JabRefFrame.java:897) at net.sf.jabref.JabRefFrame.init(JabRefFrame.java:460) at net.sf.jabref.JabRefFrame. (JabRefFrame.java:429) at net.sf.jabref.JabRef.openWindow(JabRef.java:769) at net.sf.jabref.JabRef. (JabRef.java:201) at net.sf.jabref.JabRef.main(JabRef.java:84) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at net.sf.jabref.JabRefMain.main(Unknown Source) Caused by: java.lang.ClassNotFoundException: com.jgoodies.common.internal.StringLocalizer at java.net.URLClassLoader$1.run(URLClassLoader.java:359) at java.net.URLClassLoader$1.run(URLClassLoader.java:348) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:347) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ... 14 more
```

**Comment by Siedlerchr** [comment]
Hi,
would you please give some information about the JabRef version you are using?
Please be aware that all recent JabRef versions 3.x and 4.x (beta)[ require Java 8](http://help.jabref.org/en/Installation) which is probably the cause for the error.

**Comment by omendezmorales** [comment]
Hi Christoph,
 I see 2.10 (build 0)

Thanks,

Christoph wrote:

**Comment by koppor** [comment]
Does http://help.jabref.org/en/Installation help? 🕺

Am 10.05.2017 21:29 schrieb "Orlando Méndez" <notifications@github.com>:

**Comment by omendezmorales** [comment]
I've updated to java 1.8 as per the instructions above, 

> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
> 

however _Jabref_ still crashes :-( Any other suggestion? Thanks,

**Comment by Doc73** [comment]
I have no issues in my Debian Jessie amd64 machine, but I use `openjdk-8` and `openjfx` from `jessie-backports`:
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by omendezmorales** [comment]
OK, I've decided to use the latest release instead of my old version, and seems to be working fine. I'll close the issue now. Thanks for the feedback.

**Comment by koppor** [comment]
We are also working on providing a snapcraft image: https://github.com/JabRef/jabref/issues/3121
