### ISSUE TITLE
Groups panel: Unused space (and possible solution)

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2833]
JabRef 4.0.0-dev--snapshot--2017-05-09--master--78185153b
Windows 10 10.0 amd64 
Java 1.8.0_131

The groups panel currently requires quite a lot of space, if the complete group names are to be shown, especially in highly nested group structures. If there's not enough space, the group names will be abbreviated or - in the worst case - not shown. I noticed that there's quite a lof of unused space between the group names and the figure indicating the number of entries in a group. Maybe this space needs to be reduced a bit (?). See attached file for comparison:
![groups_panel](https://cloud.githubusercontent.com/assets/12767489/25992672/3b266bc8-36ff-11e7-8ec6-42f83a3c1218.png)

**Comment by lynyus** [comment]
related? https://github.com/JabRef/jabref/issues/2803

**Comment by AEgit** [comment]
Hmmm, it's not the same problem, as pixels are not missing in the UI. But, indeed, you could see it as being related to this UI design issue.

**Comment by Siedlerchr** [comment]
It would be nice if you could check with this tool the css styles: http://fxexperience.com/scenic-view/
This could give us some insights where the space is comingfrom

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by AEgit** [comment]
I can confirm that this has been fixed in:
JabRef 4.0.0-dev--snapshot--2017-05-14--master--d6b6235a4

Thank you very much!
