### ISSUE TITLE
JabRef 4.0.0-beta needing way more ressources than v.3.8.2

### ISSUE THREAD

**Issue by andipabst** [JabRef/jabref#2837]
JabRef version 4.0.0-beta on Windows 7 (x86_64)

When using the beta version JabRefs RAM usage is at roughly over 1.000.000K and the CPU usage minimum 25% when it is idle.
For scale: Using the old (v. 3.8.2) version the CPU usage is between 0 and 1% and the RAM is at about 180.000K.

The problem is reproducable and occurs everytime I start JabRef.

**Comment by lynyus** [comment]
Thanks for the report @andipabst.

Can you provide us some more specifics?  How many databases did you open? How many entries are in your BibDatabase(s)? Does the memory spike fast after opening it or does it increase with time like reported in https://github.com/JabRef/jabref/issues/2533? Are there any special operations (like performing a search or sorting the table) that increase the memory dramatically?

**Comment by andipabst** [comment]
I opened just one database with about 50 entries. 

The memory spikes up before I even can see the GUI (I just see the process in the Windows Taskmanager). During the start the Task Manager also reports a CPU usage of about 80% for JabRef.

I just checked: Performing a search increases the memory for roughly the same amount (10.000K) in both versions of JabRef. When I stop typing for a while the memory drops again by that amount.

If I can provide with any other information just ask, I'm willing to help :)

**Comment by lenhard** [comment]
That is weird. On my Win7 with the current development snapshot, I have idle CPU consumption of ~5%, but with several other applications opened including an IDE, and about 1 GB of RAM consumption by JabRef. But I have 4 databases open, one of them with more than 6500 entries. 

So I am afraid that I can not really reproduce your performance problem, which might indicate that it comes from a system configuration issue. 

What is your java runtime? Could you try out the current development master of JabRef available at http://builds.jabref.org/master/ ?

**Comment by lenhard** [comment]
@andipabst Any news here with the newest dev version?

**Comment by andipabst** [comment]
Sorry, I could not test it until today.
I tired the current dev master snapshot as you suggested and the performance now is quite equal to the old version, just a slightly higher amount of RAM.

So the problem seems to be fixed?

**Comment by lenhard** [comment]
Thanks for testing! There have been quite a few changes and removals of old code in the meantime, in particular regarding groups. Maybe this gave JabRef a little boost.

I'll close this for now, but we'll keep an eye on performance issues.

**Comment by koppor** [comment]
What I stumbled upon while searching for various commons lang replacements: [Eclipse Collections](http://www.eclipse.org/collections/).

![grafik](https://user-images.githubusercontent.com/1366654/28246188-8d1ff41a-6a14-11e7-9f2f-bd6b93623c7b.png)

![grafik](https://user-images.githubusercontent.com/1366654/28246190-9c54b434-6a14-11e7-95a8-6eb2e6edf769.png)


![grafik](https://user-images.githubusercontent.com/1366654/28246189-96a460e8-6a14-11e7-862a-606c9edc96c3.png)


Maybe, we can reduce our memory by using Eclipse Collections?
