### ISSUE TITLE
4.0.0-Beta not showing PDF File Annotations

### ISSUE THREAD

**Issue by kafran** [JabRef/jabref#2839]
Text Highligh and Comments created with FoxitReader for Linux and Evince (with copy and past of the text inside the pop-up note, this is how it works on Docear) do not appear on File annotations tab.

**Comment by lynyus** [comment]
Thanks for reporting this issue @kafran. We need some more information to resolve the issue.

Have you checked the event log (Help -> View event log) for messages related to this problem?
If there are not messages the easiest would be to send us a PDF file where the issue occurs.

**Comment by kafran** [comment]
@lynyus Sure. https://gist.github.com/kafran/c6dc9ab84bb3a25b24b908b42d406d67

**Comment by lynyus** [comment]
Thanks, that helps a lot. Will fix this soon!

**Comment by kafran** [comment]
Thank you. @lynyus, also... is this possible [#2545](https://github.com/JabRef/jabref/pull/2545#issuecomment-301242416) Should I open a feature request?

**Comment by lynyus** [comment]
Hi @kafran, the reported Issue should be fixed in the latest development branch. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by kafran** [comment]
Hey @lynyus, this is really getting good. I can see some annotations now. But, others are getting this error: https://gist.github.com/kafran/79903f6961a6e0757c13824ad5812662

Do you think this is JabRef or the PDF Reader (Foxit for Linux) I'm using? Some PDFs' who annotations works was annotated using the same software.

**Comment by lynyus** [comment]
The problem lies in the the library we are using to extract these annotations.
I will investigate this "soon". Stay tuned. (:

**Comment by kafran** [comment]
This new feature is getting awesome. Congratulations. =)
I'm not a developer but I use JabRef for helping me with my research at university. This new feature came in a good time when I was about to change my research workflow from Zotero/Docear/etc. to a more simple approach with BibLaTex + JabRef and TiddlyWiki for note taking. By the way, if someone else is looking for another way to organize a Master/Doctor Tesis research here is the tip: http://tesis.tiddlyspot.com/

This new feature gonna be handy to extract annotation and place on TiddlyWiki. And with the page information I can even save a link like this "file:///file.pdf#page=x" and open the file directly on the note on Firefox =D.

Thank you for this great work guys.

**Comment by lynyus** [comment]
Hi @kafran, I had a look and created a fix for the bug you reported before https://github.com/JabRef/jabref/issues/2839#issuecomment-302058227.
Can you please check if it works for you? You can find a fixed version at http://builds.jabref.org/foxit-annotations/ .

**Comment by kafran** [comment]
@lynyus this seems to be fixed now =). I can see all annotation without errors. Although there is a minor improvement: in some PDFs there is an annotation called "Citation link" that is irrelevant since it has no "Content" or "Marking". This seems to happen on Reference page with some references that includes a link. I observed this on "Emerald Insight's" PDFs, with references they had published they seem to create a link in the PDF (Something like a crossref). This is just an improvement. Since some PDF has a lot of Crossref, this is a lot of useless information in File Annotation tab.

Since I'm not a good english writer, here you have an image: https://www.dropbox.com/s/51k461j53h0gqm4/Screenshot_2017-06-01_04-41-13.png

**Comment by lynyus** [comment]
I also fixed that now in the pull request #2878. After all I removed all link annotation type from the supported annotations. 
Can you check the result at http://builds.jabref.org/foxit-annotations and tell us your thoughts?

**Comment by kafran** [comment]
@lynyus Its everything working great. Thank you. =)
