### ISSUE TITLE
Cleanup entries not fully working

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#284]
When running Cleanup entries, I get the error:

Nov 02, 2015 10:48:07 PM net.sf.jabref.gui.BasePanel runCommand
SEVERE: runCommand error: null

Some of the cleanup actions are performed (not sure if all are), but the status bar is not updated with the "XX entries needed a cleanup" (or whatever it says), so something breaks before that.

Guess: page number change?

**Comment by oscargus** [comment]
And instead of guessing: I unselected the page number clean up and then everything works.

**Comment by matthiasgeiger** [comment]
@stefan-kolb your job ;-)

@oscargus I don't know how much entries your testing database has - but do you have an idea which entries might cause the trouble and could be provide those as test cases?
