### ISSUE TITLE
Bibliographic fields missing

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#2843]
JabRef version snapshot 15 may on Debian 8 Jessie AMD64

Steps to reproduce:

1. Launch JabRef
2. Select and view a bibliographic item
3. Fields are blanck
4. Go to source editor --> all fields are filled
5. Returns to the main board --> all fields are regularly filled

I attach screenshot:
![schermata del 2017-05-16 08-23-08](https://cloud.githubusercontent.com/assets/1306260/26092384/f29506ac-3a10-11e7-96b0-cdab3690bd27.png)

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by Doc73** [comment]
Sorry, but it doesn't work. All fields are not visible:

![schermata del 2017-05-18 16-51-18](https://cloud.githubusercontent.com/assets/1306260/26208512/96cd42cc-3bea-11e7-8118-a7e6249a168c.png)

I used JabRef-4.0.0-dev--snapshot--2017-05-18--master--018173ebd.jar

**Comment by tobiasdiez** [comment]
Thanks for the feedback. I don't have a Linux system at hand to test this right now. Can someone of the @JabRef/developers reproduce these problems (and fix them 😸 )

**Comment by ninfito** [comment]
I have the same issue on OpenSuse 13.2 (jre1.8.0_131), JabRef-4.0.0-dev--snapshot--2017-05-23--master--6db383443.jar
#2851

**Comment by lenhard** [comment]
@Doc73 @ninfito We believe that we have fixed this issue. Can you please try out the fix here: http://builds.jabref.org/fixEntryEditor/ and report if it works for you?

**Comment by Doc73** [comment]
Thanks! It's working!

There is a small delay between the click on the bibliographic item and the appearance of entries in the editor, but it works very well.

**Comment by tobiasdiez** [comment]
Perfect! Thanks for the feedback. The fixed version is now merged into master and can be downloaded as usual from http://builds.jabref.org/master/.
