### ISSUE TITLE
JabRef-Citavi integration plans and licensing issues

### ISSUE THREAD

**Issue by baimafeima** [JabRef/jabref#2849]
I have read (https://blog.jabref.org/) that JabRef has acquired Citavi. 
1. What plans do you have in regards to the future of the two programs? Will they continue to exist as two separate programs or will you eventually have their functions merged?
2. Will JabRef remain open source and will you eventually release Citavi with an open source license?
3. As I use a Linux-based operating system (Solus), I cannot use Citavi for my research work. Do you have any plans for a new cross-platform version of Citavi?

**Comment by Siedlerchr** [comment]
Hello @baimafeima 
thanks for your interest in JabRef.
if you look closely again at the date of the news, you may see that it was posted on **April 1st** - as an April fool's joke. 😏  
JabRef and Citavi are in no way affiliated. We are just a small team of enthusiastic OpenSource developers who rely on donations and want to constantly improve JabRef in their free time.

Nonetheless, we welcome any contributions to JabRef.  A list of possible things you can do to improve the User Experience with JabRef are listed here: 
http://help.jabref.org/en/FAQcontributing

**Comment by lenhard** [comment]
I think it is safe to close this one.

**Comment by koppor** [comment]
Solus packaging has been reported to work at https://discourse.jabref.org/t/unexpected-exception-java-nio-file-filesystemnotfoundexception-during-startup/4420/20?u=koppor
