### ISSUE TITLE
Clicking on links in About dialog

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#285]
Two in one, but probably related (and might be updated with more information tomorrow).

When clicking on a link the following happens (except that it opens in the web browser as expected):

On my Linux computer at the office (started using `./gradlew run`): a list with all html-files are shown in the About-dialog (like a directory listing)

On my Windows laptop (started from Eclipse, no developers, authors, or licenseInformation shown): error message such as
    Nov 02, 2015 10:54:12 PM net.sf.jabref.gui.help.HelpContent setPage
    SEVERE: Could not find html-help for file 'gpl-2.0'.
    Nov 02, 2015 10:54:45 PM net.sf.jabref.gui.help.HelpContent setPage
    SEVERE: Could not find html-help for file 'external-libraries.txt'.
are shown in the console, but the about-page is OK.

**Comment by matthiasgeiger** [comment]
Confirmed here.

Should be introduced by c3528708b4f148441bc6b4ef1f5bd8b31ca6a023 which opens external browser to show the help file. 
This works fine, but after opening the URL JabRef still tries to open local files which do not exist.

**Comment by koppor** [comment]
I know. Currently no time to investigate 🙈 

----- Ursprüngliche Nachricht -----
Von: "Matthias Geiger" <notifications@github.com>
Gesendet: ‎06.‎11.‎2015 14:54
An: "JabRef/jabref" <jabref@noreply.github.com>
Betreff: Re: [jabref] Clicking on links in About dialog (#285)

Confirmed here.
Should be introduced by c352870 which opens external browser to show the help file. 
This works fine, but after opening the URL JabRef still tries to open local files which do not exist.
