### ISSUE TITLE
Key binding DELETE tries to delete whole entry when file is selected in general tab

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2853]
![image](https://cloud.githubusercontent.com/assets/2141507/26243464/3e901a06-3c8c-11e7-98a9-17fa8b204aeb.png)

1. select file in general tab
2. press DELETE key

RESULT: JabRef wants to delete whole entry
EXPECTED: File assignment is removed

**Comment by tobiasdiez** [comment]
This is the same underlying problem as https://github.com/JabRef/jabref/issues/2855.
