### ISSUE TITLE
Command + X does not work properly

### ISSUE THREAD

**Issue by iTao8** [JabRef/jabref#2855]
JabRef 4.0.0-dev--snapshot--2017-05-18--master--018173ebd
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

Steps to reproduce:
1. select an entry
2. double click the selected entry
3. select the title
4. Command +X
5. the selected entry is deleted

**Comment by iTao8** [comment]
Similar problem #2842

**Comment by Siedlerchr** [comment]
I found a solution and created a PR.

**Comment by iTao8** [comment]
I think it has a similar problem with #2923, all are about the keybindings. For me, the Command + X has been fixed in 
JabRef 4.0.0-dev--snapshot--2017-06-18--master--26d1e2e07
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

**Comment by Siedlerchr** [comment]
Thanks for your report. With the linked PR #2937  I also fixed the problem with doing CTRL+C inside the entry editor,e.g. inside the title field would always copy the whole entry bibtex code to the clipboard.
Could you please test that, too?

**Comment by iTao8** [comment]
I test Command + C, Command + X, Command + Z, these keybindings work well in 
JabRef 4.0.0-dev--snapshot--2017-06-22--master--bee062c6a
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

**Comment by tobiasdiez** [comment]
Thanks for the quick feedback!

**Comment by iTao8** [comment]
This problem appears again in the current snapshot:

JabRef 4.0.0-dev--snapshot--2017-07-06--master--edd3f7cc1
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

**Comment by Siedlerchr** [comment]
Hi, you have to reset the keybindings first (or if you use custom ones, you have to modify the preferences and add a plus sign between each modifier.  We ware working on a preference migraiton

**Comment by iTao8** [comment]
This works well on Windows 7, but not on mac

JabRef 4.0.0-dev--snapshot--2017-07-10--master--e80f450ee
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

**Comment by Siedlerchr** [comment]
Hi,
this should now be fixed again in the latest snapshot f23db0ee1a0130d7b835bb321acf5bf483cc7a0c. 
The snapshot should be ready in a couple of minutes.
