### ISSUE TITLE
Import from web search into group

### ISSUE THREAD

**Issue by hudcap** [JabRef/jabref#2858]
JabRef version 4.0.0-beta on Windows 10

Steps to reproduce:

1. Groups settings -> "Automatically assign new entry to selected groups" is checked
2. Select a group
3. Perform a search from the "Web search" box and import an entry

The new entry is imported, but is not assigned to the selected group.

**Comment by AEgit** [comment]
Cannot confirm for:
JabRef 4.0.0-dev--snapshot--2017-05-20--master--01e854829
Windows 10 10.0 amd64 
Java 1.8.0_131

I've performed a "Google Scholar" search in the "Web search" box. Are you sure, that the new entry is not assigned to the selected group? Have you tried to select another group and then select the group, to which the article was supposed to be assigned to? If not and if that is a workaround for your problem, this issue is just a duplicate of:
https://github.com/JabRef/jabref/issues/1903

**Comment by hudcap** [comment]
Yes, I just tried again (Google Scholar) and checked the entry -- it's not assigned to any group.
Selecting another group and going back doesn't change anything.
I'm not on the latest dev--snapshot, but I'm not quite sure how to compile that for Windows. Anytime I try doing something like that, I get error after error...

**Comment by AEgit** [comment]
Ok, let's do this step-by-step.

1) Select the group to which you want to assign your article
2) Try searching the following using "Google Scholar" within the "Web search" box (without quotation marks):
"Cancer progression by reprogrammed BCAA metabolism in myeloid leukaemia"

This should give you one article to import (http://www.nature.com/nature/journal/vaop/ncurrent/full/nature22314.html).

"Fetch" --> "Ok"
3) The article has been imported. Now it looks like, as if the article had not been assigned to the group you initially selected.
4) Select any other group in the groups panel by clicking onto it. Then select your original group. The article should now be shown as assigned to that group. If we check the Bibtex code of the item, it should also show, that it is assigned to that group.

These 4 steps definitely work for me with the following setup:
JabRef 4.0.0-dev--snapshot--2017-05-20--master--01e854829
Windows 10 10.0 amd64 
Java 1.8.0_131

You can download the latest snapshot from here (you don't need to compile it):
https://builds.jabref.org/master/

**Comment by lenhard** [comment]
@AEgit Thank you many times for your help in debugging here!

**Comment by AEgit** [comment]
@lenhard : I thought, as I can't help you guys with the Java coding, I might be able to help with these kind of things.

**Comment by hudcap** [comment]
Whoops - didn't realize they were compiled - thanks!
Apparently it's fixed in the latest snapshot, because it works now.
I was unable to try with Google Scholar because I hit their limit (captcha in browser didn't help).
It worked with Springer, whereas it didn't work before.
@AEgit Thanks for the assist!!

**Comment by AEgit** [comment]
You are welcome ;)
