### ISSUE TITLE
MSBibEntry office xml import and (re-)export of yearAccessed monthAccessed dayAccessed

### ISSUE THREAD

**Issue by gnu9** [JabRef/jabref#2859]
Bug report: After import of fields yearAccessed monthAccessed dayAccessed from an office xml file, they are stored in format mm dd, yy in the field msbib-accessed (or mm dd, yyyy).

Re-export fails as it expects format \d{2}\s*[.,-/]\s*\d{2}\s*[.,-/]\s*\d{2,4} but \d{2} \d{2}, \d{2,4} doesn't match.

Possible fixes: change DATE_PATTERN s.t. month and day may be separated by \s*[ .,-/]
OR line 168 of MSBibEntry.java to `sbDateAccesed.append(', ');` (Typo "Accesed" present in source code).

Additionally, shouldn't the biblatex field "urldate" be exported to the fields yearAccessed monthAccessed dayAccessed in an office xml file? And vice versa for import? In that case importing into msbib-accessed should be replaced by importing into urldate (except for possible cases where urldate wouldn't be appropriate).

In case that urldate doesn't correspond to yearAccessed monthAccessed dayAccessed in some or all cases, importing into msbib-accessed could be changed to yyyy-mm-dd (yy-mm-dd) to make it coherent with biblatex date format. Parse msbib-accessed as year month date if pattern \d{2,4}\s*-\s*\d{2}\s*-\s*\d{2} is matched, if not try DATE_PATTERN \d{2}\s*[ .,-/]\s*\d{2}\s*[.,-/]\s*\d{2,4} for month year day.

**Comment by lenhard** [comment]
@gnu9 Thanks for your report!

@Siedlerchr : You have worked on this, if I recall it correctly. Can you comment here?

**Comment by Siedlerchr** [comment]
Okay, I looked into the code and I think I can understand the issue with the regex. I would propse to store the date from import into yyyy-mm-ddd (ISO8601).  I will try to get rid of the regex, as we have some methods for parsing dates in several formats. But as I am currently busy with another project it could take some time I can get to work on this

**Comment by Siedlerchr** [comment]
The issue with the date exporting should be fixed now.  Would you please create a new issue for the sugesestion about the urldate?`Makes it easier to keep track of it

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
