### ISSUE TITLE
Event log not available

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2863]
JabRef_windows-x64_4_0_0-dev--snapshot--2017-05-23--master--6db383443

Steps to reproduce:

1. Open a data base
2. Goto Help-> View event log
 
Nothing shows up, before at least the files opened were shown.

This is serious since it does hamper the user feedback

**Comment by tobiasdiez** [comment]
Mhh...I can't reproduce this issue. Can you please try to start JabRef from the command line as described here http://help.jabref.org/en/CommandLine and see if there is some output (errors or at least "Opening: file to database")

**Comment by Siedlerchr** [comment]
I can't reproduce this either, even under Xubuntu it works fine.

It could be a side effect of  #2851

**Comment by bernhard-kleine** [comment]
Myself, i cannont reproduce it.
