### ISSUE TITLE
Groups panel does not scroll when group is assigned to another group as subgroup

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2869]
JabRef 4.0.0-dev--snapshot--2017-05-25--master--4c87dde9c
Windows 10 10.0 amd64 
Java 1.8.0_131

It is now possible to assign a group (let's call it the "child group") via drag'n'drop to another group (= "parent group") as subgroup: https://github.com/JabRef/jabref/issues/2785

If the parent group is not visible in the groups panel (as there are too many groups to be displayed), it is not possible to drag'n'drop the child group directly onto the parent group. The groups panel will not start scrolling automatically when you hover over the border of the groups panel with the selected child group.

As a workaround you can just drag'n'drop the child to the next group that is nearest to the chosen parent group and then continue doing this until you have reached the actual parent group.

**Comment by tobiasdiez** [comment]
Pointers to code that should be helpful for this task: https://bitbucket.org/gluon-oss/scenebuilder/src/ef68e38ec2422a66f71f3922b5aa83a5ece1aa84/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/hierarchy/treeview/HierarchyTreeCell.java?at=default&fileviewer=file-view-default https://bitbucket.org/gluon-oss/scenebuilder/src/ef68e38ec2422a66f71f3922b5aa83a5ece1aa84/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/hierarchy/HierarchyDNDController.java?at=default&fileviewer=file-view-default

**Comment by AEgit** [comment]
This issue persists in:

JabRef 5.0-dev--snapshot--2018-10-28--master--05047f32a
Windows 10 10.0 amd64 
Java 1.8.0_191

Note, that this can be quite troublesome, if you have a large database with many groups (it is obviously less of a problem with only a few groups).

**Comment by AEgit** [comment]
JabRef 5.3--2021-01-04--10180ed
Windows 10 10.0 amd64 
Java 14.0.2

The issue persists in the latest development version of JabRef.

**Comment by AEgit** [comment]
JabRef 5.10--2023-02-22--76b221d
Windows 10 10.0 amd64 
Java 19.0.2 
JavaFX 19+11

The issue persists in the current development version of JabRef.

**Comment by AEgit** [comment]
JabRef 5.10--2023-04-05--643319b
Windows 10 10.0 amd64 
Java 19.0.2 
JavaFX 20+19

As far as I can tell, this has been fixed in the current dev version. Well done!
There are a few quirks, which may or may not be related to the fix:
1) The scrolling speed is really high. On one hand this is a nice feature for large databases with thousands of groups when you want the child group to be added to a parent group that is very distant in the group table view. On the other hand, it makes it nearly impossible to precisely add a child group to a parent group, since it is very likely that you will whoosh past the parent group due to the scrolling speed. It would be nice if the user could control the scrolling speed by moving the mouse more or less into the direction he wants to put the child group.
2) If you add an article to a group that is far distant (using the new scrolling groups feature) the group table view gets `confused' sometimes and either scrolls to the bottom of the groups panel (after the article has been added) or starts scrolling from top to bottom non-stop. Sometimes it appears to be necessary to have a search term (e.g. a bibtex key) in the search form to trigger this behaviour (at least, that is what it appears to me).

**Comment by AEgit** [comment]
@Siedlerchr Given the above mentioned quirks (https://github.com/JabRef/jabref/issues/2869#issuecomment-1497179500), should we keep this issue open or should I open new tickets?

**Comment by ThiloteE** [comment]
i think it would make sense to open a new follow-up issue and link to your comment there.

**Comment by AEgit** [comment]
> i think it would make sense to open a new follow-up issue and link to your comment there.

Done: https://github.com/JabRef/jabref/issues/9754#issue-1661295265
