### ISSUE TITLE
Some optional fields have more height than others on lowering the tab height

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2872]
DOI, Eprint and Journal Subtitles stay at a greater size 

![grafik](https://cloud.githubusercontent.com/assets/320228/26531224/ebce341e-43e4-11e7-9e93-1690e997388e.png)

```
@Article{Testa,
  author         = {Sam and jason},
  title          = {Test},
  journaltitle   = {Test},
  year           = {2012},
  date           = {2016},
  month          = {4},
  msbib-accessed = {2015-12-12},
}
```

**Comment by Xiaochi-Li** [comment]
Trying to solve this bug. But I don't see as many optional fields for Article entries as your screen shot. I tried to create other entry types and found none of them has such much optional field. I'm relatively new to Github. Is there anything I missed? Here is what the optional fields look on my computer.
<img width="825" alt="screen shot 2017-05-31 at 11 24 46 pm" src="https://cloud.githubusercontent.com/assets/16205579/26633935/5c23833e-4658-11e7-81ca-da46ee1036ac.png">

**Comment by Siedlerchr** [comment]
Thanks for digging into this, you have to use the biblatex mode of the library  (either create a new one in biblatex mode or File -> Change to biblatex mode)

Some of the fields were already moved to a second tab,  but some fields still have a greater size

**Comment by tobiasdiez** [comment]
I made some changes to the layout in order to fix https://github.com/JabRef/jabref/issues/2871. Maybe these changes also fix this issue. Can you please try it out. Thanks.

Moreover, I just noticed that you have way more fields than I have. It appears that for me the second column is moved to the "Optional Fields 2" tab. Did you modified the entry types by hand?

**Comment by Siedlerchr** [comment]
Yeah, they were still associated with EntryType Optional. I reset this to default and now it looks better;
![grafik](https://user-images.githubusercontent.com/320228/26895450-f23ce090-4bc1-11e7-8ff4-c2e532128994.png)

Deprecated fields looks slightly better:
I think it's not possible to center the label in the middle while keeping the textboxes at the same position?
I'm okay with that.
![grafik](https://user-images.githubusercontent.com/320228/26895493-0eecf22a-4bc2-11e7-80d1-ea0bedc64898.png)
