### ISSUE TITLE
tab title grey or highlighted

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2886]
This could be a feature not a bug, I don't know :-)

JabRef version
JabRef 4.0.0-dev--snapshot--2017-05-31--master--c9566c2a9
Linux 4.10.0-21-generic amd64 
Java 1.8.0_131

Steps to reproduce:
1. open a couple of libraries.
2. the tabs for the currently selected library is greyed, while the non-selected tabs are in normal/bold font.

To me, that's counter-intuitive.  In a hurry, I keep thinking I'm in the wrong database.

![screenshot from 2017-06-05 08-18-16](https://cloud.githubusercontent.com/assets/762246/26787532/91e83358-49c7-11e7-959f-2c7cee3d6159.png)

**Comment by lenhard** [comment]
That's arguably a bug, since the display is not in a wrong state. The highlighting is just not as good as it could be. I'll re-categorize this as an enhancement.

**Comment by stefan-kolb** [comment]
See maintable-beta implementation.
