### ISSUE TITLE
popups are placed nearly offscreen

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2887]
Often, when I open a UI element that creates a popup window, that window is placed nearly offscreen.  See the screenshot for an example.

This is on JabRef 4.0.0-dev
![jr4popupsoffscreen](https://cloud.githubusercontent.com/assets/3851891/26787957/f93d469e-4a0b-11e7-81fc-7b5f89783f98.png)

**Comment by Siedlerchr** [comment]
Do you use multiple monitors?  Do you use Windows or linux?
When I try to reproduce this (windows, single monitor) it is always placed in the center of the screen, so I guess it has some problems with extended monitors

**Comment by notuntoward** [comment]
This was on Windows 10, and just the single screen of my surface pro 4.  Since there are other problems with high resolution screens, could this be one too?

**Comment by notuntoward** [comment]
I don't see this problem on more recent builds so I'll close this myself.
