### ISSUE TITLE
Strings in edit fields not updating to match the source fields

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2888]
JabRef version
JabRef 4.0.0-dev--snapshot--2017-05-31--master--c9566c2a9
Linux 4.10.0-21-generic amd64 
Java 1.8.0_131

Steps to reproduce:

1. I edit a field, e.g., shorthand (which I've added to the "Required Fields" tab)
2. I go to the "{} biblatex source" tab and edit the shorthand field
3. Returning to the "Required Fields" tab, the shorthand field is not updated.

![screenshot from 2017-06-05 09-18-42](https://cloud.githubusercontent.com/assets/762246/26790173/093a16d0-49d0-11e7-826c-eb063e33f16e.png)

![screenshot from 2017-06-05 09-18-55](https://cloud.githubusercontent.com/assets/762246/26790182/13922f14-49d0-11e7-8dd0-6cbcf2d54526.png)

**Comment by Siedlerchr** [comment]
When you change to another entry and then change back, the update is applied and the field content is visible

**Comment by Siedlerchr** [comment]
I think to solve this, wee need a Binding between codeArea.textProperty() and entry.toString() or a field which represents the whole BibEntry as String.

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/2946

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by wujastyk** [comment]
My brief tests are successful.  Thanks for fixing #2888!

​
--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
​,​

Singhmar Chair in Classical Indian Society and Polity
​,​

Department of History and Classics <http://historyandclassics.ualberta.ca/>
​,​
University of Alberta, Canada
​.​

South Asia at the U of A:

​sas.ualberta.ca​
​​

**Comment by wujastyk** [comment]
Sorry, this story isn't over after all.

Edits to "biblatex source" are now correctly displayed in "required fields".  But not vice-versa.  Edits to "required fields" are not updated in "biblatex source."

Dominik

**Comment by lenhard** [comment]
@wujastyk We've attempted another fix and source field should now also be updated. Could you please try out the newest development snapshot and report back if it works?

**Comment by wujastyk** [comment]
Seems good, after simple tests.  Thank you!!!

**Comment by wujastyk** [comment]
Sorry to say, but further work today shows that this problem persists.

I've been working with this record:

> @article{10.2307/40849180,
>  ISSN = {09353518, 21968071},
>  URL = {http://www.jstor.org/stable/40849180},
>  author = {Gerd Carling},
>  journal = {Historische Sprachforschung / Historical Linguistics},
>  number = {1},
>  pages = {75-95},
>  publisher = {Vandenhoeck \& Ruprecht (GmbH \& Co. KG)},
>  title = {New look at the Tocharian B medical manuscript IOL Toch 306 (Stein Ch.00316. a2) of the British Library - Oriental and India Office Collections},
>  volume = {116},
>  date = {2003}
> }

In the "Required fields" tab I change the title to

> New Look at the {Tocharian B} Medical Manuscript {IOL Toch 306 (Stein Ch.00316. a2)} of the {British Library} - {Oriental and India Office} Collections

and that change isn't saved or reflected in "biblatex source".

JabRef 4.0.0-dev--snapshot--2017-07-18--master--7d31fa28c
Linux 4.8.0-58-generic amd64 
Java 1.8.0_131

**Comment by lenhard** [comment]
@wujastyk That's interesting, because the dev-snapshot you reported (7d31fa28c) is the one directly *before* my fix with regards to the source panel was merged. In that the version, the bug actually shouldn't have been fixed (yet). Could you try again with a new version from http://builds.jabref.org/master/ ?

**Comment by wujastyk** [comment]
Oh!  I bungled my versions somehow.  I thought I had everything straight,
but no.    I've reinstalled the latest build and everything is fine.

My mistake, and many apologies for a false alarm!

Dominik
​
