### ISSUE TITLE
Some menu & message items lack translation keys

### ISSUE THREAD

**Issue by kojiyokota** [JabRef/jabref#289]
In l10n property files in HEAD, some translation keys are missing. On starting JabRef, we have following stderr (thus, we may have more which not appear on stderr):

Warning: could not get menu item translation for "Insert selected citations into %d" for locale ja
Warning: could not get menu item translation for "Groups" for locale ja
Warning: could not get message translation for "Check integrity" for locale ja
Warning: could not get message translation for "ADS from ADS-DOI" for locale ja
Warning: could not get message translation for "Save fields sorted in alphabetic order (as in versions 2.10+)" for locale ja
Warning: could not get message translation for "Save fields in unsorted order (as until version 2.9.2)" for locale ja
Warning: could not get message translation for "Save fields in user-defined order" for locale ja
Warning: could not get message translation for "HTML to LaTeX" for locale ja
Warning: could not get message translation for "Unicode to LaTeX" for locale ja

**Comment by koppor** [comment]
Regarding the `2.9.2` and `2.10+` entries: Depends on #116. We will check the others.

**Comment by oscargus** [comment]
"Insert selected citations into %d", "HTML to LaTeX" and "Unicode to LaTeX" I have added, and I have definitely not done anything related to the translations (as I didn't understand how it worked at that time).

However, with the rather massive remake of the translations in #301 it may make sense to wait a bit and then introduce all new strings in one go.

**Comment by matthiasgeiger** [comment]
Fixed with #390.
