### ISSUE TITLE
DBLP fetcher negative operators do no longer work (server side issue)

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2890]
> Update May 7, 2017: Please note that we had to disable the phrase search operator (.) and the boolean not operator (-) due to technical problems. For the time being, phrase search queries will yield regular prefix search result, and search terms preceded by a minus will be interpreted as regular (positive) search terms.

http://dblp.uni-trier.de/search

**Comment by lynyus** [comment]
fixed in https://github.com/JabRef/jabref/pull/2891
