### ISSUE TITLE
Changing the entry when in Editor the panel should be maintained and not falling back on Required fields

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2896]
JabRef_windows-x64_4_0_0-dev--snapshot--2017-06-08--master--11f2b0080
 
When in the entry editor and in another panel than Requitred Fields and you change the entry then you are brought to Required Fields and the program does not stay in the same panel as before. This is counterproductive since you want the look at e.g. abstracts of different entries.

(Maybe a doubled issue since I remember having seen it before)

Steps to reproduce:

1. double click an entry
2. go to e.g. General
3. change the issue by clicking on the ^ in the left border of the editor window
4. you are in the Required Fields of the previous entry, not in General

**Comment by wujastyk** [comment]
Looking forward to this fix!  I very often work with the "biblatex source" window, and move between entries, laundering the data.  Having the system jump to "required fields" every time is a pain.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by wujastyk** [comment]
Yes, it works for me.  Thank you!
