### ISSUE TITLE
Content selectors in 4.0

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#2897]
In the current dev version, the content selectors are broken. This issue is just to remind ourselves that they have to be functional before we release 4.0. @tobiasdiez has this in mind, but judging from my own forgetfulness, I'd rather have an issue that tracks this ;-)

**Comment by koppor** [comment]
Documentation of that feature at http://help.jabref.org/en/ContentSelector

**Comment by lenhard** [comment]
I'll reopen this issue, but just to indicate that we have to adjust the documentation for content selectors that @koppor has linked above.

**Comment by lenhard** [comment]
And since it's so dead simple, I've done that just now. The updated documentation should be online in a few minutes.
