### ISSUE TITLE
SourceForge references

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#290]
In PR #286 I have replaced most references to sourceforge.net, but the following would need a bit more work (from someone else):

In ManageJournalsPanel.java, there is a default link to a journal abbreviation list:
`http://jabref.sf.net/journals/journal_abbreviations_general.txt`

I guess that in the long run, this file is better moved to GitHub? I can of course change the source, but do not know enough about GitHub (nor have enough access rights) to be able to place the file somewhere sensible.

**Comment by matthiasgeiger** [comment]
http://jabref.sourceforge.net/journals/journal_abbreviations_general.txt is currently a 404.

My proposal would be: Remove the hint to the list "maintained" by us :see_no_evil: and the default URL.

**Comment by koppor** [comment]
For the record: The new URL of the list is https://raw.githubusercontent.com/JabRef/reference-abbreviations/master/journals/journal_abbreviations_general.txt
