### ISSUE TITLE
TAB-Navigation instead of Shift-Tab

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2902]
Currently you have to use SHIFT+TAB to move from one field to another in the entry editor.

https://stackoverflow.com/questions/12860478/tab-key-navigation-in-javafx-textarea

**Comment by lynyus** [comment]
(: @matthiasgeiger

**Comment by Doc73** [comment]
Attention!
SHIFT+TAB usually moves the cursor to the _previous_ field; on the contrary, TAB moves to the _following_ tab.

Therefore, I suggest to keep unmodified the behaviour of SHIFT+TAB, but to add the usual behavior of the TAB button.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by Doc73** [comment]
Checked right now v. 4.0 beta2 and working!

Many thanks!
