### ISSUE TITLE
Author / editor field shows part of string only

### ISSUE THREAD

**Issue by carbonmetrics** [JabRef/jabref#2909]
The author/editor field in the main view shows only part of the total name, right aligned. 
So instead of "Parliament of Kenya", you see only "of Kenya", see screenshot.

![image](https://user-images.githubusercontent.com/4662049/27129151-fa58b388-5109-11e7-8a16-9f14ddabf444.png)

Using JabRef 3.8.2 jar on Linux Mint XCFE 64.

**Comment by tobiasdiez** [comment]
What do you put in the `author` field? `{Parliament of Kenya}` (with braces) should work.

**Comment by carbonmetrics** [comment]
It is in the author field with braces, see screen shot. 

![image](https://user-images.githubusercontent.com/4662049/27131440-64fc32ec-5113-11e7-8bce-044449130f0e.png)

**Comment by Siedlerchr** [comment]
Please try again with the latest snapshot of the 4.0.0 version, There it is displayed correctly.
As the 4.0.0 version has some major changes and is still beta, it is advisable to do a backup before
