### ISSUE TITLE
Pressing Delete/Sup key in editing mode, JabRef (9f9c145ac) try to delete the whole entry

### ISSUE THREAD

**Issue by ninfito** [JabRef/jabref#2910]
JabRef-4.0.0-dev--snapshot--2017-06-14--master--9f9c145ac.jar on Linux x86_64 (jre1.8.0_131)

Steps to reproduce:

1. double click an entry in order to edit
2. focus in e.g. Title textedit and press Delete key to delete a character 
3. JabRef shows "Delete entry" window

**Comment by Siedlerchr** [comment]
Thanks for your report. This is a duplicate of #2855
