### ISSUE TITLE
ID-based entry generator using DOIs incorrectly populates date field

### ISSUE THREAD

**Issue by moewew** [JabRef/jabref#2915]
JabRef version `JabRef 4.0.0-dev--snapshot--2017-06-15--master--31b345e00`
on Windows 10 10.0 amd64 Java 1.8.0_121 

Steps to reproduce:

1. Open JabRef
2. New biblatex library
3. New entry (Ctrl+N)
4. Use ID-based entry generator from DOI, say `10.1086/261527`
5. Generate
6. Find that the `date` field is (incorrectly) populated with the current date (2017-06-15) and not the entry date (1988), the field `year` is correctly populated with `1988`.

Ideally JabRef would use the `date` field instead of `year` and `month` in `biblatex` mode. But that might be something to fix on the side of the info provider, not JabRef.

<details>
  <summary>Generated `.bib` file</summary>
  
  ```
  @Article{Bollerslev1988,
  author    = {Tim Bollerslev and Robert F. Engle and Jeffrey M. Wooldridge},
  title     = {A Capital Asset Pricing Model with Time-Varying Covariances},
  journal   = {Journal of Political Economy},
  year      = {1988},
  date      = {2017-06-15},
  volume    = {96},
  number    = {1},
  month     = {feb},
  pages     = {116--131},
  doi       = {10.1086/261527},
  publisher = {University of Chicago Press},
}
  ```
</details>

**Comment by moewew** [comment]
A bit more playing around revealed that this is a more general problem. In fact all entries added have the `date` field populated with the current date by default. I have to explicitly overwrite the `date` when creating a new entry.

Naturally 'Mark new entries with addition date' is unchecked. (The designated field is `timestamp` and not `date` anyway.)

**Comment by Siedlerchr** [comment]
Thanks for your report. In biblatex, the year is an alias of date for background compatibility with bibtex.  So this is definitely a bug of the new entry editor
Could you please try if the clean up operation convert to biblatex mode then writes the year field into the date field? (I doubt it, but worth checking)

**Comment by moewew** [comment]
The 'Quality -> Cleanup entries' did not help, unfortunately.

While `year` is a backwards compatibility alias for `date`, the accepted formats are different.

**Comment by Siedlerchr** [comment]
I tried to investigate this a bit more and found that this is a problem with the Binding of the `date`field. 
I don't know why but in the  method `bindToEntry `in  the `AbstractEditorViewModel` the consumer newValue has the actual date when the fieldName is the date field.

I can only speculate that this oviously has sth to do with the year field set, because for other fields it does not aplly. 
@tobiasdiez  Any idea where I have to look?

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by moewew** [comment]
The bug indeed seems to be fixed in the new dev builds. Thank you very much.
