### ISSUE TITLE
Issue with java.lang.NullPointerException: Files

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#2917]
java.nio.file.Files.exists
	
	
org.jabref.gui.util.FileDialogConfiguration$Builder.withInitialDirectory
	
FileDialogConfiguration.java
	
82
org.jabref.gui.util.FileDialogConfiguration$Builder.withInitialDirectory
	
FileDialogConfiguration.java
	
90
org.jabref.gui.preftabs.PreferencesDialog.lambda$new$4
	
PreferencesDialog.java
	
168

Probably `directory` is null at https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/util/FileDialogConfiguration.java#L90
<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortal?subscriptionId=47cf7e0e-fb38-4184-aa27-6bd33822da55&resourceGroup=JabRef&componentName=JabRef%20application&bladeDetails=SearchResultExceptionDetailBlade%2Fid%2F%257B%2522id%2522%253A%2522fe7979e1-51d4-11e7-8bab-5322c40909fe%2522%252C%2522name%2522%253A%2522java.lang.NullPointerException%2522%252C%2522eventTime%2522%253A%25222017-06-15T14%253A14%253A43.886Z%2522%252C%2522eventType%2522%253A2%252C%2522componentId%2522%253A%257B%2522SubscriptionId%2522%253A%252247cf7e0e-fb38-4184-aa27-6bd33822da55%2522%252C%2522ResourceGroup%2522%253A%2522JabRef%2522%252C%2522Name%2522%253A%2522JabRef%2520application%2522%257D%252C%2522timeContext%2522%253A%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222017-06-15T20%253A00%253A00.000Z%2522%252C%2522createdTime%2522%253A%2522Thu%2520Jun%252015%25202017%252021%253A43%253A08%2520GMT%252B0200%2520(W.%2520Europe%2520Standard%2520Time)%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522context.device.type%2522%253A%255B%2522PC%2522%255D%252C%2522basicException.typeName%2522%253A%255B%2522java.lang.NullPointerException%2522%255D%257D%257D" target="_blank">View this instance in the Azure portal<\a>
<a href="https://stamp2.app.insightsportal.visualstudio.com/PortalRedirection/NavigateToPortalFeature?subscriptionId=47cf7e0e-fb38-4184-aa27-6bd33822da55&resourceGroup=JabRef&resourceName=JabRef%20application&featureName=Search&bladeDetails=SearchBlade&InitialFilter=%257B%2522eventTypes%2522%253A%255B2%255D%252C%2522typeFacets%2522%253A%257B%2522basicException.problemId%2522%253A%255B%2522java.lang.NullPointerException%2520at%2520java.nio.file.Files.provider%2522%255D%257D%252C%2522isPermissive%2522%253Afalse%257D&InitialTime=%257B%2522durationMs%2522%253A86400000%252C%2522endTime%2522%253A%25222017-06-16T02%253A14%253A43.886Z%2522%252C%2522createdTime%2522%253A%25222017-06-15T19%253A51%253A07.857Z%2522%252C%2522isInitialTime%2522%253Afalse%252C%2522grain%2522%253A1%252C%2522useDashboardTimeRange%2522%253Afalse%257D" target="_blank">View similar exceptions in this time range<\a>

**Comment by Siedlerchr** [comment]
I'll take a look at it
