### ISSUE TITLE
No response "Open Library"

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2924]
When I try to open a new bibtex library with:

- file-->Open Library
- ctrl-O
- clicking on the open library icon

nothing happens.  No window pops up and there's no error message.

JabRef 4.0.0-beta
Windows 10 10.0 amd64 
Java 1.8.0_77

**Comment by tobiasdiez** [comment]
I think this is already fixed in the [latest development version](https://builds.jabref.org/master/).

**Comment by notuntoward** [comment]
Yup, it's fixed on the latest dev.
