### ISSUE TITLE
IEEE search is broken again

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2925]
This is a reopening of #2870, but on the 4.0 beta:

JabRef 4.0.0-beta
Windows 10 10.0 amd64 
Java 1.8.0_77

The first time I tried downloading an IEEE reference, the 4.0 beta worked.  But now it's broken again, with the same response as in #2870.

**Comment by Siedlerchr** [comment]
Could you please try out the latest snasphot?  I just tested it and it works fine:
http://builds.jabref.org/master/
search for 
`adaptive bandwith` and got some results.

**Comment by notuntoward** [comment]
Yup, it's fixed on the latest dev
