### ISSUE TITLE
Form fields do not resize properly

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2927]
Sometimes the icons on the right are missing after resizing the main window. I do not understand the logic, when this happens.

JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131

![selection_301](https://user-images.githubusercontent.com/298682/27304180-8eca34b0-553d-11e7-872b-2bbf837ffeac.png)

**Comment by lenhard** [comment]
Since this is not a functional error, but UI polishing, I'll relabel it from "bug" to "enhancement"

**Comment by tobiasdiez** [comment]
@jonasstein Does this issue still happen with the most recent development version?

**Comment by jonasstein** [comment]
Just downloaded 
```
JabRef 4.0-dev--snapshot--2017-09-08--master--007a534d0
Linux 4.9.34-gentoo+ amd64 
Java 1.8.0_144

```
The icons did not disappear any more. Thank you.
