### ISSUE TITLE
New windows open behind main window

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2928]
Reproduce: 
Open the about window. 
Opens often, not always behind the main window.

JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131

update: Tested on Linux Mint 18.1 with OpenJDK and got the same results.

**Comment by tobiasdiez** [comment]
Is this something specific to Linux? At least on Windows 10, I can't reproduce it.

**Comment by Siedlerchr** [comment]
I can neither reproduce it under Linux, I am testing Xubuntu 16.10 with oracle jdk, latest snapshot
Did you maybe choose a window option to hide the window below others?

**Comment by jonasstein** [comment]
I did not activate things like "always on top" from the window manager. 
I click in the "general" tab on "+" to attach a pdf file and an `Untitled window` with a file selection interface opens in the **background**.
![selection_080](https://user-images.githubusercontent.com/298682/27739637-975eae56-5daf-11e7-915e-a263cb879741.png)

**Comment by koppor** [comment]
Which Window Manager is that? 😇 

Wanna join [JabCon 2018](http://jabcon.jabref.org/) in Dresden? 🎉

**Comment by jonasstein** [comment]
@koppor  This is on the Mate Desktop.
I also think the window should have a title like "Select File..."
![selection_437](https://user-images.githubusercontent.com/298682/34697163-2d4bf180-f4d2-11e7-92ab-229f2a8ddcc1.png)

**Comment by tobiasdiez** [comment]
This bug occurs only for JavaFX dialogs since we cannot yet set the main window as the parent for the new dialogs (they excepting a javafx window). Thus closed for now until the migration progresses further.

**Comment by jonasstein** [comment]
why do you close open bugs? Is the plan to reopen all  `after-migration-to-javafx` bugs later?
