### ISSUE TITLE
File Link icon not shown, can't access paper, hangs

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2930]
If I create a new bibtex entry and store a pdf in the "General file directory" with the same name as the bibtex key, then JabRef somehow finds it automatically and adds an entry to the File Window on the General Tab (see screenshot).  However,

1.) The file icon doesn't show up in the main table
2.) If I click on the paper icon in the File Window, I can't open the file by clicking the open button in the popup.
3.) If I add a description in the popup, the description isn't show the next time I click on the File Window
4.) There's no File entry in the raw bibtex
5.) JabRef sometimes hangs after the popup is shown -- no response to keyboard or mouse, and I have to use the Task Manager to kill it.

JabRef version  on 
JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07
Windows 7 6.1 amd64 
Java 1.8.0_131

![image](https://user-images.githubusercontent.com/3851891/27328045-f5db00bc-55b0-11e7-8c7a-01f5727b11bb.png)

**Comment by tobiasdiez** [comment]
Most of these points are actually by design: you first have to click the briefcase button to actually link the automatically found file.
I'll have a look at the other issues you mentioned.

**Comment by notuntoward** [comment]
Thaks for the explanation about the briefcase icon -- could be a bit bigger or red or something so that you know to click on it.  But it works for me on this version:

JabRef 4.0.0-dev--snapshot--2017-06-22--master--bee062c6a
Windows 10 10.0 amd64 
Java 1.8.0_77

However, it's still true that, if I add a description in the popup, the description isn't show the next time I click on the File Window.

Also, it seems that the file format in the saved bibtex entry has changed.  If, in the library properties, I enter the name of the directory immediately below the directory where the bibfile is stired, the auto-added file links look like this:

  file          = {:tmp\\Accardo08Samplingproblemsusing.pdf:PDF},

where 'tmp' is the name of the file directory (see example1.txt).  

In example1.txt, I also see that JabRef has stored the full path to the file directory, even though I entered only 'tmp').  The breaks cross-platform compatibility, for example, where my bibtex file is stored in git, and is checked out in different root paths on different machines (this is unavoidable).  It also breaks other bibtex reading programs, for example, the emacs org-ref package, which cannot find the paper and open it.

[example1.txt](https://github.com/JabRef/jabref/files/1095756/example1.txt)

**Comment by Siedlerchr** [comment]
I could reproduce this partly. The library properties directory setting is by design. If you want to keep it relative, I suggest you use the Option: Use location of Bib File as Main Directory, and then you can have subfolders as you want. 

To your second thing with the description.
I debugged it and this is getting weird now: @tobiasdiez 
When you add a `System.out.println(linkedFile);` in the method `public void edit` in `LinkedFileViewModel`, the description is actually stored. I dunno if this is a threading problem. 

And if you click the edit file and then click again on browse in the dialog, JabRef hangs 
Furthermore the context menu floats around and stays, even on top of other apps 
![image](https://user-images.githubusercontent.com/320228/27540154-6ccb3dc2-5a7f-11e7-8c13-e3b2b1f356a4.png)

**Comment by notuntoward** [comment]
Thanks for the tip about the setting: Use the BIB file location as primary file directory.

It works.

**Comment by tobiasdiez** [comment]
So to summarize, the only open problem is the missing description text, right? As this is only a minor issue, I remove this from the 4.0 milestone.

**Comment by notuntoward** [comment]
The other issue still remaining is that, the workaround for this problem causes the file pane to look in the wrong directory (workaround: setting the BIB file location as primary file directory).  See #2985.

A (big to me) problem still remains but I'm not sure which PR # it should be assigned to.

**Comment by notuntoward** [comment]
One thing still missing is 3.) in the original report.  The "description" field (entered in the File popup), isn't displayed.  Lately, there is  a mouse-hover hint but you have to hover your mouse over the entry but it takes nearly a second for it to show up, and if there no description was entered, you wait longer until you finally give up and conclude that there is no description.

In JabRef 3x, the description field was always displayed in the File window.  I think this behavior was much better.

**Comment by Siedlerchr** [comment]
@notuntoward  The description problem are acutally two problems.
 The displaying is not the problem, the problem is that the descr does not get synchronized/wrritten to the bibtex code

**Comment by notuntoward** [comment]
@Siedlerchr you're absolutely right that the description doesn't get written to the bib file -- I hadn't noticed that before -- but if it had been written, would it still be displayed only as a mouse hover hint?

**Comment by Siedlerchr** [comment]
Existing descriptions are shown as tooltip, but not updated if you change them. I am currently preparing a PR for the display directly, however I first wanted to make sure the synchro of the description works

**Comment by tobiasdiez** [comment]
To display the description only as a tooltip was actually by design. In most cases (I guess), the file name is sufficient to identify the file and thus the description is not really necessary. Thus the idea was to hide the description a bit in order to make the interface lighter and don't cramp everything. @notuntoward what is your use case for which you need the description field?

**Comment by Siedlerchr** [comment]
@tobiasdiez 
You don't happen to have an idea why the file description is not synced with the bib entry code but the file link and type, although they are just properties of the same class ?

**Comment by tobiasdiez** [comment]
no, sorry, I don't have an idea. Did you write (do we have?) a test checking that the linked file class is serialized correctly? If thats the case, the problem has to lie in saving the contents of the description text field in the class field (or serializing the previous class before the edit).

**Comment by Siedlerchr** [comment]
@notuntoward  I created a follow up issue for the description sync problem in #3208

**Comment by notuntoward** [comment]
Hi @tobiasdiez, I often have several documents under one entry.  Examples are:

1. the paper, the presentation slides, the tech note
2. several drafts of a paper I'm reviewing for a journal
3. a paper and a bunch of supporting documents (math pages from wikipedia, emails from the author, ...)

It's sometimes not easy to compactly distinguish these things with a file name, but if you try, you'll want to keep some order in the huge directory where all the documents go, usually by naming each file starting with the bibtex key, then following that with description text.  Depending upon the key length, that's a lot of redundant characters for the short JabRef File window.  And in my opinion, it's less clean than just having the description without the key.

But in addition, there is the bother of mouse hovering while you wait for the tooltip to show, or to wait somewhat longer than that in order to confirm that there is no description.
