### ISSUE TITLE
No way to see other related article links

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2931]
The related articles tab usually produces links to several articles.  But if I click on one, I don't see a way to go backwards to get to the other links; it seems that I have to rerun the search.

JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07
Windows 7 6.1 amd64 
Java 1.8.0_131

**Comment by lenhard** [comment]
The Mr.Dlib team is planning improvements to the related articles tab. @Joeran might be interested in this.

**Comment by Joeran** [comment]
hi @notuntoward . can you please explain in more detail what you mean by saying that you "don't see a way to go backward"? If you click a recommendation in the related-article tab, the recommendation should open in your web browser, i.e. when you go back to jabref, all recommendations should be still there.

**Comment by Siedlerchr** [comment]
@Joeran By default all links are opened in this javafx WebView control. 
I now added a handler which opens all hyperlinks in a new browser window.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by notuntoward** [comment]
Yes, this version:  

JabRef 4.0.0-dev--snapshot--2017-06-22--master--bee062c6a
Windows 10 10.0 amd64 
Java 1.8.0_77

opens links in an external browser instead of inside of JabRef -- much better.

However, there seems to be something wrong with the source of the links.  For example,  one third of the related article links for the attached bibtex entry are 404's

[example.txt](https://github.com/JabRef/jabref/files/1095703/example.txt)

**Comment by Siedlerchr** [comment]
Thanks for the report. This seems to be a problem on the server side where

**Comment by Joeran** [comment]
> @Joeran By default all links are opened in this javafx WebView control.

I am using JabRef-4.0.0-beta.jar under Windows 10, and all links open in the web browser (each link in a new tab)
![image](https://user-images.githubusercontent.com/2410381/27461019-aba4624c-57f2-11e7-8127-902c61ca759e.png)

> However, there seems to be something wrong with the source of the links. For example, one third of the related article links for the attached bibtex entry are 404's

I will check this. It might be that some documents are not available any more but overall this certainly should not be 1/3 of the documents.
