### ISSUE TITLE
Group information in new database not stored

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#2932]
Current master.

I debugged a bit through and found that in the ` MetaDataSerializer.getSerializedStringMap ` the `metaData.getGroups() `returns null/empty optional. In the metadata class the `groupsRoot ` is null.

Furthermore I found out that `setGroups()` in `Metadata `is never called (except from the importer and some tests)

**Comment by lenhard** [comment]
So at what point in the code are the new groups (most important the root) actually created? I had a look at the code and have a hard time finding it.
