### ISSUE TITLE
Delete (DEL) key always opening dialog

### ISSUE THREAD

**Issue by andipabst** [JabRef/jabref#2936]
If I press the delete key (DEL) anywhere in JabRef I get a promt asking me, if I really want to delte this entry. 
This also occurs if I didn't want to delete an entry but delete an character in a description field.

JabRef version 4.0.0-dev--snapshot--2017-06-22--master--bee062c6a
Windows 7 6.1 amd64 
Java 1.8.0_121

Steps to reproduce:

1. Open a database
2. Select an entry to edit it in the editor view at the bottom
3. Select any field or text there and press the 'DEL' key on your keyboard

Screenshot of the dialog: 
![image](https://user-images.githubusercontent.com/9639382/27470822-e8f6358c-57f5-11e7-8eac-52a4fff04693.png)

**Comment by Siedlerchr** [comment]
Thanks for your report!  This problem is already known and this problem affects all keybinding like ctrl+c etc. #2855 
The only workaround for deleting is to use the backspace key, which does not trigger the dialog
