### ISSUE TITLE
Add copy and paste enabled textbox with version information to about window

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2942]
I suggest to add a copy and paste enabled textbox with version information to the about window. At the moment there is only a copy to clipboard button. It would be nice to see the information already in the window. There should be also more detailed information on the Java environment
![jabref_about](https://user-images.githubusercontent.com/298682/27512491-13343ee6-5942-11e7-8a53-be38d1baa1e9.png)
.

**Comment by Siedlerchr** [comment]
At least the snapshot information should be displayed and copied.

**Comment by koppor** [comment]
+1 for implementing it 😇

**Comment by steph37tours** [comment]
So I agree to look at this.
I suppose I have firstable to find the form and add the textbox.

**Comment by Siedlerchr** [comment]
@steph37tours In our wiki you find some information about the package structure and some explainations to the architecture to get an understanding how things work together: https://github.com/JabRef/jabref/wiki/High-Level-Documentation

Even I often struggle to locate a specific gui dialog in the package structure.. So I give you a little hint:  Look at gui.help

**Comment by steph37tours** [comment]
Thank you @Siedlerchr, I found the gui.help.
As long as for instance I've got any experience into javafx. Does I have to install scenebuilder ?

**Comment by Siedlerchr** [comment]
@steph37tours Yes, it might come in handy and eases the gui creation. The resource files (fxml) are stored in the respective folder under /src/main/resources/ 
If you use eclipse, I can recommend installing the e(fx)clipse plugin: http://www.eclipse.org/efxclipse/index.html

**Comment by steph37tours** [comment]
Actually version show is "unknow" and I've got any developers, etc...
How to have some info to test ?

**Comment by steph37tours** [comment]
I use a TextArea.

**Comment by steph37tours** [comment]
I create a String into the controller. Into a Label, I see it, but not into the textarea.

**Comment by jonasstein** [comment]
Please do not get me wrong, but I suggest you use a chat like IRC for discussion in spite of a bug tracker. I (and all others) get a notification for each activity here and it is rather about general Java programming/ Jabref structure than the bug. Anyway, thank you for taking care of this ticket and your effort.

**Comment by Siedlerchr** [comment]
@steph37tours  Agree with @jonasstein  You can add me at Skype for more discussions:
My Skype name is  `siedlerkiller2.0`

**Comment by lynyus** [comment]
@jonasstein This issue was fixed in https://github.com/JabRef/jabref/pull/3205

**Comment by koppor** [comment]
Regarding the discussion channels: Although IRC is non-proprietary, we offer a slack group. We are also aware of [gitter](https://gitter.im/), but opted for the more popular one. @steph37tours already joined.

Hey, and slack offers XMPP 😄  See https://www.slant.co/versus/4553/4567/~slack_vs_gitter-im
