### ISSUE TITLE
Mistake on installation website

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2948]
http://help.jabref.org/en/Installation

"Set your preferred Java version on Linux distributions using the following command:"
should be
"Set your preferred Java version on Debian based Linux distributions using the following command:"

**Comment by koppor** [comment]
Please submit a pull request - this would ease inclusion very much. 😇 

Would you mind clicking on "Edit this page" at the end of the installation page? Or to click the octo cat at the upper right corner? And then on the edit pencil?

Detailed instructions given at https://github.com/JabRef/help.jabref.org/blob/gh-pages/CONTRIBUTING.md

**Comment by jonasstein** [comment]
here you are https://github.com/JabRef/help.jabref.org/pull/163
