### ISSUE TITLE
"change case" for multiple references

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#295]
I dont know if this is relevent or not. 
When we want to change the case of titles of serveral references, we need to do "right-click, change case" for every reference, I was wondering if it is possible to change case in a batch way, or for a multiple selection.
This could be added in "Cleanup entries" for example,
Thank you all :)

**Comment by oscargus** [comment]
One could clearly think of an extended Cleanup functionality, being able to perform clean-ups on specific user-specified fields. For example, at the moment, some of the clean-ups are only performed on specified fields (such as Unicode conversion), which is defined by the developers. Clearly, it would be better to be able to apply "all" clean-up actions on "all" fields (for some definition of "all", some of the actions, such as page number clean-up clearly only makes sense on the pages field).

I will think about how to implement this, as I would also find it useful.

**Comment by oscargus** [comment]
Thinking again: are there any other fields than title where this would make sense? In that case, it would be a rather quick fix.

**Comment by matthiasgeiger** [comment]
Thanks for your suggestion. 
I think this might be indeed useful can could be performed as a cleanup action.

We developers are currently discussing the serialization and clean up mechanisms and how to configure them, so I'll add this to our agenda.

@oscargus So please wait with introducing this feature :wink:

The most sensible use case are changing the cases of titles. But (depending on the quality of the BibTeX sources) it *might* be also useful to change the "casing" for other field such as  `booktitle`, `journal`, `series`, and so one... But this must be all configurable and would require quite some effort to be implemented (and it's questionable how often is would be actually used).

**Comment by g10996694** [comment]
glad that you think that it would be useful.
but, we know that it takes time, 
thanks again for all these efforts :)
