### ISSUE TITLE
Jabref wants to delete entry instead a single char (Label: bug, gui, Linux)

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2950]
JabRef 4.0.0-dev--snapshot--2017-06-22--master--bee062c6a
Linux 4.4.0-78-generic amd64 
Java 1.8.0_131

Reproducable on Linux Mint 18.1:
Select Paper, click on "Title" textfield in the bottom region. 
Press delete to delete first character. 
Warning message pops up.
![delete entry_077](https://user-images.githubusercontent.com/298682/27685964-cea006d8-5cd0-11e7-9325-23805bc98e4d.png)

Answer **no**, first character is deleted. 
I would expect, that just the first character gets deleted, but Jabref seems to have a focus on the textfield and the paper selection at the same time.

**Comment by Siedlerchr** [comment]
Hi, this should be fixed in a more recent snapshot of the master. You can
download it from builds.JabRef.org

Am 29.06.2017 1:43 nachm. schrieb "Jonas Stein" <notifications@github.com>:

**Comment by jonasstein** [comment]
Thank you. I confirm, that is it fixed at least in 
```
JabRef 4.0.0-dev--snapshot--2017-06-29--master--7e50e84a1
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131

```
