### ISSUE TITLE
FR: link to the latest jabref-4.0.*.jar

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2953]
**could you provide a link / symlink to the latest  jabref-4.0.*.jar**, please?
It would be very nice, if users can use a bash script like
UpdateJabref.sh

```
#!/bin/bash
wget https://builds.jabref.org/master/JabRef-4.0.0-dev--snapshot--latest.jar

```
which fetches the latest .jar.
Upstream has just to provide `https://builds.jabref.org/master/JabRef-4.0.0-dev--snapshot--latest.jar` which links to `https://builds.jabref.org/master/JabRef-4.0.0-dev--snapshot--2017-06-29--master--7e50e84a1.jar` and so on

**Comment by koppor** [comment]
The script to modify is [upload-to-builds.jabref.org.sh](https://github.com/JabRef/jabref/blob/master/scripts/upload-to-builds.jabref.org.sh). Do you have an idea how to implement that using sftp commands?

**Comment by Siedlerchr** [comment]
Maybe this can be done by providing a symlink?
I have no idea how to code that, but I think this could work

Am 30.06.2017 10:32 vorm. schrieb "Oliver Kopp" <notifications@github.com>:

**Comment by koppor** [comment]
Sure, but the target of the symblink changes at each update. And AFAIK, it
is not possible to use "wildcard symlinks".

Am 30.06.2017 11:42 schrieb "Christoph" <notifications@github.com>:

**Comment by tobiasdiez** [comment]
Maybe we should just use the [install4j auto updater](http://blog.ej-technologies.com/2010/12/beyond-installing.html) for the development version. I think this really makes sense since we get quite a lot of bug reports recently that are already fixed in master.

**Comment by jonasstein** [comment]
I do not know your work flow, but it would be fine to run a script, which creates a symlink to the latest *.jar
https://stackoverflow.com/questions/10626120/is-it-possible-to-create-a-symlink-to-the-latest-file-in-a-directory

**Comment by koppor** [comment]
Implemented via https://github.com/JabRef/jabref/commit/2ec520fd05523f5c3d7ad9b355e77a93a0a1d99a. Not using bash as the builds are done at CircleCI (see https://github.com/JabRef/jabref/wiki/CI) and I did not want to install and maintain [icrond](https://linux.die.net/man/8/incrond).

http://builds.jabref.org/master/JabRef--master--latest.jar now always links to the latest file.

**Comment by tobiasdiez** [comment]
@koppor should we also put the link on the main homepage?
