### ISSUE TITLE
Compose key does not work in Jabref 4.x 

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2954]
On Linux and Unix systems it is very common to assign a key to the compose function.
https://en.wikipedia.org/wiki/Compose_key
The user can write international special characters on a standard QWERTY keyboard.

This worked in Jabref 3.8.2 but unfortunately it fails on 4.x

Users can not write umlauts anymore with Compose " o -> ö 
or Compose / O -> Ø

JabRef 4.0.0-dev--snapshot--2017-06-29--master--7e50e84a1
Linux 4.4.0-78-generic amd64 
Java 1.8.0_131

**Comment by tobiasdiez** [comment]
Does it still works in the old Swing text inputs (like the search bar)?

**Comment by jonasstein** [comment]
**Yes**, it still works in the search bar:
![selection_078](https://user-images.githubusercontent.com/298682/27739403-b7095ce8-5dae-11e7-872f-4e1a221e7e65.png)

**Comment by lenhard** [comment]
Possibly related: #3028

**Comment by Siedlerchr** [comment]
I close this in favor of #3028
