### ISSUE TITLE
Double-click on jabref file from Gnome Nautilus opens it as "untitled"

### ISSUE THREAD

**Issue by giacecco** [JabRef/jabref#2958]
JabRef version: 2.10 on Linux Fedora, installed from packages (2.10 is the latest available from packages)

Steps to reproduce:

1. Create a jabref file and save it somewhere with ".jabref" extension
2. Close the JabRef application
3. Double-click on the .jabref file from Nautilus (Gnome's default file manager installed with Fedora) 

... and the file will be correctly open, but JabRef thinks it is a new file (the titlebar says "JabRef - untitled *" etc.).

**Comment by Siedlerchr** [comment]
JabRef version 2.10 is outdated and no longer supported. I suggest that you
try at least version 3.8.2 or the latest snapshot of version 4.



Am 03.07.2017 10:34 vorm. schrieb "Gianfranco Cecconi" <
notifications@github.com>:

**Comment by koppor** [comment]
Please follow up at https://bugzilla.redhat.com/show_bug.cgi?id=1299158
