### ISSUE TITLE
RIS import error : Booktitle / Series

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#296]
It seemed that there would be a problem when importing RIS format data.
Most likely for chapter type, generally the Booktitle tag is T2, but when the Series tag (for RIS tag :  T3) exists, JabRef would take T3 as booktitle, instead of T2.
you could test the following RIS
<pre>
TY  - CHAP
PY  - 2015
Y1  - 2015/09/10
Y2  - 2015/11/06
M1  - 0
DO  - doi:10.1201/b19107-2
UR  - http://dx.doi.org/10.1201/b19107-2
N1  - doi:10.1201/b19107-2
M3  - doi:10.1201/b19107-2
AU  - Catarina Barata
AU  - MEmre Celebi
AU  - JorgeS Marques
SP  - 1-22
TI  - Toward a Robust Analysis of Dermoscopy Images Acquired under Different 					Conditions
T2  - Dermoscopy Image Analysis
T3  - Digital Imaging and Computer Vision
SN  - 978-1-4822-5326-9
PB  - CRC Press
ER  - 
</pre>
Here, "T2" is the Booktitle, "T3" is Series, 
I'm under 2.11b3.

**Comment by stefan-kolb** [comment]
@JabRef/developers Can anyone confirm this? And mark as a bug if reproducible?

**Comment by obraliar** [comment]
Confirmed. In such case T3 is taken as booktitle  instead of T2. See https://github.com/JabRef/jabref/pull/505

**Comment by simonharrer** [comment]
Is this fixed in #817 @obraliar ?

**Comment by obraliar** [comment]
Yes.
