### ISSUE TITLE
Duplicate finder ignores book edition

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2960]
My bibtex file contains two editions of a book, but the "find duplicates" function considers them to be duplicates and tries to merge them.

Also, shouldn't the jabref gitup bug reporter accept bibtex files for uploading?  As it is, it's necessary to rename them to *.txt.

JabRef version 

JabRef 4.0.0-dev--snapshot--2017-06-29--master--7e50e84a1
Windows 7 6.1 amd64 
Java 1.8.0_131

Steps to reproduce:

1. Load the attached bib file
2. Quality--> Find Duplicates
3. A window should pop up with a merge suggestion

[example2editionBooks.txt](https://github.com/JabRef/jabref/files/1119705/example2editionBooks.txt)

**Comment by lynyus** [comment]
Hey @notuntoward,
whether this is a bug or a feature is actually a question.

My feeling is that you are right as the two BibEntries correspond to different physical entities. However, I can imagine that for many users the actual edition does not matter so much and that they would prefer to keep only the BibEntry of the latest edition.

I guess we will discuss what is the best behavior.

**Comment by notuntoward** [comment]
OK.  In my case, I like to keep both editions around because 

1.) I have different markups in the different book pdf revisions, and I'd like to refer to them in my own notes (instead of manually copying markups from one pdf to the next)
2.) An old paper may have referred to the old revision of the book (with a certain page number)

As the JabRef duplicate detector is now, I see this duplicate warning every time I do an integrity check.  I can get around that by selecting to keep both revisions, but I have to remember to do that while I'm hurriedly clicking through all the other stuff.  At some point, I'm going to forget and accidentally delete one of the book revisions.

**Comment by lynyus** [comment]
Hey, @notuntoward, I had a look and improved the duplicate checker as you suggested. Would you mind checking my changes are working out well for you? You can download the improved version here: https://builds.jabref.org/non-duplicate-editions/

**Comment by notuntoward** [comment]
Hi Linus, this works perfectly.  Thanks.
