### ISSUE TITLE
The jabref windows freezes and doesn't response.

### ISSUE THREAD

**Issue by poofee** [JabRef/jabref#2962]
when the bibtexkey is too long, the jabref will not response and I can't do anything except closing it.
 

JabRef version  on 

Steps to reproduce:

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by daesters** [comment]
Could you indicate, which version of jabref and wich Bibtexkey you used?

**Comment by poofee** [comment]
The version of jabref is 3.8.2. And the bibtex is
@article{何晓东2000有限差分法在静态电磁场计算中的应用,
  title={有限差分法在静态电磁场计算中的应用},
  author={何晓东 and 杨博 and 刘大力},
  journal={吉林大学学报(信息科学版)},
  volume={18},
  number={4},
  pages={27-30},
  year={2000},
},
so the bibtexkey is "何晓东2000有限差分法在静态电磁场计算中的应用"

**Comment by Siedlerchr** [comment]
I can not reproduce this in the latest snapshot of JabRef version 4. Please try the latest snapshot from http://builds.jabref.org/master

**Comment by poofee** [comment]
I tried it again. It really did not happen. I don't know why. Maybe it sometimes happens.  I have seen it for several times. If you can't reproduce it, then forget it.

**Comment by Siedlerchr** [comment]
Thanks for your feedback. I would vote to close this for the moment. If it occurs again and you can provide some more details (e.g. steps to reproduce) feel free to reopen the issue.
