### ISSUE TITLE
total count of entries - UI misses pixels (open again)

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#2964]
JabRef 4.0.0-dev--snapshot--2017-07-03--master--6897b10fb
Linux 4.11.7-200.fc25.x86_64 amd64 
Java 1.8.0_131

Whilst #2803 was closed, the same issue happens in the current version again.

![screen](https://user-images.githubusercontent.com/20518297/27826858-1441fdbc-60b5-11e7-8c7c-875ecca5a592.jpg)

**Comment by lenhard** [comment]
I can confirm this still occurs, but I'll take the liberty to change the tags.

It's not a bug (the GUI doesn't break down, freeze, etc.) and its not a show-stopper for 4.0 (plenty of other things to fix before that)
