### ISSUE TITLE
Add menu option to remove link to a file

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2968]
![selection_081](https://user-images.githubusercontent.com/298682/27859481-2bedf15e-6179-11e7-9b0d-d7ab6a466916.png)

add 'remove link to file' to context menu

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
