### ISSUE TITLE
Resizing of the window "Select files" does not scale properly

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2970]
Windows should be scalable and move the buttons intelligent within a given range.
Scaling should be limited to the minimum/maximum size.

![selection_082](https://user-images.githubusercontent.com/298682/27860029-22d52478-617b-11e7-98e6-309262bf395c.png)
![selection_083](https://user-images.githubusercontent.com/298682/27860030-24b4c582-617b-11e7-8411-74c7149aa729.png)
![selection_084](https://user-images.githubusercontent.com/298682/27860033-27e49cd2-617b-11e7-9ecf-56cc040e91d8.png)

```
JabRef 4.0.0-dev--snapshot--2017-07-03--master--6897b10fb
Linux 4.4.0-78-generic amd64 
Java 1.8.0_131
```

**Comment by jonasstein** [comment]
perhaps related to or duplicate of #2927

**Comment by Siedlerchr** [comment]
I will try to convert that dialog to javafx , this will hopefully also
resolve the problem with the freezing

Am 07.07.2017 7:03 vorm. schrieb "Jonas Stein" <notifications@github.com>:

**Comment by jonasstein** [comment]
in 

```
JabRef 4.1
Linux 4.14.12-gentoo+ amd64 
Java 1.8.0_152 

```

This looks like this after minimize, maximize the window:

![selection_438](https://user-images.githubusercontent.com/298682/34698912-f1213d92-f4da-11e7-9429-02ff28f67aae.png)

**Comment by Siedlerchr** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See #3621 for further details.
