### ISSUE TITLE
Uniform notation in the menu camelcase or without camelcase (label ui trivial enhancement 4.x)

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2975]
![selection_093](https://user-images.githubusercontent.com/298682/27905658-e79bf88e-6240-11e7-83dd-28579f2c04d3.png)

-> BibLaTeX would fit here better.

**Comment by lenhard** [comment]
You might think this way (and in fact we from the JabRef development team did so), but it turns out that biblatex is supposed to be spelled in lowercase. More information here: #2493

So I can safely say we won't change this, sorry.
