### ISSUE TITLE
Ctrl+S does not save (Label 4.x, Linux, bug)

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2976]
![selection_094](https://user-images.githubusercontent.com/298682/27906614-92f1f884-6244-11e7-92d0-1a91412f3d55.png)

Changes were made, a star appeared next to the filename. 
Now press Ctrl+S, but the star does not disappear.
But Ctrl+S was defined:
![selection_097](https://user-images.githubusercontent.com/298682/27906693-e7e47fc4-6244-11e7-8b37-a7d6b54bf572.png)

```
JabRef 4.0.0-dev--snapshot--2017-07-03--master--6897b10fb
Linux 4.4.0-78-generic amd64 
Java 1.8.0_131
```

**Comment by lenhard** [comment]
Can you check if the changes were written to the file system? It might very well be the case that this is only a UI problem and the star does not disappear although the changes were written to disk.

**Comment by Siedlerchr** [comment]
This is related to https://github.com/JabRef/jabref/pull/2971
As I fix this I close this for the moment

**Comment by jonasstein** [comment]
@Siedlerchr Thank you very much for fixing this. 
Ctrl+S works now, if the star appears and the star is away.
However the star does not appear, after changing groups, or edit existing entries. But appears, when creating a new article entry. Should I create a new ticket for this?

```
JabRef 4.0.0-dev--snapshot--2017-07-06--master--edd3f7cc1
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131
```

**Comment by tobiasdiez** [comment]
Thanks for the feedback. The issue you mention is already known https://github.com/JabRef/jabref/issues/2787.
