### ISSUE TITLE
LaTeX -> UTF-8 conversion fails for {\textquotesingle}

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2977]
{\textquotesingle} returns nothing
see also #2757

```
JabRef 4.0.0-dev--snapshot--2017-07-06--master--edd3f7cc1
Linux 4.4.0-78-generic amd64 
Java 1.8.0_131
```

**Comment by lenhard** [comment]
Hi @jonasstein 

Thanks for reporting! As far as I can see, {\textquotesingle} is not part of normal LaTeX, but comes with the textcomp package: https://ctan.org/pkg/textcomp

We decided to limit the unicode conversion to the built-in commands only. There are simply too many packages with too many potential commands to support and in the end JabRef is not a LaTeX processor.
