### ISSUE TITLE
Preview pane has gotten really slow

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2982]
It seems that the preview pane has gotten much slower in the beta version of JabRef.  If I remember correctly, I used to be able to quickly scan through papers by moving the cursor down the file list.   The preview pane would be nearly instantaneously updated as I moved from one paper to the next.  But now it takes about a second for the preview pane update, and this really slows down this type of scanning (screenshot attached, for clarity, in case I'm using the wrong terminology).

In preferences-->Entry preview, I have "IEEE (with URL)" set, with "IEEE" as the second option.

JabRef 4.0.0-dev--snapshot--2017-07-07--master--eaf53f75d
Windows 7 6.1 amd64 
Java 1.8.0_131

![image](https://user-images.githubusercontent.com/3851891/27991666-b44c74f0-647e-11e7-8743-892d403b5bff.png)

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/pull/2250

**Comment by notuntoward** [comment]
With the latest dev snapshot, if I type any search string, then preview is pretty fast, both within the search hits and outside of them.  But until I do a search, preview remains very slow.

JabRef 4.0.0-dev--snapshot--2017-07-09--master--220d65432
Windows 7 6.1 amd64 
Java 1.8.0_131

**Comment by AEgit** [comment]
Cannot confirm for:
JabRef 4.0.0-dev--snapshot--2017-07-16--master--4c805effd
Windows 10 10.0 amd64 
Java 1.8.0_131

Note, however, that the performance problems (if they exist) may be machine-dependent.

**Comment by notuntoward** [comment]
@AEgit, I noticed you were on Windows 10, so I found a Windows 10 computer and tried it there.  I see the same as you; JabRef beta scrolling is fast on Windows 10.

However, it's still slow on the Windows 7 machine, which is a much faster beast: i7 vs. i5; 16GB ram vs. 8 GB; and so on...  This is with:

JabRef 4.0-dev--snapshot--2017-07-20--master--6ea5eb999
Windows 7 6.1 amd64 
Java 1.8.0_141

**Comment by AEgit** [comment]
Hmmm, that's interesting - it might be a Windows 7 problem (?). @Koppor: Could other people try as well (maybe also with Linux and Mac) to see whether they can reproduce this behaviour?

**Comment by AEgit** [comment]
@lenhard: I remember from one of your comments that you had a Windows 7 machine at your disposal. Can you confirm the issue mentioned by @notuntoward? If not, this will be quite difficult to narrow down, I guess.

**Comment by tobiasdiez** [comment]
I actually don't think that the performance problem comes from Windows 7. @notuntoward can you try to reset the preferences and see if the issue persists.

**Comment by lenhard** [comment]
@AEgit Will try!

@notuntoward Did you try the suggestion from @tobiasdiez ?

**Comment by notuntoward** [comment]
OK, I reset my preferences and it's now just as fast on Windows 7 as it is on Windows 10 (preferences before and after the reset attached, if that helps).

[jabrefPrefsAfterReset.txt](https://github.com/JabRef/jabref/files/1245387/jabrefPrefsAfterReset.txt)
[jabrefPrefsBeforeReset.txt](https://github.com/JabRef/jabref/files/1245386/jabrefPrefsBeforeReset.txt)

**Comment by notuntoward** [comment]
More Info:  Actually, preview on my Windows 10 and Windows 7 machines are equally slow if I set them both to IEEE style -- for IEEE, JabRef is looking up something on the internet.  I didn't notice this difference in my preferences.

**Comment by koppor** [comment]
@notuntoward It is a known issue - see https://github.com/JabRef/jabref/pull/2250#issuecomment-264824598

Do you know someone having experience in gradle packaging?

**Comment by koppor** [comment]
@notuntoward It is a known issue - see https://github.com/JabRef/jabref/pull/2250#issuecomment-264824598

When you reset the preferences, the internal preview WITHOUT citation styles. If you change the preview to a citation styles, citation styles is used again and the thing gets slow.

Do you know someone having experience in gradle packaging? I created a [stackoverflow question](https://stackoverflow.com/q/43459663/873282) and also made first steps at https://github.com/JabRef/jabref/pull/3180, but I am stuck.

**Comment by notuntoward** [comment]
Ah, thanks.  The first time I tried the IEEE style, I was offline and had just fired up Jabref.  I noticed a message in the bottom of the window saying that it could not connect to a server (screenshot), which I now guess is where Jabref updates come from.  Anyway, I jumped to the erroneous conclusion that the slowness was due to an connection weight. 

Sorry, I don't know much about Java, and unfortunately, I don't know anybody who knows gradle.

![image](https://user-images.githubusercontent.com/3851891/29970318-5c868e88-8f24-11e7-958c-c6fa679f8f53.png)

**Comment by lenhard** [comment]
The preview performance, also using citation styles, has been drastically improved with #3533 That's about as much as we are able to do at the moment.

Hence, I dare to close this issue. Feel free to reopen if the performance doesn't cut it.
