### ISSUE TITLE
Cut/Paste article

### ISSUE THREAD

**Issue by mpele** [JabRef/jabref#2989]
JabRef version - development release

Steps to reproduce:

1. Cut article from some group
2. Paste to another group

The article is copied to another group but it is not removed from original group.

**Comment by AEgit** [comment]
I can confirm this issue for:
JabRef 4.0.0-dev--snapshot--2017-07-10--master--e80f450ee
Windows 10 10.0 amd64 
Java 1.8.0_131

**Comment by tobiasdiez** [comment]
How do you cut and paste "from the group"?
The usual Cut/Paste operations are semantically performed against the database, that is, cut removes the entry from the database and paste inserts it (in a possible different database). All information like the group membership are preserved in the process. So for example if you have two databases with the same groups then copying/cutting an entry and pasting it in the other database still assigns the entry to the correct group. Thus the behavior you describe is expected.

If you want to change the group membership you can right click the entry and use "Add/Remove from group" or use the corresponding options in the right click menu of the group.

**Comment by AEgit** [comment]
@tobiasdiez: Ah fair enough, if that's the expected behaviour there's no issue to report. Following @mpele I had the impression that "cut" was supposed to remove an article from a group and "paste" add it to the selected group.
