### ISSUE TITLE
Enable DeclarationOrder in Eclipse and IntelliJ

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#2996]
[DeclarationOrder](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/DeclarationOrderCheck.html) should be set in the IntelliJ config - or disabled.

1. Class (static) variables. First the public class variables, then the protected, then package level (no access modifier), and then the private.
1.  Instance variables. First the public class variables, then the protected, then package level (no access modifier), and then the private.
1. Constructors
1. Methods

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/pull/2765#issuecomment-297405985
@snisnisniksonah

**Comment by tobiasdiez** [comment]
Same applies for the rule `'METHOD_DEF' has more than 1 empty lines before. [EmptyLineSeparator]`

**Comment by tobiasdiez** [comment]
I found a checkstyle IntellJ plugin, which imports a checkstyle configuration and changes the style accordingly. I also added a description of how to setup everything in the wiki. So this issue can be closed in my opinion.
