### ISSUE TITLE
The LibraryOfCongressTest started failing recently

### ISSUE THREAD

**Issue by lynyus** [JabRef/jabref#3013]
Currently it throws a 500 error.
We should check why, and try to fix it, if possible.

Refs. https://github.com/JabRef/jabref/pull/3012

**Comment by Siedlerchr** [comment]
Seemsl ike a problem with the lccn.gov website as I even can't get it to work manually
http://lccn.loc.gov/2010045158

**Comment by stefan-kolb** [comment]
Should work again now?
