### ISSUE TITLE
Has anyone tested docbook export recently? Export failed!

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3020]
JabRef version JabRef-4.0.0-dev--snapshot--2017-06-22--master--bee062c6a

I used the line from http://help.jabref.org/en/CommandLine
    ```java -jar JabRef-4.0.0-dev--snapshot--2017-06-22--master--bee062c6a.jar -o EndokrinologieKunde.xml.docbook -n true EndokrinologieKunde.bib```

Edit: There was a typo should read file.xml,docbook therefor I delete the noise

**Comment by bernhard-kleine** [comment]
There was an error in my command, sorry for noise.

However, [Formatter not found: CreateDocBookEditors] when the bib-file was converted no editors were found and converted.

This is something that should not have happened.

**Comment by lenhard** [comment]
@bernhard-kleine Thanks for the report!

I've had a look at this and I think I found the error that caused the problem. It seems that the CreateDocBookEditors formatter got lost at some point. Could you please try out the version available here http://builds.jabref.org/link-docbookeditors/ and report back if it works again?

**Comment by lenhard** [comment]
And since the PR has already been merged, I'll also close this issue.

Please re-open if the problem persists.

**Comment by bernhard-kleine** [comment]
It works.
