### ISSUE TITLE
Use Eclipse Collections

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3023]
Context: #2837, #2533, #2247

[Eclipse Collections](http://www.eclipse.org/collections/) seem to be be more memory efficient than standard Java Implementations.

Should we try to switch to Eclipse Collections?

![grafik](https://user-images.githubusercontent.com/1366654/28246188-8d1ff41a-6a14-11e7-9f2f-bd6b93623c7b.png)

![grafik](https://user-images.githubusercontent.com/1366654/28246190-9c54b434-6a14-11e7-95a8-6eb2e6edf769.png)

![grafik](https://user-images.githubusercontent.com/1366654/28246189-96a460e8-6a14-11e7-862a-606c9edc96c3.png)

**Comment by Siedlerchr** [comment]
I would vote against switching as we then heavily depend on an external
library for core features and switching back would be a problem then.


Am 18.07.2017 10:55 vorm. schrieb "Oliver Kopp" <notifications@github.com>:

**Comment by koppor** [comment]
Fir the first months, I would just use their implementations and rely on the normal Java interfaces. (Is that [item 18](https://github.com/mgp/book-notes/blob/master/effective-java-2nd-edition.markdown#item-18-prefer-interfaces-to-abstract-classes) of Effective Java?)

Thus, it would be "just" another dependency. 😇

**Comment by koppor** [comment]
Drop-in replacements are listed at https://github.com/eclipse/eclipse-collections/blob/master/docs/guide.md#-basic-collection-types

**Comment by koppor** [comment]
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.
