### ISSUE TITLE
SAO NASA ADS plugin writes garbage into bib file.

### ISSUE THREAD

**Issue by RafiKueng** [JabRef/jabref#3035]
1. add < new entry >
2. use id based entry generator
3. ID type SAO NASA ADS
4. enter "1920RSPTA.220..291D", < generate >
5. the resulting .bib file looks like:

```
Query Results from the ADS Database


Retrieved 1 abstracts, starting with number 1.  Total number selected: 1.

@Article{1920RSPTA.220..291D,
  author  = {Dyson, F. W. and Eddington, A. S. and Davidson, C.},
  title   = {A Determination of the Deflection of Light by the Sun's Gravitational Field, from Observations Made at the Total Eclipse of May 29, 1919},
  journal = {Philosophical Transactions of the Royal Society of London Series A},
  year    = {1920},
  volume  = {220},
  pages   = {291-333},
  doi     = {10.1098/rsta.1920.0009},
}

@Comment{jabref-meta: databaseType:biblatex;}
```
please note the first two lines.

JabRef version 3.8.2 in biblatex mode on OpenSuse

**Comment by Siedlerchr** [comment]
Thanks for the info, this is also a problem in the current 4.0 version. We will see if we can contact either the authorities responsible for this or provide a fix in JabRef.

This is also the reason for the failing fetcher test

**Comment by tobiasdiez** [comment]
A fix similar to the code from the [MathSciNet fetcher](https://github.com/JabRef/jabref/blob/56a4c5d5c003e18b74c0e12f4133209e23368753/src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java#L112) should work.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
