### ISSUE TITLE
Jabref freezes when dragging entries to groups panel or moving entries within groups

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#3036]
JabRef version 4-beta2 on Ubuntu 16.04 with open JDK 1.8.0_131 (happens also under Windows 7)

Steps to reproduce:

Issue A:
1. Drag new entry into a group
2. Jabref freezes - need to kill process to continue

Workaround: Assign a new entry to a group by  using right-click context menu -> add to group
This will add an article to the assigned group.

Issue B:
1. Drag an entry in the groups menu into a different position
2. Jabref freezes - need to kill process to continue

Workaround: None found yet.

**Comment by AEgit** [comment]
I can confirm both issue A (dragging an item/article to a group) and issue B (dragging a group to a new position in the groups panel) on:

JabRef 4.0-dev--snapshot--2017-07-19--master--2f12fecfb
Windows 10 10.0 amd64 
Java 1.8.0_141

**Comment by bernhard-kleine** [comment]
The available snapshot does not solve this. Where to get the files?

**Comment by matthiasgeiger** [comment]
Hi!
Please try the Files from http://builds.jabref.org/fixGroupFreez/ 

Thank you!

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by juejung** [comment]
@Siedlerchr, @matthiasgeiger. Development version from 7/31/2017 has resolved the issue. I tested it on Ubuntu 16.10 and on Windows 7. Thank you for the quick fix.

**Comment by AEgit** [comment]
I can confirm that this issue is fixed in:
JabRef 4.0-dev--snapshot--2017-08-06--master--ee4f25242
Windows 10 10.0 amd64 
Java 1.8.0_141
