### ISSUE TITLE
overriding fail for journal abbreviation

### ISSUE THREAD

**Issue by jhshinn** [JabRef/jabref#3044]
JabRef version 4.0beta2 on Windows 10

Steps to reproduce:

1. add a custom journal abbreviation file using `Options` - `Manage journal abbreviations`
2. press the switch button in the `Journal` field in the entry edit window.

Here are my bib file and journal-abb file.
https://www.dropbox.com/s/z1w5kr0igpp3j8n/temp.bib?dl=0
https://www.dropbox.com/s/jqgr28q9n8zbbxy/ADS%20journal%20abb.txt?dl=0

**Comment by lenhard** [comment]
I have tested this on current master with your bib file and journal abbreviation files. When I load both files, I can click the switch button and JabRef correctly switches between the full name and the abbreviated name.

Does this problem still exist? Can you clarify how to reproduce it?

**Comment by jhshinn** [comment]
@lenhard sorry for the confusion. I have found that my abbreviation file does not follow the format described [here](http://abbrv.jabref.org/). I was not aware of the format change. I confirmed that the custom abbreviation works seamlessly with the current master snapshot.

**Comment by lenhard** [comment]
Ok, thanks a lot for confirming! Then we can close this.
