### ISSUE TITLE
Duplicates of fields corrupt Entry Editor display

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3046]
data in a shorthand field gets displayed in a keywords field.

JabRef version 

JabRef 4.0-dev--snapshot--2017-07-19--master--2f12fecfb
Linux 4.8.0-58-generic amd64 
Java 1.8.0_131

Steps to reproduce:

1. In biblatex source tab, enter:

```
@Book{pys,
  title     = {Pātañjalayogaśāstra},
  shorthand = {PYŚ},
}
```

2. switch to the Optional fields tab

3. looks like the attached image.

It's a bit odd too, because the field data area for "shorthand" doesn't display.

![screenshot from 2017-07-24 17-20-55](https://user-images.githubusercontent.com/762246/28530554-847ce5ee-7094-11e7-873e-545d5e006591.png)

**Comment by lenhard** [comment]
I cannot reproduce this on Win7 with current master. Could this be related in some way to a custom field configuration? When I add a `@Book` entry in biblatex mode, then the "Keywords" field is displayed in the General tab and not in the Optional fields tab. Moreover, I have no Shorthand field anywhere in the entry editor.

**Comment by wujastyk** [comment]
Yes, I had diddled with "Customize the entry types."  And by mistake, I had "pubstate" twice in the Book entry type (as is seen in my screenshot above).  When I deleted the extra "pubstate", the display looks correct, and the shorthand displays correctly in the Shorthand field. 

So, it's a recondite buglet.  If you have a field twice in your data entry tab, then you may see artefacts.

Thanks,
Dominik

JabRef 4.0-dev--snapshot--2017-07-19--master--2f12fecfb
Linux 4.8.0-58-generic amd64 
Java 1.8.0_131


![screenshot from 2017-07-24 20-50-06](https://user-images.githubusercontent.com/762246/28539371-b41f5a3a-70b1-11e7-81dc-e0dfaa1c80a8.png)

**Comment by matthiasgeiger** [comment]
Thanks for the update! 
As you noted this is only a minor aspect which will not affect many users - thus, I don't add it to the 4.0 milestone.
