### ISSUE TITLE
Overwriting the biblatex source field crashes Jabref

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3047]
JabRef version  on  4.0.0-dev

Steps to reproduce:

1. click on "New BibTeX entry"
2. click on "biblatex source"
3. paste BibTeX entry

The application freezes and can only be killed.

<details>
  <summary>Log File</summary>
  
  ```
  Opening: /mnt/scratch/test.bib
Unable to parse stored date for field 'timestamp' with current settings. Clear button in calender popup will not work.
  ```
</details>

**Comment by j0hannes** [comment]
The crash happened on Linux (Arch). Using version 4.0.0-dev on OSX it works.

**Comment by Siedlerchr** [comment]
Could you please try the latest snapshot? http://builds.jabref.org/master/

**Comment by j0hannes** [comment]
I reinstalled the jabref AUR package [1]:
```
Downgrading jabref-git (4.0.0_v_2.9.2.r6907.cd939b535-1 -> 4.0_v_2.9.2.r7130.0847f5d15-1)...
```
I expect that pacman is mistaken here regarding the downgrade. Jabref reports version 4.0-dev.

If I repeat the same actions (add new BibTeX entry, overwrite source with valid code, click somewhere) nothing happens, i.e. the entry remains unchanged. If I click on one of the tabs (say Abstract) instead, the entry is correctly processed, no crash.

Thanks.

[1] https://aur.archlinux.org/packages/jabref-git/

**Comment by anassal** [comment]
Exacetly the same with:

JabRef 4.0-dev--snapshot--2017-08-19--master--091383dbe
Linux 4.4.0-92-generic amd64 (Ubuntu16.04)
Java 1.8.0_144

Editing the bibtex (biblatex) source tab then directly clicking on the entry table --> crash.
Editing the bibtex (biblatex) source tab then changing to another tab, then clicking on the entry table --> no crash.

**Comment by Siedlerchr** [comment]
I can not reproduce this: Neither with Ubuntu 16.04 nor with Windows.
Can you try to start JabRef via terminal, e.g. java -jar JabRef.jar and check if there a error or anything related printed?

**Comment by anassal** [comment]
Unfortunately it doesn't produce any error messages.

[AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: [../file].bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case

Then Ctrl+c to terminate.
