### ISSUE TITLE
Dialogs not focued in ubuntu 16.04

### ISSUE THREAD

**Issue by Holzhauer** [JabRef/jabref#3049]
JabRef version 4.0 beta2 on Ubuntu 16.04

Steps to reproduce:

1. E.g., hit the "+" icon in General > Files. Same with exceptions

The icons open up and the user is notfied about the new window but the dialog is not focused as I expect it.

**Comment by jonasstein** [comment]
Do you mean this effect? #2928

**Comment by lenhard** [comment]
For the same reasons as in #2928, we'll close this to hopefully fix this when the JavaFX migration progresses.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by Holzhauer** [comment]
Works on my system (ubuntu 18.04) now. Thanks!
