### ISSUE TITLE
Jabref fetches completly wrong bibliographic data by "Get BibTex data from DOI"

### ISSUE THREAD

**Issue by a7n8xmb** [JabRef/jabref#3051]
JabRef version 4.0-dev on Windows 10
Snapshot version: JabRef_windows-x64_4_0-dev--snapshot--2017-07-25--master--0847f5d15

Steps to reproduce:

1. Try to fetch bibliographic data from DOI: 10.1126/science.1111104 
2. You should get the article "Where Do the Dopants Go?" from 2005 by Roy et al.
3. Instead BibTex fetches the bibliographic data for an article from 1975 ("Dynamic random-dot stereograms reveal up-down anisotropy and left-right isotropy between cortical hemifields" by Breitmeyer et al.)

If I resolve the DOI by my own using http://dx.doi.org/10.1126/science.1111104 I am redirected to the correct Science paper from 2005.

BibTeX source (as exported from Science by downloading the bib file for that specific article This is what I would expect to get fetched by "Get BibTex data from DOI) :
@Article{Roy2005,
  author    = {Roy, Scott and Asenov, Asen},
  title     = {Where Do the Dopants Go?},
  journal   = {Science},
  year      = {2005},
  volume    = {309},
  number    = {5733},
  pages     = {388--390},
  issn      = {0036-8075},
  doi       = {10.1126/science.1111104},
  publisher = {American Association for the Advancement of Science},
  url       = {http://science.sciencemag.org/content/309/5733/388},
}

BibTeX source after "Get BibTex data from DOI"
@Article{Breitmeyer1975,
  author    = {B Breitmeyer and B Julesz and W Kropfl},
  title     = {Dynamic random-dot stereograms reveal up-down anisotropy and left-right isotropy between cortical hemifields},
  journal   = {Science},
  year      = {1975},
  volume    = {187},
  number    = {4173},
  pages     = {269--270},
  month     = {jan},
  doi       = {10.1126/science.1111104},
  publisher = {American Association for the Advancement of Science ({AAAS})},
}

![grafik](https://user-images.githubusercontent.com/17081540/28609878-a4101e64-71e6-11e7-82e1-5765573cedc6.png)

**Comment by matthiasgeiger** [comment]
Hi,
and thanks for your report.

A few words on the implementation of "Get BibTeX from DOI": It is not implemented as a generic way to visit the resolved page of the publisher of an article (here: Science) and download the information provided there as each publisher uses it's own site structure and often there is no BibTeX export possible at all.

Thus, we had to go another way: We are using crossref.org to fetch the BibTeX information for DOIs. 

This works generally fine - however, there seems to be a problem with the article you want to access: http://search.crossref.org/?q=10.1126/science.1111104

The wrong article [stored at PubMed](https://www.ncbi.nlm.nih.gov/pubmed/1111104) has the same identifier `1111104` which seems to cause the trouble...

I'm not sure whether this is a temporarily problem or not (other DOIs are working fine), but nonetheless this is not a problem we, as JabRef developers, can fix.

**Comment by a7n8xmb** [comment]
Thanks Matthias for the explanation of the implementation of the "Get BibTeX from DOI" function. 

I reported the wrong resolving to crossref.org.
