### ISSUE TITLE
Error: Could not find or load main class org.jabref.JabRefMain

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3054]
After fetching the latest jabref today (2017-07-28) it does not start anymore.

Fetch with:
`wget https://builds.jabref.org/master/JabRef--master--latest.jar -O jabref.jar -o jabref_update.log`

start with:

```
java -jar jabref.jar 
Error: Could not find or load main class org.jabref.JabRefMain
```

see also: #2867, but openfx is installed.

```
System Linux Mint 18.2
$ dpkg -l | grep jre
ii  openjdk-8-jre:amd64                          8u131-b11-2ubuntu1.16.04.2                 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64                 8u131-b11-2ubuntu1.16.04.2                 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-9-jre:amd64                          9~b114-0ubuntu1                            amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-9-jre-headless:amd64                 9~b114-0ubuntu1                            amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

$ dpkg -l | grep jfx
hi  libopenjfx-java                              8u60-b27-4                                 all          JavaFX/OpenJFX 8 - Rich client application platform for Java (Java libraries)
hi  libopenjfx-jni                               8u60-b27-4                                 amd64        JavaFX/OpenJFX 8 - Rich client application platform for Java (native libraries)
ii  openjfx                                      8u60-b27-4                                 amd64        JavaFX/OpenJFX 8 - Rich client application platform for Java
```

**Comment by Siedlerchr** [comment]
Which one of your java versions is set as default?  (sudo update-alternatives --config java )

**Comment by jonasstein** [comment]
Thank you, I just checked. Indeed it was JDK9, would it be possible to provide an appropriate error message? 
`Error: JDK9 required, see bug #2594`

However I could start now with
`$ /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar jabref.jar`
Perhaps it helps other Linux Mint (*buntu) users who got here.

**Comment by tobiasdiez** [comment]
I fear it is not possible to present a better error message. The error is thrown by java itself before anything one the side of Jabref is invoked. We are in a similar dead end as for the case where the JavaFX component was missing and where we were also not in the position to report a better error message.

**Comment by matthiasgeiger** [comment]
duplicate of #2594

**Comment by jonasstein** [comment]
Thank you for your comment on this. Just another idea: You could provide an jabreftester.jar 
which just tests if the environment is fine for jabref. #3073

**Comment by ytzemih** [comment]
For me this problem seems to reoccur with JabRef 4.3.1 on Ubuntu 18.04: 

With the OpenJDK version `openjdk version "1.8.0_191"` (/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java), I get
```
java -jar /opt/jabref/JabRef-4.3.1.jar
Error: Could not find or load main class org.jabref.JabRefMain
```
With the Oracle version `java version "1.8.0_201"` (/usr/lib/jvm/java-8-oracle/jre/bin/java), I can start JabRef as usual. 

Because of other reasons, I am normally using OpenJDK, and was just playing around this morning with `sudo update-alternatives --config java` to find a working configuration.

Hope it won't take much to find a fix for this. Best wishes.

**Comment by tobiasdiez** [comment]
@ytzemih see https://github.com/JabRef/help.jabref.org/issues/204

**Comment by ytzemih** [comment]
> @ytzemih see [JabRef/help.jabref.org#204](https://github.com/JabRef/help.jabref.org/issues/204)

Great, thx!
