### ISSUE TITLE
Freeze on delete key

### ISSUE THREAD

**Issue by brian-ammon** [JabRef/jabref#3055]
JabRef 4.0-beta2
Mac OS X 10.12.3 x86_64 
Java 1.8.0_131
Steps to reproduce:

1. Open edit entry dialog
2. Press fn+backspace (= [delete](https://en.wikipedia.org/wiki/Delete_key)) in an entry field
3. JabRef freezes

**Comment by Siedlerchr** [comment]
This is maybe related to #3057

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by brian-ammon** [comment]
JabRef 4.0-dev--snapshot--2017-07-30--master--81e6e8ed6
Mac OS X 10.12.3 x86_64 
Java 1.8.0_131

The issue seems fixed for me now. Thank you!
