### ISSUE TITLE
Beta2 version gets stuck on UTF8 bibtexkey

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3056]
JabRef versionJabRef-4.0-beta2 on  Windows 7 64

Steps to reproduce:

1. any entry 
2. add © to the bibtexkey
3. remove the © and JR goes into Nirwana

![grafik](https://user-images.githubusercontent.com/9216487/28743560-d682ee90-744c-11e7-99b2-a34c815aa687.png)

<details>

 ```
no log file available
```
</details>
JR has to be stopped by the Task Manager, no reaction in the program any further. Serious!
(I have found similar failure when trying to drag an entry to group, will deal with it separately)

**Comment by Siedlerchr** [comment]
Could be the same reason as in #3057 (threading issue)

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
