### ISSUE TITLE
Switching from FileAnnotationTab causes high CPU load

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#3059]
JabRef version 4.0-beta2/`master` on at least Win10

Steps to reproduce:

1. Open the FileAnnotationTab in the EntryEditor of an entry having an attached file
2. Switch to another Tab
3. CPU load goes up until EntryEditor is closed

I was not really able to pin down the exact reason for this... Seems to be yet another Java FX bug caused by the usage of `SwingNode` - at least removing the SwingNode from the FileAnnotationsTab helps  - even a simple SwingNode containing only a simple JLabel reintroduces the behavior...
Memory dump shows hundreds of thousands of `com.sun.javafx.stageFocusUngrapEvent` instances...

Possibly related:
- https://bugs.openjdk.java.net/browse/JDK-8136530 - more or less ignored until now...
- https://bugs.openjdk.java.net/browse/JDK-8144504 - skipped from JDK9 release :-(

I think the best solution would be to migrate this Tab to JavaFX prior the 4.0 release...

@lynyus Do you think you'll find the time to manage this?

**Comment by lynyus** [comment]
On the [javafx-fileannotationtab](https://github.com/JabRef/jabref/tree/javafx-fileannotationtab) branch I am working on a JavaFX implementation of the FileAnnotationTab. Hope the problem goes away as soon as this is finished.

Refs https://github.com/JabRef/jabref/issues/2922
