### ISSUE TITLE
Del key in search box deletes entry

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#3067]
JabRef 4.0-dev--snapshot--2017-08-02--master--63414b030
Windows 10 10.0 amd64 
Java 1.8.0_66
Steps to reproduce:

1. Type a known author in the search box
2. When the first suggestion comes up, hit enter
3. Now press shift+home to select the entire content of the search box and press del
4. The first bib entry is removed (in addition to the contents of the search box)

**Comment by Siedlerchr** [comment]
Do you mean the search field at the top in JabRef or do you mean typing an author in the entry editor?
In the entry editor it works, but apparently not in the search field on top of JabRef.


PS: You should upgrade your java version, the latest java version is 144:
http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by Siedlerchr** [comment]
Same problem as in #2855

**Comment by lc9275** [comment]
Yes I meant in the search box on top.
