### ISSUE TITLE
Tool to check the environment for Jabref

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3073]
I suggest to prepare a tool `jabref-tester.jar` which just tests and reports, if the environment is fine for Jabref-4.x

Reason: 
* There are many bug reports due to wrong versions, or incompatible environment (#2867, ...)
* The output can be used to enhance bugreports.

The tool could print something like
```
Jabreftester version 4.123 compiled 2017-08-07 
Environment test from 2017-08-09 12:30
JDK:     FAILED  Required 8.x    found 9.1234 
OpenFX:  PASSED  Required 1.8x   found 1.82

```

**Comment by lenhard** [comment]
Since all of the dev team is solely focused on fixing bugs right now, I see little chance of this happening unfortunately. But such a tool would be a good idea.

@jonasstein  Given your knowledge on the required setup, could you step in and write this tool?

**Comment by jonasstein** [comment]
Unfortunately, I can not develop this, but I volunteer to test it on different machines. I am finding out the requirements on the hard way at the moment. If there is an up to date dependency list, can we link it here? 
I saw on the `stderr`, that Jabref expects a newer FX library than available on the latest *buntu and Mint distributions. I think this should be one of the early features of this tool, because it affects many (nearly all Linux) users.

**Comment by koppor** [comment]
Is there an indication for a concrete least version? This would help at
debian packaging (https://github.com/koppor/jabref/issues/135) and refining
our installation guide: http://help.jabref.org/en/Installation

Maybe, the solution is to use snaps:
https://github.com/JabRef/jabref/pull/2345

Maybe, someone else takes care of a flatpack -
http://www.makeuseof.com/tag/snaps-vs-flatpaks-whats-difference/

Am 03.08.2017 5:55 nachm. schrieb "Jonas Stein" <notifications@github.com>:

**Comment by Siedlerchr** [comment]
I think it would be easiest to write a shell script to test for java version and the openjfx version:
https://stackoverflow.com/questions/23263826/how-to-find-out-javafx-version

 AFAIK the problem only exists with linux, as the windows installer installs the libs in the right folder I suggest. For linux all libs have to be on the classpath. See my workaround I describe ed in the other issue

For linux: Why don't we use install4j to create linux versions as well?

**Comment by tobiasdiez** [comment]
I second the suggestion that instead of a tool that checks all the requirements an installer that actually installs these required packages is preferable.

**Comment by jonasstein** [comment]
An installer would probably ignore the package management of the distribution. Many installer are blackboxes, nobody knows what they do. I would prefer a solution which distributions can use.

**Comment by lenhard** [comment]
Well, Java can't do that out-of-the-box, at least not that I know. A Java version of such a tool would be no more than a bash script in Java syntax and packaged as a jar. We would still have to check the current OS and know the names of the packages for every distro.
