### ISSUE TITLE
Adding from DOI does not generate timestamp

### ISSUE THREAD

**Issue by a-torgovitsky** [JabRef/jabref#3074]
JabRef version 
JabRef 4.0-dev--snapshot--2017-08-03--master--e9fbf1963
Linux 4.4.0-21-generic amd64 
Java 1.8.0_144
on
Ubuntu 14.04

Steps to reproduce:

1. 
Check on Options --> Preferences --> General --> Mark new entries with addition date
Check on Options --> Preferences --> General --> Overwrite
Field name: timestamp

2. Add an entry by DOI. I have tried several and the same behavior happens. Here is a sample: 10.1002/jae.2557

3. Entry is added, but timestamp is not populated.

I have confirmed that adding an entry manually still creates a timestamp.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/fetcher-timestamp.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by a-torgovitsky** [comment]
I checked the latest master build and the behavior is as expected now. Thanks!
