### ISSUE TITLE
KeyEvent -> keybinding mapper : handle duplicate keys

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3076]
The current code only matches the first finding of the keyEvent to a keycombination to a keyBinding
e.g. the first found entry in the KeyBindings enum will be returned.

This is a problem when multiple dialogs/windows have the same keybinding (e.g Entry Editor and Search bar)

**Comment by tobiasdiez** [comment]
Are there good reasons for allowing the same key combination to trigger different actions (except generic things like "delete" whose target is specified by the current focus)? If not we can just forbid it in the shortcut management dialog and clean up a few shortcuts (e.g. "delete entry" -> "delete")

**Comment by Siedlerchr** [comment]
Generic would be best, I will see if checking for focus works

Am 04.08.2017 11:27 nachm. schrieb "Tobias Diez" <notifications@github.com>:

**Comment by lenhard** [comment]
Fyi: Since we had a few keybinding issues lately, I've added a label for that now.

**Comment by Siedlerchr** [comment]
We currently still have to differ between the javafx keybindings and the swing keybindings, for example javafx expects Esc while swing ESCAPE.  And we have ctrl+ PLUS /MInus for navigating in the entry editor and also for decreasing/increasing font size. The problem is that with the current solution the first enum constant is returned which matches the given keycode/keycombination.

**Comment by Siedlerchr** [comment]
As we completely switched to javafx, I think this issue is no longer relevant

**Comment by koppor** [comment]
The issue is still relevant. We introduced `org.jabref.gui.keyboard.KeyBindingRepository#matches` to check if the given key event matches a key combination (instead of asking the first match of a keybinding at org.jabref.gui.keyboard.KeyBindingRepository#mapToKeyBinding). - Introduced at https://github.com/JabRef/jabref/pull/11190
