### ISSUE TITLE
Automatically set file links only updates after selecting another entry

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#3087]
JabRef 4.0-dev--snapshot--2017-08-07--master--5ef7d684e
Windows 10.0 amd64 
Java 1.8.0_66

Steps to reproduce:

1. Create new bib entry
2. Make sure the pdf file exist with the right name (<Bibtexkey>.pdf )
3. Click the "Automatically set file link for this entry"
4. Go to the general tab, no file and/or briefcase is shown
5. Select another bibentry and go back to the previous entry
6. Now the briefcase symbol is shown.

Btw, is there a way to disable the briefcase confirmation? For how I use jabref, it just slows down the process.

**Comment by lc9275** [comment]
I see now that my action 3, has nothing to do and files also appear just toggling back and forward between entries after that I have added them. so it seems that button does nothing.

**Comment by sbitzer** [comment]
I can't confirm the slow browsing, but I do see the same file searching behaviour. Does the button for automatically setting file links (or F7) actually do something? Why are (local) file links added only after selecting a different entry?

JabRef 4.0
Linux 3.16.0-38-generic amd64 
Java 1.8.0_144

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by sbitzer** [comment]
Appears to work for me now. Thanks!
