### ISSUE TITLE
Fetchin article direcly to group

### ISSUE THREAD

**Issue by novak82** [JabRef/jabref#3088]
JabRef version JabRef-4.0-dev--snapshot--2017-08-08--master--3acd1f8d0.jar on Windows 10

Steps to reproduce:

1. Select group that you want to add article in (on left side)
2. Fetch article by DOI

The article is added to selected group (the number of articles is increased by one in left table) but article is not shown in view. You have to select some other group and to came back to original group to see the fetched article.

**Comment by AEgit** [comment]
Probably a duplicate of this (?):
https://github.com/JabRef/jabref/issues/1903

**Comment by lenhard** [comment]
Yes, I agree. This is a specialization of #1903, hence I'll mark it as duplicate and close it. Progress will be tracked in the other issue.
