### ISSUE TITLE
question 1, the web search by doi is gone? why?

### ISSUE THREAD

**Issue by XP2009home** [JabRef/jabref#3099]
JabRef version  on 

Steps to reproduce:

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by XP2009home** [comment]
my default webrowser is firefox, but the jabref insists open url links by interexplorer, i don't know the reseason.

**Comment by matthiasgeiger** [comment]
Hi. As the purpose of the DOI search is to find a new entry we have moved the functionality to the "New Entry" dialog.

And normally JabRef is using the system default browser...

**Comment by lenhard** [comment]
@XP2009home Please direct help request to the support forum http://discourse.jabref.org/ and not to the issue tracker.

**Comment by XP2009home** [comment]
thanks @matthiasgeiger ! the problem mentioned above is found just to the newer jabref version.
