### ISSUE TITLE
Add preference option to disable field validation

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#3100]
In #3090 @tobiasdiez introduced field validation in the entry editor. This is clearly beneficial, but I can image that some users do not want it.

We should add a preference option that disables field validation for the entry editor.

**Comment by lenhard** [comment]
@tobiasdiez Could you please implement this one little addition to your validation feature. It is no big deal and we really need it for 4.0 (user's are complaining about the validation).

**Comment by tobiasdiez** [comment]
I'll have a look next week but can't promise anything.

**Comment by tobiasdiez** [comment]
Sorry, I will not manage to do this in the foreseeable future.

**Comment by lenhard** [comment]
The option (default false) is now implemented and merged. The UI to change it will be added when the feature is fixed in controlsfx. 

Hence this can be removed from 4.0
