### ISSUE TITLE
Move to group works like add to group

### ISSUE THREAD

**Issue by diravan** [JabRef/jabref#3101]
JabRef version 4.0-beta2 on Ubuntu 17.04 with oracle JVM

Steps to reproduce:

1. Add an entry to a group
2. Right click and press move to group
3. The entry is added to the new group but not removed from the old one

**Comment by lenhard** [comment]
I can confirm this.

@tobiasdiez What is the actual desired behavior for "Move to group"? Clear all prior groups and move it to the new one?

**Comment by tobiasdiez** [comment]
@lenhard, yes I also would expect "Move to group" to remove the selected entries from their previous groups and then adds them to the new one. It seems that https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/groups/GroupAddRemoveDialog.java#L176 is missing a `if(move) { foreach group.removeEntries(...)}` statement. 

@diravan, I think you can control the drag & drop behavior by using the Ctrl (and/or Shift) modifier. I.e. holding Ctrl/Shift and drop the entries should move it.
