### ISSUE TITLE
New gitignore config ignores lib folder

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#3106]
In #3091 we updated our gitignore to a suggestion from gitignore.io

Unfortunately, this includes *.jar and this makes git ignore our /lib folder. Tracking this down just cost me a few hours....

@koppor What are your thoughts on this? It means that we cannot blindly take the suggestions from gitignore.io Is there a way to exclude jar files from their generated configuration?

**Comment by koppor** [comment]
Damn it. - Who versions jar files 🤔. I would suggest to keep it (I really like that community-driven approach and especially like the ignore files for latex, jabref, windows, microsoft office) and add a howto to CONTRIBUTING if one wants to add a JAR manually.

**Comment by koppor** [comment]
@github really ignores all `.jar` files: https://github.com/github/gitignore/blob/690a433b668348c33087d34fafe2155ebe8bb4cf/Java.gitignore#L14

**Comment by Siedlerchr** [comment]
We could just add a `!/lib/*.jar ` https://stackoverflow.com/questions/987142/make-gitignore-ignore-everything-except-a-few-files

**Comment by lenhard** [comment]
I have no strong opinion how we adjust the .gitignore file, just that we do it. Right now, parts of our source tree are not in version control. It would probably be best to get rid of the libs (Spin and mac-extensions). But I guess we don't want to drop support for Mac ;)

And we need to make sure that a future update of the .gitignore doesn't break this again.
