### ISSUE TITLE
The General tab in the entry editor is not scrollable.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3117]
JabRef version JabRef 4.0-beta3
Windows 7 6.1 amd64 
Java 1.8.0_131

The display is cluttered!

![grafik](https://user-images.githubusercontent.com/9216487/29386744-6f24ff8c-82dd-11e7-9a61-6a93a339b968.png)

**Comment by lenhard** [comment]
@bernhard-kleine Thanks for reporting.

The fields in a tab of the entry editor are shrunk to fit in the display space that's available to that tab. When there's not enough space for all fields, a scroll pane for the complete tab should appear (it does for me).

What would you suggest to change to make the display less cluttered in the general tab?

**Comment by bernhard-kleine** [comment]
@lenhard 
When there is scrolling possible why not here, the keywords field is not properly visible, so there should be scrolling.

**Comment by lenhard** [comment]
Ok, thanks. The layouting is done by a library we are using, so I have no immediate solution. Maybe it's possible to increase the field size to two rows by default.

**Comment by lenhard** [comment]
@bernhard-kleine Could you perhaps try out this version http://builds.jabref.org/increase-textarea-size/ It assigns a minimum height to all text fields, so hopefully keywords should be more readable and the scroll bar should appear more easily. Do you think that's better? Would you want an even bigger minimum size or a smaller one?

**Comment by bernhard-kleine** [comment]
IMHO this looks much better.

**Comment by lenhard** [comment]
Perfect! The PR is merged now, so we can closed this issue.
