### ISSUE TITLE
Sorting in columns corresponding to additional file types not working

### ISSUE THREAD

**Issue by noravanq** [JabRef/jabref#3119]
JabRef version JabRef 4.0-beta3
Linux 4.4.0-92-generic amd64 
Java 1.8.0_131

Steps to reproduce:

1. Add a new external file type by doing the following:
JabRef preferences-> External programs->Manage external file types->Hit on + to add a new file type (in my case Name xournal, Extension xoj, Application xournal)
2. Restart JabRef
3. JabRef preferences->Entry table columns->Show extra columns->Select xournal
4. Attach some files of the new extension to some of the table entries.

At this point there is a new column in the main table corresponding to the new file type. 

1st issue is that the column header is empty (this is a very minor issue). 
2nd issue is that pressing on the column header doesn't sort according to that column correctly. The expected behaviour is that all the entries which have that type of a file attached should move to the top. This doesn't happen. See 4th column in attached image. 

![jabref](https://user-images.githubusercontent.com/550958/29436462-aac0a572-8379-11e7-8821-43ea36479fb7.png)

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.
