### ISSUE TITLE
Better place for feature requests?

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#312]
Since the importance of a new feature depends on how many people want it, there should be the possibility to vote on feature requests. 
As far as I can see this is not possible in github. So it might be useful to track feature requests somewhere else. Maybe on http://uservoice.com/ or http://feathub.com/ or...

**Comment by stefan-kolb** [comment]
Typical behavior for this is spamming feature requests on Github with :+1: :smile:

**Comment by koppor** [comment]
This is related to https://github.com/isaacs/github/issues/9 and https://www.zenhub.io/, isn't it?

**Comment by oscargus** [comment]
No insight into the core dev team, but personally, I only implement things I want or I for some reason find amusing. I think a possible issue with voting systems is that people may expect that a highly voted feature will actually be implemented.

**Comment by matthiasgeiger** [comment]
Thats one side of the coin - on the other side, this would at least give us developers some feedback which feature are actually requested/required from users.

**Comment by koppor** [comment]
Even though feathub doesn't allow for deletion of a project (see http://feathub.com/feathub/feathub/+28), I vote for using that. It helps us to keep our core issue tracker smaller.

Currently, the feature requests are cluttered around following places:

  * GitHub: https://github.com/JabRef/jabref/labels/feature and possibly https://github.com/JabRef/jabref/labels/enhancement
  * SourceForge: https://sourceforge.net/p/jabref/feature-requests/
  * Wiki: https://github.com/JabRef/jabref/wiki/FeatureRequests-Sorted (which is "only" a view on the sourceforge list)

The latter two will fade out through the years. Then, we have GitHub and feathub only. On the one hand, I see the drawback that cross-linking between GitHub and feathub is not easy. On the other hand, I really like to possibility of ranking things and trying to put the GitHub issue tracker in a directory of "important" issues, whereas feathub would be used to collect "nice-to-have" features.

**Comment by stefan-kolb** [comment]
Postponed to a later date when JabRef is more mature in last dev call.

**Comment by jkulesza** [comment]
While merely a user and in no way a developer for JabRef, I agree with the idea of keeping project-related items as centralized as possible.  Decentralization makes it more work for developers to keep track of everything, more work to ensure all the "moving parts" function together, and more confusing for users to know where the "right place" is for retrieving content, providing feedback, etc.

That said, it would be a good feature request to GitHub itself to have voting buttons made available for each issue/comment/choose your granularity.

**Comment by koppor** [comment]
The last paragraph is https://github.com/isaacs/github/issues/9
