### ISSUE TITLE
Absolute path in JabRef last edited

### ISSUE THREAD

**Issue by alfadaco** [JabRef/jabref#3138]
Hello everybody,

I have JabRef version 3.8.2 on both Ubuntu 12.12 and Mac OS X 10.7.5 and I encountered the following problem.

My set-up is the following: I have all .bib files and the last version of JabRef (the cross platform one) in a Dropbox folder.
I set up the option that opens the last edited file at startup, but when I move across different operating system (like e.g. from Mac to Linux) it doesn't work because it looks for the .bib files using an absolute path (which is different on different systems) instead of a relative one.
So every time I have to re-open all .bib files that were opened on the other system, it's really annoying. Can you fix it guys?

This is not happening with the preferences instead, which are correctly loaded no matter what system you launch JabRef on.

BTW, JabRef is the best!! Great work guys.

Best,
Ale

**Comment by Siedlerchr** [comment]
Hi,

Thank you for your kind words!

In the preferences you need to check the option Use bib file location as
primary file directory
Then it works with relative directories.

It should override all other file directory settings.

PS: you should consider updating to JabRef 4, but beware that the groups
format changed, so a backup of the bib files is recommended

Am 19.08.2017 10:44 nachm. schrieb "alfadaco" <notifications@github.com>:

**Comment by alfadaco** [comment]
Hi,

First of all, thanks you for your prompt response.

Actually, I have that option checked already. In fact, the path of all external files is relative to each .bib file location. The problem is with the path of the .bib iteself, which is stored as an absolute path in the preferences .xml file.

Best

P.S. Thanks for the suggestion. I use JabRef for my research and right now everything is working properly (a part for this absolute path thing). I'll try to update to JB4 when I have a little bit of spare time to check if everything still works properly.

**Comment by stefan-kolb** [comment]
@JabRef/developers  How should this work without an absolute path? What kind of relative path should we use for the last edited file? Starting from which directory? Unfortunately, I don't think this is feasible.

**Comment by alfadaco** [comment]
Hi stefan-kolb,

I understand that your question was not directed to me but, if I may, I would use the position of the .jar file when you launch it. It's very convenient for a cross-platform application.

For example, you could have everything inside a pen drive and, moving together both the .jar and the .bib files would work like a charm.
Instead, for those that have JabRef installed in a fixed position it would be like an absolute path.

It's a win-win in my opinion. =)

**Comment by stefan-kolb** [comment]
For me this is a hack. Makes only sense if you install JabRef in the same location on every computer and the bib file's path is consistent to this directory on every pc. Isn't it a lot easier to just put the bib files in a shareable directory or syymlink mount this directory if you want to work with the bib and Jabref consistently on different PCs? You are expecting a similar experience from JabRef on every PC as for web applications, but it is a local application. If you want this behavior, I suggest to emulate web application storage which means you store your bib files in a globally accessible path, e.g. google drive, dropbox, whatever.

**Comment by alfadaco** [comment]
Ok, maybe I should have better explained myself.

Below I will use
 - "XX fixed" to say that XX remains in the same directory
 - "XX moving" to say that XX changes directory
and I refer to JabRef as the .jar file (the portable version that you can open on every OS)

With absolute path you have this behaviour for last edited:
 - JabRef fixed, BiB fixed: it works
 - JabRef fixed, BiB moving: doesn't work (this of course cannot work)
 - JabRef and BiB moving together: doesn't work

With relative path with respect to JabRef location you have that
 - JabRef fixed, BiB fixed: it works
 - JabRef fixed, BiB moving: doesn't work (this of course cannot work)
 - JabRef and BiB moving together: it works

Since JabRef can be moved between operating systems (it is fairly lightweight), it's not necessarily "local". It's local only when you install it, and in that case you retain the usual behaviour.
This way you can have both JabRef and the Bib inside a pen drive and open your bibliography even on computers without JabRef installed and without installing it.

BTW, Dropbox doesn't work because it can be installed in different places on different systems. It is unlikely that everybody has it in the same place, and certainly this is not true among my colleagues.

Please, let me know if it is more clear now

**Comment by stefan-kolb** [comment]
Ok, I get what you mean. You want a portable version of JabRef including the bib files in some folder.

**Comment by alfadaco** [comment]
Yep, exactly! I think it will be very convenient accessing your bibliography basically everywhere there is a JavaVM running.

I don't know how hard it is, but you could even add a switch in the preferences to toggle the behaviour between the relative one and the absolute one. But this is up to you guys. ;-)

I'm glad we finally understood each other, and thank you for your time.

**Comment by lynyus** [comment]
We'll discuss the feasibility and utility of this in the next devcall and come back to you.

**Comment by koppor** [comment]
- [ ] Store location of last recent files relative to JabRef's location if 
 - a) JabRef is not located in its default directory (Program Files)
 - b) JabRef is located in a parent folder
 - c) JabRef is located in the sub folder

Workaround: Create a `bat` file for Windows and `sh` file opening all bibliographies
