### ISSUE TITLE
Menu bar at wrong position on Mac OS

### ISSUE THREAD

**Issue by cedmfr** [JabRef/jabref#3146]
JabRef version 4.0-beta3
The menu bar is included into the main windows as it should be fixed into the Mac OS menu bar.

**Comment by cedmfr** [comment]
I don't know. Just the menu bar in mac is not included in the current window but stack into the upper bar of the OS.

**Comment by lynyus** [comment]
@cedmfr Can you provide a screenshot to clarify the problem? For me the title bar is quite where I would expect it.

JabRef 4.0-dev
Mac OS X 10.12.6 x86_64 
Java 1.8.0_144

**Comment by cedmfr** [comment]
Please find attached a screenshot of the trouble. In previous Jabref versions those 2 bars were merged on the top bar of macOS.
<img width="1920" alt="capture d ecran 2017-08-28 a 17 31 16" src="https://user-images.githubusercontent.com/31250593/29780741-242a4bb6-8c17-11e7-9851-f6e802adfaa4.png">

**Comment by lynyus** [comment]
@cedmfr thanks for the clarification, I'll investigate the issue.

**Comment by tobiasdiez** [comment]
This could be a consequence of the transition to JavaFX (as the whole application is now started under the JavaFX umbrella https://github.com/JabRef/jabref/blob/45031170ccc6285505599bbdfd0a3445024e31d9/src/main/java/org/jabref/JabRefMain.java#L40). Maybe a related/helpful discussion: https://stackoverflow.com/questions/22569046/how-to-make-an-os-x-menubar-in-javafx

**Comment by chochreiner** [comment]
yes, this is due to the migration to JavaFX.

The current approach in JabRefGUI.java only works with swing.

`       // This property is set to make the Mac OSX Java VM move the menu bar to the top of the screen
        if (OS.OS_X) {
            System.setProperty("apple.laf.useScreenMenuBar", "true");
        }
`


So far I have not found any possibility how to restore this feature for the JMenuBar within a JavFX application.
I fear this can be only fixed as soon as the JMenuBar is also migrated to a JavaFX component.

**Comment by jiajunwu** [comment]
Just curious if there happens to be a chance to resolve this? It seems the above stackoverflow link offers several possible solutions. Would any of them work?

**Comment by lynyus** [comment]
@jiajunwu I have tried this a month ago with some hacks as decribed in the stackoverflow threads, but it seems like we have to go the long way by implementing the whole menubar in javafx to get this working (as @chochreiner  suggested).
We are quite happy to have 4.0 released, as we (hopefully) can now focus on such improvements...

**Comment by LinusDietz** [comment]
This still persists, gave it another try today, but to no avail (;

**Comment by Siedlerchr** [comment]
Seems like we need to migrate the menubar to javafx first

**Comment by Siedlerchr** [comment]
Him could @jiajunwu  @LinusDietz  could you please check if it works in the javafx-global version?

Could you please check the build from https://builds.jabref.org/javafxGlobalEverything/ ?. Thanks! Note this version is in a very early beta stage and might not work as expected. See #3621 for further details.

**Comment by LinusDietz** [comment]
![screen shot 2018-02-20 at 13 31 14](https://user-images.githubusercontent.com/1254003/36424054-61fc1914-1642-11e8-9a94-e316e08c1c3e.png)

not quite

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/javafxGlobalEverything/. Thanks! Note this version is in a very early beta stage and might not work as expected. See #3621 for further details.. Thanks!
