### ISSUE TITLE
"Protect terms" leads to freeze

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3157]
JabRef 4.0-dev--snapshot--2017-08-25--master--2abf65127
Linux 4.8.0-58-generic amd64 
Java 1.8.0_144

Steps to reproduce:

1. Edit in Required Fields tab
2. Select a word and right click mouse
3. Select Protect terms/Add selected term to list/New/Browse
4. Jabref freezes.  
5. Have to "killall java" from the commandline.

![screenshot from 2017-08-25 10-52-27](https://user-images.githubusercontent.com/762246/29723963-e24149c4-8983-11e7-95f5-ab56b3671536.png)

**Comment by Siedlerchr** [comment]
Confirmed also under Windows. Probably one of these threading issues between javafx/swing
