### ISSUE TITLE
Snapcraft image does not allow opening linked files

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#3159]
I followed installation guide from  #3121. JabRef seems to work quite well; but I cannot open the files, linked to bibtex entries (the call of the viewer does not work)
Tested with .pdf and .doc.

JabRef 4.0-dev
Linux 4.12.8-300.fc26.x86_64 amd64 
Java 1.8.0_131

**Comment by ilippert** [comment]
Just as a brief addition: it is well possible to add a file via the + icon to the (Entry editor's) File field.

**Comment by koppor** [comment]
Frozen, because of no time.
