### ISSUE TITLE
Could not save file... Error in field '...': Braces don't match

### ISSUE THREAD

**Issue by MarioLipinski** [JabRef/jabref#3167]
I am using JabRef 4.0 beta3, so i guess #2995 is merged, this issue is identical to #2993.

I am using a shared (PostgreSQL) database and have the "Automatically save the library to" option enabled.

When starting to enter a brace `{` into a field I get an error dialog that sais:

```
Save library
Could not save file...
Error in field '...': Braces don't match.
```

When I disable "Automatically save the library to" this is not an issue.
Also there is a latency while typing.
Maybe you should only sync when leaving the field and not on every keystroke?

**Comment by lenhard** [comment]
@MarioLipinski Thanks for your report.

You've already linked the right issue and PR above. This fixes the same problem for local files, but it seems that shared databases need extra attention.

I think I've found the problem and fixed it (by applying the same solution as we have for local databases). But I haven't worked with the shared database feature before and I have no way of testing this properly. So you'll have to help me a little here. Could you please install the latest build from http://builds.jabref.org/master/ and let me know if the error message is gone?

**Comment by MarioLipinski** [comment]
Just tried _JabRef_windows-x64_4_0-dev--snapshot--2017-08-30--master--07edf68fc.exe_. Unfortunately I still get the error messages and typing is still slow:

![grafik](https://user-images.githubusercontent.com/1518492/29888581-b9bea0d6-8dc1-11e7-9155-72b02d94fcd3.png)

**Comment by lynyus** [comment]
Can confirm this with current master 6f1fda1393ccec1877c573bdedee6c400676f719

**Comment by lenhard** [comment]
Ok, I see. I've done one more try (and accidentally commited directly to master _again_). @MarioLipinski  @lynyus Please try out the latest build from http://builds.jabref.org/master/ currently JabRef-4.0-dev--snapshot--2017-08-31--master--54e0994ba

If this doesn't work, I give up.

**Comment by lynyus** [comment]
@lenhard sorry, still doesn't do the job:
In 3.8.2 you could not close the entry editor when there were unmatched braces. This is possible now.

**Comment by lenhard** [comment]
Ok, strangely it works for me locally.

As I've written above: I give up. Lately, I am spending way too much time trying to fix bugs that others have introduced by merging very premature features.

**Comment by lynyus** [comment]
Thanks to @snisnisniksonah, we finally have a solution for this. Check out the latest build from http://builds.jabref.org/master/ if it works for you.

**Comment by MarioLipinski** [comment]
I am still seeing this issue with current master.

When I open Jabref, Use File -> Connect to shared database and enable 'Automatically save the library to', I am still seeing this issue.
If I close Jabref and reopen, the local file is opened instead but automagically it is still synced to the database (a bit scary though). Then I do not see the errors.

In any case, typing in the text fields is a nightmare caused by a huge delay between pressing a key and the character appearing in the text input.

(btw. there is a translation error for German for the menu entry 'Connect to shared database')
