### ISSUE TITLE
Translations for JabRef v.4.0

### ISSUE THREAD

**Issue by lynyus** [JabRef/jabref#3174]
Dear @JabRef/translators, after three beta versions, we are planning to finally release the major JabRef v4.0 in the end of next week.

We have been working hard on getting JabRef ready for this big milestone and we want to make it as AWESOME as possible.
It would be great if the translations for this major release are as complete as possible, since it might attract some new users which we don't want to disappoint.

Please have a look where you can help us by completing some of the missing translations.

As usual, we would kindly ask @mlep to coordinate this again.

**Comment by mlep** [comment]
Dear @JabRef/translators, you can check the translation status of your preferred language here: https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/TranslatingGUI.md
(I will try to keep it updated).

- For the menus, whatever the language, there is a maximum of 16 strings to translate, so quite easy to get it done for all of us.
- For the JabRef*.properties files, less than 40 strings for Japanese, French,  Spanish, Turkish and Italian, so quite possible to get a full translation for these five languages. Would be nice, indeed.

@lynyus: when is JabRef 4.0 expected to be released?

**Comment by lynyus** [comment]
@mlep: We don't have a concrete date, but today's devcall concluded that it should be released as soon as the issues from the 4.0 Milestone are fixed. https://github.com/JabRef/jabref/milestone/8
Realistically and also to give you sufficient time we (most probably me) do this next Thursday or Friday earliest.

**Comment by mlep** [comment]
@JabRef/translators: with about a week ahead, we should be able to improve significantly the translation of JabRef interface.

**Comment by mlep** [comment]
@frithnanth: Thank you for completing the localization of JabRef in Italian.
JabRef interface is now fully localized for 2 languages (and considering the menus only, 7 languages).

CC: @JabRef/translators

**Comment by mlep** [comment]
@Siedlerchr : Thanks to you, German is the 3rd language with a fully-localized interface.

CC: @JabRef/translators

**Comment by mlep** [comment]
Thank you @koji33 for completing the translation of the JabRef interface (and for the help files, too!).

JabRef interface is now fully localized for 3 languages. For the menus, Spanish an Turkish require the translation of a dozen strings only to get a full localization.

CC: @JabRef/translators

**Comment by mlep** [comment]
@JabRef/translators 
There is only one programming issue to be resolved before the release of JabRef 4.0. So, it is time to tidy up things!
- For the menus, only 10-20 strings are waiting for the following languages: Indonesian, Vietnamese, Swedish, Farsi, Dutch, Russian, Danish, Portuguese and Norwegian.
- For the general files, **a single string** is waiting for translations into Japanese, French and Italian; and about 15 for Spanish and Turkish.

**Comment by lynyus** [comment]
Thanks to everyone! We will release 4.0 quite soon!
