### ISSUE TITLE
syncLang.py: improvements

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#3181]
Following comments in PR #3179, here are ideas for improving syncLang.py:
- automatically generate the translation status with each push to master and publish a html version on jabref.org
- keep a constant order for the table of languages: English first, then alphabetical (or all alphabetical). (I guess it currently depends on the OS)
- put the table of menus first (so that is it not discouraging newcomers with a huge number of strings waiting for translation).
- align to the right the columns with numbers (easier to read, but just a tiny detail).

**Comment by lynyus** [comment]
- [ ] Update to python3
- [ ] Apply object-oriented design principles

**Comment by LinusDietz** [comment]
Successort Issue: https://github.com/JabRef/help.jabref.org/issues/171
