### ISSUE TITLE
Deleting a group via groups interface does not remove that group reference from BibTex source

### ISSUE THREAD

**Issue by Andrew-Lev** [JabRef/jabref#3190]
JabRef 4.0-dev
Linux 4.4.0-92-generic amd64
Java 1.8.0_131

Steps to reproduce:

1. Open group interface. (Groups -> toggle groups interface)
2. Create a group
3. Add an item to the group
4. Right click on the group in the group interface -> remove group and subgroups

The group gets removed but the reference to it in the BibTeX source of each item that was in the group does not. (i.e. groups = {abc}).
This causes an unstable state where jabref might freeze if you try adding that item to another group because of a null pointer.

 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null

**Comment by betheunique** [comment]
This is a bug. It is reproducible. While removing or changing group name from entry editor works fine but from groups menu it shows unexpected behaviour.

**Comment by Andrew-Lev** [comment]
Ah sorry didnt realize that.  Will do so in the future.
