### ISSUE TITLE
JR doesn't send citation commands to TeXworks

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#3197]
JabRef 4.0-beta3
Linux 4.11.0-0.bpo.1-amd64 amd64 on Debian 9 Stretch AMD64
Java 1.8.0_141

Steps to reproduce:

1. Launch TeXworks and JabRef
2. Select a bibliographic item
3. Click on "Send to LaTeX editor"
4. Nothing appens

In settings LaTeX editor is set to default `/usr/bin/texworks`.

Thank you very much in advance.

**Comment by mlep** [comment]
In fact, LatexEditor is a specific software (see http://www.latexeditor.org/).
So, it makes sense that selecting LatexEditor as external program does not work for TeXworks.
In fact, currently, TeXworks is not supported by JabRef (supported editors are Emacs, LatexEditor, Lyx/Kyle, Texmaker, TeXstudio, Vim and WinEdt.

**Comment by Doc73** [comment]
Yes, but
1. LatexEditor is configured to point to `/usr/bin/texworks`
2. I remember that in previous versions of JR it worked very well

Alternatively, can you add support for TW?

**Comment by Siedlerchr** [comment]
I could not find any information regarding commandline usage from Texworks, only that issue:
You could try to see what --help offers 
https://github.com/TeXworks/texworks/issues/113
It would be nice if you could try to find information for inserting citation.
In TexMaker for example it's `-insert`

**Comment by Doc73** [comment]
@Siedlerchr 
Unfortunately, `--help` offers only this:
> Usage: texworks [opts/args]
>   --help, -?   Display this message
>   --position=..., -p=...   Open the following file at the given position (line or page)
>   --version, -v   Display version information

and I'm using the latest stable version 0.6.2 (Apr 2017). :-(

**Comment by Siedlerchr** [comment]
@Doc73 Sorry, then we have no chance to implement this. I would suggest creating an issue at the Texworks repository asking and referencing this.

**Comment by Doc73** [comment]
Yes, I understood. Many thanks! :-)

**Comment by Siedlerchr** [comment]
I close this issue now. If you have more information regarding the command line usage, then feel free to reopen it.

**Comment by vladdobre** [comment]
Hi, can I work on this issue (and assign it to myself?)

**Comment by Siedlerchr** [comment]
TeXWorks must be at least  Version 0.6.9
