### ISSUE TITLE
LatexEditor: defunct ==> drop JabRef support

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#3199]
The latest version of LatexEditor is from 2009 (see http://www.latexeditor.org/news.html).
Maybe the "Push to LatexEditor" could be removed from JabRef?

**Comment by h93xV2** [comment]
I would like to solve this issue.

**Comment by h93xV2** [comment]
If this feature does need to be removed, I would like to do so.

**Comment by BKDevelop** [comment]
Hey,
I am new to the codebase and also still fairly new to java development. My sleepy brain thinks that I solved that issue, but I will check again tomorrow morning before making a pull request.

Cheers,
Ben
