### ISSUE TITLE
Some latex author name characters are deleted in entry list

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#3206]
When an author name has latex in it e.g. "B{\o}rmann," JabRef usually renders it in the entry list.  But not for the attached BibTeX entry.  As shown in the screenshot, "{\DH}alto" is shown as "alto," although it is shown correctly in the preview.

![image](https://user-images.githubusercontent.com/3851891/30247236-e0ce062a-960f-11e7-8fa6-54f6fbce9653.png)

[AuthorProblem.txt](https://github.com/JabRef/jabref/files/1290352/AuthorProblem.txt)

JabRef 4.0-dev--snapshot--2017-09-08--master--007a534d0
Windows 10 10.0 amd64 
Java 1.8.0_121

**Comment by stefan-kolb** [comment]
I think we use https://github.com/tomtung/latex2unicode for that right now, if I'm not mistaken?

**Comment by stefan-kolb** [comment]
So the test would be `{\DH}alto`has to turn into `Ðalto`.
@tomtung Can this be fixed in your library?

**Comment by stefan-kolb** [comment]
Ok, for more information.
This only works with `\usepackage[T1]{fontenc}` and should also be the case for `{\DJ}`.
Not sure if this is handled by latex2unicode.

**Comment by notuntoward** [comment]
Whose feedback is expected?

**Comment by tomtung** [comment]
This can be done by editing the https://github.com/tomtung/latex2unicode/blob/master/src/main/scala/com/github/tomtung/latex2unicode/helper/Escape.scala file and adding those characters. Feel free to open a pull request :)

**Comment by lynyus** [comment]
As you can see I have opened a PR next door at latex2unicode. This should resolve this issue as soon @tomtung makes a new release.

**Comment by lynyus** [comment]
Good news. This should be resolved now in the latest master. You can download and test the newest version from http://builds.jabref.org/master.

**Comment by notuntoward** [comment]
Looks good.  Thanks.
