### ISSUE TITLE
Cannot import groups when opening a bibtex database created by a windows version of jabref with the ubuntu version

### ISSUE THREAD

**Issue by Tsovet** [JabRef/jabref#3215]
I created a bibex database under windows with jabref, when I moved to ubuntu and open the .bib file, I lose all the group information, because it seems the grouping is implemented differently under windows and ubuntu. Therefore I need to recreate all goups by hand..

**Comment by Siedlerchr** [comment]
Are you using different versions of JabRef under windows and linux? Since version 4.0 JabRef has a new group format which is not backwards compatible to the old 3.x format.

For Ubuntu you can try out the latest version as snap: 
https://github.com/JabRef/jabref/issues/3121

**Comment by lynyus** [comment]
Thanks for the report. Please note that the groups have been restructured between 3.8.2. and 4.0. (cf. http://blog.jabref.org/#april-17-2017-–-jabref-4-0-is-on-the-way-–-beta-version-release)...

@Siedlerchr was faster....

**Comment by bernhard-kleine** [comment]
I wonder whether the group information in the individual entries remained. Why not using that information for building the group tree? Then, the group tree at the end of the bib file could be recreated at least without subgroups.

**Comment by lenhard** [comment]
@bernhard-kleine That is exactly how groups work now :) The info is stored as part of the entries.

**Comment by bernhard-kleine** [comment]
But not used to build the tree!

**Comment by lenhard** [comment]
Since there's been no feedback here for quite a while, I am closing this now. Feel free to reopen it when you have retested it with the newest development version on your systems and the error persists.
