### ISSUE TITLE
New entries should be shown when matching the current selection (search, web search)

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3219]
JabRef version 4.0-dev

Steps to reproduce:

1. Search for an author, e.g. Miller.
2. Use web search to find some publications by someone called Miller.
3. Add them.

The new entries are not shown although matching the search expression.

**Comment by tobiasdiez** [comment]
Same concerns filtering by groups: https://github.com/JabRef/jabref/issues/3256

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.
