### ISSUE TITLE
snapshot: file attachments view wrong

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#3222]
relevant for #3121 

I use JabRef 4.0-dev
Linux 4.12.11-300.fc26.x86_64 amd64 
Java 1.8.0_131
as a snapshot.

I get a wrong view about attached files - it shows lots of attached files, whilst only the top file is the one indicated in the raw bibtex code

![file-field](https://user-images.githubusercontent.com/20518297/30478423-451adf72-9a11-11e7-94c0-7c1c77c45f6c.jpg)

![entry raw](https://user-images.githubusercontent.com/20518297/30478432-49543bd8-9a11-11e7-951b-f37f4d951599.png)

**Comment by Siedlerchr** [comment]
Probably resolved when #3210 is merged

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
