### ISSUE TITLE
Check integrity complains on a valid name

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#3225]
JabRef 4.0-beta3
Windows 10 10.0 amd64 
Java 1.8.0_131

Check integrity (biblatex mode) complains on "Names are not in the standard BibTeX format" for the following valid entry:

```
@Article{Kempton2011,
  author       = {Matthew J. Kempton and Ulrich Ettinger and Russell Foster and Steven C.R. Williams and Gemma A. Calvert and Adam Hampshire and Fernando O. Zelaya and Ruth L. O'Gorman and Terry McMorris and Adrian M. Owen and Marcus S. Smith},
  title        = {Dehydration affects brain structure and function in healthy adolescents},
  journaltitle = {Human Brain Mapping},
  date         = {2011},
  volume       = {32},
  number       = {1},
  pages        = {71--79},
  doi          = {10.1002/hbm.20999},
  langid       = {english},
}
```

Also in my opinion the error message should be congruent with the current mode (BibTeX  or biblatex).

**Comment by tobiasdiez** [comment]
I think you are just missing a space between the initials in `C.R. Williams`.

**Comment by crystalfp** [comment]
You are right. Was just this missing space. May I suggest two enhancements?
1) Just minor. If I'm in biblatex mode I found less distracting if the message say: "Names are not in the standard BiBLaTeX format" 
2) Is it possible to expand why the names are not in standard format? I was never thinking of a missing space. Also because it is usual to find these initials without spaces in the literature e.g.  C.A.R. Hoare (example: http://www.cs.ox.ac.uk/people/bill.roscoe/publications/68b.pdf)

**Comment by tobiasdiez** [comment]
Thanks for the feedback. 
1. Yes, I just changed it and it will show the proper message depending on the BibTeX/biblatex mode.
2. No this sadly not possible. But, in the entry editor, you can just rightlick in the "author" field and choose normalize (or something similar) and JabRef actually tries to fix the format on its own.
