### ISSUE TITLE
Jabref slow/hangs on Macbook Air, Sierra

### ISSUE THREAD

**Issue by bdcaf** [JabRef/jabref#3227]
JabRef version JabRef 4.0-dev--snapshot--2017-09-17--master--a0e552925
Mac OS X 10.12.6 x86_64 
Java 1.8.0_144

On my machine Jabref hangs for about 30 minutes as soon as the edit entry window is opened.

Steps to reproduce:

1. Start Jabref
2. Click "New Bibtex Library"
3. Click "New Bibtex Entry"
4. Select "Article"
5. Spinning Beachball for about 30 minutes

<details>
  <summary> Description</summary>
Originally I was working with the beta 3, but on monday I was unable to edit entries, as jabref would hang.  Some older similar questions suggest to use the latest version, so I reinstalled Java and the latest development snapshot and reset the preferences.  By now anything opening the edit window will hang jabref till I kill it.  At first I thought my library is corrupted but I even get the same effect with an empty library.
  
Actually once I happend to leave the window open and after about 30 minutes the edit fields would appear.  But this happens every time I click edit, so it's not really usable.
</details>

**Comment by lynyus** [comment]
@bdcaf that's weird, that would mean that JabRef is basically not usable for anybody on a Mac.

I personally can't reproduce this on my mac, so we need to investigate what's the problem with JabRef on your system.
So please, try the following
1) reboot and test again with a current 4.0-dev build.
2) If this fails try executing JabRef with a runnable jar from commend line (also available here http://builds.jabref.org/master/). Are there any exceptions in the log?
3) if this fails test with JabRef 3.8.2

Please report whether you are connected with the internet when you try JabRef. Also monitor the CPU and RAM usage using the activity monitor. Maybe we find a hint what's the problem.

**Comment by bdcaf** [comment]
Yeah I suppose this is not too common otherwise someone would have noticed.

So I started doing: `java -jar JabRef-4.0-dev--snapshot--2017-09-17--master--a0e552925.jar`

In the console the output is:
```
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
```

The adding the entry is still slow.   In activity monitor there is just 1% CPU utilisation during the "hang", after the time it jumps to around 25% then back to 1%. Memory usage was 255MB before, and 290MB after "hang".  Adding a second empty entry increases memory to 307MB.

The "event log" - under "Help" - "view event log" is empty.  But in the console I got
```
File: errorconsole.fxml not found, attempting with camel case
File: errorconsole.css not found, attempting with camel case
```

I was looking in the usual locations for additional logs in /var/log but couldn't find anything relevant.

**Comment by matthiasgeiger** [comment]
Another idea: can you please export your preferences and then reset the preferences to the defaults. Does this solve the problem?

**Comment by bdcaf** [comment]
I just tried with 3.8.2 and I can add entries as expected. Unfortunately I can not download DOI information with this version.

About the preferences.  It's hidden in the details section, I already tried resetting them.  I also manually removed all Jabref related files that were put in `~/Library/Preferences`.

**Comment by bdcaf** [comment]
I did some research.   [This article](https://dzone.com/articles/macos-sierra-problems-with-javanetinetaddress-getl)  suggests explicitely adding the hostname to `/etc/hosts` - and the window opens after a few seconds.  I did just a short test but it looks promising.  Will close this bug if I can confirm this.   Funny that it was no issue for 3.8.2.

Btw. I followed other leads suggesting that programs in "Accessibility" may be the culprit - but this was not the case for me.

**Comment by matthiasgeiger** [comment]
Thanks for your effort in investigating the problem! 

Hopefully, this is really the underlying problem...

**Comment by Lyr3x** [comment]
adding the hostname explicitely is working for me too.

**Comment by mariondumas** [comment]
This worked for me as well.

**Comment by EfremBraun** [comment]
It's not working for me. Would love to be able to use 4.0 or 4.1, but I've been stuck with 3.8.2.

By the way, when I start Jabref 4.1 from my Mac running Sierra, I get the warning: "Your current Java version (1.8.0_111) is not supported. Please install version 1.8.0_144 or higher. Note that currently, Jabref does not run with Java9."

But per my Java Control Panel, my system has the recommended version of Java, and there's no easy way to update Java from a Mac without using the Java Control Panel. So maybe this is the issue.

**Comment by Siedlerchr** [comment]
@EfremBraun  Hi, you should be able to install the latest version from Oracle directly:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by EfremBraun** [comment]
Updating Java fixed the problem for me.

**Comment by annebeth** [comment]
Adding my Mac hostname (in /etc/hosts) solved the problem for me.
