### ISSUE TITLE
Specify string file to be used in entry preview

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#323]
Some people (like myself) have a separate file with strings containing names for e.g. journals and conferences to keep the naming consistent (one good thing is that more people can use these abbreviations without having to share .bib-files). This is also the case with IEEE, which has the file IEEEabrv. bib (which is supported by JabRef). Now, it would be nice if this file could be specified in the .bib file in some way and that the content from the file in the first place is used to show the "correct" name in the entry preview. Later one could also think of using this file and make a reverse conversion of the abbreviation, just as it works with IEEE at the moment (maybe this is already supported? I do not use the built in abbreviation support except for IEEE).

Normally, this is specified in the TeX-file as

```
\bibliography{IEEEabrv,../ES_Conf_abrv,../ES_Journal_abrv,../oscar}
```

so one would probably need to add something corresponding JabRef specific to the bib-file.

**Comment by oscargus** [comment]
Also see https://sourceforge.net/p/jabref/feature-requests/238/

**Comment by ahlusar1989** [comment]
@koppor I would be happy to address this, if you would like.

**Comment by koppor** [comment]
@ahlusar1989 Sure, every helping hand is welcome! Please take care about good architecture when implementing it. See https://github.com/JabRef/jabref/wiki/High-Level-Documentation.

Looking forward to your first pull request to JabRef!

**Comment by tobiasdiez** [comment]
I think the current support for journal abbreviations is already sufficient and somewhat covers this feature request (or use case). Under "Manage journal abbreviations" you can edit the journal abbreviations and add custom ones.

**Comment by koppor** [comment]
I put it on freeze, because we do not have support for placeholders ("Strings" in BibTeX) in JabRef.
