### ISSUE TITLE
Feature request: file preview with browsers, give access to hypothes.is

### ISSUE THREAD

**Issue by fylimas** [JabRef/jabref#3231]
[Hypothes.is](https://web.hypothes.is/) is a very good annotation methods, to keep the notes on almost everything you can read via a browsers, such as web pages, pdf, epub, etc.

While doing research, the annotation on pdf is a great part of the work. Adobe pdf readers, and others, bound the users and annotations on a single file, and changes the file. This prevent the readers collect all his annotations, and also prevent the communication of annotations among people.

Hypothes.is has solved the above problem.

So it would be great, if jabref could integrate the hypothes.is to enable a  great feature on annotations and collaboration.

**Comment by lynyus** [comment]
Well, I somewhat like the idea, but nobody of the maintainers has time to implement this. We have quite some other issues to work on.

So if someone is eager to work on this give us a shout.

**Comment by FieldsLi** [comment]
Dear maintainers:

Though I do not have the capability to work this out, I still comeup a dirty way to "connect" jabref and hypothes.is. I will put my experience here in case someone need it.

1. Setup a localhost via Google Browser APP `Web Server for Chrome` or `USB webserver`, configure the `localhost directory`, thus the local pdf in the directory can be reached via browser and viewed with pdf.js;
2. Download the project `pdf.js-hypothes.is` of Hypothes.is, extract to the localhost directory with dir `_pdf.js-hypothes.is`;
3. Create a bat file `_view_via_browser.bat` with content in `localhost directory`: 
```bat
set filename="%~nx1"
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --kiosk http://localhost/_pdf.js-hypothes.is/viewer/web/viewer.html?file=/%filename%
```
This bat file will open the pdf in browser with link `http://localhost/_pdf.js-hypothes.is/viewer/web/viewer.html?file=/%filename%`;
4. Options - Preferences - External programs - Manage external file types - PDF applications: `D:\path\to\localhost directory\_view_via_browser.bat`;
* Now the browser will open the corresponding pdf when click `file` icon of each entry of Jabref.
* Click the annotation link on dashboard of Hypothes.is will also create a new tab with the corresponding pdf opened along with annotations.

**Comment by stefan-kolb** [comment]
We currently have no resources for this and will put it on hold temporarliy.
