### ISSUE TITLE
Edit Group window too large for screen with 768px height

### ISSUE THREAD

**Issue by bdcaf** [JabRef/jabref#3232]
JabRef 4.0-dev--snapshot--2017-09-20--master--b0489d5b3
Mac OS X 10.12.6 x86_64 
Java 1.8.0_144

Steps to reproduce:

1. Start JabRef on screen with 768px height
![bildschirmfoto 2017-09-22 um 14 45 04](https://user-images.githubusercontent.com/7136120/30744970-ae661ef4-9fa4-11e7-8322-c762ff057260.png)

As you notice the buttons to confirm and abort are not on screen and not clickable. As about a quarter of the window is empty I don't think it needs to be this big.

Also notice in the main window that the button for adding new groups can not be seen unless one scrolls down.  Again there seems sufficient vertical space to display it.

**Comment by Siedlerchr** [comment]
Refs #2630

**Comment by Siedlerchr** [comment]
Will be treated with #2630
