### ISSUE TITLE
Weird behaviour in PostgreSQL database

### ISSUE THREAD

**Issue by g-mos** [JabRef/jabref#3235]
JabRef version JabRef-4.0-dev--snapshot--2017-09-20--master--b0489d5b3 on  Windows 10 | Ubuntu 16.04

Steps to reproduce:

1. Connect to a shared database
2. Tick automatically save the library to 
3.  Connect

On a database viewer I was monitoring what was done on the database.
The weird thing I saw was, that when Jabref started to connect all the metadata table was deleted. The first thing restored was the databaseType key. Then gradually the program restored back all the information. This is independent if the file I save to, exists or is a new one.  This does not happen to the ENTRY and FIELD tables. It happens both in WIndows and Ubuntu 16.04.
Since db connection is slow at initializing, if it crashes in the middle metadata information can be lost (I have lost the group information once but I cannot repeat that). Maybe this is what had happened.

**Comment by lenhard** [comment]
To add a link to the issue you were referring to  #2647

**Comment by g-mos** [comment]
Some more info I can provide. I do not know what the logic inside Jabref is but database oriented from what I understood:
1. There is an ENTRY table for which per entry it tells what type of entry it is and its version type.
2. There is a FIELD table with multiple inputs per entry with the different fields and the data per field.
3. There is a METADATA table with all the "Unconventional" Information, like the database type, the group structure, the save-actions and the personalized file directory.

I was playing with Wireshark, a program registering all the packages to and forth the database and I saw the following, after the initialisation:
SELECT * FROM "METADATA" 
TRUNCATE TABLE "METADATA" 
INSERT INTO "METADATA"("KEY", "VALUE") VALUES($1, $2) 
The first is absolutely logical but the second and third statements are puzzling me in 2 different ways.

First as I already mentioned the metadata table sometimes gets completely lost. I can say that it has a 10% probability to get lost per opening the program. I am opening and reopening a lot and I can say I restore the metadata table from a backup often.
 
Secondly the database setup is to be used in a group environment. I have it now only with three colleagues where we are experimenting (desktops, laptops etc) resulting in a 12 line table. If I go mainstream in the group I expect at least 20 more lines. Why should Jabref rewrite them every time? 

I hope I helped a little bit in the problem.

**Comment by lenhard** [comment]
@g-mos: @tobiasdiez has implemented a fix for this problem. Could you please check out the version available at http://builds.jabref.org/fix3235/ and see if that solves your issue? Meta data should now be updated instead of deleted and re-inserted.

**Comment by g-mos** [comment]
I have already downloaded this version and I am testdriving it. I will reply tomorrow for sure but until now it seems ok.

**Comment by g-mos** [comment]
Update: Wireshark confirmed that the data are updated and not deleted. Furthermore 4/5 restarts didn't cause a problem yet. As a general question some other weird things that I am seeing in wireshark, irrelevant to this bug where should I discuss them, eg (double login on the db, SELECT * FROM "ENTRY" WHERE "SHARED_ID" = 1 ORDER BY "SHARED_ID" )

**Comment by g-mos** [comment]
After 3 days of working, deleting of the metadata did not happen again, so I can consider the problem fixed and this bug closed.
