### ISSUE TITLE
add to group for several issues only by dragging

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3237]
JabRef 4.0-beta3
Windows 7 6.1 amd64 
Java 1.8.0_144

When I wanted to "add to group" and had selected 15 entries, it did not work: 

Steps to reproduce:

1. Select a couple of entries e.g. 15
2. Right click and choose "Add to group"
3. Select the group e.g. test in the example
4. Press OK and the group indicator indicates that 1 entry has been added.
5. Pressing additional OKs adds further entries to the group.

This is unexpected. One would think this is an error. Is there any reason that I have to click 15 times "OK" to add the selected entries to the group. 

The situation before clicking OK:
![screenshotjabrefaddtogroup1](https://user-images.githubusercontent.com/9216487/30910801-8c573696-a386-11e7-8382-f4b00d9375b2.PNG) 

The situation after clicking OK 6 times.
![screenshotjabrefaddtogroup2](https://user-images.githubusercontent.com/9216487/30910817-9916f952-a386-11e7-88df-efe39b303bc9.PNG)

**Comment by Siedlerchr** [comment]
Refs #2630

**Comment by bernhard-kleine** [comment]
Seems to be solved in 4.0
