### ISSUE TITLE
IEEE preview does not display month

### ISSUE THREAD

**Issue by fylimas** [JabRef/jabref#3239]
Currently, the reference are previewed in Jabref without the field month, as shown in the following:
![image](https://user-images.githubusercontent.com/17979090/30964175-d44f2376-a482-11e7-95d0-cece57920f5c.png)

However, the bib should be and is compiled correctly as follows (in which the month is displayed):
![image](https://user-images.githubusercontent.com/17979090/30964158-c508ab1c-a482-11e7-9fbb-d6b7ef6efaf0.png)

This is consistent as the ieee.csl fromcitationstyles.org
![image](https://user-images.githubusercontent.com/17979090/30964145-b6348e1c-a482-11e7-87dd-7951113d274b.png)

That is to say, jabref handles the field month correctly, but the preview with ieee.csl lack the display of field month.
I think this is an error and should be fixed.

Thanks guys for the great jobs.

**Comment by vatdaell** [comment]
I can look into this and try to fix it

**Comment by tokkot** [comment]
I looked into this some, but got stuck. If the month is a literal string "{january}", the preview prints correctly. So, I think there is a problem with how the month field is getting passed to citeproc-java. Which in turn, is maybe a problem with how the BibTeXEntry object is getting built by JabRef. But I'm really not sure if that is a bug in citeproc-java or in JabRef.

**Comment by Siedlerchr** [comment]
@tokkot  Thanks for your analysis! Maybe you could debug through it and see where the problem lies?
I took a quick look and it seems that the conversion is done outside of JabRef in the citeproc java:
Maybe you can have a look here and an at the DateParser in detail
https://github.com/michel-kraemer/citeproc-java/blob/b60592f4e02876fc06dde233e17b8411a6703408/citeproc-java/src/main/java/de/undercouch/citeproc/bibtex/BibTeXConverter.java#L223

**Comment by koppor** [comment]
Coming from the linked issue:

Possibly, our data model needs to be improved. Currently had a "hack" to be able to store

    month = mar

When entering `mar` in the entry editor, JabRef saves it to

    month = {mar}

How to produce the other result? JabRef offers to enter `#mar#` in the entry editor. Then, the field content is saved without `#`.  See also http://help.jabref.org/en/EntryEditor#field-consistency-checking

**Comment by Siedlerchr** [comment]
Is probably a similar issue as #3539, modifying the StringConverter should do the job

**Comment by DevSiroukane** [comment]
Guys,
I just fix both issues Month preview on IEEE style.
Also, on SourceTab.

Check my last commit here on my repository that I fork.
[My suggested solution](https://github.com/DevSiroukane/jabref/commit/67387113513ce9529e08b62ffc430d13e24f0b4b)

**Comment by Siedlerchr** [comment]
@DevSiroukane  Yeah, cool! Please open a Pull Request. Go to https://github.com/JabRef/jabref/pulls
and create a new Pull Request, on the left you select master and on the right your branch

**Comment by tobiasdiez** [comment]
This is now fixed in the maintable-beta branch.
