### ISSUE TITLE
Text input in authors field has strange behavior

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#324]
It sometimes jumps to another position while entering authors or overwrites text.
Should have todo with any on input actions that may be running.
Experienced while overwriting something like 

``` 
Khajeh-Hosseini, Ali and others
```

with 

```
Khajeh-Hosseini, Ali and Sommerville, Ian and Bogaerts, Jurgen and Teregowda, Pradeep
```

Edit: Should be an auto-completion problem.

**Comment by koppor** [comment]
ACK for auto-completion problem. No idea how to write test cases and how to fix :cry:

**Comment by stefan-kolb** [comment]
See #486

**Comment by stefan-kolb** [comment]
See #644
