### ISSUE TITLE
Command line use doesn’t exit with -n on completion

### ISSUE THREAD

**Issue by davidaknowles** [JabRef/jabref#3247]
JabRef version 4.0-beta3. Mac OS X 10.12.6

Why I care: 
http://discourse.jabref.org/t/command-line-use-doesnt-exit-with-n-on-completion/798

Steps to reproduce:
`java -jar JabRef.jar -n` hangs indefinitely.

**Comment by MrTosz** [comment]
I'll have a go at it, if you don't mind.

**Comment by stefan-kolb** [comment]
Fixed in #3274
