### ISSUE TITLE
Editor: changing bibtype doesn't work properly

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3249]
JabRef 4.0-dev--snapshot--2017-09-29--master--6cca2ed32
Linux 4.10.0-35-generic amd64 
Java 1.8.0_144

Steps to reproduce:

1. open editor
2. click the pencil icon
3. select another bib type
4. nothing changes

5. start again from 2
6. success the second time.

**Comment by lynyus** [comment]
@wujastyk that's odd, on my system this works as it should right away.
Current master
Mac OS X 10.12.6 x86_64 
Java 1.8.0_144

Are there any log messages? Is this behaviour specific to any entry types?

**Comment by bernhard-kleine** [comment]
Here, Jabref 4.0, everything is fine.

**Comment by wujastyk** [comment]
JabRef 4.1-dev--snapshot--2017-10-07--master--fae290caa
Linux 4.10.0-35-generic amd64
Java 1.8.0_144

I can't reproduce this problem with my current JabRef.  JabRef has improved
in other ways too since I started using the
"com.jgoodies.looks.plastic.Plastic3DLookAndFeel" look and feel.  Maybe
there's a connection?

The entry types that used to cause trouble were normally switches between
article, book and incollection (the types I use most often).


​
--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
​,​

Singhmar Chair in Classical Indian Society and Polity
​,​

Department of History and Classics <http://historyandclassics.ualberta.ca/>
​,​
University of Alberta, Canada
​.​

South Asia at the U of A:

​sas.ualberta.ca​
​​

**Comment by Siedlerchr** [comment]
Good news! It indeed could be a problem with the GTK style and environment. 
I close this and you reopen this when you experience problems again
