### ISSUE TITLE
No user info about changing bib-format in 4.0

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#3251]
I tested 4.0 in the past, read the changelog and so on. But not every user does this.

The current stable 4.0 modify the file-format of the bib-file without aksing or even informing the user about it. Writing this in the changelog and in the blog is not enough.

The application itself should do this in the GUI. A big fat warning dialog about what will happen should appear there, when a 3.x-bib-file is opened with a JabRef 4.0! This is IMO a heavy usability bug.

And in the past I suggested this behaviour in the forum while the testing phase of 4.0.

**Comment by koppor** [comment]
This concerns the groups only, doesn't it? I think, we have a groups warning in JabRef 4.0, don't we?

**Comment by buhtz** [comment]
No warning at all.

Because you can not open 4.0-bib-file with JabRef 3.8. it is a big change (for a novice user). Maybe she/he tries out 4.0, don't like it or find out that her/his peers are not updateting to 4.0 and she/he has to step back. This is a heavy change in some use cases and could scare away some novice users from JabRef ("The new update corrupted my data....").

**Comment by lenhard** [comment]
@koppor We have a warning message when someone is using duplicate group names: #3077 You are probably thinking of that.

I have to say that I disagree, though, and find calling this a "heavy usability bug" a bit rich. It's not even a bug. There are plenty of other things in JabRef that would fit this description better. Major releases indicate major changes, that's why you call them major after all. An old version not being able to read something written in the format of a new major version isn't really something totally unusual.

I have no intention of getting into a flame war (and this seems to have potential) on a minor detail, so I won't reply to this thread any further.

**Comment by koppor** [comment]
@buhtz KK. I added "help-wanted", as we are out of resources. If you know someone who can help, please forward hir to https://help.jabref.org/en/FAQcontributing.

**Comment by tobiasdiez** [comment]
I think in principle you are right - a warning message wouldn't hurt and may help some people. However, now it is a bit late since we have already released 4.0 (and the message is not worth to go trough the trouble to release a hotfix). Thus I'll close this issue now.

**Comment by buhtz** [comment]
@koppor @lenhard 
You react to emotional. An Issue/BugReport is not a request to do work on the code or things like that. It is just for documentation of problems/wishes and a place to discuss these things. That is all. It doesn't mean you have to fix that or your software is sh... because the problem is there. Not now and not in the future.

And I think of FOSS-software as a team. For me a warning message like I wish here doesn't matter. I read the blog and doing backups like a paranoid. But a lot of users don't. So I didn't report this because I had the problem. I report this because I think about all users.

JabRef is important on the market. It is my wish and my goal that JabRef has a good standing their and a good image to potential users. JabRef has real potential to kick the commercial and proprietary competitors in the ass. That is why I like and use it. It is not only for me. I never thing about FOSS in an egostic way - I think global. It is not for me. It is for the world.

Because of that I think it would be a nice idea if JabRef would treat data (a bib-file) of the users with more respect and doesn't change the structure/format of it without informing her/him.
