### ISSUE TITLE
Groups view: position of unfold-symbols & heigth of entry-lines & group icons

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#3252]
Using stable 4.0 for your download site with Windows 10. There are three aspects about the groups view.

The __symbols__ for fold and unfold the groups are on the right side/end of each entry. This is unusual compared to tree-views in other software on many operating systems. Maybe their are but currently I am not aware of other software using it this way. It should be possible (per settings dialog) to switch the position to the left.

The __height__ of the lines for each entry are quite heigh. I think this is because of the circle-box around count symbol. It is not only unusual compared to other software. :) It is wasting space on the screen. Can we modify this? It is nice that you currently have users with big screens in mind while developing JabRef. But please don't forget the other ones with small screens or not using JabRef in full-screen mode.

On the left of the group names are __icons__. They are two wide/big and have no functionality. And they look a bit like a fold-unfold-symbol. So you clicking on it and nothing happens before you are aware of the missplaced fold-symbols on the right end of the group name.

**Comment by tobiasdiez** [comment]
The new icons on the left are customizable and were actually a feature requested by users quite a few times. Because of these icons the (un-)fold icons moved to the right (admittedly, a bit unorthodox but not too unusual). I think we will not revert these ui-changes. Note also that you can simply double-click a group to collapse/expand it.

**Comment by buhtz** [comment]
Would it be an option to make the postion customizable by a setting?

**Comment by Druidefix** [comment]
What about the height of the entries? Having many groups I'm now always scrolling...

**Comment by geyslein** [comment]
I'm in for every recommendation made by buhtz. The height of the entries is a bit annoying, I'm scrolling way too much now. I am not so much against putting the symbols to (un)fold on the right but it takes longer to grasp whether a group is folded or not. The two symbols do not differ that much on the first glimpse and the indention of a subgroup is not so big either which both makes it a bit more complicated to distinguish between group and subgroup.

**Comment by AEgit** [comment]
Maybe as a workaround until the issue is fixed: Instead of scrolling in the groups panel, you can just search for a group with the newly implemented groups filter:
https://github.com/JabRef/jabref/pull/2588

**Comment by noMICROSOFTbuhtz** [comment]
4.3.1 problem is there

**Comment by noMICROSOFTbuhtz** [comment]
Could be related #4220

**Comment by noMICROSOFTbuhtz** [comment]
Still exists in 5.* dev

**Comment by noMICROSOFTbuhtz** [comment]
The problem still exists in current 5.* dev
