### ISSUE TITLE
4.0 groups view: what are the up down arrows for?

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#3253]
Please see the up and down arrows on this screen shot. For what they are for? Nothing happens when clicking on them.

![unbenannt](https://user-images.githubusercontent.com/11861496/31170956-66b1fb38-a8fe-11e7-8072-1f4e19b4f766.png)

**Comment by tobiasdiez** [comment]
Those buttons can be used to change the order of side widgets (like group, websearch, open office integration). 

Please use the forum for questions. We try to use github only for bugs and other issues. Thanks!
