### ISSUE TITLE
new imported entries are not shown in table

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#3256]
Using stable 4.0 on Windows 10.

When importing a new entry ("Import into current database" & JabFox AddOn) the entry count of the current selected group is increased correct by one. But the table is not updated. The new entry doesn't appear there.

I have to select another group and then go back to the one where I imported the entry. The the new imported entry (with green color) is shown correct.

**Comment by tobiasdiez** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/3219 (which actually concerns an active search).
