### ISSUE TITLE
4.0 groups view: no automatic unfold while dragging

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#3258]
Using 4.0 stable on Windows 10.

When I drag a bib-entry/publication over a un-folded group which has sub-groups I would expect (compared to other software) that the group will fold after some seconds automaticly.

I would use this future to drag & drop entries to sub-groups which are hidden in un-folded groups.

**Comment by noMICROSOFTbuhtz** [comment]
The problem is still there in 4.3.1 (Win64).

**Comment by AEgit** [comment]
This issue might be related to the same problem that is reported here:
https://github.com/JabRef/jabref/issues/2869

**Comment by Siedlerchr** [comment]
There's already a PR for drag and drop on the maintable which also covers groups. Would you mind to link this as well?

**Comment by AEgit** [comment]
Done: https://github.com/JabRef/jabref/pull/3765#issuecomment-407892996

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
