### ISSUE TITLE
Cannot go through entries with up and down keys

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#326]
Sometimes it just stops at an entry and probably looses focus due to an autosave action?
Editor must be open. Some entries must be marked as incomplete.

**Comment by simonharrer** [comment]
:+1:

**Comment by lenhard** [comment]
Confirmed, this is really annoying.

It is too frequent for autosave (set to 5 minutes in my setting, yet focus is lost every few seconds).

**Comment by matthiasgeiger** [comment]
NOT reproducible here... Even after switching from other programs back to JabRef scrolling is still possible (in "preview" and "edit mode" - with saved or unsaved changes).

**Comment by stefan-kolb** [comment]
Hard to reproduce on master. Closing for now.
