### ISSUE TITLE
Unable to "open folder" in case of filename with spaces

### ISSUE THREAD

**Issue by jamal919** [JabRef/jabref#3264]
JabRef version 4.00 on CentOS 7.1

Expected:
When selecting the "Open folder" from the entry context menu, the folder containing the article should open.

What Happens:
Jabref opens a lot of locations based on the number of words in the name. Every word in the name is appended to the root location and get opened in Nautilus. 
For instance - if the file name is "someone2010 - A Sample file.pdf" saved in ~/, then the following folder will be invoked - 

~/someone2010
~/A
~/Sample
...

Steps to reproduce:
1. Create a BibTeX entry.
2. Attach a file with space in the name
3. Right-click on the entry, Select "Open Folder" or Ctrl + Shift + O

**Comment by stefan-kolb** [comment]
@lynyus Maybe the file path needs to be in quotes? `cmd = "nautilus " + filePath;`

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `nautilus-space-fp`. Please try the latest build from http://builds.jabref.org/nautilus-space-fp.

**Comment by jamal919** [comment]
Great! Thank you :+1:
