### ISSUE TITLE
Automatically create groups and hierarchical keywords

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#3265]
JabRef version 4 on macOS Sierra 10.12.6

I really like the possibility of using groups to organize my bibliography. So when the group format changed, I followed the discussion #1495 where a workaround using the automatic group feature and hierarchical keywords #628 was presented by @tobiasdiez to avoid losing the hierarchy between groups. So when the version 4 has been available, I wanted to try but I cannot find the **Automatically create groups for database** button (it is not in the Groups menu) and I cannot find any option to define a hierarchical delimiter for example. More generally, I cannot find how to use hierarchical keyword with groups.

**Comment by tobiasdiez** [comment]
These are special types of groups. Just use the usual "add new group" dialog and there choose "based on keyword". 
Please use the [discussion forum](http://discourse.jabref.org/) for questions. Github is only used for keeping track of issues and bugs. Thanks!d
