### ISSUE TITLE
Blurry entry editor

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#3268]
JabRef version 4 on macOS Sierra 10.12.6

With the version 4, I noticed that the entry editor becomes blurry when you open an entry and then it becomes normal if you interact with the editor (click on it, or hover your mouse on the name of a pane like "Required fields"). 

I have a recent MacBook Pro with retina and it feels a bit strange. Is it a performance issue ? may be linked to #3175 ?

Not that it bothers me a lot, but I do not know if you were aware of this and I did not find any issue about it.
<img width="554" alt="capture d ecran 2017-10-06 a 11 09 01" src="https://user-images.githubusercontent.com/15056323/31271037-f1d0a96a-aa86-11e7-864d-0d4efd3a6246.png">
<img width="556" alt="capture d ecran 2017-10-06 a 11 09 13" src="https://user-images.githubusercontent.com/15056323/31271038-f1f472a0-aa86-11e7-9842-ea3c5e8c38e1.png">

**EDIT** I just noticed that it happens only on my macbook screen, it does not happen if I use a secondary screen. May be this is related to Retina screens.

**Comment by lenhard** [comment]
I don't think this is directly related to #3175, but it's certainly related to the JavaFX or controlsfx support on mac. Might be somehow related to lazy initialization (at least it reads like that).

**Comment by kbarros** [comment]
I'm having the same problem.

**Comment by tobiasdiez** [comment]
@kbarros Thanks for the feedback. @PierreMarchand20 can you please check the build from http://builds.jabref.org/master/ and see if it is also fixed for you. Thanks!

**Comment by PierreMarchand20** [comment]
I confirm it, it seems fixed in 4.1-dev. Thanks !
