### ISSUE TITLE
Missing characters in the maintable to display titles

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#3270]
JabRef version 4 on macOS Sierra 10.12.6

With version 4, I noticed that a few characters do not work in the maintable. As you can see in the screenshot, math characters and the first letter in upper-case are missing.

<img width="757" alt="capture d ecran 2017-10-06 a 16 16 24" src="https://user-images.githubusercontent.com/15056323/31282080-c5a4c21a-aab1-11e7-9247-7cabb6edf206.png">

**Comment by lenhard** [comment]
This might be down to the font you are using in main table. We are converting LaTeX to unicode there and some fonts have problems with displaying unicode symbols. Could you try playing around with different fonts here? Maybe one that sounds more math-savvy.

**Comment by PierreMarchand20** [comment]
I am using the default font (sans serif), and I tried a few other ones (arial, comic sans ms, courrier...) and I always have the same issue.

**Comment by lenhard** [comment]
We've discussed a similar problem here: #3008 Maybe Cambria Math does the trick?

**Comment by PierreMarchand20** [comment]
Sorry, I have not this font, do you have another suggestion ?

But notice that the first upper-cased letters are also not rendered, so I am not sure it is just a font issue. Besides, in version 3.8, I also used the default font (sans serif, I checked on another computer with JabRef 3.8) and there is no issue as you can see : 
![capture d ecran 2017-10-07 a 15 00 13](https://user-images.githubusercontent.com/15056323/31308077-490fe45e-ab70-11e7-99f6-b0c3208342ad.png)

**Comment by Siedlerchr** [comment]
Well, at least in the preview it should be displayed correctly.  Could you please add the bibtex code for the sample entry?

**Comment by PierreMarchand20** [comment]
This is a small sample illustrating my issue :

'
% Encoding: UTF-8

@Article{Boerm2007,
  author   = {Steffen B{\"{o}}rm},
  title    = {Data-sparse approximation of non-local operators by {$\mathcal{H}^2$}-matrices},
}

@Comment{jabref-meta: databaseType:bibtex;}
'

**Comment by Siedlerchr** [comment]
On Windows 10, setting Table font to **Dialog** solves this for me:
![grafik](https://user-images.githubusercontent.com/320228/31308843-8d65af28-ab7d-11e7-8ce8-57aaad9d7f68.png)

**Comment by PierreMarchand20** [comment]
It did not solve this for me : 
<img width="743" alt="capture d ecran 2017-10-07 a 16 36 55" src="https://user-images.githubusercontent.com/15056323/31308867-d86cbe94-ab7d-11e7-9453-cea702f1425b.png">

**Comment by Siedlerchr** [comment]
For Windows (since 8.1 or 10) the Segoe UI is used. For other math fonts check out here:
http://www.fileformat.info/info/unicode/block/mathematical_alphanumeric_symbols/fontsupport.htm
There are some OpenSource fonts which may be avaiable for Mac. I would vote to close this issue now, as it only depends on the font and OS.

**Comment by PierreMarchand20** [comment]
Well freeserif works for me. But I still do not understand why sans serif worked with version 3.8 and not with 4.0

**Comment by Siedlerchr** [comment]
@PierreMarchand20  Okay good to know!  The reason is simple: We replaced the latex2unicode converter with a new [parser](https://github.com/tomtung/latex2unicode)  which is more flexible and more advanced.

Would you mind editing the corresponding installation notes for Mac OS then by adding some info regarding the Font?
https://help.jabref.org/en/FAQosx

**Comment by PierreMarchand20** [comment]
I tried without success to find a font installed by default on macOS that supports unicode and math characters. It seems that we cannot avoid installing a new one, but luckily, it is pretty easy. Thank you for your answers 👍
