### ISSUE TITLE
JabRef 4.0 for Mac won't quit (MacOS 10.13)

### ISSUE THREAD

**Issue by dpdpdpdpdpdp** [JabRef/jabref#3278]
JabRef version  on 

Steps to reproduce:

1. Choose Quit from File menu.
2. main window closes, but ....
3. the program does not quit, and has to be force-quit.

This is consistent and reproducible on two different machines, both running High Sierra.  (No idea if the problem is specific to this version of the OS.)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by lynyus** [comment]
Can you please state the version of JabRef and Java you use and how do you execute it? From sources/JAR/installed?
You find this information when you click on Help -> About JabRef.

**Comment by michaellass** [comment]
If you are on version 4.0, could you please try the current development build from https://builds.jabref.org/master/? It contains a few related fixes.

**Comment by dpdpdpdpdpdp** [comment]
Yes, the development build fixes that.  I installed it, quit, and the program actually quit.  Thanks!

**Comment by LukasDrude** [comment]
I have the same issue. I also tried this two versions, and it does need force quit to really quit the program.

*JabRef version: 4.3.1*
Mac OS X 10.13.4 x86_64 
Java 1.8.0_171

*JabRef 5.0-dev*
JabRef 5.0-dev--snapshot--2018-08-12--master--04691549e
Mac OS X 10.13.4 x86_64 
Java 1.8.0_171

What other information do you need?
