### ISSUE TITLE
Improve dialog for saving/discarding changes on exit ->Better usability

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#328]
There is room for improvement of the "Save changes on exit".

First of all: When I have opened multiple bib files and then close JabRef, the dialog pops up, but it is not clear which database I save/don't save.
![jabrefsavebeforeclosing](https://cloud.githubusercontent.com/assets/320228/11126768/d0b6eed0-8970-11e5-8b2b-b36bcf84d572.png)

There should be the name of the current database visible.
And furthermore it's bad UI design to ask questions in dialogs.
http://www.informit.com/articles/article.aspx?p=1146301

I suggest the following improvement:
Database changed. Click "Save changes" to  save the changes, click "Discard changes" to discard any changes. Click "return to JabRef" to return back to the main window.

The dialog itself should then have the above mentioned buttons.

This would be a huge improvent in usabilty.

**Comment by simonharrer** [comment]
Thank you for the issue. I second this. 

We are open for pull requests on this one.

**Comment by oscargus** [comment]
@simonharrer : You can assign this to me.

**Comment by oscargus** [comment]
@simonharrer : Not sure if you planned to self-assign it or not. Feel free to do so as well, I can contribute these lines:

``` java
                    String filename;
                    if (baseAt(i).getFile() != null) {
                        filename = baseAt(i).getFile().getAbsolutePath();
                    } else {
                        filename = GUIGlobals.untitledTitle;
                    }
                    int answer = JOptionPane.showConfirmDialog(JabRefFrame.this,
                            Localization.lang("Database %0 has changed. Do you want to save before closing?", filename),
                            Localization.lang("Save before closing"), JOptionPane.YES_NO_CANCEL_OPTION);
```

**Comment by oscargus** [comment]
That is, I'll put it on hold until it is clear who will sort it out. If you want to: go ahead!

**Comment by simonharrer** [comment]
No, I wanted to assign it to you. But it does not work as you are not part of the JabRef organization here on github. Please go ahead and sorry for the assignment mess.

**Comment by oscargus** [comment]
OK! Thanks! :smile:
