### ISSUE TITLE
When PDF file is highlighted without any comment, File annotations display "N/A", it is better to leave it empty

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3280]
JabRef version 4.0 on Windows 10 

Just as the following screenshot, N/A seems a little intrusive for users.

![na](https://user-images.githubusercontent.com/13306020/31342889-974cc6c4-ad40-11e7-8f71-24f902598c74.png)

**Comment by psychelzh** [comment]
And on the left panel, I do think it is best to display the so-called `Marking`, and try to remove `CRLF`/`\n`/'\r' from the content.

**Comment by PammyS** [comment]
@psychelzh @tobiasdiez  I'll be happy to take this. Please assign it to me

**Comment by tobiasdiez** [comment]
@PammyS nice to hear! If you have any questions, feel free to ask here. I can't assign you to this issue since you have not made any contribution before.

**Comment by lynyus** [comment]
I am not sure if we can remove these line breaks from the extracted markings, as it is quite unclear if they come from line break in the paper or from a new paragraph... However, who has a marking spanning several paragraphs or headings?

**Comment by psychelzh** [comment]
I tend to suggest that the line breaks can be safely removed. Just as you put, not many people will try to marking several paragraphs; and if so, they can also be merged, can't they? @lynyus

**Comment by tobiasdiez** [comment]
The `N/A` string is now removed, but the line breaks of the marking are still there. By the way, in https://github.com/JabRef/jabref/pull/3285 I added a new formatter that removes line breaks. So one just needs to run it on the marking.

**Comment by psychelzh** [comment]
You meant that in future releases, users can remove the line breaks mannually? But how can that be done?
