### ISSUE TITLE
Running jar directly fails with error

### ISSUE THREAD

**Issue by nicolasbock** [JabRef/jabref#3284]
When I run
```
$ java -jar JabRef-4.0.jar 
Error: Could not find or load main class org.jabref.JabRefMain
```
The same incantation works for version 3.7. Am I missing something?

**Comment by lynyus** [comment]
Well, if you use linux most probably you are missing the `openjfx` package.  See: https://help.jabref.org/en/FAQlinux#jabref-does-not-start-under-linux-what-can-i-do

**Comment by nicolasbock** [comment]
Thanks @lynyus, that was it!
