### ISSUE TITLE
Focus of entry in table lost when first typing a letter

### ISSUE THREAD

**Issue by miwurster** [JabRef/jabref#3286]
JabRef 4.0
Windows 10 10.0 amd64 
Java 1.8.0_121

Steps to reproduce:
![jabref-tablefocuslost](https://user-images.githubusercontent.com/2610997/31440079-ecd463be-ae8e-11e7-88e4-331cd49b3234.gif)
After the focus is lost, you cannot use the "Generate Bibtex Key" Button any longer, which is really annoying since you have to re-select the entry first; which is even more annoying if you are having lots of entries available.

**Comment by AEgit** [comment]
The following two issues also describe a behaviour where JabRef unexpectedly looses or changes its focus:
https://github.com/JabRef/jabref/issues/2868
https://github.com/JabRef/jabref/issues/3176

If the issue mentioned above is just related to the maintable, the other issues are probably not connected to this problem. If it is not just related to the maintable, it could be a more fundamental problem with the focus (I just wanted to point out that possibility).

**Comment by Siedlerchr** [comment]
From analysis in #3373  I could narrow this dow, that this only happens when the field is used as sorting criteria. As I just updated the description in #3373  I would close this as duplicate
