### ISSUE TITLE
MacOS Sierra - Crash while copy a code to '{}BibTex - sourcecode'

### ISSUE THREAD

**Issue by HopeICanHelp** [JabRef/jabref#3290]
Hello people,

I'm useing a MacBook pro 2012 first Retina edtion, Software macOS Sierra version 10.12.6. Everytime I open 'new BibTex entry' got to '{}BibTex - sourcecode' and than try to copy a code inside the box Jabref crashes. 

Hope my discription was detailed enough. 

Thanks for working on this good programm!

**Comment by lenhard** [comment]
This is likely a duplicate of #3236 Please have a looked at that. A description to a potential fix is also linked in the issue.
