### ISSUE TITLE
GRDLE ERROR 

### ISSUE THREAD

**Issue by vishnudesam** [JabRef/jabref#3297]
I ADDED build.gradle
plugins {
  id "org.sonarqube" version "2.5"
}

gradle.properties
systemProp.sonar.host.url=http://localhost:9000

C:\Users\reddydv\Downloads\sonar-runner-2.4\bin>gradle sonarqube

FAILURE: Build failed with an exception.

Where:
Build file 'C:\Users\reddydv\Downloads\sonar-runner-2.4\bin\build.gradle' line: 2

What went wrong:
Error resolving plugin [id: 'org.sonarqube', version: '2.5']

Could not GET 'https://plugins.gradle.org/api/gradle/3.5/plugin/use/org.sonarqube/2.5'.
Connect to plugins.gradle.org:443 [plugins.gradle.org/104.16.174.166, plugins.gradle.org/104.16.172.166, plugins.gradle.org/104.16.173.166, plugins.gradle.org/104.16.171.166, plugins.grad
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 1 mins 51.35 secs

getting this error when i am running gradle sonarqube

**Comment by Siedlerchr** [comment]
You need to add the repo to gradle:
https://stackoverflow.com/questions/30114860/multiple-maven-repositories-in-one-gradle-file
