### ISSUE TITLE
Linux: ad a file to an article -> JabRef freezes

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#3301]
```
JabRef 4.1-dev--snapshot--2017-10-09--master--1b030b459
Linux 4.10.0-37-generic amd64 
Java 1.8.0_144
```
also with
```
JabRef 4.0
Linux 4.10.0-37-generic amd64 
Java 1.8.0_144
```

Steps to reproduce:

1. Double click on article
2. Go to _General_
3. on the right side of _File_ click on the first icon _Open_
4. Select any file
5. Click on _Open_

My Log details here: (but I think they will be useless)

<details>
  <summary>Terminal Message (nothing from this error)</summary>
    ```
jkalliau@jkalliau-Z87M-D3H:~/prgm$ java -jar JabRef-4.1-dev--snapshot--2017-10-09--master--1b030b459.jar
AI: INFO 13-10-2017 19:32, 20: Configuration file has been successfully found as resource
19:32:17.470 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/Desktop/jk.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7Killed
  ```
</details>

<details>
  <summary>Log File (till just before freezing)</summary>
    ```
Opening: /home/jkalliau/Desktop/jk.bib
  ```
</details>

**Comment by Siedlerchr** [comment]
I can not reproduce this under Ubuntu16.04.3 LTS (Xfce) works as expected. 
You could try to change the Look and Feel. Other users reported problems with GTK L&F

**Comment by JoKalliauer** [comment]
Thank you very much, that solved the problem.

Does not work JabRef frezzes
 - com.sun.java.swing.plaf.gtk.GTKLookAndFeel

Does work:
 - javax.sing.plaf.metal.MetalLookAndFeel
 - com.jgoodies.looks.plastic.Plastic3DLookAndFeel

Warning: Unable to find the reuested look and feel and thus the default one is used.:
 - com.jgoodies.looks.windows.WindowsLookAndFeel
 
 
 Can I change the "Default look and feel"?

**Comment by tobiasdiez** [comment]
No the default look and feel is hard-coded for every operating system. I'm glad that you were able to resolve your issue.
