### ISSUE TITLE
Jabref 4.0 on High Sierra does not import saved citations

### ISSUE THREAD

**Issue by ml115** [JabRef/jabref#3302]
I would like to open the enw type file, but it is gray out.
![screen shot 2017-10-13 at 1 36 42 pm](https://user-images.githubusercontent.com/32778826/31560885-ab9523b4-b01b-11e7-9fa5-a1fc54e2bf5c.png)

 

JabRef version  on 

Steps to reproduce:

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by stefan-kolb** [comment]
Do you try to __open__ or __import__ it?
`File -> Import into library` should work, but `file -> open library` is expected to fail as it only opens bib databases per default!

**Comment by ml115** [comment]
The citation, which I try to import into library was grayed and I was not
able to import it. Also, I was not able to quit JabRef 4.0, I had to force
it
to quit. I downgraded to JabRef 3.8.2.

**Comment by Siedlerchr** [comment]
Could you please test again with the current dev  version?
http://builds.jabref.org/master/

**Comment by ml115** [comment]
Thanks, it works.I have to use Jabref-dev.jar, because when I tried to open
the JabRef-dev.dmg on macos 10.13.1, I got a message that a file is damaged.


Michal
