### ISSUE TITLE
Jabref4 does not open in Mac OSx Sierra 

### ISSUE THREAD

**Issue by shoumitro11** [JabRef/jabref#3306]
I installed Jabref 4, and my environment is OSX sierra 10.12.6
I have java version "1.8.0_144"

Jabref wont open. I can only see Jabref written on the top menubar but nothing else.

I downloaded the platform independent jar file and that works.

**Comment by lynyus** [comment]
Which Java Virtual machine are you using? I mean not just the version, but the whole console output of
`java -version`

**Comment by shoumitro11** [comment]
Here it is:
MacBook-Air:Downloads shoumitrochatterjee$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by shoumitro11** [comment]
Java was the issue. I uninstalled and reinstalled Java and then it worked. Thanks!
