### ISSUE TITLE
Cannot resolve '\textendash', etc. when displaying article title

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3307]
JabRef version `4.0` on Windows 10

See the following screenshot. `\textendash` cannot be resolved to the corresponding character.

![image](https://user-images.githubusercontent.com/13306020/31583271-bd65aa0e-b1ca-11e7-8d63-6a282aaa4f71.png)

![image](https://user-images.githubusercontent.com/13306020/31584134-f5601196-b1da-11e7-9504-fa87875c7413.png)

**Comment by psychelzh** [comment]
Maybe other `LaTex` [Text commands (encoding)](http://tex.loria.fr/ctan-doc/macros/latex/doc/html/usrguide/node28.html) are not resolved, either.

**Comment by lenhard** [comment]
For the record, this is not a problem in latex2unicode which translates the `\textendash` correctly. I guess this s a part of the html translation for the preview.

**Comment by psychelzh** [comment]
Yeah, you are right.
![image](https://user-images.githubusercontent.com/13306020/31586301-9b2011dc-b201-11e7-9644-220b48b2eae1.png)

**Comment by lenhard** [comment]
I added the command to the conversion table. Could you please check out the version here: http://builds.jabref.org/textendash/ and let me know if the problem is resolved at your end?

**Comment by psychelzh** [comment]
Thank you, and I will test it tomorrow, because it is too late here in China.

**Comment by psychelzh** [comment]
Greatm, it works! Here is a screenshot.
![image](https://user-images.githubusercontent.com/13306020/31592237-64bed580-b259-11e7-829e-2b0c28786d40.png)

**Comment by lenhard** [comment]
It's a bit difficult to say what all means here, since we don't really know what is missing.

Could you perhaps provide a list of encoding symbols that you want, but which do not work at the moment? With such a list, it should be no big hassle to complete the implementation.

**Comment by psychelzh** [comment]
No more wrongly encoding ones encountered, only some supported ones, say `\textquotedblleft` and `\textquotedblright`. I guess there could be a complete list in the `LaTex` documentation, e.g. [one](http://tex.loria.fr/ctan-doc/macros/latex/doc/html/usrguide/node28.html) that I had found, but would it be a huge work?

**Comment by lenhard** [comment]
We're trying to minimize developer time consumption :) Hence, it would be cool if someone just checks which of the things listed on the page you you linked are missing.

But overall there are not too many symbols, so this should be doable.

**Comment by psychelzh** [comment]
It would be so kind of you if they are all supported! 👍

**Comment by tobiasdiez** [comment]
@psychelzh If you find symbols that are not working, then you can help us and provide a list in the form
` {"unicode character", "html macro", "$\\latex command$"},`
similar to https://github.com/JabRef/jabref/pull/3308/files#diff-6b1e5b042a6b79fceea700ac0592dbd0R297. Thanks!

**Comment by psychelzh** [comment]
No problem, I am very glad to do this! 😄

**Comment by psychelzh** [comment]
I have tested the `{\textquotesingle}` conversion newly generated developing version
```
JabRef 4.1-dev--snapshot--2017-12-07--master--0ee2090ad
Windows 10 10.0 amd64 
Java 1.8.0_151
```

I checked that this version should have included #3487, but, unfortunately, `{\textquotesingle}` cannot be converted to `'` in the html preview. I wonder whether what I have added works or not. If not, what should be done? @lenhard @tobiasdiez 

![default](https://user-images.githubusercontent.com/13306020/33720392-c6f4d42a-db9e-11e7-8bcc-c376c490dc79.jpg)

**Comment by lenhard** [comment]
@psychelzh I had a look at this and actually the mapping in your PR has not been correct, we should have tested this more. When adding the mapping at this stage, we no longer need brackets or backslashes.

I have fixed the mapping in #3496 and added a test for it as well. With that setting the conversion works for me. Let's wait until this is reviewed and then it should be in master soon.

**Comment by psychelzh** [comment]
Okay. I think I know what happened now. And thank you for your quick response! @lenhard

**Comment by psychelzh** [comment]
@lenhard I have tested on the snapshot version of

```
JabRef 4.1-dev--snapshot--2017-12-08--master--6f39151a7
Windows 10 10.0 amd64 
Java 1.8.0_151
```

And to my surprise, the html preview cannot convert `&apos;` to `'`, either. This is my screenshot.

![image](https://user-images.githubusercontent.com/13306020/33792556-5ee306cc-dcde-11e7-8ed8-26c21c1ccd42.png)

**Comment by psychelzh** [comment]
@lenhard Sorry to disturb you again. Any suggestions about the failure of conversion from `&apos;` to `'`?

**Comment by lenhard** [comment]
@psychelzh Oh my, it seems that our preview component does not handle `&apos;` correctly... 

From https://www.w3.org/TR/xhtml1/#C_16

> The named character reference `&apos;` (the apostrophe, U+0027) was introduced in XML 1.0 but does not appear in HTML. Authors should therefore use `&#39;` instead of `&apos;` to work as expected in HTML 4 user agents.

I've done this replacement in the current dev version and now the apostrophe is displayed correctly in the preview. One day, we'll have a preview panel with better HTML capabilities.

**Comment by tobiasdiez** [comment]
@lenhard Maybe the better rendering comes already with #3504.

**Comment by lenhard** [comment]
@tobiasdiez Yes indeed. I just tested the PR and there `apos;` works as desired. We can change the mapping back in that PR, or keep it as it is.
