### ISSUE TITLE
Distracting visible redraw of entry editor

### ISSUE THREAD

**Issue by ckuhlmann** [JabRef/jabref#3314]
JabRef 4.0
Windows 7 6.1 amd64 
Java 1.8.0_144

Steps to reproduce:

1. open a database
2. double click an entry to bring up the entry editor
3. select another entry using a single click into the database list
4. notice that the entry editor becomes blank for a second until it is redrawn
5. perform the same operation in JabRef 3.8 and notice that this operation is almost instantaneous and no blank entry editor panel can be seen there.

The visible redraw is rather distracting. If would be better if there was no blank period in between.

**Comment by lynyus** [comment]
I think we have a working solution for this, over at http://builds.jabref.org/entry-editor-performance/
Note that this version is a bit older and we could not incorporate this into JabRef yet. (Backup your bibtex database before trying!) Can you give this a try if it is performing better?

**Comment by ckuhlmann** [comment]
Hi lynyus, 
thanks for your quick reply.
With the build you suggested, performance of the editor is much better than the current 4.0 release. 

However, it is not as good as the 3.8 version, since the tabs are still 'sliding in' for me when I change an entry. But since the intermediate blanking of the complete editor is gone it is much less distracting (which is quite telling considering there is movement on the screen). I hope the tabs can be fixed as well in the long run.
Keep up the good work.

**Comment by lynyus** [comment]
thanks for looking into that @ckuhlmann! The new UI technology is quite inevitable from a project management perspective, but of course it needs some more time to become as mature as the old one.

**Comment by lynyus** [comment]
@ckuhlmann You have triggered some activity which made it possible to merge the mentioned version of the entry editor into the current development version of jabref. Regarding the sliding I can't promise a fast solution, but we'll keep working on this.

**Comment by ckuhlmann** [comment]
Hi @lynyus,
Thanks for keeping me posted. I really appreciate your efforts. As I said, this improvement should be a large step in the right direction. I'm happy UI performance will continue to get some attention.
