### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by SilasBerger** [JabRef/jabref#3316]
When running JabRefMain.java as an Application, i get the following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.jabref.JabRefMain.<clinit>(JabRefMain.java:42)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

Process finished with exit code 1
```

I ran all gradle tasks in the _build_ folder, but I keep getting the exception.

**Comment by Siedlerchr** [comment]
> I ran all gradle tasks in the build folder, but I keep getting the exception.

You have to run the gradle tasks in the main folder of the project, where the gradle files reside,
Running: `./gradlew run `

**Comment by SilasBerger** [comment]
Okay, running `./gradlew run` builds and starts the application successfully, thanks. Is there also a way to start it from within an IDE? I imagined that I could in some way build the application, then run JabRefMain.java as a Java Application (in IntelliJ, or Eclipse).

**Comment by halirutan** [comment]
@SilasBerger In IDEA this is simple. Open the project and ensure that you have the Gradle plugin installed first. You start all tasks from the Gradle tool-window on the right side. For the tasks used, you will get a run configuration automatically so that you can restart them by pressing the green run button at the top (or use shortcuts).

**Comment by SilasBerger** [comment]
That was it! I didn't look at the `application `folder in the Gradle tool-window. I just built it with tasks in the `build` folder, then tried to directly run the JabRefMain.java class. Thank you very much for your help!

**Comment by halirutan** [comment]
@SilasBerger Btw, in the preferences under Build, Execution, Deployment -> BuildTools -> Gradle -> Runner you find a check box "Delegate IDE build/run actions to gradle" which might make things even easier.

**Comment by matthiasgeiger** [comment]
Or you import the project as a Gradle project and than simply use the normal 'run' command
