### ISSUE TITLE
New Entry from Plain Text doesn't work

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#3321]
If I do BibTex -> "New Entry from Plain Text" and then click on "article", then I can successfully paste a [bibtex entry](https://www.wind-energ-sci.net/2/477/2017/wes-2-477-2017.bib) into the "paste here box."

But after that, nothing works.

1. I click "accept," JabRef makes a blank bibtex entry (it doesn't matter if I click around on the bibtex choices to the right or use the "insert" button.

2. If I click "parse with FreeCite," JabRef adds a non-empty entry but it's mangled.  See screenshot.

This is with:

JabRef 4.1-dev--snapshot--2017-10-18--master--81ff8f20e
Windows 7 6.1 amd64 
Java 1.8.0_141

![image](https://user-images.githubusercontent.com/3851891/31724097-188acd58-b421-11e7-98ec-1f040a8429b7.png)

**Comment by 125m125** [comment]
The plain text entry creation works different: You are supposed to paste your plaintext (in your case the bibtex) and then mark different sections of the text and assign it to the entry field on the right. For example to add the author you mark "Mittelmeier, N. and Allin, J. and Blodau, T. and Trabucchi, D. and Steinfeld, G. and Rott, A. and K\"uhn, M.", klck author on the right and then click on insert (or double click on author).
If your entry already is in a known format (bibtex in your case) you can simply paste it in the main table and the entry will be created for you.

Maybe it would be helpful to add a new button into the dialog that uses `Globals.IMPORT_FORMAT_READER#importUnknownFormat(String)` to try and parse the pasted text?

**Comment by notuntoward** [comment]
Ah, I didn't hit upon that incantation, especially not the double click.  But what should the Parse with FreeCite button do?

**Comment by 125m125** [comment]
It uses FreeCite( http://freecite.library.brown.edu/ ) to create an entry from your pasted content.

**Comment by notuntoward** [comment]
Should it create an entry like in the screenshot?

**Comment by Siedlerchr** [comment]
@notuntoward  If you already have bibtex code, just paste it on the maintable and it will create a new entry.

**Comment by notuntoward** [comment]
Ah, nice.  I didn't know about that.

But it still seems to me that there are bugs with FreeCite.  Up to you, of course.
