### ISSUE TITLE
Jabref rewrites the entire journal list on addition

### ISSUE THREAD

**Issue by bdcaf** [JabRef/jabref#3323]
JabRef versionJabRef 4.0
Mac OS X 10.13 x86_64 
Java 1.8.0_144

I was surprised that the files from abbrv.jabref.org were rewritten in a randomised order.  This happens under serious CPU and memory usage.  I suppose this is not intended.

Steps to reproduce:

1. clone JabRef/abbrv.jabref.org
2. Select: Options - Manage journal abbreviations
3. Add one of the journal abbreviations
4. Click save changes. In Task Monitor I now see memory jumps from about 200MB to >1GB, CPU load > 100% 
5. The file is now changed with entries in randomised order
6. Possible related - after doing this Jabref takes forever to quit - like minutes.  After the window closes the symbol still stays in the task bar.  Still the same memory and CPU load.
7. If the process is killed at next start the journal abbreviations are not in the list and the process needs to be repeated.

`head journal_abbreviations_ams.txt` now looks like this:

```
Philosophy of Science = Philos. Sci.
Philosophia Naturalis = Philos. Natur.
MIT Press Series in Artificial Intelligence = MIT Press Ser. Artificial Intelligence
Acta Academiae Aboensis = Acta Acad. Abo. Ser. B
Advances in Chemical Physics = Adv. Chem. Phys.
Cahiers de Topologie et Géométrie Différentielle Catégoriques = Cahiers Topologie Géom. Différentielle Catég.
Malaysian Mathematical Society = Bull. Malaysian Math. Soc. (2)
ASA-SIAM Series on Statistics and Applied Probability = ASA-SIAM Ser. Stat. Appl. Probab.
Nonlinear Analysis = Nonlinear Anal.
Problems of Information Transmission = Problems Inform. Transmission
```

**Comment by lenhard** [comment]
The code that does the actual writing of the abbreviations is actually quite simple: 

https://github.com/JabRef/jabref/blob/1751cba4d3a2dde892ac8472bb5766819b0a2559/src/main/java/org/jabref/logic/journals/AbbreviationWriter.java#L29-L38

I don't see an immediate problem in it and the performance problems might simply come from the fact that there are so many abbreviations (around 14 000) if I recall it correctly. Last time I dealt with this, I think also Notepad++ had problems processing the file. I am unsure as to why the sorting is lost. This needs further investigation.

**Comment by Siedlerchr** [comment]
Are the abbreviations somewhere read or stored in a HashMap ? That might explain the different order

**Comment by AEgit** [comment]
Regarding the performance issue: Has the following suggestion already been incorporated into JabRef?
https://github.com/JabRef/jabref/issues/2831

**Comment by bdcaf** [comment]
From user side I would have two suggestions:


1. as it is not intended to change the files - would it be possible to add them read only?
2. as these files are provided by jabref and suggested in the documentation. I think it would make sense either to provide files that don't cause performance issues or clearly point that out in the documentation.

**Comment by lenhard** [comment]
@AEgit As far as I can see this has not yet been addressed.

@bdcaf Regarding 2.: Can you suggest how to provide files that don't cause performance issues? We can delete 75% of the abbreviations. Then performance issues are gone, but that's surely not the right solution. Let me make this clear: The performance problems stem from the fact that the list of abbreviations is so gigantic. There's probably some optimizations that we can do in the code, but that won't make the huge amount of data to process go away. I would be very happy about suggestions on how to improve the file structure!

**Comment by halirutan** [comment]
Maybe I understand something wrong, but I believe the implementation flawed. To explain what I mean, see this memory profile that was collected during exactly what @bdcaf described

![img](http://i.imgur.com/5JkjdiS.png)

This shows the call-tree and you see that the memory consumption goes down to `String.replace`. What troubles me is, why `addEntry` is implemented like this

``` java
    public void addEntry(Abbreviation abbreviation) {
        Objects.requireNonNull(abbreviation);

        if (abbreviations.contains(abbreviation)) {
            Abbreviation previous = getAbbreviation(abbreviation.getName()).get();
            abbreviations.remove(previous);
           LOGGER.info("Duplicate journal abbreviation - old one will be overwritten by new one\nOLD: "
                    + previous + "\nNEW: " + abbreviation);
        }

        abbreviations.add(abbreviation);
    }
```

First the obvious part: We log every duplicate entry to the log file. While this surely was well intended, note that several ten thousand lines are written into the log-file during a run like this that should be fast.

My major question is the following: The `abbreviations` list is a `HashSet` which means it cannot contain duplicates. When I see this right, then [`equals`](https://github.com/halirutan/jabref/blob/277b40c9e79e0158d272de33e24fa7fc06af91bf/src/main/java/org/jabref/logic/journals/Abbreviation.java#L84) for `Abbreviation` is well defined by comparing the keys.

Can someone explain why the costly battle down to `isMatched` is necessary (@simonharrer)? Why can we not simply insert this and let the HashSet remove it?

**Comment by lenhard** [comment]
@halirutan Thanks once again for an in-depth analysis :-)

Maybe we should just remove the logging here or alternatively switch to a log level that will not execute in regular mode.

As for the removal of the abbreviation, I agree with what you write. If `contains()` returns true here, then also `remove()` will operate as expected. I do not know why there should be a need to retrieve the old abbreviation. The implementation of `equals()` in `Abbreviation` seems flawed to me, because it is just based on the `name` and not the actual `abbreviation`. But I do not know if this is intentional and what may break if we change it.

I think we should remove the logging and change the code as you described.

**Comment by halirutan** [comment]
@lenhard I think there is a good reason for the `equals` in Abbreviation. When I see this right, the intention is as follows:

1. There can only be exactly one Journal XXXX, but there can be different abbreviations for it. In JabRef, we always have exactly one current abbreviation for Journal XXXX and we can
    1. insert new Journal names where we currently don't have an abbr for
    2. overwrite existing one if we need a different style

Therefore, making two "Abbreviations" equal by comparing their name sounds OK for me. I would have chosen a different layout for this though.

I tested my fix in mean-time and it runs in maybe 200ms for the largest of those abbr-files with no memory worth mentioning, even with logging. Maybe we should wait for some others to give their OK.

**Comment by lenhard** [comment]
@JabRef/developers What do you think about the proposed solution? Can we go ahead?

**Comment by Siedlerchr** [comment]
All that increases performance is welcomed ;)

**Comment by tobiasdiez** [comment]
The fix suggested by @halirutan looks good to. There are even some tests for the abbreviation stuff so I don't expect that something serious breaks.

This, however, still leaves the question why do we actually rewrite an abbreviation list that just got imported?

**Comment by bdcaf** [comment]
@lenhard about shortening the lists.  IMO the goal should be lists that load efficiently.  

The largest list is web of science having 87230 lines and entrez with 19506 lines.  I had a quick look at them.  There seem to be a serious number of non-english journals - I suppose they could be separated in their own files.  When I look at the webofscience files there are 5745 Proceedings, 3995 Conferences and 2028 Symopsium. Many of which having numbers or years in the full name. Maybe put these in their own file.
