### ISSUE TITLE
File links to author-year bibtex keys extended with an "a" are wrongly automatically added to entry

### ISSUE THREAD

**Issue by sbitzer** [JabRef/jabref#3324]
JabRef 4.0
Linux 3.16.0-38-generic amd64 
Java 1.8.0_144

Steps to reproduce:

1. create entry with bibtex key "xxx2010"
2. put files xxx2010.pdf and xxx2010a.pdf into the file directory of the database
3. let file links automatically update by changing between entries

The problem is that xxx2010a is the standard bibtex key for entries with the same author and year of an existing entry xxx2010 and the files belonging to xxx2010a should not be mixed with those of xxx2010.

**Comment by Siedlerchr** [comment]
You have to adjust the search pattern in the Options->File.
 Probably comes from the fact that you have "Starts with bibtexkey" enabled and not "Only files that match the key"

**Comment by sbitzer** [comment]
Oh, yes, that fixes it. Thanks! Never noticed the option before.
