### ISSUE TITLE
GUI button label is not correctly translated

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#3326]
If you set a different language than English, the search filter button is not correctly translated. In the image below, it is always "Filter" and "Float" no matter the language settings I have. The tooltips for these buttons are not translated either

![img](http://i.imgur.com/pt9REqi.png)

The reason for this is that the string values are initialized as static fields in `org.jabref.gui.search.SearchDisplayMode` when the user language was not loaded. Therefore, they will never be translated.

**Comment by lenhard** [comment]
Should be fixed by #3327
