### ISSUE TITLE
Code for icons

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#333]
Where do I find the code needed for an icon, e.g. where does `"\uf494"` comes from?
```java
ADD("\uf494") /*css: plus-box*/
```

(Background: I want to show the FOLDER("\uf07b") icon, but it is now showing...so probably the identifier is wrong.)

**Comment by matthiasgeiger** [comment]
We are using the IconFont (int the `*.ttf` version) provided by https://materialdesignicons.com/.

The code `"\uXXXX" is the unicode representation of the icon to be used. You can determine the unicode either using *CharMap* tools or by searching for "folder" in the "materialdesignicons.css" available at https://codeload.github.com/Templarian/MaterialDesign-Webfont/zip/master

However, the code for "folder" is correct, as Icon is already used as the Icon for "Open" in the toolbar.

**Comment by tobiasdiez** [comment]
Thanks this helps and solves my problem! (although I still don't understand how the values in the css file correspond to the unicode representation in Jabref...)
