### ISSUE TITLE
Drag and drop of .pdf from JabRef to Freeplane does not work in 4.0

### ISSUE THREAD

**Issue by davydden** [JabRef/jabref#3339]
JabRef version 4.0 on Mac OS X 10.13.

Steps to reproduce:

1. Open a Bibtex with at least one entry with .pdf attached
2. Drag-and-drop .pdf icon from main window in JabRef to a node in Freeplane 1.6.5 to be come a child node
3. Nothing will happen.

This works fine in 3.8. At step (3) a child node is automatically created with a title of the entry and a link to .pdf. 

p.s. Feel free to close this issue if you think it's an expected behaviour. Since it works with 3.8 i though something is wrong with 4.0

**Comment by koppor** [comment]
Note, this is not #121, but the counter part: JabRef seems to have changed the way it handles drop into **other** applications. Maybe something, how we handle mime types?

**Comment by stefan-kolb** [comment]
This is superseeded by two bug reports for 5.0
