### ISSUE TITLE
Feature suggestion: Text file export for "find unlinked files"

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#3341]
`Quality --> Find unlinked files` is handy --  I just used it to discover that an old .bib file has 51 unlinked pdfs.

However, the unlinked files are mostly due to bibkey/pdfname misspellings, and therefore don't need to have a new bib entry made for them -- the only option currently in the interface.

Instead, I'd like to simply export the list of unlinked pdfs to a text file, and then deal with this programmatically, or maybe with some Emacs cut and paste.

I did try `Quality --> Synchronize file links` but that ran for 45 minutes with no result before I gave up on it (there are about 5K entries in this bib file).

**Comment by jssander** [comment]
I'd like to try this as my first issue. Is that ok?

**Comment by Siedlerchr** [comment]
That sounds like a good idea. Just make sure that you name the button so that it is clear what the functionality does

**Comment by jssander** [comment]
Another question: What is the preferred method of writing to a file for JabRef?

**Comment by stefan-kolb** [comment]
When looking at this issue, I ask myself if writing to a file is really the best way to solve this problem or if we need to rework the functionality....

**Comment by tobiasdiez** [comment]
This is now implemented thanks to @jssander.
