### ISSUE TITLE
Find Duplicates marks different book chapters as duplicates

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#3344]
Quality --> "Find duplicates" marks different chapters of the same book as duplicates (see attached example).

JabRef 4.1-dev--snapshot--2017-10-23--master--451b6f3de
Windows 7 6.1 amd64 
Java 1.8.0_151

[notDupes.txt](https://github.com/JabRef/jabref/files/1413987/notDupes.txt)

**Comment by lenhard** [comment]
The duplicate finder is not perfect (far from it) and seems to be happy if titles are the same. There is plenty of room for making the detection algorithm smarter.

**Comment by Naitoreivun** [comment]
I would like to take a look at that issue :)

**Comment by tobiasdiez** [comment]
@Naitoreivun Perfect! If you get stuck somewhere, feel free to post your question here or contact us directly in the [developer chat](https://gitter.im/JabRef/jabref).
