### ISSUE TITLE
Position of Special Field Columns is reset

### ISSUE THREAD

**Issue by devBeginner** [JabRef/jabref#3354]
JabRef version 4.1-dev on Windows

Steps to reproduce:

1. Activate the special fields (rank/priority/...)
2. Change the position of the columns in the table
3a. Go to preferences and click OK, then the columns are shifted to the right of the table
3b. Also after restarting jabref...

**Comment by lenhard** [comment]
It is news to me that you should be able to configure the order of fields in the main table. @JabRef/developers Did a feature like this ever exist?

**Comment by Siedlerchr** [comment]
Interesting. I never cared about this, but I could reproduce this. If I rearrange the columns, the order is not saved upon exiting. But as far as I remember, nobody touched the Maintable code for ages. 
Maybe there is/was a reason to not save this?

**Comment by lenhard** [comment]
@Siedlerchr So this has actually been working at some point? You could actually rearrange columns just by dragging and JabRef would store that somehow?

**Comment by Siedlerchr** [comment]
@lenhard  I actually have no idea if this ever worked. Mabye @koppor  remembers this

**Comment by matthiasgeiger** [comment]
This should work for all "Standard" columns - However the configuration of the Special field order was never possible as they are treated completely different and I had not the nerves to refactor this shitload of messy code 😜

**Comment by devBeginner** [comment]
Maybe it would be helpfull to shift them to the left (should not be as hard as treating them like the other columns).

**Comment by devBeginner** [comment]
@lenhard You can rearrange the "non special" columns and then update the column order in preferences to the one you set up in the table. This is working well, but as mentioned, not for the special columns.

**Comment by devBeginner** [comment]
Hey there,

I managed out, that the order of columns is given by the updateTableFormat() in org\jabref\gui\maintable\MainTableFormat.java.

By moving the code for the special columns after the URL_Column part, the special columns are placed right after url column, in case, that they are activated. I was able to test it locally and seems to work.

**Comment by Siedlerchr** [comment]
Thanks for your analysis of the problem. So if the cols are after URL their position will be stored?

I would say, go for a PR so we can see the changes in the code

**Comment by devBeginner** [comment]
As matthiasgeiger said, storing the position is still not possible. What happens is, that at redrawing the maintable, the special field columns are always added directly after the URL column. The question is, if anyone beside me finds it more convenient to have the columns added to the left.

I will open a PR today or tomorrow so you can see what I mean.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
