### ISSUE TITLE
JabRef never starts

### ISSUE THREAD

**Issue by ianhbell** [JabRef/jabref#3357]
JabRef version 4.0 (windows)

Steps to reproduce:

1. Click on exe installed, or start jabref.exe from console
2. Wait forever...

When I start the exe, jabref never shows up.  I have tried these recommendations, still nothing shows up on the screen: http://help.jabref.org/en/FAQgeneral#q-jabref-does-not-start-what-should-i-do

If I do
```
java -jar JabRef-4.0.jar
``` 
it starts the GUI, but when I kill the GUI it doesn't stop the java instance.

**Comment by AEgit** [comment]
Cannot replicate for:

JabRef 4.1-dev--snapshot--2017-10-26--master--3d4b5104d
Windows 10 10.0 amd64 
Java 1.8.0_151

Could you please report your JabRef version (Is it the stable version of JabRef 4.0?), your Windows and your Java version? Are you running an Antivirus scanner in the background that might block the program?

**Comment by ianhbell** [comment]
I use the stable version 4.0, I can try the dev snapshot too

C:\Users\ihb>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) Client VM (build 25.151-b12, mixed mode, sharing)

**Comment by AEgit** [comment]
Which Windows version are you using (Windows 7, 10, ...)? 32 or 64 bit?
Are you running anything in the background that could prevent JabRef from starting (Antivirus, ...)?

**Comment by ianhbell** [comment]
window 7, 64-bit

I do have antivirus running, but I can't disable it to check if that is the problem.

**Comment by ianhbell** [comment]
Works fine with dev... weird...
