### ISSUE TITLE
key generator fails to parse colon

### ISSUE THREAD

**Issue by jiajunwu** [JabRef/jabref#3359]
It seems that in 4.0 (Mac version), when I customize the key generator to [author][year][veryshorttitle], the generated keys will include the trailing colon if there is one in the title. It also includes other special characters like (`). 

I remember this wasn't the case in 3.6.

**Comment by lenhard** [comment]
Could you please re-check the behavior with the most recent development version available here: http://builds.jabref.org/master/ and report what you find?

Since the release of 4.0 there have been changes in the key generation, which might also have affected this.

**Comment by jiajunwu** [comment]
Sorry, on my mac it says things like file damaged and should be moved to trash. Your FAQ says I can avoid this by changing the security setting to allow apps from 'anywhere', but I don't have this option on my OS (Sierra, 10.12.6).

**Comment by i2000s** [comment]
I can verify that this happens in the latest 11-13 build on Windows:
```
JabRef 4.1-dev--snapshot--2017-11-13--master--c1d425a31
Windows 10 10.0 amd64 
Java 1.8.0_152
```

Not only the special characters like colon or '`' are kept in the key phrase, I also think it is not necessary to keep the curly brackets in the file name when the PDF file is downloaded from the fetcher automatically based on the bibtex information (the curly brackets are from the title entry in the bibtex code). But this could be a separate issue.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
