### ISSUE TITLE
Source field in entry editor is not updated

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#3363]
When editing the title field, the biblatex source field is not updated automatically.

JabRef 4.1-dev
Linux 4.13.8-200.fc26.x86_64 i386 
Java 1.8.0_144

see screencast https://owncloud.itu.dk/index.php/s/70vMaV68KWw8h40

**Comment by lenhard** [comment]
Thanks for reporting! A bigger rework in the entry editor is currently underway, especially regarding the source tab. This should also fix this bug.

Stay tuned!

**Comment by tobiasdiez** [comment]
This should be fixed now with #3366 in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
