### ISSUE TITLE
Entry editor does not reflect change of entry type in bibtex source

### ISSUE THREAD

**Issue by tpet** [JabRef/jabref#3372]
JabRef version: JabRef 4.0
Linux 4.4.8-040408-generic amd64 
Java 1.8.0_151

Steps to reproduce:
1. Create entry with one document type (e.g. Article)
2. In bibtex source tab, change document type to something else (e.g. InProceedings)
3. Switch to another tab - the new document type is not reflected, the fields for the original type are shown

If I'm not mistaken this issue appeared with version 4.

**Comment by Siedlerchr** [comment]
Please try the latest dev version from builds.jabref.org

**Comment by lenhard** [comment]
I think this is still broken in the latest builds.

**Comment by sambo57u** [comment]
My test using the current master did not have this problem.

**Comment by LinusDietz** [comment]
cool!

**Comment by tpet** [comment]
I just tested it with
http://builds.jabref.org/master/JabRef--master--latest.jar
and it still has this problem.

**Comment by Siedlerchr** [comment]
@tpet  We currently have some issues with our build infrastructure due a certificate expiration. So the latest master binary does unfortunately not represent the current git version.
To try this out at the moment you would need to execute 
git clone
gradlew run  to get the latest master-
