### ISSUE TITLE
"Autolink files with names starting with the BibTex key" links entry with wrong BibTex key

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3374]
JabRef 4.0
Windows 10 10.0 amd64 
Java 1.8.0_144

See the following screenshot. **Monsell2003** and **Monsell2003a** are both auto-linked to the entry with **Monsell2003** `BibTex` key.

![image](https://user-images.githubusercontent.com/13306020/32154581-96357d26-bd6c-11e7-978e-a0adc8e0a116.png)

**Comment by Siedlerchr** [comment]
This is accurate behavior, both start with the key. To have exact matches, you have to use the other option in the settings

**Comment by psychelzh** [comment]
OK, I am sorry to put this issue without enough research.

But it might be kind of misleading, because I would think the other option means that the `BibTex` key could be at any location of the file names.

**Comment by psychelzh** [comment]
FYI, see laso #3472
