### ISSUE TITLE
Drag and drop marks groups

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3379]
```
JabRef 4.1-dev--snapshot--2017-10-31--master--42ea6bc9c
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```

I have groups 
```
a
b
c
d

```

reorder `d` by dragging with the mouse 

```
a
d
b
c

```

Now, two groups (not d) are marked blue for no reason.

**Comment by lenhard** [comment]
Just tested this on recent master. Now, selecting d (for dragging) marks this group. When you drop it somewhere else, the marking moves to the group that was in the position of d (which is now c). I guess that is better than the random marking described here.
