### ISSUE TITLE
Accumulate autocompletion of the search box

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3382]
```
JabRef 4.1-dev--snapshot--2017-10-31--master--42ea6bc9c
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```
The dropdown list shows duplicates instead of accumulating them. There is no use or information for the user in the multiple listing. See screenshot:

![jabref - -home-stein-my-uni-thesis-bib-literature bib- biblatex mode _378](https://user-images.githubusercontent.com/298682/32247840-f60f4a0c-be83-11e7-8a77-d8c6c6634c35.png)

It should list only unique matches instead.

**Comment by PJozeph** [comment]
Can I work on this ?

**Comment by Siedlerchr** [comment]
@PJozeph  Sure, go ahead. You do not need to ask everytime. Just check if there isn't already a PR for the issue and then you can work on whatever open issue you want

**Comment by PJozeph** [comment]
what does PR mean?

**Comment by tobiasdiez** [comment]
Pullrequest.
If I remember correctly, then this bug here comes from the library we use (controlsfx). But maybe you find a work-around.

**Comment by PJozeph** [comment]
ohh okay, i would like to understand the concept. Does not matter what i type in search bar i returns nothing. Can you give me some hint how to demonstrate the bug?

**Comment by Siedlerchr** [comment]
Create two entries with the same first name but different last name:
e.g.
entry1: Gustav Adam Test
entry2: Gustav Test
Not sure if required, but both entries should have generated bibtexkeys. Then when you search, it will look like this:


![grafik](https://user-images.githubusercontent.com/320228/34415842-0b8590c2-ebf1-11e7-978a-8039b062da48.png)

**Comment by PJozeph** [comment]
GlobalSearchBar? or what the name of the class which responsible for search ?

**Comment by Ali96kz** [comment]
I can't reproduce these bug. Is these bug still exists?

**Comment by vGsteiger** [comment]
Is this still an issue? In the current version of jabref that I work on I don't get any autocompletion at all.

**Comment by vGsteiger** [comment]
Thank you, we (group of two) will try to work on this for our university project.

**Comment by Siedlerchr** [comment]
@vGsteiger  Sure, go ahead!

**Comment by Siedlerchr** [comment]
@vGsteiger  I just got informed that you succesfully completed your university project and were able to solve this issue. It would be really great to create a PR with your fixes, so that all JabRef users can benefit.
