### ISSUE TITLE
Preferences: Metal Look and Feel is listed twice

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3391]
```
JabRef 4.1-dev--snapshot--2017-11-01--master--84e90719a
Linux 4.12.12-gentoo+ amd64 
Java 1.8.0_152
```

![selection_384](https://user-images.githubusercontent.com/298682/32316492-b5dd4104-bfb0-11e7-893c-c09f706fcc36.png)

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by jonasstein** [comment]
fixed, thank you.

![selection_389](https://user-images.githubusercontent.com/298682/32369800-f38259ec-c08a-11e7-9c44-3eed0d95115d.png)
