### ISSUE TITLE
Untranslated text 

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#3397]
In todays master, for example:

Warning: could not get message translation for "Create_blank_entry_linking_the_PDF" for locale en
Warning: could not get message translation for "Create_entry_based_on_XMP-metadata" for locale en
Warning: could not get message translation for "Create_entry_based_on_content" for locale en
Warning: could not get message translation for "Only_attach_PDF" for locale en

The problem is the old format using the underscore. I think the were missed, when @halirutan improved the language handling. Our tests should be adapted to report warnings in this cases (just report them as not found).

**Comment by Siedlerchr** [comment]
Refs #3184

**Comment by halirutan** [comment]
@tobiasdiez I was aware of that and carefully checked that all usages did not use underscores. There was at this time only one instance that needed to be replaced. I'm sorry, I should have pointed this out more clearly back then: To make a fast cache, the un-quoting and translating of the messages is done on the first instantiation. Messages in code `lang(..)` must not contain the underscored variant but need to be the real message (which is more natural anyway).

**Comment by tobiasdiez** [comment]
@halirutan Its perfectly fine! I actually like that the underscore version does no longer work (it was a relic of old times).

**Comment by halirutan** [comment]
I added a test that will take care of this.

```
java.lang.AssertionError: Language keys must not be used quoted in code! Use "This is a message" instead of "This_is_a_message".
Please correct the following entries:
[
"Create_entry_based_on_content" (src/main/java/org/jabref/gui/preftabs/ImportSettingsTab.java)
, 
"ID-based_entry_generator" (src/main/java/org/jabref/gui/EntryTypeDialog.java)
, 
"Only_attach_PDF" (src/main/java/org/jabref/gui/preftabs/ImportSettingsTab.java)
, 
"Create_entry_based_on_XMP-metadata" (src/main/java/org/jabref/gui/preftabs/ImportSettingsTab.java)
, 
"Create_blank_entry_linking_the_PDF" (src/main/java/org/jabref/gui/preftabs/ImportSettingsTab.java)
] 
```
