### ISSUE TITLE
[Proposal] New UI design

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#341]
I just played around a little bit and created a proposal for the new ui (it's a wireframe, so not meant to display the graphical details but more the general idea).
![UI mockup](https://jabref.mybalsamiq.com/mockups/3795406.png)
More details and an explenation of the numbers are on [Balsamiq](https://jabref.mybalsamiq.com/projects/ui/Main%20screen). You can also find further mockups over there (so far just the [dropdown menu for databases](https://jabref.mybalsamiq.com/projects/ui/DB%20dropdown)). I plan to add more in the coming days.
What do you think about it?

If you want to help and create your own mockups, just create an account on balsamiq and I can add you there as a "staff member" so you should be able to edit/create mockups.

**Comment by lenhard** [comment]
This probably belongs to #113

**Comment by bluebirch** [comment]
Reminds me of BibDesk. That's not a bad thing. :-) CSL formatting in preview and proper biblatex support in editing dialogue, and we're home. :)

**Comment by koppor** [comment]
For me, it's way too early to discuss a new UI. We wanted to start with that next year. First minor feeback: "Database 1" should be a "name" for a database, not the filename. This allows for using "bibliography.bib" in different papers, but having a different label.

Huge feedback: The UI should be based on use cases. Thus, the use cases of JabRef should be collected. Each use case should be weighted how often it is used and the UI designed accordingly. To follow the concept of the least surprise, the UI should be aligned with UI concepts known to the user. Possibly, the [available latex editors](http://tex.stackexchange.com/questions/339/latex-editors-ides) can be used as basis. Alternatively, popular products such Libre Office, Microsoft Office, or Firefox, which are both available on Mac and Windows.

Maybe @SamyStyle can provide us with some references for good UI design and howtos.

**Comment by stefan-kolb** [comment]
Postponed to JavaFX implemantation.
