### ISSUE TITLE
BibTeX - customize entry types ordering issue

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#3411]
Using jabref-4.1-dev 2017-11-07 with java 1.8.0_152 on Linux x86_64.

1. Open a bib file
2. Select Bibtex - customize enttry types from menu
3. Choose Article type (default)
4. Select author and move it to top clcking the up button, order some other things
5. Click Apply

The ordering immediately goes back to its original order and saving the bib file adheres to that
ordering in bibtex entries. I presume this is not the "required" ordering for Article type, in which
case the  possibility to reorder should not be there. I have tested other functions but removing
items does seem to work, namely after the apply button they stay removed.

**Comment by tobiasdiez** [comment]
Probably introduced by my recent PR, where we moved from List to Set and might have lost the ordering on the way.

**Comment by lenhard** [comment]
@tobiasdiez Maybe a `LinkedHashSet` is the way to go: https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashSet.html

It should preserve uniqueness of items and ordering.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

@lenhard Yes, that was the solution!
