### ISSUE TITLE
JabRef hangs when adding PDF file to entry

### ISSUE THREAD

**Issue by sudarshan85** [JabRef/jabref#3417]
JabRef version 4.0 on Ubuntu 16.04
Hello,

JabRef in my system hangs when I try to add the PDF to the entry via the option in the General tab. I have to force a shutdown of the application and have to start it up again. This is a recurring issue and always happens. Please see the screenshot below

![hang](https://user-images.githubusercontent.com/488428/32560794-8598cf3c-c478-11e7-8b92-3bb85374819c.png)

Steps to reproduce:

1. After adding a bibtex entry go to the General tab.
2. Click on the '+' button to add a PDF file.
3. Select the PDF file and click on Open.

Thanks.

**Comment by Siedlerchr** [comment]
Hi,
please try again with the latest master, there have been multiple fixes regarding freezes:
http://builds.jabref.org/master/

**Comment by daniwech** [comment]
Hi,
I encounter the exact same problem (JabRef version 4.0 on Ubuntu 16.04). This happens also when I use the latest master.
Cheers.

**Comment by Siedlerchr** [comment]
@daniwech  Do you use GTK style? Swtich to another Look and Feel (e.g. Plastic)

**Comment by daniwech** [comment]
@Siedlerchr Thanks for the quick response. Yes, I do use GTK style and switching to Plastic resolved the problem.

**Comment by sudarshan85** [comment]
@daniwech Hi could you let me know how you did that?

**Comment by daniwech** [comment]
Hi,

To switch look and feel go:

Options->preferences->Appearance

In the Look and feel section change Class name to 
com.jgoodies.looks.plastic.Plastic3DLookAndFeel

Hope that helps.

**Comment by coronarajan** [comment]
I confirm the same issue and solution:
On Ubuntu 16.04:
Tried jabref 4.0 with jabref freezing on pdf addition. 
Tried latest master with same result. 

Changed the look and feel as suggested by daniwech. Now works fine.

**Comment by technic** [comment]
I also had this issue with JabRef 4.2, switching to default look and feel `MetalLookAndFeel` solved it.
