### ISSUE TITLE
Feature Request: OpenSSL for SQL

### ISSUE THREAD

**Issue by mwessley** [JabRef/jabref#3419]
It would be really nice to include SSL support for the shared database function.
Up to now for SSL encrypted communication, tunneling is necessary.

**Comment by stefan-kolb** [comment]
Would be useful, as many remote DBs are only accessible via SSL.

**Comment by Siedlerchr** [comment]
Refs #4040

**Comment by Siedlerchr** [comment]
Hi,
starting with the current development version, https://builds.jabref.org/master/
 JabRef now supports the usage of SSL for both MySQL and PostgreSQL. 
In a nutshell, you have to convert your certificates for the usage with Java and add them to a (custom) keystore. This file is then specified in JabRef.


I already create a PR for the documentation update for the upcoming 5.0.
Therefore you have to use this link to see the changes.
 Feel free to ask any questions.
https://github.com/JabRef/help.jabref.org/blob/74c3bf244017ba17f7533cd85044a56c9361d1c8/en/SQLDatabase.md
