### ISSUE TITLE
how to clear configuration file

### ISSUE THREAD

**Issue by yangdaweihit** [JabRef/jabref#3423]
JabRef version `3.8.1` on `Debian 9.1`

Jabref menu cannot pop-up. I guess I made some wrong settings in `preference`. So I want to clear the configuration file of jabref, but where is the file in Linux? Please give me some clue. Thank you in advance.

**Comment by LinusDietz** [comment]
Hi @yangdaweihit, you should try an up-to-date JabRef: https://www.fosshub.com/JabRef.html
Does the problem persist?

**Comment by tobiasdiez** [comment]
You can also reset the preferences using the command line: http://help.jabref.org/en/CommandLine#reset-preferences--d-key

**Comment by yangdaweihit** [comment]
@LinusDietz @tobiasdiez Thank you very much. I reset jabref in terminal like this:
```
jabref -d all
```
Then the problem is resolved.
