### ISSUE TITLE
Trouble with using biblatex source tab

### ISSUE THREAD

**Issue by ssblee** [JabRef/jabref#3437]
JabRef version: JabRef 4.0 / Mac OS X 10.13.1 x86_64 / Java 1.8.0_151

I suffer several problems after upgrading to JabRef 4.0.
These problems did not happen before 4.0, so I would say they are bugs.

[Trouble 1] File changed without editing?
The steps to reproduce:
1. I have my 'some_list.bib' open in the entry table.
2. Click any entry from the table.
3. Click the tab 'biblatex source' In the lower part of JabRef window.
4. *Just* click anywhere within the source, without typing anything.
5. Then the file 'some_list.bib' gets into the state changed/unsaved: the file name button shows 'some_list.bib*'. And when I try to close the file, JabRef asks me to save or not. I didn't change anything, but JabRef misunderstands!

[Trouble 2] Not properly working with the 'biblatex source' window.
The steps to reproduce:
1. I have my 'some_list.bib' open in the entry table.
2. Add an entry to the table, by pressing Command+Shift+A, and then by doing copy-and-paste the source.
3. Before upgrading to JabRef 4.0, the information of the new entry was immediately visible. But for the current version 4.0, the new entry (with blue highlight) shows nothing, before I click anywhere else the 'biblatex source' blank.
    3.1. *Before* I click anywhere else the 'biblatex source' blank, 'Autogenerate BibTeX keys' (Command+G) does not work. JabRef 4.0 is simply ignoring Command+G. Before 4.0, it worked.
    3.2. *After* I click anywhere else the 'biblatex source' blank, the location of the entry is changed; it was the last before clicking, but move to somewhere in the entry table according to sorting. The new entry is not blue-highlighted. Then I need to scroll over the table, click the entry, and press Command+G.

[Trouble 3] (Probably) Anti-aliasing problem.
The steps to reproduce:
1. I have my 'some_list.bib' open in the entry table. And in the lower panel of JabRef window, I have 'biblatex source' tab on top.
2. Click any entry from the table. Then its biblatex source looks fuzzy for a while, or until I click the 'biblatex source' blank.

[Trouble 4] Window is not appearing.
The steps to reproduce:
1. I have JabRef window open. And I close the window by clicking the red-x button. JabRef is still in the background (for example, having black dot next to the Dock icon).
2. Open .bib file from Finder.
3. JabRef window does NOT come. The window reappears only by clicking the JabRef Dock icon or by running JabRef.app.

**Comment by halirutan** [comment]
Would you mind to try the latest master snapshot from here: https://builds.jabref.org/master/

Some of the issues might already be fixed. It would be extremely helpful if you could report back and edit your original post.

**Comment by ssblee** [comment]
@halirutan : Thank you for quick response! But I couldn't install the snapshot. My OS X says the .dmg file is corrupted; I am not sure about the exact statement in English, since I am using Korean locale.

**Comment by halirutan** [comment]
@ssblee I could reproduce this problem on my mac and have opened another issue for this. I hope we find the source of this problem soon. Until this is fixed, you still can try the latest JabRef if you like. Download the `JabRef-master-latest.jar` from there. Open a terminal (usually `Cmd`+`Space` to open search and type `terminal` does the trick) and inside the terminal, you first verify that you have a recent java version by typing

```
java -version
```

This gives you an output like the following

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Please ensure that you have at least 1.8.0_144 (but not Java 9, which doesn't work at the moment!). If you need to update java, use the one from [here](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html). If you have done this, and `java -version` gives the correct installation (probably after a restart), you can start Jabref in the following way

```
java -jar /Users/patrick/Downloads/JabRef-master-latest.jar
```

The path should be adapted to where you have downloaded JabRef on your machine.

**Comment by Siedlerchr** [comment]
@LinusDietz  Could you please verify that  the  the keybinding (CMD+G) for autogenerating Bibtekeys on ma works?

**Comment by tobiasdiez** [comment]
Some of the issues above are fixed with in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.

Since there was no response in the past months, I close this issue now. Please open a new issue if the problem should reappear. But please one issue per problem, because this makes the issue management way easier.
