### ISSUE TITLE
Feature request: autosave

### ISSUE THREAD

**Issue by vrossum** [JabRef/jabref#344]
Hi
Currently autosave is active every 5 minutes. Would it be possible to whenever an entry is added? 

This would help a lot when one is typing a latex document and needs to include an extra ref in jabref.
Currently one needs to remember to save jabref everytime before running latex.

**Comment by stefan-kolb** [comment]
You are talking about an autosave so a Latex run can include the newly created entry inside the references?! If not please clarify your use case.

How should the algorithm detect when you are finished with the entry?
It may save when it has a Bibtex key but might still be incomplete.

I don't see a good algorithm to detect the autosave point. Imho the normal use case should be:
1. create your entry
2. save when your done (just CTRL-S for convenient saving)
3. Insert cite inside Latex document
4. compile Latex

**Comment by tobiasdiez** [comment]
We could consider saving after every edit (maybe as an additional preference option).

**Comment by vrossum** [comment]
Thanks for looking into this.

On 16/11/15 23:22, Stefan Kolb wrote:
> You are talking about an autosave so a Latex run can include the newly
> created entry inside the references?! If not please clarify your use case.

Indeed.

> How should the algorithm detect when you are finished with the entry?
> It may save when it has a Bibtex key but might still be incomplete.

I see the problem.
However, I typically search via google scholar or pubmed. In that case 
saving after getting the bibtex key would work.

-- 
Mark van Rossum, Reader, School of Informatics, U Edinburgh
Forum Rm 2.52, 44-131-6511211

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by stefan-kolb** [comment]
@JabRef/developers Any comments if we want to change anything or keep the current behavior?

**Comment by lenhard** [comment]
I guess unless @vrossum commits to creating a pull request and implementing the feature, nothing will happen here. At least I do not see any other volunteers.

@vrossum Will you implement this, or can we close the issue?

**Comment by obraliar** [comment]
The JabRef StuPro feature team will take care of this issue.

**Comment by simonharrer** [comment]
Hm, to make this a useful feature it should make saving obsolete. Every edit or change should be directly reflected in the persisted the database.

**Comment by obraliar** [comment]
Now we are collectiong ideas about realizing this. Suggestions are welcome.

**Comment by koppor** [comment]
Maybe, it should be possible to turn on and off this feature on demand. If I work on a dropbox shared folder, I don't like that each change is instantly saved in dropbox, do I?

**Comment by obraliar** [comment]
We just received the message that there are discussions about implementing event system (https://github.com/JabRef/jabref/pull/937#issuecomment-195420018). Once this system is implemented the problem will get easier to solve. So we think we should wait, or?

**Comment by koppor** [comment]
Initial sketch for the event system (#969) in the context of autosave.

**Comment by stefan-kolb** [comment]
Could this potentially make JabRef slow again with large databases?

**Comment by obraliar** [comment]
So this problem is indepedant of the event system. I think that the save process of large databases takes too long, right? If so, we could implement another save method, which only updates the affected entry instead of overwriting the hole file.

**Comment by koppor** [comment]
@obraliar Please follow up at #1103 and #1094. Since bibtex are text files, one cannot easily seek into the file and write a larger portion. Currently, JabRef uses the read serialization if the entry was not changed. Thus, there should be no performance improvement possibilities in that case.

**Comment by obraliar** [comment]
This is my imagination of this feature:

- UI/Preferences:

![autosave_mockup](https://cloud.githubusercontent.com/assets/15609468/16808238/fae4f0ba-491b-11e6-9036-93a328233b39.png)

- Functionality:
  - Event based saving
  - Time based saving

- Decisions:
  - Should we keep the already existing Autosave mode?
  - Should we add a new item "Autosave" to the list of the preferences? (There is no place for the UI part above)


Discussions are welcome.

**Comment by koppor** [comment]
What is the existing autosave mode?

I would not make "Autosave on every" configurable. It is always saved after each change.

I would not offer the choice between timebased and eventbased. Just eventbased. Or something sensible such as IntelliJ does. The recovery should also be done automatically.

Reason: There should be less configuration possibilities. JabRef should just do it right.

**Comment by obraliar** [comment]
> What is the existing autosave mode?

Time based autosave already exists.

Okay, in that case I'm going to replace it completely.

**Comment by tobiasdiez** [comment]
I'm also in favor for only supporting event-based auto-save and only the following configuration options:
- Enable / Disable
- Disable for huge databases (with a fixed limit which we have determined before)

I think the backup functionality is very important, but of course should be adopted to work with the auto-save method. For example, it is relative pointless to save the same data to two files on every change. Thus I would differentiate between the following two cases:
- auto-save enabled: make a backup copy on opening the file but don't write changes to it. In this way, we have a backup for the old state and the real file always contains the current state.
- auto-save disabled: create a backup copy when the file is opened and save all changes to it. Only write to the real file if the user presses save. 

So in either case there is a file with the old state and a file with the current state.

**Comment by koppor** [comment]
Implemented in #2118 and help pages prepared (https://github.com/JabRef/help.jabref.org/pull/108).

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is now implemented in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master.
