### ISSUE TITLE
Mac OS X dmg is corrupted for the nightly builds

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#3440]
In this issue https://github.com/JabRef/jabref/issues/3437#issuecomment-345182095, the reporter pointed out he could not install the `dmg` file from the development builds. I tried to reproduce the problem on my MacBook (10.12.6) and I got as well the following error:

<img width="532" alt="screen shot 2017-11-17 at 18 26 57" src="https://user-images.githubusercontent.com/511683/32960567-a33b70cc-cbc5-11e7-89a8-e2e5fe5eba73.png">

That is something we need to fix ASAP. Could the dev who is responsible for the release building on CI look at this? I can help and test, but I cannot build the release myself as there seem to be some local settings that are required that I don't have.

**Comment by Siedlerchr** [comment]
Could you try to test with an older version of here?
http://builds.jabref.org/fixfetcherisbn/
I am unsure whether it is caused by a certficiation issue (the code signing expired) or if its caused by a commit

**Comment by halirutan** [comment]
@Siedlerchr This one works.

**Comment by ncihnegn** [comment]
My Firefox download is corrupted but curl works fine.

**Comment by halirutan** [comment]
OK, I googled a bit around and I believe I found the problem:

```
codesign -v JabRef_macos_4_1-dev--snapshot--2017-11-13--master--c1d425a31.dmg

JabRef_macos_4_1-dev--snapshot--2017-11-13--master--c1d425a31.dmg: CSSMERR_TP_CERT_EXPIRED
```

The certificate of the older `dmg` is not expired.

**Comment by Siedlerchr** [comment]
@halirutan  Yes, what I already thought. We are aware that our codesigning is expired and we are in the process of getting a new one.
In the meantime I found this solution: https://github.com/processing/processing/issues/4705#issuecomment-269241488

**Comment by LinusDietz** [comment]
We disabled code signing until we obtain the certificate.
