### ISSUE TITLE
Changing entry type doesn't work

### ISSUE THREAD

**Issue by arnyeinstein** [JabRef/jabref#3446]
Steps to reproduce:

1. Generate an entry (e.g. article)
2. .Try to change the type from article to technical report using the "pencil" symbol
3. Nothing happens.

CHeers
Renger

**Comment by lenhard** [comment]
Hi @arnyeinstein 

What version of JabRef are you using? Please try again with the most recent master version and reply if the error persists: http://builds.jabref.org/master/

**Comment by arnyeinstein** [comment]
I work with the official Windows 64 version. I download the snapshot today and now it works fine.
Thanks
