### ISSUE TITLE
Revision history not up to date

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#345]
The revision history in the help of version 2.11.1 only goes through 2.10.  The website is also behind, not describing what's in 2.11.1

**Comment by matthiasgeiger** [comment]
Thanks for your report!

We'll update our website accordingly.

Meanwhile you can check out all changes since 2.10 in the [CHANGELOG file here](https://github.com/JabRef/jabref/blob/dev_2.11/CHANGELOG).

**Comment by koppor** [comment]
I removed the revision history within JabRef in f65446be551d0e21ec6eba. It causes an additional manual step during releasing and we aim for automatic building and releasing to remove human errors.

Maybe, we readd the history in the help file in 3.0, when we can place [CHANGELOG.md](https://github.com/JabRef/jabref/blob/master/CHANGELOG.md) automatically into the build (somehow :sunflower:).

BTW: We really welcome new contributors. See https://github.com/JabRef/jabref/issues/133 and https://github.com/JabRef/jabref/issues/111 for a list of open issues regarding the documentation.

Meanwhile, the source homepage itself is also available at github and be improved: https://github.com/JabRef/htdocs
