### ISSUE TITLE
Converting bib to ris format does not preserve crossref and additional fields

### ISSUE THREAD

**Issue by RohanAsmat** [JabRef/jabref#3452]
When using the converting feature of Jabref from bib to ris, the cross references are not preserved and additional fields are not supported by the tool.

**Comment by lenhard** [comment]
Hi @RohanAsmat 

To make something out of this, we need more information. What version of JabRef are you using, what additional fields are you expecting, etc.? 

Please provide the code for a bib entry and the corresponding version of the ris format that you would expect. When we have that, we can see if there is a problem and we can decide if we are going to do something about.

**Comment by lenhard** [comment]
I am closing this now due to a missing reaction. Feel free to reopen when you have more details.
