### ISSUE TITLE
Write Checker for every BibTex field

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#346]
We should have checkers for every field and conformant to the Bibtex manual.
http://mirrors.ibiblio.org/CTAN/biblio/bibtex/base/btxdoc.pdf

**Comment by bluebirch** [comment]
... and biblatex...

**Comment by koppor** [comment]
This seems to be related to https://github.com/JabRef/jabref/pull/150.

**Comment by mairdl** [comment]
Our feature team would like to take care of this. We understand it this way: We have to make a syntax check for every field.

**Comment by koppor** [comment]
@stefan-kolb Could you elaborate a bit more? Maybe give examples. Do you mean that pages should be formatted as pages and file references as file references? Most fields are text, though. Title, Review, Abstract. How does this relate to the integrity check? Refs #416, #419, #698, #863

**Comment by stefan-kolb** [comment]
These issues are what I meant by this. Integrity checks for all defined fields. A lot of them are probably already written by now. As my first post mentions these checks should be based on official sources that restrict the usage of fields in BibTeX or Biblatex.

**Comment by mairdl** [comment]
As far as @tschechlovdev and I understood the manual, there are no restrictions for the fields. Oren Patashnik only suggests how to use the fields.

**Comment by stefan-kolb** [comment]
Ok, so we can close this?!

**Comment by koppor** [comment]
OK, let's focus on the checkers and reopen if we find MUST things in the documentation.
