### ISSUE TITLE
autolinks all the files in the folder into each of the references

### ISSUE THREAD

**Issue by Dellu** [JabRef/jabref#3461]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version **4.1 dev** on Mac OS x 10.13

Steps to reproduce:

1. Create sample library (or download my [sample library](https://www.dropbox.com/s/i2r180klcmmnuvi/Jabref4.1_sample.zip?dl=0)), **test.bib**, with some references: say 3 references. The references must have Bibtex keys. 
2. Put 3 pdf files in a folder in your desktop, call it **myFolder**. Each of the pdf files must have a file name starting with the Bibtex keys of the references we have in 1. Or, you can put my sample pdf files. 
3. Go to Database properties of **test.bib** and set the default file directory  your desktop folder you just created. 
4. Save the library  
5. Go to Quality menu in Jabref and Automatically Set file links (or, simply hit F7).

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by AEgit** [comment]
Hmmm, I don't really understand the problem. What happens after (5.)?

**Comment by tobiasdiez** [comment]
I think this is behavior is expected. You have probably activated the option (in the preferences), that files are found if they start with the bibtex key.

**Comment by Dellu** [comment]
The File field of a reference  contains the names of all the files. it is supposed to contain only the name of one file--the corresponding file. 
@tobiasdiez: this is not expected. What is expected is the File field of reference X would point to the linked file Y. Now, what I have is, the File field of one file X contains the list of all the files in the folder (10,000 files, in my case). That made Jabref crash and fail.

**Comment by Dellu** [comment]
Here is the result of one of the references I sent you (attached). Look at the file field. It has 3 PDF files attached to it (=complete junk). It is supposed to have only one. 

@Article{MakiKishida1987,
  author     = {Maki Kishida, Yosuke Sato},
  title      = {Psychological Predicates and Point of View Roles: A Hyperprojection Analysis},
  year       = {1987},
  pages      = {1–44},
  date-added = {27-11-2017},
  **file       = {:/Users/dwo000/Desktop/Jabref4.1_sample/myFolder/Miltenburg2015 - How to determine the role of alternatives in scalar implicatures ∗.pdf:PDF;:/Users/dwo000/Desktop/Jabref4.1_sample/myFolder/MakiKishida1987 - Psychological Predicates and Point of View Roles_ A Hyperprojection Analysis.pdf:PDF;:/Users/dwo000/Desktop/Jabref4.1_sample/myFolder/Cohen2006 - How to deny a presupposition.pdf:PDF;:/Users/dwo000/Desktop/Jabref4.1_sample/myFolder/Miltenburg2015 - How to determine the role of alternatives in scalar implicatures ∗.pdf:PDF;:/Users/dwo000/Desktop/Jabref4.1_sample/myFolder/MakiKishida1987 - Psychological Predicates and Point of View Roles_ A Hyperprojection Analysis.pdf:PDF;:/Users/dwo000/Desktop/Jabref4.1_sample/myFolder/Cohen2006 - How to deny a presupposition.pdf:PDF}**,
  keywords   = {backward binding; pivot; point of view projection; psychological predicate},
  url        = {http://ling.auf.net/lingbuzz/000794},
}

**Comment by tobiasdiez** [comment]
@Dellu is your problem the same as https://github.com/JabRef/jabref/issues/3472?

**Comment by Dellu** [comment]
Yes, this is the same problem.
