### ISSUE TITLE
Inconsistency with  "mastersthesis" &  "masterthesis"

### ISSUE THREAD

**Issue by Dellu** [JabRef/jabref#3464]
This is not a big issue. But, I have seen inconsistencies across Jabref functions with the alternating use of the field. 
The folders created when files are named, for example, are marked as **masterthesis** while the actual field in the entry table is named as **mastersthesis**

**Comment by lenhard** [comment]
Which version of JabRef are you running?

The correct version of the term should be "mastersthesis". I've done a search in the complete project and the only points I can find the term "masterthesis" are in the localization and some of the tests, so it doesn't seem that the wrong term is actually encoded in JabRef.

**Comment by Siedlerchr** [comment]
Can not be reproduced. It might be that one imported entry from a journal included that. I can also confirm that the word is never used internally.
