### ISSUE TITLE
automatically added file link has absolute instead of relative path

### ISSUE THREAD

**Issue by sbitzer** [JabRef/jabref#3476]
- [x ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.1-dev--snapshot--2017-11-30--master--d45d7ca38
Linux 3.16.0-38-generic amd64 
Java 1.8.0_151
on Mint 17 (Ubuntu 14.04)

Steps to reproduce:

1. import new entry
2. add file with bibtex key into file directory
3. open new entry in entry editor

I just switched from v4.0 to the latest development version, because Medline import did not work in v4.0 anymore. Unfortunately, now files appear to be added with absolute paths to the library. E.g., I added entry Lake2016 and Jabref now automatically adds the corresponding file as `/home/bitzer/papers/Lake2016.pdf` instead of as `Lake2016.pdf` as before. So I have to manually edit the file link to get the relative path. Is that intended behaviour and how do I get Jabref to automatically add relative links again?

**Comment by Siedlerchr** [comment]
Hi,
relative links are created automatically. And this depends on your settings, there are 4 settings for files:
1. Checkbox: Use bibfile as main file location -> Overwrites all other settings
2. Main file directory. globally in JabRef, valid for all files
3. Use and Library setting in the properties of the bib file: Here you can also enter relative path.
So depending on your settings, JabRef will relatvize all paths against the first found file directory.

**Comment by sbitzer** [comment]
Hi,

all of these 3 were set in Jabref 4.0 and are still set in the development version I'm using now (1. checked, 2. set to `/home/bitzer/papers` and 3. set to `/home/bitzer/papers`, too). Still, version 4.0 added relative paths while the development version adds absolute paths.

**Comment by Siedlerchr** [comment]
Is the location of the bibfile the same as /home/bitzer/papers? If not then uncheck the combobox

**Comment by sbitzer** [comment]
Yes, the bibfile is in /home/bitzer/papers itself.

**Comment by Siedlerchr** [comment]
Ah I now can reproduce your  behavior. It is the auto link which adds it as absolute path. If you manually select the file, it is correct. I will be working on a fix for this

**Comment by sbitzer** [comment]
Cool, thank you!
