### ISSUE TITLE
File sorting option not inherited from previous versions

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#348]
I just updated to Jabref 2.11.  In the previous version I used, I think I had selected the option to leave the bib file unsorted -- at least I can say for sure that my bib file stayed unsorted when I saved it.  But after loading the same bib file into 2.11, I noticed that Options->Preferences->File->"Save fields in unsorted order (as until version 2.9.2)" was not selected; instead "Save fields sorted in alphabetic order (as in versions 2.10+)" was selected.

**Comment by lenhard** [comment]
Just to make sure we are talking about the same thing: The configuration option you are talking about sets the sorting style of fields inside a Bibtex entry and has nothing todo with sorting the entries of the database.

Moreover, the configuration setting in the GUI is only available in 2.11, so you weren't able to set the sorting style before. If you upgraded from 2.10, nothing changes. If you upgraded from 2.9.2, it changes quite a bit (but you can reset it with this option).

From what version of JabRef did you upgrade? What part of your bibliography is sorted now, but hasn't been before?

**Comment by notuntoward** [comment]
Ah, thanks for the clarification. I didn't notice that the entries were
sorted in the database, but I thought that could have been because I turned
this sorting option off as soon as I updated to 2.11.  Anyway, I
upgradedfrom 2.10b, I think, and if that still matters.

Scott

**Comment by lenhard** [comment]
Ok, I think this issue is solved.

By the way, we will disable sorting and auto-formatting in future versions (3.0+), so there will be no more nasty surprises like this one.
