### ISSUE TITLE
Italian localization issue in file JabRef_it.properties

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#3480]
At line 2078 of file `JabRef_It.properties`, instead of
`Check_for_updates=Cerca_degli_aggiornamenti`

I would suggest
`Check_for_updates=Cerca_gli_aggiornamenti`

or, better,
`Check_for_updates=Ricerca_degli_aggiornamenti`

Many thanks in advance,
Domenico

**Comment by Siedlerchr** [comment]
Hi,
you can directly edit the things in your browser:
https://help.jabref.org/en/TranslatingGUI#directly-in-your-web-browser

**Comment by lenhard** [comment]
Fixed by #3482
