### ISSUE TITLE
Double click on an entry on file list should open the PDF

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3491]
As is:

![grafik](https://user-images.githubusercontent.com/1366654/33706710-4557e95c-db35-11e7-87d0-c42291ebe9c6.png)

opens:

![grafik](https://user-images.githubusercontent.com/1366654/33706727-4bd06ba6-db35-11e7-9d99-fee24167e818.png)

Should be: 

- [ ] Double click directly opens the PDF
- [ ] Furthermore, there is no button to open the PDF. The Lupe searches for a PDF, but does not open one

**Comment by Siedlerchr** [comment]
I think  this is consistent with the 3.x version. Only in the  main table the file will be opened directly. Otherwise the "modify file" dialog in your screenshot pops up where you can add a description or similar 
Maybe we can simply add a new icon for opening the file
