### ISSUE TITLE
It should be possible to delete an attached file

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3493]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

![grafik](https://user-images.githubusercontent.com/1366654/33706962-238c01f4-db36-11e7-94ea-104d0f905bc1.png)

There also should be a `-` icon at the right side, shouldn't it?

**Comment by Siedlerchr** [comment]
There never was an icon and delete via del key is already possible

**Comment by koppor** [comment]
It does not work here. You are invited to connect using Teamviewer.

> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

**Comment by koppor** [comment]
I also cannot select the second entry.

![grafik](https://user-images.githubusercontent.com/1366654/33711962-1b27efcc-db46-11e7-9510-6f5710436187.png)

**Comment by Siedlerchr** [comment]
confirmed, that's weird. It was definitely working at some recent point. So I would label it as regression bug,

**Comment by stefan-kolb** [comment]
1. There was an icon `-` in the old entry editor to remove the assignment of a file.
2. DELETE key removed the assignment.
3.  Deleting a file was only possible via right-klick and delete from file system.

**Comment by Siedlerchr** [comment]
Okay, works as expected: Check your file dir settings:
The code checks if the file exists  in the file directories.

![grafik](https://user-images.githubusercontent.com/320228/33770000-6aae4546-dc2c-11e7-86de-d2f967fc40c6.png)

Although the gui doesn't indicate it, you can select the second entry.

**Comment by koppor** [comment]
There should a log message why no popup comes.

Even if the file does not exist, it has to be possible to remove the
assignment!

Am 08.12.2017 15:30 schrieb "Christoph" <notifications@github.com>:

**Comment by Siedlerchr** [comment]
Right click -> Remove file entry

2017-12-09 13:22 GMT+01:00 Oliver Kopp <notifications@github.com>:

**Comment by koppor** [comment]
The ENTF key should work. It used so to be like that in 3.x

Am 09.12.2017 13:33 schrieb "Christoph" <notifications@github.com>:

**Comment by Siedlerchr** [comment]
Will move the file exist check
