### ISSUE TITLE
Reuse Zotero's translators?

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#350]
I think the reference manager with the best import functionality is Zotero. Fortunately, their importers are [open-source](https://github.com/zotero/translators). So it seems to be natural to reuse the code for the import into Jabref, right?

One way would be to set-up a [translation-server](https://github.com/zotero/translation-server) and speak with it via simple (same-machine) http requests as for example [here](http://stackoverflow.com/questions/33282289/using-zotero-translators-to-get-author-affiliation).

**Comment by simonharrer** [comment]
Yes, but as far as I understood it they only support importing to and exporting from the Zotero format. So we would always need to do two steps: import to Zotero and export into Bibtex for a single import functionality. The same when doing an export.

**Comment by tobiasdiez** [comment]
Yes. First you transform the website into a zotero object (json) and then convert this into bib(la)tex. Actually, this works quite well and is the same strategy I used for [my firefox addon](https://github.com/tobiasdiez/Jabref-FirefoxAddon).
(I don't understand what you mean with "same when doing an export").

**Comment by koppor** [comment]
Runs on `zotero.jabref.org:1969`:

    curl -d '{"url":"http://www.tandfonline.com/doi/abs/10.1080/15424060903167229","sessionid":"abc123"}' --header "Content-Type: application/json" zotero.jabref.org:1969/web

Issue: I did not update the code. The current fetchers are from 2013. Don't know whether I should try to update them. Have no test cases running to ensure that everything runs as expected.

**Comment by tobiasdiez** [comment]
So I would propose (and work on it if you give the ok) the following: 
- modify the server code so that it produces bibtex and uses the most recent translators
- create the necessary code for JabRef to speak with zotero.jabref.org

**Comment by koppor** [comment]
Yeah, go ahead :rocket: I currently don't have a clue how the UI should look like: The firefox addon seems to do the job perfectly?

**Comment by tobiasdiez** [comment]
I had a look in implementing something. So far it seems like the Zotero server does not return the found pdfs (see [#17 in their issue tracker](https://github.com/zotero/translation-server/issues/17)). I think it does not make sense to use the zotero server until this is resolved.

Just for the record the powershell version of the above `curl` command:
```` powershell
try {
    $body = @{
        #url = "http://www.tandfonline.com/doi/abs/10.1080/15424060903167229"
        url = "http://arxiv.org/abs/1508.01114"
        sessionid = "abc123"
    }        
    $result = curl -Uri http://zotero.jabref.org:1969/web -Method Post -Body (ConvertTo-Json $body) -ContentType application/json
    $result.Content
}
catch {
        $result = $_.Exception.Response.GetResponseStream()
        $reader = New-Object System.IO.StreamReader($result)
        $responseBody = $reader.ReadToEnd();
        $responseBody
}
````

**Comment by koppor** [comment]
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.
