### ISSUE TITLE
Update group name in list when it's changed

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3527]
- [x] I have tested the latest git version

JabRef version 4.1-dev

Steps to reproduce:

1. change group name via "edit group"
2. it's updated under General > Groups but not in the group tree

**Comment by Siedlerchr** [comment]
You have to collapse/expand the specific group (double click)  to make the changes visible. It's a known problem. There is a similar issue about this, which I can't find atm

**Comment by j0hannes** [comment]
I can't, it's a top-level group without any subgroups. Searching for 'group' and 'name' gave no results.

**Comment by tobiasdiez** [comment]
Duplicate of #3189.
