### ISSUE TITLE
Paste entries into group bug

### ISSUE THREAD

**Issue by jmkeil** [JabRef/jabref#3537]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.0 on Windows 8.1

Steps to reproduce:

1. Open JabRef (error on console, see details)
2. Open the groups view
3. Create a new Document
4. Click "All entries"
5. Paste some Bibtex
6. Entry does not appear, entry counter is "0" (Expected: Entry does appear, counter increases)
7. Save the file
8. File contains the entry (as expected)
9. create a new group and click on them
10. click on "All entries"
11. the entry now appears (as expected), counter is still "0" (not expected)
12. create a second new document
13. switch back to the first document
14. counter is "1" (as expected)

<details>
  <summary>Log File</summary>
  
  ```
  AI: INFO 15-12-2017 16:13, 22: Configuration file has been successfully found as resource
16:13:18.717 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
        at org.jabref.gui.search.GlobalSearchBar.lambda$new$5(GlobalSearchBar.java:196) ~[JabRef--master--latest.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
  ```
</details>

**Comment by Siedlerchr** [comment]
The exception looks similar to #3525. Should be fixed. But unfortunately, as we currently have issues with our certificate, the master binary does not get updated. 
Either you wait or you run JabRef from source with gradlew run

**Comment by tobiasdiez** [comment]
Yes, the NPE error should be fixed but not the update problem. I'll try to have a look at it in the next days.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by jmkeil** [comment]
Hi. I tested the old steps to reproduce with JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04.jar. I see some improvements (new entry now appears immediately), but there are still some problems.

New steps to reproduce:

1. Open JabRef
2. Open the groups view
3. Create a new Document
4. Click "All entries"
5. Paste some Bibtex
    * Entry appears (as expected)
    * **entry counter of  "All entries" is "0" (not expected)**
7. Save the file
8. File contains the entry (as expected)
9. create a new group
   * entry counter of  "All entries" is now "1" (as expected)

**Comment by Siedlerchr** [comment]
@jmkeil  Thanks for your report. The entry number bug is known. If you switch to another db and then back it should be correct again. See issue #4441

**Comment by jmkeil** [comment]
Yes, this is the same bug. So this issue can stay closed. Thanks.
