### ISSUE TITLE
Freeze UI when searching + switching open files

### ISSUE THREAD

**Issue by lizliz** [JabRef/jabref#3545]
Switching between open files in JabRef has suddenly started freezing the UI.  

My Specs:

JabRef 4.0 on Ubuntu 16.04
Linux 4.10.0-42-generic amd64 
Java 1.8.0_151

Steps to reproduce:

1. Search for something in the searchbar
2. Try to switch files to another already open file by clicking in the top bar.

I can't access the log since the UI is completely gone, so I can't post any errors unless someone can tell me where else to look for them.

**Comment by Siedlerchr** [comment]
Please try again with the latest master and please check if you use the GTK style. If yes, try another.
https://builds.jabref.org/master/

**Comment by lizliz** [comment]
I get the same behavior both with the 4.1-dev snapshot (6f39151a7) and with the JabRef--master--latest.jar.

I don't know what using GTK style means.... how do I check that?

**Comment by Siedlerchr** [comment]
In the options you can select the Look and Feel in the Appearence. People who used the GTK Look and Feel experienced problems

**Comment by lizliz** [comment]
Ok, so this is definitely a GTK issue. If I switch the appearance to either the Plastic3D or the Metal options in the dropdown menu, the problem does not persist.

Thank you all for the help!

**Comment by tobiasdiez** [comment]
I close this and mark it as "wont-fix" since GTK is the reason for other similar problems and we have an easy work-around.

**Comment by NikoKrause** [comment]
I have the same issue on Linux Mint 18.3, which is based on Ubuntu 16.04.

Using the GTK theme in JabRef and trying to add/edit a `File` in the `General` Tab results in a frozen JabRef (4.0 and 4.1) application.

This issue does not happen with GTK and JabRef 3.8.2.

I change the theme for now. Hopefully this doesn't happen with newer versions of GTK (3.22+) in Ubuntu 18.04.

For now I'll change the JabRef theme. Thanks for the workaround.
