### ISSUE TITLE
"generate bibtex keys" overwrites entries

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3547]
JabRef 4.1-dev--snapshot--2017-12-08--master--6f39151a7
Linux 4.10.0-42-generic amd64 
Java 1.8.0_151

(no new build for 10 days...)

Steps to reproduce:

1. import an external bib file into an existing library.
2. in the import options screen, choose "generate" option
3. press "generate now"
4. press "OK"
5.  all the different entries are replace by one entry.  See picture (entries marked yellow)
[log.txt](https://github.com/JabRef/jabref/files/1569940/log.txt)

![screenshot from 2017-12-18 18-03-12](https://user-images.githubusercontent.com/762246/34135574-c195792a-e41e-11e7-94a2-1a6ed155c59c.png)

[log.txt](https://github.com/JabRef/jabref/files/1569943/log.txt)

**Comment by stefan-kolb** [comment]
I have tested the described behavior, but cannot reproduce it.
Can you post a minimal reproducible example for us?

**Comment by wujastyk** [comment]
I can't reproduce it either, now.

Happy Christmas!

JabRef 4.2-dev--snapshot--2017-12-25--master--d29a4ca5d
Linux 4.10.0-42-generic amd64
Java 1.8.0_151

​
