### ISSUE TITLE
Features and bugs of shared database

### ISSUE THREAD

**Issue by JHoahg** [JabRef/jabref#3548]
Hi everybody,
this is just a wishlist for shared databases ;). We are using shared databases now regularly since the 4.0 release.
Here are a few things we have noticed
• upon creation of a new entry, a duplicate of this entry appears. this entry disappears after a reconnect.
• automatic reconnect with last used shared database. same as reopening last used bib-files.
• a dropdown menu to choose different databases in the connect dialog
• it seems as if every keystroke is directly transferred to the database, this make typing sometimes unpleasant
• the "save to file option" only works if the file you are saving to already exists

Thanks and merry christmas
-johannes

**Comment by Siedlerchr** [comment]
As there have been made some improvements to the shared database feature I guess this can be closed.
