### ISSUE TITLE
Wrong file gets overwritten

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3549]
- [x] I have tested the latest version from github

JabRef version 4.1-dev

Steps to reproduce:

1. have an entry with a file linked
2. choose "rename file"
3. "remove link"
4. add a different file
5. choose "rename file", a dialog will appear asking you if you want to overwrite the existing file
6. choose yes

The result is that the new file has been deleted and the old one (with the matching name) has been inserted instead.

**Comment by Siedlerchr** [comment]
This is the AutoLink File feature which kicks in it seems like it has found the other file first.
Remove link only removes the link from the bib, it does not remove the file on disk.
sounds to me like correct behaviour. I don't your use case really. Why do you rename it first and then delete it?

**Comment by j0hannes** [comment]
To me, it definitely looks like a bug. I'll try to make a concrete example:

* you have an entry with file `Smith2000 - The Meaning of Life.pdf`
* you find a better version and store it in your pdf folder with its original filename `f77bc4e5-a979-4587-86a3-480f28540be9.pdf`
* you remove the link from the entry to file `Smith2000 - The Meaning of Life.pdf`
* you add a link to `f77bc4e5-a979-4587-86a3-480f28540be9.pdf`
* now, you want `f77bc4e5-a979-4587-86a3-480f28540be9.pdf` to become `Smith2000 - The Meaning of Life.pdf`

What happens instead is that the old `Smith2000 - The Meaning of Life.pdf` is linked and `f77bc4e5-a979-4587-86a3-480f28540be9.pdf` is gone. That pretty much describes a bug because I chose the second file to be renamed with option "rename file" and not the option "find me anything that fits and delete what I have just added".

**Comment by stefan-kolb** [comment]
Please delete the old file and then link and rename the new file.
The autolink feature is based on linking matching file names and cannot work otherwise.

**Comment by j0hannes** [comment]
It is still a bug if a file (the wrong one) is deleted without warning. You definitely can't sell this behaviour for a feature.

**Comment by Siedlerchr** [comment]
Why don't you add the new file manually?

**Comment by j0hannes** [comment]
I do, see my description above. The manually added file is the one that is deleted on rename.
