### ISSUE TITLE
Check integrity - display selected entries problem

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#3550]
Using 4.1dev 12-19 on Linux x86_64:

1. Choose "Check integrity"
2. Wait for the window displaying entries with problems
3. Click on one of the entries that has a problem - entry is displayed in main window
4. Click on another entry - gray window where the entry should be displayed
5. Hitting Esc key clears the gray window and displays the second entry

**Comment by Siedlerchr** [comment]
I can not really reproduce this: Yes, it takes a moment to load the entry editor for the entry. But then all fields are displayed correctly. At least under Windows. I will check out Linux soon

**Comment by sambo57u** [comment]
OK, I cannot reproduce it now. The entries I had problem with were ArXiv entries and I just replaced them
Please close for now and I will open again if I encounter this.
