### ISSUE TITLE
dependency-updates-20171220111048

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3561]
* [ ] `com.microsoft.azure:applicationinsights-core:2.0.0-BETA`
* [ ] `com.microsoft.azure:applicationinsights-logging-log4j2:2.0.0-BETA`

**Comment by tobiasdiez** [comment]
It appears that https://github.com/JabRef/jabref/pull/3559 reintroduced the problem that "page views" (i.e. dialogs) are not tracked. At least, the last version that reported this information was from the 19th. It could be, of course, that nobody yet opened a dialog in a newer version. 

Thus I reopen this issue. If you want to release a new version in the next few days, I would kindly ask you to revert https://github.com/JabRef/jabref/pull/3559. I'll keep an eye on the logs and will report in a few days again if dialogs are tracked or not.
