### ISSUE TITLE
Library properties: no change but...

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#3562]
After opening the library properties window, if you click directly on OK, the file is shown as modified while no properties was modified by the user.

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists 

JabRef 4.1-dev--snapshot--2017-12-21--master--55abd5e2e
Linux 3.11-2-amd64 amd64 
Java 1.8.0_131

Steps to reproduce:

1. File -> New bibTeX library
2. File -> Save library as...
3. Enter a file name, like test.bib
4. Click on OK
Note that, at this point, the file is not shown as modified (no star in the name tab). Which is ok.
3. File -> Library properties
4. Click on OK  (without modifying any properties)
The file is shown as modified (star in the name tab)

Nothing special in the console.

**Comment by PJozeph** [comment]
can I work on this ?

**Comment by Siedlerchr** [comment]
Sure, go ahead
