### ISSUE TITLE
Translation contexts are missing

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3566]
We have the strings "not", "or", "with", "contains" as separate strings to translate. This is very hard to translate:

> Needs context of the word usage. This word is too short to make an appropriate translation. The order of words can be forced to exchange before and after this word in translation. It can be resolved by tweaked choice of words, but in some cases it becomes impossible.

>  This word is too short to make an appropriate translation. Could you give the context where this is used?

Can we cleanup the code to include more context in the translation string?

Refs https://github.com/JabRef/jabref/pull/3563

**Comment by koppor** [comment]
I checked with @tobiasdiez and these are strings used to generate text in the group settings.

**Comment by tobiasdiez** [comment]
What should be done here? Can this be closed?

**Comment by koppor** [comment]
I freeze it. That is much work, where we don't have time to do.
