### ISSUE TITLE
missing dot in files exported 

### ISSUE THREAD

**Issue by ziruizhuang** [JabRef/jabref#3576]
issues with JabRef version 4.1
however, 4.0 is fine.

Steps to reproduce:

1. File - Export
2. Select MS2007 XML format
3. Save

Expected: a file saved with name "NAME.XML"
Got: a file saved with name "NAMEXML"

**Comment by Siedlerchr** [comment]
Probably related to #3565

**Comment by tgkolda** [comment]
I'm having the same problem.

**Comment by tobiasdiez** [comment]
@ziruizhuang @tgkolda I think, I fixed the bug. Could you please try out the version from https://builds.jabref.org/fixExport3576/ and report back if these issues are indeed resolved. @tgkolda what do you mean with "custom export"?

**Comment by tgkolda** [comment]
@tobiasdiez  Thanks for your response. The fixExport3576 version didn't run at all for me, so I couldn't check the fix. Sorry. As for custom export, I refer to this capability: https://help.jabref.org/en/CustomExports, of which I am an enthusiastic user.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by ziruizhuang** [comment]
solved this issue, yet introduced another one.
The export format varies, so usually  we call a format "Microsoft Word Citation (*.XML)" "Open Document Citation (*.XML)", etc. 
Instead, in the latest snapshot(http://builds.jabref.org/master/JabRef_windows-x64_4_2-dev--snapshot--2018-01-05--master--d6435d56d.exe), there are multiple "XML file (*.XML)". Although they are all en-capsuled using XML, but they are different formats and now we cannot identify one from another.
