### ISSUE TITLE
auto add "referrer header" for url link

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#358]
Sometimes, the url link in the field URL has no referrer header (http://) etc. 
So, when we click the link icon, JabRef showed the error that
<pre>Windows cannot find '....'. Make sure you typed the name correctly, and
then try again. To search for a file, dick the Start button, and then dick Search.
</pre>
Perhaps this can be avoided by adding automatically the referrer header.
Tested on the 2.11.1
Thank you

**Comment by stefan-kolb** [comment]
Personally, I'm not sure if we should add a protocol by default if it is missing. It is just a bad URL then and should be fixed by the user to get a correct field value?!
However, we may add a autocorrection feature for this in the cleanup section.

**Comment by koppor** [comment]
[This is how Chrome works](http://www.theinquirer.net/inquirer/news/1601917/google-drops-http-chrome). Why not just trying to add `http://` if the protocol is missing?

**Comment by stefan-kolb** [comment]
It's not displayed in Chrome, but prepended if you copy the URL. 
Why not:
  - Do not foster unsecure http:// protocol
  - Can we be sure it is not another protocol, like a file path?

**Comment by g10996694** [comment]
@stefan-kolb you are right. perhaps the right way would be check if it is a file path or url link.
thank you

**Comment by koppor** [comment]
Add it to ntegrity check

Eventually, we add it to cleanup to add `http` before, which whould match 80% of the cases.
