### ISSUE TITLE
JR still hangs in High Sierra Mac

### ISSUE THREAD

**Issue by Professor-Teplow** [JabRef/jabref#3589]
JabRef version <4.1> on <Mac OS X 10.13.2>

Steps to reproduce: Start the app and then hit CTRL-I to import a citations. The app then hangs and I can't even find a pid in terminal to force quit.

See screenshot showing the screen at the hang.

I did add my hostname to /etc/hosts see <
https://dzone.com/articles/macos-sierra-problems-with-javanetinetaddress-getl>. This did not change anything.

The problem does not occur when I use JR 3.8.2.

I can't find the log file in Console. Any suggestions would be most appreciated.
![jr-4 1-hang](https://user-images.githubusercontent.com/29470512/34449719-5c5d3170-ecb0-11e7-849e-76577ccc41a3.png)

Thanks!

**Comment by koppor** [comment]
Does this ref https://github.com/JabRef/jabref/issues/3236 or another closed issue (https://github.com/JabRef/jabref/issues?q=is%3Aissue+label%3Aosx+is%3Aclosed)?

**Comment by Professor-Teplow** [comment]
I had looked at these before, but I had not noticed that I was running JRE 1.8.0_131-b11. I updated my Java to 1.8.0_151-b12 and now things are working fine. Thanks for helping me out!
