### ISSUE TITLE
trademarks in `Description`

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3592]
https://www.fosshub.com/JabRef.html
lists trademarks in `Description` for all OS but Linux.
I am not sure, if you have to add this disclaimer at all, but Linux is a registered trademark too.

**Comment by koppor** [comment]
Field an issue to FossHub.

**Comment by jonasstein** [comment]
Oh, I expected you have edit rights.

**Comment by koppor** [comment]
Should really be fixed now.
