### ISSUE TITLE
Disable autocomplete in the search field

### ISSUE THREAD

**Issue by adessec** [JabRef/jabref#3598]
JabRef version <4.1> on <Linux 4.4.103-18.41-default amd64, Java 1.8.0_151>

If I start searching a database, a drop-down menu appears below the search window although I have tried to globally disable autocomplete in the preferences. Shouldn't there be a way to totally disable this feature for each and every place where it might pop up?

Steps to reproduce:

1. Open an existing database.
2. Begin typing into the search window.
3. Unwanted drop-down menu appears.

**Comment by lenhard** [comment]
There is a preference option that you can set as part of the entry editor preferences, which turns off the autocompletion there. I think we should just extend the preference to capture the search box as well.
