### ISSUE TITLE
Where did the splash screen go??

### ISSUE THREAD

**Issue by fishforbreakfast** [JabRef/jabref#360]
Hi,

First, thank you very much for the 2.11 release.  I did notice though that the splash screen is gone.  I rather miss it but it's not a huge issue.  Numerous projects have their interesting startup logos.  Makes work a bit more pleasant at times.  The splash screen for JabRef was one of the better ones (in my humble opinion).

Cheers,

Fred

**Comment by simonharrer** [comment]
Sorry but the splash screen was removed because of performance reasons. Currently, we are not planning to add it again.

**Comment by koppor** [comment]
It was [sf.net feature request 884](https://sourceforge.net/p/jabref/feature-requests/884/). Furthermore, maintenance for the splash screen was difficult. We had to manually add the year and adapt the version number. That caused effort at the release. Currently, we aim to automate as much as possible.

Additional discussion is available at https://github.com/JabRef/jabref/pull/89.
