### ISSUE TITLE
Export dialog with unclear format list

### ISSUE THREAD

**Issue by ziruizhuang** [JabRef/jabref#3605]
issues with JabRef version 4.2 snapshot (http://builds.jabref.org/master/JabRef_windows-x64_4_2-dev--snapshot--2018-01-05--master--d6435d56d.exe)

Steps to reproduce:

* File - Export

**Expected:** a list of formats such as "MS2007 XML format (*.XML)", "Open Document Citation (*.XML)"

**Got:** a list of formats with only the filename extension for indication, such as "XML file (*.XML)", "XML file (*.XML)"

Although they are all en-capsuled using XML, but they are different formats and now we cannot identify one from another. Other formats suffer from this issue as well.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
