### ISSUE TITLE
jabref for ipad

### ISSUE THREAD

**Issue by zhangkmsjtu** [JabRef/jabref#3611]
How can I use it on the ipad?

**Comment by lenhard** [comment]
JabRef is still a desktop application, not an app. So, to the best of my knowledge, you can't use JabRef on the iPad unfortunately.

**Comment by TOB-KNPOB** [comment]
Though not a real solution, I write some scripts to convert the JabRef repository to a series of Markdown files. It can be viewed on iPad with [Obsidian](http://obsidian.md), and the links between groups and entries are added for convenience.

If what you need is merely browsing the literature you collected on iPad, this may be adequate to serve your need. You may check it [here](https://github.com/TOB-KNPOB/Jabref2Obsidian) if you're interested. Following are some example pages generated with it:

<img width="1292" alt="note_page" src="https://user-images.githubusercontent.com/77708899/223037002-50ed9e7f-bf94-43ab-b2e1-1685652f1d20.png">

<img width="1292" alt="group_page" src="https://user-images.githubusercontent.com/77708899/223036956-0daefb76-6440-408a-802f-51832d6f2738.png">
