### ISSUE TITLE
Download no longer shows progress

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#3614]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

recent master

Steps to reproduce:

1. Create entry and go to General tab
2. Click "Download from URL" button and insert a link to a relatively large PDF. Click ok.
3. When the download starts an empty progress bar is displayed. However, the progress is not updated and the progress indicator is hidden immediately.

**Comment by Siedlerchr** [comment]
Refs #3005
