### ISSUE TITLE
The group field is missing?!

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3615]
Stable release Jabref 4.1

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 Win 7-64

Steps to reproduce:

1. Open jabref 4.1
2. select a group and try to edit an entry
3. Any group field cannot be found in "optional" "rejected" "other" "general" field, it is still in the biblatex source. 

IIRC from previous discussions, it should have been now under "general". I could show you a screenshot, but this you can easily see yourself.

Regards
Bernhard

**Comment by Siedlerchr** [comment]
Confirmed in latest master. Should really be under general.

**Comment by lenhard** [comment]
Hm, for me the group field is where it should be. It seems that it's possible to configure the contents of the general tab in the preferences. Maybe this is related to this problem. However, I am unable to find a UI control where you can actually do this.

**Comment by bernhard-kleine** [comment]
I looked through preferences and under groups or "eintragseditor" there was not any indication that the group field is to be configured. Please show a screenshot of the entry editor with the groups field present.

**Comment by tobiasdiez** [comment]
Did you followed the instructions in the changelog?
> We moved the groups field from the "Other fields" tab to "General" (you may have to reset your editor preferences under Options > Set up general fields)

**Comment by bernhard-kleine** [comment]
There was a little trouble due to missing translation. Since I use the Germen version, it was not obvious to me that "allgemeine Felder festlegen" meant the fields under the General tab (General even in German), this General should to be translated to Allgemein. I have now the group field under General.

**Comment by tobiasdiez** [comment]
Thanks for the feedback. 
You can propose better translations yourself: http://translate.jabref.org/
