### ISSUE TITLE
Re-evaluate table after pasting entry or editing an antry

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3618]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

Steps to reproduce:

Pre-Condition: Have a group with keyword "ADR"

![grafik](https://user-images.githubusercontent.com/1366654/34679459-54c90914-f496-11e7-9bd8-88f2790b1d5f.png)

## Case 1: Edit entry to contain keyword ADR

Before:

![grafik](https://user-images.githubusercontent.com/1366654/34679487-6d09d9d6-f496-11e7-8740-f27cea6481ed.png)

After:

![grafik](https://user-images.githubusercontent.com/1366654/34679495-74d183a8-f496-11e7-8831-bfbd41b80a01.png)

Expected:

![grafik](https://user-images.githubusercontent.com/1366654/34679554-9f7490e6-f496-11e7-97fd-004ea34ca161.png)

## Case 2: Paste entry with keyword

As is:

![grafik](https://user-images.githubusercontent.com/1366654/34679596-c24162e8-f496-11e7-922f-a6a00c9d1fad.png)

Expected:

![grafik](https://user-images.githubusercontent.com/1366654/34679614-ca9d4b8c-f496-11e7-9df9-7e1c15b0f699.png)

**Comment by tobiasdiez** [comment]
Should be fixed with #3591.

**Comment by koppor** [comment]
KK, I put it "on-hold" to reduce the number of issues, it will be fixed, and it seems I am currently the only one touching this issue :)

**Comment by tobiasdiez** [comment]
It is indeed fixed with https://builds.jabref.org/maintable-beta/. I hence remove the "on-hold" tag.
