### ISSUE TITLE
Renaming of files should keep file in directory

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#3619]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

This is a regression of 3.x to 4.1. I'm not sure which version it worked at last.

Steps to reproduce:

1. Store a file in bibdir/subdir
2. Execute cleanup

![grafik](https://user-images.githubusercontent.com/1366654/34679725-2473b2b8-f497-11e7-9c5f-1b240d20cce1.png)

3. File is renamend AND MOVED to bibdir

Expected: File should be put into bibdir/subdir.

**Comment by Siedlerchr** [comment]
From your screenshot it appears that you have both renaming and moving enabled
"Move linked files to default file directory" -> BtSync\lit...

**Comment by koppor** [comment]
Then, the default should be disabled. Or be more intelligent? The button should not be checked if the file is already in a subdirectory of the bib dir?

**Comment by tobiasdiez** [comment]
Didn't we introduce the `file directory pattern` to handle the placement in subdirectories? Maybe I just don't see your usecase but I would like to keep the algorithm as simple as possible.

**Comment by koppor** [comment]
Sometimes, I am the only user of JabRef using the advanced features. I should begin writing blog entries. 😇 

I manually place files in the (for me) **correct** file folder. Then, I drop them into the main table/entry editor to get them linked (refs https://github.com/JabRef/jabref/issues/121). The dialog is currently not appearing as in version 3.x, so I push the cleanup button and expect that JabRef just renames the file. For me, **removing** a checkmark to **keep** a file in the current directory (which was hard work to choose ;)), is counter-intuitive for me.

**Comment by tobiasdiez** [comment]
Ok, I see your point. But how should JabRef detect that you placed the file in the correct directory?

**Comment by koppor** [comment]
If it is in a sub directory of the default directory, it is correct. The check is the same as used for "Rename only PDFs having a relative path".

I am not sure whether the least WTF would be to set the default of "Move linked files to the default folder ..." to `false`. Not any check. --> implemented in https://github.com/JabRef/jabref/pull/3620.
