### ISSUE TITLE
Cursor reset in multi-line fields after bibtex source edit

### ISSUE THREAD

**Issue by schmohlo** [JabRef/jabref#3622]
- [X] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 on Windows 10

Steps to reproduce:

1. Open Jabref 4.1 
2. Add a new entry to a existing database (or choose an old one)
3. Make some alterations in the bibtex source code
4. Enter some text in one ot the multiline fields (abstract, review)
5. Press enter on keyboard
6. Write some new text

<details>
 After the new line is created or after the first letter of step 6, the cursor is placed at the beginning of the first line, and also after each letter. Restarting Jabref fixes the issue temporarily.
![grafik](https://user-images.githubusercontent.com/35264015/34725453-40c3d4b0-f551-11e7-9ec0-d2bfb4ab6466.png)

</details>

**Comment by lenhard** [comment]
Probably related #3471

**Comment by stefan-kolb** [comment]
I would even say it is a duplicate.
