### ISSUE TITLE
OS-specific paths to external applications

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#3628]
My bibliography folder is synced across Windows and Linux machines.

However, for external applications (e.g., TeXstudio) there is currently (as for 4.1) only one path field for each application. I set it to `C:\Program Files (x86)\TeXstudio\texstudio.exe` when working on Windows (in the morning), and change it to `texstudio` when on Linux (at home). 

For people with similar setup, it would be convenient to allow multiple OS-specific paths, one of which is used based on the host OS. Do you agree?

(viva JabRef!)

**Comment by lenhard** [comment]
It is new information to me that this path is part of the bib file. Isn't this stored in the preferences? 

The preferences are tied to the OS user account and that will be different for different machines. So it shouldn't be a problem to set it to a different value on a Windows and a Linux machine. Am I wrong in that assumption?

**Comment by anassal** [comment]
Hi lenhard, 

I forgot to say I use Jabref in the 'portable/memory stick mode', so the local jabref.xml is synced across machines.

**Comment by anassal** [comment]
Also, Jabref is also synced in my setup.

**Comment by lenhard** [comment]
Ok, then it makes sense. The preferences would be in the XML file.

I'll categorize this as a feature request for OS-specific push-to-application preferences. I guess this would be doable by extending the preferences, the corresponding UI and the push-to-application code.

**Comment by tobiasdiez** [comment]
@anassal The command `textstudio` might also work on Windows if you add `C:\Program Files (x86)\TeXstudio\` to your PATH environment variable.

**Comment by anassal** [comment]
@tobiasdiez Thanks for the idea. I added `c:\Program Files (x86)\TeXstudio` to the PATH user variable (Windows 8.1): `texstudio` from the command line launched TeXstudio as expected, but JabRef said

> Error: could not call executable 'texstudio'. 

Is there something I'm missing? Have this worked for other users?

**Comment by stefan-kolb** [comment]
I think we need to divide the preferences in OS-specific preferences and preferences which are portable, i.e., concern the settings for a Bib file. Only those which are portable should be stored inside the XML.
Only problem here is that we also use to export and import preferences via this XML which would break exporting all preferences attributes.

**Comment by Siedlerchr** [comment]
To your workaround: You have to enter the program path to textstudio in the **system** environment variables. Not in the user environment variables.
