### ISSUE TITLE
Visual selection only possible for first entry in the file field tab

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3639]
Visual selection (highlighting) only possible for first entry in the file field tab
![image](https://user-images.githubusercontent.com/2141507/35033744-0dc30312-fb6c-11e7-91c2-f773b9947808.png)

**Comment by Siedlerchr** [comment]
If you have three files then you can select the third one as well, seems only to work with odd rows. Could be some css styling or whatever.

**Comment by Siedlerchr** [comment]
I tried a bit around and I can exclude some things:
It's not a problem with the underlying CSS, nor a problem with the CellFactory, nor with the jfxpanel container.  I created a little demo app to test this.
The only thing I could image is about the concrete LinkedViewFileModel.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
