### ISSUE TITLE
ID-based entry generator ISBN search does not accept ISBN without -

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3643]
Try:
`978-1449304232`
vs
`9781449304232`.

`Error fetching metadata`

https://www.amazon.de/Sinatra-Up-Running-Alan-Harris/dp/1449304230/ref=sr_1_1?ie=UTF8&qid=1516196675&sr=8-1&keywords=Sinatra%3A+Up+and+Running

**Comment by Siedlerchr** [comment]
I can not reproduce this. Both versions work for me. 
New Entry-> ISBN

**Comment by stefan-kolb** [comment]
Surpringly the same for me.. 🤔
