### ISSUE TITLE
Parameterized tests are not executed on travis

### ISSUE THREAD

**Issue by lenhard** [JabRef/jabref#3645]
Based on this discussion: https://github.com/JabRef/jabref/pull/3642#issuecomment-358591687

It seems that the move to JUnit5 has somehow turned off the parameterized tests on travis. That's bad, because it means that our importer tests are basically gone. We need a way to re-enable them, most likely by adapting them to JUnit5 syntax.

**Comment by Siedlerchr** [comment]
If I execute them in Eclipse with junit5, they are listed as a single test

**Comment by Siedlerchr** [comment]
For the migration to juit5. Refs https://github.com/junit-team/junit5/issues/1247

**Comment by stefan-kolb** [comment]
Are these tests running now? PR is merged.

**Comment by Siedlerchr** [comment]
Most of them. We still have a few left  especially those with Temporary folders. And not all of them are executed. 
However, an official support for them is currently planned for the next milestone (see linked issue above)
