### ISSUE TITLE
Refactor entry type/custom entry type logic

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#366]
Further work from #352:
- [ ] Primary/SecondaryOptionalFields is only used in BibLatex and this logic should be moved into the GUI code.
- [ ] How to handle OR requirements in the GUI? Currently both are marked as required. Next to each other? Highlight required fields red if empty and green if entry hasAllRequired?
- [ ] Check for duplicate field names in requirements and optionals (use a Set? what about 'author/editor'<->'editor/author')
- [x] Rework custom entry types and include them in the GUI 'new entry'
- [x] What about overriding known types? (allowed? rejected? what if [natbib](https://www.ctan.org/pkg/natbib) uses 'book'? and I just need this custom type for natbib files? What about [jurabib](https://www.ctan.org/pkg/jurabib)?)
- [x] Add more tests
- [x] Resetting overridden default entry types does not work, sometimes even crashes

**Comment by koppor** [comment]
Regarding "OR": In [the doc](http://jabref.sourceforge.net/help/CustomEntriesHelp.php) at "Either/or fields", it is talked about that this should work with a special configuration. At least for custom types.

**Comment by tobiasdiez** [comment]
Also:
- Store custom entry types in MetaData class and reuse some of the parsing/writing logic.

**Comment by matthiasgeiger** [comment]
"Rework custom entry types and include them in the GUI 'new entry'" is already included:
![custom-new-entry](https://cloud.githubusercontent.com/assets/676652/21097634/dc5d3ab4-c065-11e6-81b6-39309ffe2116.png)

**Comment by LinusDietz** [comment]
superseded by https://github.com/JabRef/jabref/projects/6
