### ISSUE TITLE
Crossref field is erased if the entry that matches the required crossref field is deleted (even if the bibtex key is duplicated)

### ISSUE THREAD

**Issue by magsilva** [JabRef/jabref#3663]
Crossref field is erased if the entry that matches the required crossref field is deleted (even if the bibtex key is duplicated)

I have tested it on JabRef version 4.1 on Fedora 27 (but I had observed it since version 4.0).

Steps to reproduce:
1. Create an entry with bibkey 'abc'
2. Create another entry with bibkey 'abc' (yes, we will have duplicated entries)
3. Create an entry with a crossref set to 'abc'
4. Erase any of the entries with bibkey 'abc'
5. The entry that has the crossref set to 'abc' will have that crossref information removed (although there is an entry which bibkey still matches the required crossref').

My suggestion:
- After deleting an entry, check if there is a match to the crossref'ed entry. If so (as it is the case for duplicated bibtex entries), leave it as it is. If there isn't a match, ask the user if the entry should be deleted (or, at least, create a configuration option to handle this). Personally, I would prefer to leave the crossref field as is, so that I could detect (and fix) the inconsistency later.

**Comment by stefan-kolb** [comment]
In our notion, bibtex keys must be unique. So I have to tag this as wont fix.
