### ISSUE TITLE
Annotations tab - Annotation selection not visible for even numbered annotations

### ISSUE THREAD

**Issue by serialc** [JabRef/jabref#3664]
Version:
JabRef 4.2-dev--snapshot--2018-01-20--macInstall4j--3d5e9f251
Mac OS X 10.13.2 x86_64 
Java 1.8.0_152

Steps to reproduce:

1. Open the File Annotations tab for a reference with a PDF linked and highlighted text.
2. Click on the first annotation and notice it becomes blue while the text is shown in the right panel.
3. Click on the second annotation. **The annotation does not become blue (provides no feedback).** The right panel _does_ update to show the correct information however.

Bug: **Highlighting of even numbered annotations, on click, is absent. Functionality is fine however.**

First annotation selected:
![annotation1_selected](https://user-images.githubusercontent.com/777410/35380867-6038a2ea-01b2-11e8-8fe6-9df37a62e673.png)

Second annotation selected:
![annotation2_selected](https://user-images.githubusercontent.com/777410/35380868-605cd192-01b2-11e8-89fa-9ce9d725feb8.png)

**Comment by Siedlerchr** [comment]
This seems like the same issue with the file list view in the general tab.

**Comment by serialc** [comment]
I tested the File list in the **General tab** as @Siedlerchr said. Yes - it's exactly the same issue. Following this I explored other lists and found the same problem in the **Optional fields** tab - Month drop down list.

**Comment by Siedlerchr** [comment]
Okay, thanks for your quick test. I hope this helps us to narrow the error down as it seems to be a more general problem with the listview.
Refs #3639

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
