### ISSUE TITLE
ISI import failure related to String index out of range: -1

### ISSUE THREAD

**Issue by elizagrames** [JabRef/jabref#3669]
JabRef version 4.1 on Ubuntu 17.04 (and also the latest master build) fails to import ISI files (saved as .txt) if the field PS has no hyphen in it. Examples to repeat the issue are below. The error is "String index out of range: -1". 

**Will import:**
```
PT J
DT Article
TI Example title.
PS 201-
BP 201
EP 299
LA English
AB Example abstract text.
ER

EF
```

**Will not import:**
```
PT J
DT Article
TI Example title.
PS 201
BP 201
EP 299
LA English
AB Example abstract text.
ER

EF
```

**Comment by stefan-kolb** [comment]
Is this format even still in use? I cannot find any documentation on the file format in the web?

**Comment by stefan-kolb** [comment]
Also not sure what PS is used for. https://web.archive.org/web/20131031052339/http://wos.isitrial.com/help/helpprn.html
Does not say anything about such a field.

**Comment by elizagrames** [comment]
ISI is still used by Web of Science if you export references for "other reference software." I have no idea why they include PS (it's the page range) but it prevents the import. The workaround I did was to just use sed to remove all lines beginning with PS.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
