### ISSUE TITLE
Delete from disk should not be default option/selected on DELETE in file tab

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3679]
![image](https://user-images.githubusercontent.com/2141507/35624303-e83114da-068e-11e8-9b3d-d38aa0c4fd9a.png)

Changing the buttons should be sufficient.

**Comment by bdach** [comment]
Hi! :wave: 

I have submitted a pull request aiming to fix this issue (and another issue with the "Cancel" button, which I discovered during testing my first change). I would appreciate it if you could review the changes and suggest possible improvements!
