### ISSUE TITLE
merge bibtexkeys on linux, text does not show up

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#3686]
JabRef 4.1
Linux 4.13.0-32-generic amd64 
Java 1.8.0_161

Steps to reproduce:

1. open a bibfile with two time the same bibtexkey on Linux (any theme)
2. Click yes on the question if you want to merge them
3. then there are two white boxes appearing (I think there should be text?)

![screenshot from 2018-02-02 11-16-08](https://user-images.githubusercontent.com/15687581/35728532-27e308b2-080c-11e8-9740-a3e9e0070d0c.png)

The Log-file does not tell anything.
I tested all existing themes.

**Comment by Siedlerchr** [comment]
On Windows it worked as expected. I will checkout this error on my Ubuntu machine.

**Comment by JoKalliauer** [comment]
```
JabRef 4.2-dev--snapshot--2018-02-04--master--6bac6ff2f
Linux 4.13.0-32-generic amd64 
Java 1.8.0_161
```

Still does not work on my computer.

![screenshot from 2018-02-05 11-04-45](https://user-images.githubusercontent.com/15687581/35798937-8389d34e-0a64-11e8-96aa-cf15caedd18b.png)

```bib
% Encoding: UTF-8
@Article{Kalliauer2018,
  author    = {Kalliauer, Johannes and Schlappal, Thomas and Vill, Markus and Mang, Herbert and Pichler, Bernhard},
  title     = {Bearing capacity of concrete hinges subjected to eccentric compression: multiscale structural analysis of experiments},
  journal   = {Acta Mechanica},
  year      = {2018},
  month     = {Jan},
  issn      = {1619-6937},
  day       = {17},
  doi       = {10.1007/s00707-017-2004-3},
  publisher = {Springer Nature},
  url       = {https://doi.org/10.1007/s00707-017-2004-3},
}

@Article{Kalliauer2018,
  author    = {Kalliauer, Johannes and Schlappal, Thomas and Vill, Markus and Mang, Herbert and Pichler, Bernhard},
  title     = {Bearing capacity of concrete hinges subjected to eccentric compression: multiscale structural analysis of experiments},
  journal   = {Acta Mechanica},
  year      = {2018},
  month     = {Jan},
  issn      = {1619-6937},
  day       = {17},
  doi       = {10.1007/s00707-017-2004-3},
  publisher = {Springer Nature},
  url       = {https://doi.org/10.1007/s00707-017-2004-3},
}

@Comment{jabref-meta: databaseType:bibtex;}

```
<details>
<summary>Log-file (nothing interesting)</summary>
Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib<br/>
Opening: /home/jkalliau/ownCloud/LaTeXBI/LaTeX-Vorlage-Dissertation-TUWBI-201801/Literatur.bib<br/>
Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/Kalliauer.bib<br/>
Warning: could not get message translation for "Opens JabRef's Twitter page" for locale de<br/>
</details>
<details>
<summary>Terminalmessages (nothing interesting)</summary>
<br/>
AI: INFO 05-02-2018 11:10, 20: Configuration file has been successfully found as resource<br/>
11:10:34.018 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib<br/>
11:10:34.260 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/LaTeXBI/LaTeX-Vorlage-Dissertation-TUWBI-201801/Literatur.bib<br/>
11:10:34.264 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/Kalliauer.bib<br/>
11:10:34.526 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Opens JabRef's Twitter page" for locale de<br/>
File: grouptree.fxml not found, attempting with camel case<br/>
File: grouptree.css not found, attempting with camel case<br/>
</details>

**Comment by JoKalliauer** [comment]
Sorry, I just had to change theme, now it works! Thanks!

![screenshot from 2018-02-05 11-14-45](https://user-images.githubusercontent.com/15687581/35799462-10809e62-0a66-11e8-95d7-de61058a300f.png)

![screenshot from 2018-02-05 11-15-14](https://user-images.githubusercontent.com/15687581/35799466-16899b88-0a66-11e8-9572-0adfab48e9b7.png)

![screenshot from 2018-02-05 11-16-11](https://user-images.githubusercontent.com/15687581/35799468-196a73ae-0a66-11e8-8e2d-968d54e2d708.png)
