### ISSUE TITLE
Export selected 

### ISSUE THREAD

**Issue by mpele** [JabRef/jabref#3693]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version JabRef-4.2-dev--snapshot--2018-02-04--master--6bac6ff2f.jar 

Steps to reproduce:
1. Select some entities 
2. Export selected

The last used type for export is not remembered and in case of overwriting the old file the confirmation is asked two times.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by mpele** [comment]
Thanks.
I will open new issue for not remembering last used type for export.
