### ISSUE TITLE
Preference value of entry table font size is not updated when changed from the menu

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#3716]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-02-11--master--f1977f53e
Windows 8.1 6.3 x86 
Java 1.8.0_161

Steps to reproduce:

1. View (menu) --> Increase table font size [table font size increases]
2. Options --> Preferences --> Appearance --> Set table font [_Font size preference value is not updated_]
3. Press Ok [_table font size resets to the preference value_]

Also, the keyboard shortcut `Ctrl+Plus` doesn't work, but `Ctrl+Minus` and `Ctrl+0` work fine.

**Comment by tobiasdiez** [comment]
Table font size customization was removed in the current development version since it should no longer be necessary to change only the font of the main table. Customization of the global font size is coming with #4178.
