### ISSUE TITLE
Tests in master break

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#372]
The tests in the current master branch break. Not good :-1:

**Comment by stefan-kolb** [comment]
Build is passing again.

**Comment by tobiasdiez** [comment]
And breaking again :)

**Comment by koppor** [comment]
@tobiasdiez Are you aware of https://circleci.com/docs/configuration#notify? Multiple emails in our inbox with the same content does not help. :umbrella: Could you please report minor issues at https://github.com/koppor/jabref/? :two_men_holding_hands:

**Comment by tobiasdiez** [comment]
Sorry, I really didn't know about the notification function of circlci and just wanted to let you know that there is a problem.
