### ISSUE TITLE
Search field input is added in reversed order

### ISSUE THREAD

**Issue by Brainsucker92** [JabRef/jabref#3727]
~~When typing any text into the search field the text is added in reversed order.
For example when typing 'Hello' the search field ends up showing: 'olleH' which is quite a strange behaviour.~~

- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef *unknown*
Windows 7 6.1 amd64 
Java 1.8.0_161

Steps to reproduce:

 1. ~~type anything into the search field~~

EDIT: I have absolutely no idea how and why this issue happenend to me before but actually it seems to be fixed now, eventhough I updated to the latest version of the master branch before writing this isse. Very strange... looks like this issue can be closed.

**Comment by lenhard** [comment]
That sounds funny :-) 

I'll close this now, as you suggest. Feel free to reopen it if you manage to reproduce the problem.

**Comment by Siedlerchr** [comment]
Maybe you accidentally changed your input layout from left to right to the right to left? (you know, as for Arabic)

**Comment by Brainsucker92** [comment]
@Siedlerchr I don't think so, the issue was fixed after I restarted the program. In other programs I didn't experience this problem which means it might be related to JabRef itself. Hopefully this occurrence was a 'one and only' thingy.
