### ISSUE TITLE
Entries dissapear and reappear as duplicate of other items

### ISSUE THREAD

**Issue by Pouya-moh** [JabRef/jabref#3728]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 on Linux 4.10.0-32-generic amd64 with Java 1.8.0_151

> Steps to reproduce:

I can't explain the steps, but I will explain my workflow and describe what happens. I usually find a paper online and then import it by doi either from "Web search" or "New bibtex entry". Then I will change the bibtexkey to my liking.

Today, for the third time, suddenly some of my imported items changed to some previously imported entries. For instance, I have a already existing "Foo" and now I import a "Bar". Out of nowhere, suddenly I have two "Foo"s. My other citations are gone, and I have duplicate entry error.

Any ideas?

**Comment by tobiasdiez** [comment]
This issue was already reported (I cannot find the link right now) and should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!
