### ISSUE TITLE
Don't convert unknown entries to @Other or @Misc

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#376]
Unknown entries shouldn't be converted to `@Other` but instead the custom entry type should be kept. Using the `UnknownEntyType` this should be easy to achieve.

**Comment by stefan-kolb** [comment]
This was the case before but isn't the case now.

**Comment by koppor** [comment]
Which build are you referring to? :camel: Maybe you didn't see that we are currently active (this contradicts #372). :honeybee: Did you test [JabRef v.2.11.1](https://github.com/JabRef/jabref/releases/tag/v2.11.1)? :octocat: We worked on it and fixed it. :hurtrealbad:

**Comment by tobiasdiez** [comment]
I added some tests in the parser which didn't passed because the parsed type was "Other". But with the very recent code changes by @stefan-kolb the tests also pass. So indeed already fixed.
