### ISSUE TITLE
The "biblatex source" text field is deselected after every key

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3763]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev

Steps to reproduce:

1. open the source tab of an entry
2. try to change the type by typing between @ and {

workaround: a mouse click on the position where the cursor was before after every key stroke

**Comment by lenhard** [comment]
Though it's not obvious, this is caused by the same changes as #3730: Changing the entry type.

We'll either find a solution to this or revert the underlying changes before the release of 4.2

**Comment by Siedlerchr** [comment]
With #3872  typing works fine, except betwen changing the entrytype. But that' is in my opinion an edge case. It's way easier to do a rightclick and select --> Change entry type.

This is a cause of the runInFXThreadAndWait. But it's necessary to have this, as otherwise the maintable is f*cked up.
