### ISSUE TITLE
Freeze on rename file action

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3768]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev on OSX

Steps to reproduce:

1. add file to entry
2. choose "rename file"

Jabref does not react to anything but "force quit" anymore.

**Comment by LinusDietz** [comment]
I use that feature basically every days on all kinds of branches and never had problems.

**Comment by stefan-kolb** [comment]
> I use that feature basically every days on all kinds of branches and never had problems.
👍

**Comment by stefan-kolb** [comment]
Sorry, we cannot reproduce the issue with the current information.

**Comment by LinusDietz** [comment]
I guess I'll close this for now. @j0hannes, thank you for your report. Does it happen all the times, or just sometimes?

**Comment by j0hannes** [comment]
It happened more than once, but just now I tested it successfully. I have no idea why in some cases it led to a crash.
