### ISSUE TITLE
After downloading a pdf, the suffix is missing and opening the file fails

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3772]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev

Steps to reproduce:

1. choose General > Get fulltext for an entry
2. click on PDF symbol

The error message is "unable to open file". Renaming the file via "Rename file" option adds the .pdf suffix, which solves the problem.

**Comment by Siedlerchr** [comment]
Could you please edit the title of the issue and provide us with the bibtex entry for which it failed so we can see which fetcher was used to download the fulltext.

**Comment by Siedlerchr** [comment]
Could you please edit the title of the issue and provide us with the bibtex entry for which it failed so we can see which fetcher was used to download the fulltext.

**Comment by j0hannes** [comment]
I think it was this one:
```
@Article{Langer2004,
  author        = {Langer, Stefan},
  title         = {A linguistic test battery for support verb constructions},
  journal       = {Lingvisticæ Investigationes},
  year          = {2004},
  volume        = {27},
  number        = {2},
  pages         = {171--184},
  publisher     = {John Benjamins Publishing Company},
}
```

**Comment by Siedlerchr** [comment]
Hm. That entry works fine.  I would vote to close the issue and you reopen it when you identify an entry/concrete fetcher which produced that file.
