### ISSUE TITLE
Add Tagalog (Phillipine language) as language for JabRef

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3776]
Request from a User at crowdin:
TODO:

- [x] Add a new property file (ISO Code "tl" ) with the keys,  @Brainsucker92   Does the script support the creation of a new file with just the english keys?

- [x] Adjust code?
- [x] Add to crowdin?
- [ ] Adjust wiki/help?

**Comment by Brainsucker92** [comment]
No, this feature is currently not supported. But you could simply create the file yourself and the next update by the script will automatically add all keys to the file.

**Comment by stefan-kolb** [comment]
@Siedlerchr What do you mean with adjust wiki/help? The rest seems to be done?!

**Comment by Siedlerchr** [comment]
We once had a list of the translation status for each language in the wiki, but with crowdin this is kinda obsolete.
