### ISSUE TITLE
Improper handling of multi-line text in the "Review" section

### ISSUE THREAD

**Issue by c3h899** [JabRef/jabref#3780]
JabRef version 4.1 on Windows Server 2016 64-bit (Fresh Install)
"JabRef 4.1
Windows Server 2016 10.0 amd64 
Java 1.8.0_152"

Steps to reproduce:
1. Modify citation entry "Review" to contain a multi-line comment (containing newline/carrage return characters).
2. Observe poor cursor placement, and save.
3. Note duplicated (overwritten) entries.

Bibliography can be attached if needed (contact me). However this seems to easy to reproduce without it.

No log file. However the ability to add or modify additional articles may break. This result is less reproducible, hence, not mentioned directly.

Personal note: To the developers and maintainers of this project, thank you.

**Comment by LinusDietz** [comment]
Hi @c3h899, we have done some modifications lately concerning this field. can you check the current master, if this problem persists? Note that it is now called comments instead of review.

**Comment by c3h899** [comment]
I switched machines- (read your posting after I left my office.)
I will try to make a point of testing on my original machine tomorrow.

However, the latest master build appears to have addressed this.
Cursor Behavior is definitely better.

Specifically:
Notable Change: Windows 7 x64 (Different OS)
Using: JabRef_windows-x64_4_2-dev--snapshot--2018-02-26--master--d19b6d74e.exe
JRE Version: jre-8u161-windows-x64.exe

Testing Methodology:

1. Open a clean copy of "Test_Clean.bib"
2. Modify: "Optically Powered..."
3. Add Comments (no quotes):
	"
	Key Findings:
	-This is a finding
	-This too is important
	-Don't forget this
	-Publications matter
	"
4. Save
5. Remove NewLines from Entry
6. Save
7. Re-Add
8. Save
9. Create new inproceedings
10. Overwrite with source included:
	"
	@INPROCEEDINGS{8284384, 
	author={M. Taha and D. Abualnadi and O. Hasan and E. A. Feilat}, 
	booktitle={2017 7th IEEE International Conference on Control System, Computing and Engineering (ICCSCE)}, 
	title={Lightning impulse parameters estimation using fractional model order reduction}, 
	year={2017}, 
	volume={}, 
	number={}, 
	pages={80-84}, 
	abstract={In this work, the lightning impulse parameter estimation is formulated as a fractional model order reduction problem. In this method the received impulse is viewed as an impulse response of an unknown fractional order system. Unlike that of the existing techniques the estimation of the signal parameters is carried out for an unknown number of modes in which all signal modes are compressed using a proposed frequency domain template. This eliminates the necessity of identifying all signal parameters that usually needs computationally demanding matrix analysis. For this purpose, a fitness function is provided such that its minima are the parameters of the impulse by which the mean curve and the impairments are reconstructed accurately. Simulation results have shown accurate representation for the underlying impulse for oscillatory and front overshoot signal models.}, 
	keywords={Conferences;Control systems;Frequency-domain analysis;Lightning;Oscillators;Particle swarm optimization;Transfer functions;Fractional order control;Lightning Impulse;Mean curve;Model order reduction}, 
	doi={10.1109/ICCSCE.2017.8284384}, 
	ISSN={}, 
	month={Nov},}
	"
11. Add multiline comment
12. Save

Files and results included for ease of reproducability
[Testing.zip](https://github.com/JabRef/jabref/files/1760546/Testing.zip)

**Comment by c3h899** [comment]
Yeah, that particular issue seems resolved.

On the Original Machine,
Testing using: JabRef_windows-x64_4_2-dev--snapshot--2018-02-27--master--a51fff8e0.exe
