### ISSUE TITLE
External modifications of the entry type are not detected

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3787]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev

Steps to reproduce:

1. open a bib file
2. externally edit one entry, including the entry type
3. accept the changes in JabRef

All changes are accpted except for the entry type. Possibly related to #3730?

**Comment by stefan-kolb** [comment]
I can confirm this behavior. The changes are even not detected if one just changes the entry type. Only changes to the attributes are detected.

**Comment by Siedlerchr** [comment]
This issue is still present in 5.x. EntryType is not detected

**Comment by koppor** [comment]
Refs #5085 #4143

**Comment by j0hannes** [comment]
Just for the record: changes of the entry type are now correctly detected and displayed.
