### ISSUE TITLE
Crashes after accepting edits

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3788]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev

Steps to reproduce:

1. accept external modifications to the bib file
2. continue editing using inside JabRef

It seems that the external edit will eventually lead to a crash, at least I can reliably make the application crash like this.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`.
