### ISSUE TITLE
OSX: With maintable-beta, JOptionPane for the "load backup file"  on startup does not show up and freezes JabRef

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#3799]
I am sure now that this is indeed a problem. I suspect this issue was introduced after we made JabRef an FX application. Now, the initial confirmation dialog if I want to load a `.sav` bibliography does not show up any longer. The window is not hidden and JabRef goes in a waiting loop that I cannot leave.

I believe the issue here is that we still use Swing for the confirmation dialog in 

```
org.jabref.gui.dialogs.BackupUIManager#showRestoreBackupDialog
```
and in some other places too.

How to reproduce:

- System Mac OS X 10.13.3 x86_64, Java 1.8.0_162, maintable-beta branch
- Leave JabRef dirty once so that you have a `.sav` file for your opened bibliography
- Start JabRef either through the IDE, terminal or by double-clicking on the jar.

This issue does not appear on Linux. I have not tested Windows.

**Comment by Siedlerchr** [comment]
On windows I can not reproduce this. But shouldn't be hard to replace the fileDialog.  I will create a PR for this and then you can test this again under OSX and hook into that PR.

**Comment by tobiasdiez** [comment]
Yes, it would be nice to replace all the swing confirmation/warning/error dialogs by their JavaFX equivalent (using the `DialogService` interface).

**Comment by halirutan** [comment]
@Siedlerchr Thanks. I have verified this now on a second OSX machine. Our master-branch works but the maintable-beta goes into a waiting loop and the dialog never shows up.

**Comment by Siedlerchr** [comment]
Did you try out the branch from my pr?  If it works?

**Comment by halirutan** [comment]
Later. After dinner.
