### ISSUE TITLE
"File updated externally" error message

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3813]
JabRef 4.2-dev--snapshot--2018-03-06--master--bb471a26d
Linux 4.13.0-36-generic amd64 
Java 1.8.0_161

- [yes ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

Steps to reproduce:

1. working quietly and innocently.
2. popup appears on the screen saying   "File updated externally"

![screenshot from 2018-01-14 23-13-01](https://user-images.githubusercontent.com/762246/37115643-f5a11ac6-2208-11e8-9bcd-30b431867940.png)

3. I have to choose.  Save normally works and clears the popup.  

4. Sometimes, though, I am forced to Review Changes.  In some cases the database is then suddenly populated with duplicate copies of many entries.

I use Dropbox, including for the directory where my bib files live.  But I turned off Dropbox syncing and still got the error.

Best,
Dominik

**Comment by wujastyk** [comment]
I now think this is the same as  report #3775

**Comment by wujastyk** [comment]
Sometimes the screen looks like this, but essential it's the same problem:
![screenshot from 2018-03-08 15-59-58](https://user-images.githubusercontent.com/762246/37188576-22ca6af2-230d-11e8-86c4-3fc5cdd6b51b.png)

**Comment by stefan-kolb** [comment]
Duplicate of #3775?

**Comment by wujastyk** [comment]
Yes, I believe so.  I'll move over to #3775.
I had the problem just yesterday, with the library populated with duplicate entries.  My main library file is now over 4000, so I had 8000 entries.  The duplicates checker did a good job, but it took quite a while.
