### ISSUE TITLE
Adjust eclipse style to intellij (line wrapping)

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3815]
Has intellij one or two default indendation lines? @tobiasdiez 
I now changed to align on column

[JabRefModdedStyleSettings.xml.txt](https://github.com/JabRef/jabref/files/1791055/JabRefModdedStyleSettings.xml.txt)

![grafik](https://user-images.githubusercontent.com/320228/37120788-a68af3be-225b-11e8-874b-a7874005c6ea.png)

![grafik](https://user-images.githubusercontent.com/320228/37120852-d567d5e4-225b-11e8-91f4-88498c86fdd3.png)

![grafik](https://user-images.githubusercontent.com/320228/37120873-e470f9da-225b-11e8-9c70-d633aad4823b.png)

![grafik](https://user-images.githubusercontent.com/320228/37120884-f4e0b300-225b-11e8-8bae-2a78b9e1c458.png)

**Comment by tobiasdiez** [comment]
What do you mean by "indendation lines"?

If you did not already change it, please don't forget to tweak the "chain and align on dot" policies, i.e. something like
````java
object.foo().bar()
      .bar2()
      .bar3();
````

should be considered correct and not be changed.

**Comment by Siedlerchr** [comment]
Align on Dot is not a direct option in Eclipse, that's controlled by the indentation columns and wrapping polices. That's why I included a Screenshot 

But note that in your examples is only correct if all operate on the same object, if

**Comment by tobiasdiez** [comment]
Mhh, I couldn't spot such a chain call in your screenshots. This is why I asked again. According to https://stackoverflow.com/questions/6275785/wrapping-chained-method-calls-on-a-separate-line-in-eclipse-for-java, the option `Indent on column` corresponds to the "align on dot" (and this option is now activated accordingly to your screenshots). Moreover, "Line wrapping policy" should be set to something not so aggressive. I think you should create PR with these changes.

**Comment by tobiasdiez** [comment]
@Siedlerchr can this be closed?
