### ISSUE TITLE
Duplicate finder brings the same duplicates even when told to keep both

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#3817]
- [X] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-06--master--bb471a26d
Linux 4.4.0-104-generic amd64 
Java 1.8.0_161

Steps to reproduce:

1. Quality -> Find duplicates
2. On first entry, click "Keep both"
3. Close duplicate finder
4. Quality -> Find duplicates again

The same first entry is shown.

**Comment by Siedlerchr** [comment]
As the information about duplicate is nowhere stored, every time you start the duplicate finder again, the entry is found as duplicate which is right , according to the duplicate detection algorithm.
It would be nice to see which entries are marked as duplicates and where they differ, so that the duplicate finder can be adjusted.
Could you paste the bibsource of the  entries here?

**Comment by erelsgl** [comment]
Sure. Here is one:

@inproceedings{Aziz2016Discrete,
    abstract = {We consider the well-studied cake cutting problem in which the goal is to
find an envy-free allocation based on queries from \$n\$ agents. The problem has
received attention in computer science, mathematics, and economics. It has been
a major open problem whether there exists a bounded and discrete envy-free
protocol. We resolve the problem by proposing a discrete and bounded envy-free
protocol for any number of agents. The maximum number of queries required by
the protocol is a power tower of \$n\$ of order six. We additionally show that
even if we do not run our protocol to completion, it can find in at most
\$n^{n+1}\$ queries a partial allocation of the cake that achieves
proportionality (each agent gets \$1/n\$ of the value of the whole cake) and
envy-freeness. Finally we show that an envy-free partial allocation can be
computed in \$n^{n+1}\$ queries such that each agent gets a connected piece that
gives the agent \$1/(3n)\$ of the value of the whole cake.},
    archivePrefix = {arXiv},
    author = {Aziz, Haris and Mackenzie, Simon},
    booktitle = {FOCS 2016},
    citeulike-article-id = {14015680},
    citeulike-linkout-0 = {http://arxiv.org/abs/1604.03655},
    citeulike-linkout-1 = {http://arxiv.org/pdf/1604.03655},
    day = {9-11},
    eprint = {1604.03655},
    keywords = {cake-cutting, envy-free, seminal},
    month = oct,
    pages = {416--427},
    posted-at = {2016-04-19 08:56:43},
    priority = {2},
    title = {{A Discrete and Bounded Envy-Free Cake Cutting Protocol for Any Number of Agents}},
    url = {http://arxiv.org/abs/1604.03655},
    year = {2016}
}

and here is the other:

@inproceedings{Aziz2015Discrete,
    abstract = {{We consider the well-studied cake cutting problem in which the goal is to
identify a fair allocation based on a minimal number of queries from the
agents. The problem has attracted considerable attention within various
branches of computer science, mathematics, and economics. Although, the elegant
Selfridge-Conway envy-free protocol for three agents has been known since 1960,
it has been a major open problem for the last fifty years to obtain a bounded
envy-free protocol for more than three agents. We propose a discrete and
bounded envy-free protocol for four agents.}},
    archivePrefix = {arXiv},
    author = {Aziz, Haris and Mackenzie, Simon},
    booktitle = {STOC 2016},
    citeulike-article-id = {13761485},
    citeulike-linkout-0 = {http://dx.doi.org/10.1145/2897518.2897522},
    citeulike-linkout-1 = {http://arxiv.org/abs/1508.05143},
    citeulike-linkout-2 = {http://arxiv.org/pdf/1508.05143},
    day = {18-21},
    doi = {10.1145/2897518.2897522},
    eprint = {1508.05143},
    keywords = {cake-cutting, envy-free},
    month = jun,
    posted-at = {2015-09-10 20:19:18},
    priority = {2},
    title = {{A Discrete and Bounded Envy-free Cake Cutting Protocol for 4 Agents}},
    url = {http://dx.doi.org/10.1145/2897518.2897522},
    year = {2016}
}

**Comment by LinusDietz** [comment]
Well, this is exactly how jabref should detect it.
