### ISSUE TITLE
Trouble starting JabRef 4.1 on Linux (Ubuntu 16.04)

### ISSUE THREAD

**Issue by ThomasA** [JabRef/jabref#3819]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1  on Ubuntu 16.04 

Steps to reproduce:

1. Download JabRef-4.1.jar from the SourceForge project page
2. Attempt to run it using `java -jar JabRef-4.1.jar`

I am using OpenJDK version 8u151-b12-0ubuntu0.16.04.2 distributed by Ubuntu.

<details>
  <summary>Command line output</summary>
  
  ```
  Error: Could not find or load main class org.jabref.JabRefMain
  ```
</details>

**Comment by ThomasA** [comment]
Bonus info: JabRef 3.4, which I have lying around from earlier, works just fine in my set-up.

**Comment by Siedlerchr** [comment]
See  FAQ for linux, you are missing the openjfx package
http://help.jabref.org/en/FAQlinux
