### ISSUE TITLE
jabref export xml not working in newest version 4.1

### ISSUE THREAD

**Issue by Guruprasad-Rao** [JabRef/jabref#3822]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 

Steps to reproduce:

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by tobiasdiez** [comment]
Please fill out the issue template and give more details what exactly is not working. Thanks.

**Comment by Guruprasad-Rao** [comment]
When we use export to xml (word) from jabref  The file .xml is not created propely. It cannot be imported in the microsoft word. ( Sorry I am not programmer)

**Comment by Siedlerchr** [comment]
Please try out the latest master version https://builds.jabref.org/master/
Works fine for me, tested with Word 2013

**Comment by bernhard-kleine** [comment]
I can confirm that the master mentioned does work.
