### ISSUE TITLE
File annotations: remove line breaks, increase width, and reduce font size

### ISSUE THREAD

**Issue by anassal** [JabRef/jabref#3823]
JabRef 4.2-dev--snapshot--2018-03-09--master--988fb54a9
Windows 8.1 6.3 x86 
Java 1.8.0_161

1. Multi-line PDF annotations like these:

![1](https://user-images.githubusercontent.com/3094352/37212695-a907ab08-23a7-11e8-91e1-22c0ece31939.png)

are shown with "line breaks" like this.

![2](https://user-images.githubusercontent.com/3094352/37212696-a9371f6e-23a7-11e8-8a15-455fb09c3b2f.png)

2. There is currently a wide white space between the annotation text and the date/page number. Text should be warped with the maximum available/appropriate width.

3. Then, the height of each annotation item should be "auto".

4. I suggest the font size of the extracted annotations in the left-hand panel be reduced (e.g., x0.6). The right hand panel font size looks OK.

**Comment by Siedlerchr** [comment]
@miderleta You are welcome! Please take a look at our [Contribution guideline](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) for getting started and setting up a workspace etc and you can start. 

For this specific issue it's probably sufficient to play around with the css properties and the fxml.
If you have any questions please ask here or in our [gitter chat](https://gitter.im/JabRef/jabref)

**Comment by miderleta** [comment]
It seems like I cannot generate Javadoc for the project. Is that an issue or am I doing something wrong?

**Comment by Siedlerchr** [comment]
@miderleta  Where do you need it for? Any modern IDE will show you the javadoc automatically for each method - if it's annotated.

**Comment by Siedlerchr** [comment]
Maybe you can differentiate between a new paragraph starting vs a normal line break code wise.

**Comment by anassal** [comment]
@upupming This is a valid point. But can't we reasonably assume that most annotations are in single paragraphs, since paragraphs usually contain different ideas?

For annotations that actually span over multiple paragraphs, we can see if there are statistical differences between "end-of-line" and "end-of-paragraph" linebreak characters, as @Siedlerchr suggested, in PDFs annotated in multiple readers (e.g., Adobe, Foxit, Okular). It is also worth checking if this has been solved in other libraries/tools that extract text from PDF.

Regarding the "auto" height of an annotation item (left-hand panel), I just meant auto height that would result from text wrapping and fixed/limited width. Along with text wrapping and other improvements, the summary could be limited to, say, 10-15 words.

**Comment by upupming** [comment]
@anassal Done~ 

Now you can check the build from http://builds.jabref.org/master/. Please remember to make a backup of your library before trying out this version.
