### ISSUE TITLE
Distinguish simple fetchers and web searches

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#383]
JabRef offers a Web Search ( `F5`), where on can choose between things like DBLP or `DOI to BibTeX`. The DBLP search is a real search returning multiple entires, whereas the latter is a "simple" fetcher for a single entry identified by a DOI.

I propose to move the simple fetchers returning a single entry into "BibTeX -> new entry" as fourth group: "Generate based on id"

    Fetcher                  Identifier
    [dropdown for fetchers]  [empty field to key in id]

Example

    Fetcher                          Identifier
    DOI                              10.1145/2578903.2579140

- [ ] Move the single-id fetchers away from web search

**Comment by simonharrer** [comment]
:+1:

**Comment by koppor** [comment]
Implemented in https://github.com/JabRef/jabref/pull/1925
