### ISSUE TITLE
in*-entries marked as incomplete when booktitle is not provided in superentry (crossref in biblatex mode)

### ISSUE THREAD

**Issue by fkoglin** [JabRef/jabref#3832]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.1
Windows 10 10.0 amd64 
Java 1.8.0_161

**Description:**
In compilation, biblatex/biber automatically matches the `title` field of a crossreferenced `collection` entry to the `booktitle` field of an `incollection` entry. Specifying the `booktitle` in the `collection` entry is thus not necessary (unlike in bibtex). But even in biblatex mode, JabRef doesn't perform the same matching and still marks the `incollection` entry as incomplete. Filling the `booktitle` field in either the `incollection` or the `collection` entry removes the mark. The same issue shows up with every other `in`-type.

**Steps to reproduce:**

1. Create a `collection` entry with all required fields, e.g.
```
@Collection{Example2018,
  editor    = {Example, Alex},
  title     = {Example Collection},
  date      = {2018},
  publisher = {Example Publishing},
  location  = {Exampletown},
}
```
2. Create an `incollection` entry with the locally required fields that crossreferences the `collection` entry, e.g.
```
@Incollection{Sample2018,
  author   = {Sample, Blair},
  title    = {Example Contribution},
  date     = {2018},
  pages    = {1-42},
  crossref = {Example2018},
}
```

3. The `incollection` entry is marked by JabRef as incomplete.

**Comment by tobiasdiez** [comment]
Thanks for your report. When you say "mark as incomplete" you mean that the entry (the field) is colored red in the main table, right?

**Comment by fkoglin** [comment]
With standard colors it is marked red, yes.

**Comment by tobiasdiez** [comment]
This kind of marking was completely removed from the maintable in the current development version and hence this issue can be closed.
