### ISSUE TITLE
Order of fields in entry editor is not saved / automatically changed

### ISSUE THREAD

**Issue by CharlesVilliers** [JabRef/jabref#3836]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 on Mac OS X 10.13.3

Steps to reproduce:

1. Open "Customize entry types"
2. Change the order of fields in any table, click Apply, click OK
3. The order is not changed and remains (mostly, it seems) alphabetical

Sometimes, I am able to save my set options, I tried around creating a new database, change it there, open the actual database, but this does not always work.

Sometimes, the customized order is suddenly and automatically changed.

If this issue was known and is solved in the latest master I apologize, I am new to JabRef.

**Comment by stefan-kolb** [comment]
@JabRef/developers  Not sure if the order of fields is saved here. I don't think so. Maybe we will add something like that later on. We are currently reworking the whole UI 😄
