### ISSUE TITLE
Tooltip for title or long field

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#384]
Adding a tooltip so we know the meaning of each column headtitle (R, R, Q, F, P is not obvious) 

When a field doesn't fit in column width, show a tooltip with the complete content.

Thanks

**Comment by oscargus** [comment]
Thanks for your input. This issue is actively discussed among the developers, so something will happen. :-)

**Comment by matthiasgeiger** [comment]
Postponed to 3.1 (will be part of a general overhaul of the MainTableFormat).

**Comment by stefan-kolb** [comment]
Also see #315

**Comment by matthiasgeiger** [comment]
Implemented with #452 - changes are available now in current [development builds](http://builds.jabref.org/master/) and will be released with 3.1
