### ISSUE TITLE
Rework EntryType Dialog Fetcher to Task and not swing worker

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3844]
Reported by @halirutan 
Add new entry -> Enter ISBN or whatever -> Searching starts and "freeezes"
Pressing cancel adds the entry.

As suspected: It's a threading issue. The Fetcher is executed using a `SwingWorker`. The done method of the worker is excuted on the Swing EDT. Any call to the FX Thread seems to be delayed/waited upon the EDT thread returns. The actual "freeze" occurs in the ImportInspectionDialogwhere the javafx preview panel is initalized (when a duplicate is found). The init of the panel is on the FX Thread. So when you press cancel, the EDT Thread ends and the javafx thread shedules the update
The only way to fix this is to replace the swing worker with a `Task` or `Service`

**Comment by tobiasdiez** [comment]
We have a nice helper interface for these kind of async tasks in JavaFX: https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/util/BackgroundTask.java

**Comment by stefan-kolb** [comment]
I used the ISBN fetcher a few times lately. For me it was working, so it might be a random thread issue again.

**Comment by halirutan** [comment]
I'm not sure, but I vaguely remember that someone worked on this. I might be wrong.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
