### ISSUE TITLE
import from pubmed errorneous, authors not in bibtex format

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3848]
When I import from pubmed using the internet search->pubmed, I see an little yellow triangle beside the author field in the entry editor, saying that the author do not fullfill bibtex formats. Adding dots to each of the single latter first names made the triangle go away.

- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-12--master--586b934ba
Windows 7 6.1 amd64 
Java 1.8.0_161

Steps to reproduce:

1. import from pubmed e.g. PMID 10399915
2. open the entry editor, note the yellow triangle
3. add dots to single letter first names

**Comment by stefan-kolb** [comment]
To add information, this is the list of authors:
```
Böhni, R and Riesgo-Escovar, J and Oldham, S and Brogiolo, W and Stocker, H and Andruss, B F and Beckingham, K and Hafen, E
```
Not sure if the format requires dots after the names...

Relevant code in PersonnamesChecker by @LinusDietz 
```
        // Check that the value is in one of the two standard BibTeX formats:
        //  Last, First and ...
        //  First Last and ...
        AuthorList authorList = AuthorList.parse(value);
        if (!authorList.getAsLastFirstNamesWithAnd(false).equals(value)
                && !authorList.getAsFirstLastNamesWithAnd().equals(value)) {
            return Optional.of(Localization.lang("Names are not in the standard %0 format.", bibMode.getFormattedName()));
        }
```

**Comment by LinusDietz** [comment]
@stefan-kolb actually, the code is by @tobiasdiez. (;

The behaviour should be quite easy to fix, although it's weird that this hasn't been reported earlier.

**Comment by stefan-kolb** [comment]
Dots are added in AuthorListParser via #concatTokens:
```
        String firstAbbr = firstPartStart < 0 ? null : concatTokens(tokens, firstPartStart, firstPartEnd,
                OFFSET_TOKEN_ABBR, true);
```

**Comment by stefan-kolb** [comment]
@LinusDietz Sorry linked wrong person as Intellij gave your name in the README changes somehow. Or I just misread it...

**Comment by stefan-kolb** [comment]
Not sure if it's so easy to fix. Actually I'm also not sure if the current check condition really makes sense...

**Comment by tobiasdiez** [comment]
Mhh, isn't `Böhni, R.` with dot the standard BibTeX format?

**Comment by stefan-kolb** [comment]
I have no clue 😄

**Comment by tobiasdiez** [comment]
I think, it is (at least it is not the wrong format). So its not really a bug for JabRef to warn about it. It would be nice if the author cleanup would run automatically after the import so that the user don't have to fix the authors by hand. As this feature is already tracked in #1283, I'll close this issue here now.
Please feel free to reopen if it turns out that the "without dot" format is actually valid BibTeX.

**Comment by koppor** [comment]
According to http://serialmentor.com/blog/2015/10/2/Bibtex -> "Incorrectly abbreviated first names and missing middle initials", @tobiasdiez is right in saying that "`Böhni, R.` with dot the standard BibTeX format".

I also found [Tame the beast](http://texdoc.net/texmf-dist/doc/bibtex/tamethebeast/ttb_en.pdf) and linked it at http://help.jabref.org/en/Bibtex. Side node: The "Jr" discussion is made at Section 11 "The author field".
