### ISSUE TITLE
Preview Pane does not show CSL styles

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3849]
JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Linux 4.13.0-36-generic amd64 
Java 1.8.0_161

Steps to reproduce:

1. Select Options / Preferences / Entry preview

2. Choose a "Current preview" and move it to the right pane

3. The "preview" pane at the bottom does not show the formatting of the selected preview style.  It always shows the same, namely: 

> <font face="sans-serif"><b><i>\bibtextype</i><a name="\bibtexkey">\begin{bibtexkey} (\bibtexkey)</a>\end{bibtexkey}</b><br>
> \begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\author}<BR>\end{author}
> \begin{editor} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\editor} <i>(\format[IfPlural(Eds.,Ed.)]{\editor})</i><BR>\end{editor}
> \begin{title} \format[HTMLChars]{\title} \end{title}<BR>
> \begin{chapter} \format[HTMLChars]{\chapter}<BR>\end{chapter}
> \begin{journal} <em>\format[HTMLChars]{\journal}, </em>\end{journal}
> \begin{booktitle} <em>\format[HTMLChars]{\booktitle}, </em>\end{booktitle}
> \begin{school} <em>\format[HTMLChars]{\school}, </em>\end{school}
> \begin{institution} <em>\format[HTMLChars]{\institution}, </em>\end{institution}
> \begin{publisher} <em>\format[HTMLChars]{\publisher}, </em>\end{publisher}
> \begin{year}<b>\year</b>\end{year}\begin{volume}<i>, \volume</i>\end{volume}\begin{pages}, \format[FormatPagesForHTML]{\pages} \end{pages}
> \begin{abstract}<BR><BR><b>Abstract: </b> \format[HTMLChars]{\abstract} \end{abstract}
> \begin{review}<BR><BR><b>Review: </b> \format[HTMLChars]{\review} \end{review}</dd>
> <p></p></font>

4. pressing "test" always shows the same formatting, which is not the styling of the selelcted preview format,  See screenshot below.

![screenshot from 2018-03-14 10-12-03](https://user-images.githubusercontent.com/762246/37415062-2de187e2-2770-11e8-8f54-825aa2ccff65.png)

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Opening: /home/dom/Dropbox/Projects/HSSA/issue 5.2 rasayana issue/07 Sehnalova/paper/sehnalova.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
```

</details>

**Comment by Siedlerchr** [comment]
Yes, this something I noticed already a while ago,  but never cared ;)
The preview shows only the internal preview style and not the CSL ones. 
However, as the PreviewWindow is codewise the same from the entry editor, showing the CSL styles should be easy

**Comment by Jlimp** [comment]
Hi - If available would like to tackle this : )

**Comment by Siedlerchr** [comment]
Sure, go ahead! Have a look at our Contributing guide to get started. If you have any questions just ask in our gitter chat

**Comment by tobiasdiez** [comment]
Thanks to @eso31, this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by wujastyk** [comment]
Yes, it seems to work well now!  Very helpful indeed.
