### ISSUE TITLE
Required vs optional fields

### ISSUE THREAD

**Issue by icamps** [JabRef/jabref#385]
Hello,

I use JabRef for a long time now. From older versions (aka 2.9) the volume and pages for an article are in the "Require fields" tab when adding and article. Now, in the latest version (aka 2.11.1, and also from 2.10) these two properties where moved to the "Optional fields".

For me this is very awkward since these two properties ARE required to find and article and in order to add them, I have to change to another tab.

I wondering if they can getback to the "Require fields" tab.

Regards,

Camps

**Comment by matthiasgeiger** [comment]
Hi Camps,
those fields are declared as optional in the BibTeX documentation - therefore they are *technically* optional. 

If you want to make these fields required for you, you can do this using the "Options" -> "Customize Entry Types" dialog.

Regards,
Matthias

**Comment by koppor** [comment]
Here the excerpt from the [biblatex](https://www.ctan.org/pkg/biblatex) documentation:

![grabbed_20151124-121112](https://cloud.githubusercontent.com/assets/1366654/11365087/84476f2e-92a4-11e5-8586-438bc9cfc385.png)

**Comment by icamps** [comment]
Today (googling) it is easy to find an article only with the journal, authors and title information. I am not aware about when the biblatex change the volume/pages to optional.

Anyway, I will try the suggestion to add this fields manually.

Thank you very much!

**Comment by shat07** [comment]
While pushing the entries into Jabref library through Websearch, the name of journal and year of publishing are going to the optional field instead of required field. Thus, the journal name and year information gets missed in references in the latex document. Kindly guide how to add this to main field. I cant find the "customize entry type" key in "Options" tab.
