### ISSUE TITLE
Fetcher broken without anyone noticing

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3854]
As we have deactivated the tests in Travis we do not notice that they fail.
Right now, a lot of them are actually broken again. 
I think this is not a good situation if we are not aware of this.
This is a major functionality for us, even if we hide such errors from the user the results will not be as good as expected when the fetchers are broken.
Need to discuss possibilities in the dev call.

- [x] ScienceDirect
- [x] OpenAccessDOI
- [x] Isbnfetcher just returns wrong result because ebbok.de is broken
- [x] viaEbook inputstream seems to be empty via code call. browser result is fine. #3967
- [x] MathSciNet no subscription
- [ ] zbMath only available with subscrption (https://zbmath.org/subscription/)

**Comment by stefan-kolb** [comment]
@tobiasdiez Did you have a chance to test the remaining two fetchers?

**Comment by tobiasdiez** [comment]
MathSciNet works, but I've no longer a subscription to zbMath...
