### ISSUE TITLE
import bib hangs for gtk2 look and feel

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#3855]
I have tested the JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c version for reading in a bib file containing few entries (import into current library). With Look and Feel gtk2 jabref hangs when
OK button is pressed. Other look and feels are working but Nimbus takes a long time to import the entry from the file saying "proceessin IEEE......" and I also get a warning on the console:

ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1

**Comment by stefan-kolb** [comment]
We are reworking the UI to Java FX at the moment. Please use a working LAF for the time being. THanks for your understanding.
