### ISSUE TITLE
Set better default windows size for maintable beta version

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3859]
It is quite ugly when you first startup the maintable beta version of `JabRef`:

![image](https://user-images.githubusercontent.com/13306020/37550834-182dc12a-29cf-11e8-93bf-cd25c15f1f44.png)

Plus, it won't memorize my modifications, either. That is, after I modify the size to a better one, it restores to the default again when I restart it.

This is better:

![image](https://user-images.githubusercontent.com/13306020/37550862-e0d5988c-29cf-11e8-9cef-1577fd533f35.png)

```
JabRef 4.2-dev--snapshot--2018-03-16--maintable-beta--2c2a302a5
Windows 10 10.0 amd64 
Java 1.8.0_161
```

**Comment by JavierMF** [comment]
I felt this annoying too. Just adding `mainStage.setMaximized(true);` on starting would provide a wider visualization. Is that ok?

**Comment by tobiasdiez** [comment]
I agree that the window should be maximized by default. We also have preference values that sound related by are apparently ignored on start. I think, their original purpose was to save the window location across sessions. It would be nice if this could be investigated as part of resolving the default value.
https://github.com/JabRef/jabref/blob/cc3f7f0fd218e8e936ae4a77a5d1bb3c7b38e3f2/src/main/java/org/jabref/preferences/JabRefPreferences.java#L500-L505

**Comment by JavierMF** [comment]
`WINDOW_MAXIMISED` is used for reading on start:
https://github.com/JabRef/jabref/blob/66afd4216b4ee0db9525df9782200e36161a9b4f/src/main/java/org/jabref/JabRefGUI.java#L156-L158

but never updated.

`POS_X`, `POS_X`, `SIZE_X` and `SIZE_Y` are never used.

`AUTO_RESIZE_MODE` seems related to the MainTable, not to the Window.
https://github.com/JabRef/jabref/blob/66afd4216b4ee0db9525df9782200e36161a9b4f/src/main/java/org/jabref/preferences/JabRefPreferences.java#L1878-L1882

My proposal would be:

- set the WINDOW_MAXIMISED default to true
- save the window state (maximinization state, pos and size) when closing the application
- reload the window state on start if different to defaults

What do you think?

**Comment by tobiasdiez** [comment]
Thanks for the investigation. Sounds like a good solution to me!

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
