### ISSUE TITLE
entry preview font style break when using HR tag

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#386]
In the entry preview, if no HR tag used, everything goes well.
however, when I tried to add a HR tag, the font style is broken -- meaning that the defined FONT does not apply to the text after the HR tag.
Is this a bug, or just HR tag is not supported ?
thank you,
I tested this under 2.11.1 and the nightly build.

**Comment by matthiasgeiger** [comment]
Hi,
I can confirm this behavior...

However it is rather easy to fix by adding `</font><hr><font ....>` to the format instead of simply adding `<hr>`. (Repeating the `<font ... >`definition e.g. `<font face="arial">` from above).

**Comment by g10996694** [comment]
@matthiasgeiger Yes, I did also this trick. What I thought is that perhaps there would be something wrong in HTML rendering. Because generally this "problem" should not exist.
Is there a list of supported HTML tags in JabRef ?

**Comment by oscargus** [comment]
Late reply, but see https://docs.oracle.com/javase/8/docs/api/javax/swing/text/html/HTMLEditorKit.html

"The default support is provided by this class, which supports HTML version 3.2 (with some extensions), and is migrating toward version 4.0. The <applet> tag is not supported, but some support is provided for the <object> tag."

**Comment by lenhard** [comment]
As far as I can understand, the problem in this issue is fixed. Hence, I will mark it as closed.

Feel free to reopen if you disagree!
