### ISSUE TITLE
The `URL` column missed in the maintable beta version

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3860]
Look at the screenshot:

![image](https://user-images.githubusercontent.com/13306020/37555286-2e4a0ecc-2a20-11e8-9573-dc167a577e1d.png)

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `maintable-beta`. Please try the latest build from http://builds.jabref.org/maintable-beta.
