### ISSUE TITLE
JabRef fetches wrong authors list from DOI when author's name followed by hieroglyphs

### ISSUE THREAD

**Issue by igreenman** [JabRef/jabref#3869]
- [+] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.1
Linux 4.15.10-1-arch amd64 
Java 1.8.0_162

Steps to reproduce:

1. Try to fetch bibliographic data from DOI:  10.1063/1.3623424
2. You should get 
author    = {L. H. Li and E. H. Linfield and R. Sharma and A. G. Davies}
3. Instead JabRef fetches
author    = {E. H. Linfield and R. Sharma and A. G. Davies}

And similar for DOI 10.1088/0268-1242/30/5/055009
wrong bibtexkey - only 2015

The error occurs with this particular DOI numbers. In the remaining hundreds of cases, I did not notice any mistakes.

**Comment by stefan-kolb** [comment]
This is not in our hands. We retrieve the BibTeX data directly from https://doi.org.
The results from their API are not correct in your cases. Maybe you can report it to them, I'm not sure.
Also, the BibTeX key is not automatically adapted to your key pattern (if you use one) as far as i know.
You might need to regenerate it afterwards.
