### ISSUE TITLE
Link JabRef File to DevonThink

### ISSUE THREAD

**Issue by Fabniam** [JabRef/jabref#3885]
Hello Github-Community of JabRef,

Tobias Diez suggested me to write down my problem here, as [this Thread](http://discourse.jabref.org/t/link-jabref-file-to-devonthink/1087) in the JabRef Help Forum couldn't solve the problem until now.

I will copy-paste my description in the following. For already tried solutions please take a look at the linked thread:
> Hello JabRef-Community,
>
> I just started working with JabRef and while I’m trying to integrate my collected eBooks into JabRef, I have problems linking my files properly. As I couldn’t find any answers on the Forum, I might ask you for help. :slight_smile:
> I’m a Mac-User with DevonThink as a my DMS for nearly everything. All my eBooks are stored within a DevonThink Database. If I drag and drop one of my PDFs from my DevonThink GUI into JabRef, it’s going to copy the path of the database in “Finder Structure”.
> For Example it will save:
> 
> `:/Users/Fabniam/Documents/DevonThink/Studium.dtBase2/Files.noindex/pdf/5/Secondary symptoms of dyslexia a comparison of self esteem and anxiety profiles of children with and without dyslexia.pdf:PDF`
> But as you can see in the path, JabRef copy the Link of the database. If I’m going to reorganise my database or even just renaming the file, this link will be useless. For this purpose DevonThink is able to give out Permanent Links, which are common for use in other Apps like Microsoft OneNote or GTD Software. These links (I don’t know if there is a special name for them, but I saw similar links in other apps, so I’m guessing it’s an macOS feature) look like the following:
> 
>` x-devonthink-item://3E364AA0-F93D-492D-9D4A-AEC6013612D2`
> So DevonThink produces an unique Fingerprint for my file and no matter if I rename, move or edit the file, I can access it through this link. Some integrated workflows also use these link, e.g. if I link a file with a wunderlist task:
> 
> ![Image of Wunderlist](https://discourse-cdn-sjc2.com/standard13/uploads/jabref/original/1X/9d5f2a0c3c666b97eb320a964cea099b9a3a48d4.png)
> 
> I can click this link or just use it via terminal if I use the open command:
> 
> `open x-devonthink-item://3E364AA0-F93D-492D-9D4A-AEC6013612D2`
> Now I want JabRef to use these links instead of these “Finder Structure” links. I don’t mind if I manually need to update these links in my JabRef Library.
> 
> Thank you in advance for your help. :slight_smile:

**Comment by Siedlerchr** [comment]
I think we need to check/adjust the detection and mark it as online link

**Comment by koppor** [comment]
We currently have no money to pay someone for that ([donations page](http://donations.jabref.org)). No one of the JabRef team gets paid for JabRef. Thus, working on this really depends on the availability of our personal free time. - We really welcome feedback on our volunteer work. In case you can spend some more time (other than reporting issues), we would really like to encourage you to check https://contribute.jabref.org/ - especially the part asking for improvement of our [help pages](https://help.jabref.org/en/). This would help JabRef getting better as a whole. 🥇
