### ISSUE TITLE
iOS app is not updated for the new iOS11 version.

### ISSUE THREAD

**Issue by AravSd** [JabRef/jabref#3894]
- The iOS app for the JabRef is not working with most recent iOS 11 update, App Store says the current version is not compatible and updated (iPhone and iPad).

**Comment by koppor** [comment]
I assume, JabRef never worked at iOS. Please follow up at http://discourse.jabref.org/t/ios-app-is-not-compatible-with-the-ios11-please-update-the-app/1101.
