### ISSUE TITLE
license of external libraries not exact enough

### ISSUE THREAD

**Issue by alick** [JabRef/jabref#3897]
Steps to reproduce:

1. Check out https://github.com/JabRef/jabref/blob/master/external-libraries.txt
2. Note that it particularly says "BSD" is not exact enough
3. However, quite a few libraries has "BSD" as the license ID.

**Comment by lenhard** [comment]
I have the impression that this file is not maintained as rigorously as other things. Some libraries (jgoodies, etc.) in there have already been removed from JabRef.

In anything license-related @koppor is our expert.

**Comment by koppor** [comment]
Yes, we shall use the [SPDX License Identifiers](https://spdx.org/licenses/).

I wonder whether you read [line 11 onwars](https://github.com/JabRef/jabref/blob/40a007aabaf96ad963cc9cb72f94a9f7371bfedd/external-libraries.txt#L11) in the file:

> We follow the [SPDX license identifiers](https://spdx.org/licenses/).
> [...]
> For instance, "BSD" is not exact enough, there are numerous variants out there: BSD-2-Clause, BSD-3-Clause-No-Nuclear-Warranty, ...

Feel free to open a pull request fixing the license statements for each listed library.

**Comment by stefan-kolb** [comment]
@lenhard We still have jgoodies stuff in there?!

**Comment by alick** [comment]
OK I'll do a license audit/check when I get the time.

Please remove any libraries that are no longer in use if any.

**Comment by koppor** [comment]
@alick Can you do a cross-check with `build.gralde` when you are on it? We do not know by heart which libraries we included an dropped. The build.gradle is the single source of truth.
