### ISSUE TITLE
Apple Java Extensions still needed?

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3905]
Do they still make any sense?https://developer.apple.com/legacy/library/samplecode/AppleJavaExtensions/Introduction/Intro.html

**Comment by Siedlerchr** [comment]
At least with Java 9 they are obsolete and with JavaFX no longer needed. But we still have one or two dialogs who use them.

**Comment by stefan-kolb** [comment]
#3861

**Comment by koppor** [comment]
So full steam ahead for the JavaFX migration. 🎉

**Comment by Siedlerchr** [comment]
Refs #3421
