### ISSUE TITLE
Copy from the preview copied the entire bibtex entry, not the items you selected

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3914]
- [ +] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-30--master--b3b0b44ef
Windows 7 6.1 amd64 
Java 1.8.0_161

Steps to reproduce:

1. open the preview of jabref
2. select a single author
3. ctrl-C
4. go to any other program where to want the autho copied,
5. ctrl-V and you get the whole bibtex entry copied instead of the author you selected

In the stable version 4.1 you could select the author and copy the author and nothing else. Bug acquired in 4.2dev.

**Comment by tobiasdiez** [comment]
Ok, if it works in maintable-beta then we can close the issue.

@bernhard-kleine Could you please try out the version from https://builds.jabref.org/maintable-beta/ and confirm that it works there. This version is getting more stable every day and, as you see, has even less bugs than the current master/4.1 (in some regards 😸 ).

**Comment by bernhard-kleine** [comment]
I can confirm that it works in maintable-beta, however, the look and feel and the missing buttons for group preview, entry preview etc. were very irritating in that version. Will there be any notice when that is taken over to master?

**Comment by bernhard-kleine** [comment]
Since you did not merge the maintable-beta into the new release, Please reopen!!!

**Comment by Siedlerchr** [comment]
@bernhard-kleine  The maintable-beta will become the next major release 5.0. The 4.2 release will be stable with minor bugfixes until the 5.0 is ready and usable for production.  
We are sorry for that inconvience, but we don't have resources to maintain two versions or to backport from the newer one to the older
