### ISSUE TITLE
latex_to_unicode produces problematic filename

### ISSUE THREAD

**Issue by bdcaf** [JabRef/jabref#3920]
I encountered this when retrieving information for `doi:10.1088/1752-7155/7/1/017106`.
Which retrieves the authors: `Patrik {\v{S}}pan{\v{e}}l and Kseniya Dryahina and David Smith`.

A cleanup/rename pdf gives following filename: `S}pane{l}EtAl/Spanel2013 - A quantitative study.pdf` (note the braces are produced like this) which not only is wrong, but also gives an error: `Could not save file. Error in field 'file': Braces don't match.`

I have directory pattern set to: `[authEtAl:latex_to_unicode]` and file format pattern set to `[bibtexkey] - [shorttitle:latex_to_unicode]`. And bibtex key pattern is: `[auth:latex_to_unicode][year]`.  Also note that the bibtex key doesn't contain any `}`.

**Comment by Siedlerchr** [comment]
I tried it locally and can confirm the behaviour. In fact it seems like the file directory pattern is not interpreted correctly.
```
        String fileNamePattern = "[bibtexkey] - [shorttitle:latex_to_unicode]";
        String directoryPattern = "[authEtAl:latex_to_unicode]";
```
1. Rename PDF is correct . Sample file ` Toot.pdf` ->  `Toot - A quantitative study.pdf`
2. Move Files Cleanup breaks it then -> `S}pan{e}lEtAl/Toot - A quantitative study.pdf`

**Comment by Siedlerchr** [comment]
Okay, the problem is not the latex2unicode itself, but the bracketed format expander which struggles with exactly this combination: latex encoded + authEtal

**Comment by Siedlerchr** [comment]
@JabRef/developers  Does anyone of you know why the first brace is removed?
That actually is the underlying  root problem here:

https://github.com/JabRef/jabref/blob/0c34fa4ba99821570dbf04e22d6f749a9c1b2456/src/main/java/org/jabref/model/entry/Author.java#L370-L386

**Comment by stefan-kolb** [comment]
Tests:

```
    @Test
    public void testAuthEtAlBraces() {
        assertEquals("SpanelEtAl",
                BibtexKeyGenerator.authEtal("Patrik {\\v{S}}pan{\\v{e}}l and Kseniya Dryahina and David Smith", "", "EtAl"));
        assertEquals("\\v{S}pan\\v{e}lEtAl",
                BibtexKeyGenerator.authEtal("Patrik \\v{S}pan\\v{e}l and Kseniya Dryahina and David Smith", "", "EtAl"));
    }
```

It is actually problemetic what to expect here.
- Making the braces unbalanced is leading to problems in any code except sorting!
- Keeping the braces produces problematic output for cases like key generation imho (not sure if key generation should only produce alphanumeric keys?!)

**Comment by koppor** [comment]
DevCall:

- AuthorClass: Strangest method to get names is taken. 
- Remove non-ASCII characters to ensure compatibility with `pdflatex`

**Comment by Siedlerchr** [comment]
Still present in 5.0 dev

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I can try to fix this one.

**Comment by koppor** [comment]
This is a hard one, but just goahead!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@koppor **right now** directory names are allowed to contain unicode. Unless there have been complaints, shouldn't that remain the case?

I currently believe there are two issues the solution depends on
1. Is unicode allowed in the directory path?
2. Is it too much of a performance hit to call the `LatexToUnicodeAdapter`? (the "latex-free" string will not have been cached)

I prefer to use the `LatexToUnicodeAdapter` because I think it is a better user experience if both Gödels generate the same directory names, and changing the directory structure is an infrequent event.

**Comment by Siedlerchr** [comment]
Unicode path names are perfectly valid.
you can even use emoji on windows 10.

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#file-and-directory-names

Regarding performance. Don't know but I would also go for the latex2unicode adapter. Seems reasonable to me. Don't you have the latex free author already in the author list class? 
The author patterns are just equivalent to methods for getting the authors

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Siedlerchr , @koppor earlier pointed out that,
> * Remove non-ASCII characters to ensure compatibility with `pdflatex`

but perhaps that is only relevant for the bibtex key? I am not entirely sure about the use case (except for organizing pdfs). Does people use it to organize plots, etc. that they later import into a .tex file?

> Don't you have the latex free author already in the author list class?

No, the latex-free methods cache full "patterns" (e.g., `authorsLastOnly`), unfortunately not individual authors or this particular pattern.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Actually, you could use `AuthorList#getAsLastNamesLatexFree` and parse that string. That would remove the performance bottle-neck at the cost of having a "hacky" solution.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Never mind. Unless the user has the exact right preferences it would amount to the exact same solution but with an extra split operation at the end.

`Author`s fields are currently not latex-free. I'd consider it an option to change that, and cache latex-free `Author`s instead of `AuthorList`s.
