### ISSUE TITLE
Dropping a PDF onto the File entry in General is inconsistent with standard attach method

### ISSUE THREAD

**Issue by Sethur** [JabRef/jabref#3923]
- Issue persists in current master

JabRef Version 4.1, Windows 7, Java x64 Version 8 Update 162

Steps to reproduce:

1. Drag and drop a PDF onto the file textbox in General for an existing DB entry
2. The file will be added with the full path. In contrast adding the file via Right Click->Attach File will produce an entry with the correct relative path (relative to Library Properties->General File Directory).

![image](https://user-images.githubusercontent.com/2142589/38302458-10a681e8-3803-11e8-817f-366b577a9073.png)

**Comment by Sethur** [comment]
This issue is connected to #121.

**Comment by Siedlerchr** [comment]
Hi, thanks for the report: I am currently on reworking that feature in https://github.com/JabRef/jabref/pull/3765 for the new maintable-beta release (https://github.com/JabRef/jabref/pull/3621) 
It will be made consistent as suggested in the comment by koppor

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
