### ISSUE TITLE
Integrity check should not report Coorporate Authors as "Names are not in standard format"

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3928]
Jabref Master:

1. Add a corporate author in braces in the author field  e.g. `{JabRef}`
=> Integrity check reports: Names are not in standard biblatex format
Expected behaviour: No warning, as this is the correct way for corporate authors:
See section 2.3.3 Corporate Authors and Editors of the [biblatex manual](ftp://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf)

Addtionally, JabRef should offer the field `shortauthor`

**Comment by stefan-kolb** [comment]
@Siedlerchr for which entries do we need to add the field shortauthor?

**Comment by stefan-kolb** [comment]
I think we "support" it, at least it is inside our PERSON_NAMES declaration. Can you comment more oon what is missing here?

**Comment by Siedlerchr** [comment]
We  could add it to the optional fields. When I have a corporate author and define a short author, e.g. BMBF for the corporate author  (Bundesministerium....) this field takes precedence in citations as key in biblatex
