### ISSUE TITLE
"File: grouptree.fxml not found, attempting with camel case" although it exists

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#3938]
- [X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-04-08--master--4d8291483
Linux 4.4.0-116-generic amd64
Java 1.8.0_161

Steps to reproduce:

1. touch grouptree.fxml - to create an empty file.
2. touch grouptree.css
3. Start JabRef.

It says that the files do not exist, although they clearly do  exist.

[NOTE: I do not really use these files. My main goal is just to silence the messages so that I can focus on real error messages].

<details>
  <summary>Log File</summary>
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
</details>

**Comment by Siedlerchr** [comment]
Hi, this is just a warning from an underlying external library which we can't  In the new maintable beta branch we fixed this problem.
