### ISSUE TITLE
When JabRef is re-opened, it re-opens one library but not the others

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#3939]
- [ X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-04-08--master--4d8291483
Linux 4.4.0-116-generic amd64
Java 1.8.0_161

Steps to reproduce:

1. Open a library.
2. Open another library.
3. Close JabRef.
4. Re-open JabRef.

The first library is opened automatically, but the second is not - I have to re-open it manually.

It could be very convenient to return to the same point after restart. This is especially true while debugging the hangs and freezes (see previous issue).

**Comment by Siedlerchr** [comment]
Cannot confirm this behaviour. Neither under Windows, nor under Xubuntu. Have you checked the option "Open last edited libraries at startup under Options-> General?

**Comment by erelsgl** [comment]
​Yes (in my version, it is in Options -> File and it is checked).

**Comment by Siedlerchr** [comment]
Is this issue now resolved by switching the Look and Feel?

**Comment by erelsgl** [comment]
Yes, it seems to be solved when I am using Nimbus.

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*
