### ISSUE TITLE
Encoding setting in 4.1 is saved incompatibly to older version, e.g. 2.11.1

### ISSUE THREAD

**Issue by Sethur** [JabRef/jabref#3941]
I have tested the latest master version and the problem persists

JabRef version 4.1 on Windows 7

Steps to reproduce:

1. Create a database
2. Go to File->Library Properties and select UTF-8
3. Create an entry with some multi-byte characters (in UTF-8) like äöüß, etc.
4. Save the database
5. Open the database in Jabref 2.11.1
6. The encoding will not be detected as UTF-8

The reason for this is the encoding string. Newer versions of Jabref use:

```
% Encoding: UTF-8
```
while oder versions use

```
% Encoding: UTF8
```

Interestingly, Jabref 4.1 also detects the version without hyphen correctly, but as soon as you save the file, this line is changed to the version with hyphen, so Jabref 2.x will fail again.

**Comment by Siedlerchr** [comment]
Hi,
due to our limited resources we can only fix bugs in the latest development version. All older versions of JabRef are not supported by us and JabRef 2.11 is way too old.

**Comment by Sethur** [comment]
Well, this issue is not really about fixing bugs in older versions, but about keeping your chosen bibliography format (BibTex or BibLaTex) compatible between versions.

JabRef users are often collaborating on a database. If you don't keep the bibliography format upwards and downwards compatible (as it is now), then one person of a collaboration updating his JabRef version forces everybody else to update as well, or else they cannot properly read the database any more, or worse, they can read it but the encoding is mis-guessed and upon saving, they will corrupt the database (this is what happens now).

Fixing this issue is very simple as newer version of JabRef can read in the old formatting string without problems, so it's simply a matter going back to using:

´´´
% This file was created with JabRef <version number>
% Encoding: <java.io string instead of java.nio string, i.e. UTF8 instead of UTF-8>
```

(Note that the first line without the version number must be present) instead of just:

´´´
% Encoding: UTF-8
```
