### ISSUE TITLE
Entry editor produces constant load

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3943]
When the entry editor is opened I experience constant high load from JabRef.
This needs to be evaluated and fixed!

![image](https://user-images.githubusercontent.com/2141507/38553320-3173fbec-3cbf-11e8-9509-23de34484798.png)

When I close the entry editor load immediately goes down to idle.

**Comment by stefan-kolb** [comment]
It looks like JR is producing events? in such cases.
The classes that are created over and over are:
`AccessControlContext, EventQueueItem, WeakReference`
After some time the garbage collector kills all of them and the climb to the peak starts again.
@JabRef/developers What could cause this? We really need to find out...

**Comment by stefan-kolb** [comment]
Maybe relevant: https://stackoverflow.com/questions/14558266/clean-javafx-property-listeners-and-bindings-memory-leaks?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by stefan-kolb** [comment]
I just need to click tab titles and after a while the leak starts!

**Comment by stefan-kolb** [comment]
I couldn't find anything yet, tho I'm not so much into these code parts.

**Comment by stefan-kolb** [comment]
I couldn't reproduce the constant load on the maintabl branch with a few tests yet, although I am experiencing this phenomen when cycling through the entries (memory spike/leak again):

![image](https://user-images.githubusercontent.com/2141507/40537148-8571e50c-600e-11e8-8eac-e75aa4b33b79.png)

**Comment by stefan-kolb** [comment]
Looks like AWT is creating InvocationEvents all the time:

```
java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=sun.awt.windows.WInputMethod$1@3eb272aa,notifier=null,catchExceptions=false,when=1527251549510] on org.jabref.gui.maintable.MainTable[,0,0,1896x8400,alignmentX=0.0,alignmentY=0.0,border=,flags=251658600,maximumSize=,minimumSize=,preferredSize=,autoCreateColumnsFromModel=true,autoResizeMode=AUTO_RESIZE_ALL_COLUMNS,cellSelectionEnabled=false,editingColumn=-1,editingRow=-1,gridColor=java.awt.Color[r=210,g=210,b=210],preferredViewportSize=java.awt.Dimension[width=450,height=400],rowHeight=25,rowMargin=0,rowSelectionAllowed=true,selectionBackground=javax.swing.plaf.ColorUIResource[r=0,g=120,b=215],selectionForeground=javax.swing.plaf.ColorUIResource[r=255,g=255,b=255],showHorizontalLines=false,showVerticalLines=false]
```

**Comment by stefan-kolb** [comment]
As far as I can tell this is a JVM bug and is fixed in `1.8.0_172` 😢 
Will keep an eye on this tho...

**Comment by stefan-kolb** [comment]
Maybe we should fix our Java version to `8u172` and up. Or at least warn the user?

**Comment by tobiasdiez** [comment]
depends a bit on how bad the leak is. If it makes JabRef/the system unusable we should set 172 as minimum. If its not that bad I would vote for ignoring it (we can always tell people to upgrade if they complain...)

**Comment by Siedlerchr** [comment]
I see no problem bumping the minimum version. Only the latest jdk is supported and often fixes security things.

**Comment by stefan-kolb** [comment]
For me this lead to my fan running on maximum all the time on my laptop. 
And my machine isn't that old and slow. 
I have no idea what this means for slower machines. 

I'm not 100% convinced either, tho.
