### ISSUE TITLE
Fetcher download always saves in root directory

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3945]
It does not let me choose the directory anymore.

@JabRef/developers I think this was different before?!

Now:
1. Download FT
2. Fulltext is renamed and linked inside the main file dir.

Before:
1. Download FT
2. Choose file location with modal dialog
3. Full text is linked

**Comment by koppor** [comment]
This was the discussion I had with @tobiasdiez at JabCon and we all developers agreed that there should be less dialogs. Now, it hit that dialog. I assume, it was removed on purpose. -- The user should start a second action if he wants to have a different directory (file move operation?). Possibly, there can be an auto-group-directory in place (not sure whether we implemented that).

**Comment by stefan-kolb** [comment]
Hm, well for me this pretty much sucks as I want to group RW in different folders for grouping.
Is there a commit for this change?

**Comment by koppor** [comment]
Then you need the directory-for-group-feature ^^.

**Comment by stefan-kolb** [comment]
If we want to push our grouping functionality more this is probably the way to go tho!
Maybe we should leave it like that and provide an option to show the save window if one wants to use another workflow.
Even maybe show a dialog for the first time like:
- rename and in default directory
- Save in other directory
- checkbox remember my decision
- add some preference

Think this would be a good workflow

**Comment by Siedlerchr** [comment]
I want to have a similar dialog for the dnd feature in case no entry from pdf is found.

For the download, I think it would be sufficient to follow the File Directory Pattern. That would be sufficient I think

**Comment by stefan-kolb** [comment]
If I download __multiple__ full texts it still pops up btw.
This makes no sense to me. Especially if I want to download more than one entry there should be no dialog then.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by Siedlerchr** [comment]
Fulltext downloads of PDFs now respect the file directory pattern and the file name pattern as well.
