### ISSUE TITLE
Import from txt files failed  (GTK L&F problem on mac)

### ISSUE THREAD

**Issue by Dapscoptyltd** [JabRef/jabref#3946]
JabRef 4.2-dev--snapshot--2018-03-30--master--b3b0b44ef
Mac OS X 10.13.4 x86_64 
Java 1.8.0_161

Steps to reproduce:

1. File > Import into current library.
2. Select .txt file (two attached
3. Watch spinning wheel of death for as long as your patience can bear it...
4. Attempt to verify my text file was correct. Cannot find information. 
5. Repeat with one entry.
6. Fail.

Seriously. I really, really need this to work. Otherwise it will have to be Endnote.

[18-04-11_Hang_1_on_ImportJabref.txt](https://github.com/JabRef/jabref/files/1897381/18-04-11_Hang_1_on_ImportJabref.txt)
[18-04-11_Hang_2_on_ImportJabref.txt](https://github.com/JabRef/jabref/files/1897382/18-04-11_Hang_2_on_ImportJabref.txt)
[20180224TroveBibTex Hang 1.txt](https://github.com/JabRef/jabref/files/1897383/20180224TroveBibTex.Hang.1.txt)
[20180224TroveBibTex Hang 2.txt](https://github.com/JabRef/jabref/files/1897384/20180224TroveBibTex.Hang.2.txt)

Paste your log details here.

**Comment by Dapscoptyltd** [comment]
Please also note the new entry by text file option failed too - is this problem a parsing/code/syntax issue caused by my need to rescript the txt files?

**Comment by Siedlerchr** [comment]
Hi, both work fine for me in the latest JabRef master snapshot: https://builds.jabref.org/master/
Sure, it takes a a moment, but works fine

**Comment by sambo57u** [comment]
This was happening to me with gtk2 look and feel but worked with others. I had opened a bug that was closed because this will be replaced. Could this be the case here?

**Comment by Siedlerchr** [comment]
I think we currently only have this warning for Linux and not for mac users. But we could adopt it

**Comment by Siedlerchr** [comment]
Regarding the Look And Feel for Mac:
We should add a check for OSX and set the L&F to Nimbus then:
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/JabRefGUI.java#L235

**Comment by Siedlerchr** [comment]
There is another issue from another user who still expects freezes, but as this works for you here, I close this issue and keep the others open
