### ISSUE TITLE
Unmarking an entry still retains an empty _markedentry property

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3948]
```git
-  __markedentry = {[stfn:6]},
+  __markedentry = {[stfn:]},
```

**Comment by Siedlerchr** [comment]
I think this is obsolete as in the main table PR https://github.com/JabRef/jabref/pull/3621 Marking is implemented as groups

**Comment by stefan-kolb** [comment]
Ok this is good to know. Can be removed then after the merge

**Comment by tobiasdiez** [comment]
The marking feature is completely removed in the maintable branch (and replaced by by colored groups).

**Comment by tobiasdiez** [comment]
The marking feature is no longer present in the current master.
