### ISSUE TITLE
medline search not working on Debian stable (amd64)

### ISSUE THREAD

**Issue by andber86** [JabRef/jabref#395]
Hi,

I'm experiencing troubles with the Medline search tool which doesn't find anything I type in.

I've tried with both the version from the Debian repository and the latest version downloaded from the website.

Andrea

**Comment by koppor** [comment]
What do you mean by "latest version downloaded from the website"? Could you try the latest version from http://builds.jabref.org/master/? (requires java 8)

**Comment by andber86** [comment]
I downloaded the 2.11.1, I guess it's the latest stable version..

**Comment by koppor** [comment]
Just to be sure: You have a database opened? [Ubuntu issue 1449414](https://bugs.launchpad.net/ubuntu/+source/jabref/+bug/1449414) was solved by opening a database.

Please try the development build 3.0 from http://builds.jabref.org/master/.

**Comment by andber86** [comment]
yes, I actually have 3 different databases opened.
When I click the fetch button, the search windows opens and after a quite long search time (like a minute or so) I get the message "no references found".
At first I thought I had mispelled something, but then I tried with very basic keywords and I got the same behavior.

**Comment by andber86** [comment]
ok I just tried with the latest dev build 3.0, the one released today, same story.

**Comment by andber86** [comment]
sorry, It's working fine now. I tried accessing the pubmed website and I couldn't get there either.
I changed the DNS from my router configuration and everything works now.
For some reason I couldn't get to the pubmed service.
