### ISSUE TITLE
Import from Google Scholar does not include the URL

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#3952]
- [X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 
JabRef 4.2-dev--snapshot--2018-04-13--master--68b37978a
Linux 4.4.0-119-generic amd64 
Java 1.8.0_161

Steps to reproduce:

1. Search in Google Scholar
2. Select one article
3. OK

The bibliographic details are imported, but the URL is not.

**Comment by AEgit** [comment]
I think that has always been the case (or at least it is with version 3.8.2).

**Comment by stefan-kolb** [comment]
@erelsgl Which URL are you expecting to be in the entry? Can you give us a concrete example entry? Otherwise, I guess that @matthiasgeiger is correct and there just is no URL inside the entry available!

**Comment by erelsgl** [comment]
I meant the URL that is visible when doing a search in scholar.google.com.
But, I understand that this URL might be unavailable to JabRef.

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by stefan-kolb** [comment]
In most cases, this will be the URL the DOI links to. So you could use the DOI link inside Jabref to get there. If there is no DOI use the Lookup DOI functionality first. Hope this helps!
