### ISSUE TITLE
When copying an entry to a library in another folder, the relative path to linked files should be updated

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#3953]
JabRef version:
JabRef 4.2-dev--snapshot--2018-04-13--master--68b37978a
Linux 4.4.0-119-generic amd64
Java 1.8.0_161

Steps to reproduce:

1. Open a library in folder A.
2. Attach to one of the entries, a file in a subfolder of A.
3. Open another library in folder B.
4. Copy the entry from library A to library B.
5. Try to open the file from the entry in library B.

The file does not open. The file-link is copied as a relative path, so it is invalid.

**Comment by stefan-kolb** [comment]
The correct algorithm for this is not immediately evident I think.
It depends on the usage pattern of the user.

- If the user uses one directory for all full-text PDFs, the current strategy of copying the entry 1-1 is *correct*
-  If the user uses subfolders adjascent to the Bib file, we need to *transform all relative URIs to absolute URIs*
- If the user uses absolute URIs, the current strategy is *correct*

**Comment by Siedlerchr** [comment]
JabRef has always been using relative links where possible for files.  So this correct expected behavior.
And it still works if both lib A and lib B are in the same folder.

**Comment by tobiasdiez** [comment]
What might work in all cases:
- Upon copy, convert all linked files to absolute paths
- Upon paste, make paths relative (with respect to the current library / pdf folder)

**Comment by stefan-kolb** [comment]
@tobiasdiez Sounds reasonable, but is it really worth? If a PDF is not inside one of the relative paths of the library or the bib file, I see no value by doing this. Additionally, it introduces more complexity for us.

**Comment by koppor** [comment]
We do not get the concrete use case. Is it about sharing?

I had similar case with *copying* PDFs to another folder, but I had no use case with linking.

**Comment by koppor** [comment]
The discussion seems to be that there are users having bib files in sub directories. Maybe some paper work. The thing is we should try not to contradict possible workflows.

Refs https://github.com/JabRef/jabref/issues/160

I like the solution outlined at https://github.com/JabRef/jabref/issues/3953#issuecomment-381691097

**Comment by claell** [comment]
The issue seems to be still relevant. I came across it having the following in mind:

I will likely have several, project related .bib files. Additionally, I plan to have a large .bib file collecting relevant entries from the project related files. For that, I plan to manually copy entries. That will likely also involve copying the files and updating the links.

The question is, what mechanism can best help with this workflow. Automatically copying files over to a correct location will likely not work. But keeping the link working probably will help with that.

**Comment by koppor** [comment]
This issue was fixed with https://github.com/JabRef/jabref/pull/13535

<img width="1929" height="1279" alt="Image" src="https://github.com/user-attachments/assets/0b7f0aa5-0ff4-4c80-82b5-bcd80185ae3f" />
