### ISSUE TITLE
Bibtex parser - Found unbracketed comment

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3956]
1. Create a new db with this entry
2. Save, bibtex parser complains about ubracketed comment 

As far as I remember and according to this information here, it should be valid:
http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html
@lenhard  @koppor  As you have some deeper  insight into the bibtex "standard", do you know if JabRef behaves here correct?

```
@COMMENT { BibTex package created by Trove, National Library of Australia https://trove.nla.gov.au }

@Book{Artillery1914a,
  author        = {Australia. Army. Royal Field Artillery},
  title         = {Standing orders of the Royal Australian Field Artillery : 1914},
  year          = {1914},
  language      = {English},
  note          = {State Library of NSW. M 358.21/A},
  publisher     = {Melbourne : Albert J. Mullett, Govt. Printer},
  catalogue-url = { https://trove.nla.gov.au/work/21191657 },
  subjects      = { Australia. Army. Royal Field Artillery; Australia. Army -- Regulations },
  timestamp     = {2018-04-15},
  type          = {Book; Book/Illustrated},
}
```

**Comment by koppor** [comment]
The entry has TWO things inside. This is currently unsupported at JabRef.

JabRef kind of accepts pasting that string as a whole in the entry table, but drops the `@COMMENT`.

Two options:

A) Accept that this comment is dropped
B) Enhance JabRef to handle `@COMMENT` properly, too.

We store the comments to an entry at the data structure, but IMHO do not show it.

We renamed the "Review" field to "Comments" (@LinusDietz at #3658), which might get confusing now.

![grafik](https://user-images.githubusercontent.com/1366654/38807255-52a6fdca-417c-11e8-8017-214ca452d0cd.png)

Not sure whether we should migrate comments above an entry into the entry itself. I don't think so. We should nevertheless offer a field in the entry editor showing "Annotations", which means the comments above the entry.

I think, this refs https://github.com/JabRef/jabref/pull/391.

**Comment by Siedlerchr** [comment]
I would vote for option A. When I copy and entry it should be copied complete, event with uncommented stuff.  But I personally never used that feature. That entry was from the data in #3946
