### ISSUE TITLE
Sorting of "compund" fields in entry table is not preserved in preferences

### ISSUE THREAD

**Issue by bluebirch** [JabRef/jabref#397]
In the entry table, it is possible to add two fields, like `author/editor`, and JabRef displays editor if author is not present. It is possible to sort the table on this column by clicking on the header, just like any column. However, specifying for example `author/editor` as primary sort key and `year/date` as secondary sort key in preferences doesn't work. JabRef does not sort according to this specification when restarted.

Applies to all versions I have tried, including 2.11.1. I have not tried the development version of 2.80.

**Comment by matthiasgeiger** [comment]
Mhmm... I'm not quite sure but I think it works if you change the column to "author/editor" and "date/year" - **but** as sorting criteria only add "author" and "date".

This seems to sort correctly for me (and this is also restored after closing and opening JabRef - until another sorting is set by hitting the table header).

**Comment by bluebirch** [comment]
Indeed, it does. Weird. Should perhaps be mentioned in the docs somewhere. :-)

**Comment by simonharrer** [comment]
We are open for help with improving the documentation. ;-)

If you would like to help, have a look at the HTML files available under `src/main/resources/help/en`.
