### ISSUE TITLE
'Do not overwrite existing keys' does not work

### ISSUE THREAD

**Issue by mutsuura** [JabRef/jabref#4000]
Under:... Options > Preferences > BibTex key generator

I checked the 'Do not overwrite...' box but bib entry keys are still overwritten when I click on [generate] key icon. I have tried restarting JabRef but same result. Version 4.2
- - -
Follow up: 2018/05/07

Whether 'Do not overwrite existing keys' flag is set or not, if I double click the generate key icon, it locks the new bibtexkey as one might want but there is no visual indication that the key is actually locked. If I click once every two (2) seconds or so, the key continues to be changed. So there is a locking mechanism but not as documented - perhaps not as designed. If key is locked with double click, I can still delete the key and generate a new one.

**Comment by stefan-kolb** [comment]
Both icons in the editor use a different implementation as `strg-g` and `quality - auto generate bibtex keys` does.

**Comment by stefan-kolb** [comment]
- [ ] ctrl-g
- [ ] quality auto generate bibtex keys
- [ ] entry editor left icon
- [ ] entry editor right icon
