### ISSUE TITLE
customized key generator kicks out colons in 4.2

### ISSUE THREAD

**Issue by klamkiew** [JabRef/jabref#4010]
Hi everyone,
so we are using the JabRef4.2 version since some days, because of the PubMed search issue from November. We were using a custom key template for our entries (more than a thousand, we are using this bibtex library for our whole workgroup), looking like this

[auth]:[shortyear]

Judging from this issue #3359 and fix #3506 back in January, you guys are automatically removing colons from resulting generated keys in order to prevent weird things with Title. However, wouldn't it make more sense to remove colons from the individual fields separately, instead from the final key? 

Thanks a lot and Cheers,
Kevin

**Comment by Siedlerchr** [comment]
Hi, judging from the code, there should be an option "Enforce legal keys ". 
If you disable that switch, it should still use the colon

**Comment by klamkiew** [comment]
Hi there,
disabling this option helped. Thanks for the help, I am closing this issue.
