### ISSUE TITLE
[TimeStamp] field formatting

### ISSUE THREAD

**Issue by mutsuura** [JabRef/jabref#4017]
Current formatting documentation for timestamp field [https://help.jabref.org/en/TimeStamp] does not specify seconds placeholder 'ss' or 'SS' yet under options>preferences>general I can specify "yyyyMMddHHmmss" or "...SS". each does something different.

'ss' appears to insert seconds into [timestamp] field. 'SS' inserts what appears to be a random 2 digit number. Is this by design? Or a bug? Undocumented feature? What is 'SS' supposed to do?

**Comment by Siedlerchr** [comment]
Hi, the timestamp format should follow the Java spec of the timestamp patterns. 
Uppercase S is fraction of a second. 
Lowercase s is second 
You can look here for an overview of the format patterns. https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

Section: patterns for formatting and parsing. 
Maybe you could add that link to the help page? Just click on the edit button
