### ISSUE TITLE
Corrupt file field content causes UI problems.

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#402]
As can be seen in #399 and https://github.com/JabRef/jabref/issues/184#issuecomment-159187452 invalid file links produce crazy effects in the UI.

Potential Problems:
- unescaped `:` in windows paths (as `:` is used as delimiter)
- unescaped `\`
- creative escapes as mentioned in #399: File = {:C$\backslash$:/Users/[myname]/Dropbox/Studies/Books/Analysis/[Hedy{_}Attouch,{_}Giuseppe{_}Buttazzo,{_}Gerard{_}MichailleVariationalBV.pdf:pdf}
- invalid number of elements delimited by `:` ?

**Comment by matthiasgeiger** [comment]
related/affected https://github.com/JabRef/jabref/issues/98

**Comment by koppor** [comment]
Maybe adding `RemoveLatexCommands` somewhere at the default preview is a quick fix? See
http://jabref.sourceforge.net/help/CustomExports.php

**Comment by simonharrer** [comment]
related?  557

**Comment by simonharrer** [comment]
add tests to `FileFieldTest` @matthiasgeiger

**Comment by matthiasgeiger** [comment]
Adding tests to FileFieldTest does not make sense - the problem here is a NPE which has been fixed in #893.

However, I might be useful if "wrong" ```file``` field contents are reported to the user somehow - but this is another issue ;-)
