### ISSUE TITLE
Groups are focused on right-click

### ISSUE THREAD

**Issue by andre8s** [JabRef/jabref#4025]
- [X] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2 on Windows 7 6.1 amd64, Java 1.8.0_161

I am using a database with 12000+ entries and a large number of keyword groups, which are arranged in a hierarchical tree (via using sub groups). In the group dialog, the sub branches of the group tree can be folded or unfolded via the small arrow symbols at the right side. Further, it is possible to right-click on a group or sub-group and get a context menu which allows to "add selected entries to this group". 

The problem is that already clicking on the fold/unfold symbol immediately affects the filtering status of the main entry list. Also right-clicking on a group or subgroup has the same effect. In jabref-3.x it was possible to fold/unfold a sub branch by clicking on a "+" symbol without changing the filtering state in the entry viewer. Also, getting the context menu via right-clicking did not change the filtering state. 

Currently, when I add a new literature entry and want to connect it with some keyword groups, it is not possible to do this via the right-clicking context menu, because at the moment of right-clicking, my entry disappears from the main list (because at the moment of righ-clicking it is not yet in that group, but filtering becomes immediately effective). 

An alternative way is to drag-drop the literature entry onto a group element. However in case of nested subgroups, the subbranch needs to be unfolded first, and by unfolding the subgroup the literature entry again disappears in the main entry list. Thus the way to do this is

- Find the right place in the group list and unfold the required subbranches of subgroups 
- Scroll to the top of the group list and click on "All entries"
- Scroll back to the place, where the desired subbranch is unfolded
- In some cases it is again required to find and mark the literature entry in the entry list (which temporarily disappeared)
- Finally drag-drop the literature entry onto the subgroup

A second workaround is right-clicking on the literature entry and select "add to group" in the context menu, however this opens a separate dialog box with the same list of groups, which again needs scrolling and unfolding of subgroups and allows for selecting only one group per time. In case of multiple group selections this dialog box has to be opened for each group individually and always starts at the top of the group list with all sub branches folded. 

Both workarounds are rather cumbersome. A "simple" (at least conceptually simple, I'm not aware of the coding details...) solution would be preventing the group filtering in the main entry window upon right-clicking on a group or upon clicking on the small arrow for folding/unfolding. The filtering should become effective only upon clicking with the left mouse button onto a group name. At least in jabref-3.x it always worked this way.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by andre8s** [comment]
Dear Tobias Diez,



thank you for pointing this out. I have tried the current development version today (installation file: JabRef_windows-x64_5_0-dev--snapshot--2018-08-16--master--a880addc0.exe) on Windows 10 and can confirm, that I can again right-click on the group entries without filtering the literature entries.



However in the pre-5.0 version there seem a few other issues that I didn’t see before in previous versions.



First, in the literature entry viewer the entry numbers seem to have gone. This is not a big deal, and possibly they can be switched on/off via some options settings, which I did not bother to find, yet.



Next, if I double-click on a literature entry for getting the editing dialoge, the screen layout gets distorted in some cases.



For some entries it seems ok:





For other entries, the screen layout gets distorted:





After closing the edit dialog (by clicking on the blue cross), I am left with a non-functional screen:





My first thought was that it might depend on the entry type, however it seems to depend on the length of the author’s list. If there are many authors, the width of the dialog form field gets too large, and this seems to cripple the screen layout.



I have tested this on a fresh Windows 10 enterprise installation. Please check if you could reproduce this behaviour, if needed I could provide some of my literature entries, where I observed this behaviour.



With best regards



Andreas Pflug





--

Dr. Andreas Pflug andreas.pflug@ist.fraunhofer.de<mailto:andreas.pflug@ist.fraunhofer.de>

Head of Group Simulation

Fraunhofer Institute for Surface Engineering and Thin Films IST

Bienroder Weg 54e, 38108 Braunschweig

T.: +49 (0) 531 2155 629 – F.: +49 (0) 531 2155 900







Von: Tobias Diez <notifications@github.com>
Gesendet: Mittwoch, 13. Juni 2018 17:52
An: JabRef/jabref <jabref@noreply.github.com>
Cc: Pflug, Andreas <Andreas.Pflug@ist.fraunhofer.de>; Author <author@noreply.github.com>
Betreff: Re: [JabRef/jabref] Groups are focused on right-click (#4025)



This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by andre8s** [comment]
Dear Tobias,



thank you for your feedback and sorry for my late response. Recent weeks were quite busy, and in the meantime I migrated to another laptop which is running Win10.



I have now switched from Jabref 4.31 to the latest snapshot of 2018-11-07. It seems that this version is somewhat more stable, I do not get the corrupted screen anymore, and the memory consumption seems also stable – even after adding numerous new literature entries.



I have observed a few minor issues, which I would like to summarize in the following.



·         Group interface: It is now possible to right-click onto a group without immediately setting the group focus, however ...

o   If the tiny little arrows to fold / unfold sub-groups are clicked, it will still immediately apply the group-focus. Currently, my workaround is keeping most subgroups unfolded but this seems not optimal.

o   If I have selected a literature entry, right-click on a group and klick “add selected entries to this group”, and if I have a search phrase in the search field above the literature entry list at the same time, it still works, but the literature entry gets de-selected (i.e. I have to re-select it before attaching it to another group). This does not happen, if the search field is empty.

o   The dialog “attach to group”, which is obtained by right-clicking on a literature entry, does not work properly anymore. The additional group window appears, but after some time also the context menu reappears, and jabref tends to crash.

·         Literature entry list:

o   If there is a search phrase in the search field, and I want to make another search, I usually click on the little cross at the right end of the search field in order to make it empty and then type my new search phrase. However, if there was some literature entry selected at the same time, after clicking the cross in the search field the focus will afterwards be set to the author field of that literature entry. When typing my new search phrase, I am suddenly finding myself overwriting the author field of the literature entry. If no literature entry was selected, this does not happen, i.e. the focus remains in the search field.

o   If I manually add a new entry, I have to click on “new article” and afterwards right-click on the entry in case the entry type is different. In former versions, I could select the entry type right-away.

·         PDF linking

o   I usually linked PDFs to my literature entry by drag-dropping the PDF file to the line of the literature entry. In the newest snapshot, this does only work if the PDF contains additional BibTex info --> then a dialog box pops out asking me if I want to include the BibTex info or just link the PDF to the entry. However, if there is no BibTex info in the PDF the dialogbox doesn’t turn up and the drag-drop action is being ignored. A workaround seems dragging the PDF into the edit section of the literature entry in the lower part of the window (meaning that the literature entry might have to be double-clicked in order to open the edit section).



Since the overall stability seems improved compared to version 4.31 I will try working with the 5.* snapshot versions from now on.



With best regards


Andreas Pflug





Von: Tobias Diez <notifications@github.com>
Gesendet: Donnerstag, 16. August 2018 18:24
An: JabRef/jabref <jabref@noreply.github.com>
Cc: Pflug, Andreas <Andreas.Pflug@ist.fraunhofer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [JabRef/jabref] Groups are focused on right-click (#4025)



@andre8s<https://github.com/andre8s>: Thanks for the feedback!

The number in front of the entries was indeed completely removed. We couldn't think of a use case where this number would be helpful for the user and thus removed it to make room for more important information. Why do you miss it?

The other issue that you mention sounds like a real bug to me. Can you please open a new issue here on github and add an example entry for which this problem occurs (and maybe readd the screenshots that gone missing when you posted via mail). Thanks!

**Comment by Siedlerchr** [comment]
@andre8s  Thanks for your reply. Most the issues regarding groups are already filed at issues. Please do yourself and us a favor and check for existing issues and or open a new one  if you can't find anything related to your problem. This helps us to keep the overview.
