### ISSUE TITLE
Date field can crash Jabref

### ISSUE THREAD

**Issue by davidcbenson** [JabRef/jabref#4028]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

## Manually entering the date a date field in the entry editor causes the entry editor to freeze, and most of Jabrefs features to stop working

JabRef 4.2
Windows 10 10.0 amd64 
Java 1.8.0_171

Steps to reproduce:

1. Manually enter a reference (e.g. Article)
2. Manually type date into date field (e.g. do not use the "date selector"). The problem only occurs in date fields with a date selector, not in the bibtex entry editor entering "date = {2018}," etc.
3. The date will visually replicate itself in the display, although not the file (e.g. if you type "2018" Jabref displays "20182018")
4. Pressing enter will cause Jabrefs entry field to freeze, and be unable to navigate anywhere else. You can still select another entry in the entry viewer, and you can save the file. If you save the file, the entry will be correct, and the problem will not necessarily replicate, unless you manually enter the date into the date field.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/ (please remember to make a backup of your library before trying-out this version). Thanks!
