### ISSUE TITLE
Cookie configuration for Google Scholar failed

### ISSUE THREAD

**Issue by retostockli** [JabRef/jabref#4032]
Follow up on closed issue 3975: https://github.com/JabRef/jabref/issues/3975

We have upgraded to the newest JDK/JRE 8-172. No change. I can confirm that google scholar is working without a proxy on another host. 

Is it possible that google scholar cookie fetching does not work via proxy? Could someone check that?

**Comment by Siedlerchr** [comment]
Do you pass the proxy option to JabRef? Could you please try to explicit set the proxy at startup ?

` java -Dhttp.proxyHost=webcache.example.com -Dhttp.proxyPort=8080 -jar JabRef.jar? `

**Comment by psychelzh** [comment]
Here have the same issue, when fetching from Medline/PubMed:

![image](https://user-images.githubusercontent.com/13306020/40161680-2de13e58-59e4-11e8-96cb-6b1ffe2e4fd8.png)

**Comment by retostockli** [comment]
Thanks for the hint. We have tried it, but no success. JabRef is also not able to connect to the update Servers (beginning of log file). Could be a Firewall/Proxy Problem here inhouse in our Institute.

Please Close it as we are successfully able to run JabRef on private Hosts and Networks. We'll debug on our side.
