### ISSUE TITLE
Preserve capital Umlauts during cleanup

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#405]
Ägypten in title field results in  {\"{A}}gypten. This should be the correct syntax, but the result of the pdf is ägypten (field title only!). {{\"{A}}}gypten produces Ägypten. This might be a bibtex bug, because the author field works without additional braces.

**Comment by oscargus** [comment]
Oh, yeah. I was thinking of that earlier in another discussion. If I recall it correctly, there's a parity behavior, so one needs an odd number of brackets to keep the case.

**Comment by grimes2** [comment]
I've checked the syntax: ü is {\"{u}}, Ü is {{\"{U}}} (to preserve capital letter two additional curley braces are needed). This bug should be fixed.

**Comment by lenhard** [comment]
@oscargus What is the status of this issue?

**Comment by oscargus** [comment]
One would need to add an extra set of {} around all capital entries (not characters) in the huge array, soon to be renamed in #841 .

**Comment by stefan-kolb** [comment]
Has this been addressed in #841?

**Comment by oscargus** [comment]
Not consistently, no. There may be capital letters that doesn't have double
braces around them.
