### ISSUE TITLE
Not working from command line

### ISSUE THREAD

**Issue by scriptfx** [JabRef/jabref#4055]
I am unable to run JabRef with arguments from cmd/powershell on Windows 10 April Update. It seems that JabRef.exe does not pass arguments to JabRef.jar.
Jabref was installed with Windows installers (i tried both 64 and 32 bit).

**Comment by Siedlerchr** [comment]
Hm, that's odd. Could you please test the latest version from here? There was a recent fix regarding the commandline: https://builds.jabref.org/master/

**Comment by scriptfx** [comment]
Sorry for the late response.
I've tried and it seems there's nothing to do.

**Comment by Siedlerchr** [comment]
I currently see no way to enable this in our installer. You need to pass the parameters to the JabRef.jar
