### ISSUE TITLE
discrete versus integrated graphics card on MacOS

### ISSUE THREAD

**Issue by jcrbloch** [JabRef/jabref#4070]
When starting jabref on MacOS the system automatically changes from the integrated to the discrete graphics card. This is not necessary and is due to the following incorrect key in the Info.plist in jabref 4.2:

```
<key>NSSupportsAutomaticGraphicsSwitching</key>
<string>YES</string>

```

which should in fact be:
```
<key>NSSupportsAutomaticGraphicsSwitching</key>
<true/>

```
This is also documented here:
[https://developer.apple.com/library/content/qa/qa1734/_index.html](https://developer.apple.com/library/content/qa/qa1734/_index.html)

**Comment by jcrbloch** [comment]
In an older issue from 16Jan2017 it seemed to have been proposed to solve exactly this problem, See [https://github.com/JabRef/jabref/issues/2470](https://github.com/JabRef/jabref/issues/2470).

It may be that Apple modified the switch since then, so that the old solution no longer works. I tried both possibilities in the plist and only my new suggestion works for me. This is also what is stated in Apple's documentation.

**Comment by stefan-kolb** [comment]
So do we really need the new switch or is there no problem anymore even if we remove the switch?

**Comment by jcrbloch** [comment]
I just tried removing the switch, but then the problem reappears. The new switch is thus absolutely necessary.
