### ISSUE TITLE
Cannot add exclusions into `XMP-metadata`'s `XMP export privacy settings`

### ISSUE THREAD

**Issue by KOLANICH** [JabRef/jabref#4072]
I guess we should
1 fix the exclusions mechanism
2 insert 'file' into default exclusions and enable it by default
3 stop storing files paths in bibtex

**Comment by Siedlerchr** [comment]
@johannes-manner  Maybe you can add some insight here

**Comment by johannes-manner** [comment]
Hey, can you please provide an example and your desired outcome and the problems you detected?

**Comment by KOLANICH** [comment]
I found out that the settings of exclusions are just not saved and that's why take no effect. I managed to setup exclisions by exporting settings into a file, editing that file in a text editor and then importing settings from it. So, 

1 bug with exclusions settings should be fixed
2 exclusions should be enabled by default
3 fields containing IDs and files paths (`pdf`, `bibtexkey`) and any other info about environment should be added to the exclusion list by default.

**Comment by tobiasdiez** [comment]
@KOLANICH I'm a bit lost with your description. What kind of "exclusions"? What is exactly the bug that you experience (please provide detailed steps, actual vs expected behavior)...

**Comment by KOLANICH** [comment]
1 create a bib file
2 create a record, bind it to a pdf
3 `Tools -> Write XMP metadata to PDFs`
4 Open the PDF in a plain text editor and see your bibtex id and the path to the file there
5 Go to `Options`->`Preferences`-`XMP-metadata`
6 see that `pdf` and `bibtexkey` are not there, though they should
7 try to add them
8 You can't add more than 1 record by clicking `+` button. Even if you do that, your settings are not saved when you click `OK`.

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/3861

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
