### ISSUE TITLE
Exception in search

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#408]
A search with a single [ bracket throws an exception:
Exception in thread "AWT-EventQueue-0" java.util.regex.PatternSyntaxException: Unclosed character class near index 2
([)
...
I know [ is a metacharacter in regex, that needs a ], but I think its better to catch this exception.

**Comment by simonharrer** [comment]
This is fixed in current master branch, targeting JabRef 3.0. But this uncovered another issue in the current master branch: when updating the search query field and the option for regex is active, and the search query is an invalid regex, the whole search query field is cleared.

**Comment by simonharrer** [comment]
Fixed in master, will be released with 3.0.
