### ISSUE TITLE
timestamp field is not set when drag'n'drop is used to import files

### ISSUE THREAD

**Issue by stefanct** [JabRef/jabref#4086]
I am using JabRef version 4.4-dev--snapshot--2018-06-01--master--26bb54598 on Ubuntu 16.04

Steps to reproduce:

1. Enable the Preferences/General/Mark new entries with addition date. (I am using `yyyy-MM-dd HH:mm` as format but my guess is that's not relevant). Additionally, mark the overwrite option.
2. Drag'n'drop a file onto the entry table and let the importer do its work.
3. Notice a new entry that has no `timestamp` field set and mourn.

(I have not tested a manual import via the file menu yet and have to run...)

Also, I would love to see the addition marking enabled by default and the default format to include a time in addition to the date. They work way better than the "marking" options to recognize newly added references. Cheers.

**Comment by tobiasdiez** [comment]
@Siedlerchr do you see the possibility to fix this as part of #3765 ?

**Comment by Siedlerchr** [comment]
Sounds more like an importer feature/problem for me.

**Comment by stefanct** [comment]
FWIW, I have just tested another import via `File/Import into current library` and that creates the timestamp just fine (after displaying an import selection dialog that is not visible for d&d operations). I am a n00b jabref user but from my perspective these two action should trigger the same behavior IMHO (maybe not if the drop happens over a preexisting entry but certainly when dropped at the bottom of the table where it is "empty").

**Comment by Siedlerchr** [comment]
Okay thanks for your feedback! I will take a look at that

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
