### ISSUE TITLE
Sciencedirect web search does not work

### ISSUE THREAD

**Issue by Bananach** [JabRef/jabref#409]
No matter the search string, using Web search for "Search ScienceDirect" always returns

"No entries found for the search string <searchstring>".

There are no exceptions thrown, and I am using the latest JabRef with the latest Java. 

Indeed, it seems the search has been broekn for years due to a change of sciencedirect.com, see http://sourceforge.net/p/jabref/bugs/911/

**Comment by matthiasgeiger** [comment]
Confirmed.

**Comment by matthiasgeiger** [comment]
Removed from UI for upcoming 3.0 release as the repair/rework will require some time.

**Comment by arnyeinstein** [comment]
Hi, any news on the problem with sciencedirect? I would be very grateful if it would work again.
Cheers
Renger

**Comment by oscargus** [comment]
I did just now email them to see if we can get an API key which is OK to include in the repository. In that case it should be rather straightforward to parse the search results and provide a BibTeX entry for each (Json or XML).

**Comment by koppor** [comment]
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.
