### ISSUE TITLE
Names are not in the standard BibTex format

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#4092]
`L.C. Briand and S. Morasca and V.R. Basily`

Only because space or a dot is missing after firstnames.

Also remove dot at the end of the warning message: `Names are not in the standard BibTex format.`

**Comment by bernhard-kleine** [comment]
This is an issue I would like to see been solved. Any entry I add using Medline has this problem with missing dots. Why don't you have the program add them? If it can recognize the missing dots, I guess it would be simple to add them, too.

**Comment by tobiasdiez** [comment]
Right-click > Normalize to BibTeX name format adds the missing space (and reorders the name parts).

I'm actually not sure if we should change this behavior. As far as I'm aware, the space should be there by convention...

**Comment by bernhard-kleine** [comment]
I did the rightclick > Normalize but the error (?) remains.
JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911
Windows 7 6.1 amd64 
Java 1.8.0_172
JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911
Windows 7 6.1 amd64 
Java 1.8.0_172
![grafik](https://user-images.githubusercontent.com/9216487/42750526-d09ca83a-88e7-11e8-9885-39fde0c20f43.png)

**Comment by tobiasdiez** [comment]
The BibTeX standard seems to be that there should be a space after the dot. Hence, the check is ok like it is right now.

**Comment by z3li3us** [comment]
Try to use curly brackets maybe?

**Comment by koppor** [comment]
@z3li3us Longer background of the issue: JabRef has build-in checkers for fields. One is for the content in the BibTeX field. In the issue report at hand, the names are correct, but the checker complained. The tool JabRef should not force the user to change the data, but it should adapt to other formats.
