### ISSUE TITLE
Minimum required java version for JabRef 4.3 is higher than the most recent stable java release provided for consumers on Windows 10

### ISSUE THREAD

**Issue by jonasfrede** [JabRef/jabref#4093]
JabRef version 4.3 on Windows 10 x64

This issue seems like a small increment error which was introduced in JabRef 4.3 (see [the first line here](https://github.com/JabRef/jabref/blob/v4.3/CHANGELOG.md#changed)) 

Steps to reproduce:

1. Install the most recent java version to date from [this page](https://java.com/en/download/win10.jsp) (which is 1.8.0_171 to date)
2. Install JabRef 4.3 with the installer provided
3. Start JabRef and see the error message that 1.8.0_172 is required, although 1.8.0_171 is the most recent available version

The problem is, 1.8.0_171 and 1.8.0_172 were released simultaneously, shown [here](http://www.oracle.com/technetwork/java/javase/8u172-relnotes-4308893.html) and [here](http://www.oracle.com/technetwork/java/javase/8u171-relnotes-4308888.html). 
Version 1.8.0_171 does not update to 1.8.0_172 automatically, even after checking for new updates in the scheduler, so my question is: Does the CPU leak described in [3943](https://github.com/JabRef/jabref/issues/3943) still persist in 1.8.0_171 or should JabRef support both versions?

**Comment by jonasfrede** [comment]
Seems like I really was too dumb to find 172, as both versions were released simultaneously, shown [here](http://www.oracle.com/technetwork/java/javase/8u172-relnotes-4308893.html) and [here](http://www.oracle.com/technetwork/java/javase/8u171-relnotes-4308888.html).

But the minor nuisance still stands: Java 171 does not update to 172 automatically, even after checking for new updates in the scheduler, so my question is rather: Does the CPU leak described in [3943](https://github.com/JabRef/jabref/issues/3943) still persist in 171 or should JabRef support both versions?

**Comment by tobiasdiez** [comment]
Strange...Update 172 is actually available from http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html.

**Comment by bernhard-kleine** [comment]
This is obviously an issue of Oracle Update policy. Two updates were simultaneously distributed, 171 and 172. On Win7 it is the same as on Win10. The higher Update is not provided automatically to customers. @tobiasdiez whether it is available or not is not the question. That is not distributed is the problem. Do you expext anybody to update java to run Jabref? That is really the problem for customers. They have to do update manually and not via the usual procedure.
my 5 cts

**Comment by omikro** [comment]
Just the same with Debian Jessie. Any atempt to upgrade to 1.8.0_172 failed.

**Comment by bernhard-kleine** [comment]
Upgrading with the link thomas provided work smoothly.

**Comment by omikro** [comment]
Thanks

**Comment by hu00004** [comment]
However, in mac, the recommended version for java is still 1.8.0_161 (java 8 update 161). Dont know how to set it , and of course jabref can works even with the warning of updating java.. thus maybe no need to update java??

**Comment by stefan-kolb** [comment]
The java version contains a bug that raises CPU load continuously to 15-30 %. This will heat up your PC, and also causes concurrency problems for JabRef unfortunately.
