### ISSUE TITLE
Global search not available

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#4096]
Currently that the content of the search field is bound to a tab. In the old versions, it was globally stored. So I could click through the tabs and see if an entry is available somewhere.

![search](https://user-images.githubusercontent.com/1366654/40957508-d6c75808-6895-11e8-8f68-aa57fb459cda.gif)

Refs https://github.com/JabRef/jabref/pull/1549, https://github.com/JabRef/jabref/issues/104#issuecomment-157304997, https://github.com/JabRef/jabref/pull/332, https://github.com/JabRef/jabref/pull/1981

This is the thing, I miss most. I think, we described all our search features at https://help.jabref.org/en/Search for a description of our search capabilities. I can agree to go through the documentation and redesign it.

**Comment by tobiasdiez** [comment]
I think one can make an argument for both behaviors. @JabRef/developers opinions?

**Comment by LinusDietz** [comment]
I think it should be global. Also, there should be an indication in the tab whether there are results in the respective bibliographies.

**Comment by stefan-kolb** [comment]
One could implement it like that, but I guess this comes with a performance penalty, especially if we also check the other tabs without focus.

**Comment by LinusDietz** [comment]
Well, I think the performance overhead is not really too bad, since it is a linear increase with the number of bibliographies.

**Comment by stefan-kolb** [comment]
I guess the performance is already bad in a single database with a lot of entries. At least if I recall the reports correctly.

**Comment by teertinker** [comment]
For me, removing all sorts of global search in the current 5.0(beta1) is really a drawback. I always work with several tabs - and I think JabRef is intended to be used that way. When I search for an entry, I now have to enter the search term several times. Especially when using complex search terms, this becomes very time consuming. I really liked the additional global search window. Wouldn't it at least be possible to give an option to keep the search-term when switching tabs?

**Comment by acfrery** [comment]
The global search option is fundamental.

**Comment by ytzemih** [comment]
I am with @tobiasdiez  that both options are useful. However, in my context, I have used (and would desire to use) global search by far most often (afaik in JR3, both options were available, the search interface was actually quite fast and flexible). Moreover, tab-specific search has proven to be very inconvenient to me as I am usually working with 4-6 medium too large bib files, sometimes up to 10 depending on the projects I am involved. In at least 95% of the cases, I want to have the same search repeated/updated whenever I change the tab. One could say this is not how JR should be used in which case I am happy to receive some suggestions. I'd be nice to have a search history in the search field to assist in autocompletion. That might be an alternative to tab-specific search. Thanks a lot.

**Comment by teertinker** [comment]
Can any development about the issue be expected in a foreseeable future? Is this about technical problems or design decisions? Honestly, I don't understand why global search has been removed. If working with tabs is a feature of jabref (which it really is - compared to other software like endnote), then workflows between tabs should be designed to be seamless. If a background search of all databases is too heavy, solutions in between are appreciated.

**Comment by stefan-kolb** [comment]
It is more or less a resource issue. The scarce resource is the unpaid developer that needs to implement this.

**Comment by koppor** [comment]
For the student project: Implement the search popup, where the ALL opened libraries are searched for papers. Start an old JabRef version (3.8.1 or so) using JRE8 to see the functionality.

**Comment by ytzemih** [comment]
From personal experience, the other posts here, and from other applications with similar functionality, I believe global search as described above is generally a relevant feature. E.g., I'd need to use it most of the time when I search in JR. JR 2 and 3 had this feature, as far as I remember, but it seems from the discussion that it's difficult to implement in JR 5. What is the technical reason for this difficulty? 
I imagine very naivly that _if a "global search switch" is true then the search is refreshed whenever the active file tab is changed_, an event that I believe could be associated with a corresponding "refreshSearch" handler. That doesn't sound to be difficult to implement but it's probably not the most elegant way to do it. Thanks for any comments.

**Comment by teertinker** [comment]
Irrespective of the missing ability to search across different tabs, I just discovered that the search function works different than the group search function (which works across tabs). This seems to be illogical for me as a user. 

Just compare the two screenshots. The search term "Wo" in the group filter is remembered when switching tabs. 
![grafik](https://user-images.githubusercontent.com/8830305/111611054-54313d00-87dc-11eb-8907-fc2037d6ef86.png)
----

![grafik](https://user-images.githubusercontent.com/8830305/111611104-614e2c00-87dc-11eb-8da5-75fd95ea85a5.png)

I'd wish the same behavior for the general search field.

**Comment by kainagel** [comment]
Before you close this issue because of inactivity: Global search was the feature I used most in jabref.  Now I need to go manually through all tabs ... :-(

**Comment by koppor** [comment]
This issue also includes to have a **global search window** showing the search results for **all** opened databases. One can see this in JabRef 3.8.2.

**Comment by koppor** [comment]
In JabRef 4.3.1, it was toggle button

![grafik](https://user-images.githubusercontent.com/1366654/127920516-0262f9d6-65cc-4d1b-847c-ff4d9db248ac.png)

## Keep Search String throughout all opened tabs

### JabRef main (as of today)

![grafik](https://user-images.githubusercontent.com/1366654/127920819-d231d9a3-e003-49a6-bd9f-734a584c1d54.png)

![grafik](https://user-images.githubusercontent.com/1366654/127920835-a03bfe35-cb49-4768-a3d2-54cabf7b6eee.png)

### Toggle Button On

![grafik](https://user-images.githubusercontent.com/1366654/127920578-a70686e9-fa01-49f9-9584-498cecba3b7e.png)

![grafik](https://user-images.githubusercontent.com/1366654/127920593-24a04479-35a5-46ea-935e-653c941fd6c9.png)

### Toggle Button Off

![grafik](https://user-images.githubusercontent.com/1366654/127920658-119f6554-d96f-4a47-9cf0-6c47b3646f38.png)

![grafik](https://user-images.githubusercontent.com/1366654/127920671-805ce518-3aab-4810-b3a3-b36283bd5385.png)

## Global Search Dialog

![grafik](https://user-images.githubusercontent.com/1366654/127920695-75338b7b-2e2e-46b7-8306-004ad1be9421.png)

**Comment by ytzemih** [comment]
Thanks for this summary. It's a pity to see that this clean search concept (which is a faithful extension of what is there now) got lost over the years. I wonder what the reason was.

**Comment by Siedlerchr** [comment]
It got lost by the transformation of the old GUI to the new GUI technology, but we are planning to reimplement this

**Comment by ytzemih** [comment]
I see, that makes sense. Thanks for letting me know.
