### ISSUE TITLE
Ctrl+O should open the folder in the current directory of the bib file

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#4097]
Currently, JabRef uses the last opened directory to open a file. Is it possible to fire up the action "Open File" starting in the directory of the currently edited file when pressing  <kbd>Ctrl</kbd>+<kbd>O</kbd>?

Similar issue at IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-176611

**Comment by JavierMF** [comment]
Hi! I could try to implement this.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.
