### ISSUE TITLE
Comments are not shown in entry preview

### ISSUE THREAD

**Issue by mutlusun** [JabRef/jabref#4098]
- [X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.3 on Ubuntu 18.04

Steps to reproduce:

1. Open entry preview on a entry with comments
2. Comments are not shown (older versions have shown the comments field)

How to fix it:
Change following line in the prefix preferences:
```
\begin{review}<BR><BR><b>Review: </b> \format[HTMLChars]{\review} \end{review}</dd>
```
to
```
\begin{comment}<BR><BR><b>Comment: </b> \format[HTMLChars]{\comment} \end{comment}</dd>
```

I am reporting this, because I think that all users are affected.

Thanks for your great work!

**Comment by Siedlerchr** [comment]
Thanks for reporting this. It seems to be that we overlooked this with #3762
