### ISSUE TITLE
Moving to the next entry while in entry editor no longer supported

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4104]
- [+] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists
JabRef 4.4-dev--snapshot--2018-06-04--master--ee669a542
Windows 7 6.1 amd64 
Java 1.8.0_172

In 4.1 I could move in the entry editor to the next entry using Ctrl-Shift ↓ (the latter from the numeric key pad. That it must be the numeric key pad is not mentioned in the help.
However with the latest snapshot this changing entries is no langer supported. Within the field Ctrl Shift ↓ or Ctrl Shift ↑ move to the end or beginning of that field. Moving to the next or previous entry seems no longer supported.

**Comment by Siedlerchr** [comment]
Have you tried resettting the keybindings?

**Comment by bernhard-kleine** [comment]
In the latest snapshot once you have clicked a field e.g. DOI or Note, the up/down keys stop working.

**Comment by bernhard-kleine** [comment]
Resetting the key bindings? I never touched that stuff.

**Comment by kuchenzwiebel** [comment]
I can confirm this issue for JabRef 4.3.1 (Linux 4.4.0-127-generic amd64; Java 1.8.0_171).
 Custom key bindings (like Ctrl + Shift + N) don't work; the default (Ctrl + Shift + DOWN) at least doesn't work with the standard arrow keys.

**Comment by bernhard-kleine** [comment]
JabRef 4.4-dev--snapshot--2018-06-13--master--5069cb712
Windows 7 6.1 amd64 
Java 1.8.0_172

Sorry to report it is not finished: the Ctrl-Shift down/up does not move to the next entry. It moves to the beginning or the end of the item e.g. Title.

**Comment by tobiasdiez** [comment]
Sorry, forgot to say that the defaults changed to "alt + up/down". (Moreover, you may need to wait a few minutes until the new build is ready)
