### ISSUE TITLE
Improve check for page numbers

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4113]
JabRef version 4.1 and all that followed

Since a couple of journals in the biomedical community have started to add letters to their page numbers, like American J Physiol, Current Biol and many others, it is no longer valid to label these page "numbers" as errorneous. That check should be modified.

**Comment by tobiasdiez** [comment]
The purpose of the check is to find erroneous prefixes like `pp.` and this still makes sense even for alpha-numeric pages. The biblatex documentation (in the description of the command `rangelen`) contains a list of valid examples of the pages field. We should support all those formats and recognize them as valid input.

**Comment by tobiasdiez** [comment]
As wished in http://discourse.jabref.org/t/pages-field-allow-use-of-en-dash/1199, the parser should also accept ranges separated by `--`.

**Comment by 1160200515** [comment]
Can you leave a screenshot or a more detailed explanation? My team and I want to improve this issue.

**Comment by bernhard-kleine** [comment]
If you take the DOI:10.1016/j.cub.2008.07.040 than you can see that the page range is: R795--R804.
