### ISSUE TITLE
The application hangs when selecting the "Edit > Manage keywords" menú

### ISSUE THREAD

**Issue by JavierMF** [JabRef/jabref#4117]
- [X] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version master on Mac OS X 10.11.4 x86_64 
Java 1.8.0_172

Steps to reproduce:

1. Start the application
2. Select an entry in the MainTable
3. Select the "Edit > Manage keywords" menú
4. The application hangs

After debugging, the offender sentence is `diag.setVisible(true);`
https://github.com/JabRef/jabref/blob/66afd4216b4ee0db9525df9782200e36161a9b4f/src/main/java/org/jabref/gui/actions/ManageKeywordsAction.java#L260-L264

**Comment by Siedlerchr** [comment]
Thanks for the report, looks like a Threading problem between swing and JavaFX. I think the easiest way is to use an fx dialog and add the swing content to a Swing Node. This is how we do it for the cleanup and the settings dialog

**Comment by Siedlerchr** [comment]
The dialog still works for me on windows however, it could be that it is in the background, hidden behind the main window.

**Comment by JavierMF** [comment]
I can see the Spinning Wheel of Death over the application. If I move the main window nothing is shown in the background and if I change the focus to other application I can not come back to JabRef.

**Comment by Siedlerchr** [comment]
Mayye related to #4118

**Comment by Siedlerchr** [comment]
We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by Siedlerchr** [comment]
Depends on #3861

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
