### ISSUE TITLE
Replace default group icon by small circle

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4129]
The current triangle has the disadvantage of being to small to show color and, moreover, can easily be mistaken for the arrow symbol that expands/collapses a group hierarchy. 

Material design icons provide a full circle but this one is slightly to large. 

@halirutan may I assign you this issue since you are our expert in creating custom font-based icons (e.g. a smaller circle or whatever you think is suitable)?

**Comment by halirutan** [comment]
I might be mistaken, but I believe this is not possible. When I encode the SVG's into a TTF, only their shapes, but not their absolute size is taken into account. They are all resized according to the font settings. To give an example, the [VSCode icon]() I added recently has itself a size of 260pt x 260pt.

<img width="793" alt="screen shot 2018-06-14 at 15 56 20" src="https://user-images.githubusercontent.com/511683/41416809-00516846-6fec-11e8-8e22-cb331837952e.png">

I did not change anything in this icon and directly imported it into the TTF where it was rescaled to match the size of the other glyphs. As you can imagine, creating a smaller circle would be useless, as it would be resized to the original glyph-size.

What you can try is to use a font-size that is larger for the group-icons.

**Comment by tobiasdiez** [comment]
Just a guess, but what happens if you add transparent space around the icon?

**Comment by matthiasgeiger** [comment]
Just another Idea: Styling the standard "middle dot' (\u00B7 or ·) is not doing the Trick? I think it should be part of most standard fonts, but have not checked it...

**Comment by halirutan** [comment]
@tobiasdiez That might work but it depends on the tool that builds the font from the SVG. Some tools simply grab all paths and put them into the icon. Currently, I don't have that much time at hand as building and updating the TTF is not an automatic process at the moment. Maybe someone can check if using the normal circle we already have in a different size works too.

**Comment by tobiasdiez** [comment]
Maybe one can also use a scaling of the materialdesign dot (or maybe they provide in the meantime a different dot).

**Comment by tobiasdiez** [comment]
Thanks to @mohit038 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
