### ISSUE TITLE
No program associated for help link

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#413]
JR 3.0
Help > Help contents then I clicked on BibTex help (but it happens with all entries). An error popup appears about:
There is no program associated to perform the requested action...
With the title:
jar:file:<install dir>/JabRef-3.0.jar!/help/en/BibtexHelp.html
It suggests to go to the default programs and set the program for .html (I suppose), but the association obviously already exists.
Thanks for looking!
mario

**Comment by matthiasgeiger** [comment]
This works fine for me.

Which OS do you use? 

Can you paste the messages showing up in the Error Console (Help -> Show error console)? 

Thanks!
Matthias

**Comment by crystalfp** [comment]
Good morning Matthias!
There is nothing in the error console, only the log message that I have 
loaded my bib file.
Attached the error popup.
I'm on Win 7 64bits.
BTW, I speculate the help files are inside the jar file, because in the 
installation there is no /help/en/ directory.
Thanks!
		mario

On 30-Nov-15 08:45, Matthias Geiger wrote:
> This works fine for me.
>
> Which OS do you use?
>
> Can you paste the messages showing up in the Error Console (Help -> Show
> error console)?
>
> Thanks!
> Matthias
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JabRef/jabref/issues/413#issuecomment-160546177>.
>

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS)
v. Trevano 131, 6900 Lugano, Switzerland
Tel: +41 (91) 610.82.60

**Comment by koppor** [comment]
GitHub didn't let the screenshot go through. Edit your message on GitHub and attach the screenshot by drag'n'drop. We recommend [GrabNDrop](http://www.scyv.de/gnd/) for quickly creating screenshots.

**Comment by matthiasgeiger** [comment]
(GitHub generally removes all attachments from Mail replys - so you have to use the Web-Frontend to upload screenshots)

**Comment by domwass** [comment]
Similar here (on MacOS 10.11.1): Whenever I click on a link inside the help window, nothing happens, there is even no error message.

**Comment by matthiasgeiger** [comment]
Oh... grap. I missunderstood the original report by @crystalfp... 

Yes. Help is showing up BUT clicking on links is not possible. 

Only the builded jars are affected - running help from a development build is working fine.

**Comment by crystalfp** [comment]
Here is the screenshot. Thanks!
![help-error](https://cloud.githubusercontent.com/assets/865866/11466474/6cbc5e40-9741-11e5-9ed4-a34d939c42fd.png)

**Comment by matthiasgeiger** [comment]
Fixed version is available here http://builds.jabref.org/master/jabref_windows-x64_3_1dev--snapshot--2015-11-30--master--c9fdbce.exe - released version will be updated later this day.

:disappointed:
