### ISSUE TITLE
Provide access to dark theme

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4130]
In #3891 a dark theme was introduced but so far there is no switch in the preference dialog that allows to choose it.

**Comment by Siedlerchr** [comment]
Refs #382

**Comment by OlzClark** [comment]
Hi, it's my first time contributing to open source. Mind if I give this a shot?

**Comment by tobiasdiez** [comment]
The relevant classes are: https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/util/ThemeLoader.java and https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/preftabs/AppearancePrefsTab.java

**Comment by Siedlerchr** [comment]
We could maybe also take a look at jmetro design: https://www.pixelduke.com/jmetro 
to  get some ideas

**Comment by ngrant123** [comment]
Hello, 
Is it okay if I work on this? I currently have made an option in the preferences box and the dark theme is implemented correctly. Im about to create a pull request and everything. I might have pushed some code accidentally sorry about that I'm new to open source contributing

**Comment by ngrant123** [comment]
Yeah I definetly pushed some stuff to the master branch sorry about that you can delete my commit im creating a pull request rn

**Comment by Ali96kz** [comment]
Is there any way to change theme now?
