### ISSUE TITLE
Web search input field does not work

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#4132]
- [X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.4-dev--snapshot--2018-06-15--master--f47b74066
Linux 4.4.0-128-generic amd64 
Java 1.8.0_171

Steps to reproduce:

1. Click Alt+4 to open the Web Search panel.
2. Choose e.g. Google Scholar.
3. Try to type something in the white text field just below "Google Scholar" (see screenshot).
Nothing happens and there is no error displayed.

![screenshot from 2018-06-17 18-44-06](https://user-images.githubusercontent.com/1462215/41509559-b438a5bc-725e-11e8-82c5-1a185cd1b9ff.png)

**Comment by Siedlerchr** [comment]
Google Scholar is currently broken, but that's another issue. 
Works fine for me on windows. The Problem might actually be that the window is hidden behind the main window, as it is still written in swing. Check using ALT+TAB to see if the window is somewhere in the background


![grafik](https://user-images.githubusercontent.com/320228/41510485-cffd4044-7265-11e8-8e9b-695765cde836.png)

**Comment by erelsgl** [comment]
The problem occurs with all other options in the Web Search, not only Google Scholar.

I do not see any other window. In the text field where you wrote the word "semantic", I just cannot write anything. I click on it and type but the text field remains blank.

**Comment by j0hannes** [comment]
I have exactly the same problem with 4.4-dev

**Comment by j0hannes** [comment]
back to version 4.3.1, the web search field is still editable in this version

**Comment by ilippert** [comment]
I experience the same problem in
JabRef 5.0-dev--snapshot--2018-07-02--master--aed7712bc
Linux 4.17.3-200.fc28.x86_64 amd64 
Java 1.8.0_172

**Comment by bernhard-kleine** [comment]
JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911
Windows 7 6.1 amd64 
Java 1.8.0_172
You can enter text in the window but Google Scholar seems still broken.

**Comment by Siedlerchr** [comment]
Should be fixed in master now. Just wait a couple of minutes until the build is ready.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by bernhard-kleine** [comment]
I had just installed the latest snapshot of JR5.0 and still the Websearch is not working. I show the image with the search window, upper left, the jabref window with the Medline search and Medline in Firefox showing that Medline works but cannot be accessed by Jabref.
![grafik](https://user-images.githubusercontent.com/9216487/43192944-08d69c06-8fff-11e8-9d43-8e4b460afedf.png)

**Comment by Siedlerchr** [comment]
Okay, confirmed and fixed. It was a thread issue with Swing and Javafx. The swing dialog was blocking the execution.  Your Medline search works now 3708345.
I have directly commited to master  ce071c7
