### ISSUE TITLE
In Aux Import, the Browse button makes JabRef hang

### ISSUE THREAD

**Issue by erelsgl** [JabRef/jabref#4134]
- [X ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.4-dev--snapshot--2018-06-15--master--f47b74066
Linux 4.4.0-128-generic amd64 
Java 1.8.0_171

Steps to reproduce:

1. Tools -> New sublibrary based on AUX file
2. Choose a library
3. Click "Browse"

JabRef then hangs. There is no error message. It must be killed and restarted.

![screenshot from 2018-06-17 19-25-11](https://user-images.githubusercontent.com/1462215/41509938-7ab3c244-7264-11e8-8c44-cdf1e4b77864.png)

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
