### ISSUE TITLE
Complains for missing "editor" for "Online" entries

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#414]
JR 3.0 but also 2.11
Running in biblatex mode.
My "Online" entries are marked as problematic because there is no "editor" field.
But per biblatex documentation (2.1.1 page 10) you need author or editor, but both are not required.
And I have the "author" field filled.
Again, it is a small thing.
Thanks for looking!
mario

**Comment by lenhard** [comment]
Thanks for the notification! This shouldn't be too hard to fix and will be corrected in a future release.

**Comment by stefan-kolb** [comment]
I can confirm this bug. We need to rework all required and optional fields for the BibLaTex entries. This was only done for Bibtex and IEEETran entries.

Also see http://ctan.mirrorcatalogs.com/macros/latex/contrib/biblatex/doc/biblatex.pdf for information.
