### ISSUE TITLE
Version 3.0 text too big, fuzzy on Win10 MS SP3

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#415]
JabRef 3.0 has a lot of improvements but one thing that's gone backwards are the fonts and rendering.  

In Windows 10, on my Surface Pro 3, the entry table text is now giant -- at least 2X bigger than normal text on any other program.  I can't find a way to change its size, although I can shrink the menu and label fonts. 

The size of the entry preview text is about right, matching the size of other text on my screen.

However, it's fuzzy, like everything else in JabRef 3.0.  It looks like the JabRef window is being viewed in a sauna.

**Comment by simonharrer** [comment]
Can you provide us with a screenshot?

Have you tried `View -> Increase table font size`?

**Comment by notuntoward** [comment]
Wow, that was fast, and oops, I had not tried the view menu.  I'd imagined that everything was controlled through the Options.  Anyway, thanks, yes that's the way to decrease the font size.

I've attached a screenshot showing the fuzziness. You can compare with the pdf on the left or with the window title placed at the top by Windows 10.
<img width="1080" alt="capture" src="https://cloud.githubusercontent.com/assets/3851891/11468047/d14df57a-974c-11e5-9fab-9e6d14a073ad.PNG">

**Comment by simonharrer** [comment]
What resolution does your display have?

**Comment by notuntoward** [comment]
It's 2160x1440, or 216 pixels per inch (ppi).

**Comment by simonharrer** [comment]
This may be the problem. We have not yet optimized JabRef for such displays.

**Comment by matthiasgeiger** [comment]
You might try to change the "compatability settings" for JabRef to "Disable Scaling for high DPI settings":
See MS Help: https://www.microsoft.com/surface/en-us/support/apps-and-windows-store/app-display-issues?os=windows-8.1-update-1

However, the Icons might be way to small for your display. We are aware of this and planning to improve this in further versions.

**Comment by koppor** [comment]
Refs  #113 - "Should also work at unusual setups"

**Comment by notuntoward** [comment]
Thanks Matthias, that's much better.  Yes, the icons are tiny but if I had to pick what to squint at, I'd rather squint at icons.
