### ISSUE TITLE
Rename file can generate illegal filename

### ISSUE THREAD

**Issue by HarryEClarke** [JabRef/jabref#4153]
With a very long title, JabRef version 4.3.1 running on Microsoft Windows 8 can generate illegal filenames which exceed the 255 character limitations when renaming an attached file.
To reproduce, create an entry where the bibtex key and title exceeds 255 characters. Attach a file to the entry, and then rename the file. This results in a file with an illegal filename, which the only option available is to delete the file by deleting the MSDOS 8.3 filename.

JabRef should ensure that it only creates legal filenames under the operating system it is running under,
As very long filenames are not helpful, the title could easily be truncated to the first 100 characters.

**Comment by jo-1** [comment]
While truncating BibTeX keys to 100 characters will not really solve the problem (maxlength has to consider path length), an option to cut off field contents in the BibTeX key generator would certainly be a very useful feature. An additional modifier could limit to a specified number of characters, e.g. {camel:cut(100)}, and/or it could truncate the contents before the first occurence of a string {camel:end( : )}. Judging from how the :abbr modifier works I presume modifiers are applied before transformation and concatenation. For the first option this would result in slightly varying final lenghts, but this shouldn't be a problem.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by mlell** [comment]
@Siedlerchr Maybe this is fixed as well, but are you aware that while the file name length limit is 255 on most Linux filesystems and 4096 on Ext*, if you have an encrypted home directory using eCryptFS the file name limit is 143 characters. At least for some file names.

https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs

**Comment by Siedlerchr** [comment]
Oh thanks for the info, we currently check for illegal characters in the filename (e.g. slashes) and have the 255 char limit.
