### ISSUE TITLE
Several process in background still opened after closed main program

### ISSUE THREAD

**Issue by ChillerThon** [JabRef/jabref#4155]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_171

Steps to reproduce:

1. ... Open JabRef and then close, regardless of the way
2. ... Open Task manager and see all process (not closed) in background

to each process, a memory load is taken from the system (about 220 MB each)

<details>
  <summary>Log File</summary>
   No Log File.  See picture attached
<details>
<summary>Detail information:</summary>
   No detail information automated collected.   See picture attached
</details>
  ```
  Paste an excerpt of your log file here

  ```
</details>
![jabref-memory-20180625](https://user-images.githubusercontent.com/37935693/41856242-f87c98a2-786a-11e8-8436-f05798ab2aa0.png)

**Comment by Siedlerchr** [comment]
This should be fixed in the latest Master version.
