### ISSUE TITLE
page numbers in check integrity

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#416]
Awesome new version! Great work.
"Check integrity" is complaining for field "pages": should contain a valid page number range. This is, because some Newspaper (New York Times) use A1 or D12 as page numbers.

**Comment by lenhard** [comment]
Thanks for the compliment and thanks for testing the new version. Can you provide the exact contents of the `pages` field for which the check complains, but should not?

**Comment by grimes2** [comment]
The exact content is: A19
The problem is probably the character A. But as I allready mentioned, New York Times or Chicago Tribune name their pages with capital letter (A-D) + a number.

**Comment by simonharrer** [comment]
Some journals use page numbers like `4:1--4:56`, which also fails in the current validation check. 

Example:
```
@Article{Mili2010BusinessProcessModeling,
  Title                    = {{Business Process Modeling Languages: Sorting Through the Alphabet Soup}},
  Author                   = {Mili, Hafedh and Tremblay, Guy and Jaoude, Guitta Bou and Lefebvre, \'{E}ric and Elabed, Lamia and Boussaidi, Ghizlane El},
  Journal                  = {ACM Comput. Surv.},
  Year                     = {2010},
  Month                    = {December},
  Number                   = {1},
  Pages                    = {4:1--4:56},
  Volume                   = {43},
  Address                  = {New York, NY, USA},
  DOI                      = {10.1145/1824795.1824799},
  Publisher                = {ACM}
}
```

**Comment by stefan-kolb** [comment]
The currents checks are based on the allowed format specified by the Bibtex documentation.

**Comment by tobiasdiez** [comment]
BibLatex is not so strict about the pages field. As far as I know, pretty much everything is accepted (but A1 is not recognized as a page, so it is displayed as "A1" instead of "p. A1"). Moreover, (I think) it is no longer required to separate pages by two dashes, so `5-6` should be valid.

**Comment by grimes2** [comment]
I think, its better to keep and obey this strict Bibtex check. So it is possible to check the affected entries in the Bibtex-output for processing errors. Can be closed.

**Comment by stefan-kolb** [comment]
@JabRef/developers what do you guys think?

**Comment by lenhard** [comment]
I agree with @grimes2: keep the strict check and close the issue.
