### ISSUE TITLE
Modified database marker invisible

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#4161]
Running Windows 10 with the taskbar vertical on the right side of the screen.
When I modify a database, The JabRef taskbar icon puts the modified mark, the asterisk, at the end of the filename, making it invisible on the taskbar.

The fix is to put the asterisk at the beginning of the filename as, for example, Notepad++ does.

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_171

**Comment by tobiasdiez** [comment]
Can you please add a screenshot that shows your problem. I'm a bit confused how the asterisk that JabRef adds to the library name depends on the Windows taskbar.

**Comment by crystalfp** [comment]
Here they are. The first screenshot shows JabRef with the References.bib file modified. The asterisk is not visible in the taskbar on the right. Instead Notepad++ clearly show that the file has been modified in the taskbar icon.

![capture](https://user-images.githubusercontent.com/865866/42126972-eddcfce6-7c90-11e8-81c2-f97060d7f927.PNG)

If I hover the icon the window title is visible and the asterisk is present, just in a position that makes it not useful.

![capture2](https://user-images.githubusercontent.com/865866/42126994-6fc8339c-7c91-11e8-8163-bc7c84d63813.PNG)

Hope now it is clear. For me it is a malfunction (something that does not carry to the user the status).
Thanks for your help and your useful tool!
mario

**Comment by stefan-kolb** [comment]
This might be worth a consideration. 
However, we need to check how this behaves with multiple open tabs.
Also, just for clarification this is no standard behavior and is also not inplemented by other editors like Atom or Sublime (as far as I can see).

**Comment by crystalfp** [comment]
Yes I know there is no standard here, just convenience. With the editor (btw, I tried and removed Atom and Sublime moving to np++ and VS Code also for this reason) I notice if I modified something, with JabRef I have to activate it and check. For multiple tabs only the active one should show the modified status.
Anyway, thanks for looking at it!
mario
