### ISSUE TITLE
Encoding issue in "Related Articles" tab

### ISSUE THREAD

**Issue by duelle** [JabRef/jabref#4165]
When the found related articles in the "Related Articles" tab contain special characters, they are not rendered correctly (see screenshot) 
![screen-2018 07 04_16 02 06](https://user-images.githubusercontent.com/7212186/42281403-ba21e18a-7fa3-11e8-9188-82666e32c72b.png)

- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.3.1
Linux 4.17.3-1-arch amd64 (Arch Linux)
Java 1.8.0_172

Steps to reproduce:

1. Add entry with following BibTex (or any other entry that gets related articles with Umlauts or other special characters):
@Article{zhu2016devops,
  author    = {Zhu, Liming and Bass, Len and Champlin-Scharff, George},
  title     = {Devops and its practices},
  journal   = {IEEE Software},
  year      = {2016},
  volume    = {33},
  number    = {3},
  pages     = {32--34},
  publisher = {IEEE},
}

2. Open "Related Articles" tab
3. See broken symbols

The only possibly related ticket I found was #3816 it did not mention the special characters (in a screenshot in the ticket with "some fix" there seem to be no encoding issues anymore).

**Comment by stefan-kolb** [comment]
@Siedlerchr  This is on the end of Mr.Dlib? We just show the HTML page?!

**Comment by Siedlerchr** [comment]
Yes, we show the HTML content but doesn't want jorean to rework that interface?

**Comment by stefan-kolb** [comment]
So I guess we cannot fix this?!

**Comment by stefan-kolb** [comment]
Some are rendered correctly for me:
![image](https://user-images.githubusercontent.com/2141507/42635066-454503cc-85e5-11e8-9e50-707fd50f3e78.png)

**Comment by Joeran** [comment]
Mr. DLib has indexed documents from two sources: Sowiport and CORE. The documents from Sowiport often have a wrong character encoding, while the CORE documents should be ok. For now, we cannot do anything about it. However, 

1. We are currently completely re-designing Mr. DLib as we have two new members who will work full time on the project. The new version shouldn't have any encoding problems.
2. Sowiport has terminated its service, and we will remove the documents from our corpus soon. Then the problem should also be gone.

**Comment by stefan-kolb** [comment]
@Joeran Thanks for the clarification! I'll close this as wont fix.
