### ISSUE TITLE
Entry editor: simultaneous moving and renaming of document file?

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#4166]
I believe in some distant past it was possible to use the context menu in the entry editor's file field to simultaneously move a file to the default file folder and rename it. This option has been disappearing a while ago and I wonder whether it is possible to add it again? It was so wonderful

**Comment by ilippert** [comment]
jabref allows for automatic renaming, e.g. using the bibtex citekey as a the filename.
in the current version, I can first use drag& drop to include a local link to the entry's file. then I can right-click and move it to the preferred document folder. and then I can right click (onto the file) again to rename the file (automatically, in my case the bibtex cite key).

I would hope the context menu/right click changes the "move" interaction, maybe with a simple checkbox "do you want the file to be renamed automatically?", and then simultaneously moves and renames the file automatically.

**Comment by tobiasdiez** [comment]
I would simply add a "Move and rename" action in the right-click menu. Should be easiest solution.

**Comment by tobiasdiez** [comment]
Thanks to @upupming, this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by ilippert** [comment]
I tested this for some minutes and it seems to work well. Thanks @upupming!

**Comment by upupming** [comment]
@ilippert  😄 Glad to hear that~

**Comment by tsmithe** [comment]
Is it possible to do this in a batch? For instance, to rename the linked files for multiple entries at once.

**Comment by Siedlerchr** [comment]
Sure,check out quality -> cleanup
There you can execute batch operations for all selected entries

**Comment by tsmithe** [comment]
Thanks @Siedlerchr ! Until just a moment ago, I was stuck on Debian's ancient version 3.8 of JabRef (which didn't seem to have that option). But I finally managed to get 4.3.1 working, and it's just as you say. Thanks for the pointer :-)
