### ISSUE TITLE
Using up and down keys in main table is extremly slow

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#4171]
Even feels like nonresponsive at first.
Afterwards the marking jumps in chunks of ~5 when trying to cycle though the entries very fast.
It feels like the computation of the entries became even slower than on v4.3!

**Comment by DOFfactory** [comment]
Same issue here, overall the new JabRef 4.3.1 is using rather high CPU (i7-7700HQ @ 2.8GHz) averaging around 18-19% when nothing is being done (see attached screenshot).
![jabref](https://user-images.githubusercontent.com/10846169/42409393-1996dfde-81da-11e8-998a-f43751964380.png)

**Comment by stefan-kolb** [comment]
@DOFfactory What java version are you using? Java < 1.8.0_172 produces constant load. See https://github.com/JabRef/jabref/issues/3943.

**Comment by DOFfactory** [comment]
Just an idea, but I wonder what html renderer is JabRef using for the Entry Preview (Gecko, Webkit, something else)? I have edited my preview with some goodies, and I wonder whether this is not the culprit...

**Comment by Siedlerchr** [comment]
We use the default JavaFX web component.
To which preview style are you referring? The html like style? Or are you using one of the CSL ones, e.g. ACM ? 

Could you test the latest Master version? 
Remember to make a backup of your library.

**Comment by DOFfactory** [comment]
Hi @Siedlerchr , I am using my own style that I created to look like [this](https://github.com/jiho/bd-two_columns) style (sorry, coming from BibDesk). I followed the [CustomExport](http://help.jabref.org/en/CustomExports) filters to re-create it, so I wonder that this is causing such a high CPU.

I am on Windows so I am not sure how to test the latest Master version - do you want me to clone the git somewhere? I would appreciate some short how-to, if I may bother you.

**Comment by stefan-kolb** [comment]
You can try the latest build from http://builds.jabref.org/master. It is packaged similar to the release versions.

**Comment by DOFfactory** [comment]
Ok, tested, seems fixed. Although the UI is *ugly*, hope it will be fixed or at least adjustable

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
