### ISSUE TITLE
Pin error prone error checking configuration to certain version

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#4176]
We cannot build old JabRef versions because of error prone always refers to the latest error prone checking rules. That means, a JabRef build from 2016 uses the rules from 2018. Since JabRef 2016 does not follow all rules from 2018, it fails to build.

It is possible to pin the version of the error prone rules:

```
dependencies {
  errorprone 'com.google.errorprone:error_prone_core:2.0.21'
}
```

Maybe, we should do that.

Source: https://github.com/tbroyer/gradle-errorprone-plugin

**Comment by tobiasdiez** [comment]
It is already pinned (if I understand you correctly)
https://github.com/JabRef/jabref/blob/aed7712bcd0ed9661aeb006c8317d54025f6063f/build.gradle#L24
