### ISSUE TITLE
The "Neue Eintrag" dialogue has errors

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4177]
- [+] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.0-dev--snapshot--2018-07-02--master--aed7712bc
Windows 7 6.1 amd64 
Java 1.8.0_172

Steps to reproduce:

1. open the dialogue by Ctrl-N
2. Try to add a DOI identity 
3. Press "erzeugen"
and wait for an indeterminate amount of time

If you waited for several minutes the dialogue cannot be finished either by clicking "Abbrechen" not by clicking the "x" in the title line. Program had to be canceled.

I am not able by Copy and Paste the DOI content of an entry into the "Neuer Eintrag" dialogue!!

**Comment by stefan-kolb** [comment]
Neuer Artikel creates an `@article` entry. Neuer Eintrag opens a dialog for all kinds of entries.
Nevertheless, the new entry dialog hangs in the master.

**Comment by stefan-kolb** [comment]
Refs #4164

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
