### ISSUE TITLE
JabRef 4.3.1 does not terminate

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#4194]
JabRef 4.3.1
Linux 4.15.0-24-generic amd64 
Java 1.8.0_171

Steps to reproduce:

1. open JabRef<br/>for example with the terminal command `java -jar /home/jkalliau/prgm/JabRef/JabRef-4.3.1.jar`
2. close JabRef using the red x-boton in the title bar
3. check in the Systemmonitor if there is still a process like "java"

![screenshot from 2018-07-12 16-18-48](https://user-images.githubusercontent.com/15687581/42639696-f256937c-85f0-11e8-9a4e-f365799a5bda.png)

Java needs more than 10GB:
![screenshot from 2018-07-12 16-18-48detail](https://user-images.githubusercontent.com/15687581/42639878-5369e60a-85f1-11e8-87a1-ce591fd59f34.png)

My log details here:
```log
Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
Opening: /home/jkalliau/Desktop/output.bib
```
```cmd
jkalliau@jkalliau-Z87M-D3H:~$ java -jar /home/jkalliau/prgm/JabRef/JabRef-4.3.1.jar
16:26:18.188 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
16:26:18.529 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/Desktop/output.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
```

**Comment by Siedlerchr** [comment]
Please try the latest Master version

**Comment by JoKalliauer** [comment]
Solved in `JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911`

**Comment by JoKalliauer** [comment]
Since `5.0-dev` contains some bugs (that are relevant to me), I prefer to use JabRef 4 again.

Will this bug be solved in JabRef 4?

**Comment by Siedlerchr** [comment]
Sorry to inform you, but due to a lack of resources (man power) we can only maintain the current development version 5.x as all of our developers are working in their free time on JabRef.
We are working hard to make the 5.x version stable. 
Your issue with the source tab should be fixed very soon, there is already a PR for that issue which however still has to be reviewed.
