### ISSUE TITLE
ebook.de ISBN to BibTeX is down

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4198]
No longer works, e.g `https://www.ebook.de/de/tools/isbn2bibtex?isbn=+0-387-90026-8`. @koppor do you have the contact from these guys?

**Comment by stefan-kolb** [comment]
Refs #4172?!

**Comment by koppor** [comment]
Der Service funktioniert grundsätzlich noch. Beispiele:

https://www.ebook.de/de/tools/isbn2bibtex?isbn=3462050842
https://www.ebook.de/de/tools/isbn2bibtex?isbn=9783734100932

Den Artikel mit der von dir genannten ISBN (978-3-86680-192-9) gibt es bei ebook.de allerdings nicht mehr.

Der Service liefert einen 404 mit dem Response-Text "Not Found" zurück, wenn ebook.de den Artikel nicht (mehr) im Sortiment hat.

Ich vermute deshalb, dass es bei den anderen ISBNs, mit denen du getestet hast, die gleiche Ursache hat.

Du kannst übrigens prüfen, ob es den Artikel bei ebook.de gibt, indem du die EAN/ISBN im Shop unter https://www.ebook.de/de/ in die Suche eingibst (und die Suche abschickst).

**Comment by koppor** [comment]
Is it possible that the fallback to amazon is not working and that that service is down?

Remember: We first try ebook.de. If that is unavailable, we try amazon.

**Comment by stefan-kolb** [comment]
I guess the code also produces a fetcher exception on the 404 of ebook.de so we never query chimbori (as far as I remember).

**Comment by koppor** [comment]
Visit https://bibtex.chimbori.com/ and try the example ISBN: 978-3639174304

Result:

```
@book{9783639174304,
  Author = {},
  Title = {},
  Publisher = {},
  Year = {},
  ISBN = {},
  URL = {}
}
```

**Comment by Siedlerchr** [comment]
The ebook.de fetcher now runs fine again, Maybe a temporary problem. 
@koppor  You know that guy from chimbori fetcher? https://github.com/JabRef/jabref/issues/684#issuecomment-266541507

**Comment by koppor** [comment]
@Siedlerchr Please check your private emails. I CC'd you and tobiasdiez.

**Comment by Siedlerchr** [comment]
Chimbori works again.
