### ISSUE TITLE
I could open two instances of Jabref while the Listening to Port 6050 for external access is checked

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4209]
- [+] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists
JabRef 5.0-dev--snapshot--2018-07-15--master--a44d31668
Windows 7 6.1 amd64 
Java 1.8.0_172

Steps to reproduce:

1. Open Jabref5.0dev.
2. Open Jabref4.1.
3. that wórks and shut not be possible. The checking is obviously not respected.

![grafik](https://user-images.githubusercontent.com/9216487/42757105-02d45dd6-88ff-11e8-9be4-009e367eddcf.png)

There was already an issue about this but I cannot find it within 2018.

**Comment by tobiasdiez** [comment]
Yes, 4.1 grow too old and can longer understand its younger brother 5.0dev. We improved the remote feature but on the way broke backward compatibility, which usually shouldn't be a problem since you normally only have one JabRef version installed.
