### ISSUE TITLE
Word exporter encoding of umlauts

### ISSUE THREAD

**Issue by wielanms** [JabRef/jabref#421]
The word exporter is very nice but following issue remains:

Conversion of Latex umlauts to UTF8 umlauts.

e.g. Oliver Kopp and Tobias Binz and Uwe Breitenb{\"u}cher ....
should get: Kopp, Oliver, Tobias Binz, Uwe Breitenbücher, ....

**Comment by stefan-kolb** [comment]
Confirmed, we need a formatter to remove all LaTex-specific characters from the database.

**Comment by koppor** [comment]
Is it [FormatChars](http://jabref.sourceforge.net/help/CustomExports.php)?

"This formatter converts LaTeX character sequences their equivalent unicode characters and removes other LaTeX commands without handling them."
