### ISSUE TITLE
No visual difference between static and dynamic groups

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#4220]
In current 4.3.1 I don't see a difference between static and dynamic groups. In 3.8.1 dynamic groups where shown in italic font.

**Comment by tobiasdiez** [comment]
I think, we had a discussion about this a few months ago. From the technical side there is no problem in readding a visual distinction between the two modes for a group. However, we couldn't come up with a use case, where the knowledge of the mode is important and thus makes it worthwhile to show it to the user. Why do you want such a visual indication? "It was there in 3.8.1" is not a good enough argument to bring it back ;-).

**Comment by noMICROSOFTbuhtz** [comment]
A use-case is hard to describe here. It depends on how an individal brain looks on informations. ;)
For me it is absolutly different if a groups is created out of a keyword (dynamic) or if I created it static and added entries in their manually.

For me it makes absolutely sens to use different visual styles for that groups. But I miss the words to describe it in an general understandable way. Sorry.

**Comment by noMICROSOFTbuhtz** [comment]
Take it like this: The tree structure in JabRef represtent the think-ways in the brain of a user. Each user is individual as a person, individual in the use-cases and comes from different scientific areas.
For my brian it is absolutly important to see with first view a difference between real groups and dynamic-keyword-groups. ;)

**Comment by tobiasdiez** [comment]
Thanks for the follow-up. I understand that some users (or their brains) find the distinction between dynamic and static groups helpful. However, for most users such a distinction is not helpful and/or they don't understand it (e.g. previously dynamic groups were displayed in italics but this is everything than self-explanatory). Moreover, in my opinion, it is not worth the hassle to add a preference to toggle between a visual distinction on or off. 

However, you can edit the icon and/or the color of the group yourself. Hence, it is very easy for you to introduce a color scheme in which all dynamic groups are say red and all static ones are displayed in blue.

**Comment by noMICROSOFTbuhtz** [comment]
"color scheme"? Can you explain that?

**Comment by tobiasdiez** [comment]
When you edit a group, you can specify a color of the icon (e.g. 0x5eba7dff gives green, see https://www.w3schools.com/colors/colors_hexadecimal.asp?color=5eba7dff). By using colors consistently for dynamic vs static groups you get a color-coded representation of this distinction.

**Comment by noMICROSOFTbuhtz** [comment]
I can specify the color by rgb hex value? This is far away from being ergonomic. I am the user - not a machine.

This is a design-bug. If you offer the freedom to choose color then offer also a color chooser. There is on step missing. So step back (delete the color field) or forward (color picker).

But this wouldn't solve my problem. I don't want to setup the color for each keyword-group again and again. I want to setup the "color for all existing and new in future keyword groups" **one time**.

**Comment by Siedlerchr** [comment]
Pleas be patient. We are all working in our free time on JabRef. The edit and add group dialog will be redesigned when converted to JavaFX. There is already an issue with some ideas how it might look like. Feel free to add your ideas https://github.com/JabRef/jabref/issues/2630

**Comment by noMICROSOFTbuhtz** [comment]
Please stop discussing ressources here. Issues are not about that.
An Issue/BugReport/FeatureRequest is only to find a solution or to document if the core developers would accept patches for something.

An Issue is **NOT**: Fix this now!

Because fo #2630 I would say this is an Issue. Just connect it to #2630 and leave it open to prevent other users open an Issue for the same topic again. Thats all.

Doesn't matter if you fix it now, in five years, me or another person.

**Comment by noMICROSOFTbuhtz** [comment]
#2630
