### ISSUE TITLE
GroupView: (un)fold state not persistent

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#4221]
It looks like JabRef 4.3.1 (stable) and JabRef 5.* (dev) doesn't remeber the (un)fold-state of each group between closing JabRef and starting it again.

I did some more testing about it. It looks like that the folding state is not saved automaticly.
Starting JabRef, modify some folding-states and close JabRef has no effect.
But when you do File -> Save Bib then the folding-state is saved and is persistent to the next start of JabRef.

**Comment by noMICROSOFTbuhtz** [comment]
I updated the first post with more details because I did some tests with the dev version.

**Comment by noMICROSOFTbuhtz** [comment]
I can reproduce the problem with the current 5.* dev version.

**Comment by CyraxSector** [comment]
@Codeberg-AsGithubAlternative-buhtz Could you provide steps to reproduce this issue.Thanks

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
btw: I can still reproduce the Issue.

1. Open JabRef with "open last file on start up" option
2. The current open project is in an unmodified/saved (no * behind the filename).
3. Do some (un)folding of your groups.
4. Close the window via the X sign in the top right corner.
5. Re-open and check the folding-states of the groups. -> Not persistent.

Other way
1. Open JabRef with "open last file on start up" option
2. The current open project is in an unmodified/saved (no * behind the filename).
3. Do some (un)folding of your groups.
4. Press Ctrl+S and you see the "project is saved" message.
5. Close the window via the X sign in the top right corner.
6. Re-open and check the folding-states of the groups. -> Not persistent.

My hint is: When closing the application and the project is in unmodified state the folding-states are not saved. In other words: Changing the folding-states do not brings the project in modified/unsaved state (no * appear behind the filename).

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I am confused. From @igorsteinmacher 's JabRef repo I got some comments about this issue. But now they are gone.

https://github.com/igorsteinmacher/jabref/issues/70#issuecomment-575293848

So who is working on this on which repo and what is the current state?
