### ISSUE TITLE
Ctrl-E to toggle the entry editor

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4222]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.0-dev--snapshot--2018-07-15--master--a44d31668
Windows 7 6.1 amd64 
Java 1.8.0_181

Ctrl-E is the shortcut to open the entry editor. Whereas alt-F4 toggles the internet search on and off, such a feature is not availabe for the ctrl-E, it stays, there is not any key to shut off the entry editor. When working with the keyboard, you still have to use the mouse to stop the entry editor. As you know how to do it, it should be very easy to make also the crtl-e start **and** stop the entry editor.

**Comment by Siedlerchr** [comment]
Normally you should be able to use ESC to close the entry editor and or the current window

**Comment by tobiasdiez** [comment]
Thanks to @razvan05, this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
