### ISSUE TITLE
Cannot edit entry after updating Java

### ISSUE THREAD

**Issue by niels90** [JabRef/jabref#4228]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists
The problem does not exist anymore with JabRef 5 master version

JabRef version 4.3.1 on Windows 10 Java version 8.181

Steps to reproduce:

1. Open JabRef
2. Create a new entry
3. The edit window does not appear automatically
4. It cannot be opened by clicking the new entry or clicking edit entry button

<details>
  <summary>Log File</summary>
  
  ```
  Opening: C:\Users\niels\Dropbox\Research\journal club\Jabref database\database.bib
  ```
</details>

The log file does not report any error.

**Comment by tobiasdiez** [comment]
Since this bug does no longer occurs in the latest development version, I'll close this issue now.
