### ISSUE TITLE
Clean up unsupported entrytype "other" or "conversion dialog" in JabRef 3.0+

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#423]
In JabRef 3.0+, the entry type "other" is not supported any more.
Would you think that it is necessary to add a "conversion dialog" when reading the bib file ?
We can do manual conversion, but perhaps for people with large database this conversion dialog could be convenient ...
Thanks

I tested in the latest build <pre>JabRef-3.1dev--snapshot--2015-11-30--master--2d92f63</pre>
the 
<pre> Unknown entry types will be converted to 'Misc' (was 'Other' before). </pre>
does not work.

**Comment by koppor** [comment]
What do you mean by "does not work"? Why did you close the issue? Could you write some text why you closed it? Did the conversion work for you?
