### ISSUE TITLE
Authors formatting ignored when used several times

### ISSUE THREAD

**Issue by ph0boss** [JabRef/jabref#4235]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists.

JabRef version  <4.3.1> on <fedora 28>

Steps to reproduce:

1. Insert a citation with multiple (more than 3) authors
2. use attached example style and library to generate bibliography
[style and database.zip](https://github.com/JabRef/jabref/files/2225122/style.and.database.zip)
3. In the end you get the first authors formatter rendered correctly (highlighted with green on screenshot), and the second authors formatter just lists them all (highlighted with red on screenshot) 
![screenshot_20180724_230150](https://user-images.githubusercontent.com/19243265/43163170-f4fe0318-8f95-11e8-8a82-130f501daa22.png)

**Comment by vanukkalla** [comment]
I am not sure I understand how the bibliography is supposed to look like. Can you paste an example? I can try to modify the stylefile to match your needs. If you still have the problem.

**Comment by ph0boss** [comment]
Here is an example. These are the requirements for publishing in Russia, Belarus and somewhere else, don't remember exactly (I'm from Belarus).

Willemze R. WHO-EORTC classification for cutaneous lymphomas / R. Willemze // Blood. – 2005. – Vol. 105. – № 10. – P. 3768-3785.

**Comment by ph0boss** [comment]
The citation in the above example should look like this:

M.S. van Kester. A Meta-Analysis of Gene Expression Data Identifies a Molecular Signature Characteristic for Tumor-Stage Mycosis Fungoides / M.S. van Kester **[et al.]** // Journal of Investigative Dermatology. – 2012. – Vol. 132. – № 8. – P. 2050-2059.

There should be an et.al. string according to the style, but it is ignored. It the authors formatter is used only once per citation, then everything is ok. If more than once, then the first formatter is ok, but subsequent are formatted in a weird way. You can see in the first example text marked with red

**Comment by vanukkalla** [comment]
Check, whether this style-file works for you. Right now, it will only display 1 author for the main author list (after the title) and I defined the [et al.] not as et al string but to be inserted after the authors.

NAME
Belarus

JOURNALS
Belarus Journals

PROPERTIES
Title="Used Literature."
IsSortByPosition="true"
IsNumberEntries="true"
ReferenceParagraphFormat="Text body"
ReferenceHeaderParagraphFormat="Heading 2"

CITATION
BracketBefore="["
BracketAfter="]"
BracketBeforeInList=
BracketAfterInList=.
CitationSeparator=", "
UniquefierSeparator=","
GroupedNumbersSeparator="-"
MinimumGroupingCount="3"
FormatCitations="false"
CitationCharacterFormat="Default"
PageInfoSeparator="; "

LAYOUT
article=\format[Authors(FirstFirst,InitialsNoSpace,FullPunc,1,1,EtAl=)]{\author}. \title / \format[Authors(FirstFirst,InitialsNoSpace,FullPunc,1,1,EtAl=)]{\author} <b>[et al.]</b>) // \begin{journal}\journal. - \end{journal}\begin{year}\year. - \end{year}\begin{number}№\number. - \end{number}\begin{pages}P.\format[FormatPagesForHTML]{\pages}.\end{pages}

**Comment by vanukkalla** [comment]
here the jstyle file.

[belarus.modify.zip](https://github.com/JabRef/jabref/files/2388651/belarus.modify.zip)
