### ISSUE TITLE
Groups: Selection lost when unfolding another group

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#4239]
JabRef 4.3.1

Group `A` is selected in the groups view.
Group `B` (on same level as `A`) has subgroups and is currentl folded.
Clicking on the right unfold-symbol of group `B` does correctly unfold it.
**But** the `A` is not longer selected. `B` is selected now.

When I click on an unfold symbol I would expect only that the groups is unfolded - not more. I don't want to select it.
e.g. I want to drag and drop an entry from the currently selcted group `A` to one of the subgroups of group `B`. In that case I have to unfold `B`first of course.

**Comment by noMICROSOFTbuhtz** [comment]
YFI This problem exists in current dev-snapshot (5.*).

**Comment by Siedlerchr** [comment]
We are aware of that.
I already tried to look at that. but it's not that easy from a technical point of view as the row is automatically selected when you click somewhere on that unfold icon.
Probably one has to add a change listener somewhere and reselect the old row.

**Comment by noMICROSOFTbuhtz** [comment]
The problem still appears in the 5.* dev version.

**Comment by Siedlerchr** [comment]
Maybe it could work if one applies a custom FocusModel: https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/FocusModel.html
for the treeview
