### ISSUE TITLE
JabRef 3.0 abnormal display on Windows 10

### ISSUE THREAD

**Issue by AlexanderZ11234** [JabRef/jabref#425]
Any pop-up menu is highly likely to be covered by dark and thus none of the contents can be seen.

For example, the "New bibtex entry" shows
![r 8s t 8v c a se cp](https://cloud.githubusercontent.com/assets/15089574/11496864/f5107b82-984f-11e5-9e9d-be41dfa26c78.png)

**Comment by matthiasgeiger** [comment]
Hi,
can you check whether there are any error in the error console (Help -> show error console) - if so, can you please paste the information here?

Thanks!

**Comment by stefan-kolb** [comment]
Does this only occur in Biblatex mode?

**Comment by AlexanderZ11234** [comment]
Hi,

No error information there. Only file history in 'Log', 'No exceptions  
have occurred.' in 'Exceptions' and nothing in 'Output'.

On Tue, 01 Dec 2015 17:26:31 +0800, Matthias Geiger  
<notifications@github.com> wrote:

>
> Hi,
> can you check whether there are any error in the error console (Help ->  
> show error console) - if so, can you please paste the information >here?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub.
>
> No virus found in this message.
> Checked by AVG - www.avg.com
> Version: 2016.0.7227 / Virus Database: 4477/11097 - Release Date:  
> 12/01/15



-- 
Kind regards,

Alexander Zeng

**Comment by koppor** [comment]
Just resize the window a view times, then you should see everything again. Is some sort of graphics driver issue. What graphics card do you have and which driver version is installed?

Refs https://github.com/JabRef/jabref/issues/184#issuecomment-147255863

**Comment by AlexanderZ11234** [comment]
It happens no matter the box before 'BibLaTeX' is checked or not.

On Tue, 01 Dec 2015 17:40:59 +0800, Stefan Kolb <notifications@github.com>  
wrote:

>
> Does this only occur in Biblatex mode?
>
> —
> Reply to this email directly or view it on GitHub.
>
> No virus found in this message.
> Checked by AVG - www.avg.com
> Version: 2016.0.7227 / Virus Database: 4477/11097 - Release Date:  
> 12/01/15



-- 
Kind regards,

Alexander Zeng

**Comment by koppor** [comment]
Please report your graphics card, your graphics driver, and your Java version.

Mine is Nvidia NVS 4200M, driver 327.02, and Java 1.8.0_66. And I have issues, too.

**Comment by koppor** [comment]
Maybe this will automatically be solved via #113.

**Comment by stefan-kolb** [comment]
Any updates on this? Can you try a newer version from http://builds.jabref.org/master/?

**Comment by AlexanderZ11234** [comment]
Thanks for the updates.

The problem has been solved since an update to version 3.2. But I do not  
know how to post that outcome now. Can you help to make a "solved" or  
alike mark to the case #425?

On Thu, 07 Apr 2016 02:49:41 +0800, Stefan Kolb <notifications@github.com>  
wrote:

>
> Any updates on this? Can you try a newer version from  
> http://builds.jabref.org/master/?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub



-- 
Kind regards,

Alexander Zeng
