### ISSUE TITLE
Something wrong with Chinese support.

### ISSUE THREAD

**Issue by GongSiqiu** [JabRef/jabref#4262]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version JabRef 4.3.1
Linux 4.15.18-041518-generic amd64 
Java 1.8.0_171 on Ubuntu 18.04 

Steps to reproduce:

1. Options ->Preference ->Language-> Simplified Chinese
2. Appearance -> General ->Override default font  settings
3. OK

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
![bug](https://user-images.githubusercontent.com/40697840/44000140-1f0fec50-9e4d-11e8-8611-18c323238767.png)

</details>

**Comment by Siedlerchr** [comment]
Please test the latest master from http://builds.jabref.org/master/ 
Please make a backup before testing.
On Windows 10 I cannot confirm the behavior

And also with #4253, currently the preferences dialog gets ported to JavaFX as well and I did a quick test with the version there and works fine

![grafik](https://user-images.githubusercontent.com/320228/44000899-75ca95a6-9e28-11e8-8dc2-3b65102310ac.png)

**Comment by GongSiqiu** [comment]
I have tested the latest master. It works well, but makes no sense. Because although I choose Override default font settings, I can't change the size of the font.
![bug2](https://user-images.githubusercontent.com/40697840/44008214-6d7ec268-9ed3-11e8-9f1e-a925139b4cfa.png)

**Comment by tobiasdiez** [comment]
That you cannot edit the font size (on some Linux versions) was reported before and will hopefully be fixed as part of #4253.

**Comment by GongSiqiu** [comment]
Thank you
