### ISSUE TITLE
Journal or Journaltitle

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#4269]
JabRef 4.3.1 on Windows 10.

When creating an new "Article" the first tab shows "Journal" and "Journaltitle" also when BibLaTex is used as default format.

But only one of them is valid in BibLaTex. So the edit dialog should do a decission here and should only offer one of them.

**Comment by Siedlerchr** [comment]
This was done on purpose because often journal  is the only field that is missing for bibtex compatibility @koppor can tell you more about the reason.

**Comment by noMICROSOFTbuhtz** [comment]
But I don't need bibtex compatibility because I setup BibLaTeX als default bib format.

**Comment by tobiasdiez** [comment]
I'll also find these two fields unnecessary. By default, the journal field should be shown only when it is not empty (similarly for `month` and the other old fields). If someone really wants to use Biblatex in Bibtex compatibility mode, then she can still edit the shown fields..

**Comment by DOFfactory** [comment]
Any update on this? So frustrating to always update the fields manually ...

**Comment by Siedlerchr** [comment]
@DOFfactory  When the issue is fixed it will be closed. So please be patient. We are all working in our free time in JabRef. Of course you are free to contribute and fix the issue.

**Comment by DOFfactory** [comment]
Sorry, my comment was rather an inquiry, whether there is any progress with this issue. I was just about to submit a similar ticket out of frustration, when I noticed that it has been already submitted. Sorry again.

**Comment by koppor** [comment]
@MartinKarim. You have ideas?

Thing is: Handling of field aliases in Biblatex. (journal == jounrrnaltile). Some users stick to bibtex (journaltitle), some to biblatex (journal is recommended). Mostly, you get bibtex from the web, but modern users convert all to biblatex.

**Comment by DOFfactory** [comment]
@koppor you are correct. I purposely selected Biblatex database in the settings instead of Bibtex, thus I expect that the journal field should be converted automatically to journaltitle (even after import from the web). It is simply ineffective to always click to the separate tab for checking (and copying) the journal title.

**Comment by MartinKarim** [comment]
Same as @DOFfactory I also think that fields with the same purpose and expected content should be automatically converted into each other when changing from BibTeX to Biblatex or vice versa or when a reference is imported. This might at least be the expected/desired behavior in most cases. If someone wants to keep the 'journal' field, they would still be able to create it themselves.

**Comment by DOFfactory** [comment]
Bump

**Comment by koppor** [comment]
@tobiasdiez Can we just remove "journaltitle". I think, it is annoying. We can even convert the field to "journal" during import. No need to convert "journal" to "journaltitle" when converting to biblatex.

Maybe something for #jabcon?

**Comment by Fminorelli** [comment]
With the implementation of the new interface, in version 5.x, this issue is no longer reproducible. Said that, it should be closed.
