### ISSUE TITLE
"Cannot open entry-edit-window issue" not a bug, just minimized window. Enhancement proposal

### ISSUE THREAD

**Issue by dostaji4** [JabRef/jabref#4279]
Release 4.3.1. Windows 10. 

I've just went through several installations of either this or older releases because I could't open edit window. 
I've now realized, that the edit window has just had no height (was completely minimized). It was not a pleasant useer experience and I would suggest adding a **minimal height limit to the entry edit window**.

**Comment by tobiasdiez** [comment]
Thanks for your suggestion. This is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by dostaji4** [comment]
Hey, I'm glad I helped even with such a minor contribution. However, I'm
not able to check the latest dev. version, because, for some unknown
reason, I'm getting *This site can’t be reached  ERR_CONNECTION_TIMED_OUT. *

All the best,
Jiri

*Jiří Dostál*
