### ISSUE TITLE
Saving an auto downloaded full-text document destroys the file link

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#428]
Saving to `C:\...` removes the C and destroys the file link.

**Comment by simonharrer** [comment]
I thought relative links are preferred?

**Comment by stefan-kolb** [comment]
Hm, it results in `:\..` which is never a valid relative file link?

**Comment by stefan-kolb** [comment]
Also what if not all PDF reside in the main folder set in the preferences.

**Comment by koppor** [comment]
Our relative file link thing seems to be wrong. Should we use [Apache Commons Lang](https://commons.apache.org/proper/commons-lang/)? Or does Guava offer a similar functionality?

**Comment by stefan-kolb** [comment]
@JabRef/developers Hm cannot reproduce this anymore. Anybody of you can?

**Comment by koppor** [comment]
Symptoms: There exists a D and E drive. Root directory probably wasn't set.
