### ISSUE TITLE
Trim Url field in Entry editor

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4288]
Feature request/bug report from the Forum:

1. Copy the following in the source tab of an entry
2. Try to open the url
3. Explorer is opened (on windows)

Solution would be to trim the url field automatically

```
URL = {
https://doi.org/10.1175/1520-0469(2003)060 1<1655:TOSOCC>2.0.CO;2
},
```

http://discourse.jabref.org/t/jabref-cannot-identify-the-url-if-there-is-space-between-the-url-and-opening-and-closing-braces/1314

**Comment by stefan-kolb** [comment]
I thought opening and closing spaces were automatically trimmed for each field before?

**Comment by adityaveda** [comment]
Can't seem to pinpoint where URL fields are to be trimmed. 
The only method that seems to deal with URLs is in ModsExporter.java called 
addURL. I added code to trim URL but doesnt reflect in the application. 
Does anyone know what I am missing?

**Comment by Siedlerchr** [comment]
Hi,
The right place is in the Entry Editor. I saw that there is already a paste handler for the the URL field in the fieldseditors class.   I think it should be sufficient to create a copy of the  RemoveNewlinesFormatter which only removes newlines before the first opening brace and the last closing brace and then add this as paste handler to the code area

**Comment by tobiasdiez** [comment]
Thanks to @Songyu-Wang, this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
