### ISSUE TITLE
create entry by DOI

### ISSUE THREAD

**Issue by yuejuny** [JabRef/jabref#4292]
JabRef 4.3.1
Windows 7 6.1 amd64 
Java 1.8.0_171

Steps to reproduce:

1. ID-based entry generator
2. choose ID type: DOI
3. paste 10.1073/pnas.1718850115 and click "Generate".
4. Error while fetching from DOI. Connection error.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Seems to be a temporary problem. In the current master it works fine.
You can try out that version from here https://builds.jabref.org/master/
It is advised to make a backup of your library.
