### ISSUE TITLE
Main table cut off in the width

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#4294]
JabRef 5.0-dev--snapshot--2018-08-23--master--add2b0b94
Windows 10 10.0 amd64 
Java 1.8.0_181

When double clicking on an entry, to open the editor underneath, the entry table automatically changes width, and part of it gets cut off in the width left and right (jabref seems to think that its window is much larger than it is). The part of the main table that disappears is unreachable. This effect is especially obvious when the groups interface is open. Jabref at this point becomes unusable and restart is the only option.  My screensize is a rather unusual 1200x1920 (portrait screen), but never had any problems with this in the past with Jabref.

**Comment by tobiasdiez** [comment]
Can you please make a screenshot when the problem occurs and upload it here. Thanks.

**Comment by lc9275** [comment]
Here is how it looks when Jabref starts: (all is ok).

![before](https://user-images.githubusercontent.com/3605301/44708702-16e2f380-aaa8-11e8-8685-fdb0f6920eac.png)

Now after an item is double-clicked. Notice that also part of the menu on top is cut off.

![after](https://user-images.githubusercontent.com/3605301/44708707-19454d80-aaa8-11e8-8902-bda23650f065.png)

**Comment by Siedlerchr** [comment]
Yes, I also can confirm this. It happens when you do a double click .Windows 10 here.

**Comment by Siedlerchr** [comment]
If you do a double click on the title bar again so that JabRef goes fullscreen, it looks again normal
![grafik](https://user-images.githubusercontent.com/320228/44715515-4d286f00-aab8-11e8-8649-e6f0a9a58e91.png)

After double click on title bar

![grafik](https://user-images.githubusercontent.com/320228/44715528-51548c80-aab8-11e8-9639-66e6f44e6344.png)
