### ISSUE TITLE
Import window freezes JabRef (Mac OS)

### ISSUE THREAD

**Issue by Dana-L** [JabRef/jabref#4296]
JabRef version 4.3.1
 on Mac OS X 10.13.6 x86_64 
Java 1.8.0_181

Steps to reproduce:

1. File --> "Import into current library" (command key + I)
2. Select a .bib file
3. "Open"
4. JabRef freezes. The import window never closes, and I have to "Force Quit".

<details>

I have the same problem as in https://github.com/JabRef/jabref/issues/3997, titled "Import window freezes jabref".

I haven't used JabRef for a while, and previously, this option worked fine. So I guess it is related to a recent version update.

The reply to #3997 was:
"This is a linux problem with the Look and Feel. Try switching to another Look and Feel in the Options."
I am not a programmer and I do not understand the solution suggested in your reply to #3997, for the linux system. Besides, I don't know if this is a valid solution for Mac OS, too. Can you please suggest a solution for Mac OS users who are not linux experts ?

  <summary>I cannot provide a log file because JabRef freezes and must be killed by "Force Quit".</summary>
  
<!--  ```
  Paste an excerpt of your log file here
  ```
-->

</details>

**Comment by Siedlerchr** [comment]
Hi first of all try to uninstall JabRef then try out the latest development version from http://builds.jabref.org/master/
And see also the FAQ http://help.jabref.org/en/FAQosx

**Comment by Dana-L** [comment]
Hello, 
Thank you for your answer. 

I uninstalled JabRef and installed instead your latest development version:

JabRef 5.0-dev--snapshot--2018-08-24--master--f43b9c7e8
Mac OS X 10.13.6 x86_64 
Java 1.8.0_181

However, I experience exactly the same problem in this new version:

File --> Import & Export --> Import into current library ==> JabRef freezes
                                        --> Import into new library ==> Works fine

**Comment by Siedlerchr** [comment]
Thanks for the clarification.  I could reproduce this issue now under Windows, too.

**Comment by Siedlerchr** [comment]
Hi, 
could you please test if this version fixes the issue for you? My tests under Windows were positive:
https://builds.jabref.org/fiximportfreeze/
Be aware that it could be possible that the import inspection window is hidden somewhere

**Comment by Dana-L** [comment]
Thank you, the "Import into current library" works fine in the newest version:
JabRef 5.0-dev--snapshot--2018-08-28--fiximportfreeze--a274b40e2
Mac OS X 10.13.6 x86_64 
Java 1.8.0_181
