### ISSUE TITLE
JabRef 3.0 - Websearch - Fetch ArXiv.org error

### ISSUE THREAD

**Issue by lecc0r** [JabRef/jabref#430]
I've just installed the latest JabRef version and tested the web search function  the available search machines. I have entered an entire phrase into the search field. Now an error message for every single word in that particular phrase pops up in a 15 s interval from.
"Fetch ArXiv.org": 
An Error occurred while fetching From OAI2 source (.....): 
Malformed identifier `oai:arXiv.org:WORD'
Note: A full text search is currently not supported for Fetch ArXiv.org

while WORD is replaced every time by the current search word.

Problem persists even after I close and re-open JabRef. It stops once it is done looking up every word of that phrase.

**Comment by oscargus** [comment]
The problem is that search is not supported, you can only fetch entries based on identifiers.

**Comment by Braunch** [comment]
Could this be closed?

**Comment by lecc0r** [comment]
Yes!
