### ISSUE TITLE
Jabref 5.0 dev gets stuck on 'title = {Chapter 138 - {PACAP}},'

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4301]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.0-dev--snapshot--2018-08-24--master--f43b9c7e8
Windows 7 6.1 amd64 
Java 1.8.0_181

Steps to reproduce:

1. I saved (since I have not seen Jabfox functional for a while) https://doi.org/10.1016/B978-0-12-385095-9.00138-X to Zotero and exported to Biblatex format
2. the resulting bib-file could be loaded into jabref
3. however, when trying to remove the "Chapter 138 - {" jabref get stuck and can only be closed by clicking the (x) in the title bar.

I ask already in the Zotera forum to skip these nested braces. However, JabRef 5.0 should be able to deal with the deletion, in 4.1 a message appeared that the file could not be saved since braces donot match. I could after that remove the endbraces and save the file. 5.0 just stopped working.

**Comment by bernhard-kleine** [comment]
this is almost a copy of #4256

**Comment by retorquere** [comment]
Zotero should not skip these nested braces. These nested braces are an entirely normal way to preserve capitalization for proper names.

**Comment by bernhard-kleine** [comment]
This I have realized in the meantime. Then there is something fishy with Jabref dealing with deletion of an open brace. The solutuion in version 4.1 was better.

**Comment by Siedlerchr** [comment]
Is this error still present? If I recall this, the behaviour has been improved.

**Comment by bernhard-kleine** [comment]
@Siedlerchr This can be closed. I tested just now and removing the first brace or the second showed a formatting error which is normal, but the program did no longer stop working. Thanks for the improvement.
