### ISSUE TITLE
Disable rename when file has already right name

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4306]
Entry editor > File > Right click > "Rename" asks to "Overwrite the existing file" if the generated name is the same as the original one. That's a bit confusing. Better: just disable the option if the file already has the correct name.

Same applies to "Move" and "Rename and move"

**Comment by Arbalest007** [comment]
Is anyone working on this one? If not can I see if I can fix it?

**Comment by tobiasdiez** [comment]
@Arbalest007 Feel free to work on this issue! Also have a look at our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and feel free to drop by in our [developer chat](https://gitter.im/JabRef/jabref) if you have questions!

For this issue, have a look at org.jabref.logic.externalfiles.LinkedFileHandler, which provides the method `getSuggestedFileName` that gives you the new file name. Essentially, it is enough to add a check in org.jabref.gui.fieldeditors.LinkedFilesEditor#createContextMenuForFile whether the suggested file name coincides with the current file name.

**Comment by Arbalest007** [comment]
Awesome @tobiasdiez! I'll get to work on it,
