### ISSUE TITLE
Can't permanently integrate non-default jstyles into Jabref (V 4.3.1)

### ISSUE THREAD

**Issue by PaulD02** [JabRef/jabref#4308]
Can integrate a personal jstyle into Jabref and create the desired reference list in Libreoffice, but can’t get it to integrate permanently in Jabref. _Tools -> OpenOffice/LO connection -> Select Style -> + Button -> Add style file_ works fine but after rebooting Jabref the style isn’t available anymore in Jabref and I have to add the file again.

I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.3.1 on Windows 10 64bit

**Comment by antesaj** [comment]
Is it necessary for `loadExternalFiles()` within StyleLoader.java (org.jabref.logic.openoffice) to check for validity? Styles are checked for validity prior to being placed into **externalStyles** i.e. `addStyleIfValid(String filename)`.

External styles are set after each addition in `storeExternalStyles()` which sets the external styles list within an instance of OpenOfficePreferences.

Where in the application are current OpenOfficePreferences loaded upon startup?

**Comment by Siedlerchr** [comment]
@antesaj  Thanks for your interest, but this is kind of fixed now as I am reworking the whole dialog to javafx and fixed that issue #4341

**Comment by antesaj** [comment]
Got it, great. Well I had fun looking into it anyway xD.

**Comment by Siedlerchr** [comment]
There are a couple of other issues that need investigation. Maybe you could take a look at them?

**Comment by antesaj** [comment]
Yes, of course. I've been looking for a good open source Java project to get involved with. I'll browse through the issues; any in particular you have in mind?

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
