### ISSUE TITLE
Preview window copy not working properly.

### ISSUE THREAD

**Issue by dnstarostin** [JabRef/jabref#4310]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 

Steps to reproduce:

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by dnstarostin** [comment]
Jabref 3.4.1
1. Open Preview window
2. Copy the formatted entry
3. Paste the formatted entry to a text editor
4. Get the bibtex-formatted entry @book{} etc. and not the formatted entry.

**Comment by LinusDietz** [comment]
I guess you mean JabRef 4.3.1?

I'm not quite sure from your description what's exactly the problem. Can you maybe clarify with an annotated screenshot?

**Comment by dnstarostin** [comment]
Thank you for answering. Jabref 4.3.1. First screenshot is the application
with the Preview window text selected, then I copy and paste the selected
text (Cmd+C Cmd+V since I am on a Mac), and the second screenshot is the
contexts of the buffer which gets pasted in a text editor.

вс, 2 сент. 2018 г. в 2:06, Linus Dietz <notifications@github.com>:

**Comment by dnstarostin** [comment]
Just figured it out: Shift-Cmd-C copies the whole preview window. I have
modified the preview format to my specifications, so it all works now.
Thanl you!

вс, 2 сент. 2018 г. в 6:30, Dmitry Starostin <starostin.dmitry@gmail.com>:
