### ISSUE TITLE
Timerresolution and Energy Efficiency

### ISSUE THREAD

**Issue by JohannesTimm** [JabRef/jabref#4318]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists
not yet testet the latest version, since I need to finish my thesis first

JabRef version 4.3.1 on Windows 7 x64 

Steps to reproduce:

1. ...Start Jabref
2. ...run powercfg -ENERGY 
3. ...result is that the global wakeup timer of Windows is reported to be lowered, which I suppose is unecessary most of the time. Think about the usecase when jabref is just ideling in the background. Furthermore it wastes a lot of energy ans thus battery life, since all CPU cores (on Windows 7) fire up each time the timer calls. 
Solution: only increase the timer, when needed and reset it afterwards. If it is a java related problem set an environment variable that stops this behavior (or make it user changable)

Exerpt from my powercfg output in german:
<details/>
Plattform-Zeitgeberauflösung:Plattform-Zeitgeberauflösung
Die standardmäßige Plattform-Zeitgeberauflösung beträgt 15,6 ms (15625000 ns) und sollte immer dann verwendet werden, wenn sich das System im Leerlauf befindet. Wenn die Zeitgeberauflösung erhöht wird, sind die Technologien zur Prozessorenergieverwaltung möglicherweise nicht wirksam. Die erhöhte Zeitgeberauflösung kann auf eine Multimediawiedergabe oder Grafikanimationen zurückzuführen sein.
Aktuelle Zeitgeberauflösung (100-ns-Einheiten) 	10000
Maximale Zeitgeberperiode (100-ns-Einheiten) 	156001
Plattform-Zeitgeberauflösung:Ausstehende Zeitgeberanforderung
Von einem Programm oder Dienst wurde eine Zeitgeberauflösung angefordert, die kleiner als die maximale Zeitgeberauflösung der Plattform ist.
Angeforderter Zeitraum 	10000
ID des anfordernden Prozesses 	6032
Pfad des anfordernden Prozesses 	\Device\HarddiskVolume3\Program Files\JabRef\JabRef.exe

</details>

**Comment by tobiasdiez** [comment]
Thanks for you report. Sadly, this is a [Java-intern bug](https://bugs.openjdk.java.net/browse/JDK-8164438) and currently no known workaround exist. Hence, there is nothing we can do about it from our side. Sorry.
