### ISSUE TITLE
At closed Jabref remains open in the Task Manager

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4321]
- [ +] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists
JabRef 5.0-dev--snapshot--2018-09-06--docbookfive--9ea5747f1
Windows 7 6.1 amd64 
Java 1.8.0_181

Steps to reproduce:

1. Shut down Jabref by right clicking the Jabref button in the taskbar, select "close window".
2. JabRef is closed.
3. Installation of another Jabref failed because it was not completely stopped as judged by the task manager. This is certainly an error.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
I could not reproduce this. Windows 10. It might take some time until all threads are stopped. But generally it works.

**Comment by DOFfactory** [comment]
Yes. I can confirm this, especially with v4.3.1. 

It happens on ~10% of the cases. Windows 10.

**Comment by AEgit** [comment]
JabRef 5.0-dev--snapshot--2018-10-28--master--05047f32a
Windows 10 10.0 amd64 
Java 1.8.0_191

I encountered this problem as well, if a previous JabRef version was open, then closed and then the installation of a new JabRef version was attempted.

My workaround was to just restart my system and to then run the installation, without having opened and closed the older JabRef version before the installation.

**Comment by Siedlerchr** [comment]
Could you please test with the latest version? I can no longer reproduce this.
When I start it from terminal java -jar JabRef.jar do sth and then exit by clicking on the x on the window right top JabRef shuts down correctly. It takes a couple of seconds until all Threads are stopped, but then it works fine.

**Comment by sanjayankur31** [comment]
Confirming that it doesn't happen with the dev snapshot here either: JabRef-5.0-dev--snapshot--2018-11-02--master--611e35a6b.jar

With the current stable release (4.3.1), it doesn't exit on quit. The processes still hang around and must be killed manually.

**Comment by Siedlerchr** [comment]
Okay, thanks for confirming that it works @sanjayankur31  Due to a lack of resources we only maintain the latest version. Therefore bugs should always be tested/confiremd with the latest snapshot, as they might already be fixed.

**Comment by DOFfactory** [comment]
Hm, thanks @jeremylea for the feedback. Unfortunately, I have disabled the telemetry and anonymous statistics, and rarely I still experience the aforementioned issue. Therefore, I am afraid, your solution, although it might be on the right path, does not fully resolve the issue.
