### ISSUE TITLE
Jabref 5.0-dev UI can't resize in Debian GNU/Linux testing (buster)

### ISSUE THREAD

**Issue by xiaodongcentury** [JabRef/jabref#4322]
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version <JabRef 5.0-dev--snapshot--2018-09-06--master--6c5bc563f> on <Debian GNU/Linux testing (buster), Linux 4.17.0-3-amd64 amd64, Java 1.8.0_181>

Steps to reproduce:

1. Open Jabref. java -jar JabRef 5.0-dev--snapshot--2018-09-06--master--6c5bc563f. 
![image](https://user-images.githubusercontent.com/20276890/45192291-0f76d380-b27a-11e8-84ef-f19d2b0cb491.png). After google "Gtk-Message", I installed "libatk-bridge2.0-*, the warning was persistent.
![image](https://user-images.githubusercontent.com/20276890/45192538-7b0d7080-b27b-11e8-9906-4a48120c9285.png)
2. Now let's check JabRef main UI,
![image](https://user-images.githubusercontent.com/20276890/45192801-24089b00-b27d-11e8-804e-03816a7336ed.png)
and the "Option" > "Preferences" panel, for example,
![image](https://user-images.githubusercontent.com/20276890/45192878-a4c79700-b27d-11e8-9a7e-d949d33ff186.png)
obviously, the entire window is cut off, the "OK" button is invisible, though it actually exist.
3. Again, I install the stable version, JabRef-4.3.1.jar, open it as previously. Sadly, the warning is persistent.
![image](https://user-images.githubusercontent.com/20276890/45193326-07219700-b280-11e8-9374-e17da315dd53.png)
But, the preference panel was normal.
![image](https://user-images.githubusercontent.com/20276890/45193421-78f9e080-b280-11e8-9bad-cdfa9cc62124.png)
My question is,
1) If i want to use dev version, what should i do to avoid the "Gtk-Message", because i belive the problem i encounter is arised by module "atk-bridge", though the OS is actually installed.
2) or i just use the stable version, and wait for the newer stable version.

Many thanks!

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Hi, it may be a problem that the correct 64bit libs are missing, after a quick google search I found this issue which refers to ubuntu but maybe it helps here as well:
https://askubuntu.com/a/769033

**Comment by xiaodongcentury** [comment]
Thanks!
After i install "libatk-adaptor", the Gtk-Message warning is missing, so i am no longer put the screenshot.
But the second problem is persistent.
![image](https://user-images.githubusercontent.com/20276890/45223607-47b5fa80-b2ea-11e8-9084-f0f0fd069e29.png)

**Comment by Siedlerchr** [comment]
Ah yes, I can reproduce this under Windows, too. The buttons vanish on resize. I have just created a quick fix which should resolve this.

**Comment by xiaodongcentury** [comment]
Thanks , the latest version (2018-09-07) works!!!

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
