### ISSUE TITLE
JabRef stops responding for x64 Windows

### ISSUE THREAD

**Issue by orxshi** [JabRef/jabref#4332]
I used JabRef-5.0 on Ubuntu and x32 Windows 7 with no problem. But on x64 Windows 10, JabRef-5.0 keeps crashing after doing some operations such as paste a bibtex or remove an entry from a group. My java version is up to date (1.8.0_181). To note, JabRef-4.0 was working OK on the same x64 Windows. I tried the jar as well and below is the output.

> java.lang.IllegalStateException: Not on FX application thread; currentThread = JabRef CachedThreadPool                                                                                                                                               at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279) ~[jfxrt.jar:?]                                                                                                                                                              at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) ~[jfxrt.jar:?]                                                                                                                                        at javafx.scene.Parent$2.onProposedChange(Parent.java:367) ~[jfxrt.jar:?]                                                                                                                                                                    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113) ~[jfxrt.jar:?]                                                                                                                                    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108) ~[jfxrt.jar:?]                                                                                                                                    at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575) ~[jfxrt.jar:?]                                                                                                                                 at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204) ~[jfxrt.jar:?]                                                                                                                   at com.sun.javafx.scene.control.skin.LabelSkin.handleControlPropertyChanged(LabelSkin.java:49) ~[jfxrt.jar:?]                                                                                                                                at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197) ~[jfxrt.jar:?]                                                                                                             at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55) ~[jfxrt.jar:?]                                                                                                at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89) ~[jfxrt.jar:?]                                                                                                                                                  at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182) ~[jfxrt.jar:?]                                                                                                                      at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]                                                                                                                                    at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103) ~[jfxrt.jar:?]                                                                                                                                at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110) ~[jfxrt.jar:?]                                                                                                                                          at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144) ~[jfxrt.jar:?]                                                                                                                                                  at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49) ~[jfxrt.jar:?]                                                                                                                                                   at javafx.beans.property.StringProperty.setValue(StringProperty.java:65) ~[jfxrt.jar:?]                                                                                                                                                      at javafx.scene.control.Labeled.setText(Labeled.java:145) ~[jfxrt.jar:?]                                                                                                                                                                     at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:199) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                              at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:195) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                              at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:179) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                              at org.jabref.gui.JabRefFrame.output(JabRefFrame.java:1025) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                                 at org.jabref.gui.importer.actions.OpenDatabaseAction.openTheFile(OpenDatabaseAction.java:200) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                              at org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openFiles$2(OpenDatabaseAction.java:174) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]                                                                                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]                                                                                                                                                          at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]                                                                                                                                                                                17:21:25.467 [JabRef CachedThreadPool] INFO  org.jabref.logic.importer.OpenDatabase - Opening: C:\Users\Javanshir\Dropbox\MyLibrary\bibtex\soviet\soviet.bib                                                                                 17:21:25.635 [JabRef CachedThreadPool] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JabRef CachedThreadPool,5,main]                                                                                     java.lang.IllegalStateException: Not on FX application thread; currentThread = JabRef CachedThreadPool                                                                                                                                               at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279) ~[jfxrt.jar:?]                                                                                                                                                              at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) ~[jfxrt.jar:?]                                                                                                                                        at javafx.scene.Parent$2.onProposedChange(Parent.java:367) ~[jfxrt.jar:?]                                                                                                                                                                    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113) ~[jfxrt.jar:?]                                                                                                                                    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108) ~[jfxrt.jar:?]                                                                                                                                    at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575) ~[jfxrt.jar:?]                                                                                                                                 at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204) ~[jfxrt.jar:?]                                                                                                                   at com.sun.javafx.scene.control.skin.LabelSkin.handleControlPropertyChanged(LabelSkin.java:49) ~[jfxrt.jar:?]                                                                                                                                at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197) ~[jfxrt.jar:?]                                                                                                             at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55) ~[jfxrt.jar:?]                                                                                                at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89) ~[jfxrt.jar:?]                                                                                                                                                  at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182) ~[jfxrt.jar:?]                                                                                                                      at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]                                                                                                                                    at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103) ~[jfxrt.jar:?]                                                                                                                                at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110) ~[jfxrt.jar:?]                                                                                                                                          at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144) ~[jfxrt.jar:?]                                                                                                                                                  at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49) ~[jfxrt.jar:?]                                                                                                                                                   at javafx.beans.property.StringProperty.setValue(StringProperty.java:65) ~[jfxrt.jar:?]                                                                                                                                                      at javafx.scene.control.Labeled.setText(Labeled.java:145) ~[jfxrt.jar:?]                                                                                                                                                                     at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:199) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                              at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:195) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                              at com.jfoenix.controls.JFXSnackbar.show(JFXSnackbar.java:179) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                              at org.jabref.gui.JabRefFrame.output(JabRefFrame.java:1025) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                                                                 at org.jabref.gui.importer.actions.OpenDatabaseAction.addNewDatabase(OpenDatabaseAction.java:278) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                           at org.jabref.gui.importer.actions.OpenDatabaseAction.openTheFile(OpenDatabaseAction.java:256) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                              at org.jabref.gui.importer.actions.OpenDatabaseAction.lambda$openFiles$2(OpenDatabaseAction.java:174) ~[JabRef-5.0-dev--snapshot--2018-09-11--master--4c3e520a3.jar:?]                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]                                                                                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]                                                                                                                                                          at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
