### ISSUE TITLE
The cleaning of non-Bibtex conforming has an unnecessary additional step.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4343]
I have used earlier 4.1 to make authors/editors conform to Bibtex standards. It is at the moment not possible to do so with the latest dev version since that chokes on missing dots in the author field

- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JJabRef 4.1
Windows 7 6.1 amd64 
Java 1.8.0_181

Steps to reproduce:

1. Open Jabref 4.1 and select an entry with is not conforming to Bibtex Standard for missing dots e.g.
2. Go to the author field and right click and choose "Normalize to Bibtex name format"
3. with the example of 
`> Hobson, S-A and Bacon, A and Elliot-Hunt, C R and Holmes, F E and Kerr, N C H and Pope, R and Vanderplank, P and Wynick, D`
I arrive at:
`Hobson, S.-A. and Bacon, A. and Elliot-Hunt, C.  R. and Holmes, F.  E. and Kerr, N.  C.  H. and Pope, R. and Vanderplank, P. and Wynick, D.`

which is still not conforming to Bibtex name format

4. I need an additional right click and normalizing to achieve the Bibtex name format:
`Hobson, S.-A. and Bacon, A. and Elliot-Hunt, C. R. and Holmes, F. E. and Kerr, N. C. H. and Pope, R. and Vanderplank, P. and Wynick, D.`

This additional step in my opinion is superfluous. The program should be able to do multiple steps without user input. 

(edit: double spaces are not properly shown)

**Comment by bernhard-kleine** [comment]
I noticed also the \~n (for ñ ) is not recognized as a valid latex command.

**Comment by Siedlerchr** [comment]
Normally that should be also reachable via Quality Cleanup.

**Comment by tb77phd** [comment]
I tried this in 4.3.1 and the issue is there, too. Normalizing once does indeed add an extra space after adding a dot, so one has to do the normalization a second time.

**Comment by tobiasdiez** [comment]
Whats the difference between the second and third version of the example string?

**Comment by bernhard-kleine** [comment]
In the second version there are a couple of double spaces which are removed in the third version. Unfortunately this double spaces are removed html of this page, even they are marked as code. Maybe you could raise a complain to the webmaster.

**Comment by LinusDietz** [comment]
I'm not sure if we can fix this.
