### ISSUE TITLE
Jabref 4.3.1 Bibtex key generation on Cmd-G (OsX) does not insert ':' between last name and date despite setting

### ISSUE THREAD

**Issue by dnstarostin** [JabRef/jabref#4344]
Cmd-G or Cmd-S on Jabref for OsX generate key without the ':' despite it being set in Options/Preferences/Bibtex key generator.

**Comment by Siedlerchr** [comment]
Another issue I just noticed: Corporate authors are ignored as well. e.g. {JabRef} and date 2018 becomes only 2018.
Mabye related to #4152

**Comment by Siedlerchr** [comment]
@dnstarostin  In Preferences -> General there is a checkbox "Enfocre legal chars in genereated keys".
If this is checked the colon will be dropped from the key. If you disable it, it works fine.

**Comment by dnstarostin** [comment]
Thank you.
