### ISSUE TITLE
JabRef hangs on macOS High Sierra, and adding localhost to "hosts" file doesn't solve it

### ISSUE THREAD

**Issue by murattasdemir** [JabRef/jabref#4347]
Every time do the following JabRef freezes, and I have to force quit:

* Open a file using File/Open from the menu.
* Open Help/About and then close it.
* Open preferences/external applications/vim/browse.

I have tried standalone java version as well. I happened again. It also happens with version 4.3.0.

BTW, the solution in the FAQ did not worked.

My JabRef version info:
JabRef: JabRef 4.3.1
OS: Mac OS X 10.13.6 x86_64 
Java: Java 1.8.0_181

**Comment by Siedlerchr** [comment]
Please try again with the latest development version. Howev,er it is recommended to create a backup of your db. https://builds.jabref.org/master/

**Comment by murattasdemir** [comment]
It works. Thank you. I like the new interface better.

**Comment by Siedlerchr** [comment]
@murattasdemir  Please report any issue you encouter with the development version. This is important for us. 
You can find all older builds here: https://github.com/JabRef/jabref/releases
