### ISSUE TITLE
Full Text Search Feature 

### ISSUE THREAD

**Issue by jkathir** [JabRef/jabref#4349]
Can you please kindly consider the following suggestions for JabRef ?

1. type ahead search, 
2. number of hits 
3. auto-complete suggestion 
4. faster search when we have 5,00,000 pages or contents being saved
5. easy navigation between the next hit found
6. preview of the text with paragraph
7. highlight the entered keyword in the page which is being saved

**Comment by tobiasdiez** [comment]
Thanks for your suggestions! However, this issue tracker is for keeping track of bugs and smaller suggestions for improvement. Your ideas are bigger feature requests and better fall in the scope of the [feature section of our discussion forum](http://discourse.jabref.org/c/features). Please open a new thread there, one for each feature suggestion (and please provide a bit more details about your ideas).
Thanks.
