### ISSUE TITLE
Sciencedirect fetcher non OpenAccess PDF links don't work

### ISSUE THREAD

**Issue by lecc0r** [JabRef/jabref#435]
I've just tested the newly implemented "Full text article download" function, however for several articles it downloaded a version from ResearchGate but I want to have the one from Elsevier. Dependent who you are working for, you have special access privileges on certain publisher sites where you download papers.

It would be handy to specify (in the preferences) which publisher the download pdf function should prefer. Perhaps even define a priority list, e.g. Sciencedirect (Elsevier), Wiley, ResearchGate, google, etc..

**Comment by stefan-kolb** [comment]
@lecc0r There is a hard-coded priority list right know which prefers the official publishers over google scholar for example. You can see it here: https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/external/FindFullText.java#L28
So this should already work as you expected. We need to reproduce the issue why it didn't fetch the one from Elsevier. Obviously it wasn't found or you had no priviledges.

**Comment by jhshinn** [comment]
Can you add some more full text crawler? I can't download the pdf files from some official publishers except the arXiv ones. I've made some example bib file here. https://dl.dropboxusercontent.com/u/60311114/temp.bib

**Comment by lecc0r** [comment]
@stefan-kolb : I reproduced the issue using the "Look up full text document" function to download the paper. The first screenshot shows on the right-hand side the pdf file that's been downloaded. The second screenshot shows the search result on sciencedirect (note the "brought to you by Universitätsbibliothek Stuttgart" message on the top right-hand side) offering the pdf download. The third screenshot shows the paper version I want.

I am going to check this issue against a paper which is available for the public to see if there is some privilege issue when downloading via JabRef.

![paper-lookupfunction](https://cloud.githubusercontent.com/assets/8577296/11555428/7577d044-99a0-11e5-87c4-bd547849dc91.png)
![paper-sciencedirectdownload](https://cloud.githubusercontent.com/assets/8577296/11555426/75773274-99a0-11e5-81a1-f6d34aa8e745.png)
![paper-wantedversion](https://cloud.githubusercontent.com/assets/8577296/11555427/757744c6-99a0-11e5-9e44-c5b28dcaff75.png)

**Comment by stefan-kolb** [comment]
@jhshinn I can get all of your papers from arXiv. If you want to submit a feature request for a particular publisher please open a new issue or even better submit a pull request :smile:

**Comment by stefan-kolb** [comment]
@lecc0r Most of the fetchers are based on DOIs at the moment, except for GoogleScholar as far as I remember correctly. See https://github.com/JabRef/jabref/tree/master/src/main/java/net/sf/jabref/logic/fetcher. Therefore you won't get your PDFs from official sources but from the Scholar search if you don't include a valid DOI in your BibTeX entry.

**Comment by lecc0r** [comment]
@stefan-kolb I manually downloaded the citation from sciencedirect because the websearch import does not include doi, url, and abstract (see https://github.com/JabRef/jabref/issues/431). The citation by default shows in the doi field: http://dx.doi.org/10.1016/j.coldregions.2013.03.002.
I tried your suggestion "doi:10.1016/j.coldregions.2013.03.002" as well as "10.1016/j.coldregions.2013.03.002". All tested doi entries result in the ResearchGate version.

**Comment by stefan-kolb** [comment]
This should work. However, I can't test it because i don't have access to this particular paper on Elsevier. Can you possibly reproduce this with an open access paper on Elsevier?

**Comment by lecc0r** [comment]
@stefan-kolb Yes it works but on sciencedirect only for Open Access Articles. I've just tested the function to download the open access paper "Numerical simulation of displacement characteristics of CO2 injected in pore-scale porous media" (http://www.sciencedirect.com/science/article/pii/S1674775515001079). I received the correct version. 
So this means that for some reason JabRef does not pass on the privilege you automatically receive when browsing sciencedirect while being connected to a privileged network. What could be the reason for that?

**Comment by stefan-kolb** [comment]
@lecc0r Does this URL return a PDF for you? http://api.elsevier.com/content/article/doi/10.1016/j.coldregions.2013.03.002?httpAccept=application/pdf

**Comment by lecc0r** [comment]
@stefan-kolb Not when opened in the browser. Sorry I am not quite sure if that's what you want.
![screenshot 2015-12-03 18 14 21](https://cloud.githubusercontent.com/assets/8577296/11567901/b5b04a94-99e9-11e5-89fe-72b3993ea2a0.png)

**Comment by stefan-kolb** [comment]
Yeah, ok that's what i expected. The current crawler returns a URL that is given by the API. Although, it seems that these URLs only work for public PDFs. Thanks for debugging, I'll see what  I can do.

**Comment by jhshinn** [comment]
@stefan-kolb Thanks for the guide. I wish I could pull request, but I don't know much about java script. :sweat: I'll open a new issue.

**Comment by stefan-kolb** [comment]
@lecc0r This should work as expected now. Please try the current master build at http://builds.jabref.org/.

**Comment by lecc0r** [comment]
@stefan-kolb Yes, sciencedirect full document look up works now! Thanks.
