### ISSUE TITLE
Add Generate BibtexKeys to Toolbar

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4353]
That's one of the things I miss in the new redesigned toolbar.

**Comment by tobiasdiez** [comment]
I also miss this since my brain is trained to search for the icon in the toolbar. However, the button next to the bibtexkey field is much more intuitive and the space in the toolbar limited. I would hence vote to close it.

**Comment by Siedlerchr** [comment]
I now tend to use the shortcut ctrl + g on all selected entries. So
