### ISSUE TITLE
software stucks when choose browse in Find unlinked files

### ISSUE THREAD

**Issue by GongSiqiu** [JabRef/jabref#4357]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on Ubuntu 18.04

JabRef 5.0-dev--snapshot--2018-09-19--master--d8f6c5cec
Linux 4.15.18-041518-generic amd64 
Java 1.8.0_181

Steps to reproduce:

1. Quality
2. Find unlinked files
3. browse
Then it will stuck. I can move the mouse, switch to other software, but whatever I do to jabref is useless. I can't  close it by clicking exit.

<details>

![2018-09-23 19-30-31](https://user-images.githubusercontent.com/40697840/45927579-e045af00-bf67-11e8-82b0-cd1fd54dfa6b.png)
</details>

**Comment by tobiasdiez** [comment]
Ahh damn. I started yesterday to convert the dialog to JavaFX in order to fix this issue. Sorry @NorwayMaple for not letting you know. My bad 😞 I hope you didn't invest to much time into debugging this issue.

**Comment by NorwayMaple** [comment]
That's fine!  I can find another issue, and I didn't spend a lot of time.

Was I right that the problem stemmed from incompatibility between Swing and JavaFX?

**Comment by tobiasdiez** [comment]
@NorwayMaple Yes, the underlying problem was a threading issue between the JavaFX and Swing thread.

**Comment by NorwayMaple** [comment]
@tobiasdiez Thanks for the info!

**Comment by NorwayMaple** [comment]
@tobiasdiez I looked at your commit, and it looks like there is no FXML or MVVM in `src/main/java/org/jabref/gui/externalfiles/FindUnlinkedFilesDialog.java`.  Since I'm trying to learn JavaFX and MVVM, what is your reasoning for writing it differently?

**Comment by tobiasdiez** [comment]
Laziness 😉 
I'm currently a bit short on time and it would have been additional work to convert the code structure to proper MVVM. The combo MVVM+FXML is convenient when writing new dialogs but for the conversion of old dialogs it is sometimes easier to just replace the swing controls by the JavaFX ones. That's not perfect but still better than having a buggy dialog.

If you want, you can start to convert other dialogs in a similar fashion (but please not the "Merge entries dialog" - that's my next project) and we can then refactor those dialogs to MVVM later together.

**Comment by NorwayMaple** [comment]
For me, the two biggest tasks would be to familiarize myself with the working parts of JabRef in general in order to write the ViewModel, and do better understand ViewLoader and EasyBind in the View.  Is there an easy way, for example, to learn how to apply EasyBind to MVVM (no pun intended)?

**Comment by GongSiqiu** [comment]
I wonder wheather the problem is fixed? I have tried the JabRef 5.0-dev--snapshot--2018-11-01--master, but the problem still exits.

**Comment by tobiasdiez** [comment]
Yes, this issue should be fixed now (and it is for me). Please make sure that you run the newest version. The dialog was completely rewritten and now should also look differently.
