### ISSUE TITLE
i-acute not handled / displayed correctly

### ISSUE THREAD

**Issue by akosthekiss** [JabRef/jabref#4359]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.0-dev--snapshot--2018-09-25--master--2f433d2a6
Mac OS X 10.13.6 x86_64 
Java 1.8.0_181

Steps to reproduce:

I-acute (í) can be written in multiple ways: `\'\i ` (note the space after i), `\'\i{}`, `{\'\i}`, or `\'{\i}`. Unfortunately, none of these forms display correctly either in the entry table or in the preview if used in the title or author fields. 

- In the entry table, title field becomes unreadable if any of the above forms is used.
- In the entry table, the author field becomes unreadable if any of the above forms is used in the last name.
- In the entry table, the author name becomes incorrectly partitioned if the space-separated form is used in the first name.
- In the preview, the space-separated form is rendered as `\i ` (with a space after i), while the curly-braced forms appear as `\i`

Interestingly, if i-acute is written in the bib as `\'i` (which is not proper LaTeX), then `í` is shown both in the table and in the preview.

Screenshot:
![screen shot 2018-09-26 at 12 02 24 2](https://user-images.githubusercontent.com/9976482/46073283-bf0dda00-c184-11e8-831a-4200458c5d97.png)

<details>
  <summary>Bib file:</summary>
  
  ```
@Misc{test1,
  author = {T\'\i m\'ar, John},
  title  = {Dummy},
  note   = {Last name with iacute (space-separated)},
}

@Misc{test2,
  author = {T\'{\i}m\'ar, John},
  title  = {Dummy},
  note   = {Last name with iacute (curly-braced)},
}

@Misc{test3,
  author = {Doe, T\'\i mea},
  title  = {Dummy},
  note   = {First name with iacute (space-separated)},
}

@Misc{test4,
  author = {Doe, T\'{\i}mea},
  title  = {Dummy},
  note   = {First name with iacute (curly-braced)},
}

@Misc{test5,
  author = {Doe, John},
  title  = {Megval\'os\'\i t\'as},
  note   = {Title with iacute (space-separated)},
}

@Misc{test6,
  author = {Doe, John},
  title  = {Megval\'os\'{\i}t\'as},
  note   = {Title with iacute (curly-braced)},
}

@Misc{test7,
  author = {T{\'\i}m\'ar, T\'\i{}mea},
  title  = {Megval\'os\'\i{}t\'as},
  note   = {Iacutes everywhere},
}

@Misc{test8,
  author = {T\'im\'ar, T\'imea},
  title  = {Megval\'os\'it\'as},
  note   = {Incorrect iacutes rendered as iacutes},
}
  ```
</details>

**Comment by Siedlerchr** [comment]
I am not a Mac Expert, but it might have to do sth with the font being able to display all unicode chars.
On Windows 10 I see the following.  

![grafik](https://user-images.githubusercontent.com/320228/47865997-ea2bbf00-ddfd-11e8-9108-b6a3206b6eb5.png)

@LinusDietz  Could you please check this on your Mac?
