### ISSUE TITLE
5-dev GUI: transposed "new entry" and "new article"

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#4360]
This is about the latest dev-version (from 25th Sept. 2018) on Win x64.

In the right toolbar the first button/symbol is explained (by tooltip) as "New entry".
When clicking on it a new **Article** is created and the field editor of it opens.

What I would expect is the real "New entry" behaviour, when using the menu "Library -> New Entry".
This opens an extra dialog where I can select a entry type or add an entry by the DOI.

IMO in the current state the "New entry" toolbar-button use the same click-handler as the menu "Library -> New Article".

**Comment by tobiasdiez** [comment]
Now the correct tooltip "New article" is shown on hover.
