### ISSUE TITLE
"copy preview" included unwanted HTML codes

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4365]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 
JabRef 5.0-dev--snapshot--2018-10-09--master--29838ee59
Linux 4.15.0-36-generic amd64 
Java 1.8.0_181

Steps to reproduce:

1. select an entry
2. display preview (alt+2)
3. copy preview (ctrl+shft+C)
4. paste preview

The result is tagged with HTML tags.  In most situations, like pasting to a word-processor or editor, I don't want these.  
Also, it's not possible to just select the previewed entry and copy it using the OS cut-n-paste system.

Please stop the "copy preview" command that putting HTML into the output.  Just plain text into the paste buffer.  
Another command which behaves as the present "copy preview" may be retained if there's user-demand.

Thanks!

**Comment by tb77phd** [comment]
It doesn't do this in all cases:

Clicking Edit -> Copy preview from the menu and then pasting gives **no HTML tags**.

Typing Ctrl+Shift+C and then pasting gives **no HTML tags**.

_Right-clicking_ in the preview window and then pasting does indeed give **HTML tags**.

I agree, HTML tags are not one usually wants when pasting information.

**Comment by wujastyk** [comment]
I've just eagerly tested what you say, hoping for a nice workaround, but

   - clicking Edit -> Copy preview from the menu and
   - typing Ctrl+Shift+C and then pasting

both *do give HTML tags*, on my system.  There's no way on my system to
avoid the HTML tags.  :-(

Using today's release:

JabRef 5.0-dev--snapshot--2018-10-09--master--29838ee59
Linux 4.15.0-36-generic amd64
Java 1.8.0_181

**Comment by tb77phd** [comment]
I see. Either a version issue or a system issue, probably. I am using JabRef 4.3.1 on a Windows 10-64bit.

**Comment by wujastyk** [comment]
Aha, yes, with 4.3.1 I get the same behaviour as you.

**Comment by tobiasdiez** [comment]
Thanks to @Ali96kz this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by wujastyk** [comment]
I've just tested today's snapshot

JabRef 5.0-dev--snapshot--2018-12-09--master--b52c97239
Linux 4.15.0-42-generic amd64 
Java 1.8.0_191

and when I do ctrl-shift-C or use the cursor popup to copy the preview, then I get the string "null" with a newline copied to memory fourteen times:

null
null
null
null
null
null
null
null
null
null
null
null
null
null
null

If I select the preview text and the press Ctrl+C, I get a good copy of the entry, with no HTML.

**Comment by wujastyk** [comment]
Yes, seems to be fixed now in the development release.  Many thanks!

**Comment by wujastyk** [comment]
JabRef 5.0-dev--snapshot--2019-01-05--master--d281ece4b
Linux 4.15.0-43-generic amd64 
Java 1.8.0_191

The 

null
null
null
null
null
null
null
null
null
null
null
null
null
null

behaviour reported on 9 December is back.  :-(

As before, selecting the preview and copying it with ctrl+C does put an un-tagged copy into the buffer correctly.  But ctrl+shft+C isn't working properly, either from the mouse right-click, the dropdown edit menu or by key presses.
