### ISSUE TITLE
New Search bar partly hidden in Ubuntu

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#437]
Hey,
just tried the new version.  Looks quite good! However, the new search bar at the top of the table is partly hidden on my Ubuntu 14.04

- I can see the search field, but not the optional buttons below.
- I tried with other look& feels, but this doen't change the problem. 

Unfortunately, I can't change the size of the search bar.
![bildschirmfoto vom 2015-12-01 15 08 22](https://cloud.githubusercontent.com/assets/8830305/11502836/6826fa5a-983d-11e5-99f1-4b365ee5adc4.png)

**Comment by simonharrer** [comment]
Hm, the options are put into the next line as the space is not enough, but the main table is not giving up any of its space. 

Workaround: try to maximize JabRef to see the options. If your display supports a resolution in which all options can be shown in one line. 

Expected solution: the options should not be hidden by the main table.

**Comment by koppor** [comment]
The fixed version can be downloaded at http://builds.jabref.org/master/
