### ISSUE TITLE
Jabref Stars

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4370]
It would be great if the **stars** would be consistent with the stars in the table headings. 

Another issue is with the **read status**, the colours of which are almost invisible, if the item is selected

![jabref_stars](https://user-images.githubusercontent.com/10846169/46918727-cda61f00-cfd5-11e8-95be-1bee41008897.png)

**Comment by tobiasdiez** [comment]
That's sadly not possible at the moment, because the library that we use for the stars in the main table does not allow for customization. Depends on https://bitbucket.org/controlsfx/controlsfx/pull-requests/685/make-rating-star-node-accessible-for/diff.

**Comment by DOFfactory** [comment]
What about changing the library for the needs of JabRef or using some other solution? No other solution possible for fixing this?

**Comment by LinusDietz** [comment]
Hey @DOFfactory, sure that would be the way to go. We are working hard to improve the UI of JabRef, however we have limited developer resources and currently focus on the more fundamental issues. If you (or anybody else reading this) has some time and knows some Java, this would be a nice contribution to fix!

**Comment by DOFfactory** [comment]
Hi @LinusDietz, I greatly appreciate all your efforts. I am afraid I cannot help you out with Java. Unfortunately, I had to revert back to v4.3.1, as this rather crucial feature for literature reviewing works perfectly well in that version. The issue is that sometimes JabRef v4.3.1 every now and then hooks up my CPU, as reported earlier #4171. I think it has something to do with incorrectly closing Java in the background.
![jabref_stars](https://user-images.githubusercontent.com/10846169/47067677-72994580-d1ea-11e8-80df-8bc76c6b28b7.png)

**Comment by Ali96kz** [comment]
Can you advice me. how I can do that?

**Comment by Ali96kz** [comment]
@LinusDietz Can you help me with that issue? 
P.S. as I understand there is no way to make stars smaller in controlsfx.

**Comment by DOFfactory** [comment]
The link from @tobiasdiez refers to some CSS modding ... not sure what the author meant

**Comment by Siedlerchr** [comment]
Thanks to @Ali96kz  this is now fixed!
