### ISSUE TITLE
Font choice and Row Spacing for entry table

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4371]
I try to use JabRef on a 4K screen and to be honest, I have big difficulties with overviewing my 1000+ entry table. The issues:

1. **The font of the entry table is very light** - it looks nice but it does not enhance readability. At least not on a 4k screen. *Solution:* Please provide a possibility to change the font typeface. Even better solution: It would be great to provide additional highlights for the various Entry Table cells (i.e. it would be great to be able to have the `bibtexkey` in bold typeface while the rest can be normal; or the `bibtexkey` can be monospaced typeface while the others could be regular). For example, if I use in the Entry Preview Lucida Sans, it is much more readable than the default font of JabRef in 4K screens.

![jabref_fonts](https://user-images.githubusercontent.com/10846169/46918855-99336280-cfd7-11e8-8610-dc5e3aeef7a8.png)

2. **The spacing between the rows is too big.** I believe JabRef is missing a lot of usable space by doing this. Unfortunately, in JabRef5 it is not possible to edit the spacing between the rows, JabRef4 was a bit better in this regard. *Solution:* Please give us the option to edit the Entry Table row spacing.

**Comment by Siedlerchr** [comment]
In addtion, the font size of the maintable should also be adjustable by the global settings or separate

**Comment by DOFfactory** [comment]
> I'm also not a big fan of the padding customization. The row size is taken from the style guidelines of Microsoft and Google. I think, the guys there have more experience and do more user testing.

I am not sure how much research guys at Microsoft and Google need to conduct and how many publications they need to review. What I can say is that my user-case (and many of my colleagues-scientists) depends a lot on overview and being able to review quickly list a lot of results in an easily discernible way. This means, being able to squeeze a biblatex database through search or filtering based on sorting options with a definable row size would be of *HUGE benefit*. Not everything that works for Google/Microsoft/any other company works for scientists. For a reference, please check out Bibdesk for macOS, JabRef in comparison is "too airy" - meaning it wastes space unnecessarily.

> In either way, it should be consistent with other paddings / spacings and thus this is something for a user-defined theme. Since the latter are now possible, I'm voting for a "wont-fix" on the second point.

Could you elaborate a bit more about this `user-defined theme`? I cannot find any reference to this neither in the Preferences, nor in the website.

**Comment by atulim** [comment]
@Siedlerchr I don't think there is much issue to be addressed here. The pattern of represntation of databases and fields is satisfactory. I myself work on 4K screen and I didn't have any problem when I was working through the application in order to find bugs.

**Comment by tobiasdiez** [comment]
There were indeed some huge improvements for high resolution displays. Moreover, the font size is now customizable on a global level.
