### ISSUE TITLE
manually defined multiline fields in entry editor do not work

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#4373]
This is 
JabRef 5.0-dev--snapshot--2018-10-14--master--73ec32189
Linux 4.18.12-200.fc28.x86_64 amd64 
Java 1.8.0_172

In this and prior dev versions, I seem not be able (anymore) to define multiline fields in the entry editor. I used to have defined an own general field with multiline content; but now this is not shown as such any more. Only, I guess pre-defined, fields like "Abstract" are shown as multiline fields.

**Comment by ilippert** [comment]
just for reference - I am referring to those fields I defined in
JabRef 4.3
Linux 4.18.12-200.fc28.x86_64 amd64 
Java 1.8.0_172

at JabRef preferences | File "Do not wrap the following fields when saving"

**Comment by Bastian-B** [comment]
Hi everyone! Has this been resolved for the now released version 5.0? I just installed it and all the manual linebreaks are gone despite the respective list. What seems odd: They are only missing in the "annote"-field, while everything is fine in "abstract" or "review". Does anyone have an idea? Thank you!

**Comment by ilippert** [comment]
I confirm:
JabRef 5.0--2020-03-08--93de138
Linux 5.5.7-200.fc31.x86_64 amd64 
Java 13.0.2
the issue is not solved.

**Comment by Siedlerchr** [comment]
I looked into the code and it's hardcoded for abstract and comment:
https://github.com/JabRef/jabref/blob/b5002e041d587ffb997e946f55daa9f8bdb438d4/src/main/java/org/jabref/model/entry/field/FieldFactory.java#L142-L149

As the "Do not wrap fields" aka multine are already stored in the preferences as part of the `FieldContentFormatterPreferences` it can be used.

1. Pass the preferences down to the above method and check the list
2. If it's in the list => multiline
3. Otherwise single line

**Comment by ilippert** [comment]
I am terribly sorry, but I would love to insist that this is an issue that is really preventing from using jabref well. This bug prevents me from using all my manually defined multiline fields. Please, please add it to the agenda for v5.1 again ;) - and lots of health and good spirit in the hard covid19 times!

**Comment by Bastian-B** [comment]
May I asked why this has been removed from the agenda? For myself, JabRef is unusable at the moment since all my annotations are shredded upon saving a file in 5.0, so I had to move to manually editing bibtex files …

**Comment by Siedlerchr** [comment]
We created a simple temporary solution for this issue: In the Preferences add the fields to the list of "do not wap". 
Should be available in latest master in half an our so.
I created a follow up issue to create a better solution #6448

**Comment by ilippert** [comment]
Thank you so much, this temp fix boosts productivity enormously!
