### ISSUE TITLE
Localization: untranslated menu items

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#438]
In JabRef 3.0 (but also using JabRef-3.1dev--snapshot--2015-12-01--master--4630d6b.jar), some menu items are not translated into French while the proper localization strings are present in the file Menu_fr.properties .
This is the case for the menu items "Cut", "Copy", "Paste".

Additionally, the menu "Check integrity" is not localized, but this may be because the proper key seems missing: we have the key "Integrity_check=V\u00e9rification_d'int\u00e9grit\u00e9"
but not  "Check_integrity=".

**Comment by matthiasgeiger** [comment]
I fixed the issues with "Cut", "Copy" and "Paste".

Regarding "Integrity check": We renamed "Integrity check" to "Check integrity" to use the "verb noun" style consistently - so this change is correct.

**Comment by domwass** [comment]
The German translation for "Check ingegrity" in the menu now is "Prüfe Integrität." (with period). I think this should be the translation for the status bar, not for the menu for which "Integritätsprüfung" or "Integrität prüfen" would be correct.

**Comment by mlep** [comment]
About the integrity check, I am fine with the decision to use "verb noun". The strange things are that 1) "Check integrity" still appears as a menu item and the key
"Integrity_check=" is still in the localization file.

**Comment by matthiasgeiger** [comment]
You are both right...

@mlep Can you provide me a translation for "Check integrity"? I'll add this to the menu preferences...

**Comment by mlep** [comment]
Check_integrity=Vérifier_l'intégrité
for French (but I guess translators for other languages are concerned, too)

**Comment by matthiasgeiger** [comment]
Renamed "Integrity Check" to "Check integrity" in https://github.com/JabRef/jabref/commit/68536e46e08b458431908010af0040a162b93af7 - I reused the old translations as a) they seem to use the "verb noun" style in some languages and b) the old translation is better than no  translation ;-)

**Comment by stefan-kolb** [comment]
Can this be closed again?

**Comment by matthiasgeiger** [comment]
Yes.
