### ISSUE TITLE
EZProxy integration

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4382]
Would it be please possible to integrate EZProxy functionality into JabRef? It would help in downloading the PDFs immensely. 

> EZproxy is the most widely used authentication and remote access software for libraries in the world. It manages institutional data about staff and users, domains and IT settings plus libraries’ electronic collections to facilitate access to online materials both inside and outside institutional IP ranges. The service ensures that a user’s interaction and engagement with their library’s e-resources can be the same, wherever they happen to be when accessing them.

Most of the university libraries have access through a single institutional login, which then parses the website with added values to the URL through a proxy. Usually it looks like `http://ezproxy.lib.cam.ac.uk:2048/login?url=` or similar. The database is available here: [https://ezproxy-db.appspot.com/](https://ezproxy-db.appspot.com/)

I understand that using EZProxy can parse the wrong URL for bibliography entries, therefore, it would be good to have an option to select it only for the PDF download or general parsing. In the latte option it would be good to have a functionality to change the URL back to the original URL.

**Comment by LinusDietz** [comment]
We currently have no money to pay someone for that (see our donations page at http://donations.jabref.org). No one of the JabRef team gets paid for JabRef. Thus, working on this really depends on the availability of our personal free time. - We really welcome feedback on our volunteer work. In case you can spend some more time (other than reporting issues), we would really like to encourage you to check https://contribute.jabref.org/ - especially the part asking for improvement of our help pages (https://help.jabref.org/en/). This would help JabRef getting better as a whole. 🥇

Nevertheless, to enable volunteers to work on your issue, we would recommend to file one at https://github.com/JabRef/jabref/issues/new/choose.
