### ISSUE TITLE
Menu entries in the ranking context menu show only one star for every entry

### ISSUE THREAD

**Issue by Nerator** [JabRef/jabref#4384]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 5.0-dev on Windows 10 and Lubuntu 18.04.1

JabRef 5.0-dev--snapshot--2018-10-17--master--d37ef3e18
Windows 10 10.0 amd64 
Java 1.8.0_181

Steps to reproduce:

1. Launch JabRef jar-file
2. Click "New BibTeX library" or "New BibLaTeX library"
3. Click "New Entry"
4. Right click on "Article" entry
5. Move pointer to the "Rank" submenu

<details>
  <summary>Screenshot</summary>
  
![default](https://user-images.githubusercontent.com/38375449/47162408-8f25a280-d2fc-11e8-9896-4464156a5d1e.png)
</details>

P.S. Sorry, if this is a duplicate, didn't find anything similar in tracker.

**Comment by Siedlerchr** [comment]
Seems to be related to #4370

**Comment by maloney8** [comment]
Hey,
I'd like to work on this issue

**Comment by tobiasdiez** [comment]
Thanks to @topalavlad this should be fixed now in the most recent development version.
