### ISSUE TITLE
Misc entry has Year and Month both in Optional and Deprecated tabs

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#4388]
JabRef 4.3.1
Linux 4.18.14-arch1-1-arch amd64 
Java 1.8.0_192

Steps to reproduce:

1. Create and select a Misc entry in biblatex mode

While these fields should be in the Required tab, as BibLaTeX manual says:
> Required fields: `author/editor, title, year/date`
> Optional fields: `subtitle, titleaddon, language,howpublished,type,version,note,organization,location,date,month,year,addendum,pubstate,di,eprint,eprintclass,eprinttype,url,urldate`

**Comment by Siedlerchr** [comment]
I talked to the  biblatex guys  plk/biblatex#833 and it's an error in the specification. It does not make sense to add the fields double. Year and months are only valid in required fields
