### ISSUE TITLE
Automatic Bug Report - 20181020235219

### ISSUE THREAD

**Issue by dprodanov** [JabRef/jabref#4393]
JabRef 4.3.1
Windows 7 6.1 amd64 
Java 1.8.0_191

Steps to reproduce:

impossible to access the edit interface in an existing bib database.

Paste your log details here.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
