### ISSUE TITLE
can not edit entry

### ISSUE THREAD

**Issue by Steff82** [JabRef/jabref#4401]
Hello, 
I am working on Windows 10 with JabRef. Since the last update, I can not open any entry. Creating a new entry (type article) directly creates an empty entry. The editor does not open.

Best regards, 
Steff

**Comment by Siedlerchr** [comment]
Hi,
you probably have just hidden the entry editor. Sometimes the entry editor minimizes to the bottom. Check if this is the case.

**Comment by Steff82** [comment]
:$. Thanks! Now I can edit again 👍
