### ISSUE TITLE
Arxiv link prefix should be discarded to produce working links in BibLaTeX

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#4407]
JabRef 4.3.1
Linux 4.18.14-arch1-1-arch amd64
Java 1.8.0_192

Related TSE question: https://tex.stackexchange.com/questions/436684/correct-arxiv-hyperlinks-with-biblatex-and-mendeley

Steps to reproduce:
Random example: https://arxiv.org/abs/1810.09995

1. Use biblatex mode and biblatex format
2. Import a publication by its arxiv URL.
_The problem_: unlike with DOI (e.g. it easily parses https://doi.org/10.1137/16M1104986 but not doi.org/10.1137/16M1104986), arxiv cannot discard `https://arxiv.org/abs/` URL prefix
3. Import a publication by its ID.
Result:
```
@Article{marcheggiani2018dgc,
  author      = {Diego Marcheggiani and Laura Perez-Beltrachini},
  title       = {Deep Graph Convolutional Encoders for Structured Data to Text Generation},
  date        = {2018-10-23},
  eprint      = {http://arxiv.org/abs/1810.09995v1},
  eprintclass = {cs.CL},
  eprinttype  = {arXiv},
  abstract    = {...},
  file        = {:http\://arxiv.org/pdf/1810.09995v1:PDF},
  keywords    = {cs.CL},
}
```
4. Cite this using biblatex, and it reads

> D. Marcheggiani and L. Perez-Beltrachini. “Deep Graph Convolutional En-
> coders for Structured Data to Text Generation”. In: (Oct. ...). arXiv:
> https://arxiv.org/abs/1810.09995 [cs.CL].

_The problem:_ biblatex generates wrong link because of wrongly formatted `eprint`: https://arxiv.org/abs/http://arxiv.org/abs/1810.09995v1

### Summary
When importing an arxiv preprint, JR only accepts ID, but it puts the full URL into the `eprint` field, while it should contain only the ID.

### Suggestions

- unify URL parsing: protocol and website name should not matter
- write only ID to the eprint field

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by homocomputeris** [comment]
It seems fine:
```
@Article{marcheggiani2018dgc,
  author      = {Diego Marcheggiani and Laura Perez-Beltrachini},
  title       = {Deep Graph Convolutional Encoders for Structured Data to Text Generation},
  abstract    = {...},
  date        = {2018-10-23},
  eprint      = {1810.09995v1},
  eprintclass = {cs.CL},
  eprinttype  = {arXiv},
  file        = {:http\://arxiv.org/pdf/1810.09995v1:PDF},
  keywords    = {cs.CL},
}
```
