### ISSUE TITLE
Restrict selection of multiple radio buttons that belong to the same group to just one

### ISSUE THREAD

**Issue by shahamish150294** [JabRef/jabref#4409]
JabRef version on Windows 10/Java 8.
- I am having trouble installing the JabRef.exe from http://builds.jabref.org/master/. I have tested checking out the latest from master.

In Preferences, there are instances at which we need to select an option through radio buttons. Eg: Check screenshot attached. There are many instances in the Preferences where I am able to select multiple radio buttons for each group. Either we need to use checkboxes if multi-select is to be allowed or we should group the radio buttons under a toggle group as done here https://github.com/JabRef/jabref/pull/4408/files#diff-e0f0e1ade7c4cee8c43b0bb2254c21ebR123

I debugged an verified this issue. If multiple options are selected then always the first option (out of all the other selected options) in the if-else condition gets set as the preference.
1. Start the app
2. Go to Options > Preferences > Entry Editor
3. Enable autocomplete options
4. Under the "Name format used for auto completion" option, you should be able to select all the options

![image](https://user-images.githubusercontent.com/7998085/47560233-4dd55a00-d8dd-11e8-8dcd-a28c86d5edd7.png)

**Comment by Siedlerchr** [comment]
Toggle Group seems like the best solution to me. Do you want to fix this?

**Comment by paulKra** [comment]
Hi, we are two students who found your project through the awesome beginners page and wanted to try on a issue before. If @shahamish150294 does not want to fix it, we would like to try, if he is okay with it.

**Comment by shahamish150294** [comment]
@paulKra Sure, go ahead! I haven't started this yet. Let me know if you have any questions.

**Comment by tobiasdiez** [comment]
Thanks to @paulKra this is now fixed.
