### ISSUE TITLE
Conventions for tests

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#442]
Since I couldn't find any conventions for tests in the wiki, I would like to launch a discussion about them here. 

As a starting point, I propose the following points. Imagine you want to test a method `format(String value)` in the class `BracesFormatter` which removes double braces in the given string.
- *Placing:* all tests should be placed in a class named `classTest`, e.g. `BracesFormatterTest`. 
- *Naming:* the name should be descriptive enough to describe the whole test. Use the format `methodUnderTest_exspectedBehaviour_context` (without the dashes). So for example `formatRemovesDoubleBracesAtBeginning`. Some people prefer an additional `test` prefix, but I think this is redundant as the class name already entails that we are dealing with tests. See also the [Stackoverflow discussion](http://stackoverflow.com/questions/155436/unit-test-naming-best-practices).
- *Test only one thing per test:* tests should be short and test only one small part of the method. So instead of 
````
test() {
   assertEqual("test", format("test"));
   assertEqual("{test", format("{test"));
   assertEqual("test", format("{{test"));
   assertEqual("test", format("test}}"));
   assertEqual("test", format("{{test}}"));
}
````
we would have five tests containing a single `assert` statement and named accordingly (`formatDoesNotChangeStringWithoutBraces`, `formatDoesNotRemoveSingleBrace`, `formatRemovesDoubleBracesAtBeginning`, etc.). See [JUnit AntiPattern](http://www.exubero.com/junit/antipatterns.html#Multiple_Assertions) for background.
- Do *not just test happy paths*, but also wrong/weird input.
- Try to write tests *before* you actually implement the functionality (test driven development).
- *Bug fixing:* write a test case covering the bug and then fix it, leaving the test as a security that the bug will never reappear.
- *Integration testing:* we should use a different class for this higher level testing and not mix them with unit tests.

As I have said above, these things should just service as a starting point for further discussions. They are more or less a distillation of some guides I read about unit testing.

**Comment by lenhard** [comment]
A good idea and definitely something that should be documented!

I agree with practically everything you write. My discussion points are:
 - TDD is fine, but we shouldn't be dogmatic about enforcing it.
 - Regarding integration testing: Currently, nearly all tests are integration tests (they combine objects of different classes for a test and check their interaction). Building true unit tests would require the usage of mocks and stubs and this would require to rewrite nearly all tests. More importantly, JabRef is so tightly coupled in many positions that unit tests are impossible to write without a major rewrite of the program (I am talking about the infamous `Globals` class and the like). I don't think we have the resources for that and, therefore, I would just keep unit and integration tests together.

**Comment by matthiasgeiger** [comment]
Moreover, apart from those rather general (but nonetheless important!) aspects we should create and document specific guidelines and best-practices. 
Some food for thoughts:
- Testing preferences without affecting the stored prefs for the developer
- creating and using databases, entries, ... for test purposes
- ...

**Comment by tobiasdiez** [comment]
Another point is which mocking/stubbing framework should we use? According to a [Stackoverflow question](http://stackoverflow.com/questions/22697/whats-the-best-mock-framework-for-java), [Mockito](http://mockito.org/) is the way to go. After reading a little bit through their documentation, I have to admit that I really like the syntax. Other opinions?

**Comment by simonharrer** [comment]
It is, but I am not sure if we should build a strong unit test harness based on the currently hard to test classes with a lot of global variables and singletons. The most gain is in tests using the CLI commands and checking input/output or testing classes or testing whole modules through their main interfaces. Additionally, GUI testing would also have quite some gain, but would also require additional libraries and will be obsolete in some parts when migrating to JavaFX.

**Comment by tobiasdiez** [comment]
Yes, Mockito wouldn't help to solve the problem of to many global objects floating around. But it is a necessary tool testing `good` code. If you write new code (or refactor old one) in a proper fashion (i.e. not relaying on global objects), then the tests really need a mocking framework. 

Let me give you an example: you have suggested in #467 that there should be a new class 
````
public class LastFocusedTabPreferences {

    public LastFocusedTabPreferences (JabRefPreferences prefs) {
    }

    public void setLastFocusedTab(File file) {
       // make absolute path, set, ...
    }

    public boolean hasHadLastFocus(File file) {
       // true if file.absolutePath.equals(getLastFocusedTab())
    }
}
````
A proper test for these methods would require a mock of the JabRefPreferences class, so that we can test if changes are properly stored. Now JabRefPreferences should derive from an interface so that we can insert a custom mock into the constructor of `LastFocusedTabPreferences`. This does not change the problem of a singleton preference class, but at least the new class `LastFocusedTabPreferences` is free of these shortcomings, is properly tested and has no references to global objects. Without a mocking framework it would be way easier to erase the constructor of `LastFocusedTabPreferences` completely and store the changes directly in the singleton preference class. Works but is no longer testable.

**Comment by koppor** [comment]
Who writes the test cases for the mocks? :sunglasses:

Do we have resources for writing mocks? Would people writing mocks spend time to fix other things? On top or instead of? Or would they only write mocks instead of doing anything? If that latter is the case, we can go for mocks. If anything else is the case, I would spend time on improve existing code and test coverage.

Is JabRef really that large that we need mocks? I agree for large projects, where many side effects arise (such as the [Apache ODE BPEL Engine](http://ode.apache.org/)), but for JabRef?

**Comment by tobiasdiez** [comment]
The people from Mockito write tests for the mocks, not us (actually, there are at 80%+ instead of our 14%). In my opinion, mocks are useful for every project size. For example a typical test using preferences could like this (example taken from #469)

````java
@Test
public void testBibLatexMode() {
     // Mock preferences
     JabrefPreferences mockedPrefs = mock(JabrefPreferences.class);        
     // Switch to BibLatex mode
     when(mockedPrefs.getBoolean("BiblatexMode")).thenReturn(true);

     // Now test
     EntryTypes biblatexentrytypes = new EntryTypes(mockedPrefs);
     assertEquals(BibLatexEntryTypes.ARTICLE, biblatexentrytypes.getType("article"));
}
````
In my opinion, this code is way simpler, easier to write and understand. 

The aim of a mocking framework is to increase test coverage by making it easier to write tests.

**Comment by koppor** [comment]
When doing `when(mockedPrefs.getBoolean("BiblatexMode")).thenReturn(true);`: Who tests that? :smiley: OK, that's an edge case.

You example convinces me.

**Comment by simonharrer** [comment]
I know how Mockito works and I really like it as a testing library. But with the current amount of code change/refactoring, I do not think this approach of unit testing is feasible. Because when you change/refactor the class you have to rewrite the unit tests coming with it. Because of this, I like to have more tests at the CLI level, or at higher API calls. They can give feedback if my internal change is still working. And do not have to touch them, as they depend only on quite small APIs.

**Comment by tobiasdiez** [comment]
I see your point @simonharrer. Of course tests make it sometimes harder to refactor something. That is true. But don't you think that some parts of JabRef have a relatively stable API and would profit immensely from through-out unit testing? I was thinking about the parser, export + import functionality, the formatters, etc. 
What about a compromise: add Mockito to the arsenal, but allow it only for testing specific parts (like the above for example).

**Comment by lenhard** [comment]
From my point of view, the compromise is fine. We can add Mockito, which, to the best of my knowledge, is the most convenient mocking library for Java. If someone wants to use mocking, he can do so, but no one is forced to. 

What JabRef would really benefit from in my point of view, would be a big roundtrip test, e.g. startup the ui, load a database, add/modify an entry, save the database. But this is really hard due to the UI.

**Comment by simonharrer** [comment]
Basically the CLI commands could do this roundtrip as they are quite flexible. Especially, if we make cleanups available there as well.

**Comment by tobiasdiez** [comment]
I just added most of the points we have discussed above to the wiki. Feel free to further improve the wiki pages and/or correct what I added.

**Comment by koppor** [comment]
@tobiasdiez Could you have a look at https://github.com/JabRef/jabref/pull/508#issuecomment-196202065 - especially regarding the file names used for parameterized tests?

**Comment by tobiasdiez** [comment]
@koppor I have no objections about the suggested file names. But I'm not sure that you even need to split the test into two files...

**Comment by koppor** [comment]
The splitting is required as for each parameter, **all** tests are executed. This makes reading the tests result very hard. For instance, the check for the formatter name won't change if other checks are done. When I have 5 tests, 3 of them changing based on the parameters, and 2 of them never changing, should they be included in the iteration? I don't think so.

![grabbed_20160314-100110](https://cloud.githubusercontent.com/assets/1366654/13739482/b68b6264-e9cb-11e5-8704-c96f4293829d.png)

versus

![grabbed_20160314-100144](https://cloud.githubusercontent.com/assets/1366654/13739495/c7474190-e9cb-11e5-824a-04ed2bb23c7a.png)

I prefer the latter.

Branch: cryptedpdfs. In the first screenshot, `net.sf.jabref.importer.fileformat.PdfContentImporterTest.doesNotHandleEncryptedPdfs()` has been copied into `net.sf.jabref.importer.fileformat.PdfContentImporterTestFiles`.
