### ISSUE TITLE
Report proper error when google fetcher hits limit

### ISSUE THREAD

**Issue by skanskan** [JabRef/jabref#4423]
The web search option sometimes works well but many times doesn't work ,it just doesn't open the search Window nor produce any result.
No error message is produced.

JabRef 5.0-dev--snapshot--2018-10-27--master--aeea80969
Windows 10 x64

**Comment by Siedlerchr** [comment]
Could you provide some details which and where you are searching (e.g. Springer, acm...) and possible a keyword/identifier that fails. That would help us narrow down the error.

**Comment by skanskan** [comment]
I'll try to reproduce the problem and post it. I tried with both Pubmed and Google Scholar.
Maybe the Window with results stayed on the background.

One question, maybe related...
When you have used Google Scholar several times it asks you for a captcha.
How does Jabref deal with that problem?

**Comment by stefan-kolb** [comment]
> When you have used Google Scholar several times it asks you for a captcha.
How does Jabref deal with that problem?
You need to manually enter the Captcha in the web browser at the moment.

**Comment by stekeller** [comment]
I think this is connected to #4027 
Using JabRef 4.3.1 on Windows 10 10.0 amd64 with Java 1.8.0_201
I have the same issue, mostly in my university network, but from time to time also in my home network.
Entering the captcha in the browser doesn't fix the issue in jabref. Please fix this!

**Comment by Siedlerchr** [comment]
Sorry, we can't do anything about this. The problem lies on the side of Google limiting access.

**Comment by skanskan** [comment]
> Sorry, we can't do anything about this. The problem lies on the side of Google limiting access.

Thank you

**Comment by Andlon** [comment]
> Sorry, we can't do anything about this. The problem lies on the side of Google limiting access.

I also have the same problem., JabRef 4.3.1 on Debian 10. However, I respectfully disagree with your conclusion here: I think it would be appropriate for JabRef to return an error, instead of just closing the window without warning. The user experience right now is a little frustrating, because there's no error and also nothing in the Event Log.
