### ISSUE TITLE
How to construct a group containing entries that not in any user defined group

### ISSUE THREAD

**Issue by springzfx** [JabRef/jabref#4425]
Just as the title described. Currently, dynamic group will never include a entry if the field (eg. groups) not exists, because of the regex match.  Regex won't match _null_ value.

![image](https://user-images.githubusercontent.com/8992037/47612835-a6634d80-dabd-11e8-811e-bbb3957e952a.png)

**Comment by tobiasdiez** [comment]
That's not possible at the moment. Please use our forum for questions!
