### ISSUE TITLE
Update timestamp on modification does not keep the status on saving

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4427]
JabRef 5.0-dev--snapshot--2018-10-27--master--aeea80969
Windows 7 6.1 amd64 
Java 1.8.0_191
- [ +] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Trying to uncheck "Update timestamp on modification" in Preferences->General does keep "unchecked" when saving options is unsuccessful, this feature is not saved at all.

1. Open Preferences
2. The presents checked as in screenshot 1.
3. Press "mark new entries with date" twice and you will be able to uncheck "Update timestamp on modification". Then the display is like in screenshot 2.
4. Do so and save the options.
5. Open Preferences again, we are back to screenshot 1. The option has not been saved.

screenshot 1:
![grafik](https://user-images.githubusercontent.com/9216487/47630142-78265200-db3f-11e8-983a-397c60cd9214.png)
screenshot 2:
![grafik](https://user-images.githubusercontent.com/9216487/47630316-61ccc600-db40-11e8-85e7-2c7c2618b156.png)

<details>
  <summary>Log File</summary>
  
  ```
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20171208VS5.0.bib
Can only load style files: Preview

  ```
</details>

**Comment by PJozeph** [comment]
I will go for this.

**Comment by Siedlerchr** [comment]
Thanks for your interest, but @sbeitzel already provided a PR fixing this. However you might want to take a look at other open issues

**Comment by Siedlerchr** [comment]
Thanks to @sbeitzel  this issue got fixed!


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by tobiasdiez** [comment]
Thanks to @sbeitzel this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by bernhard-kleine** [comment]
seems ok now.
