### ISSUE TITLE
Performance issues in development version 5.0

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#4430]
JabRef 5.0-dev--snapshot--2018-10-28--master--05047f32a
Windows 10 10.0 amd64 
Java 1.8.0_191

Steps to reproduce the behaviour:
1. Open a large database (in my case > 16,000 entries)
2. Select a group in the groups panel
3. Entries belonging to the group are displayed in the main panel
4. Select another group in the groups panel
5. Entries belonging to this group are displayed again in the main panel. Note, however, that there is a noticeable delay until the entries are displayed (about 1 to 2 seconds).

If you repeat steps 4 and 5 you will always notice this delay of one or two seconds. This can get quite annoying if you quickly have to change groups. Note, that in JabRef version 3.8.2 (which I am still using as my main version) there is no such delay. Is it possible to get a performance in handling large databases in version 5.0 that is comparable to that of 3.8.2?

**Comment by Siedlerchr** [comment]
The changing of group is still slow and causes a spike in CPU load.  Tested with a large database o 6,400 entries and many groups. 
Memory is not an issue.
![grafik](https://user-images.githubusercontent.com/320228/59868194-9243c780-9390-11e9-8e16-92187aac8a22.png)

**Comment by AEgit** [comment]
Can confirm - I might have time during this weekend to run some additional performance test. Unfortunately my YourKit Java Profiler test license ran out, so I will probably have to create a new Virtual Machine and run a new installation of YourKit in there - unless someone else knows a method to extend the evaluation period a little? I don't really need the tool except for showing the performance issues in the current JabRef version compared to version 3.8.2

**Comment by tobiasdiez** [comment]
This should be fixed now. A few remaining performance issues are mentioned at https://github.com/JabRef/jabref/issues/5071#issuecomment-554769666

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-11-28----ce0e8870c
Windows 10 10.0 amd64 
Java 13.0.1

This issue, indeed, appears to be fixed in the current version of JabRef (the remaining issues can be found here: https://github.com/JabRef/jabref/issues/5071#issuecomment-554769666). Big shout out to @tobiasdiez for the continuous support!
