### ISSUE TITLE
Some bugs in preference->Entry table columns

### ISSUE THREAD

**Issue by springzfx** [JabRef/jabref#4437]
preference->Entry table columns

1.  The _Field name_ is not editable
2.  The value in _Field name_ is not identical with table header
2.  The two buttons in bottom looks the same
3.  _Column width_ is float which is not compatible with jabref-4.3.1. 

![image](https://user-images.githubusercontent.com/8992037/47720209-4f5da400-dc88-11e8-99b3-01590d0069ee.png)

**table header:**
![image](https://user-images.githubusercontent.com/8992037/47720778-a748da80-dc89-11e8-8aab-0d3b776cf22c.png)

**Comment by tobiasdiez** [comment]
Moreover, the column width should be completely removed from the preferences since column can now comfortably resized directly in the main view.

**Comment by morganlovato** [comment]
I have a group for a school project and we would like to contribute this issue, is it available?

**Comment by tobiasdiez** [comment]
@morganlovato Sure, feel free to work on this issue! Also have a look at our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and drop by in our [developer chat](https://gitter.im/JabRef/jabref) if you have questions!

**Comment by Siedlerchr** [comment]
Agree with @tobiasdiez  The preferences option should be completely removed, this should already be sufficient as there is already a change listener present in `PersistenceVisualStateTable`  which stores the width

**Comment by tobiasdiez** [comment]
The buttons now have the correct size thanks to @morganlovato.

However, the other issues remain and in addition:
- [ ] The Field name is not editable
- [ ] The value in Field name is not identical with table header

**Comment by aman-coolinc1** [comment]
Hi, 
Remove everything related to the width from the preference dialog (but not from the preference themselves)

Do you mean we should remove these things from the dialog
![image](https://user-images.githubusercontent.com/8446821/49984889-ea3be480-ff8f-11e8-9fbe-b3ecf74b8ec5.png)

**Comment by aman-coolinc1** [comment]
![image](https://user-images.githubusercontent.com/8446821/49984910-0049a500-ff90-11e8-9dba-cf43ba99dc7f.png)

**Comment by Siedlerchr** [comment]
@aman-coolinc1  Yes, exactly the things you marked. This is because, you can change the column size  directly in the main table,

**Comment by rachelwu21** [comment]
I'm working on this.

**Comment by tobiasdiez** [comment]
Thanks to @rachelwu21, this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
