### ISSUE TITLE
Warn on empty entrykey (bibtexkey)

### ISSUE THREAD

**Issue by moewew** [JabRef/jabref#4440]
*Small Enhancement*

All `.bib` entries processed by Biber must have a non-empty `entrykey`. Entries without a key, e.g.
```
@Book{,
  author  = {Emma Sigfridsson},
  title   = {El book},
  date    = {2012},
  edition = {6},
}
```
produce an error along the lines of
```
syntax error: found ",", expected one of: number, name (entry  type, key, field, or macro name), end of entry ("}" or ")") or quoted string 
```
and the compilation will abort.

`biblatex` with the BibTeX backend will not error on an empty `entrykey`, but the entry can not be cited and will not be added to the bibliography even with `\nocite{*}`.

Classical BibTeX adds entries without key to the bibliography with `\nocite{*}`, but does not allow to cite them. In any way there can only be one entry with an empty entrykey (after all the key must be unique).

Conclusion: Even though empty entry keys are half possible, they don't quite work as expected and I can't imagine any user choosing an empty key on purpose.

**Suggestion** JabRef already warns the user directly in the editor view with a little icon if the `year` field is not a four-digit integer and if it detects journal abbreviations.  It seems like a good idea to also warn the user if they leave the entry key empty.

---

Just to be sure: I tested with JabRef 4.3.1 and did not get an error or a warning about empty keys in the editor view. I also got no report from "Ctrl+F8" on the file
```
% Encoding: UTF-8

@Book{,
  author  = {Emma Ryde},
  title   = {El book},
  date    = {2010},
  edition = {1},
}

@Comment{jabref-meta: databaseType:biblatex;}
```
But when I was just playing around with JabRef I saw a message about entrykeys at one point (I can reproduce messages about a key that does not match the automatic pattern, but I could have sworn I also managed to get one about an empty key once, I can't reproduce that one, though), so it seems that some kind of detection is already built-in.

---

*edit*: https://tex.stackexchange.com/q/457685/35864 on TeX.SX started this. The OP had an empty entrykey in a JabRef-generated file and was surprised that Biber would report a syntax error.

**Comment by Siedlerchr** [comment]
I think there is a setting, which enables the Warning of empty bibtexkeys

**Comment by tobiasdiez** [comment]
There is a warning about the empty key in the integrity check. However, the warning message is not shown in the entry editor.

**Comment by moewew** [comment]
Oh, I might have overlooked such an option. I have the *Enforce legal characters in BibTeX keys* option checked, but that does not help with empty keys as far as I can tell (FWIW I don't quite understand what the option does: the quite dangerous `Sig,([fri}{dßä\"o:1998)]` still passes "Ctrl+F8" and I get no warning icon, but maybe the option is only about auto-generated keys?). 

Re the integrity check: I might be missing something obvious. But if I open the file I posted above with JabRef in `biblatex` mode and press "Ctrl+F8" for the *Integrity check*, I get "No problems found".

**Comment by ms111ds** [comment]
I've been playing around with this issue. Would it be ok to try to help with it?

**Comment by Siedlerchr** [comment]
Sure, go ahead! If you need any further help or have questions just ask here or in our gitter chat
