### ISSUE TITLE
Moving ranking column: moved visually, but function still in old place

### ISSUE THREAD

**Issue by sbitzer** [JabRef/jabref#445]
In JabRef 3.0 I moved the ranking column to the end of my entry table using drag and drop. The file and URL columns took its place. When I then clicked on the file icon, the ranking dialogue popped up (star selection) and when I clicked the URL icon the file was opened. I could also not drag and drop the ranking column back in place - it stayed after the author column. When I switched off the ranking column in preferences, the file and URL icons worked as expected. I had also moved the entry type column towards the end of the table, but guess that this didn't cause the observed behaviour.

I'm on Linux Mint 17.1. My Java version is Oracle Java 1.8.0_66.

**Comment by koppor** [comment]
Possibly #443 is related.

**Comment by matthiasgeiger** [comment]
Fixed with #452 - changes are available now in current [development builds](http://builds.jabref.org/master/) and will be released with 3.1
