### ISSUE TITLE
Shared DB Connection issue in development version 5.0

### ISSUE THREAD

**Issue by AurelienBioprojet** [JabRef/jabref#4464]
The server and DB connection works fine with Jabref 4.x. but the following connection error appeared using dev 5.0 with our shared database (MySQL 5.7) hosted on Windows Server 2008 R2.

"The server timezone value 'Paris, Madrid (heure d'été)' is unrecognized or represents more than one timezone. You must configure the server or JDBC driver to use more specific time zone value if you want to utilize time zone support."

The problem was solved by setting the MySQL server GLOBAL time_zone to a fixed value (example: '+1:00'). 

The default time_zone value 'SYSTEM' indicates that the time zone used is the system time zone.
This default value raised the mentionned connection error in dev v5.0.

**Comment by Siedlerchr** [comment]
Hi, in the 5.0 dev we updated the MySQL driver to support newer versions of MYSQL.
Maybe we can add a parameter timezone to the configuration.

**Comment by AurelienBioprojet** [comment]
It seems there's no major change about timezone support between MySQL version 5.x and 8.0.
https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html

What is the change between v4.x and v5.0?
Did you add the timezone parameter in the jdbc connection string for v5.0? 
If yes, it would be a good idea to add this optional parameter in the shared DB login window.
If no, it would be needed to populate TimeZone Tables in MySQL server.
See section _Populating the Time Zone Tables_

**Comment by Siedlerchr** [comment]
In 5.0dev we use the version 8 of the ConnectorJ jdbc library. The easiest option would be to add a field to the dialog where the user can enter the timezone data string.
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-usagenotes-known-issues-limitations.html

**Comment by AurelienBioprojet** [comment]
Using ConnectorJ v8, many properties about date and time disappeared.
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-properties-changed.html

Your option (free text field) seems a good and easy solution since _The server's time zone is overridden by setting the Connector/J connection property serverTimezone_
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-other-changes.html

Thanks for your answers, looking forward the next v5.0 release.

PS: MySQL v8 should be recommended for JabRef v5.x?

**Comment by AndresSan6** [comment]
Hello! I can help with this issue, will start working on it today.

**Comment by AndresSan6** [comment]
Hello, I made a PR #4483 where I am adding the requested feature.

**Comment by tobiasdiez** [comment]
Thanks to @AndresSan6 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
