### ISSUE TITLE
"Save" has no effect for new libraries without a file yet

### ISSUE THREAD

**Issue by jmkeil** [JabRef/jabref#4467]
JabRef version JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04 on Windows 8.1

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. create a new library
2. click on "save" (not "save as")
    * nothing happens (expected: file browser appears to select file, as for "save as")

**Comment by PJozeph** [comment]
I will go for this

**Comment by Ali96kz** [comment]
@PJozeph Do you work on it?

**Comment by tobiasdiez** [comment]
Thanks to @Ali96kz should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by jmkeil** [comment]
I have tested it with JabRef-5.0-dev--snapshot--2018-11-18--master--64f320971.jar and it works well. Thank you.
