### ISSUE TITLE
Can't input Chinese characters in biblatex source

### ISSUE THREAD

**Issue by GongSiqiu** [JabRef/jabref#4474]
JabRef version 
JabRef 5.0-dev--snapshot--2018-11-09--master--bab9ae819
Linux 4.14.77-041477-generic amd64 
Java 1.8.0_181
 on Ubuntu 18.04

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1.Open and entry
2. Choose biblatex source
3.Input Chinese characters
I can't input Chinese characters in biblatex source, but I can do it in other fields and copy Chinese characters from other places to biblatex source.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by tobiasdiez** [comment]
The workaround posted in https://github.com/FXMisc/RichTextFX/issues/146 should work.

**Comment by CaptainDaVinci** [comment]
I would like to work on this issue.

**Comment by Siedlerchr** [comment]
Thanks to @CaptainDaVinci  this should now be fixed in the latest development version.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by GongSiqiu** [comment]
Yes, it is fixed. Thank you!
