### ISSUE TITLE
crash in entry editor after moving entry to groups 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4478]
1. Move items from one group to another
2. Open the item view/panel, switch between tabs including the "BibTex Source" tab (without making any modifications)
3. llose the item view/panel
4. Try to move the same items to another group

Followup from #4414  reported by @AEgit

**Comment by skanskan** [comment]
I have the same problem.

**Comment by Siedlerchr** [comment]
No longer reproducible in master.
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
I can confirm this bug has been fixed in:

JabRef 5.0-dev--snapshot--2019-03-28--master--a73167933
Windows 10 10.0 amd64 
Java 1.8.0_201
