### ISSUE TITLE
Search: Drop down displays author name with Encodings/Escape but selecting not possible

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#448]
The new search is awesome!

I noticed some strange thing when searching for an author, who has accents in his name and therefore is encoded/escaped:
`Mari Carmen Su{\'a}rez-Figueroa`

![jabrefsearchencodingescape](https://cloud.githubusercontent.com/assets/320228/11537412/22724574-991d-11e5-97b8-d569d8539758.png)

When I enter  "su" in the search, the following author is suggested, but however clicking on it, does say: Entry not found. However when I search the term "Suarez", the entry is found (BibtexKey generated is without accents). 

![jabrefsearchencodingescapenoresults](https://cloud.githubusercontent.com/assets/320228/11537460/6697c6a2-991d-11e5-9429-2df5ec0e78db.png)

```
@InCollection{Suarez-Figueroa2012,
  Title                    = {Introduction: Ontology Engineering in a Networked World},
  Author                   = {Mari Carmen Su{\'a}rez-Figueroa and A. G{\'o}mez-P{\'e}rez and Enrico Motta and A. Gangemi},
  Booktitle                = {Ontology Engineering in a Networked World},
  Publisher                = {Springer Berlin Heidelberg},
  Year                     = {2012},
  Note                     = {oeg},
  Pages                    = {1--6},
  Timestamp                = {2015.11.18},
  URL                      = {http://oa.upm.es/21452/}
}
```

**Comment by simonharrer** [comment]
The search does not understand latex commands. And it would require a lot of thinking and code to change that.

We are open for help with this issue.

**Comment by lenhard** [comment]
Since 3.8 (I think) we convert everything to unicode for the search, so I think this issue can be closed.
