### ISSUE TITLE
After downloading an article I can't broswe for the folder to save it.

### ISSUE THREAD

**Issue by skanskan** [JabRef/jabref#4489]
Hello.

JabRef_windows-x64_5_0-dev--snapshot--2018-11-15--master--81f15e9e6.exe
Windows 7 x64

1. Select an entry on your bibliography 
2. Go to the menu "Quality" -> "Lookup Full Text Document" 
3. If something is found  A Windows will be opened.
4. Select "Save File" 
5. The option "Browse" doesn't work.

**Comment by tobiasdiez** [comment]
When a fulltext document was found, then it should be downloaded to the default file directory and linked to the entry without showing a dialog as an intermediate step, similarily to how it works when the same action is triggered from the button next to the file field in the entry editor.

**Comment by skanskan** [comment]
But there is a button to select other folder and it doesn't work.
I think it's not an important bug but I report it.

**Comment by nmancus1** [comment]
I'd like to start on this one, @tobiasdiez.  Any tips on where to look first?

**Comment by Siedlerchr** [comment]
You could start looking in the `linkedFilesFilesEditorViewModel` there is a metho for fetching fulltext.
And otherwise I agree with @tobiasdiez  it makes sense to have the same behavior in the entry editor next ot the file field and in the menu.

And the action from the menu is probably the "FindFullTextAction" class.

**Comment by tobiasdiez** [comment]
Thanks to @nmancus1 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
