### ISSUE TITLE
 Looking up Full Text Document of multiple entries simultaneously.

### ISSUE THREAD

**Issue by skanskan** [JabRef/jabref#4490]
Hello.

JabRef_windows-x64_5_0-dev--snapshot--2018-11-15--master--81f15e9e6.exe
Windows 7 x64

The option "Quality -> Lookup Full Text Document" doesn't work if you have several entries selected, it doesn't produce any result, it only works if you go one by one.

It would be nice to be able to let Jabref find and download all possible entries at once.

PD: I've tried several times and some of them it pops up a window to download the results, but most often nothing happens.

**Comment by nmancus1** [comment]
@tobiasdiez I can take a look at this, since I was already in this class for issue #4489, and noticed the same behavior.

**Comment by tobiasdiez** [comment]
Sure, feel free to work on this issue!

**Comment by nujabse** [comment]
Is there any option to download all the papers selected asynchronously?

**Comment by Siedlerchr** [comment]
Thanks to @nmancus1  this issue is no fixed in the latest master.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
