### ISSUE TITLE
Export to clipboard: preselect last used export format

### ISSUE THREAD

**Issue by fspreng** [JabRef/jabref#4495]
When calling the export functionality of JabRef via "File"-->"Export"/"Export selected entries", the previously used export format is preselected as "Save as type" in the opening "Save as" window based on the information stored for the user preference key named "lastUsedExport". This behavior is much appreciated by my colleagues and me. When right-clicking one or multiple selected entries in the entry table and calling the export functionality via "Copy..."-->"Export to clipboard", however, the topmost instead of the last used export format is always preselected in the opening "Select export format" window. This behavior causes unnecessary additional clicks in case an export format other than the topmost one is typically chosen by the user. We would much appreciate if the preselection by the "Export to clipboard" function was the same as the one by the "Export"/"Export selected entries" function. Many thanks in advance!

**Comment by aman-coolinc1** [comment]
I would like to work on this.

**Comment by Siedlerchr** [comment]
Thanks to  @nmancus1  this issue is now fixed.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by fspreng** [comment]
Works for me. Many thanks!
