### ISSUE TITLE
Jabref freezes when selecting style in libreoffice plugin

### ISSUE THREAD

**Issue by ueberferret** [JabRef/jabref#4506]
I installed jabref 4.3 on a new windows 10 machine using the standard installer. 
I open a library, select Tools|OpenOffice/LibreOffice connection. The docker appears on the left as it should. I connect to my Libre office document. I can even insert and format citations. But as soon as I click on the "Select style" button JabRef becomes totally unresponsive. Any click or key press produces a message beep but no response. I cannot maximize, minimize or quit either. It is as if the program is in a system modal waiting state, waiting for the style selection dialog window to appear but the window never comes. 
I tried installing Jabref 4.2 but have the same problem.
Running Jabref 4.3 on my Linux box does not freeze in this way. (That has other problems. It can never remember which styles I selected. But at least it doesn't just hang). 
I suspect this is something system specific to do with the way dialog windows are created.

**Comment by ueberferret** [comment]
Update: when reinstalling jabRef with choclatey the issue goes away. IMy guess is that this is because chocolatey also installs jdk 1.8 on top of the jdk 1.11 that came with my new windows install.

**Comment by Siedlerchr** [comment]
Yes, JabRef requires java 1.8. Newer versions are currently not supported.

**Comment by oe1rsa** [comment]
The same issue happened to me today. Unfortunately installing with chocolatey didn't help.
I am running on a win7 box and my Jabref Info reads:
JabRef 4.3.1
Windows 7 6.1 amd64 
Java 1.8.0_192
Some observations: I remember it was working some days ago, and I even managed to import a *.jstyle script from my linux box to windows before it stopped working and started to freeze.

**Comment by Siedlerchr** [comment]
Please try to use the latest development version. The OO dialog is also currently reworked in #4341

**Comment by oe1rsa** [comment]
ok the freezing of the whole program stopped, but now I cannot connect to the writer nor can I open the style window. It seem as if the freezing is just of the oo pane.

**Comment by oe1rsa** [comment]
after a little more trying: behavior is almost the same as with the 4.3.1 version with the only difference that after clicking the style button just the oo pane is freezing. i.e. I can still do everything else with Jabref. 
Is there a debug log or similar available? Can I put the settings of the oo connector into some default state?

**Comment by Siedlerchr** [comment]
Hi, you can try resetting the preferences, but I am not sure if the Open Office preferences are affected then.
You could try to modify ther preferences as I outlined here:
https://github.com/JabRef/jabref/issues/3263#issuecomment-391641422

**Comment by oe1rsa** [comment]
No, unfortunately this did not help. Btw.: I am using all 64 bit. Could this be the problem?
