### ISSUE TITLE
importing preference

### ISSUE THREAD

**Issue by jhshinn** [JabRef/jabref#451]
When I import the preference.xml file made form v.2.9.2 into v.3.0, the key pattern for the BibTeX key generator does not get loaded. Can anybody check this point?

**Comment by koppor** [comment]
Reason: Internal restructuring of the code. The labels are now stored elsewhere in the Java properties, because we use a different Java package.

**Comment by stefan-kolb** [comment]
I tend to close this as wont-fix as we cannot implement migrations for every legacy version in v3.0.

**Comment by simonharrer** [comment]
I think we should handle this and make sure that the location where we store the preferences is not influenced by the package of the preferences class but a fixed value.

**Comment by stefan-kolb** [comment]
:+1:
