### ISSUE TITLE
Problem with preview DGPs (inbook, incollection)

### ISSUE THREAD

**Issue by alexteichmann79** [JabRef/jabref#4522]
JabRef version 4.3.1-jar, 5.0-dev.jar on Windows 10

- [ x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

when using the style "Deutsche Gesellschaft für Psychologie (German), the previews of the entry types inbook and incollection put the title of the book in braces after the title of the chapter. This is not standard, I think.

@InCollection{Flick2011,
  author    = {Flick, Uwe},
  title     = {Das Episodische Interview},
  booktitle = {Empirische Forschung und soziale Arbeit. Ein Studienbuch},
  date      = {2011},
  editor    = {Oelerich, Gertrud and Otto, Hans-Uwe},
  edition   = {1. Aufl},
  publisher = {{VS} Verl. für Sozialwiss},
  location  = {Wiesbaden},
  isbn      = {978-3-531-17204-0},
  pages     = {273--280},
}

 

<html><head></head><body><div class="csl-entry">Flick, U. (2011). Das Episodische Interview (Empirische Forschung und soziale Arbeit. Ein Studienbuch). In G. Oelerich &amp; H.-U. Otto (Hrsg.), <i>Empirische Forschung und soziale Arbeit. Ein Studienbuch</i> (1. Aufl., S. 273–280). Wiesbaden: VS Verl. für Sozialwiss.</div>
</body></html>

<br>

APA Style looks fine:

<html><head></head><body><div class="csl-entry">Flick, U. (2011). Das Episodische Interview. In G. Oelerich &amp; H.-U. Otto, G. Oelerich &amp; H.-U. Otto (Eds.), <i>Empirische Forschung und soziale Arbeit. Ein Studienbuch</i> (1. Aufl, pp. 273–280). Wiesbaden: VS Verl. für Sozialwiss.</div>
</body></html>

<br>

Thanks in advance

Alex Teichmann

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Hi,

thanks for noticing this. As this style is part of the CSL styles, it is an external style which we can't do anything about, JabRef just includes the style collection from the CSL repository.  So you should file an issue about the style format here: https://github.com/citation-style-language/styles
