### ISSUE TITLE
Can't import files through find unlinked files

### ISSUE THREAD

**Issue by GongSiqiu** [JabRef/jabref#4525]
JabRef 5.0-dev--snapshot--2018-11-29--master--37be33450
Linux 4.9.0-8-amd64 amd64 
Java 1.8.0_181

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Quality
2. find unlinked files
3. scan directory
4. import
Then the window will disappear and the files are not imported.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by mlep** [comment]
JabRef 5.2--2020-09-02--5c9edc9
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

Working for me.
Fixed by PR #6567 ?
