### ISSUE TITLE
Jabref freezes when selecting style in libreoffice plugin 

### ISSUE THREAD

**Issue by oe1rsa** [JabRef/jabref#4534]
JabRef version 5.0-dev on Windows (German)

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The bug has already been reported in issue #4506 but has been closed without resolution.

1. Start Jabref
2. Press Alt-0
3. Press topmost button, in German reads "Stil wählen"

Result is that the OO/libreoo pane is frozen. I can work with the rest of Jabref however.

If I never press the style button, I can connect to an OO document and I even can insert cites and sync the document. However I need to choose a different style.

**Comment by Siedlerchr** [comment]
in PR #4341 the LibreOffice/Open Office panel got reworked completely and I would like you to try out the version from here and report back if this issue is fixed: http://builds.jabref.org/ooPanel/

**Comment by oe1rsa** [comment]
The freezing has gone. I can also set a custom style and use it, but the setting is not preserved when Jabref is closed and opened again. I.e. the plugin is functional but still has issues.

Possibly a different issue or related: I still get a segmentation fault when I shut down the computer (only after the Plugin has been run, i.e. the OO panel has been opened) The Error is related to "DDE Server Window" an "unknown software exception (0x40000015) at 0xedc0eacf" (Text is not verbose since original is in German language).

**Comment by Siedlerchr** [comment]
@oe1rsa  Thanks for your feedback! I will look at this. Could you please post the whole stacktrace/error message and your LO Version? It might be the case that it is coming from the the libre office libraries.

**Comment by Siedlerchr** [comment]
Could you please try the latest snapshot?
http://builds.jabref.org/master/

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
