### ISSUE TITLE
Entry-editor typing lag

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4537]
I am experiencing terribly slow data entry in the entry-editor.  I first reported this in #4526, but I'm making a separate report here for clarity's sake.  This makes the present JabRef snapshot unusable.

JabRef 5.0-dev--snapshot--2018-12-14--master--49c3ef396
Linux 4.15.0-42-generic amd64 
Java 1.8.0_191

Both in the field-tabs, and in the biblatex area, it can take two seconds from keypress to the appearance of a single character on the screen. Needless to say, Jabref 5 is unusable until this is improved.

Autocompletion is off.

Jabref 4.3.1 works fine.

My biblatex database has about 4000 entries ([here's a link](https://www.dropbox.com/s/kqipiyq205clpgy/biblio4-utf8.bib?dl=0), if you want to examine it).  With a smaller database the typing works much better.  Still not quite at system-speed (compared against a terminal window).  But definitely in the range of normal data entry.

<details>
<summary>Detail information:</summary>

```
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
```

</details>

**Comment by wujastyk** [comment]
JabRef 5.0-dev--snapshot--2018-12-17--master--2754c2891
Linux 4.15.0-42-generic amd64 
Java 1.8.0_191

No improvement with the latest changes, unfortunately.

This [screencapture](https://www.dropbox.com/s/s374yj56dfta7ii/jabref-slowkeys.mp4?dl=0) illustrates the lag between typing and the appearance of characters on the screen.  I was whacking the keys somewhat to make sure they were audible. :-)

**Comment by wujastyk** [comment]
JabRef 5.0-dev--snapshot--2018-12-19--master--949d20496
Linux 4.15.0-43-generic amd64 
Java 1.8.0_191

So much improved!  Using 5.0 now possible again.  Thank you!

**Comment by noMICROSOFTbuhtz** [comment]
#5156

I still have this problem.
