### ISSUE TITLE
Automatically created groups: "entrytype" not working as a keyword

### ISSUE THREAD

**Issue by fspreng** [JabRef/jabref#4539]
Right now, specifying the type of an entry ("entrytype") as a keyword for the automatic generation of groups is ineffective (I also tried "type", "jabref-entrytype" and "bibtextype" as values of "Field to group by"). I tested this using the latest release as well as the current development version on both Win 7 and Win 10 (all English). For other functionalities of Jabref, e.g. the definition of displayed entry table columns, "entrytype" is a valid keyword. My colleagues and I would much appreciate if "entrytype" was also a working keyword in the case of automatically created groups. Many thanks in advance!

**Comment by tobiasdiez** [comment]
Thanks to @shahamish150294 this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by fspreng** [comment]
Works for me. Many thanks!
