### ISSUE TITLE
Downloads from arxiv saved with wrong file suffix

### ISSUE THREAD

**Issue by stefanct** [JabRef/jabref#4544]
This is with the current snapshot (JabRef 5.0-dev--snapshot--2018-12-19--master--949d20496). Opening the attached bibtex library and trying to download the respective PDF via the entry's general tab leads to a file name ending in `.01203v1` instead of `.pdf`. The contents are fine though. This is most probably due to the URL used by arxiv: `https://arxiv.org/abs/1801.01203` but that shouldn't be an excuse ;)

[arxiv.bib.txt](https://github.com/JabRef/jabref/files/2700102/arxiv.bib.txt)

**Comment by Siedlerchr** [comment]
Thanks to @stefan-kolb  this should be fixed  in the latest master.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
