### ISSUE TITLE
reset Preference or tool for clear JabRef registry

### ISSUE THREAD

**Issue by g10996694** [JabRef/jabref#455]
I noticed that when I use different versions of JabRef, some times they load different files. 
This means that different versions read perhaps different registry keys, or the jabref preference are saved in different registry locations.
on the same machine, the 3.x version preference is different to 2.x version. 
perhaps I've tested too many versions ?

Is there an option to reset JabRef preference ?
Or, perhaps it would be better a tool which deletes all previous JabRef registries.

**Comment by stefan-kolb** [comment]
You can reset the preferences by starting JabRef with `java -jar JabRef-2.11.jar --prdef all -n`.

**Comment by lenhard** [comment]
We don't really need two issues in different repositories for the very same thing, do we?

https://github.com/koppor/jabref/issues/47 is enough
