### ISSUE TITLE
Wrong bibtexkey is generated when first author uses BibTeX extended name format

### ISSUE THREAD

**Issue by douglasrizzo** [JabRef/jabref#4557]
JabRef version 4.3.1

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Have an entry in the database in which the first author name is written using the BibTeX extended name format, for example:
```
@InProceedings{Hasselt2016,
  author     = {family=Hasselt, given=Hado P., prefix=van useprefix=false and Guez, Arthur and Hessel, Matteo and Mnih, Volodymyr and Silver, David},
  title      = {Learning Values across Many Orders of Magnitude},
  booktitle  = {Advances in Neural Information Processing Systems},
  date       = {2016},
  pages      = {4287--4295},
  url        = {http://papers.nips.cc/paper/6076-learning-values-across-many-orders-of-magnitude},
  urldate    = {2017-06-07}
}
```
2. Under _Options > Preferences > BibTeX key generator_, use a key format that mentions the author name (for example, the default one `[auth][year]`);
3. Use the _Autogenerate BibTeX keys_ funcionality of JabRef.

Expected behavior: the generated `bibtexkey` would be something like `Hasselt2016` or `vanHasselt2016`.

Actual behavior: the generated `bibtexkey` is actually `2016`, ignoring the author's name.

Additional info: The BibTeX extended name format is somewhat described in section 3.8 of the [Biber manual](http://mirrors.ctan.org/biblio/biber/documentation/biber.pdf).

**Comment by Siedlerchr** [comment]
See the other issue .JabRef does not support this extended name format,
