### ISSUE TITLE
Edit entry workflow - lost focus

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4564]
JabRef 5.0-dev--snapshot--2018-12-31--master--a4e735b38
Windows 10 10.0 amd64 
Java 1.8.0_172 
on Windows 10

1. Open Jabref, select an entry under "All entries"
2. Click on any other group, entry table stays open, entry list changes
3. Click back to "All entries" -> the previously edited entry is not re-selected (or highlighted) in the entry list

Expected behaviour:

If an entry is opened for editing, it should be always highlighted in the entry list, except when it is not in the selected group. However, if you are again in the group where the entry is present, it should **highlight** the entry, and ideally the entry list should be **centered** to the edited entry (in case there are many 100s entries).

**Comment by AEgit** [comment]
I think a big problem, which might be related to this, is that the floating mode was lost in the new version:
https://github.com/JabRef/jabref/issues/4237

If the floating mode were re-introduced, this issue might solve itself (or as a consequence of it).
