### ISSUE TITLE
Automatic Bug Report - 20190105211612

### ISSUE THREAD

**Issue by SzyBer** [JabRef/jabref#4567]
JabRef 5.0-dev--snapshot--2019-01-05--master--e1cfec9c5
Windows 10 10.0 amd64 
Java 1.8.0_191

Steps to reproduce:

1. ...
2. ...
3. ...

<details>
<summary>Detail information:</summary>

```
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
```

</details>

**Comment by SzyBer** [comment]
Hi, this happens when I go to options / preferences. A couple of days ago, I was able to edit the prefrences. What happened? Best regards, Bernd

**Comment by Siedlerchr** [comment]
As I told you in the forum thread we need the whole stack trace. There have been changes to the preferences, so you might need to run `java -jar JabRef.jar -d `all to reset the prefs.

See also #4516
