### ISSUE TITLE
Key generator not so automatic

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4569]
JabRef 5.0-dev--snapshot--2019-01-05--master--e1cfec9c5
Windows 10 10.0 amd64 
Java 1.8.0_172

I have enabled the automatic key generator with the following pattern:
```
[auth:lower]_[veryshorttitle:lower]_[year]
```

Whenever I add a new entry manually, starting with entry of `Author`, then `Title`, and `Date`, the resulting key generated is always `__`. I always need to delete this in order to have the key re-generated.

What should be the desired operation is that as soon as an entry is entered, that is relevant for the bibkey generated, the key should be automatically re-generated. Even if some entry points are still missing. I am not sure though whether this re-generation should occur only one leaves a field. If the re-generation is continuous, it might cause some higher CPU usage, I assume, but it would be nice to have it continuously scanned. Another issue might be how to respect once edited keys to remain the same.

**Comment by Siedlerchr** [comment]
Do you have "Overwrite existing keys" enabled?

**Comment by DOFfactory** [comment]
Yes, under Preferences > BibTeX key generator::

- [x] Generate keys for imported entries
- [x] Warn before overwriting keys
- [ ] Do not overwrite existing keys

**Comment by tobiasdiez** [comment]
I see where you are coming from but I believe that automatically updating leads to more frustration. It's a good idea when you add new entries. However, imagine you edit older ones and then your latex build fails just because you changed a year and forgot that the bibtexkey updates automatically... For this reason, I think, editing the key should be conscious process. 

That being said, with your configuration you should be able to overwrite the key without the need to clear the field before. Is this not working for you?

**Comment by matthiasgeiger** [comment]
I agree with the reasoning of @tobiasdiez and would not like to have this "automated" key generator.

**Comment by DOFfactory** [comment]
Hi @tobiasdiez, I absolutely agree with you, bibtex keys should not change without approval of the user. 

My use-case is that the autogeneration when adding new entries does not work as it should, as after filling in the necessary entry fields all the bibtex key inserts automatically are the `_` elements, without the entry fields. 

All I had in mind is that if my BibTeX key generator is defined as follows:
```
[auth:lower]_[veryshorttitle:lower]_[year]
```

When I type in the `Author` field as AAA, the bibkey should already look like `aaa__`. When I add `Title` field s TTT, the bibkey should then look immediately as I type as `aaa_ttt_`, and adding the `Date` as 2019-01-06 would yield the bibkey as `aaa_ttt_2019` as soon as I type it in. At the moment after filling in all these fields I get only `__` as a result (please note the underscores are there 2x).

Thanks for looking into this for me.

**Comment by matthiasgeiger** [comment]
Hi @DOFfactory , 
I also get your point. 
In case of an import of a complete entry (e.g. from Websearch or by DOI/ISBN) the automated generation is already possible. However, it is hard to detect whether you are editing a "new" entry manually or an entry which BibTeX key already has been used in ia some file or not. Because this is just an "edit operation" in a bibentry.

As @Siedlerchr already mentioned: Entering the data step-by-step, than hitting `CTRL-G` once should do the trick for you. Isn't that acceptable?

**Comment by DOFfactory** [comment]
Hi @matthiasgeiger, while I see your point, would you not agree that hitting an extra `CTRL-G` goes against the whole idea of auto key generation? 

In my humble opinion, whenever one edits a field that is relevant for the bibkey field, then clicks away to another field, there is no reason why not to fill it in to the auto key generator, **if and only if there is no key present yet** for the given entry. If you want to re-genenate, the `CTRL-G` is a useful shortcut.

**Comment by matthiasgeiger** [comment]
As I usually create my entries using the 'new entry by DOI' feature I have a different workflow and do not rely on a "fully automated" key generator. And for me the 'automatic' part was only relevant for creation on import or as a "automatic creation after manual trigger", i.e., based on the settings the key is correctly determined "automatically".

However, regarding 'why not to fill it in to the auto key generator, if and only if there is no key present yet': But then again you have the problem, that as soon you have entered the author, the generator kicks in, creates a (partial) key that is then NOT overwritten automatically after adding the year as there is already a key present then. 😉

It would be possible to implement a checking logic whether a change is affecting the key and then trigger the recreation automatically, but this definitely needs to be optional and I would not spend the effort in developing it as the CTRL-G workaround is possible. But that is just my opinion.

**Comment by Siedlerchr** [comment]
I usually select all entries in my table, hit CTRL-G and that's it.

**Comment by koppor** [comment]
Good idea. Seems to be too intrusive at first. However, I like the automation. We will come back later to this topic, therefore closing adding [freeze label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Afreeze+) and closing the issue for now.
