### ISSUE TITLE
Add Key Pattern-specific Regular Expressions

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#457]
My request is to incorporate regular expressions into the key pattern dialog to modify the key patterns.  It looks like this may have been [done previously](https://github.com/korv/Jabref-plugins) when Plugins were available.  This would effectively extend the `:(x)` functionality there which only matches on null fields.

For example, I hope that the following would be a valid "Book" key pattern:

`Book_[keywords]_[year]_[authors1]_[title:regex(" ","-")]`

which would replace all spaces in the title by dashes.

**Comment by lenhard** [comment]
@jkulesza Thanks for this suggestion. You are welcome to provide a pull request.

**Comment by tobiasdiez** [comment]
This was implemented with https://github.com/JabRef/jabref/pull/3096. 
Could you please check the build from http://builds.jabref.org/master/. Thanks!
