### ISSUE TITLE
Entries can only have one group color/color information is lost when JabRef is closed

### ISSUE THREAD

**Issue by douglasrizzo** [JabRef/jabref#4574]
JabRef version 5.0

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Hello there, I am trying version 5.0 of JabRef on Manjaro Linux. I don't know how previous versions behave regarding what I am about to describe. Suppose I have a group, whose color I set to red and a subgroup, whose color I set to blue. It so happens that, when I select the subgroup, all entries are colored red and none of them are blue.

![2019-01-09-194635_682x746_scrot](https://user-images.githubusercontent.com/2209364/50931889-1fcad500-144b-11e9-83ba-2bf480b18629.png)

The behavior I expected was for entries in the subgroup to have two color bars, one red and one blue, so I am able to know all colored groups this entry is a part of.

If I save my database, close and reopen JabRef, the color for the subgroup is unset (erased from the bib file) and only the color for the supergroup remains.

![2019-01-09-194719_682x746_scrot](https://user-images.githubusercontent.com/2209364/50931901-28231000-144b-11e9-961c-333ed68702c3.png)

When trying to erase a group's color information myself, I realized there's no way to do that using the GUI. Once you set a color for a group, there's no way to erase it. Even setting the value that is in the color box by default (#FFFFFF) just paints all entries white instead of leaving them colorless. I had to delete the color value from my bib file to fix this.

For my next test, I set two different colors for two groups which have a few entries in common. First, I set one group as purple. You can see in the image below that there is a second group which has some entries that are purple.

![2019-01-09-195018_682x746_scrot](https://user-images.githubusercontent.com/2209364/50931914-2eb18780-144b-11e9-9c6c-de3b8d006907.png)

I then set the entries of this subgroup to green. All entries that were previously colorless were colored green, while the ones that were already purple remained purple.

![2019-01-09-195041_682x746_scrot](https://user-images.githubusercontent.com/2209364/50931920-32dda500-144b-11e9-8359-d9a708437e42.png)

In the purple group, which had some entries from the green group, no entries were colored green. Again, after I saved, closed and reopened JabRef, the color information from both groups was lost.

Since I observed that the purple color (which I had set first) had precedence over green, I tried to do the opposite and set the color of the green group first and then set the color for the purple group, but purple still took precedence. I believe this is because the purple group is listed first in my database and in my bib file.

From these tests, it seems to me in that entries can only have a single color. JabRef has some way of prioritizing which color to assign to an entry (supergroups first or maybe simply groups that are listed first in the groups list) and, in case the colors from two groups overlap, JabRef deletes the information regarding the color from one or both groups. At runtime, it also has some way of prioritizing which color to display, as in my second test, purple was displayed on top of green.

I believe that, if an entry is able to be represented by multiple colors, all these problems would go away.

Thanks for taking the time to read this.

**Comment by tobiasdiez** [comment]
So the TLDR is:
- [ ] Enhancement: show the color of all groups that an entry belongs to
- [ ] Bug: color information for subgroups is deleted
- [ ] Enhancement: add possibility to erase color in group edit dialog

Concerning the first point, I'm not sure what's the best way to show the color of all groups in the main table. Simply adding a colored bar for each group might work for two or three group memberships but runs into problems for more groups (just imagine 10 colored bars...). Another possibility is to segment the one bar currently shown and color each segment accordingly.

**Comment by douglasrizzo** [comment]
I think the colored bar is small enough that more bars can be added without much problem. Segmenting a single bar into 10 colors could create a visibility problem though.

Regarding the bug, it seems to happen only when two groups share some common entries.

**Comment by AEgit** [comment]
@douglasrizzo : "I think the colored bar is small enough that more bars can be added without much problem."

I disagree with this statement (@tobiasdiez already mentioned the issue): I have thousands of groups and there should be entries that are assigned to 10 groups or more. Just adding additional bars for each group would become problematic. I agree, that segmenting a single bar into 10 colours might create a visibility problem.
Potential solution (not the best, but maybe something): Have a (user-defined?) cut-off value for bars/colours displayed. If there are more colours/bars to be shown than given by the cut-off value, they will not be displayed (or only some of them will) and one bar will be added which indicates that the cut-off threshold has been exceeded.

**Comment by douglasrizzo** [comment]
Color bars can be displayed according to the width of the column that is used to display them.

**Comment by AEgit** [comment]
Yes, that would work - as long as it is clear, that some bars are not shown (due to the limited width of the column used to display them).

**Comment by JoElfner** [comment]
Any news on this? I just ran into this and it feels like a nice addition for large libraries...

**Comment by matthiasgeiger** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master.

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-28----075f191dd
Windows 10 10.0 amd64 
Java 12.0.2

As far as I can tell, this issue has been fixed in the most recent dev version.
