### ISSUE TITLE
Preview style change notification

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4580]
JabRef 5.0-dev--snapshot--2019-01-10--master--84573cc38
Windows 10 10.0 amd64 
Java 1.8.0_172

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open 2 bib files on separate tabs
2. Switch from one tab to another
3. On the bottom always a notification appears "Preview style changed to: Preview"

There should not be any such a notification _all the time_. This is not a type of notification we should be warned about every single occurrence. 

A side note: did you consider to link the notifications in Windows/macOS to Notification panel/banners?

**Comment by chelseyong** [comment]
Hi I'm interested to take up this issue. Would you like to remove the notification from the panel? 
Can I also know what is a preview style?

**Comment by Siedlerchr** [comment]
Hi thanks for your interest.
The preview style is the default style for the entry preview in the entry editor. 
In the settings you can choose from a list of styles.  
I would only print out that notification when the user cycles through the styles in the preview panel (there is a key binding) and if current style is not the same as the previous one

**Comment by DOFfactory** [comment]
I agree with @Siedlerchr, many thanks for looking into this

**Comment by chelseyong** [comment]
Sorry I am still new to this software and need some help. I can't seem to add another entry preview style under the Preferences. There is no option for me to add another preview style. 2 errors have also occurred:

While loading a new bib file:
```
[JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Could not find file: /ieee.csl
```
When attempting to change the preview style:
```
[JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
```

I am using jdk1.8.0_192. What could be the issue causing this?
Many thanks.

**Comment by Siedlerchr** [comment]
@chelseyong No problem. If you have cloned the repository then you need to  first execute 
`git submodule update --init`   because the CSL styles are integrated as a git submodule.

In the Entry Preview you can then cycle through the styles with F9.

**Comment by Siedlerchr** [comment]
Thanks to @chelseyong  this issue should be fixed in the latest master
