### ISSUE TITLE
Contrast of several UI elements is too low

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4583]
![issuecontrast](https://user-images.githubusercontent.com/26404402/51086286-505d8800-1745-11e9-84fb-dee03502c613.png)

| Description of Issue    |      Possible Solution        |  Additional Remarks |
|----------|:-------------:|------:|
|  Contrast between entry counters in sidebar and background is too low;<br>Sidebar & toolbar not visually separated;<br>Contrast between alternative rows in entry table not high enough; |  Darker background color of sidebar;<br>Darken color of entry counters to contrast of 3:1; <br>Darker alternative row background| Contrast of font should still be high enough;<br> |

**Comment by samiyac** [comment]
Hi, I'm interested in working on this issue. Where can I start?

**Comment by tobiasdiez** [comment]
Thanks to @samiyac this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
