### ISSUE TITLE
Toolbar icons and their layout need improvement

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4584]
![issueicons](https://user-images.githubusercontent.com/26404402/51086457-77b55480-1747-11e9-9768-fec9ef61f73f.png)

|                                           Description of Issue                                          |                                    Possible Solution                                   |                            Additional Remarks                           |
|:-------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------:|:-------------------------------------------------------------:|
| Some toolbar icons are too similar; <br>Icons are not structured;<br>Too much blank space;                           | Replacing similar icons;<br>Grouping icons visually;<br>More icons of commonly used functions;              | Icons need to be unambiguous;<br>Icon groups must be meaningful; |

**Comment by yurickyh** [comment]
Hi, me and my friend @kaiquekk want to start contributing to the project. Would this be a good beginners first issue?

**Comment by tobiasdiez** [comment]
Hey @yurickyh and @kaiquekk, feel free to work on this issue - it should be a good first issue. Other issues that should provide a good entry point can you find here: https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22. Also have a look at our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and  drop by in our [developer chat](https://gitter.im/JabRef/jabref) if you have questions!

**Comment by yurickyh** [comment]
Hi @tobiasdiez, thanks for your reply, so we are going to start working on this issue.

**Comment by kaiquekk** [comment]
Hi and thanks for the reply! So, we followed the prototype and have the toolbar looking like in the screenshots below. However, as we are still not very experienced, we don't know what other functions are commonly used for them to be added in the toolbar. Could you give us an example? Thank you!

![left_menu](https://user-images.githubusercontent.com/32721660/53749361-fac07480-3e85-11e9-847a-3414e1e6ba4a.jpg)
![right_menu](https://user-images.githubusercontent.com/32721660/53749368-fe53fb80-3e85-11e9-891c-66e9b4f65bd8.jpg)

**Comment by tobiasdiez** [comment]
That looks very good! Can you please open a PR with these changes? For me, this is already enough functionality in the toolbar but maybe @MartinKarim has some good suggestions what to add.

**Comment by matthiasgeiger** [comment]
One suggestion from my side: I would replace the "New article" function with the "New Entry" (as in the menu "Library" -> "New Entry"

**Comment by tobiasdiez** [comment]
@matthiasgeiger A few weeks ago, I changed it from "New entry" to "new article" based on the observation that according to the telemetry almost all created entries were articles.

**Comment by matthiasgeiger** [comment]
Uhh... okay. 

Can you distinguish how those articles are created? 
Are the users really creating "empty" articles and fill them manually?

At least I am nearly always using either a) generation via DOI or b) using web search to create new entries.

What I also do not like is that we now have an inconsistency between menu and menu bar: In "Library" exists only the "New Entry" - in the menu only "New article".

**Comment by tobiasdiez** [comment]
Yes, the data is only if the user opens the "New entry" dialog and selects one of the entry types there.
![image](https://user-images.githubusercontent.com/5037600/53838900-77427880-3f96-11e9-953f-209475866809.png).

In the longterm, I was considering to make the "New entry" button in the toolbar a dropdown button which by default creates an article but provides access to other common options (like book). Moreover, the "create by identifier"-feature should also come to the toolbar (and should probably separated from the "new empty entry" dialog).

**Comment by Siedlerchr** [comment]
For entry generation from DOI you can simply paste the doi on the maintable and a new entry will be created automatically
