### ISSUE TITLE
Rank information of entries is too prominent

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4585]
![issuerank](https://user-images.githubusercontent.com/26404402/51086516-0a55f380-1748-11e9-90b1-62a13773c02b.png)

|                                           Description of Issue                                          |                                    Possible Solution                                   |                            Additional Remarks                           |
|:-------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------:|:-------------------------------------------------------------:|
| _Rank _ information rated as unimportant in a user survey;| Remove _Rank_ column from entry list per default;| None;|

**Comment by AEgit** [comment]
Uaagg, I am completely against this, unless the _Rank_ column can still be activated afterwards. I missed the user survey but I guess people with small databases regarded the _Rank_ category as not useful. For bigger databases, however, it is definitely useful (see also my comment here: https://github.com/JabRef/jabref/issues/4669#issuecomment-465988130). If the size of the column is a problem, you could think about bringing back the old marking scheme, which allowed to assign different colours to the entries in the maintable.

**Comment by MartinKarim** [comment]
The suggestion is not to completely remove the rank information, only to remove the column by default. It could then be displayed again, by changing the _Preferences_

**Comment by AEgit** [comment]
Yes, as long as only the default is changed, I am fine with it. With my post I just wanted to emphasize that there is actual need for this column (despite the user survey). I just wanted to make sure that the column isn't dropped silently. Thanks for your help!

**Comment by Siedlerchr** [comment]
The default value in the preferences is now that the checkbox for "show rank column" is not selected and therefore the column is not shown. So nothing removed, just hidden by default. It shouln't affect your current preferences.
