### ISSUE TITLE
Institution as author name

### ISSUE THREAD

**Issue by shaftoe99** [JabRef/jabref#4590]
JabRef 5.0-dev--snapshot--2019-01-13--master--a051e1b08 Windows 10 10.0 amd64 
Java 1.8.0_192  on 

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I can enter the name of the institution like {Robert Koch Institute} and also use the formatter  to get the parenthesis in the author field with a right click. The text is than appropriately formatted. However that change cannot be saved. The text will revert to Robert Koch Institute and not be adequately cited after saving the entry.

**Comment by tobiasdiez** [comment]
Sorry, but I don't understand your problem. Can you please describe in more detail what you want to do and where the issue lies. Thanks

**Comment by shaftoe99** [comment]
Hello Tobias

thanks for your help! I'll try to rephrase it:.

I have an entry that I would like to cite  as "Robert Koch Institut" and not "Institut"

Looks like this as biblatex source.

@Article{RKI2015,
  author   = {Robert Koch Institut},
 ...
}

I can protect the field with parenthesis {Robert Koch Institut}, either manually in the source  or using the right mouse button ("Protect terms, add {} around text").

Biblatex source looks now like this: 

@Article{RKI2015,
  author   = {{Robert Koch Institut}},
 ... 
},

However, I cannot save it. After opening the data base again, the double parenthesis are gone:

  author   = {Robert Koch Institut} 
-> only single parenthesis, and the citation reverts to "Institut"

Does that explain it better?

Thanks in advance!

**Comment by shaftoe99** [comment]
Sorry, issue is still open

**Comment by shaftoe99** [comment]
Hello Tobias

thanks for your help! I'll try to rephrase it:.

I have an entry that I would like to cite as "Robert Koch Institut" and not "Institut"

Looks like this as biblatex source.

@Article{RKI2015,
author = {Robert Koch Institut},
...
}

I can protect the field with parenthesis {Robert Koch Institut}, either manually in the source or using the right mouse button ("Protect terms, add {} around text").

Biblatex source looks now like this:

@Article{RKI2015,
author = {{Robert Koch Institut}},
...
},

However, I cannot save it. After opening the data base again, the double parenthesis are gone:

author = {Robert Koch Institut}
-> only single parenthesis, and the citation reverts to "Institut"

Does that explain it better?

Thanks in advance!

**Comment by Siedlerchr** [comment]
Do you have any save actions configured?

Open the bib file in a text editor and scroll to the end and check if there are any formatters listed

**Comment by Siedlerchr** [comment]
@shaftoe99  Yes, the culprit is latex2unicode who unfortunately kills the braces around corporate authors.  See #4152  
Either you change all your save actions (replace "enabled" with disabled) o9r you remove the all-text-fields formatter line.
So this is not a bug, but just more or less a problem known of the latex2unicode formatter.
