### ISSUE TITLE
Add check for books with first edition

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4591]
**Is your suggestion for improvement related to a problem? Please describe.**
Some journals have the convention to only print the edition of a book if it's not the first. (It's hard to find a reliable source on this, but see e.g [here on p. 19](https://www.otago.ac.nz/library/pdf/Harvard_referencing.pdf))

**Describe the solution you'd like**
Have an integrity check that reports books with `edition = 1`

**Comment by RonakLakhotia** [comment]
I would like to give this a try!

**Comment by Siedlerchr** [comment]
@RonakLakhotia  Sure, go ahead! As a starting point, you can look at the IntegrityChecker classes:
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/integrity/IntegrityCheck.java

**Comment by RonakLakhotia** [comment]
Is the solution, creating a predicate to check if the edition = 1 as given in :-
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/integrity/EditionChecker.java

**Comment by tobiasdiez** [comment]
Yes, it should suffice to add a simple `if (value = "1") then return warning` statement. Please also write a simple test similar to these here: https://github.com/JabRef/jabref/blob/master/src/test/java/org/jabref/logic/integrity/PagesCheckerBibLatexTest.java. Thanks!
