### ISSUE TITLE
Overlapping font in "ID Type" field when adding DOI or ISBN etc

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4593]
JabRef version 
JabRef 5.0-dev--snapshot--2019-01-13--master--a051e1b08
Linux 4.15.0-43-generic amd64 
Java 1.8.0_191

Steps: 

1. open JabRef
2. select Library
3. select New Entry (or ctrl+N)

display spacing of the "ID Type" identifier field is poor as in attached image below:

![screenshot from 2019-01-17 13-10-18](https://user-images.githubusercontent.com/762246/51345962-9eca9980-1a59-11e9-9574-b6a622b9c0f5.png)

**Comment by Siedlerchr** [comment]
Should be fixed now in the development version in a couple of minutes

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
