### ISSUE TITLE
JabRef 5.* (dev) with Debian stable

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#4597]
For months I am not able to start JabRef 5.* (dev version) on Debian stable.
I also reported that problem on the [forum](http://discourse.jabref.org/t/jabref-5-with-debian-9-stable/1400).

The last version I tried was `JabRef-5.0-dev--snapshot--2019-01-21--master--40d049e08.jar`.
```

$ java ./JabRef-5.0-dev--snapshot--2019-01-21--master--40d049e08.jar
Fehler: Hauptklasse ..JabRef-5.0-dev--snapshot--2019-01-21--master--40d049e08.jar konnte nicht gefunden oder geladen werden

```

Some version informations
```
$ uname -a
Linux TONNE 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

$ sudo update-alternatives --config java
[sudo] Passwort für user: 
Es gibt nur eine Alternative in Link-Gruppe java (die /usr/bin/java bereitstellt): /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
Nichts zu konfigurieren.

$ sudo apt install openjfx
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
openjfx ist schon die neueste Version (8u171-b11-2+b1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

```

**Comment by drcicero** [comment]
Hi! I had a similar error on Ubuntu with some version of JabRef. Would `java --module-path /usr/share/openjfx/lib/ --add-modules=javafx.controls -jar JabRef.jar` work for you?

**Comment by noMICROSOFTbuhtz** [comment]
The current dev works.

`java -jar JabRef*2019-02-19*jar`

But it could be the `-jar` switch. What makes no sense. I give a jar file to `java` so why should I explicite use such a switch?

**Comment by Siedlerchr** [comment]
> 
> 
> The current dev works.
> 
> `java -jar JabRef*2019-02-19*jar`
> 
> But it could be the `-jar` switch. What makes no sense. I give a jar file to `java` so why should I explicite use such a switch?

Because this is the way how java is designed. It has been since forever the way to run jar files.
The normal java command without any parameters expects a *.class file with the name you specify. In a jar file multiple class files are combined, so you need to specify that you want to run the classes inside of the jar file.
