### ISSUE TITLE
v5.0: duplicates window totally empty (except buttons at the bottom)

### ISSUE THREAD

**Issue by schniepp** [JabRef/jabref#4598]
JabRef version JabRef 5.0-dev--snapshot--2019-01-21--master--40d049e08 on Ubuntu 16.04

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open any database
2. Select an entry and copy & past the same entry, so that a duplicate is created
3. Click Quality => Find duplicates
4. The duplicate window is totally empty, no boxes or text showing up. Only the buttons at the bottom show. (If I try the same thing in v 4.3.1 it works as expected; two duplicates are showing in the left and right halves for the window.)

No errors are showing up in the console when starting from command line.

**Comment by Siedlerchr** [comment]
Working on this, could you please do me a favor and add a screenshot of the dialog in 4.3.1? That helps me to convert the dialog.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by schniepp** [comment]
@Siedlerchr 
I just tested this with the latest development version (which I always do), and it works now! Thank you so much for looking into this and fixing this!
By the way, I am so sorry I was not able to provide that screenshot for you. I was extremely busy at work in the past day. Hadn't forgotten about it but simply didn't get a chance. 
Cheers, H.

**Comment by Siedlerchr** [comment]
@schniepp  No worry, I found an old screenshot in the help. Now as the dialog is converted, it would be nice if you could update the screenshots in the help ;)
Just go to the bottom of the site (Edit this page)
http://help.jabref.org/en/FindDuplicates

**Comment by Siedlerchr** [comment]
I replaced the screenshots. The way you could have done this would have been to drag and drop the files ti upload and then create PR.

The bibtex source code is no longer present. Seems it got lost in #4410 or was not converted on purpose, probably to avoid problems as the source field is a bit complicated.
I think it is not really necessary to have the source view, so I remove that screenshot.
