### ISSUE TITLE
New entry default cursor location

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4600]
JabRef 5.0-dev--snapshot--2019-01-21--master--40d049e08
Windows 10 10.0 amd64 
Java 1.8.0_172

Issue:
1. Copy a DOI number from any website
2. Switch to Jabref, hit Ctrl-N for a New Entry window
3. There is no cursors, so one cannot hit just simply Ctrl-V copying in the DOI number

Solution:
Make the cursor by default in the ID text field. There is anyway no other place where the cursor should be active in that overlay window. This would enhance greatly the workflow and usability.

**Comment by tobiasdiez** [comment]
Thanks to @chelseyong this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
