### ISSUE TITLE
The program for opening the PDF file hangs after a while

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#4606]
JabRef 5.0-dev--snapshot--2019-01-23--master--c6a1fcbe3
Linux 4.15.0-43-generic amd64 
Java 1.8.0_201
1. from the list of publications, chose any that has a PDF stored on the local file system
2. right click and choose "Open file"
3. The PDF file is shown using evince or okular (whatever I have configured)
4. After a while (can be seconds or minutes) the program (okular or evince) freezes up and becomes non-responsive. While the program is not responding or repainting its window, jabref is still responsive
5. The only way to proceed is to kill the viewer program

This essentially makes it impossible to read my library via JabRef. I have tried with evince and okular 
(entry in the config file is `<entry key="usePDFReader" value="/usr/bin/okular"/>`)

**Comment by johann-petrak** [comment]
OK, I think the relevant setting is `<entry key="externalFileTypes" value="PDF:pdf:application/pdf:/usr/bin/okular:PDF_FILE"/>` (what does the usePDFReader setting actually do?).
And when I changed that one in the settings, so far no hang occurred, so it may be somehow related to using evince in there.

**Comment by tobiasdiez** [comment]
That sounds strange. In the end, JabRef only invokes the command `/usr/bin/okular pathToPdfFile`. I don't see why this should lead to to a freeze of okular or evince. 

The `usePDFReader` key is only used to provide the correct command line arguments for some PDF viewers that need special treatment (e.g. Adobe reader).

**Comment by stefan-kolb** [comment]
I think we need more info to reproduce this issue. Please reopen if the problem persists.

**Comment by nickorlov** [comment]
Support! If I open pdf file (size 54,5 MB), after few hours Document Viewer freezes.
