### ISSUE TITLE
Preview not configurable

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4609]
JJabRef 5.0-dev--snapshot--2019-01-23--master--c6a1fcbe3
Windows 7 6.1 amd64 
Java 1.8.0_201

- [+ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open jabref and select an entry in the maintable
2. press ALT-2 twotimes to show entry preview
3. Goto OPTIONS->PREFERENCES->ENTRY PREVIEW 
4. Select e.g. BIOLOGICA and view it in TEST
5. double click BIOLOGICA and 
6. surprisingly you are back to the default preview 

Screenshot of the desired preview
![grafik](https://user-images.githubusercontent.com/9216487/51740712-11102f00-2095-11e9-8e56-fcce88aea3fa.png)

Screenshot of the default preview
![grafik](https://user-images.githubusercontent.com/9216487/51740866-8c71e080-2095-11e9-9047-645a83949274.png)

<details>
  <summary>Log File</summary>
  Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20171208VS5.0.bib
Can only load style files: Preview
Can only load style files: Preview
Can only load style files: Preview
Can only load style files: Preview
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
@chelseyong  You recently worked at this in #4587 Could you please take a look at this issue?
