### ISSUE TITLE
full text crawler enhancements

### ISSUE THREAD

**Issue by jhshinn** [JabRef/jabref#461]
Please add some more publishers to the full text crawlers.
IOPScience http://iopscience.iop.org/
Wiley http://onlinelibrary.wiley.com/
edp sciences http://publications.edpsciences.org/

Actually, it would be great if the crawler access all the publishers included in this database. :smile: 
http://ads.harvard.edu/
see also http://adsabs.github.io/help/

**Comment by oscargus** [comment]
Some comments so far:

Wiley supports Z39.50

"This service is freely available and does not require a subscription. It is not necessary to register your server or IP addresses with Wiley Online Library.

The URL to connect to Wiley’s Z39.50 service is:

onlinelibrary.wiley.com:210
or
tcp:onlinelibrary.wiley.com:210"

A Java Z39.50 toolkit is available at http://sourceforge.net/projects/jzjkit/

A very good overview of different resources and APIs are available at http://libguides.mit.edu/apis

**Comment by oscargus** [comment]
EDP seems to support OAI: http://publications.edpsciences.org/oai-pmh-and-edp-sciences

ADS API: https://github.com/adsabs/adsabs-dev-api

**Comment by stefan-kolb** [comment]
What I want to note here is that we have to think about whether it is beneficial to add a new publisher because papers cannot be retrieved elsewhere. For example I think it makes no sense to include publishers that are open access and all papers can be grabbed by the GoogleScholar anyway.

**Comment by oscargus** [comment]
You are correct, but I think I was primarily thinking of search facilities, not crawlers (opposed to the subject of the issue, I admit...).

**Comment by jhshinn** [comment]
@stefan-kolb @oscargus I'm sorry that I didn't clearly describe what I want. The full-text crawler doesn't work for some paper as I expect.
Some *open-access* and *subscription-required* articles couldn't be downloaded from the original publishers. When it has an arXiv version, it downloads from arXiv. (I want to download the article from the original publishers rather than arXiv.)
I've made an example bib file below. It would be great if any of you check whether the crawler works properly. Open-access articles are tagged with *[Free]* in their titles.
https://dl.dropboxusercontent.com/u/60311114/temp.bib

**Comment by stefan-kolb** [comment]
Your right it doesn't download from the original publishers. It just follows this list of downloaders and checks whether it could find the correct paper.
```
        finders.add(new ScienceDirect());
        finders.add(new SpringerLink());
        finders.add(new ACS());
        finders.add(new ArXiv());
        finders.add(new GoogleScholar());
```
The only thing we could do about this is to try to find the original publisher via following the doi and checking the URL of the target site and then try to prioritze a crawler if it matches for the site.
However, this is probably error-prone and only works when a doi is present. 
Or looking for IEEE/ACM values inside the entry data.
Except from that, I don't see any other good approach to infer the publisher from the entry data.

The question is how much benefits come from implementing such a guessing technique and how much complexity/effort it introduces.

**Comment by jhshinn** [comment]
@stefan-kolb Thanks a lot for your quick and detailed explanation. I see what's going on inside the crawler. But I'd like to mention that, as you may know, the plugin "LocalCopy" seamlessly downloads the articles from the original publishers. I hope the same feature will be provided in version 3 or higher. :wink:

**Comment by stefan-kolb** [comment]
Does localcopy download from more publishers than arxiv? I took a quick look and it looks like the plugin just tries to find a pdf file link on the redirected doi url. On the one hand this might help to get the pdf from the authorative publisher but it might also download the wrong pdf. it might just be a random pdf link on the site. the current algorithm only downloads pdfs that are tagged with the doi. Still an interesting idea to think about!

**Comment by jhshinn** [comment]
@stefan-kolb As you may know, LocalCopy has two buttons---arXiv and Journal. When I push the Journal button, sometimes it shows a pop-up window to choose one among several pdf files. Now I understand why I had to choose one in the pop-up window. Thanks-

**Comment by stefan-kolb** [comment]
@jhshinn The latest build of JabRef http://builds.jabref.org/master/ now has a new fetcher that tries to download directly from the publisher at first (similar to LocalCopy). It only succeeds when there is just one PDF link on the site, but this should handle quite a few of your described problems.

**Comment by jhshinn** [comment]
@stefan-kolb Great! :+1:  I've found that it works as you described. Thanks a lot for the job-

**Comment by stefan-kolb** [comment]
@jhshinn Good to hear :smile:
