### ISSUE TITLE
Group window size and font inconsistency

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4610]
JabRef 5.0-dev--snapshot--2019-01-24--master--48c5a20fd
Windows 10 10.0 amd64 
Java 1.8.0_172

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open a new group
2. The window, if keyword is being defined, opens a lengthy description that extends the HIDPI (4K) size of the screen resolution, pushing the `OK` and `Cancel` buttons off the screen
3. In addition, there is also an inconsistency in the font style and font size (see attached picture)

![group window font](https://user-images.githubusercontent.com/10846169/51741869-57b35880-2098-11e9-9ee6-b7768cef4f00.jpg) 

Please, correct (or eventually remove) the expansion of Description area, rendering the OK and Cancel buttons consistently on the screen.

**Comment by tobiasdiez** [comment]
The description is currently rendered using html (if I'm not mistaken). The best solution is probably to use a TextFlow control instead.

**Comment by tobiasdiez** [comment]
Thanks to @LeonhardWolz this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by DOFfactory** [comment]
Looks great, thanks!
