### ISSUE TITLE
Web search font size inconsistency

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4611]
JabRef 5.0-dev--snapshot--2019-01-24--master--48c5a20fd
Windows 10 10.0 amd64 
Java 1.8.0_172

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open a Web search on a HiDPI display (4K)
2. The fonts are super-small, making the search results almost impossible to read

![web search font size](https://user-images.githubusercontent.com/10846169/51742199-59c9e700-2099-11e9-975d-20a3bb4620a4.jpg)

Please correct this consistenlty throughout JabRef, other pop-up windows still have this issue as well (except the Preferences window).

**Comment by Siedlerchr** [comment]
That will be automatically fixed once the import inspection dialog is converted to JavaFX. 
 There are still a few dialogs that have not yet been converted and therefore do not scale well in high dpi.
See issue #3861 for an overview
