### ISSUE TITLE
General fields layout: url and doi missing

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4612]
Default layout does not contain the fields url;doi;arxiv; and so on:

**Comment by tobiasdiez** [comment]
Applies only to bibtex I think

**Comment by Siedlerchr** [comment]
This should be a preferences issue onlly as it can be configured via Options -> Setup General fields

**Comment by stefan-kolb** [comment]
This has really hight priority as we do every fetching based on the DOI fields!

**Comment by stefan-kolb** [comment]
> Applies only to bibtex I think

Applies to both modes as far as I can see.
