### ISSUE TITLE
BibTexKey Duplicate Check throws NPE 

### ISSUE THREAD

**Issue by rvb-033** [JabRef/jabref#4614]
JabRef version  on 

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by rvb-033** [comment]
Good afternoon,
I received the appended windows and error log while opening my data base.
I think the issue is linked with an attempt from JabRef to resolve duplicated keys.
Regards,
Hervé
[Pb JabRef.txt](https://github.com/JabRef/jabref/files/2799061/Pb.JabRef.txt)
![pb jabref](https://user-images.githubusercontent.com/20064725/51788222-c9180780-217b-11e9-9448-d4e5fb5223df.png)

**Comment by Siedlerchr** [comment]
We decided to remove this dialog as the feature is already covered in the integrity check and will be covered in the import dialog
