### ISSUE TITLE
Action to open console in folder which contains .bib file

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#462]
I always have my .bib files under version control with git. Because of this, I often have to open a console in the folder with the .bib file. If I could open a console right from JabRef, this would be nice, helping me to commit my changes faster.

**Comment by koppor** [comment]
Code hint: "Open folder".

Featurewish: configurable console application such as [ConEmu](http://conemu.github.io/).

**Comment by mairdl** [comment]
The JabRef StuPro feature team will take care of this issue.

**Comment by obraliar** [comment]
The primary branch for this issue is located at https://github.com/obraliar/jabref/tree/OpenConsoleFeature

**Comment by koppor** [comment]
Thank you for lettings us know. Please open a pull request if you want us to look into code. :innocent: This also allows @JabRef/stupro-qa to look into and to help avoiding git pitfalls such as starting at the wrong commit.

**Comment by obraliar** [comment]
Now the feature is working on all supported operating systems :) You can start it with a mouse-click on the apropriate button (see image) or by using the shortcut CTRL+SHIFT+J.
![jabref_open_console_feature](https://cloud.githubusercontent.com/assets/15609468/13709271/4e9e232c-e7b3-11e5-9e6b-da3dd189102b.jpg)

Consider that a new terminal can be opened only if your database file is opened and saved.

**Comment by obraliar** [comment]
Can be closed.

**Comment by matthiasgeiger** [comment]
:+1: Implemented in #931
