### ISSUE TITLE
What happened with the development branch?

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4625]
I cannot access nor can I download the development branch anymore (see attached screenshot):

![jabref dev](https://user-images.githubusercontent.com/10846169/52178769-905adc80-27d2-11e9-9bd2-012a41061df4.png)

**Comment by Siedlerchr** [comment]
Hmm thanks for mentioning this issue, it was definitely working a couple of days ago

**Comment by Siedlerchr** [comment]
Seems like someone cleaned up all branches on the build portal. I ran the master build again and it should now be up again:
https://builds.jabref.org/master/
