### ISSUE TITLE
Can't save new content selectors

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4628]
Current master.
Options -> Manage content selectors
Enter new field and new keyword,
press apply or enter 

Is still a swing dialog.  Refs #3861 

```

17:00.740 [AWT-EventQueue-0] INFO  org.jabref.gui.contentselector.ContentSelectorDialog - Could not apply changes in "Manage content selectors" - java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113) 
```

**Comment by ricantech** [comment]
Hi, if not urgent I can take a look on this :)

**Comment by Siedlerchr** [comment]
@ricantech  Thanks for your interest. The solution would be to simply convert the dialog to javaFX like the other dialogs. Maybe you can also optimize the layout of the dialog. You can start with the scene builder

**Comment by ricantech** [comment]
Hi, here is just design proposal - https://github.com/ricantech/jabref/commit/a34a926ac5ed22f3bd658893632f96d898b61952

![image](https://user-images.githubusercontent.com/5075491/52658289-fb0ac700-2efa-11e9-8cf7-1ed18c85ed40.png)

**Comment by tobiasdiez** [comment]
@ricantech Thanks for working on this! The design looks good to me. The only suggestion I have is to maybe move the buttons to the right of the list (or below it), because the "Remove" action only makes sense if you first select an entry in the list and the usual flow should be from the right to the left.
Please also add the `%` sign in front of the other texts. This looks strange in the preview, but in the real application these strings are then automatically translated correctly.

**Comment by ricantech** [comment]
@tobiasdiez @Siedlerchr Hi guys, just a minor question. I would like to enable the menu item only when there is existing database connection. From my understanding I should add my action into org.jabref.gui.JabRefFrame#openDatabaseOnlyActions but this enable/disable logic is being called from org.jabref.gui.JabRefFrame#initActions which logic is commented at all so it will be never called.
Another option would be to reuse org.jabref.gui.actions.OldDatabaseCommandWrapper but not sure whether this is good approach as from the name I would say it's some old logic which was/will be replaced.

Can you give me a hint :) ?

**Comment by tobiasdiez** [comment]
That's a good observation. As of now, all menu items are always activated even if they don't make sense in the given moment. Previously, the activation/deactivation was handled by the `JabRefFrame` (using the commented-out code). In the new framework, every action (or to be more precise every `Command`) has control over its status by using the `executable` property, see e.g
https://github.com/JabRef/jabref/blob/7b784586364cd804110fa740125218a942ed7c5a/src/main/java/org/jabref/gui/actions/SimpleCommand.java#L23-L25
So binding the `executable` property to the correct condition should work.
As I said above, we need to revisit every menu item and implement a corresponding check, so it's totally fine if you omit this step at the moment from your PR.

**Comment by tobiasdiez** [comment]
Thanks to @ricantech this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
