### ISSUE TITLE
Improve telemetry collection

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4629]
At the moment, mostly user actions involving dialogs are tracked. It would be nice to include also other interactions (especially button presses and tab changes in the entry editor).

This amounts to adding code similar to the following one in the appropriate places:
https://github.com/JabRef/jabref/blob/b411cfbb1c60af09052e17d1780f1cdb770bc4ef/src/main/java/org/jabref/gui/actions/JabRefAction.java#L36-L39

**Comment by DhruvThakker** [comment]
I would like to work on this

**Comment by tobiasdiez** [comment]
@DhruvThakker Sure, feel free to work on this issue! Also have a look at our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and drop by in our [developer chat](https://gitter.im/JabRef/jabref) if you have questions!

**Comment by guozix** [comment]
Where were these tracking infomations saved? In format of log or something else?  I have set up environment and take some actions on the software, and saved a bibtex database. The saved file only contains the information of the database. And I don't find any sign in the code. Hope for some hint.

**Comment by Siedlerchr** [comment]
@guozix  Hi thanks for your interest. The Telemetry data is logged using [Microsoft Azure Application insights](https://docs.microsoft.com/de-de/azure/azure-monitor/app/app-insights-overview)

It's only avaiable to the core developers.  It allows to see e.g. what kind dialogs are used how often:
![grafik](https://user-images.githubusercontent.com/320228/61719533-650a8080-ad65-11e9-8aa3-55e458fe1ab5.png)


https://github.com/JabRef/jabref/blob/8777c16a99bd83e4a30ddafc859c0c2208b68733/src/main/java/org/jabref/gui/logging/ApplicationInsightsAppender.java

**Comment by ffffatgoose** [comment]
Sorry to disturb again, what does the Telemetry data focus on, the action client made or the function we run? For example, there is an undo button and also an undo section in the toolbar, is it necessary to distinguish them in the saved telemetry log data? Thanks for your comment.

**Comment by tobiasdiez** [comment]
The telemetry data should reflect the user actions so that we can for example see if users use the toolbar to do x but prefer the menu for y.

**Comment by ffffatgoose** [comment]
I get it now. our group is trying to solve the issue these days……thanks for answering.

**Comment by ffffatgoose** [comment]
![图片](https://user-images.githubusercontent.com/44337029/61861890-6ff91880-aeff-11e9-800d-026d0125b0d9.png)
![图片](https://user-images.githubusercontent.com/44337029/61861954-9323c800-aeff-11e9-9f68-60eedb6d7ed1.png)
This example can show the user made same action by different ways. This is only an example for test. So is there any grammar for the telemetry data? Or do I need to change the description for showing the ways

**Comment by tobiasdiez** [comment]
This looks good! So far we don't have any conventions concerning the name of the action. It would probably be a good idea to introduce a new enum for all the possible events (to collect and unify them).

**Comment by ffffatgoose** [comment]
That's a good idea, but I find some problem in distinguish the action between undo, redo…… Their telemetry data appear the same:"OldDatabaseCommandWrapper FromButton(or Menu)" I'm trying to distinguish them……

**Comment by ffffatgoose** [comment]
#5150 hoping for merge if you pleased :)
