### ISSUE TITLE
Jabref (dev) : running .:gradlew assemble with ubuntu 18.04

### ISSUE THREAD

**Issue by BGhass** [JabRef/jabref#4643]
JabRef on Ubuntu 18.04

I imported the last source code of the master branch in my IDE (intellij), and I ran the 'gradlew assemble' command. I had the following errors (Log file).
I guess that I have a problem with the gradle version and some dependencies but I can't solve it.

<details>
  <summary>Log File</summary>
  

> Task :generateBstGrammarSource UP-TO-DATE
> Task :generateSearchGrammarSource UP-TO-DATE
> Task :generateSource UP-TO-DATE
> Task :xjc UP-TO-DATE

> Task :compileJava
plug-in not found: ErrorProne
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/actions/JabRefAction.java:11: error: cannot access EventHandler
class JabRefAction extends org.controlsfx.control.action.Action {
^
  class file for javafx.event.EventHandler not found
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/icon/JabRefIconView.java:9: error: cannot access Text
public class JabRefIconView extends GlyphIcon<IconTheme.JabRefIcons> {
       ^
  class file for javafx.scene.text.Text not found
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/autocompleter/AutoCompletionTextInputBinding.java:45: error: cannot access EventTarget
public class AutoCompletionTextInputBinding<T> extends AutoCompletionBinding<T> {
       ^
  class file for javafx.event.EventTarget not found
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/preferences/GeneralTab.java:29: error: static import only from classes and interfaces
import static javafx.beans.binding.Bindings.not;
^
Processing annotations
Annotations processed
Processing annotations
No elements to process
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/JabRefGUI.java:9: error: package javafx.scene does not exist
import javafx.scene.Scene;
                   ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/JabRefGUI.java:10: error: package javafx.stage does not exist
import javafx.stage.Stage;
                   ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:24: error: package javafx.application does not exist
import javafx.application.Platform;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:25: error: package javafx.beans.value does not exist
import javafx.beans.value.ChangeListener;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:26: error: package javafx.beans.value does not exist
import javafx.beans.value.ObservableValue;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:27: error: package javafx.collections does not exist
import javafx.collections.ListChangeListener;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:28: error: package javafx.scene does not exist
import javafx.scene.Node;
                   ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:29: error: package javafx.scene.control does not exist
import javafx.scene.control.Alert;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:30: error: package javafx.scene.control does not exist
import javafx.scene.control.Button;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:31: error: package javafx.scene.control does not exist
import javafx.scene.control.ButtonBar;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:32: error: package javafx.scene.control does not exist
import javafx.scene.control.ButtonType;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:33: error: package javafx.scene.control does not exist
import javafx.scene.control.Menu;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:34: error: package javafx.scene.control does not exist
import javafx.scene.control.MenuBar;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:35: error: package javafx.scene.control does not exist
import javafx.scene.control.ProgressBar;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:36: error: package javafx.scene.control does not exist
import javafx.scene.control.SeparatorMenuItem;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:37: error: package javafx.scene.control does not exist
import javafx.scene.control.SplitPane;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:38: error: package javafx.scene.control does not exist
import javafx.scene.control.Tab;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:39: error: package javafx.scene.control does not exist
import javafx.scene.control.TabPane;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:40: error: package javafx.scene.control does not exist
import javafx.scene.control.TextInputControl;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:41: error: package javafx.scene.control does not exist
import javafx.scene.control.ToolBar;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:42: error: package javafx.scene.control does not exist
import javafx.scene.control.Tooltip;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:43: error: package javafx.scene.input does not exist
import javafx.scene.input.DataFormat;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:44: error: package javafx.scene.input does not exist
import javafx.scene.input.KeyEvent;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:45: error: package javafx.scene.input does not exist
import javafx.scene.input.TransferMode;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:46: error: package javafx.scene.layout does not exist
import javafx.scene.layout.BorderPane;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:47: error: package javafx.scene.layout does not exist
import javafx.scene.layout.HBox;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:48: error: package javafx.scene.layout does not exist
import javafx.scene.layout.Pane;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:49: error: package javafx.scene.layout does not exist
import javafx.scene.layout.Priority;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:50: error: package javafx.stage does not exist
import javafx.stage.Stage;
                   ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:51: error: package javafx.util does not exist
import javafx.util.Duration;
                  ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:147: error: cannot find symbol
public class JabRefFrame extends BorderPane implements OutputPrinter {
                                 ^
  symbol: class BorderPane
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/DialogService.java:10: error: package javafx.concurrent does not exist
import javafx.concurrent.Task;
                        ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/DialogService.java:11: error: package javafx.print does not exist
import javafx.print.PrinterJob;
                   ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/DialogService.java:12: error: package javafx.scene.control does not exist
import javafx.scene.control.Alert;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/DialogService.java:13: error: package javafx.scene.control does not exist
import javafx.scene.control.ButtonType;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/DialogService.java:14: error: package javafx.scene.control does not exist
import javafx.scene.control.ChoiceDialog;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/DialogService.java:15: error: package javafx.scene.control does not exist
import javafx.scene.control.DialogPane;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/DialogService.java:16: error: package javafx.scene.control does not exist
import javafx.scene.control.TextInputDialog;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/JabRefGUI.java:50: error: cannot find symbol
    public JabRefGUI(Stage mainStage, List<ParserResult> argsDatabases, boolean isBlank) {
                     ^
  symbol:   class Stage
  location: class JabRefGUI
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/JabRefGUI.java:67: error: cannot find symbol
    private void openWindow(Stage mainStage) {
                            ^
  symbol:   class Stage
  location: class JabRefGUI
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/JabRefGUI.java:199: error: cannot find symbol
    private void saveWindowState(Stage mainStage) {
                                 ^
  symbol:   class Stage
  location: class JabRefGUI
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:153: error: cannot find symbol
    private static final Duration TOAST_MESSAGE_DISPLAY_TIME = Duration.millis(3000);
                         ^
  symbol:   class Duration
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:155: error: cannot find symbol
    private final SplitPane splitPane = new SplitPane();
                  ^
  symbol:   class SplitPane
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/preferences/JabRefPreferences.java:38: error: package javafx.scene.control.TableColumn does not exist
import javafx.scene.control.TableColumn.SortType;
                                       ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:10: error: package javafx.animation does not exist
import javafx.animation.KeyFrame;
                       ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:11: error: package javafx.animation does not exist
import javafx.animation.KeyValue;
                       ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:12: error: package javafx.animation does not exist
import javafx.animation.Timeline;
                       ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:13: error: package javafx.beans.binding does not exist
import javafx.beans.binding.Bindings;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:14: error: package javafx.css does not exist
import javafx.css.PseudoClass;
                 ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:15: error: package javafx.event does not exist
import javafx.event.Event;
                   ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:16: error: package javafx.geometry does not exist
import javafx.geometry.Orientation;
                      ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:17: error: package javafx.geometry does not exist
import javafx.geometry.Pos;
                      ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:19: error: package javafx.scene.control does not exist
import javafx.scene.control.Button;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:20: error: package javafx.scene.control does not exist
import javafx.scene.control.ContentDisplay;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:21: error: package javafx.scene.control does not exist
import javafx.scene.control.Label;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:22: error: package javafx.scene.control does not exist
import javafx.scene.control.ListView;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:23: error: package javafx.scene.control does not exist
import javafx.scene.control.Separator;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:24: error: package javafx.scene.control does not exist
import javafx.scene.control.Skin;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:25: error: package javafx.scene.control does not exist
import javafx.scene.control.TextField;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:26: error: package javafx.scene.control does not exist
import javafx.scene.control.ToggleButton;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:27: error: package javafx.scene.control does not exist
import javafx.scene.control.ToolBar;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:28: error: package javafx.scene.control does not exist
import javafx.scene.control.Tooltip;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:29: error: package javafx.scene.control.cell does not exist
import javafx.scene.control.cell.TextFieldListCell;
                                ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:30: error: package javafx.scene.input does not exist
import javafx.scene.input.KeyEvent;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:31: error: package javafx.scene.input does not exist
import javafx.scene.input.MouseButton;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:32: error: package javafx.scene.layout does not exist
import javafx.scene.layout.BorderPane;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:33: error: package javafx.scene.layout does not exist
import javafx.scene.layout.HBox;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:34: error: package javafx.scene.layout does not exist
import javafx.scene.layout.Priority;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:35: error: package javafx.scene.text does not exist
import javafx.scene.text.TextFlow;
                        ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:36: error: package javafx.util does not exist
import javafx.util.Duration;
                  ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/search/GlobalSearchBar.java:67: error: cannot find symbol
public class GlobalSearchBar extends HBox {
                                     ^
  symbol: class HBox
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:159: error: cannot find symbol
    private final ProgressBar progressBar = new ProgressBar();
                  ^
  symbol:   class ProgressBar
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/menus/FileHistoryMenu.java:6: error: package javafx.scene.control does not exist
import javafx.scene.control.Menu;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/menus/FileHistoryMenu.java:7: error: package javafx.scene.control does not exist
import javafx.scene.control.MenuItem;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/menus/FileHistoryMenu.java:16: error: cannot find symbol
public class FileHistoryMenu extends Menu {
                                     ^
  symbol: class Menu
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:174: error: cannot find symbol
    private final Stage mainStage;
                  ^
  symbol:   class Stage
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:177: error: cannot find symbol
    private TabPane tabbedPane;
            ^
  symbol:   class TabPane
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/SidePane.java:6: error: package javafx.scene.layout does not exist
import javafx.scene.layout.VBox;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/SidePane.java:11: error: cannot find symbol
public class SidePane extends BorderPane {
                              ^
  symbol: class BorderPane
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:183: error: cannot find symbol
    public JabRefFrame(Stage mainStage) {
                       ^
  symbol:   class Stage
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:595: error: cannot find symbol
    private Node createToolbar() {
            ^
  symbol:   class Node
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:22: error: package javafx.application does not exist
import javafx.application.Platform;
                         ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:23: error: package javafx.beans.binding does not exist
import javafx.beans.binding.Bindings;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:24: error: package javafx.geometry does not exist
import javafx.geometry.Orientation;
                      ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:26: error: package javafx.scene.control does not exist
import javafx.scene.control.ScrollPane;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:27: error: package javafx.scene.control does not exist
import javafx.scene.control.SplitPane;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:28: error: package javafx.scene.layout does not exist
import javafx.scene.layout.AnchorPane;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:29: error: package javafx.scene.layout does not exist
import javafx.scene.layout.StackPane;
                          ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/BasePanel.java:116: error: cannot find symbol
public class BasePanel extends StackPane {
                               ^
  symbol: class StackPane
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:698: error: cannot find symbol
    private Tab getTab(BasePanel comp) {
            ^
  symbol:   class Tab
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:711: error: cannot find symbol
    public TabPane getTabbedPane() {
           ^
  symbol:   class TabPane
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:723: error: cannot find symbol
    private MenuBar createMenu() {
            ^
  symbol:   class MenuBar
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:1066: error: package ListChangeListener does not exist
    public void updateEnabledState(ListChangeListener.Change<? extends Tab> change) {
                                                     ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/gui/JabRefFrame.java:1066: error: cannot find symbol
    public void updateEnabledState(ListChangeListener.Change<? extends Tab> change) {
                                                                       ^
  symbol:   class Tab
  location: class JabRefFrame
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/model/entry/BibEntry.java:18: error: package javafx.beans does not exist
import javafx.beans.Observable;
                   ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/model/entry/BibEntry.java:19: error: package javafx.beans.binding does not exist
import javafx.beans.binding.Bindings;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/model/entry/BibEntry.java:20: error: package javafx.beans.binding does not exist
import javafx.beans.binding.ObjectBinding;
                           ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/model/entry/BibEntry.java:21: error: package javafx.beans.property does not exist
import javafx.beans.property.SimpleStringProperty;
                            ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/model/entry/BibEntry.java:22: error: package javafx.beans.property does not exist
import javafx.beans.property.StringProperty;
                            ^
/home/bgh/wsghassen/gitrepository/jabref/src/main/java/org/jabref/model/entry/BibEntry.java:23: error: package javafx.collections does not exist
import javafx.collections.FXCollections;
                         ^
100 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
4 actionable tasks: 1 executed, 3 up-to-date
Compilation failed; see the compiler error output for details.
10:56:26 ص: Task execution finished 'assemble'.

</details>

**Comment by Siedlerchr** [comment]
Hi you probably need to install and configure Java 8 as jdk for JabRef.
Newer Java versions currently don't work.

**Comment by BGhass** [comment]
Hi, 
Thank you for the response, but, I verify the jdk and it's setted.
![jdk](https://user-images.githubusercontent.com/15387271/52521304-78bda100-2c75-11e9-804b-55a93ed9db43.png)

**Comment by BGhass** [comment]
Resolved
