### ISSUE TITLE
Exporting to MS Office 2007 XML omits "von" part from author's last name

### ISSUE THREAD

**Issue by grebnetiew** [JabRef/jabref#4655]
JabRef version 4.3.1 and 5.0-dev on Windows 10.

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When exporting a bibliography with a 'von' part, the 'von' part is omitted from the XML file.

1. Add an entry with as author, for example, John von Neumann (preserve caps)
2. Export to MS Office 2007 XML
3. Observe that your entry has `<b:Last>Neumann</b:Last>`, and "von" is nowhere to be found

I suspect this is due to the fact that the XML format does not offer a separate tag for the "von" part, and the [model of the author in JabRef](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/msbib/MsBibAuthor.java#L51) omits the "von" when returning a last name.

<details>
<summary>Bibtex file</summary>

```bibtex
@Article{Neumann1987,
  author  = {John von Neumann},
  title   = {ABC},
  journal = {aaa},
  year    = {1987},
}
```

</details>
<details>
<summary>XML file fragment</summary>

```xml
<b:NameList>
<b:Person>
<b:Last>Neumann</b:Last>
<b:First>John</b:First>
</b:Person>
</b:NameList>
```

</details>

**Comment by deepakkumar96** [comment]
@grebnetiew is the issue still persist or it is solved? because when I exported to MS 2007 in ubuntu using the latest master development version, then it includes middle name.

**Comment by CaptainDaVinci** [comment]
I check [this source](http://www.datypic.com/sc/ooxml/e-bibliography_Author-1.html) there seems to be a _Middle_ tag provided.

**Comment by Siedlerchr** [comment]
It's an export problem, the code which handles the exporting of authors is here:

https://github.com/JabRef/jabref/blob/ddd12aec466eee9b9eb3434948d4b2459298eae6/src/main/java/org/jabref/logic/msbib/MSBibConverter.java#L132-L134

**Comment by CaptainDaVinci** [comment]
There are tests for First, Middle and Last Names but I didn't find any for von part. The [MsBibAuthor](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/msbib/MsBibAuthor.java) does not include von part when returning middle and last names. 

Should the von part be part of middle name or last name?

**Comment by tobiasdiez** [comment]
Thanks to @CaptainDaVinci this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
