### ISSUE TITLE
Main Menu: change File tab 

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4668]
![mmfile](https://user-images.githubusercontent.com/26404402/53025909-2f820400-3462-11e9-8f18-0f644f85e001.png)

|Description of Issue|Possible Solution|  Warnings |
|:-----------------------------------------:|:-------------------------------------------------:|:---------------:|
| separate _new library_ items for LaTeX and Biblatex are used|use hierarchy to reduce number of items in the tab| -|
|_Import_ and _Export_ share one item with one masive submenu| separate export and import for easier use| keep import submenu, but change the export submenu as shown above.|
|-|-|other changes can be found in issues #4665 , #4666 , #4667 |

**Comment by AEgit** [comment]
Again, I am not sure, whether this additional hierarchy is useful, given the limited number of options - if there are plans to provide additional options, it makes sense to me to have these hierarchies, but otherwise they do not appear convenient.
Isn't avoiding deep hierarchies generally considered better?

**Comment by MartinKarim** [comment]
You are right, deep hierarchies should be avoided in most cases. Mainly for the following reasons:
1. It hides functions from the user
2. It adds additional steps to access a menu item

Point 1 does not seem a big issue here, as the name of the action is still stated in the first level of the menu, only additional information was put into the second level.
Point 2 is very much valid here, as an additional step is added to a very basic function.

But hierarchies in menus can have an advantage as well. They reduce the number of menu items that are displayed at once, making the menu easier to search, which increases efficiency. They can also structure a decision process and guide the user, as I mentioned in #4682 .

The number of items in the _File_ tab is already quite high, which is why hierarchy seems as an appropriate means to make it more structured. Especially in the _Export_ item, the hierarchy is meant to guide the user though the process, which can seems odd for more experienced users.

**Comment by AEgit** [comment]
Maybe have a user survey for this? As you mentioned before, in the end it comes down to a trade-off between learnability and efficiency/convenience. I think I know which option I would prefer, but I might be represent just a minority.
