### ISSUE TITLE
Icons form the Material Design Icons

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4677]
I have used the mdi-folder icon saying folder in the group edit window. With 
![grafik](https://user-images.githubusercontent.com/9216487/53082292-d4e9b600-34fc-11e9-9692-04bc1b17f417.png)
mdi-shape-circle-plus this does seem to work using shape-circle-plus.
What is wrong?

JabRef 5.0-dev--snapshot--2019-02-19--master--1b6c7b5b9
Windows 7 6.1 amd64 
Java 1.8.0_201

**Comment by tobiasdiez** [comment]
Some of the icons on the material design website are not present in the font that we use in JabRef (which is essentially an older version of the Material Design Icons). Here is a list of all the available icons: 
https://bitbucket.org/Jerady/fontawesomefx/src/6cbf97484669c4ab79318a158e1dadf59363c85c/fontawesomefx/fontawesomefx-materialdesignfont/src/main/java/de/jensd/fx/glyphs/materialdesignicons/MaterialDesignIcon.java?at=master&fileviewer=file-view-default

**Comment by bernhard-kleine** [comment]
Can you please advise how to make that showing the graphics?
