### ISSUE TITLE
Add option to allow for integers in field "edition" when running database in bibtex mode

### ISSUE THREAD

**Issue by fspreng** [JabRef/jabref#4680]
My colleagues and I much appreciate the integrity check of the information stored in the field "edition" that was implemented by @grimes2 as part of PR #1914. However, our literature database, which runs in bibtex mode, typically contains an integer in the edition field since this way of specifying the edition is much more convenient for us and all *.bst files we use are capable of handling integers appearing in this field. Would it be a reasonable improvement to provide the user with the option to allow for integers in the edition field even if the database runs in bibtex mode (as is the case with the biblatex mode)? By default, this option could be deactivated in order to meet the official bibtex specifications. Many thanks in advance!

**Comment by hamacekh** [comment]
I would like to work on this.

So the objectives are:
- [ ] Add checkbox option "Allow integers in edition field in BibTeX mode" to preferences - off by default.
- [ ] Modify org/jabref/logic/integrity/EditionChecker.java to reflect this setting.

There doesn't seem to be any tests to update.
Is this correct? Where should new checkbox option appear? After existing "Enforce legal characters in BibTeX keys" in "General" tab?

**Comment by Siedlerchr** [comment]
@hamacekh  Thanks for your interest! 
>Where should new checkbox option appear? After existing "Enforce legal characters in BibTeX keys" in "General" tab?
Think this would make sense 

> There doesn't seem to be any tests to update.
In IntegrityChecks there is a method for EditionChecks 
/src/test/java/org/jabref/logic/integrity/IntegrityCheckTest.java

**Comment by Siedlerchr** [comment]
Thanks to  @rodps  this issue should be now fixed in the latest master.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by fspreng** [comment]
Works for me. Many thanks!
