### ISSUE TITLE
Groups: change Automatic grouping

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4683]
![groupautomatic](https://user-images.githubusercontent.com/26404402/53121033-8adfef00-3553-11e9-9011-652f5ce2afc0.png)

|Description of Issue|Possible Solution|  Warnings |
|:-----------------------------------------:|:-------------------------------------------------:|:---------------:|
| Automatic grouping (e.g. by keywords is too complex)|Automatically create groups for every unique value of a BibTeX field;<br/>let the user change the field for grouping via dropdown at the top;| Users should not be able to manually add or remove groups in this tab;|
| Users need to be aware of the different grouping modes|use unique icon for automatic grouping|-|

**Comment by AEgit** [comment]
Note, that this suggestion appears to imply that users can only see EITHER manual groups OR automatic ones. I personally do not use the automatic grouping feature, so I don't mind this, but I could see people wanting to be able to see both manual and automatic groups simultaneously.

**Comment by AtrusRiven** [comment]
I consider this an important step for UI usability and clarity. Should be linked with #4681 and #4682 in a "metaissue".

**Comment by AtrusRiven** [comment]
Is there planning on working on this? I don't know what the devs are planning but it could be merged with #4681 and #4682 (and other issues related to the topic?).

**Comment by koppor** [comment]
@AtrusRiven proposed three tabs at https://github.com/JabRef/jabref/issues/4681#issuecomment-737300403. Thus, that issue is the more recent one. I close this to keep the number of opend issues low.
