### ISSUE TITLE
Entry Editor: general changes

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4686]
![entrygeneral](https://user-images.githubusercontent.com/26404402/53190004-08196b80-3609-11e9-926b-0ab44e679572.png)

|Description of Issue|Possible Solution|  Warnings |
|:-----------------------------------------:|:-------------------------------------------------:|:---------------:|
| Text fields are empty per default;<br/>there is no guide what to write in a field and in what form (e.g. text, numbers)|text suggestions in grey for every text field| font color needs to be very different from normal text;<br/> do not use suggestions if the form of input can vary;|
| flat buttons at the end of text fields are too inconspicuous;<br/>button icons are not always recognized|make buttons bigger and elevated;<br/>use text buttons, sometimes in combination with icons|-|
|too many tabs in the entry editor;<br/>some information repeats in other tabs;<br/>information structure does not match the users expectation;|remove tabs from the entry editor;<br/>divide fields on new tabs with more fitting structure;|-|
|||changes to the specific tabs can be found in #4687 #4688 #4689 #4690 #4691 |

**Comment by LinusDietz** [comment]
I like the change with the more explicit button. I would prefer if it would shorten the field instead of being in a seperate column. (here the prototype is maybe a bit misleading)

**Comment by koppor** [comment]
This is a minimal change. We think of doing some more UI chainging change.
