### ISSUE TITLE
Entry Editor: change Required Fields tab

### ISSUE THREAD

**Issue by MartinKarim** [JabRef/jabref#4687]
![entryreq](https://user-images.githubusercontent.com/26404402/53191052-22544900-360b-11e9-8ca4-53a8016dcc88.png)

|Description of Issue|Possible Solution|  Warnings |
|:-----------------------------------------:|:-------------------------------------------------:|:---------------:|
|text fields are too long to provide a good overview over long content;<br/>buttons at end of the fields get less noticable|shorten text fields| -|
|-|-|other changes are found in #4686 |

**Comment by samiyac** [comment]
Hi I would like to work on this.
