### ISSUE TITLE
Define alternative fields for displaying in main table

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#470]
Currently, if an entry does not have an author then nothing is shown in author column of the main table. It would be nice if in such cases JabRef would fall-back and try another field (e.g. editor).
(If this is implemented, the column header should be adapted accordingly, i.e. show "Author / Editor")

The following combinations present themselves:
- Author / Editor
- Journal (Article) / Publisher (Book)
- Title could be supplemented by subtitle (in the case we implement the multi-line display of entries as [suggested by sci](http://sourceforge.net/p/jabref/mailman/message/34519834/) )

**Comment by oscargus** [comment]
You can just write "author/editor" in the entry table editor and it will happen. (I learned a few weeks ago.)

**Comment by oscargus** [comment]
Or you mean it should be automagic?

**Comment by tobiasdiez** [comment]
Thanks for the tip! In this case, it would be nice if this feature is used by default. Accomplished in #472.

**Comment by lenhard** [comment]
If the issue is fixed in #472 it can be closed, right?

**Comment by tobiasdiez** [comment]
Yes can be closed.
