### ISSUE TITLE
Wrong newline format in Jabref 5.0

### ISSUE THREAD

**Issue by mutlusun** [JabRef/jabref#4703]
Hello,
thanks for all your work on Jabref! I am using the snap version of Jabref 5.0.

JabRef 5.0-dev
Linux 4.18.0-15-generic amd64 
Java 1.8.0_191

If I change the newline separator in the preferences from "CR/LF" (the default? even on Linux?) to "LF", it will always switch back to "CR/LF". I think, this is not the intended behaviour. I don't get any errors in the console while saving the preferences.

Let me know, if you need more information.

Best

**Comment by Siedlerchr** [comment]
@LyzardKing Could you test this and report back if this is a problem of the snap version or if it also occurs in the non snap version?

**Comment by LyzardKing** [comment]
I'm not sure how to run the non snap, since javafx is not abailable for openjdk-8 in 18.10
How can I verify the character being used?

**Comment by mutlusun** [comment]
Hello,
I ran the latest non-snap version under Ubuntu 18.04. For me, the same problem occured ...

**Comment by LyzardKing** [comment]
@Siedlerchr I'm not sure, I haven't been able to properly dive in the code at it that much..
There might be an issue with the settings interface..
I tried to edit a bib file with a simple text editor, setting a different newline format,
JabRef still shows CR/LF

**Comment by tobiasdiez** [comment]
There was indeed a problem in the preference dialog. Should be fixed with https://github.com/JabRef/jabref/pull/4720.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by LyzardKing** [comment]
It seems to be working in the snap!

**Comment by mutlusun** [comment]
Works for me, too! Many thanks for your fast response!
