### ISSUE TITLE
Handling of diacritics in bibtex key generator

### ISSUE THREAD

**Issue by doctor-ian** [JabRef/jabref#4709]
JabRef version 4.3.1 on Windows 7.

There are certain diacritics (and other symbols) that produce undesired output when generating bibtex keys. I am using `[auth3][shortyear]` as generation pattern. Examples with first authors' last names and year:

- Müller, 2019 -> Muel19 (4 characters instead of 3 when converting umlaut, i.e. ä, ö, ü)
- Al-Ketan, 2019 -> Al-19 (dash in bibtex key is awkward, should probably be ignored in favor of the next letter and become AlK19)
- D'Alessandro, 2019 -> DA19 (Apostrophe is correctly ignored, but the name is reduced to 2 characters when it should probably be DAl19)

Some other diacritics that I quickly tested (Ç, Â, é) are handled more gracefully, i.e. the corresponding letter without diacritic is used.

1. Use [auth3][shortyear] as pattern for bibtex key generation. 
2. Enter one of the last names mentioned above in the last author field of a new article. Enter any year.
3. Generate bibtex key (CTRL+G)

**Comment by Siedlerchr** [comment]
Well, dash is a perfectly legal char in a bibtex/biblatex key: Forbidden are only these symbols: `" # % ' ( ) , = { }`
But I agree with you that the pattern of sometimes two, three and 4 chars is confusing.

**Comment by chelseyong** [comment]
Can I work on this issue?

**Comment by Siedlerchr** [comment]
Thanks to @chelseyong  this should now be fixed in the latest master.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
