### ISSUE TITLE
Cleanup entries: no braces around capital letters in field title

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#471]
3.0, Win10: Using cleanup entries should convert capital letters (A) to a syntax with braces around the capital letters ({A}). This is not working anymore.

**Comment by oscargus** [comment]
It had never worked that way. The cleanup entry action only works with a specified list of words (currently quite a lot of Electrical Engineering terms). However, you can in Preferences -> File enter "title" in "Store the following fields with braces around capitals".

One may also think of a cleanup action that does this explicitly.

**Comment by grimes2** [comment]
> However, you can in Preferences -> File enter "title" in "Store the following fields with braces around capitals".
In this case bug #419 occurs.

**Comment by oscargus** [comment]
Ah, OK! I think this is more related to #419 than the cleanup though. So probably better to fix it in the correct place. (However, I assume that not using the automatic braces and add them through a cleanup would indeed solve it from some perspective.)
