### ISSUE TITLE
Re-implement "Customize entry types" dialog

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4719]
In https://github.com/JabRef/jabref/pull/4716, the Customize entry types dialog was temporarily removed. It should be rei-mplemented in JavaFX once we converged to a stable entry editor layout (refs https://github.com/JabRef/jabref/issues/2790 https://github.com/JabRef/jabref/issues/366 https://github.com/JabRef/jabref/issues/4687 https://github.com/JabRef/jabref/issues/4688).

**Comment by burrbull** [comment]
Can I customize them manual?

**Comment by tobiasdiez** [comment]
@burrbull you can use an older JabRef version (e.g. 3.4.1) to customize the entry types and then use the customized types in the new 5.0 version (only the customization dialog was temporarily removed, not the functionality). Sorry for the inconvenience.

**Comment by koppor** [comment]
The dialog shows like that: 

![grafik](https://user-images.githubusercontent.com/1366654/70297735-7e313c80-17ef-11ea-9b42-4ce2e0947f50.png)

When working on that, https://github.com/JabRef/jabref/issues/725 should also be addressed

**Comment by johann-petrak** [comment]
Is there a way to do this by manually editing some configuration file (instead of trying to mix JabRef versions)?
For some reason I do not have an Editor field available for @book entries and I would like to add that somehow.

**Comment by Siedlerchr** [comment]
Sure, custom fields and custom entry types are all stored in the metadata at the end of the bib file.
You can always manually add the field also in the source-editor in the tab of the entry editor, e.g. `editor= { The book editor}`

**Comment by johann-petrak** [comment]
Thanks, I am happy to manually add something to the bib ...  what would the metadata at the end of the bib file have to look like in order to simply add the editor field to @book entries?
