### ISSUE TITLE
Wrong default filename format pattern 

### ISSUE THREAD

**Issue by i-Zaak** [JabRef/jabref#4724]
JabRef 5.0-dev--snapshot--2019-03-06--master--ddd12aec4

The default file format patterns given in the Preferences->Import drop down menu are `bibtexkey` and `bibtexkey - title`, however this leads to files being named literally `bibtexkey.pdf`. The correct options should be `[bibtexkey]` and `[bibtexkey] - [title]` -- then the renaming (and moving) of files works in the cleanup entries.

**Comment by Siedlerchr** [comment]
This issue should be fixed now in the lastet master
We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by i-Zaak** [comment]
Yep, the defaults are now correct. Thanks!
