### ISSUE TITLE
Nightly: Indicate the build-date and git revision

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#4733]
In the current nightly/dev versions, please display the build-date in the title bar.
It would also be nice if I could see the git-rev (commit-hash), too.

**Comment by Siedlerchr** [comment]
This should be displayed already in the about window.

**Comment by tobiasdiez** [comment]
The class `BuildInfo` should contain all necessary information.

**Comment by CaptainDaVinci** [comment]
The `BuildInfo` class reads the file [build.properties](https://github.com/JabRef/jabref/blob/master/src/main/resources/build.properties), however the file contains place holder values (which are reflected in the about page as well). Should these values be updated at run time?

**Comment by tobiasdiez** [comment]
These placeholders are resolved by the build server. So no need to change the file.

**Comment by tobiasdiez** [comment]
As @Siedlerchr said, this information is already contained in the about dialog:
![image](https://user-images.githubusercontent.com/5037600/54813838-bf4be580-4c8e-11e9-9d0e-57c0972170b0.png)

As the build date is a relativly unimportant information, I also don't see any reason to add it to the titlebar.
