### ISSUE TITLE
Non-existing aux file in group throws IOException

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4735]
JabRef dev version  on Windows 10 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Create a group based on aux file
2. Close and save library
3. Remove aux file
4. Open library again -> get error message because of IOException, group tree is empty

Solution:
Catch exception (and log warning) here https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/model/groups/TexGroup.java#L31

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by arturolc** [comment]
Hi @tobiasdiez, I would like to work on this issue.

**Comment by tobiasdiez** [comment]
@arturolc I've now fixed this myself as I again run into this problem. Hope you didn't already started working on this.
