### ISSUE TITLE
Relativize paths to aux files

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4736]
**Is your suggestion for improvement related to a problem? Please describe.**
When a group based on an aux file is created, JabRef stores the absolute path to the aux file. This makes it hard to use the feature across different computers.

**Describe the solution you'd like**
Introduce "LaTeX folder" in Library properties similar to the `UserFileDirectory` (which signals where the pdfs are stored). All aux paths should then be relative to this data folder (when the user leaves the path field in the group editor or after a file was selected through "browse").
(note: the introduction of a LaTeX folder might appear somewhat of an overkill on first sight, but it is also essentially for the latex integration project)

**Comment by samiyac** [comment]
Hi, I would like to work on this issue.

**Comment by samiyac** [comment]
@tobiasdiez as of now I have made changes to LibraryPropertiesDialogView.java and LibraryPropertiesDialogViewModel.java
I believe I will also have to add required changes in Metadata.java to accomodate the new LaTex folder. Am I on the right track?

**Comment by tobiasdiez** [comment]
Sounds right too me. The new folder is specific for to the library and thus the metadata class is the correct place to store it (and you need corresponding parsing/writing logic). Because of this relative wide range of changes, I didn't marked this issue as "good-first-issue" but it's nice that you found yourself around the code so quickly. Good job!

**Comment by samiyac** [comment]
@tobiasdiez Does the LaTex directory have to be user-specific like in the case of `UserFileDirectory` or can it be general?
I am currently making changes in MetaDataSerializer, and I was planning on adding -L after `MetaData.FILE_DIRECTORY` help in identifying that this path is for LaTex File `MetaData.FILE_DIRECTORY + '-L'`. Would this work?

I have made the rest of the changes and would be making a pull request soon. Thank you

**Comment by Siedlerchr** [comment]
If it's stored in the bib file it's library specific,
Should be enough for this purpose. Offers the greatest flexibility. 


Just some background info. In the library properties you can enter relative file paths for the file directory. The file directory is then relative to the location of the bib file. 
(e.g you store the bib file with you latex files and the literature in a subdirectory) 

The general file directory is an absolute directory which applies for all libraries. 
(you have a single folder for pdf on your system where you put all files into not just for one library) 

And the third option is bib file location. Bib files and pdfs are stored in the same folder.

**Comment by samiyac** [comment]
As of now, I am saving relative path of the aux file in `serializeTexGroup` in GroupSerializer.java and I convert this relative path to absolute path in `texGroupFromString` in GroupsParser.java. However, in order to do this expansion to absolute path, I need an instance of MetaData, as of now I am doing this by passing it through `GroupsParser.importGroups(value, keywordSeparator, fileMonitor, metaData)`

However, this would require changing in tests.

Is there a better way to do this?

Also if LaTex Folder is not specified, I was planning on having relative path User-Specific or General file directory. If these directories aren't specified, relative to which folder should I save Aux file?

I will also have to add tests for LaTex Folder right?
Thanks

**Comment by samiyac** [comment]
Hi, I am facing this error

```org.jabref.logic.l10n.LocalizationConsistencyTest > findMissingLocalizationKeys() FAILED
    org.opentest4j.AssertionFailedError: DETECTED LANGUAGE KEYS WHICH ARE NOT IN THE ENGLISH LANGUAGE FILE
    PASTE THESE INTO THE ENGLISH LANGUAGE FILE 
     LaTex\ file\ directory=LaTex file directory
     ==> expected: <[]> but was: <[LaTex\ file\ directory (src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialog.fxml LANG)]> 
```
I understand what is causing it but don't exactly understand how to fix it.
I have made the rest of the changes to tests

**Comment by tobiasdiez** [comment]
@samiyac Sorry for the late answer. 
I think it is slightly better to relativize the path only in the group dialog, i.e. after the user selected a file via the browse button. In this way the relatization is transparent to the user and codewise you don't run into the problems that you describe above.

It would be nice if you could add tests for the basic things (serialization/parsing/making paths relative) but you are not required to cover everything.

**Comment by samiyac** [comment]
@tobiasdiez I have implemented that. The only problem is that when I am saving my AUX file, I am saving relative path. So when I parse to create TexGroup, I need access to LaTexFileDirectory which I can only get through MetaData.

**Comment by tobiasdiez** [comment]
Thanks to @samiyac this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
