### ISSUE TITLE
Unable to update entry table column order and column name in preferences

### ISSUE THREAD

**Issue by CaptainDaVinci** [JabRef/jabref#4752]
JabRef development version, Arch Linux.

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Under _entry table column_ in preferences I am not able to change the order of the columns by more than one column, on saving the order and reopening the Bib file the changes aren't reflected.

Edit: Apart from the column order the column names aren't updated either.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Related issue #3354 #4579

The column order is stored on update in : `PersistenceVisualStateTable` and in `    private List<TableColumn<BibEntryTableViewModel, ?>> createNormalColumns() { `  in `MainTableColumnFactory`

**Comment by CaptainDaVinci** [comment]
Are the `PersistenceVisualStateTable.updateColumnPreferences()` and `PersistenceVisualStateTable.updateColumnSortType()` method called every time the UI is built? That  would explain why it discards the preferences which were saved earlier.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
