### ISSUE TITLE
Enable import button only if entry selected

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4755]
The import button in the import dialog should only be enabled if at least one entry is selected.

Moreover, if this dialog is triggered by an import action all entries should be selected by default. (If triggered by a websearch then no entries should be selected by default as it is right now.)

**Comment by samiyac** [comment]
I would like to work on this issue.

**Comment by tobiasdiez** [comment]
@samiyac Glad to hear!
You should be able to get the button via `(Button) this.getDialogPane().lookupButton(...);`. Then it is probably enough to bind the `disableProperty` to the `emptyProperty` of the list of checked items.
