### ISSUE TITLE
Jabref generates CPU load all the time

### ISSUE THREAD

**Issue by andreasbuhr** [JabRef/jabref#4756]
**Is your suggestion for improvement related to a problem? Please describe.**

Jabref generates CPU load all the time. See attached a screenshot of htop:
![jabref_cpu_load](https://user-images.githubusercontent.com/3892222/54203015-9d55a480-44d1-11e9-9c41-de8ed705a14d.png)
This keeps my CPU hot which in turn keeps the fan of my laptop spinning. This is annoying. I often close Jabref to have silence.

**Describe the solution you'd like**
When Jabref is just open doing nothing, it would be great if Jabref did not produce any CPU load.

**Comment by Siedlerchr** [comment]
I see you are using the version 4.3.1. 
Please try the latest development build from https://builds.jabref.org/master as there have been a lot of fixes and changes and performance improvements and report back if it works better.

Please remember to make a backup of your library before trying-out this version.

**Comment by andreasbuhr** [comment]
Thanks for your quick reply. 
Unfortunately, there is still the same behaviour in the latest version:
![jabref_cpu_load](https://user-images.githubusercontent.com/3892222/54263894-32a87580-4572-11e9-9f75-330e7cfecfb1.png)

**Comment by bernhard-kleine** [comment]
After opening a large (4000 entries) library, Jabref does not take much of the RAM. However, deleting from this library takes up to 5Gb RAM and upto 90 % of CPU time. Since I have 16 GB available RAM for me it is not so much, but on a laptop with smaller RAM there might be a lot of activity. (and warming and spinning).

**Comment by bernhard-kleine** [comment]
After starting the deletion, the processor occupancy went to 95 %, and the RAM used was about 5GB, However after deletion was completed, the RAM was not freed. That might be an error!
![grafik](https://user-images.githubusercontent.com/9216487/54692450-59901a00-4b25-11e9-8076-1e6f26349488.png)

**Comment by LinusDietz** [comment]
much has changed since the opening of this issue. The 5.0 Alpha release is imminent. Closing for now.
