### ISSUE TITLE
Bibtex key generator bug introduced

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4767]
JabRef version 
JabRef 5.0-dev--snapshot--2019-03-16--master--d7dd41b00
Linux 4.15.0-46-generic amd64 
Java 1.8.0_201

on Linux Mint 19.1

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. open Options/Preferences/BibTeX key generator
2. set the key to "[auth4:lower]-[year]"
3. In the entry editor, using ctrl+G to create the key produces output without the hyphen.  E.g., "smit2019" instead of the expected "smit-2019".

It worked fine in JabRef 5.0 dev until recently, and it works in older version of JR.

<details>
  <summary>Log File</summary>
  
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Opening: /tmp/jabref1689428551091217694.bib
Opening: /tmp/jabref1689428551091217694.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
</details>

**Comment by Siedlerchr** [comment]
Maybe a side effect from #4709?

**Comment by tim-kilian** [comment]
This is because - is an illegal character in the BibtexKeyGenerator KEY_ILLEGAL_CHARACTERS pattern.

https://github.com/JabRef/jabref/blob/d7dd41b0022978b9db958505cf6031768cf2cd8c/src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java#L29
