### ISSUE TITLE
Compare dialog requires scroll bars

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#477]
When comparing two entries, and they have too long titles, they can only be displayed if the monitor has a high enough resolution. We should add scroll bars to this.

![image](https://cloud.githubusercontent.com/assets/375693/11614875/268ad23a-9c50-11e5-9706-5fc00f5c6f89.png)

**Comment by oscargus** [comment]
This was discussed in an old PR (which I cannot find). I think it needs to be redesigned completely (and use some clever LayoutManager) to accomplish this. At least I can not really understand how to design it such that a column can scroll.

When scrolling is implemented there are also plans to add coloring of differences.

**Comment by matthiasgeiger** [comment]
Simpler solution might be to show a ToolTip with the full text if the text is too long.

Example code from the main table can be found here: 4f9ff0d7fc647f68733fde5bd783af722cf9ef7c

**Comment by koppor** [comment]
I think, the discussion was held at https://github.com/JabRef/jabref/pull/206#issuecomment-146983960

**Comment by simonharrer** [comment]
@oscargus is this now fixed?

**Comment by oscargus** [comment]
Yes!
