### ISSUE TITLE
track where bib file is stored?

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#4778]
Working with
JabRef 4.3
Linux 4.20.15-200.fc29.x86_64 amd64 
Java 1.8.0_201

Use situation: I have worked with jabref on a bib file (in the midst of a work process involving lots of other work, between my brain, a latex document and file structures). Externally, at some point I renamed the folder in which that bib file was located. Careless as I was, I did not tell JabRef about the directory change name. In parallel, JabRef's error message (when trying to save the file) also helped me little (it did not tell me "the folder vanished" or something along these lines).

for such a careless use case - might it be possible to offer a more precise error message? or maybe even find a way of tracking where the file is actually stored...?

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
