### ISSUE TITLE
Search in import (inspection) window

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4781]
This is a follow-up on the issue #4685 as kindly suggested by @Siedlerchr.

It would be great if the new import dialog will have a search where one ideally can filter the listed results. Maybe implementing `author:john`, `title:goal-oriented`, etc, filters might be useful.

**Comment by tobiasdiez** [comment]
I'll like your suggestion. It makes sense especially for (larger) imports. However, for the web search, we usually show only between 10 to 20 entries. Thus, in case, I would suggest that we show a text field with the search query and changing the text would trigger a new search.

**Comment by DOFfactory** [comment]
Thanks @tobiasdiez for the feedback, I was unaware of the fact that the results window shows only 10-20 results. Personally, I liked the compact view of the 3.4 version, where a lot of articles were loaded. I think the best would be if one could conduct some basic literature review searches in the import as well. Just in idea.
