### ISSUE TITLE
Find unlinked PDF files

### ISSUE THREAD

**Issue by dschrempf** [JabRef/jabref#4790]
I am using `Jabref--master--latest.jar` (March 20, 2019).

I was missing the feature "find unlinked PDF files". I believe this already existed at some point but seems to be absent now. I use this feature often, and would like to have it back.

Since I am not using Java, in the meantime I wrote a simple BASH script. Maybe it can be used as a starting point?

```bash
#!/usr/bin/env bash

d="/path/to/papers/"
b="/path/to/library/library.bib"

cd "$d" || exit 1

while IFS= read -r -d '' file
do
    if ! grep -q "$file" "$b"
    then
        echo "$file was not found in bibliography."
    fi
done < <(find -- * -type f -name '*.pdf' -print0)
```

Thanks a lot for working on JabRef!

**Comment by tobiasdiez** [comment]
We resorted the menu to group related features and make them more accisble. The "Find unlinked files" is now placed under "Quality".

**Comment by dschrempf** [comment]
This entry is not showing up in my JabRef instance.

![2019-03-20-203744_1920x1080_scrot](https://user-images.githubusercontent.com/5596239/54713955-2616b500-4b50-11e9-8650-ab6a14965f30.png)

**Comment by Siedlerchr** [comment]
It's under Tools: (Search for unlinked local files)
![grafik](https://user-images.githubusercontent.com/320228/54714454-498e2f80-4b51-11e9-9142-f16f98e16970.png)

**Comment by dschrempf** [comment]
Thank you!

**Comment by scfrank** [comment]
For the next person looking for this feature: In Jabref 5.1 it's in the 'Lookup' menu -> 'Search for unlinked local files',  fn F7.
