### ISSUE TITLE
List not refreshing when creating an entry in a new library

### ISSUE THREAD

**Issue by tim-kilian** [JabRef/jabref#4793]
JabRef version 5.0-dev--snapshot--2019-03-20--master--6c61664a8 on Windows 10 10.0 amd64 Java 1.8.0_172

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

It seems that the lsit is empty when I try to create a new library. When I try to create a new entry with <kbd>Ctrl</kbd>+<kbd>n</kbd> it doesnt show up. Seems to be related to the non existing list at the beginning.

1. Create a new library (bibtex/biblatex)
2. Create a new entry (<kbd>Ctrl</kbd>+<kbd>n</kbd>)

![create-entry](https://user-images.githubusercontent.com/5788010/54725161-5b320000-4b6e-11e9-94cb-9a93ee9c486f.gif)

<details>
  <summary>Log File</summary>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
00:02:07.326 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: C:\Users\Tim\LatexProjects\ba\bib\ba\main.bib
00:02:07.463 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: C:\Users\Tim\Documents\test.bib
00:02:11.750 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
00:02:11.825 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
00:02:17.549 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
00:08:41.973 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
</details>

**Comment by Siedlerchr** [comment]
You are missing keys in the registry, have s look at the forum there was a similar problem and the solution is to manually create the missing registry keys

**Comment by tim-kilian** [comment]
So this is not a bug, I am just missing something out, right? Can you link the topic in the forum for this?

**Comment by matthiasgeiger** [comment]
No, this is a bug introduced recently. 

@siedlerchr this is a side effect of the @tobiasdiez fix regarding the not opening entry editor

**Comment by Siedlerchr** [comment]
Thanks to  @matthiasgeiger  this should be fixed in the latest master now.
https://builds.jabref.org/master
