### ISSUE TITLE
Options should be inactive or show Error or Information Box

### ISSUE THREAD

**Issue by atulim** [JabRef/jabref#4795]
JabRef version 5.0

I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists-

(1) Open JabRef 5.0 and go to Tools option.
(2) Click on the link 'Push entries to external application(TeXstudio)' which comes as active.
(3) Nothing happens.

Actual behavior: Nothing happens on clicking 'Push entries to external application(TeXstudio)' option.

Workaround: open JabRef 5.0, 'Push entries to external application(TeXstudio)' option shouldn't be active or should show the error or information box like it shows when we add a new Library with no entry which results in 'This operation requires one or more entries to be selected'.

Why it matters: It's a common U.I. bug that needs to be fixed. In this P.R. I will suggest more options that could be inactive or show error or information box.

**Comment by atulim** [comment]
@tobiasdiez As I said, I would suggest initial bugs in U.I. when there is no database involved. They are listed below -

Bugs Involved - (a) Some of the options that show as active and don't perform an operation. They should be marked as inactive or a dialog box should appear.

(1) Edit (Menu bar)- Manage keywords

(2) Library - New entry
                   New entry from plain text
                   Manage field names and content
(3) Tools - Search document identifier online


(b) Some of the options show exception. Instead they should show inactive or error dialog box - 

(1) Library -
     Library properties
     Edit preamble 
     Edit string constraints
     BibTex key patterns
qualitiy-
Find Duplicates
Merge Entries
Check integrity
Automatically set file links
Search for unliked social files

(2) Tools-
     Search for unlinked local files
     Copy Linked Files to Folder

Actual Behaviour - These options have a buggy nature and should show behaviour like Abbreviate Journal names in Tools bar.

Also I request @tobiasdiez to address these bugs. I will try to remove these bugs in three to four days, reason being which there is a problem in setting up the environment even after resetting everything(as i mentioned on gitter).

**Comment by tobiasdiez** [comment]
@atulim Thanks for the list! That helps a lot. 

If you are really motivated you can go ahead and try to fix this bug as well. However, this is definitely not a beginner task. As it would require a lot of refactorization. For example, the disable status of the menu item needs to be bound to the command here:
https://github.com/JabRef/jabref/blob/e14b567425cdd2a49efcf56b0e4eafd0b96f1c1a/src/main/java/org/jabref/gui/actions/ActionFactory.java#L40-L45
And then there should be some general procedure (helper methods?) that allow to disable a command when no database is opened.

**Comment by Ali96kz** [comment]
Try to work on it.  If someone start work on that issue please notify me

**Comment by atulim** [comment]
> @atulim Thanks for the list! That helps a lot.
> 
> If you are really motivated you can go ahead and try to fix this bug as well. However, this is definitely not a beginner task. As it would require a lot of refactorization. For example, the disable status of the menu item needs to be bound to the command here:
> [jabref/src/main/java/org/jabref/gui/actions/ActionFactory.java](https://github.com/JabRef/jabref/blob/e14b567425cdd2a49efcf56b0e4eafd0b96f1c1a/src/main/java/org/jabref/gui/actions/ActionFactory.java#L40-L45)
> 
> Lines 40 to 45 in [e14b567](/JabRef/jabref/commit/e14b567425cdd2a49efcf56b0e4eafd0b96f1c1a)
> 
>  public MenuItem createMenuItem(Action action, Command command) { 
>      MenuItem menuItem = ActionUtils.createMenuItem(new JabRefAction(action, command, keyBindingRepository)); 
>      setGraphic(menuItem, action); 
>   
>      return menuItem; 
>  } 
> 
> And then there should be some general procedure (helper methods?) that allow to disable a command when no database is opened.

@tobiasdiez Yeah I will work on this issue. It's just that there is some problem that I am facing in setting up the correct development environment which I will fix in the next 2-3 days.

**Comment by atulim** [comment]
> Try to work on it. If someone start work on that issue please notify me

@Ali96kz Yes. I think I would have no problem with you solving this bug. It will be great if someone improves this bug, be it anyone. Please reference the issue in the pull request when you solve the bug.

Thank you.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

Thanks @atulim for the above list. Was really helpful while coding!

**Comment by koppor** [comment]
I tried it today with an empty database:

![grafik](https://user-images.githubusercontent.com/1366654/61177297-28ef5700-a5d2-11e9-9953-3d14782fa789.png)

![grafik](https://user-images.githubusercontent.com/1366654/61177302-36a4dc80-a5d2-11e9-9e50-6e54120f7277.png)

Export should not be possible if no entries are selected (which is especially the case with no opened database)

**Comment by koppor** [comment]
Curent state:

* File > Save-All needs to be disabled
* Export needs to be disabled (Can we disable a complete submenu?)
  ![grafik](https://user-images.githubusercontent.com/1366654/104094051-df4aff80-528e-11eb-9e84-4fcc86f7bf81.png)
* Edit -> Copy selected entries needs to be disabled  
  ![grafik](https://user-images.githubusercontent.com/1366654/104094066-f5f15680-528e-11eb-8dff-02131d4653f8.png)

Other than these issues: Everything OK in latest master.

**Comment by koppor** [comment]
Current status:

- ![grafik](https://user-images.githubusercontent.com/1366654/127909463-da20b24f-0c80-42e1-bc90-3b52538b2253.png)
- ![grafik](https://user-images.githubusercontent.com/1366654/127908928-721837fe-0658-49f6-96fc-183d935ba51c.png)
- ![grafik](https://user-images.githubusercontent.com/1366654/127909095-a1ebef27-6c06-4f66-821e-713d98125d4f.png)
- ![grafik](https://user-images.githubusercontent.com/1366654/127909184-47a4f023-d340-4dcf-851b-11964a00f34d.png)
- ![grafik](https://user-images.githubusercontent.com/1366654/127909354-cbc8514f-c095-47cc-a32c-ed3122faf53f.png)
- Can we disable the main menu if all sub items are disabled: ![grafik](https://user-images.githubusercontent.com/1366654/127909429-574e4c47-3290-4aec-84b9-9109464de969.png)
