### ISSUE TITLE
program won't quit when loading a library bound to a postgresql

### ISSUE THREAD

**Issue by shichuzhu** [JabRef/jabref#4804]
JabRef version 
<JabRef 5.0-dev--snapshot--2019-03-20--master--6c61664a8
Linux 4.15.0-46-generic amd64 
Java 1.8.0_201>
on <Ubuntu 18.04>

- [Y] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

It's OK if I'm using JabRef with a regular .db file. However, if the .db file is bound to a postgresql database (i.e., the .db file starts with a line
"% DBID: 4grj2t8cd5i......"
), then JabRef program won't terminate when I click "File--Quit".

1. `/usr/lib/jvm/java-8-oracle/bin/java -jar /home/shichu/usr/jabref/JabRef.jar`
2. File -- Open library -- select the .db file containing the "% DBID" attribute.
3. File -- Quit
4. The GUI interface will close, but in the terminal that I run the step 1, the program is still **blocking**. If I'm using the Desktop shortcut, then after "Quit", `ps aux | grep JabRef` still shows the program is not terminated.

Upon the GUI close, the only one line of log I got from the terminal is following:

<details>
  <summary>Log File</summary>
  
  ```
21:39:31.919 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /mnt/data/shared/path/to/thedbfile.bib
  ```
</details>

**Comment by tobiasdiez** [comment]
It could be that this issue is fixed now in the development version. Can you please try it again. Thanks!

**Comment by shichuzhu** [comment]
I'm sorry I've switched to use the db file instead of using postgresql, so I won't be able to confirm the fix.
Anyone else is welcome to validate this.
