### ISSUE TITLE
Improvement: Add all messages shown also to event log

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#4805]
Currently, the information displayed, e.g., during saving, is not logged in the event log:
![grafik](https://user-images.githubusercontent.com/676652/54878244-3ec1ec00-4e2a-11e9-88ab-ae08d08113f9.png)
not logged here:
![grafik](https://user-images.githubusercontent.com/676652/54878255-6c0e9a00-4e2a-11e9-882b-b528c952430e.png)

In my opinion it would be helpful to have it also there.

@tobiasdiez @Siedlerchr WDYT?

**Comment by tobiasdiez** [comment]
I agree. If it's important enough to be displayed to the user as a status update, then it should also be displayed in the event log (as info).

**Comment by bernhard-kleine** [comment]
why not make to saving lines optional, otherwise the log can become clattered.

**Comment by matthiasgeiger** [comment]
... at least when "autosaving" is enabled. Apart from that I would like to see the information that saving was successful.

**Comment by Siedlerchr** [comment]
Thanks to @r0light  this should be fixed in the latest master
