### ISSUE TITLE
"The library has been modified by another program" while no other program is active on the library

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4810]
JabRef version  on 

JabRef 5.0-dev--snapshot--2019-03-26--master--83c802269
Windows 7 6.1 amd64 
Java 1.8.0_201
- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Whenever I add a group, add entries to that group and likewise, the message pops up. 
![grafik](https://user-images.githubusercontent.com/9216487/55023556-543b3f80-4ffd-11e9-91ae-b3e0e651cfd6.png)
I checked whether a second jabref instance was active, none was. 

1. open a library
2. add a group "test" and press enter, then you can save the group. 
3. add some entries to test. The message will pop up.
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by matthiasgeiger** [comment]
Same version JabRef 5.0-dev--snapshot--2019-03-26--master--83c802269 on Windows 10 10.0 amd64  with Java 1.8.0_201:

Working fine for me...

**Comment by bernhard-kleine** [comment]
I will enquire further. It did appear not at once but a short time later the exact time I missed.

**Comment by Siedlerchr** [comment]
Do you use Autosave and is your file in a cloud folder, e.g. synced with dropbox?

**Comment by bernhard-kleine** [comment]
I cleared the log befor proceding. Then I added to "Physiological Reaction" the subgroup "Test".
The log shows:

```
Opening: C:\Users\bk\AppData\Local\Temp\jabref2029372894609818251.bib
Opening: C:\Users\bk\AppData\Local\Temp\jabref2029372894609818251.bib
Opening: C:\Users\bk\AppData\Local\Temp\jabref2029372894609818251.bib
Error occurred when parsing entry: 'Error in line 10435: EOF in mid-string'. Skipped entry.
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib
Opening: K:\BuchprojektSpringer\VierteAuflage\Literatur\EndokrinologieKunde20190320VS5.0.bib
```

**Comment by bernhard-kleine** [comment]
@Siedlerchr Where would I find autosave?
No cloud, all at the desktop.

**Comment by bernhard-kleine** [comment]
The Pop-Up is also there then autosave is unchecked.

**Comment by matthiasgeiger** [comment]
Maybe threading/Timing issue in real big databases where saving is Not yet finished when another save run is started?

**Comment by bernhard-kleine** [comment]
The actual library has 7 Mb, 2800 entries, which I do not regard as very large. But maybe right, a timing problem. BTW the actual library and the c: drive where the temp files are saved to are on fast SSD drives.

**Comment by bernhard-kleine** [comment]
@matthiasgeiger : Today the error message appeared immediately upon opening Jabref, there was however, a backup from which the library was restored.

**Comment by gicanzo** [comment]
Same issue here (also using Jabref 5.0-dev). The message appears every time I save my library (even if no changes have been made). I do not have a big library, just about 100 entries. If I save the changes, all my entries are duplicated. My bib file is on a cloud folder (although that does not seem to be the issue). I am running Ubuntu Mate 19.04

**Comment by koppor** [comment]
Also explained at https://github.com/JabRef/jabref/issues/4167#issuecomment-485262955.

Refs https://github.com/JabRef/jabref/issues/5085.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
