### ISSUE TITLE
The colums of main table upon changing the group shrink to a minimal value.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4812]
JabRef 5.0-dev--snapshot--2019-03-26--master--83c802269
Windows 7 6.1 amd64
Java 1.8.0_201

- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The columns of the main table shrink when a different group is selected.
Before changing the group 
![grafik](https://user-images.githubusercontent.com/9216487/55025778-e9403780-5001-11e9-8daa-8dcc3a59a3bb.png)
and after changing the group
![grafik](https://user-images.githubusercontent.com/9216487/55025441-3bcd2400-5001-11e9-87f4-a8d78b3f908b.png)

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by bernhard-kleine** [comment]
Columns shrink when options have been modified, too.

**Comment by matthiasgeiger** [comment]
... and also here: I'm using the same version than you, and it is working fine for me...

Can you please export your preferences and upload them here in order to allow us whether this might be related to some preference settings.

Thanks!

**Comment by bernhard-kleine** [comment]
[Jabref5.0beta_20190326.xml.zip](https://github.com/JabRef/jabref/files/3009994/Jabref5.0beta_20190326.xml.zip)

**Comment by bernhard-kleine** [comment]
@matthiasgeiger This does no longer happen with the last snapshot.
