### ISSUE TITLE
The file import dialog does not react to "enter".

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4820]
JabRef 5.0-dev--snapshot--2019-03-28--master--a9115a256
Windows 7 6.1 amd64 
Java 1.8.0_201
- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Once you have selected a file for attachment to an entry Jabref opens a dialogue where you can confirm your selection of refuse it. You can select either the "cancel" or the "apply", however confirmation with "enter" does not work in both cases, you must use the mouse left click. The selection can, however, be changed with "tab".
![grafik](https://user-images.githubusercontent.com/9216487/55157441-a8a90100-515c-11e9-96d0-2984819a8bdc.png)

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by johannes-manner** [comment]
If you want to use the keyboard in combination with tab, you can use <kbd>space</kbd> instead of <kbd>enter</kbd> to fire buttons when the button is selected.

Is this an appropriate way to go for you?

**Comment by bernhard-kleine** [comment]
This is not obvious, but it works. I would prefer to use "enter".

**Comment by Siedlerchr** [comment]
I think the default behaviour is <kbd>alt </kbd> or <kbd>ctrl </kbd>  <kbd>enter </kbd> 
Default <kbd> enter </kbd> "commits" the entered text.

**Comment by Siedlerchr** [comment]
I just saw that behaviour is defined in the keybinding, as follows.
This is the default behaviour for all dialogs.  Normally it should be possible to change that in the keybinding dialog, but 

```  
DEFAULT_DIALOG_ACTION("Execute default action in dialog", Localization.lang("Execute default action in dialog"), "ctrl+ENTER", KeyBindingCategory.VIEW),
```

**Comment by tobiasdiez** [comment]
I guess the dialog just doesn't define a default action...

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
