### ISSUE TITLE
Adding two or more files cause JabRef to hang

### ISSUE THREAD

**Issue by bdcaf** [JabRef/jabref#4829]
I frequently encounter following trouble adding pdfs via Drag-and-Drop into JabRef.

I can reproduce it with a freshly started JabRef:

1. Drag 2 or more Pdfs into to window to add to library
2. For first pdf dialogs are normal: select entry type, then select whether to move file
3. For second pdf enty type can be selected - but the second dialog never shows up.
4. JabRef does no longer react and needs to be force quitted.

Note in "longer" running JabRef instances sometimes I can add the second pdf successfully.

The same behavior also sometimes appears when I add the files one after the other.  Though I can not reproduce it.

JabRef version 4.3.1 on Mac OS 10.14.3

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
