### ISSUE TITLE
File-Import for Zenodo-DOIs

### ISSUE THREAD

**Issue by geyslein** [JabRef/jabref#4842]
I am not sure whether it is implemented or not. At least zenodo file import with DOI doesn't work for me. It would be great to be able to import the documents via file import since zenodo is the source for me in the last months that I used most.

**Comment by Siedlerchr** [comment]
JabRef currently only queries doi.org for DOIs.
Could you please add an example doi/link to a citation or an example of a not found DOI?

**Comment by geyslein** [comment]
Sorry, I didn't stop by since: here are 2 DOI I just checked right now: 10.5281/zenodo.1254997  10.5281/zenodo.168388

- uname -a
`Linux buntstift 5.0.7-arch1-1-ARCH #1 SMP PREEMPT Mon Apr 8 10:37:08 UTC 2019 x86_64 GNU/Linux
`
- jabref --version
`JabRef 4.3.1`
- java -version
`java version "1.7.0_171"
OpenJDK Runtime Environment (IcedTea 2.6.13) (Arch Linux build 7.u171_2.6.13-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.171-b02, mixed mode)`

**Comment by Siedlerchr** [comment]
Hi, 
I just checked with the latest development version and both DOIs are resolved. 

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

PS: I am wondering a bit that your java output says it is still 1.7, JabRef requires at least 1.8.

**Comment by geyslein** [comment]
Hey, I just checked on another machine with Java 1.8:
`JabRef 4.3.1
Linux 5.0.6-arch1-1-arch amd64 
Java 1.8.0_212`
Same here. I'll try the dev version in a few.

**Comment by geyslein** [comment]
So, I tried the dev build:
`JabRef 5.0-dev--snapshot--2019-04-15--master--9ab59d044
Linux 5.0.6-arch1-1-arch amd64 
Java 1.8.0_212`
Still same result, no DOIs found for Zenodo. 

How can I help you further to solve this issue? Cheers and thanx a lot for JabRef.

**Comment by matthiasgeiger** [comment]
Okay, maybe there is a misunderstanding about what you are requesting. 

What @siedlerchr was referring to was to resolve the DOI key to BibTeX, i.e., you enter just `10.5281/zenodo.1254997` and the title, author, etc. is resolved automatically. This seems to be working...

Is this also the functionality you wanted to have?
Or are you trying to download the fulltext document? 

This download functionality is NOT implemented for all kind of publishers and is in most cases not accessing the resolved DOI website but e.g. is (after trying out some other repositories) finally using a Google search to find the document.

**Comment by geyslein** [comment]
Hey Matthias, yeah, I was originally requesting the file (pdf, fulltext, document) import functionality for Zenodo. I guess @Siedlerchr missinterpreted and I then jumped on the same train :) The bibtex/metadata import with DOI works like a charm. So it is a **+1** for importing fulltext via Zenodo

**Comment by matthiasgeiger** [comment]
Okay I think now it is clearer ;-)

The API for file-downloads is currently not yet published (see http://developers.zenodo.org/#rest-api) - so I think we will put this "on-hold" for the moment and check later the status of the API.
