### ISSUE TITLE
Check for comma separation in "keyword" field

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#4843]
Using the dev version from today.

JabRef accept keywords in the `keywords` field without (or with space) separator.
By default `biblatex` use comma (`,`) as separator. Not using it causing some problems e.g. when you filter your bibliography by keywords.

![screen](https://user-images.githubusercontent.com/11861496/55477388-37b09000-5619-11e9-8f85-9dd9b34e2af0.png)

Separators in `biblatex` can be modified. So I think it would not be the best solution for JabRef to check for comma only.

There should be a warning or something like that if you have multiple keywords but no comma between them.

**Comment by tobiasdiez** [comment]
If I understand you correctly you want to have a check that reports `keywords={TestA TestB TestC}` because there is no comma between the words, right? But what if the user decides to put spaces into their keywords like `bibliographic manager, JabRef is the best` (which would be two valid keywords)?

**Comment by Siedlerchr** [comment]
At least for keyword groups you can speficy your own keyword separator

**Comment by noMICROSOFTbuhtz** [comment]
You understood me correct and I understand you.
Currently I have no solution.

But keep in mind: A user of JabRef shouldn't know much about biblatex syntax rules. JabRef is a GUI. IMO it is the job of a GUI to keep the user away from "to complex things". You have to find a way to vizualize this different possible and valid ways to use keywords.

e.g.
You know how keywords/tags are displayed on StackExchange (e.g. StackOverflow?). Do it like this would be ergonomic, user friendly and easy to understand. This would protect the user for having problems.

**Comment by Siedlerchr** [comment]
I think this is a good idea. For crossref field we have such highlighting, so could be implemented similarly

**Comment by DOFfactory** [comment]
I can second this, multiple websites provide multiple ways of keywords, unfortunately JabRef performs pretty poor in scraping them at the moment from these websites. Sometimes these are listed as `keyword1, keyword2, keyword3`, others as `Key Word1; Key Word2; Key Word3` (please note the spaces) or `Keyword1 [Tab] Keyword2 [Tab] Keyword [3]`. It would be great if Jabref could automatically adjust the keywords into correct `biblatex` syntax based on these hidden/not so hidden characters.

**Comment by noMICROSOFTbuhtz** [comment]
I aggree with Sidlerchr and DOFfactory
