### ISSUE TITLE
Cleared search is redone after switching library

### ISSUE THREAD

**Issue by bdcaf** [JabRef/jabref#4846]
to reproduce:

1. open two libraries
2. search in first one
3. clear search in first
4. switch to second library
5. switch back to first

then in first library the search is restored.

info:
```
JabRef 5.0-dev--snapshot--2019-04-03--master--a273eb1fa
Mac OS X 10.14.3 x86_64 
Java 1.8.0_191
```

**Comment by Siedlerchr** [comment]
I recently worked on the search feature and I would like you to try out this version here and report back if it is now working for you:
https://builds.jabref.org/convertSearchWorker/

**Comment by bdcaf** [comment]
Did a quick test.  Unfortunately it still restores the deleted search.

**Comment by Siedlerchr** [comment]
Thanks for your feedback. Will look into this. in #4897

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
