### ISSUE TITLE
No visual feedback for searching multiple fulltexts online and only the URL is linked and not updated after the file is downloaded

### ISSUE THREAD

**Issue by r0light** [JabRef/jabref#4854]
**Is your suggestion for improvement related to a problem? Please describe.**
When using the tool "Search full text documents online" there is no visual feedback to the user whether the search is in progress. When many entries are selected the tool may take some time but the user does not know.

Furthermore, in `FindFullTextAction` the found URL is linked, the download is triggered via `LinkedFileViewModel.download` and then the file is added to the entry. But because, `download` is executed in a background task, only the URL is linked and not the downloaded file. It is then found by the automatic file linker leading to two entries (see screenshot).

![fileEntries](https://user-images.githubusercontent.com/24212145/55611979-65b3e280-5787-11e9-8e49-3a359f7446de.PNG)

**Describe the solution you'd like**
I would suggest a dialog with the progress, although the user then has to wait.
And add the entry only after the file is downloaded.

**Comment by Siedlerchr** [comment]
Fixed by #4855
