### ISSUE TITLE
Dialog close after pressing ok button

### ISSUE THREAD

**Issue by Ali96kz** [JabRef/jabref#4857]
Steps to reproduce:
1) File -> Connect to shared database
2) Enter wrong database password
3) You will see error. When you close or press ok the connect to database dialog will close too. 
<img width="473" alt="Screenshot 2019-04-06 at 22 49 53" src="https://user-images.githubusercontent.com/15236829/55674513-71ee8b80-58be-11e9-9425-7351e3c25699.png">

**Comment by tobiasdiez** [comment]
Thanks to @harinda05 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
