### ISSUE TITLE
Error occurred when parsing entry: 'Error in line 286: EOF in mid-string'. Skipped entry.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4861]
JabRef 5.0-dev--snapshot--2019-04-05--master--38e162df4
Windows 7 6.1 amd64 
Java 1.8.0_201
- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I worry about this error. I opened the bib-file in notepad ++ and there does not seem to be an error, not is the entry at line 286 skipped or any one in the vicinity before or after this line. 
I would like to get tipps to analyze the situation for the following reasons:

1. If there is an error I would like to remedy it. But how to get the proper line? The one given by the log is obviously not the one an editor sees. And this is strange since bib-files are not compressed and differ otherwise from textfiles.
2. If there is not an error in line 286, why does Jabref report it as such?

  
1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Could you please provide us the bib file? The error might be a follow up error from a previous entry, where a curly brace is missing or one is too much. So this might be interpreted as a new entry and therefore the line might differ
Do you get an error in your Latex compiler (bibtex/biber)?

**Comment by bernhard-kleine** [comment]
Hi, I will provide a dropbox link to the bib-file:
https://www.dropbox.com/sh/skr30lg9weaom8l/AAAYiN-Ylb9Hz5eiReoE05CXa?dl=0. 
I have not used for quite some time Latex so I do not know.

**Comment by bernhard-kleine** [comment]
I checked some entries in front and behind the error but do not find any indication of something unusual.

**Comment by Siedlerchr** [comment]
Your bib file is fine. No errors in the latest master version , neither opening nor import
