### ISSUE TITLE
AuthorList parse adds extra space if author middlename is abbrevatied without dot

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4864]
Importing the PubMed entry with the Id gives me a bunch of names.
However in e26d9ab9a7e47b2818c8eafd2e08de5808d6ce98 I added a normalize names formatter to add dots to the abbrevated names.

However, the Authorlist.parse method adds an extra space between the first and last name of the last author.
`N.[space][space]Henriette`
```java
Author{firstPart='N.  Henriette', firstAbbr='N. H.', vonPart='null', lastPart='Uhlenhaut', jrPart='null'}
```

Input entry to the formatter:
```
@article{,
  author = {Dyar, Kenneth Allen and Hubert, Michaël Jean and Mir, Ashfaq Ali and Ciciliot, Stefano and Lutter, Dominik and Greulich, Franziska and Quagliarini, Fabiana and Kleinert, Maximilian and Fischer, Katrin and Eichmann, Thomas Oliver and Wright, Lauren Emily and Peña Paz, Marcia Ivonne and Casarin, Alberto and Pertegato, Vanessa and Romanello, Vanina and Albiero, Mattia and Mazzucco, Sara and Rizzuto, Rosario and Salviati, Leonardo and Biolo, Gianni and Blaauw, Bert and Schiaffino, Stefano and Uhlenhaut, N Henriette},
}
```

Workaround is to call the NormalizeNames formatter again, then the space is removed

Entry preview in import is correct, so the error is the parser:
![grafik](https://user-images.githubusercontent.com/320228/55688817-75951780-597d-11e9-96b2-2851890a24a5.png)

**Comment by matthiasgeiger** [comment]
Not the last author is affected, but the problem seems to be caused by the quite special format of this particular name `Uhlenhaut, N Henriette`.

The single character without dot as the first firstname causes problems...

**Comment by Siedlerchr** [comment]
@matthiasgeiger  is right. I wrote a quick test to check:
```
        Author author = AuthorList.parse("Uhlenhaut, N Henriette").getAuthor(0);
        author.getLastFirst(false) 
```
Results in `Uhlenhaut, N.[space][space]Henriette`
