### ISSUE TITLE
Main Table: Right click on DOI field: Allow copying DOI

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#490]
Currently, the popup of DOI allows for clicking the DOI only. It should also be possible to isse "copy DOI", where the complete link is copied.

Usecase: Quick sharing of URLs to references.

**Comment by stefan-kolb** [comment]
On which field? In field editor? See #492

**Comment by koppor** [comment]
In the main table. At the DOI column. See screenshot:

![grabbed_20151209-205427](https://cloud.githubusercontent.com/assets/1366654/11696901/0facf692-9eb7-11e5-9533-7b6bb0ff59f1.png)

**Comment by matthiasgeiger** [comment]
I'll check whether I can integrate this in #452.

**Comment by matthiasgeiger** [comment]
Status: not yet implemented

**Comment by simonharrer** [comment]
Function could also be added to the entry editor.

**Comment by boceckts** [comment]
I will close this as everything seems to be done.
