### ISSUE TITLE
Error when opening a bibtex file with a entry containing and "id" field

### ISSUE THREAD

**Issue by sverlan** [JabRef/jabref#4905]
If the bibtex file contains a field which is named id, then the corresponding file is not read (nothing happens). If run from the command-line, then Jabref is not starting.

Tested on Jabref 4.3.1

Sample file :
```
@article{a,
	author = {John Doe},
	id = {a},
	journal = {X},
	number = {8},
	pages = {1--2},
	title = {Y},
	volume = {1},
	year = {2010}
}
```
[sample.zip](https://github.com/JabRef/jabref/files/3100969/sample.zip)

**Comment by Siedlerchr** [comment]
Hi, the bibtex field 'id ' is a reseverd field by JabRef and JabRef should show an appropiate error message on opening

When I open the file via drag and drop in JabRef I get an exception in the Sytem.err stream on the console.
`Java Messsge:The field name 'id' is reserved`
When I selected File-> Open Database, I get the Exception dialog.

IllegalArgumentException is a RuntimeException and therefore unchecked and in our case seems to be caught by the JVM/JavaFX runtime.

BibEntry.java
setField(.....)
```
 if (BibEntry.ID_FIELD.equals(fieldName)) {
            throw new IllegalArgumentException("The field name '" + name + "' is reserved");
        }

```

**Comment by tobiasdiez** [comment]
There is no reason to throw an error when the id field is present. The internal id of the entry is stored in a separate variable:
https://github.com/JabRef/jabref/blob/1d4e2d1ad254a32a1444e0515a8bfdef1a812a8c/src/main/java/org/jabref/model/entry/BibEntry.java#L61

**Comment by tobiasdiez** [comment]
Thanks to @CaptainDaVinci this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
