### ISSUE TITLE
"Mark entries" is gone in 5.0 (or not implemented yet)

### ISSUE THREAD

**Issue by geekoverdose** [JabRef/jabref#4906]
JabRef version 5.0-dev (master--latest)

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The possibility to [mark entries](http://help.jabref.org/en/Marking) seems to be gone. Was this removed for 5.0 on purpose, or is it not implemented yet? Sorry if I overlooked information that would point this out somewhere.

As usual, my system setup: Arch Linux, i3 window manager, java version:
```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

1. Way 1: right click on any entry in the database: the context menu does not show any possibility to mark references. 
2. Way 2: mark any reference in the database: the top menu does not provide any way for marking/unmarking an entry either.

![2019-04-22-152448_5280x1080_scrot](https://user-images.githubusercontent.com/1210249/56491784-9edca880-6524-11e9-8eff-196cff9383d0.png)
![2019-04-22-173623_5280x1080_scrot](https://user-images.githubusercontent.com/1210249/56491967-4063fa00-6525-11e9-82a1-9caf034373e5.png)

**Comment by Siedlerchr** [comment]
Hi, the feature has been reworked, it is now part of the Groups function: See #3769 for details. You can assign a group color and it will be displayed.
The help page will be updated on release.

**Comment by koppor** [comment]
For reference, this is how it looked like - taken from https://github.com/JabRef/jabref/issues/3276#issuecomment-334938339

![grafik](https://user-images.githubusercontent.com/320228/31308687-2711e144-ab7b-11e7-9597-32b25ae9cf6f.png)

<img width="805" height="760" alt="Image" src="https://github.com/user-attachments/assets/f6eee0f8-646e-4039-9465-80a7110854fb" /> - taken from https://www.linux-magazin.de/ausgaben/2011/11/bitparade/

![grafik](https://user-images.githubusercontent.com/320228/31308690-2ec66216-ab7b-11e7-9952-30ec6dc7d505.png)

**Comment by koppor** [comment]
Background:

- https://discourse.jabref.org/t/why-was-the-mark-specific-color-option-removed/1954/7
- color for imported entries: https://discourse.jabref.org/t/what-does-the-entry-colors-mean/402/9
- https://github.com/JabRef/jabref/issues/4906
