### ISSUE TITLE
Right part of top icons seems to be positioned too far right in 5.0 if window is small

### ISSUE THREAD

**Issue by geekoverdose** [JabRef/jabref#4907]
JabRef version 5.0-dev (master--latest)

- [ x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

This concerns the top icons in JabRef, like new database, open database, save, etc (right below the menu). The right portion of those icons, including new article, delete article, undo, redo, cut, etc, seems to be positioned too far right if there is limited space available (e.g. window being resized to being somewhat small). In those cases there is a lot of space available in that area, but the icons are displayed out of the screen and the small `>>` arrows button is shown, which on click shows those icons. The search bar is displayed like in the middle of the available space it seems.

My system setup, should this be a system specific thing:
Arch Linux, i3 window manager, java version:
```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

1. Resize Jabref to a smaller size
2. Observe the icons on top: the left portion is displayed correctly, the right displayed too far right, despite there is still space available to show buttons there.

![2019-04-22-151910_1295x527_scrot2](https://user-images.githubusercontent.com/1210249/56492436-c765a200-6526-11e9-9787-ee6c81373915.png)

**Comment by Siedlerchr** [comment]
@MartinKarim Did you track this issue as well in your User study`?

**Comment by wujastyk** [comment]
I hadn't noticed this before reading #4907, but I see the issue too.

JabRef 5.0-dev--snapshot--2019-05-26--master--7c2580230
Linux 5.0.0-15-generic amd64 
Java 1.8.0_212

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
