### ISSUE TITLE
Remove apostrophes from generated BibTex keys

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4912]
JabRef version: latest master  on  Windows 10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Have an author with the name `Arnolʹd`
2. Generate key to get something like `Arnolʹd2000`

The apostroph `ʹ` should have been removed from the key.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Fixed in aab77a1
