### ISSUE TITLE
Main table sorting also seems to have disappeared from Preferences

### ISSUE THREAD

**Issue by pirius** [JabRef/jabref#4919]
JabRef version 5.0-dev (master--latest)

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Besides the maintable not being sortable by clicking the column headers atm (https://github.com/JabRef/jabref/issues/4886), the sorting described in [JabRef's main window](http://help.jabref.org/en/BaseFrame) "The default sort order can be set up in Preferences → Entry table" seems to not show up in the preferences. I would guess it would be in "Entry table" tab as the docs say and where it is in 4.3, or in "Entry table columns" tab. Did that move somewhere else for 5.0 and are the docs simply out of sync, or is that a bug/not implemented yet?

1. In 5.0, open preferences: sorting is missing in "Entry table" (as well as in "Entry table columns")

![2019-04-24-100215_990x774_scrot](https://user-images.githubusercontent.com/1210249/56625537-bb89f500-6678-11e9-97af-7ac0d2761a86.png)
![2019-04-24-100658_911x764_scrot](https://user-images.githubusercontent.com/1210249/56625539-bfb61280-6678-11e9-9640-ed9adeb411d2.png)

**Comment by Siedlerchr** [comment]
Simliar to the column width, the sort order is stored on change and can be directly manipulated in the maintable, it is stored but however currently not reapplied after startup: https://github.com/JabRef/jabref/issues/4224#issuecomment-455907173

**Comment by pirius** [comment]
OK, to clarify: this does not exist in the preferences in 5.0 anymore *on purpose*, as it should *only* be done directly through the maintable? Then I guess this actually is not an issue and sorting instead just depends on https://github.com/JabRef/jabref/issues/4886 and https://github.com/JabRef/jabref/issues/4224 being fixed. Thx!

**Comment by tobiasdiez** [comment]
Yes, it was removed on purpose, because it is more intuitive to change sorting via the maintable.
