### ISSUE TITLE
Copy to clipboard disabled for every field in FieldEditor

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#492]
Only available when text is selected.

**Comment by koppor** [comment]
Here on my system, If field editor is opened and if nothing is selected, nothing is copied at Edit/Copy (or click on copy).

**Comment by koppor** [comment]
"Paste from clipboard" should be disabled if clipboard is empty.

**Comment by koppor** [comment]
Bonus: Show current clipboard content

**Comment by simonharrer** [comment]
http://www.javapractices.com/topic/TopicAction.do?Id=82
