### ISSUE TITLE
Option to disable notification popups at bottom of screen

### ISSUE THREAD

**Issue by kbarros** [JabRef/jabref#4942]
In my use with JabRef 5.0 so far (which is starting to look very promising!), I have found the dark gray notification boxes at the bottom of the screen to be distracting, and not very useful. Is there a way to disable them? Perhaps they would fit better in an optional "activity log" window for users who really want to track/debug the history of actions.

JabRef 5.0-dev--snapshot--2019-05-01--master--f1b4b5be3
Mac OS X 10.14.4 x86_64 
Java 1.8.0_212

**Comment by LinusDietz** [comment]
Well, we kinda want to stick with these notifications and will improve them in future. They might not yet be perfect, but there won’t be a way around them.
