### ISSUE TITLE
Automatically move linked PDF files to general file directory

### ISSUE THREAD

**Issue by kbarros** [JabRef/jabref#4948]
There is an option to set `Library properties` -> `General file directory`. Once set, this shows up in the `.bib` file as:

`@Comment{jabref-meta: fileDirectory:[mydir];}`

However, this option does not seem to be respected when linking a PDF. I can't drag-and-drop (that's [issue 4947](https://github.com/JabRef/jabref/issues/4947)), but I can right-click and select `Attach file`. When attaching this way, it will not move the PDF file to the target directory [mydir].

JabRef 5.0-dev--snapshot--2019-05-01--master--f1b4b5be3
Mac OS X 10.14.4 x86_64 
Java 1.8.0_212

**Comment by matthiasgeiger** [comment]
I think there is a misunderstanding about this feature. Existing files already stored elsewhere are not automatically moved to the set file directory (but there should be a manual action in the right click menu to do this).
 The main file dir is however used for the "Autolink" feature and when files are directly downloaded by JabRef.

**Comment by kbarros** [comment]
Hi, thanks for your response.

This feature seems to work differently in JabRef 4. Previously, I could "drag-and-drop" the PDF file and it would do two three things: (1) Rename the file as "[bibkey] - [title].pdf", (2) move the file to the "General file directory", and (3) link it with the entry.

In JabRef 5,  it does only (1) and (3), and step (2) requires an additional (and unintuitive) action.

It would be very helpful if JabRef 5 were able to move the file, consistent with the JabRef 4 behavior.

**Comment by kbarros** [comment]
Let me also say: I'm super grateful for all the work you and others do on this project. JabRef has been my tool of choice bibtex manager for a long time. Version 5 is shaping up to be a huge upgrade. It is fantastic that we have such a mature, functional, cross-platform bibtex manager

With this feature and a few other fixes ([PDF drag and drop](https://github.com/JabRef/jabref/issues/4947); [integration with Mac Finder](https://github.com/JabRef/jabref/issues/4938); [order by column](https://github.com/JabRef/jabref/issues/4886); [avoid pasting twice](https://github.com/JabRef/jabref/issues/4836)) I don't think there is much to miss from JabRef 4!

**Comment by Siedlerchr** [comment]
The current development version now has a setting to define the default action for drag and drop. 
In addtion, it supports the use of modifiers.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by awa5114** [comment]
is it possible to deactivate the autolink behavior altogether?
