### ISSUE TITLE
Switch to ADS API

### ISSUE THREAD

**Issue by zychen-astroph** [JabRef/jabref#4949]
ADS Classic is closing this Fall. Currently ADS search in JabRef fetches entries from ADS classic (and also they are linked to ADS classic). Is there any plans for updating ADS classic to new ADS in 'web search'？

Although we can by ourselves replace all the 'http://adsabs' with 'https://ui.adsabs/' in our existed .bib files or modify some of the codes, I am wondering if there are any other better solutions.

Many thanks.

**Comment by matthiasgeiger** [comment]
Currently we were not aware of ongoing changes. 
Can you please provide us some links to the new search function and maybe to some documentation? 

This would make life a bit easier for us... 

Thank you!

**Comment by zychen-astroph** [comment]
Dear Madam/Sir,

Thanks for your email.

Open ADS classic (http://www.adsabs.harvard.edu/), and you will find on the top of the page: “ADS Classic will be deprecated in May 2019 and retired in October 2019. Please redirect your searches to the new ADS modern form or the classic form. More info can be found on our blog.”

An official reminder about the transition is available here: https://adsabs.github.io/blog/transition-reminder,
While search in classic form is still available: https://ui.adsabs.harvard.edu/classic-form

And here is a simple guide to the new ADS where you can find more about the search function: http://adsabs.github.io/help/quickstart/
(B.T.W., I find the new ADS is much much better than the old version)

I really appreciate your work on it as I am a heavy user of jabref.

Best,
Zuyi

- - - - - - - - - - - - - - - - - - - -
Zuyi Chen

Undergraduate Student
Department of Astronomy, University of Science and Technology of China
No. 96 JinZhai Road, Hefei, 230026, China.
Email : czyxzjl@mail.ustc.edu.cn, zychen.astroph@gmail.com
Homepage : http://home.ustc.edu.cn/~czyxzjl/

**Comment by zychen-astroph** [comment]
Thanks for your email.

Open ADS classic (http://www.adsabs.harvard.edu/), and you will find on the
top of the page: “ADS Classic will be deprecated in May 2019 and retired in
October 2019. Please redirect your searches to the new ADS modern form or
the classic form. More info can be found on our blog.”

An official reminder about the transition is available here:
https://adsabs.github.io/blog/transition-reminder,
While search in classic form is still available:
https://ui.adsabs.harvard.edu/classic-form

And here is *a simple guide* to the new ADS where you can find more about
the search function: http://adsabs.github.io/help/quickstart/
(B.T.W., I find the new ADS is much much better than the old version)

I really appreciate your work on it as I am a heavy user of jabref.

Best,

**Comment by tobiasdiez** [comment]
We should probably switch to the official API: https://github.com/adsabs/adsabs-dev-api/blob/master/Search_API.ipynb

According to https://github.com/adsabs/adsabs-dev-api/issues/30, we need to use the search API and then afterwards the [Export API](https://github.com/adsabs/adsabs-dev-api/blob/master/Export_API.ipynb) to obtain the bibtex code.

**Comment by DBerke** [comment]
A few weeks ago I noticed that using the ADS option in the drop-down list in the ID-based entry generator had stopped working, and seeing this issue I wonder if the timing of that is related? Has it stopped working for anyone else?
(I'm using JabRef version 4.3.1 on MacOS 10.12.6 in case that's relevant.)

**Comment by JoHaHu** [comment]
I will try to resolve this issue.

**Comment by JoHaHu** [comment]
This issue can be closed.

**Comment by tobiasdiez** [comment]
Thanks to @JoHaHu this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by astroboylrx** [comment]
It seems fetching some items fail with this fetcher. If I understand correctly, for ADS, I need to use the Bibcode. And some examples of fetcher failure with

JabRef 5.5--2022-01-17--27a05c7
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

are

https://ui.adsabs.harvard.edu/abs/2008ApJ...684.1291O/abstract
https://ui.adsabs.harvard.edu/abs/2018ApJ...869L..46D/abstract

Any ideas? Thanks in advance.

**Comment by zychen-astro** [comment]
> It seems fetching some items fail with this fetcher. If I understand correctly, for ADS, I need to use the Bibcode. And some examples of fetcher failure with
> 
> JabRef 5.5--2022-01-17--27a05c7 Windows 10 10.0 amd64 Java 16.0.2 JavaFX 17.0.1+1
> 
> are
> 
> https://ui.adsabs.harvard.edu/abs/2008ApJ...684.1291O/abstract https://ui.adsabs.harvard.edu/abs/2018ApJ...869L..46D/abstract
> 
> Any ideas? Thanks in advance.

Such problems occur whenever there are latex errors in the abstract. In the first case, there is "\mathstrutN}". Can this be fixed easily?
