### ISSUE TITLE
Duplicate check on import should be run in background Task

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#4963]
Import a large database.
Import dialog nearly freezes. In debug mode you see that the DuplicateCheck is run on the FXThread and is time consuming.

Should be running in a background task.

**Comment by dimmonn** [comment]
could you help me to understand it better? what action do I do to import db? is it File -> Import ?
how many entries shall the db have to be able to reproduce the issue?

**Comment by Siedlerchr** [comment]
@dimmonn  Thanks for your interest in this issue.
First start JabRef with debug parameter http://help.jabref.org/en/CommandLine#debug-mode---debug
Then File->Import into current library 

Large database: We have a simple pyhton script to generate a large bib database  in the /scripts/ folder.
It generates 10,000 entries or so. I think 100 entries or so should be enough.

When you now import, you see the import window which listst the entries to be imported and you see that it freezes because of the duplicate check .

Codewise a starting point is to look at the methods in ImportEntriesViewModel.java
there are two methods findInternalDuplicates and DuplicateCheck.
At least the internalDuplicate method is running on the FX Thread and therefore blocking the user input.

**Comment by dimmonn** [comment]
@Siedlerchr thank you, ill try to figure this out

**Comment by tobiasdiez** [comment]
It might be a good idea to show a progress dialog for the complete import. For this you can use the following method:
https://github.com/JabRef/jabref/blob/c754a790d669212464742fea4bc7cf67f83e094b/src/main/java/org/jabref/gui/DialogService.java#L196

**Comment by dimmonn** [comment]
@tobiasdiez thank you

**Comment by dimmonn** [comment]
@tobiasdiez shall I implement DialogService or shall I somehow re-use jabref/src/main/java/org/jabref/gui/JabRefDialogService.java to show the progress?

**Comment by Siedlerchr** [comment]
@dimmonn You should wrap the code in a BackgroundTask, that is the javafx high level concept. 
See for example  here: 
https://github.com/JabRef/jabref/blob/251c44d37207663834660e9582cb36c9fcedaabe/src/main/java/org/jabref/gui/externalfiles/AutoLinkFilesAction.java#L73-L76

And for the ProgressDialog:
See here for an example:
https://github.com/JabRef/jabref/blob/251c44d37207663834660e9582cb36c9fcedaabe/src/main/java/org/jabref/gui/externalfiles/AutoLinkFilesAction.java#L73-L76

**Comment by dimmonn** [comment]
@Siedlerchr ok thx

**Comment by Siedlerchr** [comment]
@dimmonn  Bascially our BackgroundTask is a wrapper around the javafx Task 
https://docs.oracle.com/javase/8/javafx/interoperability-tutorial/concurrency.htm

**Comment by dimmonn** [comment]
Right got it thx

**Comment by dimmonn** [comment]
hey gents, just wanted to check if im on the right way
I am trying to do the below
org/jabref/gui/importer/ImportEntriesDialog.java:103

I introduce changes lilke

   Callable<Boolean> hasDuplicateEntryTask = () -> viewModel.hasDuplicate(entry);
                    BackgroundTask.wrap(hasDuplicateEntryTask).onSuccess(e -> {
                        if (e) {
                            Button duplicateButton = IconTheme.JabRefIcons.DUPLICATE.asButton();
                            duplicateButton.setTooltip(new Tooltip(Localization.lang("Possible duplicate of existing entry. Click to resolve.")));
                            duplicateButton.setOnAction(event -> viewModel.resolveDuplicate(entry));
                            container.getChildren().add(1, duplicateButton);
                        }
                    }).executeWith(Globals.TASK_EXECUTOR);
                    return container;

so that this method org.jabref.gui.importer.ImportEntriesViewModel#findInternalDuplicate

will be seen in the other thread

<img width="584" alt="image" src="https://user-images.githubusercontent.com/6670698/57971599-61870180-7990-11e9-93a1-1ed1f1cdd334.png">

**Comment by Siedlerchr** [comment]
Best is to create a Pull Request, so we can directly see the code changes in the context and see the results of unit tests.
But generally looks like it goes in the right direction
See also that the method hasDuplicate is called from the importEntries method in viewModel and at least one other method. So you need to wrap those as well.

**Comment by dimmonn** [comment]
sorry added wrong description

**Comment by Siedlerchr** [comment]
Fixed by #4981
