### ISSUE TITLE
Reference Link for Exception handling rationale not working - Code Howto documentation

### ISSUE THREAD

**Issue by dressjo** [JabRef/jabref#4969]
Minor link change. The link for further reading around rationale for exception handling is no longer valid on this page:

https://github.com/JabRef/jabref/wiki/Code-Howtos#test-cases

Non working link:

(Rationale and further reading:
 https://today.java.net/article/2006/04/04/exception-handling-antipatterns
)

**Comment by Siedlerchr** [comment]
Thnks for pointing this out! Changed it to  https://www.baeldung.com/java-exceptions and also fixed another method regarding files
