### ISSUE TITLE
Italics for species and gene in entry preview 

### ISSUE THREAD

**Issue by Lxmic** [JabRef/jabref#4982]
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_191

Steps to reproduce:

1. ...
2. ...
3. ...

Paste your log details here.

**Comment by matthiasgeiger** [comment]
Hello, can you please provide us some more details?

Thank you!

**Comment by Lxmic** [comment]
Hello，I have anquestion：How does jabref identify the species and gene name italics in the reference title。when I search a reference，jabref can't recognize the italics。like following pic：in the red rectangle，this is a species name，it should be italicized，but not。the jabref has this function？because I'm a biology student, I will ususally use species and gene name(they should be italic). Can you give some advices?



121428269@qq.com
 
From: Matthias Geiger
Date: 2019-05-19 23:04
To: JabRef/jabref
CC: lxm0404; Author
Subject: Re: [JabRef/jabref] Automatic Bug Report - 20190519155628 (#4982)
Hello, can you please provide us some more details?
Thank you!

**Comment by Siedlerchr** [comment]
Hi,

you need to upload the picture in the github issue directly, answering per mail does not work with pictures included.

**Comment by Lxmic** [comment]
![image](https://user-images.githubusercontent.com/24666444/57984968-a34ca080-7a93-11e9-9e62-17a285800b1a.png)

**Comment by tobiasdiez** [comment]
If you want them to be shown in italics, you need to surround them by `\textit{Gymnadenia canopsea}`.

**Comment by Lxmic** [comment]
but，if Ihave hundreds of reference，I must do it one by one？


发自我的iPhone

------------------ Original ------------------

**Comment by matthiasgeiger** [comment]
If the data source from where you download the data is not providing this information, yes. 

It is not possible for JabRef to automatically know what part of a title should be in italics.

**Comment by Lxmic** [comment]
thanks。
Another question. I used Google scholar to get information, my IP was blocked. How long my IP can use again or never be reused?


发自我的iPhone

------------------ Original ------------------
