### ISSUE TITLE
Backgroundcolor of all the dialogs in dark mode

### ISSUE THREAD

**Issue by calixtus** [JabRef/jabref#4987]
JabRef 5.0-dev--snapshot--2019-05-20--master--21b13f3f2
Windows 10 10.0 amd64 
Java 1.8.0_212
- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The Backgroundcolour in all the dialogs (I did not test all, but it seems so) in dark-mode is bright-white.

1. Open Preferences / Appereance
2. dark-mode and ok
3. restart JabRef
4. Open any Dialog

<img width="424" alt="prefs-dark-mode" src="https://user-images.githubusercontent.com/50491877/58050468-b3c25100-7b4f-11e9-9530-c95e02a4b419.png">
<img width="235" alt="about-dark-mode" src="https://user-images.githubusercontent.com/50491877/58050470-b624ab00-7b4f-11e9-8f0a-6e1bd78a784b.png">

**Comment by tobiasdiez** [comment]
Thanks to @davidemdot this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
