### ISSUE TITLE
File entry dialog does not start in the main file directory mentioned in Options

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4995]
JabRef 5.0-dev--snapshot--2019-05-11--master--3baa6bd22
Windows 7 6.1 amd64 
Java 1.8.0_211

When adding a file to an entry, the dialog starts at the location of the bib-file. However it should start at the directory mentioned in Options - preferences - file - main file directory. If the file is not in that directory, there might be something unusual. But normally I put my pdf etc. files there. 

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks to @davidemdot  this should be fixed now in the latest master.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by bernhard-kleine** [comment]
It works! Thank you very mich.
