### ISSUE TITLE
IEEXplore Online Fetcher not working

### ISSUE THREAD

**Issue by shat07** [JabRef/jabref#4997]
Online fetcher not generating results. Problem started 3 weeks back, prior to that it was working perfect. In the beginning, the error was shown as internet connection issue. After updating the JabRef with latest version, the search keeps processing, with no result. The internet is connected with proxy hostname and authentication already given in the preferences.
![screen](https://user-images.githubusercontent.com/50617012/58316944-633e4280-7e32-11e9-8485-11b9bfb55537.png)

**Comment by Siedlerchr** [comment]
Thanks for your report! This was indeed a bug in the IEEE fetcher. In addtion, if any fetcher throws an error it will be displayed in a dialog now.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by shat07** [comment]
Thank you for your reply. The following error occurs while search. Kindly guide.

![error](https://user-images.githubusercontent.com/50617012/62124196-36515480-b2e7-11e9-9187-db696788aa3a.png)
