### ISSUE TITLE
Right Click Option Menu Truncated

### ISSUE THREAD

**Issue by wangch7** [JabRef/jabref#5000]
Version:
JabRef 5.0-dev--snapshot--2019-05-25--master--3ebc59a76
Mac OS X 10.13.6 x86_64 
Java 1.8.0_201

Download:
![image](https://user-images.githubusercontent.com/32211053/58389641-ea85e480-7ff1-11e9-8850-7d3645d50d99.png)
http://builds.jabref.org/master/ 

**Issue Description**
Option menu is truncated when entering full screen.

Full option menu
![image](https://user-images.githubusercontent.com/32211053/58389693-3e90c900-7ff2-11e9-93aa-c0e835306fdb.png)

Truncated option menu
![image](https://user-images.githubusercontent.com/32211053/58389701-4ea8a880-7ff2-11e9-9803-b60606074dc6.png)

**Steps to reproduce the issue**
1. Launch JabRef tool
2. Open library --> Open any bib file (if do not have an existing bib file, create a new one)
3. Double click on Article
4. Navigate to General tab
5. In File field, import a pdf file
6. Enter full screen for JabRef tool
7. Right click on one pdf file
8. Issue occurred. For my computer, "Remove link" and "Permanently delete local file" options are truncated. (screen shot comparison shown above).

**Comment by Siedlerchr** [comment]
Can no longer reproduce in newest version on OSX.
