### ISSUE TITLE
LaTeX integration

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5002]
Dear JabRef users, we have accepted one student (@davidemdot) for Google Summer of Code who will be working to improve JabRef. The topic of his work is to improve the workflow for LaTeX and JabRef users, for example to import citations from a .tex file.
He is actively looking for feedback on his use cases and prototype designs. Of course, additional ideas are always welcome as well!

http://discourse.jabref.org/t/project-latex-integration-please-give-us-your-feedback/1660

**Comment by harinda05** [comment]
First of all congratz @davidemdot . If the tex file is related with .bib file, the solution would become rather complex. The workflow would be something like 

1. search and find '\cite' in tex file.
2. extract the keyword of the related bib entry
3. search bibtex file for that keyword and extract the bib entry itself.
4. List bib entries in Jabref main table.
5. Add forward and backward integration for editing bib entries.

Im nor pro in latex or jabref but always would love to help out in any issues or related work

Hari

**Comment by davidemdot** [comment]
Thanks so much, @harinda05! I really appreciate your time. The workflow that you propose is broadly what it has been planned. Therefore, I am happy to agree with your point of view.

Whenever you may have some spare time, it would be great if you could have a look at some prototypes, please. They are shown in this forum thread:

http://discourse.jabref.org/t/project-latex-integration-please-give-us-your-feedback/1660

In particular, here is the prototype for finding bibliographic entries:

![Finding bibliographic entries](https://user-images.githubusercontent.com/12954316/58562536-be54a880-8229-11e9-9788-881ba618fb89.png)

Regards,

David

**Comment by calixtus** [comment]
Hi @davidemdot , I tested your additions with my thesis, and I found it actually useful. 👍 
However I found an issue: in the citations search results (and the tab) you show the quoting paragraph in the tooltip. As there is no automated linebreak, this tooltip becomes very large. Is there a way to automatically break the paragraph into multiple lines and to shorten long paragraphs into about 5 lines before and after the quotation? Long URL's probably have to be shortened by force...

**Comment by davidemdot** [comment]
@calixtus

Hi there!

Thank you for your quick and positive feedback. Big point what you commented. We will work on it and have a solution as soon as possible.

![tooltip](https://user-images.githubusercontent.com/12954316/62811475-1f3e0e00-bb02-11e9-9e53-74088d566a29.png)

Thank you again!

**Comment by Siedlerchr** [comment]
There is a class called Tool tip Text Util or similar. Maybe you can add it there

**Comment by tobiasdiez** [comment]
As this is project is now finished and the feature included in the latest development versions, I'll close this issue. Feel free to experiment with it and report any problems that you encounter or suggestions for improvement.
