### ISSUE TITLE
Missing icon in macOS Launchpad

### ISSUE THREAD

**Issue by dheckl** [JabRef/jabref#5003]
JabRef version 4.3.1 on macOS 10.14.5

Apple's generic app icon is displayed instead of JabRef's icon in macOS Launchpad:
<img width="150" alt="screenshot" src="https://user-images.githubusercontent.com/9950090/58429283-b1a74780-80a5-11e9-9e77-33381520e823.png">
The icon is displayed normally in the dock – depending on the required resolution.

I had to recreate the app.icns file because it is partially corrupted. Could the updated file be added to the pre-build dmg-files?
[app.icns.zip](https://github.com/JabRef/jabref/files/3224351/app.icns.zip)

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. The icon file was indeed corrupted. I replaecd it and it should be avaiable in the latest master version now.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by dheckl** [comment]
Commit fixed the corrupted icon. Checked with `JabRef_macos_5_0-dev--snapshot--2019-05-27--master--0a4210e2a.dmg`.
