### ISSUE TITLE
BibLaTeX: Shorttitle and Shortauthor fields

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#5004]
It would be great, if in the new and updated entry editor it would be possible to add also `shorttitle` and `shortauthor` fields. Some biblatex styles enable the use of these, and it makes sense when referencing institutions, e.g. United Nations – UN.

**Comment by Siedlerchr** [comment]
As a workaround you can add them manually in the biblatex source editor tab and JabRef will show them then also in the entry editor

**Comment by DOFfactory** [comment]
Thank you @Siedlerchr, I am well aware of this. However, it is a "feature request" since the redesign is well underway, so why not to implement it? If I might recommend to have a look at BibDesk, where introduction of new fields is easy, and can be pre-set for individual use-cases. Something similar would be great to have in such an excellent tool as JabRef is.

**Comment by Siedlerchr** [comment]
@DOFfactory  We had the option to easily customize fields (Custom fields) but this needs to be re implemented in javafx #4719 and is still aviable in 4.3.1

**Comment by stefan-kolb** [comment]
The question is which special types we should include. As far as I know we stuck with the required and ioptional fields defined by the Biblatex manual. ALl other types that are special or data types, such as the mentioned Shorttitle and Shortauthor fields would require us to include a multitude of additonal fields. Therefore, this is up to the user to customize if needed at the moment.

**Comment by soloturn** [comment]
@stefan-kolb how would one customize these fields without always going with a text editor and edit the bib file?

**Comment by Siedlerchr** [comment]
We had previously the Customize entry types dialog for this. This dialog needs to be reimplemented with the new gui architecture.
