### ISSUE TITLE
Entry preview doesn't appear

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5012]
Using JabRef 5 from 2019-05-30 on Windows 10.

Menu point "View / Entry preview (Alt + 2)" is check by default.
But the entry preview doesn't appear when I select an entry.

I have to press Alt + 2 two times.
Or I have to double click on an entry, the edit window comes up and I close the edit window.

It feels like that the entry preview window/pane doesn't have a correct heigth/possition when starting JabRef.

**Comment by Siedlerchr** [comment]
Possible related to #4808 . However, we are currently evaluating the option of integrating the entry preview in the entry editor. See #4976 for an idea

**Comment by stefan-kolb** [comment]
With #5218 the entry Preview will be integrated inside the entry editor.
