### ISSUE TITLE
Entry preview: Missing DOI in Test-Entry data

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#5013]
Using JabRef 5 from 2019-05-30 on Windows 10.

In "Preferences / Entry preview" is a button "Test" which shows up "Smith2016" as a bibtex entry. This entry doesn't have a doi what makes it impossible to test how my entry preview style would look like with a doi.

I checked the sources but couldn't find the file/position where "Smith2016" comes from. Sorry, I am not familar with modern Java and the project structure.

**Comment by Siedlerchr** [comment]
The TestEntry comes from the TestEntry class.
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/util/TestEntry.java

**Comment by matthiasgeiger** [comment]
I'm already updating it ;-)
