### ISSUE TITLE
where to drop PDF to import as new entry?

### ISSUE THREAD

**Issue by mensch72** [JabRef/jabref#5017]
Where exactly do I need to drop a PDF file that I drag into Jabref if I want Jabref to import it as a new entry and extract the metadata from it? While I can drag a file onto an existing entry to link it to it, dragging it anywhere else in the Jabref panel seems to have no effect. I expect an import dialogue to appear. At some screen locations (like in the top row of the main panel where the column names are shown or in empty rows of the main panel), the mouse cursor shows a plus sign, but dropping it there still has no effect...
I'm using 
JabRef 5.0-dev
Linux 5.0.0-15-generic amd64 
Java 1.8.0_191

**Comment by andrejdam** [comment]
Really good question. This worked very good in Docear (with JabRef 2.7.1) by dropping a PDF on the labels of the columns in the table (i.e. entrytype, author/editor, title, year, etc.).

But I tried dragging a PDF myself now there, to no avail. Nothing happens.
An automatic metadata extraction from the file title or xmp or other metadata would be great!

**Comment by matthiasgeiger** [comment]
You are right. That *should* be working...

**Comment by andrejdam** [comment]
Well, I just tried this on Windows by dropping the PDF onto the list itself. It was successful. It created a new item.

However, instead of populating it with sniffed data, it just fills the [Title] field with the name of the file. 
Then I have to go to GScholar, find the bibtex file, paste it in the entry's bibtex field, then add the file = {} field....

You could just use Docear's GScholar sniffer, it works great for now (unless Google change their layout). Here's a link: https://www.scss.tcd.ie/joeran.beel/blog/2017/10/05/update-for-the-google-scholar-parser-library-to-fetch-metadata-for-pdf-files/

**Comment by Siedlerchr** [comment]
The feature has been reworked, there is a PR or issue discussing the changes. Also the new key binding Dropping on maintable should read XMP values and create a new entry with them. If no value found pdf import will be triggered or dialog shown 
Alternatively, you can still use the import dialog

**Comment by andrejdam** [comment]
Could you please post a link to the discussion? I cannot find it.

BTW the import dialog is, for now, a suboptimal solution - especially when compared to Docear's sniffer. In Docear, one can import an entry with info based on multiple information types: file name, XMP, or just plain import without any data.

Additionally, you can search GScholar according to the name of the file, it's XMP/PDF title, or the user can change the query! This is clearly superior and more convenient (see the picture below).

Of course, Docear's sniffer is not perfect - there's plenty of room to be improved. But if you could implement these features, or integrate the sniffer, inside JabRef - that would ease the organizational burden, especially when dealing with multiple documents that are to be imported.

<img width="348" alt="Docear GScholar sniffer" src="https://user-images.githubusercontent.com/51234066/58761269-f0b81b80-8531-11e9-91d3-9c22d6123faf.png">

**Comment by Siedlerchr** [comment]
@andrejdam 
The following behavior has been implemented as documented here: https://github.com/JabRef/jabref/pull/3765 in the 5.0-dev

Dropping a file on the maintable:
1. First XMP import is tried, it no value found then the normal PDF import is tried.
2. If both XMP and PDF import are unsucessful, an empty entry with the linked files i created

The "sniffer" you refer to has long been implemented in JabRef. Just open the entry editor and click on the circular arrow: Update with bibliographic from the web (e.g. CrossRef, Arxiv and some others)
![grafik](https://user-images.githubusercontent.com/320228/58778025-3546c400-85d1-11e9-827b-334035297ec1.png)

**Comment by andrejdam** [comment]
Ah, yes, I know. No GScholar, though. :) I still hope to have an import dialog that also adds Docear's unique solution.

**Comment by Siedlerchr** [comment]
@andrejdam We have a google scholar fetcher accessible in the left Web Search pane, but after too many requests you will be blocked by Google for a while.

The usual workflow is the other way round: First I search the entry from within JabRef using the web search or generate it from an identifier like DOI, arxivid, ISBN....) and then I use the Lookup fulltext document feature.

**Comment by andrejdam** [comment]
Yes, but it doesn't connect to the document itself that I have on my hard drive. What I typically do is download the file, rename it in a manner that makes sense (author - title [year]), and then put it in Docear. Docear fetches the bibtex data.

Now I additionally copy Docear's fetched bibtex data and go into JabRef to copy them into a new entity (because Docear messes up with my database, so I use a separate one for JabRef).

**Comment by tobiasdiez** [comment]
This is now implemented in the latest development version. You can drop the files in between entries (or before/after them) to import the file as a new entry, see screenshots in #5306. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
