### ISSUE TITLE
Add UTF-8 explanation for jstyle files / Enable Unicode import

### ISSUE THREAD

**Issue by andrejdam** [JabRef/jabref#5018]
Alright, so, several days ago I tried to create my own .jstyle file. It went great until I unconsciously saved the file in Unicode (in Notepad) instead of UTF-8. All hell broke loose. I couldn't load the file, JabRef was unable to see it, started banging my head upon the keyboard - all the usual troubleshooting.

Then, my subconscious floated this wonderful idea: what if I resave the same file in UTF-8?! I did it and - voila: JabRef can use it again.

Now, this is not clear at all in your documentation for LibreOffice connection. So either make it clear on the website (https://help.jabref.org/en/OpenOfficeIntegration), or enable JabRef to read all types of Unicode files, not just UTF-8.

**Comment by Siedlerchr** [comment]
JabRef interally uses UTF8 for all kind of files and so I would suggest you rather add an explaination to the3 help page. You can do that by, just clicking on the "Edit this page" link at the bottom of the link.

**Comment by andrejdam** [comment]
Excuse me @Siedlerchr, I had no idea I could do that. I just made a suggestion. Thanks for the heads up.
