### ISSUE TITLE
"Set up general fields" character check not correct & alphabetical ordering

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#5019]
This is a report from the latest snap built version

Enter options | Set up general fields

Enter a field name that contains a hyphen "-". This input is not accepted; the error message does not mention hyphens, however.

In earlier jabref versions fields with a - were still possible to be specified as a general field.

**Comment by ilippert** [comment]
Also, I note that the Tabs are automatically alphabetically ordered - this is unfortunate.

**Comment by Siedlerchr** [comment]
Thanks to @yurickyh  and @kaiquekk this issue is now resolved in the latest master.
The snap should be updated automatically (edge). If not. please drop a message so we can trigger a manual build.
https://build.snapcraft.io/user/JabRef/jabref

**Comment by ilippert** [comment]
thanks a lot!
