### ISSUE TITLE
entry editor: select which fields to show wrapped

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#5021]
Current snap version on fedora 30

Whilst the Abstract field is shown in the entry editor as a wrapped field, a custom field is not shown as wrapped.

**Comment by ilippert** [comment]
just to note that this "enhancement" worked as expected in JabRef 4.3.1.

**Comment by johann-petrak** [comment]
I think this is a bug, not a feature request as this has worked as expected before, has been used to enter text and now breaks all these use cases.

**Comment by stefan-kolb** [comment]
what the fuck are you talking about?

**Comment by LinusDietz** [comment]
can you post a screenshot with the "bug"?

#jabcon

**Comment by ilippert** [comment]
updated now to latest snap version

I have this entry

`@InCollection{Clark:2010Mem,
  author       = {Andy Clark},
  title        = {Memento's Revenge: Objections and Replies to the Extended Mind},
  chapter      = {3},
  editor       = {R. Menary},
  pages        = {43--66},
  abstract     = {In the movie, Memento, the hero, Leonard, suffers from a form of anterograde amnesia that results in an inability to lay down new memories. Nonetheless, he sets out on a quest to find his wife's killer, aided by the use of notes, annotated polaroids, and (for the most important pieces of information obtained) body tattoos. Using these resources he attempts to build up a stock of new beliefs and to thus piece together the puzzle of his wife's death. At one point in the movie, a character exasperated by Leonard's lack of biological recall, shouts: ``YOU know? What do YOU know. YOU don't know anything. In 10 minutes time YOU won't even know you had this conversation'' Leonard, however, believes that he does, day by day, come to know new things. But only courtesy of those photos, tattoos, tricks and ploys. Who is right?These are the kinds of question addressed at length in the paper (co-authored with David Chalmers) ``The Extended Mind'. Is the mind contained (always? sometimes? never?) in the head? Or does the notion of thought allow mental processes (including believings) to inhere in extended systems of body, brain and aspects of the local environment? The answer, we claimed, was that mental states, including states of believing, could be grounded in physical traces that remained firmly outside the head. As long as a few simple conditions were met (more on which below), Leonard's notes and tattoos could indeed count as new additions to his store of long-term knowledge and dispositional belief. In the present treatment I revisit this argument, defending our strong conclusion against a variety of subsequent observations and objections. In particular, I look at objections that rely on a contrast between the (putatively) intrinsic content of neural symbols and the merely derived content of external inscriptions, at objections concerning the demarcation of scientific domains via natural kinds, and at objections concerning the ultimate locus of agentive control and the nature of perception versus introspection. I also mention a possible alternative interpretation of the argument as (in effect) a reductio of the very idea of the mind as an object of scientific study. This is an interesting proposal,},
  annote       = {read 5/10/2010, London. I liked the paper. Clark defends his argument for an extended mind (incorporating things outside the brain) against various criticisms. It is a philosophical paper, involving mostly thought experiments. The point, really, is that cognition is situated in a socio-techno-natural environment.},
  crossref     = {Menary:2010},
  file         = {:Clark.A2010 Memento's Revenge Objections and Replies to the Extended.pdf:PDF},
  project      = {Thinking},
  ranking      = {rank4},
  readstatus   = {read},
  recommend-by = {A Billion Gadget Minds-Workshop},
  timestamp    = {2019-08-25 02:34},
}`

and it shows in the entry editor these two fields - one with wrapped text, the other without.

please let me know, if you need further information.

![1](https://user-images.githubusercontent.com/20518297/63644092-1a23b600-c6e1-11e9-821e-89c9ab0f0dab.png)
![Screenshot-20190825023339-1003x382](https://user-images.githubusercontent.com/20518297/63644093-20199700-c6e1-11e9-8a01-527b1edbdc73.png)

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Note that it only works for unknown fields. So for example, the field `annotation` is still displayed as a single-line field because it is a standard bibtex field.

Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by ilippert** [comment]
Hi @tobiasdiez,
thanks - will only be able to check once it is rolled out to snap package.
Just to check my UI confusion: in the preferences|File I can specify which fields to save not wrapped. As a user I would expect that this would relate to how the field is displayed. I note the technical difference. However, it does not seem straight forward, if storage and display are handled differently, especially if a user makes an effort to specify fields in the preferences.
cheers,
ingmar

**Comment by johann-petrak** [comment]
Thanks I just tested this and can confirm that this now works for all unknown fields.
