### ISSUE TITLE
Entry Editor: "Other fields"

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#5028]
current snap version on Fedora 30.

It seems to me that the algorithm that sorts what fields to show in the tab "other fields" is well identifying and showing those fields that are not default or optional. 
The algorithm does not seem to check whether a "custom" field is displayed in another tab.

Use case: I have defined as general fields a field called "teachingmodule" and show that field in a separate tab. However, it is also shown in tab "other fields". The latter seems not clean.

**Comment by CyraxSector** [comment]
I'm working on this. Still in the analysis phase and get back with more information.

**Comment by Siedlerchr** [comment]
If you need any help with locating the issue or the code, just ask here or in gitter chat

**Comment by CyraxSector** [comment]
@Siedlerchr I've analysed the logic under EntryEditor.createTabs(). Hope I'm on the right path or is there any other place I should look at?

**Comment by tobiasdiez** [comment]
@CyraxSector That's the correct place to look at. In particular,
https://github.com/JabRef/jabref/blob/47e3cc5617e456df03ef8b48500c824d09cec004/src/main/java/org/jabref/gui/entryeditor/OtherFieldsTab.java#L33-L43

**Comment by CyraxSector** [comment]
@tobiasdiez Thanks. I'm carrying on the investigations

**Comment by CyraxSector** [comment]
PR https://github.com/JabRef/jabref/pull/5056 is open for review

**Comment by Siedlerchr** [comment]
Thanks to @CyraxSector  this issue should be fixed now. 
The snap might take a bit longer to update
