### ISSUE TITLE
No Database update when clicking on group

### ISSUE THREAD

**Issue by boothjw** [JabRef/jabref#503]
I have an extremely large database, and so I rely on the groups function heavily since I use them something like pre-set searches.  This makes Jabref very difficult to use, especially when I am switching often between groups.

In, prior versions of JabRef, when you clicked on a group, the group would automatically float in the main viewer.  In the current version, when you click on a group, then another group, the main viewer does not update.  It only updates when you click on a group, then "all entries", then a new group, or when you submit an unrelated function, such as editing the group or changing a setting.

**Comment by g10996694** [comment]
@boothjw This bug has been reported #417 
It seemed that from the version 3, we have this bug, the 2.x version works fine.

**Comment by lenhard** [comment]
@g10996694 Thanks for making the connection! Since a bug report already exists, I will close this one as duplicate.

@boothjw Feel free to add more info to #417 if needed.
