### ISSUE TITLE
Generate key not working when focus on entry-edit window

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5036]
Using JabRef 5.* on Windows 10 and Debian unstable

 - Add new entry.
 - The entry window opens.
 - Ctrl+G are resulting in "First select an entry" message.

This makes no sense because **of course** I will generate a key for the current entry I am editing.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. Can you please try the latest build from http://builds.jabref.org/master.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I can reproduce on Linux and Windows with current (Friday) dev version of JabRef 5.*

**Comment by stefan-kolb** [comment]
@JabRef/developers Can any of you reproduce this? For me it works.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Please see this screen capture video as a step by step example.
At the end I press Ctrl+G to generate a bibtext-key. And the warning dialog (no entry is selected) pops up.

https://github.com/Codeberg-AsGithubAlternative-buhtz/MICROSOFT_GO_AWAY-Unison-Walker/raw/master/FreeOnlineScreenRecorderProject1.mp4

**Comment by AEgit** [comment]
JabRef 5.0-dev
Linux 5.0.0-27-generic amd64 
Java 1.8.0_222

Ok, I can only reproduce this issue, if the following procedure is followed:

1. Create a new database
2. Do NOT save this database (but keep it open)
3. Generate a new database entry
4. Press <kbd>Ctrl</kbd> + <kbd>G</kbd>
5. The following error message is shown: "First select the entries you want keys to be generated for."

If the database is saved before generating a new database entry, this issue does not occur. So there is a simple workaround for the problem and I do not even know, if this counts as a bug (since the user decided to not save the database).

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I do not get your point.
You mean it matters if the database is saved or not? :D

I can reproduce the Issue in a new database (no matter if saved or not) and in my productive environment. On Windows 10, 7 and Debian GNU/Linux 10.

**Comment by AEgit** [comment]
JabRef 5.0-dev--snapshot--2019-09-09--master--1ad3bd5ae
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

Ok, I have now also checked the Windows version. The behaviour is the same as described for the Linux version https://github.com/JabRef/jabref/issues/5036#issuecomment-529195740 , i. e. I can only reproduce the issue, if the database is NOT saved.

@Codeberg-AsGithubAlternative-buhtz : Yes, I can only reproduce the behaviour you mentioned if the database is newly created and not saved. If I save the database at least once, I no longer encounter the error message you report. Can you please check again, whether that is not the case for you? If not, this is a really strange behaviour - I thought that my observation would explain why @stefan-kolb was not able to reproduce the behaviour you described. But if you encounter this message all the time, then there is something else going on.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I think the main problem is the selection of an entry. That behaviour is not usual.
When creating a new entry it should selected by default - but it is not.
