### ISSUE TITLE
Handling of umlaut while copy and paste of entries

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#5043]
Using `JabRef 5.0-dev--snapshot--2019-05-30--master--ef2ebe165` on Windows 10.

The bib-file is UTF-8 encoded (double checked! with extern editor) and in biblatex style. There are entries with umlauts in the abstract, title, etc.

- On entry has well formated umlauts and they are correctly displayed in JabRef editor and preview window.
- Copy such an entry (Ctrl+C)
- Paste it (Ctrl+V)
- All Umlauts are converted into `�`

Example of such a result (copied from the bib-file)
```
@Misc{Nordhausen2019c,
  author    = {Nordhausen, Thomas and Hirt, Julian},
  title     = {One size does not fit all-systematische Literaturrecherche in Fachdatenbanken. Schritt 6: Entwicklung des Suchstrings},
  date      = {2019},
  language  = {ger},
  doi       = {10.6094/KlinPfleg.5.21},
  abstract  = {In diesem Schritt werden die identifizierten Synonyme und Schlagw�rter entsprechend der Suchkomponenten mithilfe von Booleschen Operatoren miteinander verkn�pft. Diese Verkn�pfung wird als Suchstring bezeichnet und muss f�r jede Datenbank gesondert vorgenommen werden. Bei der Entwicklung ist auch der Einsatz von Wortabstandsoperatoren und/oder Platzhaltern f�r eines oder mehrere Zeichen zu ber�cksichtigen. Neben der Verwendung von Schlagw�rtern stellen die Suchbefehle f�r Suchbegriffe und Synonyme eine M�glichkeit dar, um die Suche einzugrenzen. Bei der Verwendung von Suchbefehlen ist deren Schreibweise (Syntax) in der jeweiligen Fachdatenbank zu beachten.},
  file      = {:1015-2668-1-PB.pdf:PDF},
  groups    = {Review, 2019-06},
  keywords  = {lesen, hirt},
  publisher = {Albert-Ludwigs-Universit�t Freiburg},
  year      = {2019},
}
```

**Comment by stefan-kolb** [comment]
First tests show that copying is fine but pasting alters the encoding via a BibTeX parser.

**Comment by noMICROSOFTbuhtz** [comment]
I can still reproduce the problem with today `JabRef_windows-x64_5_0-dev--snapshot--2019-06-16--master--8d99db113`.

**Comment by stefan-kolb** [comment]
The PR is not merged yet. You can try the branch version if you like http://builds.jabref.org/copy-paste/.

**Comment by noMICROSOFTbuhtz** [comment]
It is fixed. Thanks a lot!

**Comment by noMICROSOFTbuhtz** [comment]
I am not sure here but maybe something other is no brocken.

This is an entry correctly viewed with the current master-snapshot version.
![snapshot](https://user-images.githubusercontent.com/11861496/59856656-a7602c80-9377-11e9-9031-3edb92c60ec9.png)

This one is viewed with the copy-paste branch.
![copy-paste](https://user-images.githubusercontent.com/11861496/59856700-bcd55680-9377-11e9-8a23-a31cf7497dc6.png)

**Comment by Siedlerchr** [comment]
Merged this now into master. So will be avaiable in a couple of minutes in the master version.
