### ISSUE TITLE
crossref resolution does not comply with biblatex specification

### ISSUE THREAD

**Issue by sfo** [JabRef/jabref#5045]
**JabRef version** 

> JabRef 5.0-dev--snapshot--2019-06-10--master--eb42850f7
> Linux 4.4.0-150-generic amd64 
> Java 1.8.0_212

on

> Ubuntu 16.04

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

**Steps to reproduce the behavior**

1. create a *Proceedings* entry `Foo2019`
```
@Proceedings{Foo2019,
  title  = {Foo Conference},
  date   = {2019},
}
```
2. create an *InProceedings* entry `Bar2019` with crossref to `Foo2019`
```
@Proceedings{Bar2019,
  title  = {Bar Paper},
  crossref = {Foo2019},
}
```
3. have a look at the `Bar2019` row at the main table view

**Observed behavior**

The *year* field of the `Bar2019` entry gets populated with the value from the `Foo2019` entry.

**Expected behavior**

All fileds (esp. *year* and *journal/booktitle*) get populated with values obtained from the crossref'ed entry.

**Explanation**

According to the [biblatex documentation](https://ftp.agdsn.de/pub/mirrors/latex/dante/macros/latex/contrib/biblatex/doc/biblatex.pdf) (Appendix B), the *booktitle* field of an *InProcessings* entry inherits the value from the *title* field of the referenced *Proceedings* entry.

**Comment by tobiasdiez** [comment]
As of now, JabRef simply takes the value of the same field from the referenced entry. These advanced mappings of biblatex are not yet taken into account.

The following code needs to be adapted:
https://github.com/JabRef/jabref/blob/d8b2c7ef0e7f8149c50a2b4f6b982731d612993a/src/main/java/org/jabref/model/entry/BibEntry.java#L137-L142

**Comment by CyraxSector** [comment]
@tobiasdiez I'll work on this issue

**Comment by CyraxSector** [comment]
@tobiasdiez PR https://github.com/JabRef/jabref/pull/5086 is open for review.

**Comment by Siedlerchr** [comment]
Thanks to @CyraxSector  this should be fixed now in the latest master.

**Comment by sfo** [comment]
Thanks for you effort. Unfortunately, this does not work for me in the latest master. See the [attached MWE](https://github.com/JabRef/jabref/files/3541139/mwe_inheritance.txt) for testing.

JabRef 5.0-dev--snapshot--2019-08-26--master--b2e6e8383
Linux 4.4.0-159-generic amd64 
Java 11.0.4

**Comment by tobiasdiez** [comment]
Thanks to you this should be fixed in the latest development version 😸 . Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
