### ISSUE TITLE
Validator-Visualization Icon jumping around

### ISSUE THREAD

**Issue by calixtus** [JabRef/jabref#5046]
JabRef 5.0-dev--snapshot--2019-06-10--master--eb42850f7
Windows 10 10.0 amd64 
Java 1.8.0_212
- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The Icon of the validation-visualizer is just in the middle of a textfield, until you click on the textfield, then it moves to the bottem left. Happens in Entry-Editor, not in Shared-Database, but is completly broken in String Constants (as the rest of the dialog)

1. Pick a textfield with a validator showing his icon
2. click on the textfield

<img width="26" alt="visiconhigh" src="https://user-images.githubusercontent.com/50491877/59285953-20240200-8c6f-11e9-9383-c5daa698d696.png">
<img width="24" alt="visiconlow" src="https://user-images.githubusercontent.com/50491877/59285956-22865c00-8c6f-11e9-9640-146ec717146c.png">

**Comment by Siedlerchr** [comment]
The String Dialog is a bit complicated as per default in javafx table the input is accepted when you hit enter (tab does not work).

**Comment by calixtus** [comment]
This was resolved by #6287
