### ISSUE TITLE
Bib file saved in v5.0 beta scrambled in v4.3

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#5050]
The screenshot says it all. In the background the simple text-bib file, in the front the same file opened with v4.3.1 that has been previously saved by the beta v5. I am quite fed up with the beta bugs so tried to go back to stable ... with these results.
![image](https://user-images.githubusercontent.com/10846169/59339716-fae1d300-8d04-11e9-9216-425492a7044f.png)

**Comment by Siedlerchr** [comment]
Hi, we are sorry to hear about your problems with 5.x so far. We are continously working to improve it and fix bugs.
Please check your encoding settings in the preferences. 
Seems like in 4.3.1 you have a different encoding selected as in 5.x

**Comment by DOFfactory** [comment]
Hi, both are UTF-8 for very long time (since 2012 or so).

**Comment by Siedlerchr** [comment]
try resettting your prefs. could be a font issue

**Comment by DOFfactory** [comment]
Done, no effect. The issue remains.

**Comment by stefan-kolb** [comment]
Can you provide us with a part of the bib file to reproduce the issue, please.

**Comment by DOFfactory** [comment]
Not sure why you ask, you have the part of the bibfile on the screenshot. I tried with multiple bib files, all open OK in v5, and none of them open OK in v4.3 (latest stable). I tried resetting the preferences, not sure what else I can do. It is definitely not with the bib files, as you can see yourselves on the screenshot.

**Comment by stefan-kolb** [comment]
The characters that are shown on the screen and the actual byte encoding may totally differ. I'll try to reproduce the issue with an artificail bib file then.

**Comment by DOFfactory** [comment]
I suspect it is not only the bib file as also the headers if the columns are scrambled.

**Comment by stefan-kolb** [comment]
Kind of has to be a font issue, like @Siedlerchr said.

**Comment by DOFfactory** [comment]
Actually, you are right, I reset to Segue UI and it seems fine now. Strange that Jabref 4.3.2 is not able to render a TTF font that is otherwise OK in the rest of the system.

**Comment by Siedlerchr** [comment]
Okay, thanks for your feedback.
