### ISSUE TITLE
Find entries linked to a specific file

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5052]
I would like to know if the file attached to one entry is attached to other entries, too.

I would expect such a feature in the context menu of a "File" in the entry editor.

**Comment by tobiasdiez** [comment]
Why would you want to know this? Because you may have (by accident) linked one file to two entries? In this case, I would suggest to add a check in the Integration check feature.

**Comment by noMICROSOFTbuhtz** [comment]
Again such questions...! Please just accept that other users have other workflows. I do not wish such features just for fun.

But I'll try to explain...
There are PDF files with mutliple articles in them. Thats why.
Sometimes I edit the PDF files - deleting pages etc
But before delete some pages I need to be sure that this PDF is not linked to any other jabref entry where the pages I would like to delete could be relevant.

**Comment by Siedlerchr** [comment]
Thanks for your explaination. We are aware that users have different workflows. Therefore, it's important to us how the workflow exactly looks like and in which context the feature should be implemented.
I agree that such a feature could be useful

**Comment by AEgit** [comment]
On a side-note: Note, that some users have linked files to multiple different entries on purpose (e.g., different chapters of a Book, where both the single chapter AND the book are linked). So this might not be an oversight, but actually desired. I am just mentioning this in case someone wanted to introduce a check that automatically prevents a user from having the same file linked to multiple entries.
