### ISSUE TITLE
JabRef interface

### ISSUE THREAD

**Issue by Mimamok** [JabRef/jabref#5063]
Hey,

this might be a stupid question, but I have some problems with my Jabref interface.

Usually I can see the list of all my literature entries in an upper tab and the "edit entry" fields in the lower part of the monitor. Unfortunately, at the moment it is only the list or just the entry information in the whole view, such as

Book (Raffel2018)
Raffel, M.; Willert, C. E.; Scarano, F.; Kähler, C. J.; Wereley, S. T. & Kompenhans, J.
Particle Image Velocimetry 
Springer International Publishing, 2018

As soon as I click on one entry in the list, I only see the information of that specific entry, which is really annoying.

I think I clicked every button that I could find to change back the view to how it originally was. There is probably an easy solution how I can have both the list and the edit fields simultaneously again.

Thanks already for your answers.

**Comment by Siedlerchr** [comment]
Hi, in the menu view there is an option for opening Entry editor and for toggling entry preview.
When the entry preview is shown, a double click on one entry should open the entry editor.

If it doesn't help you can always reset your preferences

**Comment by Mimamok** [comment]
Hey, thanks for your answer. Resetting the preferences finally did the trick!
