### ISSUE TITLE
Open PDF not working + bibtex key generator

### ISSUE THREAD

**Issue by elvyre** [JabRef/jabref#5064]
JabRef 5.0-dev--snapshot--2019-06-16--master--8d99db113
Linux 4.15.0-51-generic amd64 
Java 1.8.0_212

Hi,
I have switched to Ubuntu 18.04 and since then I puzzle with jabref that I use almost every day: this is very critical for me... I have tried the latest release without success. I have two issues : 
- the first one is for opening PDF, when I click on a pdf link it does not open the file (even though it was working with another version, link not broken). 
- The second issue is the bibtex key generetor that does not follow the pattern I am asking. It always put all the authors names like this
SearlesD.J.andEvansD.J.2000_TJoCP
instead of [auth4:lower][year]_[vol] as written in the preference.

Thank you for your help !

**Comment by stefan-kolb** [comment]
Hi, thanks for your report.

As for your first issue with the PDF functionality, I cannot reproduce this. Can you please have a look inside the preferences -> external programs -> open PDF where you can potentially set the desired PDF reader.
