### ISSUE TITLE
Entry editor: "Copy linked files"

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [JabRef/jabref#5066]
Current dev version.

In the entry editor when I right click on a linked PDF I can move (and rename) the file. But I would also like to have the option to "copy" the file instead of moving.

Because:
Sometimes I work with network drive (e.g. ownCloud, ...) related to a whole team.  I add literatur (PDF) from there to my bib file. And I want to have my own copy of the PDF because my buddies move and edit the PDF on the network drive.

**Comment by Siedlerchr** [comment]
Hi, This option is already there, new in 5.x it's called Copy linked files to folder and located under the Tools menu.
It's also suited for a batch export of linked files, e.g. of all entries.

**Comment by noMICROSOFTbuhtz** [comment]
I see.
I would expect to see this feature in the context menu where "Move file to..." is located already.
For me it would make sense.

**Comment by AEgit** [comment]
Regarding the feature request: It may make sense to also have the feature in the context menu. This should never, however, replace the original functionality, since the latter allows one to quickly batch export the linked files of all (or a large number of) entries, as mentioned by @Siedlerchr (and I have used that option again just yesterday).

**Comment by Siedlerchr** [comment]
Yeah, it should be easy and simple to just add this dialog feature to the context menu in the linked file editing.

**Comment by Siedlerchr** [comment]
Thanks for your suggestion. There is now an option in the contextmnenu of a file in the general tab to copy that selected file. 
Multiple files etc can still be copied from the already existing dialog.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
I can confirm that this feature has been implemented in:

JabRef 5.0-dev--snapshot--2019-07-06--master--add35be12
Windows 10 10.0 amd64 
Java 1.8.0_211
