### ISSUE TITLE
Entry preview lose formating if search field is used

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5069]
Tried with current 5.* dev on Windows 10.

Entry preview looks nice.
![snapshot](https://user-images.githubusercontent.com/11861496/59857384-1e49f500-9379-11e9-9427-f842f2b77aa7.png)

But when I use the search field e.g. `keywords=lesen` or `author=nord` then it looks like this.
![copy-paste](https://user-images.githubusercontent.com/11861496/59857412-328df200-9379-11e9-84b9-ff65369627cd.png)

**Comment by Siedlerchr** [comment]
Issues is from the search highlighting of the search term. When you stop searching it's back to normal

**Comment by Siedlerchr** [comment]
The highlighting is handled by this simple javascript code:

https://github.com/JabRef/jabref/blob/dd4f0a08905cf2ef3d2e3231b1fb87c1950fab9c/src/main/java/org/jabref/gui/preview/PreviewViewer.java#L42-L48

**Comment by noMICROSOFTbuhtz** [comment]
I know nothing about JS.
What does your last post mean? It is easy to fix or the opposite?

**Comment by TomasLukac** [comment]
I have tried if this issue still remains in the master branch and not only does it lose formatting, it also jumps to the Author field automatically, so I am rewriting my Author after search finds a result.
The formatting goes back to normal when I click to other article, not after finishing search, as @Siedlerchr said.

I would like to look at this issue and fix it.

**Comment by tobiasdiez** [comment]
The problem is probably that we read the inner text (i.e everything without formatting) and then set it as the inner html. Should work if `document.body.innerText` is replaced by `document.body.innerHtml`

**Comment by Siedlerchr** [comment]
@tobiasdiez  It is not that easy. That's what I did before. The problem is then that it display and searches matches in html tags

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Confirmed. It is fixed and working for me.
Thanks a lot.
