### ISSUE TITLE
Cursor jumps from Search to Entry window and overrides content

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#5084]
Using
JabRef 5.0-dev--snapshot--2019-06-16--master--8d99db113
Linux 4.15.0-52-generic amd64 
Java 1.8.0_172

When I type a search term into the search field and the entry editor tab is open, sometimes
at arbitrary unexpected moments, the cursor jumps into the first field of the entry window, 
removing and overriding the content there. 
I am now trying to avoid this by always closing the edit window before using the search field, but when I forget, it does still happen.
I have seen #1938 but as that one is for version 3 and closed I thought it may be more appropriate to open a new issue.

**Comment by shat07** [comment]
I am facing same problem even on latest version: JabRef 5.0-dev--snapshot--2019-07-29--master--f6eb5344a

**Comment by Siedlerchr** [comment]
Thanks to @tobiasdiez  this is now fixed in the lastest master

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
