### ISSUE TITLE
JabRef suddenly warns the file has changed on disk and requires review of changes

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#5085]
Similar to #4143, the same behaviour happens. I am using today's version of the snap build on fedora 30. 

when I look into the review of changes list, it seems like all entries of the file are shown.

**Comment by miwurster** [comment]
Happens for me as well... I'm on Windows 10 (10.0 amd64) with Java 1.8.0_171. My Bibfile is synced with Dropbox.

**Comment by tobiasdiez** [comment]
Hopefully, this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
