### ISSUE TITLE
JabRef freezes in Mac OS

### ISSUE THREAD

**Issue by muldergj** [JabRef/jabref#5088]
Sometimes when navigating away from the file annotations tab JabRef freezes. I see this behaviour when I have made annotations in a PDF file. When Jabref freezes I have ForceQuit and restart JabRef
<img width="1332" alt="Screenshot 2019-06-30 at 10 17 48" src="https://user-images.githubusercontent.com/19665831/60393584-82f71380-9b20-11e9-9d63-517e3ab96c02.png">

**Comment by Siedlerchr** [comment]
Are you using the latest development version? Do you get any error in the console?

**Comment by muldergj** [comment]
Hi

I am using this version.
JabRef 4.3.1
Mac OS X 10.14.5 x86_64
Java 1.8.0_211

I believe it is the latest.

Where do I check for errors in the console?

Regards,

[https://s3-eu-west-1.amazonaws.com/gjmautomation/Logo.png]     Gerhard Mulder
Director, GJM Automation Services | EDGE Data Services
RSA: +27 83 631 2737 | UAE: +971 50 465 0453
web: www.gjmtech.com<http://www.GJMTECH.com>
email: gmulder@gjmtech.com |   <mailto:gmulder@gjmtech.com> gm@edgedataservices.com<mailto:gm@edgedataservices.com>
[https://s3-eu-west-1.amazonaws.com/gjmautomation/fb.png]<https://www.facebook.com/GJMTech/>    [https://s3-eu-west-1.amazonaws.com/gjmautomation/li.png] <https://www.linkedin.com/company/gjm-automation-services>    [https://s3-eu-west-1.amazonaws.com/gjmautomation/www.png] <http://www.gjmtech.com/>

On 30 Jun 2019, at 14:21, Christoph <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using the latest development version? Do you get any error in the console?

**Comment by Siedlerchr** [comment]
Hi, please try the latest development version from here. 
http://builds.jabref.org/master/
There haben been a lot of fixes regarding the freezing stuff.
Remember to make a backup of your bib file before trying out the new version.

**Comment by muldergj** [comment]
Thanks

I will give it a try.

Regards,

[https://s3-eu-west-1.amazonaws.com/gjmautomation/Logo.png]     Gerhard Mulder
Director, GJM Automation Services | EDGE Data Services
RSA: +27 83 631 2737 | UAE: +971 50 465 0453
web: www.gjmtech.com<http://www.GJMTECH.com>
email: gmulder@gjmtech.com |   <mailto:gmulder@gjmtech.com> gm@edgedataservices.com<mailto:gm@edgedataservices.com>
[https://s3-eu-west-1.amazonaws.com/gjmautomation/fb.png]<https://www.facebook.com/GJMTech/>    [https://s3-eu-west-1.amazonaws.com/gjmautomation/li.png] <https://www.linkedin.com/company/gjm-automation-services>    [https://s3-eu-west-1.amazonaws.com/gjmautomation/www.png] <http://www.gjmtech.com/>

On 30 Jun 2019, at 15:54, Christoph <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, please try the latest development version from here.
http://builds.jabref.org/master/
There haben been a lot of fixes regarding the freezing stuff.
Remember to make a backup of your bib file before trying out the new version.

**Comment by winterwang** [comment]
Hi, I tried the latest development version on my Mac Mojave, it showed error messages as below:

An internal error occurred (error code: Could not load JRE from The bundle “Java SE 8” couldn’t be loaded because its executable couldn’t be located..)

So it could not be launched normally.

**Comment by Siedlerchr** [comment]
@winterwang  Have you tried the solution here? https://github.com/JabRef/jabref/issues/3587#issuecomment-401551628
Might be the case that there is still an old version of java 8/JabRef in your folder which interferes with the new one

**Comment by winterwang** [comment]
@Siedlerchr Thanks for pointing that out. Problem solved after removing the previously installed JabRef. Now the latest development version works just fine and I like the new interface design. Thanks for the great work!
