### ISSUE TITLE
Bug after editing

### ISSUE THREAD

**Issue by eriicf** [JabRef/jabref#5100]
JabRef version 4.3.1 on Windows 10

- [ x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When you load the .bib file, you then double-click on a line to open the editing part, make the edits, and then close the edit screen, then the detail screen increases in size by itself and covers the screen where shows the references, so it is necessary to manually

1. load the .bib file
2. double-click on a line to open the editing part
3. close the edit screen

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
