### ISSUE TITLE
Not mention OS shutdown

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5102]
JabRef 5.* dev

For me it looks like that JabRef did not recoginize if the operating system is shuting down. While shuting down the OS signaling this to all open applications.

JabRef should catch such events. Blocking shutdown (a bit to much IMO) or saving the content to the backup-file

In the last case JabRef should tell the user at the next start that the backup file is there because of a OS shutdown.

**Comment by stefan-kolb** [comment]
https://stackoverflow.com/questions/1392260/handling-shutdown-event
