### ISSUE TITLE
Unify month field formatting in test bib files

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5116]
In several bib files we have not a unique formatting for the month:

Example:
Some bib files used for testing have different formats for the months. 
This should be made consistent across all files

correct; 
```
  number    = {1},
  pages     = {55--68},
  month     = oct,
```
other looks like
```
  number    = {1},
  pages     = {55--68},
  month     = #oct#,
```

other looks like
```
  number    = {1},
  pages     = {55--68},
  month     =  {#oct#},
```

**Comment by vitorcime** [comment]
Do you know where can I find this bibs files ?

**Comment by koppor** [comment]
@vitorcime Use your IDE's search capability. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> in IntelliJ.

**Comment by koppor** [comment]
Note that `#` is used to render a BibTeX string (see http://help.jabref.org/en/EntryEditor#field-consistency-checking). That means, the entry editor displays `#oct#` when the BibTeX field is `month = oct`. Thus, `oct` is correct. `#oct#` and `{#oct#}` are wrong. They are a result of a wrong implementation somewhere in JabRef. We guess that it is at the entry fetchers or converters (RIS for instance).

**Comment by PorcelainMouse** [comment]
I think this is related to another issue.  The "cleanup entries" implements a "normalize" option on the month field, but converts to abbreviated month, which is not supported by python-bibtexparser (by default).  Also, JabRef writes this field as an integer, not a string, when set from the GUI pull-down field.  So, the code is is not consistent, either.

Is this the right issue?  Or, should I open another one?
