### ISSUE TITLE
Find duplicates: No whitespace on right side

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#5126]
JabRef version 5.0-dev on Arch

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The "Find duplicates" dialog suppressed all whitespace characters on the right side.

1. Create a duplicate entry (copy & paste)
2. Open "Quality" > "Find duplicates"

**Comment by Ezioisbatman** [comment]
I would like to address this issue

**Comment by stefan-kolb** [comment]
As far as I can see, this is only present in `show diff - word`.

**Comment by stefan-kolb** [comment]
Fixed by 72dbfa7a492be39bd86e1c4c38b7cf37c6418863
