### ISSUE TITLE
Import of abbreviation list with umlauts not correctly read in

### ISSUE THREAD

**Issue by equinitry** [JabRef/jabref#5133]
JabRef version JabRef 5.0-dev--snapshot--2019-07-17--master--b094bc6ab
Windows 10 10.0 amd64 
Java 1.8.0_211

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Importing or adding a Journal name with umlauts is scrambled and not correctly saved

1. Open "Manage abbreviations" menu
2. create a new list or import an existing one with journal names having umlauts
3. "Save changes"
4. reopen menu and have a look at the entry (also doesnt abbreviate it because not found)

looks like ISO <--> UTF8 encoding problem

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `journal-abbrev-encoding`. Please try the latest build from http://builds.jabref.org/journal-abbrev-encoding.
