### ISSUE TITLE
DOI from European Commission not loaded

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#5149]
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_172

JabRef version  on 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. check the loading of DOI number 10.2777/130485 on https://dx.doi.org
2. it works
3. check the loading of DOI number in JabRef
4. it does not work

It would be lovely if JabRef would be capable of loading DOI numbers from European Commission documents. Would make life so much easier ....

**Comment by Siedlerchr** [comment]
I could confirm this error, but from what I saw this is a bug on the doi.org side. It does not return the bibtex, but instead the website html code. 
This doi works fine `10.1109/5.771073` 

From what I see this is a general problem with the EU DOIs.

**Comment by DOFfactory** [comment]
Thanks @Siedlerchr, I reported this issue to the contact email of DOI.org

**Comment by Siedlerchr** [comment]
@DOFfactory  JabRef simply makes a HTTP-Request with application/x-bibtex header, if you want to test it yourself

```
curl -X GET \
  https://doi.org/10.2861/747184 \
  -H 'Accept: application/x-bibtex' \

```

**Comment by noMICROSOFTbuhtz** [comment]
Please go to doi.org or do https://doi.org/10.2777/13048.

Then you will receive an error to but you can give a error report on that site. The error depends on the European Commission.

**Comment by LinusDietz** [comment]
Closer as proposed
