### ISSUE TITLE
ToolTip to explain color in the first column of table view

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5152]
Using the JabRev 5.* dev from today. See screenshot for detailed version information.

![screen](https://user-images.githubusercontent.com/11861496/62011221-988a4800-b175-11e9-9a9b-bf4c24cc60db.png)

In that screenshot you also can see blue and white colored vertical bars in the first column of the table view (2 blue, 2 white and 1 without color).

What do they mean?

It should be explained with a tooltip when hovering the color.

**Comment by fdmcneill2019** [comment]
Is there any specific explanations you want provided for each?

**Comment by noMICROSOFTbuhtz** [comment]
I even have no idea what the colors mean. So I do not know what could be provided here. ;)

**Comment by tobiasdiez** [comment]
These are the colors of the groups that this entry belongs to. Thus a tooltip would be "Entry is part of the following groups: x, y, z."

**Comment by noMICROSOFTbuhtz** [comment]
Ah. In that case a tooltip would be the right choice I think.

_Simplest solution_: The color is in the first column right? Title it as "group color" is to wide of course. But you could set a tooltip "group color" to the title of the column (not the entries).

_Alternative_: Or if setting up a tooltip for each entry then I would assume color and the group name (including its path!).

Also in the column settings of the settings dialog I can not see that the first column is the group color. I was looking there first.

**Comment by fdmcneill2019** [comment]
> These are the colors of the groups that this entry belongs to. Thus a tooltip would be "Entry is part of the following groups: x, y, z."

So essentially, the names of the group are the same as the color names? For example, a blue bar means that the entry belongs in the group called "blue"?

**Comment by fdmcneill2019** [comment]
@noMICROSOFTbuhtz  How do I find the main source code file(s) to address this issue?

**Comment by noMICROSOFTbuhtz** [comment]
I am not a core developer here - just a user. I think @tobiasdiez knows the answer.

The name of the group is different from the color. I mean the tooltip should contain the name (e.g. "Science") of the group as a string and the color as a colored rectangle.

**Comment by tobiasdiez** [comment]
According to the code, there should be even a tooltip https://github.com/JabRef/jabref/blob/4b39b78e4afcd6c36b385f5c46f1d9a4eac2e29b/src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java#L142

**Comment by noMICROSOFTbuhtz** [comment]
@tobiasdiez Nice. Again the GUI lib is the "problem".

The tooltip araise only if the entry is selected. If not no tooltip. This is unusual and against standard behaviour of other GUI libs.

Aren't there are GUI libs available with Java today?

**Comment by Siedlerchr** [comment]
Thanks to @mmihuu the problem should be fixed now. there is a now an icon and a tooltip.
