### ISSUE TITLE
Technical report type field broken

### ISSUE THREAD

**Issue by khatchad** [JabRef/jabref#5162]
The `@TechReport` type has a field called "type" with a few options. Selecting one of those options doesn't produce the desirable results. Basically, it looks like those options are shortcodes for some expanded string that never gets expanded. I found [this article](http://bib-it.sourceforge.net/help/fieldsAndEntryTypes.php#type) that explains that the field value should actually be the expanded string.

JabRef 3.8.2
linux 5.0.0-21-generic amd64 
Java 11.0.3

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
