### ISSUE TITLE
Journal and Year missing from bibliography

### ISSUE THREAD

**Issue by shat07** [JabRef/jabref#5163]
While pushing the entries into Jabref library through Websearch, the name of journal and year of publishing are going to the optional field instead of required field. Thus, the journal name and year information gets missed in references in the latex document. 

Kindly guide how to add this to main field. I cant find the "customize entry type" key in "Options" tab. I am using latest version: JabRef 5.0-dev--snapshot--2019-07-29--master--f6eb5344a Windows 7 6.1 amd64.

![a](https://user-images.githubusercontent.com/50617012/62270250-2eaebe80-b453-11e9-8e69-bcb6eb6de084.png)

**Comment by Siedlerchr** [comment]
Thanks to @mmihuu this issue should be fixed now in the latest master version.
