### ISSUE TITLE
Modify columns in table view

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5164]
Using JabRef 5.* dev

The settings dialog looks like that it could be possible to modify the columns of the table view. But it does not work.
e.g. modifing "title" into "subtitle" has no effect and is reset.
What is more unusuabl it is not possible to add new columns (e.g. "subtitle" under "title") or modify their ordering.

**Comment by Siedlerchr** [comment]
The settings dialog is currently in the process of beeing reworked . We will take this into account. 
You can reorder the columns in the main table directly. The position is stored, as well as the size.

**Comment by noMICROSOFTbuhtz** [comment]
Thanks for the hint. Is there an Issue for this?

But I do not only want to reorder the columns. I want to other columsn e.g. `subtitle`.

**Comment by Siedlerchr** [comment]
@calixtus  is currently redesigning and improving the settings dialog. See #5185 for details
