### ISSUE TITLE
Gradle build does not work on a fresh repository clone

### ISSUE THREAD

**Issue by halirutan** [JabRef/jabref#5175]
Latest JabRef repository version on master 9daa645cc compiled on Mac OS X 10.14.5.

Currently, it is not possible to run `gradle build` on a freshly cloned JabRef. The one major issue are errors of the following kind:

```
jabref/src/jmh/java/org/jabref/preferences/LastFocusedTabPreferencesTest.java:5: error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.AfterAll;
```

This error has its origin in the `build.gradle` where the jupiter dependency is included with 

```
testImplementation 'org.junit.jupiter:junit-jupiter:5.5.1'
```

However, the `LastFocusedTabPreferencesTest.java` does not live in the test directory. An easy fix is to use `implementation` instead of `testImplementation`.

Furthermore, for ages and on different machines I got this Gradle error

```
plug-in not found: ErrorProne
```

and @Siedlerchr confirmed that he also sees this error. I wonder why this package is used if obviously, its absence doesn't bother the built.

Finally, I got ~several~ two failing tests (after initializing the submodules):

```
RegExpBasedFileFinderTests. testAuthorWithDiacritics()
BibDatabaseTest. setStringAsCollectionWithUpdatedContentOverridesString()
```

I believe the aim should be that the master branch can be built without errors and all tests passing. This reduces confusion for possible new contributors, e.g. [like this one](https://github.com/JabRef/jabref/issues/5159).

**Comment by Siedlerchr** [comment]
For the citation style failures, did you use the git input

**Comment by halirutan** [comment]
@Siedlerchr Good point, I forgot about this. Nevertheless, there are still two failing tests, and I updated my original post.
