### ISSUE TITLE
Add support for biblatex field aliases

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#521]
In the biblatex documentation at Section 2.2.5, "Field Aliases" are described. 
- address for location
- annote for annotation (jurabib)
- archiveprefix for eprinttype (arXiv)
- journal for journaltitle
- key for sortkey
- pdf for file (JabRef compatibility :sunny:)
- primaryclass for eprintclass (arXiv)
- school for institution

Issue: When switching from bibtex to biblatex mode, the field "journal" is written as optional field, even though it is a required field.
### quick hack

In the serialization of JabRef, aliased fields should be treated like the original fields.

Issue with the quick hack: The aliased field is still treated as optional field or not treated at all. This seems to be inconsistent.
### related bug reports
- [support for journal alias](https://sourceforge.net/p/jabref/bugs/1014/). Reported to be resolved somehow in "JabRef v2.11 beta"

**Comment by cbersch** [comment]
The related bug report on sf isn't relevant, since this was only about the mere possibility to use the `journaltitle` field at all. It didn't try at all to handle field aliases properly.

**Comment by koppor** [comment]
We have some support in the entry table: #24 and some code has been written for the journaltitle field: #1720 and #15

The entry editor, however, still does not support alias and this causes issues when fetching entries: #2209

**Comment by tobiasdiez** [comment]
This is now implemented in the latest development version (at least if I understand it correctly). Could you please check the build from http://builds.jabref.org/master/. Thanks!
