### ISSUE TITLE
Many Rankings disappear in JabRef 3.0

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#522]
Hello,
I just tried to work more seriously with the new version of JabRef and noticed some issues:

1. My database has approximately 200 papers with rankings. I can see them with a plain text editor and they are shown in jabref 2.11 
-> The new version of jabref shows only ranks for some entries (5). All the others disappeared. The text editor doesn't show any differences between the ones shown and the hidden ones.

I can send my bib file per mail on request.

**Comment by koppor** [comment]
Please send the bib file to me. My email should appear on my GitHub site: https://github.com/koppor/

**Comment by teertinker** [comment]
As reported to koppor:
The ranks were shown one day later. May be it was caused somehow by either the very first start of jabref or importing preferences without restarting jabref.

**Comment by stefan-kolb** [comment]
@teertinker So everything is fine for you now?
@koppor Could you reproduce the issue with the bib file? If not I would suggest to close the issue for now.

**Comment by teertinker** [comment]
Everything works for me now. It was not a problem of my bib file. It was either related to loading my bib file the first time with jabref 3.0 or importing preferences without restarting jabref. In either case the reported issue isn't one.
