### ISSUE TITLE
Re-enable Cycling Trough Citation Styles in Entry Preview

### ISSUE THREAD

**Issue by LinusDietz** [JabRef/jabref#5221]
In https://github.com/JabRef/jabref/pull/5218 we disabled the cycling through citation styles in the entry preview to make this PR mergable into master.

This needs to be re-established. (this will come with a major refactoring of the whole Entry Editor.)

**Comment by matthiasgeiger** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master.
