### ISSUE TITLE
Field "Note" in 3.0 cannot be sorted as in 2.11

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#523]
I know, I did missuse the "note" field till now. But it did work until the recent update. 
I used "note" to give each of my entries an increasing number, thereby I was able to 1. give my copied papers this number to match entry and copied paper. And I was able 2. to sort my maintable showing the newest entries on top. I haven't used the timestamp field regularly, so I cant use it to sort my maintable properly.

My Note field contains integers and used to sort the following way:
1
2
.
.
100
101
..

With the new version of Jabref it sorts like:
11
110
1100
1101

My question is, whether I can use any other field that interprets numbers as  integers and not as strings?

**Comment by oscargus** [comment]
You can change it in the preferences. Go to Entry table and add "note" to "Sort the following fields as numeric fields". (The preferences were restructured in 3.0.)

**Comment by teertinker** [comment]
Great,
this was easier than expected!

thanks
