### ISSUE TITLE
Ranking field takes lots of space

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#524]
In general I like the new visualization of ranks. Good papers can be seen much faster. However on small screens, the ranking criteria takes lots of space, while giving few information. 
Most other fields can be resized. Wouldn't this be possible for rankings as well? If the column is to small to display 5 stars it could show e.g. one star and "..." like abbreviated titles do. This way uses know, that the entry has a rank, and further information could be gathered if needed (here a mouseover effect would be great).

**Comment by koppor** [comment]
Minor comment: We had a "compact rank" as setting in JabRef 2.11 and before, but dropped it due to maintainability reasons.

![grabbed_20151216-092043](https://cloud.githubusercontent.com/assets/1366654/11835792/4b470016-a3d6-11e5-8c45-42c4e2b7fc96.png)

**Comment by matthiasgeiger** [comment]
I do not think it is sensible to allow the ranking column size to be modified with the current icons as they are using a fixed size.
Moreover, it is not possible to abbreviate the stars with "..." as with normal text.

There are two "workarounds" - with obvious drawbacks:
a) disabling the ranking column
b) moving the ranking column after the more important fields (which will be default with 3.1 - and is already available in [recent development builds](http://builds.jabref.org/master/)) - then you can resize the window to the needed size and the column is outside the visible area (-> horizontal scrollbar appears)
