### ISSUE TITLE
sun.reflect.Reflection.getCallerClass is not supported

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#5262]
JabRef version 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I always get a warning running the new Jabref with Java11:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
```
Is that a problem or can it be ignored?

**Comment by tobiasdiez** [comment]
You can safely ignore this warning. It comes from `log4j`, the library that we use for logging errors, and as the warning says it still works but the performance might be not as good as before. But as you shouldn't get too much error messages (actually you should get none 😸 ) the performance in this regards is not important.

As we cannot do much against the warning message and it probably disappears automatically with future releases of log4j, I'll close this issue.
