### ISSUE TITLE
Custom SQL export (additional fields)

### ISSUE THREAD

**Issue by Timeas** [JabRef/jabref#527]
Hi,
I'm using JabRef 2.1 and now 3.0 and MySQL 5.6.
I have custom fields in my JabRef databases which I need to export to a SQL server. I have tried to review the layout files and the SQL export files under src but my programming skills are not good enough to issue a pull request and change this.
I was hoping someone might have a trick to export custom fields. Otherwise I would like to suggest it for future versions.
Many thanks
Pete

**Comment by lenhard** [comment]
Hi Pete,

thanks for this suggestion. I cannot guarantee that one of the core developers will address this, since we have other priorities right now. But maybe someone else is willing to submit a pull request.

**Comment by Siedlerchr** [comment]
I think this issues is no longer relevant as JabRef (since 3.6) supports now working directly with a shared SQL database and SQL file export support has been dropped.
http://help.jabref.org/en/SQLDatabase
