### ISSUE TITLE
Allow for deactivation of integrity check

### ISSUE THREAD

**Issue by fspreng** [JabRef/jabref#5275]
As part of #4642, @RonakLakhotia added an integrity check for books with an edition value of "1". Since the official biblatex manual (http://packages.oth-regensburg.de/ctan/macros/latex/exptl/biblatex/doc/biblatex.pdf) suggests the use of the integer "1" for marking the first edition of a book (see bottom of page 18 in the referenced manual), my colleagues and I typically follow this recommendation. As our database is quite large, this results in lots of (in our case not useful) warnings when performing an integrity check. Would it be possible to make this check optional and decide about its execution based on the user's preferences (by default, it can be enabled)? Many thanks in advance!

**Comment by tobiasdiez** [comment]
You can right click the column and select which of the errors you want to be shown (or filter based on the fields/entry types). Sadly, at the moment this feature does not work.

ToDo:
- [ ] Fix filter of table
- [ ] Document this feature as it is somewhat hidden
- [ ] Try to add a "Filter" button in the lower left corner of the dialog that shows the right-click filter menu (if that is possible)

**Comment by matthiasgeiger** [comment]
I have not used the feature lately and I cannot check it atm, but as far as I remember the check is directly executed - so I would opt to just open the dialog, having to chance to select which checks should be run and then to actively start the check. This should be especially helpful in cases of real big databases where you are interested only in some checks.

Bonus: store the selection of integrity checks for the next runs.

**Comment by fspreng** [comment]
Thanks for the hint @tobiasdiez - I completely missed that.

Good idea @matthiasgeiger. In addition, the integrity checks are also performed during the creation of a new entry. Would it be feasible and expedient to store the choice of integrity checks made by the user as part of the user's preferences (as suggested by @matthiasgeiger) and execute only the selected ones? Of course, this solution would require more effort in terms of coding, but could be really helpful.

**Comment by LakminiSenanayake** [comment]
I am investigating on this issue.

**Comment by tobiasdiez** [comment]
@LakminiSenanayake Nice!

I prefer if we don't add a step before the integrity check dialog. Keep it simple for most users and provide access to customized integrity checks in the dialog itself for more advanced use cases.

**Comment by LakminiSenanayake** [comment]
Sure @tobiasdiez , still doing technical investigations and will get back with more details

**Comment by fspreng** [comment]
Dear @LakminiSenanayake,
Have you already had some time to further investigate this issue? Would love to see a solution for it in the next release version. Many thanks!
