### ISSUE TITLE
Add "Titlecase" Formatter for save actions

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#528]
I have used Google Scholar to import entry information numerous times; however, it has usually imported fields such as "title" and "journal" with lowercase entries except for the first letter.  Can a feature be added (perhaps to cleanup entries) to convert user-defined entries (title, journal, booktitle, etc.) to titlecase (i.e., the first letter of each word capitalized)?  

Along these lines, there should perhaps be a list of acronyms that it shouldn't convert the case of (or if lowercase, make strictly uppercase) and words that it shouldn't capitalize (e.g., and, in, of).

For example, I recently imported "Physics in Medicine and Biology" as "Physics in medicine and biology".

**Comment by lenhard** [comment]
Is there not some kind of right-click option that performs this?

Certain formatters are planned as part of the rework of the serialization mechanism. We could consider a titlecase formatter as well. However, this is still distant future and we really really welcome help in the form of pull requests.

**Comment by jkulesza** [comment]
@lenhard Good call, I didn't even think to double-click.  Case conversion is there.  Thanks!  However, this might be a good item to add to the cleanup area to ensure consistency across entries.

**Comment by lenhard** [comment]
Good to hear! I'll keep that issue as a reminder for the formatters and change the title accordingly.

**Comment by oscargus** [comment]
This is a very interesting subject. See kopppor/jabref:#60 and #419 and probably some other issues.

Some points:
* The integrity checker will complain if the title is in title case and you haven't masked the capital letters with {} - this is not really clear to me why
* Masking the capital letters with {} just to keep title case is a bad idea
* The .bib-file should decide on the casing of the title anyway

As I see it, there's no single solution for this. Still providing a more flexible cleanup where one can run any of the formatters on any of the fields would be quite useful.

**Comment by g10996694** [comment]
@oscargus , this problem is also related to issue #295

**Comment by lenhard** [comment]
@g10996694 Thanks so much for this reminder! #295 and this issue stand for the same thing. Since there is no point in having two open issues for the same aspect, I'll close this one as duplicate and discussion can continue in #295.
