### ISSUE TITLE
crossref field must not contain multiple entries

### ISSUE THREAD

**Issue by sfo** [JabRef/jabref#5284]
JabRef 5.0-dev
Linux 4.4.0-159-generic amd64 
Java 11.0.4

Build from latest master at 99a0a7a8d 

---

The entry editor allows to specify a comma separated list for the crossref field. However, this is not allowed, an entry can have only one "parent" entry.

**Comment by tobiasdiez** [comment]
I think this would be best implemented as an integrity check (as we usually don't restrict input in the fields).

**Comment by sfo** [comment]
Actually, the GUI needs refinement as well, I think. The crossref field explicitly allows to set multiple values, which is not correct (see screenshot). This might be changed to allow only one entry or change to a simple text field combined with some integrity checks.

![jabref_crossref](https://user-images.githubusercontent.com/571497/64520572-ba3f2900-d2f6-11e9-8284-a2dbb29c20e9.png)

**Comment by ajsaraujo** [comment]
Can I take this one? In which classes I should work? Which integrity checks should the program perform?

**Comment by LucasB98** [comment]
Hello, 

We are a team of three students from France and we would be glad to try to help solving this issue.
It will be our first contribution to an OpenSource project.

**Comment by Siedlerchr** [comment]
@LucasB98  Bonjour et merci de l'intérêt que vous portez à JabRef 😸 

Please follow our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) for getting started and for setting up the workspace ( I would suggest you use Intellij as there are currently some difficulties with eclipse has some problems atm).
If you have all setup, the relevant classes for this behaviour are `FieldEditor` and `LinkedEntriesEditor`.
They are located under `org.jabref.gui.fieldeditors `
It seems that at the moment both `FieldProperty.SINGLE_ENTRY_LINK` and `FieldProperty.MULTIPLE_ENTRY_LINK` are handled in the same way.
A possible solution would be to separate the handling of multiple entry links (allowing multiple values) and single entry links (allowing only one link).

**Comment by LucasB98** [comment]
We noticed that in crossref field, you can enter your own bibtexkey in crossef. 
An exemple: if I create an entry in a library with John as Author and John2019 as bibtexkey, I noticed we can put John2019 as crossref. But i think that's not normal. What do you think about it ?

**Comment by tobiasdiez** [comment]
That's a good observation. I think, we shouldn't prevent people from entering the same key (maybe he wants to change the key immediately after), but there should indeed be a warning (realized using an integrity check).

**Comment by Vencesdab** [comment]
About the warning you propose, should it be made a new issue ?

**Comment by tobiasdiez** [comment]
I think it would be best to directly implement it as part of your PR, if that is possible.

**Comment by LucasB98** [comment]
We searched a way to compare the crossref field to the bibtexkey of the current entry. Do you know in which file this can be done? 
We found the class BidirectionalListBinding that seems to be related to this task. But we are not quite sure, and it's really far in terms of function calls from EntryLinkList. 
Can you help us please :)

**Comment by Siedlerchr** [comment]
What Tobias means is you should use the integrity checker logic (Quality-> Check integrity)
The integrity check is located under org.jabref.logic.integrity .Take a look at the FieldChecker implementations. Both Crossref (Standard field) and the Key field (internal fields) fields of the class BibEntry.
The ListBIndings are only for the gui to provide helper functions for dealing with javafx

**Comment by tobiasdiez** [comment]
Thanks to @Julien29121998 and collaborators this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
