### ISSUE TITLE
use the systems default language per default in 5.*

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5290]
JabRef 5.0-dev--snapshot--2019-09-08--master--373b9f5f5
Windows 7 6.1 x86 
Java 11.0.4-bellsoft

After installation English is set as language.
But the Windows default is German which IMO should be used by default from JabRef.

**Comment by tobiasdiez** [comment]
This should already be the case:
https://github.com/JabRef/jabref/blob/373b9f5f582729f2e5cb12d03f139eac67d4c7d3/src/main/java/org/jabref/preferences/JabRefPreferences.java#L509-L510

But in order for this to work, you might need to reset the preferences.
