### ISSUE TITLE
System freezes when trying to add a PDF link

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5297]
JabRef 4.3.1
Linux 5.0.0-27-generic amd64 
Java 1.8.0_222

I have not had this problem with the v.5 test releases.

1. Open entry editor, 
2. select "General" tab
3. click the + sign to add a PDF file
4. The file-picker opens (Nemo for me, since I'm in Linuxmint/Cinnamon)
5. type the first letter of a filename to jump to that file
6. Either system freezes for several minutes until a timeout, or Jabref and immediately nemo crash.

Sorry, can't give you a log because of crashes.
The problem is intermittent but common.

**Comment by Siedlerchr** [comment]
Thanks for n the report. 
Yes this was a known issue with 4.3.1, which is solved in 5.0dev.
As we lack resources, cause all of the devs work in their free time, we are unable to support any older versions then the most recent master version. 
We are however working towards a stable and hopefully nearly bug free 5.0 release version.
