### ISSUE TITLE
Combination of working/broken file links -- no fallback to working link

### ISSUE THREAD

**Issue by spamlankin** [JabRef/jabref#5303]
Hi,

I've been using JabRef since 2004ish (currently running v4.3.1, Windows 10 10.0 amd64, 
Java 1.8.0_172), and my .bib file has moved around quite a bit, such that many (most) of the file links are now broken. But, the entries will also have multiple file links associated with them -- a combination of broken links and currently working links. In the screengrab, the top link is broken, and the second link works. When I attempt to open the pdf from the main window, it seems as if JabRef only tests the first link in the list, and does not attempt to fallback and test the others.

 I have tried synchornizing the file links, but that doesn't seem to fix my problem. So, is there a way around this? Is there an easy way of removing all the file links?

cheers,
mike.
![Capture](https://user-images.githubusercontent.com/55181376/64678985-a4ef0980-d472-11e9-8c1c-45b39fa4da9d.PNG)

**Comment by tobiasdiez** [comment]
The second file is not linked (i.e. not part of the `file = {...}` ) but found automatically by JabRef. You can click the small brief case icon to add the file as a link. 

In order to remove all linked files, you can use Library > Manage field names & content
