### ISSUE TITLE
Can't run today's snap/edge 2019-09-11

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5307]
Platform:

NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"

JabRef version:
```
$ snap info jabref
name:      jabref
summary:   Bibliography manager
publisher: Oliver Kopp (koppor)
contact:   https://github.com/koppor
license:   unset
description: |
  JabRef is an open source bibliography reference manager. The native file format used by
  JabRef is BibTeX, the standard LaTeX bibliography format.
commands:
  - jabref
snap-id:      T5x6neyM0Uc9OWDHGorm61NKxh3Bd47k
tracking:     edge
refresh-date: today at 17:41 MDT
channels:
  stable:    –                              
  candidate: –                              
  beta:      5.0-dev 2019-08-26 (530) 212MB -
  edge:      5.0-dev 2019-09-11 (531) 256MB -
installed:   5.0-dev            (531) 256MB -

```

Result of executing /snap/bin/jabref:

```
$ /snap/bin/jabref
Picked up _JAVA_OPTIONS: -Duser.home=/home/dom/snap/jabref/531
Error: Could not find or load main class org.jabref.org.jabref.JabRefLauncher
Caused by: java.lang.ClassNotFoundException: org.jabref.org.jabref.JabRefLauncher

```

**Comment by Siedlerchr** [comment]
I will trigger a manual build later so that yesterday's fixes for snap are included.
Thanks for the report

**Comment by wujastyk** [comment]
Again today, snap/edge of 26 September 2019.  I get this:

```
$/snap/bin/jabref 
ln: failed to create symbolic link '/home/dom/snap/jabref/543/.config/gtk-2.0/gtkfilechooser.ini': File exists
/snap/jabref/543/bin/desktop-launch: line 574: /snap/jabref/543/jabref/bin/JabRefMain: No such file or directory
```

**Comment by LyzardKing** [comment]
I guess the name changed to Jabref...
I just downloaded the tarfile.

**Comment by tobiasdiez** [comment]
Yes, the name changed. Moreover, it should be possible to download https://builds.jabref.org/master/JabRef-portable_linux.tar.gz and run it. So the snap does not need to build via gradle (at least if this is not one of the requirements of a snap - no idea about conventions there).

**Comment by LyzardKing** [comment]
To be honest, it could be easier, since you already have your build system, to pull the tarball and use that directly.
I'm not sure if the snapcraft build system can see that the tarfile changed and to that, but since you are using github actions (or travis) it can be added to the ci I believe

**Comment by tobiasdiez** [comment]
You mean that we should build and push the snap during our build? That's definitely possible (see e.g. https://github.com/sirredbeard/nim_lang_snap/blob/master/.github/workflows/nightly.yml). But maybe there was/is a reason why it's not done. @koppor @Siedlerchr ?

**Comment by Siedlerchr** [comment]
I think one of the problems was that it takes around 15 minutes or around that time to build the snap.
and in earlier versions it was not possible to build and push it to snap

**Comment by koppor** [comment]
+1 for building here. For the master branch only -- second .yml file 😅

Think, I just had difficulties with the long building time and the
upload... Maybe just with the building as such...

Tobias Diez <notifications@github.com> schrieb am Fr., 27. Sep. 2019, 20:25:

**Comment by LyzardKing** [comment]
The snap could be a simple "dump" plugin with the portable build
and the snapcraft build and push to the store could be set up on the existing jabref ci.
I can add a PR with a test it you'd like

**Comment by LyzardKing** [comment]
@tobiasdiez Should I use the portable or the other tarfile?
What is the difference?

**Comment by tobiasdiez** [comment]
Please use the portable! The other (older files) are a remnant of the old build. @koppor can you please clean-up the master and the root https://builds.jabref.org to remove the old builds/experiments. sorry for the additional work!

**Comment by koppor** [comment]
@LyzardKing You could also try the Debian package -- seems to be the most native to snapcraft: http://builds.jabref.org/master/jabref_5.0.0-1_amd64.deb

**Comment by LyzardKing** [comment]
I opened a pr for a snap with the java package.
It might need testing (more than my daily use case)
________________________________

**Comment by koppor** [comment]
Refs #3121

**Comment by tobiasdiez** [comment]
Can this be closed now, or is there more work needed to make the snap working? @LyzardKing @koppor

**Comment by LyzardKing** [comment]
The snap still is not pushing from the build system.
I think this can be closed since it's related to an older version of the snap.
The one currently on the store should mostly work, but it's not up to date.
For the updated version we need to wait for the validation of the permission for the browser addon.
Or while we wait we could remove that part and upload a version without the browser integration.
(I'm not sure if the integration has to be in the snap when they vote on the forum to accept it,
or if it can be added back later on. I suppose I can comment it in the snap and add it back at a later date)

**Comment by tobiasdiez** [comment]
Ok, then we just leave this issue open for now and wait...

**Comment by LyzardKing** [comment]
What do you think?
Is it better to upload a working snap without the browser integration?
Keeping in mind that the extension can still be installed and work

**Comment by tobiasdiez** [comment]
I would say we wait for about a week to get the permission. If this doesn't work out (or we are still waiting), we could push a temporary snap without the extra JabFox stuff.

**Comment by LyzardKing** [comment]
Ok! :)
A week is about what they usually say to wait on the forum before starting the vote as far as I can tell..
In any case a working snap is ready to be pushed. But I wouldn't want to confuse the store upload in any way..

**Comment by koppor** [comment]
If publish another snap, we have to cancel the voting and restart it at a
later time. Since the current snap state is not that critical, I would vote
for "waiting".

Galileo Sartor <notifications@github.com> schrieb am Fr., 18. Okt. 2019,
00:12:
