### ISSUE TITLE
[Bug] "Empty" BibTeX key error on launch for populated key

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#532]
When I launch JabRef 3.0 with my "normal" library it displays the error "Empty BibTex key: ..." for an entry that has the key entered (see screenshot).  

Is there a more useful way I can help debug why this happens for this entry and no others (which I've entered in an identical fashion)?

![screen shot 2015-12-17 at 7 44 41 am](https://cloud.githubusercontent.com/assets/9939059/11870162/2d9eb21c-a493-11e5-9e4c-4907856dd0d2.png)

**Comment by matthiasgeiger** [comment]
Thanks for the report.
However, as you already said this is a rather strange behavior and not easy to debug... 

I think you already did that, but can you please check first, whether there is no duplicate of your selected entry (without a bibtexkey) in the database (e.g. by searching for "oliver" in a text editor).

Has the entry in the file the correct bibtex key?

Have you tried to change the key in JabRef manually to another value? Does the problem persist?

**Comment by jkulesza** [comment]
Ack, you catch me again.  There was a duplicate entry that came along with the import.  I didn't see it because (a) my database was large enough and sorted in such a way it wasn't nearby and (b) the "correct" entry was automatically highlighted on launch rather than the "incorrect" entry.

Regardless, perhaps the dialog about the missing BibTeX key can suggest looking for duplicate entries?
