### ISSUE TITLE
Group Count shows the value of the other library

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5327]
master 1bec5ef Refs #5325 @tobiasdiez 
Two libraries,
one with 16 entries, one with 2 entries.
All entries group shows always the value of the other library.
![grafik](https://user-images.githubusercontent.com/320228/65019167-fc85ed00-d92a-11e9-860a-02e3d3baa783.png)

![grafik](https://user-images.githubusercontent.com/320228/65019413-70c09080-d92b-11e9-9141-87af97e5836e.png)

**Comment by tobiasdiez** [comment]
Can you please debug and/or describe how to reproduce this issue... for me everything is working

**Comment by Siedlerchr** [comment]
I just started the latest build from gradle with ./gradlew run
Two libs were opened at startup.

**Comment by Siedlerchr** [comment]
It appears to me that the wrong bibdatabasecontext is passed

**Comment by tobiasdiez** [comment]
I cannot reproduce it on my two installations...

**Comment by AEgit** [comment]
JabRef 5.0-dev--snapshot--2019-09-16--master--1bec5efd3
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

Cannot reproduce the issue mentioned.
Note, that my setup differs in two (?relevant) points:
1. Library 1 contains 6462 entries. Library 2 contains 4 entries.
2. I have several groups in both libraries, not just the "All entries" group.
3. When I change from one library to the next, the correct entry count is shown in the "All entries" group. Note, however, that it takes a few seconds for library 1 to display the correct entry count. Every time I switch from library 2 to library 1, the entry count displayed in "All entries" is initially 0 and then jumps to 6462 entries. I reckon, JabRef always recalculates the number of entries when switching between the libraries. This behaviour will not be noticed if the libraries contain only a few entries, but with thousands of them you can notice the delay (which I personally do not mind).

**Comment by tobiasdiez** [comment]
Very nice observation @AEgit that the libraries had to have an empty groups tree in order to replicate this issue. With this I was able to fix the problem, and as a thank you also fixed a few other groups related issue you reported a while ago (see #5328).

**Comment by Siedlerchr** [comment]
Can confirm it's fixed now!

**Comment by AEgit** [comment]
@tobiasdiez Cheers, thanks for the nice bugfixes!
