### ISSUE TITLE
Entry preview parses html incorrectly after search with regular expression enabled

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#533]
Jabref 3.0 as well as recent development versions do not parse the html code in the preview window correctly. This seems to happen if there is some html code WITHIN a certain bibtexfield. The citation is parsed correctly, but the "abstract" field in the preview window, which contains some autogenerated and manually inserted html code, seems to delete the "<" of each tag.
the string automatically inserted string "br>", appears the same way as my manual added italics "i>"

![bildschirmfoto vom 2015-12-17 14 16 09](https://cloud.githubusercontent.com/assets/8830305/11870525/ceb1e1da-a4c8-11e5-864b-27c0cf9bd854.png)
![bildschirmfoto vom 2015-12-17 14 16 33](https://cloud.githubusercontent.com/assets/8830305/11870526/cebd3e9a-a4c8-11e5-967d-eb8eae2e932f.png)

**Comment by matthiasgeiger** [comment]
This is working fine for me.

I'm using the default entry preview setting with: 
`\begin{abstract}<BR><BR><b>Abstract: </b> \format[HTMLChars]{\abstract} \end{abstract}`

Can you try this snippet in Options -> Preferences -> Entry Preview?

**Comment by teertinker** [comment]
Thank you for your snippet. I was able to narrow down the problem... somehow. First your snippet changes nothing. There are, however some entries being parsed correctly, and some are parsed false. 
After some digging I realized, that it is somehow connected with the new search function!

How to reproduce it:
- look in your database for some entries with abstract with a certain keyword (e.g. "statistics") 
-> do NOT use the search function.
- have a look at the abstracts, they are parsed correctly
- enable "regular expression" 
- search for the key word e.g. "statistics"
- look at the abstracts of your filtered entries -> they should be parsed incorrectly
- clear the search term and unmark "regular expression"
- go through your database. 
entries that have NOT been part of your filter, should be parsed correctly
entries that were part of the filter are STILL parsed incorrectly

**Comment by matthiasgeiger** [comment]
Thanks for digging into this.

I can reproduce the problem now.

**Comment by simonharrer** [comment]
Please confirm that it is fixed by trying out the newest build containing the fix available at build.gradle.org in about 20 min.

**Comment by teertinker** [comment]
Thanks, it works now. 

However, there is something new, that ist a bit irritating. The preview window for long entries (e.g. those with abstract) is now always scrolled to the bottom. So I can see the abstract, but not the reference. Therefore, to start reading, I have always to scroll to the top of the page. I don't know whether this is intended - it wasn't like this yesterday.

**Comment by simonharrer** [comment]
Hm, yes, I see. Will revert this. Thanks for the info!
