### ISSUE TITLE
Unexpected interaction of keyword and static groups

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#5331]
JabRef version 5.0-dev (commit db96f88 master) on Ubuntu-16.04 x86_64

- [x ] I have tested the latest development version from `* master db96f88 Fix problem with search and switching between libraries (#5326)` from https://github.com/JabRef/jabref.git and the problem persists

The GUI allows to add a static group (or another manually created group) to an automatically create(d) keyword group. However, when such new group is created as a subgroup of the *root* keyword group ("kwds" in my example), it is not displayed in the GUI, although it is registered in the program (the second group with the same name can not be created), and is written into the bibliography file. The only way to access or get rid of such group seems to be manual editing of the bibtex file.

If, on the other hand, the new group is manually created as a subgroup of a *sub-keyword*, it is displayed in the GUI, but is not saved into the output file.

1. Copy the example bibtex database to a new file (both files are in [test-keyword-groups.zip](https://github.com/JabRef/jabref/files/3631639/test-keyword-groups.zip)):
`cp test-keyword-groups-saved.bib test-keyword-groups.bib`
2. Run JabRef on the copy of the file:
`build/image/bin/JabRefMain test-keyword-groups.bib &`
3. Create an "Automatically create groups" subgroup on all entries, call it "kwds":
![Screenshot from 2019-09-19 16-47-39](https://user-images.githubusercontent.com/10668420/65249875-59d19800-dafd-11e9-9782-c5b876823f7f.png)
4. Try to add a "sub-kwds" group by right clicking on the "kwds" group and then immediately "OK". The group is created but not shown on the GUI:
![Screenshot from 2019-09-19 16-52-00](https://user-images.githubusercontent.com/10668420/65250170-d3698600-dafd-11e9-89ad-d756d87011ff.png)
5. Now try to create a group with the same name, "sub-kwds", as as subgroup of "All entries" (right click on "All entries", select "Add subgroup", enter "sub-kwds" as "Name", click "OK"). An error message "There exists already a group with the same name" appears. The "sub-kwds" group, however, is not shown, even after collapsing and expanding the "kwds" groups:
![Screenshot from 2019-09-19 16-54-01](https://user-images.githubusercontent.com/10668420/65251738-8b982e00-db00-11e9-950f-3a1b4fe8a822.png)
6. Add a sub-group of some keyword: right-click on "languages", select "Add subgroup", name it "sub-languages", click "OK". A new sub-group appears on the list:
![Screenshot from 2019-09-19 16-56-38](https://user-images.githubusercontent.com/10668420/65250638-8afe9800-dafe-11e9-960d-b675a917b1a7.png)
7. Click the "Save library" icon to save the bibtex file; exit the JabRef.

The resulting "test-keyword-groups.bib" file has the following groups:
```
@Comment{jabref-meta: grouping:
0 AllEntriesGroup:;
1 AutomaticKeywordGroup:kwds\;0\;keywords\;,\;>\;1\;0xffffffff\;\;\;;
2 StaticGroup:sub-kwds\;0\;1\;0xffffffff\;\;\;;
}
```

Loading this file again into JabRef obviously will miss the "sub-languages" group (which was shown on the GUI!), but will retain the hidden "sub-kwds" group; this group is not shown on the GUI but one can not create such group once more (thus it is registered in the group list). A workaround to "unhide" this group is to edit the "test-keyword-groups.bib" with a text editor and change `2 StaticGroup:sub-kwds` to `1 StaticGroup:sub-kwds`, for example.

Both BibTeX files are attached in a ZIP archive.
[test-keyword-groups.zip](https://github.com/JabRef/jabref/files/3631639/test-keyword-groups.zip)

**Comment by tobiasdiez** [comment]
All subgroups (regardless of there level) of an automatic group should be read-only to every action (i.e drag&drop, edit and adding subgroups should not be possible).

**Comment by sauliusg** [comment]
Thanks for the instant reply! Making auto-groups r/o seems like a good solution.

**Comment by sauliusg** [comment]
On a second thought, keyword groups read-only could remove useful functionality.
Another idea would be to use the same Java code to handle static groups and keyword groups. The advantages would be:

- more functions implemented in less code :);

- both automatic groups and static groups would behave in a similar way, reducing confusion and learning curve height;

- Since keywords now can be hierarchical with the same sub-keyword attached to different main keywords (like in "Astma > Treatment" and "Diabetes > Treatment"), the same would be possible for the static groups!

I apologise for resurrecting issues #3115 and #1873, but the ability to have subgroups with the same name in various parts in the group tree seems essential (all competing bibliography managers can do it seamlessly, and people are used to that). The naming scheme used in hierarchical keywords seems to resolve the name uniqueness issue in the Java code.
