### ISSUE TITLE
Keyword groups with keywords that consist only of spaces are displayed in a strange way

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#5333]
JabRef version 5.0-dev (commit db96f88 master) on Ubuntu-16.04 x86_64

[x ] I have tested the latest development version from * master db96f88 Fix problem with search and switching between libraries (#5326) from https://github.com/JabRef/jabref.git and the problem persists

When a bibtex database contains an entry with a keyword with only spaces in its value:
```
@Article{id3,
authors = {B. Kolker},
title = {Lernolibro de lingvo Esperanto},
keywords = {human > languages, , interlinguistics},
}
```

JabRef displays a strangely shifted empty keyword group that contains *all* entries:
![Screenshot from 2019-09-20 14-39-51](https://user-images.githubusercontent.com/10668420/65324438-e7bc8a00-dbb4-11e9-9256-43f7c1220eb7.png)

1. Load the file `test-empty-keword-group-BROKEN.bib` or `test-empty-keword-group-BROKEN2.bib` (from 
[test-empty-keword-group.zip](https://github.com/JabRef/jabref/files/3635705/test-empty-keword-group.zip)) into JabRef:
```
build/image/bin/JabRefMain test-empty-keword-group-BROKEN.bib &
```

The correctly formatted file `test-empty-keword-group-OK.bib` behaves as expected.

The partially broken file, `test-empty-keword-group-FAIR.bib`, that contains an *empty* "keyword":
```
@Article{id3,
authors = {B. Kolker},
title = {Lernolibro de lingvo Esperanto},
keywords = {human > languages,, interlinguistics},
}
```
(note missing spaces between the two consecutive commas) is also displayed as expected.

**Comment by AEgit** [comment]
JabRef 5.0-dev
Linux 5.0.0-29-generic amd64 
Java 11.0.4

Can confirm this issue.

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-03----16eca244
Windows 10 10.0 amd64 
Java 11.0.4

Can confirm this issue has been fixed in the current development version.
