### ISSUE TITLE
Web search in Medline/PubMed produces empty result

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#5335]
JabRef version 5.0-dev (commit db96f88 master) on Ubuntu-16.04 x86_64

[x ] I have tested the latest development version from * master db96f88 Fix problem with search and switching between libraries (#5326) from https://github.com/JabRef/jabref.git and the problem persists

When searching Medline/PubMed using the Web search feature, a dialogue opens but stays empty, apparently indefinitely. No progress indicator or status feedback is provided:

![Screenshot from 2019-09-20 15-20-07](https://user-images.githubusercontent.com/10668420/65326603-8ac3d280-dbba-11e9-820c-b32319194794.png)

Searches in other libraries (ArXiv, ACM portal, Google Scholar) work as expected.

1. Start JabRef: `build/image/bin/JabRefMain &`
2. Create a new library
3. Search for "nuclease" in Medline/PubMed. An empty dialogue appears and stays indefinitely long.

The PubMed web site (https://www.ncbi.nlm.nih.gov/pubmed/?term=nuclease) is operational during the search and produces 22077 hits. Searches with fewer hits (~50) also fail on JabRef.

The STDERR log does not contain any hints; a lot of "ERROR ThemeLoader Could not watch css file for changes jrt:/org.jabref/org/jabref/gui/Base.css / java.lang.UnsupportedOperationException" are produced, however (but they are always produced in this revision of JabRef...)

Update: creating a new entry using the "Select entry type dialogue", selecting Medline/Pubmed ID type and pasting PMID into the ID field does *not* work as well. The same dialogue works for DOIs, however. Thus, it could be a related issue...

**Comment by Siedlerchr** [comment]
It takes a moment to load the data, but it works fine otherwise.
Could not reproduce it.

**Comment by tobiasdiez** [comment]
We should definitely add a progress indicator.

**Comment by Siedlerchr** [comment]
One of the key performance issues is that for each entry the  Duplicate check is executed, although it's already in a background thread it still takes a lot time.

**Comment by AEgit** [comment]
JabRef 5.0-dev
Linux 5.0.0-29-generic amd64 
Java 11.0.4

Can confirm the issue for the current dev snap version. Note, however, that Google Scholar also does not appear to work reliably.

**Comment by sauliusg** [comment]
Update:
the reproducibility of this issue seems to be dependent on how the KabRef was started (checked both commits db96f88 and 2bd0995, after `./gradlew -Dskip.tests build; ./gradlew -Dskip.tests jlink`):

- if JabRef is started using `./gradlew run`, then the list of PubMed entries appears in 12 sec and is the same as @Siedlerchr reports;

- if JabRef is started using `build/image/bin/JabRefMain &`, the search window stays empty after 1 min., and probably indefinitely.

JabRef 5.0-dev
LinuxMint-18.1 
Linux 4.4.0-53-generic x86_64
openjdk 11.0.4 2019-07-16

In both cases the start sequence was the same:

- start JabRef without a library;

- click the 'new library' icon, select BibTeX

- the PubMed search interface and the group interface were activated automatically (saved from previous launches, or by deleting preferences and selected "PubMed");

- type "nuclease" into the search field and click "Search".

**Comment by bernhard-kleine** [comment]
As of today, I could not repeat the error. The search was done in under 10 seconds.
JabRef 5.0-beta.409--2020-02-09--6a9c915
Windows 10 10.0 amd64 
Java 13.0.2

**Comment by Enrico68** [comment]
As of today, I can reproduce the error. Just upgrade to 5.0 from the dev version (which worked like a charm, and the search button was  showing the entries. Now I have to wait indefinitely without success. I will return to 5.0.dev 
OSX 10.14.6
