### ISSUE TITLE
In a Web search interface, source selection drop-box, highlight moves in an opposite direction

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#5336]
JabRef version 5.0-dev (commit db96f88 master) on Ubuntu-16.04 x86_64

[x] I have tested the latest development version from * master db96f88 Fix problem with search and switching between libraries (#5326) from https://github.com/JabRef/jabref.git and the problem persists

In a Web search interface source selection drop-box, the mouse hover highlight moves in an opposite direction than the mouse cursor itself.

1. Start JabRef
2. Switch on "View|Web search" if not already displayed
3. Click on the drop-down list (search source with a down-arrow on the right).

The behaviour:

http://saulius-grazulis.lt/~saulius/Screencast_2019-09-20_16.03.41.mp4

Update: the same behaviour manifests itself in the "Select entry type" dialogue, "ID type" drop-down list.

**Comment by calixtus** [comment]
duplicate of #5277

**Comment by sauliusg** [comment]
Sorry, overlooked that.
