### ISSUE TITLE
Nothing happens in options dialog "settings for open office"

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#534]
Got to "Settings"-> "External Programs" click on "Settings for open office"

-> nothing happens. Clicking on the other external programs opens a dialog. Should probably be grayed or something else.

**Comment by matthiasgeiger** [comment]
Confirmed. Another `NullPointerException`...

**Comment by oscargus** [comment]
Which isn't surprising considering the code:

``` java
    @Override
    public JPanel getSettingsPanel() {
        return null;
        /*if (settings == null)
            initSettingsPanel();
        return settings;*/
    }
```

I do not have time to look more into it (as in creating a branch, uncomment, and test) but should be rather straightforward (although I guess it might be commented for a reason...).

**Comment by matthiasgeiger** [comment]
:scream:

**Comment by stefan-kolb** [comment]
@oscargus Is this treated in #602 somehow?

**Comment by oscargus** [comment]
Yes, the button is removed from the preference dialog and there's no `PushToApplication` for OpenOffice anymore (only through the sidepane), so I close it now.
