### ISSUE TITLE
Search triggers too soon when entering regex

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5349]
1. Enable regex mode in search.
2. Start typing `F[` 
3. Search triggers and results in regex error:
![grafik](https://user-images.githubusercontent.com/320228/65603202-870ec200-dfa5-11e9-8b24-8fc7f28386f4.png)

Idea would be to only trigger regex search if user stops typing or if focus is left?

**Comment by CaptainDaVinci** [comment]
How do I enable regular expression? The key binding <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>F</kbd> did not open global search settings window. Also, I am not able to find the toggle buttons for regex and case sensitive search.

**Comment by Siedlerchr** [comment]
Hi,
this is another odd thing. You first have to enable autocompletion in the preferences.
Then enter a word and then you can use the toggle buttons.

**Comment by CaptainDaVinci** [comment]
Hello, 
How about instead of waiting for the user to input the text or for the search field to lose focus, we consume the exception caused due to incorrect regex? 
Instead of displaying the exception we can have an incorrect syntax indicator next to the search field?

**Comment by Siedlerchr** [comment]
That is a good idea, display the validation indicator like its done in the preference or other places now

**Comment by koppor** [comment]
Does this ref https://github.com/JabRef/jabref/pull/3871#issuecomment-375055243 somehow?
