### ISSUE TITLE
Scroll to imported entry

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5383]
**Is your suggestion for improvement related to a problem? Please describe.**
After importing/adding a new entry the added entry is not always visible in the main table.

**Describe the solution you'd like**
Always scroll to the (first) imported entry.

**Comment by b0n541** [comment]
I would take that one. Or will it be fixed with #5384?

**Comment by matthiasgeiger** [comment]
Feel free to start with this. The other aspect mentioned in #5384 is complementary - but maybe you can fix this as well.
