### ISSUE TITLE
JABRef Freezes

### ISSUE THREAD

**Issue by 3-1415926535** [JabRef/jabref#539]
JABRef freezes when opening (during splash screen) or after one or two operations (e.g., opening reference, searching for reference) after opened.
 Let me know what information I can provide to help this.

When trying to start from terminal:
-------------------------------------------
~> jabref
log4j:WARN No appenders could be found for logger (org.java.plugin.ObjectFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Found 2 plugin(s):
  - net.sf.jabref.core (jar:file:/usr/share/jabref/JabRef-2.10.jar!/plugins/net.sf.jabref.core/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/usr/share/jabref/JabRef-2.10.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)

The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 117 error_code 2 request_code 138 minor_code 2)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

=============================================
JABRef version: 2.10+ds-4

Java Verison:
-----------------
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

OS:
-----------
Linux 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Hardware:
------------
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Stepping:              9
CPU MHz:               3735.218
CPU max MHz:           3900.0000
CPU min MHz:           1600.0000
BogoMIPS:              6784.22
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
=============================================

**Comment by matthiasgeiger** [comment]
Hi,
thanks for your report. This seems to be a duplicate of #393.

You might try to change the "look-and-feel": Preferences -> Advanced

**Comment by 3-1415926535** [comment]
Yes, that seems to have fixed it for me, too.  Thank you!

The issue for me appears to be the GTK theme (which, of course, is my favorite : / )

The available themes and how to install them are discussed [here](http://sourceforge.net/p/jabref/mailman/message/32703401/).

Note that the [Motif](com.sun.java.swing.plaf.motif.MotifLookAndFeel) theme is slightly problematic since it won't allow you to paste in another option to change it away from that; instead, you have to type in the URL for the other theme.
