### ISSUE TITLE
Installing latest snapshot in a different folder

### ISSUE THREAD

**Issue by tb77phd** [JabRef/jabref#5413]
I'm trying to install the latest snapshot (or whatever it is called) JabRef-5.0.0.msi into a folder I have defined (e.g. c:\tools\jabref), but no matter what folder I define during the installation process, Jabref installs into (default) C:\Program Files\JabRef.

I'm using Windows 10, 64-bit.

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-17----e81d58c51
Windows 10 10.0 amd64 
Java 12.0.2

Cannot confirm this issue.

I managed to install JabRef (using the msi) to "C:\Program Files\JabRef_dev" (which I use to test the current development version of JabRef). In fact, it would be a big problem for me, if it was not possible to change the installation directory, because my working installation of JabRef (version 3.8.2) is found in "C:\Program Files\JabRef".

**Comment by tb77phd** [comment]
I tried again into a different folder and it still got installed into C:\Program Files\JabRef. I wonder if it is because my working installation 4.3.1 is **not** in C:\Program Files\JabRef? I may try later on a different computer to install 4.3.1 into default and then install the 5.0.0 msi into a different folder.

**Comment by stefan-kolb** [comment]
@tb77phd any new findings?

**Comment by tb77phd** [comment]
Sorry, haven't had a chance to test with a different computer. I did, however, install the 5.0.0 again on my work computer and the issue is the same: I specified a folded I wanted it in, but it installed into the default. This could be related to my 4.3.1 not being in default C:\Program Files\JabRef folder.

**Comment by AEgit** [comment]
@tb77phd Could you please specify the exact version that you are using? Is it the latest master snapshot? Go to Help- > JabRef -> Copy Version and paste the respective information here.

**Comment by tb77phd** [comment]
JabRef 5.0-alpha--2019-12-10--778d7a0
Windows 10 10.0 amd64 
Java 13.0.1

**Comment by AEgit** [comment]
JabRef 5.0-alpha--2019-12-11--c3b7ee7
Windows 10 10.0 amd64 
Java 13.0.1

Hmm, still cannot reproduce the problem. I have JabRef 3.8.2 installed at "C:\Program Files\JabRef" and the current dev version at "C:\Program Files\JabRef_dev".

**Comment by tb77phd** [comment]
No problem. As mentioned earlier, probably due to me not having the stable 4.3.1 in default "C:\Program Files\JabRef" and therefore the installation of 5.0.0 automatically goes there no matter what folder is specified.

Not a big deal, I can live with 5.0.0 being in the default folder.
