### ISSUE TITLE
Check serialization order of fields with alias

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5424]
Need to double check, but just had a changelog where `journaltitle` and `date` were moved to the end of the bibtex entry.

**Comment by matthiasgeiger** [comment]
Might be a side effect of my recent changes in https://github.com/JabRef/jabref/pull/5392 ?

**Comment by matthiasgeiger** [comment]
For me it looks like it's working like expected:
Output for `bibtex` mode:
```
@Article{key,
  author       = {Author Name},
  title        = {Title},
  journal      = {journal},
  year         = {2015},
  date         = {2015-10-16},
  journaltitle = {JournalTitle},
}
```

Output for `biblatex` mode:
```
@Article{key,
  author       = {Author Name1},
  title        = {Title},
  journaltitle = {JournalTitle},
  date         = {2019-10-16},
  journal      = {journal},
  year         = {2015},
}
```
But as `journaltitle` is not defined for a "bibtex" entry, it is one of the "optional" field that is placed after the last required field "year". I also quickly cross-checked with a jar from May this year that I still had, and the behavior was the same at that time.

**Comment by tobiasdiez** [comment]
So the required fields are not supposed to be ordered alphabetically? I.e. author > date > journaltitle > title > year?

**Comment by matthiasgeiger** [comment]
Okay... Now I'm a bit confused... 
After checking the code I saw that it should be sorted alphabetically, and therefore I wanted to check again from source and there I now get another output... 

However, using the jar from May the output is as above.

Bibtex:
´´´
@Article{key,
  author       = {Author Name},
  journal      = {journal},
  title        = {Title},
  year         = {2015},
  date         = {2019-10-16},
  journaltitle = {JournalTitle},
  timestamp    = {2019-10-12},
}
´´´
Biblatex:
´´´
@Article{key,
  author       = {Author Name},
  date         = {2019-10-16},
  journaltitle = {JournalTitle},
  title        = {Title},
  journal      = {journal},
  timestamp    = {2019-10-12},
  year         = {2015},
}
´´´

Checking the history I guess the new behavior was introduced with #5148 - but atm I don't have really time to investigate this deeply.

**Comment by koppor** [comment]
Not sure whether we have test cases for that in https://github.com/JabRef/jabref/tree/master/src/test/resources/testbib.

**Comment by tobiasdiez** [comment]
It works as expected in the latest dev version and I added a test to make sure it stays like this: https://github.com/JabRef/jabref/commit/9fd49bcb2560a46c7f319dd59fdd9a58845415ce
