### ISSUE TITLE
Make gradle script compatible with 6.0

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5428]
Currently, gradle reports
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6/userguide/command_line_interface.html#sec:command_line_warnings

As we want to upgrade to Gradle 6 at some point, these deprecated features should be migrated.

**Comment by vpbhargav** [comment]
I would like to work on this. Can you assign it to me please?

**Comment by matthiasgeiger** [comment]
Thanks for your interest! Just go ahead!

**Comment by koppor** [comment]
This is for Gradle 7.0, because we updated to Gradle 6.0 and everything works, right?

**Comment by tobiasdiez** [comment]
It was for Gradle 6.
