### ISSUE TITLE
Make snap output more compact

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5440]
The current output at GitHub actions is:

![grafik](https://user-images.githubusercontent.com/1366654/66697674-2935e600-ecd8-11e9-8231-d799048b5041.png)

Can this output be removed during build @LyzardKing?

Refs #5379

**Comment by LyzardKing** [comment]
The problema Is how GitHub actions generates the logs.
I guess an idea could be to set something like:
snapcraft >/dev/null
To disable all the output.
I can open a branch to test a few ideas.
What do you think?

**Comment by tobiasdiez** [comment]
I take this as a "not easy to do". As the snap logs are really large anyway, I'm so free to close this issue. @LyzardKing if you want to play around with something: https://github.com/JabRef/jabref/issues/5418 would be nice to solve

**Comment by LyzardKing** [comment]
Actually there might be a simple easy fix..
I'll try it (basically setting an env variable in the docker image).
Should I try a PR or a branch?
Regarding the deb issue: I had a look at it, I'm trying to figure how the gradle works with the jpackage debs.
(Same with this, can I try a branch for a fix?)

**Comment by LyzardKing** [comment]
This should be fixed in the docker image.
I set the env variable TERM to dumb
so it should not be interactive with the (snapcraft) progressbars.
We'll see on the next build
