### ISSUE TITLE
Action "Import into current library" is active without any open library

### ISSUE THREAD

**Issue by b0n541** [JabRef/jabref#5447]
JabRef version 5.0.0 (develop) on Ubuntu 18.04

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Start JabRef
2. Choose menu File - Import - Import into current library
3. Try to import some bib entries
4. Alert dialog with NullPointerException is shown

![Screenshot from 2019-10-14 21-57-20](https://user-images.githubusercontent.com/2326303/66779120-bb530f80-eecd-11e9-918b-0e42572e80a2.png)

**Comment by Siedlerchr** [comment]
The import into current library should be disabled if  there is no library open

**Comment by b0n541** [comment]
Yes, I'll try to find a fix for that.

**Comment by tobiasdiez** [comment]
https://github.com/JabRef/jabref/blob/d2ddff574cfdb8d60a09f8f783f6bee92b85c60c/src/main/java/org/jabref/gui/actions/ActionHelper.java#L9-L11
should be helpful

**Comment by b0n541** [comment]
Yes, I already found that one... :-D

**Comment by koppor** [comment]
Refs #4665
