### ISSUE TITLE
Null error while writing XMP metadata

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#5449]
ArchLinux package by j0hannes #5299 
```
JabRef 5.0.0-dev--2019-10-14----d2ddff574
Linux 5.3.6-zen1-1-zen amd64 
Java 12.0.2
```
```console
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11)
OpenJDK 64-Bit Server VM (build 11.0.4+11, mixed mode)
$ archlinux-java status
Available Java environments:
  java-11-openjdk (default)
```
- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

An error with no description:
> Author2000
>   Error while writing '/home/user/Documents/Literature/TPSA.pdf':
>     null
> 
> Finished writing XMP for 0 file (0 skipped, 1 errors).
Happens with different PDFs. 
The event log is empty.

1. Create an entry
2. Add link to a local PDF in the General tab
3. Select this file
4. Tool - Write XMP...
5. A pop-up appears

**Comment by homocomputeris** [comment]
The one from my snippet is https://agenda.infn.it/event/2620/attachments/29206/34301/TPSA.pdf

Basically, it doesn't write to any PDF.
For example, from these links I downloaded jabref-authors.bib and one PDF, and, say, I want to write the 1st entry metadata to the PDF:
```
GarridoKallstromKummEtAl2016
  Error while writing '/home/user/Documents/Literature/thesis-example.pdf':
    null

Finished writing XMP for 0 file (0 skipped, 1 errors).
```

**Comment by homocomputeris** [comment]
I tried it today with the latest snapshot on Windows 10: the same `null` error is raised

**Comment by Siedlerchr** [comment]
Thanks to @tobiasdiez  this issue should be fixed now

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
