### ISSUE TITLE
Entry editor: Keep it open as default

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5460]
JabRef 5.0.0-dev--2019-10-17----e81d58c51
Windows 10 10.0 amd64 
Java 12.0.2

At the moment, it is not possible to have the entry editor open all the time. This is a problem, since the new changes to the entry preview make it part of the entry editor:
https://github.com/JabRef/jabref/issues/5244

This makes it difficult to quickly cycle through all entries (see also https://github.com/JabRef/jabref/issues/5244#issuecomment-525290454). It should be possible to have the entry editor open all the time.

**Comment by tobiasdiez** [comment]
What do you mean by "always open"? If I open the entry editor, it usually stays opens until I close it again. And you can click on a new entry to edit it (without that the editor closes).

**Comment by AEgit** [comment]
Yes, but I would like to see the old JabRef behaviour, where after opening JabRef the entry preview was immediately visible. At the moment, this is only possible after clicking onto the entry (note, that Strg+E does not work).
I think it is more intuitive to always have the entry preview open, instead of just the main table. Since the entry preview is now part of the entry editor, the entry editor should always be open. This behaviour mirrors JabRef 3.8.2 (and it is the same in Mendeley).

**Comment by tobiasdiez** [comment]
Thanks to @CaptainDaVinci tihs is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-21----0f0dce621
Windows 10 10.0 amd64 
Java 12.0.2

Amazing, that was quick! I can confirm, that this issue has been fixed in the current dev version.
