### ISSUE TITLE
Entry editor: Formatting of entry preview is lost after performing search

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5462]
JabRef 5.0.0-dev--2019-10-17----e81d58c51
Windows 10 10.0 amd64 
Java 12.0.2

If a search is performed, the formatting of the entry preview is lost.

Entry preview before performing search:

![Entry_preview_no_search](https://user-images.githubusercontent.com/12767489/66990108-7db4d900-f0bd-11e9-9937-b04b89335490.png)

Entry preview after performing search:

![Entry_preview_with_search](https://user-images.githubusercontent.com/12767489/66990115-81e0f680-f0bd-11e9-91ac-477995d9a702.png)

**Comment by Siedlerchr** [comment]
This is a duplicate and has to do with the search highlight function.
