### ISSUE TITLE
Remove background command line window

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5474]
Currently, a console window is shown in the background. Reason is the `command-line` argument to `jpackage` which enables command line input. Thus, currently we have to life with the background console window. 

Java bug report: https://bugs.openjdk.java.net/browse/JDK-8234469

**Comment by koppor** [comment]
Current (visible) state: The JDK guys ask for feedback:

> I cannot reproduce with simple example, and have emailed submitter for further instructions. 

https://bugs.openjdk.java.net/browse/JDK-8234469?focusedCommentId=14301796&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14301796

**Comment by koppor** [comment]
The upstream bug was closed. We have to write a MWE, don't we? @tobiasdiez

**Comment by koppor** [comment]
Is https://github.com/tobiasdiez/javatestbed the MWE? (item 2 in README.md?)
