### ISSUE TITLE
ERROR StatusLogger Log4j2 could not find a logging implementation. 

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5475]
JabRef 5.0.0-dev--2019-10-18----bc26c3ac5
Windows 7 6.1 amd64 
Java 12.0.2

- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. When opening jabref a console starts with this error message
     ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to   the classpath. Using SimpleLogger to log to the console...
2. Then Jabref opens still. I do not know what the effect of this error will be. 
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-18----bc26c3ac5
Windows 10 10.0 amd64 
Java 12.0.2

I can confirm this "issue". As mentioned by @bernhard-kleine I do not know, whether the error is an actual problem, since JabRef starts flawlessly.

As explained by @tobiasdiez the console starts due to a limitation of the software that is used to created the installer: https://github.com/JabRef/jabref/issues/5468#issuecomment-543356121
There is already a ticket open to remove the console window:
https://github.com/JabRef/jabref/issues/5474

**Comment by Siedlerchr** [comment]
We also have a ticket open at the log4j guys.
It should not be a problem for n the user as JabRef works with it.

**Comment by bernhard-kleine** [comment]
the versions from 2019-08-25 didnot show the console. What has changed inbetween?

**Comment by AEgit** [comment]
@bernhard-kleine : See here
https://github.com/JabRef/jabref/issues/5468#issuecomment-543356121

and here:

https://github.com/JabRef/jabref/issues/5475#issuecomment-543553962

**Comment by koppor** [comment]
The issue with the console is described here https://github.com/JabRef/jabref/issues/5474. (Right?)

**Comment by bernhard-kleine** [comment]
Yes

Am 2. Februar 2020 15:03:42 MEZ schrieb Oliver Kopp <notifications@github.com>:
>The issue with the console is described here
>https://github.com/JabRef/jabref/issues/5474. (Right?)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/JabRef/jabref/issues/5475#issuecomment-581138638

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Siedlerchr** [comment]
Refs https://issues.apache.org/jira/browse/LOG4J2-2690
Refs also #5226

**Comment by digdig** [comment]
> 
> 
> the version from 2019-08-25 didnot show the console. What has changed inbetween?

neither does 2019-04-19 or 2010-09-16 has the black console problem

**Comment by AEgit** [comment]
@digdig:
See the comments in this thread (and elsewhere) - the reason has already been explained.
https://github.com/JabRef/jabref/issues/5475#issuecomment-543553962
https://github.com/JabRef/jabref/issues/5468#issuecomment-543356121

**Comment by digdig** [comment]
@AEgit Does the explained reason say something about why previous versions are OK and no consoles?

**Comment by Siedlerchr** [comment]
We switched to a new installer, we now use the native Java packager to create custom versions for n each OS

**Comment by bernhard-kleine** [comment]
Which version is supposed the new version, since the snapshot is still from 2020-06-02?

**Comment by AEgit** [comment]
@bernhard-kleine Which new version are you talking about? Is this relevant to this issue?

**Comment by bernhard-kleine** [comment]
I would like to know whether the snapshot from 2020-06-02 has already the new installer or not. Since the statusLogger error is the only thing which is not ok as far as I see, I donot want to download every new snapshot. Maybe you can understand.

**Comment by AEgit** [comment]
You opened the issue yourself (https://github.com/JabRef/jabref/issues/5475#issue-508881928) - the new installer has been part of the JabRef dev version since (at least) JabRef 5.0.0-dev--2019-10-18----bc26c3ac5

There is no other current dev version out there, without this "new" installer (at least I am not aware of it).

Do I misunderstand you?

**Comment by bernhard-kleine** [comment]
Then I have Christoph misinterpreted. I seemed to me that as of today there was a new installer. Sorry for the noise.

**Comment by Siedlerchr** [comment]
I think somewhere directly after the alpha release we switched to the new installer.
And the bug is reported to the external libraries/Java components

**Comment by AEgit** [comment]
@bernhard-kleine Ok, no worries.

**Comment by tobiasdiez** [comment]
The problem is that Log4j2 is simply not compatible with Java 9. I've created a very simple Java 9 application which shows this problem: https://github.com/tobiasdiez/javatestbed.
Currently, I'm in contact with the log4j devs to solve this problem. Luckily the consequences for JabRef are not that negative - the only functionality that does not work because of this issue is the "error console" and errors are only written to the command line.

**Comment by jorgman1** [comment]
I do not habe the console log anymore in the latest version:

JabRef 5.0-beta.457--2020-02-22--d38f813
Windows 7 6.1 amd64 
Java 13.0.2

**Comment by bernhard-kleine** [comment]
JabRef 5.0-beta.458--2020-02-23--b2ab177
Windows 10 10.0 amd64 
Java 13.0.2

I can confirm that there is any console any further. Thanks a lot.

**Comment by tobiasdiez** [comment]
Sadly, the bug is still there - it's only not displayed anymore because the console window is hidden. For the same reason, the Error console is currently not working (nothing is shown there).

**Comment by bernhard-kleine** [comment]
@tobiasdiez ,  @Siedlerchr Is this issue with the Log4j2 resolved, then this should be closed, otherwise it should remain open, even its last activity was 6 months ago.

**Comment by AEgit** [comment]
I think the issue is still present in:

JabRef 5.2--2020-11-07--df80c13
Linux 5.4.0-53-generic amd64 
Java 15.0.1

**Comment by Siedlerchr** [comment]
Yep, issue is still here, apache log4j team did not fix it yet. Were thinking of switching to another log framework maybe.

**Comment by AEgit** [comment]
JabRef 5.3--2021-06-08--9d1c448
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8

I think the issue is still present in the current dev version.

**Comment by koppor** [comment]
> Yep, issue is still here, apache log4j team did not fix it yet. Were thinking of switching to another log framework maybe.

In 2021, I am fan of [tinylog](https://tinylog.org/v2/) in contrast to 2017, where I tried to convince people to use jcabi: https://github.com/JabRef/jabref/pull/3015
