### ISSUE TITLE
UI: Group pane is very small when having LO connector opened

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5479]
![grafik](https://user-images.githubusercontent.com/320228/67111026-5dc40900-f1d4-11e9-8ca9-6bda4b113c2e.png)

OO/LO panel should be scrollable or a bit smaller

**Comment by matthiasgeiger** [comment]
As the buttons do not really need that much space to display the label text maybe an easy solution would be to reduce their size and put more buttons in one row (floating layout depending on the width of the panel)

**Comment by ddunig2** [comment]
May I take take this issue?

**Comment by Siedlerchr** [comment]
@ddunig2  Sure, go ahead!  Read the [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and for questions ask here or in our gitter chat

**Comment by ddunig2** [comment]
@Siedlerchr when you say Group pane is very small which group pane are you referring to?

**Comment by Siedlerchr** [comment]
See the Screenshot, the groups panel at the left side. The open office connector dialog takes 
 half of the space from the groups

**Comment by ddunig2** [comment]
@Siedlerchr Just to confirm, the blue box is taking too much vertical space?
![LOC](https://user-images.githubusercontent.com/36016544/71193600-5b277380-2258-11ea-9efc-3b7332b52afb.png)

**Comment by Siedlerchr** [comment]
Yes. Exactl.  Create a library with some groups (toggle group view) and if you then toggle the Libre office connection you see. 
how much space it consumes.
Maybe @aegit could provide a Screenshot showing the issue with a lot of groups.

**Comment by AEgit** [comment]
JabRef 5.0-beta.19--2019-12-20--9b0dd5d
Windows 10 10.0 amd64 
Java 13.0.1

Here an example with a database with several thousand groups (though you should already notice the issue with only a few groups):

![Untitled](https://user-images.githubusercontent.com/12767489/71293947-f0b52700-236e-11ea-96bf-a82033bdcfbd.png)

**Comment by ddunig2** [comment]
![LO OO1](https://user-images.githubusercontent.com/36016544/71302357-8a350680-2378-11ea-80f6-eec0b89dacc7.png)

A fix that I thought of was logical was to put the buttons in groups of threes, let me know if this seems piratical.

**Comment by AEgit** [comment]
Are two rows not feasible?

**Comment by ddunig2** [comment]
@AEgit There are nine items, I figured rows of three would be more logical but here is a look with two rows. What do you think?
![OO](https://user-images.githubusercontent.com/36016544/71312194-06b9fa80-23f6-11ea-9ebc-f0791baa08a6.JPG)

**Comment by Siedlerchr** [comment]
Three rows look better. We should also think about if we move one or two options to the context menu

**Comment by tobiasdiez** [comment]
What are all these buttons are actually doing? They are also not described at https://docs.jabref.org/import-export/other-integrations/openofficeintegration. Things like "Settings" are natural candidates that should be moved to the menu (or even better to the preferences). But that's probably somewhat going beyond the scope of this issue.

**Comment by AEgit** [comment]
Three rows might look slightly (?) better (not even sure about that), but two rows take up less vertical space. That would probably be more important - but I have no strong opinion on this, since I do not use this feature anyway.

**Comment by ddunig2** [comment]
I made a pull request but not sure if I did it correctly. Please let me know if I need to redo it.

**Comment by tobiasdiez** [comment]
Thanks to @ddunig2 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
JabRef 5.0-beta.407--2020-02-06--9407bef
Windows 10 10.0 amd64 
Java 13.0.2

There are now threes rows for the OO/LO connector. As far as I can tell, this fixes this issue. Cheers!
