### ISSUE TITLE
Crossref API parameter query.title deprecated

### ISSUE THREAD

**Issue by dheckl** [JabRef/jabref#5485]
JabRef version 5.0-alpha on Mac OS X 10.15 x86_64 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When trying to lookup a DOI for an entry, I get the error "An I/O exception occurred". The answer from api.crossref.org says: "Parameter query.title has been deprecated. Please use query.bibliographic instead. See https://status.crossref.org/incidents/4y45gj63jsp4"

1. Open entry without DOI reference
2. Lookup DOI

**Comment by Siedlerchr** [comment]
Thanks to @CaptainDaVinci  this issue is now fixed! 

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by dheckl** [comment]
Fix looks good. Thanks to all for the quick fix.
