### ISSUE TITLE
shortcut for copying a url link in the name of bibtexkey

### ISSUE THREAD

**Issue by jhshinn** [JabRef/jabref#549]
This is a sort of feature request.
It would great if JabRef provides a shortcut key for copying the url in the name of bibtexkey.
During discussion with other people in email, I've encountered many occasions that I should direct them to some articles.
I think the url link is useful for this purpose, especially in the name of bibtexkey. e.g. [Zaritsky(1994)AJ_108_1619](http://adsabs.harvard.edu/abs/1994AJ....108.1619Z)

**Comment by simonharrer** [comment]
> copying the url in the name of bibtexkey.

What do you mean by that? Can you please elaborate?

**Comment by koppor** [comment]
I think, when issuing the new "copy key and link" command, a RTF/HTML should be copied.

    <a href="http://adsabs.harvard.edu/abs/1994AJ....108.1619Z">Zaritsky(1994)AJ_108_1619</a>

The content of `href` should be taken from the `URL` field, the content of the link text is the bibtex key.

**Comment by simonharrer** [comment]
Ah ok. Should be straight forward then.

**Comment by jhshinn** [comment]
@simonharrer I'm sorry not to clarify it enough. It is as @koppor described. Thanks much, @koppor

**Comment by boceckts** [comment]
I will close this as everything seems to be done.

**Comment by tobiasdiez** [comment]
This is now implemented in the latest development version. Note that not every applications support HTML content in the clipboard and thus paste does not always work (e.g. the link appears in Word but not in Notepad). Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by jhshinn** [comment]
Thanks much for your excellent job! I've found that the "copy bibtex key and link" function of the recent build works properly on Windows 10, but not on Ubuntu 16.04 as before. I could not paste anything on Ubuntu. I've checked the function in the new message window of Gmail.
