### ISSUE TITLE
ZIP "ungültig"

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5504]
I tried to download the JabRef windows portabel zip file from the developers snapshots download section today. I tried several times.

But Windows 10 told me the zip file is "ungültig" (corrupt).

Open the same file with 7zip works fine.

So something is unusual with your zipper that Windows can not open it. Should be fixed asp because most of the Windows users using the windows inbuild zipper.

**Comment by AEgit** [comment]
I can confirm this issue.

**Comment by AEgit** [comment]
This issue appears to be fixed in the current dev version.
