### ISSUE TITLE
Cannot log in via github to discourse

### ISSUE THREAD

**Issue by reox** [JabRef/jabref#5506]
I know this is probably not the right place to ask this question, but I hope it reaches someone who might can look into this:
I try to log in to discourse.jabref.org via github oauth but all I get is this error message:
```
Sorry, there was an error authorizing your account. Please try again.
```

In the github settings, I can see that I authorized jabref's discourse to access my e-mail.
I even tried with Google Chrome and Firefox, but I get the same error message all the time.

I also revoked the access in github's settings, but this does not help either.

If I search for this issue, I can find some information regarding broken discourse url redirects. Maybe the discourse has some problem?

**Comment by Siedlerchr** [comment]
I have the same issue since a while. @koppor

**Comment by koppor** [comment]
Please try again. I registred the app for GitHub, Facebook, and Twitter with my personal accounts.

**Comment by reox** [comment]
yes, it works now!
