### ISSUE TITLE
Make it easier to import single entries

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5508]
**Is your suggestion for improvement related to a problem? Please describe.**
If you import a single entry (e.g. a bib file containing only one entry), then the import dialog opens and one needs to select the entry by hand, before one can click "Import".

**Describe the solution you'd like**
Preselect the entry, so that one can directly click "Import".

**Comment by P4trice** [comment]
PR #5513 sent. 

If you have any feedback or issues with it, please tell me.

**Comment by tobiasdiez** [comment]
Thanks to @P4trice this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
