### ISSUE TITLE
Improve message when changing the theme

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5509]
After changing the theme in the preferences (Preferences > Appearance), a message is displayed à la "Changed theme to: xyz", where "xyz" is "Base.css" or "Dark.css" depending on the new theme. These should be replaced by better names such as "Light theme" or "Dark theme".

Code implementation: Introduce enum for themes with the properties "display name" (localized), "name" (for storage in the preferences) and "css file name".

**Comment by jairus-crabb** [comment]
Hello, I am a new GitHub user and would like to tackle this issue!

**Comment by namanvats** [comment]
I am working on it.

**Comment by carlg0ransson** [comment]
Hey, I just created a pull request for this issue #5584

**Comment by tobiasdiez** [comment]
Thanks to @carlg0ransson this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
