### ISSUE TITLE
Reordering Groups does not work after previous drag & drop

### ISSUE THREAD

**Issue by mgroth0** [JabRef/jabref#5510]
Can we reorder groups? I don't mean the automatic alphabetized "sort all subgroups (recursively)" which I can click in the context menu. I mean can I manually choose the order of my groups? It seems that drag and drop only works if I'm adding a group as a subgroup into another group.

**Comment by Siedlerchr** [comment]
Sure you can drag and drop the groups in any order. You can move a group onto another group to make it a subgroup or you move in between two groups to put it there 
If you move a subgroup to the all entries group, it should become another top level group.
Also moving subgroups works by moving them onto the parent group

**Comment by mgroth0** [comment]
Thank you! Nice workaround but for larger lists of groups is unrealistic. I'd suggest a new feature where the drag listener detects if the cursor is near the top or bottom of the receiving cell, and if so tries to insert the dragged group in between two cells.

**Comment by AEgit** [comment]
Similar to:
https://github.com/JabRef/jabref/issues/4869#issuecomment-480845941 (see also discussion there)

**Comment by mgroth0** [comment]
Ok I had a feeling it might already be implemented. Actually, this did not work for me when I made this post. I wasn't sure if it was a bug or a missing feature. But I just pulled the latest commit and rebuilt it, and now drag and drop reordering is working as expected.

**Comment by mgroth0** [comment]
Actually, this issue started to happen again. And I figured out how to reproduce it: 

1. Start up JabRef normally. Drag and drop reordering of groups should work fine.
2. Drag and drop an article into a group.
3. Try to drag and drop reorder a group again. It does not work.

Since articles can't be drag and dropped in between groups, my guess is that some flag  indicating that the dragged item cannot be placed in between groups does not get reset after an article is drag and dropped.

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-10-25----681d6aa6f
Windows 10 10.0 amd64 
Java 12.0.2

Can confirm for the current dev version.
After dragging an article to a group, it is no longer possible to insert a group between two other groups using drag'n'drop. It is possible, however, to assign a group as a new subgroup of another group using drag'n'drop.

**Comment by mgroth0** [comment]
Thanks, I think I fixed it.

I'm having issues with git so I can't pull request. Please add 
```java
if (!groupsToMove.isEmpty()) {
	localDragboard.clearAll();
}
```
or something similar to src/main/java/org/jabref/gui/groups/GroupTreeView.java line 215

I don't understand why this wasn't here before so perhaps someone could check that my fix isn't causing any new problems.

**Comment by AEgit** [comment]
@tobiasdiez : Have you seen the issue and fix reported by @mgroth0 ? I reckon as long as the fix has not been implemented, this issue needs to be re-opened.

**Comment by Siedlerchr** [comment]
Thanks to the solution from @mgroth0  this issue should be fixed now in the latest master.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
JabRef 5.0-beta.466--2020-02-24--4eefcc6
Windows 10 10.0 amd64 
Java 13.0.2

I am afraid, with the new version the performance is now so bad for my large database (>20,000 entries; several thousand static groups), that I cannot test features any more. JabRef behaves as if crashed (status: "Not responding" in task manager) most of the time and the CPU usage is constantly around 80% on a hexacore. When trying to assign a group as a subgroup of another, JabRef will appear as it crashed for 10 to 20 sec, before performing the action). I will see, whether I can get a smaller database, where I can still at least test features, but at the moment this performance is a complete showstopper. Could you please test this feature also with a large database? Do you manage to use JabRef when using a large database?
Maybe its introduction has caused these issues - the performance of the current JabRef version has already been bad before ((see also here: https://github.com/JabRef/jabref/issues/5071 and here: https://github.com/JabRef/jabref/issues/5735), but not its abysmal.

**Comment by calixtus** [comment]
This code part should only be invoked, when a drag'n'drop of a group item happens. I don't believe this is connected to the performance issue, but I will try to test it.
