### ISSUE TITLE
Dark Theme: Wrong font color for textfield text in merge window 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5516]
Latest master.

1, Merge two entries

![grafik](https://user-images.githubusercontent.com/320228/67601563-f9292100-f774-11e9-9992-c08fc9b8a805.png)

**Comment by martinacat** [comment]
Hello! Is the desired colour for the field `-fx-light-text-color (#9aa3af)`?

**Comment by martinacat** [comment]
Like this? 

<img width="843" alt="Screenshot 2019-10-26 at 10 36 00" src="https://user-images.githubusercontent.com/17515408/67617589-72a82a00-f7dc-11e9-9a36-c7d286e8c857.png">

**Comment by tobiasdiez** [comment]
Thanks to @martinacat this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by Siedlerchr** [comment]
Thanks a lot for the fix! Really good looking now!

**Comment by martinacat** [comment]
No worries! 👍 ✨
