### ISSUE TITLE
Grouping of entry types

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#552]
Under `BibTeX` -> `New entry... >` the list is not structured according to the `BibTeX` -> `New entry` popup. We should reflect the structure in the popup also in this list as it is done when changing the entry type via the entry editor.

**Comment by koppor** [comment]
`New entry..." should be removed completely. The shortcuts should be shown at "Select entry type".

**Comment by simonharrer** [comment]
Hm, may be more effort then, as currently all shortcuts are registered through menu items.

**Comment by simonharrer** [comment]
No really important.
