### ISSUE TITLE
Fix typos in external-libraries.txt file 

### ISSUE THREAD

**Issue by parammittal16** [JabRef/jabref#5523]
JabRef version  on 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Grammatical typos in the external-libraries.txt file 

1. Fix typos

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by koppor** [comment]
Thank you for reporting. In this project, it is not mandatory to open an issue of a problem one fixes directly afterwards.

Did you check our https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md - we do not require to open an issue.

Another #hacktoberfest learning: Read `CONTRIBUTING.md` of a repository. 🎉
