### ISSUE TITLE
[Q]: Fulltext download removed?

### ISSUE THREAD

**Issue by Krzmbrzl** [JabRef/jabref#5527]
I found this question on SE: https://tex.stackexchange.com/questions/310774/downloading-the-full-texts-for-the-whole-database-in-jabref-3-3 and it references #1323. The issue is closed and from it I assumed that this functionality has been implemented somewhere in JabRef 3.x. However I can't seem to find it in the 5.x series. Has this feature been removed in the meantime or is it just to be found somewhere else (no longer under Quality -> ...) :thinking:

**Comment by Krzmbrzl** [comment]
Okay I found the option I was searching for. In the Entry-editor under `General` in the `File` field one can right-click on a URL-entry and chose to download the file.

**Comment by Siedlerchr** [comment]
In the menu there is an option lookup fultext as well

**Comment by Krzmbrzl** [comment]
That options doesn't seem to download anything though. It finds the URLs (if any) and stores them as linked "files" but it won't doenload any PDFs
