### ISSUE TITLE
importBibtex imports to an untitled library in a new instance

### ISSUE THREAD

**Issue by LyzardKing** [JabRef/jabref#5537]
As the title suggests, with the recent jabref updates the --importBibtex option opens a new instance of JabRef, and automatically adds the reference to a new "untitled" library.
Last time I used this functionality it asked confirmation and added to the running Jabref and lib.

**Comment by Siedlerchr** [comment]
A quick look in the code reveals that it checks if there is a currentBasePanel active.
I guess the base panel is not yet there due to the lazy loading stuff

**Comment by LyzardKing** [comment]
And that should work for the untitled library, but why is it launching another instance in the first place?
Should the cli part not look for an open instance in the first place?

**Comment by Siedlerchr** [comment]
The point for debugging would be: https://github.com/JabRef/jabref/blob/f14b12b9d863af5079f194eba4590bd8785026de/src/main/java/org/jabref/cli/ArgumentProcessor.java#L87-L98

**Comment by LyzardKing** [comment]
This is still an issue in the last builds...
I'm not sure how to debug this.
Is the open instance of jabref be set by line 92 (`result.setToOpenTab();`)?

**Comment by tobiasdiez** [comment]
Yes, I guess that libraries with `setToOpenTab` are opened as new tabs. It might be sufficient to simply remove that line...

(You can debug this by adding command line arguments to the start configuration in IntelliJ.)

**Comment by LyzardKing** [comment]
Removing that line makes no difference..
I wonder why the open instance of jabref is not being recognized any more..

**Comment by Siedlerchr** [comment]
Have you checked that it's enabled in the preferences? e.g. allow only a single instance of jabref?

**Comment by LyzardKing** [comment]
@Siedlerchr Do you mean the `remote operation` option in `advanced`?
It's checked, but on linux it never made a difference.
(I noticed I forgot to add the os to the original post..)

**Comment by LyzardKing** [comment]
I get the same issue if I --importToOpen file.bib
It always opens a new instance of JabRef..

**Comment by LyzardKing** [comment]
This issue apparently only applies to the deb install.
The rpm works properly..

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by LyzardKing** [comment]
I tried the latest build from master and it behaves the same, opening a new blank window.
This time it doesn't add the reference to the new blank window, but neither to the original window..
So I'm left with the original unchanged bib window, and a blank one, with no tab open.

**Comment by tobiasdiez** [comment]
Do you start with having an instance of JabRef open?

**Comment by LyzardKing** [comment]
Yes, i have the open instance with my bibliography file active

**Comment by tobiasdiez** [comment]
ok, than this is another bug. What I fixed was that starting a new instance with the cmd option works as expected.

**Comment by LyzardKing** [comment]
So with this fix it should work if I don't have an instance open already?
