### ISSUE TITLE
Keyboard shortcuts do not work anymore

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5540]
- Expected: I press <kbd>Alt</kbd>+<kbd>F</kbd>, then the file menu opens
- Expected: I press and hold <kbd>Alt</kbd>, then all menu shortcuts are shown

Doesn't JavaFX support keyboard shortcuts for menus anymore?

**Comment by tobiasdiez** [comment]
This is supported but you need to tell javafx what to underline, e.g. `setText("_File")`. Thus, to make this work all localizations have to be reworked to include mnemnonics. See also https://medium.com/@zoha131/handling-keyboard-shortcuts-in-javafx-2972ba950a48

**Comment by koppor** [comment]
We had these translations at JabRef 3.x. Have to search why we dropped them. There probably is the PR (where we documented it; I bet, we put it as issue for future-Olly, who found it now), but not an ADR.
