### ISSUE TITLE
Link file (without copying) doesn't work

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5546]
JabRef 5.0.0-dev--2019-10-29----3b6c355ae
Linux 5.0.0-32-generic amd64 
Java 12.0.2

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. open Preferences/Entry Editor
2. set Default drag & drop action to "Link file (without copying)"
3. The file nevertheless is renamed using the bibtex key.

**Comment by tobiasdiez** [comment]
After a long discussion in the last dev call, we have decided to remove the preference option that controls the default drag and drop action (see #5668). You can use the modifier keys like `Ctrl` or `Alt` to change the drop behavior.
