### ISSUE TITLE
cannot switch to biblatex mode 

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5550]
JabRef 5.0.0-dev--2019-10-31----ac7875a96
Linux 5.0.0-32-generic amd64 
Java 12.0.2

This used to be a problem once before, #420 

5  dev apparently can't switch from bibtex to biblatex library format.  I would expect to find this under "Library/Library Properties" although it used to be under "File/Properties" in the past.

**Comment by Ka0o0** [comment]
Hi,
just as clarification: should this be like a switch in the library properties or shall this be implemented as in Jabref4 where it was an action which needed to be triggered from the main menu?

**Comment by Siedlerchr** [comment]
I think it's sufficient to have a switch in the library properties as this is an action which is probably not what most users will do on a regular basis.
In addtion the File menu there is already an option to create a new library either in bibtex or biblatex.

**Comment by Ka0o0** [comment]
I considered adding it into the library properties panel but there is a button which label changes depending on the current library type. To keep things simple, I added another menu item like it used to be in Jabref 4.x for now in PR #5565. 

Maybe we can change this for a later 5.x release.

**Comment by tobiasdiez** [comment]
Thanks to @Ka0o0 this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by wujastyk** [comment]
Yes, fixed.  Thanks.
