### ISSUE TITLE
Custom Journal Abbreviations Lists not working

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#5552]
Dear Devs,

JabRef 5.0.0-dev--2019-10-31----ac7875a96
Linux 5.2.0-0.bpo.3-amd64 amd64 -- Debian 10 Buster
Java 12.0.2

1. Add a list of abbreviations
2. txt files are not seen
3. I converted my list in csv
4. Import csv file
5. JabRef don't see any abbreviation and abbreviations don't work

My list is this, but I use a file in my machine: [https://github.com/JabRef/abbrv.jabref.org/blob/master/journals/journal_abbreviations_annee-philologique.txt](https://github.com/JabRef/abbrv.jabref.org/blob/master/journals/journal_abbreviations_annee-philologique.txt)

Best wishes,
Domenico

P. S.: I proposed a new italian translation for the corresponding item in the menu (#5553)

**Comment by Siedlerchr** [comment]
@davidemdot could you pleasettake a look?

**Comment by davidemdot** [comment]
@Doc73 Please could you try with this file?

https://github.com/JabRef/abbrv.jabref.org/blob/csv/journals/journal_abbreviations_annee-philologique.csv

We should merge `csv` branch with master in the `abbrv.jabref.org` repository. I will send a PR.

**Comment by Doc73** [comment]
@davidemdot 
Yes, it works!
As I see, the syntax has changed

**Comment by Doc73** [comment]
@davidemdot 
EDIT: Jabref seems not seeing lots of the items in database. For example, SCO (= Studi Classici e Orientali) doesn't appear

**Comment by davidemdot** [comment]
@Doc73 Thanks, I have just detected an error in the converted file. It is already solved. Please [try again](https://github.com/JabRef/abbrv.jabref.org/blob/csv/journals/journal_abbreviations_annee-philologique.csv).

**Comment by Doc73** [comment]
@davidemdot 
Yes, now it works, but I found two missing items. I can add them, if you want

**Comment by davidemdot** [comment]
@Doc73 Good! Those items were not in [the TXT file](https://github.com/JabRef/abbrv.jabref.org/blob/master/journals/journal_abbreviations_annee-philologique.txt).

**Comment by Doc73** [comment]
@davidemdot Yes, they were in my personal file :-D
