### ISSUE TITLE
Quality check on the journaltitle field not working proberly

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5562]
JabRef 5.0.0-dev--2019-11-03----921f44283
Windows 7 6.1 amd64 
Java 12.0.2

- [ +] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. type e.g. European Journal of Biochemistry into the journaltitle field
2. by the button to the right of that field change the text to the abbreviated Journaltitle.
3. The correct Eur. J. Biochem. gets the "error" orange triangle.
4. If you press the button again the Eur J Biochem shows which has also the orange triangle.

As clicking the triangle does not show any message at all, I wonder why the triangle and whether the meaning of it is totally superfluous.

![grafik](https://user-images.githubusercontent.com/9216487/68086395-d7eac380-fe4b-11e9-97a3-c256860ac501.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by jorgman1** [comment]
Hovering over the triangle shows: "abbreviation detected". Which is the same message that one gets in the integrity check.

I suppose it is better practice to have the complete journal name in the database and abbreviate it uppon using it. That way, the database can be transfered to someone without abbreviation list.

**Comment by Hollyqqqqq** [comment]
Hi, I was going to try fixing this bug. But I found it a little comfused.

**Comment by Hollyqqqqq** [comment]
Hi, I was going to try fixing this bug. But I found it a little comfused.

I think maybe it is not a bug. The orange triangle is not "error" but "warning". I think it is reasonable to have this "warning triangle" if this message occurs when running "Check integrity". In other words, if this "warning triangle" shouldn't occur, then "Check integrity" shouldn't occur this message, either.
![image](https://user-images.githubusercontent.com/55199983/80990947-d84f3000-8e69-11ea-9ce7-bc86426fe936.png)
![image](https://user-images.githubusercontent.com/55199983/80990987-e9983c80-8e69-11ea-8142-15edcbbcac8f.png)
Does this issue mean that, in expected result, "abbreviation detected" message as well as the "warning triangle" shouldn't occur? Or just "warning triangle" shouldn't occur? Or maybe it is not a bug as I mentioned above?

If there is any misunderstanding, please point it out. Thanks!
