### ISSUE TITLE
BibtexImporter does not handle header information

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#558]
JabRef writes file encoding information in the header. This is not covered by the BibtexImporter as revealed by https://github.com/JabRef/jabref/pull/515#issuecomment-164766590.

The open method in `OpenDatabaseAction` should be moved to somewhere else. Maybe `OpenDatabaseAction` should use the BibtexImporter?

**Comment by koppor** [comment]
This seems to be invalid as the BibtexImporter seems only to be used for "--importToOpen".

**Comment by stefan-kolb** [comment]
So can we close this?
