### ISSUE TITLE
Problem with current installer: Installation path can no longer be specified

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5580]
JabRef 5.0.0-dev--2019-11-09----42053a819
Windows 10 10.0 amd64 
Java 12.0.2

The current developer version of JabRef apparently does not allow any more to specify the installation path. I realised this because I always had two installations of JabRef.

1) The one I use for actual work (version 3.8.2)
2) The second I use to test new features/stability/bugs/etc. (version 5.0.0-dev)

The first one was installed under `C:\Program Files\JabRef`, the second one under `C:\Program Files\JabRef_dev`. Previously this worked flawlessly - but now apparently it is no longer possible to specify the installation path. If I install a new developer version of JabRef it will just replace my working version 3.8.2 since I cannot specify the installation folder (I reckon it defaults then to this folder).

This is very inconvenient - every time I install the developer version of JabRef now, it will replace my working version. To get that one back, I have to reinstall version 3.8.2 (which obviously also means, that the developer version is then not available anymore). I have not tested what happens if I change the installation directory of 3.8.2 to `JabRef_dev` instead of `JabRef`, but this is would be a very bad workaround anyway, so should not be pursued.

Please make it possible again, to have two separate installations of JabRef. Otherwise I cannot test the new developer version any more.

**Comment by tobiasdiez** [comment]
Problem is known and due to a bug in jpackage. Hopefully, the next jpackage update resolves it.
https://github.com/JabRef/jabref/blob/42053a819183c587adf5da39c9791e765edca2a7/build.gradle#L585-L586

**Comment by AEgit** [comment]
Cheers, ok, then let's hope they fix this quickly - as long as they don't fix it, I cannot test any developer versions of JabRef any more.

**Comment by Siedlerchr** [comment]
@AEgit  You can also use the windows portable verisons as well. Just unzip it to a dir.

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/pull/5572 and https://github.com/JabRef/jabref/pull/5570 and https://github.com/JabRef/jabref/pull/5559.

**Comment by AEgit** [comment]
@Siedlerchr Thanks for the heads up. Hmmm, at the moment I will wait until this issue is solved. Due to the problems with the installer, I cannot even uninstall the last dev version I had installed and I would like to avoid cluttering my system with different dev versions, where I might loose track of them. If it takes too long, though, I will have to consider your suggestion. Thanks again!

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
JabRef 5.0.0-dev--2019-11-17----151a216a2
Windows 10 10.0 amd64 
Java 13.0.1

Can confirm that his has been fixed in the current dev version.
