### ISSUE TITLE
BibTeX source should not start with two empty lines

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#559]
Due to #391, the "BibTeX source" contains two empty lines. This is explainable when discussing the implementation, but not understandable why JabRef breaks with the existing display of source and why users have to see two empty lines for each entry.

The source in the "BibTeX source tab" should contain the content from `@` until `}`.

Current state:

![grabbed_20151221-181005](https://cloud.githubusercontent.com/assets/1366654/11936426/13d0b0f0-a80e-11e5-8719-7d53fe3e71f5.png)

Wanted display:

![grabbed_20151221-181110](https://cloud.githubusercontent.com/assets/1366654/11936446/381effd4-a80e-11e5-9ac6-649f4bff9a5e.png)

The only enhancement I would agree if **comments** in front of the entry would be stored. Currently, JabRef does not support comments.

![grabbed_20151221-181043](https://cloud.githubusercontent.com/assets/1366654/11936434/28175488-a80e-11e5-8ecd-8f80bb9c66c2.png)

**Comment by lenhard** [comment]
Should be terribly easy to implement by using [trim()](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#trim--) in the preview panel, shouldn't it? Just go ahead and fixt it.

**Comment by koppor** [comment]
Side effect: When I use "send as Email", I also want to have the same rendering as in the BibTeX source. What if I do an HTML export? Then I also want to get the trimmed representation. What of other accesses of the BibTeX source. Does that quick fix really work for all usages?

**Comment by lenhard** [comment]
We could offer a second getter for the representation `getTrimmedSerialization` or something similar. Then it really depends on the use case. I cannot tell if `trim()` is appropriate in all cases, but at least it is in yours :) I wrote the `getParsedSerialization` with file writing in mind.

**Comment by stefan-kolb** [comment]
What is the reason for this two empty lines? Personally I would always expect the serialization of a sole entry to start with @ and end with }.

**Comment by lenhard** [comment]
Because we decided that entries that have not changed should be written back exactly as they were read from the file:  #116 That means newlines have to stored somewhere and prepending newlines are stored with the parsed serialization of an entry. 

It seems that the entry editor uses the `getParsedSerialization` method from `BibEntry` and, therefore, displays the entry exactly as it was read from the file (including newlines).

**Comment by koppor** [comment]
It cannot be changed easily as it goes through the BibEntryWriter.

**Comment by lenhard** [comment]
This has already been fixed with JabRef 3.2.
