### ISSUE TITLE
Oversized Libray properties dialog

### ISSUE THREAD

**Issue by fmartelg** [JabRef/jabref#5604]
JabRef version 5.0-alpha

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. - In the toolbar section where he icons are located I see three icons, about 3x empty space, a long search box and then more empty space and >>> where, once clicked, I can see the other icons. 
3. - Click Library > Library properties, and oversize window opens that spills outside the viewing area.  I cannot resize it, nor close it except by hitting ESC.
5. - I cannot find the menu to set font sizes that existed in previous version.  The current version is very hard to read, even with reading glasses in a modern laptop.

My computer is a HP SPECTER laptop, display res 1920 x 1018, scaling 150%

**Toolbar Menu Display**
<img width="969" alt="Annotation 2019-11-12 211302" src="https://user-images.githubusercontent.com/2328896/68727022-3f61eb00-0591-11ea-8ed6-7356fee63beb.png">

**Library properties windows is oversized**
<img width="960" alt="Annotation 2019-11-12 211528" src="https://user-images.githubusercontent.com/2328896/68727159-9f589180-0591-11ea-8f21-46e8f33531d7.png">

**Comment by calixtus** [comment]
Hi @fmartelg , at least about the font size: should be available via options -> preferences -> appearance.

**Comment by fmartelg** [comment]
> Hi @fmartelg , at least about the font size: should be available via options -> preferences -> appearance.

Options -> preferences yields this menu + error. I don't see option "appearance" but maybe I am missing something
<img width="845" alt="Annotation 2019-11-13 205805" src="https://user-images.githubusercontent.com/2328896/68820201-86ff7a00-0658-11ea-99f8-3bf89074d8d7.png">

**Comment by calixtus** [comment]
You can scroll scroll down the list on the left. The scrollbars should already be a little bit more visible on the latest dev-build.
The bad visibility of that tab is probably another issue here.

**Comment by AEgit** [comment]
@fmartelg : Are you using the 5.0 Alpha version from https://github.com/JabRef/jabref/releases?

If so, you might want to try the latest development version: https://builds.jabref.org/master/
(I think at the moment you have to use the portable version, since there is a problem with the installer.) Before installing the dev version, always remember to make a backup of your database, in case something goes wrong.

**Comment by tobiasdiez** [comment]
In the latest development version, issues 1 and 3 should be fixed.
