### ISSUE TITLE
Add support for anystyle.io

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#561]
We currently support FreeCite and are working on resurrecting old JabRef code (`TextAnalyzer`) at #546.

anystyle.io (Source at https://github.com/inukshuk/anystyle-parser) also seems to be very promising. Should we additionally include it, drop TextAnalyzer, and/or drop FreeCite?

I quickly evaluated [ParsCit](http://aye.comp.nus.edu.sg/parsCit/) a few months ago. It turned out that their WSDL does not match XML schema and that it will be difficult to integrate it.

**Comment by oscargus** [comment]
Update: TextAnalyzer is no more...

**Comment by stefan-kolb** [comment]
@koppor How should we add this? It is a Ruby Gem. I would suggest to close this for now.

**Comment by lenhard** [comment]
@stefan-kolb I agree. And as nothing has happened here for quite a long time, I'll mark it as on-hold and close it now.

**Comment by koppor** [comment]
ParCit fails on the test string: `Kopp, O.; Martin, D.; Wutke, D. & Leymann, F. The Difference Between Graph-Based and Block-Structured Business Process Modelling Languages Enterprise Modelling and Information Systems, Gesellschaft für Informatik e.V. (GI), 2009, 4, 3-13`

![grafik](https://user-images.githubusercontent.com/1366654/68479988-f2e67a80-0233-11ea-87aa-82a69bb00791.png)
