### ISSUE TITLE
Error StatusLogger

### ISSUE THREAD

**Issue by jorgman1** [JabRef/jabref#5616]
I have just installed the newest dev-version and get the two windows when opening JabRef. The second one is the normal JabRef, but the first one is like a command line, with JabRef logo and title containing the following message:

"ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console..."

Version: JabRef-5.0.0.msi (2019-11-15)
OS: Windows 7x64

**Comment by AEgit** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/5474 and https://github.com/JabRef/jabref/issues/5475

**Comment by jorgman1** [comment]
Thank you @AEgit I had not seen them.

**Comment by AEgit** [comment]
You are welcome!
