### ISSUE TITLE
Support update of entries

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#562]
As user, I want to update an existing entry using information fetched from Google Scholar, Bibsonomy, dblp, ...

As far as I know, Mendeley supports that feature. Maybe, zotero does it, too.

Maybe the entry can be updated using the DOI or call all fetchers and use the "best" result.

The [Autocomplete plugin](https://github.com/gumulka/JabRefAutocomplete) updates entries based on data available at ACM, DBLP, ...

Refs #152

**Comment by lenhard** [comment]
Duplicate of #675
