### ISSUE TITLE
Today's "master builds" .deb won't install (2919-11-17)

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5626]
- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
(Reading database ... 
(Reading database ... 5%%
(Reading database ... 10%%
(Reading database ... 15%%
(Reading database ... 20%%
(Reading database ... 25%%
(Reading database ... 30%%
(Reading database ... 35%%
(Reading database ... 40%%
(Reading database ... 45%%
(Reading database ... 50%%
(Reading database ... 55%%
(Reading database ... 60%%
(Reading database ... 65%%
(Reading database ... 70%%
(Reading database ... 75%%
(Reading database ... 80%%
(Reading database ... 85%%
(Reading database ... 90%%
(Reading database ... 95%%
(Reading database ... 100%%
(Reading database ... 348213 files and directories currently installed.)
Preparing to unpack .../jabref_5.0.0-1_amd64.deb ...
Unpacking jabref (5.0.0-1) over (5.0.0-1) ...
Setting up jabref (5.0.0-1) ...
install: cannot stat '/opt/jabref/lib/native-messaging-host/firefox/org.jabref.jabref.json': No such file or directory
dpkg: error processing package jabref (--install):
 installed jabref package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 jabref

  ```
</details>

**Comment by LyzardKing** [comment]
The change to build.gradle isn't in the branch...
It might have been excluded in a merge..
I can look into the issue properly tomorrow.
I think the addition was a replacement of the include line with: `include "native-messaging-hosts/**", "jabrefHost.py"`
I'm not on my computer now, so I can't test it...

**Comment by LyzardKing** [comment]
@wujastyk It should be fixed in the branch..
If you want to test it once it uploads (if it works :wink: )

**Comment by wujastyk** [comment]
Yes, the .deb master build of 18 Nov installed fine.

**Comment by wujastyk** [comment]
Problem with today's deb (2019-12-15):

$ sudo dpkg -i jabref_5.0-1_amd64.deb 
[sudo] password for xxxx:          
(Reading database ... 352134 files and directories currently installed.)
Preparing to unpack jabref_5.0-1_amd64.deb ...
Unpacking jabref (5.0.30003-1) over (5.0.30001-1) ...
dpkg-deb (subprocess): cannot copy archive member from 'jabref_5.0-1_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg: error processing archive jabref_5.0-1_amd64.deb (--install):
 cannot copy extracted data for './opt/jabref/lib/runtime/lib/server/libjvm.so' to '/opt/jabref/lib/runtime/lib/server/libjvm.so.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 jabref_5.0-1_amd64.deb

**Comment by koppor** [comment]
How large is the file? - We sometimes have upload issues to our build server. In case you see the file size differing more than 30MB from the others, it wont't be complete.

We are working on a fix at https://github.com/JabRef/jabref/pull/5748.

**Comment by wujastyk** [comment]
Dec 16 "master builds" .deb compiles fine.  Sorry, I don't have yesterday's
file now.
