### ISSUE TITLE
File annotations should be parsed if a file is attached

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5633]
If a new file is attached, the tab "File Annotations" should be shown immediately - and not at refocus.

Video:

![jabref-rulez-2](https://user-images.githubusercontent.com/1366654/69026638-f9ab8500-09cb-11ea-8152-2e511c4c4bf5.gif)

In case one plays around with it - approx each second time, just a new entry is created instead of attaching the file.

**Comment by Xuanxuan-Zou** [comment]
Hi, we are interested in this issue.

We find a way to solve this problem, that is set the new entry after the file is attach. 
It needs add one line code in 

https://github.com/JabRef/jabref/blob/db3d409a79192ecf88dc1114143029ff738789b2/src/main/java/org/jabref/gui/maintable/MainTable.java#L276-L289

Between line 283 and line 284, adding ``` panel.getEntryEditor().setEntry(entry);```

It works, but we are not sure whether it is a proper way.

**Comment by koppor** [comment]
Thank you for looking into this. it is very hard for us to really review it. Would it be possibility OK for you to create a pull request? This is our preffered and we'll established way to review even small changes!

**Comment by Xuanxuan-Zou** [comment]
I had created a draft pull request. 
I am sorry for the misoperation coused by my unfamiliarity.
