### ISSUE TITLE
latest windows install version is afunctional

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5637]
Today 18.11.2019 I wanted to install the latest version. It did not work. Comparing the file sizes in the master directory, I notice that JabRef-5.0.0.msi as well as the portable windows zip file were very much to small.

![grafik](https://user-images.githubusercontent.com/9216487/69053855-a0167b00-0a0a-11ea-92d4-9f2e0ea86258.png)

**Comment by Siedlerchr** [comment]
Thanks for the report, I noticed that the build did not upload correctly. I triggered a rebuild which willl hopefully work
https://github.com/JabRef/jabref/runs/307878630

**Comment by AEgit** [comment]
Note, that this can happen when the newest build has just been uploaded. It appears, that the Windows build is usually the one, that takes the longest to upload (at least coming from my experience it always seemed to be the one that is the last to be fully uploaded to the Master directory). The download will appear in the Master directory as being ready to download, but actually the build is still being uploaded. If you then try to download the available build, it will be incomplete.
Usually this problem is automatically solved if you just wait for a few minutes until the build has been fully uploaded to the Master directory.

**Comment by bernhard-kleine** [comment]
Most probably that is not the case here: I loaded it at 13:45 according to the date on my file. The time between downloads were some 3 min. The latest at 13:13. BTW Siedlerchr has already confirmed incomplete downloads.

**Comment by AEgit** [comment]
Yes, in this particular case, this might not apply. But I wanted to leave this comment here, in case someone else encounters the problem again in the future: I did, a couple of times, and was about to submit a bug report before I realised that I just had to wait a little bit, until the build upload was complete. So my post is just meant as future reference, but - as you say - it might not apply to this particular case.

**Comment by bernhard-kleine** [comment]
@Siedlerchr The download stopped again at 144.7 MB, the same file size as before. That is most probably wrong.

**Comment by AEgit** [comment]
The upload for the Windows build appears to have failed:
https://github.com/JabRef/jabref/runs/307971519

@Siedlerchr Can something be done about this? The error message of the for the Windows deployment is:
`[error]Node run failed with exit code 134`

**Comment by Siedlerchr** [comment]
I think this is a bug from the SFTP Upload script. Will create a bug report
In the meantime you can download the artifact from the action: https://github.com/JabRef/jabref/suites/316024234/artifacts/355189


```
Establishing a SSH connection to builds.jabref.org.
🤝 Connected to builds.jabref.org.
Starting scp Action: build/distribution to www/master
❕copy failed for build\distribution\JabRef-portable_windows.zip.
❕copy failed for build\distribution\JabRef-5.0.0.msi.
The copy of directory build/distribution was unsuccessful.
failed transfers [object Object], [object Object]
Retrying to copy build\distribution\JabRef-portable_windows.zip to www/master/JabRef-portable_windows.zip.
⚠️ An error happened:(. Failure Error: Failure
    at SFTPStream._transform (d:\a\_actions\garygrossgarten\github-action-scp\release\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (d:\a\_actions\garygrossgarten\github-action-scp\release\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at SFTPStream.Writable.write (_stream_writable.js:301:11)
    at Channel.ondata (_stream_readable.js:713:22)
    at Channel.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
 1: 00007FF607A0814F napi_wrap+121231
 2: 00007FF6079B16F6 uv_loop_fork+44550
 3: 00007FF60795A859 v8::internal::StackGuard::ArchiveSpacePerThread+26553
 4: 00007FF607F9A049 v8::internal::OFStreamBase::xsputn+5065
 5: 00007FF607F99588 v8::internal::OFStreamBase::xsputn+2312
 6: 00007FF607F998B8 v8::internal::OFStreamBase::xsputn+3128
 7: 00007FF607F996DD v8::internal::OFStreamBase::xsputn+2653
 8: 00007FF608554196 v8::internal::NativesCollection<0>::GetScriptsSource+662454
##[error]Node run failed with exit code 134
```

**Comment by tobiasdiez** [comment]
We had the same problem a few weeks ago, and it disappeared again without us doing anything. It's probably a temporary problem with our build server. Closing this for now. Please report back if this is not resolved in a few days.

**Comment by Siedlerchr** [comment]
Today the error seems to be gone.

**Comment by AEgit** [comment]
Indeed, the full Windows dev version can be downloaded again.
