### ISSUE TITLE
Add reference to architecture diagrams for high-level packages

### ISSUE THREAD

**Issue by alexkarezin** [JabRef/jabref#5639]
**Is your suggestion for improvement related to a problem? Please describe.**
Not a problem, requesting an addition to Wiki page

**Describe the solution you'd like**
Add reference to architecture diagrams for `model`, `gui` and `logic` packages 
https://sourcespy.com/github/jabref/

**Additional context**
Not sure how to submit PR for Wiki page. Please advise. I have staged the change here.
https://github.com/alexkarezin/jabref-wiki/commit/713d119f31e8febc8337e9e8a9b3efdad8d9a361

**Comment by tobiasdiez** [comment]
Thanks, these diagrams look really cool. I added the link: https://github.com/JabRef/jabref/wiki/High-Level-Documentation
