### ISSUE TITLE
Cite command seems to have no effect at TeXstudio

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#564]
I have configured "Cite command" to be `\citep`, but TeXstudio seems to ignore this setting.

![grabbed_20151221-235016](https://cloud.githubusercontent.com/assets/1366654/11943376/b6fe7c4c-a83d-11e5-988a-e17c7a962ff7.png)

I assume that it is impossible to set a cite command for TeXstudio, is it?

**Comment by oscargus** [comment]
Actually, #564 will not fix this particular problem (although it is required to fix it). For older versions of Texstudio only the key was sent through the command line and the \cite{} was inserted by Texstudio. However, now it seems like it supports adding a customized cite command as well, so probably one should change the code to enable this.

See: http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION38

**Comment by simonharrer** [comment]
Thanks for the hint. Should be fixed now.

**Comment by dbitouze** [comment]
>Should be fixed now. 

Thanks for this fix (I didn't test). Is it possible to have an approximate date of the release that will integrate it?

**Comment by tobiasdiez** [comment]
I think the fix is already included in [version 3.2](https://github.com/JabRef/jabref/releases/tag/v3.2) which was released in January. Moreover, a new version is in the planning and should be released very soonish.

**Comment by dbitouze** [comment]
Ooops, I didn't notice JabRef 3.0 had been updated: sorry for the noise.
