### ISSUE TITLE
Highlightning stops working when "regular expression" is active

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#565]
![grabbed_20151221-235346](https://cloud.githubusercontent.com/assets/1366654/11943421/14bdf0b0-a83e-11e5-83fd-6d451fbf7700.png)

vs.

![grabbed_20151221-235359](https://cloud.githubusercontent.com/assets/1366654/11943430/2306ae14-a83e-11e5-86f2-14d8358281a7.png)

Refs #533

**Comment by stefan-kolb** [comment]
@simonharrer I thought this is expected as we cannot really detect a match yet?!

**Comment by simonharrer** [comment]
I was wrong. It could be implemented with existing methods relatively straight forward. Most things are already in place for this.
