### ISSUE TITLE
duplicate file links

### ISSUE THREAD

**Issue by urielz** [JabRef/jabref#5650]
"Quality" -> "Automatically set file links" works however it produces two identical file links.

JabRef 5.0.0-dev--2019-11-20----5376dcfb6
Mac OS X 10.13.6 x86_64 
Java 13.0.1

**Comment by koppor** [comment]
Implementation hint: For creating test cases, I would recommend [Google's JIMFS](https://github.com/google/jimfs)

**Comment by Siedlerchr** [comment]
We usually use TempFolder as Junit Parameter

**Comment by urielz** [comment]
FYI this issue seems to be resolved in JabRef 5.1--2020-06-01--aa2ac70. 

I'll leave this open for a while in case someone else wants to chime in.

Thanks

**Comment by urielz** [comment]
Closing this now.
