### ISSUE TITLE
Display error in custom entry types dialog

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5651]
Most recent development version.
![image](https://user-images.githubusercontent.com/5037600/69288049-a36f5980-0bf8-11ea-82c3-ed2b6919aa76.png)

The list should show only the name of the entry type (e.g `Lecturenotes`) instead of the `toString` output. Moreover, the label "Currently unknown:" can be removed.

**Comment by lromero21** [comment]
Hi, can I work on this?

**Comment by tobiasdiez** [comment]
Sure, feel free to work on this issue! Also have a look at our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and drop by in our [developer chat](https://gitter.im/JabRef/jabref) if you have questions!

**Comment by CloudFenrir** [comment]
Hello, I want to help but how can I get to that option? Which are the steps to deploy the error?

**Comment by JosejeSinohui** [comment]
@tobiasdiez Hi!, I made a pull request with the changes requested from this issue but it seems i don't have permission to add reviewers, can you review it or add someone to review it?

**Comment by tobiasdiez** [comment]
Thanks to @JosejeSinohui this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
