### ISSUE TITLE
Import option "Copy, Rename, Link" behaviour in v5-dev

### ISSUE THREAD

**Issue by jfk88** [JabRef/jabref#5653]
I don't know if this a bug or the expected behaviour of the "Copy, Rename, Link" option but I got this when importing a PDF (I cannot be sure of the correct order of the execution of course):

1. File is copied into my JabRef folder.
2. _Original_ file is renamed in its current location.
3. Renamed file is linked to the database.

Ergo I got a correctly renamed PDF in the program which is not the one imported in my JabRef folder. Seems rather buggy. 

Tested with the AUR package and portable version on Linux. 

Thanks

**Comment by Siedlerchr** [comment]
Refs #5563

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by jfk88** [comment]
Thank you Tobias, I confirm works.
