### ISSUE TITLE
Generate BibTeX key does not work in "BibTeX source" panel

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5654]
I pasted the following bibtex entry - and wanted to generate the key using <kbd>Ctrl</kbd>+<kbd>G</kbd>.

```bibtex
@Article{Saatkamp201ddd9,
  author    = {Karoline Saatkamp and Uwe Breitenb{\"{u}}cher and Oliver Kopp and Frank Leymann},
  journal   = {Computer Science - R{\&}D},
  title     = {An approach to automatically detect problems in restructured deployment models based on formalizing architecture and design patterns},
  year      = {2019},
  number    = {2-3},
  pages     = {85--97},
  volume    = {34},
  bibsource = {dblp computer science bibliography, https://dblp.org},
  biburl    = {https://dblp.org/rec/bib/journals/ife/SaatkampBKL19},
  doi       = {10.1007/s00450-019-00397-7},
  timestamp = {Sat, 19 Oct 2019 19:13:28 +0200},
  url       = {https://doi.org/10.1007/s00450-019-00397-7},
}
```

Note that it sometimes works - I haven't found out. Here a video where it did not work:

![jabref-rulez-3](https://user-images.githubusercontent.com/1366654/69314550-bc95fb80-0c34-11ea-8bc7-502c30539edf.gif)

**Comment by bulmust** [comment]
JabRef 5.0-beta.1--2019-12-15--0b8b1d6
Linux 4.15.0-72-generic amd64 
Java 13.0.1

If you change BibTeX key generator option to empty one, the problem still occurs.

Also, If you fetch a article from a database (for example inspire), the original inspire bibtex key is changed by BibTeX key generator. This behavior does not occur at JabRef 4.3.1.

It seems like, key generator has a priority no matter you want to do.

**Comment by koppor** [comment]
I think, the behavior with the bibtex key overwriting thing is intended. We want JabRef do to more magic. However, that change is not included in the CHANGELOG 😕 

The thing with the empty one not.

**Comment by bulmust** [comment]
We should keep our hope until stable version is released.

**Comment by Siedlerchr** [comment]
Works fine in the current master.
