### ISSUE TITLE
Can not open file with Okular version 1.3.3

### ISSUE THREAD

**Issue by bulmust** [JabRef/jabref#5660]
JabRef version 5.0.0-dev on Linux Mint 19.2 Mate

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The JabRef 5 can not open a pdf file with my default document viewer okular (version 1.3.3). To open file, I press F4 shortcut and right-click->open-file. 

1. I changed my default document viewer to xreader (version 2.2.3)
2. JabRef 5 opened the file.

Second attempt with JabRef version 5.0.0-alpha:
1. Same result

Event log is empty.

**Comment by sankayop** [comment]
Was this issue solved? I'm having the same issue with latest version:
JabRef 5.2--2020-11-19--0412684
Linux 5.9.11-3-manjaro amd64 
Java 15.0.1

**Comment by bulmust** [comment]
> @bulmust:
> Was this issue solved? I'm having the same issue with latest version:
> JabRef 5.2--2020-11-19--0412684
> Linux 5.9.11-3-manjaro amd64
> Java 15.0.1

Yes, it works with following version.

JabRef 5.1--2020-08-30--e023aa0
Linux 5.4.0-47-generic amd64 
Java 14.0.2

**Comment by sankayop** [comment]
> > @bulmust:
> > Was this issue solved? I'm having the same issue with latest version:
> > JabRef 5.2--2020-11-19--0412684
> > Linux 5.9.11-3-manjaro amd64
> > Java 15.0.1
> 
> Yes, it works with following version.
> 
> JabRef 5.1--2020-08-30--e023aa0
> Linux 5.4.0-47-generic amd64
> Java 14.0.2

Thanks for your fast answer,
In my case, it looks like I can't get my default document viewer to switch from Evince (Gnome) to Okular but I guess the issue is probably more on my default application configuration (xdg-mime) than on jabref itself.
Sorry for spamming.
I was just wondering how did you solve your issue but now I know :)

**Comment by sankayop** [comment]
> > > @bulmust:
> > > Was this issue solved? I'm having the same issue with latest version:
> > > JabRef 5.2--2020-11-19--0412684
> > > Linux 5.9.11-3-manjaro amd64
> > > Java 15.0.1
> > 
> > 
> > Yes, it works with following version.
> > JabRef 5.1--2020-08-30--e023aa0
> > Linux 5.4.0-47-generic amd64
> > Java 14.0.2
> 
> Thanks for your fast answer,
> In my case, it looks like I can't get my default document viewer to switch from Evince (Gnome) to Okular but I guess the issue is probably more on my default application configuration (xdg-mime) than on jabref itself.
> Sorry for spamming.
> I was just wondering how did you solve your issue but now I know :)

Ok, now I feel stupid...
It was indeed more on the default app configuration.
I just right-clicked on a pdf file (in GUI file explorer), then on properties > Open with>Okular) and now, Jabref opens it with my default pdf viewer: Okular...

If it can help somebody on the net, at least, these messages will not be lost :)

**Comment by Siedlerchr** [comment]
@sankayop  Thanks for the info! You may want to add this as an FAQ entry: https://docs.jabref.org/faqgeneral so people searching for this will find it easier
Just click on "Edit at github" in the top right corer

**Comment by sankayop** [comment]
@Siedlerchr : done :)
