### ISSUE TITLE
Provide option to automatically download files upon import

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5662]
**Is your suggestion for improvement related to a problem? Please describe.**
Usually, when importing entries using the browser extension, they include urls to PDFs etc. After the import, one has to go to the general tab and then download these files manually.

**Describe the solution you'd like**
Add an option in the import dialog (checkbox), that allows to automatically download all linked files and rename /move them to the default file location.

**Comment by joelostblom** [comment]
This would be a convenient feature! Minor potential addition: remembering the last checked status as the default for the next import dialog, or with the option in the preferences menu of setting the default status.

**Comment by LyzardKing** [comment]
@tobiasdiez Does the jabref cli have an option to import a pdf?
I'd like to try adding this option

**Comment by tobiasdiez** [comment]
@LyzardKing Awesome that you want to have a look at this.
No, the cli only allows to import bib entries / databases. But I would integrate this functionality at a later stage anyway. Namely, add a checkbox at the bottom of the import dialog (https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/importer/ImportEntriesDialog.java) "Download linked online files" and then reuse this code for the actual download of the contained files:
https://github.com/JabRef/jabref/blob/eb988b6ead6beae3d64b95aa8827567adf8b81df/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L395-L418

**Comment by LyzardKing** [comment]
Ok, so integrate it directly in the jabref dialog!
Sounds good..
I'll try and cook up something :)

**Comment by btut** [comment]
I implemented the basic functionality. There is no persistence yet though. I think it would be better to have this as a setting rather than remembering if the box was checked the last time or not. Don't know how to do that though as this is my first contribution here.

**Comment by LyzardKing** [comment]
Great job! I haven't had time to look at this, and you managed to do it better than I could have :)

**Comment by ilippert** [comment]
ref https://github.com/JabRef/jabref/issues/1456

**Comment by Siedlerchr** [comment]
Thanks to @btut  this issue should now be fixed in the latest master (should be ready in roughly hafl an hour
