### ISSUE TITLE
How can I fetch a references bibtex key with special character?

### ISSUE THREAD

**Issue by bulmust** [JabRef/jabref#5681]
Version: JabRef 5.0.0-dev--2019-11-21----782953d0a

- I tried following command but it is not recognized.

```
/opt/jabref/bin/JabRef -f INSPIRE:arXiv:1007.5048
Expected syntax for --fetch='<name of fetcher>:<query>'
The following fetchers are available:

``` 
On the other hand if I enter `/opt/jabref/bin/JabRef -f INSPIRE:neutrino` it works. Thus, I need to understand how should I put special characters (: , . , etc.) in the fetch syntax.

- Also, how can I add fetched reference to current bib file? I do not want to add created temporary 'untitled' file.

**Comment by tobiasdiez** [comment]
Did you tried to add quotes, i.e. `/opt/jabref/bin/JabRef -f INSPIRE:"arXiv:1007.5048"` ?

Please use our forum for questions the next time: http://discourse.jabref.org/

**Comment by bulmust** [comment]
Yes, I tried following command:
`/opt/jabref/bin/JabRef -f INSPIRE:'arXiv:1007.5048'`

I will continue this topic on http://discourse.jabref.org/
