### ISSUE TITLE
Dark theme: not for "Restart required" window (and others)

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#5699]
A glitch...

JabRef 5.0.1-dev--2019-11-29----9043f8008
Linux 4.9.0-11-amd64 amd64 
Java 13.0.1

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists **(No. I could not. See other issue)**

In dark theme, the window asking to restart JabRef remains in light mode.

1. Set JabRef to dark theme
2. In Preferences, General, change the language
3. Click on Save
4. A window asking for restarting JabRef pops up

This window is in light theme:

![image](https://user-images.githubusercontent.com/6931104/69967256-505ea600-1518-11ea-97f2-46e6ac12be4e.png)

Note: same glitch for windows "Save before closing", "Check integrity", "Overwrite keys" and "Download full text documents".

**Comment by gilbertoayala12** [comment]
Hey, can I work on this ?

**Comment by Siedlerchr** [comment]
@gilbertoayala12  Thanks for your interest. Sure, go ahead. Please see 
our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) for getting started

**Comment by tobiasdiez** [comment]
Thanks to @MootezSaaD this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by mlep** [comment]
I can confirm this issue is now solved. @MootezSaaD thank you!
