### ISSUE TITLE
Add test cases for IEEEXplore search

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#570]
Test cases are given at https://sourceforge.net/p/jabref/bugs/1146/ and https://sourceforge.net/p/jabref/bugs/1267/

Refs #488

**Comment by stefan-kolb** [comment]
I checked both bugs and they are working fine now. Also, the data source is different than before as far as I can see. So this cannot happen anymore, or in other words we don't do any scraping to avoid this anymore.

**Comment by koppor** [comment]
I just ask to create two `@Test` methods. Just to be sure that when touching the IEEE fetchers again, this does not happen.

Could be something for @fronchetti to use to learn the way testing works at JabRef.

**Comment by stefan-kolb** [comment]
I would have created those test if I knew how to do it.

**Comment by koppor** [comment]
Side note: `net.sf.jabref.gui.importer.fetcher.IEEEXploreFetcher` uses the old fetcher style and has some RegEx patterns in it. `net.sf.jabref.logic.importer.fetcher.IEEE` just implements `FullTextFetcher`. No other kind of fetchers. Thus, it is OK to have no test coverage here. Focusing on important things 🔥
