### ISSUE TITLE
Cannot update JabRef using .deb from master (Linux)

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#5700]
JabRef 5.0.1-dev--2019-11-29----9043f8008
Linux 4.9.0-11-amd64 amd64 
Java 13.0.1

After installing the above version using the .deb package (from https://builds.jabref.org/release-5-0-beta/), I wanted to test the last development version (from http://builds.jabref.org/master/).

The package updater could not install it because "A more recent version is already installed".

**Comment by Siedlerchr** [comment]
Hi,

thanks for reporting.
The beta is not yet ready to be released (the PR ist not yet merged), there are still some minor things in the deployment workflow we need to adapt regarding the version number. As the beta PR is not merged, the master has a lower version number than the beta.
Refs #5684  Once it's merged it should be working fine again.
