### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#5701]
JabRef 5.0.1-dev--2019-11-29----9043f8008
Linux 4.9.0-11-amd64 amd64 
Java 13.0.1

Strings that are not translated in the GUI of JabRef:
- In the group panel: the field to search a string within the groups displays "Filter groups". "Filter groups" is not translated. 
- In preferences: BibTeX key generator: key patterns: The header of the table (Name, Key pattern, Reset all) are not translated.

**Comment by CloudFenrir** [comment]
Hello, I will take this bug if no one else is doing it

**Comment by CloudFenrir** [comment]
Hello, I will take this bug if no one else is doing it

**Comment by Vencesdab** [comment]
Actually, there are other untranslated things in the Preferences that I found out :
- In Entry table columns, Columns and the list under it are not translated.
- In Entry preview, the first (and only) box to check ("Show preview as tab in entry editor") is untranslated
- In Entry editor, the 5th box "Show 'LaTeX Citations' tab" is untranslated.
- In Entry editor, Autocompletion, the name of this part, the box "Use autocompletion", the "affected fields", and the categories "Name format" and "First names" are not translated.
- In Import, "Linked file name conventions" is not translated.
- In XMP-metadata, the box "Do not write the following fields to XMP Metadata" is untranslated.

Here you go, have fun :)

**Comment by mlep** [comment]
Thank you @Vencesdab for looking at this issue.

There are two reasons strings may appear untranslated in the GUI:
- programming does not allow for translation.
- translation is not provided in language XYZ.

My issue concerned only the first case (but I did not mention it. My mistake).

Except for the case "In Entry table columns, Columns and the list under it are not translated.", the strings you reported fall in the second case.
Please, contribute their translations in your preferred language at https://crowdin.com/project/jabref .

@CloudFenrir: 
About "In Entry table columns, Columns and the list under it are not translated.":
- "Columns" is available to translation
- "Name" (the list header) falls in the present issue.   
- not all strings in the list should be translated. Typically, the usual bib(la)tex fields are kept in English (author, title, howpublished, etc.), while the JabRef-specific fields should be made available for translation (Relevance, Readstatus, Ranking, etc.).

**Comment by mlep** [comment]
JabRef 5.0-beta.16--2019-12-18--28d3439
Linux 4.9.0-11-amd64 amd64 
Java 13.0.1

Update:
Almost all strings are now translated :+1: 
Only the special fields in the drop-down list of Options > Preferences >  Entry table columns remains untranslated.
