### ISSUE TITLE
Very small display with high DPI screen on linux

### ISSUE THREAD

**Issue by HarryPommier** [JabRef/jabref#5704]
Hi,

JabRef appears really small (text, menus, icons...) on 4K, high dpi screen on linux Mint 18 with Cinammon.

To fix this, I changed my /usr/lib/java-wrappers/java-wrappers.sh, line 305
exec $JAVA_CMD $JAVA_ARGS $cp "$@"
by
exec $JAVA_CMD $JAVA_ARGS $cp -Dsun.java2d.uiScale=2 "$@"

It works well for me, but might not be very clean.
Could someone generalize this idea ?

Thanks.

**Comment by calixtus** [comment]
Hi @HarryPommier , did you try to change the font size in the JabRef preferences (the appereance preferences are a little bit hidden in the left list at the very bottom)

**Comment by HarryPommier** [comment]
Hi @calixtus, I try changing the font size. It works well for the menu but it does not for the buttons (see below)

**Base display:**
![JabRef_base](https://user-images.githubusercontent.com/50177956/71068458-124bbe00-2177-11ea-8812-5a50ef1b584d.png)

**Fontsize = 20**
![JabRef_fontsize_20](https://user-images.githubusercontent.com/50177956/71068544-3b6c4e80-2177-11ea-8c48-ae3d3e665c38.png)

I think this looks better when setting -Dsun.java2d.uiScale=2 in the run command (see below)

**My modification with uiScale=2 (and fontsize=11)**
![JabRef_UIScale=2](https://user-images.githubusercontent.com/50177956/71068538-3909f480-2177-11ea-83fc-9d0a23e0e8f7.png)

Thanks,

**Comment by calixtus** [comment]
Thanks for your reply, I notice you are using a rather old version of JabRef. In the last months there have been made some big changes to the ui and the framework behind. If you like, you can download and test the latest build of 5.0-beta from [builds.jabref.org/master](https://builds.jabref.org/master) . But remember to backup your libraries before you do.

**Comment by HarryPommier** [comment]
I installed the latest build. The new interface looks very well !
![JabRef_5 0beta](https://user-images.githubusercontent.com/50177956/71071685-58a41b80-217d-11ea-80e8-5b18bd254cd7.png)

Thanks for your work,
