### ISSUE TITLE
[Code] Use Project Lombok?

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#571]
I just stumbled upon [Project Lombok](https://projectlombok.org/), which allows one to write 
````
@Getter @Setter private boolean employed = true;
```` 
instead of the whole `getEmployed` and `setEmployed` non-sense. (Its like C# 's automatic properties). Are you ok with me including and using this library?

**Comment by simonharrer** [comment]
I am against this. Normally, one should not write getters and setters blindly, but use final variables which are set by the constructor. And this increases the entry barrier for new developers for JabRef as they would have to learn this technology as well.

**Comment by tobiasdiez** [comment]
I'm not sure what you mean by "not write getters and setters blindly". Isn't common to write code like the following?
```` java
private boolean employed = true;

public boolean isEmployed() {
    return employed;
}

public void setEmployed(final boolean employed) {
    this.employed = employed;
}
````
I would call this blindly and redundant :-)
Data objects consists just of methods like this, see for example the class [`CleanupPreset`](https://github.com/tobiasdiez/jabref/blob/cleanupRefact/src/main/java/net/sf/jabref/logic/cleanup/CleanupPreset.java).

But I do understand the point of a increased entry barrier.

**Comment by lenhard** [comment]
Ah, the good old discussion of getters/setters vs properties :-)

Technically, properties are superior. It would have been better if Java had included them from the beginning. However, it did not and by now the Java Ecosystem has evolved using getters and setters. Various Java standards make use of getters/setter (Beans, etc.) and most documentation and resources use getters/setters for explaining Java code. For that reason, I would stick with getters and setters. The annotations from Lombock avoid some boilerplate code, but that is really no huge advantage. Any IDE can generate getters/setters if you don't want to write them and if they should do anything above the absolutely basic (say, a setter with a null check), you will end up writing the code anyway.

We don't have many objects in JabRef where this *really* would make a difference. Thus, I will stick to the standard way. I don't have a strong opinion and would be open to you using this feature if you really want, but I guess there are others with a strong opinion.

**Comment by tobiasdiez** [comment]
Ok convinced. I don't have a strong opinion about it too, just found it neat.
