### ISSUE TITLE
Remembering sorting of maintable

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#5713]
Hi,
Using JabRef 5.0-alpha--2019-12-04--5dcb565 (but was present in earlier version).
In 4.* version, maintable was always sorted by date (my choice). However in 5.*, each time I restarted the program, the sorting returned to default alphabetical order of author. 
Thanks
Mélanie

**Comment by Siedlerchr** [comment]
Hi,
thanks for your report. This is a known issue. We had it once activated in 5.x. but the approach was killing the performance so we had to disable it. We are investigating other solutions for this problem.

Duplicate  of #4224
