### ISSUE TITLE
Problem with Windows installer

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5732]
It does not seem possible to install the current development version that is offered on the master branch. Every time I try to run the installation I get the following error message:

"This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package."

EDIT: I have only tested the Windows .msi installer.

**Comment by Siedlerchr** [comment]
Hi, I just encountered this, too. I guess it's a problem with the build server. I try to trigger a new build.

**Comment by AEgit** [comment]
JabRef 5.0-alpha--2019-12-11--c3b7ee7
Windows 10 10.0 amd64 
Java 13.0.1

Problem appears to be solved with the newly uploaded build.

**Comment by chrisrapson** [comment]
I ran into the same problem today.
JabRef-5.0.msi (2019-12-18 02:02 347.5MB)
Windows Server 2016 v10.0
Java 1.8.0

This link might be relevant: https://java.com/en/download/help/error_installpackage.xml

(I'm trying to upgrade from 4.3.1 due to this issue: https://github.com/JabRef/jabref/issues/2829

**Comment by AEgit** [comment]
Try downloading the current developer version:
JabRef-5.0.msi (2019-12-18 08:14 347.6MB)

That one appears to be 0.1 MB larger than the version you downloaded. Maybe the build had not been fully uploaded when you tried to download it?

**Comment by chrisrapson** [comment]
I downloaded the newest 5.0-beta version (2019-12-23 09:56 343.9MB) and that solved both problems (installing and editing entries). Thanks for suggesting a retry @AEgit
