### ISSUE TITLE
New installation does not automatically upgrade previous installation

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5739]
It's now possible to install a new version even through an older (5.0.x) version is already installed. However, the user experience is just as for a normal installation instead of an upgrade. Thus, the user has to reselect the folder etc. This should happen automatically.

This should be possible with WiX, so I have to investigate if this a bug with jpackage or if we are misconfiguring something. https://wixtoolset.org/documentation/manual/v3/howtos/updates/major_upgrade.html

**Comment by bernhard-kleine** [comment]
This actually works. I have a Jabref 4.3.1 and Jabref 5.0 version in parallel on my desktop. The only thing I have to adjust is the directory where JR5.0 should be installed: jabref5 instead of jabref. Everything else runs smoothly.

**Comment by tobiasdiez** [comment]
I did a  bit of research, and what I originally had in mind does not seem to work. Since it generally works, I'll close this issue now.
