### ISSUE TITLE
Proprietary dependencies in JabRef

### ISSUE THREAD

**Issue by sudoman** [JabRef/jabref#5742]
JabRef master branch on GNU/Linux

- I have checked the latest development version from the master branch.

Thanks for the cool project. : ) Your main page says that JabRef is "open source", but it looks like you have a proprietary dependency listed in https://github.com/JabRef/jabref/blob/master/external-libraries.txt . Are there any other proprietary dependencies currently used by your project? It would be awesome if those dependencies were dropped in favor of freely licensed code.

Your documentation also states that you bundle a JRE in version 5.x builds. Do you bundle the proprietary Oracle version, or do you use OpenJDK? I think that GNU/Linux users would be surprised if your project distributes a non-free version of Java. It would also be nice to bundle the free version of the JRE for other platforms too.

I think your project is cool, and could be even cooler if all of its components were free software. Thanks. : )

**Comment by Siedlerchr** [comment]
Hi,
thanks for your interest in JabRef.  It seems the list of external dependencies is a bit out of date as we removed some deprecated dependencies. As far as I know we don't have any proprietary dependencies.  Regarding the JRE: We build a custom jre based on Liberica JDK (OpenJDK) using [jlink/jpackage](https://openjdk.java.net/jeps/220) 
All our current dependencies are listed in the build.gradle 
You could take this as an opportunity to update the list.  This would help us a lot.

**Comment by tobiasdiez** [comment]
As @Siedlerchr said the bundled JRE is the one used by https://github.com/actions/setup-java, which defaults to OpenJDK.

The Oracle license is indeed outdated. I corrected this. Thanks!
