### ISSUE TITLE
Broken link on JabRef documentation website

### ISSUE THREAD

**Issue by sudoman** [JabRef/jabref#5743]
The following link comes from the main page of <https://docs.jabref.org/>: <https://docs.jabref.org/finding-sorting-and-cleaning-entries/import-using-publication-identifiers>, which prints an error instead of loading.

**Comment by tobiasdiez** [comment]
For me the link works, maybe there was a temporary problem.
For the future, please open documentation related issues at https://github.com/JabRef/user-documentation, or even better fix them directly. The documentation can be edited very easily (in fact it probably took you longer to create this issue than it would have been to correct the URL yourself).
