### ISSUE TITLE
Compiled jar files in git repo

### ISSUE THREAD

**Issue by sudoman** [JabRef/jabref#5744]
I found these `.jar` files in the source repo:

```
./lib/sourcecode-0.1.4.jar
./lib/libreoffice.jar
./lib/afterburner.fx.jar
./lib/fastparse-utils-1.0.0.jar
./lib/fastparse-1.0.0.jar
./gradle/wrapper/gradle-wrapper.jar
```

It would be nice if JabRef only included source code in the git repo, partly to keep things clean.

Some of these files may be under copyleft licenses, so distributing them in binary form could require sending source code to users who request it.

Could any of these files be compiled from source, or fetched by gradle? As for the gradlew dependency, could that be fetched with a script? Thanks : )

**Comment by tobiasdiez** [comment]
All of these libraries are open-source (and their licenses are listed in the respective file).
There were problems with each of these libraries that forced us to put the jar file directly into our rep. If you have an idea how to solve these issues, please feel more than welcome to open a PR!

(By the way, there is real difference between having the jar files in our rep and using gradle to fetch them from maven...)
