### ISSUE TITLE
Ampersands in German translation

### ISSUE THREAD

**Issue by funnym0nk3y** [JabRef/jabref#5754]
JabRef version 5.0-beta on Windows 10

Thanks for the new beta build!
The new beta build has a few, uncritical, quirks I want you to inform of.

In the German translation of JabRef are a few cases where the word is preceded by an ampersand (&). 
This is the case in the following menues:
Datei -> Importieren -> Importieren in aktuelle &Bibliothek
Datei -> Importieren -> &Importieren in neue Bibliothek
Werkzeuge -> &XMP-Metadaten in PDFs schreiben
Werkzeuge -> &Einträge in extern Anwendung einfügen
Werkzeuge -> &Abkürzung der Zeitschriftentitel aufheben

EDIT:
Hope a quick update of the translation files fixes the issue. See translated file.

**Comment by Siedlerchr** [comment]
Hi, these ampersands are from the old version and indicated the mmemonic key (e..g underline the accelerator with alt).
Seems like they can be replaced with underscores:
https://medium.com/@zoha131/handling-keyboard-shortcuts-in-javafx-2972ba950a48

This would need some testing if this really works so easy.

**Comment by funnym0nk3y** [comment]
Unfortunately I have never written Java or anything JVM-based. I can offer to replace the ampersands with underscores, but that's it. Probably won't fix that issue though...

Also please excuse the updates in the localization service, I was a little rash.

**Comment by Siedlerchr** [comment]
I will try the next days if the underscore works. Then you can again work on crowdin.

**Comment by tobiasdiez** [comment]
I would prefer to use the `setMmemonic` method (also discussed in your link). This way we don't clutter the localization files with underscores (what happens if the same string is used in the menu and somewhere else?) and are more flexible it the future. Not sure if we can simply reuse the key shortcut or if a new field is necessary (does this need to be language specific? How do memonics work in say Chinese?)

A lot of questions...maybe it's simpler to just remove the memonic stuff completely.

**Comment by Siedlerchr** [comment]
As far as I know we had the menu properties in a separate file. But I think we got rid of them.

**Comment by koppor** [comment]
Do we have accelerator keys if we remove the mnemonic stuff? I really :heart: keyboard shortcuts. Do we need to re-introduce Menu_xx.properties again?

**Comment by calixtus** [comment]
I believe this issue can be closed, as the ampersands have been removed from all the translations.
As accelerator keys just the keyboard shortcuts are now left. I think we could make another issue out of that.
