### ISSUE TITLE
Installation .deb via Gdebi

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#5757]
JabRef version 5.0-beta on Ubuntu 18.04
Hi,
Try to installed jabref_5.0-beta-1_amd64.deb via Gdebi and got this error. Show 0% progress.
![Logiciel_029](https://user-images.githubusercontent.com/1063951/70955282-42437600-203e-11ea-9ca9-698d715730e1.png)

Using terminal seems to works (even though looks was already installed but didn't displayed any error message): 
![Sélection_030](https://user-images.githubusercontent.com/1063951/70955370-a108ef80-203e-11ea-9d53-7f6764e218d1.png)

Anyway, it's installed fine, go try now!

**Comment by Siedlerchr** [comment]
@LyzardKing could you take a look at this?

**Comment by LyzardKing** [comment]
That's Gnome Software, not Gdebi..
The issue seems to be with a version of oracle-java not configured correctly..
You can reconfigure it, if I remember correctly, by running
`sudo dpkg-reconfigure oracle-java11-installer-local`

**Comment by Siedlerchr** [comment]
But why does it want to install java 11? JabRef ships with jre 13 included. Or is this is a leftover from a previous installation or is this unrelated?

**Comment by LyzardKing** [comment]
I think it was already installed in the computer of @melTr 
It's not a package included in the ubuntu repos, so it cannot have been installed by jabref

**Comment by melTr** [comment]
Okay. When I tried to install the alpha version the first time, i had also
an error. I think i tried to manually installed via console this
oracle-installer and since then i have errors during update processes. I
will verify tonight which ones exactly.
Thanks
Mélanie

Le mar. 17 déc. 2019 03 h 46, Galileo Sartor <notifications@github.com> a
écrit :

**Comment by Siedlerchr** [comment]
You can safely remove the oracle java version. JabRef now ships with a custom JRE included in the deb file.

**Comment by LyzardKing** [comment]
as @Siedlerchr said.. a jre is not needed.
The error should disappear after removing the oracle java installer as well.
