### ISSUE TITLE
Import from JabFox Causes New Instance of JabRef (Linux,FF)

### ISSUE THREAD

**Issue by PorcelainMouse** [JabRef/jabref#5766]
JabRef version 5
jabref-5.0.30016-1.x86_64 (master)

The issue is that importing from JabFox causes a new instance of JabRef to start running, same as if JabRef isn't running already.  However, JabFox reports that it has established communication to JabRef.  So, not sure why it is doing that.

1. Start Jab Ref
2. navigate to importable page
3. cick JabFox import icon

There is no error, per se, only the behavior is wrong; I assume this is not the intended behavior, but I don't know because I haven't got it working yet.  It is certainly atypical behavior, for sure.  When the second instance starts, it complains about backup files for all the open jabref databases, which is predictable.

I opened a bug on JabFox for this, but I the team over there thought it could be a JabRef bug because JabFox says that it can communicate with JabRef.  They also said they would look into it further, though.

https://github.com/JabRef/JabRef-Browser-Extension/issues/111

(BTW, love the new v5.  Super excited. Thanks!  Looks a lot better on my system than v4, for starters.)

**Comment by bernhard-kleine** [comment]
Under "Options->Advanced" you should add 6050 to the port and check "listen for remore operation on port".

**Comment by bernhard-kleine** [comment]
In the Details part of the Jabfox add-on there is written:

> Download jabref.json, JabRef.bat and JabRef.ps1, and copy them to the same directory as JabRef.exe

However the .bat file is burrowed in C:\Program Files\JabRef5\runtime\bin and JabRef.ps1 does not exist in the 5.0 version. Therefore for me JabFox does not work.

**Comment by PorcelainMouse** [comment]
@bernhard-kleine, Oh, thanks!  Yes, that makes sense.  However, JabFox said it was communicating with JabRef before.  It still says it can communicate, now that I have checked that box for port 6050.

But, now, JabFox doesn't work!  Before, JabFox would be visible on import-able pages.  Now, it's grey-ed out on journal article pages, but not on other regular web-pages.  For example, it's available on this page for this github issue, but not on this DOI:10.1088/0143-0807/28/3/E01 .  So confusing!

**Comment by PorcelainMouse** [comment]
Ignoring the problem with JabFox not working on the pages I need, I tested another page, and it *does not* cause a new instance of JabRef.  I seems pretty clear that was the problem.  Thanks @bernhard-kleine .

**Comment by bernhard-kleine** [comment]
I cannot import via JabFox at all. When using Pubmed (on firefox) the jabfox icon is greyed and does not work. Trying to import DOI 10.1002/cne.20260 from the website fails because the import into jabref is never finished. Please reopen the issue!

**Comment by PorcelainMouse** [comment]
@bernhard-kleine doyou have the latest JabRef 5 (beta, from the development branch)?  I think there is a new package just about every day.  I tried your DOI and, for me JabFox doesn't let me try to import it, it is also grayed out.  So, it sounds like you are getting different behavior than me.

Also, your suggestion fixed this bug for me, and it sounds like you aren't getting new instances started, either.  So, I think this issue is solved.

Are you following this issue? https://github.com/JabRef/JabRef-Browser-Extension/issues/90

That is my main issue, now, and I think that is one of your problems, too.

It also sounds like you have another problem with JabRef imports failing.  I would open a new issue for that.  When JabFox does work, import succeeds for me, at least most of the time.  So, I think JabRef will want to know about your issue.  It's probably something specific about the reference you want to import.  I got an error importing from a random web-site, but it wasn't really a journal article, so I figured I would let it go, since other imports worked fine.

Also, I had weird problems before I installed the extra .json file, correctly.  Do you know what I'm talking about?
