### ISSUE TITLE
Impossible to add a rank to an entry directly from the main window

### ISSUE THREAD

**Issue by leosumi** [JabRef/jabref#5768]
If you want to add a rank to an entry, you need to add it from the edit menu. This is not an issue in jabref 4.3.1.

I would expect a pop-up to open to select the number of stars when you click the rank field of the entry (the same behavior as for the read status).

JabRef 5.0-beta.16--2019-12-18--28d3439
Linux 5.3.0-24-generic amd64 
Java 13.0.1

**Comment by Siedlerchr** [comment]
In the latest master, stars can be clicked directly to set the rank:
<img width="1125" alt="grafik" src="https://user-images.githubusercontent.com/320228/101535587-2a74a880-3999-11eb-8104-491eb155bf45.png">
