### ISSUE TITLE
Decrease size of distribution

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5771]
(I did not find the issue. Feel free to link the issue and close this one)

Our installer size decreased. I quickly looked into it and foudn following two files:

![grafik](https://user-images.githubusercontent.com/1366654/71220572-49ca7f80-22c9-11ea-9cdd-54fe2479c5f1.png)

Do we really need `JabRef.merged.module-....jar`?

We also have lib/runtime/lib/modules with 157MB of size. Are the modules doubled here?

**Comment by tobiasdiez** [comment]
I think the jar files are obsolete (also the ones from the libraries) as they all should be included in the lib/modules file...

**Comment by koppor** [comment]
The other size info was http://builds.jabref.org/chocoDev/:

![grafik](https://user-images.githubusercontent.com/1366654/71287148-d166cb80-2367-11ea-8bc9-98b233b9cf25.png)

**Comment by koppor** [comment]
Largest difference - as we discussed. Will remove them at https://github.com/JabRef/jabref/pull/5748

* ![grafik](https://user-images.githubusercontent.com/1366654/71287401-8f8a5500-2368-11ea-84da-b6c8a22ea319.png)
* ![grafik](https://user-images.githubusercontent.com/1366654/71287419-99ac5380-2368-11ea-93fb-74fa98b1067f.png)
* ![grafik](https://user-images.githubusercontent.com/1366654/71287440-a7fa6f80-2368-11ea-9416-4e5eb62f04d8.png)

**Comment by koppor** [comment]
Reading the [badass jlink link doc](https://badass-jlink-plugin.beryx.org/releases/latest/#_mergedmodule):

> The badass-jlink plugin takes a more pragmatic approach by combining all non-modular dependencies into a single jar. This way, only the resulting **merged module** needs a module descriptor.

I interpret this as that the merged module is required somehow. However, I tried to start the portable zip where this was removed (source: http://builds.jabref.org/change-upload-back-to-script/) and it worked. Strange.

**Comment by tobiasdiez** [comment]
It's probably related to https://github.com/beryx/badass-jlink-plugin/issues/51. I would recommend to remove these files as part of https://github.com/JabRef/jabref/blob/5ffb1b2924691f132b578c86123248fe3355e3a7/build.gradle#L699

**Comment by koppor** [comment]
# Windows

![grafik](https://user-images.githubusercontent.com/1366654/71310267-60c8b900-2412-11ea-8599-a97d3e4dc7fa.png)

# Linux

![grafik](https://user-images.githubusercontent.com/1366654/71310272-6cb47b00-2412-11ea-8482-94c0964cda27.png)

# Mac 

![grafik](https://user-images.githubusercontent.com/1366654/71310274-79d16a00-2412-11ea-9aeb-d2b128d94b99.png)

**Comment by koppor** [comment]
I would assume 

- `jpackageImage` creates the `.deb`, `.msi`, `.pkg` files
- `jpackageImage` includes the `app/mods` folder
- `deleteModsFolder` runs **after**

Which assumption is wrong?

**Comment by tobiasdiez** [comment]
The first. jpackageImage creates the so-called application image, which contains everything you need to run JabRef (distribution/JabRef). The installer are created afterwards in jpackageInstaller (or something similar named).

Nonetheless, there appears to be a problem as the mods folder is never deleted, right?

**Comment by Siedlerchr** [comment]
There is a bug report for jpackage: https://bugs.openjdk.java.net/browse/JDK-8236830

**Comment by tobiasdiez** [comment]
Guess who reported it :smile:

**Comment by koppor** [comment]
Try quick shot by deleting `mods` folder. IF not succeed, take out of v5.1.

**Comment by koppor** [comment]
Idea:

- run `gradle jPackage` locally
- create `.sh` locally to test
- code and fix
- copy back script commands to build file
- Alternative: register as gradle task and remove files from archive
- Good documentation of jlink

**Comment by koppor** [comment]
Should be fixed now.
