### ISSUE TITLE
Context menu of linked file not updated after downloading

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#5777]
JabRef version  on 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add online link to a pdf to some entry
2. Right-click pdf > Download
3. Wait until downloaded.
4. Right-click pdf again. Most of the options are still grayed-out, probably because JabRef still thinks that this is an online pdf and not a local pdf.

Relevant code:
context menu: https://github.com/JabRef/jabref/blob/fc4201d6dffe16d2d3a820bd1200c4256c9c3e02/src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java#L215-L267
download: https://github.com/JabRef/jabref/blob/fc4201d6dffe16d2d3a820bd1200c4256c9c3e02/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L407-L410

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by kevone123** [comment]
Mac OS X 10.14.4
Java 13.0.1

 I can’t recreate this bug.
 
1) I clicked general and added the link http://www.africau.edu/images/default/sample.pdf to URL
2) Then I right-clicked  “Open URL or DOI”(I did this because Open File was grayed-out despite adding the URL
3) I downloaded the pdf but Open File was still grayed - out.
    
<img width="1440" alt="Screen Shot 2019-12-31 at 12 24 04 AM" src="https://user-images.githubusercontent.com/12687673/71611051-1824a480-2b64-11ea-84e4-5172287b1a3a.png">





 Then I tried to download from URL. I didn't get the same grayed out the issue.

<img width="841" alt="Screen Shot 2019-12-31 at 12 26 52 AM" src="https://user-images.githubusercontent.com/12687673/71611071-47d3ac80-2b64-11ea-9e25-00422cee6c00.png">

What am I missing to recreate this bug?

**Comment by tobiasdiez** [comment]
@kevone123 Thanks for your interest! The entry context menu of the main table is working fine, but the context menu of the file is the problem (right click on "PDF" in your last screenshot). Sorry for being imprecise.

**Comment by kevone123** [comment]
@tobiasdiez I'm still unable to recreate this bug. 

  1) Added the link to an entry

<img width="420" alt="Screen Shot 2020-01-06 at 1 04 42 PM" src="https://user-images.githubusercontent.com/12687673/71837748-25babc80-3085-11ea-9077-2755a8183e85.png">

  2) Downloaded the pdf

<img width="1154" alt="Screen Shot 2020-01-06 at 12 49 20 PM" src="https://user-images.githubusercontent.com/12687673/71837079-8e089e80-3083-11ea-8dad-8b015fd8acc6.png">

3) When I right-clicked the pdf it isn't grayed out.

<img width="601" alt="Screen Shot 2020-01-06 at 12 50 53 PM" src="https://user-images.githubusercontent.com/12687673/71837150-b85a5c00-3083-11ea-9b6e-68bb01cdaac3.png">

However it is greyed out when I clicked the empty grayed line after it.
<img width="597" alt="Screen Shot 2020-01-06 at 12 51 09 PM" src="https://user-images.githubusercontent.com/12687673/71837178-cc9e5900-3083-11ea-90d3-83ee962564ef.png">

Thank you for your response.

**Comment by tobiasdiez** [comment]
This is very strange. For me, the context menu looks like the one on your last screenshot. Only after I switch between entries, the context menu is updated correctly.

**Comment by Xuanxuan-Zou** [comment]
Hi, we are a team of 5 students, and we are interested in working on this issue. 

Firstly, we had reproduced this bug. Thanks for your tips, we understand the reason. In our opinion, we find that only after downloading completed, ```LinkedFile``` object’s link attributes will update, and content menu will consequently update, making some options not grayed out. 

We guess that it can’t immediately update for it not renews content menu, and can only reinitialize after switch between entries.

We consider whether it is possible to renew the content menu immediately after downloading complete, that is after ```onSuccess``` function. But we are a little confused about the ```onSuccess``` function, it seems like a blocking, which can make the program continue to do other things. And we have no ideas on where to add operation after this function. Therefore, we are stucking at this.

We would sincerely appreciate it if you could give us some hints or suggestions.

https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L415-L420

**Comment by tobiasdiez** [comment]
Thanks for your interest!

Updating the context menu manually would be one option. However, the "proper" JavaFX way would be to listen to the changes in the linked files. However, this automatic update should work in principle - but it doesn't for some reason.
I would start investigating this issue by debugging how often/ when https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java#L217 is called. Then go up the chain and check when these methods are called:
https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/util/ViewModelListCellFactory.java#L190
https://github.com/JabRef/jabref/blob/7cb7ea60324932723db22fcd1964e26f73f7d9b4/src/main/java/org/jabref/gui/util/ViewModelListCellFactory.java#L161

**Comment by Xuanxuan-Zou** [comment]
Many thanks for your guidance, we understand this issue better.

After re-syncing today, we find this bug seems to be solved due to issue [# 6381](https://github.com/JabRef/jabref/pull/6381). After downloading completed, the context menu will update immediately. And a new entry will be added but not overwrite. Sorry for not syncing this project in time. 

Please point out if there is any misunderstanding. Thanks a lot!

**Comment by Siedlerchr** [comment]
I think @btut still noticed some issues in his comment https://github.com/JabRef/jabref/pull/6381#discussion_r420556932
Maybe you can work together on the remaining issues?

**Comment by Xuanxuan-Zou** [comment]
We will try to work on the remaining issues. Thanks.

**Comment by btut** [comment]
I'd be happy to!
The issue that I am having is that it would be nice to somehow let the user know that the file is still being downloaded. Otherwise people may wonder why the file entry is missing while actually the file is not downloaded yet.
@Xuanxuan-Zou feel free to join the discussion in #6381

**Comment by calixtus** [comment]
I noticed that the ContextMenu for the FileEditor is not using the factory methods, we normally use for JabRef menus.
Take a look at `gui/maintable/RightClickMenu.java` for an example. Maybe this is worth some programming time. 😉

**Comment by Xuanxuan-Zou** [comment]
Thanks for your reminder！We will try to. 😃
