### ISSUE TITLE
Help does not work

### ISSUE THREAD

**Issue by jkomelj** [JabRef/jabref#578]
I have installed 32- and 64-bit JabRef 3.0 on 32- and 64-bit Windows 7 using relevant *.exe installation files. In both cases help does not work. There is no file ...JabRef-3.0.jar!/help/en/HelpHelp.html (see the error message in the attachment) and no help directory. I have found it in the *.zip version of the installation file and have copied it in the installation directory but the problem has not be resolved.

[HelpDoesNotWork.pdf](https://github.com/JabRef/jabref/files/71660/HelpDoesNotWork.pdf)

**Comment by koppor** [comment]
Could you please check version 3.1?

BTW, for quickly taking screenshots and dropping it into the issue tracker, we recommend [GrabNDrop](https://github.com/scyv/GrabNDrop/).

**Comment by jkomelj** [comment]
Help in both JabRef 3.1 versions does work on 64-bit Windows 7.
Thanks!
