### ISSUE TITLE
Allow to load customized css

### ISSUE THREAD

**Issue by thanever** [JabRef/jabref#5790]
Would reducing the height of the part shown in the figure below make appearance more coordinated?

<img width="958" alt="Capture" src="https://user-images.githubusercontent.com/17105777/71543784-2df26800-29b2-11ea-900c-fac6c9533b80.PNG">

**Comment by tobiasdiez** [comment]
Thanks for your suggestion. What do you mean in detail: reduce the size of the icons, or remove them completely?

**Comment by thanever** [comment]
Sorry for the confusion. What I mean is to reduce the height as shown in the figure below. 

<img width="846" alt="ccc" src="https://user-images.githubusercontent.com/17105777/71551507-3aafa400-2a24-11ea-947d-3e9e655b357d.PNG">

A comparison with the height of Google Chrome.  Thanks for your work.

<img width="334" alt="Capture1" src="https://user-images.githubusercontent.com/17105777/71551528-a98cfd00-2a24-11ea-9aa9-bf9764a558d9.PNG">

**Comment by urielz** [comment]
small detail but I agree with @thanever

**Comment by koppor** [comment]
Decision: 

- [ ] Offer editing of CSS
- [ ] Offer importing / exporting of CSS

We will tag as good first issue for newcomers and hope for contributions.

**Comment by tobiasdiez** [comment]
In a bit more detail, the following needs to be done:
- Add a possibility to specify a custom css file in the preference dialog.
https://github.com/JabRef/jabref/blob/2a5507fd3cb789398f66769bb6202bb450fb219d/src/main/java/org/jabref/gui/preferences/AppearanceTab.fxml#L30-L31
- The following code needs to be slightly modified to allow loading of external css files:
https://github.com/JabRef/jabref/blob/b6c266377ae157f0c922eda418c2c8a367c68fb2/src/main/java/org/jabref/gui/util/ThemeLoader.java#L62-L70

As a workaround, it is already possible to specify the css as a command line argument as described here:
https://github.com/JabRef/jabref/blob/b6c266377ae157f0c922eda418c2c8a367c68fb2/src/main/java/org/jabref/gui/util/ThemeLoader.java#L24-L35
This method should be properly documented by adding it with a bit more details to http://devdocs.jabref.org.

**Comment by nilsstre** [comment]
Hey, I would like to try to solve this issue 😃

**Comment by koppor** [comment]
Thank you for submitting a PR. While seeing the solution, we improved our specification. Maybe, you can work on finalizing the PR?
