### ISSUE TITLE
Rewrite ACM fetcher, because of ACM web site changes

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5804]
Test query: https://dl.acm.org/exportformats_search.cfm?query=%28%25252Bjabref%2520%25252Barchitectural%2520%25252Bchurn%29&within=owners.owner%3DGUIDE&expformat=bibtex

![grafik](https://user-images.githubusercontent.com/1366654/71647570-5acbb580-2cf9-11ea-8212-5f89e18efd2d.png)

Asked on twitter: 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">.<a href="https://twitter.com/TheOfficialACM?ref_src=twsrc%5Etfw">@TheOfficialACM</a> Your exportformats_search.cfm seems to be down. This feature was very useful and widely used in the web. Is it intended that it currently does not work? <a href="https://twitter.com/hashtag/opencitations?src=hash&amp;ref_src=twsrc%5Etfw">#opencitations</a> - example query: <a href="https://t.co/TOf3sgqvL1">https://t.co/TOf3sgqvL1</a></p>&mdash; Oliver Kopp (@koppor) <a href="https://twitter.com/koppor/status/1212520118179311616?ref_src=twsrc%5Etfw">January 1, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by koppor** [comment]
The fetcher has to be rewritten. See https://github.com/zotero/translators/pull/2101 vor some code ideas.

(Thank you @zuphilip for the pointer)

**Comment by koppor** [comment]
We need the ACM fetcher - or we need to drop it.

**Comment by JofielB** [comment]
Hello, is this issue still available? And if is available I would like to take it

**Comment by calixtus** [comment]
Go for it! :-) If you have questions, don't hesitate to ask at our gitter dev chat ( https://gitter.im/JabRef/jabref ). If you want to learn more about JabRef-programming in general have a look at our dev docs ( https://devdocs.jabref.org/ )

**Comment by JofielB** [comment]
Nice, I am gonna start working on it

**Comment by koppor** [comment]
Internal reference for JabRef developers: Implementation using the screen-scraping technology is available (privately) at https://github.com/NatashaDudi/jabref/blob/develop/src/main/java/org/jabref/logic/importer/fetcher/ACMPortalFetcher.java?rgh-link-date=2020-12-21T19%3A46%3A53Z.

@JofielB How are your implementation efforts going?

**Comment by koppor** [comment]
@JofielB Happy new year. May I ask for some progress regarding that issue?

You can get some inspiration from https://github.com/koppor/jabref/pull/476

**Comment by JofielB** [comment]
@koppor Hello and Happy new year. I am sorry for taking me so long to respond to this. I wasn't able to have any kind of progress and I am not pretty sure that I will be able to keep working on this issue.

**Comment by jvera701** [comment]
Hello, can I work in this issue ? I am new to open source software and want to contribute

**Comment by koppor** [comment]
@jvera701 After checking @JofielB's reply, it is very OK for you to try. Always keep test-driven development in your mind and try to use the "play" button in IntelliJ. See <https://www.jetbrains.com/help/idea/performing-tests.html> for details.

**Comment by jvera701** [comment]
I am sorry, I am replying this late but I couldn't make any substantial progress .and I am not sure I can continue working on this.. Writing this feature was harder than I first thought.

**Comment by XDZhelheim** [comment]
I think I got some clues.

Referring to https://github.com/zotero/translators/pull/2101, there is an API to query `bibtex` with DOI.

The format of URL is: `https://dl.acm.org/action/exportCiteProcCitation?targetFile=custom-bibtex&dois=<doi1>,<doi2>,...` (and encode it).
For example: https://dl.acm.org/action/exportCiteProcCitation?targetFile=custom-bibtex&dois=10.1145%2F3129790.3129810%2C10.1145%2F1961189.1961199. It's OK to open with browser.

The query result is a JSON file. And the `"items"` field contains `bibtex` citation. (Last part of the JSON file.)
![query_result_json](https://user-images.githubusercontent.com/57553691/117096318-41c68f00-ad9b-11eb-81a2-5fa269e1a93f.png)

After that, we can extract all the information needed from JSON.
 
But in the original fetcher, we use keywords to search, such as `jabref architectural churn` in the example given by @koppor. Therefore, the question is how to get a paper's DOI by its title. I have no idea now.

Hope this can give help.

**Comment by Ryyyc** [comment]
One solution is to get the DOI from the HTML results of the search page, then use the export interface to get the JSON format data, and finally parse them.

Search API: https://dl.acm.org/action/doSearch?AllField=<queryString>
Export API: https://dl.acm.org/action/exportCiteProcCitation?targetFile=custom-bibtex&format=bibTex&dois=<doi>,<doi>,...

**Comment by XDZhelheim** [comment]
> One solution is to get the DOI from the HTML results of the search page, then use the export interface to get the JSON format data, and finally parse them.
> 
> Search API: https://dl.acm.org/action/doSearch?AllField=
> Export API: https://dl.acm.org/action/exportCiteProcCitation?targetFile=custom-bibtex&format=bibTex&dois=,,...

Yes, I have tried. The difficulty is how to build a script to get DOI from the web page. ACM digital lib uses some anti-crawler techniques.

**Comment by Ryyyc** [comment]
> Yes, I have tried. The difficulty is how to build a script to get DOI from the web page. ACM digital lib uses some anti-crawler techniques.

<br>

I used a browser and curl for testing. The browser access is all normal. The curl response requires cookies, so the cookie should be included in the request.

```bash
C:\Users\ruan>curl https://dl.acm.org/action/doSearch?AllField=lidar
The URL has moved <a href="https://dl.acm.org/action/doSearch?AllField=lidar&cookieSet=1">here</a>
```

**Comment by XDZhelheim** [comment]
Nice work.

But if I remember correctly, the old ACM fetcher searches in "ACM Guide to Computing Literature", which means the query URL is https://dl.acm.org/action/doSearch?AllField=lidar&expand=all

**Comment by Ryyyc** [comment]
> Nice work.
> 
> But if I remember correctly, the old ACM fetcher searches in "ACM Guide to Computing Literature", which means the query URL is https://dl.acm.org/action/doSearch?AllField=lidar&expand=all

Thank you for your reminder, but I did not find this in the original code file.
Maybe we need a little help from @koppor .
