### ISSUE TITLE
Command line operations result in java.nio.file.InvalidPathException

### ISSUE THREAD

**Issue by rlkamalapurkar** [JabRef/jabref#5813]
When I try to do an HTML export using command line, that is,

`C:\"Program Files"\JabRef\jabref.exe -o C:\FilePath\scc.html,sccList -i C:\FilePath\scc.bib -n -console
`

I get the error 

> java.nio.file.InvalidPathException: Illegal char <:> at index 29: Files\JabRef\jabref.exe  -o C:\FilePath\scc.html

The `FilePath` does not have any spaces, and is comprised entirely of uppercase and lowercase letters. The same command works without any issues if I use JabRef 4.3.1.

On Jabref 5.0, the same .bib file exports correctly to HTML using the same export filter if I use the GUI instead of the command line.

**Comment by calixtus** [comment]
Hi @rlkamalapurkar , tank you for your bug report. I was just taking a look into it. I had some trouble understanding the command line option: as "sccList" is not recognized as an exporter. Can you clearify this a bit and provide some more information about what exporter you want to use?
Does JabRef provide a stacktrace of the error?
