### ISSUE TITLE
Error when messing up bibtex

### ISSUE THREAD

**Issue by cbontoiu** [JabRef/jabref#5820]
Hello,
Here is a deadlock error which happened to me while pasting a bibtex entry next to en existing one. A warning appears as shown in the picture but the user cannot close it as it keeps reopening. I had to search the JabRef process in Linux and kill it.

This happened for version5.0 beta 1 in Linux.
Regards,
Cristian

![Screenshot_2020-01-07_11-36-41](https://user-images.githubusercontent.com/7108691/71893581-fcad3100-3143-11ea-862e-8bed77f18a77.png)

**Comment by calixtus** [comment]
Hi, I encountered this problem also once. It's not really locked, but a real bunch of error messages (one for every letter?). You can close all those dialogues, but it takes some time. But in the end you should be able to save your changes.

But I can confirm this issue.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
