### ISSUE TITLE
Autolinked pdf: icon not shown

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#5831]
JabRef 5.0-beta.342--2020-01-15--58709e7
Linux 4.9.0-11-amd64 amd64 
Java 13.0.2

When JabRef finds automatically the pdf of a reference in the file directory, the icon is not shown in the main table, and the link does not appear in the BibTeX source.

1. Create a new file
2. In the main file directory (defined in Options -> Preferences -> File -> External file links), put a file named test20.pdf
3. Create a new article entry 
4. set the bibtexkey as "test20"
5. go to the "General tab"
    The linked file appears in the file field:
![Capture du 2020-01-15 14-34-35](https://user-images.githubusercontent.com/6931104/72438004-44673480-37a4-11ea-8203-08ce84cc3faa.png)
  In the BibTeX source tab, the file field is absent:
![Capture du 2020-01-15 14-39-51](https://user-images.githubusercontent.com/6931104/72438351-eab33a00-37a4-11ea-964e-4e911055d21a.png)
 In the main table, the file link icon is absent:
![Capture du 2020-01-15 14-37-00](https://user-images.githubusercontent.com/6931104/72438138-81cbc200-37a4-11ea-870e-f924425d06c0.png)

Note: log file is empty

**Comment by Siedlerchr** [comment]
Are you aware that you have to click on the icon in the tab to "accept" the file?

**Comment by mlep** [comment]
No, I did not know. Completely not obvious!

Why do I have to click? If a confirmation was needed, I would have expected a message to be prompted.

**Comment by Siedlerchr** [comment]
The Autolink in the entry editor/general tab is just a "suggestion".  The user has to click the briefcase icon to confirm the choice. There should also be a tooltip. Unfortunately, our existing help/user documention at docs.jabref.org is out of date.
We don't add it automatically as it could overwrite another previously existing file of the user.
This feature has been at leat since late of v4. or early development of v5 implemented in JabRef.

**Comment by mlep** [comment]
I realize I had the same issue with JabRef 4.0. And since all that time I did not know about this briefcase icon...

To me, prompting a message would be better than documentation.
And if no previously-existing link is present in the entry, there is no risk at overwriting anything. So the link could be added without prompting anything.

**Comment by tobiasdiez** [comment]
I agree that the briefcase icon is not self-explanatory and the UI in this regard needs improvement. This is however already tacked in https://github.com/JabRef/jabref/issues/3607.

**Comment by mlep** [comment]
Thanks for pointing to issue #3607! (I did not find it...)
