### ISSUE TITLE
"New Group" > "Specified keywords" > "Generate groups for author last names" not working properly

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5833]
When selecting "New Group" > "Specified keywords" > "Generate groups for author last names", providing any group name, entering "author" in the field "Field to group by" and clicking "OK", then hardly any (or even none) of the generated groups with the authors' last names have entries in it. Most badges have the value 0.

I'm using the latest JabRef 5 master build on Ubuntu 16.04.

![image](https://user-images.githubusercontent.com/3658393/72471460-050c0880-37e3-11ea-972b-953820fb8631.png)

**Comment by systemoperator** [comment]
Issue still persists. Description has been updated.

**Comment by Siedlerchr** [comment]
Seems like JabRef creates group for the first name as well, but only fills the ones for the last names. I don't really understand how it's working

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Should I look at it as part of the solution to #6394? I haven't looked at the details of this one but it would surprise me if it does not have overlap with the issues I am having updating the count badge and refreshing the content.

The scope of #7173 keeps expanding "naturally" anyway 😧

**Comment by systemoperator** [comment]
@k3KAW8Pnf7mkmdSMPHz27 If you find some time, it would be great.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
There are multiple issues with getting this working properly and they are unfortunately not connected to #6394 so I won't continue with it for now, but these are my notes for now

1. The first problem is the use of `KeywordListSearchStrategy` in `WordKeywordGroup`, this means that any author with a "," before/after the last name is ignored (e.g., `Turing, Alan` should not be listed under "Turing")
    1. This particular issue can be relieved by using `StringSearchStrategy` but then other parts of the name will be matched as well, not only last names
    2. I believe there are issues where names containing latex also doesn't work, but I have not confirmed it (e.g., `Gödel` ≠ `G{\"{o}}del`)
        3. Is there a drawback to `KeywordList` being latex-free? (I don't remember how the global search deals with this issue)
2. The use of `BibEntry#getLatexFreeField` is not going to work in all cases (e.g., institutes)
3. #7129 should also be a problem in this issue (I have not confirmed this either)

If there is a point to making the "groups for author last names" slightly more accurate, switching to "StringSearchStrategy" is done by changing a boolean value. But it does not make the group work "properly".
