### ISSUE TITLE
Menu item 'Copy DOI link' no more visible/accessible

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#5835]
JabRef version JabRef 5.0-beta.342--2020-01-15--58709e7 Linux 5.3.0-26-generic amd64 Java 13.0.2 on Ubuntu 19.10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. The "Copy DOI link" (actually the whole context menu for the URL column) is no more visible/accessible in  the entry list
2. Also can't find this menu item under "Copy ..." (where I thought it went after migrating from JR 4 to 5)
3. The menu entry "Copy -> Copy bibtex key and link" does not seem to copy anything to the clipboard. The validation message anyway shows that only the key was copied.

This is probably not a bug but I thought it is tiny enough to include it as an issue.

**Comment by PremKolar** [comment]
Hi, I would like to try and fix this.
