### ISSUE TITLE
Improve Ranking column feature in main table

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#5842]
Unranked papers can currently only be ranked through the context menu, unlike read status, relevance, priority, and quality which can be directly toggled. However, after the first ranking, the star bar is shown in the entry list and can be toggled as usual. Although I realise that "empty star bar" = 0 stars and "unranked" are two different states. Following the logic of the other classification attributes, one could just treat these two states as equal, btw tools such as Rythmbox (a GTK-based media player) also handle it like this.

Otherwise, I consider this issue as closable.

_Originally posted by @ytzemih in https://github.com/JabRef/jabref/issues/5834#issuecomment-575527597_

**Comment by castro-truelogic** [comment]
Any news about this feature?

**Comment by calixtus** [comment]
I'm looking into it.

**Comment by calixtus** [comment]
For those who maybe work on that:
You could also change the graphic style of the stars by css (see https://github.com/controlsfx/controlsfx/blob/jfx-13/controlsfx/src/main/resources/org/controlsfx/control/rating.css )

**Comment by calixtus** [comment]
This should provide a quick start on the changes necessary: https://github.com/JabRef/jabref/compare/main...koppor:fix-5842
