### ISSUE TITLE
Bug report : not just for bugs anymore

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#5845]
When starting a bug report, this frame contains the following text:

> Note: Please use the GitHub issue tracker only for bug reports. 
> Feature requests, questions and general feedback is now handled at http://discourse.jabref.org.
> Thanks! 

This is not true anymore, since, when you start a new issue, you get to the following options:

![Capture du 2020-01-18 17-09-15](https://user-images.githubusercontent.com/6931104/72666747-74693e80-3a15-11ea-9751-8c79c5568751.png)

Hence, the text should be modified.

**Comment by tobiasdiez** [comment]
This issue tracker is still only used for bug reports and minor suggestions for improvement. The other two types will refer you to discourse.jabref.org. We felt that this way is more welcoming for new users, which are not aware of the different purposes of this issue tracker vs the forum.
