### ISSUE TITLE
Changing settings in "Options" > "Manage external file types" has no effect

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5846]
I'm using JabRef 5 master build (JabRef-5.0-portable_linux.tar.gz, JabRef 5.0-beta.342--2020-01-15--58709e7, Linux 4.4.0-171-generic amd64 Java 13.0.2) on Ubuntu 16.04.

1. Click "Options"
2. Click "Manage external file types"
3. Click pencil edit icon
4. change some values
5. Click "OK"
6. Result: The changed settings are lost.

Whenever changing some settings in step 4 and clicking "OK", the settings will not be stored: The shown table is not being updated and when clicking the same pencil edit icon once again, the original, unchanged settings appear once again.

In my case, I especially wanted to assign a specific pdf reader/editor solely for JabRef (which should be different to the default pdf reader on my system), but setting a different one could not be accomplished.

At this point I would like to reference an already mentioned issue, which is related to setting a different pdf reader/editor: "Open PDF options" #5529 Nevertheless, this referenced issue is about a different dialog in JabRef.

In my opinion, it should really be possible to assign user-specific programs to given file types and not relying on the system's settings. This allows important program-specific personalization.

**Comment by systemoperator** [comment]
I have looked into this issue for quite some time now. Maybe someone can give me some hints in the code.

When I click `Options` > `Manage external file types`, then 

        ViewLoader.view(this)
                  .load()
                  .setAsDialogPane(this);

gets called in `CustomizeExternalFileTypesDialog.java`.

When some settings get submitted by clicking the `OK` button, then 

        this.setResultConverter(button -> {
            if (button == ButtonType.OK) {
                viewModel.storeSettings();
            }
            return null;
        });

gets called in the same file.

My questions are:

1. How can I refresh the content of the table, when I edit an existing default file type?
2. Where exactly are the default file types stored, when a different program gets associated?
2.1. Changing some settings of the default file types will currently not be stored in `prefs.xml`. This is an issue, right?
3. Where is the code for saving all settings to `~/.java/.userPrefs/org/jabref/prefs.xml`?

Maybe someone can give me some hints in general about this issue.

**Comment by Siedlerchr** [comment]
Hi,
thanks for your ongoing interest in JabRef
I will try to answer your questions:
3. ) org.jabref.preferences JabRefPreferences/PreferencesService:  Jabref uses the java Preferences mechanism. On Windows it will store the settings in the registry, on linux in that path.

1+ 2.) You probably need to return the edited item from the EditExternalFileTypeEntryDialog in the class
CustomizeExternalFileTypesViewModel and add it to the ObservableList. As the name implies, the ObservableList is a speciality in JavaFX, it automatically notifies any subscribers of new content. As the table is bound (aka subsribed) to the list, it wil be updated automatically.

The method for showing the dialog is showEditDialog and it doesn't return the modified object.
And from a quick look it seems like you are right, modifications are nowhere saved.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
