### ISSUE TITLE
Add tooltips for all fields in the entry editor

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5847]
Since there are many different entry fields in the entry editor, it would be useful, if every field provided some tooltip when hovering a field or some tooltip which can be clicked next to the entry field.

**Requirements:**
- A tooltip should contain detailed information for what this field is used.
- A tooltip should describe which type of information should be entered into a field.
- A tooltip should describe the required input format for the input field. In some cases different input formats are possible.
    - example: `pages`: `One or more page numbers or range of numbers, such as 42-111 or 7,41,73-97 or 43+ (the ‘+’ in this last example indicates pages following that don’t form a simple range). BibTEX requires double dashes for page ranges (--).`
- Some dedicated input examples should also be listed, since examples are very intuitive and very easy to understand.
- It should be mentioned whether the field is optional or not. Sometimes also only one out of several input fields is required (example: `author` or `editor` in biblatex entry type `@Misc`).
- The information within a tooltip should be self-contained, without the need to look up other external documents and without being linked to other entry fields.
- It should be implemented for all provided entry fields in the entry editor, also considering other tabs like `Optional fields`.
- Depending on, whether bibtex or biblatex is enabled, different input fields are visible and the tooltip should depend on whether bibtex or biblatex is active.

If more information gets added to the tooltips, maybe the information could be structured in sections, split with new lines. Maybe extended tooltips are possible, which allow formatting texts using e.g. bold, underline, italic, etc.

Some (incomplete) inspiration:
- https://www.andy-roberts.net/res/writing/latex/bibentries.pdf
- https://www.openoffice.org/bibliographic/bibtex-defs.html
- http://bib-it.sourceforge.net/help/fieldsAndEntryTypes.php
- http://tug.ctan.org/info/biblatex-cheatsheet/biblatex-cheatsheet.pdf

**Comment by lglopezh** [comment]
Hello! I think I can do this, can I contribute? I´m totally new to open source projects.

**Comment by systemoperator** [comment]
Hello! Yes, that would be great! :)

**Comment by lglopezh** [comment]
Thanks! I'm reading the Guidelines, I want to start ASAP

**Comment by lglopezh** [comment]
When trying to run from intelliJ i got this error: Could not target platform: 'Java SE 13' using tool chain: 'JDK 11 (11)'.

**Comment by systemoperator** [comment]
A library can be configured with either bibtex or biblatex.

You might find the following documents useful:
- entry types in biblatex: http://mirror.easyname.at/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf (p. 8ff, 2.1 Entry Types)
- entry types in bibtex: http://mirror.kumi.systems/ctan/biblio/bibtex/base/btxdoc.pdf (p. 3ff, 3.1 Entry Types)

**Comment by lglopezh** [comment]
Thanks!

**Comment by lglopezh** [comment]
Sorry guys! I can't find where all fields are created, my progress is practically zero.

**Comment by lglopezh** [comment]
Oh! Someonde did it already.

**Comment by tobiasdiez** [comment]
Thanks to @ShikunXiong this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

@lglopezh Don't be too upset! We have a bunch of nice issues that are just waiting to be attacked: https://github.com/JabRef/jabref/labels/good%20first%20issue

**Comment by lglopezh** [comment]
I'm not upset, hehe.

Let me see other issues, thanks.
