### ISSUE TITLE
Idea: Use Zotero's connectors for fetching data in general

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5848]
This is just an idea:

Zotero's connectors (https://github.com/zotero/zotero-connectors) are very advanced and they work very well. Maybe it would be a good idea to create an interface to use Zotero's connectors, if this is possible? This would also have the benefit to fetch google.scholar's data without any limit, since the data would be fetched via an offical web browser.

**Comment by Siedlerchr** [comment]
We already have the JabRef extension for Firefox and Chrome which usese the thing from zotero.
 https://github.com/JabRef/JabRef-Browser-Extension

**Comment by systemoperator** [comment]
Oh great, now the addon finally works for Firefox Quantum as well. :) I've just installed and configured it. It works great! Thanks for pointing it out!
