### ISSUE TITLE
Retrieve and show (e.g. google scholar's) citation count for each table entry

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5849]
In Zotero it is possible to show the citation count for each table entry. It would be great, if this would be possible in JabRef as well! Zotero automatically retrieves the current citation count and adds it to a new entry.

**Comment by tobiasdiez** [comment]
How is the update of the citations handled in Zotero (e.g. I added an entry 5 years ago, and since then it was cited again)?

**Comment by systemoperator** [comment]
To be more precise, it's a Zotero addon, which allows fetching citation counts. It's called "Zotero Scholar Citations" ([https://github.com/beloglazov/zotero-scholar-citations](url)).

On initial import of a reference, the current citation count is fetched from Google Scholar and currently inserted into a field, called "extra". Furthermore, it allows batch updating several citations by firstly selecting them and then triggering the update, since they may change over time.

**Comment by systemoperator** [comment]
Can JabRef send requests to the JabRef-Browser-Extension?

**Comment by koppor** [comment]
Prevoius feature request: https://github.com/koppor/jabref/issues/168

**Comment by koppor** [comment]
To repeat https://github.com/koppor/jabref/issues/168#issuecomment-542045720:

The database mentioned at https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000385 could be helpful (via https://twitter.com/egonwillighagen/status/1183974415534559234)

**Comment by koppor** [comment]
No time on work on this.
