### ISSUE TITLE
Required fields in entry editor are incomplete

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5853]
I have looked at the different entry types of biblatex in [http://mirror.easyname.at/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf](url) (p. 8ff, 2.1 Entry Types). Here, I have observed that some entry types define that either the entry field "year" or "date" (year/date) is required. Contrarily, JabRef only shows the entry field "date" as required. The entry field "date" is only shown in "Other fields". This can confuse some users.

**One example:**

Entry type: article
biblatex: Required fields: author, title, journaltitle, **year**/date
JabRef shows the following entry fields as required: author, title, journaltitle, date

This could also lead to a problem, when pasting references, where only `year={yyyy}` is set.

Maybe it could be defined more clearly in the required fields, that either the field "year" or "date" is required. (Of course I see, that the date also includes the year.)

Affected entry types are:

article, book, mvbook, inbook, booklet, collection, mvcollection, incollection, dataset, manual, misc, online, patent, periodical, proceedings, mvproceedings, inproceedings, report, thesis, unpublished

Furthermore, for the entry types:

- "misc" the following is defined as required: author/**editor**, title, year/date
  - But in JabRef required are: author, title, date
- "online" the following is defined as required: author/**editor**, title, year/date, **doi/eprint**/url
  - But in JabRef required are: author, title, date, url

**Comment by Siedlerchr** [comment]
@systemoperator 
Are you sure you have your library in biblatex mode?

Year + month are aliases to the field date. JabRef can interpret date from year + month and also the other way round to some extend. Not all biblatex date formats can be entered atm. See #2753 
Therefore it's only necessary to show the date field. And biblatex is backwards compatible see section §2.3.9.

author/editor: Those are both present:
![grafik](https://user-images.githubusercontent.com/320228/72748659-23de1680-3bb8-11ea-90d9-3944c06602e0.png)

And JabRef has also special logic to serialize them and parse them.
You can see all EntryType/Field related defintions in JabRef here:
https://github.com/JabRef/jabref/tree/master/src/main/java/org/jabref/model/entry

**Comment by systemoperator** [comment]
@Siedlerchr Yes, I have biblatex mode enabled: I have set it for the current library as well is in the JabRef settings in general ("Default bibliography mode").

I'm using the latest JabRef 5 master build (JabRef-5.0-portable_linux.tar.gz, JabRef 5.0-beta.357--2020-01-18--6319d05, Linux 4.4.0-171-generic amd64, Java 13.0.2) on Ubuntu 16.04.

Concerning the entry type misc, there is no Editor field visible:

![image](https://user-images.githubusercontent.com/3658393/72749281-ef6b5a00-3bb9-11ea-8994-9051ed972e09.png)
