### ISSUE TITLE
Problem with Angstrom symbol in LaTeX notation

### ISSUE THREAD

**Issue by PUKK** [JabRef/jabref#586]
Hi,

After installing JabRef 3.1 I suddenly got several complaints about entries when loading my default database. Apparently I do have several entries with "\AA{}", i.e., the Latex version of "Angstrom" in my database which cause this problem. In some of the entries this actually is written as "\{AA}" which to my knowledge is not correct in LaTeX. Having a look at an 2.11 version of my database, this "\{AA}" was there already and did not cause any problem. I did fix the issue in emacs replacing "\{AA}"  by "\AA". No problem on loading the fixed version of the database BUT after saving the database again, some of the "\{AA}"  were back, causing again errors the next time opening the database again. Unfortunately this bug makes this version of JabRef unusable for me at the moment.

Example entry:
@Article{abra94,
  Title                    = {{S}tructure at 2.8 \{AA} resolution of {F}$_1$-{ATP}ase from bovine heart mitochondria},
  Author                   = {{J}. {P}. {A}brahams and {A}. {G}. {L}eslie and {R}. {L}utter and {J}. {E}. {W}alker},
  Journal                  = {{N}ature},
  Year                     = {1994},
  Pages                    = {621--628},
  Volume                   = {370},
  Pmid                     = {8065448}
}

**Comment by oscargus** [comment]
I cannot reproduce this. Both entries

@Article{abra94,
  author =    {{J}. {P}. {A}brahams and {A}. {G}. {L}eslie and {R}. {L}utter and {J}. {E}. {W}alker},
  title =     {{S}tructure at 2.8 {\AA} resolution of {F}$_1$-{ATP}ase from bovine heart mitochondria},
  journal =   {{N}ature},
  year =      {1994},
  volume =    {370},
  pages =     {621--628},
  pmid =      {8065448},
  timestamp = {2015.12.26}
}

and my "clean" version

@Article{abra94a,
  author =    {J. P. Abrahams and A. G. Leslie and R. Lutter and J. E. Walker},
  title =     {Structure at 2.8 {\AA} resolution of {F}$_1$-{ATP}ase from bovine heart mitochondria},
  journal =   {Nature},
  year =      {1994},
  volume =    {370},
  pages =     {621--628},
  owner =     {Oscar},
  pmid =      {8065448},
  timestamp = {2015.12.26}
}

reloads just as is.

I would guess that there's a preference issue here, but someone else can probably answer it better.

**Comment by PUKK** [comment]
Looks like \AA in a title is written as \{AA} on saving (at least for me).  Tried to play with "Preferences -> Advanced -> Add {} to specified title words on search to keep the correct case". But changing this option has no effect though my guess is that the problem is located here. 

BTW, other options also seem not to work properly such as "Preferences -> General -> Mark entries imported into an existing database" or "Unmark all entries before importing new entries into an exisitng database"

**Comment by stefan-kolb** [comment]
@PUKK Did you try to reset the preferences? Should be possible inside the preferences dialog for the newest version now. Please try http://builds.jabref.org/master/

**Comment by PUKK** [comment]
Resetting preferences solves the issue.

Thanks for all your fabulous work on JabRef!
