### ISSUE TITLE
Printed  in keyword vs printed; The libary has been modified by another program

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#5884]
JabRef version  on 

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. open 
```bib
@Article{pearlman1995amber,
  author    = {Pearlman, David A. and Case, David A. and Caldwell, James W. and Ross, Wilson S. and Cheatham III, Thomas E. and DeBolt, Steve and Ferguson, David and Seibel, George and Kollman, Peter A.},
  journal   = {Computer Physics Communications},
  title     = {{AMBER}, a package of computer programs for applying molecular mechanics, normal mode analysis, molecular dynamics and free energy calculations to simulate the structural and energetic properties of molecules},
  year      = {1995},
  issn      = {0010-4655},
  month     = sep,
  number    = {1-3},
  pages     = {1-41},
  volume    = {91},
  day       = {2},
  doi       = {10.1016/0010-4655(95)00041-D},
  file      = {:PhDJK/Literature/MD/DNA/Pearlman_Case_Caldwell_Ross_CheathamIII_DeBolt_Ferguson_Seibel_Kollman_1995_ComputerPhysicsCommunications.pdf:PDF},
  groups    = {MD_DNA, AnCH, AnKahl, parmbsc, AMBER_DNA, Potential},
  keywords  = {Molecular mechanics, Molecular dynamics, Normal modes, Free energies, Computer simulations, printed},
  publisher = {Elsevier},
}
```
2. open file
3. The library has been modified by another program, similar message to  #4877 (but different reason?)
4. View changes
5. ![Screenshot from 2020-01-28 13-53-25](https://user-images.githubusercontent.com/15687581/73265922-2b17ac80-41d6-11ea-8992-bbb9a18211bf.png)

<details>
  <summary>Log File</summary>
  
![Screenshot from 2020-01-28 13-59-54](https://user-images.githubusercontent.com/15687581/73266100-80ec5480-41d6-11ea-8596-d8229db8fe26.png)

</details>

**Comment by JoKalliauer** [comment]
This also occures with:
 - printed
 - ranking
 - readstatus

![Screenshot from 2020-01-28 14-07-32](https://user-images.githubusercontent.com/15687581/73266752-d2491380-41d7-11ea-9b4b-a022b4dd6ea4.png)

All three fields are not displayed:
![Screenshot from 2020-01-28 14-12-55](https://user-images.githubusercontent.com/15687581/73267011-64e9b280-41d8-11ea-8bc8-7309419fd46f.png)
![Screenshot from 2020-01-28 14-13-04](https://user-images.githubusercontent.com/15687581/73267014-687d3980-41d8-11ea-86a5-d7880a6ae548.png)

**Comment by Siedlerchr** [comment]
@JoKalliauer  You have the option activated "Synchronize with keywords" under special fields activated.
So JabRef sees the keyword "printed" and extracts that to the field printed.
You could  change it to separate fields

**Comment by JoKalliauer** [comment]
@Siedlerchr : This might solved my problem, I'm closing this issue (and reopen if it persists)
