### ISSUE TITLE
Use the preference help messages to clarify which directories are searched for file links

### ISSUE THREAD

**Issue by joelostblom** [JabRef/jabref#5891]
I couldn't figure out why "Automatically set file links" was taking so long until I found [this comment](https://github.com/JabRef/jabref/issues/5105#issuecomment-508959559) mentioning that the directory where the `.bib` database is located is being searched recursively (which was my home directory because I am just getting start with jabref). This was surprising to me since I had "Use the BIB file location as the primary file location" unchecked and had specified a directory to search manually.

It would be helpful if it was displayed in the preferences file tab (maybe via hover messages) which directories are being searched so that it is clear to the user. Changing the location of the bib file did not only improve the performance of "Automatically set file links", but the general snappiness of JabRef and makes my CPU spin up less often. These attributes are quite important for the overall impression of the program, so some sort of indication recommending not to use a very large file tree could also be valuable.

**Comment by silverhorse** [comment]
I want to contribute to jabref as first contribution. I looked at this issue and it appears there is a bug - when the "Use the BIB file location as primary file directory" is unchecked and a directory is explicitly provided, search is still taking time to complete even though the provided directory is empty. Is this a known issue? It seems the file location's directory is still being searched, which contains lots of files and directories leading to long search time.

**Comment by Siedlerchr** [comment]
@silverhorse  Thanks for your investigation. That sounds like a bug.  You can check the code, the relevant methhods should be `getFileDirectoriesAsPaths` in BibDatabaseContext and `getFirstExistingFileDir`
And the method which does the search should be in FileUtil, method "find"

**Comment by silverhorse** [comment]
@Siedlerchr thanks for replying. I looked at the code and it seems the BIB file directory is always added for search, even though the checkbox is not clicked. If the checkbox is clicked, it is added at first position in list of directories to search, otherwise it is added at last position. So, I want to confirm the default behaviour of "Automatically set File links" feature. Is it supposed to always search in the BIB file location directory? OR Should we skip the file's directory only when main file directory is provided, otherwise there will be no directory to search.

**Comment by Siedlerchr** [comment]
I would say, only search in the bib location directory  when the checkbox is checked. 
And when it's checked it takes precedence over all other directories.
The library and user specific file directories can be set in the library properties.

**Comment by silverhorse** [comment]
@Siedlerchr I will focus on fixing the bug then and float a PR.

**Comment by silverhorse** [comment]
@Siedlerchr I have created a draft PR. Its WIP and I need to make sure all testing passes as mentioned in documentation. However, it would be great if you could see the changes I have done and point out anything to lookout for. Thanks to @koppor who has commented on the sensitivity of these changes already.

**Comment by Siedlerchr** [comment]
thanks to @silverhorse  and @abadar this issue is now fixed.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
