### ISSUE TITLE
Except for the "Title" column, columns in main table view are not displayed anymore

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5898]
JabRef 5.0-beta.388--2020-01-29--eb988b6
Windows 10 10.0 amd64 
Java 13.0.2

In the current developer version of JabRef the columns in the main are not displayed anymore, the only exception being the "Title" column.

![Untitled](https://user-images.githubusercontent.com/12767489/73436804-1573c580-4343-11ea-9e1b-37cddbbacec5.png)

Just for reference, here also the preferences for the entry table:

![Untitled2](https://user-images.githubusercontent.com/12767489/73436959-5f5cab80-4343-11ea-973f-4dff8a6f1ab0.png)

**Comment by Siedlerchr** [comment]
I'm sure they are there, they just might be "hidden" at the right border because the title column takes all space. Try resizing them at the "invisible" border between the two columns

**Comment by AEgit** [comment]
Oh, you are right! As a follow-up, though, there is still a bug there (which I noticed already some time ago, but never found the time to report):

The re-sizing of the columns does not seem to work properly:

1. Resize the columns to make them visible.
2. Resize the JabRef window itself (for example make it fullscreen)
3. The columns that were previously visible are invisible again - only the title column is visible
4. If you bring the JabRef window back to the original size, the columns are still invisible
5. This means, that any change to the size of the JabRef window will immediately lead to most columns becoming invisible/hidden

I reckon this issue might be connected:
https://github.com/JabRef/jabref/issues/5872

Maybe this commit is connected as well (?):
https://github.com/JabRef/jabref/pull/5730

**Comment by tobiasdiez** [comment]
This is indeed very tightly connected to #5872. In fact, I believe it's a duplicate (in the sense that a fix for #5872 will likely resolve this issue as well).
