### ISSUE TITLE
Umlaute while adding entries via DOI

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5900]
Please try to add an entry by DOI with 10.1007/s16024-020-00337-5 and look in the title.

The `ä` in "Technikaffinität" is misshandeld and appears as a black ? in JabRef (dev version 5.* on Windows 10).

**Comment by Siedlerchr** [comment]
Seems like a similar problem to #5899

**Comment by AEgit** [comment]
Yes, I think this issue is a duplicate of https://github.com/JabRef/jabref/issues/5899. See also https://github.com/JabRef/jabref/issues/5899#issuecomment-580658891

**Comment by Siedlerchr** [comment]
Could you please try the latest snapshot?
http://builds.jabref.org/master/

**Comment by AEgit** [comment]
JabRef 5.0-beta.409--2020-02-09--6a9c915
Windows 10 10.0 amd64 
Java 13.0.2

The issue persists.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
On Debian 10 the issue seams to be fixed.
