### ISSUE TITLE
Changing entry type does not work when biblatex source is shown

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#5905]
I am using the latest JabRef 5 master build:
Java 13.0.2
on Ubuntu 16.04

**Steps to reproduce the behavior:**

1. Double click an entry in the main table (with e.g. entry type "Article")
2. Open tab "biblatex source"
3. Change entry type via the dropdown menu to a different entry type (e.g. entry type "Misc")

_Observation:_ Commonly, the entry type will not change in the biblatex source and will not be updated in the main entry table.

I think in seldom cases the biblatex source has been updated as expected, but I could not reproduce this intended behavor anymore.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by systemoperator** [comment]
@tobiasdiez I have tested it. It seems there is still some issue left. Apparently, the first time the entry type gets changed, it does not get changed. (Subsequent changes seem to work.)

**Problem case:**

1. Close JabRef (to make it easier to reproduce)
2. Start JabRef
3. Open Library (or use an already auto-opened Library)
4. Select an entry in the main table
5. Open tab "biblatex source"
6. Change entry type via the dropdown menu to a different entry type

_Observation:_ The entry type will not change in the biblatex source and will not be updated in the main entry table and the library is indicated as "modified" (*).

_Verification:_

a.) Save library with CTRL+S.
b.) Close Library
c.) Open Library
d.) Previous (old) entry type is shown.

If after step 6. the entry type gets changed at least another time (so at least twice) then it works.

This behavor can also be reproduced with another (untouched!) entry in the main table.

**Comment by calixtus** [comment]
This is really strange. Why is just the first one failing? I'm reopening this Issue.
Thanks for testing anyways.

**Comment by Siedlerchr** [comment]
Does closing/reopening the entry editor help?

**Comment by systemoperator** [comment]
Closing/reopening the entry editor does not help.

**Comment by calixtus** [comment]
I tried to triangulate the problem a bit.
Changing the entry type wont work the first time (but it does from the second time on), but only in the source tab AND if you did not change the entry type from another tab before.
This is getting really obscure...

**Comment by Siedlerchr** [comment]
Thanks to @dawidm  this issue is now fixed
