### ISSUE TITLE
keystrokes in editor very slow; "library has been modified" still popping up

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5912]
JabRef version

JabRef 5.0-beta.399--2020-02-02--06f2c18
Linux 5.3.0-28-generic amd64 
Java 13.0.2

The slow keystroke problem below occurs on a Thinkpad T560 with 8MB RAM and a SSD drive with 6GB free. It does not occur on a Thinkpad T580 with same RAM and a bigger SSD drive.

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. open Jabref and go to editor tab
2. type a character
3. it takes between four and nine seconds for the character to appear.
4. on saving, the "library has been modified" message still appears.

See the screen video link below.  The date was typed into the date field as soon as the cursor was in that field, and the backspace delete key was hit four times as soon as the date appeared.

- [video screen capture](https://www.dropbox.com/s/47ztoxymtk2r4dq/jabref-screen.mp4?dl=0) 

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by PorcelainMouse** [comment]
This also seems very similar to my issue. I think these are probably all related, but the match isn't exact.

**Comment by koppor** [comment]
The issue of @PorcelainMouse is https://github.com/JabRef/jabref/issues/5919.

**Comment by PorcelainMouse** [comment]
I may have overstated the similarity.  It could be related, but I have many other symptoms besides slowness. My slowness quickly escalates to full system lock-up.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
