### ISSUE TITLE
Add support for Neovim(-remote) as external editor

### ISSUE THREAD

**Issue by mxxhaupt** [JabRef/jabref#5957]
Neovim is a popular alternative to the traditional Vim. However, the lack of the "--servername" option in recent versions of Neovim makes JabRef's integration of vim incompatible with Neovim, although Neovim-Remote provides basically the same functionality. 
An implementation of Neovim support should not be a difficult task and I would appreciate it.

**Comment by xolotl90** [comment]
You can just specify the path to your _nvr_ executable which features the _--servername_ option. This way Neovim just behaves like Vim8. Be sure that your _nvr_ executable can be found by JabRef and is not sourced somehow in your .bashrc.

**Comment by koppor** [comment]
@mxxhaupt Does the solution by @xolotl90 solve your issue? You are very welcome to enhance our user documentation (FAQ?) at https://github.com/JabRef/user-documentation/blob/master/en/README.md.

@mxxhaupt You could also work on the source code, if you want. 🎉
