### ISSUE TITLE
Don't bundle dependencies if a package manager is used

### ISSUE THREAD

**Issue by KOLANICH** [JabRef/jabref#5959]
Instead proper metadata should be set to enable autoinstallation of the needed packages and proper scripts (packaged as packages) should be used for classpath discovery.

**Comment by koppor** [comment]
I understand that you are referring to our `.deb` and `.rpm` packages.

Regarding Debian, please support us at https://github.com/koppor/jabref/blob/master/jabref-in-debian.md.

Regarding RPM, please become a maintainer for a proper RPM package.

Until that, we need to stick with the self-contained archives produced by [jpackage](https://jdk.java.net/jpackage/).

Please reopen the issue if I understood something wrong from your descrption.
