### ISSUE TITLE
additional file type just shows as red rectangle

### ISSUE THREAD

**Issue by xuzhipengnt** [JabRef/jabref#598]
i use JabRef for many years, but i find window style changes from V3.1, i hava a small issue about icon of file type.
In China, .caj is very popular because many Phd thesis download form www.cnki.net and this is a private file format. But i add .caj type into Jabref, the icon is normally, but when i reopen Jabref, icon become red rectangle as fig. I want to know the reason and how to solve this problem. My platform is OSX 10.11, Thanks! 
![image](https://cloud.githubusercontent.com/assets/10328093/12015647/6fe3d20c-ad7a-11e5-8dbe-524b047e2d05.png)
![image](https://cloud.githubusercontent.com/assets/10328093/12015802/aef70746-ad7c-11e5-923f-891e2eab27c3.png)
Windows version also has the same problem.(Windows 7)
![image](https://cloud.githubusercontent.com/assets/10328093/12015811/d6310eb0-ad7c-11e5-9dc4-5b8125b0a556.png)

**Comment by oscargus** [comment]
The red image just shows that there is no dedicated icon for that type of file. All missing icons are shown like that.

I guess that there may be a better default icon for external files though.

**Comment by oscargus** [comment]
Ahh, sorry, my bad. It seems like it works when the file type is added. On load, JabRef looks for an icon called "new" (which doesn't exist).

**Comment by simonharrer** [comment]
Fixed in master. You can try out the fix in about 20 min with the build available at http://builds.jabref.org/master/

**Comment by XaraB** [comment]
Hi,
Is this supposed to be fixed in the dev snapshot ?

I just tried JabRef-3.3dev--snapshot--2016-02-16--master--eabc584.jar, expecting the problem to be solved, but it isn't. To reproduce: 
* Open jabref, edit external file types, add a specific command to launch pdf files. Save and close dialog.
* For now, the pdf icons still look good. 
* Close and open jabref : red squares are back.

Where can I get a fixed version ?

**Comment by xuzhipengnt** [comment]
I also repeat the bug in OS X, if i modify the internal file linkage of PDF, red rectangle will appear. But in fact, we are not often change the PDF settings because JabRef can detect the PDF view software if Acrobat or other can installing correctly. So this Bug is very concealed. Ha ha!

**Comment by XaraB** [comment]
I've got the pdf application set to a custom script which opens side by side the pdf and a file to take notes on it, which explains how I stumbled into the bug. I'd guess this would happen for other filetypes, and maybe even when changing other fields, though I haven't checked.

**Comment by XaraB** [comment]
Thanks !
