### ISSUE TITLE
"invalid BibTex key" - warning when bibtex key includes a ":"

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#5982]
JabRef 5.0-beta.443--2020-02-21--0b90005
Linux 5.4.20-200.fc31.x86_64 amd64 
Java 13.0.2

I have a bibtex file with many entries and all are a unique bibtex keys

Jabref shows me the orange warning triangle when the entry includes  ":".

**Comment by stefan-kolb** [comment]
`:` is considered as an illegal character for the BibTeX key. Therefore, you get the warning.

```
KEY_ILLEGAL_CHARACTERS = "{}(),\\\"-#~^:'`ʹ";
```

Maybe some of the other developers or @koppor can comment why this is the case?

**Comment by mlep** [comment]
Some packages, like babel, do not like the colon character in the entry key (see https://tex.stackexchange.com/questions/89016/colon-in-bibliography-keys-incompatible-with-babel-biblatex-and-tex4ht and https://tex.stackexchange.com/questions/408530/what-characters-are-allowed-to-use-as-delimiters-for-bibtex-keys).

Note that this is just a warning from JabRef: you may proceed with keys containing colons (as long as it does not cause trouble during compilation!).

**Comment by stefan-kolb** [comment]
Thanks @mlep for clarification!

**Comment by Siedlerchr** [comment]
Please note also the settings under options where you can allow/disallow forbidden characters in the bibtexkey

**Comment by koppor** [comment]
@MLEP Could you update https://docs.jabref.org/fields --> "bibtexkey" accordingly? (File: https://github.com/JabRef/user-documentation/blob/master/en/fields/README.md).

Refs https://github.com/JabRef/jabref/pull/6239

**Comment by mlep** [comment]
@koppor OK, I will do it.

**Comment by mlep** [comment]
Oops, I did a direct commit of my changes.
Please review anyway: https://github.com/JabRef/user-documentation/blob/master/en/fields/README.md
