### ISSUE TITLE
Clear fields does nothing

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#5996]
JabRef 5.0-beta.451--2020-02-21--5168d43
Linux 5.5.5-200.sof1.fc31.x86_64 amd64 
Java 13.0.2

I wanted to clear some of the entries from a new bib file. Choosing cleanup and then selecting, say clear month, does nothing. Saved library still contains all these fields.
I tried on a single item or selected the entire library to no avail.

**Comment by bernhard-kleine** [comment]
I wanted to repeat this. Then I noted that the field "month" is not among those fields to be selected. Maybe the unvailability for the month field is the reason that it can not be cleared. The same is with the field "language". You can not clear it.
Then I choose as field to clear DOI. This field is not empty. This did not work at the first trial. I had to **check in addition to "Clear fields" "overwite existing field values"** then the Doi field was cleared. Doing the same on the language field, this was now also cleared.  Maybe you have forgotten to check "overwrite existing field values. 

The entry in an freshly generated library is DOI 10.1073/pnas.1612177114.

**Comment by sambo57u** [comment]
Yes I did forget that...did not realize the distinction I had tried many other and put month when I was writing the bug report as an example. This brings up another issue that "month" should be on the list!
Thanks for your help.

**Comment by bernhard-kleine** [comment]
When I cleared language, that was not on the list either. It seems that you can clear fields that are not on the list. May you can close the issue.
