### ISSUE TITLE
New messages from StatusLogger

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#6009]
JabRef 5.0-beta.464--2020-02-24--469d41c
Linux 5.5.5-200.fc31.x86_64 amd64 
Java 13.0.2

After this morning the old log4j message is gone but it replaced by these:
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.

**Comment by bernhard-kleine** [comment]
Where did you get these messages from?

**Comment by Siedlerchr** [comment]
If you start JabRef with the bat file and not the exe you will see the console again

**Comment by sambo57u** [comment]
Hi, I am on Fedora linux. The bat file /opt/jabref/lib/runtime/bin/JabRef.bat is giving me:
/opt/jabref/lib/runtime/bin/JabRef.bat: line 1: @echo: command not found
/opt/jabref/lib/runtime/bin/JabRef.bat: line 4: unexpected EOF while looking for matching `"'
/opt/jabref/lib/runtime/bin/JabRef.bat: line 5: syntax error: unexpected end of file

**Comment by Siedlerchr** [comment]
The bat file is for windows.

**Comment by sambo57u** [comment]
Naturally....so should there be a shell script?

**Comment by Siedlerchr** [comment]
Yep, it's next to the bat file, simply "JabRef" without any file extension. If you open it an editor you see it's a shell script.

**Comment by sambo57u** [comment]
Ok....I added " > /dev/null 2>&1" at the end of the execution line and it works fine.
Howeve, I usually like to make a logical link from /usr/bin/jabref to this file and I had to
change the DIR statement to point to the runtime library for this to work.

**Comment by tobiasdiez** [comment]
This issue is probably a result of https://github.com/JabRef/jabref/commit/d2de477d8de49de191c5fad16a65c65a96d102a3#diff-c197962302397baf3a4cc36463dce5eaR641, which includes the log4j plugin. This adds a `Log4j2Plugins.dat` file that is known to lead to similar problems: https://stackoverflow.com/questions/48033792/log4j2-error-statuslogger-unrecognized-conversion-specifier
Thus a solution would be to remove the `Log4j2Plugins.dat` from the merged module.

**Comment by sambo57u** [comment]
The issue is still occurring exactly the same way with jabref 5,2 daily development versions on Fedora 33 Linux.

**Comment by zenny** [comment]
I am running JabRef 5.3 in VoidLinux and this issue emerged today:

```
JabRef 5.3--2021-07-05--50c96a2
Linux 5.4.128_1 amd64 
Java 16.0.1 
JavaFX 16+8
```

```
$ ./JabRef
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Jul 06, 2021 4:24:55 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true

(JabRef:11068): Gdk-WARNING **: 16:24:58.762: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

**Comment by rlkamalapurkar** [comment]
Same issue in Windows PowerShell when launched using the batch file.

```
JabRef 5.3--2021-05-24--59fb185
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8
```
```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Jul 23, 2021 10:39:03 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
```

**Comment by horror-vacui** [comment]
The exact same error messages appear in the terminal if I start jabref from it.

```
JabRef 5.4--2021-08-10--3c5a316
Linux 5.15.2-2-manjaro amd64 
Java 16.0.2 
JavaFX 16+8
```

**Comment by calixtus** [comment]
Hi all, we just switched from log4j to tinylog (#8226). We would appreciate it, if you could test the latest development version https://builds.jabref.org/main/ . Please remember to backup your libraries before testing a development build.
Thanks!

**Comment by sambo57u** [comment]
Hi, I have been using development versions regularly. I don't see the syslog messages anymore but in the last few says I am seeing a different messages:
==============================
$ /opt/jabref/bin/JabRef VU_bibtex_master.bib
Dec 20, 2021 8:02:29 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2021-12-20 08:02:29 [JavaFX Application Thread] org.jabref.logic.net.URLDownload.bypassSSLVerification()
WARN: Fix SSL exceptions by accepting ALL certificates

(JabRef:4755): Gdk-WARNING **: 08:02:31.834: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
2021-12-20 08:02:32 [JavaFX Application Thread] org.jabref.model.database.BibDatabaseContext.getFulltextIndexPath()
INFO: Index path for VU_bibtex_master.bib is /home/umar/.local/share/JabRef/0.5a
================================

This is on Linux Fedora 35 using jabref rpm version.

**Comment by calixtus** [comment]
The Gdk-warning is probably related to https://bugs.openjdk.java.net/browse/JDK-8156779
The info message is just a debug message
The SSL-Message is expected
Yet unclear is the first message about the javafx startup (PlatformImpl)

We will investigate. Maybe something about the module system:
https://stackoverflow.com/questions/67854139/javafx-warning-unsupported-javafx-configuration-classes-were-loaded-from-unna

@sambo57u Does JabRef run on your machine? Can you work with it?

**Comment by Siedlerchr** [comment]
@calixtus  The warning is just because we have a merged module with the gradle plugin doing the jlink stuff. It's just a hint that you should normally not start javafx from the classpath
