### ISSUE TITLE
Text extraction from PDF to annotation not working

### ISSUE THREAD

**Issue by funnym0nk3y** [JabRef/jabref#6011]
JabRef version:
JabRef 5.0-beta.438--2020-02-20--5fa1dcf
Windows 10 10.0 amd64 
Java 13.0.2

Hi there,

when using JabRef I found a bug in the annotations function. I marked several passages in my pdf-file and they were shown in the annotations tab accordingly. But unfortunately the text extracted from those annotations did not match the marked text. I tried copying the text directly from Adobe Reader DC via right click > copy text  and pasting it to notepad, which works fine. There are characters missing within the whole marked area. Also there are passages included which are not marked. 

Example:
While these results are excellent from an academic perspective, scaling up the overallcell device area is crucial for achieving practical utility for hybrid perovskite based thin-film solar cells.In this paper, we present a comprehensive study on the use of temperature-controlled doctor bladingtechnique for the growth of large island, crystalline perovskite thin-films. **Specifically, we elucidate thephysical conditions such as substrate temperature, solution volume, and blade speed under ambientconditions that control the growth of large area perovskite thin-films with desired island size, thickness,uniformity and crystallinity**. Using these doctor-bladed thin-films we fabricated devices of ∼1 cm2areain air that yielded an average efficiency of 7.32% with negligible hysteresis in the current-voltage scans.Further improvements in

In JabRef displayed:
 ng  up  the  overall rea  is crucial  for achieving  practical  utility  for hybrid  perovskite  based  thin-film  solar  cells.
r,  we present  a  comprehensive  study  on  the  use  of  temperature-controlled  doctor  blading r the growth  of  large  island

When exported via Acrobat Reader: 
Specifically, we elucidate the
physical conditions such as substrate temperature, solution volume, and blade speed under ambient
conditions that control the growth of large area perovskite thin-films with desired island size, thickness,
uniformity and crystallinity

Regards,
funnym0nk3y

**Comment by Siedlerchr** [comment]
Could you maybe attach or give us a link to the pdf? Is this the only pdf where you noticed that or do experience that with others as well?

**Comment by funnym0nk3y** [comment]
I experienced this behavior with several PDFs. 
Unfortunately I can't attach the PDF here because of copyright protection. But you can find the files here:
[https://pubs.acs.org/doi/10.1021/la803646e](https://pubs.acs.org/doi/10.1021/la803646e)
[https://www.sciencedirect.com/science/article/pii/S2352940716300038?via%3Dihub](https://www.sciencedirect.com/science/article/pii/S2352940716300038?via%3Dihub)
If you don't have access through your institution I'll try to find some with OpenAccess.

Besides that I noticed that there are difficulties with some characters like µ,° and sub-/superscript or stuff like 4,23 x 10^2. But that is just an annoyance.

**Comment by smihael** [comment]
I can reproduce this with attached pdf and txt.

I am using:
JabRef 5.0--2020-03-06--2e6f433
Linux 5.3.0-42-generic amd64 
Java 13.0.2 

PDF was generated using LibreOffice and annotations were added in Okular.

[test.pdf](https://github.com/JabRef/jabref/files/4397885/test.pdf)
[test.bib.txt](https://github.com/JabRef/jabref/files/4397887/test.bib.txt)

**Comment by funnym0nk3y** [comment]
@smihael provided an example pdf, please update status
