### ISSUE TITLE
Integrate ShortSicence

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6015]
There are many tools out there to share information on publications. Be it summaries and comments on publications or be it some collections of bibliographic entries. [ShortSience.org](https://shortscience.org) is a platform for post-publication discussion aiming to improve accessibility and reproducibility of research ideas. [BibSonomy](https://www.bibsonomy.org/) is a tool to collect bibliographic information. The aim of this task is to integrate ShortScience.

The BibSonomy task is https://github.com/JabRef/jabref/issues/5888

Bonus: Integrate hypothesis.is (refs https://github.com/JabRef/jabref/issues/3231, which is currently frozen)

**Comment by stevensdavid** [comment]
@koppor What kind of integration and functionality are you thinking of? Any specific requirements would be helpful, I'd gladly work on this along with my group of students the coming days 😄

**Comment by koppor** [comment]
@stevensadavid I understand that you ask for a sort of a Requirements Document so that you can deduct a specification from?

**Comment by stevensdavid** [comment]
@koppor That would be ideal, but it would be enough to have some sort of idea of the core functionality. I assume that the basic idea would be to provide some sort of quick access to ShortScience summaries of the articles that are in your bibliography. 

However, I'm not entirely sure if the best way to go about this would be to scrape the ShortScience website for summaries (as they don't seem to have a public API) and display them within JabRef, or do something more simple such as providing a link to open the article in ShortScience. The former solution would require quite a lot more code, but would probably be more user friendly. The latter solution would probably be friendlier towards ShortScience.

**Comment by koppor** [comment]
Thank you for checking out. Could you investigate hypothesis.is whether they support an API (https://github.com/JabRef/jabref/issues/3231)?

If this does not work, a link to short science is enough. It should be a deep link to the paper. Maybe it's not enough work for 5 students - but manageable until Friday.

**Comment by koppor** [comment]
@stevensdavid Meanwhile, could you work on https://github.com/JabRef/jabref/issues/6017?

**Comment by koppor** [comment]
Maybe it would make sense that you join gitter --> https://gitter.im/JabRef/jabref feel free to open a private conversation with me there. - Or search me on Skype (hint: same username). -- I'll delete this post as soon as we have contact out of GitHub ^^

**Comment by koppor** [comment]
I put label "freeze", because there is no "real" UI integrations showing the data in JabRef, but only a jump to the browser.

Similar to the "Metrics" of the "Citations" tab:

<img width="1219" height="534" alt="Image" src="https://github.com/user-attachments/assets/74e9163e-d072-4bdd-b963-1dee7934bdb2" />
