### ISSUE TITLE
Emacs Keyboard shortcuts for data entry/editing

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6017]
Versions of JabRef prior to 4 allowed me to use keyboard shortcuts to move the cursor during text entry using the Emacs chords; e.g., ctrl-f (move cursor right one space), ctrl-b (move cursor left one space), ctrl-d (delete character at cursor), ctrl-a (move cursor to beginning of line), ctrl-e (move cursor to end of line). These seem to be missing in the 5.0 snapshots (for example,  ctrl-e closes the document entry dialog box). Please add them back to the next snapshot release for 5.0.

This helps those of us users who are touch-typists and does not affect those who prefer to move the cursor with a pointer device. There's no reason to choose only one method for data entry and editing just like you support multiple platforms (Linux, Apple, Microsoft) and not only one. The code was in earlier versions so adding it back to allow the user to select their preferred data entry/editing method should easily be done.

**Comment by muachilin** [comment]
Hello! I would like to work on this. Thanks!

**Comment by tobiasdiez** [comment]
Some pointers: the Emacs keybinding feature was introduced in https://github.com/JabRef/jabref/commit/e7a27ef897b7985faf8406ceed7f07fdb72ea6ac and removed in https://github.com/JabRef/jabref/pull/4894. Shouldn't be hard to reimplement, e.g: https://gist.github.com/uphy/aea373af1b097cd3c269

**Comment by rs-aesi** [comment]
On Wed, 26 Feb 2020, Tobias Diez wrote:

> Some pointers: the Emacs keybinding feature was introduced in
> https://github.com/JabRef/jabref/commit/e7a27ef897b7985faf8406ceed7f07fdb72ea6ac
> and removed in https://github.com/JabRef/jabref/pull/4894. Shouldn't be
> hard to reimplement, e.g:
> https://gist.github.com/uphy/aea373af1b097cd3c269

Tobias,

Please do re-implement!

Thanks in advance,

Rich

**Comment by koppor** [comment]
It is worked on at https://support.papersapp.com/support/solutions/articles/30000031839-what-are-lists-how-do-i-make-them-in-readcube-papers-.

**Comment by rs-aesi** [comment]
On Wed, 2 Sep 2020, Oliver Kopp wrote:

> It is worked on at
> https://support.papersapp.com/support/solutions/articles/30000031839-what-are-lists-how-do-i-make-them-in-readcube-papers-.

Oliver,

I don't see the relevance of that link to using keyboard shortcuts when
editing text in JabRef.

Regards,

Rich

**Comment by koppor** [comment]
My bad - I had the wrong link in my clipboard. Too many parallel things.

The right link is https://github.com/JabRef/jabref/pull/6037

**Comment by rs-aesi** [comment]
On Fri, 4 Sep 2020, Oliver Kopp wrote:

> My bad - I had the wrong link in my clipboard. Too many parallel things.

Oliver,

It's Friday so too many parallel things are acceptable. :-)

> The right link is https://github.com/JabRef/jabref/pull/6037

muachilin's post looks promising, but that's not what I see in 5.2.dev
installed yesterday (2020-09-03). The choices under Options -> Customize key
bindings show the CUA set (see attached image), not the Emacs set that
allows ctrl-a (go to head of line), ctrl-e (go to end of line), ctrl-d
(delete to right of point), etc.

Have I missed something in that posting?

Carpe weekend,

Rich

**Comment by rs-aesi** [comment]
On Fri, 4 Sep 2020, Oliver Kopp wrote:

> My bad - I had the wrong link in my clipboard. Too many parallel things.

Oliver,

It's Friday so too many parallel things are acceptable. :-)

> The right link is https://github.com/JabRef/jabref/pull/6037

muachilin's post looks promising, but that's not what I see in 5.2.dev
installed yesterday (2020-09-03). The choices under Options -> Customize key
bindings show the CUA set (see attached image), not the Emacs set that
allows ctrl-a (go to head of line), ctrl-e (go to end of line), ctrl-d
(delete to right of point), etc.

Have I missed something in that posting?

Screenshot's attached to this one.

Carpe weekend,

Rich

**Comment by Siedlerchr** [comment]
This feature is not yet implemented.

**Comment by rs-aesi** [comment]
On Fri, 4 Sep 2020, Christoph wrote:

> This feature is not yet implemented.

Christoph,

I'm surprised that implementing it in 5.x when it was present in earlier
versions (not sure about 4.x but certainly in earlier ones) is so difficult.

I look forward eagerly to having it available as I much prefer the editing speed
the emacs chords provide.

Stay well,

Rich
