### ISSUE TITLE
5.0.dev: exception thrown during data entry

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6025]
First seen with the Abstract tab as the focus during data entry. When I move the internal window frame to expand the abstract text entry widget horizontally the attached exception message box pops up. It also displays when I am reformatting the abstract so each line fills the maximum space available to it.

It turns out that that exception message box pops up frequently when I'm entering data in other tabs/text entry widgets as well as in the Abstract 
![jabref-exception](https://user-images.githubusercontent.com/18408428/75353717-b2515200-5860-11ea-84e0-c3360fe329c8.png)
widget. Annoying.

**Comment by Siedlerchr** [comment]
Could you please copy the contents of the exception details? 
Click on show details and paste it here. And please also fill out the other relevant information. Version and OS.

**Comment by rs-aesi** [comment]
On Wed, 26 Feb 2020, Christoph wrote:

> Could you please copy the contents of the exception details?

> Click on show details and paste it here. And please also fill out the
> other relevant information. Version and OS.

Christoph,

I'm running Slackware-14.2/x86_64 and the 2020-02-24 snapshot of JabRef-5.0.

Could not highlight the text in the message box and paste it into a text
file in a v.t. so I grabbed three screenshots (attached) as I scrolled the
details from beginning to end.

Could not expand the message box window, only move it, so I could not
display the entire details at the same time.

HTH,

Rich

**Comment by Siedlerchr** [comment]
You have to upload the screenshots direclty at github, images or attachments from emails are stripped  when you reply to an issue via mai

**Comment by rs-aesi** [comment]
On Wed, 26 Feb 2020, Christoph wrote:

> You have to upload the screenshots direclty at github, images or
> attachments from emails are stripped when you reply to an issue via mai

Christoph,

You asked me to respond to your message and that's what I did. I'll repost
it on github.

Regards,

Rich

**Comment by rs-aesi** [comment]
Here are the three screenshots.
![jabref-exception-details-1](https://user-images.githubusercontent.com/18408428/75368893-4e865380-5877-11ea-9b8a-c51a79a063a2.png)
![jabref-exception-details-2](https://user-images.githubusercontent.com/18408428/75368918-56de8e80-5877-11ea-8a5a-f78525381fa2.png)
![jabref-exception-details-3](https://user-images.githubusercontent.com/18408428/75368929-5ba34280-5877-11ea-919a-c649128a6a9e.png)

I hope these help.
