### ISSUE TITLE
List editors in Author column for multi-authored documents.

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6029]
When a book contains individual contributions by separate authors while the book itself has one or more editors their names are not displayed in the 'Author' column of the database view (see attached screenshot.) It would be helpful if that first column contained editor names when there's not a single author for the book, proceedings, or other multi-author compendium.
![jabref-database-view](https://user-images.githubusercontent.com/18408428/75395917-2fec8080-58a8-11ea-80ab-136e16d2a56f.png)

Thanks in advance,

Rich

**Comment by AEgit** [comment]
Hmm, this could be a bit confusing. If such a change is made, it should still be clear (just by looking at the main table), that these are editors, not authors of the item. Maybe add a tag "editor" or something along the lines that is visible in the main table (again, this would be only necessary, if the proposed changes are made - otherwise it won't).

**Comment by mlep** [comment]
On my screen, the title of the column is "Author/Editor":
![Capture du 2020-02-27 11-33-36](https://user-images.githubusercontent.com/6931104/75436542-09385380-5955-11ea-94fc-c29cb8d84369.png)
This is for a BibTeX file (not biblatex). I do not think I changed something in the setup.

@rs-aesi which version of JabRef are you using? Are you displaying a BibTeX or a biblatex file?

JabRef 5.0-beta.496--2020-02-27--1d4efaa
Linux 4.9.0-12-amd64 amd64 
Java 13.0.2

**Comment by calixtus** [comment]
Hello @rs-aesi, this behaviour should normally be achievable by adding a column with the name "author/editor" in the preferences.

**Comment by rs-aesi** [comment]
On Thu, 27 Feb 2020, MLEP wrote:

> @rs-aesi which version of JabRef are you using? Are you displaying a
> BibTeX or a biblatex file?

I am using JabRef-5.0-portable_linux.tar.gz downloaed yesterday (26 Feb)
with a BibTeX file on Slackware-14.2/x86_64.

I'm using the default column displays on each tab.

If there's already an option to have the first column display Author/Editor
please point me to where I make the change.

HTH,

Rich

**Comment by rs-aesi** [comment]
On Thu, 27 Feb 2020, Carl Christian Snethlage wrote:

> Hello @rs-aesi, this behaviour should normally be achievable by adding a
> column with the name "author/editor" in the preferences.

Thank you Carl. Since I started using the development snapshots a couple of
weeks ago I've not modified any of the columns.

Regards,

Rich

**Comment by rs-aesi** [comment]
On Thu, 27 Feb 2020, Carl Christian Snethlage wrote:

> this behaviour should normally be achievable by adding a column with the
> name "author/editor" in the preferences.

Carl,

How do I replace the Author column with Author/Editor in Preferenced -> Data
Entry Columns? I looked at the choices and did not see it.

Regards,

Rich

**Comment by calixtus** [comment]
Hi @rs-aesi,
take a look at options -> preferences -> entry table columns

![tablecolumsnew](https://user-images.githubusercontent.com/50491877/75467007-5df6c100-598b-11ea-8052-8f131f539d7f.png)

You will find all the entry columns in a list and below that a combo box. Enter there (1) 'author/editor'. If you click somewhere outside this field or on the '+' it should automatically change to 'field:author/editor' and another click on the '+' should add the column 'Author/Editor' to the list. You can move the column with the up and down arrows on the right to your favorite position or use the reorder feature of javafx by dragging the columns in the main table view to your favorite position.

I hope this was helpful. Feel free to ask, but please also note that we usually use the forums ( https://discourse.jabref.org/ ) and the gitter chat ( https://gitter.im/JabRef/jabref ) to provide support. If you like JabRef we would be happy if you tell others about it.

**Comment by rs-aesi** [comment]
On Thu, 27 Feb 2020, Carl Christian Snethlage wrote:

> take a look at options -> preferences -> entry table columns

Carl,

That's where I looked. And I searched the alphabetical list produced by the
combobox's down-arrow.

> You will find all the entry columns in a list and below that a combo box.
> Enter there (1) 'author/editor'.

I had no idea I could enter a data type like this and JabRef would know what
to do with it.

> If you click somewhere outside this field or on the '+' it should
> automatically change to 'field:author/editor' and another click on the '+'
> should add the column 'Author/Editor' to the list.

I didn't see 'field:author/editor' but clicking on the '+' key added it to
the list.

> You can move the column with the up and down arrows on the right to your
> favorite position

Yep. Moved it just below the group and deleted the 'Author' column.

> I hope this was helpful. Feel free to ask, but please also note that we
> usually use the forums ( https://discourse.jabref.org/ )

I had posted all issues and bugs on the mail list and was asked to post to
the devs on github. So I did. Since I did not see this column option in the
combobox I asked on github. This response now posted on both places.

Thanks,

Rich

**Comment by calixtus** [comment]
You're welcome. :smile:
