### ISSUE TITLE
Installer on Mac OS X 10.15.3 beachballs

### ISSUE THREAD

**Issue by retorquere** [JabRef/jabref#6032]
JabRef version 4.3.1 on Mac OS X 10.15.3

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The bug is not reproducible with the latest dev version, but that does not have an installer, so I don't think the comparison is relevant here.

1. Download the DMG for Mac OS
2. Start the installer
3. Go through installer window until you get to the file association screen
4. The installer beachballs, and processor load goes to 100%

The log file is too large to paste here (GH won't allow it) so I've attached it.
[jabref-installer-crash.txt](https://github.com/JabRef/jabref/files/4261665/jabref-installer-crash.txt)

**Comment by szhorvat** [comment]
I just wanted to note that ideally JabRef would not use an installer at all on Mac. The presence of a (completely unnecessary) installer has always been an inconvenience and it does not inspire confidence.

**Comment by Siedlerchr** [comment]
We switched to the native packacking tool jpackage after the 5.0 alpha version and that creates packages for mac and linux and windows. So no more installer for mac.
As you said this issue is not reproducible with the latest version, I will close this issue as we are planning to release 5.0 soon,
