### ISSUE TITLE
Make preferences larger

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6038]
We have "Appearance" below "Advanced"

IMHO "Advanced" should be last. Can we switch it and make the preferences a bit higher so that a user does not need to scroll at the left side?

![grafik](https://user-images.githubusercontent.com/1366654/75487536-da4ecb80-59ae-11ea-8fc0-46d9a9c8e6ca.png)

**Comment by Siedlerchr** [comment]
Nope, height is problematic, especially if you have a small notebook monitor. We also have a search.

**Comment by koppor** [comment]
Can't we adapt the window size if the window does not cover the whole screen? I hope, this is possible with JavaFX.

After resetting the preferences, restarting JabRef, it appears like that on my monitor:

![grafik](https://user-images.githubusercontent.com/1366654/75489661-f81e2f80-59b2-11ea-9a31-d3d18db776cb.png)

I assume that a significant amount of users expects 

- programs starting taking a reasonable size - if not full screen
- popups appearing taking a reasonable size - if not full screen

I would bet that we earn question marks if 50 pixels are missing on a dialog so that it is complete AND the dialog has 300 pixels to grow on the screen.

**Comment by calixtus** [comment]
What could be done is to change the buttons below the list to icon buttons with the names in tooltips...
I think, not every user uses import/export/show prefs every day.
