### ISSUE TITLE
Entry removed from group keeps being displayed in entry table

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6055]
JabRef 5.0-beta.519--2020-03-02--f908883
Linux 4.9.0-12-amd64 amd64 
Java 13.0.2

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When removing an entry from a group, the entry remained displayed in the entry panel.

1.Select a group (only the entries from this group are displayed)
2. In the entry table, select one entry to be removed from the group
3. On the group name, right click and select "Remove selected entries from this group".
==> The number of entries in the group is decreased, but the display of the entry table is not updated: the removed entry is still there.
To update the entry table, you have to select another group, and select again the group.

**Comment by ShiqingLiu** [comment]
It seems it is not reproduceable in the latest version. Could you provide more information about this issue? Thanks.

**Comment by mlep** [comment]
I have tried to reproduce it with JabRef 5.1--2020-06-09--595f085, but could not...
Behavior solved by a PR merged in the meantime?
