### ISSUE TITLE
Add a subgroup: a warning should not close the window

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6066]
JabRef 5.0-beta.532--2020-03-04--8111707
Linux 4.9.0-12-amd64 amd64 
Java 13.0.2

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

While adding a subgroup, if a warning is displayed, the "add subgroup" window is closed.

1. In the group interface, right click and select "Add subgroup". This opens a window entitled "Add subgroup"
2. In this window, add a text in the description field. And DO NOT enter a group name.
3. Click on OK

==> An error window appears, stating (rightfully) that "Please enter a name for the group". Click on OK (no other choice). This causes the window "Add subgroup" to disappear.
Expected behavior: leave open the window "Add subgroup", so that I can enter the name of the group.

**Comment by stefan-kolb** [comment]
Should be fixed within https://github.com/JabRef/jabref/pull/6110
