### ISSUE TITLE
Entry table displayed twice!

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6067]
JabRef 5.0-beta.532--2020-03-04--8111707
Linux 4.9.0-12-amd64 amd64 
Java 13.0.2

- [X ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

While resizing the entry editor (to give more room for the entry table), a second entry table appeared in the entry editor.
To show you what I mean:
![Capture du 2020-03-05 10-40-00](https://user-images.githubusercontent.com/6931104/75969093-b1f32f80-5ece-11ea-9a56-e19d43abe532.png)

- The display went back to normal after switching between tabs (i.e. databases).
- I could not find a way to make it reproducible.
- Log file (Help > View event log) is empty.

**Comment by calixtus** [comment]
It seems to me that the maintable is not displayed twice, but behind a very small entry editor, which is not scaled according to the main window.

**Comment by mlep** [comment]
Looking at it again: the entry editor seems displayed in the middle of the maintable. And an empty space appears at the bottom of the maintable.

**Comment by calixtus** [comment]
Thanks for the follow-up. Is there any chance to reproduce this behaviour? I played around with the editor a bit but was not able to reach this issue.

**Comment by mlep** [comment]
> Is there any chance to reproduce this behaviour? I played around with the editor a bit but was not able to reach this issue.

Neither do I...

**Comment by tobiasdiez** [comment]
Thanks for notifying us about this issue. As this seems not reproducible, there is nothing we can really do. Hence, I'll close this for the moment. Feel free to reopen if you find a way to (more or less reliably) reproduce it.
