### ISSUE TITLE
JabRef cannot connect ot LibreOffice on Mac OS X

### ISSUE THREAD

**Issue by tzvet** [JabRef/jabref#607]
I tried to connect JabRef (latest: 3.1) to LibreOffice (latest: 5.0.2.2) on my OS X (El Capitan). At work i have a windows system installed and everything worked fine on it...clean connection and pushing references.
On OS Xthe automatic search does not find the directory, but also the Manual selection !
It gives:
Error message: File not found: /Applications/LibreOffice.app/Contents/basis-link/program/classes/unoil.jar (see the grabed pic below).
I checked where are the files, in:
/Applications/LibreOffice.app/Contents/Resources/java/
But impossible to make it link to that folder since it appends all the "Contents/basis-link/..." folders automatically... any solution for OSX ?!?

![jabref_libreoffice_wrong_connection](https://cloud.githubusercontent.com/assets/16489452/12051263/f6c112e0-af3b-11e5-9b9a-5a25ef0364dc.jpg)

**Comment by oscargus** [comment]
OK! I'll see what I can do. The problem is that I had no idea where the files where located in OSX, so when upgrading to support OO4/LO5, I changed the OSX filenames based on the other OS:es (and the path you provided wasn't the previous one either). Expect a trial version in an hour or so.

**Comment by oscargus** [comment]
You can try it out at: http://builds.jabref.org/cleaneroo/

Note that this version also includes some other changes to the OO/LO interface, such that only the side panel can be used and not the push-button. Also, if you specify the path manually, do not include the Contents part (as it shows up twice in the screen shot).

**Comment by tzvet** [comment]
perfect ! Thx a lot ! Manual connection works fine ! Happy New Year !!!
