### ISSUE TITLE
Protect Author with {} arround selection.

### ISSUE THREAD

**Issue by amaridev** [JabRef/jabref#6070]
Hello,

I have the following problem with the 5.0 alpha and beta. 

When editing an entry, for example the author field, you can click with the right mouse button on it and select "protect term" and add {} around the selected text. 

My observation is, that when the bibtex file is saved, all {} for term protection are removed. Even if I edit the bibtex file manually and open jabref afterwards, the {} get stripped. This is unfortunate since, some Authors are not Names of persons and have to be in the order I put them into the text field. 

I would be happy if this could be fixed sometime soon.

**Comment by mlep** [comment]
I cannot reproduce the describe behavior with the latest master version (https://builds.jabref.org/master/): the {} are still there when saving, closing, and reopening the file.
A few ideas:
- do you have any "save action" configured? See Menu Content > Library properties?
- could you try the latest master and report if the behavior you observed is still there?

**Comment by amaridev** [comment]
Indeed. I had a save action enabled to convert latex to unicode. I disabled all of them and the Problem is gone. 

Thank you very much.

**Comment by Siedlerchr** [comment]
This is a known issue with the Latex2Unicode formatter: #4152
