### ISSUE TITLE
jabref 5 freezes with options menu

### ISSUE THREAD

**Issue by mifads** [JabRef/jabref#6077]
JabRef version 5.0-portable-linux-tar on Elementary OS 5.0

- YES, I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

JabRef starts, and I can load .bib files. Any attempt to use the Options menu fails though, e.g. Options - Preferences. At this stage, I can't cancel, or change to a different option.

1. unpack the tar version (though .deb also failed in the same way)
2. cd JabReb 
3. bin/JabRef  -> opens JabRef, though many errors appear in terminal - see png
4. Press Options then e.g. preferences -> freeze

![top_of_log](https://user-images.githubusercontent.com/22075144/76159647-fb3bbd00-6122-11ea-929e-deb8469f2f09.png)

**Comment by Siedlerchr** [comment]
On Windows I could not reproduce this. Could you try to reset your preferences?
You can do this using the command line switch `-d all`
 https://docs.jabref.org/general/commandline#reset-preferences-d-key

**Comment by mifads** [comment]
> You can do this using the command line switch `-d all`

Just tried. No difference.

**Comment by Siedlerchr** [comment]
Try to delete the preferences file:
https://stackoverflow.com/a/1320798

**Comment by mifads** [comment]
In ~/.java/.userPrefs I have 7 prefs.xml files in different sub-directories. Should I just do 
rm -r .userPrefs?

**Comment by Siedlerchr** [comment]
There should one be labeled JabRef

**Comment by mifads** [comment]
ls -laRt from .java gives:

./.userPrefs:
total 12
drwxrwxr-x 3 davids davids 4096 mar  9 09:35 ..
drwxrwxr-x 4 davids davids 4096 mar  8 12:19 org
-rw------- 1 davids davids    0 mar  6 14:11 .userRootModFile.davids
drwx------ 3 davids davids 4096 mar  6 14:09 .
-rw------- 1 davids davids    0 mar  6 14:09 .user.lock.davids

./.userPrefs/org:
total 20
drwxrwxr-x 4 davids davids 4096 mar  8 12:19 .
drwxr-xr-x 3 davids davids 4096 mar  8 12:19 jabref-shared
drwxrwxr-x 5 davids davids 4096 mar  8 12:19 jabref
-rw-rw-r-- 1 davids davids  148 mar  6 14:10 prefs.xml
drwx------ 3 davids davids 4096 mar  6 14:09 ..

./.userPrefs/org/jabref-shared:
total 16
-rw-r--r-- 1 davids davids  148 mar  8 12:19 prefs.xml
drwxr-xr-x 2 davids davids 4096 mar  8 12:19 default
drwxr-xr-x 3 davids davids 4096 mar  8 12:19 .
drwxrwxr-x 4 davids davids 4096 mar  8 12:19 ..

./.userPrefs/org/jabref-shared/default:
total 12
-rw-r--r-- 1 davids davids  148 mar  8 12:19 prefs.xml
drwxr-xr-x 2 davids davids 4096 mar  8 12:19 .
drwxr-xr-x 3 davids davids 4096 mar  8 12:19 ..

./.userPrefs/org/jabref:
total 24
-rw-r--r-- 1 davids davids  353 mar  8 12:19 prefs.xml
drwxrwxr-x 4 davids davids 4096 mar  8 12:19 ..
drwxrwxr-x 2 davids davids 4096 mar  8 12:19 customizedBiblatexTypes
drwxrwxr-x 5 davids davids 4096 mar  8 12:19 .
drwxrwxr-x 2 davids davids 4096 mar  8 12:19 customizedBibtexTypes
drwxrwxr-x 2 davids davids 4096 mar  6 14:10 bibtexkeypatterns

./.userPrefs/org/jabref/customizedBiblatexTypes:
total 12
-rw-r--r-- 1 davids davids  148 mar  8 12:19 prefs.xml
drwxrwxr-x 2 davids davids 4096 mar  8 12:19 .
drwxrwxr-x 5 davids davids 4096 mar  8 12:19 ..

./.userPrefs/org/jabref/customizedBibtexTypes:
total 12
-rw-r--r-- 1 davids davids  148 mar  8 12:19 prefs.xml
drwxrwxr-x 2 davids davids 4096 mar  8 12:19 .
drwxrwxr-x 5 davids davids 4096 mar  8 12:19 ..

/.userPrefs/org/jabref/bibtexkeypatterns:
total 12
drwxrwxr-x 5 davids davids 4096 mar  8 12:19 ..
-rw-rw-r-- 1 davids davids  148 mar  6 14:10 prefs.xml
drwxrwxr-x 2 davids davids 4096 mar  6 14:10 .

**Comment by Siedlerchr** [comment]
You can delete all starting with the path org/jabref/...

**Comment by mifads** [comment]
Well, it stopped the freezing, but Options - Preferences -  is still on 'General'. If I press on any other entry the dialog box disappears (it is just hidden), but I can't access the other items. My terminal is reporting:

(JabRef:10236): Gdk-WARNING **: 10:01:03.792: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.

Additionally, as soon as JabRef starts I get the same type of warning messages about Unrecognised format specifier as in my first posrt above.

ON the other hand, all of the above problems are on laptop (Elementary OS 5). I have tried running the same bin/JabRef from my desktop (Xubuntu 20.04), and all seems well there. Except that I get exactly the same warning message.

**Comment by Siedlerchr** [comment]
Okay, that seems to be a specifiy linux issue with the distribution.  As far as I know Javafx (the UI technology)  uses GTK3. But I'm not an expert in the linux differences.
The warning messages regarding the format specifier are irrelevant, they are related to an external dependency and also occur on windows. See #6009 


For me this seems to be some external java/linux bug which we can't do anything about for the moment.
