### ISSUE TITLE
Icons from Material design icons not recognized

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#6078]
JabRef 5.0-beta.519--2020-03-02--f908883
Windows 10 10.0 amd64 
Java 13.0.2

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Fonts from Material Design Icons are not recognized: airballoon, or account.
1. open jabref
2. choose any group
3. add a color and as the icon name airballoon or account
4. save and see that the color is changed while the icon is not.

This has been working before. IIRC it was not possible to add icons with hyphens in the name, but the names airballoon and account do not have any icons
![grafik](https://user-images.githubusercontent.com/9216487/76161991-f71a9a00-6138-11ea-8fb9-1c27bc871426.png)
![grafik](https://user-images.githubusercontent.com/9216487/76162000-20d3c100-6139-11ea-9d98-1f35abd1c8c6.png)

When I checked this in Jabref 4.1 the icon was there!!!!!
![grafik](https://user-images.githubusercontent.com/9216487/76162057-b707e700-6139-11ea-9793-f9e2766fe1cc.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by stefan-kolb** [comment]
![image](https://user-images.githubusercontent.com/2141507/76682572-845c6380-65fd-11ea-9384-8b105d66bd76.png)

**Comment by bernhard-kleine** [comment]
It would be very good, if a dropdown with icons is avaaible. The present situtation is untainable.
