### ISSUE TITLE
Adjust scaling of JabRef for high-resolution displays

### ISSUE THREAD

**Issue by xolotl90** [JabRef/jabref#6086]
I am facing a problem with the display resolution of Jabref I could not resolve yet. I am working on a high resolution monitor (2560x1440), but JabRef scales everything too big for me (see image). Ex-/ and Re-importing the settings while changing the "mainWindowSizeX/Y" fields have no effect at all. Is there a way to force Jabref to a smaller rendering?

This might be related to #5498, although changing the settings of resolution and scaling of my window manager have no effect, either. 

I am using LinuxMint 19.3 with the cinnamon desktop.

![Bildschirmfoto vom 2020-03-09 14-08-37](https://user-images.githubusercontent.com/12495347/76215858-e25d0580-620f-11ea-925e-1f197c0c8123.png)

**Comment by Siedlerchr** [comment]
You could try to apply these scale tips here in the sh startup file of JabRef:
https://wiki.archlinux.org/index.php/HiDPI#JavaFX

**Comment by xolotl90** [comment]
Thank you @Siedlerchr . I could resolve the issue by adding
-Dglass.gtk.uiScale=1.4
in the file JabRef.cfg (for me located at /opt/JabRef/lib/app/JabRef.cfg) in the section [JavaOptions]
The file looks now like this. 

> [Application]
> app.name=JabRef
> app.version=5.0.30001
> app.runtime=$ROOTDIR/lib/runtime
> app.identifier=org.jabref
> app.classpath=
> app.mainmodule=org.jabref/org.jabref.JabRefLauncher
> 
> [JavaOptions]
> --module-path
> $ROOTDIR/lib/app/mods
> -Dglass.gtk.uiScale=1.4
> [ArgOptions]
> 
>

**Comment by Siedlerchr** [comment]
@xolotl90  Glad that it works! It would be nice if you could add a section to the FAQ with your configuration tips:
https://docs.jabref.org/faq/faqs-on-operating-systems/faqlinux (Click on Edit on Gitbub)

**Comment by xolotl90** [comment]
I added a small paragraph about this and made a pull request. #260 in the user-documentation repo
