### ISSUE TITLE
Citation copied to LyX allows no formating

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6087]
Two issues with 5.0.dev germane to citation transfers to LyX.

- [ ] First, the the icon bar is apparently no longer available; I cannot find a way to display it in the Preferences. Clicking on the LyX icon is quicker than is using the menus.

- [ ] Second, the citation is inserted in LyX between brackets and there's no way to change the format when a right-click -> Settings is used. Please restore the ability to select the proper citation format and the tool bar (at least for citation transfers).
  ![jabref-citation-screenshot](https://user-images.githubusercontent.com/18408428/76265515-ec87ff80-6221-11ea-89e7-15de0b3bd630.png)

**Comment by mlep** [comment]
Using 5.0, I still have the LyX icon in the bar on my computer:
![Capture du 2020-03-10 08-55-12](https://user-images.githubusercontent.com/6931104/76291216-f73ba680-62ac-11ea-823e-f7d96936d92b.png)

About the "proper citation format": Upon clicking the LyX icon, JabRef sends to LyX something like \cite{Cronshey1986}. This is a standard LaTeX syntax. Then, it is up to LyX to render the citation.

**Comment by rs-aesi** [comment]
On Tue, 10 Mar 2020, MLEP wrote:

> Using 5.0, I still have the LyX icon in the bar on my computer:

MLEP,

My apologies: I had not before clicked on the '>>' at the extreme right of
the frame. Is there a way to have that icon string constantly available
rather than indirectly available?

I now have the 5.1.dev uploaded to github today at 03:25 (timezone not
specified).

> About the "proper citation format": Upon clicking the LyX icon, JabRef
> sends to LyX something like \cite{Cronshey1986}. This is a standard LaTeX
> syntax. Then, it is up to LyX to render the citation.

I had not yet inserted the bibiography when I posted the message; I have now
made it available and it's not behaving well. I'll follow up on the lyx mail
list about this.

Please close this issue.

Regards,

Rich

**Comment by mlep** [comment]
> MLEP, My apologies: I had not before clicked on the '>>' at the extreme right of the frame. Is there a way to have that icon string constantly available rather than indirectly available? 

No need for apologies!
I believe that, at the moment, you cannot do much about the '>>'... It is an issue related to the GUI desing. I guess it will be improved in future versions (@JabRef/developers: any additional comments on this?).

> I had not yet inserted the bibiography when I posted the message; I have now made it available and it's not behaving well. I'll follow up on the lyx mail list about this. Please close this issue. 

Good to know it is working on the JabRef site. I hope the LyX community will help you solve your issue of citation format.

**Comment by rs-aesi** [comment]
On Tue, 10 Mar 2020, MLEP wrote:

> No need for apologies! I believe that, at the moment, you cannot do much
> about the '>>'... It is an issue related to the GUI design. I guess it
> will be improved in future versions (@JabRef/developers: any additional
> comments on this?).

MLEP,

Of course it's what the widget set allows you to do in placing things.
Perhaps in the not-too-distant-future it will be different.

> Good to know it is working on the JabRef site. I hope the LyX community
> will help you solve your issue of citation format.

Yes, the lyx community will help. It's perhaps an unintentional glitch when
versions were recently updated to fix Windows problems (which seems to me to
be like trying to push water up hill).

Regards,

Rich

**Comment by calixtus** [comment]
Hi @rs-aesi and @mlep . Thanks for the bug report and the quick support on this.
The two arrows are displayed instead of the whole toolbar probably because of a small window width of JabRef. If the window width is large enough the whole toolbar should be displayed. But I think, it's really annoying that even when almost the complete toolbar could be visible, but only a few pixels are missing, the complete toolbar is hidden. JabRef should at least display some buttons. an the others behind the two arrows. But I have to investigate this further, if this is possible.

Note that you can also change the push-to-application and the cite command in `Preferences -> External programs`.

I hope this solves at least the first part of this issue. The second part needs some more investigation.

**Comment by rs-aesi** [comment]
On Tue, 10 Mar 2020, Carl Christian Snethlage wrote:

> The two arrows are displayed instead of the whole toolbar probably because
> of a small window width of JabRef.

Carl,

I'm working with a HP 19" square monitor (1280x1024 dpi resolution). The
JabRef window's width is ~85% of the available space. Expanding the window's
width to the monitor's does not provide sufficient room to display all the
icons.

It seems that most monitors sold today are wide screen; probably for better
movie viewing. I prefer the additional height for writing documents and
other applications.

Regards,

Rich

**Comment by calixtus** [comment]
I can relate to that. I'm using an old monitor as second one in portrait mode on my workstation to display PDFs or JabRef while working on a document on my primary screen.

**Comment by mlep** [comment]
About the icon bar position, there is already an opened issue (https://github.com/JabRef/jabref/issues/4907)
