### ISSUE TITLE
Arrow to sort field

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#609]
On 3.1 version, at least on my system, I lost the little arrow in header of field to show which field is sorted and its order (up or down). I used Ubuntu 14.04. I try GTK and MetalLookandFeel apparences.

**Comment by matthiasgeiger** [comment]
Confirmed... I'll check this in the next days.

**Comment by matthiasgeiger** [comment]
Some quick, intermediate feedback: I introduced this bug during the rewrite of the main table. However, fixing it (without losing the functionality for the Icon-Headers) is not so trivial.
