### ISSUE TITLE
Library sort order get lost

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6091]
JabRef 5.0--2020-03-06--2e6f433
Linux 4.9.0-12-amd64 amd64 
Java 13.0.2

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In Library > Library properties, the export sort order can be specified.
However, the choice is not memorized.
1. Open a library
2. Go to Library > Library properties
In my case, the sort order was:
![Before-Capture du 2020-03-10 11-08-08](https://user-images.githubusercontent.com/6931104/76302054-a2555b80-62bf-11ea-8b90-98cc346b05db.png)
3. Change the sort order
Like:
![During-Capture du 2020-03-10 11-10-08](https://user-images.githubusercontent.com/6931104/76302184-d3359080-62bf-11ea-98f0-079c68e9db80.png)
4. Click on OK (closing the Library properties window)
5. Go (again) to Library > Library properties
The initial sort order is displayed:
![After-Capture du 2020-03-10 11-10-32](https://user-images.githubusercontent.com/6931104/76302194-d892db00-62bf-11ea-8ca5-5d57bc4c3de3.png)

**Comment by Hugoo98** [comment]
Hello,
I would like to try to correct this bugs and add a little functionality, as part of a course taken under license 3, I would like to know if this is not already done ...
cordially

**Comment by Siedlerchr** [comment]
@Hugoo98  Sure, go ahead! To me this looks like some issue with storing the properties and loading them from the preferences.
Read through the [Contribution Guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) 
The related code is located in this package:
https://github.com/JabRef/jabref/tree/master/src/main/java/org/jabref/gui/libraryproperties

**Comment by Hugoo98** [comment]
@Siedlerchr thank you very much, I will try to do it and keep you posted.

**Comment by calixtus** [comment]
Hi @Hugoo98, im very sorry, I already startet work on this issue a few days ago, but did not uploaded my draft as a PR. I hope you did not put too much effort yet in it. Especially this one is a bit more complicated, since the library properties dialog is a little bit screwed up... 🙈 Maybe we can work on this together?

**Comment by Hugoo98** [comment]
Hi @calixtus no no i haven't started yet but i sent it to my teacher and he said it might be interesting.
Ducoup, I made my decision to do it even if it is complicated because there are 3 of us in our group which allows us to exchange ideas.

**Comment by calixtus** [comment]
Good, JabRef always welcomes students, who would like to practice software architecture and programming. I'll leave than the rework of SaveOrderConfigPanel to you. If you have questions, don't hesitate to ask us, we always like to help.

My original plan was to replace the three comboBoxes with a single TableView, offering the user the ability to add more than three SortCriteria. Fortunatly SaveOrderConfig already works with a LinkedList in its data model, so you probably don't have to change too much outside SaveOrderConfigPanel and SaveOrderConfigPanel. This would imply you add a CheckBoxTableCell in gui.utils (for a similar example take a look at @Siedlerchr s implementation of RadioButtonTableCell). But maybe you have a better idea.

Please take a look at my PR. The finished result must respect the mvvm-design pattern and should respect the design principles of JabRef (the finished result should fit in the common look and feel). SortOrderPanel should only be a fx control and the data should be handled in the LibraryPropertiesDialogViewModel /  ExportSortingTabView.

You can base your work on my branch. I will try to hurry to refactor the still remaining parts that are still illegally tangled to the LibraryPropertiesView / ExportSortingTabView, so you have a clear workspace for your work.

Good luck and have fun.

**Comment by Siedlerchr** [comment]
You are lucky, as javafx already has a CheckboxTableCell you can use.
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/cell/CheckBoxTableCell.html

**Comment by Hugoo98** [comment]
ok thanks @calixtus  i will take a look at your PR and i will keep you posted
