### ISSUE TITLE
"create backup file while saving" option is non-functional.

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#6092]
JabRef 5.1--2020-03-10--d5ee20b
Windows 10 10.0 amd64 
Java 13.0.2

In the settings I deactivated the "create backup file while saving" option.
I also deleted the `*.sav` file from the filesystem.

But the `sav`file is still created when **starting** JabRef.
When closing JabRef it is gone.

**EDIT**: The behaviour is not always reproducable. But please see the attached video which contains different behaviours.

[6092.zip](https://github.com/JabRef/jabref/files/4313103/6092.zip)

Makes no sense for me.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
The problem is still reproducable with the current dev - also with the release version. I can not understand why there was a release in the last days but JabRef is still unstable.

**Comment by koppor** [comment]
The option "create backup file while saving" is for the `.bak` file, not for the `.sav` file. - Because of the **while** saving.

The issue is that the setting is without implementation. See https://github.com/JabRef/jabref/blob/209d336d24eef2a4bf4405d6d334370466d88a65/src/main/java/org/jabref/logic/exporter/AtomicFileOutputStream.java#L185.

Options:

1. Remove setting from the GUI.
2. Remove creation of `.bak` while saving - accepting that the user cannot go back one revision manually.
3. Implement code to respect setting.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
What is the difference between bak and sav file?

**Comment by koppor** [comment]
sav == autosave each 15sec
bak == version saved before last save. -- HEAD~ in nerd speak

Reason for bak: non IT users can restore something if they accidentally
saved. -- Very old functionality. Could be done differently these days. See
IntelliJ for instance...

Codeberg-AsGithubAlternative-buhtz <notifications@github.com> schrieb am
Sa., 14. März 2020, 07:57:

**Comment by stefan-kolb** [comment]
> The option "create backup file while saving" is for the `.bak` file, not for the `.sav` file. - Because of the **while** saving.
> 
> The issue is that the setting is without implementation. See
> 
> https://github.com/JabRef/jabref/blob/209d336d24eef2a4bf4405d6d334370466d88a65/src/main/java/org/jabref/logic/exporter/AtomicFileOutputStream.java#L185
> 
> .
> Options:
> 
> 1. Remove setting from the GUI.
> 2. Remove creation of `.bak` while saving - accepting that the user cannot go back one revision manually.
> 3. Implement code to respect setting.

I guess we can remove that option from the UI/preferences. @JabRef/developers WDYT? Consens or dev call?

**Comment by Siedlerchr** [comment]
I'm voting for remove

**Comment by calixtus** [comment]
If it's of no use, remove it.
There are probably some more things that could be removed from the preferences: Like the special option to select the sumatra pdf reader. This should work with the application binding in the external file types manager dialog...

**Comment by koppor** [comment]
Decision: Remove option, but keep functionality.

**Comment by koppor** [comment]
We documented both features at https://docs.jabref.org/general/autosave and https://docs.jabref.org/general/backup. I am merging both documentation into one - and remove the configuration option so that JabRef always creates .sav and .bak.
