### ISSUE TITLE
JabRef 5.0 "Show/Edit Bibtex Source" gets stuck in Windows 10

### ISSUE THREAD

**Issue by VivaldoMendes** [JabRef/jabref#6093]
I have JabRef 5.0 installed in a Windows 10 machine. It works remarkably well, but there appears to be an annoying problem with the "Show/Edit Bibtex Source" pane. From time to time, it just gets stuck, not allowing me to write or edit any entry at all. If I restart JabRef, this pane starts working OK again, but after a while, it gets stuck again. 

I will give you an example. I went to Google Scholar and just copied the following BibTex citation:

@book{cournot1995mathematical,
  title={Mathematical principles of the theory of wealth},
  author={Cournot, Antoine Augustin and Fisher, Irving},
  volume={1},
  year={1995},
  publisher={James \& Gordon}
}

Then go to JabRef, choose "New entry", then in the "Select entry type" I choose "Book", and a new pane opens up with the single entry:

"@Book{,
}"

I try to paste the BibTeX citation above on top of this, but JabRef does not allow me to do anything at all. This pane/window is stuck. Indeed, I can manually copy the entire citation into the "Required fields" which keeps going properly, but this is a not very useful approach for at least three reasons: (i) is not very efficient, (ii) is prone to typing mistakes, (iii) if I want to add a new column to the entries of this citation, I will not be able to do so.

In some other times, JabRef allows me to copy the citation into the "Show/Edit Bibtex Source" pane, but does not allow me to change anything in the entries of this citation. It gets stuck again.

Once again, if I restart JabRef everything works perfectly for sometime, but then the same problem keeps coming back. 

JabRef is a magic piece of software. This small bug is just annoying.

**Comment by Siedlerchr** [comment]
Thanks for your report.  We will check that
 Did you know that you can also directly paste the bibtex on the main table?
JabRef will then automatically create a new entry from the pasted bibtex.

**Comment by VivaldoMendes** [comment]
Thanks for helping. 

No I did not know that. I have just used the "New entry" button, then choose the ID type, then copy+past into the box dialog (e.g. the DOI code), and a new citation entry is generated. But I do not know to insert a Bibtex citation directly into the **main table**.  If JabRef is already magical as I know it, that would be awesome.

Let me try to help a little bit more, concerning the "getting stuck" thing. It does not happen when we start JabRef. It happens after the program has been working for a while. I have also tried to see if after any new entry, I save the file. But the problem keeps coming because we are not working with JabRef on a permanent basis. There are breaks .... and then.

**Comment by Siedlerchr** [comment]
You can also paste the DOI direcly on the maintable and JabRef performs the lookup also automatically.

**Comment by VivaldoMendes** [comment]
It works. Wonderful.

**Comment by VivaldoMendes** [comment]
Sorry, I am a newcomer to JabRef, so it turns out I have too many doubts.

If by mistake, I attach two files to a particular BibTex entry, how do I correct this mistake? I see that in the "File annotations" pane, I can find the code used to attach those two files. The only thing is that I am not allowed to edit the code inside the "File annotations" pane. 

Obviously, I can delete this particular entry and create a new one, with the correct linked file. But if, somehow the pane above could be edited, mistakes could be corrected more easily.

Thanks a lot.

**Comment by mlep** [comment]
Go to the tab "General". There, you will find the field "file". By right-clicking on a filename, you can delete the link.
Note: for help demands, the use of https://discourse.jabref.org/c/help/ is preferred

**Comment by VivaldoMendes** [comment]
That's great. Easy and efficient. Terrific.
Thank's.

**Comment by koppor** [comment]
@VivaldoMendes Please try JabRef 5.1. Feel free to reopen this issue if the problem persists.
