### ISSUE TITLE
How to install the 5.0 release aside the dev Snapshot?

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#6094]
I have the 5.1 dev-snapshot installed and wanted to install the 5.0 release side by side. This seems not possible. The 4.1 release had been well installed along side the 5.0 devs. Is there a way to have both versions installed? 5.1dev and 5.0 ?

**Comment by mlep** [comment]
Under Linux, I could install version 5.0 with the regular package, while I am running the version 5.1 using the portable version available at https://builds.jabref.org/master/

**Comment by bernhard-kleine** [comment]
The installer refuses to install the release since a higher version is already installed!

**Comment by mlep** [comment]
Under Linux, the portable version is not really "installed". The file is simply uncompressed, and the executable is then launched via a command line.
For win10, JabRef-5.1-portable_windows.zip

**Comment by bernhard-kleine** [comment]
It actually worked under win10, too.

**Comment by koppor** [comment]
@mlep or @bernhard-kleine - Could you add a howto to https://github.com/JabRef/user-documentation/blob/master/en/faq/faqgeneral.md? "Q: How to install the 5.0 release aside the dev Snapshot?" 😇

**Comment by mlep** [comment]
@bernhard-kleine I have just added an Q-R about your issue. Please, could you review it?

**Comment by bernhard-kleine** [comment]
Could be closed!
