### ISSUE TITLE
Two versions of Jabref 5.1. while "listen to remote operation on port" 6500 is checked

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#6095]
JabRef 5.1--2020-03-10--d5ee20b
Windows 10 10.0 amd64 
Java 13.0.2
- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. I load jabref from the toolbar.
2. Another loading from start menu resulted in a second jabref instance if the same program
3. 

![grafik](https://user-images.githubusercontent.com/9216487/76336480-5c67ba00-62f6-11ea-9ad9-53c12a9abd07.png)
The advance -> listen to remote operation on port 6500 is checked.
![grafik](https://user-images.githubusercontent.com/9216487/76336611-8d47ef00-62f6-11ea-90f9-41223cdfa07a.png)
         
<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Can you please test if this is still an issue in the latest master version? 
https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by koppor** [comment]
@bernhard-kleine May I ask for an update?

**Comment by bernhard-kleine** [comment]
Soory I missed the status change.

No, I tested it today. The bug is not happy any longer. Can be closed.
