### ISSUE TITLE
5.x snapshots: "Year" field not included in bibtex source and document

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6096]
These are questions about the 5.x development version, not the stable release.

I've entered a couple of dozen references in the database and today cited one in a lyx document. The bibliography did not display the year of the publication (with the display style in lyx set to authoryear4). When I looked at the bibtex source it had the date field but not the year field so I added the latter and now the publication date appears in the bibliography. I've no more references to enter and ask someone to test this and see if the year field is added to the bibtex source as well as the date field.

While researching this glitch I noticed that when I look at a reference's data entry field the bibtex source field is labeled 'biblatex source', not 'bibtex source'. In Options -> Preferences -> General I've selected 'BIBTEX' as the Default bibliography mode. Shouldn't the data entry field title match the selected mode?

**Comment by rs-aesi** [comment]
I forgot to mention that the document type is Tech Report. Other tech reports have both the 'optional fields' tab and an 'other fields' tab, but this one does not, only 'optional fields'

**Comment by tobiasdiez** [comment]
The mode (bibtex vs biblatex) can be changed under Library > Library properties.

**Comment by rs-aesi** [comment]
On Tue, 10 Mar 2020, Tobias Diez wrote:

> The mode (bibtex vs biblatex) can be changed under Library > Library properties.

Thanks, Tobias. I had not seen that.

Regards,

Rich
