### ISSUE TITLE
Error: Could not find or load main class org.jabref.JabRefMain Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by zenny** [JabRef/jabref#6098]
Hi,

```
$ java -jar JabRef-4.3.1.jar
Error: Could not find or load main class org.jabref.JabRefMain
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```
I am in voidlinux with java 11:

```
$ java --version
openjdk 11.0.5-internal 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-internal+11-adhoc..jdk11u-jdk-11.0.510)
OpenJDK 64-Bit Server VM (build 11.0.5-internal+11-adhoc..jdk11u-jdk-11.0.510, mixed mode)
```
There is nothing like javafx as advised in https://github.com/JabRef/jabref/issues/2867#issuecomment-303979350 which points to a page that does not exist, fyi.

UPDATE:

However, after much searching, I got an impression from https://docs.jabref.org/faq/faqs-on-operating-systems/faqlinux that JabRef 4.xx does not work with java requires Java 8. Whereas Jabref 5 requires Java 13.

But I tried with openjdk8 first with the same error and that is the reason I updated to openjdk11, fyi.

Any clue?

Cheers,
/z

**Comment by Siedlerchr** [comment]
JabRef 4.3.x requires java 8 and openjfx 8 and is no longer supported.
JabRef 5 ships with all necessary java libraries.
You can download JabRef 5 here.
https://www.fosshub.com/JabRef.html
