### ISSUE TITLE
crash when clicking on menu

### ISSUE THREAD

**Issue by nicfreeman1209** [JabRef/jabref#6100]
I can run jabref, but as soon as i try to click on any of the drop down menus, it crashes and exits. See attached log file.
[hs_err_pid11604.log](https://github.com/JabRef/jabref/files/4317785/hs_err_pid11604.log)

**Comment by Siedlerchr** [comment]
Can you always reproduce this error or was this only one time? Every menu or only a single menu?
The crash log shows that it happened somewhere outside  JabRef and crashed the java process, in the graphic driver. I found this forum post of another software:
Maybe you have some other program running that interferes with the graphics driver?
https://community.cryptomator.org/t/cryptomator-desktop-crash-after-1-4-15-update-exception-illegal-instruction-0xc000001d-d3d9-dll/4313

**Comment by nicfreeman1209** [comment]
Thanks - indeed, I use RivaTuner.
