### ISSUE TITLE
Readstatus: in dedicated field but also in keywords

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6105]
JabRef 5.0--2020-03-06--2e6f433
Linux 4.9.0-12-amd64 amd64 
Java 13.0.2

When setting the "ReadStatus" of an entry (to "read" or to "skimmed"), the status is saved in the "readstatus" field (which makes sense), but also in the "keywords" field (which looks weird).

1.Set the read status of an entry to "read"
2. Go  to the tab "BibTeX source"
==> you find the lines: 

    keywords   = {read},
    readstatus = {read},

**Comment by Siedlerchr** [comment]
There is a setting in the preferences:
Entry table columns: Special field status
- Sync with keywords 

which is probably enabeld.

**Comment by mlep** [comment]
Indeed!
Sorry for noise. Closing...
