### ISSUE TITLE
No display over dual screen remote desktop connection

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#6124]
I'm connecting my home dual monitor machine to my work dual monitor machine (both Windows 10).  If I set up the remote desktop connection to display both work screens  on both home screens, then JabRef will start on the work computer, but not display anything on either home screeen.  If, on the other hand, I set up the remote desktop connection so that both work screens are displayed on only one home screen, then JabRef works correctly.  JabRef is the only program I've noticed that has this problem.

**"Starts but does not display"**
There is no JabRef user interface display.  The only evidence that JabRef is running is that the JabRef task bar icon is highlighted as it is when JabRef runs normally, and that JabRef shows up in Task Manager.   

**How to set up the dual screen to dual screen connection**
Tick the "Use all my monitors for remote session" in the display options of the home machine's Remote Desktop Connection startup window.

**JabRef Version**
JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2

**Windows Version**:  Windows 10.0.18363 Build 18363

**Comment by Siedlerchr** [comment]
@notuntoward  I found this related bug reports, seems to be a problem with the HW renderer
https://bugs.openjdk.java.net/browse/JDK-8118805
Could you try this? You need to modify the bat file and add the parameters behind the java command

**Comment by notuntoward** [comment]
Unfortunately this didn't change anything.  
In:
`C:\Program Files\JabRef\runtime\bin\JabRef.bat`
I changed the last line from this:
`pushd %DIR% & %JAVA_EXEC%  "%~dp0/../app" -m org.jabref/org.jabref.JabRefLauncher  %* & popd`
to this
`pushd %DIR% & %JAVA_EXEC%  "-Dprism.order=sw,j2d" -p "%~dp0/../app" -m org.jabref/org.jabref.JabRefLauncher  %* & popd
`
but JabRef still does not display if I set up a dual screen Remote Desktop Connection

**Comment by notuntoward** [comment]
Hey @Siedlerchr, I'm getting a "this issue will be removed because you haven't answered a question" warning, yet I _have_ answered the question.  Do you need anything else?
