### ISSUE TITLE
2.11 icons: How to retrieve these into 3.1

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#613]
I wonder if it would be possible to have the old icons back?

Kind regards and Happy New Year!

Bernhard

**Comment by koppor** [comment]
We ran out of icons for new functionality and therefore searched for a long-term solution. #130 and #230 show the discussion a bit.

Do you find the new icons too indistinguishable in comparison to [the old ones](https://upload.wikimedia.org/wikipedia/commons/0/0f/Jabref-ScreenShot-MainWindow.png)? Could you provide us with some motivation of your feature request?

**Comment by bernhard-kleine** [comment]
Am 01.01.2016 um 14:32 schrieb Oliver Kopp:
> We ran out of icons for new functionality and therefore searched for a
> long-term solution. #130 <https://github.com/JabRef/jabref/issues/130>
> and #230 <https://github.com/JabRef/jabref/pull/230> show the discussion
> a bit.
> 
> Do you find the new icons too indistinguishable in comparison to the old
> ones
> <https://upload.wikimedia.org/wikipedia/commons/0/0f/Jabref-ScreenShot-MainWindow.png>?
> Could you provide us with some motivation of your feature request?
> 
I find especially the icons for "pdf", "html" and "doi" in the new
version lacking distinction in the color, every things is green now, not
very distinguishing.

Bernhard

**Comment by koppor** [comment]
You mean the icons discussed at #598? Would it be enough to offer different colors depending on the type? In other words: The distinction by the icons is not good enough for your needs, you ask for a second distinguishing factor in the context of file types?

**Comment by lc9275** [comment]
I also miss the old Jabref icons, however perhaps it is just a question of getting used to the new ones. Different colors would definitely brighten up the interface though.

One request: would it be possible to have different icons for doi and html like before? Currently they are both the same, so there is no way of telling whether it is the doi or the html which is displayed. I find this distinction quite helpful - e.g. it can be used to see immediately which items have a missing doi. I am not sure if there is a suitable icon on materialdesignicons.com for the doi. Perhaps "code-brackets" or "Disqus"?

**Comment by stefan-kolb** [comment]
@lc9275 We are discussing your request in #696

**Comment by jkomelj** [comment]
Are icons in JabRef 3.2 on 32- or 64-bit Windows intentionally mono-colored or is this a bug?

Janez Komelj

![clipboard02](https://cloud.githubusercontent.com/assets/16426183/13372370/10681f80-dd41-11e5-9989-364c3ff64ba6.png)

**Comment by mlep** [comment]
This is intentional.

**Comment by NikoKrause** [comment]
Could there be implemented an option to get the old (3D) icons back?
Maybe add a checkbox under Options -> Settings -> Appearance -> Use old 3D icons

The new icons are flat and monochrome. I can get used to the new icons, but still it would be great if I at least had the chance to choose between old and new ones.

**Comment by koppor** [comment]
If you find someone who a) is willing to provide icons for all actions (there are quite a few new ones) for until at least 2018 and b) is willing to implement the style switch, be our guest. Otherwise, I really fear that we have not enough resources to maintain two different icon sets. We are trying to focus on the opened issues, then work on the feature requests on discourse, then to work on https://github.com/JabRef/jabref/wiki/FeatureRequests-Sorted and then to dig on the old sourceforge trackers if we forgot something. In parallel, we try to cleanup the code (see https://github.com/JabRef/jabref/wiki/Development-Strategy). However, we really totally welcome new contributors working on something immediately visible for all users.

**Comment by NikoKrause** [comment]
I see you have a lot to do. Like I said, I can get used to the new icons. It was only a suggestion.

Can you tell me were the icons are stored?
I only found the external icons for emacs, texstudio, etc.

**Comment by Siedlerchr** [comment]
@NikoKrause  The icons are from [materialdesign](https://materialdesignicons.com/) webfont and are loaded in this class::
https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/gui/IconTheme.java
