### ISSUE TITLE
Copy paste selection from bibtex source not working 

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#6134]
JabRef version 5 on Mac OS X 10.14

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When copying something selected (like the key of the entry) from the bibtex source of an entry, it actually copies the whole entry.

1. Copy something selected
2. Paste

**Comment by Siedlerchr** [comment]
On Windows this works fine,  only the highlighted text is copied, so it might be some Mac behavior.

**Comment by domhardt** [comment]
I had the same problem. I deleted the key binding for Edit -> Copy. The key bindings could be modified under Options -> Customize key bindings. The icon on the right is unclear and backspace will do nothing but the delete key worked.

JabRef 5.0--2020-03-06--2e6f433
Mac OS X 10.14.6 x86_64 
Java 13.0.2
<img width="519" alt="Bildschirmfoto 2020-04-24 um 12 42 30" src="https://user-images.githubusercontent.com/1955290/80204438-24f46900-8629-11ea-858c-e99b06b0cc26.png">

**Comment by Siedlerchr** [comment]
@domhardt  The right icon is to reset the key bindings. Then you can enter a new one by pressing the key combination

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by rcmusgrave** [comment]
@Siedlerchr I was also having the problem with pasting bibtex source in 5.1, and this seems to be solved in the development version of 5.2 that I just downloaded.
