### ISSUE TITLE
Version 3.1 no autosort

### ISSUE THREAD

**Issue by HainesB** [JabRef/jabref#614]
When a database is saved, entries are not sorted.

For example, in one database, it starts with a set of 66 entires sorted by author, then a set of 42 sorted by author, and then a set of 3267 entries sorted by author, and finally at the end a single entry of a work just entered.

**Comment by oscargus** [comment]
Just to double-check: in Preferences -> Save sort order, have you selected "Save entries ordered as specified"? (Last of the radio buttons in case you use a translated version.)

**Comment by HainesB** [comment]
Yes. In Preference, File Sorting, Save sort order, Save entries ordered as specified, I have selected "author" as primary criterion, descending.

**Comment by lenhard** [comment]
Auto sorting will be removed soon anyway. I think we should direct our scarce resources to other issues.

**Comment by lenhard** [comment]
The global sorting options have been removed in #711 Therefore, I am closing this issue.

To reenable sorting for your database in a newer version of JabRef, please right-click on your database tab, select database properties and there you have the usual dialog, which you can configure. If your problem persists with the file local sorting options, please reopen this issue.
