### ISSUE TITLE
Improve display of groups and keywords in entry editor

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#6140]
Our custom `TagBar` should be replaced by the [ChipView](https://github.com/jfoenixadmin/JFoenix/blob/master/demo/src/main/java/demos/gui/uicomponents/ChipViewController.java) of [jfoenix](https://github.com/jfoenixadmin/JFoenix) and this control should be used to display groups and keywords in the entry editor.
![image](https://camo.githubusercontent.com/bf8b04f92786534da2763b69a800c650766cd89b/687474703a2f2f6a666f656e69782e636f6d2f6769662f63686970766965772e676966)

(Related Javascript library: https://dragonofmercy.github.io/Tokenize2/)

**Comment by dextep** [comment]
I'd like to work on that. It's will be my first issue so im open to additional tips :)

**Comment by tobiasdiez** [comment]
Thanks for your interest @dextep! First of all have a look at our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and follow the instructions given there to setup a local working environment. 

Coding-wise: The editor for the `keyword` field is described here https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/fieldeditors/KeywordsEditor.java. As of now this class is very simple. A good starting point is probably to migrate the related https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/fieldeditors/LinkedEntriesEditor.java to the `ChipView` instead of the `TagBar`. 

Please create a PR as soon as possible so that we can discuss your progress and give early feedback. Moreover, feel free to drop by in our [developer chat](https://gitter.im/JabRef/jabref) if you have questions! Finally: Happy Coding! 🎉

**Comment by dextep** [comment]
Should i continue this issue?

**Comment by AEgit** [comment]
Note, that such a feature should also be able to handle databases which contain thousands of groups (looking at the autocompletion feature displayed in the original post) and items which have been assigned to 30 or 50 groups simultaneously. The group name should always be visible.

I am just putting this here so that developer are aware of these use cases.
