### ISSUE TITLE
Unable to install JabRef version 5.0

### ISSUE THREAD

**Issue by ihesham** [JabRef/jabref#6141]
I have been using JabRef for many years as my biblography manager. I work on windows system (WIN10, now ver. 1909). I noticed the JabRef  update installer file this time was given as msi  `file JabRef-5.0.msi` rather than the usual exe extension `JabRef_windows-x64_4_3_1.exe` used in previous updates.

When trying to install the new update file `JabRef-5.0.msi`, the following error message is displayed

>   _There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor._

![pNH6m](https://user-images.githubusercontent.com/62292276/76858792-377cc500-6869-11ea-9b3e-1d2b62b85667.png)

When clicking OK and Next, the setup is finished without installing anything.

The following solutions have been tried: 

1. Empty internet temporary folder.
2.  Update Java to the recent version `jre-8u241-windows-x64`.
3. Uninstall old version and reinstall the new one.

None of them worked.

**Is there any idea what's wrong?**

**Comment by tobiasdiez** [comment]
Could you please create a detailed installation log (e.g [as described here](https://www.advancedinstaller.com/user-guide/qa-log.html)) so that we can see which particular library is missing for the installer. Thanks

**Comment by ihesham** [comment]
Thanks for your reply.
This is the log file created as described above.

[JabRef-5.0.log](https://github.com/JabRef/jabref/files/4343941/JabRef-5.0.log)

**Comment by ihesham** [comment]
The problem is solved by opening `cmd` as admin, then running the installer with the command `msiexec /i "path\to\JabRef-5.0.msi"`

**Comment by tobiasdiez** [comment]
The log points to 
> Error 1723. There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor.  Action JpCheckInstallDir, entry: CheckInstallDir

The JpCheckInstallDir action is a standard widget from WiX toolset (the tool that we use to create the installer).  So I doubt that there is a problem with the code.

A few ideas:
- Try to re-download the installer
- Try to invoke the installer from a different folder
- "Property(C): TARGETDIR = F:\", maybe the target folder does not exist?
- Try to disable the antivirus before installing


EDIT: Ok! Happy to hear!
