### ISSUE TITLE
Add icon picker in group edit dialog

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#6142]
As noted recently, the user has to manually lookup the icon-code and put it in the "Edit group" dialog. Instead, we should show a (searchable) list of all available icons.

Example for how the UI can look like: https://itsjavi.com/fontawesome-iconpicker/ (and maybe https://dmdc0de.github.io/material-ui-icon-picker/ )
![image](https://user-images.githubusercontent.com/5037600/111888463-0cc5cf00-89dd-11eb-8788-e0da0c74f7ae.png)

Example code for a similar implementation in JavaFX: https://github.com/kordamp/ikonli/blob/18b3fb679d358801f5730352014cdbc780aff31a/apps/sampler-javafx/src/main/java/org/kordamp/ikonli/sampler/javafx/Sampler.java#L131-L153

**Comment by Siedlerchr** [comment]
Refs #7058

**Comment by Siedlerchr** [comment]
As the switch from fontawesomefx to Ikonli is now finished it should be relatively easy to implement an icon picker dialog.
Example from the Ikonli project can probably be adapted
 https://github.com/kordamp/ikonli/blob/master/apps/ikonli-browser/src/main/java/org/kordamp/ikonli/browser/IkonPickerDialog.java

**Comment by aakarshvats638** [comment]
I would like to work on this issue can you please elaborate what is to be done?

**Comment by tobiasdiez** [comment]
Thanks for your interest. When you right-click a group and choose "Edit group" you get an dialog with an "icon" text field (among other input fields). Right now the user needs to put the name of the icon in this text field. It would be good if there would be a graphical input possibility, similar to 
![image](https://user-images.githubusercontent.com/5037600/111888455-f9b2ff00-89dc-11eb-9bdd-4ff25048fcc9.png)

(taken from the link in the issue description)

**Comment by srdeotarse** [comment]
I want to participate in GSOC 2021, so I would like to work on this issue with dropdown icon combobox as suggested by @tobiasdiez @Siedlerchr

**Comment by tobiasdiez** [comment]
@srdeotarse Thanks for your interest! @aakarshvats638 do you still plan to work on this, or even already started?

**Comment by NicholasBian** [comment]
Hi! We are a group of 4 students from the University of Adelaide, and we are learning to contribute to open source projects. Is anyone currently working on this issue? If not, we'd like to help with this issue. Any guidance would be appreciated. Cheers!

**Comment by EricLee543** [comment]
![image](https://user-images.githubusercontent.com/43877209/118869342-d8588b80-b917-11eb-9120-f63bb14f481d.png)
I have implemented a simple demo like this. However, there is a problem. I can only load 1000 icons. If I load all of the icons, there will be UI lags.
Do you think 1000 icons are enough? Maybe we can keep the previous way, and  add a limited(1000 icons) icon picker.

**Comment by tobiasdiez** [comment]
That looks very nice! Good job.

Concerning the performance problem, how did you implement the grid? It might be necessary to use something like https://github.com/FXMisc/Flowless to not create 1000 buttons but only a couple (essentially what fits in the display) and reuse them when scrolling. I would suggest you open a draft PR where we can discuss these things.
