### ISSUE TITLE
":PDF" will not show the pdf icon in the 

### ISSUE THREAD

**Issue by ShuguangSun** [JabRef/jabref#6169]
JabRef version JabRef 5.1--2020-03-10--43f533b on Windows 10 10.0 amd64 Java 13.0.2

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add a file to General => File, which will add a file field looking like 
   `file      = {:STAT/aa.pdf:PDF},`
2. It will show an unrecognized file type icon in the linked files column instead of the pdf type icon (although it will open the pdf file using the proper reader)
3. Change it to `file      = {:STAT/aa.pdf:pdf},`, the pdf type icon will be shown.

**Comment by Siedlerchr** [comment]
Thanks for your report, looks like this was missed in #6119

**Comment by leitianjian** [comment]
Hi, We're a team of 5 students currently attempting to make our first open-source contribution, and we want to firstly work on this bug

We have reproduced this bug successfully. Because it is our first time trying to participate in this project. I would be grateful if any hint can be provided. And I am trying to get more familiar with this project. A question is, how long could we take to fix this bug?

**Comment by Siedlerchr** [comment]
Thanks for your interest in contributing to JabRef!
Please follow our contribution guide https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

There is no hurry in finishing. Take your time to make yourself familiar with the code. Just create a PR with your changes early on, so we can provide constant feedback.
Code wise, as a hint you should check the pr I linked in the comments which probably introduced this bug

**Comment by leitianjian** [comment]
Ok, I will check the material carefully.

"Just create a PR with your changes early on" means that we can create a PR before we fix the bug and let you know our progress or comment on our code?
Thanks for your reply, I will check the PR you linked carefully

**Comment by dimitra-karadima** [comment]
@leitianjian Yes! You can create a PR even if you haven't fixed the bug in order to get a feedback on your code! Check the draft PRs: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by leitianjian** [comment]
@dimitra-karadima Thanks for your reply and sorry for my late comment. I am working on it, If there are some difficulties I cannot solve, I will create a PR and get some feedback

**Comment by leitianjian** [comment]
Hi, I have fixed the bug of the icon. Please check my draft pull request, thanks

**Comment by tobiasdiez** [comment]
See also my comment in https://github.com/JabRef/jabref/blob/fb2a6d7612b1651d2b41a3de3e6fe17f5f4c8d49/src/main/java/org/jabref/gui/StateManager.java#L39

**Comment by tobiasdiez** [comment]
Thanks to @leitianjian (and his crew) this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
