### ISSUE TITLE
Enter in global search should open the selected entry

### ISSUE THREAD

**Issue by HainesB** [JabRef/jabref#617]
<s>It is possible to bring up the search field with C-f to enter a search term. But it is not obvious how to activate "search globally" except with the use of the mouse. When the global search button is clicked with the mouse, it returns a message that "No results found" even though a "Search results" window pops up that displays the search term.</s>

Context (added by @koppor): Opened global search:

![grabbed_20160408-080008](https://cloud.githubusercontent.com/assets/1366654/14375267/f6458748-fd5f-11e5-9274-d5e9a31821c4.png)

In that window, when the `ENTER` key is hit, instead of the entry being displayed in the main window, the next item in the Search results window is selected, the same as the down arrow. So the only way to display the selected search result is to double click it with the mouse, for the operation does not seem bound to any keys.

**Comment by koppor** [comment]
In short:

`ENTER` in the global search should function as double click, not as `ARROW DOWN`.

**Comment by koppor** [comment]
@HainesB The latest development build (http://builds.jabref.org/master/) does not show the popup "no search results found" any more. - Your first concern is tracked at #573. - I reformulated your request to describe the last concern. - I hope that I understood everything now and that it is OK for you to update your description.

**Comment by teertinker** [comment]
#825 
-> a double-click does (e.g. after a global search in bib2.bib) not even show the entry in case the result refers to an entry that has been filtered away in a previous local search (e.g. bib1.bib)

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version.
Please use a development build from http://builds.jabref.org/master
The fix will be included in the next release.

We are well aware, that <kbd>cursor up</kbd> and <kbd>cursor down</kbd> does not work as expected in the global search dialog. @bartsch-dev takes care.
