### ISSUE TITLE
Group color, only display identical colors once

### ISSUE THREAD

**Issue by Yery** [JabRef/jabref#6175]
Suppose i have the following Categories and Subcategories
Category: Food: Subcategory: Nuts
Category: Trees: Subcategory: Nut trees

Now it is possible (and makes sense) to assign a single colour to both subcategory Nuts and Nut trees.  Some papers however, will naturally be categorized in both groups. In such instances, Jabref currently displays twice the colour in the main table (in the column group color). Would it be possible to only display the unique colours?

I hope this (rather contrived) example is clear.  Please let me know if not!

**Comment by WangAooa** [comment]
Hi, I'd like to contribute to this issue.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I were not intending to contribute to this issue.  I am just wondering if it makes sense to have some kind of sort based on color as distinct() and similar solutions are not stable?

**Comment by LuckyOne09** [comment]
I am wondering the meaning of this issue because I think it is reasonable to display multiple colors if this paper belongs to multiple subgroups. If you want to display only one color, how to choose the color from multiple groups it is in?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
If I understand @Yery correctly different colors should be displayed as long as they are distinct?

**Comment by Yery** [comment]
@k3KAW8Pnf7mkmdSMPHz27   
Thanks, yes, that is what I meant. It is of course good to see different colours, the issue is on merging  multiple identical colours.

**Comment by LuckyOne09** [comment]
@k3KAW8Pnf7mkmdSMPHz27 @Yery  Thanks for your explanations, but since it is possible that users give identical colors to two groups which are not relevant, I think it is troublesome to distinguish which identical colors should be merged and which should not.

**Comment by Yery** [comment]
To me it simply doesn't make sense to have two or three times the same colour, and these should always be merged, otherwise the user should use different colours. The example I gave illustrates a situation where a user would want to chose the same colour (and would like to have them merged). For my user case, I would use this feature a lot.

**Comment by WangAooa** [comment]
So, can I combine all colors together and provide a new color if it has multiple colors? I'm a little confused about the above discussion.

**Comment by Siedlerchr** [comment]
I think the main point is that we are talking about subgroups

**Comment by Yery** [comment]
Sorry this is confusing, but this issue is just about merging identical colours (so not displaying them twice, which looks silly), so:

red | red = red
red |  green | blue = red |  green | blue
red | green | red = red | green
