### ISSUE TITLE
Select library during import

### ISSUE THREAD

**Issue by jorgman1** [JabRef/jabref#6177]
Would it be possible to select the library into which the entry is imported?

I often have several libraries open at the same time, and I have to switch to the desired library before importing (something that I often forget).

**Comment by jorgman1** [comment]
issue is still relevant

**Comment by JofielB** [comment]
Hello, just to be sure the desire solution would be something like this:
1. create or open at least 2 libraries 
2. Make a web search for anything 
3. Select 1 or more things you want to important 
4.  Start importing 
4.  **A dialog view appears and asks you in what library you want to make the imports (solution)**
5. The imports are done

**Comment by jorgman1** [comment]
Something like that. The button to select the library could be in the current import window. It is large. Or it could be a dropdown list.

**Comment by JofielB** [comment]
Nice, I am gonna try to add that dropdown to the Import window

**Comment by JofielB** [comment]
I don't gonna be able to continue working on this issue but for the ones that may take this issue in the future I will leave the following tips:
- You can change the import window design to add the dropdown at this file: `ImportEntriesDialog.fxml`
- The `ImportEntriesDialog.fxml` has assigned the `ImportEntriesDialog.java` as a controller
- Another import file to check is the `ImportEntriesViewModel.java`
- Read how the MVVM pattern works to understand how the:  `ImportEntriesDialog.fxml`, `ImportEntriesDialog.java` and the `ImportEntriesViewModel.java` files are connected

**Comment by mohit038** [comment]
I think fixing this issue will create another issue related to duplicate entries. Bc in the current implementation, after fetching data from the web, jabref compares those imported entries with the current context to find duplicates. If you change the library after the import, it has to compare it again, and also if the newly selected library has groups, then In which group entries should be imported.

<img width="1440" alt="Screenshot 2021-04-02 at 7 46 55 AM" src="https://user-images.githubusercontent.com/62339705/113373112-cb8fd080-9387-11eb-9d6f-fc76aba88fe8.png">

**Comment by tp-1000** [comment]
@mohit038 I think you're right. I don't know how implementation would be but what about at least adding an undo to recover from a bad import??

**Comment by mohit038** [comment]
@tp-1000 That's a really good idea. How about adding an undo button in the toast message.


<img width="682" alt="Screenshot 2021-04-02 at 12 29 12 PM" src="https://user-images.githubusercontent.com/62339705/113390388-3c96ae80-93af-11eb-95d7-c8e8d6e5393c.png">

**Comment by tp-1000** [comment]
@mohit038 Seems like if it was set up to handle undo it would make sense to take advantage of the existing architecture – the mainMenu or Keyshort cut. Toast only last so long and could be missed.

**Comment by Siedlerchr** [comment]
@jorgman1  Thanks to the work from @MaryJml  it is now implemented in the latest development version (6.0) https://builds.jabref.org/main/ 
and will be ready in roughly 20 minutes

**Comment by jorgman1** [comment]
Thank you very much. It works like a charm! :)
