### ISSUE TITLE
[Code] Get rid of StringInt class

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#618]
The `StringInt` class is very strange and not documented.

Usage of the `i` of it is mostly following follwing pattern:

    parsedEntry.i == LayoutHelper.IS_LAYOUT_TEXT

Therefore, enums should be used and the whole class deleted.

**Comment by oscargus** [comment]
I increase the usage of it in #610 (RTFChars) and removed the local class IntAndString. :-)

**Comment by stefan-kolb** [comment]
#610 is merged so this could be closed @simonharrer
