### ISSUE TITLE
Groups panel does not keep size when resizing window

### ISSUE THREAD

**Issue by reox** [JabRef/jabref#6180]
JabRef version 
```
JabRef 5.1--2020-03-23--67daf36
Linux 5.4.0-4-amd64 amd64 
Java 14
```
Debian bullseye/sid with i3 window manager.

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Before, the groups panel would stay at it's size when the window is resized.
Now, it seems to scale proportionally with the whole window.
This is especially annoying when a tiling window manager is used and you open a PDF next to jabref: in this case the groups panel scales to about 50% of the whole window.

1. resize jabref window
2. groups panel scales proportionally instead of keep size

**Comment by tobiasdiez** [comment]
Thanks to @Hollyqqqqq this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by reox** [comment]
I tested with
```
JabRef 5.1--2020-05-16--cb50b50
Linux 5.6.0-1-amd64 amd64 
Java 14.0.1
```
and it seems to be fixed for me!
thanks you!
