### ISSUE TITLE
Import Dialog should show BibTeX entry

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6182]
Current "Import Dialog"

![grafik](https://user-images.githubusercontent.com/1366654/77678799-fdf73880-6f91-11ea-9dcc-f8f041bc4ec3.png)

When clicking on an entry, I expect the BibTeX source to be shown.

**Comment by tobiasdiez** [comment]
Why is this? Is it rarely the case that you care about the exact bibtex code you import, right?

**Comment by koppor** [comment]
Similar to the `<details>` thing of GitHub. Gives more control for the users new to JabRef and not fully trusting it 😅

**Comment by koppor** [comment]
Alternatively, 

- do not show the dialog when importing entries via "File -> Import"
- Add the new entries to a group "Imported Entries"

**Comment by tobiasdiez** [comment]
I still have trouble seeing the use case. The purpose of the import dialog is to let the user decide which entries to import, and I don't see why the bibtex code should matter for this. Normally, you either want to import all entries or a subset. So the important part is that the user is able to identify the relevant entries as quickly as possible. 

> Add the new entries to a group "Imported Entries"
That's a good suggestion in my opinion (maybe have a group "Last import" and then reuse it)

**Comment by systemoperator** [comment]
Zotero allows defining really powerful filters. I created e.g. one called "recently added", which covers the last 7 days. (The numeric value can be set freely. Possible time units are days, months, years. Several filter constraints can be defined at once.)

![image](https://user-images.githubusercontent.com/3658393/77797517-7e409b00-7071-11ea-9579-48d993e0b9e3.png)

![image](https://user-images.githubusercontent.com/3658393/77797819-0757d200-7072-11ea-8ea7-2b47d0123930.png)

![image](https://user-images.githubusercontent.com/3658393/77797777-f27b3e80-7071-11ea-87ce-d121e0f27c9a.png)

Match all or match any.

**Comment by koppor** [comment]
At this place I really wondered whether my .bib file is broken or if JabRef is broken. Thus, I wished, I could inspect the raw data within JabRef. I was too lazy to open my text editor. Next time, I will just open my text editor to inspect the `.bib` file.

@systemoperator Could you comment that at #4475?
