### ISSUE TITLE
Add posibility to explore citation relations

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#6187]
Add the possibility to find (and easily add) papers that cite or are cited by a a given paper (or a couple of paper).

Here are a bunch of links that might be relevant/helpful:
- http://api.semantischolar.org/
- https://opencitations.net/index/api/v1
- http://citationgecko.com/
- https://www.yewno.com/discover
- https://openknowledgemaps.org/
- http://wikicite.org/
- https://www.scholarcy.com/
- https://www.dimensions.ai/dimensions-apis/
- https://www.springernature.com/gp/researchers/bookmetrix
- (https://github.com/adsabs/adsabs-dev-api)

**Comment by koppor** [comment]
Internally, JabRef stores this information by the field "`cites`". See https://docs.jabref.org/advanced/entryeditor/entrylinks for details.

**Comment by koppor** [comment]
Related work: "showme". Details at https://github.com/koppor/jabref/issues/413.

**Comment by koppor** [comment]
Work in progress at: https://github.com/JabRef/jabref/pull/7160

**Comment by tobiasdiez** [comment]
Marking this as frozen since none of the above APIs is really suitable so this is best implemented with JabRef Online (help there is of course appreciated).
