### ISSUE TITLE
Create a group from list of entry ids

### ISSUE THREAD

**Issue by smihael** [JabRef/jabref#6192]
Please add a possibility to create a group based on a list of entry IDs. This would function similar to aux import, but would be useful to create static groups. It would be especially useful when you don't have the aux file anymore.

**Comment by tobiasdiez** [comment]
You can already create a manual group which contains only entries added by hand. Thus simply search for the relevant entry and drag & drop it on the manual group to add it.

**Comment by smihael** [comment]
What if you have a list of say twenty entries and you don't want to search each separatelly?

**Comment by Siedlerchr** [comment]
You can select all and drag them to the group.

**Comment by smihael** [comment]
This still means that you have to manually select them. Search bar does not allow user to input a list of queries.

**Comment by tobiasdiez** [comment]
Searching for `bibtexkey == miller2005 or bibtexkey == miller2006` should show both entries (not sure if the `bibtexkey ==` part is actually necessary.
