### ISSUE TITLE
Allow each row to have different colour

### ISSUE THREAD

**Issue by smihael** [JabRef/jabref#6193]
I typically work with large .bib files. Over time the file becomes a mess and it is hard to quickly find an entry. It would be fine if one could opt in to have a different background color of rows given different types of entires (journal/conf. paper, read status, ...)

Currently coloring is supported for groups, but as each entry can be assigned to multiple groups, only a small rectangle is shown in the column with a label icon.

**Comment by rafaelbalanquet** [comment]
Hello! My team and I would like to claim this issue and get to work on a solution. Let me know if this is possible.

**Comment by koppor** [comment]
Workaround is to have groups. -- currently, we have colors of groups on the left

<img width="2880" height="1658" alt="Image" src="https://github.com/user-attachments/assets/f7e168b1-0f04-4cbf-a211-f87ceba72299" />

Introduced by https://github.com/JabRef/jabref/pull/3769

---

Screenshots at https://github.com/JabRef/jabref/issues/4906#issuecomment-5410354165

---

Background:

- https://discourse.jabref.org/t/why-was-the-mark-specific-color-option-removed/1954/7
- color for imported entries: https://discourse.jabref.org/t/what-does-the-entry-colors-mean/402/9
- https://github.com/JabRef/jabref/issues/4906
