### ISSUE TITLE
Allow basic markup syntax in the comments tab

### ISSUE THREAD

**Issue by smihael** [JabRef/jabref#6194]
Currently once can write comments within the entry editor. I would suggest to support and highlight basic markdown syntax or generate a comment preview instead of the entry preview in the right pane of the tab.

**Comment by teertinker** [comment]
This feature is really great! Finally I don't have to fiddle with html tags and replace formatters to get something similar. An extension to the abstract field would be nice.

**Comment by lrhammond** [comment]
Sorry if this is a stupid question, but do you know how I can use this in the current version of JabRef? I can't find anything under 'Markdown' when I search for preview styles in the relevant preferences section. Thanks for any help!

**Comment by Siedlerchr** [comment]
make sure you have "Customized preview style"  enabled and selected Then it will be rendered automatically: 
<img width="878" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/1f87c1b6-30d3-4de7-b608-88b920feeaa9">

**Comment by lrhammond** [comment]
Hmmm... that doesn't seem to work for me. Maybe it's because I already had a customised preview style set before? In particular, it currently is:

```
\begin{author}\format[Authors(FirstLast,Initials,Comma,And),HTMLChars]{\author}<BR>,\end{author}
\begin{title}"\format[HTMLChars]{\title},"\end{title}<BR>

\begin{journal}<em>\format[HTMLChars]{\journal}</em>\end{journal}
\begin{chapter}\format[HTMLChars]{\chapter}<BR>, \end{chapter}
\begin{booktitle}in <em>\format[HTMLChars]{\booktitle}</em>\end{booktitle}

\begin{volume}<i>, (\volume</i>\end{volume}\begin{number}<i>:\number</i>\end{number}\begin{pages}<i>)</i>, Pages \format[FormatPagesForHTML]{\pages}\end{pages}

\begin{editor}, \format[Authors(FirstLast,Initials,Comma,And),HTMLChars]{\editor} <i>(\format[IfPlural(Eds.,Ed.)]{\editor})</i><BR>\end{editor}

\begin{school}, <em>\format[HTMLChars]{\school}, </em>\end{school}
\begin{institution}, <em>\format[HTMLChars]{\institution}, </em>\end{institution}

\begin{publisher}. <em>\format[HTMLChars]{\publisher}</em>\end{publisher}
\begin{year}. \year\end{year}.

\begin{note} \note.\end{note}
```

This gives the following text:

<img width="1130" alt="Screenshot 2023-08-19 at 9 34 57 pm" src="https://github.com/JabRef/jabref/assets/40001618/c25990c4-d08c-4a8c-a822-fe9556e0c992">

Could you possibly let me know what it says on your customised preview style at the moment? Maybe simply copying that across will fix the issue. Thanks very much for your help! :)

**Comment by Siedlerchr** [comment]
Ah I see, now i remember that you have to enable the Markdown formatter for the field:
You would need to add this somewhere (I am using Jabref's default style):

`\begin{comment}<BR><BR><b>Comment: </b>\format[Markdown,HTMLChars]{\comment}\end{comment}`

**Comment by lrhammond** [comment]
Fantastic, that worked – thank you!
