### ISSUE TITLE
Allow user to use system theme

### ISSUE THREAD

**Issue by smihael** [JabRef/jabref#6195]
For better integration, users should be allowed to use system theme or imitate it. On Linux this would be GTK/Qt Look-And-Feel.

**Comment by tobiasdiez** [comment]
With https://github.com/JabRef/jabref/pull/6036 users can create custom themes. We sadly don't have the resources to create theme for each OS, but feel free to provide one for GTK (as soon as the PR is merged).

**Comment by smihael** [comment]
Unfortunately I was not clear enough, what I mean by Look-And-Feel. The term relates to (possibly) obsolete swing feature (https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html), that changes the widget elements to match the OS. It is also not that much about colors but more about widget form. It seems that this used to be supported in previous versions (https://benjaminirving.github.io/blog/2013/03/19/a-few-things-about-jabref-gtk-theme-and/). I'm not sure whether themes can cover that (i.e. which elements will be theme-able by css).

**Comment by smihael** [comment]
I looked a bit deeper and found out that you transferred to JavaFX. It seems that .css for my DE of choice already exists: https://github.com/devedge/KDE-Breeze-JavaFX-CSS

**Comment by Siedlerchr** [comment]
@smihael I think controls that look like native OS is partially possible,
However, you might want to look into the Base (light) and Dark Theme: 
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/Base.css
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/Dark.css

If you run JabRef from source, modifications to the theme css will be instantly visible

The base Theme for all javafx application is Modena.css
https://github.com/openjdk/jfx/blob/master/modules/javafx.controls/src/main/resources/com/sun/javafx/scene/control/skin/modena/modena.css

And some explanation on the CSS Properties:
https://openjfx.io/javadoc/13/javafx.graphics/javafx/scene/doc-files/cssref.html
