### ISSUE TITLE
Do not store downloaded file if it is already attached

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6197]
Follow-up to https://github.com/JabRef/jabref/pull/6174

When a user downloads a PDF - and this PDF **equals** to an already attached PDF, it should not be attached again.

Possible steps:

1. `default.pdf` exists
2. Download as `default (1).pdf`.
3. Check if file content of `default.pdf` equals file content of `default (1).pdf` (Use https://guava.dev/releases/21.0/api/docs/com/google/common/io/Files.html#equal-java.io.File-java.io.File-)
4. If it is equal, just delete `default (1).pdf`. Show notification that already linked. Finish.
5. If not equal, add to linked files.

**Comment by koppor** [comment]
This issue is still relevent.

```bibtex
@Article{ALHashemy2020,
  author    = {Rageed Hussein AL{-}Hashemy and Sadiq A. Mehdi},
  journal   = {J. Intell. Syst.},
  title     = {A New Algorithm Based on Magic Square and a Novel Chaotic System for Image Encryption},
  year      = {2020},
  number    = {1},
  pages     = {1202--1215},
  volume    = {29},
  bibsource = {dblp computer science bibliography, https://dblp.org},
  biburl    = {https://dblp.org/rec/journals/jois/AL-HashemyM20.bib},
  doi       = {10.1515/jisys-2018-0404},
  file      = {:ALHashemy2020 - A New Algorithm Based on Magic Square and a Novel Chaotic System for Image Encryption (1).pdf:PDF},
}
```

Then 

![grafik](https://user-images.githubusercontent.com/1366654/101542357-f2726300-39a2-11eb-9048-13f54db0a873.png)

Then

```bibtex
@Article{ALHashemy2020,
  author    = {Rageed Hussein AL{-}Hashemy and Sadiq A. Mehdi},
  journal   = {J. Intell. Syst.},
  title     = {A New Algorithm Based on Magic Square and a Novel Chaotic System for Image Encryption},
  year      = {2020},
  number    = {1},
  pages     = {1202--1215},
  volume    = {29},
  bibsource = {dblp computer science bibliography, https://dblp.org},
  biburl    = {https://dblp.org/rec/journals/jois/AL-HashemyM20.bib},
  doi       = {10.1515/jisys-2018-0404},
  file      = {:ALHashemy2020 - A New Algorithm Based on Magic Square and a Novel Chaotic System for Image Encryption (2).pdf:PDF;:ALHashemy2020 - A New Algorithm Based on Magic Square and a Novel Chaotic System for Image Encryption (1).pdf:PDF},
}
```

**Comment by JofielB** [comment]
Hello, I would like to work on this issue

**Comment by cboyce376** [comment]
A group of us from Adelaide University are going to work on this project over the next 4 weeks.

**Comment by Pikayue11** [comment]
Hi, I think it has already been 4 weeks and I am interested in this issue. Could I try to fix it?
