### ISSUE TITLE
Rewriting of entries even without change

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#620]
When I write my bib file, many entries are rewritten even though I did not change anything. Could it be related with the special fields feature and that they are synced upon load?

![grabbed_20160102-130132](https://cloud.githubusercontent.com/assets/1366654/12074385/f62cb14c-b150-11e5-9152-b61599ff4580.png)

**Comment by lenhard** [comment]
Is fixed with 52e77df9cb7c7975421ed3c236f509194843fc0a

Please re-check and confirm!

**Comment by koppor** [comment]
:+1: - The name of the method `updateNonDisplayableField` might not be appropriate as it also affects `WriteableFields`. This is OK... We should address this in the context of #574.
