### ISSUE TITLE
Path vanishes if database is changed

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#622]
Before:

![grabbed_20160102-154207](https://cloud.githubusercontent.com/assets/1366654/12074779/63dca628-b167-11e5-8669-5acf5eac5bb3.png)

After:

![grabbed_20160102-154229](https://cloud.githubusercontent.com/assets/1366654/12074780/71a48d02-b167-11e5-892d-b3f343a34719.png)

Is it possible to just add the asterisk behind without removing the prefix?

Refs  #351

**Comment by oscargus** [comment]
And when fixing that, please also fix the NPE for a new database when e.g. adding entries:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.sf.jabref.gui.BasePanel.markBaseChanged(BasePanel.java:1964)
```

(To reproduce: create new database, import an entry from the web.)

**Comment by simonharrer** [comment]
@stefan-kolb can you have a look at this, please?

**Comment by stefan-kolb** [comment]
@koppor Please confirm or reopen.
@oscargus Cannot reproduce, maybe create a new issue?

**Comment by oscargus** [comment]
@stefan-kolb The fix solved my issue as well (which I guess was that `getDataBaseFile()` returned null, now it is checked first).
