### ISSUE TITLE
Group validation: Convert error dialogs to checkers

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6221]
In well-designed dialogs we don't show any error message: instead we disable the ok buton until all required fields are set. An additional popup dialog is unneccsarry.

See for example the SharedDatabaseLogin Dialog which is implemented correctly.

Follow up from https://github.com/JabRef/jabref/pull/6110/

**Comment by MootezSaaD** [comment]
Hello,
So the requirement is to show an alert instead of disabling the OK (connect button in the case of SharedDatabaseLogin)?
i.e
![image](https://user-images.githubusercontent.com/34676841/80306721-3ecab300-87c5-11ea-84cd-a738db5eb34a.png)

**Comment by Siedlerchr** [comment]
No the other way round. The alert dialog is superfluous, the validation icons show already the required fields with a hover message.
So for the groups dialog this should be the same. Disabling the ok button until required fields are set and show the validation icon

**Comment by nsmt09** [comment]
Hello, 

I was looking for a good first issue to contribute to your project and found this one. I checked the behavior and it seems like it already works like it should.
Is it possible that the issue has already been fixed?

Best regards 
Niklas

**Comment by catarinagomespt** [comment]
Hi, 
I would like to collaborate with your project. I already understand the problem.
Is this issue still open, right?

Thanks

**Comment by koppor** [comment]
The challange of this issue is to understand the issue.

I try to clarify:

The shared database dialog is implemented (more or less) **correctly**. There are field checkers in place. And no pop ups.

When following the link in the description, one finds https://github.com/JabRef/jabref/pull/6110#issuecomment-599038949

> Disabled button should work, except for when the dialog is opened at first. The checks only come into place when one has entered data in the mandatory fields. We need to trigger the validation after initialization to change this.

I think, this is the only place where the issue appears.

A more enduring bug hunter would try to open all JabRef dialogs and check whether there are any popups. This might be too much for a new comer. Thus, I close this issue. We will reopen new issues in case we encounte error popups.

We will discuss at #6418 whether the group dialog issue was solved.
