### ISSUE TITLE
Sort by priority broken

### ISSUE THREAD

**Issue by GSinsley** [JabRef/jabref#6222]
JabRef version
JabRef 5.1--2020-03-31--97fcf38
Windows 10 10.0 amd64 
Java 14

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Sorting by priority does not appear to work correctly in Jabref 5.x. (I originally saw the problem in 5.0, and have verified that it persists in the latest 5.1 snapshot.) In older versions of Jabref, when sorting by priority all red flags would appear first, followed by yellow and green flags, followed by blank priorities. In the latest version all priorities are lumped together followed by entries with no priority, as seen in the attached screenshot.

1. Add priority as a column in the entry table.
2. Assign priorities to some, but not all entries.
3. Click twice on the priority column to sort by priority descending.
4. Observe the order of entries.

![image](https://user-images.githubusercontent.com/62947051/78038662-1329e980-733b-11ea-8b47-9e832be1f105.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
I took a quick look and could confirm this isssue.
There probably needs to be implemented a new Comparator for that field like for the others.
https://github.com/JabRef/jabref/blob/eccfb577b7dc29e55ece8acbfe02bf6895408e39/src/main/java/org/jabref/gui/maintable/MainTableColumnFactory.java#L310-L319

**Comment by tobiasdiez** [comment]
Thanks to @dextep this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
