### ISSUE TITLE
allow merging of year and date if identical

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#6224]
```
JabRef 5.1--2020-03-23--67daf36
Windows 10 10.0 amd64 
Java 14
```
```tex
% Encoding: UTF-8

@Article{morgenthal2016Concretehingesandintegralbridgepiers,
  author       = {Morgenthal, Guido and Olney, Peter},
  title        = {Concrete hinges and integral bridge piers},
  year         = {2016},
  month        = jan,
  number       = {1},
  pages        = {06015005},
  volume       = {21},
  date         = {2016-01},
  doi          = {10.1061/(ASCE)BE.1943-5592.0000783},
  file         = {:Shared/Literatur Betongelenke/Morgenthal_2015_Concrete Hinges and Integral Bridge Piers.pdf:PDF},
  groups       = {FEMPaper, Betongelenke},
  journaltitle = {Journal of Bridge Engineering},
  keywords     = {rank3},
  owner        = {jkalliau},
  publisher    = {American Society of Civil Engineers},
  ranking      = {rank3},
  timestamp    = {2020-03-26},
}

@Comment{jabref-meta: databaseType:biblatex;}
```

1. open [bibtex2biblatexBugJK.bib.txt](https://github.com/JabRef/jabref/files/4410546/bibtex2biblatexBugJK.bib.txt)
2. clean up using following settings 
![Screenshot 2020-03-31 18 57 27](https://user-images.githubusercontent.com/15687581/78054678-b8b47b80-7382-11ea-8527-77c5e7045f28.png)

year does not get removed

**Comment by nathanvercaemert** [comment]
Would this be a change to the "Normalize Date Formatter?" I think I can handle this PR, and would like to take care of it if that's alright.

**Comment by catarinagomespt** [comment]
Hi,
I would like to contribute to your project.
Is this issue still open, right?

Best regards

**Comment by catarinagomespt** [comment]
I'd like to collaborate on this issue. I would like additional tips to understand better the problem.

**Comment by JoKalliauer** [comment]
@catarinagomespt 
I'm just a stupid user, so I might be wrong:

Afaik everyone can make a personal fork and edit this fork and then make a pull request to merge your input (afaik, even if the masterbrach changed meanwile)
No one else claimed to start on this issue and it was marked as low priority (which imho means the user can wait for several month-years for a bugfix), therefore it is highly unlikely someone else will fix this issue within the next month. ("Nobody" cared about it the last month, so the following might be the same.)

@ Developers: I know you are volenteering and I'm glad that you developed JabRef. (So don't understand that wrong. I like JabRef, otherwise I would not use it.)

Do you need tips from the developers (code) or from the problem?

I cannot comment on the code, where to look for.

The problem is:
```
@Article{bibtexkey,
  year         = {2020},
  month        = may,
}
```
converts to
```
@Article{bibtexkey,
  date         = {2020-05},
}
```
but
```
@Article{bibtexkey,
  year         = {2020},
  month        = may,
  date         = {2020-05},
}
```
stays the same, and leads to warnings in biber

**Comment by Siedlerchr** [comment]
Some more background information.
JabRef supports bibtex and biblatex (successor of biblatex). However, biblatex uses the date field and not year month like in bibtex. JabRef therefore threats them as alias fields to allow conversion to biblatex and bibtex 
The cleanup in jabref should now offer the possibility to merge the year and month field into date and additionally remove/clear the fields afterward.
Code wise I suggest looking into the Cleanup classes in logic

**Comment by catarinagomespt** [comment]
> Do you need tips from the developers (code) or from the problem?

Thanks @JoKalliauer . I want to understand the problem not the code. 👍 
That was it! Perfect. I also like to thank @Siedlerchr 's feedback.
I will analyze the code.

**Comment by tobiasdiez** [comment]
Thanks to @catarinagomespt this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by webanck** [comment]
Hello, I see date processing is still in the pipes !
Almost two years ago (see [here](https://discourse.jabref.org/t/custom-export-filter-month-field/1214)), I asked for a way to write a custom export with dates from the biblatex `date` field to bibtex `year`, `month` and `day` fields.
An error is still raised when the `date` field doesn't resolve as a full ISO date, any clue on how to solve this ?

**Comment by JoKalliauer** [comment]
Thanks to @catarinagomespt : As the author I want to confirm that it is fixed in:
```
JabRef 5.2--2020-09-04--3db4313
Linux 5.4.0-42-generic amd64 
Java 14.0.2
```
