### ISSUE TITLE
Simplified import from doi.

### ISSUE THREAD

**Issue by smihael** [JabRef/jabref#6225]
Currently in order to import bibtex data from doi, one has to undergo the following procedure.

1. Click on the new entry icon (+)
2. Switch to general tab
3. Paste in DOI number in the DOI field
4. Click on the download symbol to fetch bibtex data
5. Confirm to merge fetched data in the otherwise empty (new) entry.

I would suggest to add a menu idem and a shortcut to create a new entry directly from DOI in clipboard or open a dialog to paste it in in order to directly add a new entry from data fetched from DOI. 

Please correct me if there is already a simpler way.

**Comment by Siedlerchr** [comment]
Hi,

the usual workflow is: Click on the new entry icon (the + icon creates only an article, the icon next to article) 
paste the doi, arxiv or other identifier in that dialog and submit.

However, for DOIs you can simply paste the DOI direclty on the maintable and JabRef will fetch the information in the background and create a new entry based on the DOI data.

PS: Such questions are better suited for the forum.
