### ISSUE TITLE
Libreoffice integration: Character formatting issue

### ISSUE THREAD

**Issue by Steggen** [JabRef/jabref#6243]
Hi all, 
I experienced the following bug during using citing in Libreoffice.
My Jabref (bitex format) entry has chemical formulas in the title that I wrote as e.g. 

> Magnetic domain properties of {FeBO\textsubscript{3}}

This is correctly dislpayed in Jabref in both, table view and entry preview. When citing the article in a Libreoffice document the subscript (same happens to superscripts) is malformed:

<img width="539" alt="test" src="https://user-images.githubusercontent.com/63192976/78499717-9b9cf580-7752-11ea-9f23-7176b3eb4a2b.PNG">

The malformed subscript has the following character format:

<img width="394" alt="charactersetting" src="https://user-images.githubusercontent.com/63192976/78499879-b1f78100-7753-11ea-932b-b987944fdf4f.PNG">

After selecting the subscript and twice clicking the Subscript-icon in Libreoffice the subscript is displayed correctly. The character settings are now:

<img width="394" alt="charactersettingafter correction" src="https://user-images.githubusercontent.com/63192976/78499891-bde34300-7753-11ea-90c0-d647bb5939d0.PNG">

Now "automatic" is activated. This should be the default.
 
JabRef version 5.1 on Windows 10

[X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

**Comment by Siedlerchr** [comment]
I could reproduce this problem. The  101% Value is defined here;
 https://github.com/JabRef/jabref/blob/f85c081e75e373820077e720fe9d48db6542704c/src/main/java/org/jabref/logic/openoffice/OOUtil.java#L228-L242

The api only defines CharEscapement and CharEscapementHeight.
I  don't  know the Auto value is set internally or if there is some magic

>CharEscapement
>specifies the percentage by which to raise/lower superscript/subscript characters.
>Negative values denote subscripts and positive values superscripts.
https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1style_1_1CharacterProperties.html#a1335d73b4d11f4a48b01115bac73c083
