### ISSUE TITLE
[Code] Overwrite BibEntry.equals and use it in tests

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#625]
The `equals` method of a BibEntry should be overwritten and compare two entries based on their id, type and field values. Then the tests for the parser and importers should be rewritten to construct a list of entries and compare this list with the parsed/imported list.
Reasoning: Currently specific fields of imported entries are checked, however it is not verified that these fields are the only ones present in the entry.

**Comment by koppor** [comment]
Refs  #579
