### ISSUE TITLE
Dash in bibkey

### ISSUE THREAD

**Issue by melTr** [JabRef/jabref#6252]
Hi
I'm curious. Before (I'm not sure which version), dash was added in the bibtex and now striped out. Obvious example is the author name, like Smith-Thomson.
I didn't check option to "autorize only legal character". 
Thanks
Mel

JabRef 5.0--2020-03-06--2e6f433
Linux 4.15.0-91-generic amd64 
Java 13.0.2

**Comment by koppor** [comment]
Duplicate of #6295, therefore closing this.
