### ISSUE TITLE
bibtexkey: 2 more incompatible characters

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6257]
Currently, src/main/java/org/jabref/logic/bibtexkeypattern/BibtexKeyGenerator.java
states 
````
KEY_ILLEGAL_CHARACTERS = "{}(),\\\"-#~^:'`ʹ";
````
This list of characters is used to display a warning for the field bibtexkey.

Following issue #5982, I digged a bit further about the incompatible characters in a bibtexkey.
According to https://tex.stackexchange.com/questions/408530/what-characters-are-allowed-to-use-as-delimiters-for-bibtex-keys , for biber, `%` and `=` should not be used, and hence be added to the illegal characters.

**Comment by koppor** [comment]
Fixed by https://github.com/JabRef/jabref/pull/6300. Will be in latest `master`.
