### ISSUE TITLE
"Add to Group" option does not show up anymore when right click on the bib entry

### ISSUE THREAD

**Issue by AlexPars** [JabRef/jabref#6261]
JabRef version 
JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2

In JabRef 4.3.1 there was an option Add to group in the context menu (right click on the individual bib entry). This option does not appear anymore in JabRef 5.0

**Comment by Siedlerchr** [comment]
Hi,

This was removed in favor of Drag and Drop. You can simply drop the entries from the main table on the group.
