### ISSUE TITLE
"readstatus" lost after reopening JabRef

### ISSUE THREAD

**Issue by swekia** [JabRef/jabref#6262]
When reopening JabRef, the field "Readstatus" is empty for almost all entries.

I've just installed the following version of JabRef on my Windows machine:
JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2

Steps to reproduce the behaviour:
1. create an entry of whatever type (e.g. article)
2. set the "read status" by
  * either right-clicking on the entry > Read status > read (or skimmed respectively)
  * or typing it into the field "Readstatus"
3. save the project
4. close JabRef
5. reopen JabRef
&rarr; read status is lost

The error log is empty.

**Comment by Siedlerchr** [comment]
I cannot reproduce this issue in the latest development version.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by swekia** [comment]
Hey,

Thank you for your reply. I've tried out this version:
JabRef 5.1--2020-05-31--455ed8b
Windows 10 10.0 amd64 
Java 14.0.1

and still the problem exists. =(
