### ISSUE TITLE
custom entry table columns with multiple fields not organised by order

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6263]
JabRef 5.1--2020-04-08--8968ccf
Linux 5.5.15-200.fc31.x86_64 amd64 
Java 14

In the preferences/entry table columns I can add custom columns. Jabref does not differentiate whether I add a column booktitle/title vs title/booktitle.

1. Open Preferences | Entry Tabel Columns
2. Add booktitle/title in textfield below the list, press "+"
3. Add title/booktitle in textfield below the list, press "+"
4. Close preferences, and see effect on entry table: two identically named columns booktitle/title.

**Comment by Vince250598** [comment]
I think it's fixed in the unreleased(development) version. When i download JabRef from Github i don't have this issue but when i download it from the website this issue persists.

**Comment by ilippert** [comment]
I confirm - thus closing this for now
