### ISSUE TITLE
Search for field not containing multiple possible strings

### ISSUE THREAD

**Issue by awa5114** [JabRef/jabref#6271]
In the absence of group subtraction possibilities, I must resort to  search queries like this:

`groups contains "ContainsFunction" and not (groups contains "Earthquake")`

Is it possible to have additional strings in the `not` clause? I tried the following without success:

`groups contains "ContainsFunction" and not (groups contains "Earthquake", "Flood")`

`groups contains "ContainsFunction" and not (groups contains "Earthquake") and not (groups contains "Floods")`

How can I get the intended result? Thanks.

**Comment by awa5114** [comment]
I found one way, but it is quite verbose:

`groups contains "ContainsFunction" and not (groups contains "Earthquake" or groups contains "Flood" or groups contains "Landslides" or groups contains "Rainfall" or groups contains "Wind")`

Is there anything more concise?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
If you allow regexp,
<img width="378" alt="Skärmavbild 2020-11-04 kl  16 16 08" src="https://user-images.githubusercontent.com/2598631/98168837-298fb900-1eb9-11eb-8f71-285e471f5496.png">

does `groups = ContainsFunction and not groups = Earthquake|Flood|Landslides|Rainfall|Wind` work?

**Note that space has a special meaning, to search for "Contains Function" use Contains.Function**
