### ISSUE TITLE
Copy... -> Export to clipboard Dialog has no icon

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#6286]
Select an entry in the main table
1. Right click -> Copy... -> Export to Clipboard 

See that there is no icon. This results in the standard java icon shown in the task bar on windows

5.1 master
![grafik](https://user-images.githubusercontent.com/320228/79217031-6da06b00-7e4e-11ea-82f9-650100f7fbf8.png)

![grafik](https://user-images.githubusercontent.com/320228/79217084-86a91c00-7e4e-11ea-9127-b86243492f6d.png)

**Comment by MootezSaaD** [comment]
Hello, I would like to inquire if I could contribute by fixing this issue.

**Comment by Siedlerchr** [comment]
@MootezSaaD  Sure. The dialog should be called somewhere in  `org.jabref.gui.exporter.ExportToClipboardAction`

**Comment by MootezSaaD** [comment]
Hello,
Sorry for the delay, I have tried to convert the ExportToClipboard to mvvm-pattern, this is the dialog

![image](https://user-images.githubusercontent.com/34676841/80277864-40777680-86f2-11ea-8f16-8de5d588f82d.png)

What I have done is I created `ExportToClipboardModelView` and `ExportToClipboardDialogView` and `ExportToClipboardAction`  now calls `ExportToClipboardDialogView` .
Is it fine to make a draft PR ?

**Comment by Siedlerchr** [comment]
@MootezSaaD  Oh wow, well, that would be a solution, but I fear that you have "overengineered" in this case. Maybe I also did not specify it better, but if you look into the JabRefDialogService class, there the dialog is created  by using the standard ChoicedDialog component.

I think the solution would be just a one liner as in the ProgressDialog:
`        ((Stage) progressDialog.getDialogPane().getScene().getWindow()).getIcons().add(IconTheme.getJabRefImageFX());`

**Comment by MootezSaaD** [comment]
Oh then that settles it, thank you @Siedlerchr

**Comment by Siedlerchr** [comment]
See your other work not as wasted, but as a good training that enables you a good understanding of the Gui in jabref and hopefully you are interested in fixing other issues as well.

**Comment by MootezSaaD** [comment]
Absolutely! 
Thank you again for the assistance
