### ISSUE TITLE
Drag and Drop behaviour cannot be set in Preferences -> Entry editor tab

### ISSUE THREAD

**Issue by jhh931** [JabRef/jabref#6288]
JabRef 5.0--2020-03-06--2e6f433 (Portable version)
Windows 10 10.0 amd64 
Java 13.0.2

According to the manual, on  [https://docs.jabref.org/general/entryeditor#drag-and-drop-behavior-settings](https://docs.jabref.org/general/entryeditor#drag-and-drop-behavior-settings), the Drag and Drop behaviour can be defiend in the Entry editor tab. However, my "Entry editor" tab shows no such options:

![Capture](https://user-images.githubusercontent.com/20792626/79235301-b9add880-7e6b-11ea-917f-e87dc7c51341.JPG)

When I export my preferences, I see fields like 

- DroppedFileHandler_LeaveFileInDir
- DroppedFileHandler_CopyFile
- DroppedFileHandler_MoveFile
- DroppedFileHandler_RenameFile

But I fail to see where in the Preferences I can set these. 

In an earlier Jabref version (JabRef_windows-x64_4_3_1.exe), I used to see these related options under Preferences -> Import, but in JabRef 5.0 these seem gone (red box marking by me):

![Untitled1](https://user-images.githubusercontent.com/20792626/79235841-6b4d0980-7e6c-11ea-9236-f3481cb439b4.jpg)

**Comment by calixtus** [comment]
refs #5668 and #5563

**Comment by jhh931** [comment]
My latest experience with this was on:
JabRef 5.2--2020-12-02--f22968e
Windows 10 10.0 amd64 
Java 14.0.2


As the manual currently says, on https://docs.jabref.org/general/entryeditor#drag-and-drop-behavior-settings,
drag-and-drop behaviour is now modified (on Windows using Shift, Alt or Ctrl). For me this works as specified and as I need, so I'm closing this issue now.
