### ISSUE TITLE
Creating an new entry should clean up the filter

### ISSUE THREAD

**Issue by pet-ro** [JabRef/jabref#6297]
When I filter the entries and open a new entry,
for example a TechReport,
the list of entries does not show the new entry.

Therefore I recommend:
  Creating a new entry should clean up the filter
because I prefer that a new entry is also immediately
reflected in the list of entries.

If the current behaviour is a feature,
please provide a possiblity to switch this feature on and off.

Thanks.

JabRef 5-0 2020-03-06
MacOS 10.15.4
Java 13.0.2

**Comment by nsmt09** [comment]
Hello,

I was looking for my first contribution to an open source project to get to know the fork-branch git workflow. I found this issue and even though it is not labeled as a good first issue I would like to try work on it. I will let you know if I made any progress!

Best regards
Niklas

**Comment by Siedlerchr** [comment]
Thanks to @nsmt09 this should be fixed now in the latest master.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
