### ISSUE TITLE
BibTeX key generator should remove ( and )

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#631]
When generating the bibtex keys with `[authors3]`, the name `Bundeswirtschafts Ministerum (BMWI)` gets `BundeswirtschaftsMinisterium(BMWI)`. Then, biber complains that brackets may not be used as key.

**Comment by oscargus** [comment]
What if you put the whole name within {}? I have no idea if it helps, but I know that the code checks for those curly brackets to determine if the author is an institution. No idea what happens later though...

**Comment by lenhard** [comment]
Fixed with d505452d04b421818dd966a85121468138de8ff3 

The key generator now also checks for and avoids round braces.

**Comment by wbmacleod** [comment]
As I point out in #1272 this a poor idea that has caused many of us problems.  A better solution would be to enforce this only when jabref is in bibalatex mode.
