### ISSUE TITLE
Using Web Search results in being banned from Google Scholar

### ISSUE THREAD

**Issue by JosephRedfern** [JabRef/jabref#6331]
JabRef version: JabRef 5.0--2020-03-06--2e6f433

First off, thank you mainteners and contributors for spending time on JabRef. It's a really useful piece of software and I appreciate it.

I recently used JabRef's web search function against Google Scholar to find some references. I sucessfully imported 2-3, however soon afterward the tool stopped working. I then manually searched Google Scholar, only to be issued with a HTTP 403, and some reference to Google's terms of service:
![image](https://user-images.githubusercontent.com/861949/79853199-a9dc4a00-83bf-11ea-962c-3a7866fdddca.png)

As there was no warning that this might happen, I consider it a bug. May I suggest that this tool come with a warning or be disabled by default?

**Comment by Siedlerchr** [comment]
This is a known problem where we can't do anything about it.
Please see the FAQ for an alternative way: https://docs.jabref.org/finding-sorting-and-cleaning-entries/import-using-online-bibliographic-database/googlescholar#traffic-limitations
