### ISSUE TITLE
Replacement installation not possible anymore with current dev 5.1

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#6337]
Windows 10

I have downloaded the current dev version 5.1 (.msi package) today (last modification 22-04-2020 at 13:53). Apparently it is no longer possible to do a replacement installation of a previously installed dev version. When opening the installer the only options that are offered are either "Repair" or "Remove" - the "Change" option is greyed out. I did not proceed with the installation since I was not sure whether this is the new intended behaviour or whether this was a new bug?
Previously it was possible to install a new dev version which would directly replace the previous if you specified the path of the older version.

Can you confirm this new behaviour? Is this intended behaviour?

**Comment by AEgit** [comment]
JabRef 5.1--2020-04-23--bbea7df
Windows 10 10.0 amd64 
Java 14.0.1

With today's most recent dev version, the problem seems to have disappeared.

**Comment by Siedlerchr** [comment]
Maybe the version didn't change (the build number needs to be different)

**Comment by AEgit** [comment]
Possible - since I did not try to install yesterday's version when confronted with the problem I did not check, whether it was the same dev version.

**Comment by AEgit** [comment]
Actually, as a follow-up on this. Would it be possible again to have the dev version number in the filename (or something along the lines)? I think this was the case in the past but was removed at some point in time.

If that is not possible - is there a way to determine which development status the dev version currently offered on master represents without having to install that version?

I mean, this is obviously only a minor issue, that only affects people that frequently test the dev version, so you could say it is not worth investing time. But I just wanted to bring this up in case it can be easily fixed.
