### ISSUE TITLE
Dialog "Customize Entry Types" - drag&drop not working - adding new field buggy 

### ISSUE THREAD

**Issue by ElisEck** [JabRef/jabref#6338]
Luckily the "Customize Entry Types"-Dialog ist back! Unfortunately it is not (yet) working thoroughly:
* the "plus"-button for fields is grey and can therefore not be pressed, although I have entered a fieldname in the dropdown-box - this only changes after one clicks into the "new entry type"-box at least once
* the drag and drop to change the order isn't working at all (or at least I cannot figure out where to touch the line to drag&drop)

I have experienced this using:
JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2

I have tested the latest development version and the problem persists:
JabRef 5.1--2020-04-23--bbea7df
Windows 10 10.0 amd64 
Java 14.0.1

**Comment by ElisEck** [comment]
>     * when the Entry type is changed

after one clicks into the "new entry type"-box

**Comment by Siedlerchr** [comment]
Refs #6152

**Comment by domhardt** [comment]
I can reproduce this problem. Additionally I'm not able to delete entry types (left half of the "Customize Entry Types" dialog). They are back as soon as I reopen the dialog.

JabRef 5.0--2020-03-06--2e6f433
Mac OS X 10.14.6 x86_64 
Java 13.0.2
 
<img width="1280" alt="Bildschirmfoto 2020-04-24 um 12 27 59" src="https://user-images.githubusercontent.com/1955290/80203238-2329a600-8627-11ea-82f8-acab895a9981.png">

**Comment by Siedlerchr** [comment]
Yes, this is known and I started working on it (see linked PR, but turned out it's complicated).
Second, you can't delete StandardEntryTypes atm. Maybe needs a "reset to default button".

**Comment by Siedlerchr** [comment]
@domhardt  @ElisEck 

You can now use drag and drop to reorder to the fields. The order is now also reflected in the entry editor. 
You can't delete the Standard Entry Types. They will be re added upon reopening the dialog. That's actually a safety measure to prevent accidental breaking of JabRef.

The new version (currently building) will be available at 
https://builds.jabref.org/master/

**Comment by ElisEck** [comment]
@Siedlerchr Tank you so much, works quite well!

**Comment by Siedlerchr** [comment]
@wujastyk Can you please test this version? I improved the DnD  https://builds.jabref.org/pull/8121/merge/ 
(just needs some more visual clues, but works when you drop in between)

**Comment by wujastyk** [comment]
Yes, it works.  This is super.  Thank you so much; I can now leave the asylum and resume normal life :-)
