### ISSUE TITLE
Fetcher tests failing

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#6369]
Some of the fetcher tests are failing (ISBN, Inspire, ...)
https://github.com/JabRef/jabref/actions?query=workflow%3A%22Fetcher+Tests%22

**Comment by Siedlerchr** [comment]
* Grobid is failing due to Connection refused
* IEEE is failing due to API key probably
*  MrDLibFetcherTest Gateway Timeout
*  AstrophysicsDataSystemTest (needs ne API ?=>https://github.com/adsabs/adsabs-dev-api)

**Comment by koppor** [comment]
API keys: Howto for getting a sandbox key for developers

ADs-Fetcher: This is the PR switchting to the new API, isn't it? --> https://github.com/JabRef/jabref/pull/5501

**Comment by Siedlerchr** [comment]
Just got mail that the INSPIRE has now an official API:
https://github.com/inspirehep/rest-api-doc

**Comment by koppor** [comment]
![grafik](https://user-images.githubusercontent.com/1366654/85367428-7fc31780-b529-11ea-97d0-cb47286af7c1.png)

https://github.com/JabRef/jabref/runs/794938868

**Comment by Siedlerchr** [comment]
Springerlink is giving m,e 401 locally when I debug

**Comment by koppor** [comment]
@DominikVoigt Can you confirm for SpringerLink? 😅

**Comment by DominikVoigt** [comment]
If I supplement the API key that is hardcoded into the SpringerLink fetcher with my own API key all tests execute.

**Comment by koppor** [comment]
Springer mailed us on 2020-04-29:

> Dear User,
>
> Thank you for using Springer Nature APIs! While we are most pleased at your interest, we see traffic that is very high and well over the limit of 300 calls/min and 5000/day. The limit is 300 hits/min and 5000/day. Can you please adjust your code to stay within these limits? Please advise/confirm so we may restore service.
>
> Sincerely,
> SpringerNature API Team

**Comment by koppor** [comment]
## State as of 2020-08-02

Source: https://github.com/JabRef/jabref/runs/937189942

- Grobid: java.net.ConnectException: Connection timed out
- IEEE: Results differ
- CollectionOfComputerScienceBibliographiesFetcher: Assertion error
- LibraryOfCongressTest: Results differ
- CiteSeerTest: no answer
- DoiFetcherTest: Results differ
- AstrophysicsDataSystemTest: Results differ
- Springer: `@DisabledOnCIServer("Disable on CI Server to not hit the API call limit")`

**Comment by Siedlerchr** [comment]
We should add the Springer key to the build secrets as well

**Comment by koppor** [comment]
I will aquire a sepearate key for Springer and enable Springer tests in a separate PR.

**Comment by koppor** [comment]
Rate limit of IEEE

- 10 calls / second
- 200 calls / day

Source: Key agreement

**Comment by Siedlerchr** [comment]
We should execute the fetcher tests maybe once a month on CI and not on every PR

**Comment by koppor** [comment]
Since a few months, we DO NOT execute the fetcher tests on each PR.

We currently the fetcher tests, when

- something in the fetcher code changed
- each wednesday

See https://github.com/JabRef/jabref/blob/master/.github/workflows/tests-fetchers.yml

**Comment by koppor** [comment]
The discussion on this move can be found at https://github.com/JabRef/jabref/pull/5807.

**Comment by calixtus** [comment]
- IEEE returns a bad URL: https:/ieeeexplore… (Note: only one slash). Problem seems to be serverside
- LibraryOfCongress returns bad year ( year = {c201} instead of year = {2011} )
- The JabRef BibEntry builder seems to automatically add an url-field, which is not included in the returned result from the server. Will do some research on this.
- ADS seems to be identical on first sight. Not sure why failing, maybe something I overlooked... Will also do some research on this.

**Comment by Siedlerchr** [comment]
citesser => journaltitle instead of journal

**Comment by koppor** [comment]
@DominikVoigt added a conversion layer at https://github.com/JabRef/jabref/pull/6687. Thus, it should not matter whether journaltitle (BibLaTeX) or journal (BibTeX) is returned. -- the layer converts to the format required by the target database

**Comment by koppor** [comment]
@Siedlerchr Thank you for the hint --> @DominikVoigt's layer doesn't help here as the fetcher tests directly check the fetcher result - and not the reformatting by the intermediate layer.

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/3854 (as background information)

**Comment by koppor** [comment]
- Grobid runs in a time out. @LinusDietz can you check please?
- org.jabref.logic.importer.fetcher.ArXivTest has some differences, need to check later

**Comment by Siedlerchr** [comment]
Currently there seems to be a latex/unicode conversion issue in the INPIRE test
```
 org.opentest4j.AssertionFailedError: expected: <[@mastersthesis{Diez:2014ppa,
    archiveprefix = {arXiv},
    author = {Diez, Tobias},
    eprint = {1405.2249},
    primaryclass = {math-ph},
    school = {Leipzig U.},
    title = {Slice theorem for Fr'echet group actions and covariant symplectic field theory},
    year = {2013},
    _jabref_shared = {sharedId: -1, version: 1}
  }]> but was: <[@mastersthesis{Diez:2014ppa,
    archiveprefix = {arXiv},
    author = {Diez, Tobias},
    eprint = {1405.2249},
    primaryclass = {math-ph},
    school = {Leipzig U.},
    title = {Slice theorem for Frtextbackslash{}'echet group actions and covariant symplectic field theory},
    year = {2013},
    _jabref_shared = {sharedId: -1, version: 1}
  }]>
      at org.jabref.logic.importer.fetcher.INSPIREFetcherTest.searchByQueryFindsEntry(INSPIREFetcherTest.java:45)
```

**Comment by koppor** [comment]
- [ ] Jstor: Result differs
- [ ] CiteSeer: Result differs
- [ ] TitleFetcher: Change format
- [ ] Disable CompositeFetcherTest on CI
- [ ] Grobid: Server down

---

- [ ] Google Scholar. Refs #7075 
- [ ] Jstor: 403?
- [x] IEEE: 403 --> rate limit

---

- [ ] ACM Fetcher --> disable or rewrite (https://github.com/NatashaDudi/jabref/blob/develop/src/main/java/org/jabref/logic/importer/fetcher/ACMPortalFetcher.java)

**Comment by koppor** [comment]
We disabled ACM, Google Scholar and JSTOR at https://github.com/JabRef/jabref/pull/7229. We have different follow-up tickets and PRs. Thus, I can close this issue.
