### ISSUE TITLE
Strange group diff diff when saving bib file

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6374]
1. Open `jabref-authors.bib`
2. Check ZEUS group color:  ![grafik](https://user-images.githubusercontent.com/1366654/80602071-f4e50580-8a2e-11ea-9a95-a263e228a64e.png)
3. Save
4. Diff:

    ```diff
    -1 SearchGroup:ZEUS\;0\;ZEUS\;0\;0\;1\;0x008000ff\;\;\;;
    -1 SearchGroup:TOSCA\;0\;TOSCA\;0\;0\;1\;0x0000ffff\;\;\;;
    +1 SearchGroup:ZEUS\;0\;ZEUS\;0\;0\;1\;\;\;\;;
    +1 SearchGroup:TOSCA\;0\;TOSCA\;0\;0\;1\;\;\;\;;
    ```

This isn't the color, but something else. What is removed here and why?

**Comment by tobiasdiez** [comment]
That's the default color of a group, right? In that case it is no longer saved.
