### ISSUE TITLE
Recent Libraries list in File menu omits underscores in filenames

### ISSUE THREAD

**Issue by GreyMatter17** [JabRef/jabref#6383]
JabRef version 5.0 on Windows 10 and Ubuntu 16.04

- [ ] I have NOT tested the latest development version from http://builds.jabref.org/master/ but I have not found any other Bug report for this problem.

The "Recent libraries" list within the File menu displays the filenames of recently opened .bib database files, but if any of those filenames include an underscore, the underscore is **not**  shown. 
For example, the database Bug_List.bib will be be displayed as BugList.bib.

Strangely, clicking on the entry BugList.bib within the Recent Libraries list will (correctly?) open the database file Bug_List.bib, so the problem must simply be related to how the filename is displayed within the Recent Libraries list.

I did not observe this problem with JabRef 4.3.1, or any earlier version.

1. Create a minimal .bib database file, and name it Bug_List.bib 
This .bib file need contain only a single entry.
2. Open Bug_List.bib within JabRef 5.0. 
The name in the Tab above the main table will correctly show the filename Bug_List.bib
3. Look at the entries in the File/Recent libraries menu. 
The most recent library will be listed as BugList.bib

**Comment by MootezSaaD** [comment]
By default `mnemonicParsingProperty` is set to `true` for MenuItem which parses the underscore character.
https://docs.oracle.com/javase/9/docs/api/javafx/scene/control/MenuItem.html#mnemonicParsingProperty--
https://github.com/JabRef/jabref/blob/2825c29ae797c2c1ff5e632152ac1b6280f7af40/src/main/java/org/jabref/gui/menus/FileHistoryMenu.java#L53_L58
So setting it here to `false` will fix it.

**Comment by Siedlerchr** [comment]
@MootezSaaD  Thanks for investigating, freel free to create a fix

**Comment by tobiasdiez** [comment]
Thanks to @MootezSaaD this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
