### ISSUE TITLE
Default bibliography mode: only bibtex

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6387]
JabRef version  on 
JabRef 5.1--2020-05-01--a123eb1
Linux 5.3.0-51-generic amd64 
Java 14.0.1

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Options/Preferences/General
2. Default Bibliography Mode dropdown has only one value, "BibTeX".  I would expect
also to see "BibLaTeX".

**Comment by Siedlerchr** [comment]
Hm. This is odd: I can choose biblatex as well.
I also did a reset of my preferences, but biblatex is still there
![grafik](https://user-images.githubusercontent.com/320228/80824052-f7d22880-8bdd-11ea-92fe-ed79dbecfe8c.png)

**Comment by wujastyk** [comment]
![image](https://user-images.githubusercontent.com/762246/80824321-6e016b80-8b9b-11ea-98f5-7f14d2a64865.png)

**Comment by Siedlerchr** [comment]
It's correct, all lowercase.
![biblatex](https://user-images.githubusercontent.com/320228/80824481-cf96f980-8bde-11ea-9c90-95d89e316fc0.png)

**Comment by wujastyk** [comment]
JabRef 5.1--2020-05-03--b472942
Linux 5.3.0-51-generic amd64
Java 14.0.1

Agreed. "biblatex" now appears in the dropdown.
