### ISSUE TITLE
Brackets added to surname display after slash

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6388]
JabRef version  on 
JabRef 5.1--2020-05-01--a123eb1
Linux 5.3.0-51-generic amd64 
Java 14.0.1

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open editor
2. If the author's surname is preceded by a slash, it get curly brackets round it in the table display.  This is odd behaviour and probably a small bug.

![image](https://user-images.githubusercontent.com/762246/80823806-7dcc8000-8b9a-11ea-894b-a310ccbdf38e.png)

**Comment by Gena928** [comment]
Closed pull request. Can't work on the issue now, because of Intellij IDEA problems.

**Comment by catarinagomespt** [comment]
Hi! 
I'd like to collaborate on this issue.
Best regards

**Comment by tobiasdiez** [comment]
There were some improvements of the citation key generator in https://github.com/JabRef/jabref/pull/6479, can you please check if they also resolve this issue here. Thanks!

**Comment by wujastyk** [comment]
Seems to be fixed now.  Many thanks!

![image](https://user-images.githubusercontent.com/762246/85953729-c2249400-b92f-11ea-84b9-04d77abf9183.png)
