### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6390]
There isn't an appropriate "issues" category for this, but I want to thank the JabRef team for their work and to say that 5.1 has developed significantly in the last few weeks.  
Especially its performance is dramatically faster and more memory-efficient, its funny saving issues seem to be cured, some features that were on the back shelf are now appearing (editing entry fields, preview formatting, etc.).  Generally, for me as a mere end-user, Jabref 5.1 is now a tool I can use daily and with pleasure and satisfaction.  Thank you !!!

**Comment by tobiasdiez** [comment]
Thanks for your kind words!
