### ISSUE TITLE
StartupWMclass org.jabref.JabRefMain vs org-jabref-JabRefMain

### ISSUE THREAD

**Issue by HifeFish** [JabRef/jabref#6396]
I installed JabRef 5.0 from the .deb package on Ubuntu 16.04.

JabRef is not correctly associated with the .desktop file, so it doesn't show the icon in the launcher (it shows the default ?-icon instead).

The StartupWMclass in the .desktop file is org-jabref-JabRefMain whereas the application seems to use org.jabref.JabRefMain.

Changing the line in the .desktop file to StartupWMClass=org.jabref.JabRefMain resolves the issue.

**Comment by Siedlerchr** [comment]
@HifeFish  Thanks for reporting that issue.  It would be nice if you could change that line here as well, this is the desktop file that gets copied over
https://github.com/JabRef/jabref/blob/master/buildres/linux/JabRef.desktop
