### ISSUE TITLE
Cleanup date entries in title inconsistency

### ISSUE THREAD

**Issue by ddauer** [JabRef/jabref#640]
The cleanup command changes dates in titles to 
```...23~{A}pril 2009``` for June July April but not for October December. Have not checked all months.
```19 {December} 1996 ```

**Comment by oscargus** [comment]
Well, it actually changes it to 23~{A} as in Amperes... (J as in Joules). Probably the case keeper (which I think should include months) should be run before the unit converter.

**Comment by lenhard** [comment]
What is the actual problem here? How should the cleanup command behave correctly?

From what I understand, only the first letter of each month should be capitalized and enclosed in curly brackets? Can you specify the input month format and the desired output?

**Comment by tobiasdiez** [comment]
As far as I have understood it:
Input: 19 December 1996
Get: the same
Expected 19~{D}ecember 1996

**Comment by oscargus** [comment]
The thing is that the unit formatter converts the A, not the CaseKeeper. Simple way: add all months to a suitable list in CaseKeeper. I was thinking about it at the time, but then ran into translation thoughts.

**Comment by oscargus** [comment]
Oh yeah, keep the complete month within {}, not just the first letter (but that will be automatic if you add the months to the list).

**Comment by lenhard** [comment]
For me, the complete month is already kept in {}. My result from applying the cleanup operation is "19 {December} 1996" and not the same.

So the correct cleanup should be "19~{December} 1996"?

**Comment by oscargus** [comment]
Correct! I checked the code now and all months are included. I guess @ddauer only ran the unit formatting and not the case keeping.

**Comment by oscargus** [comment]
I think it can be closed and there's nothing that can be done which isn't already done (apart from possibly improving the documentation).

**Comment by lenhard** [comment]
Great!
