### ISSUE TITLE
JabRef.xml for memory stick mode is not generated when running installed version

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#6401]
JabRef version 5.1 dev (latest master)

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1.  Select Memory stick mode in the Preferences 
2. Click apply
3. Preferences recorded message appears but no JabRef.xml file is created
No exception is shown either.

By default, JabRef creates the jabref.xml relative to the current directory where the executable is located. I guess it could be the directory is not writable. Maybe present the user with an option to choose the bib file location as an alternative?

https://github.com/JabRef/jabref/blob/a123eb1bd9d6ea71e286224d452534416c72a945/src/main/java/org/jabref/preferences/JabRefPreferences.java#L982-L991

**Comment by jasciiz** [comment]
I will try

**Comment by Stang-wm** [comment]
Maybe the point is "User could select the config file's position when generating 'Jabref.xml' file in memory-stick mode"? Thus I think program should have a mode confirm dialog box when starting the program, as Jabref probably use the existence of "Jabref.xml" as a way to determine current mode, so the file's position could not be adjustable freely.
