### ISSUE TITLE
Some keyboard shortcuts are no longer working.

### ISSUE THREAD

**Issue by humbleambition** [JabRef/jabref#6403]
I'd sent a help message to the forum and Christoph Siedlerchr responded with a confirmation that it is still not working in the latest development version, and a request to post a bug report.

Some keyboard shortcuts are NOT Working:
e.g. (these are the only ones I checked, not sure about others)
Keyboard binding: Cntrl+shift+A Action: Create new article 
Keyboard binding: Cntrl+shift+B Action: Create new book
Keyboard binding: Cntrl+shift+I Action: Create new inbook
Keyboard binding: Cntrl+shift+M Action: Create new masterthesis
Keyboard binding: Cntrl+shift+T Action: Create new phdthesis
Keyboard binding: Cntrl+shift+P Action: Create new proceedings
Keyboard binding: Cntrl+shift+R Action: Create new report
Keyboard binding: Cntrl+shift+U Action: Create new unpublished

but 
other keyboard shortcuts ARE Working:
Keyboard binding: Cntrl+N  Action: Create new entry (brings up the menu to select type of entry)
Keyboard binding: Cntrl+shift+N  Action: Create new entry from plain text
Keyboard binding: Cntrl+E  Action: open editor of highlighted reference

JabRef version 
JabRef 5.0–2020-03-06–2e6f433
Windows 10 10.0 amd64
Java 13.0.2

**Comment by tobiasdiez** [comment]
Thanks to a very quick fix by @MootezSaaD this should be working now in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by humbleambition** [comment]
Work great!
Thanks so much for such speedy work guys! :)

All the Best,
Jen

**Comment by humbleambition** [comment]
Forgot to include:

JabRef 5.1--2020-05-04--b5599c9
Windows 10 10.0 amd64
Java 14.0.1
