### ISSUE TITLE
Creating or editing a group of cited entries triggers "Library has been modified by another program." whenever saving the library subsequently

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#6420]
Tested with the latest JabRef development version (master branch) on Ubuntu 16.04

<ins>Steps to reproduce the behavior (creating group):</ins>

1. Save current library (only needed, if the library is indicated as modified)
2. Create a group of cited entries with an attached `*.aux` file
    -  Side note: even without attaching an existing `*.aux` file and leaving this field empty allows reproducing it as well
3. The library has been modified, indicated by the star character (*) in the tab of the main table
4. Save library

*Observation:*

**After saving the library, the message "Library has been modified by another program." shows up, asking either to choose "Dismiss changes" or "Review changes". When such a group has been created (or updated), then this message appears whenever the library is changed and gets saved.**

<ins>Steps to reproduce the behavior (editing group):</ins>

After restarting JabRef and opening the previously opened library the aforementioned issue does not arise until one does the following (or one repeats the steps above):

1. Save current library (only needed, if the library is indicated as modified)
2. Edit an existing group of cited entries
3. Click "OK" to save the changes in the dialog for editing an existing group of cited entries (no changes need to be made in the dialog)
4. A dialog appears, asking "Assign the original group's entries to this group?"
4.1. Either click "Cancel" or "OK" (it does not matter)
5. The library has been modified, indicated by the star character (*) in the tab of the main table
6. Save library

*Observation:*

**After saving the library, the same issue as described above arises.**

<ins>Remark:</ins>

As stated in #6394, groups of cited entries also have another issue.

<ins>Removal of issue:</ins>

1. Delete the group of cited entries or change the group type to something different than "Cited entries".

*Observation:*

The issue vanishes.

**Comment by tobiasdiez** [comment]
Maybe the color code changes upon saving? (I slightly remember there was something like that in the code...)

**Comment by systemoperator** [comment]
I've tried to find some differences in the variable `changes` in

https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/gui/collab/DatabaseChangeMonitor.java#L46

but there is quite a lot information contained. I could not find any differences, only things which are equal.

**Comment by systemoperator** [comment]
What I could find is that in "metadata change", the originalMetaData entry had subscribers, but the newMetaData entry doesn't.

**Comment by tobiasdiez** [comment]
@ https://github.com/JabRef/jabref/issues/6420#issuecomment-635943587
This looks like a bug. The change scanner should only return things that are different...

What you you mean by the "subscribers" for the metadata change? What's the content of 
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/logic/bibtex/comparator/MetaDataDiff.java#L35 ?

**Comment by systemoperator** [comment]
The content of `changes` at

https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/gui/collab/DatabaseChangeMonitor.java#L46

looks as follows:

![image](https://user-images.githubusercontent.com/3658393/83462926-c19df800-a46c-11ea-99b7-da6fb63db8db.png)

The content of `changes` at 

https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/logic/bibtex/comparator/MetaDataDiff.java#L35

is:

![image](https://user-images.githubusercontent.com/3658393/83463083-4426b780-a46d-11ea-8577-7d80885d6e6c.png)

The subscribers I was talking about were at (but probably irrelevant):

![image](https://user-images.githubusercontent.com/3658393/83463601-cd8ab980-a46e-11ea-94ef-1e082d028318.png)

**Comment by systemoperator** [comment]
But I suspect properly fixing #6394 could fix this as well, because everything started with that.

**Comment by tobiasdiez** [comment]
Thanks for the investigation. It's strange. I don't see any problems with the equals method of the groups:
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/groups/AbstractGroup.java#L58-L60
It's also strange that you experience this problem since https://github.com/JabRef/jabref/commit/bc57d22f2a4ae8912d263608cf0a606fbbecd43a, since this change doesn't touch anything that is relevant for the group diff.

Can you please have a closer look and see which groups fail the equality check (and why).

**Comment by systemoperator** [comment]
@tobiasdiez I have concretized the description and reproducibility of the issue its description https://github.com/JabRef/jabref/issues/6420#issue-612206411 Can you reproduce it this way?

**Comment by systemoperator** [comment]
> It's also strange that you experience this problem since [bc57d22](https://github.com/JabRef/jabref/commit/bc57d22f2a4ae8912d263608cf0a606fbbecd43a), since this change doesn't touch anything that is relevant for the group diff.

@tobiasdiez You are right about commit bc57d22. It is not the cause of this issue. I have tested this issue before this commit now and it persists. (Sorry for the confusion.)

**Comment by systemoperator** [comment]
For the case, where an `*.aux` is attached and the group gets updated, the diff is caused by the following line:

https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/groups/GroupTreeNode.java#L134

where `Objects.equals(group, that.group)` is `false`.

```
group = 
TexGroup{filePath=/home/systemoperator/test/main.aux, keysUsedInAux=[Test2015, Test2018], auxParser=org.jabref.logic.auxparser.DefaultAuxParser@f972069, fileMonitor=org.jabref.gui.util.DefaultFileUpdateMonitor@1bb768ee} AbstractGroup{name='cited entries', context=INDEPENDENT, color=Optional[0x008000ff], isExpanded=true, description=Optional.empty, iconName=Optional.empty}

that.group = 
TexGroup{filePath=main.aux, keysUsedInAux=null, auxParser=org.jabref.logic.auxparser.DefaultAuxParser@4ded40, fileMonitor=org.jabref.model.util.DummyFileUpdateMonitor@29db0b7c} AbstractGroup{name='cited entries', context=INDEPENDENT, color=Optional[0x008000ff], isExpanded=true, description=Optional.empty, iconName=Optional.empty}
```

More concretely, it's finally the filePath which causes the problem at:


https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/groups/TexGroup.java#L94

For

https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/model/groups/GroupTreeNode.java#L135

`Objects.equals(getChildren(), that.getChildren())` is `true`.
