### ISSUE TITLE
forward-delete key while editing author name

### ISSUE THREAD

**Issue by Dan-Essin** [JabRef/jabref#6421]
JabRef version  on 

JabRef 5.0--2020-03-06--2e6f433
Mac OS X 10.15.4 x86_64 
Java 13.0.2

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. ...Enter the author name field
2. ...place the cursor
3. ...strike the forward-delete key to delete the char to the right of the cursor
3. ...A dialog pops up asking if I want to delete the record.

This is inappropriate behavior when editing a field. It should only act this way when a record is highlighted in the list AND the list has focus.

<details>
  <summary>Log File</summary>
  
 event log is empty

</details>

**Comment by Dan-Essin** [comment]
Interestingly, pressing the backspace key while editing a field does NOT attempt to delete the record.

**Comment by braincident** [comment]
I'd like to deal with this issue.

**Comment by Siedlerchr** [comment]
Thanks to @braincident  this issue should be fixed now in the latest master (build should be ready in roughly half an hour)

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
