### ISSUE TITLE
No option to connect to libreoffice/openoffice

### ISSUE THREAD

**Issue by diabl0w** [JabRef/jabref#6422]
I have tried the jabref, jabref-latest, and jabref-git packages from the arch linux user repository. None of them have the connect to libreoffice/openoffice option available! Has this been removed? I am getting nervous having to manually include all these references for my report due in 2 days! haha

**Comment by Siedlerchr** [comment]
@diabl0w  Hi, the function should still be there? Have you checked View -> OpenOffice/LibreOffice?
![grafik](https://user-images.githubusercontent.com/320228/81055643-67d7fb80-8ec9-11ea-8065-ce6d5cb7dce1.png)


cc @j0hannes Any thing related to arch?

**Comment by diabl0w** [comment]
> @diabl0w Hi, the function should still be there? Have you checked View -> OpenOffice/LibreOffice?
> ![grafik](https://user-images.githubusercontent.com/320228/81055643-67d7fb80-8ec9-11ea-8065-ce6d5cb7dce1.png)
> 
> cc @j0hannes Any thing related to arch?

oh my gosh thank you! it is there! all the documentation that i have seen seems to point to "Tools > connect", so I was mostly just checking there. I know that I was looking through all the submenus occassionally tho, and I know that it wasnt under "View" either at some point, but I have been messing around with installing so many different versions of jabref and so many different versions of java and java-common etc. that I am not sure which combinations made it not be under "View" either. None the less, running latest java, libreoffice, and jabref it is working fine so I don't think this is an issue moving forward.

Thanks again! especially for the fast reply. calmed my nerves!

**Comment by Siedlerchr** [comment]
Glad that issue is solved. We recently restructured the menus a bit and unfortunately our documentation is not 
always up to date. 
Good luck with your report!
