### ISSUE TITLE
lowercase bibtexkey

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#6432]
This is with the latest 5.1 5/4/2020 on Linux.

My default bibtexkey should be  [auth:lower][year] but no matter what I do in preferences it is not
preserved and goes back to [auth][year]. Did the :lower convention changed in 5.x? Thanks,

**Comment by MootezSaaD** [comment]
Hi,
Simply hit "enter" keyboard button to save the field's content
Related issue #6196

**Comment by calixtus** [comment]
The underlying issue is a well known bug in JavaFX, waiting to be fixed.
However, there are some workarounds, but they bring downsides with them too.
https://bugs.openjdk.java.net/browse/JDK-8089514

**Comment by calixtus** [comment]
Can you please test, if the solution proposed by @MootezSaaD works?
Thank you!

**Comment by mikegilchrist** [comment]
As I noted in [here](https://github.com/JabRef/jabref/issues/5825#issuecomment-631749990), hitting 'enter' does not work for me.

**Comment by Siedlerchr** [comment]
This was fixed in the dev version now, right?
