### ISSUE TITLE
Auto-completion is suggested when irrelevant 

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#644]
In general the auto-completion function is very usefull, however, sometimes it suggests phrases when not needed:

For example:
A bibtexentry fetched with google scholar gives the following Journal title:
"Zeitschrift f{\"u}r Soziologie"

I want to change it to:
"Zeitschrift für Soziologie"
-> move cursor after "}", delete the latex expression and press "ü" -> now the auto-completion suggests some other (already used) Journal name, and I have to refuse the suggestion first, to modify the entry the way I want it to be. Note, when modifying several characters, this can be pretty annoying, because I have to refuse the suggestion each time.

Expected behavior:
- auto-completion should only be suggested when the cursor is at EOL (or may be before a space character).

**Comment by koppor** [comment]
Workaround: Turn off autocompletion at Preferences -> Entry editor -> Autocompletion options.

**Comment by koppor** [comment]
Should we disable auto completion completely until the issue is fixed? It is pretty annoying for new users. I don't know, who is really using it.

**Comment by stefan-kolb** [comment]
@teertinker You might want to take a look at #1077 and the builds at http://builds.jabref.org/auto-complete/
