### ISSUE TITLE
Install both 5.0 and latest development snapshot?

### ISSUE THREAD

**Issue by tb77phd** [JabRef/jabref#6449]
Is it not possible to have both the stable version (5.0) and the latest development snapshot installed?

I downloaded the stable version, installed it into C:\Tools\JabRef, confirmed that it worked, restarted the computer.

Then, I installed today's snapshot (2020-05-08) into C:\Tools\JabRefDev (different folder than the stable version). For some reason, the stable version got uninstalled and the entire folder C:\Tools\JabRef was removed during the installation of the development snapshot.

Windows 10 64-bit, Java 14.0.1

**Comment by mlep** [comment]
To my knowledge, if you want to have both, the development version has to be the portable one.

**Comment by ilippert** [comment]
I don't face this issue on Linux.

**Comment by Siedlerchr** [comment]
Both your folders started with JabRef, maybe this also the case that the installer got confused or treated it as same directory? Might also be that the installer recognizs the application ID . No idea.
In doubt use the development version

**Comment by tb77phd** [comment]
Strange that the installer would get confused by directories starting with the same word but otherwise be different... But yes, I'll stick with the development snapshot.

**Comment by bernhard-kleine** [comment]
> 
> 
> To my knowledge, if you want to have both, the development version has to be the portable one.

It doesn't matter which version is the portable version. I have the snapshot installed in a Jabref5 directory while the portable version 5.0 sits in a Jabref dir.  As long as the directories are different there is no confusion. (win10)

**Comment by Siedlerchr** [comment]
This seems to be not an issue on JabRef's side but more an issue on where you put the installations As suggested, portable versions can be used in addtion to the installer
