### ISSUE TITLE
"App can't be opened" error on OS X with JabRef 3.1

### ISSUE THREAD

**Issue by aleth** [JabRef/jabref#645]
With the latest Oracle JRE installed, running 3.1 (after installing from the dmg provided) results in an "Application can't be opened" error.
(OSX El Capitan)

**Comment by stefan-kolb** [comment]
@aleth Please try version 3.2 and take a look at the Mac OSX FAQ which states something about the security manager which could be a problem. We tried it with OSX El Capitan and it did work for us for both 3.1. and 3.2.

**Comment by aleth** [comment]
@stefan-kolb Unlike v3.1, v3.2 now works fine for me on 10.11.4 (without requiring security manager tweaks). Thanks!

**Comment by stefan-kolb** [comment]
@aleth That's nice to hear! :smile:

**Comment by simonharrer** [comment]
:trophy:
