### ISSUE TITLE
multiline fields: cursor jumps to beginning of field

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6457]
Currently on 

JabRef 5.1-PullRequest6455.368--2020-05-09--fff4926
Linux 5.6.8-200.fc31.x86_64 amd64 
Java 14.0.1

In the entry editor, try to type many words; I routinely observe that the cursor jumps to the beginning of the text field.

@Bastian-B, can you also observe this?

I suspect this is likely a consequence of https://github.com/JabRef/jabref/pull/6315.

**Comment by AEgit** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/5904 (?).

**Comment by ilippert** [comment]
Ok, closing this if favour of discussion at https://github.com/JabRef/jabref/issues/5904.
