### ISSUE TITLE
Generated Key contains 'null' when (corporate) author contains several special words after curly braces

### ISSUE THREAD

**Issue by rolandog** [JabRef/jabref#6459]
JabRef version JabRef 5.0--2020-03-06--2e6f433 on Ubuntu 19.10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists (JabRef 5.1--2020-05-08--40f908f on Ubuntu 19.10).

1. Add the attached reference to a database
2. Check database integrity
3. Get notified of difference ("BibTex key deviates from generated key")
4. Go to mentioned key, click "generate key"
5. The key will now be "nullL2019".

Sample Bibliography
```bibtex
@Online{TSoL2019,
  author    = {{The School of Life}},
  editor    = {Abbot, Jack},
  date      = {2019-10-08},
  title     = {What Is The Secret Of Happiness?},
  url       = {https://youtu.be/sBSwJ6HOBG4},
  urldate   = {2019-11-05},
}
```

<details>
  <summary>Log File</summary>

  No events were generated in the event log, even though I followed procedure according to [the docs](https://docs.jabref.org/general/commandline), and I ran both the `.deb` and Portable versions (the latter I ran with the following options: `./JabRef --console --debug`).

  This was the output on the terminal:

  ```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.

(java:20862): Gdk-WARNING **: 18:01:46.992: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks for your report. It would be helpful if you could tell us which key pattern you have defined for the entry type or if you are using the default pattern

**Comment by rolandog** [comment]
Hi @Siedlerchr ! Thanks for your reply!

I don't think I have modified the defaults;

![Screenshot from 2020-05-10 22-43-20](https://user-images.githubusercontent.com/12400926/81510135-e4c30500-930f-11ea-8f8e-02ceb3c9102b.png)

If I click on the 'reset' button on the entry, a value of `[auth][year]` appears, instead of a blank value... but the behaviour is the same: the entry's generated key still contains `null`.

This may or may not be helpful, but I noticed that most of the "corporate" authors are not displayed properly; here's a screenshot on how the column is displayed for the author `{Commission on Isotopic Abundances and Atomic Weights}`:

![Screenshot from 2020-05-10 22-50-44](https://user-images.githubusercontent.com/12400926/81510304-040e6200-9311-11ea-99e4-8befaaa7ad13.png)

I don't think I have any odd settings on the 'Entry Table' settings:

![Screenshot from 2020-05-10 22-48-02](https://user-images.githubusercontent.com/12400926/81510385-87c84e80-9311-11ea-8122-269155514200.png)

Just to be on the safe side, I reset all my preferences, restarted JabRef, modified the entry's key, re-generated it and got the same results; also the same problem was present with the format of the corporate author's name in the author's column.

![Screenshot from 2020-05-10 23-01-51](https://user-images.githubusercontent.com/12400926/81510508-729fef80-9312-11ea-94b5-cc948b3f1a84.png)

Tomorrow morning I'll try uninstalling, removing configuration files, and see if there are any different results.

**Comment by Siedlerchr** [comment]
Thanks for your feedback! Resetting preferences was enough as clarification. Looks really like a bug,

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I can take a look at this?

**Comment by Siedlerchr** [comment]
@k3KAW8Pnf7mkmdSMPHz27  Sure go ahead

**Comment by tobiasdiez** [comment]
Thanks to @k3KAW8Pnf7mkmdSMPHz27 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
