### ISSUE TITLE
view independent groups not working when switching groups

### ISSUE THREAD

**Issue by Olifair** [JabRef/jabref#646]
Hello, 
I have started using the groups feature (V3.2dev) and there seems to be a problem with the groups view (I'm using the option of independent groups, so only the references int eh group should be shown).
When all Entries are shown and then one clicks on a group, this is working correctly and only the references in the group are shown. However when one now clicks on a different group, then nothing happens. One needs first to click on "All Entries" and then on a different group to get the references of a different group shown. 
Cheers

Oliver

**Comment by tobiasdiez** [comment]
I think this is a duplicate of #417 and should be fixed since a few days with #633. Could you please try out the latest build available here: http://builds.jabref.org/master/

**Comment by Olifair** [comment]
I donwloaded a dev version yesterday afternoon, because of the LibreOffice V5 bug which was not producing the reference list. If I get this new version, will I loose this functionality if I use this other dev version ? Otherwise I'll take your word, I'd rather wait for a new complete version for this group bug, it's less important to me than the LL bug.

**Comment by oscargus** [comment]
No, they are incremental so shouldn't be a problem.

**Comment by Olifair** [comment]
OK I'll try tomorrow

**Comment by Olifair** [comment]
Great, it's working now. Thanks very much for this very rapid bug-fix.
