### ISSUE TITLE
 Cursor periodically bounces to top of comment window

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#6460]
The cursor unpredictably bounces from the spot I'm typing in the comment window to the comment window top (upper left hand corner).  Sometimes, if I have the preview showing, the bouncing seems to happen when the preview window refreshes.

But the bouncing happens whether or not the preview window is visible.

JabRef 5.1--2020-05-08--40f908f
Windows 10 10.0 amd64 
Java 14.0.1

**Comment by AEgit** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/5904 (?).

**Comment by notuntoward** [comment]
Yes, they sound related, maybe the same.

**Comment by Siedlerchr** [comment]
It seems it's related to the Autcompletion. Maybe we should disable autocmpletion for multiline fields
In addition, I noticed a search is fired every time an entry changes. (SearchListener in BasePanel)

**Comment by Siedlerchr** [comment]
Please try this version:; https://builds.jabref.org/pull/6455/merge/ 
Please report back in the other thread #5904
