### ISSUE TITLE
copy formatted

### ISSUE THREAD

**Issue by Olifair** [JabRef/jabref#647]
It would be great if one could (right-click on a reference) copy a reference formatted in the selected style. This is something Mendeley does and it is very helpful, for example for sharing references with people who do not necessarily want the complete Bibtex reference.
It would be nice if you could consider this
thanks in advance

Oliver

**Comment by oscargus** [comment]
Something like what is shown in the entry preview? I guess a menu entry "Copy preview" there could make sense.

**Comment by Olifair** [comment]
Yes, something like that would be great, but style would also be great ;-)

**Comment by oscargus** [comment]
What do you mean by style? Using a .bst?

**Comment by oscargus** [comment]
(Better not close it, if you want it to happen. :-))

**Comment by Olifair** [comment]
I'm new to GitHub, used the wrong button :-)
I'm talking about the style that is chose when for example connecting to LibreOffice.

**Comment by oscargus** [comment]
Ah, OK! That's a third style (I think). :-)

**Comment by oscargus** [comment]
I implemented copy of the preview in #648. Not exactly what you asked for, but a start and maybe substitute.

**Comment by Olifair** [comment]
Wow great, you are really rapid. I think copying the preview is largely sufficient. To get the formatted citation one can always use as a workaround a connection to LL. Thanks again.

**Comment by oscargus** [comment]
I think it is possible to copy the layout from the LL style to the preview (more or less, there are probably a few more tweaks available in the LL style and it can be adapted for different entry types).

**Comment by teertinker** [comment]
Isn't this what "Export to clipboard" after right-click does? It opens a window, where you can choose the style you need.

**Comment by Olifair** [comment]
No, these are export formats, not LL styles

**Comment by oscargus** [comment]
Oh, really. Didn't know about that feature. :-) I don't think that the "Copy preview" hurts, but that one is clearly useful for a similar purpose as well!

**Comment by Olifair** [comment]
As far as I can see most of the export filters (haven't tested all) copy a reference formatted with tags, symbols etc in order to import into another program. So Copy preview is really quite different.

**Comment by koppor** [comment]
Refs #119 - when citation styles are supported, the entry preview should be more nicely formatted.

**Comment by teertinker** [comment]
@Olifair I think "Export to clipboard" is almost exactly the thing you asked for. There are export filters. Some of them are created to import it into another program, other were created to build bibliographies according to a certain paper style (MIS Quarterly, Harvard RTF...). See the description at: http://jabref.sourceforge.net/resources.php#export_filters 
Sure, the styles available do not cover many journals, but you can rather easily create your own export filter. The "coding" needed is not that hard and almost the same as in the LO style files - so its not that different.

**Comment by Olifair** [comment]
Just downloaded the latest build to test the "copy of preview" but cannot find it, neither int he "Edit" menu, not in the right click menu on a reference, nor right click into the review field. 

Oliver

**Comment by Olifair** [comment]
Fiddling with export filter seems complicated to me for this simple functionality : generally copy preview is probably sufficient, however when a copy in a specific style is required, then the user should be able to chose from the styles list and not program an extra export filter for an already existing style. 
just my opinion
Cheers

Oliver

**Comment by tobiasdiez** [comment]
The `copy of preview` functionality is not yet merged in the main release. See #648.
I think the most clean (and hardest) solution is to implement CitationStyles for the preview, for export and for `Export to clipboard`. Can I close this here and track the feature suggestion at  #119 or do you think that implementing CitationStyles does not solve this problem?

**Comment by Olifair** [comment]
copy of preview is absolutely fine for me.  Being able to select different styles really is a different thing, much more work and perhaps a question of strategy concerning CitationStyles. Have you had a look a the web interface for create a new citation style ? I find it quite horrible, especially how  the way to define "general" versus the other citation types is organised is quite opaque for me.

**Comment by stefan-kolb** [comment]
Further discussion will continue in #119
