### ISSUE TITLE
 Latex citations search - Missing citations for biblatex-mla

### ISSUE THREAD

**Issue by FredericChopin** [JabRef/jabref#6476]
I'm using the LaTeX citation feature with the biblatex-mla style, which provides the commando `\autocites` for citing multiple sources:
http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-mla/doc/biblatex-mla.pdf
To fully support biblatex-mla, `\headlesscite` and the starred versions `\autocite*`, `\parencite*` seem to be missing in the parser:
https://github.com/JabRef/jabref/blob/16d4938b72919e7454fb23633d3d8e53f16f38b5/src/main/java/org/jabref/logic/texparser/DefaultLatexParser.java#L35-L39

My suggestion is
```java
    private static final String[] CITE_COMMANDS = {
            "[cC]ite(alt|alp|author|authorfull|date|num|p|t|text|title|url|year|yearpar)?",
            "([aA]|[aA]uto|fnote|foot|footfull|full|no|[nN]ote|[pP]aren|[pP]note|[tT]ext|[sS]mart|super)cite([s*]?)",
            "footcitetext", "(block|text)cquote"
    };
```

**Comment by Siedlerchr** [comment]
Thanks for the suggestion! Feel free to create a PR with your changes!
