### ISSUE TITLE
Column search suggestions

### ISSUE THREAD

**Issue by sochtends** [JabRef/jabref#6484]
First, if Author is selected, the search wheel turns for very long time. If Bibtex key is selected, it is quite fast.
Second, if no column is selected, it does not search at all. It would be better if the search is still performed, by Bibtex Key or by Author by default.

**Is your suggestion for improvement related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by leitianjian** [comment]
Hi, Thanks for your suggestions.
I wonder whether you are describing the function of jumping to an entry in the main table with the same value as the typed key?

**Comment by sochtends** [comment]
Hi leitianjian,

Indeed, I refer to the recently added feature of searching within the main table by typing name. If a particular column is selected, i.e. there is an arrow up or down next to the column name, then the search is performed. But if no column is selected, nothing happens. It would be better if it still does the search by bibtex key for example.

**Comment by leitianjian** [comment]
Great idea, I know your idea now, I will try to satisfy your advice. However, it seems a little difficult. Because from your description, I think you need to search bibtex key by default, which is going to filter entry not related. It is a little different than a simple jump.

**Comment by sochtends** [comment]
I am not quite sure I follow you. But I would prefer it doing exactly the same as Bibtex Key selected. It is probably something that you refer as a jump. It is not a filtering what I would like to have. i would say that it should scroll along the table to the corresponding bibtex key.

**Comment by leitianjian** [comment]
Thanks for your clarification. I think a simple jump should not be used when the list is not sorted. For example, the first entry with bibtex key 602...., 200th entry with 602.... too, where to jump when you typed 602?
