### ISSUE TITLE
right click on library above entry table not possible

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6485]
According to
https://docs.jabref.org/setup/databaseproperties
it should be possible to perform

> right clicking on the tab of the database and choosing "Database properties".

This should be restored - though as "Library properties".

**Comment by Siedlerchr** [comment]
Yes, I am missing that right click feature as well.
However, as workaround you can still access them using the library menu.

**Comment by ilippert** [comment]
> as workaround you can still access them using the library menu.
confirmed

**Comment by Oltman-B** [comment]
Hello,

I'm new to open source but I'm interested in working on this issue. I've found examples of the context menu and mouse event handling in the code, but I'm not exactly sure where to implement. I'm assuming this would be somewhere in the JabRefFrame. Can anybody give me a little direction for starting? Thank you!

**Comment by Siedlerchr** [comment]
@Oltman-B  Thanks for your interest!  Please read  through our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) 
The TabbedPane is indeed initialized in JabRef Frame. 
You probably need to add the menu handling to the add method, there the tabs are added for each library:

`    public void addTab(BasePanel basePanel, boolean raisePanel) {`

**Comment by calixtus** [comment]
To be honest, I personally thing that an additional right click menu with just the menu entry for library properties is just polluting JabRef.
I dont think that opening the library properties via the menu bar is really a work around, bot merly a the UI cleaned up. I don't believe that anybody really needs the library properties on short dial and cannot spent another 2 seconds to call the library properties via the menu bar.

**Comment by koppor** [comment]
We merged the PR and created a follow-up issue at https://github.com/JabRef/jabref/issues/6527.
