### ISSUE TITLE
special fields/show extra columns doesn't work anymore

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6486]
JabRef 5.1--2020-05-14--09111be
Linux 5.6.12-300.fc32.x86_64 amd64 
Java 14.0.1

for some versions now, the entry table does not show the extra columns anymore.

**Comment by Siedlerchr** [comment]
Cannot confirm: 
Enable Special fields checkbox then you can add them to the table:

![grafik](https://user-images.githubusercontent.com/320228/82082948-2f19fc80-96e9-11ea-8d26-8eea7632a09e.png)

![grafik](https://user-images.githubusercontent.com/320228/82082974-39d49180-96e9-11ea-9218-f047f839ccfa.png)

**Comment by ilippert** [comment]
i confirm it works - this is why it did not work before: in the columns list, the special fields were missing.
I cannot recall ever having removed them.
so, will close this, and if the fields are removed again from the list, will report so.

**Comment by Siedlerchr** [comment]
In the column list drop down the special fields are only shown if you tick the checkbox.

Could have been a side effect of the preferences migration/backwards compatibility fix for 4.3.1

**Comment by ilippert** [comment]
ok, thanks for the migration scenario.

the checkbox was always ticked ;)
