### ISSUE TITLE
"There are possible duplicates (marked with an icon) that haven't been resolved. Continue?" But there are no markers and it's unclear, duplicates of what haven't been resolved.

### ISSUE THREAD

**Issue by lockywolf** [JabRef/jabref#6488]
JabRef version 5.1 Portable from the 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

![image](https://user-images.githubusercontent.com/2077025/82141223-fb64e100-9866-11ea-8e42-dbda90c5fbf8.png)

1. Launch JabRef
2. In the lower left corner, in the drop-down menu, select DBLP
3. Type in "abelson sussman"
4. Select "Structure and Interpretation of Computer Programs" 2nd Edition, 1996
5. Click import

The message appears. It is not clear at all what are the "duplicates" in question. Duplicate papers? Duplicate authors in a paper? Is it even connected to the papers I select, or is it something within my bibliography? Additionally, there is no icon anywhere, or at least there is nothing that would be "obviously the icon the message is speaking of".

I am not sure it is related, but for completeness, I am attaching the console log:

<details>
  <summary>Log File</summary>
  
  ```
Picked up _JAVA_OPTIONS:  -Dsun.java2d.uiScale=1.35 -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.

(JabRef:11752): Gdk-WARNING **: 17:47:48.377: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.


  ```
</details>

**Comment by WangAooa** [comment]
Hi, I would like to work on this issue. I'm going to add some details to make it easy to be understood.  Do you have other suggestions?

**Comment by koppor** [comment]
Confirmed.

In other words: The user started with an *empty database*. He imports a single entry. This entry is added. Then, JabRef complains that a duplicate exists. This is really wired.

Wild guess: Side-effect of https://github.com/JabRef/jabref/pull/6332, but I haven't checked.

**Comment by koppor** [comment]
Cannot reproduce with latest master. Please comment if the problem persists.
