### ISSUE TITLE
Select and toggle groups of files in Find unlinked files dialog

### ISSUE THREAD

**Issue by avm19** [JabRef/jabref#6490]
The requested feature should allow the user to do the following in the **Find unlinked files** dialogue:
- Highlight a contiguous group of files or directories via **Shift+Click** or **Shift+Up/Down** Arrows
- Highlight or un-highlight additional single files or directories via **Ctrl+Click** or **Ctrl+Up/Down** Arrows followed by **Ctrl+Space**
- Select ("tick") or unselect ("untick") the highlighted files or directories (with all its content) via a context menu command, additional button or by pressing **Enter**
- Select ("tick") or unselect ("untick") single files by pressing **Enter**

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the feature is absent.

Many thanks to the development and support teams for all the great work!

**Comment by mlep** [comment]
Other suggestions:
- only one button is needed for Select all and Unselect all
- only one button is needed for Expand all and Collapse all
