### ISSUE TITLE
Truncate DOIs and URLs in the column "Linked identifiers" in main table, if too long

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#6499]
DOIs and URLs should be truncated in the column "Linked identifiers" in main table, if too long, otherwise display issues arise.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

By the way, you do not need to open an issue before proposing a PR.
