### ISSUE TITLE
error opening bib

### ISSUE THREAD

**Issue by icamps** [JabRef/jabref#650]
Hello,

I update my JabRef to v3.1

Now, opening my bibtex database (attached) I got an error message (attached) that I do not know how to solve.

Regards,

Camps

[unifal.zip](https://github.com/JabRef/jabref/files/81500/unifal.zip)
![error_jabref_camps](https://cloud.githubusercontent.com/assets/13273938/12177763/0341a466-b555-11e5-8772-8b1efb14a659.jpg)

**Comment by oscargus** [comment]
Open the file in a text editor. Go to line 1516. See if there's a strange looking line there (missing a comma between fields). If you cannot find it copy +/-5 five lines and paste here.

Look at the end of the file. Seems like the last entry is not ended correctly. Again, paste the last five lines or so here unless you figure out what to fix.

**Comment by icamps** [comment]
I did that: nothing out of normal.

Here there are:
Lines 1513 to 1525:

@Article{dock_compare2,
  Title                    = {Evaluation of docking programs for predicting binding of Golgi $\alpha$-mannosidase {II} inhibitors: {A} comparison with crystallography},
  Author                   = {Pablo Englebienne and H\{'e}l\grave{e}ne Fiaux and Douglas A. Kuntz and Christopher R. Corbeil and Sandrine Gerber-Lemaire and David R. Rose and Nicolas Moitessier},
  Journal                  = {Proteins},
  Pages                    = {160--176},
  Volume                   = {69},
  Year                     = {2007},
  File                     = {dock_compare2.pdf:dock_compare2.pdf:PDF},
  Keywords                 = {docking},
  Owner                    = {icamps},
  Timestamp                = {2008.11.03}
}

Last lines:
@comment{jabref-meta: selector_publisher:}

@comment{jabref-meta: selector_review:}

@comment{jabref-meta: groupsversion:3;}

**Comment by oscargus** [comment]
The entry looks OK.

I think it might be the semi-colon at the end, but no idea really... Weird.

**Comment by icamps** [comment]
I remove the Latex code in H{'e}l\grave{e}ne, and I could open the file with the EOF error only.

**Comment by tobiasdiez** [comment]
Did you tried removing the last line?

So just to understand you correctly: the file opened without any problems in a previous version of jabref (which one?) and after the upgrade you got these errors, without changing the file. Right?

**Comment by icamps** [comment]
@tobiasdiez: 

Answer: Did you tried removing the last line?
Yes I removed various "last lines", unsuccessfully.

Answer: ...after the upgrade you got these errors, without changing the file. Right?
Yes, that's right.

Just now I fixed the problem manually: create an empty database, copy/paste all my entries, save the new database, and everything is ok.

**Comment by tobiasdiez** [comment]
Could you pls send me the problematic bib file (and the working one) via email to TobiasDiez@gmx.de if it does not contain sensitive information? Then I can better investigate this problem.

**Comment by icamps** [comment]
@tobiasdiez I already sent the files to your email.

**Comment by tobiasdiez** [comment]
There were two problems with the bib file (wrong format of the accent and not closed brackets in one entry). Thus it is correct that JabRef warns here.  

Nonetheless, there is room for improvement: the second warning occurs 1000 lines below the faulty entry. Not sure though to implement a better warning message (it should remember when a field started and then also print this additional information). Track this here or in a new issue?

**Comment by icamps** [comment]
@tobiasdiez Thank you very much. I will be more careful :)

**Comment by tobiasdiez** [comment]
@icamps You are welcome. Did you get my email with details how to fix the issues in the bib files?

**Comment by icamps** [comment]
Yes! I fixed and recovered the entries missed.

Thank you very much.


[]'s,

@mps
