### ISSUE TITLE
Would you have a timeline for official release of JabRef 5.1?

### ISSUE THREAD

**Issue by AlexPars** [JabRef/jabref#6500]
Please use the GitHub issue tracker only for bug reports and suggestions for improvements.
Feature requests, questions and general feedback is now handled at http://discourse.jabref.org.
Thanks!

**Comment by tobiasdiez** [comment]
We do not have a particular release schedule. There are still a few issues that we want to address before releasing 5.1. You can follow the progress here https://github.com/JabRef/jabref/milestone/20.

Feel free to try out the latest development version: http://builds.jabref.org/master/.
