### ISSUE TITLE
GUI updates very slow on every other action

### ISSUE THREAD

**Issue by tilltnet** [JabRef/jabref#6501]
JabRef version 5.0 and 5.1 dev on Mac OS X 10.14.6 (tried dmg/pkg/portable)

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open Application create new (small) library.
2. Try actions as clicking on entry, deleting, adding entries.
3. Every other action will take a long time before the GUI elements get updated.

This is a screen recording. I do get a spinning beach ball when the GUI is frozen, but for some reason the screen recorder only records the regular mouse pointer.

![Screen Recording 2020-05-15 at 12 34 42 PM](https://user-images.githubusercontent.com/8319636/82226780-eb93de00-98f4-11ea-9cdf-b49e750fc385.gif)

**Comment by MelleNi** [comment]
Same issue here on 10.14.6 with all versions. Absolutely unusable.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by tilltnet** [comment]
Yes, it works smooth now! Thanks for the fix!

**Comment by homocomputeris** [comment]
@tobiasdiez  The issue appears again in 5.1 and 5.2-master 2020-10-26: the spinnig ball, freezes, very long wait times to switch tabs, etc.
