### ISSUE TITLE
Author parser has problem with latex symbols

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#651]
The author `H{'e}l\grave{e}ne Fiaux` is shown as `Fiaux, H'e.` in entry preview. Would have expected `Fiaux, H`.

**Comment by icamps** [comment]
Yeap.

I remove all the latex stuf, and opened ok (the EOF error persist).

**Comment by oscargus** [comment]
One should probably use the bibtex-VM-based name formatters.

**Comment by tobiasdiez** [comment]
Note that the above is a bad example since the correct way to write the acute accent is `\'{e}` and `H\'{e}l\grave{e}ne Fiaux` is correctly written as `Fiaux, H.`.

However, `H{e}lene Fiaux` results in the unexpected `Fiaux, He`.

**Comment by simonharrer** [comment]
I propose to close this as it is only a very minor bug which only occurs in very special circumstances with bad input. Any objections @JabRef/developers ?
