### ISSUE TITLE
The maintable authors' column does not update on preference change

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [JabRef/jabref#6515]
In JabRef 5.0--2020-03-09--6bff936 changes in `preferences -> entry table -> Format of author and editor names` updates the column. E.g., changing from "Firstname Lastname" to "Lastname, Firstname" is immediately shown.

In the current master (built from Intellij on Mac OS 10.15.4 the 23rd of May) changes requires a restart before the author column updates.
It also does not work with
JabRef 5.1--2020-05-22--ef2a31c
Mac OS X 10.15.4 x86_64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Attempt to change the style of the authors' column
2. Press save
3. Notice that the format of the authors' names are not changed
4. Easiest to spot with "Firstname Lastname" to "Lastname, Firstname"

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by LuckyOne09** [comment]
Maybe I could try to check what differences are between these two version and find solution to enhance it ^_^

**Comment by Siedlerchr** [comment]
Thanks for your interest, there recently have been some refactorings of the preferences, maybe that is related (@calixtus )

**Comment by calixtus** [comment]
Thanks for the bug report. In fact, this is related to a deeper issue with the preferences, which existed already before I started refactoring the preferences. In the long run, the refactorings target to provide a clean solution for this one besides others.

Possible workaround: close and reopen the library in JabRef.

I'll look for a temporary quick fix for this issue.

**Comment by calixtus** [comment]
Funny, I already started to work on the main table preferences on friday, but did not yet create a pull request. 😄
