### ISSUE TITLE
jabref_5.0-1_amd64.deb is corrupt

### ISSUE THREAD

**Issue by jkbsc** [JabRef/jabref#6526]
This file

https://www.fosshub.com/JabRef.html?dwl=jabref_5.0-1_amd64.deb

will not install after I download it.

    # apt install ./jabref_5.0-1_amd64.deb

reports that the metadata is not found.

Thanks,
John

**Comment by Siedlerchr** [comment]
Have you tried sudo dpkg -i path_to_deb_file?

**Comment by jkbsc** [comment]
Well, the dpkg command works better in that it claims to succeed but there is no executable present.  Something odd has happened.  I am using the portable version for now.

**Comment by Siedlerchr** [comment]
Hmm that's mysterious. Maybe the package was broken.
you could also use the snap version of JabRef (if you don't need libre office connexio)

**Comment by FossHub** [comment]
Can anyone from Jabref team confirm that the file signatures match? We upload what we receive from the team, but considering we replicate the files to multiple CDN providers, this could be a bug. The project manager should see the file signatures along with the virus scan results.

**Comment by Siedlerchr** [comment]
@jkbsc   Dpes the file from our github release page works? 
https://github.com/JabRef/jabref/releases

**Comment by jkbsc** [comment]
****

> @jkbsc Does the file from our github release page works?
> https://github.com/JabRef/jabref/releases
> @koppor

Same behaviour. It feels as if this version maybe works and there is something up with my configuration.  I did a CRC check on the two files (Fosshub and the above) and they are identical.

**Comment by Siedlerchr** [comment]
Could you also please try the latest dev version?
https://builds.jabref.org/master/
if it doesn't work either, it seems something on your system is broken

**Comment by FossHub** [comment]
You just confirmed that the files are identical on FossHub and GitHub. At this point, the problem is not on our end. Thank you!

**Comment by jkbsc** [comment]
Agreed, something up with my configuration. Thanks for the help.

**Comment by koppor** [comment]
Is this an issue that other users also might encounter. Then it would be a good thing to add it to the FAQ.

**Comment by jkbsc** [comment]
Ok, so analysing my errors in case it helps with the FAQ:

- I used # apt install path/to/jabref_package.deb and this fails.
- When I used # dpkg -i  path/to/jabref_package.deb, I now believe that it
  always worked, whether I used the fosshub file, the jabref download or,
  lastly, the 5.1 version as linked in the bug report

However, I was looking for a command

$ jabref

on the command line, whereas the executable is called JabRef (case-sensitive)
and there is no link put into /usr/bin in any case.  I see that the executable
is expected to be called from a desktop menu or as the handler for a bibtex
file.

Incidentally, the version in the standard repos is jabref 2.10, which means that

# apt install jabref

would work but would get a poor outcome.


Hope this helps.
