### ISSUE TITLE
Add more menu items to tab context menu

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6527]
JabRef 3.8.2:

![grafik](https://user-images.githubusercontent.com/1366654/82867871-e3a6f000-9f2b-11ea-8cc7-031aceb5d115.png)

The old implementation is available at https://github.com/JabRef/jabref/commit/88bae8571a5afc0ba9967745f57d74347db112ad. Maybe, this some sort of inspiration.

**Comment by Hollyqqqqq** [comment]
Hi, I am interested in this issue. 
If no one is working on this issue, I'll try to work on it these two days.^_^

**Comment by Hollyqqqqq** [comment]
Hi, I have add the menu items as following:
![image](https://user-images.githubusercontent.com/55199983/83178854-b6d52180-a153-11ea-9e26-b4bb2cec7d41.png)

Is it enough or it needs more other menu items?

**Comment by Siedlerchr** [comment]
@Hollyqqqqq  Thanks, that looks good to me! That should be sufficient for the moment

**Comment by Hollyqqqqq** [comment]
OK^_^
I will try to write some tests, and then create pr.

**Comment by Hollyqqqqq** [comment]
Sorry, I got stucked into how to run tests although I have some ideas to write tests. There are always errors like "Error(19, 33) java: program package org.jabref.logic.journals not exist" when running both original tests and the tests I added. I have troubles to solve these errors.

Then, I will just create pr for codes that fix this issue and skip the tests codes for the moment.

**Comment by tobiasdiez** [comment]
Thanks to @Hollyqqqqq this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
