### ISSUE TITLE
[Enhancement] Numbers in the file picker drop-down menu

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6529]
JabRef 5.1--2020-05-26--0d7156b
Linux 5.3.0-53-generic amd64 
Java 14.0.1

**Is your suggestion for improvement related to a problem? Please describe.**

When opening a recent library file, File/Recent libraries, the list of recent libraries is numbered.  

**Describe the solution you'd like**

I would expect that typing one of the displayed numbers would open that library.  That's the common behaviour in other programs that have numbered file lists  like this.

![image](https://user-images.githubusercontent.com/762246/82959229-74092300-9f74-11ea-80e8-a0ac9acddea6.png)

**Comment by Siedlerchr** [comment]
Thanks to @Hollyqqqqq  this is now implemented in the latest master version. (currently building).
When that menu is open, you will be able now open the libraries by using the number keys.-
