### ISSUE TITLE
Support more than two preview styles

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#653]
Currently, one can select between two different preview styles. It should be more a matter of interface design to support more than two. Basically the following:

- [ ] Change preference tab to a list of styles and a single style editor
- [ ] Change the way the preview styles are stored in the preferences
- [ ] Change "Switch preview layout" to cycle through the list rather than switching between the two

As a bonus/alternative:
- [ ] Store each layout in a file which can be edited/opened/saved from the editor. (Will simplify sharing preview layouts and also simplify storing in preferences.)

**Comment by simonharrer** [comment]
Related to #119

**Comment by oscargus** [comment]
Focus on CitationStyles #654 .
