### ISSUE TITLE
Opening the menu 'Library properties' marks the database as modified

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6541]
JabRef 5.1--2020-05-26--0d7156b
Linux 4.9.0-12-amd64 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When opening the menu "Library properties", the database is instantaneously marked as modified (a star is displayed in the title of the tab).

1. Open a library 
2. Click on the menu Library -> Library properties
==> The window Library properties opens. And, simultaneously, the library is marked as modified.
3. Click on Cancel, and exit JabRef
==> The message "Save before closing" is displayed, confirming the database is considered as changed.

**Comment by Siedlerchr** [comment]
I debugged it and found out that as soon as no saveActions are present for the current library metadata, then the default save actions are set for the current library metadata and a Changed-Event is posted which marks the library with an asterisk.

I think the line 131 is wrong here. Opening without changing anything should not have any effect, metadata should only be changed when I click save.  We need to think a bit about other side effects.

https://github.com/JabRef/jabref/blob/bb19d29abb3fabc29c2a9b5b8f7b4ded0085d00e/src/main/java/org/jabref/gui/libraryproperties/LibraryPropertiesDialogViewModel.java#L127-L131

**Comment by Siedlerchr** [comment]
Should now be fixed in latest master (currently building, ready in roughly half an hour)

**Comment by mlep** [comment]
Thank you @Siedlerchr, this is fixed in JabRef 5.1--2020-06-16--bc63ccb.
