### ISSUE TITLE
Small icon for files in Windows 10

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#655]
For some reason the small icon is used even if the bib file is displayed bigger. See here.
![bug](https://cloud.githubusercontent.com/assets/5037600/12209705/2e584dd4-b655-11e5-9a43-ecd97e950689.png)

**Comment by simonharrer** [comment]
Maybe related to `JabRef.VisualElementsManifest.xml`?

**Comment by stefan-kolb** [comment]
We need a full icon set and decide which icon we want to use.
Currently, we use a different JabRef icon for Mac and Windows.

Refs:
Full icon set: https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485.aspx
