### ISSUE TITLE
jabref does not shut down (on Linux); process keeps running

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6559]
- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

JabRef 5.1--2020-05-29--ed275b6
Linux 5.6.14-300.fc32.x86_64 amd64 
Java 14.0.1

Not on every run, but often, shutting down jabref does not cleanly proceed. A process continues to run for many minutes. Maybe related to https://github.com/JabRef/jabref/issues/5071 ?

If you give me pointers for how to investigate this further, I am happy to do.

**Comment by ilippert** [comment]
This continues to be a problem with the recent builds.

**Comment by ilippert** [comment]
JabRef 5.1--2020-06-08--b810356
Linux 5.6.16-300.fc32.x86_64 amd64 
Java 14.0.1

Issue is still present - Jabref hangs my system... no error messages.

**Comment by ilippert** [comment]
Sorry, it is really quite terrible - jabref simply does not shut down - a process continues to run and slow down my computer. no error messages.

**Comment by Siedlerchr** [comment]
Seems to be some linux issue, I cannot reproduce it on Windows. Maybe some file watching is still in the background active?

**Comment by ilippert** [comment]
thanks for reacting. It is running for hours, literally... it must have been introduced, I assume, at some point before 2020-05-29--ed275b6. I am not aware of a change of my file system.


now
JabRef 5.1--2020-06-17--ef0a6bb
Linux 5.6.18-300.fc32.x86_64 amd64 
Java 14.0.1

ok, I am testing systematically for some minutes:

- 3 minutes running with 1 file. no problem to shut down, CPU at around 2-10%
- 10 minutes running with 2 files. no problem to shut down, CPU at around 2-10%
- 3 minutes running with 3 files. **problem to shut down**, CPU at 50%. files in different folders
- 3 minutes running with 3 files. no problem to shut down, CPU at around 2-10% files in different folders
- 3 minutes running with 3 files. **problem to shut down**, CPU at 95%. I had to kill it. files in different folders
- 3 minutes running with 3 files. **problem to shut down**, CPU at 34%. I had to kill it. files in different folders
- 10 minutes running with 2 files. no problem to shut down, CPU at around 2-10%
- 5 minutes running with 3 files. no problem to shut down, CPU at around 2-10%. files in same folder.
- 30 minutes running with 2 files. no problem to shut down, CPU between 2-60% files in different folders

Hmm, I do not see any pattern.

**Comment by sanjayankur31** [comment]
I also see this on Fedora 32:
```
jabref-5.0.50001-1.x86_64
```

Often when I've closed Jabref, processes are still running:
```
3969481 /opt/jabref/bin/JabRef
```

![jabref-processes](https://user-images.githubusercontent.com/102575/85207001-b3315680-b31d-11ea-94e2-21644cd60572.png)


I haven't tried the dev builds yet. I can collect more info if someone can tell me what info is needed.

**Comment by Siedlerchr** [comment]
Try a  `kill -QUIT <pid>`  to get thread dump from the jvm

Alternatively 
You could try to use jconsole: https://docs.oracle.com/en/java/javase/14/management/using-jconsole.html#GUID-EFDD2B40-6E4B-45E9-84B2-5E6D609065AE
Or you could try jstack to get a thread dump.
https://programmer.ink/think/jdk14-performance-management-tool-introduction-to-jstack.html

**Comment by ilippert** [comment]
`kill -QUIT <pid>` does not generate any visible result; process is not killed.

Just to check: for jstack and jconsole - do I need to download jdk14 from oracle?

**Comment by Siedlerchr** [comment]
You need jdk 14, you can use the openjdk variant. 
https://bell-sw.com/pages/downloads/

**Comment by ilippert** [comment]
Hi, please find the `jstack -l -e` output in the txt file

[jstack-jabref.txt](https://github.com/JabRef/jabref/files/4812619/jstack-jabref.txt)

**Comment by Siedlerchr** [comment]
Thanks, that looks indeed helpful. It is somehow related to the search and to the recent implementation of the authors parser #6552

**Comment by ilippert** [comment]
happily I can report that jabref

JabRef 5.1--2020-06-30--5f2b994
Linux 5.6.19-300.fc32.x86_64 amd64 
Java 14.0.1

has now been running for 3h without problems - let's see for how long it runs ;)

**Comment by ilippert** [comment]
ending my observation for the day. jabref successfully ran for 16h, well interrupted by computer sleeping. but still. and CPU use was very low. great, too.

**Comment by ilippert** [comment]
I am afraid I must report that the same jabref version has the old behaviour today again ;( too optimistic, I was. So, no visible change.

**Comment by ilippert** [comment]
JabRef 5.1-PullRequest6528.793--2020-07-11--93eaf4f
Linux 5.7.7-200.fc32.x86_64 amd64
Java 14.0.1

a correlation: when jabref CPU use goes up, I cannot save the library anymore.

**Comment by ilippert** [comment]
JabRef 5.1--2020-08-03--586044a
Linux 5.7.11-200.fc32.x86_64 amd64 
Java 14.0.2

> a correlation: when jabref CPU use goes up, I cannot save the library anymore.

still not functional on
JabRef 5.1--2020-08-03--586044a
Linux 5.7.11-200.fc32.x86_64 amd64 
Java 14.0.2

I am very happy to conduct more tests/provide more logs if that might help.

**Comment by vsht** [comment]
It seems that installing `bellsoft-java14` according to https://bell-sw.com/pages/repositories/#yum fixes the issue for me
on Fedora 32 (using the latest dev build of JabRef). 

Without Liberica JDK installed (i.e. just having the standard OpenJDK from Fedora repos)
JabRef generates 100% CPU load on all cores roughly 1 min after being launched.

**Comment by ilippert** [comment]
JabRef 5.2--2020-09-01--35f5078
Linux 5.8.4-200.fc32.x86_64 amd64 
Java 14.0.2

as recommended by @vsht, I now use `bellsoft-java14`. My immediate observation is this: CPU load is ok. However, I still cannot close jabref. Process continues to run.

**Comment by Siedlerchr** [comment]
I think we finally found the issue for the problem with the shutdown. The fix just got merged, so it would be nice if you could test  the new version in a few hours.

**Comment by vsht** [comment]
In my case 

JabRef 5.1--2020-08-28--5540b93
Linux 5.8.4-200.fc32.x86_64 amd64 
Java 14.0.2

JabRef already shut downs properly. My only issue was the CPU load and that one got fixed by installing
that other JVM.

**Comment by ilippert** [comment]
Hi

JabRef 5.2--2020-09-03--1283f9f
Linux 5.8.6-201.fc32.x86_64 amd64 
Java 14.0.2

hmm, sorry, I am afraid whilst it does work to close jabref now without error messages, it also happened at least one time that the process was not actually ended.

**Comment by ilippert** [comment]
Just crashed still with 80% CPU load

JabRef 5.2--2020-09-09--46e9fe2
Linux 5.8.7-200.fc32.x86_64 amd64 
Java 14.0.2

**Comment by ilippert** [comment]
JabRef 5.2--2020-09-09--46e9fe2
Linux 5.8.7-200.fc32.x86_64 amd64 
Java 14.0.2

does not reliably shut down. Sometimes the process keeps running after the window closes.

@Siedlerchr - sorry to report this. Should I open a new issue or would you reopen this?

**Comment by Siedlerchr** [comment]
Thanks for the report. I am working on a solution. Think have found the underlying issue.

**Comment by ilippert** [comment]
JabRef 5.2--2020-12-12--86e2c82
Linux 5.9.12-200.fc33.x86_64 amd64 
Java 15.0.1

gets me again 90%ish CPU load with `openjdk version "14.0.2" 2020-07-14`.

https://github.com/JabRef/jabref/issues/6559#issuecomment-683448217 points me to bellsoft-java. I use `bellsoft-java15` now. That works fine.

**Comment by ilippert** [comment]
JabRef 5.3--2021-02-03--242a494
Linux 5.10.11-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 15.0.1+1

Well, it happens again, JabRef does not shut down reliably, a process continues to run, using between 30 to 90% CPU.

A new dimension of this issue (or should this be a new issue?): when I shut down, and try to start JabRef anew a few seconds later, then Linux system freezes.

**Comment by Siedlerchr** [comment]
Do you have a shared sql database opened?
I noticed that it takes some time after exiting for JabRef to stop the process

**Comment by ilippert** [comment]
> Do you have a shared sql database opened?

No, I am not using sql databases.

**Comment by ilippert** [comment]
Problem continues.

**Comment by vsht** [comment]
True. Especially using the search bar (e.g. to search for author names) and leaving the filtered view
for longer time (i.e. by not clearing the search bar) seems to trigger it.

**Comment by ilippert** [comment]
JabRef 5.3--2021-04-29--cfb14b2
Linux 5.11.16-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 16+8

problem continues

**Comment by ilippert** [comment]
> True. Especially using the search bar (e.g. to search for author names) and leaving the filtered view
> for longer time (i.e. by not clearing the search bar) seems to trigger it.

JabRef 5.3--2021-05-15--0a26d31
Linux 5.11.19-200.fc33.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

I also suspect that the comment on the search bar detects something important! It seems to be a good predictor of how to get CPU use at 100%.

**Comment by Siedlerchr** [comment]
Do you have autocomplete enabled?

**Comment by ilippert** [comment]
autocomplete is enabled for the entry editor.

**Comment by ilippert** [comment]
JabRef 5.3--2021-06-17--38d7a30
Linux 5.12.11-300.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

meanwhile slightly updated system - no significant change.

I often seem to observe, that jabref hangs when I search for something and then go for entry editor tab that includes a local file field.

**Comment by ilippert** [comment]
JabRef 5.3--2021-07-16--c99d61c
Linux 5.13.4-200.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

no change ;)

**Comment by ilippert** [comment]
JabRef 5.3--2021-07-16--c99d61c
Linux 5.13.7-200.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

I have now disabled autocomplete.

But I have changed one aspect today - with seeming success: the jabref _preference_ window told me to not include specific signs twice today: once in the entry editor dialogue and once in the custom editor tabs dialogue. I checked and found I was using a "prohibited" sign in there. I am not sure how many months or years ago I had created these field names. But I have now removed the prohibited signs and seemingly JabRef runs and closes stable now. I will observe this for a bit longer and report back.

**Comment by ilippert** [comment]
> But I have changed one aspect today - with seeming success: the jabref _preference_ window told me to not include specific signs twice today: once in the entry editor dialogue and once in the custom editor tabs dialogue. I checked and found I was using a "prohibited" sign in there. I am not sure how many months or years ago I had created these field names. But I have now removed the prohibited signs and seemingly JabRef runs and closes stable now. I will observe this for a bit longer and report back.

I have now run JabRef for many hours today without the problems I had for a year or so. So, maybe that was the issue.

Suggestion: could JabRef notify the user in a more accessible way that their preferences are set with a problem - such as saying, Dear user, you have an illegal field name OLD1, OLD2 in the Preferences section "entry editor" and the "custom editor tabs". This risks unstable behaviour. Suggested field names are NEW (removed prohibited characters). Shall all the field names "OLD" be updated to NEW in the library?

**Comment by Siedlerchr** [comment]
Thanks for the analysis! I'm sure we can add a preferences migration. Can you please specify which "illegal character" you entered/had there?
And we can also add a check when saving the changes

**Comment by ilippert** [comment]
Ok, further testing:

in the preferences/_entry editor_, when I add the  "illegal character" `-`, I do not get a warning. And I am able to add the "illegal character".

When I add `-` at _custom editor tabs_, I get the warning
![Screenshot from 2021-08-08 20-10-23](https://user-images.githubusercontent.com/20518297/128641559-41326ca7-86ae-44ab-b5dc-6dfb7c8f7216.png)

and the save button lets me save/proceed, but the "illegal character" is actually not saved.

I believe I had entered the `-` years ago. So a migration check might be helpful, or a once a month consistency check run might be helpful.

The window
![Screenshot from 2021-08-08 20-10-23](https://user-images.githubusercontent.com/20518297/128641559-41326ca7-86ae-44ab-b5dc-6dfb7c8f7216.png)

only is partially helpful: it might be better to highlight which specific character I am not supposed to be using - and the complete list of illegal characters is still helpful, but of secondary importance. 

This morning, when I changed the field names, I also got the  window
![Screenshot from 2021-08-08 20-10-23](https://user-images.githubusercontent.com/20518297/128641559-41326ca7-86ae-44ab-b5dc-6dfb7c8f7216.png)

at the _entry editor_ section.

**Comment by ilippert** [comment]
Given that I am now on
JabRef 5.5--2022-01-02--55ceed9
Linux 5.15.12-200.fc35.x86_64 amd64 
Java 16.0.2 
JavaFX 17.0.1+1
and have not encountered the issue for a while anymore, I am closing this issue - but of course other are welcome to comment to ask for this to be reopened/or to reopen yourself...
