### ISSUE TITLE
Connection Check for HTTP Proxy

### ISSUE THREAD

**Issue by KaenbyouR** [JabRef/jabref#6560]
Hi there, I would like to request a feature for HTTP Proxy connection check. Unlike some IDE such as IntelliJ IDEA, there do not have a check button for proxy connection. I would like to have a URL written, and verify if a connection via proxy to that URL is ok. A dialog box shown said that "Connected successfully" or "Connection failed". Thx

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
