### ISSUE TITLE
langid field not provided if not already present in the entry

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6576]
JabRef 5.1--2020-05-29--ed275b6
Windows 10 10.0 amd64 
Java 14.0.1
- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The field "langid" is no more offered by the entry editor. If the field is already present in the .bib file it appears in the editor under "Other fields" tab. This field is needed for multi-language bibliographies.
 
1. Create a new entry of type "Article" or "InProceedings"
2. The field "langid" is not present
3. Open a bib file with an entry that has the langid field.
4. Note the langid field is accessible in JabRef

**Comment by Siedlerchr** [comment]
JabRef only provides the field language. However, you can simply add the field langid to the entry types using the Customize Entry types dialog.
Just type in langid in the field combobox and add it as required or optional

**Comment by crystalfp** [comment]
OK, this works. Thanks for remembering me JabRef functionalities I never used. But:
1) I added `langid` as optional, but the + button is disabled, I have to click in the other (left) field to have it enabled.
2) The dropdown menu of this field is useless because it lists only few field, seems the ones already added, so I have to type `langid`
3) In the editor the new field is added at the beginning, not in alphabetical order. This is quite distracting.
Maybe now this issue could become a usability bug.
Thanks for considering!

**Comment by Siedlerchr** [comment]
We are already  working on improving the handling and manually defining an order which will be used in the entry editor as well
Refs #6152 and #6338

**Comment by crystalfp** [comment]
OK, so the solution is already in the making. Perfect, thanks! So I close this issue.

**Comment by Siedlerchr** [comment]
@crystalfp The order of the fields in the CustomEntryTypesDialog now reflects the order of the fields in the entry editor. Note that it still distinguishes between optional/required fields. Fields are grouped by required/optional.
The fields can be reordered with drag and drop.

I would like you to test the current implementation. Maybe you have some ideas how to imrpove the user experience
https://builds.jabref.org/pull/6152/merge/
Please remember to make  a backup of your library before trying out this verison.

**Comment by crystalfp** [comment]
Thanks @Siedlerchr ! The drad-and-drop works, but it has no effect on the ordering in the entry editor. I put the evergreen `langid` as optional after Number, but in the editor it comes as first entry in the Optional fields tab.

**Comment by Siedlerchr** [comment]
Thanks, indeed I could reproduce it. It seems this ordering does not work when it's a non standard field.

**Comment by Siedlerchr** [comment]
@crystalfp  Could you please test the latest build from here https://builds.jabref.org/pull/6152/merge/ again?
The issue with the order is now resolved.

**Comment by crystalfp** [comment]
OK, seems to work. The only minor thing is the spacing of the added item in the list. In the Optional Fields tab below I added the `langid` field:
![image](https://user-images.githubusercontent.com/865866/85987184-98ca3d80-b9ed-11ea-9e98-405712b3c15c.png)
