### ISSUE TITLE
Custom export format biblatex date field to bibtex year, month and day ones.

### ISSUE THREAD

**Issue by webanck** [JabRef/jabref#6579]
Hello, I see date processing is still in the pipes ! (See issues #1249 and #6224)

Almost two years ago (see [here](https://discourse.jabref.org/t/custom-export-filter-month-field/1214)), I asked for a way to write a custom export with dates from the biblatex `date` field to bibtex `year`, `month` and `day` fields with an emphasis on the `month` field (I am not the first one, see [here](https://discourse.jabref.org/t/date-eventdate-dateformatter/330)).
I tried using the [DateFormatter](https://docs.jabref.org/collaborative-work/export/customexports#built-in-export-formatters) but an error is still raised when the `date` field doesn't resolve as a full ISO date (`YYYY-MM-DD`), and even if it worked, it would only output the month number, and not the bibtex equivalent.

Any clue on how to solve this ?

**Comment by webanck** [comment]
Well, in fact, it is very easy to solve now as all fields seem well treated as valid aliases now.

The custom export filter as
```
\begin{year}  year = \year\end{year}\begin{month},
  month = \month\end{month}\begin{day},
  day = \day\end{day}
```
will now output entries as
```
  year = 2018,
  month = May,
```

**Comment by webanck** [comment]
Well, in fact, it only works for the month of May because it is already a 3 characters long string, but for January for instance, the full month name will be output, instead of `Jan`.
So my initial problem is still not solved :(
There is no formatter documented to output the month in the same format as the bibtex field !
Even the undocumented [RisMonth](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/layout/format/RisMonth.java) format makes the assumption of a month formated in a short name.

**Comment by Siedlerchr** [comment]
Have you seen the DateFormatter? https://docs.jabref.org/collaborative-work/export/customexports#built-in-export-formatters

**Comment by webanck** [comment]
Yeah, I tried but it doesn't work, as you saw (I added an explicit mention about it in the first message of this issue).

**Comment by Siedlerchr** [comment]
I currently see no existing solution, so you would need to write your own Formatter which can format Months

**Comment by Siedlerchr** [comment]
Thanks to @joethei there's now a new Short Month Formatter 

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version. 
.
