### ISSUE TITLE
Remember the size of "Possible duplicate entries" window

### ISSUE THREAD

**Issue by avm19** [JabRef/jabref#6582]
Current behaviour:
In the "Find duplicates" dialogue (**Quality -> Find duplicates**) each "**Possible duplicate entries**" window pops up with the default size. If the size of the window changed (to see all content without scrolling), the same window for the next collision will appear with its default size. This creates uncomfortable user experience.

Desired behaviour:
If the user resizes or moves the "Possible duplicate entries" window, JabRef remembers its size and position until the dialogue is over (or within current session, database, or installation). Newly created windows for next possible duplicates are of the same size and at the same position as their predecessors in the series.

**Comment by telvinzhong** [comment]
I can take a crack at this!

**Comment by tobiasdiez** [comment]
Thanks to @gdstewart this is now implemented in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
