### ISSUE TITLE
Remove old jars during installation

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#659]
Currently, install4j does not remove the old JARs. It can do so when we add [an "Uninstall previous installation" action to our "Installation" screen](http://stackoverflow.com/a/25739098/873282). I am not aware of side effects, therefore I'm not taking a quick action. Some users report that "this also removes the desktop shortcut as part of the uninstall and doesn't re-add it in the installation", therefore fixing this should be done with care.

**Comment by stefan-kolb** [comment]
I think the uninstall previous installations action is already activated. However, it behaves a little bit strange. when I install a dev version and a full version afterwards it does not recognize the dev version. If i install a newer dev version afterwards it works and removes all other installations. We need to check the  necessary properties and test some installations.

**Comment by simonharrer** [comment]
This works already since 8549b9b by who who must not be named ;)
