### ISSUE TITLE
DOI fetcher for medra 

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6602]
**Is your suggestion for improvement related to a problem? Please describe.**

A DOI I was searching for recently didn't work from within Jabref.   10.2143/JIABS.41.0.3285748

When I tried [Crossref.org](http://crossref.org) directly, it also didn't work. When I queried the publisher, they said they registered their DOIs with [Medra,](https://www.medra.org/) not Crossref, because they are a European publisher.  

I find this an inadequate answer from the publisher.  The whole point of DOIs is that they should be universal, not grouped in ghettos.

**Describe the solution you'd like**

Nevertheless, if that is how it is, could JabRef please also fallover to the Medra resolver if crossref doesn't work

**Comment by Siedlerchr** [comment]
Thanks, yeah I always thought that all DOIs can be resolved from every register. But apparently not.
But this implementation should be straight forward as it supports content negotiation as well for bibtex
http://data.medra.org/

**Comment by mind000** [comment]
Hi,
this could be my first time contribution. I've already set up the local project and worked on the issue by myself. 

I think I've made the modification needed to retrieve DOI metadata from mEDRA, but I'm facing an issue on several DOIs and I'm waiting an answer from mEDRA team. 
Some of their registered DOIs, queried through their content negotiation api at [https://data.medra.org/](https://data.medra.org/) return 500 internal server error. The same DOIs queried through Crossref API at [https://api.crossref.org/works/](https://api.crossref.org/works/) are correctly retrieved and the agency check at [https://api.crossref.org/works/{DOI}/agency](https://api.crossref.org/works/{DOI}/agency) correctly detects mEDRA as the owner.

As soon as I will have any more info I will update here.

**Comment by Siedlerchr** [comment]
@mind000  Welcome! That sounds already good! Thanks for taking this issue. If you don't mind, you can already create a PR so we can review your code changes
