### ISSUE TITLE
Can't edit "Set up general fields"

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6604]
JabRef version  on 

JabRef 5.1--2020-06-08--b810356
Linux 5.3.0-53-generic amd64 
Java 14.0.1

1. Options/Set up general fields
2. Don't change anything.   (Or do.)
3. Hit OK
4. Error popup.

![image](https://user-images.githubusercontent.com/762246/84203676-117d5000-aa67-11ea-9bb9-34f1b1f505c1.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks to @alex-petrov-vt  this should now be fixed in the latest master (currently building)

**Comment by wujastyk** [comment]
JabRef 5.1--2020-07-01--c83ea3f
Linux 5.4.0-39-lowlatency amd64 
Java 14.0.1

Confirming the fix.  Many thanks!
