### ISSUE TITLE
Add auto-updater for development builds

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#661]
In view of the more regular release schedule, it would be nice if JabRef can perform an auto-update.

**Comment by stefan-kolb** [comment]
Definitely :+1:

**Comment by koppor** [comment]
install4j offers that functionality and also generates an [updates.xml](https://circle-artifacts.com/gh/JabRef/jabref/2337/artifacts/0/home/ubuntu/jabref/build/releases/updates.xml). Have to investigate where to put that file and how to automate that process.

Currently, I think, it should be put at https://www.jabref.org/updates.xml. Since that page is served via github, we currently do not get a valid SSL certificate. [It doesn't seem possible to offer SSL at custom domains](https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it). Thus, I have to provide https://updates.jabref.org/updates.xml or https://builds.jabref.org/updates.xml or https://files.jabref.org/updates.xml. Think, builds.jabref.org is the right choice, isn't it?

**Comment by simonharrer** [comment]
:+1: but needs to be automated so this is not too much a hassle.

**Comment by tobiasdiez** [comment]
[Apperently](http://stackoverflow.com/questions/8226486/how-to-configure-install4j-versioning-to-allow-both-stable-and-beta-alpha-upgrad), it is relatively easy to support a special channel for dev-builds.

**Comment by obraliar** [comment]
Stupro features team would like to take care about this issue for the 3rd sprint which just started.

**Comment by stefan-kolb** [comment]
This would free users from downloading from our affiliate sites. How much income do we potentially lose with this?

**Comment by koppor** [comment]
The income numbers are confidential, because of company regulations.

**Comment by simonharrer** [comment]
Ask github API whether newer version exists
Menu option: Help - Check for update
During startup: check and if newer display this somehow

**Comment by matthiasgeiger** [comment]
Important for usability: Checkbox: "Do not notify for this update again" or sth like this.

**Comment by matthiasgeiger** [comment]
Example from TexStudio:
![auto-update](https://cloud.githubusercontent.com/assets/676652/15392834/ea729a98-1dc9-11e6-8c1e-99fb76a53f22.png)

@obraliar Any news on this topic?

**Comment by obraliar** [comment]
Due to decision problems we switched to other topic in this sprint. Full steam ahead now we are working on shared-database support. Should we implement only a checker (see https://github.com/JabRef/jabref/issues/984) without updating the software?
If this is clear, we are going to implement this quickly in the next sprint which starts on 5th June.

**Comment by matthiasgeiger** [comment]
Allright - no problem ;-)

Before implementing a solution it would be great if you can evaluate which possibilities install4j provides for updating a program.

**Comment by Siedlerchr** [comment]
I would vote for just adding a dialog like in TexStudio.
Regarding install4j, it should also be evaluated how it support building msi packages for easier rollout on Windows environments and how to handle updates.  A  typical scenario is to automatically deploy software to Windows PCs in the network.

**Comment by koppor** [comment]
Implement it like Simon and Matthias said:
 - https://github.com/JabRef/jabref/issues/661#issuecomment-218168994
 - https://github.com/JabRef/jabref/issues/661#issuecomment-218170361

I think, @mairdl can do it.

**Comment by mairdl** [comment]
We are currently working on it. Our first prototype looks like this
<img width="288" alt="newversion" src="https://cloud.githubusercontent.com/assets/15333533/15575718/97de1baa-2354-11e6-8fee-bdfb09b37c22.png">
Feel free to leave suggestions about the layout.

**Comment by Siedlerchr** [comment]
Like the Ignore Update and Remind me Later. 

I would change the text from Visit Downloadpage to simply Download (update).
And add a description text like in TexStudio, e.g. A new version of JabRef is avaiable. 
And add some bottom line text, For more information and a changelog  visit the website www.jabref.org.
Or maybe simpler: To see what's new visit the website (clickable Link). 


Regarding the behavior of the dialog: When you open JabRef for the first time then the dialog should be displayed, in case a new version is available.

**Comment by bartsch-dev** [comment]
![updatepopup](https://cloud.githubusercontent.com/assets/15333371/15587100/f9589300-2387-11e6-9634-4fe1344407f4.JPG)
The download button leads the user to http://www.jabref.org/#downloads.
If the user clicks the ignore button this update will be ignored by automatic updates, when the updatesearch is manually started by the user this update will be suggested again.
When remind me later is clicked the update will popup whenever the next versioncheck is performed.

An automated versioncheck will be performed dependend on the users preferences.

![updatepreferences](https://cloud.githubusercontent.com/assets/15333371/15587225/8860cae0-2388-11e6-9a66-96ee6b479334.jpg)

**Comment by Siedlerchr** [comment]
Good work :+1:
For me it's looking perfect now.


2016-05-26 21:28 GMT+02:00 bartsch-dev <notifications@github.com>:

**Comment by stefan-kolb** [comment]
Dialog looks good, just capitalize first letzter of latest Version. For the
preferences, i'd rather simplify this a little bit. As for the Naming i'd
suggest Updates. Does the user really need to select how often we check?
And all the other Options? We could just handle that in the background?!
Am 27.05.2016 10:40 vorm. schrieb "Christoph" <notifications@github.com>:

**Comment by stefan-kolb** [comment]
Download button should go to fosshub?! No intermediary Clicks needed then.
Am 27.05.2016 10:51 vorm. schrieb "Stefan Kolb" <stfnklb@gmail.com>:

**Comment by stefan-kolb** [comment]
Maybe just use a check for updates entry in the help menu that ignores all
Settings and Displays the Dialog after, instead of the preferences?
Am 27.05.2016 10:53 vorm. schrieb "Stefan Kolb" <stfnklb@gmail.com>:

**Comment by tobiasdiez** [comment]
Can we please add support for automatic downloading and installation via install4j for the dev builds? We should make it as easy as possible to use development versions so that bugs are detected as soon as possible (especially, since not all features are used by the developers). Manually downloading a new dev version every day is thus not acceptable.

**Comment by bartsch-dev** [comment]
This update system is for the end user as it grabs the lastest stable version.
It now directs directly to fosshub.

For myself I like the Update tab in the preferences but I can see that they don't matter much for the end user. What do the others think?

**Comment by matthiasgeiger** [comment]
I think the prefs are not really needed - at least not with that much options. Maybe a single setting "Check automatically for updates" (which is enabled by default) should be placed at the "Advanced" tab.

**Comment by koppor** [comment]
When using a development version, the dialog looks like this:

![updatedialog](https://cloud.githubusercontent.com/assets/1366654/16178437/00f97f98-3648-11e6-924a-4b4ea64ea5c1.png)

**Comment by matthiasgeiger** [comment]
Is this really necessary? 
We are not working with "Release Candidates" or "Beta Versions" - but the newest "development version" is simply a snapshot of current master - which changes (in phases where someone has time for development) daily or even more frequent - i.e., users of the dev versions will see this dialog every time they start JabRef.
I would prefer the following: If a dev version is installed the user only gets informed, if the matching stable version is released. If v3.5 dev is installed, it is checked whether v.3.5 (or later) is released. If so, a notification is shown.

**Comment by tobiasdiez** [comment]
I would prefer an automatic update of the dev version via install4j. We really need as much testers of the dev version as possible and thus it should be very very easy to stay up-to-date with the recent version (maybe add a mechanism that the popup is only displayed once a day or so). Also the funding argument does not apply in the case of the dev version.

**Comment by simonharrer** [comment]
install4j seems to be quite complicated to handle - @stefan-kolb can probably say something about this. I am not sure if investing time into this which is not completely necessary is worth the effort. Maybe we can achieve something quickly, but I am not sure.

**Comment by koppor** [comment]
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.
