### ISSUE TITLE
jabref can't parse bib file when the bibtexkey field contains symbol "="

### ISSUE THREAD

**Issue by Moriaty0o0** [JabRef/jabref#6615]
JabRef 5.1--2020-06-15--ed96faa
Windows 10 10.0 amd64 
Java 14.0.1

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

jabref can't parse bib file when the bibtexkey field contains symbol =.
the error information :
error occurred when parsing entry: 'error in line 1626: expected = but received , '. Skipped entry.

for some reason , i can't show the complete bib entry, but i‘m sure it is the bibtexkey  contains symbol "=" that make error occur.

the title of the entry contains equal sign "="  and i make bibtexkey  consists of title, so error occurs.

<details>
  <summary>Log File</summary>
  %d [%thread] %-5level %logger - %msg%nImporting in unknown format: game.bib
Error opening file 'game.bib': Could not find a suitable import format.
</details>

**Comment by Siedlerchr** [comment]
The equal sign is illegal in the key. Therefore JabRef is right that the entry is invalid.
