### ISSUE TITLE
Rename PDF to format doesn't respect title capitalization. 

### ISSUE THREAD

**Issue by musm** [JabRef/jabref#6617]
JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2  on 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Rename PDF doesn't respect the `title` capitalization. In previous version of JabRef this wasn't an issue.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Do you have an example of what happens, and what it should have been?

I am not sure if that is a recent change, but in the [online documentation](https://docs.jabref.org/setup/bibtexkeypatterns#title-related-key-patterns) `[title]` does not respect capitalization.

How does what you want differ from the output of `[fulltitle]`?

**Comment by calixtus** [comment]
Devcall: Is there any any update on this issue?
https://docs.jabref.org/setup/citationkeypatterns#title-related-field-markers
Please note the difference between `[title]` and `[camel]`.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
The last discussion I was part of on this topic can be found in https://github.com/JabRef/jabref/issues/4342#issuecomment-752178567.

My summary is that for now, this is the intended behavior of `[title]`, but it should be changed.
I think `[TITLE:latex_to_unicode]` might resolve this for @musm .

**Comment by calixtus** [comment]
Devcall: since there was no reaction by the issue author, we consider this issue solved. Thanks especially to @k3KAW8Pnf7mkmdSMPHz27 for posting the quick solution.
