### ISSUE TITLE
file save does not work when editing bib code in entry editor

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6622]
JabRef 5.1--2020-06-13--0432100
Linux 5.6.18-300.fc32.x86_64 amd64 
Java 14.0.1

1. edit an entry in the source field within the entry editor
2. press ctrl+s
3. close file
4. open file

Effect: the final change was not saved.
it gets saved when the user shifts to another field of the entry editor and then presses ctrl+2.

**Comment by DaniloMurer** [comment]
Has anyone picked this issue up? If not I'd like to give it a try.

**Comment by Siedlerchr** [comment]
@DaniloMurer  You can take a look at it. But be warned that the source code editor tab is a complex issue and modications can produce nasty side effects. The code is in gui/entryeditor/SourceTab,java.
I guess it's related to the focusedPropertyListener

**Comment by DaniloMurer** [comment]
Ok thanks for the advice and the warning. I'm going to try my best maybe I can find a solution to this.

**Comment by DaniloMurer** [comment]
I'm new to this whole Open-Source project, so I wanted to ask why I'm not able to create a new branch and how I can move the issue inside of the project.

Thanks in advance

**Comment by Siedlerchr** [comment]
Feel free to ask here or in the developer channel. You might want to read the contribution guide for our contribution process 
https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

**Comment by DaniloMurer** [comment]
Ok thank you very much. I got it how to make the branch so that's not a problem anymore.

Greetings

**Comment by Siedlerchr** [comment]
Is this still a problem?

**Comment by ilippert** [comment]
Will take some days until I can check. Thanks for asking!

On 31 August 2020 21:52:48 CEST, Christoph <notifications@github.com> wrote:
>Is this still a problem?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JabRef/jabref/issues/6622#issuecomment-684002357

-- 
Sent from my LineageOS device with K-9 Mail. Please excuse my brevity.

**Comment by DaniloMurer** [comment]
Hello, yes the issue does still persist and I'm not sure if I've got enough free time to fix this issue.

Regards

**Comment by ilippert** [comment]
JabRef 5.2--2020-09-01--35f5078
Linux 5.8.4-200.fc32.x86_64 amd64 
Java 14.0.2

problem persists.

**Comment by ilippert** [comment]
JabRef 5.2--2020-11-21--b0af521
Linux 5.9.8-200.fc33.x86_64 amd64 
Java 15.0.1

problem persists.

**Comment by Siedlerchr** [comment]
This issue should now be resolved in latest master.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by ilippert** [comment]
JabRef 5.2--2020-11-23--350ec1f
Linux 5.9.9-200.fc33.x86_64 amd64 
Java 15.0.1

Hi, in this version, when I edit the bib code directly, it takes some seconds until the `*` appears next the the library's name, indicating the unsaved change of the file.

**Comment by ilippert** [comment]
But saving now works- thanks!
