### ISSUE TITLE
Serach options (integrated in auto-complete): states not visible

### ISSUE THREAD

**Issue by jhh931** [JabRef/jabref#6623]
JabRef version 5.0  on Windows 10 

When using Autocompletion (by chacking the box under Preferences -> Entry editor,
the user can toggle 3 options: RegEx (on/off), case sensitivity (on/off)  and Float/Filter.
For the first two, the user cannot see what the current state is.

![Untitled](https://user-images.githubusercontent.com/20792626/85200962-e06d0d00-b2fb-11ea-8f56-6963fc57a361.jpg)

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our current release version!
