### ISSUE TITLE
Settings in Searching: suggest to separate these from autocompletion 

### ISSUE THREAD

**Issue by jhh931** [JabRef/jabref#6625]
JabRef 5.0 under Windows 10.

Usability of Jabref is reduced for me by the following issue related to searching (i.e. searching for  entries within the current library).

 The options for using RegEx or not and searching case-sensitive or not are only available via Auto-complete:
![Untitled](https://user-images.githubusercontent.com/20792626/85201098-03e48780-b2fd-11ea-83e3-03924edcdcf7.jpg)
. I don't see the logic behind that; having these available adjacent to the search bar, irrespective of using autocomplete or not, (as it used to be, see below) makes more sense to me. 

![search-bar](https://user-images.githubusercontent.com/20792626/85201115-25457380-b2fd-11ea-9886-6e1bed502e48.jpg)

**Comment by Siedlerchr** [comment]
Thanks to @calixtus  this should be fixed now in the latest master

**Comment by jhh931** [comment]
I am now testing the Portable version of:

- JabRef 5.1--2020-07-13--6344401
- Windows 10 10.0 amd64 
- Java 14.0.1

The GUI elements I would expect based on [Rework search bar #6682](https://github.com/JabRef/jabref/pull/6682) are not visible for me. 

![Capture](https://user-images.githubusercontent.com/20792626/87851013-0edb0980-c8f5-11ea-9d26-516b04eb861f.JPG)

Please let me know if I can do additional tests.

**Comment by Siedlerchr** [comment]
@jhh931  Please install the latest version (18.07)

**Comment by calixtus** [comment]
The buttons should be visible if you click on the search bar in the most recent development version.

Remember to always backup your data before using a development version.

**Comment by jhh931** [comment]
Check: in V 18.07, the buttons appear when clicking on the search bar.
So on this point we're OK.

(This version does have another issue w.r.t. files linked to my entries; should I report this?)

**Comment by Siedlerchr** [comment]
Please open a new issue for the problem with the linked files

**Comment by jhh931** [comment]
Done: 
https://github.com/JabRef/jabref/issues/6698
