### ISSUE TITLE
columns widths cannot be controlled - independent of subgroup

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6626]
JabRef 5.1--2020-06-17--ef0a6bb
Linux 5.6.18-300.fc32.x86_64 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

no idea

but have a look at this screencast
https://owncloud.itu.dk/index.php/s/i6Gww3znBx4t71A

**Comment by mlep** [comment]
Looks like a behavior similar to #6690

**Comment by ilippert** [comment]
JabRef 5.2--2020-10-19--af203b6
Linux 5.8.15-201.fc32.x86_64 amd64 
Java 15

The issue is still: I have no control over column width. 

See screencast at https://owncloud.itu.dk/index.php/s/aP2ztvdeUAaB1vP

**Comment by ilippert** [comment]
> Looks like a behavior similar to #6690
> @ilippert: maybe you could try to reproduce it?

yes, https://github.com/JabRef/jabref/issues/6626#issue-642365907 reproduces #6690, and I still can reproduce this today. 

But https://github.com/JabRef/jabref/issues/6626#issuecomment-712705920 indicates an issue that also is different from #6690 in that independently of group selection I cannot control group width.

**Comment by lpilz** [comment]
I can second that problem - experiencing exactly the same bug constantly. It is possible to recover by going into 'Preferences' and clicking 'Save'.

jabref 5.2-1
Arch Linux running 5.12.1-arch1-1 and XFCE4
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by lpilz** [comment]
Ah, just saw #6818. This bug should be fixed with #7507 - now we just have to wait for release ;)

**Comment by Siedlerchr** [comment]
@lpilz  You can try the latest dev version which includes this bug fix https://builds.jabref.org/main/

**Comment by lpilz** [comment]
Cheers :) Since I'm lazy and using the packaged AUR version, I think I'll just wait for it to make it to stable :+1:

**Comment by Siedlerchr** [comment]
For the record: We have now disabled the option  by default for new installations: "Fit table horizontically on screen" which often caused issues with jumping column sizes
