### ISSUE TITLE
Icon in start menu is dull

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6629]
The JabRef icon in start menu is dull compared to the other icons (see screenshot)
![image](https://user-images.githubusercontent.com/865866/85217338-22e02980-b390-11ea-8624-2a7af86c3d9c.png)
Could the logo be more saturated (the background is OK)?
Thanks!
mario

**Comment by koppor** [comment]
Pull Request welcome

**Comment by ddunig2** [comment]
Would simply making the logo more saturated be ok? Also should one consider not overshadowing the other icon when editing the jabref icon?

**Comment by ddunig2** [comment]
The images on the right are the original, the left are the edited versions, Which one would be more suitable from the three on the left?



![jabrefIcon](https://user-images.githubusercontent.com/36016544/88748413-f5b93080-d11e-11ea-8d4d-626aaeab1aaf.JPG)

**Comment by ddunig2** [comment]
I actually am not sure how to get the start menu. @koppor It would help if you can help me.

**Comment by Siedlerchr** [comment]
Hi, thanks for your interest.
The Logos need to be put in the buildRes folder and named according to this guide:
https://docs.oracle.com/en/java/javase/14/jpackage/override-jpackage-resources.html#GUID-405708DC-0243-49FC-84D9-B2A7F0A011A9

I think we need to try it out. For mac this wozld be also cool, the JabRef icon is hardly visible in the dock.

**Comment by koppor** [comment]
I think, the modified icon should also be placed to https://github.com/JabRef/jabref/tree/master/src/main/resources/icons.

I like the second one (on the left) most.

**Comment by ddunig2** [comment]
To begin, should the logo be an SVG file? Also, I'd like to try the logo on that start menu if possible, but I still do not know how to get that start menu up.

**Comment by Siedlerchr** [comment]
We use the java jpackage tool to build native installations for each operation system and in the link above I posted  it's explained how the files have to be named and as which format.  See "Launcher" in the document. That is probably the right way.

It should be sufficient to put them in the buildRes subfolder for each OS: https://github.com/JabRef/jabref/tree/master/buildres
They should then be picked up by the installer creation tool.
