### ISSUE TITLE
Mac OS X: Search for umlauts

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6636]
the search function got extremely slow, often stalls after each letter - search does not work anymore for Umlauts and other special symbols like searching for 'M{\"u}ller' [typing 'Müller' neither works as "ü" input via long-pressing "u" doesnt work; typing "Müller" elsewhere and then copying over into Jabref works - quite annoying

Dev version of last week: die beschriebenen Umlautprobleme bestehen weiter [wenn ich ein “ü” von woanders kopiere klappt es, aber das ist mühselig] Das Beste waere die Suche nach {\”u} oder \”u wuerde klappen

**Comment by Siedlerchr** [comment]
Windows 10: 
Entry author `M{\"{u}}ller, P.` 
Search works with Müller. 
Searching for `M{\"{u}}ller` does not work.

Probably some keyboard layout stuff

**Comment by Siedlerchr** [comment]
I can reproduce the same behaviour as under Windows. Typing unlauts etc is no problem on mac.
Searching for the latex encoded umlaut/stirng does not really make sense
