### ISSUE TITLE
New fetcher: "Collection of Computer Science Bibliographies"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6638]
> [The Collection of Computer Science Bibliographies](https://liinwww.ira.uka.de/bibliography/index.html)  is a collection of bibliographies of scientific literature in computer science from various sources, covering most aspects of computer science. The bibliographies are updated weekly from their original locations such that you'll always find the most recent versions here.
>
> The collection currently contains more than 7 millions of references (mostly to journal articles, conference papers and technical reports), clustered in about 1500 bibliographies, and consists of more than 2.3 GBytes (530MB gzipped) of BibTeX entries. More than 600 000 references contain crossreferences to citing or cited publications. 

Example query: 

http://liinwww.ira.uka.de/bibliography/rss?query=jabref&sort=score

Result: RSS

Example:

![grafik](https://user-images.githubusercontent.com/1366654/85585543-619c0b00-b640-11ea-8447-d20a0901a3ff.png)

**Comment by daniel-price** [comment]
@koppor Hello, I'd like to start working on this as my first issue.
I've already had a look at the contribution guide and set up the local project, and had a look at some of the other fetchers.

**Comment by koppor** [comment]
Thank you for choosing JabRef as project. - Just go ahead. You can create a draft pull request if you want to!
