### ISSUE TITLE
Enable one column libreoffice panels

### ISSUE THREAD

**Issue by liubenyuan** [JabRef/jabref#6639]
**Is your suggestion for improvement related to a problem? Please describe.**
I am using jabref with LibreOffice, the connect panel is 3x3 grid with small icons on top. It is very inconvenient when citing references because the 3x3 grid makes the main panel of jabref narrower.

**Describe the solution you'd like**
would it be possible that this LibreOffice plugin is 1 column, i.e., a side panel.

**Additional context**
![jabref](https://user-images.githubusercontent.com/171338/85707492-cffecd00-b715-11ea-9f57-858f8794eb98.png)

**Comment by tobiasdiez** [comment]
Instead of using a fixed grid, a more flexible layout in forn of a Flowpane should be used. In this way the buttons can still be aligned in rows if there is enough space but move to the next row if the width is decreased. http://www.java2s.com/Code/Java/JavaFX/FlowPanepreferredwidthallowsfortwocolumns.htm

**Comment by ddunig2** [comment]
I can make this change if that's alright.

**Comment by Siedlerchr** [comment]
@ddunig2  Sure, go ahead

**Comment by tobiasdiez** [comment]
Thanks to the quick initiative of @ddunig2 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by ddunig2** [comment]
Glad I can help! @tobiasdiez why check the build? Is there something else I need to do for this issue?

**Comment by tobiasdiez** [comment]
This was directed to @liubenyuan, so that he/she can verify that the fix indeed works as expected. No further action required from your side, except for looking for your next issue that you want to fix ;-).

**Comment by liubenyuan** [comment]
Sure, I will download the test version and try it.
