### ISSUE TITLE
Alt-F3 does not open keyword group view

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6646]
I'm running JabRef-5.1.dev (portable linux, 2020-06-24 21:56) and the Alt-F3 chord does not display the keyword groups. Using the menu View -> Groups works.

**Comment by alex-petrov-vt** [comment]
Are you referring to the group interface? If so, the hotkey for that is Alt+3 and not Alt+F3, but I may be misunderstanding your question

**Comment by rs-aesi** [comment]
On Tue, 30 Jun 2020, alex-petrov-vt wrote:

> Are you referring to the group interface? If so, the hotkey for that is
> Alt+3 and not Alt+F3, but I may be misunderstanding your question

I must have mis-typed on my post. Alt-3 does not open the group interface
(nor does Alt-F3). I just tested alt-3 and the group interface did not open.

Regards,

Rich

**Comment by alex-petrov-vt** [comment]
Hmm, weird. It seems to be working for me on Ubuntu 20.04 and JabReg 5.1

**Comment by rs-aesi** [comment]
On Tue, 30 Jun 2020, alex-petrov-vt wrote:

> Hmm, weird. It seems to be working for me on Ubuntu 20.04 and JabReg 5.1

I run Slackware-14.2/x86_64. Shrug.

Rich

**Comment by koppor** [comment]
I will try to install XFCE here and try to use the hotkey

**Comment by rs-aesi** [comment]
On Mon, 14 Sep 2020, Oliver Kopp wrote:

> I will try to install XFCE here and try to use the hotkey

Oliver,

The menu says it is Alt-3 rather than Alt-F3.

Regards,

Rich
