### ISSUE TITLE
Better warning when importing a bib file with unclosed brackets

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#665]
If the bib file contains unmatched opening brackets, then JabRef warns at the end of the file that something went wrong. However, there is no indication that maybe a closing bracket is missing and especially where in the file this is the case (the warning prints the last line of the file - not very helpful).

For more context see #650.

**Comment by lenhard** [comment]
I just tested this on current master and actually the warning has improved. A missing brace is now reported the next time the parser encounters an @ symbol (i.e. the next entry in the bib file).
