### ISSUE TITLE
Problems with export and export selected in XML format Jabref ver >=3

### ISSUE THREAD

**Issue by AMHurrell** [JabRef/jabref#666]
Dear Jabref team

I have tried version 3.0 and up and all provide an error "cannot save to file. Stream closed" when I attempt to export in xml format for inclusion in a MS Word Document.  However reverting to version 2.11.1 and all works fine.

I've just un-installed the versions >= 3 and reverted to the older one.  I hope this bug report is of use.  Apologies if its in the wrong format.  Not a coder but trying to provide helpful feedback

**Comment by koppor** [comment]
Refs #608

**Comment by oscargus** [comment]
Did you try 3.2? This *should* be fixed there. If not, can you please provide the exception message?

**Comment by AMHurrell** [comment]
Thanks for the quick response guys.  Tried version 3.2 and got the following message from the exception window (hope this is what is needed)

java.io.IOException: Stream closed
	at net.sf.jabref.exporter.MSBibExportFormat.performExport(MSBibExportFormat.java:70)
	at net.sf.jabref.exporter.ExportFormats$1ExportAction$1.run(ExportFormats.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)

**Comment by oscargus** [comment]
It should be fixed in #663. I will deal with some things tomorrow and hopefully it can be merged then (or at least provide you with a trial build).

**Comment by AMHurrell** [comment]
Amazingly quick response - thank you Oscar.  Do let me know if there is anything I can do to assist with testing.  Best wishes. Andrew

**Comment by oscargus** [comment]
@AMHurrell now it is merged in master. Sorry for not managing to get a test version out earlier. Some issues with GitHub which I didn't manage (to spend enough time on) to solve.

**Comment by AMHurrell** [comment]
Thanks Oscar - will download and let you have feedback

**Comment by lenhard** [comment]
@AMHurrell Any news on this? Is this issue fixed?

**Comment by AMHurrell** [comment]
Sorry Guys – not being a coder I am unfamiliar with how to get package to run, but didn’t want to both you with such a noobie question so was trying to sort it out for myself.

 

I have downloaded jabref-master zip, unzipped and run gradlew.bat.  However, am now stuck.  Please can someone point me to FAQ and I’ll learn as quick as I can and then get some feedback to you

 

Thanks

**Comment by oscargus** [comment]
You can try any of the pre-built versions at http://builds.jabref.org/master/

**Comment by AMHurrell** [comment]
@Oscar – thanks didn’t realise that

 

@Jabref team – have just tried the both export and export selected entries and both appear to work now.  Thanks for your prompt responses everyone

**Comment by LS77** [comment]
hello, 
I have the 3.2 version and have the same problem : I can't export xml format for inclusion in a MS Word Document. what should i do?

**Comment by oscargus** [comment]
This is (should be) solved in current master and will be included in 3.3.
Get it at builds.jabref.org/master (and please confirm if it did work for
you).

**Comment by LS77** [comment]
it works!!! thanks :)

**Comment by sandakith** [comment]
I encountered the same issue! Now downloaded the 3.3 dev snapshot jar and it seems to be working fine. When will you release 3.3?

**Comment by m4k2k** [comment]
had the same issues, 3.3 dev build helped. thank you.

**Comment by lenhard** [comment]
@sandakith We plan to release version 3.3 in about 2 weeks.

**Comment by princefisher** [comment]
Thank you for this. I upgraded to the dev build for now.
