### ISSUE TITLE
Import again: While one entry could be imported via Jabfox, another could not.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#6666]
JabRef 5.1--2020-07-01--a336842
Windows 10 10.0 amd64 
Java 14.0.1

- [ +] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

https://doi.org/10.1186/s12915-020-0760-3 could be imported, while 
https://doi.org/10.1210/endrev/bnaa009 could not. 
1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by LyzardKing** [comment]
Hi. I tried to import these references and they both work on the latest version of jabref + the extension.
Could you try again after opening the web console of your browser to see a log?

**Comment by bernhard-kleine** [comment]
As is evident from the partial screenshot, the first item is imported, the endorev entry is not. A log is not possible since jabref is immediately unresponsive. This screenshot with the empty right display is all the is possible.
If you tell me whether there is a way to grab the offending software, I would be willing to try. For me this is a serious blocking of my work.

![grafik](https://user-images.githubusercontent.com/9216487/86766899-77033300-c04b-11ea-89fc-d696ae533b0c.png)

**Comment by LyzardKing** [comment]
The log can be enabled from the browser where you have the extension running.
In firefox you can open from the menu Web Developer > Web Console
in chrome from the menu More Tools > Developer Tools > Console
Then you can press the jabfox button and check the output
