### ISSUE TITLE
Confused plain text citation to entry

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6672]
JabRef 5.1--2020-06-17--ef0a6bb
Windows 10 10.0 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Paste the following citation (from https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2414478) into "New entry from plain text":
```
Di Stefano, Giada and Gino, Francesca and Pisano, Gary and Staats, Bradley R., Making Experience Count: The Role of Reflection in Individual Learning (June 14, 2016). Harvard Business School NOM Unit Working Paper No. 14-093; Harvard Business School Technology & Operations Mgt. Unit Working Paper No. 14-093; HEC Paris Research Paper No. SPE-2016-1181. Available at SSRN: https://ssrn.com/abstract=2414478 or http://dx.doi.org/10.2139/ssrn.2414478 
```
the result is:
```
@TechReport{StefanoJune14.2016a,
  author = {Stefano, Di and Giada, Gino and Pisano, Francesca and Staats, Gary and null, Bradley},
  title  = {Harvard Business School NOM Unit Working Paper No. 14-093; Harvard Business School Technology & Operations Mgt},
  doi    = {10.2139/ssrn.2414478},
  year   = {June 14. 2016},
}
```
As you see the authors are messed up and the title has been confused with the publication.

Hope it can help as a test case.
mario

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/issues/4826 --> https://github.com/JabRef/jabref/pull/5614, because we switched from a shut-down service and afterwards self-made implementation to GROBID.

Maybe, we cannot do anything about it and have to get in contact with the [grobid](https://github.com/kermitt2/grobid/) developers.

I remember a comment many years ago stating: In case there is a DOI in a PDF, just download the data belonging to the DOI. This argument would apply here, too.

The resulting BibTeX code is:

```bibtex
@Article{Stefano2014,
  author    = {Giada Di Stefano and Francesca Gino and Gary P. Pisano and Bradley R. Staats},
  title     = {Learning by Thinking: How Reflection Aids Performance},
  journal   = {{SSRN} Electronic Journal},
  year      = {2014},
  doi       = {10.2139/ssrn.2414478},
  publisher = {Elsevier {BV}},
}
```

Would that be closer to your expectation? Then, we could easily add a patch.

**Comment by crystalfp** [comment]
Yes! Perfect. 
The disappeared manual entry method could have solved the problem of this strange formatted citation. In the current version I'm forced to create an empty entry and manually selecting, copying and pasting the various fields from the citation.
Anyway, JabRef is fantastic, only I don't understand this removal.
Thanks!
mario

**Comment by koppor** [comment]
@crystalfp Are you really talking about following dialog?

![grafik](https://user-images.githubusercontent.com/1366654/86782916-f3077600-c05f-11ea-8d5c-08e3464532c6.png)

You would be the first person I'm meeting who used that dialog! We had a long discussion about the dialog. My wish would be: 1. User pastes text, 2. JabRef identifies fields by using Grobid or other services 3. User can override suggestions using that dialog 4. User adds entry based on that entry.

That functionality could be offered by the plain-text "BibTeX Source" editor somehow (e.g., to quickly set a title without having to write `title = {` and `}`.

**Comment by Siedlerchr** [comment]
@crystalfp  as long as you have a DOI you can simply paste it on the maintable and it will be resolved automatically
