### ISSUE TITLE
Check SourceSpy

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6677]
As reported by our link checker, SourceSpy is down:

![grafik](https://user-images.githubusercontent.com/1366654/86829714-04b74080-c095-11ea-91af-aa81a54205f3.png)

We are ignoring the site at link checks from now on: https://github.com/JabRef/jabref/commit/865bf3c15629c07ae550e4a16e33c9853e609634 to get PRs working: https://github.com/JabRef/jabref/pull/6675#issuecomment-655035934

I did not find any public announcement, but will contact @SourceSpyTeam (I found their [GitHub profile](https://github.com/SourceSpyTeam)) to ask about their future.

![grafik](https://user-images.githubusercontent.com/1366654/86830741-58765980-c096-11ea-92f8-304f2e4d307a.png)

**Comment by tobiasdiez** [comment]
As the build fails again because some link is (temporarily) down, I think the link checker should work similar to the fetcher tests (i.e. don't run every time etc) and not as part of the checkstyle tests...

**Comment by koppor** [comment]
I wrote the SourceSpy guys. No reply yet. We still need to keep the check to be reminded that the site is down. Nevertheless files a PR moving the check to a monthly one. See https://github.com/JabRef/jabref/pull/6695.

**Comment by Siedlerchr** [comment]
It's working again, so I close this issue.
