### ISSUE TITLE
Can't find bundle for base name l10n/JabRef, locale en

### ISSUE THREAD

**Issue by wangmax0330** [JabRef/jabref#6678]
## reproduce
* git clone https://github.com/JabRef/jabref.git
![image](https://user-images.githubusercontent.com/7903596/86901322-09d0ca00-c13f-11ea-877d-5446ce1fced5.png)
* import to idea
* debug JabRefLauncher
![image](https://user-images.githubusercontent.com/7903596/86900783-5bc52000-c13e-11ea-94a6-a632d150a867.png)
## environment
 Windows 10 x64  1903
 jdk-14.0.1
 gradle 6.3

## log
![image](https://user-images.githubusercontent.com/7903596/86900178-98444c00-c13d-11ea-8f74-9f0cd6305168.png)
``` java 
17:05:51.988 [JavaFX Application Thread] ERROR org.jabref.JabRefMain - Unexpected exception
java.util.MissingResourceException: Can't find bundle for base name l10n/JabRef, locale en
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055) ~[?:?]
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689) ~[?:?]
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1582) ~[?:?]
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556) ~[?:?]
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:932) ~[?:?]
	at org.jabref.logic.l10n.Localization.createResourceBundles(Localization.java:111) ~[main/:?]
	at org.jabref.logic.l10n.Localization.setLanguage(Localization.java:83) ~[main/:?]
	at org.jabref.preferences.JabRefPreferences.<init>(JabRefPreferences.java:429) ~[main/:?]
	at org.jabref.preferences.JabRefPreferences.getInstance(JabRefPreferences.java:706) ~[main/:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:55) ~[main/:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846) ~[javafx-graphics-14-win.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455) ~[javafx-graphics-14-win.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx-graphics-14-win.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx-graphics-14-win.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx-graphics-14-win.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx-graphics-14-win.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx-graphics-14-win.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 25s
```

**Comment by Siedlerchr** [comment]
Hi, did you follow the setup guide? https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace#setup-for-intellij-idea

**Comment by wangmax0330** [comment]
> Hi, did you follow the setup guide? https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace#setup-for-intellij-idea

 i  follow the guide ,and this problem is resolved; but  after i run, i  see nothing,the app interface not appear
![image](https://user-images.githubusercontent.com/7903596/86904028-b3658a80-c142-11ea-9ce8-01e2ebff226a.png)

**Comment by koppor** [comment]
Select the project:

![grafik](https://user-images.githubusercontent.com/1366654/86906000-2b1bc100-c113-11ea-812d-cbd1115fbdd8.png)

Press <kbd>F4</kbd>

Go to SDKs. Double check that Java 14 is active

![grafik](https://user-images.githubusercontent.com/1366654/86906046-3e2e9100-c113-11ea-85a4-a6acb811571d.png)

Then go to "Projekt" and check that Java 14 is active there, too

![grafik](https://user-images.githubusercontent.com/1366654/86906079-4a1a5300-c113-11ea-9401-189f54af5031.png)

The above checks are the double check for

![grafik](https://user-images.githubusercontent.com/1366654/86906419-cdd43f80-c113-11ea-8ac5-67d063ae8444.png)

(Source: https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace)

**Comment by wangmax0330** [comment]
> Select the project:
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86906000-2b1bc100-c113-11ea-812d-cbd1115fbdd8.png)
> 
> Press F4
> 
> Go to SDKs. Double check that Java 14 is active
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86906046-3e2e9100-c113-11ea-85a4-a6acb811571d.png)
> 
> Then go to "Projekt" and check that Java 14 is active there, too
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86906079-4a1a5300-c113-11ea-9401-189f54af5031.png)
> 
> The above checks are the double check for
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86906419-cdd43f80-c113-11ea-8ac5-67d063ae8444.png)
> 
> (Source: https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace)

Thank you,i follow the steps;but after i run JabRefLauncher.java ,and still got the problem;i dont know what cased this

**Comment by Siedlerchr** [comment]
Did you run ./gradlew assemble?

**Comment by koppor** [comment]
The error message indicates that a wrong Java version is used:

![grafik](https://user-images.githubusercontent.com/1366654/86935107-c37a6b80-c13c-11ea-97f3-c84aa8d7dc9f.png)

See the source code of JabRef (found by <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>)

![grafik](https://user-images.githubusercontent.com/1366654/86935248-e9a00b80-c13c-11ea-8d7b-548e0032ec4d.png)

Check the JRE used for running:

![grafik](https://user-images.githubusercontent.com/1366654/86935359-06d4da00-c13d-11ea-8ef2-0d04db088568.png)

![grafik](https://user-images.githubusercontent.com/1366654/86935394-13593280-c13d-11ea-9da6-7255fe6dedb3.png)

**Comment by koppor** [comment]
In case this still doesn't work, please provide Screenshots of the JDK you have configured. Just to double-check. We recommend [Snipaste](https://www.snipaste.com/) as screenshot tool.

**Comment by Siedlerchr** [comment]
It's probably not the Java version which causes the problem but missing ressources.it's a misleading error message.

**Comment by koppor** [comment]
The mentioned message is only output if the Java check fails. I checked the provided screenshot again and hightlighted two things: 1. Java 1.8.0 Update 171, 2. the error message only being output at that part of the code.

![grafik](https://user-images.githubusercontent.com/1366654/86955847-87550400-c158-11ea-9c2d-011f45c2e6f4.png)

**Comment by wangmax0330** [comment]
> The error message indicates that a wrong Java version is used:
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86935107-c37a6b80-c13c-11ea-97f3-c84aa8d7dc9f.png)
> 
> See the source code of JabRef (found by Ctrl+Shift+F)
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86935248-e9a00b80-c13c-11ea-8d7b-548e0032ec4d.png)
> 
> Check the JRE used for running:
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86935359-06d4da00-c13d-11ea-8ef2-0d04db088568.png)
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86935394-13593280-c13d-11ea-9da6-7255fe6dedb3.png)

please look at this ,
## Project Structure
![image](https://user-images.githubusercontent.com/7903596/86985646-527e9680-c1c4-11ea-8963-26548e6abaa7.png)
![image](https://user-images.githubusercontent.com/7903596/86985656-59a5a480-c1c4-11ea-9de7-c7537da47415.png)
## run configuration
![image](https://user-images.githubusercontent.com/7903596/86985627-472b6b00-c1c4-11ea-8d78-6b3a48668a31.png)

**Comment by wangmax0330** [comment]
> The mentioned message is only output if the Java check fails. I checked the provided screenshot again and hightlighted two things: 1. Java 1.8.0 Update 171, 2. the error message only being output at that part of the code.
> 
> ![grafik](https://user-images.githubusercontent.com/1366654/86955847-87550400-c158-11ea-9c2d-011f45c2e6f4.png)

 i use jdk14.0.1
java9Fail is true,but versionFail is false;
![image](https://user-images.githubusercontent.com/7903596/86986006-2d3e5800-c1c5-11ea-9c7a-50f435a2b410.png)

**Comment by wangmax0330** [comment]
Everybody,i have resolve this problem;
i used LibericaJDK-14 rather than oracle jdk 14, and have everything done!
why the oracle cannot run still a question

![image](https://user-images.githubusercontent.com/7903596/86991817-92e51100-c1d2-11ea-9085-d172e3f744c6.png)
![image](https://user-images.githubusercontent.com/7903596/86991805-8f518a00-c1d2-11ea-8769-85e4d0799846.png)
![image](https://user-images.githubusercontent.com/7903596/86991792-882a7c00-c1d2-11ea-973b-f0b49af4c9a9.png)

**Comment by koppor** [comment]
Good to hear that it runs now.

I assume you run JabRef with the internal IntelliJ runner (and not with gradle) - as recommended in the "getting started guide".

[JavaFX is not part of the default JDK any more](https://www.reddit.com/r/java/comments/82qm9x/javafx_will_be_removed_from_the_java_jdk_in_jdk_11/). It needs to be installed separately if not using a special JDK. This is what you encounter.

Let my quote https://openjfx.io/openjfx-docs/

![image](https://user-images.githubusercontent.com/1366654/86996257-784b7180-c1ab-11ea-9005-5a58d447c769.png)

Note to self JavaFX installation with `zip` from Gluon is described there: https://taylorial.com/cs1021/Install.htm

As far as I remember our internal discussions, one has to download the "jmods" JavaFX file from https://gluonhq.com/products/javafx/ and put the `.jmod` files into `C:\Program Files\OpenJDK\jdk-14.0.1\jmods`.

Do you have time to check whether this works? Then, we can update our [guidelines](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) accordingly.
