### ISSUE TITLE
New search bar too wide for many displays

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#668]
This is not really a bug. 

I think, I have a rather usual screen with 1280x1024 pixel. Even though I like the new search bar, it is a pity, that it takes so much screen size. On my screen it gets wrapped into two lines. With regard to the few options that are actually accessible, this is too much in my opinion. 

it's like this for my usual workflow:
![image](https://cloud.githubusercontent.com/assets/8830305/12272782/5b60597e-b962-11e5-84cc-f623d0cad84a.png)

and gets even wrapped when the left bar is closed:
![image](https://cloud.githubusercontent.com/assets/8830305/12272928/3be33aca-b963-11e5-8f00-ac14319c1cd9.png)

Wouldn't it be possible
a) to use images for the different options and have the text as popover, like in the menu bar
or b) resize the search field in case of smaller window size
or c) abbreviate the text in case of smaller window size and give the full text as popover
or d) use shorter strings than now?
or e) somehow get rid of the space taken by the 'reset' button

**Comment by g10996694** [comment]
Indeed, the locked search-bar takes too many vertical display space, especially today we have very limited vertical resolution. 
This is the only reason that all researchers in our team haven't updated to the new 3.0+.

**Comment by koppor** [comment]
Refs #113

**Comment by lc9275** [comment]
My screen is also 1280x1024 and the search bar never gets wrapped - however this is the case in the English version of the interface. The long german translation of "case sensitive" seems to be the main cause for the two line wrap in the German interface.

**Comment by matthiasgeiger** [comment]
In #681 the string "Groß-/Kleinschreibung unterscheiden" has been shortened - http://builds.jabref.org/master/ contains the latest builds with this update (however this will not be sufficient in the first screenshot with the left sidebar open).

**Comment by simonharrer** [comment]
If we could find a good symbol for "Clear", one could reduce the overall size.

**Comment by lc9275** [comment]
How about: https://materialdesignicons.com/icon/backspace

**Comment by simonharrer** [comment]
Looks good. What do you think @matthiasgeiger?

**Comment by matthiasgeiger** [comment]
:+1:

**Comment by matthiasgeiger** [comment]
Problem: this icon is not available in the version we currently use for jabref - and the issue regarding changing codepoints in the ttf is not solved yet - so the integration has to wait (as I'm willing to change the codepoints of all our ~100 icons manually again :scream: )

**Comment by simonharrer** [comment]
hm, too bad :(

**Comment by koppor** [comment]
The proposed symbol for "clear" looks like the delete key on my Lenovo keyboard (which indicates the deletion of one character). Why not https://materialdesignicons.com/icon/close-box?

Other suggestions:

![grabbed_20160121-130809](https://cloud.githubusercontent.com/assets/1366654/12480084/0ac40cec-c040-11e5-85a7-67583046846a.png)

**Comment by teertinker** [comment]
If an icon is used, it would be great to place it into the search box (or at least make it look like that), so everybody knows whats its purpose. Otherwise one could think it closes the search bar.

Compare the Thunderbird filter: 
![image](https://cloud.githubusercontent.com/assets/8830305/12505107/496d90cc-c0e4-11e5-9017-4fc755a82081.png)

**Comment by simonharrer** [comment]
@teertinker we postpone complex UI changes like this as we are planning a major rework in the whole UI.

**Comment by simonharrer** [comment]
Does the current implementation solve your issue? You can try out a new JabRef version in about 30 minutes through builds.jabref.org

**Comment by teertinker** [comment]
It is much better now. Thank you.
![image](https://cloud.githubusercontent.com/assets/8830305/12574989/1914fa6e-c409-11e5-8d69-595fa1e53223.png)
When using the side bar (like LO plugin) in a proper width, it still gets wrapped. May be when major UI changes will be implemented a flexible width of the search bar adapting to the window size should be considered.

**Comment by tobiasdiez** [comment]
I think we should take this account after we migrated to JavaFX. I close this for now...
