### ISSUE TITLE
Cannot run JabRef from Source

### ISSUE THREAD

**Issue by DaniloMurer** [JabRef/jabref#6685]
Hello together,

I wanted to run JabRef from source following the documentation: https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.

Everything builds correctly with gradle except that if I'm trying to run it, I get an error.
The error looks like following:

![2020-07-13 19_59_58-JabRef – JabRefMain java  JabRef main  IntelliJ IDEA](https://user-images.githubusercontent.com/29736103/87337243-74b94100-c543-11ea-9ef7-22d690d614c7.png)

I've no clue why this happens, does anyone have similar issues?

Thanks in advance!

**Comment by Siedlerchr** [comment]
Hm, that looks like some intellij stuff. Does a ./gradlew run on the command line in the folder work? 
And we recently noticed that some people had problems with jdk versions that do not contain a javafx installation. In that case we recommend the liberica jdk:
https://bell-sw.com/pages/downloads/?version=java-14&package=jdk-full

**Comment by DaniloMurer** [comment]
Hello @Siedlerchr,

With the gradlew run command everything worked. Is there a fix so I can run it with Intellij?
Otherwise I think it doesn't matter.

Thank you very much.

Greetings from Switzerland

**Comment by Siedlerchr** [comment]
Another use recently had the same issue, maybe this screenshot help : https://github.com/JabRef/jabref/issues/6678#issuecomment-655425132
cc @koppor

**Comment by koppor** [comment]
What does `git status` output? Was the run command modified in some way?

**Comment by DaniloMurer** [comment]
@koppor I did run git status on the master branch, I didn't modify anything on the run configuration. It just won't work when I'm running it through Intellij. The `gradlew run` command does work though.

**Comment by koppor** [comment]
This is Oracle JDK, isn't it? Quick fix: Change the runner to Gradle in IntelliJ.

 Other fix: Install LibericaJDKFull (the "full" is important! - choco install libericajdk-full). This is what Christoph meant in https://github.com/JabRef/jabref/issues/6685#issuecomment-657753592.

**Comment by DaniloMurer** [comment]
@koppor I used the Oracle Open JDK 14 with JavaFx installed via Jmods. I'll try to change the runner to Gradle.

Greetings

**Comment by DaniloMurer** [comment]
So I found a fix to my little problem.

So if someone also has these problems follow the following steps:

First make sure that everything is set up according to the documentation: https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.

After that create a new Gradle run configuration in intellij:
![SNAG-0786](https://user-images.githubusercontent.com/29736103/87536179-f79fe000-c698-11ea-93cb-c78bc67a0365.png)

After that you should be able to run and debug the application from Intellij.

Regards from Switzerland

**Comment by koppor** [comment]
Thank you for the update.

I can see that you can handle IntellIj settings with ease. May I ask whether you cold spend some time to install LibericaJDKFull alongside the OpenJDK and configure IntelliJ to use it? That way, I would be enabled to claim that following the workspace setup guideline really includes setting up LibericaJDKFull.

The other reason I'm asking is that development speed significantly increases in case the built in Java Compiler of IntelliJ is used. Reason: At each test run, that tool chain is invoked. If Gradle is used, the startup time is increased by a few seconds. This adds up. See also cococomo turnaround time. I would like to avoid that 😅

**Comment by DaniloMurer** [comment]
@koppor Yes I can give it a try this evening and give some feedback how it worked out.

**Comment by tobiasdiez** [comment]
Also the Console should have a more detailed output of what actually went wrong (the screenshot above doesn't include any information about the error).

**Comment by Siedlerchr** [comment]
@DaniloMurer  any news on this?

**Comment by koppor** [comment]
Somehow refs https://github.com/JabRef/jabref/issues/6378

**Comment by DaniloMurer** [comment]
Hello together,

Sorry if im answering this late but I was on a longer vacation so I hadn't the time to look at this closer. Today Im trying with LibericaJDK to see if this works out better.

Regards

**Comment by DaniloMurer** [comment]
Hello together, I stumbled across a new problem, in this one the class "EasyBind" misses the method "listBind()". I don't know were this problem came from, I tested it on the master.

Regards

**Comment by DaniloMurer** [comment]
Here is the screenshot for further investigation.

![grafik](https://user-images.githubusercontent.com/29736103/89810365-3ceeea80-db3d-11ea-8455-f9e2df59d6af.png)

**Comment by Siedlerchr** [comment]
@DaniloMurer  Please try again. First mege the latest upstream/master and then rerun gradlew run to process the updated dependencies

**Comment by koppor** [comment]
Does the update at https://github.com/JabRef/jabref/pull/6794 help?

**Comment by koppor** [comment]
We think the issue is solved. If not, please comment.
