### ISSUE TITLE
Can JabRef automatic save (.bak,.sav) file in ~/.cache/jabref/ rather than the directory of the bib file

### ISSUE THREAD

**Issue by hebinhao1993** [JabRef/jabref#6688]
JabRef will genereate .bak and .sav file in the directory of the bib file. Can JabRef support generate these file in the diretory like ~/.cache/jabref/<the path of bib file>

**Comment by Siedlerchr** [comment]
Currently not, but we are trying to change that backup concept as it can lead to timing issues when autosave is enabled,
Refs #6453

**Comment by hebinhao1993** [comment]
Thank you for your reply.

**Comment by koppor** [comment]
On Windows, there could be `%APPDATA%` used.

**Comment by koppor** [comment]
@hebinhao1993 We know that this is an uncommon concept at users in the computer science field. However, we have many users in other fields. They do not know such directories. It is easier for them to have the backup file nearby.

Note that https://gitignore.io is fully aware of these extensions - they will be ignored at a git commit if you use their generated .gitignore file: https://www.toptal.com/developers/gitignore/api/jabref
