### ISSUE TITLE
JabRef 3.1/3.2 writes bib file in a format that it will not read

### ISSUE THREAD

**Issue by LonelyProf** [JabRef/jabref#669]
If the @PREAMBLE field is present, JabRef 3.1/3.2 omits the newline between that line and the preceding Encoding line when saving the file. The resulting file is not readable by JabRef. Sample attached. Problem seems to have been introduced at v3.1.

[test.txt](https://github.com/JabRef/jabref/files/89065/test.txt)

**Comment by lenhard** [comment]
related #621

**Comment by stefan-kolb** [comment]
@tobiasdiez Is this fixed?

**Comment by tobiasdiez** [comment]
@stefan-kolb It will be fixed with #718

**Comment by stefan-kolb** [comment]
Too late in the evening, should have seen that myself :smile: :+1:
