### ISSUE TITLE
Groups: "All entries" not highlighted on start-up

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6691]
JabRef 5.1--2020-07-13--6344401
Linux 4.9.0-12-amd64 amd64
Java 14.0.1

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

A minor UI inconsistency:
On start-up, JabRef displays all entries, but the group "All entries" is not highlighted.

**Comment by sumitsantape30** [comment]
Hey! I am beginner and I would like to work on this issue, can you suggest me the ways to get started?

**Comment by Siedlerchr** [comment]
@sumitsantape30  Hi welcome to JabRef!
For getting started please read through our [Contribution](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) Guide It explains also how to setup your workspace
Codewise the solution would be to add a call to select first here:
https://github.com/JabRef/jabref/blob/5540b93caf05b165ab12dee5ad8991e4065285b6/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L83

https://openjfx.io/javadoc/12/javafx.controls/javafx/scene/control/SelectionModel.html#selectFirst()

**Comment by mlep** [comment]
Trying the development version, I confirm that this issue is solved. Congratulation @Niffler, and many thanks!
