### ISSUE TITLE
Cannot build source code, com.tobiasdiez.easybind.EasyBind.listBind doesn't exist

### ISSUE THREAD

**Issue by Vince250598** [JabRef/jabref#6692]
- [yes] : I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. clone JabRef github repository
2. try to gradle build
3. build fails: jabref/src/main/java/org/jabref/gui/JabRefFrame.java:992: error: cannot find symbol
            EasyBind.listBind(taskProgressView.getTasks(), stateManager.getBackgroundTasks());

It looks like the dependency has changed and listBind doesn't exist anymore

**Comment by Siedlerchr** [comment]
Thanks for mentioning, I just saw this at our CI server as well 
Ping @tobiasdiez

**Comment by Vince250598** [comment]
should i make a pull request to update the function name to bindContent, i read it changed to this name in the EasyBind commit history

**Comment by Siedlerchr** [comment]
Yes, go ahead!

**Comment by tobiasdiez** [comment]
Thanks for reporting and fixing this @Vince250598!
