### ISSUE TITLE
Failing architecture tests

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6697]
Just as to remind that this is known, but not yet fixed.

We cannot fix it today, but hopefully a PR will come in soon.

```text
Test 10 -- is org.jabref.model independent of org.jabref.logic? FAILED

  org.opentest4j.AssertionFailedError: The following classes are not allowed to depend on org.jabref.logic ==> expected: <[]> but was: <[src/main/java/org/jabref/model/cleanup/NormalizeNewlinesFormatter.java]>
      at org.jabref@100.0.0/org.jabref.architecture.MainArchitectureTests.firstPackageIsIndependentOfSecondPackage(MainArchitectureTests.java:110)
```

**Comment by Siedlerchr** [comment]
It depends on OS.newline which is in logic. Need to move OS to model as well

**Comment by Siedlerchr** [comment]
Argh. It depends on l10n which is also in logic. Should I add an exception for this case?
I know the reason for our architecture, but due to one instanceof check I already had to move OS and NormalizeCleanupFormatter down to model.

**Comment by koppor** [comment]
Please try to keep model with inbound dependencies only. This allows for offering JabRef as a programming library.

**Comment by koppor** [comment]
I tried to dig down the root cause:

- 1a43290a5e306a4ceb2c58d2d01ec9bca4163516 move formatter down to model. Did this happen directly in the master branch? There is no PR linked from the commit.
- The call to `NormalizeNewlinesFormatter` was introduced in #6528 by @calixtus to fix https://github.com/JabRef/jabref/issues/5904.

## Notes

- `public abstract class Formatter {` was always in `org.jabref.model.cleanup`. I always felt is trange that the abstract interface is is model, but the implementation in logic. There is no ADR for this
- `FieldFormatterCleanup` seems to be in the model packge sind ages.

**Comment by Siedlerchr** [comment]
https://github.com/JabRef/jabref/pull/6717#issuecomment-664556955
