### ISSUE TITLE
Using master of forks is dangeours

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6699]
1. We update `master` in a GitHub actions "cron job".
2. The `master` of forks is also updated
3. The updates of the forks do NOT happen at the same time 
4. That leads to **different** commit ids at each `master` branch
5. That leads to strange pull requests, when conributors merge `master` instead of `upstream/master` (strange behavior e.g. at https://github.com/JabRef/jabref/pull/6641#issuecomment-652620709 and https://github.com/JabRef/jabref/pull/6687#pullrequestreview-448887911)

Solution possibilities:

1. Guard the GitHub action by checking whether we are on JabRef/jabref
2. Have the CSL update happening at another branch and merge the branch using a pull request to our GitHub repository
3. Ensure that all documantation says `upstream/master` - also in our manual pull request comments.

Think, we should go for option 1, since we cannot ensure that all references to `master` are prefixed by `upstream/master`.

**Comment by Siedlerchr** [comment]
Something like this should work:` if: github.repository == ‘JabRef/jabref’`
