### ISSUE TITLE
Searching for multi-word keywords fails

### ISSUE THREAD

**Issue by JackKelly** [JabRef/jabref#670]
First off: thanks so much to everyone who has worked on JabRef.  It's an awesome tool!

If I do a search like `keywords=building` then this works fine.  But I cannot seem to use multi-word search terms.  None of the following searches return any results, despite the fact that I definitely have a bunch of entries which have `building management` as one of their keywords:

* `keywords="building management"`
* `keywords='building management'`
* `keywords=building management`
* `keywords=(building management)`
* `keywords=\"building management\"`
* `keywords=\'building management\'`

If I enclose even single-word search terms in quotes then this also fails.  e.g. `keywords="building"` or `keywords='building'`.

The best I can do is search for `"building management"` (i.e. exclude `keywords=`) but, of course, this returns results where `building management` is in *any* field.

I'm using JabRef 3.2 on Ubuntu 15.10 x64 and OpenJRE 8.

**Comment by oscargus** [comment]
What about `keywords=building and keywords=management`? At least as a temporary workaround. Or the regexp `keywords = building\smanagement`?

**Comment by JackKelly** [comment]
ah, great, both of those solutions work, thank you so much :)

**Comment by stefan-kolb** [comment]
@simonharrer What do you think about this?

**Comment by JackKelly** [comment]
nice work, thank you :)

(I haven't run the new code yet - I'll probably wait until the next release).

**Comment by tobiasdiez** [comment]
What is now the correct way to search for the keyword "building management" versus search for entries having keywords "building" and "management" ?

**Comment by simonharrer** [comment]
`keywords="building management"` vs `keywords=building` and `keywords=management`
