### ISSUE TITLE
JabRef freezes on Windows 10 with autocompletion feature

### ISSUE THREAD

**Issue by amaxi99** [JabRef/jabref#6704]
JabRef 5.1--2020-07-20--df8b2e5
Windows 10 10.0 amd64 
Java 14.0.2

During entering text in any text box with autocompletion activated CPU load goes up to almost 100% and the system almost freezes (even for text boxes for which no autocompletion is used). JabRef has to be closed. After closing there is still a "JabRef" entry in the Task Manager using all CPU power which has to be killed.

With autocompletion deactivated the problem does not exist.
I have a large database (>12000 entries).

I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

**Comment by ThiloteE** [comment]
Stumpled upon this by chance. Can you still reproduce?

Apparently JabRef is trying to go through your whole database:

See documentation:

> 
> Word/name autocompletion
> The entry editor offers autocompletion of words. In the Options → Preferences → Entry editor, you can enable or disable autocompletion, and choose for which fields autocompletion is active.
> With autocompletion, JabRef records all words that appear in each of the chosen fields throughout your database. Whenever you write the beginning of one of these words, it will be suggested visually. To ignore the suggestion, simply write on. To accept the suggestion, either press Enter or use your arrow keys or other keys to remove the selection box around the suggested characters.
> Note: the words considered for suggestion are only the ones appearing in the same field in entries of the same database as the one you are editing. There are many ways to realise this kind of feature, and if you feel it should have been implemented differently, we'd like to hear your suggestions!

**Comment by ThiloteE** [comment]
Duplicate of #6967
