### ISSUE TITLE
Main table: linked files and identifiers: inconsistencies

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6705]
JabRef 5.1--2020-07-20--9cd9390
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

This is about 2 inconsistencies in the user interface concerning the _Linked identifiers_ column (in comparison with the _Linked files_  column):
- When several files are linked to an entry, a specific icon is used in the _Linked files_ column. But, in the _Linked identifiers_ column, the same icon is used whatever the number of identifiers.
-  When a single file is linked to an entry, a left click on the icon opens the file directly. But when a single indentifier is listed, a left click opens a little window, and a additional click is needed to open the link.

**Comment by hemantgs** [comment]
Hey @calixtus , I just opened a #6809 for this :smiley:  , can you please have a look

**Comment by mlep** [comment]
I can confirm this is fixed. @hemantgs: thank you!
