### ISSUE TITLE
Improvement of Duplicate Detection

### ISSUE THREAD

**Issue by mattys101** [JabRef/jabref#6707]
Please see the original write-up for this on the features request page: https://discourse.jabref.org/t/more-control-on-the-duplicate-finder/120/8

Adding the issue here based on the recommendation of Chirstoph's response to the above.

**Comment by KunAndrew** [comment]
Hi. Can I start working on this?

**Comment by Siedlerchr** [comment]
@KunAndrew  Sure, go ahead! To get started check out the [Contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md)
As I outlined in the forum answer already, the code for the Duplication algorithm is located in this class:
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/bibtex/DuplicateCheck.java

One first easy step would be the comparison of the Identifier Objects, by using the classes from the Identifier package and calling parse, like DOI or ArXIV or ISBN. It might be useful to add the parse method to the interface. 
https://github.com/JabRef/jabref/blob/ba68c09765d1cf7a7b90fec4c78924243210b1dc/src/main/java/org/jabref/model/entry/identifier/DOI.java#L133

A second good thing would also to reduce the weighting of the entry type and to exclude or reduce the weighting of some fields like note or comment.

**Comment by KunAndrew** [comment]
Should I do "option to mark the entries as not duplicates" within this pull request?

**Comment by Siedlerchr** [comment]
@mayrmt  Thanks to the groundwork by @KunAndrew  and the finishing of us, we could merge it
