### ISSUE TITLE
Jabref doesn't remember import location

### ISSUE THREAD

**Issue by noirchen** [JabRef/jabref#671]
The latest 3.x version has one annoying bug, or maybe I didn't explore all the preferences. Every time I __import an entry file into my current database__, Jabref starts from my main file directory where I store my huge bib database and pdfs, but the file I want to import is in "Downloads", and Jabref won't remember this location the next time I want to import a new entry. I looked into the options and find no way to change it. I remember that in 2.x version, Jabref could remember this location.

**Comment by koppor** [comment]
@JabRef/developers Has this something to do that we removed the Java file dialog and use the native file dialog only? Refs #459

**Comment by stefan-kolb** [comment]
@noirchen Should be fixed in current master. You can try the version @ builds.jabref.org.
