### ISSUE TITLE
Cannot sign up on discourse.jabref.org with Google

### ISSUE THREAD

**Issue by szhorvat** [JabRef/jabref#6727]
When I try to register on https://discourse.jabref.org/ using Google, I get this error message:

![image](https://user-images.githubusercontent.com/1212871/89103209-53e05f00-d410-11ea-85bb-85ca5ec6934f.png)

This happens both in Firefox and Chrome.

I hope this is an acceptable place to report this. I mentioned it here a few weeks ago and got no feedback: https://github.com/JabRef/www.jabref.org/issues/104

**Comment by Siedlerchr** [comment]
Sorry that your first report did go unnoticed. @koppor  Seems like you need to readd this auth stuff

**Comment by tobiasdiez** [comment]
I tried to follow https://meta.discourse.org/t/configuring-google-login-for-discourse/15858 but the JabRef account is not registered at https://console.developers.google.com/.

**Comment by koppor** [comment]
- @matthiasgeiger used to have an eye on it. Currently busy with other things
- We had an `oauth2` client configured somehow (I think, @matthiasgeiger's app)
- I created an application as described at the tutorial linked at https://github.com/JabRef/jabref/issues/6727#issuecomment-667655008 (and also in the discourse settings - https://discourse.jabref.org/admin/site_settings/category/all_results?filter=google)

I submitted a request just now

> The Trust and Safety team has received your form. They will reach out to you via your contact email if needed. The review process can take up to 4-6 weeks. Your last approved consent screen is still in use. 

Seems, we can check again in October.

**Comment by koppor** [comment]
@szhorvat I don't have many google accounts to test things. Could you please describe the steps, what you are doing. Is the following assumption right:

1. Open https://discourse.jabref.org/
2. Click on "Sign up"
3. Then, the error appears?

I just checked now and in my private Firefox window, Google asks me for my Google login data.

**Comment by szhorvat** [comment]
@koppor It appears fixed now. Do you still need feedback?

**Comment by koppor** [comment]
Glad to know that it works. Hope that Google approves our application.

If the issue comes back, feel free to reopen this one.

**Comment by szhorvat** [comment]
Thanks for the very quick help on a Sunday!

**Comment by koppor** [comment]
You're welcome! JabRef is a free-time project and most of my freetime is on the weekend 😅.
