### ISSUE TITLE
Asking for more than 100 entries downloaded for IEEE Search

### ISSUE THREAD

**Issue by williamzhiyong** [JabRef/jabref#673]
Dear Developer, could you enable 100 more entries (or even all sought results) downloaded for IEEE search, please?

Many thanks

William

**Comment by g10996694** [comment]
@oscargus perhaps an alert should be added in case of unlock-100-limit : IEEE Explore generally will put the related IP into blacklist for downloading too many references with API access.

**Comment by oscargus** [comment]
Are IEEE also doing that? I know that someone managed to ban an entire university from ACM a few years ago.

Since a month or so, JabRef is not using the HTML parsing though, but an actual API, so maybe it is not an issue anymore?

**Comment by oscargus** [comment]
To clarify: JabRef gets a json-file from IEEE using an IEEE-provided API for this, which is then parsed for article ID:s and the corresponding BibTex entries are downloaded one at a time. I'd guess that it is the second part that may create problems (if any). Not sure what information is available in the json. There's also another API available that returns XML...

**Comment by williamzhiyong** [comment]
Thanks Oscar, where I can find this json-file…? ☺

Cheers Will from sunny Auckland (ha…here is morning now)

**Comment by oscargus** [comment]
Use the source. :-)

https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/importer/fetcher/IEEEXploreFetcher.java

The URL is http://ieeexplore.ieee.org/rest/search?reload=true, but it must be accessed through a post request which is created in the method `makeSearchPostRequestPayload`on line 201. Maybe it is just to change rowsPerPage to an arbitrarily large number, but ideally I guess one shouldn't fetch all 1870489 hits for "system" in a single request. :-)

**Comment by g10996694** [comment]
@oscargus I'm not sure if IEEE still blocks today. I cannot give a try, because last year our university is banned by IEEE for this kind of reason. It took several weeks to get everything go back to normal, If I tried, I could be probably kicked out :)
Personally, I prefer always the 100 limits, in case someone would like download all records, he can just go to directly (or redirected) to IEEE Explore for online research and export all records. This will not cause any issues.

**Comment by koppor** [comment]
Think, we should not risk to get JabRef banned by IEEE.
