### ISSUE TITLE
Delete and Cut functionalities do not work anymore

### ISSUE THREAD

**Issue by AlexPars** [JabRef/jabref#6738]
JabRef development Release as of August 5, 2020, on Windows 10

Issue: Delete and Cut functionalities do not work anymore

I was not able to delete an entry. I have tried Delete from Edit menu, Delete icon, Cut from Edit Menu

**Comment by Siedlerchr** [comment]
Duplicate of #6293 This is a side effect of my recent mac fix. Will try to add a workaround.
Keyboard shortcuts do work fine
