### ISSUE TITLE
Add a proper way to set external application for pushing

### ISSUE THREAD

**Issue by ziggystar** [JabRef/jabref#674]
I searched for 10 minutes how to change the external application for pushing from emacs to vim, when I finally found the drop-down next to the tool bar button.

Please add a proper way of changing this setting through a menu action. I think it's not good style to have an action only available through the tool bar.

**Comment by oscargus** [comment]
What would you suggest to be a proper way?

**Comment by ziggystar** [comment]
One possible way would be adding a menu entry (with a sub menu) right beside `Tools -> Push Entries`.

And you're sure there is no other way to set this? Maybe I've just missed it.

**Comment by oscargus** [comment]
You can edit the preferences file. :-)

I think the idea is that since one (typcially) press the button to push, having the setting exactly there is quite convenient. On the other hand, since most users do not change it continuously one can ask if it is needed. I think an additional dropdown in the preferences tab may make sense. Maybe a submenu below the "Push entries...". Let's see who implements it. :-)

**Comment by lenhard** [comment]
related  #382

**Comment by ziggystar** [comment]
How should this function work, suppose one were to implement it using Actions?

## One action for pushing to each application

### Pro
- ability to configure hotkeys for each application

### Con 
- you'd have more than one button and menu entry (one for push to emacs, one for push to vim...), requires some tricks to reduce burden on user (see below)

I think the current implementation partially belongs here, since you have this button with a selectable target application. But as I noted, the menu-way of accessing these actions is broken, since you cannot change the target of the menu action. The canonical way to transfer this to the menu would be a sub menu to select the target application to push to, but this is cumbersome. 

## One push action, select target application in preferences

### Pro
 - obvious how to implement button, menu, hotkey
 - clear design

### Con
 - cumbersome if you are working with multiple applications (actually I used both Vim and Emacs some weeks ago and wanted to insert references in both, but I suppose this is a rarely used feature)

## Configurable push actions

Another approach would be to not have all available applications as possible targets, but to configure explicit targets. This could include Vim twice, but with different parameters.

This would enable using two different instances of Vim, and selectively pushing to each instance from Jabref, while never having to deal with other targets in the UI (only within the preferences.

Since this would reduce the number of targets (to one in most cases), one could have a dedicated button, configurable hotkey, or menu entry, for each target.

### Pro
- reduces number of targets (usually one, more for power users)
- targeting different instances of the same application

### Con
- requires most changes to code base
- unclear how default looks like; if no application is configured initially, the feature would become invisible in the UI

**Comment by mutetext** [comment]
With the existence of this menu/button combination, is this ticket solved?
![completed](https://user-images.githubusercontent.com/23666842/28641691-237a0584-721e-11e7-93ef-dd191ca7bb00.png)

**Comment by koppor** [comment]
Screenshot of the dropdown:

![grafik](https://user-images.githubusercontent.com/1366654/35246862-828ac3fa-ffc8-11e7-8d30-e447e54c3df2.png)

**Comment by slyr91** [comment]
Hello, is anyone working on this currently? If not I would like to take a stab at it.

**Comment by tobiasdiez** [comment]
@slyr91 Feel free to work on it! 👍
Please base your pull request on the `maintable-beta` branch and not master. We are currently switching to JavaFX for the UI and in the progress made some changes to the menu and toolbar. 

From the solutions @ziggystar proposes in https://github.com/JabRef/jabref/issues/674#issuecomment-175478728, I like "Configurable push actions" the most, but "One push action, select target application in preferences" is already a good start.

**Comment by slyr91** [comment]
Awesome! I will get started on this soon. Give it a good try this weekend. Should I open a pull request with the WIP title?

**Comment by tobiasdiez** [comment]
Thanks to @calixtus this is now implemented in the latest development version. You can select the push to application now in the preferences. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
