### ISSUE TITLE
Change the line spacing in table and groups

### ISSUE THREAD

**Issue by horror-vacui** [JabRef/jabref#6743]
Is there a way to change the line spacing between entries in the main table and in the groups tab? I am OK with manually editing a config file if its not in the GUI. (I have not found it.)

I have already so many groups that they does not fit into my screen and scrolling takes time. Also due tot he higher distance between them it is harder manually to find what I am looking for, since I can not keep too many group names in the focus of my eyes. (A related annoying small issue is that by dragging an entry into a group is possible only if the group name is on the screen. During dragging there is no scrolling)

In the main table it is also about the ability to quickly find what I am looking for. The built in search feature is only helpful if I know exactly what keyword I am looking for. By browsing the entries I could find publications which I would have not found with the search tool. I also find smaller line spacing aesthetically more pleasing.

---
JabRef 5.1--2020-06-09--595f085
Linux 4.15.0-112-generic amd64 
Java 14.0.1

**Comment by calixtus** [comment]
#6725 has been merged, so we can consider this fixed.
