### ISSUE TITLE
cannot delete selected entry

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#6745]
JabRef 5.1--2020-08-05--3d68514
Linux 5.7.11-200.fc32.x86_64 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Deleting entry not possible

1. mark an entry
2. press `delete` or use context menu and select `delete`

Result: the entry is not deleted

**Comment by Siedlerchr** [comment]
Duplicate of #6739 . I just merged a fix. It was a side effect of a mac osx fix.
