### ISSUE TITLE
Add a way to complete item's metadata from the internet

### ISSUE THREAD

**Issue by cossio** [JabRef/jabref#675]
There should be a way to complete an item's metadata from the internet, using the metadata that is already inserted into the item. For example, suppose I add an article to my database, and I insert the article's Title and Year. Then Jabref should be able to search the internet (maybe Google Scholar?) for the missing information, like Authors, Journal, Volume, Pages, etc. If we get more sophisticated, maybe it can detect a misspelling in the Title, and correct that two. I think this feature would save a lot of time.

**Comment by stefan-kolb** [comment]
@cossio We will be working on that in the future :smile:  This is part of a larger set of features which is why I'll be closing this for now.

**Comment by koppor** [comment]
This refs #152 as [Autocomplete](https://github.com/gumulka/JabRefAutocomplete) seems to implement that. @cossio Am I right?

**Comment by cossio** [comment]
@koppor I did not know about autocomplete. Thanks for pointing it out.

**Comment by cossio** [comment]
@koppor Yes. I see now that plugin support has been dropped. You're right.
