### ISSUE TITLE
Enhancement: also retrieve abstract when adding bib entry through DOI

### ISSUE THREAD

**Issue by AlexPars** [JabRef/jabref#6754]
It would be very useful if the bib entry in JabRef constructed from a DOI would also include the abstract that is available in that DOI.

Also, it would be good if the bib entry constructed from a DOI would use journaltitle rather than journal, to be consistent with biblatex format

Example: extract bib entry info from DOI:  10.1016/j.orl.2020.07.016 or https://doi.org/10.1016/j.orl.2020.07.016

**Comment by tobiasdiez** [comment]
The abstract is sadly not available through the crossref API, see e.g https://api.crossref.org/v1/works/10.1016/j.orl.2020.07.016.

@DominikVoigt is working on the conversion to biblatex, and this is tracked in https://github.com/JabRef/jabref/issues/895.

**Comment by Siedlerchr** [comment]
I guess it's more a legal issue: Abstracts are copyright protected

**Comment by AlexPars** [comment]
Thank you for clarifications and for the great piece of software that is JabRef.
