### ISSUE TITLE
Preferences are not stored

### ISSUE THREAD

**Issue by mwip** [JabRef/jabref#6770]
JabRef version 5.0 / 5.1--2020-08-19--9adfd5b on Ubuntu 20.04

Linux 5.4.0-42-generic amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Preferences that I make in the `Options -> Preferences` are not stored at all. Namely, I want to change the default Key pattern to `[auth:lower][year][veryshorttitle:lower]`. When I click save and open the Preferences again immediately, I see the default key pattern again. 

I installed both the stable release as well as the development version using `dpkg -i`. Might this have to do with the way I installed it and hence messed up permissions on any config files? I also don't get an event log.

1. Open Options, Preferences
2. Go to Citation Key Generator
3. Double click the Default pattern "Key Pattern"
4. Enter desired pattern
5. Click Save
6. Open Options, Preferences
7. Check Key Pattern -> it has not been saved.

**Comment by Siedlerchr** [comment]
Did you press enter after entering the new pattern? That is a common problem.

**Comment by mwip** [comment]
That indeed solves the problem -- thanks. 

That said, I think behaviour this is very counter intuitive. Even if it is as intended, one should be alterted that some settings will not be stored.

**Comment by Siedlerchr** [comment]
We are aware of this and fully agree with you. Unfortunately it's the default behavior of the underlying javafx gui framework which we cannot change. However, we have 
 @calixtus

**Comment by calixtus** [comment]
No I did not. In fact, it's a well known bug in JavaFX. There are possible workarounds, some work better, some not, they all come with sideeffects (e.g. https://gist.github.com/james-d/be5bbd6255a4640a5357). We do have this on our priority list, but this would take some more work.
see https://bugs.openjdk.java.net/browse/JDK-8089514
and here https://github.com/kleopatra/swingempire-fx/tree/master9/fx8-swingempire/src/tableedit/de/swingempire/fx/scene/control/edit

**Comment by calixtus** [comment]
refs #6432 #5825

**Comment by Siedlerchr** [comment]
I'll close that now. Added the idea from calixtus to the linked issue
