### ISSUE TITLE
Settings in "Enable field formatter" in "Cleanup entries" do not work

### ISSUE THREAD

**Issue by Zhengguo-Xu** [JabRef/jabref#6787]
JabRef version jabref_5.1-1_amd64.deb (build 2020-08-22)  on Linux (Ubuntu 20.04) 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Settings in "Enable field formatter" in "Cleanup entries" do not work at all. 

1. create new entrytype book with the following info.
    + title: test for title case
    + url: any url address
2. In "Enable field formatter" in "Cleanup entries", set the following:
    + title: Title case
    + url: Clear 
3. When click the cleanup entry button (or from Quality menu), title should be formatted as Title case (change to: Test for Title Case) and url field should be empty. However, nothing is changed: title is still in all lower case and url is still there.

My actual setting is much more complicated with much more fields and other settings but none of them works. 

I like the new version with filter group on top since I have several thousands of entries in my database and the list of group is very long. Hpefully it would be an easy fix otherwise I'll be forced to install the stable version since I use the "cleanup entry" tool very frequently.  

Is there anything you can do to help?  Thanks.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks for reporting. I could confirm this bug and I prepared a fix.
If you disable the checkbox "Enable field formatters" it should work. The logic is apparently the wrong way.
