### ISSUE TITLE
Application has become slow and unresponsive

### ISSUE THREAD

**Issue by parmeshgajjar** [JabRef/jabref#6793]
Hi, 

My version of jabref has become very slow and unresponsive. If I type something into the search box, it takes about 10 seconds before the text I typed appears. 

I have 1 bib file open which is less than 1Mb in size, but on task manager JabRef is using 800Mb of RAM. 

Any advice on whether this is a bug or how I can return the application to normal are much appreciated. Upto now it has been great. 

JabRef 5.0--2020-03-06--2e6f433
Windows 10 10.0 amd64 
Java 13.0.2
Windows 10 Laptop with Intel Core i7, 16Gb RAM and 512 SSD.

**Comment by AEgit** [comment]
There have been performance improvements in the recent development builds. The recent master build can be found here:
https://builds.jabref.org/master/

Note: Always make a backup of your JabRef database before using development versions (in case something goes wrong).

**Comment by koppor** [comment]
@parammittal16 Please also provide the base line for your comparison. I tried with JabRef 2.0 this week. I agree that this verison starts faster. However, it has not as much features as this vesion. And also doe snot support high-res displays (refs https://github.com/JabRef/jabref/issues/2409).

**Comment by parmeshgajjar** [comment]
The JabRef 5.0 on my laptop has only just started to become sluggish. For example, if I start to type something into the search box I can't see what I'm typing until 10-20 seconds later. JabRef 5.0 worked fine until about 2-3 weeks ago. Any suggestions on what I could adjust to get the performance back? I have tried 'repairing' the installation, and uninstalling and reinstalling. 

For a base-line comparison, the same database opens in JabRef 3.8.2 fine with no sluggish behaviour. JabRef 3.8.2 is using 280Mb of memory by comparison.

**Comment by AEgit** [comment]
Have you tried the current dev build as suggested above? JabRef 5.0 has been known to have an abysmal performance in certain use cases - the developer build contains various fixes that tried to address this problem.

Note: Always make a backup of your JabRef database before using development versions (in case something goes wrong).

**Comment by parmeshgajjar** [comment]
I can try the development build. 

Is there any reason why the performance should suddenly deteriorate?

**Comment by AEgit** [comment]
The following thread (and links therein) report some of the performance issues with version 5.0:
https://github.com/JabRef/jabref/issues/5071

Maybe your problem is linked to one of the issues reported there?

**Comment by parmeshgajjar** [comment]
5.1 does not work on my system #6801 - it simply does not load up. 

Any other ideas on rebooting the performance?

**Comment by koppor** [comment]
Seeing https://github.com/JabRef/jabref/issues/6801#issuecomment-682121002, I close this issue to keep the amount of (unncessarily) opened issues low.

We will do a release the next few hours (have to wait until we are unblocked by Apple).
