### ISSUE TITLE
Memorize external .jstyle files

### ISSUE THREAD

**Issue by RolfTMeles** [JabRef/jabref#6806]
The two standard citation styles don't fit my needs. So I created my custom jstyle file. But I have to add and select it anew anytime I start jabref.

It would be nice if jabref would save the filepath and lastly chosen style file, it would save some clicks.

I am running:
JabRef 5.0--2020-03-06--2e6f433
Linux 5.4.0-42-generic amd64 
Java 13.0.2

I tried saving the .jstyle file on an external SD card as well as in my home directory, it did not change anything. So I think it's not a bug but just a missing feature.

Here are some images:
![jabref_Select_Style](https://user-images.githubusercontent.com/66771694/91595674-38f80080-e964-11ea-8aad-46ffff19882a.png)
I click on select style file.
![jabref_Add_Style_File](https://user-images.githubusercontent.com/66771694/91595671-37c6d380-e964-11ea-850f-1a014842a8de.png)
Only the default styles are shown, so I add my custom style file.
![jabref_select_Style_File](https://user-images.githubusercontent.com/66771694/91595679-38f80080-e964-11ea-984e-9e0bb7a72c28.png)
It is selected and I can work with it as long as jabref is running.
As soon as I close jabref, it seems to reset it and story begins anew.

**Comment by Siedlerchr** [comment]
Hi, this should the fixed in the 5.1 version which will be released today/soon

**Comment by RolfTMeles** [comment]
Under
JabRef 5.1--2020-08-28--5540b93
Linux 5.4.0-42-generic amd64 
Java 14.0.2
Everything works just as I dreamt of! Thank you so much!
