### ISSUE TITLE
When enlarging JabRef window, columns shrink in width

### ISSUE THREAD

**Issue by serialc** [JabRef/jabref#6818]
JabRef 5.1--2020-08-30--e023aa0
Linux 5.4.0-42-generic amd64 
Java 14.0.2

1. Resizing JabRef window works fine on opening, scaling column width with window size.
2. Have more than 2 files/tabs open.
3. Change the width of a column (e.g., Year).
4. **Enlarge** the JabRef window width.
5. JabRef responsively **shrinks** all the columns, except the rightmost (as if you were reducing window width).

**Comment by mlep** [comment]
Similar to #6690

**Comment by serialc** [comment]
Thanks @mlep. I had three files open, now with two files it no longer happens.
I've added that to the OP. I think you're right that it's likely the same issue as #6690.

**Comment by ilippert** [comment]
See also https://github.com/JabRef/jabref/issues/5872

**Comment by wujastyk** [comment]
JabRef 5.3--2021-01-24--ae43548
Linux 5.4.0-62-generic amd64 
Java 15.0.2 
JavaFX 15.0.1+1

Columns have a life of their own!



https://user-images.githubusercontent.com/762246/105756372-bfac0c00-5f09-11eb-84dc-02ca1618f69a.mp4

**Comment by ilippert** [comment]
> JabRef 5.3--2021-01-24--ae43548
> Linux 5.4.0-62-generic amd64
> Java 15.0.2
> JavaFX 15.0.1+1
> 
> Columns have a life of their own!
> cinnamon-20210125-1.mp4
see https://github.com/JabRef/jabref/issues/6626#issuecomment-712705920 ;)

**Comment by wujastyk** [comment]
Thanks!  I'm so grateful to all the JabRef developers.
