### ISSUE TITLE
Content selector does not seem to work for custom fields

### ISSUE THREAD

**Issue by Holzhauer** [JabRef/jabref#6819]
JabRef version JabRef 5.1--2020-08-30--e023aa0 Linux 4.15.0-112-generic amd64  Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The content sectors just do not show up when entering text in the input fields that are connected with content selectors.

**Comment by Siedlerchr** [comment]
Have you enabled autocomplete?

**Comment by Holzhauer** [comment]
Yes, autocomplete is enabled, but it does not seem to have any effect on content selectors. I noticed that content selection works for native fields (e.g. Keywords), but not for custom ones. For customs ones, the "Manage content selectors"-dialog shows "UnknownFiled{name='topic'}, e.g. When I try to add a new content selector with the proper name ("topic") it says "Field name "Topic" already exists. The according information in the .bib file seems ok.
![JabRefContentSelector](https://user-images.githubusercontent.com/1692563/91749328-9d63cb80-ebc1-11ea-8879-a53d5caf2e01.png)

**Comment by anna-adamczyk** [comment]
I have the same issue. Are there any plans to resolve this in the future?

**Comment by Siedlerchr** [comment]
Thanks to @yinpeiqi  this issue is now fixed in the latest master.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by Holzhauer** [comment]
Unfortunately, it does not work reliably in the latest built (JabRef 5.3--2021-05-04--bbd04cc, Linux 5.8.0-50-generic amd64, Java 15.0.2, JavaFX 16+8). It works for one out of six custom fields, and I could not find a reason why it works for the single one. A difference I spot is that for the working custom field, the cursor appears vertically centered in the input field, whereas it is placed on top in the other input fields.
Besides, for the working custom field, suggestions only appear as the user starts typing. This is not what I expect from a selector when I want to choose from a predefined list of entries. Rather, all the suggestions should be able to be selected as soon as the user places the cursor in the input field.

**Comment by Siedlerchr** [comment]
Closing this in favor of a new issue which focuses on the seleciton in the entry editor

**Comment by Siedlerchr** [comment]
New issue https://github.com/JabRef/jabref/issues/11109
