### ISSUE TITLE
I cannot include books by placing the ISBN.

### ISSUE THREAD

**Issue by profiack** [JabRef/jabref#6821]
Hello, I use Jabref for some time. I updated today to version 5.1 (Windows 10). I cannot include books by placing the ISBN.

**Comment by Siedlerchr** [comment]
@profiack  Can you plasee give an example? Do you get an error message?

**Comment by crystalfp** [comment]
It works for me adding a new entry and, on the new entry dialog, select ISBN and enter, for example: 978-8820007256

**Comment by profiack** [comment]
I apologize for the delay in the response, as I was in poor health.

I reinstalled Jabref and there were no more errors.

 If there is any further observation, I inform you. Thank you very much.

Em seg., 31 de ago. de 2020 às 11:58, Christoph <notifications@github.com>
escreveu:
