### ISSUE TITLE
Wiki: translation from Crowdin: redirection needed

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6827]
In the wiki table of content (https://github.com/JabRef/jabref/wiki), clicking on `Development --> Integrating new translations from Crowdin` should redirect to https://docs.jabref.org/faqcontributing/how-to-translate-the-ui instead of displaying its own (old) instructions (https://github.com/JabRef/jabref/wiki/Integrating-new-translations-from-Crowdin).

**Comment by Siedlerchr** [comment]
Thanks, it works!
