### ISSUE TITLE
Medline import not functional!

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#6832]
JabRef 5.2--2020-09-01--35f5078
Windows 10 10.0 amd64 
Java 14.0.2

- [+] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. I tried to add PMID 8040303 from within jabref.
2. the Medline/pubmed windows is opened and I get stuck with this window: 
![grafik](https://user-images.githubusercontent.com/9216487/91888812-2f84d600-ec8d-11ea-8592-61665b6f0c9a.png)

3.  ... jabref is blocked completely. Only shutting down by the windows manager works. Maybe you tell me how long to wait, but waiting above 2 min is much to long with a working connection to ncbi.
4. the situation has been seen now for some month with different versions of Jabref-dev. Maybe you could start to do something about it.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
May have been a temporary issue. Works fine for me. 
Please  be aware that the current development version is currently under heavy development.

**Comment by bernhard-kleine** [comment]
I had tried with the previous version and the new snapshot. I didnot work. Upon retrying I was successfull. Today I tried  32517655 first via Jabfox, which did not work, then via Medline import. I got stuck again. At least for me the import via Medline and Jabfox are seriously compromised and not really functional. Which I do not like at all.

**Comment by Siedlerchr** [comment]
@bernhard-kleine  Ah okay. The way with the new entry dialog worked for me direclty:
<img width="514" alt="Bildschirmfoto 2020-09-03 um 10 55 43" src="https://user-images.githubusercontent.com/320228/92093899-25212400-edd4-11ea-92a1-c45ed5f40aba.png">

**Comment by bernhard-kleine** [comment]
That worked?! What is difference to the call to Websearch Medline? May be with that solved and the Import Dialogue functional, JabFox import will become working again. That would be very time saving.

**Comment by DominikVoigt** [comment]
> That worked?! What is difference to the call to Websearch Medline? May be with that solved and the Import Dialogue functional, JabFox import will become working again. That would be very time saving.

Hey there, the Pubmed/Medline API that is called using the ID-based import dialog is different from the API that is called in the web search. Currently, the web search is not "smart" enough to differentiate text field search/ ID-based search.  
For a workaround please use the ID-based import dialog and select the correct ID-type:
![image](https://user-images.githubusercontent.com/43381984/92110627-4e00e380-edeb-11ea-9f48-aa2439ca53bc.png)
![image](https://user-images.githubusercontent.com/43381984/92110989-e7c89080-edeb-11ea-8f02-3ed1c4d5a844.png)

**Comment by bernhard-kleine** [comment]
I will start to use this. However, the JabFox firefox plugin still uses the Websearch import window. At that does not work.
