### ISSUE TITLE
ISBN to BibTeX Fetch updates

### ISSUE THREAD

**Issue by ajbelle** [JabRef/jabref#684]
Issues  that seem left over from http://sourceforge.net/p/jabref/bugs/1241/

I tried 0-444-41881-4 and  0444418814 which return  an “Invalid ISBN” message. It is a valid ISBN and all other ISBN sites find the book. The message is misleading and should be “ISBN metadata unavailable”. Perhaps unlike http://manas.tungare.name/software/isbn-to-bibtex/  http://www.ebook.de/ does not accept  the old 10 digit ISBN. I tried 9780444418814 (the 13 digit converted ISBN) and ebook.de returned the same message. SOMETHING SHOULD BE ADDED TO THE HELP FILE TO EXPLAIN THIS MISLEADING “Invalid ISBN” MESSAGE. 

Trying to figure out why I read http://jabref.sourceforge.net/faq.php "Q: I have an ISBN. Is it possible to create an entry directly out of the ISBN?" and http://jabref.sourceforge.net/help/ISBNtoBibTeXHelp.php which are still to reflect what has changed, unlike the JabRef Help src/main/resources/help/en/ISBNtoBibTeXHelp.html (It is good that the embedded help is current). PLEASE UPDATE THE ONLINE CONTENT.

**Comment by koppor** [comment]
Thank you for your report. This is OUTSTANDING.

If you read the [CHANGELOG of 2.11 beta 4](https://github.com/JabRef/jabref/blob/dev_2.11/CHANGELOG), you would have read ""ISBN to BibTeX" fetcher now uses eBook.de's API (fixes bug [#1241](https://sourceforge.net/p/jabref/bugs/1241/))". Then,you would have read some background information. Sure, you cannot have read the private conversation between me and @manastungare. We came up with the solution that http://www.ebook.de (via @freiheit-com) implemented a completely new API for us. It has the drawback, as you noted, that only books available via ebook.de can be converted to bibtex.

Maybe you have noticed that we are under heavy load with other things. Maybe it is unnoticed, but we are NOT paid for JabRef at all.

It would be very helpful if you would try to [fork JabRef](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) and change the error message to "no information about this ISBN is available from ebook.de". The source of the homepage is available at https://github.com/JabRef/htdocs. We really need help migrating that to www.jabref.org. See #133 and #111.

If your valuable time allows it, please support us! This would really bring JabRef a huge step forward. :running:

**Comment by Siedlerchr** [comment]
Fortunately I have some time now. I will have a look at this and change the error message.

**Comment by manastungare** [comment]
Would you be interested in bringing back my ISBN parser as an officially-supported one? I’m in the process of moving my code to a server that can handle a bit more load than the previous one.

My previous concerns were around three aspects:
1. Hard-coded URL in client app without my knowledge,
2. bypassing ads shown on the web site, and 
3. Amazon’s API limits.

(1) won't be a problem anymore if I am kept aware of this usage. I can provide an endpoint for JabRef in addition to eBook.de that won’t change, and won't try to enforce the same-origin-policy.
(2) I don't mind offering this service for free (no ads) to JabRef users.
(3) Amazon’s API limits, unfortunately I cannot control, so as long as JabRef users stay below the Amazon API limits, this endpoint would continue to work. Once the limit is reached, users will have to wait until the restrictions are removed by Amazon (and I will provide an informative error message when that happens).

**Comment by koppor** [comment]
@manastungare Yes, we are very interested. Thank you for the offer! My current idea is to use your endpoint as fallback for ebook.de, if that's OK with you. Possibly, we could add a configuration option, but I currently don't see an advantage. Thereby, I assume that a data set provided by the ebook.de API is as complete as if it was requested via the Amazon API.

**Comment by ajbelle** [comment]
@koppor sorry if my capitalisation was taken as shouting at you as I realise you have correctly and effectively fixed a problem that arose:-( I did all you say, but I am not a programmer and was simply highlighting the changes I had identified would help others, not as criticism. You assessment is spot on, except it is well beyond my abilities to fork anything, and I take it @Siedlerchr has kindly taken it on.
 I really appreciate JabRef and fully realise you noble unpaid efforts, and will take up you offer to help as soon as I can do more, than find minor help file updates :-). If there is anything I could _effectively_ help with let me know.
I am pleased @manastungare is back on board because http://manas.tungare.name/software/isbn-to-bibtex/ is a good alternative that did access the ISBN I provided as an example. "A help message saying "If http://www.ebook.de returns an “Invalid ISBN” message try tungare.name" would let users know it is NOT AN ISBN ERROR like I did. That was my main problem, and I realise it is not JabRef that sent it.

**Comment by koppor** [comment]
@manastungare May I ask whether the move was successful and whether we may use an JabRef API endpoint? 😇

**Comment by manastungare** [comment]
Here you go! POST to this URL, and you’ll get raw BibTeX back, ready to insert into a `.bib`.

```
curl 'https://bibtex.chimbori.com/isbn-bibtex' --data 'isbn=978-3639174304' --compressed
```

**Comment by Siedlerchr** [comment]
@manastungare  Thanks for the implementation. Would it be possible to remove the URL field? Atm you return the amazon url. I doubt that this is useful for many people, especially when you cite the entry and the long url gets written.

**Comment by manastungare** [comment]
Here’s the note on the main page: https://bibtex.chimbori.com/

> One of the Terms of Use of Amazon's Web Service API (from where you are getting this information) is that any usage of the information should include a way to direct traffic to Amazon. To comply with Amazon's Terms of Use, the direct URL to the book is included. This will result in a commission to my account if you buy the book via the link.

Since JabRef already accesses this API with no ads and no attribution, I would prefer to leave the URL in, for referral traffic.

**Comment by Siedlerchr** [comment]
Okay, thanks for the information!  I just realized that this issue was closed, but no one implemented the access to your website.

Just some question, the "ibsn=xxx" is a key-value post parameter?

**Comment by matthiasgeiger** [comment]
We should discuss whether this amazon links is acceptable for us - or better: for our users.

**Comment by Siedlerchr** [comment]
We could also ask the guys from  ottobib,  #2238 
They just use the worldcat api I think

**Comment by koppor** [comment]
The link was there in old versions of JabRef and no user complained. The link is also present for the current ISBN fetcher. I would implement the GET request as fallback if ebook.de does not return anything. This should be doable for JabRef 3.8.

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by omendezmorales** [comment]
> Here’s the note on the main page: https://bibtex.chimbori.com/
> 
> > One of the Terms of Use of Amazon's Web Service API (from where you are getting this information) is that any usage of the information should include a way to direct traffic to Amazon. To comply with Amazon's Terms of Use, the direct URL to the book is included. This will result in a commission to my account if you buy the book via the link.
> 
> Since JabRef already accesses this API with no ads and no attribution, I would prefer to leave the URL in, for referral traffic.

Hello,
As of 08/2024, the chimbori site seems unresponsive
![image](https://github.com/user-attachments/assets/1fec7371-9346-4ee9-9927-ed50823399eb)

Furthermore, if I try to do a POST request via curl as indicated above, nothing comes back. Is there a workaround for this? Could https://isbnsearch.org or bibgur.ucom be used for this? It would be a great time-saver.
Thanks.

**Comment by koppor** [comment]
> Hello,
> As of 08/2024, the chimbori site seems unresponsive
> ![image](https://github.com/user-attachments/assets/1fec7371-9346-4ee9-9927-ed50823399eb)
> 
> Furthermore, if I try to do a POST request via curl as indicated above, nothing comes back. Is there a workaround for this? Could https://isbnsearch.org or bibgur.ucom be used for this? It would be a great time-saver.
> Thanks.
> 

I don't understand the comment. We have an ISBN fetcher. Based on GVK and some other provider. Doesn't it work for you? 😅

We don't use chimbori any more.

Source: https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/importer/fetcher/isbntobibtex/IsbnFetcher.java

**Comment by omendezmorales** [comment]
> > Hello,
> > As of 08/2024, the chimbori site seems unresponsive
> > ![image](https://private-user-images.githubusercontent.com/6626759/359471773-1fec7371-9346-4ee9-9927-ed50823399eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzI0OTMsIm5iZiI6MTcyNDE3MjE5MywicGF0aCI6Ii82NjI2NzU5LzM1OTQ3MTc3My0xZmVjNzM3MS05MzQ2LTRlZTktOTkyNy1lZDUwODIzMzk5ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMTY0MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ2OTk4NmJhYjlhNmViNjZjMmM3MGRmZDJjYjcyNTEzMzc3NDA2NWJkOTEwMjFjNDBjYjk2MzVhMjI0NjEyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UruLsagz8pB4D-Kbnuk73fkoPsjgZVWEvj6ZebXVv0U)
> > Furthermore, if I try to do a POST request via curl as indicated above, nothing comes back. Is there a workaround for this? Could https://isbnsearch.org or bibgur.ucom be used for this? It would be a great time-saver.
> > Thanks.
> 
> I don't understand the comment. We have an ISBN fetcher. Based on GVK and some other provider. Doesn't it work for you? 😅
> 
> We don't use chimbori any more.
> 
> Source: https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/importer/fetcher/isbntobibtex/IsbnFetcher.java

HI @koppor ,
ISBN fetcher functionality is not working for me, and I get the dialog shown above. Below the details of the JabRef version I'm using (which I assume is fairly recent).

 JabRef 3.8.2
linux 6.8.0-40-generic amd64 
Java 11.0.24

**Comment by koppor** [comment]
We need help in debian packaging!

On Debian, the version is very outdated. Please check https://docs.jabref.org/installation for resources how to install a newer version.

**Comment by chimbori** [comment]
Is this an actual widespread problem that warrants a fix? So far, we have only seen this one bug report reopened 8 years after the fact. I’m not sure this justifies the effort to set up a server that has not been alive for a while.

Also, JabRef was one of many users of the now-defunct service; showing a JabRef-specific message for all such users does not seem right.

I think a better long-term solution (though not useful for older binaries, as in this case) is to add an update check mechanism to JabRef itself, warning users who are not running the latest version, on any platform. WDYT?

**Comment by koppor** [comment]
We do have an update check. It might have been patched out for Debian though.
