### ISSUE TITLE
Offer migration from special fields in keywords to special fields as fields

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#6840]
Refs https://github.com/JabRef/jabref/issues/6621

**Comment by calixtus** [comment]
Agenda:
[x] Set default sync to keywords to disabled #6846 
[ ] Understand problems with synchronisation 
[ ] Create cleanup for non-syncd keywords

**Comment by koppor** [comment]
@DominikVoigt I have some detailed information in this. Should be a "Fingerübung", because of your experience at https://github.com/JabRef/jabref/pull/7334
