### ISSUE TITLE
Shortcut to paste BibTeX source no longer works in version 5.1 (macOS)

### ISSUE THREAD

**Issue by szhorvat** [JabRef/jabref#6843]
JabRef 5.1--2020-08-30--e023aa0
Mac OS X 10.14.6 x86_64 
Java 15

1. Go to the BibTeX tab source of an entry
2. Delete all text and ensure that the input cursor is in the box where the BibTeX source goes
3. Copy some text to the clipboard and press Command-V

Expected: The text should be pasted.

Actual: Nothing happens.

Note: Right click, Paste does work.

This problem is new in version 5.1, and did not happen in 5.0.

**Comment by Siedlerchr** [comment]
@szhorvat  you can directly paste the code on the maintable.
And this issue should also be fixed in the current development version

**Comment by szhorvat** [comment]
Is there a plan for a 5.1.1 release? 5.1 seems to have broken a few things that I use, and is overall a step down from 5.0 for my specific use cases ... (I'm sure it fixed many things that affected others...)

**Comment by Siedlerchr** [comment]
@szhorvat We are sorry for that. We are planning the next release to be sooner. Pleas keep in mind that we are all working in our free time at this project and don't get paid for it.

I'm a mac user as well and can therefore tell you that the issue with the copy paste is already fixed in the current development version. https://builds.jabref.org/master/
It was one of the first things we fixed after the release.

**Comment by szhorvat** [comment]
> @szhorvat you can directly paste the code on the maintable.

Unfortunately, this is a hit-or-miss. Sometimes it works, sometimes the Paste menu item is inexplicably greyed out. Right now I can't even paste between two databases concurrently open in JabRef. I can't determine what causes this, it seems random whether it works or not (does not depend on the copied entry).

**Comment by Siedlerchr** [comment]
@szhorvat  Are you using the latest development version? There have been also some follow up fixes

**Comment by szhorvat** [comment]
@Siedlerchr OK, I'll try today's dev version because 5.1 has been a pretty rough ride. If you are aware of any serious/dangerous (= data loss) issues in today's build, please do give me a warning.

**Comment by Siedlerchr** [comment]
As always, when trying out a new version it's recommended to make a backup of your library. Otherwise I don't see any problems.
