### ISSUE TITLE
Search for unlinked local files: "collapse all" button expands tree

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6848]
JabRef 5.2--2020-09-02--5c9edc9
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In the window "Search for unlinked local files", after scanning the directory, a click on "Collapse all" does not collapse the tree. But this button can be used to expand the tree.

1. Lookup -> Search for unlinked local files
2. scan directory
3. click on "Collapse all". Nothing happens.
4. collapse the tree manually by clicking on the triangle at the root.
5. click on "Collapse all". The tree is expanded.

The "Collapse all" button works the same way as the "Expand all" button.

**Comment by PremKolar** [comment]
Hi, I would like to try to fix this as my first issue :)

**Comment by PremKolar** [comment]
I think there is no bug actually..
When you hit Collapse all, every directory **except** the root one gets collapsed. Expand all, _expands all_...
I think it makes sense and works well.. There is no use on collapsing the root level.

**Comment by mlep** [comment]
Well, maybe the issue is limited to:
When everything is collapsed (only the root directory is shown), "Collapse all" should not expand the tree.

**Comment by skeric** [comment]
Hi, I would like to work on that issue.

**Comment by Siedlerchr** [comment]
Thanks to @skeric  this issue should now be fixed

**Comment by mlep** [comment]
It works now! Thank you @skeric!

**Comment by skeric** [comment]
@Siedlerchr and @mlep, you're welcome
