### ISSUE TITLE
Drag & drop of PDF: not on empty library

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6851]
JabRef 5.2--2020-09-02--5c9edc9
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Drag & drop of a PDF file (to create a new entry) does not work if the library file has no entry.

1. Menu File --> New library (the table entry space displays "No content in table")
2. Drag & drop a pdf file in the entry table space.
Nothing happens

**Comment by Siedlerchr** [comment]
The Drag and Drop listener operate on the TableRow, that means you need at least one entry.
Solution: Add drag and drop handler for tableView as well in MainTable.java

**Comment by tp-1000** [comment]
I'll take a look.

**Comment by aakarshvats638** [comment]
Hey can i work on this issue?

**Comment by tp-1000** [comment]
@aakarshvats638 I'll let you know if I need a hand.

**Comment by mlep** [comment]
@Siedlerchr  I wanted to check on this issue, but the last version on https://builds.jabref.org/master/ was published on March 22. Is there a problem?

**Comment by Siedlerchr** [comment]
@mlep  Yep, our Apple developer account expired, we have to renew it to build for mac again. However, you can use the artifact download https://github.com/JabRef/jabref/actions/runs/687970576  (contains all Linux versions)

**Comment by mlep** [comment]
@tp-1000 Thank you for solving this issue. It now works as expected!
@Siedlerchr Thank you for the pointer.
