### ISSUE TITLE
No detailed errors when opening a bib file

### ISSUE THREAD

**Issue by VadeTech** [JabRef/jabref#686]
Hi,

I have just tested the version 3.2 on windows x64, it seems there is no detail when
there is an error in a bib file (at the opening) whereas with version 3.0 on windows x64, jabref provides the line of the ten first errors.

It can be usefull to restore this feature in the future because for example, when we export a bib from ieeexplore website, sometimes there are errors (paper with special symbol in its title as sigma, delta, ...) which have to be corrected by the hand and without the lines number, the modification takes lots of time

Best regards

**Comment by oscargus** [comment]
Hmm, this is a bit weird. The feature is indeed changed, but the only change should be that all errors (not just the ten first) are shown and that the list is scrollable. The dialog looks slightly different, but I do indeed see it when opening bib-files with issues in...

**Comment by stefan-kolb** [comment]
@VadeTech Can you send us a sample Bib file and detailed steps to reproduce this? We cannot see the problem on our end at the moment.

**Comment by VadeTech** [comment]
@stefan-kolb Here comes an example of bib file generated by IEEE Explore.

[example.zip](https://github.com/JabRef/jabref/files/104698/example.zip)

**Comment by lenhard** [comment]
@VadeTech When opening the bib file with the current master branch, I get a Warning dialog with the following messages as desired. Here is a screenshot:
![jabref-snip](https://cloud.githubusercontent.com/assets/1515701/12580814/da76b46c-c432-11e5-984c-b52f7a3e3a4d.PNG)

So it seems that this is fixed on master and I am closing this issue.
