### ISSUE TITLE
File not found popup even if the file has just been added

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6860]
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Added a file, the correct path appears in the file field, but it is highlighted and hovering gives "Could not find file: ..."

1. Load a library containing the following entry:
```
@Article{Cocito2003,
  author    = {Silvia Cocito and Sergio Sgorbini and Andrea Peirano and Mario Valle},
  journal   = {Journal of Experimental Marine Biology and Ecology},
  title     = {{3-D} reconstruction of biological objects using underwater video technique and image processing},
  year      = {2003},
  month     = dec,
  number    = {1},
  pages     = {57--70},
  volume    = {297},
  doi       = {10.1016/S0022-0981(03)00369-1},
  keywords  = {refereed},
  langid    = {english},
  mvpubtype = {refereed},
  url       = {http://mariovalle.name/publications/3D-publication.pdf},
}
```
2. Add an existing PDF file using the + button next to the File field. In my case "D:/Books/Publications/3D-publication.pdf"
3. The path appears in the File field, but it has an orange background an hovering it gives the mentioned error

![image](https://user-images.githubusercontent.com/865866/92071384-dd3bd600-edae-11ea-984d-181b6ff5f933.png)

4. In the library the field is stored as:
```
  file = {:D\:/Books/Publications/3D-publication.pdf:PDF},
```

**Comment by crystalfp** [comment]
If you add twice the same file and then delete the first one the warning disappears and the library does not change.

**Comment by Siedlerchr** [comment]
@crystalfp  PLease check your settings for the file directory in the preferences. Other users reported simliar issues in the forum. It seemeed that somehow the setting main file directory got changed

**Comment by crystalfp** [comment]
That is! Seems this old library had never set the directory.
