### ISSUE TITLE
Fields URL and urldate overlap if the URL is long

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6865]
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The fields `URL` and `urldate` overlap if the URL is longer than one line.

1. Load a library containing:
```
@InProceedings{Herd2010,
  author    = {Seth Herd and Brian Mingus and Randall O'Reilly},
  booktitle = {In Proceedings of the 2010 conference on Biologically Inspired Cognitive Architectures 2010: Proceedings of the First Annual Meeting of the BICA Society},
  date      = {2010},
  title     = {Dopamine and self-directed learning},
  editor    = {Alexei V. Samsonovich and Kamilla R. Jóhannsdóttir and Antonio Chella and Ben Goertzel},
  pages     = {58--63},
  publisher = {IOS Press},
  url       = {https://grey.colorado.edu/mediawiki/sites/mingus/images/c/c0/HerdMingusOReilly10.pdf},
  urldate   = {2020-09-04},
}
```
2. Go to the `Optional Fields` tab and scroll to the URL field.
3. Here the result:

![image](https://user-images.githubusercontent.com/865866/92206730-47747980-ee88-11ea-9c93-eadd3aaac016.png)

**Comment by crystalfp** [comment]
Also without content the URL field spacing below (and/or field height) seems not right:

![image](https://user-images.githubusercontent.com/865866/92475699-1f657d00-f1de-11ea-9876-36d4c085699f.png)

**Comment by Siedlerchr** [comment]
Might be that one of the fields is defined as multiline

**Comment by crystalfp** [comment]
OK, but the result is not nice or readable. Could be multiline, but not overlapping the following field.
