### ISSUE TITLE
Preferences: Search: Many items are not found

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6866]
JabRef 5.2--2020-09-03--1283f9f
Linux 4.9.0-13-amd64 amd64 
Java 14.0.2

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In the preferences window, the search feature misses many (existing) items.

1.Options -> Preferences
2. In the search field, type in *mark*.
-> "Mark new entries with addition date" is found.
But "Mark new entries with owner name" (two lines above) is not.

Many other items cannot be found (Language; special fields; fit; filename; etc.), without any apparent logic between the found/not found items.

PS: I have just discovered the Preferences search. Great feature!

**Comment by fabiojavamarcos** [comment]
I am using JabRef version 5.0 with MacOS 10.14.6 and java OpenJDK 14.0.2 2020-07-14 and I saw the same behavior. I am going to take a look.

**Comment by fabiojavamarcos** [comment]
I found the problem. Trying to fix it.

**Comment by fabiojavamarcos** [comment]
Fixed. Submitting the PR soon.

**Comment by mlep** [comment]
@fabiojavamarcos I have just tested the feature. It works like a charm now! Thanks a lot for your contribution to JabRef development. That will make life easier for many people!

**Comment by fabiojavamarcos** [comment]
It is a pleasure to help!
