### ISSUE TITLE
Double key binding for inserting new TechReport and pulling changes from shared database

### ISSUE THREAD

**Issue by m-mauersberger** [JabRef/jabref#6867]
JabRef version 5.2 on openSUSE Leap 15.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open a shared database.
2. Press "Ctrl+Shift+R".
3. Changes from shared database are pulled **and** a new TechReport is inserted.

Maybe this is quickly done... ;)

**Comment by Gena928** [comment]
Just realised this bug does not depend on Shared Database.
I.e. you can open any library, press "Ctrl+Shift+R" and a new TechReport will be inserted. 

I'll try to fix that.

**Comment by Gena928** [comment]
@tobiasdiez 
need an advice. ))) Looks like there are 2 actions on "ctrl+shift+R" key combination:
- pull changes from shared database;
- create new technical report;

I see it in `KeyBinding.java` file. Which one is better to change? 
I propose to change keybinding for `NEW_TECHREPORT` constant from `ctrl+shift+R` to `ctrl+alt+R`.

**Comment by m-mauersberger** [comment]
I would do it otherwise because there are a lot of 'New' key bindings on `ctrl+shift+... ` (e.g. New Report, New Proceeding,...).

**Comment by Gena928** [comment]
ctrl+shift+
ctrl+shift+

**Comment by Gena928** [comment]
OK, the followed combinations are already assigned:
ctrl+shift+(A, C, D, E, I, K, L, M, N, O, P, R, S, T, U)

ctrl+shift+W?
ctrl+shift+J?

**Comment by tobiasdiez** [comment]
Personally, I would remove the default keybinding for "new techreport". I don't think that many people use that regularly to justify having a keybinding for it (but keep it as an option for people to set it later).

It may be a good idea to revise the keybindings in general, and come up with a consistent layout. Most of the current bindings are a result of step-by-step additions, instead of having a general idea. Some pointers for best practices: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/dnacc/guidelines-for-keyboard-user-interface-design#assigning-shortcut-keys

**Comment by Gena928** [comment]
OK, I'll look into Microsoft guidelines.
Meanwhile, @m-mauersberger what do you think about removing hotkey for "Pull changes from shared database" ?

**Comment by Siedlerchr** [comment]
I think the hotkey for pulling changes is important for Databases that do not support pushing

**Comment by m-mauersberger** [comment]
For me the same, I would keep it. Mh, what about "Alt+Shift+R" for pull changes?

**Comment by Gena928** [comment]
Looks like `alt+shift+R` can be used.
I'll test it tomorrow on Mac & Windows.

**Comment by Gena928** [comment]
Seems like `alt+shift+R` is OK.
In case if no more comments, I'll create a pull request.

**Comment by Gena928** [comment]
Ouch ))
I've created a pull request and it shows 56 commits and 2 files change. Looks like this is because I created the branch from my Master, but it should be created from JabRef/Master. 

Is that a problem? If yes, I will create a new commit.
