### ISSUE TITLE
JabRef should support users entering their own API keys for the lookup services that use API keys

### ISSUE THREAD

**Issue by JasonGross** [JabRef/jabref#6877]
I am running into the same issue as https://github.com/JabRef/jabref/issues/6395 . As per https://github.com/JabRef/jabref/issues/6369#issuecomment-667648423, this is probably Springer rate-limiting JabRef's API key.  If there's no way to permanently fix this problem, I'd suggest adding a dialog box that lets advanced users enter their own API keys, to work around the app-limits.

**Comment by JasonGross** [comment]
I suspect this issue is still relevant, given that https://github.com/JabRef/jabref/issues/6395 has been closed without any indication of it having been fixed

**Comment by SuXiChangZhen** [comment]
@Siedlerchr Hi, I am intersted in this issue. But I wonder how to design the UI to let user enter the api key. Which one is better, add in the preferences or pop up a dialog when exception occur?

**Comment by JasonGross** [comment]
I think it should be in preferences.  The setting should be stateful; I shouldn't have to reenter it every time an error occurs.  (And it should be possible to go back to the default key, which it wouldn't be if there was a stateful change that could only be entered on error.)

**Comment by SuXiChangZhen** [comment]
Thank you for your reply. I agree with you, and I think other api keys(like ieee) should also be included in the preferences. Otherwise, it may seem odd if only springer's api key can be changed.

**Comment by Siedlerchr** [comment]
Yep and gui wise mabye under the Network tab. @calixtus  is the master of preferences atm, maybe he has a btter idea

**Comment by SuXiChangZhen** [comment]
OK, I get it. My teammate @Ryyyc and I was thinking put it in the "Customization" where user can custom DOI URI.
