### ISSUE TITLE
Paste in Bibtex Source field does not work

### ISSUE THREAD

**Issue by nickhalmagyi** [JabRef/jabref#6878]
JabRef version 5.1 on OSX

- [ x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Use the + button to add new article
2. attempt to paste a bibtex item
3. observe that paste fails

**Comment by Siedlerchr** [comment]
Paste the bibtex on the maintable instead. Jabref will automatically create a new entry. Also works for DOIs

**Comment by nickhalmagyi** [comment]
I see so is the paste functionality deliberately disabled in the bibtex source panel? Paste seems to work in other panels.

**Comment by Siedlerchr** [comment]
Normally it should work as well, but we had to implement a workaround for a bug in jdk which would paste things twice in the other input fields. 
This is probably a consequence of that
We need to check if we can tweak the work around for the source field.
