### ISSUE TITLE
Icon doesn't show in Start menu | JabRef.exe does not start (JRE15 issue)

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6890]
JabRef 5.2--2020-09-07--aa14db9
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

On the Start menu the JabRef icon is substituted with the icon of a generic file.

1. Disinstall JabRef
2. Install official version (5.1) or the one from master
3. Look at the Start menu. The icon is not the one from JabRef

![image](https://user-images.githubusercontent.com/865866/92445554-cdf4c800-f1b4-11ea-9c7b-390a373f8852.png)

**Comment by crystalfp** [comment]
If I open the shortcut I see the cause of the problem:

![image](https://user-images.githubusercontent.com/865866/92449872-f5e72a00-f1ba-11ea-935a-a1a8eb080ed6.png)

Manually changing the icon to `JabRef.ico` solved the problem.

**Comment by Siedlerchr** [comment]
DId you encounter this problem again?

**Comment by crystalfp** [comment]
Deinstalled an installed from http://builds.jabref.org/master/
Now JabRef does not start anymore, but the icon is present.
What I don't know is if the icon has been installed by the installer or is a relic of my previous setting it manually.
Now trying to make JabRef working again...
Thanks!
mario

**Comment by crystalfp** [comment]
Well, removing the shortcut from the Start menu, after installation does not appear in the start menu. No JabRef folder containing JabRef link to the program.
I cannot get the program version because it does not starts. But is the version downloaded today at 4.42 CET

**Comment by crystalfp** [comment]
Temporary made JabRef start by running runtime/bin/JabRef.bat

JabRef 5.2--2020-10-04--31f894c
Windows 10 10.0 amd64 
Java 15

**Comment by Siedlerchr** [comment]
Thanks for the feedback. That's odd. We will investigate that

**Comment by Siedlerchr** [comment]
@crystalfp  Can you please test to start the Jabref.exe from the cmd? Do you get any errors?

**Comment by crystalfp** [comment]
I have to run JabRef.bat from runtime\bin, the JabRef.exe in the installation directory does nothing.
```
PS C:\Program Files\JabRef> .\JabRef.exe
PS C:\Program Files\JabRef> .\JabRef.exe --debug
PS C:\Program Files\JabRef> cd .\runtime\bin\
PS C:\Program Files\JabRef\runtime\bin> .\JabRef.bat --debug
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n java.net.SocketTimeoutException: Connect timed out
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at org.jabref.logic.remote.client.RemoteClient.openNewConnection(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.remote.client.RemoteClient.ping(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.handleMultipleAppInstances(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[org.jabref.merged.module:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n
```
The same problem happened before, unfortunately I don't remember how I had solved it.
Thanks!
mario

**Comment by crystalfp** [comment]
Forgot to add the Java Error log:
[hs_err_pid5340.log](https://github.com/JabRef/jabref/files/5331222/hs_err_pid5340.log)

**Comment by Siedlerchr** [comment]
@crystalfp  Thanks. Could you please try this version? if the exe starts?
https://builds.jabref.org/pull/6988/
I changed the jdk

**Comment by crystalfp** [comment]
No, it does not start. But creates the following error log:
[hs_err_pid11668.log](https://github.com/JabRef/jabref/files/5338099/hs_err_pid11668.log)
And the installation does not put the JabRef icon in the start menu.

**Comment by crystalfp** [comment]
Is it true that latest build (JabRef 5.2--2020-10-12--46cc82c, Windows 10 10.0 amd64, Java 15) does not put an entry in Start menu and does not associate .bib to JabRef? Before downgrading to the latest official version, I want to be sure it is not a problem from my side.
Thanks!

**Comment by Siedlerchr** [comment]
Normally it should work. I will check that. 
@crystalfp  Can you please test if this version starts with the exe?  https://builds.jabref.org/pull/7008/merge/
If not, please post the log here

**Comment by crystalfp** [comment]
Deinstalled and rebooted before installing 7008/merge.
It does not start, nor it adds icons in Start Menu.
Here is the error log file: [hs_err_pid3296.log](https://github.com/JabRef/jabref/files/5369737/hs_err_pid3296.log)
I don't know if it is relevant, but the Java I have installed is 32bits: "C:\Program Files (x86)\Java\jre1.8.0_261\bin\java.exe" and the JabRef one (from the log file) seems 64bits: Java VM: OpenJDK 64-Bit Server VM 
Next, maybe not relevant info: During tests, before rebooting, the windows protection dialog appears asking if I want to run this unknown executable. Deinstalling and reinstalling it does not appear again.
Confused
Thanks for your investigative job!
mario

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
In reference to https://discourse.jabref.org/t/5-2-dev-do-not-start/2344/6?u=buhtz
pull 7008 from 13.10.2020 08:19

The msi-version still do not start, no error output or any log.

The portable-version do not start but create a log. See attachment.
[hs_err_pid13436.log](https://github.com/JabRef/jabref/files/5369807/hs_err_pid13436.log)

**Comment by crystalfp** [comment]
The Java 32bits was a red herring. Installed JRE 64bits and nothing changed.
@Codeberg-AsGithubAlternative-buhtz if you run from a writable directory the error log will be created. If you simply double click on the exe file, nothing appears because the directory under C:/Program Files/ is protected

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> @Codeberg-AsGithubAlternative-buhtz if you run from a writable directory the error log will be created. If you simply double click on the exe file, nothing appears because the directory under C:/Program Files/ is protected

Than you should fix JabRef to write its log in the appropriated directory and also create a usefull output on stderr. I did not double click. I started via command line.

**Comment by Siedlerchr** [comment]
Thanks all for the testing, I am in contact with the official Java Development Team regarding the error, because it's an error coming from the JDK itself. I will keep you updated.
@crystalfp  JabRef ships with it's own version of the jdk.
@Codeberg-AsGithubAlternative-buhtz  The crash happened in the JAVA VM.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> FYI the bug is reported here: https://bugs.openjdk.java.net/browse/JDK-8254697

Useless because the bug ticket can not be monitored because the system is restricted to high level users. No way to create an account for normal persons like me. Thanks Oracle. ;)

**Comment by Siedlerchr** [comment]
We downgraded the windows version back to java 14, so the exe issue should not be longer a problem.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Can confirm that this version is running with Windows 10

JabRef 5.2--2020-10-14--a768f6e
Windows 10 10.0 amd64 
Java 14.0.2

**Comment by AlexPars** [comment]
This development build is running under Windows. However, the "Check Integrity" option does not work anymore under the development build for the last few days

**Comment by Siedlerchr** [comment]
@AlexPars  Works fine for me. Can you please open a new issue with some details e.g. what exactly is not working.

**Comment by AlexPars** [comment]
will open a new issue. The problem is the following: I can run "Check integrity" (Quality -> Check Integrity) , and at the end of run I am getting a pop-up message "Error occurred: Integrity check failed" , with no other details

**Comment by crystalfp** [comment]
Yea! This version JabRef 5.2--2020-10-14--a768f6e starts from the exe! Thanks!
Unfortunately installation elicit the classical Windows protection dialog:

![image](https://user-images.githubusercontent.com/865866/96144942-00f15080-0f05-11eb-8607-c23c645dea87.png)

and does not put an entry in the Start menu, but correctly associates JabRef to .bib files.

We are almost there!
Thanks for your efforts
mario

**Comment by Siedlerchr** [comment]
@crystalfp The Windows protection dialog will always come because we don't have a code signing certificate yet (that costs money). We tried to buy one but it was not successful. We will probably try this again once our non profit org is officially registered.

I just merged a change which should now create a start menu folder as well. Should be ready in half an our so.

**Comment by crystalfp** [comment]
I confirm that JabRef 5.2--2020-10-15--13a80ba solved all problems.
If you don't mind, I close this issue.
Thanks again for your work!
mario
