### ISSUE TITLE
Add entry for plain text does not complain, but nothing happens

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6891]
JabRef 5.2--2020-09-07--aa14db9
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Add entry for plain text does not complain, but nothing happens with a specific text copied from an article's bibliography.

1. Put the following text in the "Add entry for plain text":
```
Przybylski, A. K., Murayama, K., DeHaan, C. R., & Gladwell, V. (2013). Motivational, emotional, and behavioral
correlates of fear of missing out. Computers in Human Behavior, 29(4), 1841-1848.
```
2. Push "Add to current library".
3. Message stating the "Your text is being parsed" appears.
4. Then nothing. No error message, no "parsed 0 entries", nothing added to the library.

**Comment by mlep** [comment]
Duplicate of issue #6517 ?

**Comment by crystalfp** [comment]
You are right! Sorry for the duplication. Maybe the text could be another example for #6517
