### ISSUE TITLE
Institution field repeated twice in preview

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6894]
JabRef 5.2--2020-09-07--aa14db9
Windows 10 10.0 amd64 
Java 14.0.2
- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In the Report entry type the standard preview has the "Institution" field repeated twice.

Steps to reproduce:

1. Load a library containing:
```
@Report{Coviello2010,
  author      = {Decio Coviello and Andrea Ichino and Nicola Persico},
  date        = {2010-10},
  institution = {CEPR Centre for Economic Policy Research},
  title       = {{Don’t Spread Yourself Too Thin. The Impact of Task Juggling on Workers’ Speed of Job Completion}},
  type        = {resreport},
}
```
2. Look at the standard preview:

![image](https://user-images.githubusercontent.com/865866/92555542-3486ee00-f268-11ea-9cb3-f1489775e963.png)

The institution field is show twice. Seems that the Institution field is counted also as school.

**Comment by Siedlerchr** [comment]
school is an alias for institution , see section 2.2.2 Data Fields in the biblatex manual, so this is correct.
ftp://ftp.tu-chemnitz.de/pub/tex/macros/latex/contrib/biblatex/doc/biblatex.pdf#subsubsection.1.5.6
Btw, You can modify the default preview style (HTML) in the preferences

**Comment by crystalfp** [comment]
Understand but disagree. I understand they are synonymous, even more so only one should go there.
It is a very minor problem, but visually it is really annoying, especially if the institution name is long.
A feature request, maybe?

**Comment by Siedlerchr** [comment]
@crystalfp  in general I would agree with you, however, there is a minor difference.

The manual says about the field `school`
>An alias for institution, provided for BibTeX compatibility. The institution field is used by traditional BibTeX for technical reports whereas the school field holds the institution associated with theses. The biblatex package employs the generic field name institution in both cases. 

The default preview code is supposed to support both biblatex and bibtex mode.
But you can simply delete one of the lines in the Preferences under -> Entry preview -> Preview -> Edit field

```
\begin{school} <em>\format[HTMLChars]{\school}, </em>\end{school}
\begin{institution} <em>\format[HTMLChars]{\institution}, </em>\end{institution}
```

**Comment by crystalfp** [comment]
OK, thanks for the clarification! Deleted the "school" preview entry and now I'm happy.

BTW, lately I'm opening a lot of issues, but when you really use a tool that helps your work this happens. Continue with the good work! Thanks!

**Comment by Siedlerchr** [comment]
@crystalfp  Thanks for the kind words! No problems with opening bug reports. It helps us to improve JabRef and to spot problems or bugs we might have not noticed otherwise.
