### ISSUE TITLE
Error of "Uncaught exception in Thread[..." when trying to resync references

### ISSUE THREAD

**Issue by andrejdam** [JabRef/jabref#6903]
Hi there guys,

After updating to JabRef 5.1, updating to LibreOffice 7.0.1.2, loading APA6.jstyle (included at the end of this report), and trying to resync references and references list, I get this error: 

> 
> Uncaught exception in Thread[JavaFX Application Thread,5,main]
> 
> class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')

JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

Please help quick, I am in the final editing phase of my thesis and can't afford to lost any time because of program errors (not being arrogant, just pleading for a quick answer/solution, if possible, as time is nigh). For now, the references list stays as was synced the last time I did it, and there's not much I would change in it (so that's good for my situation, let's say), but still I would like to be able to resync it without issues.

Thank you for your assistance, very much appreciated.

Steps to reproduce:

1. Load APA6.jstyle (find it below; note that I used ReferenceParagraphFormat=“References bulleted list”, my own formatting for the references list, a few months before with no issue) 
2. Connect to LibreOffice document (my thesis)
3. Click on references synchronize button
4. JabRef goes through all the references within the text without an issue (it seems)
5. Then, JabRef reaches the References list at the end of the document and throws this exception.
6. The references list is not completed, or even started, for that matter.

There were no issues before with JabRef 4.8.something (but I am not really sure it's because of the update).

Here's the rest of the log:

> java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
> 	at org.jabref@5.1.60000/org.jabref.logic.openoffice.OOBibStyle.isSortByPosition(Unknown Source)
> 	at org.jabref@5.1.60000/org.jabref.gui.openoffice.OOBibBase.refreshCiteMarkersInternal(Unknown Source)
> 	at org.jabref@5.1.60000/org.jabref.gui.openoffice.OOBibBase.refreshCiteMarkers(Unknown Source)
> 	at org.jabref@5.1.60000/org.jabref.gui.openoffice.OpenOfficePanel.lambda$initPanel$9(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/javafx.event.Event.fireEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/javafx.scene.Node.fireEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/javafx.scene.control.Button.fire(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/javafx.event.Event.fireEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene.processMouseEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
> 	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at org.jabref.merged.module@5.1.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 

APA6.jstyle:

> NAME
> APA6 style
> 
> JOURNALS
> Journal name 1
> Journal name 2
> 
> PROPERTIES
> Title=“References”
> IsSortByPosition=“false”
> IsNumberEntries=“false”
> ReferenceParagraphFormat=“References bulleted list”
> ReferenceHeaderParagraphFormat=“Heading 1”
> 
> CITATION
> AuthorField=“author/editor”
> YearField=“year”
> MaxAuthors=“2”
> MaxAuthorsFirst=“5”
> AuthorSeparator=", "
> AuthorLastSeparator=" & "
> AuthorLastSeparatorInText= " and "
> EtAlString=" et al."
> YearSeparator=", "
> InTextYearSeparator=" "
> BracketBefore="("
> BracketAfter=")"
> BracketBeforeInList="("
> BracketAfterInList=")"
> CitationSeparator="; "
> UniquefierSeparator=","
> GroupedNumbersSeparator="-"
> MinimumGroupingCount=“3”
> FormatCitations=“false”
> CitationCharacterFormat=“Text Body”
> MultiCiteChronological=“false”
> 
> LAYOUT
> article=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title. \journal, \volume\begin{number}(\number)\end{number}, \format[FormatPagesForHTML]{\pages}. \begin{doi}doi:\format[DOIStrip]{\doi}\end{doi}
> 
> book=\begin{author}\format[Authors(LastFirst,Initials,Amp,7)]{\author}\end{author}\begin{editor}\format[Authors(LastFirst,Initials,Amp,7)]{\editor} (\format[IfPlural(Eds.,Ed.)]{\editor})\end{editor} (\year\uniq). \title\begin{edition} (\edition ed.)\end{edition}\begin{volume} (Vol. \volume)\end{volume}. \address: \publisher. \begin{url} Retreived from \url\end{url}
> 
> incollection=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title. In \format[Authors(FirstFirst,Initials,Amp,7)]{\editor} (\format[IfPlural(Eds.,Ed.)]{\editor}), \title\begin{edition} (\edition ed.)\end{edition}\begin{volume} (Vol. \volume)\end{volume}. \address: \publisher
> 
> inbook= \format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \chapter. In \format[Authors(FirstFirst,Initials,Amp,7)]{\editor} (Ed.), \title\begin{edition} (\edition ed.)\end{edition}\begin{volume} (Vol. \volume)\end{volume} (pp. \format[FormatPagesForHTML]{\pages}). \address: \publisher.
> 
> phdthesis=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title (Doctoral Dissertation). Retrieved from \url
> 
> mastersthesis=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title (Master’s Thesis). Retrieved from \url
> 
> default=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title. \journal, \volume\begin{number}(\number)\end{number}, \format[FormatPagesForHTML]{\pages}. \begin{doi}doi:\format[DOIStrip]{\doi}\end{doi}

**Comment by Siedlerchr** [comment]
Thanks for your report. It's probably due to the libre office version 7. 
I would suggest reinstalling an older version of Libre office, version 6.x should work fine.

**Comment by andrejdam** [comment]
Hi @Siedlerchr , thanks for your answer. Alright, I'll try to revert back to LO 6 something and see if that fixed the problem--and let you know how it went.

**Comment by andrejdam** [comment]
Hi again @Siedlerchr ,

I tried reverting back to LO 6.3.2.2 (the version I had before I installed 7.x) but the same problem persists.

**Comment by andrejdam** [comment]
OK, so I reverted back to JabRef 5.0-beta 89 which worked previously, to no avail.

I tried deleting the JR_bib section within the document, and again JabRef is stuck with the same error message.

What could this be?!

**Comment by Siedlerchr** [comment]
@andrejdam  
Hi, I think I probably found the issue, can you please check again your jstyle file in a text editor, it might be an issue with having typographical quotation marks in the jstyle file instead of the normal ones,

```
IsSortByPosition=“false”
IsNumberEntries=“false”
```
Must be: 
```
IsSortByPosition="false"
IsNumberEntries="false"
```

Here is a corrected variant:
```


NAME
APA6 style

JOURNALS
Journal name 1
Journal name 2

PROPERTIES
Title="References"
IsSortByPosition="false"
IsNumberEntries="false"
ReferenceParagraphFormat="References bulleted list"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
AuthorField="author/editor"
YearField="year"
MaxAuthors="2"
MaxAuthorsFirst="5"
AuthorSeparator=", "
AuthorLastSeparator=" & "
AuthorLastSeparatorInText= " and "
EtAlString=" et al."
YearSeparator=", "
InTextYearSeparator=" "
BracketBefore="("
BracketAfter=")"
BracketBeforeInList="("
BracketAfterInList=")"
CitationSeparator="; "
UniquefierSeparator=","
GroupedNumbersSeparator="-"
MinimumGroupingCount="3"
FormatCitations="false"
CitationCharacterFormat="Text Body"
MultiCiteChronological="false"

LAYOUT

article=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title. \journal, \volume\begin{number}(\number)\end{number}, \format[FormatPagesForHTML]{\pages}. \begin{doi}doi:\format[DOIStrip]{\doi}\end{doi}

book=\begin{author}\format[Authors(LastFirst,Initials,Amp,7)]{\author}\end{author}\begin{editor}\format[Authors(LastFirst,Initials,Amp,7)]{\editor} (\format[IfPlural(Eds.,Ed.)]{\editor})\end{editor} (\year\uniq). \title\begin{edition} (\edition ed.)\end{edition}\begin{volume} (Vol. \volume)\end{volume}. \address: \publisher. \begin{url} Retreived from \url\end{url}

incollection=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title. In \format[Authors(FirstFirst,Initials,Amp,7)]{\editor} (\format[IfPlural(Eds.,Ed.)]{\editor}), \title\begin{edition} (\edition ed.)\end{edition}\begin{volume} (Vol. \volume)\end{volume}. \address: \publisher

inbook= \format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \chapter. In \format[Authors(FirstFirst,Initials,Amp,7)]{\editor} (Ed.), \title\begin{edition} (\edition ed.)\end{edition}\begin{volume} (Vol. \volume)\end{volume} (pp. \format[FormatPagesForHTML]{\pages}). \address: \publisher.

phdthesis=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title (Doctoral Dissertation). Retrieved from \url

mastersthesis=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title (Master’s Thesis). Retrieved from \url

default=\format[Authors(LastFirst,Initials,Amp,7]{\author} (\year\uniq). \title. \journal, \volume\begin{number}(\number)\end{number}, \format[FormatPagesForHTML]{\pages}. \begin{doi}doi:\format[DOIStrip]{\doi}\end{doi}

```

**Comment by andrejdam** [comment]
@Siedlerchr Christian, thanks for the solution--it really works!

Interestingly enough, I took the APA6 style file from here https://discourse.jabref.org/t/apa-citing-with-libreoffice-using-a-jstyle-sheet/609/2

There might be more people that would be perplexed at the sudden issue when resyncing, so maybe someone ought edit the text over there as well. And also, maybe add in the automatic checker whether the .jstyle file is valid this criterion as well.

Thanks again, I appreciate your assistance!

**Comment by Siedlerchr** [comment]
@andrejdam  Glad to hear it works now. I think it would make sense to add the correct style to the jstyles repo we have.
Will do that.

**Comment by andrejdam** [comment]
That's a great idea. 

Just make sure that ReferenceParagraphFormat refers to something else, as References bulleted list is my own creation and doesn't exist in the standard styles that are included with LO.

Thanks for your assistance again.
