### ISSUE TITLE
Cannot delete standard entry types

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#6906]
Ubuntu 20.04, JabRef 5.1
The following image shows the dialog to customize entry types. I want to delete the entry "Patent" because I never use it. I click on the trash icon. "Patent" disappears. I accept changes. I open the entry type dialog again.

Result:
"Patent" appears again

Expected behavior: 
"Patent" is deleted

Alternative behavior:
"Patent" is a standard field in bixtex, the trash icon shouldn't only appear for user defined entry types.

![grafik](https://user-images.githubusercontent.com/8830305/92999845-7fcd2500-f524-11ea-8ee7-cfa0e7026ca6.png)

**Comment by Siedlerchr** [comment]
Thanks for the report. Actually, you cannot delete the standard entry types. They are always recreated.
However, you can remove/modfiy the fields of the entry type.

=> We should show the trash icon only for custom entry types

**Comment by PremKolar** [comment]
can i do this?
