### ISSUE TITLE
Allow viewing symmetric difference between groups

### ISSUE THREAD

**Issue by mpatas** [JabRef/jabref#6908]
Sometimes a scenario like this happens:

1. A "big" group (like "Physics") corresponding to a large area, exists. Papers get assigned to it.
2. Several papers in a subarea (for example, "Mechanics") are found.
3. A subgroup for that subarea is created, with the "big" group being an union of its "own" papers and papers of this subgroup.
4. The same process is repeated.
5. Dividing group into many subgroups (having no papers assigned directly to the "big" group) starts to look like a good idea.

Then one needs to find the papers which are in the "big" group, and have not yet been distributed into the subgroups. And it looks like there is no convenient way to do that in current version of JabRef (5.1).

The first idea for implementing this would be having an option to toggle group view (when selecting more than one group) not just to "Union" and "Intersection", but also to "set difference". However, I can think of no good way to indicate the lack of symmetry between groups in this case (that is, which group is subtracted from which).

So, the second idea is to have "symmetric difference" (corresponding to logical "xor") instead. Maybe it would not be prefect for this use case, but it would create a useful workaround.

Alternatively, perhaps it would be possible to have a new button toggling between showing all entries in the group (which is done now) and showing only entries directly assigned to the group (ignoring subgroups).

**Comment by stefan2904** [comment]
I think I was looking for something similar when trying to find the papers in my library which have NOT been cited in a paper. (Doing a set operation `all entries` minus `cited entries`).

**Comment by IsaacRoles** [comment]
Unless I am misunderstanding, I believe that there is already a way to do this. If you add the Groups heading to the entry table you can sort your articles by which groups they are in.

![Pic 2](https://user-images.githubusercontent.com/71780917/95239903-a60b7b00-07d9-11eb-8120-94f80979366e.png)

In this example I have the group Nature and the subgroup Politics. I am able to see that two articles are in the group Nature and one them is also in the subgroup Politics.

**Comment by mpatas** [comment]
> In this example I have the group Nature and the subgroup Politics. I am able to see that two articles are in the group Nature and one them is also in the subgroup Politics.

Well, it is a workaround. But not a very convenient one. Especially if there are other interfering "outside" groups, or when one already uses all space for some other columns...
