### ISSUE TITLE
DoiResolution Fetcher fetches whole book for some Springer conference papers

### ISSUE THREAD

**Issue by Toromtomtom** [JabRef/jabref#6922]
JabRef version 5.1 on OpenSUSE Leap 15.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Have the conference paper [Map2Check Using LLVM and KLEE](https://doi.org/10.1007/978-3-319-89963-3_28) in your library
2. "Search full text documents online"
3. JabRef downloads a PDF of the whole conference proceedings instead of just the paper

I looked through the code a bit and it seems like the `DoiResolution` fetcher has a higher trust value (`TrustLevel.SOURCE`) than the `SpringerLink` fetcher (`TrustLevel.PUBLISHER`). Whereas the `SpringerLink` fetcher gets the correct link to the paper PDF, the `DoiResolution` fetcher selects the wrong PDF link from the Springer website.

**Comment by Siedlerchr** [comment]
JabRef's DOI  Resolution fetcher is kind of quick and dirty search, it simply looks for the first link to a pdf on the site to which the DOI redirects. And for Springer, there is only a download for the whole book. 
An idea for enhancement would be to check if the url contains springer, to call the Springer fetcher.

**Comment by Toromtomtom** [comment]
I see. Would it also make sense to not return anything if the URL contains springer? Because AFAIU the Springer fetcher is running in parallel anyways.

I'll have a go at this and see if I can open a PR.

**Comment by Siedlerchr** [comment]
If it's running in parallel then it indeed makes sense to cancel it/return nothing

**Comment by Toromtomtom** [comment]
Fixed by https://github.com/JabRef/jabref/commit/ce9f714f6d01c8a49fccf5c8df9cbf5bc3e8403f.
