### ISSUE TITLE
Cannot generate preview based on selected citation style.

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6930]
JabRef version  on 

JabRef 5.2--2020-09-21--6a6db58
Linux 5.4.0-47-generic amd64 
Java 14.0.2

- [ x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Preview doesn't work.

1. Go to "Preview" tab.
2. Receive the error message "Cannot generate preview based on selected citation style."
3. Pressing F9 to change preview styles makes no difference.  The default "Preview" style works.  All others fail.

![image](https://user-images.githubusercontent.com/762246/93818693-ea165180-fc17-11ea-8d49-d49dcab42742.png)

<details>
  <summary>Log File</summary>
Log file is empty.

</details>

**Comment by Siedlerchr** [comment]
Hm. this is odd. I tested both Windows and Mac and did not encounter any issues. And it's also add that you don't see any error messages in the log.
Do the styles show up in the list on the left when you open the preferences?

**Comment by wujastyk** [comment]
Yes, they do.  I've tried moving the styles out of my right-hand list, and
then back into it, in case that caused some kind of update or reset.  No
luck.

**Comment by wujastyk** [comment]
JabRef 5.3--2021-03-22--8fe77dd
Linux 5.4.0-67-generic amd64 
Java 15.0.2 
JavaFX 16+8

fine now.
