### ISSUE TITLE
Jabref flagging NASA DOI as invalid

### ISSUE THREAD

**Issue by NRJank** [JabRef/jabref#6932]
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

(same issue on previous JabRef 4.3.1)

- [ no] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists
[unable to run 5.2 dev version to check.](https://github.com/JabRef/jabref/issues/5314#issuecomment-696439091)

NASA DOI is flagged as invalid, so links to open/lookup/get bibtex data, etc., are disabled.

1. create new article
2. put NASA DOI in DOI feild, e.g., 2060/19660017401
3. valid doi resolves to http://dx.doi.org/2060/19660017401 at [https://ntrs.nasa.gov/citations/19660017401](https://ntrs.nasa.gov/citations/19660017401)

gets flagged with "DOI 2060/19660017401 is invalid" error.

**Comment by Siedlerchr** [comment]
I tested this with the 5.2 snapshot.
FIrst of all, JabRef's statement that the above mentioned DOI is invalid, is correct.
JabRef follows the DOI spec and the DOI spec says that it needs a prefix with "10". 

I have no idea and could not find any further information. Theoretically it should be possible to search for this using the SOA/NASA database fetcher in JabRef.

**Comment by NRJank** [comment]
Interesting. I was surprised to see the format myself, but doi.org seems to have no problem with it.  The [spec does state that DOIs use 10](https://www.doi.org/doi_handbook/2_Numbering.html#2.2.2).  and that part of ISO 26324 is paywalled. Nonetheless, Nasa uses 2060 and DOI resolves it for them.

**Comment by NRJank** [comment]
i dropped an inquiry to doi.org since that seems in conflict with their stated naming convection. we'll see if they respond.

**Comment by NRJank** [comment]
from DOI.org staff:

"The identifier you have cited for the NASA Technical Report is a handle, not a DOI. The DOI System is a specific implementation of the Handle System. Handles should be resolved on the web via the Handle System Proxy, in this case that URL would be https://hdl.handle.net/2060/19660017401 and not the DOI proxy. While handle and DOI resolution on the web are similar, the proxy servers do not have identical functionality. You are correct that an identifier, even if appended to https://dx.doi.org, that does not begin with a 10. prefix is not a DOI. It is possible that NASA is also a member of a DOI Registration Agency and does assign DOIs to some of their publications. This particular technical report has been given a handle."

**Comment by Siedlerchr** [comment]
Thanks for posting the response.
That explains a lot. In short handles are just some kind of persistent unique identifier for managing urls or other resources. 
I read a bit about that and it seems like DOI is a special  implementation of a handle system
https://project-thor.readme.io/docs/project-glossary

To sum up, JabRef's behavior is correct.

**Comment by NRJank** [comment]
seems so. Jabref -could- manage handles in general, but there's a URL field for that.
