### ISSUE TITLE
multiple monitors - Entry Editor context menu always appears on main monitor even when Jabref isn't

### ISSUE THREAD

**Issue by NRJank** [JabRef/jabref#6935]
JabRef 5.2--2020-09-21--0da0f0c
Windows 10 10.0 amd64 
Java 14.0.2

- [YES] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

On a two-monitor system, Jabref always opens on the last monitor it was on when it was closed, but the context menu for the Entry Editor seems to always only appear on whatever windows designates as the primary monitor. Tested with 5.1 and 5.2 (version above).  Context menus for other things appear near the mouse pointer as expected.

1. Open Jabref (appears on main monitor)
2. right click on a database entry, context menu appears as expected near pointer. 
3. double click entry to open Entry Editor, right click one of the fields, context menu appears near pointer.
4. move Jabref window to second monitor.  
5. right click on a database entry, context menu appears as expected near pointer. 
6. right click one of the Entry Editor fields, context menu appears back on main monitor, at closest edge to monitor with Jabref
7. move Jabref back to main monitor
8. right click in Entry Editor, context menu appears near pointer again.

Screenshot with context menu where it belongs:
![Context menu where it belongs](https://user-images.githubusercontent.com/13259444/94033299-d2ada480-fd8e-11ea-997f-53cc6211aba5.png)

Screenshot with context menu stuck on the right (main) monitor.  (note the windows start bar starts again denoting monitor edge)
![Context menu stuck on main monitor](https://user-images.githubusercontent.com/13259444/94033960-79924080-fd8f-11ea-9f6e-920d075529cf.png)

<details>
  Event log always blank
</details>

screenshots dont show it but in both cases mouse pointer was over the Title entry field.

**Comment by NRJank** [comment]
somehow missed a very similar open issue #5941 that's tagged as a linux issue.  so seems to be a cross-OS problem.

**Comment by calixtus** [comment]
@NRJank thanks for reporting and for linking to the other issue. I'll mark this as duplicate, if that's fine for you. I have put the other issue report in our soon to fix bug list.
