### ISSUE TITLE
Export to word xml or other software files without issue field

### ISSUE THREAD

**Issue by hao203** [JabRef/jabref#6947]
JabRef version  on 

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. import the entry of journal reference, number = issue.
2. export the entries to word xml, without issue field. It's still the number field. The reference in word actually don't have the number field.
3. when use reference function in word, the import references without issues.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Hi, I'm not sure I fully understand your problem, but I think it's correct behaviour her, JabRef follows the biblatex spec.
bibtex/biblatex  number field => word xml: number field (except for entry type patent)
bibtex/biblatex issue field => word xml: issue field 

So you just have to manually add/fill out the field issue.

For an overview of mapping fields
https://docs.jabref.org/advanced/knowledge/msofficebibfieldmapping#field-mappings

**Comment by hao203** [comment]
> Hi, I'm not sure I fully understand your problem, but I think it's correct behaviour her, JabRef follows the biblatex spec.
> bibtex/biblatex number field => word xml: number field (except for entry type patent)
> bibtex/biblatex issue field => word xml: issue field
> 
> So you just have to manually add/fill out the field issue.
> 
> For an overview of mapping fields
> https://docs.jabref.org/advanced/knowledge/msofficebibfieldmapping#field-mappings

Hi，Siedlerchr 
Thanks. I viewed the field mappings. But in word reference, there was no number field.
I confused that when I import one entry of article in jabref， it is the number field instead of the issue field. That is weird. We usually use issue field in other reference softwares,  such as endnote.
If jabref still insist on number field, the communication with other  reference softwares would be difficult.
For example, the export files from jabref will missed some fields when import to other reference software (no number field).

**Comment by Siedlerchr** [comment]
Thanks for the feedback. The bibtex export from your example should have used the field number. The field issue does not exist in bibtex originally. Only number. Only biblatex has it.
JabRef follows the biblatex spec, but can display also custom fields. So simply copy the value from the field issue to the field number. You can see the field issue in the Other fields tab.

http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf

> issue field (literal) The issue of a journal. This field is intended for journals whose individual issuesare identified by a designation such as ‘Spring’ or ‘Summer’ rather than the monthor a number. The placement of issue is similar to month and number. Integer ranges and short designators are better written to the numberf ield. See also month,number and §§2.3.10 and 2.3.11.

2.3.11:
>The words ‘number’ and ‘issue’ are often used synonymously by journals to referto the subdvision of avolume. The fact thatbiblatex’s data model has fieldsof both names can sometimes lead to confusion about which field should be used.First and foremost the word that the journal uses for the subdivsion of avolumeshould be of minor importance, what matters is the role in the data model. As a ruleof thumbnumberis the right field in most circumstances.

**Comment by hao203** [comment]
> Thanks for the feedback. The bibtex export from your example should have used the field number. The field issue does not exist in bibtex originally. Only number. Only biblatex has it.
> JabRef follows the biblatex spec, but can display also custom fields. So simply copy the value from the field issue to the field number. You can see the field issue in the Other fields tab.
> 
> http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf
> 
> > issue field (literal) The issue of a journal. This field is intended for journals whose individual issuesare identified by a designation such as ‘Spring’ or ‘Summer’ rather than the monthor a number. The placement of issue is similar to month and number. Integer ranges and short designators are better written to the numberf ield. See also month,number and §§2.3.10 and 2.3.11.
> 
> 2.3.11:
> 
> > The words ‘number’ and ‘issue’ are often used synonymously by journals to referto the subdvision of avolume. The fact thatbiblatex’s data model has fieldsof both names can sometimes lead to confusion about which field should be used.First and foremost the word that the journal uses for the subdivsion of avolumeshould be of minor importance, what matters is the role in the data model. As a ruleof thumbnumberis the right field in most circumstances.

Really thank you.
