### ISSUE TITLE
Enable Auto Sync per default for Open/LibeOffice 

### ISSUE THREAD

**Issue by mwittchen** [JabRef/jabref#6957]
JabRef 5.1--2020-08-30--e023aa0
Ubuntu 18.04.3 LTS 
Java 14.0.2
Libreoffice 6.0.7.3

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Instead of showing a Number in brackets as citation when using the "default [Number] style file" a minus sign with space "- " is printed when citing in LibreOffice. The "default [Author] style file" works as expected though.

1. Connect to LibreOffice Document
2. Select citation style "Default [Number] style file"
3. Cite a reference by clicking on "cite" or "cite in text"
4. The citation in Libreoffice will only contain a "- " and no Number or brackets

The bug can be reproduced with any reference I choose. I also tried to define my own copy of the default number style file from this file src/main/resources/resource/openoffice/default_numerical.jstyle but I get the same output (minus sign with space instead of Number in brackets).

**Comment by Siedlerchr** [comment]
Thanks for the report. Indeed, I could reproduce this with the latest dev version and LO 6.4.x

**Comment by Siedlerchr** [comment]
I digged into it and it's correct. The "magic" happens when you press the sync button manually or enable Auto Sync
Maybe one could add a section to the help here:
https://docs.jabref.org/cite/openofficeintegration#using-the-openoffice-libreoffice-interface
![grafik](https://user-images.githubusercontent.com/320228/94459066-21a47100-01b7-11eb-813d-de7b9b7e9d4a.png)

**Comment by mwittchen** [comment]
> I digged into it and it's correct. The "magic" happens when you press the sync button manually or enable Auto Sync.
> Then the "-" will be replaced by numbers
> 
> Maybe one could add a section to the help here:
> https://docs.jabref.org/cite/openofficeintegration#using-the-openoffice-libreoffice-interface
> ![grafik](https://user-images.githubusercontent.com/320228/94459066-21a47100-01b7-11eb-813d-de7b9b7e9d4a.png)

Thank you for diving into the details and finding a solution for the problem! This also works when "- " citations are already inserted into the document, which get exchanged for the correct citations when enabling "automatically sync". I think updating the help/documentation is not enough, as the "author/year" citation styles are correctly inserted into the document without enabling "auto sync" or performing a manual sync. As this is intransparent behavior for the user I recommend both citation styles should function identically: either one has to perform a auto/manual sync or the correct citation gets inserted directly without further user interaction.

**Comment by Siedlerchr** [comment]
@mwittchen I think the difference is that JabRef recalculates the numbers, let's say you have citation A [1] and citation B [2] and you now insert citation C after citation A,  JabRef needs to recalculate the numbers. So that citation B now becomes [3].

**Comment by mwittchen** [comment]
@Siedlerchr I understand the underlying technical problem when using the number citation style. Nevertheless I guess that the average JabRef user is not aware of this and might come to the conclusion that JabRef is not working properly. Maybe the best "bug fix" is to activate auto sync as a default regardless of the chosen citation style and the user has to turn auto sync off manually if he does not want to use it.

**Comment by Siedlerchr** [comment]
I've edited the title and added it as feature request

**Comment by mwittchen** [comment]
Thanks!

**Comment by IsaacRoles** [comment]
I am interested in solving this issue if you want to assign it to me. I am looking for a good first issue to solve.

**Comment by Siedlerchr** [comment]
Thanks for your interest. This issue is a good opportunity to understand the project. To get started follow our contribution guide  https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md
And just create a PR
