### ISSUE TITLE
Different icons for DOI vs HTML links

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#696]
From @lc9275 One request: would it be possible to have different icons for doi and html like before? 
Maybe we can do this for the url/doi column inside the main table.

**Comment by stefan-kolb** [comment]
@matthiasgeiger Do you think there are possible icons for that?

**Comment by simonharrer** [comment]
or @matthiasgeiger could we combine an icon with a text, so that we use the default icon for a document and add the text as an overlay?

**Comment by matthiasgeiger** [comment]
https://materialdesignicons.com/icon/library or https://materialdesignicons.com/icon/book for DOI?

**Comment by stefan-kolb** [comment]
I like the library icon. Although I'm generally not convinced to introduce two icons. I mean both just open a website. What if there are two URLs anyway?

**Comment by simonharrer** [comment]
maybe combine two existing icons: http://stackoverflow.com/questions/5797113/java-combine-imageicons

**Comment by koppor** [comment]
Reasoning for two icons: DOI leads to a full text provided by the publisher, HTML may lead to a background page or the paper on the homepage of the author. IMHO this distinction is quite common. Furthermore, this is also a kind of quality check: Do most of my entries contain a DOI?

**Comment by simonharrer** [comment]
Good idea for the database statistics.

**Comment by stefan-kolb** [comment]
But we only show one icon even if both links are there?!

2016-01-28 14:28 GMT+01:00 Simon Harrer <notifications@github.com>:

**Comment by ambro2** [comment]
@koppor to extend your reasoning I'd point out that several types of document do not have DOI: patents, books, reports, theses etc. Further, some "exotic" or very old paper may not have DOI. So, I vote for two different icons.

**Comment by koppor** [comment]
Minor comment: "Statistics" refs https://github.com/koppor/jabref/issues/38

**Comment by koppor** [comment]
Multiple types. Textual overlay would be great. Or the icon of the type belonging to the link which will be opened on click. Maybe with a little plus in the lower right corner to show that there are more links?

**Comment by simonharrer** [comment]
We could use the `barcode` icon from the https://materialdesignicons.com/

**Comment by stefan-kolb** [comment]
Yeah thats cool!

**Comment by simonharrer** [comment]
@matthiasgeiger is the icon already included in the current icon font we use?

**Comment by matthiasgeiger** [comment]
Yes. Codepoint should be `F071`.
