### ISSUE TITLE
Adding simple "Copy" in addition to "Copy preview" to right-click menu of preview

### ISSUE THREAD

**Issue by mpatas** [JabRef/jabref#6962]
Perhaps it would be worth to add a simple "Copy" in addition to "Copy preview" to right-click menu of preview pane. Sometimes it is convenient to copy just a part of preview (selected beforehand), and to use right-click menu for that, as in many other programs. But in JabRef (version 5.1) right-click menu only allows one to copy the whole preview. By the way, Ctrl-C still works, and thus is a workaround.

**Comment by Siedlerchr** [comment]
I would find this feature also very useful! Especially when one wants to copy only a part of the preview (e.g. without abstract)

**Comment by tmrd993** [comment]
Is this the proposed behaviour?

![selectioncopy](https://user-images.githubusercontent.com/47194464/106932123-a2501c80-6717-11eb-97de-e5fc90860f3f.gif)

**Comment by Siedlerchr** [comment]
Yes! that is the desired behavior!

**Comment by Siedlerchr** [comment]
@mpatas  Thanks to @tmrd993  this issue is now fixed in the latest master!

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
