### ISSUE TITLE
Cannot add special characters like curley brackets or copy/pase in Bibtex source entry

### ISSUE THREAD

**Issue by i-regular** [JabRef/jabref#6964]
Dear community and developers,

I recently downloaded version 5.1 of JabRef for macOS (Catalina).  If I open an entry and go to the "Bixtex source" tab I cannot insert any special characters like { or [. Furthermore I cannot copy paste using the usual shortcuts like cmd + c and cmd + v, this only works if I right click. It was possible to do all this in version 5.0

1. Download version 5.1 for macOS
2. open or add a new entry
3. go to "Bibtex source" and try to add any special characters e.g. {

**Comment by Siedlerchr** [comment]
Thanks for your report. 
Copy pasting works again in the latest development version  from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
You can also paste bibtex directly on the maintable without creating a new entry first.

The entering of the curly braces seems to be a bug in the external library.  I locally tested it with a downgrade and that seems to work. I will investigate further.
