### ISSUE TITLE
Bulk Copy/Open files

### ISSUE THREAD

**Issue by AtrusRiven** [JabRef/jabref#6966]
I would find it very helpful if it were possible to copy/open multiple attached files at once (after having selected multiple entries and having right-clicked and having selected from the context menu: "copy/open all files attached to the selected entries").

**Comment by Siedlerchr** [comment]
I'm not entirely sure what you exactly mean, but do you know about the Autolink files feature? 
Maybe that's what you wantto achieve 
https://docs.jabref.org/finding-sorting-and-cleaning-entries/filelinks

**Comment by AtrusRiven** [comment]
Be it that I want to give all PDFs (full texts) related/belonging to multiple entries to another person. At the moment, I have to pick and copy the files one by one by right-clicking on every entry and select "Open folder" where the related file is selected. But it would be very helpful if I could copy all files related to multiple entries in one single step.
Another use case would be to open (instead of copying) multiple files in one step, for example in order to analyse their relevance for me. I hope that was more comprehensible. Thanks!

**Comment by Siedlerchr** [comment]
@AtrusRiven  You are lucky, for the bulk copying/exporting there is already a feature in JabRef.
You select multiple entries and go to Tools -> Copy linked files to folder and JabRef will export all linked files from the entries to a folder you specify. Maybe that feature helps you already?

**Comment by AtrusRiven** [comment]
Thanks, @Siedlerchr! That does the trick for copying/exporting. I'd be glad if it were possible to add the feature "open linked files" (in addition / parallel to the bulk copy feature).
Thanks for your fast help!

**Comment by AtrusRiven** [comment]
- This issue is still relevant although not very urgent. Would be a »nice to have«.
- At the moment the context menu option `Open File` is greyed out when multiple entries are selected. It would be nice (in addition to the bulk copy option) to be able to open all files of multiple entries.
- Possible use case: Reviewing the content of multiple texts while looking for specific content.
![Screenshot](https://user-images.githubusercontent.com/29101440/116993767-32324200-acd8-11eb-8e55-05a78561f661.png)

**Comment by XDZhelheim** [comment]
Hello, I'm trying to work on this issue. So far I successfully added a new option in the right click menu. But when multiple entries selected, it is disabled, same as `Open file` option. Which part of codes should I modify to enable it?

**Comment by XDZhelheim** [comment]
Finally made it. There is a `needsEntriesSelected` condition.

I will draft a PR in the coming few days ASAP.

**Comment by tobiasdiez** [comment]
Thanks to @XDZhelheim this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
