### ISSUE TITLE
Improvements for check integrity

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#698]
- [x] Enable sorting by click on table header
- [x] IGNORE Enable check for unknown entry type `Other`
- [ ] Enable right-click -> "fix it" (should call a cleanup action)
- [ ] Enable configuration. For me, I do not want to have any curly brackets at the large capitals, because I use biblatex
- [x] Page number with one `-` is valid for biblatex files. (Maybe the error message "valid" is misleading. It is only not nicely typeset :sunflower:)

**Comment by simonharrer** [comment]
Configuration and corresponding clean up action is currently too far away. Putting it on hold.
