### ISSUE TITLE
UI: two menus for "Manage external file types" 

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6991]
There is two ways to access the window "Manage external file types":
1. Options -> Manage external file types
2. Options -> Preferences, tab External programs, button "Manage external file types"

Considering the management of external file types is seldom, I suggest to keep only the second way. Moreover, it helps in having  all the preferences in the Preferences window.

JabRef 5.2--2020-10-07--4b1b7b4
Linux 4.9.0-13-amd64 amd64 
Java 15

**Comment by kywelch17** [comment]
is this problem still relevant? would like to work on it if so.

**Comment by mlep** [comment]
The menu is not here anymore, making the UI more consistent. Thank you @schrothbn!
