### ISSUE TITLE
Groups: "All entries" should always display all entries

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6997]
JabRef 5.2--2020-10-07--4b1b7b4
Linux 4.9.0-13-amd64 amd64 
Java 15

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Currently, the group "All entries" can be edited as any other group.
This is OK for the name, description, icon and color.

This leads to surprising results when a "Collect by" item is activated (by default, no item is selected --- even if they are radio buttons).
And it is not possible to unselect the "Collect by" item (since it is a radio button).

This advocates for making the "Collect by" items inaccessible to the users for the "All entries" group.

Note: I have no idea if the "Hierarchical context" should be kept accessible or not.

**Comment by Siedlerchr** [comment]
I can edit the group All entries, but the changes are not saved, e..g it's always reset to default.
I think it makes sense to disable the dialog "edit group" for all entries. And I could theoricalyl also remove the group. I get a conifmration that the group is removed, but actually it's not.
I see it more of an usabily issue.

**Comment by mlep** [comment]
Issue still relevant.

**Comment by mlep** [comment]
Issue can be closed following PR #9376.
