### ISSUE TITLE
Group's color not saved

### ISSUE THREAD

**Issue by weimdall** [JabRef/jabref#6999]
JabRef 5.2--2020-10-07--4b1b7b4
Linux 5.8.14-arch1-1 amd64 
Java 15

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When I assign a color to a group, it is not saved properly, and not even shown in the list.

1. Assign a color to a group (Free search expression mode)
![2020-10-10-165141_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/95664918-a9746e80-0b19-11eb-94ff-2fe9abf0eacf.png)

2. Save, quit JabRef (We can see here that the colors haven't been assigned in the list)
![2020-10-10-165206_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/95664920-b1341300-0b19-11eb-8db2-94b46b79c2e3.png)

3. Start JabRef, color disappeared !
![2020-10-10-165247_5760x1757_scrot](https://user-images.githubusercontent.com/7267440/95664925-b5f8c700-0b19-11eb-826c-3ce249395172.png)

Here is a video that shows all my actions : 
[jabref.mkv.gz](https://github.com/JabRef/jabref/files/5360084/jabref.mkv.gz)

Any idea ? Am I doing something wrong ?

**Comment by Siedlerchr** [comment]
Maybe relevant: #6374

**Comment by mlep** [comment]
Bug is present for "Free search expression" group, but not for "Explicit selection" or "Searching for keywords" groups.

**Comment by gyowannyqueiroz** [comment]
👋 I'm new to the project and looking for a good first issue to get started.  I'm curious, why the color property is being stored in the database as an object of type `javafx.scene.paint.Color`? I got a feeling the color data is lost during serialization. I'll try to change the color property type to `String` and see if it works.

**Comment by tobiasdiez** [comment]
Thanks to @HoussemNasri  should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

Thanks @gyowannyqueiroz for your interest but @HoussemNasri was too quick ;-). I'm sure there are other issues that you may find interesting to work on.
