### ISSUE TITLE
Nothing happens creating entry from specific ISBN

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#7000]
JabRef 5.2--2020-10-07--4b1b7b4
Windows 10 10.0 amd64 
Java 15

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Creating entry from ISBN do nothing without any message stating the reason.

1. Open the new entry dialog
2. Select ID type: ISBN and enter the following ID: 88-17-21041-2
3. Push Generate, nothing happens and no error message appears
4. Same result from the newer ISBN: 9788817210416

The two ISBN are copied directly from the cover of the book. If for some reason they are invalid or not existent, I expect at least an error messages stating the reason. For other errors (I tried removing a digit and changing a digit) an error popup appears.

I search these ISBN on [bookfinder.com](https://www.bookfinder.com/) and the book indeed exists.

Here is the full entry:
```
@Book{Sagan1985,
	author    = {Carl Sagan},
	title     = {Contact},
	date      = {1997-09},
	origdate  = {1985},
	publisher = {Rizzoli},
        location  = {Milano},
	isbn      = {88-17-21041-2},
        langid    = {italian},
}
```

**Comment by crystalfp** [comment]
The same problem for ISBN: 9788845253119

**Comment by tmrd993** [comment]
As far as I know, JabRef has two sources for ISBN fetching. This behaviour happens if the ISBN is valid, but the actual book isn't available at any of the two sources. An invalid ISBN actually has an exception thrown, that's what you are seeing when you remove or add digits to the ISBN.

**Comment by tmrd993** [comment]
https://github.com/JabRef/jabref/blob/4cf2fb06d3d876d2043f65ca0e51c3c4185fd05c/src/main/java/org/jabref/logic/importer/fetcher/IsbnFetcher.java#L44-L60

I think we could throw a FetcherException here if the bibEntry is still empty after trying ottobib?

**Comment by crystalfp** [comment]
Any feedback to the user instead of nothing is a sorely needed thing
