### ISSUE TITLE
Toggle of special fields does not work for sorted entries

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7016]
JabRef 5.2--2020-10-13--fdaf25a
Linux 4.9.0-13-amd64 amd64 
Java 15

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When entries are marked and sorted by a special field, "toggling" the special field of these entries does not work.

1. open the file jabref-authors.bib (https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/jabref-authors.bib)
2. display the columns of the specials fields (options -> preferences, tab Entry table)
3. mark a small set of entries as "Relevant"
4. sort entries by "Relevance" (by clicking on the column title), so that the marked entries are displayed at the top of the entry table
5. select the entries marked as "Relevant"
6. right-click and select "Toggle relevancy". 
==> Only a portion of the selected entries have their "Relevance" status toggled.

Note: same faulty behavior with the other special fields (Read status, Rank, Quality assured, Priority, Print status)

**Comment by PremKolar** [comment]
Can I do this?

**Comment by JavuesZhang** [comment]
> This issue has been inactive for half a year. Since JabRef is constantly evolving this issue may not be relevant any longer and it will be closed in two weeks if no further activity occurs.
> 
> As part of an effort to ensure that the JabRef team is focusing on important and valid issues, we would like to ask if you could update the issue if it still persists. This could be in the following form:
> 
> * If there has been a longer discussion, add a short summary of the most important points as a new comment (if not yet existing).
> * Provide further steps or information on how to reproduce this issue.
> * Upvote the initial post if you like to see it implemented soon. Votes are not the only metric that we use to determine the requests that are implemented, however, they do factor into our decision-making process.
> * If all information is provided and still up-to-date, then just add a short comment that the issue is still relevant.
> 
> Thank you for your contribution!

Hi, I think I have reproduced this problem. Could I have a try to fix it?

**Comment by Siedlerchr** [comment]
Sure that would be neat

**Comment by mlep** [comment]
@JavuesZhang I can confirm this is now fixed. Thank you for improving JabRef!

JabRef 5.3--2021-04-26--add694a
Linux 4.19.0-16-amd64 amd64 
Java 15.0.2 
JavaFX 16+8
