### ISSUE TITLE
Sidebar may be too small

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#702]
Does not show close button etc.

**Comment by matthiasgeiger** [comment]
You mean that the **sidebar** can be too small without horizontal scrollbars, effectively hiding the close button? 

Or do you refer to the "edit group" **window**?

**Comment by stefan-kolb** [comment]
The sidebar toggle groups interface. Groups -> Toggle groups interface.

**Comment by matthiasgeiger** [comment]
(also mentioned in #668 - all sidebars are affected not only groups)

**Comment by stefan-kolb** [comment]
I think increasing the preffered default size might resolve the issue. @JabRef/developers Can anyone verify this with cleaned JR preferences?

**Comment by koppor** [comment]
I did `--prdef all -n` and it looks fine. :+1: 

![grabbed_20160129-100718](https://cloud.githubusercontent.com/assets/1366654/12671473/18cafbf8-c670-11e5-9626-a133519cc7e9.png)

**Comment by simonharrer** [comment]
:+1:

**Comment by simonharrer** [comment]
Hm, we need a changelog entry for that as well.

**Comment by matthiasgeiger** [comment]
uhh... haven't checked the code - but this is seems to be only a workaround. There are other "sidebars" such as the OO/LO sidebar which requires even more space - so only changing the default size does not help (esp. as the width is resizable by the user).

Introduce horizontal scrollbars for this case?
