### ISSUE TITLE
Error message before starting new entry from ID

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#7020]
JabRef 5.2-PullRequest7008.168--2020-10-12--67c873b
Windows 10 10.0 amd64 
Java 15

The new entry dialog has always the ID field marked with red corner and red "!". But this error message makes sense only if I push Generate without putting anything in the ID field and without pushing any of the predefined entry types. But in this case the Generate button is correctly disabled. So the message can be removed because signal something that could not happen.

Steps to reproduce:

1. Start JabRef
2. Go to Library > New Entry
3. The following sign appears:
![image](https://user-images.githubusercontent.com/865866/96142639-9c34f680-0f02-11eb-9a53-693c3ea7caa4.png)
The sign remains even if I change the ID Type.

**Comment by Siedlerchr** [comment]
Similar issue and proposed solution: https://github.com/JabRef/jabref/pull/6418#issuecomment-645950155
