### ISSUE TITLE
"Check integrity" cannot be completed on Windows

### ISSUE THREAD

**Issue by AlexPars** [JabRef/jabref#7021]
The problem is the following: I can run "Check integrity" (Quality -> Check Integrity) , and at the end of run I am getting a pop-up message "Error occurred: Integrity check failed" , with no other details

This is run under Windows 10

JabRef 5.2--2020-10-14--a768f6e
Windows 10 10.0 amd64 
Java 14.0.2

The Event log is empty

**Comment by Siedlerchr** [comment]
Could you please add a Screenshot? 
 That might help us to identify the dialog and hopefully the cause

**Comment by AlexPars** [comment]
![Jabref_IntegrityCheckFailed](https://user-images.githubusercontent.com/37603697/96184764-e9b36280-0f06-11eb-8f81-aa76cea186a6.PNG)

snapshot of error

**Comment by Siedlerchr** [comment]
Thanks. I figured out that the failure does not report any details. I added a change that should display an exception or so in the details of the dialogs. It would be nice if you could try the new master version then and report back (with hopefully more details) on the concrete error.

**Comment by AlexPars** [comment]
Thank you for enabling the details. With the latest development build (from 2020-10-16), I am getting the following details

Illegal char <:> at index 4: http://arxiv.org/pdf/2002.10199v2

The error is due to additional character(s) automatically added when an arXiv article was added to bib file
file         = {:http\://arxiv.org/pdf/2002.10199v2:PDF},

**Comment by AlexPars** [comment]
Update: after removing the extra character : in all arXiv bib entries with file = {:http://arxiv.org/pdf..., the "check integrity" operation was finished successfully. Thus this issue can be closed

That added capability (of having the details of the error shown) was very useful. Thank you for it.

On a side note, one may need to look into why that additional character : was added to file field in the bib entry when an ArXiv article was added. This additional character appears to be added only for ArXiv articles

**Comment by Siedlerchr** [comment]
Thanks for the feedback. There have recently been some internal changes to the handling of files and urls. Probably related.
