### ISSUE TITLE
Snap build no longer working

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7022]
From the action: 

> Downloading 'JabRef-5.2-portable_linux.tar.gz'   0%                            
> Downloading 'JabRef-5.2-portable_linux.tar.gz' 100%                            
> Failed to generate snap metadata: 'adopt-info' refers to part 'jabref', but that part is lacking the 'parse-info' property.
> Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
> Error: The process '/usr/bin/sg' failed with exit code 2

https://forum.snapcraft.io/t/failed-to-generate-snap-metadata-adopt-info-refers-to-part-synfig-studio-but-that-part-is-lacking-the-parse-info-property/18733/11
https://github.com/JabRef/jabref/runs/1262693776?check_suite_focus=true

**Comment by LyzardKing** [comment]
I'll look into it.
I think it's mostly an temporary issue in build.snapcraft.io, because nothing changed on our part..
I'll test locally and see if we can override the setting.

**Comment by LyzardKing** [comment]
The version is pulled form the JabRef.cfg file included in the tar file,
but the version string is missing from that file now..

**Comment by Siedlerchr** [comment]
@LyzardKing  Thanks for the investigation. No idea wh the file is missing. Maybe jpackage no longer includes it in jdk15.
 you can use the "snapcraft"  branch https://github.com/JabRef/jabref/tree/snapcraft for your changes. for testing because otherwise the snap build won't be triggered

**Comment by LyzardKing** [comment]
I'm running tests locally, when i have something proper I'll upload to that branch then

**Comment by LyzardKing** [comment]
Why does `git describe` return `v_2.9.2-12400-gaf203b655`?
If I add `--tags` I get the correct version (`v5.1-191-gaf203b655`)

**Comment by Siedlerchr** [comment]
They changed something. I see that there is a hidden .jpackage.xml file in the app/lib folder 
```
<?xml version="1.0" ?>
<jpackage-state version="15" platform="linux">
  <app-version>5.2.189</app-version>
  <main-launcher>JabRef</main-launcher></jpackage-state>
```

**Comment by LyzardKing** [comment]
I set it to read from there.
The tag issue is something related to how the tags are built on github, not a jpackage thing.

**Comment by LyzardKing** [comment]
I uploaded to the snapcraft branch.. should I open a PR or can we merge directly from there?

**Comment by Siedlerchr** [comment]
You can open a PR, makes it easier to see the actions. 
I also wanted to try if the cfg is correclty generated when I put the                     '--app-version', "${project.version}",
to the image options.

**Comment by LyzardKing** [comment]
(on a different note.. could you bump the 5.1 release to stable in the snap store?

**Comment by Siedlerchr** [comment]
I promoted it to candidate and stable now. It was beta previously
