### ISSUE TITLE
Hyphen introduced by key generation is removed

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#7035]
JabRef 5.2--2020-10-20--4cf2fb0
Linux 5.4.19-050419-generic amd64 
Java 15

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In Settings -> citation key generator, the characters "-`ʹ:!;?^+" are removed by default.
If you use the default pattern "[auth][year]-[shorttitle]", the hyphen gets removed, which seems to be a new and at least for me undesired behaviour.

Steps to reproduce the behaviour:
1. Use default pattern as described above.
2. Generate a key for a bib entry
3. There will be no hyphen as part of the key.

Solution(s): remove the hyphen from the character set or apply replacement before key generation.

**Comment by Siedlerchr** [comment]
I don't remember exactly why, but we had a long discussion somewhere about this and the list of unwanted characters which we decided to make user configurable and to include the hypen. I think a hypen can produce weird results when you ave authors which already have a hypen in their name, e.g. Jean-Baptiste
 Therefore, I see not an issue here.  It has also been recently documented in our help page.

**Comment by ytzemih** [comment]
Ah, I see. The proposed fix is straightforward, anyway. Thanks!
