### ISSUE TITLE
New Entry from Plain Text not working

### ISSUE THREAD

**Issue by humbleambition** [JabRef/jabref#7038]
Cntrl+Shft+N for "New Entry from Plain Text" always results in:
"0 entries were parsed from your query"

![image](https://user-images.githubusercontent.com/64739261/97085245-b2257400-15f2-11eb-9899-1f4e84653450.png)

**Comment by humbleambition** [comment]
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

**Comment by humbleambition** [comment]
Updated to newer version:
JabRef 5.2--2020-10-24--2555b2d
Windows 10 10.0 amd64 
Java 14.0.2

Now an attempt to part plain text reference produces this error:
"There are connnection issues with a JabRef server. Detailed information: connection timed out"
![image](https://user-images.githubusercontent.com/64739261/97091408-228fbd80-1612-11eb-87cc-13246912ee34.png)

**Comment by ilippert** [comment]
I had the same experience a few days ago

**Comment by cnmicha** [comment]
Same issue here

**Comment by cmosek** [comment]
Happened to me as well, it seems that JabRef is trying to connect to 131.159.24.23 (one63.cm.in.tum.de) on port tcp/8070

**Comment by cnmicha** [comment]
@cmosek I notified the server owner via email.

**Comment by Ryyyc** [comment]
I randomly selected a test—— “Assigned numbers,” Request for Comments, no. 1010. RFC Editor, May 1987, doi: 10.17487/RFC1010.

![ok](https://user-images.githubusercontent.com/47767371/117316743-72054f00-aebb-11eb-9deb-dd3787ade245.png)

Now jabref is working. Maybe this issue can be closed. @Siedlerchr

**Comment by Siedlerchr** [comment]
Our GrobidServer was down, we restarted/fixed it
