### ISSUE TITLE
Don't remove any field automatically

### ISSUE THREAD

**Issue by Infovarius** [JabRef/jabref#7048]
JabRef version JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2 on Windows 10

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I use "review" field for my own reviews of read article, and "comment" field for any auxilliary information (about other versions, possibility to find a source text and so on). So I need both fields and they have different semantics to me. In the newest version of JabRef I can't save bib-file with preserving both fields (they are merged automatically). The same situation was with some other fields (e.g. merged into "file" field). My plea is to make such conversion opt-in, or at least opt-out.

1. To have bib-file with both "comment" and "review" fields.
2. To open this file.
3. To click cancel when popup "Do you want to merge comment and review?"
4. To save this file.

**Comment by Siedlerchr** [comment]
Hi, if I remember correctly review and comment have been merged together since 4.x.
For your use case I would propose to define a new general field with another name
