### ISSUE TITLE
Keyword separator

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#705]
It is possible to specify keyword separator for the automatically generated groups. However, the methods in BibEntry assumes that "," is used.

If we should keep the possibility to specify keywords separator, it should be used consistently and probably not be specified in the Groups preference tab. Biblatex specify "," as the default separator.

**Comment by simonharrer** [comment]
Good point.

**Comment by oscargus** [comment]
I tried to implement it and it turns out that automatic keyword grouping can be done for any field, not just the `keywords` field. Is it worthwhile keeping this? (Most definitely someone have defined their own magic fields...)

**Comment by koppor** [comment]
Preference setting:

![grabbed_20160126-163648](https://cloud.githubusercontent.com/assets/1366654/12585148/01c9868a-c44b-11e5-9ce8-3bd02306a26a.png)

`net.sf.jabref.model.entry.EntryUtil.getSeparatedKeywords(String)`  uses `net.sf.jabref.model.entry.EntryUtil.SEPARATING_CHARS_NOSPACE`. `net.sf.jabref.model.entry.BibEntry.putKeywords(List<String>)` always uses `,`. Therefore, I would also vote to remove that configuration option and double check whether the group logic can use `EntryUtil.getSeparatedKeywords(String)`, too.

Regarding `keywords` vs. other field names. The usecase is that the a user wants too keep the keywords retrieved from an external database separate from his own keywords. And therefore, he uses a new field `labels` (or similar).

**Comment by oscargus** [comment]
I realize that #719 is not completely done yet as `getSeparatedKeywords(String)` is not changed. The group logic can use these methods, but the undo requires a bit of additional thinking...

**Comment by koppor** [comment]
Regarding undo/redo: I think, it is OK if we don't care in this case.

**Comment by ambro2** [comment]
I had frustrating experiences in trying to use the dynamic groups functionality because of the comma as a keyword separator. In chemistry it not unusual to find keywords containing commas, like "1,2-diol" or "1,3-dipolar cycloaddition" or "α,β-unsaturated carbonyl".
Actually the keyword separator is the group of characters "," and " ". Indeed on importing from a RIS file, the keywords are combined in the bibtex "keywords" field, separated by ", ".
I could not find a way to tell JabRef to consider a _comma not followed by a space_ as part of the keyword.
Maybe there are users who managed to set a different keyword separator (semicolon, pipe or other character) and have their "chemical" keywords handled correctly. I gave up.

**Comment by koppor** [comment]
This could be implemented quickly. I'm unsure whether we should make that configurable. I don't know how many users use Kommas without space as keyword separator. Implementing some intelligence there is not worth doing as it probably will be confusing. Intelligence would be: If there are commas followed by a space in the string, use comma with space as separator. If there is not, use comma without space.

**Comment by davidcbenson** [comment]
So I'm an outlier here. most likely, but I follow many libraries practice on keywords, in that multiple keywords are grouped together, with increasing specificity, and each grouping is separated by a comma. So for example, a book on China might have the following keywords:

> China, government, CCP
> China, government, dissent
> China, society, workers
> China, language, mandarin

Such a categorization is very helpful when searching for overlapping topics, and this is why LOC uses it. If a comma is enforced as a keyword separator, I suddenly have four entries of "China" and two of "Governement". More importantly there is no way for me to search for the entries that "China, government" and "United States, media, television" for instances that talk about US media and the Chinese government without also getting things about the U.S. government or Chinese television.

Also, I was under the impression that you could enter keywords on separate lines, and then JabRef would automatically enter the separator in the bib file. If that is what is supposed to happen, it isn't, and if it isn't what is supposed to happen, it would make it easier to read the keywords.

**Comment by tobiasdiez** [comment]
Keyword separator was unified in #1950.
