### ISSUE TITLE
Programm on second screen, popup on first screen.

### ISSUE THREAD

**Issue by Xethy** [JabRef/jabref#7052]
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

 on 

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Inconvenience Problem; programm on second screen, popup on first screen. 

![Error](https://user-images.githubusercontent.com/73614306/97492365-b986ad80-1963-11eb-8310-0b5bc7797c3a.png)

1. Put Jabref on screen 2 (Windows 10, Screen with number 2)
2. Make an Article as entrytype and add any title name. 
3. Mark all the Name youve typed and rightclick
4. Popup with options on the first Screen.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks for the report. Could you please test the latest development version? We switched to javafx 15 and maybe that issue is no longer present?
Otherwise I only found this old Java issue which is marked as resolved
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8160073

**Comment by crystalfp** [comment]
In almost latest version it does not happen anymore.
JabRef 5.2--2020-10-15--13a80ba
Windows 10 10.0 amd64 
Java 14.0.2
