### ISSUE TITLE
Free search expression in groups sets icon and color to default

### ISSUE THREAD

**Issue by manurare** [JabRef/jabref#7054]
JabRef 5.1--2020-08-30--e023aa0 Ubuntu 20.04

- I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

No matter the free expression I input into a particular group. Every time I restart the program the group's icon and color are set to the default gray and triangle. 

An example would be: If I want to check whether readstatus or keyword do not contain "read" then,
`keywords|readstatus!="read"`

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Isn't it the same issue as #6999?

**Comment by manurare** [comment]
Yes my bad did not see it. I close it now
