### ISSUE TITLE
Make bibtex and biblatex mode file-based

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#706]
- [x] bibtex/biblatex mode is stored in the file; if it is not available, we detect (BibDatabaseTypeDetection) it and the store it
- [ ] Remove BIBTEX_MODE from preferences as it is now file-based
- [ ] File -> New must be replaced by File -> New BibTeX and File -> New BibLaTeX
- [ ]  Where can it be switched: right-click on tab
- [x] under File -> ..., (to database separator)
- [ ] Problem: Bibtex -> New entry ...; change entry types in field editor, entry editor, ...

- [ ] menu items should adapt automatically based on currently selected tab

**Comment by tobiasdiez** [comment]
I would (also) put the switch in the Database Properties dialog.
