### ISSUE TITLE
The entry preview window does not load my customized visual theme 

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#7068]
JabRef 5.2--2020-10-15--13a80ba
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The entry preview window does not load my customized visual theme as the rest of the GUI. I loaded my customized visual theme (copy of the source `Dark.css` file) but was not able to change colors of the preview textarea to match the dark theme of the rest of the GUI. Instead selecting "Dark theme" from Options > Appearance correctly makes the background dark.

![image](https://user-images.githubusercontent.com/865866/97967068-01229480-1dbd-11eb-8699-58a3d43e5549.png)

1. From the source tree take the `Dark.css` file
2. Open Options > Appearance and select this file as "Custom theme"
3. Restart JabRef and double click on an entry. The preview textarea has a white background
4. If you select instead "Dark theme" the background is correctly dark.

I suspect the problem is in file: `jabref-master\src\main\java\org\jabref\gui\preview\PreviewViewer.java` where I don’t see any reference to theme in JS_HIGHLIGHT_FUNCTION definition or in setPreviewText() function, so the `#previewBody` block in `Dark.css` has no effect.

**Comment by Siedlerchr** [comment]
The file is right, but the highlight function is only used for highlighting search results in the preview.
The real problem lies here:
https://github.com/JabRef/jabref/blob/6dec1747d8a1c89f6c62fc1d1939d88411f17eba/src/main/java/org/jabref/gui/preview/PreviewViewer.java#L119-L129

**Comment by crystalfp** [comment]
Maybe simply adding a toggle "The custom theme is a dark theme" to pass the test `if (theme.getType() == Theme.Type.DARK) {` is sufficient.

**Comment by Siedlerchr** [comment]
I would just change the condition and replace it with != Theme.Type.LIGHT

**Comment by crystalfp** [comment]
Eagerly waiting for this change. Thanks!
