### ISSUE TITLE
Adjusting the Preview Box

### ISSUE THREAD

**Issue by AtrusRiven** [JabRef/jabref#7074]
How is it possible to change the content displayed in the preview box?

In my use case, I have a custom field `Own_citation` where I manually insert the citation of the entry in my very own citation style. I don’t use any automated referencing but copy this citation manually into my texts. I’d like to display this custom field in the preview area, for example, between the regular metadata (`author`, `title`,...) and the abstract. Is it possible to adjust that?

Thanks a lot!

**Comment by Siedlerchr** [comment]
Yes. See the help. 
https://docs.jabref.org/setup/preview
You can edit that in the Preferences - > preview.
You can display any field using the same syntax as for other fields. 
Please ask  questions in our forum the next time. http://discourse.jabref.org/
The github issue tracker is primarily used for managing bugs

**Comment by AtrusRiven** [comment]
Thanks for the help. Sorry for overseeing this. Obviously doesn't work before #6447 is fixed.

**Comment by Siedlerchr** [comment]
Thanks for pointing out that issue #6447, thought it had been fixed already
