### ISSUE TITLE
Doesn't build on Linux--- Gradle problems

### ISSUE THREAD

**Issue by Tafnab** [JabRef/jabref#7080]
JabRef version master -->

- [ X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

PLEASE DOWNLOAD a clean version of any Linux distro and see if you can build your package. I bet you can't.

The following build error occurs on multiple distros:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
I don't have Gradle 7.0 on my system.

I believe version 7.0 is YOUR version of Gradle. My gradle versions are 4, 5, and 6. Is there some quick fix? Is your script downloading the latest gradle which has broken the build?

1. ...clone repo at https://github.com/JabRef/jabref
2. ... gradlew build
3. ... one task fails: Task :generateBstGrammarSource FAILED
4. Fails exactly the same way on Debian-based & latest OpenSuse Tumbleweed
5. Github tests are passing, but JabRef doesn't build
6. If these aren't the correct steps to build, perhaps you can suggest some. You didn't include any build instructions. I'm guessing based on other projects what the proper steps are.

<details>
  <summary>Log File</summary>
  ``

  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
No, gradle 7 is incorrect. You need to use the provided gradle wrapper version.
./gradlew build

**Comment by Tafnab** [comment]
> No, gradle 7 is incorrect. You need to use the provided gradle wrapper version.
> ./gradlew build
> 
> The deprecated gradle features is just a warning.
> https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace
>
>No, gradle 7 is incorrect. You need to use the provided gradle wrapper version.
>./gradlew build
>
>The deprecated gradle features is just a warning.
>https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace

The result of your instructions:
`$ ./gradlew build

> Task :buildSrc:compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/jim/.gradle/wrapper/dists/gradle-6.3-bin/8tpu6egwsccjzp10c1jckl0rx/gradle-6.3/lib/groovy-all-1.3-2.5.10.jar) to method java.util.AbstractCollection.hugeCapacity(int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Configure project :
Project : => 'org.jabref' Java module

> Task :compileJava FAILED
...[SNIP]...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 14' using tool chain: 'JDK 11 (11)'.


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
7 actionable tasks: 7 executed
`

Glad to see your project is still in business, but I'm telling you there is a serious problem. Following these instructions a second time is not likely to improve the situation.

I think what's going on is that you can't compile on Linux using OpenJDK. Is that right? JavaFX appears to only be available from Oracle. I already have two Java environments, plus 3 Gradles. I haven't really been keeping count. Isn't Oracle clamping down on users somehow? I hesitate to deal with those people.

By contrast, Zotero built perfectly the first time using the instructions they provided. It's not as good as JabRef, but I can at least fix the things I want to fix.

**Comment by Siedlerchr** [comment]
Are you able to read or are you just stupid? Because all others are able to read the guide.
tip: there is a section prerequisites.
GO,RTFM
