### ISSUE TITLE
How to configure Vim server on mac system

### ISSUE THREAD

**Issue by zalois** [JabRef/jabref#7081]
<img width="422" alt="Screen Shot 2020-11-07 at 1 18 14 PM" src="https://user-images.githubusercontent.com/9462454/98433245-410cb300-2100-11eb-8d5c-9bb7c655f47c.png">
Thanks!
I don't know how to configure vim server on mac system. 
My vim is brew macVim.

**Comment by Siedlerchr** [comment]
Pleas ask such questions in our support forum. https://discourse.jabref.org/
