### ISSUE TITLE
Improvements for the Entry Preview

### ISSUE THREAD

**Issue by AtrusRiven** [JabRef/jabref#7083]
The preview does not differentiate between different entry types. Of course, there’s the possiblity to display the entries in a certain citation style that employs this differentiation, but in my opinion, the preview display should be independent from the citation styles. No differentiating between entry types, thus, results in an ambiguous display in some cases, crossing the metadata’s logical order, for example with `InCollection`:
![preview](https://user-images.githubusercontent.com/29101440/98445634-f0558400-2118-11eb-9fc2-c9bd0df54d27.png)
With the sequence:
1. Author
2. Editor
3. Title (< Author)
4. Booktitle (< Editor)

The preview should be _conditional_ upon the entry type, so that in this example the sequence would be:
1. Author
2. Title (< Author)
3. Editor
4. Booktitle (< Editor)

In general, the logical order should differentiate between the containing and the contained bibliographical element. Thus, this new logical order would be (the following covers the most important entry types and doesn’t claim completeness):

| `entrytype` | logical order of metadata elements |
| --- | --- |
| `Book` | 1. Author<br>2. Title<br>3. Year |
| `Collection` | 1. Editor (Ed.)<br>2. Title<br>3. Year |
| `Article` and `InCollection` | 1. Author<br>2. Title<br>3. Year<br><br>4. Editor (Ed.)<br>5. Booktitle |

Moreover, the preview could be more complete and well-arranged in displaying the entry’s metadata, for example:
![preview_new](https://user-images.githubusercontent.com/29101440/98445799-eed88b80-2119-11eb-8dd3-0b7dbb3c1eb3.png)

Would it be possible to substitute the default preview style with something like this ([code for this preview styling](https://github.com/JabRef/jabref/files/5505109/entry-preview.txt))?

**Comment by koppor** [comment]
When using citation styles, you get the style-dependend preview for free (no documentation for JabRef existing yet --> https://docs.jabref.org/collaborative-work/export/customexports). We know that not all fields are available there.

Future work: 

- Add a `.jabref` folder in the $HOME directory, where `preview.txt` can be put (instead of the preferences, which have a character limit)
- Maybe switch our complete preview style language: https://github.com/koppor/jabref/issues/392

**Comment by AtrusRiven** [comment]
Thanks for the quick reply!

My idea was to make the default preview (which already is independent from citation styles) more suitable without the necessity to adjust the citation style for the adjustments of these styles are non-trivial if you want to have them to be really consistent. A complete and consistent preview by default could help a lot, especially to those who do not work with automated citation styles. For example, in the historic or "classic" humanities there are way to many special cases and exceptions when it comes to older literature.

**Comment by koppor** [comment]
I have to think how to include localization in the preview

```
IfPlural(Hgg.,Hg.)
```

Think, in English, this is `Eds.,Ed.`.

**Comment by AtrusRiven** [comment]
> 
> 
> I have to think how to include localization in the preview
> 
> ```
> IfPlural(Hgg.,Hg.)
> ```
> 
> Think, in English, this is `Eds.,Ed.`.

Localization wouldn't be the priority in my opinion (even though very useful). We could just include `Eds.,Ed.`, and everyone could make his own localization if preferred (in case implementation of localization might be relatively too laborious).

**Comment by AtrusRiven** [comment]
Made some improvements for the entry preview that should be more entry type sensitive.
