### ISSUE TITLE
arXiv paper download & library update

### ISSUE THREAD

**Issue by nicoborghi** [JabRef/jabref#7100]
It would be very helpful if it was possible to:

1. **Directly download an arXiv paper** instead of the link to the online version (see Figs.).
2. **Scan the whole library to check if new versions of the arXiv (or similars) papers are available**, and eventually download them. In the case of arXiv you could use the url and check if `https://arxiv.org/abs/...v2 `  does exist.

Alternatively, if it's preferable to avoid the direct download of the .pdf, you could add a `Batch download/update .pdf` tool.

![image](https://user-images.githubusercontent.com/27552035/99195377-8b87d280-2785-11eb-877f-56b5d24af514.png)
![image](https://user-images.githubusercontent.com/27552035/99195395-a8240a80-2785-11eb-92b0-95702055d51e.png)

**Comment by Ryyyc** [comment]
I tested it in the latest version of JabRef. Now JabRef will automatically download the V2 version if it exists.
It seems that this issue has been solved, maybe this issue can be closed. @Siedlerchr
