### ISSUE TITLE
Can't find (writable) JabRef.cfg when installing via snap

### ISSUE THREAD

**Issue by khatchad** [JabRef/jabref#7106]
I installed JabRef version 5.0.44 on Ubuntu 20.10 and ran into [this issue](https://github.com/JabRef/jabref/issues/6086#issuecomment-596536235), for which I am trying to apply the suggested fix. However, I cannot find a *writable* `JabRef.cfg` using `snap` to install `JabRef`.

**Comment by khatchad** [comment]
Updated to say *writable*. Even root cannot edit snap files.

**Comment by Siedlerchr** [comment]
It turns out it's a security measure and that's on purpose.
https://askubuntu.com/a/919098
You can however install the deb version from here https://www.fosshub.com/JabRef.html 
5.1 is the latest release.
The deb is self containing as well, e.g. it includes the necessary java runtime etc.

**Comment by khatchad** [comment]
Yes, that's what I have done. But, snap also has its own user directory under `$HOME/snap`. Would it be possible to place the configuration file there?

**Comment by Siedlerchr** [comment]
@LyzardKing any idea?
