### ISSUE TITLE
Document Viewer do not show all pages

### ISSUE THREAD

**Issue by syhue** [JabRef/jabref#7108]
The document viewer started with the second page instead of the first page.

[https://discourse.jabref.org/t/document-viewer-do-not-show-all-pages/2421](Link)

**Comment by Siedlerchr** [comment]
Yep, I could confirm this in the 5.2-dev.
The page iterating happens here:
https://github.com/JabRef/jabref/blob/8777c16a99bd83e4a30ddafc859c0c2208b68733/src/main/java/org/jabref/gui/documentviewer/PdfDocumentViewModel.java#L22-L31

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
