### ISSUE TITLE
JabRef freezes (Linux)

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7110]
JabRef 5.2--2020-11-17--a335f0d
Linux 5.9.8-200.fc33.x86_64 amd64 
Java 15.0.1

Across about 24h of working with this version, JabRef reliably crashes every time. I have not detected any pattern yet, no error messages. I run this version on Fedora 33. How about you, @sambo57u?

**Comment by sambo57u** [comment]
I have not recently but I only use it as a bib file for latex and not extensively. It used to freeze when I was trying to import into the current library in the past but recently it has been working.

**Comment by Siedlerchr** [comment]
There are only known issues regarding search when autocomplete is enabled

**Comment by ilippert** [comment]
Ok, haven't experienced freezing anymore for a few days now.
