### ISSUE TITLE
Check Status of "case sensitivity" and "regular expression" in Search Field not identifiable

### ISSUE THREAD

**Issue by AtrusRiven** [JabRef/jabref#7123]
In the search field, it is no longer possible to uncheck `regular expression` and `Case sensitive`.

> `JabRef 5.2--2020-11-23--350ec1f`
> `Windows 10 10.0 amd64 `
> `Java 14.0.2`

**Comment by AtrusRiven** [comment]
Interesting. It still works but only if the software already has found something. I didn't find anything so tried to change case sensitivity but nothing happened. With a search that actually finds something the settings work.

**Comment by AtrusRiven** [comment]
I suppose the problem for me lies in the fact that it is not identifiable in the search field if the two settings are checked or unchecked. Is it possible to change that? At the moment, the symbols are permanently white.

**Comment by Siedlerchr** [comment]
You may want to check the css. Maybe some css definitions missing for the search buttons. 

The GUI for the search is defined here
 https://github.com/JabRef/jabref/blob/4cf2fb06d3d876d2043f65ca0e51c3c4185fd05c/src/main/java/org/jabref/gui/search/GlobalSearchBar.java

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Do they show up when you click in the search field?

The current `visibleProperty()` bindings looks strange to me when the search field is not selected.

E.g., 
<img width="375" alt="Skärmavbild 2020-11-24 kl  14 21 53" src="https://user-images.githubusercontent.com/2598631/100141450-746d7280-2e60-11eb-860a-aae78147cdf7.png">

**Comment by AtrusRiven** [comment]
Can't see the icons either, when the search bar isn't selected.

@Siedlerchr : Perhaps a short hint where to look in order to figure out what to adress in the CSS (sorry for not having an expertise in Java :-) ) Thanks!

**Comment by Siedlerchr** [comment]
No problem, the search field buttons are defined here . Glyph icon refer to the icon on the button. 
https://github.com/JabRef/jabref/blob/0412684218478d90e0a41d2a3c4be0a84af2793c/src/main/java/org/jabref/gui/Base.css#L922

**Comment by DominikVoigt** [comment]
I do not quite grasp the issue?
Do you want to see the regex and case sensitive search buttons when the search bar is not focused?

**Comment by AtrusRiven** [comment]
@Siedlerchr Thanks a lot!
@DominikVoigt Both. My problem is that the buttons do not indicate whether they are selected or not. The problem of @k3KAW8Pnf7mkmdSMPHz27 additionally is that the buttons are invisible when the bar is not focused.

**Comment by AtrusRiven** [comment]
I just realised that the toggle status is only with my custom dark theme undistinguishable. In light and normal dark theme it works (though it's only barely visible in normal dark theme). Therefore my problem is just a problem with something in my custom theme. Have to figure out what went wrong. Thanks for your help!

**Comment by Siedlerchr** [comment]
@AtrusRiven  It might be the same problem as  #6791 which also  about the dark theme having that issue

**Comment by AtrusRiven** [comment]
Yes, your're right, that's the same. Thanks. I'll comment there.
