### ISSUE TITLE
Any regex in citation key generator produces empty field

### ISSUE THREAD

**Issue by Linguista** [JabRef/jabref#7128]
JabRef version 5.1 on Kubuntu 20.04

Any use of a regex in Options > Preferences > Citation key generator > Key Patterns > Key Pattern produces an empty field.

1. Start with any key pattern, e.g.` [authEtAl][year][shorttitle:capitalize`]
2. Add a regex to a field, e.g. `[authEtAl][year][shorttitle:capitalize:regex("Del", "")]`
3. Hit enter, save preferences.
4. Open a bibliographic entry.
5. Hit the Generate button.

In this case, the generated field consists only of `authEtAl` and `year`. `shorttitle` is empty.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hi @Linguista, I am not completely up to date on my JabRef version knowledge. There were an earlier version with a bug in the regex modifier that occurred with space after `,` and the empty replacement ``. Could you try `regex("Del","_")` instead?

**Comment by Linguista** [comment]
> Hi @Linguista, There were an earlier version with a bug in the regex modifier that occurred with space after `,` and the empty replacement `""`. Could you try `regex("Del","_")` instead?

Thanks very much -- you hit the nail on the head. Both the space between the regex fields and an empty replacement string break the citation generation on any field that has them. I can avoid the space, but adding garbage strings to citation keys obviously isn't idea. I'll check out the dev builds.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> but adding garbage strings to citation keys obviously isn't idea.

While not ideal, if you are worried about using the dev version you can use the "Replace (regular expression)" feature to later remove the garbage string.

> Nor does the escaped version, `\\W`. Is this wrong, or is this a bug?

`\\W` appears to works for me. Could you give an example of what you are using it for? I'd not expect to use it for that purpose. Does something along the lines of `(\\bword\\b)` work? (example is from https://www.regular-expressions.info/wordboundaries.html)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> there seems to be no way to add stop/function words to the built-in English-only list of them that JabRef comes with.

I don't think there is, but it could perhaps be an idea for a new issue with this as a feature request? (I have never used JabRef for non-english citations, I don't know how useful this is to others)

**Comment by Linguista** [comment]
> > Nor does the escaped version, `\\W`. Is this wrong, or is this a bug?
> 
> `\\W` appears to works for me. Could you give an example of how you are using it?
> I'd not expect it to be used it for that purpose. Does something along the lines of `(\\bword\\b)` work? 

Yes! `\\b" is exactly what I needed... with one addition. I'm searching on lowercase words but I had the `capitalize` command right before it, which was making everything fail!

Duh!

Thanks so much for your help.

**Comment by Siedlerchr** [comment]
So if I understood this correctly, this issue is solved in the latest development version and you also have a custom solution.
