### ISSUE TITLE
Shared database: Additional phantom entry when adding an entry in a subgroup

### ISSUE THREAD

**Issue by m-mauersberger** [JabRef/jabref#7159]
JabRef 5.2--2020-12-03--a06f2e0
Linux 4.12.14-lp151.28.83-default amd64 
Java 15.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists.

1. Open a(n empty) shared database.
2. Add some entries to "All entries". Works fine.
3. Add a subgroup S1.
4. Add an entry to subgroup S1. Two entries will appear in entry list. Both are somehow "linked" to each other.
5. Change one of the two new entries in the subgroup. The entry conflict window (like with concurrent access) pops up. So it seems like both entries are actually the same entry.
6. Reload the database. Previously added Entries under "All entries" disappeared. Phantom entries disappeared as well. 

It seems like a problem with proper synchronization. I had encountered a similar problem when I interchanged lines 83 and 84 in `DBMSSynchronizer.java`:
line 83: `synchronizeLocalDatabase();`
line 84: `dbmsProcessor.insertEntries(event.getBibEntries());`

Maybe there lies a part of the problem?

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thanks for your investigation, I will try to look into that as well.

**Comment by m-mauersberger** [comment]
I could still reproduce the issue with

JabRef 5.3--2021-06-07--62969da
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8

But now it appears only from the second new entry in subgroup S1 (first new entry works fine).

**Comment by m-mauersberger** [comment]
With the new development version (JabRef 5.8--2022-12-08--8ebdb52) the issue seems to be fixed. Thank you for your help!
