### ISSUE TITLE
mathesis type option should not include curly braces

### ISSUE THREAD

**Issue by khatchad** [JabRef/jabref#7169]
## Version
JabRef 5.1--2020-08-30--e023aa0
Linux 5.8.0-29-generic amd64 
Java 14.0.2

## Steps to reproduce the behavior
1. Create a `@MastersThesis` entry
2. Select type as "mathesis" under the optional fields UI.

## Expected outcome
In the bibtex source: `type = mathesis,`

## Actual outcome
In the bibtex source: `type = {mathesis},`

**Comment by koppor** [comment]
## Context

![grafik](https://user-images.githubusercontent.com/1366654/101401948-5c233c00-38d3-11eb-8795-8567f85705d2.png)

## Comment

We read the BibLaTeX manual. Somehow, there is the type defined. I did not knew that at all. Think, we should remove that field. Refs https://github.com/JabRef/jabref/issues/6856

The default is that you do not need to set it manually. Please leave the field alone. ^^

Typically, one DOES NOT need to provide an additoinal `type` field. The `@MasterThesis` already provides the type. Thus, following entry is OK:

```bibtex
@Masterthesis{key,
  author = {Aline Jasmin},
  title = {My title}
}
```
  
Yours reads

```bibtex
@Masterthesis{key,
  author = {Aline Jasmin},
  title = {My title},
  type = mathesis
}
```

which is double information. See https://latextemplates.github.io/scientific-thesis-template/ for a full latex example without any `type` field.

## Information Gathering

Can you please provide us more background to your bibtex / biblatex setup? I read the string `mathesis` (see JabRef support at https://docs.jabref.org/advanced/strings) the first time. 

Is it really supported as default in BibTeX? Meaning that BibTeX internally defines `mathesis`?

Which bibtex style do you use? Does that style possibly define `mathesis`?

**Comment by khatchad** [comment]
I am using the `moderncv` class for my resume. And, you are correct, if I remove the `type = mathesis`, I get the same results. It's redundant. I agree that it should be removed.

**Comment by khatchad** [comment]
Note though that the `type` field itself may be necessary for other entry kinds other than `@MastersThesis`, or there may be types other than `mathesis` that make sense for `@MastersThesis`. I have not checked these.

**Comment by Siedlerchr** [comment]
I think this issue can be closed, as the field type is not necessary, but it's still listed in the biblatex spec.

**Comment by koppor** [comment]
I put the "freeze" label on it as we should come back later this time. In case the field `type` really produces wrong BibTeX output, it should be fixed.

I marked the difference in the submitter's comment:

![grafik](https://user-images.githubusercontent.com/1366654/103246743-d3913c00-4964-11eb-9a9e-32dde38c6af5.png)

what to do:

1. Create a minimal MWE-bibtex including a `.tex` and a `.bib` file with `type` filled. One entry with `{}`,  the other one without
2. Create a minimal MWE-biblatex including a `.tex` and a `.bib` file with `type` filled. One entry with `{}`,  the other one without
3. Typeset the document
4. Check whether the ouptputs differ
5. Think why the outputs diffor (or not)
6. Take appropriate steps (JabRef code chaganges? Comment on this issue? Add a biblatex-to-bibtex migration deleting the `type` field? Add a clenaup deleting the `type` if it matches the entry type? Add a tooltip on the Type input at the entry editor?)
