### ISSUE TITLE
Automatically change dark/light theme according to system

### ISSUE THREAD

**Issue by xiajunwen1007** [JabRef/jabref#7184]
Is there an easy way to do this by custom theme？On web browser, I can use @media (prefers-color-scheme: dark) {} to do this. But it doesn’t  seem to work on jabref. 
  Thanks a lot for your working! Love this app so much!

**Comment by tobiasdiez** [comment]
For Swing applications, one could use `UIManager` to get the system color. But this information is sadly not available for JavaFX (the UI framework we use). So there is sadly nothing we can do right now. If you really want this feature, please open an issue at https://bugreport.java.com/bugreport/ requesting the ability to determine the system theme from JavaFX.
