### ISSUE TITLE
Messy code in Windows 10 20H2

### ISSUE THREAD

**Issue by ZanderChang** [JabRef/jabref#7190]
JabRef version 5.1 on Windows 10 20H2

I update my Windows 10 to 20H2 and everything becomes messy code, including title and text.

![2](https://user-images.githubusercontent.com/12554961/102048560-58833e00-3e1a-11eb-9fa8-9ff712a6610c.jpg)
![1](https://user-images.githubusercontent.com/12554961/102048563-5a4d0180-3e1a-11eb-8faf-d72719e771c6.jpg)

Please tell me how can i fix it?

**Comment by Siedlerchr** [comment]
Hi, as this seems to come from the windows update,  you can try to change the font setting in your windows regional settings.

**Comment by ZanderChang** [comment]
Well, it seems my Windows 10 Home only supports Simplified Chinese and 202H almost messes everything up. A macbook would be a better choice :).
