### ISSUE TITLE
Move file to file directory ceased working

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7194]
JabRef 5.2--2020-12-13--931c4cb
Linux 5.9.13-200.fc33.x86_64 amd64 
Java 15.0.1

I have attached files in the entry editor. I should be able to use the contextual menu to move the file into the "file directory". But that moving is disabled. I did not change my settings.

But note, drag&drop file on entry table line still works.

**Comment by gpeteinatos** [comment]
JabRef 5.2--2020-12-24--6a2a512
Linux 4.15.0-126-generic amd64 
Java 15.0.1

Same problem.

**Comment by ilippert** [comment]
still a problem in
JabRef 5.3--2020-12-28--020cc97
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1

@Siedlerchr, sorry I presume far too many issues are calling for attention. However, I allow myself to mention you here because I  think this issue should be given some priority because it affects file handling, which I presume to be quite key for users. Now that 5.2 is out (congratulations!), this issue might be considered as very relevant for a fix for 5.3.

**Comment by Siedlerchr** [comment]
Thanks for mentioning this issue. Slipped through the attention. Fortunately, it was only a simple issue. Fix is on it's way

**Comment by Siedlerchr** [comment]
This is now fixed in the latest master version.

**Comment by ilippert** [comment]
confirmed.
JabRef 5.3--2020-12-30--afdb194
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1
