### ISSUE TITLE
Unselect entries in the main table and opacity of disabled icon-buttons

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [JabRef/jabref#7195]
**Is your suggestion for improvement related to a problem? Please describe.**
1. At the moment you can't unselect bib entries in the main table. This is perhaps a useless feature but it is part of my "default behaviour". If I am editing a bib entry in a small library, and I want to close the entry tab I click on an empty row in the main table, and I expect the bib entry to be unselected and the entry tab to hide (since there is no longer a selected entry to edit). Am I the only one that repeatedly does this ? 😬 
2. On a related note, should disabled icon-buttons change opacity, e.g., if no bib entry is selected.

**Additional context**
Regarding disabled icon-buttons,
```css
.icon-button:disabled {
    -fx-opacity: 0.4;
}
```
Looks good to me.
<img width="367" alt="Skärmavbild 2020-12-15 kl  09 12 29" src="https://user-images.githubusercontent.com/2598631/102226012-dc3e3880-3eb5-11eb-8c93-eefb5f10b1b8.png">
vs
<img width="367" alt="Skärmavbild 2020-12-15 kl  09 12 33" src="https://user-images.githubusercontent.com/2598631/102225927-c16bc400-3eb5-11eb-9d9b-1b4943206f75.png">

**Comment by tobiasdiez** [comment]
I think both ideas are good. Would you mind creating PRs for them? (we already have ActionHelper.needsEntriesSelected so this should be straigthforward)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Great! 
I'll split it over two PRs. One dealing with the opacity/disabled, which should be finished quicker, and one trying to figure out when it is reasonable to "lose" a selection.

**Comment by JavuesZhang** [comment]
Hi! Does this issue still accept pull request?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@JavuesZhang, if it is still a problem in the latest version, yes. I unfortunately haven't had time to look at the issue.
