### ISSUE TITLE
Support "Push to" for VScode

### ISSUE THREAD

**Issue by el-paso** [JabRef/jabref#7196]
I really love JabRef. 
My Latex Workflow is based on VScode.
Please bring my two biggest love together.
That would make me happy and i will donate a chocolate with Baola!

![image](https://user-images.githubusercontent.com/34002966/102242118-01549a80-3efa-11eb-8983-0c47aac4d34d.png)

**Comment by el-paso** [comment]
Alternatively add an "Copy" Button under "Generate"
= Half of a Balboa chocolate
![image](https://user-images.githubusercontent.com/34002966/102242440-58f30600-3efa-11eb-8df2-ef1d180b450f.png)

**Comment by teertinker** [comment]
Hello,
alternatively you can select your entry and just copy your key with ctrl+shift+k

see:

![copybibkey](https://user-images.githubusercontent.com/8830305/102350898-e8092800-3fa5-11eb-8531-098c0917d063.gif)

**Comment by Siedlerchr** [comment]
See also: https://github.com/JabRef/jabref/issues/6775#issuecomment-678586218
It's a problem with VSCode
Closing this as Duplicate
