### ISSUE TITLE
Modify the "Directory not found" alert to show a more descriptive path 

### ISSUE THREAD

**Issue by JofielB** [JabRef/jabref#7197]
### Problem Description
When you try to download a pdf (`Lookup -> Search full documents online `) and you don't have a file directory set, an alert tells you that you should follow a path to set your file directory:` Preference -> File`. But that path is not correct because to set the file directory you need to follow this path: `Options -> Preference -> Linked Files -> Main File Directory`

### Suggested solution
Change the text in the alert to show a more descriptive path
Path suggested:  `Options -> Preference -> Linked Files -> Main File Directory`

### Additional context
How to make the alert to appear: `Lookup -> Search full documents online ` (Be sure that you don't have a file directory set)
![issue1](https://user-images.githubusercontent.com/32725639/102267344-fe947e00-3ed6-11eb-9374-69e5f9175883.png)
![issue2](https://user-images.githubusercontent.com/32725639/102267348-005e4180-3ed7-11eb-8305-1495482cd856.png)

If you follow the path that the alert suggests to set the file directory you will not find that option
![issue3](https://user-images.githubusercontent.com/32725639/102267352-018f6e80-3ed7-11eb-9db0-fc4183f565e2.png)

 You need to follow this path to change the file directory: `Options -> Preference -> Linked Files -> Main File Directory`
![issue4](https://user-images.githubusercontent.com/32725639/102267359-03593200-3ed7-11eb-8e0f-11995685db91.png)

**Comment by Siedlerchr** [comment]
Please be aware that a main file directory can be empty and you can add relative paths in the library properties. https://docs.jabref.org/setup/databaseproperties#override-default-file-directories

**Comment by devjuliet** [comment]
Is this up for grabs? I would like to contribute @Siedlerchr 😄

**Comment by Siedlerchr** [comment]
@devjuliet Welcome to JabRef, feel free to work on that issue!
see our contribution.md for getting started.
If you have any questions, just ask here or in our gitter channel
