### ISSUE TITLE
Chinese author of essay reference section displays extra space

### ISSUE THREAD

**Issue by xiaodongcentury** [JabRef/jabref#7199]
Hi, i am using JabRef (JabRef 5.2--2020-12-14--e9be339 Linux 5.9.0-4-amd64 amd64 Java 15.0.1) on Debian sid.

JabRef version  on 

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

After importing the Chinese essay, manually insert a space or comma, such as 杨 秀群, the citationkey will generate successfully, but the Reference section of essay will display "杨 秀群 "(there is a space between杨 and 秀群) , not "杨秀群".
How could you resolve this problem, thanks!

![image](https://user-images.githubusercontent.com/20276890/102434509-db410e80-404f-11eb-9dfd-b30176ad962b.png)
The JabRef screenshot.
![image](https://user-images.githubusercontent.com/20276890/102434584-00ce1800-4050-11eb-9154-5223bd731e88.png)
The corresponding pdf file screenshot.
And the bibliography file is 
![image](https://user-images.githubusercontent.com/20276890/102434748-573b5680-4050-11eb-93b6-219aee066216.png)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hi @xiaodongcentury! I just have some follow up questions,

> citationkey will generate successfully

You mean without space/comma?

> Reference section of essay will display

1. Do you mean the preview section in JabRef?
2. Do you mean the citation key?

> comma

Are you referring to an [ideographic comma](https://en.wiktionary.org/wiki/ideographic_comma)? Should it not be included?

**Comment by xiaodongcentury** [comment]
Thanks.
Without space/comma, the citationkey will not generate successfully. 
What i mean is for most Chinese article, the author name of reference section will be a whole, such as "杨秀群", but not "杨 秀群". For example:
![image](https://user-images.githubusercontent.com/20276890/102621902-3facbc80-417b-11eb-83d0-b6715445cc1b.png)

But now, I insert the citation item to a tex file from the JabRef, the pdf file generated will display"杨 秀群", but not "杨秀群", the former has a space between last name and first name of a Chinese name.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
If it is the author's name in the pdf file that has an extra space, I don't think there is anything you can do in JabRef. The reason why you need that space/comma in the authors' name field has to do with how BibTeX/biblatex handles name (there are a lot of post/discussions on the topic, e.g., https://nwalsh.com/tex/texhelp/bibtx-23.html) and cannot be changed by JabRef.

In theory the gb7714 package should deal with this situation correctly, but I can't find enough English documentation to say for sure. I'd recommend that you ask in a TeX/LaTeX/Biblatex forum regarding the usage of xeCJK/gb7714 because I am not familiar enough with their use to help you out =/

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
A potential workaround could be to remove the space after generating the key or to use a different citation key pattern but I'd guess that might lead to further issues later on.

**Comment by xiaodongcentury** [comment]
Thanks!
From the https://www.fosshub.com/JabRef-old.html, i download the jar file ([v5.0-alpha] JabRef Platform independent runnable JAR),
![image](https://user-images.githubusercontent.com/20276890/102679434-db294600-41ea-11eb-823e-4b2e15706725.png)
then open it.
Although there is no space/comma in Chinese author name, the citationkey is successfully generated, and the pdf file generated displays correctly according to gb7714-2015.
![image](https://user-images.githubusercontent.com/20276890/102679646-0b251900-41ec-11eb-8696-20da095577f7.png)
I just change "韦金育", but do not the other author names.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Good that you got it to work! In the interest of keeping it working for future releases, I hope you don't mind answering some further questions?

* You are using the default citation key pattern `[auth][year]`?
* The correct citation key should be `秀群2020` (**not** `杨秀群2020`)?
* When the citation key does not generate successfully, do you mean that the resulting key is `2020`?

**Comment by xiaodongcentury** [comment]
Thank you!
The old version ([v5.0-alpha] JabRef Platform independent runnable JAR) works, but not the newer master version (JabRef 5.2-1).
1. yes, i am using default citation key patter.
2. the citation key of old version is 杨秀群2020, and the pdf file generated displays correctly. While the mater version is 秀群2020, and the pdf file generated displays incorrectly.
3. If there is no space/comma between first name and last name of Chinese author in Required field, the resulting key is 2000, the [auth] doesn't display. If add a space/comma to author name, the resulting key is 秀群2020, but the generated pdf file displays" 杨 秀群", there is a space in the author, which is not correct according to gb7714-2015, in that Chinese author name has no space.

**Comment by tobiasdiez** [comment]
I did a bit of research, but it seems there is no agreed standard of how to put Chinese names in bibtex. By default the naming parsing of biblatex and JabRef assume that name parts are separated by space. Maybe the strategy outlined at
https://github.com/plk/biblatex/issues/416#issuecomment-738335693 works for you.

**Comment by xiaodongcentury** [comment]
Thanks!
But the older version ([v5.0-alpha] JabRef Platform independent runnable JAR) does works.
I'll check your solution whether it works.

**Comment by tobiasdiez** [comment]
We have improved the author parsing from 5.0 to 5.1, and made it align better with biblatex. So the reason why it works in the alpha is actually a bug that was fixed later (unfortunately it leads to problems for chinese names).

Another idea would be to put the name (or parts of it?) in braces, e.g. `{杨秀群}` or `杨{秀群}`. That's actually a syntax used for organizations (e.g. `{United Nations}`) but maybe it works for your case as well.

**Comment by xiaodongcentury** [comment]
Ah, that's a lot of work to do.
Anyway, thank you.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I don't have time to write a full answer to this right now but you both are right.
The handling was improved but there is a bug because the name in this specific instance is considered by Java to start with a lower case letter (and therefore gets removed).
I'll submit a PR for this and another issue in ≈ 8 hours.

**Comment by xiaodongcentury** [comment]
@k3KAW8Pnf7mkmdSMPHz27 Thanks

**Comment by xiaodongcentury** [comment]
@tobiasdiez it seems like the {} doesn't work, whether whole name or part of it.
![image](https://user-images.githubusercontent.com/20276890/102713849-e0c77e80-4305-11eb-8afc-1b04a02cbfb6.png)
The generated key only contain year, there is no author.

**Comment by tobiasdiez** [comment]
Thanks to @k3KAW8Pnf7mkmdSMPHz27  this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by xiaodongcentury** [comment]
Thank you ALL!
The JabRef 5.3--2020-12-28--78b08b5 works perfectly with Chinese names.
Thanks again.
And i believe this issue will be closed.
