### ISSUE TITLE
[authorsAlpha] uses full surname instead of 3 first letters

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#7201]
JabRef 5.1--ArchLinux--2
Linux 5.9.15-1-clear amd64 
Java 14.0.2

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Set Default pattern to [authorsAlpha:lower][year][shorttitleINI:lower]
2. Generate a key
3. Field `author = {John Downs},` produces the key `downs2017ato,`.
However, 

> [authorsAlpha]: Corresponds to the BibTeX style “alpha”,
> One author: First **three** letters of the last name

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
While I do not know what the correct output is for the BibTeX style "alpha", the latest development build produces "dow" for `author = {John Downs}` with citation pattern `[authorsAlpha:lower]`.

It is recommended that you backup your library before you try a development build!

**Comment by calixtus** [comment]
Devcall: Any update on the status here?

**Comment by calixtus** [comment]
We were not able to reproduce this issue.
Due to inactivity we are closing this issue now. If it wont work for you please leave a note here.
