### ISSUE TITLE
Add support to add an entry from zbmath.org via its zbMATH id

### ISSUE THREAD

**Issue by ibe-314** [JabRef/jabref#7202]
JabRef supports adding entries via different kind of ids (https://docs.jabref.org/collect/add-entry-using-an-id). Right now, it is not possible to add an entry from [zbmath.org](https://zbmath.org) via its zbMATH id, however it is possible to add entries by searching its database (https://docs.jabref.org/collect/import-using-online-bibliographic-database). 

I would like to implement the possibility to add entries directly via their zbMATH id. I think this can be done quite easily by adjusting the zbMATH-Fetcher. I think this would be interesting as zbmath will become open access from January 2021 and thus no subscribtion for it is needed anymore.

**Comment by Siedlerchr** [comment]
Welcome! I think this will be a really cool thing for JabRef to have.
For getting started check out our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) 
The existing zbMath fetcher is here https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/importer/fetcher/ZbMATH.java

You probably just need  to implement the IDBasedFetcher /IdBasedParserFetcher  interface to make it work.

**Comment by ibe-314** [comment]
Thank you for the information. I already had a look at the code and found the zbMath fetcher :-) I won't have that much time this year but I will work on the fetcher the first week of January.

**Comment by ibe-314** [comment]
Hi, 
I implemented the IdBasedParserFetcher interface for the zbmath fetcher and it worked on my Computer (with `gradlew run.`)
However, I have a problem testing jabref. Even on the master branch (without my changes) neither `gradlew test `nor `gradlew check` work. The "How to test" (https://devdocs.jabref.org/getting-into-the-code/testing) did not help me. What do I have to do in order to be able to test jabref?
Best
Isabel

**Comment by Siedlerchr** [comment]
Hi, it should be fine to just run the specific test for the fetcher from your IDE. 
The Github Actions automatically execute the tests when you create the PR, so you can see the results there
