### ISSUE TITLE
Unlinked files Importer: Continue (fall-through) when individual files fail to be processed

### ISSUE THREAD

**Issue by koobs** [JabRef/jabref#7206]
### **Is your suggestion for improvement related to a problem? Please describe.**

When a user is attempting to import a "not small" (>1) number of files and the import process is completely stopped due to a single or  small number of errors, the followings impacts present themselves:

  * The user is confused as to the state of the import, and library as a whole
  * The user must elect to either delete the successfully processed items from the library and start again, or identify the respective filenames from the next Scan/Import  cycle,  and exclude them. The impact is compounded because:
    1. the Import scan default selects **all folders/items** by default, AND
    2. The main window can **displays titles** (not filenames), and the Import dialog displays **filenames**, so they are difficult to match
  * While a traceback may be provided, it is difficult and time consuming to identify the respective source (file) of the error.
  * The failure of individual items should not affect or impact the ability to process other items.

Given arbitrary file processing can result in very many failures (and/or exceptions), Import file processing should not be fatal in these cases, and instead fall-through (skip and continue processing), notifying the user of the issue and ideally retaining the debug information (details of the issue), so that users can continue to report them.

### **Describe the solution you'd like**

- [ ] Change Import file processing to fall-through when unable to process a file, **AND**

Notify the user of files unable to be processed:

- [ ] Mark the file that fails to be processed in the Import dialog tree control (file child elements), **OR**
- [ ] Create an area in the Import dialog that can contain file processing information, that contains:
  - [ ] The full path of the filename with the issue, AND
  - [ ] The error message summary, AND
  - [ ] A `traceback` or `details` link or button to view the full traceback or log, **OR**
- [ ] Create a dedicated "Processing Import" dialog that creates an entry per item (which also facilitates a "visual progress mechanism, see: #7205 "add a visual progress mechanism to the Import dialog")

### **Additional context**

 * Related Issues: #7203 #7127 (and im sure many more)

**Comment by Siedlerchr** [comment]
I am currently reworking the dialog and I thought about marking/showing a similar dialog as in the copy files dialog (Tools -> Copy  linked files to folder)
<img width="856" alt="grafik" src="https://user-images.githubusercontent.com/320228/102863289-a7406180-4432-11eb-99c7-668b8f583be1.png">

**Comment by ThiloteE** [comment]
related discussion in the forum: https://discourse.jabref.org/t/unlinked-files-importer-fall-back-for-files-failed-to-be-processed/3066
