### ISSUE TITLE
Style of checkboxes while searching in preferences

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [JabRef/jabref#7226]
JabRef 5.2--2020-12-22--d83ef74
Mac OS X 10.15.7 x86_64 
Java 15.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When searching for an option in JabRef preferences, the checkbox has incorrect styling. The "unchecked" behaviour, while distinct from the "checked", is confusing since it still has a checkmark in it. This is a visual bug, the behaviour is still correct.

1. Open Preferences
2. Search for an option that uses checkbox (e.g. autosave)
3. Observe a checkbox highlighted in red, check/uncheck it

**Highlighted unchecked box**
<img width="901" alt="Highlighted unchecked box" src="https://user-images.githubusercontent.com/2598631/102887013-28442c80-4424-11eb-873f-c6538a11e83a.png">
**Highlighted checked box**
<img width="901" alt="Highlighted checked box" src="https://user-images.githubusercontent.com/2598631/102887023-2bd7b380-4424-11eb-9dde-b5747348c6f3.png">

**Comment by faeludire** [comment]
Hi, I would like to help contribute to fixing this issue. Thanks.

**Comment by Siedlerchr** [comment]
@faeludire  Welcome to JabRef. I suggest you take a look at the PreferencesSearchHandeler and the PreferencesDialog.css
You probably need to adjust the rule for the searchHighlight in the css or define a more specific one for checkboxes
The checkbox style schema is explained here: 
https://stackoverflow.com/a/44889214

**Comment by Siedlerchr** [comment]
Thanks to @faeludire  this is now fixed.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
It is appreciated @faeludire !
