### ISSUE TITLE
JabRef 5.2 cannot open document link

### ISSUE THREAD

**Issue by WangYuzhe** [JabRef/jabref#7236]
After I updated the Jabref to the newest version (JabRef 5.2--2020-12-24--6a2a512), it could not open the document through the file link. The open button F4 becomes gray now.

My OS is Windows 10.

**Comment by Siedlerchr** [comment]
Please check the settings, linked files, main file directory if it's set

**Comment by WangYuzhe** [comment]
Hi Christoph,
Thanks for your response. It now works after I set the linked file in the preferences setting.
