### ISSUE TITLE
Translation of Traditional Chinese

### ISSUE THREAD

**Issue by Hsins** [JabRef/jabref#7237]
I would like to translate the JabRef user interface into Traditional Chinese. Could you please add the new language on Crowdin for me?

I have tried to contact @koppor on Crowdin but don't get response.

**Comment by koppor** [comment]
We have four choices in crowdin for it

* Chinese Traditional
* Chinese Traditional, Hong Kong
* Chinese Traditional, Macau
* Chinese Traditional, Singapore

Which one should I configure?

**Comment by Siedlerchr** [comment]
I think we need to add the new language also to the jabref language enum

**Comment by Siedlerchr** [comment]
https://github.com/JabRef/jabref/blob/d83ef740486dc2f1b72f7e625ad2a22b019280de/src/main/java/org/jabref/logic/l10n/Language.java

**Comment by Siedlerchr** [comment]
@Hsins I added Traditional Chinese now as well to the user Interface language selector and configured the crowdin sync correctly. The next version will then contain this changes.
