### ISSUE TITLE
External files do not open anymore (Windows 10)

### ISSUE THREAD

**Issue by blubbrezn** [JabRef/jabref#7259]
JabRef 5.3--2020-12-28--c8798ef
Windows 10 10.0 amd64 
Java 14.0.2

I updated JabRef from an unknown version to 5.2, than the external file links in the entrys didn't work anymore.
When I click on them it just opens the default documents folder.
I tried update to the latest dev version (JabRef 5.3--2020-12-28--c8798ef) but the problem persisted.
It is exactly the same behaviour as in #6863.

Before the update the links in the same bib file worked. When I copy the path from the bibtex entry, the path is right.
I also tried set up a new .bib file, but the same.
When I hover over the file entry in the entry editor -> "General" pane, a tooltip appears with the text "Could not find file ...".

Steps to reproduce the behavior (copy from #6863):
1.  Create any bibliography entry
2. In the entry editor / "General" pane, click "+" icon on the right of the "File" field, and select a pdf file
    The file name appears in the "File" field, the "Open file" icon appears near the entry, but the corresponding functionality does not work as described above.

**Comment by Siedlerchr** [comment]
Hi, please check Preferences -> Linked files -> Main file directory This is probably not set

**Comment by blubbrezn** [comment]
> 
> 
> Hi, please check Preferences -> Linked files -> Main file directory This is probably not set

thanks this was the problem. I did look at this setting, but didn't set it, as all the files are not in the same directory and I use absolute paths to the files.
