### ISSUE TITLE
Missing Key Bindings

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#7264]
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64
Java 14.0.2

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

This issue is present on the v5.2 stable.

1. Open Edit > Read Status > ...
2. Open Options > Customize key binding > Edit
3. One cannot edit the key bindings present in the menu

It would be great if all the menu options could be bound to a keystroke combination

![image](https://user-images.githubusercontent.com/10846169/103234481-1260cb00-4940-11eb-90a1-e57ca9f32d04.png)
![image](https://user-images.githubusercontent.com/10846169/103234634-74213500-4940-11eb-8390-2f56318c326a.png)

**Comment by Siedlerchr** [comment]
Thanks to @Shadow-Devil  this is now implemented in the latest master. You can now define custom keybindings for these actions
