### ISSUE TITLE
Application Dialogs Open on Wrong Display

### ISSUE THREAD

**Issue by fullben** [JabRef/jabref#7272]
JabRef version 5.2 on Windows 10

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open JabRef on a system with at least two displays
2. Move the application main window to a non-primary display (as far as I can tell, JabRef always opens on the primary display on launch)
3. Perform an activity spawning a dialog (tested: *Help*->*About*, *New entry*, and a few others, but I'm suspecting that it works for all dialogs)
4. The dialog will always appear on the primary display, regardless of the position of the application main window (My suspicion is that the `initOwner(Window)` method is never called when initializing new dialogs. This usually results in the new window appearing on the display the application opened at startup.)

**Comment by Siedlerchr** [comment]
Thanks to @faeludire  this is now  fixed in the latest master version.
