### ISSUE TITLE
Issue with INSPIRE web search

### ISSUE THREAD

**Issue by isserstedt** [JabRef/jabref#7274]
In my opinion, the INSPIRE web search does not work as expected anymore:

The search for, e.g., "Tanabashi:2018oca" should yield exactly one result but instead I get 10. In addition, among the search results is not the one I was looking for.

Furthermore, the key "Barrie:2019pqc" gets truncated to "Barrie2019" even though I turned off "Overwrite existing keys" in the preferences. This happens with every entry fetched from INSPIRE.

Version information:
JabRef 5.2--2020-12-24--6a2a512
Linux 5.4.0-58-generic amd64 
Java 15.0.1

EDIT: Problem is still present in the following version:
JabRef 5.3--2020-12-28--020cc97
Linux 5.4.0-58-generic amd64 
Java 15.0.1

**Comment by Siedlerchr** [comment]
@DominikVoigt  Do you have an idea? Is this related to the new search syntax?

**Comment by isserstedt** [comment]
@Siedlerchr The old search syntax still works. Actually, there is no old syntax as far as I know. I guess the issue is related to the new API since INSPIRE got an extensive overhaul in 2020.

Regarding the unwanted key formatting, I have no clue where this could come from. But I doubt that the INSPIRE API provides a truncated/wrong key.
