### ISSUE TITLE
Can I create nested groups by keyword?

### ISSUE THREAD

**Issue by bjhamilton** [JabRef/jabref#7278]
Hi! 

I want to combine explicit groups + keywords to create nested groups by keyword, is this possible? For example, if I create a group called TEST_GROUP, but configure JabRef to create groups by keyword field, can I nest my keywords underneath a specific group like ` keywords = {TEST_GROUP:keyword_1;},` (using the colon ':' to nest and semi-colon ';' as separator (in my configuration I changed the default separator from comma ',')) ?

Reason is I like to use keyword groups, but they can get messy if you don't force yourself to be strict with keywords, so what I want is to specify a group like "Neuroscience", but allow the keyword field to nest keywords underneath it which allows me to be "messy" but within a context which I think is a good balance between messy but organised.

Thanks.

EDIT: my question might be similar to https://github.com/JabRef/jabref/issues/628#issuecomment-204311321 . ~I will re-check the documentation.~

I checked the [documentation](https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups#hierarchical-context) and can't find the answer to what I want to achieve which to summarise is: 

1. how can I create nested keyword groups by manually creating a group, then nesting keywords underneath it in the bibtex source field `keyword = ...` ?
2. If I have `example reference A` with `keywords = {TEST_GROUP_1:keyword_1;}` and `example reference B` with `keywords = {TEST_GROUP_2:keyword_1;}` they must not be grouped together because their parent groups are different (`TEST_GROUP_1` != `TEST_GROUP_2`).
3. Nesting should be *optional*, so `keywords = {TEST_GROUP_2:keyword_1; keyword_2; keyword_3;}` is legal, i.e. the groups pane would show `keyword_2` and `keyword_3` by themselves whereas `keyword_1` would be found after expanding `TEST_GROUP_2` group.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hi @bjhamilton !

I am not sure what you'd like, could you try to use `>` instead of `:` and see if the correct groups are generated? I am getting this results with a similar setup,

<img width="329" alt="Skärmavbild 2021-01-01 kl  11 41 54" src="https://user-images.githubusercontent.com/2598631/103442670-64e30580-4c26-11eb-9ca4-2f509c89ad81.png">

**Comment by bjhamilton** [comment]
I am unable to configure this. How did you do it exactly?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Which version do you use? The screenshot is from JabRef 5.2--2020-12-22--d83ef74.

<img width="712" alt="Skärmavbild 2021-01-01 kl  21 21 11" src="https://user-images.githubusercontent.com/2598631/103449528-540eb000-4c77-11eb-9b61-e56b2baacd9a.png">

The point was rather if those are the groups/subgroups you want?

keywords looks like `TEST_GROUP_1>keyword_1;`

**Comment by tobiasdiez** [comment]
The answer of k3KAW8Pnf7mkmdSMPHz27  should solve your problem.

Please use the forum the next time for questions. discourse.jabref.org/ Thanks!

**Comment by bjhamilton** [comment]
@tobiasdiez You didn't give me an opportunity to reply. 

This is not a solution.  The nested groups do not capture the bib entries. Notice how @k3KAW8Pnf7mkmdSMPHz27 they are at zero? When I tested this, I can create the nested group entries, but they never seem to increment from zero.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I believe the point was that a discussion regarding if something can be done in JabRef, or how it can be done is better kept on https://discourse.jabref.org/. Then what should/shouldn't happen can be sorted out there.

The subsubgroups in my screenshot contain 0 entries, which I'd guess is a bug. But if **those are not the subgroups, structure and names, you'd expect based on those entries**, it is a bug that has nothing to do with your original question (if or how something can be done).

Now **if** those are the (sub)subgroups you expect **and** they should not contain 0 results. Then there is something for me to look into fixing 😛

**Comment by bjhamilton** [comment]
I'm just merely trying to create nested groups with keywords. Of course I didn't use your structure, I applied your suggestion to my library, but the result was the same, i.e. that of the nested groups capturing zero entries, which I agree with you, looks like a bug.

So, If this is a bug, what would have transpired given the premature closure of this question was me signing up for an account on https://discourse.jabref.org to re-raise the question only to be told to come back and file a bug/issue report :P

>  [if X, then] it is a bug that has nothing to do with your original question

If a question results in detection of a potential bug, it should stay here until it is determined as such. Any deviation from the original question between the question and detection of bug feels moot since the moderator can simply adjust the thread accordingly. 

In any case I'm not going to sign up at https://discourse.jabref.org as it is just *another* account for me to keep track of, and one which I may only use once. I shall leave this potential bug with you and hopefully the solution will be provided or an issue raised out of it. If herein is not a bug, perhaps the documentation can be updated at https://jabref.org to communicate how users who wish to have nested groups can approximate the desired configuration (?).

Regards

**Comment by tobiasdiez** [comment]
If the generated subgroups don't match any entries, than this sounds indeed like a bug. Feel free to create a new issue and provide the steps required to reproduce it.

I'm sorry if it's inconvenient to you to register at our discourse forum. It's the only option we currently provide for user support. The github issue tracker is exactly for this: track issues. I can assure you that maintaining JabRef is more effort than creating a discourse account. 

I would also like to say sorry that I closed this issue very quickly, which might not have given the best impression. But you created an issue here ignoring our instructions which clearly state that we do not provide support for questions in this way. Please respect this!
