### ISSUE TITLE
Rendering/conversion of π in Abstract/preview panel

### ISSUE THREAD

**Issue by evanhorn** [JabRef/jabref#7291]
JabRef version  on 
JabRef 5.3--2021-01-04--eff250b
Linux 5.4.0-58-generic amd64 
Java 15.0.1

- [X ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

In the abstract and comment fields, the LaTeX command $\pi$ renders "pi" rather than the expected "π" (lower case pi) in the preview panel. However, the LaTeX form of all other Greek letters, including Π (upper case pi) renders correctly in the preview panel. If "π" is present in the abstract field and Convert -> "Unicode to LaTeX" is used, "π" is converted to "$\phi$" and is rendered as "φ" in the preview panel.

Note: While I tested the rendering of all LaTeX Greek letters I did not test the conversion of all Greek letters from Unicode to LaTeX

1. Enter "$\pi$ in Abstract field.
2. Observe "pi" in preview panel.

1. Paste π into Abstract field.
2. Select Convert -> "Unicode to LaTeX" in context menu
3. Observe "$\phi$" in Abstract field.
4. Observe "φ" in preview panel.

**Comment by Siedlerchr** [comment]
Thanks for reporting that issue. Thanks to @k3KAW8Pnf7mkmdSMPHz27 it's now fixed in the latest development version (available in approx 30 minutes)

**Comment by evanhorn** [comment]
Thanks for the quick response, this fixed the issue!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Thank you for the detailed description, it makes it easier to narrow things down 😉
