### ISSUE TITLE
medline search not working in 5.2

### ISSUE THREAD

**Issue by vigmond** [JabRef/jabref#7294]
JabRef version 5.2  on Linux Rpm/portable 

- [] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Medline search shows syntax error (red field) if a search field is specified and no result returned

1. open Medline/Pubmed web search
2. enter jones [au]
3. click search

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by koobs** [comment]
@vigmond Can you include a screenshot of the syntax error, and/or a traceback / log file if one is produced

**Comment by melTr** [comment]
On my side, I don't have error or log. Results just never appeared. And strangely I'm not able to start a search by just clicking "enter". Other searches works.

Same in 5.2 or JabRef 5.3--2021-01-04--0d995d6
Linux 4.15.0-128-generic amd64 
Java 15.0.1

**Comment by vigmond** [comment]
I could not get a screenshot because the popup message window is too brief. So, if I enter a search field (eg, [au]),
the input field goes pink and a blue lozenge briefly pops up with the message

`This query uses unsupported syntax.
`

**Comment by koppor** [comment]
@vigmond We changed the search Syntax in version 5.2. Could you please retry your query with the new syntax? See https://docs.jabref.org/collect/import-using-online-bibliographic-database#search-syntax for details. I assume you would have liked to search for `au:"Example Author"`?

**Comment by vigmond** [comment]
Thanks. It works with one caveat. Your documentation lists the boolean operators as lowercase (and,or) when in fact, only the uppercase versions work (AND,OR).

**Comment by calixtus** [comment]
https://github.com/JabRef/jabref/pull/8573
