### ISSUE TITLE
Two separate libraries in JabRef don't generate unique citationkey

### ISSUE THREAD

**Issue by xiaodongcentury** [JabRef/jabref#7303]
My JabRef version and OS information as follows:
JabRef 5.3--2021-01-04--0d995d6
Linux 5.9.0-4-amd64 amd64 
Java 15.0.1
the citationkey mode is [auth][year]
In library1, there is a book citation, the author is bob, and year is 2012, so the citationkey is bob2012, for example.
In library2, there is an article citation, the author is bob and mike, and year is 2012, so the citationkey is bob2012.
JabRef main file directory is a folder, whose name is "Paper", which consists a "Book" folder and an "Article" folder. A book whose name is bob2012.pdf in "Book" folder and an article bob2012.pdf in "Article" folder. When JabRef links file between citationkey and the document, e.g. the citationkey bob2012 in library1 will link the book in "Book" folder AND the article in "Article" folder, obviously, this is mis-linked.

**Comment by Siedlerchr** [comment]
Hi, I think you need to adapt your Autolink pattern to respect the entry type, e.g. insert `[entrytype]` to respect the  folder structure. 
https://docs.jabref.org/finding-sorting-and-cleaning-entries/filelinks#auto-linking-files

**Comment by xiaodongcentury** [comment]
Thanks, i don't familiar with regular expression. Maybe change "Library properties", and use "User-specific file directory" is more easier.
