### ISSUE TITLE
RFC fetcher compatibility with drafts

### ISSUE THREAD

**Issue by cmosek** [JabRef/jabref#7305]
RFC fetcher does not process drafts IDs, because `prefixedIdentifier` does not begin with `rfc` prefix.

Example URL for draft's raw bibtex resource https://datatracker.ietf.org/doc/draft-ietf-sidrops-aspa-verification/bibtex 
URL structure is the same as in RFC resource, so no change in fetching part is required.

Ref: #3971 5d23970 @jacksonrya 

Thanks in advance.

**Comment by jacksonrya** [comment]
I'll take a look at this soon

**Comment by Ryyyc** [comment]
@Siedlerchr Hi, I verified the download URL of the RFC resource.

There will be different URLs for different versions, the main difference is the official release version and the draft version.

For example, rfc1945
![rfc-bib](https://user-images.githubusercontent.com/47767371/115984860-b9e2c700-a5db-11eb-8f76-f9e16b3619e7.png)

It has three versions
+ draft-fielding-http-spec
+ draft-ietf-http-v10-spec
+ rfc1945

Their bibtex item download links are:

+ https://datatracker.ietf.org/doc/draft-fielding-http-spec/bibtex/
+ https://datatracker.ietf.org/doc/draft-ietf-http-v10-spec/bibtex/
+ https://datatracker.ietf.org/doc/rfc1945/bibtex/

For the official release version of RFC, visit the download link of the draft version, they will be redirected to the official release version. In other words, access to https://datatracker.ietf.org/doc/draft-ietf-http-v10-spec/bibtex/ will be redirected to https://datatracker.ietf.org/doc/rfc1945/bibtex/.

In JabRef, the download link format of the bibtex item is forced to https://datatracker.ietf.org/doc/rfc{number}/bibtex/.

https://github.com/JabRef/jabref/blob/4bf895b7519ca6544a5d4248d9d17cf7ea609871/src/main/java/org/jabref/logic/importer/fetcher/RfcFetcher.java#L45-L47

So for some bibtex items that only have a draft version, JabRef will not be able to download correctly. E.g https://datatracker.ietf.org/doc/draft-ietf-sidrops-aspa-verification/bibtex/.

**Comment by Siedlerchr** [comment]
So when the draft redirects to the "release" version, it should be sufficient to fetch the draft and follow any redirects?

**Comment by Ryyyc** [comment]
The problem now is that for some bibtex items that do not have the "release" version,  JabRef will not be able to download correctly.
In other words, the current JabRef can only download the bibtex item with the "release" version and cannot download the draft version without the "release" version.  E.g https://datatracker.ietf.org/doc/draft-ietf-sidrops-aspa-verification/bibtex/.

We may need to add an option `RFC draft`, or use some logic to determine whether to add the prefix "rfc" in the construction of the item in the middle of the download link.

**Comment by Ryyyc** [comment]
@Siedlerchr I think this bug can be solved by judging whether the identifier prefix contains "draft". I also added some testcases. See PR [7674](https://github.com/JabRef/jabref/pull/7674).
