### ISSUE TITLE
row numbers

### ISSUE THREAD

**Issue by fewww** [JabRef/jabref#7309]
In the last two versions of Jabref, the row numbers are disappeared from the left side. Can anybody help me, how to display the row numbers?

**Comment by Siedlerchr** [comment]
Hi,

This can be enabled in the Preferences -> entry table -> add the column "Index"
Next time, please ask such questions in the discussion forum https://discourse.jabref.org/

**Comment by fewww** [comment]
Thank you.

Christoph <notifications@github.com> ezt írta (időpont: 2021. jan. 7., Cs,
16:46):
