### ISSUE TITLE
Changes inside the code view of the EntryEditor are discarded

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#731]
When you add unknown fields this inormation is discarded.
In my opinion all changes done inside the code tab should be also saved as long as the Bibtex structure is correct.

**Comment by koppor** [comment]
Workaround: Press CTRL+s after edit.

**Comment by stefan-kolb** [comment]
Cannot reproduce Problem anymore. Could be because I used "" instead of {} for the value of entries.
