### ISSUE TITLE
Add some more built in themes, especially high contrast dark

### ISSUE THREAD

**Issue by docrjp** [JabRef/jabref#7322]
The idea is to improve the handling of built in themes, and in so doing, deliver a user facing benefit in the form of some additional useful themes that can be selected easily without CSS knowledge. In particular, I suggest a high contrast dark theme that would be of benefit for accessibilty. Other suggestions for distinct themes welcome.

This is a follow up on #7177 and in response to a discussion in review of the related pull request: https://github.com/JabRef/jabref/pull/7292#discussion_r554558270

**Comment by Siedlerchr** [comment]
See one theme for example from @AtrusRiven https://docs.jabref.org/advanced/custom-themes

**Comment by koppor** [comment]
@docrjp We would really love if you contributed some more build-in themes. See https://docs.jabref.org/advanced/custom-themes for documentation how to do it. The core developers need to focus on fixing high-priority issues.
