### ISSUE TITLE
remember location of earlier position of jabref window on displays

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7341]
running Linux, Fedora 33, wayland.

JabRef 5.3--2021-01-13--4d8e4f0
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1 
JavaFX 15.0.1+1

I use several monitors. I am frustrated because JabRef forgets its location to which I had moved it before when it starts anew. Solution: remember location.

**Comment by Siedlerchr** [comment]
Do you detach the monitors (e.g external monitor for a notebook) or do you have them permanently connected to your computer?  Refs https://github.com/JabRef/jabref/issues/5037

**Comment by ilippert** [comment]
I have three monitors, running via gnome/Linux, Fedora 33. The cables between monitors and computer are always connected.
Gnome thinks of my two HDMI monitors as always connected. That is, if I turn one off, gnome still thinks both are on. The third monitor is powered by displayport, and if that is turned off, gnome relocates its windows to other windows.

**current behaviour:**
When JabRef is running: Gnome relocates JabRef correctly from and to the displayport monitor depending on whether the monitor is turned on or off.

When I quit JabRef, it always reappears on the same monitor. It also appears on that same monitor if I designate another display as a primary display.

**Comment by ilippert** [comment]
still of interest

**Comment by Siedlerchr** [comment]
There might be some fix coming with the next javafx version

**Comment by ilippert** [comment]
Hi, now on
JabRef 5.7--2022-06-22--9701e35
Linux 5.18.6-200.fc36.x86_64 amd64 
Java 18.0.1 
JavaFX *unknown*

the issue is still present. JabRef works well, but it does neither recall its last position, nor does it follow Gnome's typical window placing policy (that is, the window should be placed on the display on which the mouse cursor is located).

**Comment by ilippert** [comment]
Still an issue

JabRef 5.10--2023-01-12--5d24847
Linux 6.0.18-300.fc37.x86_64 amd64 
Java 19.0.1 
JavaFX 19+11
