### ISSUE TITLE
Some search are not working: MathSciNet, Springer and AirXiv

### ISSUE THREAD

**Issue by GreyCanis** [JabRef/jabref#7345]
JabRef version 5.2 on Windows 10, Ubuntu 20.04.1 and Mac OS Catalina 10.15.7

When I want to search on MathSciNet, Springer or AirXiv I get "Unhandled exeption"

![JAB-162](https://user-images.githubusercontent.com/59370307/104624763-448a6080-5694-11eb-83cc-26bd05d1be07.jpg)

1. Open the JabRef app
2. Create new library.
3. Select Springer, MathSciNet or AirXiv as search engine.
4. Enter some keyword and click search.

**Comment by koppor** [comment]
Do you have a valid MathSciNet subscription? I would propose to try zbMath instead.

Regarding Springer, the JabRef key might hit limits. We will contact them.

arXiv works on our side.
