### ISSUE TITLE
When typing a "-" after a long title into web search the application freezes

### ISSUE THREAD

**Issue by Nirostar** [JabRef/jabref#7349]
JabRef 5.3--2021-01-14--e66f5be
Windows 10 10.0 amd64 
Java 14.0.2 
JavaFX 15.0.1+1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The following also works with other titles containing "-". And also with other search engines. The below example triggers the bug every time:

1. Under Web Search -> Select DBLP
2. Type "Collecting Performance Data with PAPI" into the web search field
3. Type a "-" afterward and now the app does not respond anymore.

<details>
  <summary>Log File</summary>
  
  ```
  I did not find any log file or information in the event log.
  ```
</details>

**Comment by ilippert** [comment]
JabRef 5.3--2021-01-24--ae43548
Linux 5.10.9-201.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 15.0.1+1

Weirdly, I get the `unsupported syntax` note even when just typing out `Collecting Performance Data with`. Might be related to 
![Screenshot from 2021-01-26 17-41-32](https://user-images.githubusercontent.com/20518297/105875483-2579c000-5ffe-11eb-8861-0f88a827f458.png)

https://github.com/JabRef/jabref/issues/7349
