### ISSUE TITLE
new time field creation date - missing possibility to read other field names; missing backup of old information

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7351]
JabRef 5.3--2021-01-14--e66f5be
Linux 5.10.6-200.fc33.x86_64 amd64 
Java 15.0.1 
JavaFX 15.0.1+1

In the past I set a field timestamp to all entries. And this JabRef version simply deleted that information!
that's a loss for users who actually use the timestamp information.  now I see a modificationdate field, but that simply tells me todays date, because I updated to this master version today.

**Comment by Siedlerchr** [comment]
Refs : https://github.com/JabRef/jabref/pull/7334

**Comment by ilippert** [comment]
A brief consideration: if users seriously use the old timestamp information, then https://github.com/JabRef/jabref/pull/7334 renders their timestamp information useless. That's a shame. So, this issue should be fixed definitively before the next release.

**Comment by ilippert** [comment]
I am now on JabRef 5.3--2021-02-05--93ad499
Linux 5.10.12-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 15.0.1+1

And I note that my entries miss both timestamp fields and modificationdate fields.

**Comment by ilippert** [comment]
Something goes wrong if data is lost without even informing or asking the user

**Comment by ilippert** [comment]
JabRef 5.3--2021-02-22--3dc2039
Linux 5.10.16-200.fc33.x86_64 amd64 
Java 15.0.2 
JavaFX 15.0.1+1

timestamp fields and modificationdate fields data gets somehow deleted! no obvious pattern!

**Comment by calixtus** [comment]
Idea: Convert the migration to a cleanup action. Ask the user on startup, if he want's to convert the timestamp, provide "do not ask me again" checkbox.

**Comment by koppor** [comment]
DevCall result

- Migration has an issue @DominikVoigt.
- It seems that the entry is migrated (some magic happens) --> we need to explain the migration proecure somewhere (or add a link here)
- If the migration decides to put the last-updated date information, this information is overwritten, because the entry is modified during the migration. The migration MUST NOT flag the entry as modified to keep the original timestamp.

**Comment by koppor** [comment]
Note on the issue: When the date could not be parsed, the current date is taken.

@ilippert Could you provide us an example of the date entry used in your case?

**Comment by ilippert** [comment]
I think the format was 
`  timestamp = {2017-04-28},`

**Comment by ilippert** [comment]
And I used
`  date-added          = {2014-08-17 20:32:02 +0200},
  date-modified       = {2014-08-17 20:32:02 +0200},`
