### ISSUE TITLE
Field "urldate" does not become YearAccessed, MonthAccessed, DayAccessed when exporting to MSWord

### ISSUE THREAD

**Issue by Fantazstic** [JabRef/jabref#7354]
JabRef 5.2 2020-12-24
Windows 10 10.0 amd64
Java 14.0.2

- [Yes] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add online source to library (BiBlaTeX mode on, I couldn't find online or electronic on the default mode)
2. Add urldate using calendar selector
3. Export selected items to MS Word format
4. Import to MS Word, YearAccessed, MonthAccessed, DayAccessed are all empty and I have to manually input the date

I notice in the exported XML, the date I chose earlier is nowhere to be found, so it must be an Export issue.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by Fantazstic** [comment]
It works as intended now, thanks! 

However, MonthAccessed needs to be exported to text rather than numbers. For example instead of "01" it should be converted to "January". This is standard practice for academic referencing styles, to write out the full month. MS Word also states "Example: January" when Month Accessed is selected.

**Comment by Siedlerchr** [comment]
@Fantazstic  I've just created a follow up fix. It's a simple line change and changing some test files.

**Comment by tobiasdiez** [comment]
This should be fixed now as well. Thanks for the report @Fantazstic

**Comment by Fantazstic** [comment]
I can confirm these bugfixes are working on the master branch, thanks again!
