### ISSUE TITLE
Add duplicate count/progress to Possible Duplicates dialog

### ISSUE THREAD

**Issue by koobs** [JabRef/jabref#7366]
Summary
---------

As a user, when finding/managing duplicates, it is not possible to know how far through the process you are, or how many entries are left to be processed. The requisite information is apparently already available, but it is only shown *after* closing the `Possible duplicate entries` dialog (see screenshot below)

![2021-01-19 18_04_32-](https://user-images.githubusercontent.com/1011612/104999738-43a35700-5a25-11eb-9f77-02a65151baa8.png)

Improvement
--------------

In the `Possible duplicate entries` dialog, display the `current (entry) number` and `total possible duplicate count` to the dialog.

This may be in the form of:

Where `X` is **current entry cursor value** and `Y` is the **total possible duplicate count** ...

 * Updating the Dialog window title, appending "Entry X of Y" to the title, that updates each time the entry cursor is updated or moved to the "next item".
 * Add "Entry X of Y" to the right of the diff display multi-select control

![2021-01-19 18_04_25-Possible duplicate entries](https://user-images.githubusercontent.com/1011612/105000962-f88a4380-5a26-11eb-8c9f-63a1821e625d.png)

**Comment by tp-1000** [comment]
Unless someone says otherwise, I would like to work on this.

**Comment by Siedlerchr** [comment]
Thanks to @tp-1000 this is now implemented in the latest **main**  
https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
