### ISSUE TITLE
Annoying window resizing when using "Prefer tabs: Always" on macOS

### ISSUE THREAD

**Issue by julianmenzler** [JabRef/jabref#7375]
**Prerequisite**
In the macOS system preferences, under General, set "Prefer tabs" to "always."

**Problem**
Dialogs, e.g., "New Entry," are no longer displayed as dialogs. They are opened as tabs in the main window. The latter one shrinks. Also, controls become partially hidden.

After closing a dialog, the main window does not resize and stays small. It has to be resized manually, which is annoying.

**Possible Solutions**
* Do not shrink the main window
* Open dialogs as new windows, always. Ignore the "Prefer Tabs" setting from system preferences.

**Additional context**

<img width="1205" alt="Screenshot 2021-01-22 at 13 06 17" src="https://user-images.githubusercontent.com/9380917/105488987-cee54c80-5cb2-11eb-9eef-04dc77393e5d.png">

**Comment by Siedlerchr** [comment]
Hm, on my Macbook with BigSur 11.1 I cannot reproduce this with the latest development version. Changed the setting to always. Or is a system restart required?

**Comment by julianmenzler** [comment]
Maybe. I use macOS 11.1 and

```

**Comment by Siedlerchr** [comment]
Can you please test again with the latest dev version? I now did  a restart and JabRef still works fine.

**Comment by julianmenzler** [comment]
```
JabRef 5.3--2021-01-24--86d52cd
Mac OS X 10.16 x86_64 
Java 15.0.1 
JavaFX 15.0.1+1
```

Works! Thank you! 🙂

**Comment by Siedlerchr** [comment]
We recently changed something related to how dialogs are created and displayed and also upgraded javafx, so it was probably one of the two changes that fixed this issue.
