### ISSUE TITLE
App crashes with some interactions with search bar

### ISSUE THREAD

**Issue by BugInMaths** [JabRef/jabref#7376]
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64 
Java 14.0.2 on 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Copy text (I think that it has to be enriched text, i.e., with some format)
2. Paste it in the search bar
3. That's it, it crashes

Steps to AVOID the behavior:
1. Copy text (I think that it has to be enriched text, i.e., with some format)
2. Paste it somewhere where the texts has no format and copy it again
3. Paste it in the search bar

Furthermore, now I have to manually press the search button to search instead of pressing Intro in my keyboard.

I hope this report is well explained,
Thanks!

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by damanti-me** [comment]
i also experience that issue ! 
Win10, ad64, version5.2

**Comment by BugInMaths** [comment]
> i also experience that issue !
> Win10, ad64, version5.2
> 
> Edit: JabRef 5.3--2021-05-15--0a26d31 dev version seems to fix that issue

Can you search with the Intro button in that version?

**Comment by damanti-me** [comment]
> 
> 
> > i also experience that issue !
> > Win10, ad64, version5.2
> > Edit: JabRef 5.3--2021-05-15--0a26d31 dev version seems to fix that issue
> 
> Can you search with the Intro button in that version?

I dont exacly know what you mean with "intro" Button, but when i press the return key it has the same effect as clicking "Search".

**Comment by BugInMaths** [comment]
> > > i also experience that issue !
> > > Win10, ad64, version5.2
> > > Edit: JabRef 5.3--2021-05-15--0a26d31 dev version seems to fix that issue
> > 
> > 
> > Can you search with the Intro button in that version?
> 
> I dont exacly know what you mean with "intro" Button, but when i press the return key it has the same effect as clicking "Search".

Oops, in spanish it is "Introducción", always thought it was "Introduction" in english, not "enter". That answers my question, thank you.

**Comment by Siedlerchr** [comment]
@BugInMaths  For the translation of JabRef feel free to modify the Spanish translation https://crowdin.com/project/jabref

**Comment by koppor** [comment]
I tried with some Word file:

![image](https://github.com/user-attachments/assets/d274526f-30d1-4684-814f-69037c0f9b53)

No crash.

Thus, I this should be fixed now in our development version and consequently the change will be included in the next release.

Can you please try out the development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before using this version.
