### ISSUE TITLE
CSL styles do not take CrossRef fields into account

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7378]
Bug report from the [Forum](https://discourse.jabref.org/t/cross-references-in-preview/2517)

>I have the following entries in my bibliography:

> 
 ```
@InCollection{smit2021,
 author = {Smith, Bob},
title = {An article},
 pages = {1-10},
 crossref = {jone2021},
 }
```
> 
```
 @Book{jone2021,
editor = {Jones, John},
 publisher = {Great Publisher},
 title = {A book},
 year = {2021},
address = {Somewhere},
 }
```
> 
> When using the default entry preview (“Customized preview style”), the preview includes information from the cross-referenced entry:
> 
> InCollection (smit2021)
> 
> Smith, Bob
> An article
> 2021
> 
> Jones, John (Ed.)
> Great Publisher: Somewhere
> p. 1-10
> 
> But if I try other preview styles, there is no information from the cross-referenced entry. For example, this is what I get from the APA 7th edition style (and I’ve seen the same thing in other styles):
> 
> Smith, B. An article (pp. 1–10).
> 
> Is it only possible to show the information from the cross-referenced entry in the customized preview style?
> 
> Thanks

FIX:
Should  be getResolvedFieldOrAlias
https://github.com/JabRef/jabref/blob/94f4c1ebba44e0bfceb6867938b116f0cadbbcce/src/main/java/org/jabref/logic/citationstyle/CSLAdapter.java#L98-L99

**Comment by Siedlerchr** [comment]
Turns out it's not so easy to solve beause we need a library/bibdatasecontext

**Comment by jspitz** [comment]
Same for `xdata`-inherited fields with biblatex.

**Comment by Siedlerchr** [comment]
Update (Noe for implementaiton): It should be possible to pass down the bibdatabasecontext to the `CitationStyleGenerator` methods.  We already get a bibdatabasecontext in the generatePreview.
MIght be relevant for https://github.com/JabRef/jabref/issues/8372

**Comment by Siedlerchr** [comment]
Smith, B. (2021). An article (J. Jones, Ed.; pp. 1–10). Great Publisher.

**Comment by jspitz** [comment]
> Same for `xdata`-inherited fields with biblatex.

Just want to note that this still does not work (JabRef 5.12).

**Comment by jspitz** [comment]
> > Same for `xdata`-inherited fields with biblatex.
> 
> Just want to note that this still does not work (JabRef 5.12).

I have now singled this out at #10865.
