### ISSUE TITLE
URLDownload vs. getResults

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#738]
There are currently two ways to fetch text from the internet: `URLDownload` and `getResults` (now in `logic.net.NetUtil`. Any particular reason to have two ways? Currently, it seems like `URLDownload` doesn't support post, but is "nicer" for standard get.

**Comment by oscargus** [comment]
getResults is no longer needed with #739.

**Comment by stefan-kolb** [comment]
Probably both classes are poorly implemented. I can at least confirm that for URLDown load which is...

**Comment by oscargus** [comment]
I'd say the static getResults methods were probably worse then... Anyway, now URLDownload supports additional parameters and posting, so slightly better and at least only one home made solution for that. 

Not sure if one either should convert URLDownload to use Unirest or convert the use directly?

**Comment by oscargus** [comment]
I checked the code a bit more and there are basically three ways now:

* Unirest
Simple, especially if you want json etc.

* URLDownload
Simple to get a String or download to a file

* Directly accessing the URLConnection class
Good to get a reader to be used for BibtexParser

Not sure if it is worthwhile unifying further?

**Comment by simonharrer** [comment]
I think this is enough.
