### ISSUE TITLE
Testing and review items for Refactor unlinked files (PR #7209)

### ISSUE THREAD

**Issue by koobs** [JabRef/jabref#7383]
Testing and review items for Refactor unlinked files in PR #7209 

```
JabRef 5.3--2021-01-24--ae43548
Windows 10 10.0 amd64 
Java 14.0.2 
JavaFX 15.0.1+1
```

- [x] **Regression**: Searching for ``File extension: PDF file *.pdf`` appears not to match files in sub-directories during `Scan directory`. ANY_FILE appears to work recursively

PDF Search

![2021-01-25 12_12_40-Search for unlinked local files](https://user-images.githubusercontent.com/1011612/105650415-a5dbdc00-5eab-11eb-8cd4-fc6c63ad6e31.png)

ANY_FILE Search

![2021-01-25 12_12_32-Search for unlinked local files](https://user-images.githubusercontent.com/1011612/105650527-e63b5a00-5eab-11eb-9297-88427a91657c.png)

- [x] ```Start directory``` and ```File extension``` controls should **set a minimum height** (overlap during resize)

![2021-01-25 12_26_01-Search for unlinked local files](https://user-images.githubusercontent.com/1011612/105650657-4df1a500-5eac-11eb-9c86-d4ec7490eade.png)

- [ ] Allow search results control to be minimized (on resize). Minimum size is too large.

Import results list:

- [ ] Import result list columns should be resizable
- [x] Re-order columns (Status | File | Message)
- [ ] Create one row for each file processes (test case: processing one file results in 7 rows, 6 of which are empty)
- [ ] Expand/Collapse triangle moves location when switching between ```Currently linked files``` and ```Import results```. Both triangles for each list should be located on the left (not right)

UI & Usability Tweaks
--------------------

- [x] ```Search``` button should have a minimum horizontal size set
- [x] Directory and File type controls minimum size is too large (labels disappear during resize)

Control Labels:

- [x] Rename ```Scan directory``` button label to ```Search``` (consistent with dialog and feature title)
- [x] Rename ```Start directory``` to ```Directory``` (remove colon ```:```)
- [x] Rename ```File extension:``` to ```File type``` (remove colon ```:```)
- [x] Rename ```Currently unlinked files``` to ```Search results```

Unless this is an issue with windows java framework features (rather than file type static names set in JabRef)
 - [x] Rename ```ANY_FILE (*.*)``` to ```All files (*.*)```
 - [x] Rename ```BIBTEX_DB``` to ```Bibtex Database (*.bib)```

Control types

- [x] Replace Select/Unselect Collapse/Expand buttons with right-click context menus

![wizardmen__edit](https://user-images.githubusercontent.com/1011612/105651498-facd2180-5eae-11eb-9b78-4dd630080d0f.png)

References: #7205 #7206

**Comment by Siedlerchr** [comment]
Thanks for testing and reviewing!
Fixed some of your issues in a follow up PR #7385 

I disagree with some of your wording suggestions regarding the name of the labels or the buttons.

Regarding the arrow: Although it jumps it has to be on the right side.   JabRef follows Material Design guidelines. 

Otherwise: The Empty rows are created by javafx by default and the TableView resizing is a fcking shit.

**Comment by koobs** [comment]
@Siedlerchr Much ❤️ and you're welcome. Do note that some of the items here are just my initial 'easy' tweak suggestions that form part of a broader UI/UX standardizing/convention document I have going for 'later use'. I'm coming into jabref with my 'new user' hat on, and lots of UI/UX/opensource experience to guide me. All of it is motivated by wanting to get jabref to the point where its extremely friendly and coherent, applying as many good patterns and practices as possible within the scope of its goals.

I also thought we might be restricted by JavaFX stuff, but wasn't sure, so feel free not to include anything that's *too* difficult until we can do more fundamental improvements in separate/distinct issues. :)

**Comment by koobs** [comment]
> Regarding the arrow: Although it jumps it has to be on the right side. JabRef follows Material Design guidelines.

That's absolutely fine, but then we should be following it consistently everywhere else as well :) I haven't been able to find a design system / style guide / design guidelines document for JabRef, do you know if we have one?

**Comment by calixtus** [comment]
Devcall: Hi @koobs , we only have some rudimentary ui recommendations yet. We would love it, if someone would like to put some work in it. Would you be interested in working on this page (https://devdocs.jabref.org/advanced-reading/ui-recommendations) in close coordination with us?

**Comment by koobs** [comment]
@calixtus Would be my pleasure

**Comment by koppor** [comment]
> @calixtus Would be my pleasure

Would it be OK for you to submit pull requests to https://github.com/JabRef/jabref/blob/main/docs/advanced-reading/ui-recommendations.md? Would you feel more comfortable in the WYSIWG editing of GitBook?

**Comment by koobs** [comment]
> > @calixtus Would be my pleasure
> 
> 
> 
> Would it be OK for you to submit pull requests to https://github.com/JabRef/jabref/blob/main/docs/advanced-reading/ui-recommendations.md? Would you feel more comfortable in the WYSIWG editing of GitBook?
> 


I'm happy to do both, have just been overwhelmed the past few months. Is there a long term desire for the project to provide a front end to ease documentation contribution? Happy to follow whatever the project wants to do in that regard

**Comment by koobs** [comment]
Concretely what I need to do is take my set of notes,including those here, that describe concrete implementation changes and reverse derive the guidelines/patterns, then organise that in an easy to consume and structured set. 

What might be an idea is to close this issue as "done" modulo the UI/UX changes, and treat any future improvements in and as a separate logical issue/pr

**Comment by koppor** [comment]
@koobs You are right. We close this issue and will eventually open new issues for the UI/UX changes.
