### ISSUE TITLE
missing indicator for file change of liberary change

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7389]
JabRef 5.3--2021-01-24--ae43548
Linux 5.10.9-201.fc33.x86_64 amd64
Java 15.0.2
JavaFX 15.0.1+1

In the past a small star `*` next to a library's file name was an an indicator for a changed file. I cannot see this indicator anymore.

**Comment by Siedlerchr** [comment]
<img width="220" alt="grafik" src="https://user-images.githubusercontent.com/320228/106191363-108e5f80-61ab-11eb-94f1-2a0c4b1080c9.png">

Still there

**Comment by ilippert** [comment]
I apologise, the reason I did not see it was because I had autosave enabled.
