### ISSUE TITLE
Unresponsive JabRef in ElementaryOS

### ISSUE THREAD

**Issue by pglez82** [JabRef/jabref#7394]
JabRef version: JabRef 5.3--2021-01-26--034cf8c
Linux 5.4.0-64-generic amd64 
Java 15.0.2 
JavaFX 15.0.1+1

It also happens in version 5.2. I tested 5.3 to confirm that the same happens in the last version.

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

JabRef opens and looks ok. Menu options work but once a window is opened, buttons are not working. For instance, I press Help>About JabRef and the window that pop ups is impossible to close using the mouse (I can close it using tab and the keyboard).

1. Open JabRef
2. Click in Help>About JabRef (really any option that opens another window)
3. Buttons in the popup do not work using the mouse.

The only message that I can see when I run the application from the console is this:

(JabRef:16180): Gdk-WARNING **: 09:52:39.859: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.

Since I use ElementaryOS I have found this problem in JabRef but I have used this work around:

https://elementaryos.stackexchange.com/a/26136/24605

and it has worked so far. Unfortunately, this solution does not work anymore. I do not know if the reason.

**Comment by Siedlerchr** [comment]
You probably have to adjust the commandline arguments and add that -Djdk.gtk.version=2  as argument. See this forum post for how to do this https://discourse.jabref.org/t/hidpi-scaling-ignored-in-jabref-5-2/2512/2

**Comment by pglez82** [comment]
Ok. That worked. I will update my response in stackexchange with this new workaround.

I think the issue can be closed now.

Thank you.

**Comment by calixtus** [comment]
Cool! We are happy, if we can be helpful.
We hope you enjoy using JabRef!
