### ISSUE TITLE
NPE at saving does not reset save flag

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#741]
I've got an NPE during the save (have to investigate)

```
%d [%thread] %-5level %logger - %msg%n java.lang.NullPointerException
        at net.sf.jabref.exporter.FileActions.saveDatabase(FileActions.java:232)
 ~[JabRef-dev-fat.jar:?]
```

When I try close JabRef, following dialog appears:

![grabbed_20160129-050058](https://cloud.githubusercontent.com/assets/1366654/12666901/4ddf0f62-c645-11e5-86a5-d16af9b06bd1.png)

After clicking "Discard changes", following dialog appears:

![grabbed_20160129-050124](https://cloud.githubusercontent.com/assets/1366654/12666907/5c37f42a-c645-11e5-804c-2f56bc8e58f4.png)

A click on "cancel" returns to JabRef. I have to kill JabRef. This should not happen - or is it an edge case which will never appear again?

**Comment by lenhard** [comment]
The error is thrown in the following line:
``` java
if (EntryTypes.getStandardType(entryType.getName()) == null) {
```
So this propably has something to do with the refactoring of entry types and should be fixed. @simonharrer @stefan-kolb any idea?

**Comment by simonharrer** [comment]
@tobiasdiez as you created the corresponding PR, could you perhaps have a look into this?

**Comment by koppor** [comment]
With current master, I have following error when saving a database:

```
20:44:39.291 [AWT-EventQueue-0] ERROR net.sf.jabref.gui.BasePanel - runCommand error: null
java.lang.NullPointerException
        at net.sf.jabref.exporter.FileActions.saveDatabase(FileActions.java:230) ~[main/:?]
        at net.sf.jabref.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:235) ~[main/:?]
        at net.sf.jabref.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:186) ~[main/:?]
```
