### ISSUE TITLE
GUI Freezes when searching long titles with some characters

### ISSUE THREAD

**Issue by riparise** [JabRef/jabref#7410]
JabRef version 5.2 and 5.3 on Windows 10

GUI Freezes when pasting or typing a long title in the search bar. It freezes if title has some characters (e.g "," or ".")

1. Click on the search bar on lower left (for example ArXiv)
2. Paste the following title: "Introduction to Quantum Mechanics - David J. Griffiths, Darrell F. Schroeter"
3. GUI freezes

If the title is "Introduction to Quantum Mechanics David J Griffiths Darrell F Schroeter" there is no problem.

**Comment by Siedlerchr** [comment]
Thanks for your report! The issue has been fixed now in the latest master by #7391.

**Comment by Fu188** [comment]
> Thanks for your report! The issue has been fixed now in the latest master by #7391.
The current solution is just to remove the syntax check. But I think it is unreasonable to remove the syntax check. I have fixed this issue in another way and the syntax check is remain. Would you please to reopen this issue that I can pull request my solution?
