### ISSUE TITLE
Font size of the preferences dialog does not update with the rest of the GUI.

### ISSUE THREAD

**Issue by Landi29** [JabRef/jabref#7416]
JabRef version  on 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

If you change the preferred font size of JabRef under preferences/appearance, the font size of the GUI is updated on reload of JabRef, but the font size of the preferences dialog remains the same.

1. Open JabRef.
2. Press Options, Preferences and then open the Appearance tab.
3. Change the font size to `12` or `14` as an example.
4. Save the changes and reload JabRef.
5. Open the Preferences dialog again. You can see that the font size of this dialog remains the same.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Landi29** [comment]
Can anyone post how to get the preferred fontsize in a view? I think that we can just get this value and set the preferred fontsize directly in the dialog xml. Any other suggestions?

**Comment by XDZhelheim** [comment]
I looked into the source code about `PreferencesDialog` and worked out a solution. It works on my computer (Windows 10) and I will open a PR soon. Hope this will solve your problem.
