### ISSUE TITLE
Citation keys are always overwritten when importing through web search

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [JabRef/jabref#7420]
The citation key generator **never** preserves citation keys while importing from sites such as INSPIRE HEP. The citation keys are overwritten even if "Overwrite existing keys" is disabled in preferences and always without warning.

JabRef version
```
JabRef 5.3--2021-02-03--242a494
Mac OS X 10.15.7 x86_64 
Java 15.0.2 
JavaFX 15.0.1+1
```

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

#### Relevant links
1. [JabRef renaming keys?!](https://discourse.jabref.org/t/jabref-renaming-keys/1900) (I don't think these options exist anymore)
2. [InspireHEP and SAO/NASA ADS Bibtex Key Catch (feature request)](https://discourse.jabref.org/t/inspirehep-and-sao-nasa-ads-bibtex-key-catch/2453)
3. [Can I use Inspire citation keys when importing via jabref?](https://discourse.jabref.org/t/can-i-use-inspire-citation-keys-when-importing-via-jabref/2530)
4. There is a mention of unwanted key formatting in #7274

#### Temporary workaround
It is possible to keep citation keys by using the [citation key pattern `[CITATIONKEY]`](https://discourse.jabref.org/t/can-i-use-inspire-citation-keys-when-importing-via-jabref/2530/2?u=k3kaw8pnf7mkmdsmphz2) during the import.
`:` must also be removed from the "Remove the following characters" field in preferences.
It should be possible to use the regexp in https://github.com/JabRef/jabref/issues/7111#issuecomment-731763262 to create a workaround where a different pattern is used when there is no citation key in the imported entry. (If someone manages with this approach, feel free to add a comment and perhaps others will also find it useful)

#### Steps to reproduce the behavior:
1. Unmark "Overwrite existing keys" <img width="888" alt="Skärmavbild 2021-02-03 kl  15 41 33" src="https://user-images.githubusercontent.com/2598631/106808091-f257b200-6637-11eb-8e66-7e26c5ff17e7.png">
2. Make a web-search on INSPIRE and import any entry <img width="618" alt="Skärmavbild 2021-02-03 kl  15 43 47" src="https://user-images.githubusercontent.com/2598631/106807983-cccaa880-6637-11eb-864b-1f43f2e61c30.png">
3. Note that the citation key is overwritten
 <img width="618" alt="Skärmavbild 2021-02-03 kl  15 47 36" src="https://user-images.githubusercontent.com/2598631/106808003-d2c08980-6637-11eb-9ebc-39a325f16b01.png">

**Comment by bulmust** [comment]
Same issue for me. I always manually rewrite bibtex-key which i fetch from inspire or ads

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@bulmust, the workaround(s) work for now?

**Comment by bulmust** [comment]
No, still problematic. Bibtex-key is not fetched from Inspire.
![1](https://user-images.githubusercontent.com/19466488/107000896-b8062600-6799-11eb-9c9e-617462e481ce.gif)

My configs and version are:
![2](https://user-images.githubusercontent.com/19466488/107000911-be949d80-6799-11eb-944c-6f897c25e524.gif)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I meant using the citation key pattern `[BIBTEXKEY]` or `[CITATIONKEY]` while importing. (discussed [here on discourse](https://discourse.jabref.org/t/can-i-use-inspire-citation-keys-when-importing-via-jabref/2530/5?u=k3kaw8pnf7mkmdsmphz2)
However, that might not be convenient for you unless you always want to keep the imported keys.

**Comment by Siedlerchr** [comment]
I debugged a bit and the problem seems to be that this import handler doesn't check the preferences if the key should be overwritten or not. And further down there isn't any check either.

So the solution would be to add a check for the setting from the CitationKeyPrefereces.

https://github.com/JabRef/jabref/blob/86d52cd6468335d9e460aaacc870aa5088c62431/src/main/java/org/jabref/gui/externalfiles/ImportHandler.java#L196-L210

**Comment by bulmust** [comment]
> I meant using the citation key pattern `[BIBTEXKEY]` or `[CITATIONKEY]` while importing. (discussed [here on discourse](https://discourse.jabref.org/t/can-i-use-inspire-citation-keys-when-importing-via-jabref/2530/5?u=k3kaw8pnf7mkmdsmphz2))
> However, that might not be convenient for you unless you always want to keep the imported keys.

Thank you. It is solved. 

Before Jabref 5.x versions, this option was default.  Solution is following:

![Peek 2021-02-06 19-02](https://user-images.githubusercontent.com/19466488/107123313-e7a65280-68ad-11eb-9b68-026df924045d.gif)

**Comment by LucasF-42** [comment]
Hey, I've (possibly) been able to fix this, but I'm not sure if it's according to JabRefs intended behaviour for this feature (more details on that can be found in the Pull Request).
