### ISSUE TITLE
Characters in the «Preferences» dialogue are still blurry in Jabref 5.2

### ISSUE THREAD

**Issue by SN-CH** [JabRef/jabref#7422]
In spite of the fact, the ticket [6317 ](https://github.com/JabRef/jabref/issues/6317)was closed a few months ago, the issue persists. I just installed Jabref 5.2 in Windows 10 (I use 125% display scaling, otherwise every thing on my screen become way too small). It looks even worse with the dark theme (just my own impression), please have a look.
![Screen-shot_2021-02-05_11-16-20](https://user-images.githubusercontent.com/42577865/107009356-fe618200-67a5-11eb-87bd-b68246476255.png)
Could it be related, at least theoretically, with the fact I am using old Java 8.201?

**Comment by calixtus** [comment]
Normally JabRef comes with its own jre bundled and uses internally at the moment java 14. So this should not be a problem. We think this might be a javafx problem. @Siedlerchr will take a look into this. Thanks.

**Comment by Siedlerchr** [comment]
MIght be related https://bugs.openjdk.java.net/browse/JDK-8211294

**Comment by Siedlerchr** [comment]
We just upgraded to javafx16, which fixed a bug that could  be related. @SN-CH  can you please test the latest master version again?

**Comment by SN-CH** [comment]
Hi @Siedlercher

I tested it in fresh Jabref 5.3. It may sound somewhat paradoxical, but it is «mostly fixed». I mean it looks considerably better, but still a wee bit blurred when compared to text in other parts of the GUI. I can certainly live with it. And so can most of the people, I trust. From my viewpoint, for all practical reasons the issue can be closed, unless you wish to investigate it further to reveal the cause of this remaining blur and eliminate any possibility of bug re-occurrence.

No matter what will be your decision on the further course with this bug, I sincerely thank you and your colleagues for nice and handy piece of software as well as for listening to end-users.
