### ISSUE TITLE
Logger not configured when JAR is started

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#743]
When starting the JAR of JabRef, following output appears:

    ERROR StatusLogger Unrecognized format specifier [d]

Steps to reproduce:

1. ` gradlew shadowJar`
2. `java -jar build\libs\JabRef-3.3dev-fat.jar`

**Comment by simonharrer** [comment]
Problem of log4j2 in fat jars. Cannot be resolved easily. Maybe switch back to log4j v1?

**Comment by koppor** [comment]
Do you have a link for it? The stackoverflow answer at http://stackoverflow.com/a/34149368/873282 suggests that we might be using a wrong XML configuration.

OK, [JIRA-LOG4J2-954](https://issues.apache.org/jira/browse/LOG4J2-954?focusedCommentId=14936777&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14936777) suggests that we should downgrade to 2.0.2.

**Comment by simonharrer** [comment]
Commons-logging does not work well with logback.

Root issue: http://stackoverflow.com/questions/34945438/log4j2-configuration-not-found-when-running-standalone-application-builded-by-sh/34946780

Solution in the maven world https://github.com/edwgiz/maven-shaded-log4j-transformer

**Comment by simonharrer** [comment]
206ba3feea5e7e36d9bc880a7926ba9379d20578

**Comment by lockywolf** [comment]
Still present in 5.0's "Portable Linux" .

Java:

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (IcedTea 3.16.0) (Slackware)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
