### ISSUE TITLE
Enhance bibliographic information with data from zbmath.org

### ISSUE THREAD

**Issue by ibe-314** [JabRef/jabref#7437]
It is possible to enhance bibliographic information with data from some public databases via the "Update with bibliographic information from the web" button in the editor. I would like to add zbmath to the list of databases (right now one can choose between Crossref, DOI, ISBN, MathSciNet and SAO/NASA ADS). I think it would be helpful for mathematical users to have the possibility to update their bib entries with information from zbmath. 

I already worked on the zbMathFetcher [#7202] and I could implement the EntryBasedParserFetcher for the zbMathFetcher.

**Comment by Siedlerchr** [comment]
Sounds like a good idea! Go ahead!

**Comment by Siedlerchr** [comment]
Thanks again for your contribution! I merged now
