### ISSUE TITLE
Freeze for few seconds sometimes, on MacOS

### ISSUE THREAD

**Issue by Kurapikov** [JabRef/jabref#7441]
JabRef version 5.1 and git 69cc797cb5f3b20c5d698aa35b35d2ca855effe3 on Mac OS X 10.15.7

I have tested the latest development version from git and build it myself, and the problem persists

1. Open a bib, my bib is only 89 entries.
2. Switch between entries with left click.
3. Sometimes it will freeze for 5 seconds. When it backs normal, I can switch between entries fluently, but after about 5 senconds, it freeze again for about 5 seconds......

It's very same with @tilltnet in following thread:
https://discourse.jabref.org/t/jabref-5-0-very-slow-update-gui-entries/1930/8

I attached Intellij IDEA profiler snapshot and console output here.

First I run jabref with "--debug" option, and then I attach profiler to it. As soon as the profiler is attched, I switch item and cause a freeze. When jabref is out of freeze, I stop profiler and save the snapshot. The profiling lasts about 5 seconds.

[console.txt](https://github.com/JabRef/jabref/files/5953341/console.txt)

[20387_org.jabref_org.jabref.gui.JabRefLauncher_2021-02-10-014735.collapsed.zip](https://github.com/JabRef/jabref/files/5953345/20387_org.jabref_org.jabref.gui.JabRefLauncher_2021-02-10-014735.collapsed.zip)

**Comment by Kurapikov** [comment]
Forgot to mention: JRE/JDK 15.0.2

**Comment by Kurapikov** [comment]
Still no any respond?

This is not simply a performance problem. It makes JabRef almost unusable under MacOS.

If no one can reproduce this, I can do more digest if you developer can provide some hint.

Thanks.

**Comment by koppor** [comment]
@Kurapikov Is this https://github.com/JabRef/jabref/issues/5071? Do you have time to investigate? We have a yourkit profiler license in case you would like to use it to support us! #opensource #freetime

**Comment by Siedlerchr** [comment]
I noticed that only happens on start. But then no longer. I am also using Mac. Have you tried to disable Autocompletion?

**Comment by Kurapikov** [comment]
@kopper @Siedlerchr 

It's not #5071. JabRef 5.0 works fine on my Windows 10 box.

The issue I reported in OP is on MacOS. It happens with a small bib only have ~100 entries.

I saw the video attached in #5071 and found yourkit profiler is much cooler than the one in IntelliJ. I can handle the license so no worry. I don't have much time but I think I can spare some time to do this.

I'll try yourkit these days and see if I can find anything. Hope I can attach a video so you can see what to do next.

**Comment by koobs** [comment]
Cannot reproduce, using mouse (trackpad) or updown arrows to switch between entries, with a > 400 entry library on:

```
JabRef 5.3--2021-02-16--5546141
Mac OS X 10.15.7 x86_64 
Java 15.0.2 
JavaFX 15.0.1+1
```

@Kurapikov are you able to reproduce this on the latest master?

**Comment by Kurapikov** [comment]
> Cannot reproduce, using mouse (trackpad) or updown arrows to switch between entries, with a > 400 entry library on:
> 
> ```
> JabRef 5.3--2021-02-16--5546141
> Mac OS X 10.15.7 x86_64 
> Java 15.0.2 
> JavaFX 15.0.1+1
> ```
> 
> @Kurapikov are you able to reproduce this on the latest master?

Hi koobs,

I have tried on master 2 weeks ago. Recent days I don't have any time since I'm at deadline of my PhD thesis, and I think the code I tested with is new enough.

So may it be the problem with my bib? I attached my bib file here so would you like to test it?

I'll try my best to follow this issue.

[ref.zip](https://github.com/JabRef/jabref/files/6031807/ref.zip)

**Comment by Ali96kz** [comment]
@Kurapikov I found a problem, currently thinking about a solution. You can get [these solution](https://stackoverflow.com/questions/33289695/inetaddress-getlocalhost-slow-to-run-30-seconds) as a workaround

**Comment by Kurapikov** [comment]
> @Kurapikov I found a problem, currently thinking about a solution. You can get [these solution](https://stackoverflow.com/questions/33289695/inetaddress-getlocalhost-slow-to-run-30-seconds) as a workaround

Hi @Ali96kz

This workaround solved my problem magically!! Thank you very much!!!!

But, if it is a bug found 5 yrs ago, how you remembered that and linked it to my issue, and this bug exists for 5 yrs without a fix?

**Comment by koobs** [comment]
Possibly useful: [Java: no timeout on DNS resolution](https://bbossola.wordpress.com/2015/10/23/java-no-timeout-on-dns-resolution/) for code that provides DNS resolution lookups with timeouts (set low)

Might be worth pulling in a well maintained network utilities library if Java (still) doesn't provide DNS timeouts in the standard libraries instead of couture code. There's got to be some goodies out there.

**Comment by chibi03** [comment]
I have the same issue on Manjaro Linux 5.10.18 (XFCE) and the workaround fixed the problem as well.

**Comment by Ali96kz** [comment]
@koppor  Could be closed?
