### ISSUE TITLE
Saving library doesn't create .bib file but a file without ending

### ISSUE THREAD

**Issue by State-Of-Joshing-Gentle-Peevishness** [JabRef/jabref#7451]
File > New library and then Save library > choose name > lower right corner choose BIBTEX_DB file (only option) > Save
or File > Save library as > choose name > lower right corner choose BIBTEX_DB file (only option) > Save
File is saved without any ending. Expected to be saved as .bib instead, as none(?) other file-endings are displayed when using File > Open library.

Workaround: add .bib manually when choosing name.

JabRef 5.2--2020-12-24--6a2a512
Linux 5.8.0-43-generic amd64 
Java 15.0.1

**Comment by Siedlerchr** [comment]
I cannot reproduce this isuse with the latest master version under Mac. Maybe some linux thing?

**Comment by mlep** [comment]
Well, easy to reproduce on Linux.

JabRef 5.3--2021-02-27--c7f2671
Linux 4.19.0-14-amd64 amd64 
Java 15.0.2 
JavaFX 15.0.1+1

**Comment by Siedlerchr** [comment]
Okay, this is weird. After a bit of googling I stumbled across this bug which says it's intended for GTK applications: (wtf?)
Some applications add the extension, other not (gedit) 
https://bugs.openjdk.java.net/browse/JDK-8123775

Well, the  fix would be easy:
Check if the file returned from the file extension dialog contains the extension
Check if the file with extension already exists -> 
 - Yes = > cancel/throw an error :
 - Not => save file with extension

@LyzardKing  Do you maybe know if there is a kind of "flag" to add or not add the extension?

**Comment by aakarshvats638** [comment]
I would like to work on this issue if it is reproducible on windows

**Comment by LyzardKing** [comment]
> @LyzardKing Do you maybe know if there is a kind of "flag" to add or not add the extension?

Do you mean in the save dialog? I'm not sure...

**Comment by ryanhore23** [comment]
I see this issue has been tagged with Linux, a small group of us from Adelaide University would love to contribute to this issue over the course of the coming weeks.

**Comment by srdeotarse** [comment]
I want to participate in GSOC 2021 , so would like to solve this issue as I have set up local workspace on Ubuntu 20.04 and successfully reproduced the issue @Siedlerchr

**Comment by LyzardKing** [comment]
The better solution here would be to fix it upstream in openjfx.
A quick fix in jabref would be trivial (as @Siedlerchr says), but not really solve the issue.
