### ISSUE TITLE
Double-click onto PDF in file list should just open the file

### ISSUE THREAD

**Issue by xolotl90** [JabRef/jabref#7465]
Right now, when a file associated to an entry under the 'General' tab is double-clicked, a prompt opens which asks for changing the file location, description or type. 
As this operation is usually done not more than once, a more convenient behavior would be just to open the file.

**Comment by tobiasdiez** [comment]
Good idea, the dialog should then become available through a new right-click > Edit option.

**Comment by xolotl90** [comment]
@tobiasdiez In fact, that option already exists. Only the change of the double-click would be necessary.

**Comment by divyanshmishra19** [comment]
Is this issue still open to submissions? I would like to take a crack at it

**Comment by Siedlerchr** [comment]
@divyanshmishra19  Sure, go ahead! Make sure to follow our [contribution guide](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md)

**Comment by claell** [comment]
Hm, by accident, I came across this issue. Looks like the functionality already had been implemented before in #3491? Linking just for reference.

**Comment by ThiloteE** [comment]
I can confirm as well double clicking the file opens the pdf. Thanks @claell :-) The issue has already been closed though.

**Comment by claell** [comment]
I know, just wanted to link that issue for reference :) I meant that I saw this issue, I don't have the issue myself (was probably misleading).
