### ISSUE TITLE
Crash on long query with special character in online search

### ISSUE THREAD

**Issue by HifeFish** [JabRef/jabref#7472]
JabRef version 5.2 on Ubuntu 16.04

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists
 
Unfortunately, I could not test the latest development version 5.3, as it will not start on my system.

1. Open online research sidebar
2. Paste "resolution of singularities of real-analytic" into the search field (Or any long query with either a hyphen or colon or other symbol that would trigger an "unsupported format" warning)

Possibly related: #7376

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
This has been fixed in the latest development version.
Could you please describe the error when trying to start the JabRef master version? Can you run JabRef from your terminal application?

refs #7411

**Comment by HifeFish** [comment]
My bad, I should have searched closed issues as well.

In Gnome Terminal:

> ~$ /opt/jabref/bin/JabRef
> Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
> Error occurred during initialization of VM
> Could not find agent library instrument on the library path, with error: libinstrument.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
> Module java.instrument may be missing from runtime image.

(Translation of "Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden" is "Cannot open shared object file: file or directory not found")

**Comment by Siedlerchr** [comment]
Hm, this is totally odd. 
Can you start JabRef from the script in JabRef/lib/runtime/JabRef ?

**Comment by HifeFish** [comment]
Same behaviour (this time with whole error message in English):

> ~/Downloads/JabRef/lib/runtime/bin$ ./JabRef
> Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
> Error occurred during initialization of VM
> Could not find agent library instrument on the library path, with error: libinstrument.so: cannot open shared object file: No such file or directory
> Module java.instrument may be missing from runtime image.

Same for just running java -version from that directory:
 
> ~/Downloads/JabRef/lib/runtime/bin$ ./java -version
> Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
> Error occurred during initialization of VM
> Could not find agent library instrument on the library path, with error: libinstrument.so: cannot open shared object file: No such file or directory
> Module java.instrument may be missing from runtime image.

Should I create a separate issue for this?
