### ISSUE TITLE
The "custom colors" window for group color selection loads theme partially

### ISSUE THREAD

**Issue by wwtan** [JabRef/jabref#7481]
JabRef version 5.3--2021-03-01--cfb504c  on Windows 10 10.0 amd64 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Create new group
2. Under "Color", choose "Custom Color..."
3. And we see the mix-theme window
![2021-03-01 22_44_58-_Mendeley-link bib – JabRef](https://user-images.githubusercontent.com/53798617/109569470-6888f080-7ae0-11eb-82af-a3218aae60b4.png)

**Comment by Siedlerchr** [comment]
Thanks for the report. The Dark.css needs to be modified to add css for the ColorPicker dialog.
I used scenic view to display the hierarchy, the style class is  `controls-pane`
<img width="1734" alt="grafik" src="https://user-images.githubusercontent.com/320228/109864980-cd208880-7c63-11eb-81d8-418f329f9c42.png">

**Comment by tp-1000** [comment]
May I have this one? And is this the preferred way to request an issue?
