### ISSUE TITLE
Snap build fails

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7515]
I noticed that the snapcraft build fails:

Maybe related to https://github.com/JabRef/jabref/pull/7447 ?

@LyzardKing  any idea?
```
The interpreter 'python3' for 'lib/jabrefHost.py' was resolved to '/usr/bin/python3'.
The command 'lib/jabrefHost.py' has been changed to '/usr/bin/python3 $SNAP/lib/jabrefHost.py' to safely account for the interpreter.
Failed to generate snap metadata: The specified command '/usr/bin/python3 $SNAP/lib/jabrefHost.py' defined in the app 'browser-proxy' does not match the pattern expected by snapd.
The command must consist only of alphanumeric characters, spaces, and the following special characters: / . _ # : $ -
Build failed
```

**Comment by LyzardKing** [comment]
That might be the issue... if it worked previously.
It "should" find the correct python path in the snap as well, and from a first quick test it seems to work...
but I'll try and debug the new snap asap

**Comment by LyzardKing** [comment]
I removed the env declaration from the snap and it seems to work.
I assume the problem is with the fact that the python location is not in the jabref snap but in the base snap..
