### ISSUE TITLE
UI: "Export order" --> "Save order"

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7517]
For JabRef 5.3--2021-03-11--8bb7668,
in Options -> Preferences, Tab File, there is a section entitled "Export sort order":
![JabRef-Pref-SortOrder](https://user-images.githubusercontent.com/6931104/110918869-ee483f80-831b-11eb-9503-96f42cf9b2db.png)

Same in Library -> Library properties:
![JabRef-Library-SortOrder](https://user-images.githubusercontent.com/6931104/110918961-05872d00-831c-11eb-975c-0456e26feb06.png)

**Is your suggestion for improvement related to a problem? Please describe.**
Currently, these items do not affect the sort order when _exporting_ entries (like using File -> Export).
They alter the sort order when _saving_ the library.

**Describe the solution you'd like**
Make clear that these items affect the saving order by changing "Export [...]" into "Save [>...]"

**Comment by Siedlerchr** [comment]
I took a deeper lok at the code, they are both the save order for the library and for the export.
The savePreferences contain the sort Order 
https://github.com/JabRef/jabref/blob/7f4c36c03629498db8e56281906241a82846e1e3/src/main/java/org/jabref/logic/exporter/TemplateExporter.java#L232

**Comment by Siedlerchr** [comment]
I think I found a bug with regard to the export, theredfore I close this issue

**Comment by tobiasdiez** [comment]
I would say "Save order" is still better since it then includes the normal file save as well as export. Maybe even make it very explicit and say "Save and export order"?

**Comment by mlep** [comment]
I second @tobiasdiez about "Save and export order"!

**Comment by 2bein** [comment]
I would suggest to have separate options for saving the library and exporting (selected entries). The reason ist that I use SVN to follow changes of the libraray that is used by many members of our institute. Changing the save order always confuses the file versioning...

**Comment by koppor** [comment]
For me - complete screenshots to understand the issue

Export is correct:

![grafik](https://user-images.githubusercontent.com/1366654/112886213-e802e300-90d1-11eb-8e44-82495fcaa142.png)

Library properties incorrect:

![grafik](https://user-images.githubusercontent.com/1366654/112886270-fc46e000-90d1-11eb-8ba6-b8f4583e78c3.png)

**Comment by 2bein** [comment]
Yes, that would be perfect!

**Comment by Siedlerchr** [comment]
Now merged. Please note that the latest branch is now called "main" instead of master

**Comment by mlep** [comment]
Works fine, great!
