### ISSUE TITLE
Column sort order not properly stored

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7524]
There is somehow a bug in storeColumnPreferences 

Even when I change the sort oder of one column

From debugging I noticed it's always empty  and this is the root issue why the export does not take into account the current table order 
https://github.com/JabRef/jabref/blob/2c7715cf0476d504475cde7b5e23c4bff677036b/src/main/java/org/jabref/preferences/JabRefPreferences.java#L1932-L1935

**Comment by Siedlerchr** [comment]
Can no longer reproduce the issue :(

**Comment by Siedlerchr** [comment]
Debugged a bit more, it's odd: Sometimes the mainTable.getSortOrder() returns an empty list. 
I could reproduce it as follows.  Sort by year DESC, e.g. click on the table header for the YEAR column.

https://github.com/JabRef/jabref/blob/c8f7be89ad704065474decb61851e42416caf88d/src/main/java/org/jabref/gui/maintable/PersistenceVisualStateTable.java#L36-L41


@calixtus  I remember that you worked on this. Any idea?

**Comment by calixtus** [comment]
I took a quick look into it. I honestly have no idea why. mainTable.getSortOrder refs directly to the javafx-implementation of a TableView.

**Comment by Mehdi-Ayadi** [comment]
Hi, i'm a software engineering student and I'm really looking forward to solve this issue if possible. It will be really appreciated to get some guidance or help since i'm new to the project. Thanks!

**Comment by Mehdi-Ayadi** [comment]
@Siedlerchr i can propose the idea of adding a change listener to the mainTable.getSortOrder that will basically detect whenever there's a change in the sorting order we want ASC or DESC and in a case of DESC order the event will be handled. If it's a good solution i can manage to solve it directly. Thanks in advance !

**Comment by Siedlerchr** [comment]
Thanks for your interest,  but the underlying problem is a bit more complicated and we already have listeners in place if you look closely in the  PersistenceVisualStateTable

https://stackoverflow.com/questions/52255126/javafx-tableview-why-does-the-sortorder-listener-does-not-fire-when-i-sort-desc

The question is rather: Why is the getSortOrder list sometimes empty and sometimes not when a listener is triggered?

**Comment by calixtus** [comment]
Hello @Mehdi-Ayadi nice to hear, that you took interest in JabRef.
To get started, I would suggest you take a look at our developer documentation and start by solving some "good first issues" in our issue tracker to become familiar with the code base of JabRef.
Please note that you have to distinguish in JavaFX between to column sort order and the sort type of a column. Both are stored in JavaFX in separate variables. Right now we are using a changelistener (in PersistentVisualState), but somehow the JavaFX framework does not provide any sort order at all in certain cases. A first step towards a solution would be to debug the ChangeListener and to get an understanding, in which situations it does not work and in which it does.

**Comment by Mehdi-Ayadi** [comment]
@Siedlerchr  @calixtus  thank you for your fast replies and for the clarifications ! it's really appreciated. I will take a look a bit more into the details and do my best to come up with a solution.

**Comment by Siedlerchr** [comment]
Idea for debugging: Split each listener to call a separate method so it's easier to see what listener is when called
