### ISSUE TITLE
XREF Error when writing XMP Metadata to PDF

### ISSUE THREAD

**Issue by suppenkaspar109** [JabRef/jabref#7540]
JabRef version <5.2> on 

- [ x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Choose any Entry in JabRef
2. Choose Tools->Write XMP Metadata to PDFs
3. Open PDF in external Viewer (such as PDF xChange)
4. Error about Corrupt PDF is shown: "Some problems have been found and corrected within the document. You may fixed the document's copy. 

<details>
  <summary>Error detected in XREF table</summary>
  
  ```
Export of Metadata causes an wrong XREF Table entry
  ```
</details>

**Comment by Siedlerchr** [comment]
@suppenkaspar109 
We recently improved and updated the components for writing  XMP Metadata to PDfs.  Can you please test the latest development version (5.7)
https://builds.jabref.org/main/ 

Remember to make a backup of your library before trying out the new version

**Comment by ThiloteE** [comment]
Closing this as there has not been a reply. Feel free to reopen if you can reproduce even with the newest development version.
