### ISSUE TITLE
Monocolor for icons 

### ISSUE THREAD

**Issue by yaqihou** [JabRef/jabref#7550]
JabRef version

JabRef 5.3--2021-03-17--d190268
Linux 5.8.18-050818-generic amd64 
Java 15.0.2 
JavaFX 16+8

on Ubuntu 20.04

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Set either the priority or read status, the icons are mono-color and the same all options, making them indistinguishable visually. (But the status in the source file is correctly set)

**Comment by tp-1000** [comment]
I will take a look if it's alright.

**Comment by Siedlerchr** [comment]
@tp-1000  Sure, that would be great. You find the corresponding Icons in the JabRefIcons Enum in IconTheme.java
You can show the columns in the main table by adding the column in the preferences -> Entry Table -> Enable special fields 
Then you can add:
Read status, Priority, Relevance to the list

**Comment by DaliSaddoud** [comment]
I might be able to do something about this, if it's alright.

**Comment by tp-1000** [comment]
I'm pretty sure it will be resolved by #7552 and #7550 requires no further action.

**Comment by Siedlerchr** [comment]
Yep. The group ui PR fixes this as will. 
However, thanks for your interest. There are still enough other open issues...

**Comment by tobiasdiez** [comment]
Thanks to @mohit038 this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
