### ISSUE TITLE
Reformat all entries on save

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#756]
I would like to have the ability to reformat all entries in a bib file (since otherwise the whole entry is marked as a change in version control instead of the one line which actually changed).

How should this feature be implemented?

1. As a cleanup job (marking every entry as a change so that they are rewritten on save)
2. As an option for the save process

**Comment by koppor** [comment]
This somehow refs #720 as save actions are already implemented #716. A workaround would be to add a NOOP formatter, wouldn't it? We are aware that the whole entry changed, but it could not be implemented better and we thought it was a good compromise to keep all other existing entries as is when modifying one entry only.

**Comment by tobiasdiez** [comment]
Now implemented with #718 as an option under preferences.
