### ISSUE TITLE
Support of hidden fields

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#759]
When maintaining a bibliography, one often has fields such as `editor` and `url`, which one wants to keep but not published in the paper. Until we support multiple bibtex files per paper (see #160), we should offer to hide/unhide fields for `bibtex`. The assumption is that the paper authors do not want to change the `bst` file, but simply use `bibtex`.

Proposal: Introduce `_` as prefix of the key to indicate that the field should be displayed in JabRef, but not typeset by bibtex.

**Update** Some BibTeX tools seem to use "OptBooktitle" to hide the book title.

### UI
- render field name in different color when hidden
- right click on field: hide/unhide
- cleanup: unhide all entries

This somehow refs #574, but this here is a different thing.

With the third point, I meant an additional cleanup operation at the following dialog:

![grabbed_20160427-082223](https://cloud.githubusercontent.com/assets/1366654/14843524/3fbba114-0c51-11e6-939c-a22a39877c4a.png)

**Comment by oscargus** [comment]
Isn't the problem that this is really needed per entry (type)?

**Comment by simonharrer** [comment]
Hm, I do not like this with the underscore. Why not introduce a mechanism which allows to have a .min.bib file which has predefined entry fields missing?

**Comment by tobiasdiez** [comment]
There is already a RemoveFieldFormatter (or cleanup job, not sure about the naming). Thus creating a UI for it would make it very simple to remove certain fields on cleanup. 

(Or just use biblatex and remove the fields in latex...even simpler)

**Comment by ayanai1** [comment]
Our featureteam is going to take care of this issue.

**Comment by tobiasdiez** [comment]
@ayanai1 please note that with the recent advantages in the cleanup procedure the removal of certain fields is already possible. So this could be the starting point to implement the suggestion by @simonharrer.

**Comment by koppor** [comment]
I think, it is easier to teach users to use one bib file instead of two bib files. - Two bib files (`.full` and `.min`) are proposed at #160.
