### ISSUE TITLE
Copy pasting freezes jabref

### ISSUE THREAD

**Issue by abiy-tasissa** [JabRef/jabref#7605]
On Windows 10, JabRef 5.2 freezes (unable to respond), when trying to paste onto the search box. I have no similar issues with 5.1, which I reverted to due to this behavior. The version for java is: version 8 update 281

**Comment by Siedlerchr** [comment]
Thanks for the report. This issue is fixed in the latest development version. https://builds.jabref.org/main/

**Comment by abiy-tasissa** [comment]
Thank you! I will check the latest version.

**Comment by abiy-tasissa** [comment]
@Siedlerchr Thank you for the help, I have used the latest development version and the freezing issue is no longer a problem.
