### ISSUE TITLE
JabRef 5.2 not starting properly...

### ISSUE THREAD

**Issue by BPollicino** [JabRef/jabref#7607]
Hi everybody, I'm using JabRef 5.2 in combination with TeXStudio. It worked without any problems until last week. When I start JabRef either via Desktop Shortcut or from a *.bib file, it shows up in my taskbar and i can see a window of JabRef after pressing Win+Tab but i can't see the window anywhere. I already checked if it maybe slipped onto a 2nd desktop or if I can push it to my desktop by navigating the window using Win+(Arrows). Neither of those attempts worked out.
I tried reinstalling the program several times but that didnt help either.

Maybe somebody has had the same problem as well and can help me. I'll attach a photo of the window that shows up.

Best Regards

![jabref_2](https://user-images.githubusercontent.com/62886054/113511274-5971e400-955f-11eb-83ae-21db63d96ed5.png)
![jabref](https://user-images.githubusercontent.com/62886054/113511225-16b00c00-955f-11eb-847c-f7b4ce7778db.png)

**Comment by calixtus** [comment]
You could try to reset all the user preferences by using the command line argument `-d all`. This should restore the jabref preferences to the default values. Your database shouldn't be affected, but as ever: please always backup your data.

E.g. `jabref.exe -d all`

**Comment by BPollicino** [comment]
Hi calixtus, thank you for your answer. Resetting the defaults did not work but it pointed me into the right direction. Somehow the window was stuck outside my screen. I was now able to bring it back by holding Shift and right-click on the taskbar icon to choose "Maximize" and it reappeared!

In case somebody has the same problem, I'll attach the link.

https://www.technipages.com/bring-off-screen-window-back-onto-screen#:~:text=In%20Windows%2010%2C%208%2C%207,back%20and%20select%20%E2%80%9CMove%E2%80%9C.

Thank you again and enjoy your easter!
