### ISSUE TITLE
Column Width goes crazy - Program becomes completely unusable

### ISSUE THREAD

**Issue by apacha** [JabRef/jabref#7608]
JabRef version:

JabRef 5.2--2020-12-24--6a2a512
Mac OS X 10.16 x86_64 (same behavior on Windows)
Java 15.0.1

I have a massive issue with JabRef and changing the column width, see this Video for what is happening:

https://www.youtube.com/watch?v=dDVWWaa23f0

1. Type something into the search box
2. Change column width
3. Program goes nuts

Can anyone help me!? I have absolutely no idea what is going on, but the program can no longer be used like that.

**Comment by Siedlerchr** [comment]
Hi, as stated in the issue template, please always try the latest dev version from https://builds.jabref.org/main/ 
Remember to make a backup of your library before trying out the new version
