### ISSUE TITLE
Question: Installation of current dev version

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#7624]
The JabRef webpage https://www.jabref.org/#download currently links to the "Master" branch for the latest development version (
https://builds.jabref.org/master/). That version, however, is from 29/03/2021. The version on the "Main" branch, on the other hand, is from 12/04/2021 (https://builds.jabref.org/main/). Is the "Main" branch supposed to represent the new master development branch? Or is this meant as the alternative version allowing for non-duplicate groups (https://github.com/JabRef/jabref/pull/7558)?

I like to test the new development version from time to time, but I prefer to stick to major branches. Which one should a simple user use, if they want to test the current development version?

**Comment by Siedlerchr** [comment]
Thanks for your feedback. We recently renamed "master" to [main](https://github.com/github/renaming) . So the "main" is always the newest one. However, we forgot to rename the terminology at the builds.jabref.org 

cc @koppor can you update the builds.jabref.org index ?

**Comment by AEgit** [comment]
Cheers!
