### ISSUE TITLE
Unable to download arXiv PDFs if Title contains curly brackets

### ISSUE THREAD

**Issue by vlawhern** [JabRef/jabref#7633]
JabRef version 5.2/5.3 (developmental) on Ubuntu 18.04 with the portable binary

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists
- I've tested this on the following build and the bug persists: https://builds.jabref.org/main/JabRef-5.3-portable_linux.tar.gz

JabRef is unable to download arXiv links if there are curly braces in the article title. For example, the following BibTeX source works just fine when searching for the full text online:

```
@Article{zhang_machine_2021v2,
  author  = {Zhang, Ruohan and Guo, Sihang and Liu, Bo and Zhu, Yifeng and Hayhoe, Mary and Ballard, Dana and Stone, Peter},
  journal = {arXiv:2010.15942v2 [cs]},
  title   = {Machine versus Human Attention in Deep Reinforcement Learning Tasks},
  year    = {2021},
  month   = feb,
  url     = {http://arxiv.org/abs/2010.15942v2},
}
```

However this version of the BibTeX source fails, giving a "No full text document found..." when trying to look up the document online and download the PDF:

```
@Article{zhang_machine_2021v2,
  author  = {Zhang, Ruohan and Guo, Sihang and Liu, Bo and Zhu, Yifeng and Hayhoe, Mary and Ballard, Dana and Stone, Peter},
  journal = {arXiv:2010.15942v2 [cs]},
  title   = {Machine versus {Human} {Attention} in {Deep} {Reinforcement} {Learning} {Tasks}},
  year    = {2021},
  month   = feb,
  url     = {http://arxiv.org/abs/2010.15942v2},
}
```
with the only difference being the curly braces around the words that are capitalized. 

An easy fix for this is to simply delete the braces (the easiest way I've found is to use "Find and Replace" to delete the braces, limiting it to the Title field) but it would be great if it worked regardless of how the title is formatted. 

The reason this comes up for me a lot is because I use a third-party resource to pull in several BibTeX sources at once and it automatically puts the braces around capitalized words... I currently have to remove the braces for every article manually.

**Comment by Pikayue11** [comment]
Hi,  I think I have reproduced this bug and I'm intersting in this issue, could I try to fix it?

**Comment by Siedlerchr** [comment]
Sure, go ahead.

**Comment by Pikayue11** [comment]
Ok, thanks!
