### ISSUE TITLE
Failing Test: Change Test PDF Url for useGetRequestIfHeadRequestHasNoContentType

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#764]
I noticed a failing test on my system and found out that this happened because I had no access to the journal/pdf full text. The Test  returned the webpage instead of the pdf.

` String pdfUrl = "http://iopscience.iop.org/article/10.1088/0004-637X/815/1/23/pdf";
        assertEquals("application/pdf", MimeTypeDetector.getMimeType(pdfUrl));`

I suggest using the following link, because this one is OpenAcces and therefore should be 
http://iopscience.iop.org/article/10.1088/1367-2630/18/2/021001/pdf

That would stop the test from failing.
Regards
Siedlerchr

**Comment by oscargus** [comment]
Sounds good! That test failing every now and then is quite annoying...

(Or we pick one of my papers on Academia.edu and mess up the download stats... ;-))

**Comment by tobiasdiez** [comment]
I would even vote for moving the pdf to some `jabref.org/testing` folder. In this way we are completely independent from other websites. Might be that this test case is not the only one which depends on internet resources (besides the fetchers of course).

**Comment by Siedlerchr** [comment]
@tobiasdiez  That sounds even better, as the Test-case does only check the MimeType, it can be an arbitary PDF, I will look through other tests that do not depend on specific fetchers.

**Comment by tobiasdiez** [comment]
@koppor Can you please add the downloaded files in the tests to jabref.org/somesubfolder (and reduce their size if possible)?

**Comment by oscargus** [comment]
Probably we should create our own test PDF:s to avoid any copyright
hassle... For mime detection any would do I guess. What else is tested?

**Comment by stefan-kolb** [comment]
@Siedlerchr I reworked all tests of `MimeTypeDetectorTest`. Is your problem solved by this?!

**Comment by Siedlerchr** [comment]
@stefan-kolb  Works now.
