### ISSUE TITLE
Wrong path to TeXstudio

### ISSUE THREAD

**Issue by dbitouze** [JabRef/jabref#7641]
JabRef version 5.2 on Windows 10

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists: in fact not actually relevant since I could try it on Linux, but not on Windows (see below).

Students of mine, who are using Windows 10 (I'm a Linux user) experienced a problem when they tried to push citations to TeXstudio: it was impossible until we change the path to TeXstudio from `C:\Program Files (x86)\texstudio` to its, nowadays, default location `C:\Program Files\texstudio`.

**Comment by Siedlerchr** [comment]
Thanks for the report. The code for the path detection lies here https://github.com/JabRef/jabref/blob/bb011c9313367a28990ae213b3920fe6cd10d1dc/src/main/java/org/jabref/gui/desktop/os/Windows.java#L27-L37

The problem is that it doesn't check for the existence of the file/executable inside the Programs x86/Program Files and therefore incorrectly assumes it's located in the x86 folder.

**Comment by Gan-Cheng** [comment]
Hi, I think this problem is interesting and not so difficult, could I try to fix it?

**Comment by Siedlerchr** [comment]
@Gan-Cheng Sure, go ahead! Make sure to check out the contribution guide for getting started https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md

**Comment by Gan-Cheng** [comment]
Thanks. By the way, I wonder whether it is required to implement the function of searching program path, or just judging existence of target path in `program files` and `program files(x86)` is Okay.

**Comment by Siedlerchr** [comment]
Thanks to @Gan-Cheng  this issue should now be resolved in the latest main version 


We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by dbitouze** [comment]
> Thanks to @Gan-Cheng this issue should now be resolved in the latest main version

Many thanks to both of you.

> We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you.

Unfortunately, I cannot test because I don't own any Windows machine. But I'll report troubles if students of mine have again such a trouble.
