### ISSUE TITLE
Latest dvp snapshot: main, not master!

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7650]
In https://builds.jabref.org/ ,
It is specified "Please head to **master** for the latest development snapshot":
![Capture d’écran du 2021-04-19 20-29-34](https://user-images.githubusercontent.com/6931104/115285362-0d719280-a14e-11eb-8c97-a8481a2993d7.png)

After recent changes, the latest development snapshot is in **main**.

**Comment by AEgit** [comment]
See https://github.com/JabRef/jabref/issues/7624

**Comment by Siedlerchr** [comment]
This should be fixed now!
