### ISSUE TITLE
Springer.com: Export to JabRef!

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#766]
For your information:
Among its export citation formats, Springer offers "JabRef".
See http://link.springer.com/chapter/10.1007/978-3-319-19800-2_36
(right column ; Reference tools)

It returns a bib file. And this bib file seems identical if you choose JabRef, Mendeley or BibTex.
Basically, that means some people think it is worth mentioning JabRef directly.
Congratulation to JabRef development team and its users community!

**Comment by matthiasgeiger** [comment]
![Awesome!](http://i.imgur.com/red2wc6.jpg)

:wink:

**Comment by stefan-kolb** [comment]
Nice :smile: :+1: :beers:

**Comment by stefan-kolb** [comment]
@JabRef/developers Take a look at this!

**Comment by oscargus** [comment]
:+1:

**Comment by simonharrer** [comment]
:+1:

**Comment by tobiasdiez** [comment]
Very nice!

**Comment by koppor** [comment]
![grabbed_20160203-173646](https://cloud.githubusercontent.com/assets/1366654/12793535/67507330-cab1-11e5-919c-ab9ba9c34554.png)
