### ISSUE TITLE
Unable to download some arXiv links if the "eprint" field is missing

### ISSUE THREAD

**Issue by vlawhern** [JabRef/jabref#7660]
JabRef version 5.3 developmental portable JAR 

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

I am unable to automatically download some arXiv links if the "eprint" field is missing. For example, this BibTeX reference works:

```
@Article{booth_bayes-trex_2020,
  author        = {Serena Booth and Yilun Zhou and Ankit Shah and Julie Shah},
  journal       = {arXiv:2002.10248v4 [cs]},
  title         = {Bayes-TrEx: a Bayesian Sampling Approach to Model Transparency by Example},
  year          = {2020},
  month         = dec,
  archiveprefix = {arXiv},
  eprint        = {2002.10248},
  url           = {http://arxiv.org/abs/2002.10248v4},
}
```

but this one doesn't:

```
@Article{booth_bayes-trex_2020,
  author        = {Serena Booth and Yilun Zhou and Ankit Shah and Julie Shah},
  journal       = {arXiv:2002.10248v4 [cs]},
  title         = {Bayes-TrEx: a Bayesian Sampling Approach to Model Transparency by Example},
  year          = {2020},
  month         = dec,
  archiveprefix = {arXiv},
  url           = {http://arxiv.org/abs/2002.10248v4},
}
```

with the only thing different is the eprint field.

Interestingly this doesn't always happen; most of the time JabRef can fetch the arXiv PDF correctly without the eprint field, but for some reason JabRef fails to get other arXiv PDFs like the one above. I suspect it's a formatting issue similar to Issue #7633. It's not always consistent, but it feels like paper titles with colons appear to trigger this behavior more than others.

Perhaps it can be set when the url field is provided that JabRef could use that as a fallback to download the PDF..

**Comment by tobiasdiez** [comment]
This can be fixed by runing the [EprintCleanup](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/cleanup/EprintCleanup.java) on a copy of the entry at https://github.com/JabRef/jabref/blob/2af578f6a9311dace0ec3270e678cc3ae31bad8e/src/main/java/org/jabref/logic/importer/fetcher/ArXiv.java#L118 before proceeding to get the arXiv id from the eprint field.

**Comment by JavuesZhang** [comment]
Hi, I think I have solved this problem with the help of @tobiasdiez . I will open a PR later.

**Comment by tobiasdiez** [comment]
Thanks to @JavuesZhang this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
