### ISSUE TITLE
Creating entry via mEDRA (using DOI) doesn't work

### ISSUE THREAD

**Issue by sparusaurata** [JabRef/jabref#7673]
When I try to create a new entry by giving a DOI with the mEDRA service, an error is raised:

![image](https://user-images.githubusercontent.com/17063513/116244196-fcd1a580-a767-11eb-9a89-f77d06222e80.png)

… even if the DOI resolver at mEDRA.org finds the reference.

- JabRef version 5.2 on Linux Mint 20.1.
- Bug reproduced [here](https://discourse.jabref.org/t/error-when-creating-and-entry-via-doi/2679/4).

**Comment by Siedlerchr** [comment]
Thanks for your report. It seemed maybe some temporary issue, or might be specific to your DOI. I tested a few DOIs with medra, but works for me. 
Can you please post your DOI here you tried?

**Comment by mlep** [comment]
I tried with this one: 10.5194/npg-24-569-2017
JabRef replies that mEDRA did not find any entry, but works on mEDRA website.

JabRef 5.3--2021-04-26--add694a
Linux 4.19.0-16-amd64 amd64 
Java 15.0.2 
JavaFX 16+8

**Comment by Siedlerchr** [comment]
Just use the normal DOI fetcher. JabRef will automatically check if the DOI belongs to medra or not.
However, yours belongs to crossref and JabRef gets a HTTP 504 error, gateway timeout, so a problem on the CrossRef site. 
Totally odd.

**Comment by sparusaurata** [comment]
> Can you please post your DOI here you tried?
I tried this one: `10.1016/0304-3975(95)00073-6`.

> Just use the normal DOI fetcher.
This what I initially wanted to do, but it didn't work (see [here](https://discourse.jabref.org/t/error-when-creating-and-entry-via-doi/2679)) so I used mEDRA as indicated [in the docs](https://docs.jabref.org/collect/add-entry-using-an-id).

**Comment by Siedlerchr** [comment]
I cannot reproduce this. The normal DOI fetcher works fine for me with your DOI. Mabye it was a temporary issue at CrossRef

**Comment by Ryyyc** [comment]
I ran some tests:

<br>

mEDRA url: https://data.medra.org/10.3303/CET2184030
+ GET request without http header "Accept: application/vnd.citationstyles.csl+json", it has been redirected many times, and the resource website can be accessed normally(in the browser).
+ GET request with http header "Accept: application/vnd.citationstyles.csl+json", it directly gets the response result we want.
```bash
C:\Users\ruan>curl -H "Accept: application/vnd.citationstyles.csl+json" https://data.medra.org/10.3303/CET2184030
{"type":"article-journal","author":[{"literal":"Salvoni Daniela"},{"literal":"Boselli Antonella"},{"literal":"Sannino Alessia"},{"literal":"Parlato Loredana"},{"literal":"Ejrnaes Mikkel"},{"literal":"Chengjun Zhang"},{"literal":"You Lixing"},{"literal":"Wang Xuan"},{"literal":"Amoruso Salvatore"},{"literal":"Pepe Giovanni Piero"}],"issued":{"date-parts":[[2021,4]]},"container-title":"Chemical Engineering Transactions","DOI":"10.3303\/CET2184030","page":"175-180","page-first":"175","publisher":"AIDIC: Italian Association of Chemical Engineering","publisher-place":"IT","title":"Demonstration of Atmospheric Lidar Measurement in the Infrared Wavelength Domain with a Superconducting Nanowire Single Photon Detector","URL":"https:\/\/doi.org\/10.3303\/CET2184030","volume":"84"}
```

<br>

mEDRA url: https://data.medra.org/10.5194/npg-24-569-2017
+ GET request without http header "Accept: application/vnd.citationstyles.csl+json", it has been redirected many times, and the resource website can be accessed normally(in the browser)(It redirected to https://doi.org/10.5194/npg-24-569-2017 and then to https://npg.copernicus.org/articles/24/569/2017/).
+ GET request with http header "Accept: application/vnd.citationstyles.csl+json", its response is 404 not found.

<br>

Maybe this is a problem with mEDRA's API?

**Comment by Siedlerchr** [comment]
@Ryyyc  You can test also with 'Accept: application/x-bibtex'

**Comment by Ryyyc** [comment]
> @Ryyyc You can test also with 'Accept: application/x-bibtex'

The response of test https://data.medra.org/10.3303/CET2184030 with 'Accept: application/x-bibtex' is still `200 OK`.
```bash
C:\Users\ruan>curl -I -H "Accept: application/x-bibtex" https://data.medra.org/10.3303/CET2184030
HTTP/1.1 200 OK
Date: Fri, 07 May 2021 15:22:53 GMT
Server: Apache-Coyote/1.1
Cache-Control: no-transform, max-age=60
Access-Control-Allow-Origin: *
Vary: Accept
Content-Type: application/x-bibtex;charset=UTF-8


C:\Users\ruan>curl -H "Accept: application/x-bibtex" https://data.medra.org/10.3303/CET2184030
 @article{Salvoni Daniela_Boselli Antonella_Sannino Alessia_Parlato Loredana_Ejrnaes Mikkel_Chengjun Zhang_You Lixing_Wang Xuan_Amoruso Salvatore_Pepe Giovanni Piero_2021, place={IT}, title={Demonstration of Atmospheric Lidar Measurement in the Infrared Wavelength Domain with a Superconducting Nanowire Single Photon Detector}, volume={84}, url={https://doi.org/10.3303/CET2184030}, DOI={10.3303/CET2184030}, journal={Chemical Engineering Transactions}, publisher={AIDIC: Italian Association of Chemical Engineering}, author={Salvoni Daniela and Boselli Antonella and Sannino Alessia and Parlato Loredana and Ejrnaes Mikkel and Chengjun Zhang and You Lixing and Wang Xuan and Amoruso Salvatore and Pepe Giovanni Piero}, year={2021}, month={Apr}, pages={175–180} }
```
<br>

The response of test https://data.medra.org/10.5194/npg-24-569-2017 with 'Accept: application/x-bibtex' is still `404 Not Found`.
```bash
C:\Users\ruan>curl -I -H "Accept: application/x-bibtex" https://data.medra.org/10.5194/npg-24-569-2017
HTTP/1.1 404 Not Found
Date: Fri, 07 May 2021 15:22:40 GMT
Server: Apache-Coyote/1.1
Access-Control-Allow-Origin: *
```

**Comment by Siedlerchr** [comment]
I think this is something on the Medra/DOI publisher side. I had this problem with other EU publications as well, they did not return bibtex but html from the website despite the Accept header. Maybe you can contact the support and ask them
