### ISSUE TITLE
Feature Required: combine and save the "clicked" references in JabRef into a ".bib" file

### ISSUE THREAD

**Issue by LePingKYXK** [JabRef/jabref#7676]
First of all, I want to thank you for developing JabRef. It is really a great tool for collecting, managing and citing references.

I have a big BibTeX file collected by JabRef. When citing, it is convenient to click one of the references in the JabRef GUI. However, when compiling, the output PDF file could not show references, because of without a ".bib" file with the same directory of the ".tex" file. 

I was wondering if it is a way to combine and save all the clicked references in JabRef into a ".bib" file.

Looking forward to hearing from you.

**Comment by Siedlerchr** [comment]
Hi,

this is already possible. Just mark the ones you want to copy/export. In the Menu ->  File ->  Export -> Save selected as plain bibtex 

Hint: You can also change the path in the tex file to point to your bib file 
https://tex.stackexchange.com/questions/6805/bib-library-file-in-a-different-directory-how-to-use-mendeley-centralised-b

**Comment by mlep** [comment]
An workflow that maybe helpful: first, compile your LaTeX document with your big .bib file. Then, let JabRef extract the cited references into a dedicated bib file (Menu Tools ->  New sublibrary based on AUX file...)

**Comment by LePingKYXK** [comment]
> 
> 
> An workflow that maybe helpful: first, compile your LaTeX document with your big .bib file. Then, let JabRef extract the cited references into a dedicated bib file (Menu Tools -> New sublibrary based on AUX file...)

Hi,
Thank you for your reply. It works for me.
