### ISSUE TITLE
Imported settings are resetting themself

### ISSUE THREAD

**Issue by mpgvalli** [JabRef/jabref#768]
My imported settings are resetting themselves, if I restart the computer after beeing shut down for about 10 hours. The .bib file and settings file is on a network drive. All PCs are running Windows 7. JabRef v3.2.
If i restart JabRef in the morning, it shows the default settings although I imported other settings the day before.
The system also gets backuped every evening. Could that be the problem?
My second question belongs to the settings, too. If I import settings, most of the changes get applied but the required fields/ optional fields etc stay the same. I have to restart Jabref to update these fields.

Beside that, I really like JabRef and your new version 3.2!

**Comment by stefan-kolb** [comment]
As for your second question: A restart of JabRef for configuring the required/optional fields is required as far as I know.

**Comment by matthiasgeiger** [comment]
Concerning the first question: On windows machines the settings are stored in the Windows Registry.
On importing a set of preferences the preference content is written once to the registry - so it is no problem where the file was stored during import. After the initial import the file will not be read again.

> The system also gets backuped every evening.

The creation of backups is no problem. Or do you mean that your system is restored to a backuped state each day? (Which is the case in some strict environments such as PC pools in universities.)

**Comment by mpgvalli** [comment]
@stefan-kolb But is there a way, updating these fields without restarting JabRef?
@matthiasgeiger No it's just a creating a normal backup. I Don't really now much about the registry, but is it possible that the preferences in the registry are getting cleared every day, beacause I use a network user? And is there a option to select a default setting file, which loads while launching JabRef? If not, that would be a really nice feature! Ich hoffe du hast mein Problem verstanden, ansonsten kann ich dir auch auf deutsch schreiben.

**Comment by stefan-kolb** [comment]
As far as I know, it is not possible to update the fields without restarting. At least it is not implemented right now.

**Comment by tobiasdiez** [comment]
@mpgvalli You can try to use the memory stick mode which does not write the preferences in the registry but in a file (see Options -> Preferences -> General -> "Load and save preferences from/to jabref.xml"). Maybe this helps.

**Comment by mpgvalli** [comment]
@tobiasdiez Ok thanks a lot, I'll try it. In which folder can I find this new jabref.xml file with the references?

**Comment by oscargus** [comment]
I'm tempted to say that something has changed... Or at least the font size preferences was reset just now... Not sure why and what happened though.

**Comment by mpgvalli** [comment]
Thanks everyone for the help, but I found the problem by myself... The network account, which was running JabRef, was logged in on two other copmputers, too. If I use a normal account, which is only loggend in on one computer it works fine. -close please

**Comment by matthiasgeiger** [comment]
Thanks for your feedback!
