### ISSUE TITLE
Are some scripts duplicates?

### ISSUE THREAD

**Issue by ju-sh** [JabRef/jabref#7682]
There are two scripts that seems to be doing similar stuff in the [scripts/](https://github.com/JabRef/jabref/tree/main/scripts) directory: `bib-file-generator.py` and `bib-file-generator.rb`.

Are both being used (couldn't find where they were being used)?

Wasn't sure if some scripts were abandoned scripts that are no longer used.

If they are still used, wouldn't it be better to use the same language? Why use both ruby and python?

**Comment by Siedlerchr** [comment]
Hi,
those scripts are not really used. They are just helpers if you need to generate a huge bib file for testing with many thousand entries

**Comment by ju-sh** [comment]
Okay. Just wanted to attract some attention to the scripts in case some of them had got irrelevant and can be removed or something. :-)
