### ISSUE TITLE
Don't require a restart after preference changes

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#770]
Some changes of preferences require a restart of jabref. In the ideal case changes would apply immediately. 

This concerns in particular:
- required/optional fields as pointed out in #768.

**Comment by matthiasgeiger** [comment]
One note: 
Most pref changes which require restarts are UI related (e.g., language change, switch to Bib(La)TeX mode, ...) as complete parts of the UI have to be changed/repainted. So an intermediate solution which does not require a user triggered restart would be to dispose and recreate the whole UI automatically.

**Comment by tobiasdiez** [comment]
I think we don't need a special issue to keep track of this (when we rework the preferences / move enough things to javafx this will come up as a natural by-product).
