### ISSUE TITLE
Plain text parser yield connection error

### ISSUE THREAD

**Issue by ThomasJorna** [JabRef/jabref#7701]
JabRef 5.2--ArchLinux--1
Linux 5.11.16-arch1-1 amd64 
Java 15.0.2

Steps to reproduce:

1.  Enter double spaced lines of plain text into the Jabref plain text parser.
2. Click "Add to current library"
3. Get the error: "There are connection issues with a JabRef server. Detailed information: Could not process citation. Connection refused."

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Your text is being parsed...
There are connection issues with a JabRef server. Detailed information: Could not process citation. Connection refused.
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
JabRef is up-to-date.
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css
Enabling live reloading of /usr/share/java/jabref/resources/main/org/jabref/gui/Dark.css
Your text is being parsed...
There are connection issues with a JabRef server. Detailed information: Could not process citation. Connection refused.
```

</details>

**Comment by ThomasJorna** [comment]
For reference, this is the text being pasted, although it does not appear to be text dependent.
```
Ayer, A. J. 1946. Language, Truth and Logic (second edition). London: Gollancz.

Blackburn, Simon. 1993. Essays in Quasi-Realism. Oxford: Oxford University Press.

Boyd, Richard. 1988. “How to be a Moral Realist”. In Geoffrey Sayre-McCord, ed., Essays on Moral Realism. Ithaca: Cornell University Press.

Brink, David. 1989. Moral Realism and the Foundations of Ethics. Cambridge: Cambridge University Press.

Copp, David. 2001. “Realist-Expressivism: A Neglected Option for Moral Realism”. Social Philosophy and Policy 18: 1-43.

Dworkin, Ronald. 1996. “Objectivity and Truth: You’d Better Believe It”. Philosophy and Public Affairs 25: 87-139.

Edwards, Douglas. 2014. Properties. Cambridge: Polity Press.

Enoch, David. 2006. “Agency, Shmagency: Why Normativity Won’t Come from What Is Constitutive of Action”. Philosophical Review 115: 169-98.

Enoch, David. 2011. Taking Morality Seriously. Oxford: Oxford University Press.

Finlay, Stephen. 2014. Confusion of Tongues. Oxford: Oxford University Press.

Gibbard, Allan. 2003. Thinking How To Live. Cambridge, Mass.: Harvard University Press.

Horgan, Terence, and Mark Timmons. 1991. “New Wave Moral Realism Meets Moral Twin Earth”. Journal of Philosophical Research 16: 447-65.

Jackson, Frank. 1998. From Metaphysics to Ethics. Oxford: Oxford University Press.

Joyce, Richard. 2001. The Myth of Morality. Cambridge: Cambridge University Press.

Joyce, Richard. 2016. “Moral Anti-Realism”. Stanford Encyclopedia of Philosophy, https://plato.stanford.edu/archives/win2016/entries/moral-anti-realism/.

Korsgaard, Christine. 2008. The Constitution of Agency. Oxford: Oxford University Press.

Lenman, James, and Matthew Lutz. 2018. “Moral Naturalism”. Stanford Encyclopedia of Philosophy, https://plato.stanford.edu/archives/fall2018/entries/naturalism-moral/.

Lutz, Matt. 2014. “The ‘Now What’ Problem for Error Theory”. Philosophical Studies 171: 351.

Mackie, J.L. 1977. Ethics: Inventing Right and Wrong. Harmondsworth: Penguin.

Nagel, Thomas. 1997. The Last Word. Oxford: Oxford University Press.

Olson, Jonas. 2014. Moral Error Theory. Oxford: Oxford University Press.

Ridge, Michael. 2014. Impassioned Belief. Oxford: Oxford University Press.

Ridge, Michael. 2019. “Moral Non-Naturalism”. Stanford Encyclopedia of Philosophy, https://plato.stanford.edu/archives/fall2019/entries/moral-non-naturalism/.

Scanlon, T.M. 2014. Being Realistic about Reasons. Oxford: Oxford University Press.

Schroeder, Mark. 2007. Slaves of the Passions. Oxford: Oxford University Press.

Schroeder, Mark. 2008. Being For. Oxford: Oxford University Press.

Schroeder, Mark. 2010. Noncognitivism in Ethics. Abingdon: Routledge.

Shafer-Landau, Russ. 2003. Moral Realism. Oxford: Oxford University Press.

Streumer, Bart. 2017. Unbelievable Errors. Oxford: Oxford University Press.

Van Roojen, Mark. 2018. “Moral Cognitivism vs. Non-Cognitivism”. Stanford Encyclopedia of Philosophy, https://plato.stanford.edu/archives/fall2018/entries/moral-cognitivism/.

Wright, Crispin. 1992. Truth and Objectivity. Cambridge, Mass.: Harvard University Press.
```

**Comment by ThomasJorna** [comment]
Seems that when starting it already fails to connect, might be a me issue.

``java
➜  ~ jabref --debug
16:32:55.645 [JavaFX Application Thread] DEBUG org.jabref.logic.logging.JabRefLogger - Showing debug messages
16:32:55.671 [JavaFX Application Thread] DEBUG org.jabref.logic.remote.client.RemoteClient - Could not ping server at port 6050
java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:660) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
	at java.net.Socket.connect(Socket.java:648) ~[?:?]
	at org.jabref.logic.remote.client.RemoteClient.openNewConnection(RemoteClient.java:67) ~[JabRef-5.2.jar:?]
	at org.jabref.logic.remote.client.RemoteClient.ping(RemoteClient.java:29) ~[JabRef-5.2.jar:?]
	at org.jabref.gui.JabRefMain.handleMultipleAppInstances(JabRefMain.java:96) ~[JabRef-5.2.jar:?]
	at org.jabref.gui.JabRefMain.start(JabRefMain.java:66) ~[JabRef-5.2.jar:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846) ~[javafx-graphics-15-linux.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455) ~[javafx-graphics-15-linux.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx-graphics-15-linux.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx-graphics-15-linux.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx-graphics-15-linux.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[javafx-graphics-15-linux.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277) ~[javafx-graphics-15-linux.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
On a possibly related issue, using [the example in the docs](https://docs.jabref.org/collect/newentryfromplaintext) I get a `java.net.ConnectException: Connection refused` from

https://github.com/JabRef/jabref/blob/3fb11761ad2927b65a3660098c2dba9d0418bc3a/src/main/java/org/jabref/logic/importer/fetcher/GrobidCitationFetcher.java#L49

**Comment by Siedlerchr** [comment]
Seems lke our Grobid server is down again. @LinusDietz  @koppor

**Comment by LinusDietz** [comment]
@Siedlerchr Server is up again.
