### ISSUE TITLE
Cleanup action: some fields in random order

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7710]
JabRef 5.3--2021-05-05--a3f093d
Linux 4.19.0-16-amd64 amd64 
Java 16.0.1 
JavaFX 16+8

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

In the cleanup actions (Menu `Quality -> Cleanup entries`, and Menu `Library -> Library properties`), most of the field values in the drop-down menu are in alphabetical order, but some are quite misplaced, making them difficult to find:
![ksnip_20210507-143014](https://user-images.githubusercontent.com/6931104/117450237-4167f880-af41-11eb-8564-3f7c6917f116.png)
It would be more convenient if these fields were listed in alphabetical order.

My understanding is that the first three in the list (see below) are voluntarily placed at the top because of their general purpose or their expected proeminent use. 
![ksnip_20210507-143040](https://user-images.githubusercontent.com/6931104/117450228-3dd47180-af41-11eb-8c9a-cd7ec087e8e0.png)
If so, a separator would be nice between `Citationkey` and `Abstract`.

**Comment by dateri** [comment]
I think this is because `java.util.LinkedHashSet` is used to store these fields. I will new a pr about it.

**Comment by SuXiChangZhen** [comment]
I also worked on this issue, so I put my modification in my pr. But I am not sure if the separator should be added.

**Comment by Siedlerchr** [comment]
Thanks to  @dateri the fields are now sorted alphabetically again

**Comment by mlep** [comment]
Indeed, the issue is solved now. Thank you @dateri for your contribution to JabRef. I wish you can find other interesting issues to solve!
