### ISSUE TITLE
Some more fields in random order

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7716]
JabRef 5.3--2021-05-08--4f398d8
Linux 4.19.0-16-amd64 amd64 
Java 16.0.1 
JavaFX 16+8

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

I have found some other drop down menus where fields are not sorted (like in issue #7710):
- List of fields (i.e. exact same list as issue #7710):
    - Menu `Library -> Library properties`, in section `Save sort order`: Primary, secondary and tertiary sort criteria.
    - Menu `Options -> Preferences`, in tab `File`, section `Export sort order`: Primary, secondary and tertiary sort criteria.
    - Menu `Options -> Preferences`, in tab XMP metadata: drop-down list of the column `Field name`.

- List of actions:
    - Menu `Library -> Library properties`, in section `Save actions`, drop-down list of the column `Formatter name`.
    - Menu `Quality -> Cleanup actions`, in section `Enable field formatters`, drop-down list of the column `Formatter name`.

- Menu `Library -> New entry...`, drop-down list of `ID type`.

- Menu `Options -> Preferences`, in tab `General`, drop-down list of `Language`.

**Comment by mlep** [comment]
Ping @dateri, maybe?

**Comment by dateri** [comment]
Yeah, I think they need be also sorted. I'll fix them soon.

**Comment by Siedlerchr** [comment]
I think for new entry the ID list should be ordered by things that are used the most first. Doi should be on top. 

Same applies to formatter.

**Comment by dateri** [comment]
@Siedlerchr maybe sort them by displayName is enough cause the number of types of formatter and ID list are not so large as the number of fields？And i have no idea about how to store the number of times they use (add a database?).

**Comment by mlep** [comment]
@Siedlerchr ID fetchers were mostly sorted (mEDRA is not)

**Comment by mlep** [comment]
@dateri Thank you for tackling this issue. I wish you will find some other interesting issues to solve in JabRef!
