### ISSUE TITLE
import hangs for ris files with "ER  - " field, also other bib files common from journal web sites

### ISSUE THREAD

**Issue by CodeSJS** [JabRef/jabref#7737]
JabRef version JabRef 5.3--2021-05-15--0a26d31
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8

- [X ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

Certain files I download from journals cause import to hang.  (I looked through other bug reports concerning "import hangs" and this seems to be different.  Apologies if duplicate.)  The problem was perfectly reproducible in 5.2.  In 5.3 some problem files **occasionally** load.  If you cannot reproduce the bug, please try opening the problem files 3 or 4 times.

With ris files the problem is clear.  When the ris file contains "ER - " as the last line, import (ctrl-I) hangs and I have to kill jabref and restart.  Removing the last line solves the problem.   This may be an illegal ris format, but many journal citation files end this way.  I have provided examples from J. Chem. Phys., J. Phys. Chem., WIREs Comput. Mol Sci., and Biophys. J.  It is interesting, but there is no problem opening such a file using right click, open with jabref.

Bib files from journals also give similar problems.  I delete portions of the file until jabref does not hang.  However, I have not pinned down the problem as I have with ris files.  Examples of both ris and bib problem files will be attached.

I cannot post a log file example.  When the import hangs and I have to "close program", the log is empty upon restart.

Several ris and bib files that cause problems are attached.  The ris files all contain the "ER - " last line.

[FilesThatCauseImportHangs.zip](https://github.com/JabRef/jabref/files/6488022/FilesThatCauseImportHangs.zip)

Thank you.

**Comment by Noname690** [comment]
I have reproduced this issue in the latest version . And I want try to fix it , could you give me some advise  , thank you @Siedlerchr

**Comment by Siedlerchr** [comment]
@Noname690  I would take a look at the RIS Importer and debug what happenns when the importer cones to this line.
You can also start with a Unit test to reproduce this

**Comment by CodeSJS** [comment]
How can I do this?

**Comment by Noname690** [comment]
![4T2~J6YMXU}9066${JQTB5G](https://user-images.githubusercontent.com/56827551/118786104-11671080-b8c4-11eb-8e80-85563cd06f29.png)
The entries after processing are like this , I think the problem may cause by that

**Comment by CodeSJS** [comment]
Yes, for ris files the “ER – “ at the end is the problem.  If one removes that last line it’s OK.

I have not been able to determine which line causes problems in the bib file.  In the past, I removed all non-essential without isolating which one was the problem.  I will work on removing lines one by one and try to isolate the problem with bib files.

Thanks for your work on Jabref!
  Sherwin

**Comment by Siedlerchr** [comment]
@CodeSJS  Thanks to @Noname690 this issue is now fixed in the latest development build http://builds.jabref.org/main

**Comment by CodeSJS** [comment]
Thanks!  I downloaded the latest build.  Jabref now imports every ris or bib file I saved as problem-causing.

Regards,
    Sherwin
