### ISSUE TITLE
Deprecated fields are not deprecated (in BibTeX mode)

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7757]
JabRef 5.3--2021-05-15--0a26d31
Linux 4.19.0-16-amd64 amd64 
Java 16.0.1 
JavaFX 16+8

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

For a library in BibTeX mode, if an entry of type `@Article` contains the field `month`, JabRef displays it in the tab `Deprecated fields`. In BibTeX, the field `month` is an optional field (see http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf on page 8). Hence, it should not be displayed as deprecated.
My guess is that the deprecated fields are displayed _as if the library was in biblatex mode_. And I believe the concept of deprecated field does not apply to BibTeX fields. Hence, the tab `Deprecated fields` should not even be displayed in BibTeX mode.

1. Create a bib file containing:
```
@Article{ostgaard2002,
  author = {Foo Bar},
  title =  {energy},
  year =   {2012},
  month = sep,
}
```
2. open it with JabRef (in BibTeX mode)
3. open the entry editor for this entry
==> The tab `Deprecated fields` is displayed and contains the field `Month`.

- Same in the entry type `@book` for the field `address` (it is an optional field).
- Same in the entry types `@phdthesis`, `@inproceedings`, and `@techreport` for the fields `address` and `month` (they are optional fields).
- Same in the entry type `@booklet` and `@manual` for the fields `address`, `month` and `year` (they are an optional fields).
- and other cases

**Comment by ungeahnt** [comment]
JabRef 5.7--2022-08-05--73c111c
Windows 8.1 6.3 amd64 
Java 18.0.2 
JavaFX 18.0.1+2


> ... entry of type `@Article `contains the field `month` ...
> ... Same in the entry type `@book `for the field `address ` ...

At least these issues still exists. I'm a JabRef newbie and I was quite irritated by the 'Deprecated tab' and spend some time to check my entries and configuration ... until I found this issue.
