### ISSUE TITLE
Cannot open PDF files in JabRef Snap

### ISSUE THREAD

**Issue by lpilz** [JabRef/jabref#7762]
JabRef version 5.2--2020-12-24--6a2a512
Arch Linux
Linux 5.12.1-arch1-1
Snap(d) 2.50-1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists
 - ~~Does not apply~~

1. Open Library with linked files or link new files
2. Click the PDF icon/"Open File" in context menu
3. `Native open operation not successful: java.io.IOException: Failed to show URI:` error occurs

<details>
  <summary>Console Log</summary>
  
  ```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Picked up _JAVA_OPTIONS: -Duser.home=/home/lpilz/snap/jabref/1021
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Gtk-Message: 13:40:37.713: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:40:37.713: Failed to load module "canberra-gtk-module"

(java:4034): dbind-WARNING **: 13:40:37.720: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-k9h16ALXGg: No such file or directory

(java:4034): Gdk-WARNING **: 13:40:39.691: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.

 Native open operation not successful: java.io.IOException: Failed to show URI:file:<path to pdf>
  ```
</details>

**Comment by lpilz** [comment]
It seems that this is not a permissions-related snap bug, since file annotations from PDFs can be retrieved

**Comment by Siedlerchr** [comment]
Can you please test the latest snap version edge? (should be 5.3.x)

**Comment by lpilz** [comment]
I have tested it and am getting the same error
`Native open operation not successful: java.io.IOException: Failed to show URI:file:<filepath>`
Additionally I am getting this error:
`java.net.UnknownHostException: <my-pc-name>: No address associated with hostname`

**Comment by Siedlerchr** [comment]
@LyzardKing  you worked on this feature for snaps, if I remember corrreclty, any idea?

**Comment by tautomer** [comment]
Not sure if is' appropriate to reply here, but I experience similar problems on Windows.
The latest nightly build has the same problem.

```text
JabRef 5.3--2021-06-07--62969da
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8
```

`Open file` actually opens My Documents, and `Open folder` results in a "File not found" error.

![image](https://user-images.githubusercontent.com/15900605/121084206-5dfc8800-c7ae-11eb-84cd-bde9c635056f.png)

![image](https://user-images.githubusercontent.com/15900605/121084265-72408500-c7ae-11eb-94d6-3a3b0ab09185.png)

**Comment by LyzardKing** [comment]
I can't replicate this issue with the latest snap on ubuntu. 
Could there be something wrong with the path set in the options folder?

**Comment by lpilz** [comment]
@LyzardKing I double checked the paths and they are correct. Even the path shown in the error message is the right one.

@tautomer I'm not sure this is the same problem. It seems, that for me JabRef finds the files (it shows the correct annotations in the `File annotations` tab), however it just can't open them.

Additionally using `Open Folder` via the context menu just fails quietly for me.

**Comment by tautomer** [comment]
> @LyzardKing I double checked the paths and they are correct. Even the path shown in the error message is the right one.
> 
> @tautomer I'm not sure this is the same problem. It seems, that for me JabRef finds the files (it shows the correct annotations in the `File annotations` tab), however it just can't open them.
> 
> Additionally using `Open Folder` via the context menu just fails quietly for me.

Indeed, this isn't the same problem. [I just found the issue that really matches my problem.](https://github.com/JabRef/jabref/issues/7259)

Sorry about this. I deleted my original comment just in case it will mislead anyone else.

**Comment by lpilz** [comment]
@LyzardKing This issue still persists for me with the update to 5.3

**Comment by LyzardKing** [comment]
I wonder if it's an issue with the Arch snapd implementation..

**Comment by lpilz** [comment]
Is there anything I can do to help you debug this?

**Comment by LyzardKing** [comment]
Is the folder in the user home directory?

**Comment by kamaxwell** [comment]
I think I have this same issue with JabRef.

I completely reinstalled Ubuntu 20.40 two weeks ago. I was using JabRef before the reinstall and for several months maybe even a year the file and folder opening as described above did not work. When I first installed JabRef the file opening feature worked fine. I do not know what JabRef version I was using.

After Ubuntu 20.40 reinstall, I installed the JabRef snap 5.3.450, and I was quite excited that all features worked great including the file and folder opening. Today, I was organizing my library, and I must have changed some JabRef setting(s) and then it was no longer able to open files or the file folder. The last setting I changed was the font size, but I probably changed several other settings before that that I don't remember. 

I uninstalled and reinstalled the JabRef snap and the issue persists. 

Note that features such as "search for unlinked local files" works, and the internal document viewer works. 

Also, I would provide logs or an error message, but the "view event log" appears to be empty.

**Comment by LyzardKing** [comment]
@kamaxwell Did you change the base folder used to fetch the files?
It should be in the Linked files setting tab

**Comment by kamaxwell** [comment]
![image](https://user-images.githubusercontent.com/89912936/131688488-962c7123-a875-480e-828c-e959d44115b1.png)
Yes, that setting is correct, in image above. My files are in a folder I have titled "Jab Ref" while the .bib file is at /home/katherine/texmf/bibtex/bib/bibliography.bib .

**Comment by kamaxwell** [comment]
It appears that renaming the folder my files are stored in to "JabRef" have allowed me to open the folder from JabRef. That is when I now select an entry, right click, and select "Open folder", it works. I guess the issue was the space in the folder name??

However, opening files still does not work. I tried removing spaces in the file names, no success. However, the problem may be exacerbated by some error with my document viewer. When I try to open a pdf file from the terminal, it takes a while and gives this error message:
`F: Can't get document portal mount path
Gtk-Message: 17:59:31.214: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:59:31.215: Failed to load module "canberra-gtk-module"`
When I open a pdf file from the file explorer, it take a while, but does eventually open.

If I can find an alternate command to open files without an error, is there a way to tell JabRef to use a different command to open files?
