### ISSUE TITLE
Create New Import Style drag and drop with google fetcher

### ISSUE THREAD

**Issue by loveneeshr** [JabRef/jabref#777]
Hi,

I am a new jabref user and am not very good at programming or writing JAVA scripts. 

So I wanted to define a new function where I am creating a new import style as drag and drop option where I can create entry based on data fetched from Google Scholar instead of Mr.DLib.
There are a few default options in the preference which do something similar but does not use google scholar.

Not sure if it can be done but it will be very useful if it could be. 
Thanks

**Comment by stefan-kolb** [comment]
@JabRef/developers Anyone has an opinion on this?

**Comment by lenhard** [comment]
We have a working implementation of a google scholar fetcher, so I assume that this old issue can be closed.

**Comment by koppor** [comment]
Maybe @loveneeshr can explain which UI steps he wants to take. Drag'n'drop from web browser? Maybe he should take a look at [JabFox](https://github.com/JabRef/JabFox).
