### ISSUE TITLE
Journal Abbreviations does not handle protecting curly braces

### ISSUE THREAD

**Issue by jmmelko** [JabRef/jabref#7773]
Hi,
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64 
Java 14.0.2

When importing a bibTex citation from a publisher, uppercase abbreviations of editors names is often protected with curly braces, like that:
```{IEEE} Journal of Quantum Electronics```

If the journal abbrevations list contains the unprotected version:
```IEEE Journal of Quantum Electronics```

Jabref does not recognize the journal name.

Suggestion: remove curly braces before searching for an abbrevation

**Comment by jmmelko** [comment]
bug still there in:
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64 
Java 14.0.2

Braces should be there to protect from changing case of acronyms, not protective whatever happens, especially not protection against abbrevations. I think.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
The latest version of JabRef, including the portable version, can be found at [builds/main](https://builds.jabref.org/main/) and it should be 

```
JabRef 5.3--2021-05-31--edb8df5
Mac OS X 10.15.7 x86_64 
Java 16.0.1 
JavaFX 16+8
```

I can't test that it is the same version for Windows, but it would surprise me if it were different.

Remember to take a backup off your library before trying the latest build!

**Comment by jmmelko** [comment]
still there in true latest:

JabRef 5.3--2021-05-31--edb8df5
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8


(btw, why is the official jabref page pointing to fosshub which hosts outdated builds instead of builds.jabref.org ?)

**Comment by tobiasdiez** [comment]
On fosshub you find the latest stable builds, on build.jabref.org the latest development builds.

**Comment by Domquatzo** [comment]
Is this issue still open? I am new to the project and would like to contribute. What are some classes one should look into?
