### ISSUE TITLE
Read status not applied as a batch on selected entries

### ISSUE THREAD

**Issue by jmmelko** [JabRef/jabref#7785]
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64 
Java 14.0.2

* select several entries
* Edit->Read status -> [change status]

=> only the first or last entry of the selection is modified.

It works with the priority status, though

**Comment by mlep** [comment]
@jmmelko  It seems to work for me using the development version.
After backing up your library, could you try it, please? (https://builds.jabref.org/main/)

**Comment by jmmelko** [comment]
fixed in 5.3, closing

(btw, why is the official jabref page pointing to fosshub which hosts outdated builds instead of builds.jabref.org ?)
