### ISSUE TITLE
Library import: no "select all" option

### ISSUE THREAD

**Issue by jmmelko** [JabRef/jabref#7786]
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64 
Java 14.0.2

When importing another library into the current one, a dialog opens in which you have to select entries.
There is a "select new entries", which is not reliable (I tried with existing entries that had been modified: the software does not see them as new), and a "unselect all".

Why not add a "select all"?

Ctrl-click and shift-click do not even provide this functionality.

My production rate has definitly lowered after my third bug report this day

**Comment by tobiasdiez** [comment]
Thanks for your suggestion. Can you please elaborate on why you want to import duplicate entries? If you later want to merge them with an existing entry, this is already possible in the import dialog: you have a small icon next to the duplicated item that lets you manage the import / merge strategy for this entry.

**Comment by mahmutelmas06** [comment]
I have the same issiue. I cannot import PDF files at once. Drag and Drop doenst work.. How to add multiple PDF files to library ?

**Comment by Siedlerchr** [comment]
Thanks to @brapana  this issue is now resolved int he latest main!
