### ISSUE TITLE
Offer migration stategy from PDF und PS directories

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#779]
JabRef offers a single file directory with the possibility to have user-specific file directories for shared libraries. (see https://github.com/JabRef/jabref/pull/459#issuecomment-161817966)

@ajbelle came up at #496 that he still uses the `pdfDirectory` setting although it is not visible in the UI. We should offer a migration path for users with that setting.

- [ ] Understand why users want two user-specific directories (PDF and everything else?)
- [ ] convert pdfDirectory and psDirectory setting to something appropriate

**Comment by ajbelle** [comment]
Thanks @koppor 
I posted to https://github.com/JabRef/jabref/issues/496 my findings that at least on my instal this great (for me) access to multiple unlinked directories is still functional.
My answer to your first question is simple. It makes a move to JabRef (or use of JabReF together with another file manager such as EndNote/Zotero/Docear) very easy in the first instance. 
If JabRef developer's wisdom is to close this existing capability, I suggest you recommend the use a 'junction', which made very easy with LinkShellExtension from http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html. It makes is as easy as using |Windows Explorer|, so your average user can easily do it.
I often see JabRef turned down in favour of Zotero or Endnote supported and paid for by the university, but if JabReF offered easy joint file access that decision would not be required (All gain-little pain). I presonnally cannot use Docear for my large repository, so retain JabReF as my full file repository manager and give Docear just the files it needs to work with via hardlinks. Jöran Beel (he is great) can't see why everything isn't done in Docear ;-)  I have Endnote, JabReF and Docear all accessing the same files from different directories, and think I should really be accessing Zotero for its functionality. JabRef is friendly and easy to use and can handle any sized file repository a single researcher will usually generate, so I stick with it. I hope that answers why and thanks for everything.

**Comment by mlep** [comment]
This issue on JabRef repository is also an issue at stackexchange :
https://tex.stackexchange.com/questions/300963/no-linking-to-pdf-files-since-jabref-3-2-upgrade

**Comment by simonharrer** [comment]
Maybe something for the stupro? @koppor

**Comment by koppor** [comment]
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.
