### ISSUE TITLE
Add sort oder indicators in main table

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#781]
In the header of the main table, there should be little arrows indicating the active sort order of the column.

**Comment by matthiasgeiger** [comment]
See #609 - was present in earlier version, and should be generally possible to add it again - but the way it should work isn't working somehow... 

Unfortunately I had no time to dig deeper into this lateley... :disappointed:

**Comment by tobiasdiez** [comment]
This should be implemented in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.
