### ISSUE TITLE
Microsoft Office XML 2007 export: Inventor of patent not properly formatted

### ISSUE THREAD

**Issue by m-mauersberger** [JabRef/jabref#7830]
JabRef 5.3--2021-06-17--38d7a30
Linux 5.3.18-lp152.78-default amd64 
Java 16.0.1 
JavaFX 16+8
MS Word 2016

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists
- [ ] Does this problem persist with other versions of MS Word?

Patents are not properly exported to MS Office 2007 XML when using Word 2016. Following little changes should be made:

exported as:
`<b:Source>
        ...
        <b:Author>
            <b:Author>
                <b:NameList>
                    ...
                </b:NameList>
            </b:Author>
        </b:Author>
</b:Source>`

It should be changed to:
`<b:Source>
        ...
        <b:Author>
            <b:Inventor>
                <b:NameList>
                    ...
                </b:NameList>
            </b:Inventor>
        </b:Author>
</b:Source>`

There are two files attached for a better view of the format.

[test_patents_shouldbe.txt](https://github.com/JabRef/jabref/files/6675938/test_patents_shouldbe.txt)
[test_patents_asis.txt](https://github.com/JabRef/jabref/files/6675939/test_patents_asis.txt)

**Comment by Siedlerchr** [comment]
Thanks for the report! For entrytype = patent, the author is now export as inventor.
Please try the latest version https://builds.jabref.org/main/
