### ISSUE TITLE
Crowdin: confusion in translation percentage. Old/new path.

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#7844]
Following https://github.com/JabRef/jabref/pull/7843, I went to Crowdin.
It indicated 96% completion for French.
When clicking on the flag, it was either 0% or 100% depending on the directory structure.
See by yourself:
![ksnip_20210622-175513](https://user-images.githubusercontent.com/6931104/122958341-0d2a8900-d383-11eb-9d00-3224372eba9d.png)

For other languages such as simplified Chinese, percentage are 95%/94%, and then the directory structure displays 11% vs 98%

**Comment by Siedlerchr** [comment]
Hi yes, we noticed that as well. This seems like it's an artifact of the branch switching from master to main. We just turned on the sync yesterday and hoped it will normalize. I will see if I can delete the master without losing any data

**Comment by mlep** [comment]
Indeed, things are back to normal!
