### ISSUE TITLE
File link gets destroyed

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#786]
Hello,
I have an entry with the following file link (coppied from bibtex)

 file =     {C:\Studium\6. Semester\Soziologie\stata\},

-> it is supposed to link to a folder:

the new stata version raises an error message, thats why I added a blank key:

 file =     {C:\Studium\6. Semester\Soziologie\stata\ },

now, the file gets loaded properly. However, after clicking on the corresponding entry in jabref [general tab], the file link changes automatically by deleting all "\" characters. Afterwards the link is not usable any more.

**Comment by oscargus** [comment]
\ is used as an escape character and : is used to separate the three fields of the entry. Hence, the entry in the bib-file should read:
file = {C\:\\Studium\\6. Semester\\Soziologie\\stata},

**Comment by simonharrer** [comment]
@oscargus please use backquotes to escape code, as markdown will filter the backslahes out of normal text.

**Comment by teertinker** [comment]
Ok, sorry. The file link must have been created a long time ago, when I was using other software. I thought the given format was created by JabRef at first. So this is not a bug at all, but I have to update my file links. By the way, I found this error using the new development version which raised an error and pointed me right to the correct entry. Nicely done! 

 

    On Thursday, February 11, 2016 7:47 AM, Simon Harrer <notifications@github.com> wrote:
 

 @oscargus please use backquotes to escape code, as markdown will filter the backslahes out of normal text.—
