### ISSUE TITLE
Selecting an Entry preview style triggers an Uncaught Exception

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#7860]
JabRef 5.3--2021-06-28--9fe7617
Linux 5.4.0-77-generic amd64 
Java 16.0.1 
JavaFX 16+8

Following on from #7652 :

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. Select options/preferences/Entry preview
2. click one of the selected styles in the right window
3. Get an Uncaught Exception popup window.  Sometimes it takes one or two click to get the exception; I can't see quite what behaviour uniquely triggers it. 

The event log is empty.

![image](https://user-images.githubusercontent.com/762246/123707872-a5af8600-d827-11eb-99fa-dae4cd786c40.png)
<details>
  <summary>Log File</summary>
  
  ```
  java.lang.IllegalArgumentException: Visible paragraphs' last index is [-1] but visibleParIndex was [0]
	at org.jabref.merged.module@5.3.420/org.fxmisc.richtext.GenericStyledArea.visibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.420/org.fxmisc.richtext.ViewActions.firstVisibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.420/org.fxmisc.richtext.LineNumberFactory.deleteParagraphCheck(Unknown Source)
	at org.jabref.merged.module@5.3.420/org.fxmisc.richtext.LineNumberFactory.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.3.420/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.420/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Refs. https://github.com/JabRef/jabref/issues/7526#issuecomment-869237536

**Comment by crystalfp** [comment]
Still exists in latest development (you have to click on the various selected formats till the exception occurs).
```
JabRef 5.4--2021-09-20--a91420d
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17+18
```
![image](https://user-images.githubusercontent.com/865866/134116922-d5574e7e-15bd-4181-9d45-8743d6c1bead.png)

**Comment by ThiloteE** [comment]
> @ThiloteE I encountered that as well. It has to do with the Edit-Field (coming from the richtextfx library) and the syntax highlighting feature. Did not yet find out why exactly it's happening. It seems to be coming when you don't have anything selected at all, e.g the list is empty At least that triggered it a few times
> 
> If you want to try this version, you can check the build here https://builds.jabref.org/pull/8110/merge/

Mhm not sure. Which list exactly are you talking about? - Something within the edit field or the selected list?

I can trigger the error pretty reliably in "selected" even when it is not empty, so not sure if the emptiness is a criterion. I can trigger it when selecting the styles via keyboard arrows and also when selecting them via mouse. I also get the error basically every time i click on customized preview style, but not always. Sometimes something seems to reset itself, i mean i guess that is to be expected, since the error message shows index issues.

JabRef 5.4--2021-08-21--644e48d
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 16+8

**Comment by ThiloteE** [comment]
JabRef 5.4-PullRequest8110.247--2021-10-01--9bc899a
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17+18

Whereas in the older version (JabRef 5.4--2021-08-21--644e48d) prior to you having implemented the preview and edit function, the **Available** list did not trigger the error, now in the new version (JabRef 5.4-PullRequest8110.247--2021-10-01--9bc899a) it also triggers the error.

**Comment by Siedlerchr** [comment]
This bug is unfortunately coming from an external library, seems like it's https://github.com/FXMisc/RichTextFX/issues/1021
But the fixed version is not yet released :(

**Comment by ThiloteE** [comment]
The uncaught exceptions do indeed not trigger anymore in

JabRef 5.4--2021-11-08--1eaaf50
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

and they also did not trigger in the development version from yesterday.

Awesome!

**Comment by wujastyk** [comment]
JabRef 5.4--2021-11-08--1eaaf50
Linux 5.11.0-38-generic amd64 
Java 16.0.2 
JavaFX 17.0.1+1

Confirmed.  Great news.  Thank you!
