### ISSUE TITLE
Release of 5.3

### ISSUE THREAD

**Issue by MartinX3** [JabRef/jabref#7863]
**Is your suggestion for improvement related to a problem? Please describe.**
Arch linux moved to Java 16, which means, that JabRef 5.2 can't be build anymore (forces java 15).

**Describe the solution you'd like**
Tagging a 5.3 release we can build in our AUR.

**Additional context**
N/A

**Comment by Siedlerchr** [comment]
Hi, our development build already supports Java 16. And we will release the 5.3 soon.

**Comment by Siedlerchr** [comment]
@MartinX3  We just released version 5.3 which builds fine with jdk16. https://github.com/JabRef/jabref/releases/tag/v5.3
