### ISSUE TITLE
Stuck in creating library entry after Fetcher 'DOI' did not find an entry ...

### ISSUE THREAD

**Issue by WolfgangFahl** [JabRef/jabref#7870]
Im am trying to add a reference to 
http://dx.doi.org/10.2777/1524
by creating a new article entry using the doi 10.2777/1524:
![grafik](https://user-images.githubusercontent.com/1336221/124374607-f64a3780-dc9c-11eb-9c68-6e5e615ba402.png)
![grafik](https://user-images.githubusercontent.com/1336221/124374596-dadf2c80-dc9c-11eb-96e0-8f89f1bfa935.png)

and get stuck here. I'd expect that after this error message i'd be able to create the entry manually.

**Comment by koppor** [comment]
Video of the issue: https://www.loom.com/share/1a7fb6101a8e4d499c4a39f2d9f11108

Solution approach:

Add buttons: "Add entry manually" and "Return to dialog" (Refs https://github.com/koppor/jabref/issues/149)

**Comment by betochf** [comment]
Hey, would like to give this a try

**Comment by betochf** [comment]
I think I could solve this, it should be a customDialog instead of errorDialog?

**Comment by koppor** [comment]
I am not sure whether a JavaFX class `CustomDialog` exists. It should be a custom dialog (see other dialogs in JabRef). HTH.

**Comment by Siedlerchr** [comment]
Have a look at `JabRefDialogService`

**Comment by mrcstan** [comment]
Is anyone working on this issue? It not, I would like to work on it.

**Comment by koppor** [comment]
@mrcstan Sure - go ahead!

**Comment by mrcstan** [comment]
@koppor/others, I plan to create a dialog box that allows user to either "Add entry manually" or return to the original dialog box as suggested above. Is such a dialog box already available in the DialogService class or an existing method in the class can be modified to create such a dialog box? After the "Add entry manually" button is clicked by the user, should the Others menu open allowing user to choose the article type? Any hint would be appreciated.

**Comment by mrcstan** [comment]
I submitted a pull request [8203](https://github.com/JabRef/jabref/pull/8203) and the Tests / Checkstyle showed an error " Wrong order for 'org.jabref.model.entry.types.StandardEntryType' import. [ImportOrder]" Do you have a documentation somewhere showing how to order the imports? I also received an error during the test "Deployment / Create installer and portable version for macOS."  The error message is "Run apple-actions/import-codesign-certs@v1
80 Error: At least one of p12-filepath or p12-file-base64 must be provided." I was able to install the code successfully on my MacOS machine, and I don't think I have changed anything that affects the installation. Let me know if you have any hint what could be causing the issue.

**Comment by Siedlerchr** [comment]
Thanks for the interest! We have a checkstyle config https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace

And don't worry about the Mac deployment it will fail every time on forks because it accesses some signing keys that are stored in GitHub secrets and are not available when the Action runs on a fork

**Comment by evanpickett** [comment]
Are there still any problems regarding this issue that might need to be addressed? I'm only asking because the status is still listed as "open"

**Comment by WolfgangFahl** [comment]
I have not seen a release yet that would have the improvement. Is there some kind of prerelease to check?

**Comment by Siedlerchr** [comment]
We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
