### ISSUE TITLE
Please record search history

### ISSUE THREAD

**Issue by idadoudou** [JabRef/jabref#7906]
I hope the search history can be recorded. Then I can browse what I have searched, how I have searched, and what I next do to refine my search. Thank you.

**Is your suggestion for improvement related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Siedlerchr** [comment]
Possible solution for implementation:
1. Store the search history in a list (or maybe better a LinkedHashSet to avoid duplicates but keep the insertion order) whenever the search term changes/differs (empty ones need to be not stored)
- Optionally, limit it to the last 10 searches

2. Adjust the right click menu, add a new entry "Search from history.... " and then show the last searches (Similar to showing the last opened libraries) 

4. When the users choses the last search, set the text field search term to the one from the history
5. 

<img width="507" alt="grafik" src="https://user-images.githubusercontent.com/320228/208117937-a1f24248-d799-41e4-9dbe-2d049020598a.png">

**Comment by idadoudou** [comment]
Please use ***@***.*** due that it is difficult to login qq email.

**Comment by idadoudou** [comment]
Please use ***@***.*** due that it is difficult to login qq email.

**Comment by Siedlerchr** [comment]
@idadoudou  You can change the email in your github user account preferences
