### ISSUE TITLE
Software comparison on wikipedia: OS and network 

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#791]
I have started to update the page https://en.wikipedia.org/wiki/Comparison_of_reference_management_software

To end this task, I need your input about OS compatibility and nextworking capability of JabRef

- https://en.wikipedia.org/wiki/Comparison_of_reference_management_software#Operating_system_support
Is JabRef compatible with:
    - ChromeOS?
    - iOS App?
    - Android App?
    - Windows App?

- https://en.wikipedia.org/wiki/Comparison_of_reference_management_software#Password_.22protection.22_and_network_versions
Does JabRef allows for:
    - Simultaneous write access to the database?

**Comment by koppor** [comment]
OS: none of them

Simultaneous write access: There is code about that warning you if someone else modified the bib file. We should add test cases and demos about that to be sure that it works.

**Comment by mlep** [comment]
Thanks for the info.
