### ISSUE TITLE
Version number in daily build

### ISSUE THREAD

**Issue by jorgman1** [JabRef/jabref#7913]
JabRef 5.3--2021-07-15--cb8fb55
Linux 4.4.0-53-generic amd64 
Java 16.0.1 
JavaFX 16+8

- [ x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. When I installed the latest build, I was warned about a downgrading (because the new version number is lower)

> warning: downgrading jabref from 5.3.378-1 to 5.3.19-1

Is this a desired behaviour because of a new version numbering of the latest builds or should it be 5.4.19-1?

**Comment by koppor** [comment]
This is something with GitVersion. I currently don't have time to think of our GitVersion config. @tobiasdiez do we need to go to 6.0 because we seem to messed up something?

**Comment by Siedlerchr** [comment]
This is now fixed, all newer versions now wil be 5.4.x
