### ISSUE TITLE
Updating JabREf

### ISSUE THREAD

**Issue by mordred111** [JabRef/jabref#7914]
Good Morning,

I would like to update my copy of JabRef to the latest version (5.2) but I am unsure how to do this.

1) Uninstall current version and then install the new version??

2) Install new version over the top of the existing one??

Please advise

Many thanks

Michael Message

PS Might be useful to include an 'Update' instruction in the Intallation Documentation - just a thought

**Comment by Siedlerchr** [comment]
Hi,

Please note that 5.3 is the newest version. You can simply install the new version. No need to manually uninstall. you can install over the top.
Feel free to adjust the documentation https://docs.jabref.org/installation (Right top -> "Edit on Github")
