### ISSUE TITLE
Windows 11 recogniced as Windows 10

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#7916]
JabRef version JabRef 5.3--2021-07-16--c99d61c on Windows 11

- [ x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. About JabRef

![JabRef](https://user-images.githubusercontent.com/15687581/125991416-ac82a37a-9435-444d-9d77-25ddd5a5dd52.png)

**Comment by Siedlerchr** [comment]
Thanks for testing JabRef on Windows 11!
We just read the OS properties: No magic from our side involved
https://github.com/JabRef/jabref/blob/c99d61c2c7a51d11702892039589a4c84920d628/src/main/java/org/jabref/logic/util/BuildInfo.java#L15-L17
