### ISSUE TITLE
No JabRef mentor?

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#792]
Mentoring is an important task to increase the number of developers.
JabRef is among the projects of http://www.flosscoach.com, but no mentor is currently listed (http://www.flosscoach.com/index.php/find-a-way-to-start-jabref#find-a-mentor )

**Comment by koppor** [comment]
I'll try to get the red box removed.

**Comment by koppor** [comment]
The red warning has been removed. Do you think that this is OK? I could state myself as mentor but what if that changes? The mailinglist always works.

**Comment by simonharrer** [comment]
Should be fine.
