### ISSUE TITLE
Reserved characters should be automatically escaped when entries in the Bib are created

### ISSUE THREAD

**Issue by LivingUserError** [JabRef/jabref#7928]
I'm using

JabRef 5.3--2021-07-05--50c96a2
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8

and when I added a source to my bibliography and later quoted that source with BibLatex respectively Biber, suddenly my Latex project wouldn't compile anymore. It took me quite a while to figure this out, but it turns out that source contains a '%' in  the abstract and that caused an error further down the line.

Steps to reproduce:
1) Add a source with a '%' anywhere (or just add one in a bib-entry)
2) Quote it anywhere using BibLatex
3) Compile

I'd suggest that all strings should be checked and sanatized by automatically escaping characters and possibly other measures, to ensure that JabRef doesn't add stuff to a project that can break it. While I'm no expert when it comes to this, security riscs might exist here as well.

**Comment by Siedlerchr** [comment]
Hi,
for a discussion see #3148. The solution now is to use  Quality-> Cleanup -> Field formatters -> abstract + latex cleanup
That will encode the %-sign
