### ISSUE TITLE
Icons of external file types can't be chosen

### ISSUE THREAD

**Issue by mpgvalli** [JabRef/jabref#794]
If I create a new external file type, I can't chose the Icon and a standard file symbol is shown. It would be nice to chose the Icon, because there are not only two word file types, doc and docx but also docm (macro), dot, dotx, dotm. Also there are multiple excel file types. Either you could make the icon editable or you could add these file types to the default external file types.
Thank you for your efforts!!

**Comment by koppor** [comment]
No one volunteers to implement that. Feel free to reopen if you know someone who will implement that feature.
