### ISSUE TITLE
New entries are sometimes prepended to the .bib file

### ISSUE THREAD

**Issue by bschiela** [JabRef/jabref#7944]
When importing a new entry using the browser plugin, it is appended/prepended to the .bib file somewhat inconsistently.  At least the following conditions seem to hold:
1. If JabRef is already open, the new entry is appended.
2. If JabRef is initially closed, the new entry is prepended.

It would be nice to have a setting to specify that new entries should always be either appended or prepended (or at least make the behavior consistent).  I use the timestamp feature to order by creation date, but relative creation order for entries older than this feature is only encoded in their .bib file ordering.

If it's an easy first issue and someone points me in the right direction I may be able to hack it.

JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2
Firefox browser plugin v2.4

**Comment by koppor** [comment]
Which setting to you have in "Save sort order"? --> See our documentation at https://docs.jabref.org/setup/databaseproperties#save-sort-order

**Comment by koppor** [comment]
Thank you for offering to work on this. I think, the pointer to the documentation could be helpful. Maybe you know <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> in IntelliJ to globally search for a text string. With that, you can also find the routine the UI calls when adding an entry.

**Comment by bschiela** [comment]
For my specific purposes (preserving relative order by `creationdate`) it was easier to just fill with dummy values.  Here's the script I wrote using [bibtexparser](https://github.com/sciunto-org/python-bibtexparser):

```python
import bibtexparser as btp
import datetime

with open('papers.bib', 'r') as f:
    db = btp.bparser.BibTexParser(common_strings=True, ignore_nonstandard_types=False).parse_file(f)

creationdate = datetime.date(year=1000, month=1, day=1)
oneday = datetime.timedelta(days=1)
for entry in db.entries:
    if not entry.get("creationdate"):
        entry["creationdate"] = str(creationdate)
        creationdate += oneday

writer = btp.bwriter.BibTexWriter(write_common_strings=False)
writer.order_entries_by = None
db_str = btp.dumps(db, writer)
with open('papers_out.bib', 'w') as f:
    f.write(db_str)
```

Unless the append/prepend behavior bothers someone else (seemingly not) this can probably be closed.
