### ISSUE TITLE
Support Citation File Format (CFF, yaml) as an import/export format

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#7945]
JabRef should be able to parse Citation File Format (CFF) and export into it.
Information about the format can be found here.

https://citation-file-format.github.io/ 
See also https://github.com/citation-file-format/cff-converter-python 

Implementation details. 
Look at other importers, org.jabref.logic.importer
For YAML parsing, JabRef includes already the jackson yaml parser 
https://github.com/FasterXML/jackson-dataformats-text/tree/2.13/yaml

**Comment by kno10** [comment]
@AidanM11 any progress on a CFF *export*? I primarily use bibtex, and was looking for an easy bibtex to CFF conversion. Thank you.

**Comment by Siedlerchr** [comment]
@kno10 So far there is no export. As this issue was about import,  I suggest you open a new issue for the Export so we can better tag this

**Comment by koppor** [comment]
I created https://github.com/JabRef/jabref/issues/10671 as follow-up. (And also changed title of this closed issue, because the title was misleading: One might think, JabRef supports export of CFF).
