### ISSUE TITLE
Undo of cut and delete entries doesn't work

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#796]
Somehow, only one entry is restored when undoing cut or delete of more than one entry. I thought I had messed it up in #793, but it behaved like this before merging it in...

**Comment by tobiasdiez** [comment]
I can't replicate this bug. Can you please describe in more detail when this bug occurs (e.g. cut via context menu or normal menu, keybord shortcut,...).

**Comment by bartsch-dev** [comment]
When you delete 2 Entries on the same time and undo the action only one entry is recovered and an error is throw.
I'm working on a fix.

**Comment by oscargus** [comment]
As I recall it was indeed related to multiple entries.

**Comment by oscargus** [comment]
I tried it now and it seems like it is working properly. I can at least not trigger anything. I think it was related to not returning a copy of the list of selected entries, so when starting to manipulate the entries, the list changed.

Unless someone else has a problem, I believe it can be closed.

**Comment by tobiasdiez** [comment]
I close it now. If somebody experience the problem, then this issue can be reopened.

**Comment by bartsch-dev** [comment]
I still experience that bug.
tested with the current master at 7aa371c931ea51e7c092632e3e3f817c4861f66b.

![issue-796](https://cloud.githubusercontent.com/assets/15333371/13703149/05664cf8-e794-11e5-8b52-12922b6c33b4.gif)

**Comment by bartsch-dev** [comment]
This can now be closed!

**Comment by matthiasgeiger** [comment]
Thx!
