### ISSUE TITLE
Improve display of fulltext search results

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#7962]
In general the fulltext search is working great. Nice feature @btut !
A few points in the ui of the search results tab can still be improved in my opinion:
- The "search results" header in tab is not giving any new information. Either add the search term there or remove the header completely (preferred in my opinion).
- Sometimes I only get the file name without any further details. In this case it would be nice to show at least a message that we cannot extract the text.
![image](https://user-images.githubusercontent.com/5037600/127925608-36b05789-e130-4281-a069-8a2a878b838a.png)
- There is no visual separation between the link of the pdf and the matched full text. Also multiple hits are just displayed as new lines without any indication that they are different hits in separate locations.
![image](https://user-images.githubusercontent.com/5037600/127925856-6b40d614-8f7b-49b3-8b98-a7f073d40ff9.png)
- There is no sensible right-click menu for the PDF link (with e.g. "Open folder" or "Open with xyz" options.) This part should better be implemented in javafx instead of showing everything only in a webview.
- There is no indication of where the matched text can be found (at least page number, preferable also section heading or something like this) and a way to jump directly to the match (in external or our built-in pdf viewer).
- Search result is not updated when search query is changed while the tab is opened.

**Comment by btut** [comment]
Thanks for the feedback.

> - Sometimes I only get the file name without any further details. In this case it would be nice to show at least a message that we cannot extract the text.
> - There is no visual separation between the link of the pdf and the matched full text.

That would definitely help.

> - There is no sensible right-click menu for the PDF link (with e.g. "Open folder" or "Open with xyz" options.) This part should better be implemented in javafx instead of showing everything only in a webview.

That makes highlighting much harder, but I'll have a look. I agree it would be helpful.

> - There is no indication of where the matched text can be found (at least page number, preferable also section heading or something like this) and a way to jump directly to the match (in external or our built-in pdf viewer).

As the default open action for linked files is to open them in an external viewer, I would do the same here. I guess the jump to the correct page would then just work for a defined set of viewers though.

> - Search result is not updated when search query is changed while the tab is opened.

I'll have a look.

**Comment by tobiasdiez** [comment]
> > * There is no sensible right-click menu for the PDF link (with e.g. "Open folder" or "Open with xyz" options.) This part should better be implemented in javafx instead of showing everything only in a webview.
> 
> That makes highlighting much harder, but I'll have a look. I agree it would be helpful.
> 

Have a look at the textflow control: it allows to have differently styled text https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html

**Comment by btut** [comment]
I'm having enough trouble with TextFlow in #7929 (tl;dr: It's not suitable if space is constrained and you want to avoid scrollpanes - which would be acceptable here). But yes, that looks like to way to go!

**Comment by btut** [comment]
I've spend some more thought on this, please see my ideas / plan below:

> The "search results" header in tab is not giving any new information. Either add the search term there or remove the header completely (preferred in my opinion).

True, I removed it.

> Sometimes I only get the file name without any further details. In this case it would be nice to show at least a message that we cannot extract the text.

Hm, I'll investigate how this may happen. I think it shouldn't. If it is unavoidable, I'll add a message.

> There is no visual separation between the link of the pdf and the matched full text. Also multiple hits are just displayed as new lines without any indication that they are different hits in separate locations.

I see how this could be irritating. However, as of now the index does not store any location information. We can only tell that the hits are separated. So the only thing we could do would be visual separation.

> There is no sensible right-click menu for the PDF link (with e.g. "Open folder" or "Open with xyz" options.) This part should better be implemented in javafx instead of showing everything only in a webview.

I changed my mind and now think the TextFlow proposal would overcomplicate things. It would imply that we have to do the highlighting ourselves (html match-highlighting is done by lucene right now). I, therefore, suggest using a VBox, making the links to the file buttons and the highlighted search results themselves are displayed by one WebView each. Would that be ok?

> There is no indication of where the matched text can be found (at least page number, preferable also section heading or something like this) and a way to jump directly to the match (in external or our built-in pdf viewer).

I can look into adding the page number to the index. Section awareness would be great to have, but I don't think that is possible. I don't think there is a way to split a pdf into sections reliably and automatically. If you know of any, let me know!

> Search result is not updated when search query is changed while the tab is opened.

Uh, apparently I did not think of that scenario. I fixed it now.

**Comment by btut** [comment]
> Section awareness would be great to have, but I don't think that is possible.

Actually, we could do that with GROBID. But that would be a little much for now. Let's stick with page numbers and add sectioning later on.

**Comment by tobiasdiez** [comment]
> So the only thing we could do would be visual separation.

That would be a very good start, and with the added page numbers very helpful. The section can be added later indeed.

>  I, therefore, suggest using a VBox, making the links to the file buttons and the highlighted search results themselves are displayed by one WebView each. 

Sadly, adding the webview is a very expansive operation, so I'm not sure how the performance is (but that can be easily tested if you search for a very common term). On the other hand, I would really advice not to use a html-based display. Lucene also seems to provide a method to get the text fragments, which can then presumably be converted to text in a textflow (with highlighting based on the score): https://lucene.apache.org/core/6_6_1/highlighter/org/apache/lucene/search/highlight/Highlighter.html#getBestTextFragments-org.apache.lucene.analysis.TokenStream-java.lang.String-boolean-int- Would that work?

**Comment by btut** [comment]
> That would be a very good start, and with the added page numbers very helpful. The section can be added later indeed.

I have to say you kinda have me in love with the section idea now... I looked into what Grobid provides and I think that is quite helpful. Also, it probably would improve the results themselves because Grobid manages to keep sentences together (e.g. in two-column documents, thats not always the case with other readers, depending on the document). Unfortunately I still think it is a lot of overhead to send each pdf to a web service while indexing.

> Sadly, adding the webview is a very expansive operation

I see, then I will spend some more time investigating how to do the highlighting manually.

> Lucene also seems to provide a method to get the text fragments

Such a fragment is one complete result, not the result fragmented in text that needs to be highlighted or not.

> converted to text in a textflow (with highlighting based on the score)

The highlighting I meant was putting emphasis (in the html generated by lucene the text is bold) on the words in a fragment that actually match the search term. So searching 'brown' in 'The quick brown fox' would result in 'The quick **brown** fox'. It's not related to scoring.

I don't think the highlighting is particularly difficult to do, but rather it's additional code that lucene already provides - IF html would be acceptable. But I see how WebViews can be expensive so I'll do it in a textflow.

Thanks for your input @tobiasdiez

**Comment by Siedlerchr** [comment]
For the Textflow I think we have highlighting in the open office editor where you can edit citation details (e.g page number)

**Comment by btut** [comment]
I think the UI part is very easy. Finding out what to highlight is the "problem".

**Comment by btut** [comment]
Change to TextFlow is done (not pretty yet - but done).
I decided to leave the heavy-lifting to lucene. I still use lucene's html highlighter and just 'render' that html myself in a textview (simply coloring in everything between a defined tag that is used for highlighting).
I think this is a good option as it does not require knowledge of lucene data structures to maintain JabRef.

**Comment by tobiasdiez** [comment]
Okay sounds okay as well. What I had in mind was something like https://github.com/EmilioBello/RecInf/blob/91e408ca2a9d4647c32121fb22b62e34d5be2409/HighlightSearch/src/Test.java#L126-L131 but I'm not sure if that works or not.

**Comment by btut** [comment]
The fragments in this context are the whole result. So for the example from before, searching "brown" in "The quick brown fox", the fragment would be "The quick brown fox". We need to know which portion of the fragment matches the search to add the highlighting to that portion. I looked into how the HtmlFormatter that I use implements this and it's more complicated than it sounds. I therefore chose to leave that code to lucene and then work from the provided highlighted html.

**Comment by Siedlerchr** [comment]
I think we still have this HTML tags to TextFlow converter, from the
Tooltips. e..g bold/italic etc
Something with ToolTipUtils or so. @koppor worked on that in another PR as
well?

Am Mi., 18. Aug. 2021 um 22:14 Uhr schrieb Benedikt Tutzer <
***@***.***>:

**Comment by btut** [comment]
>     * Sometimes I only get the file name without any further details. In this case it would be nice to show at least a message that we cannot extract the text.

I think this was the case if the match was found in an annotation. These were indexed, but not displayed. I fixed that now.

**Comment by tobiasdiez** [comment]
Yes, there is sadly no standard interface for pdf viewers. They usually support some command line arguments that allow to jump to a certain page. This information the user would need to provide in the "open with" preference, with some predefined defaults for common pdf viewers. Similar to the following: https://github.com/James-Yu/LaTeX-Workshop/wiki/View#using-synctex-with-an-external-viewer

**Comment by Siedlerchr** [comment]
Can't the user manage the default applications already in this obscure dialog? But I guess you can't add extra commands for opening
