### ISSUE TITLE
Importing PDF with 'Any file' filter parses PDF as BibTeX instead of using PdfContentImporter or PdfXmpImporter

### ISSUE THREAD

**Issue by btut** [JabRef/jabref#7984]
All files imported without explicitly selecting an importer in the file-choose dialog are parsed as BibTeX files before trying any of the dedicated importers.
This is done [in the importUnknownFormat method](https://github.com/JabRef/jabref/blob/ca0db06db12e21ea439ed1f34383439473830152/src/main/java/org/jabref/logic/importer/ImportFormatReader.java#L158-L183).
The method:

- First tries to parse the file (no matter the file type) as BibTeX.
- Then tries to find a fitting importer

I noticed that with PDF's the BibTeX parser does not fail (but produces unusable results) and therefore the importers that are actually in place to import pdfs are not even used.

Before #694 and in particular f405cf42a92d225ba56c51696d2d8a16bfc85b2f, the priority was the other way around. First, it was tried to find a fitting importer, if there is none the BibTeX parser would try to read the file.

Why was this changed? Maybe @lenhard remembers something?

I noticed that:

- moving it back to how it was before #694 or
- removing the BibTeX parsing alltogether (if a .bib file is selected, it is imported using the BibtexImporter anyways

does not result in any failing tests. Are there any objections to moving it back?

 

JabRef version  on 

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. File -> import -> import into current library
2. Select a PDF file
3. Get an unusable entry for that file

**Comment by Siedlerchr** [comment]
Thanks for the investigation, I  would move to the status as it was before.
