### ISSUE TITLE
Disable tab "Related Articles"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#7995]
- [ ] ![grafik](https://user-images.githubusercontent.com/1366654/129610652-ba2cc8e9-a2ea-4506-812d-44188c145b38.png)
- [ ] Disable Mr. DLib tests on the CI

--- 

- Mr. DLib is currently down
- Mr. Dlib did not receive improvements the last year
- Mr. Dlib will be upa gain in some months

**Comment by calixtus** [comment]
Related articles tab works again. 🎉 🎈 
Issue is obsolete.
