### ISSUE TITLE
Field editor shows wrong fields for entry type article in Bibtex file mode

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#801]
It shows all required and primaryOptional fields of biblatex entry type, even after restart.
Not sure if this happens for other entry types, too.

**Comment by stefan-kolb** [comment]
@simonharrer This is one for us.

**Comment by simonharrer** [comment]
Are you sure that the mode is BibTeX? Can it be that the display of the mode is wrong but internally, the correct mode is used?

**Comment by stefan-kolb** [comment]
No, displayed fields differ between entries somehow.

**Comment by simonharrer** [comment]
Okaaay. Strange.

**Comment by stefan-kolb** [comment]
Looks like it is a problem with the custom entry types. We definately need to rework this as suggested in another issue.
