### ISSUE TITLE
Warn when unknown entry types are used inside Bibtex/Biblatex database

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#802]
For example if one uses entry types of Biblatex inside a bibtex-defined database.

**Comment by stefan-kolb** [comment]
@JabRef/developers Do we have a functionality which let's me check this onLoad and display a message somewhere without explicitely calling an integrity check?

**Comment by tobiasdiez** [comment]
You could add a `POST_OPEN_ACTION` in the `OpenDatabaseAction` class, which implements the check. Maybe it is worthwhile to unify integrity checks and post open actions. The user can then choose which integrity checks should be performed on load.

**Comment by stefan-kolb** [comment]
@JabRef/developers Should we be really restrictive and implement this as a POST_OPEN_ACTION and alert the user if he uses entry types from biblatex inside a bibtex database or is it better to just implement an integrity check and warn the user?
I tend to say (and it's also easier to implement 😄 ) that an integrity check is enough.

**Comment by lenhard** [comment]
@stefan-kolb I agree. So far, we designed JabRef to be as forgiving as possible on load, not messing with custom text in the bib file, etc. I think implementing this only as an integrity check would better fit to our philosophy.
