### ISSUE TITLE
Valid utf-8 title flagged as non utf-8 by check integrity

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#8022]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.4--2021-08-21--644e48d Windows 10 10.0 amd64  Java 16.0.2  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Load the attached database (two entries) as biblatex after verifying that is indeed utf-8
2. Run Quality -> check integrity
3. Atmatzidou2016 entry: "title" flagged as "not utf-8 field found" (but the quote after students is utf-8)
4. RosaZipitria2018: entries "booktitle" and "author" flagged as "not utf-8 field found" (but the quote after CSERC and the í in Zipitría are utf-8)

To be honest, I tried only in the development version.

```
@Article{Atmatzidou2016,
  author       = {Soumela Atmatzidou and Stavros Demetriadis},
  date         = {2016-01},
  journaltitle = {Robotics and Autonomous Systems},
  title        = {Advancing students’ computational thinking skills through educational robotics: A study on age and gender relevant differences},
  doi          = {10.1016/j.robot.2015.10.008},
  pages        = {661--670},
  volume       = {75},
  langid       = {english},
  publisher    = {Elsevier {BV}},
}

@InProceedings{RosaZipitria2018,
  author    = {Sylvia {da Rosa Zipitría}},
  booktitle = {Proceedings of the 7th Computer Science Education Research Conference ({CSERC}’18)},
  date      = {2018-10},
  title     = {{Piaget and Computational Thinking}},
  doi       = {10.1145/3289406.3289412},
  location  = {Saint-Petersburg, Russia},
  publisher = {{ACM} Press},
  langid    = {english},
}
```

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by Siedlerchr** [comment]
Hm, I cannot reproduce the issue I only get warnings in bibtex mode
Have you checked the Library -> Library properties are indeed utf8 and biblatex?

**Comment by crystalfp** [comment]
Yes indeed, the library is utf-8 biblatex. Here is the library that gives the problem:
[UTF8error.txt](https://github.com/JabRef/jabref/files/7142217/UTF8error.txt)

Rename it and load in:
JabRef 5.4--2021-08-23--cef4151
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 16+8

Thanks for looking!

**Comment by Siedlerchr** [comment]
This is odd: looks fine:
<img width="700" alt="grafik" src="https://user-images.githubusercontent.com/320228/132839970-0b209bd8-4efa-4fe4-80fb-bf2cc5b6a751.png">

**Comment by crystalfp** [comment]
Really don't know what to think. If the Jabref version is the same and the library is the same Could be something related to Java or the OS. Have you tried on Window? Java 32 or 64 bits? When I will be in the office, I will try an installation on a Linux VM to see if this makes a difference. Or maybe there is a way to output some debug information to help diagnose where the misclassification happens.

**Comment by ThiloteE** [comment]
I can confirm this for
the current release
JabRef 5.3--2021-07-05--50c96a2
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8

and for the development version
JabRef 5.4--2021-09-10--6c145fc
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17+18

![image](https://user-images.githubusercontent.com/73715071/132861172-c7b5813f-da69-40e6-91cd-26da92b02af3.png)

I tried to use `Quality>Cleanup entries (Alt+F8)` and then the field formaters  `All-text-fields` with `Latex to unicode` as well as `html to unicode`, but that did not help either.

**Comment by Siedlerchr** [comment]
Thanks for the insight. I tested on mac, so it may be somehow a Windows problem then

**Comment by crystalfp** [comment]
Yes, seems it is Windows specific.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
On Windows, https://github.com/JabRef/jabref/blob/3c936d7672ec1f8debce4db57bf3d5efcca45a26/src/main/java/org/jabref/logic/integrity/UTF8Checker.java#L26 reports `windows-1252`

**Comment by Siedlerchr** [comment]
Thanks for the investigation. Seems to be not so easy to find a correct solution, but I guess this one seems more suited https://stackoverflow.com/a/59167280/3450689

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I am struggling a bit with the Gradle setup on Windows so I can't really run tests/debug at the moment. But, if we assume 

https://github.com/JabRef/jabref/blob/3c936d7672ec1f8debce4db57bf3d5efcca45a26/src/main/java/org/jabref/logic/integrity/UTF8Checker.java#L45-L51

works, we can use `bibDatabaseContext.getMetaData().getEncoding()` instead of `Charset charset = Charset.forName(System.getProperty("file.encoding"));`

**Comment by crystalfp** [comment]
I confirm that it is solved in
JabRef 5.5--2021-12-27--32223a4
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1
Thanks a lot!
