### ISSUE TITLE
Merging Entries does not allow to keep groups of all duplicated entries

### ISSUE THREAD

**Issue by MarcelPa** [JabRef/jabref#8024]
**Is your suggestion for improvement related to a problem? Please describe.**
When using the "merge duplicates" functionality, it is not possible to keep the assigned groups of two duplicates. I am only able to choose the groups of one of the entries. If I choose "keep merged entry", the entry is not assigned to any group afterwards.

**Describe the solution you'd like**
I would expect the "keep merged entry" function to assign the merged entry to all groups that any duplicated object was assigned to.

**Additional context**
I think it could also be up for discussion to merge the groups even when explicitly selecting one of the entries (i.e. "Keep left" or "Keep right") during merge. Personally, I cannot think of any use case that would need to merge an entry but not merge the groups.

I assume the the part of the code to fix this can be found [here](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/mergeentries/MergeEntries.java).

**Comment by HoussemNasri** [comment]
Refs #6190
