### ISSUE TITLE
Search in dark theme: visual clues inverted

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8026]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-08-23--cef4151 Linux 4.19.0-17-amd64 amd64  Java 16.0.2  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

A follow-up on issue  #8014 

0. Open JabRef in dark mode
1. Open the bib file https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib
2. Type `alver` in the search bar

- if the `abc` icon is dark (which should mean "Not case sensitive), no results are found:
![ksnip_20210830-095000](https://user-images.githubusercontent.com/6931104/131305000-648a304b-2edb-49cd-aeb4-df8104d46789.png)

- if the `abc` icon is bright (which should mean "Case sensitive), results are found:
![ksnip_20210830-095056](https://user-images.githubusercontent.com/6931104/131305072-6cd2cd98-788b-4f97-9f0f-80ae3769cfe2.png)

The opposite behavior is expected.
Same (inverted) behavior observed for the `Regular expression`icon (and likely for the `Full text search` icon).

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by mlep** [comment]
Indeed, fixed in JabRef 5.4--2021-08-31--df83c9d
Thank you @Siedlerchr!

**Comment by Siedlerchr** [comment]
It was fortunately just a css/color problem. Thanks for the continous test and the feedback!

**Comment by mlep** [comment]
My pleasure to help enhancing a key software managed by a reactive team of programmers!
