### ISSUE TITLE
dynamically group, free-form search

### ISSUE THREAD

**Issue by cybermails** [JabRef/jabref#803]
The 'Dynamically group entries by a free-form search expression' doesn't work if a search expression is added without any field name.

For example, I have a Dynamic Group called _Reviews_, and the group is set to 'Dynamically group entries by a free-form search expression' with a Search expression: _review_. In the description is says: "This search contains entries in which any field contains the term **review** (case insensitive). Hint: To search..." However, there are no entries visible when I press OK. But, if I type _keywords=review_ in the Search expression then in the description it says: "This search contains entries in which the field **keywords** contains the term **review.** The search is case insensitive." and I see a bunch of entries when I press OK.

This works as intended in Jabref 2.10, but not in Jabref 3.2.

**Comment by stefan-kolb** [comment]
@simonharrer WDYT?

**Comment by simonharrer** [comment]
Thanks for the bug report. I will fix this in the next few days.
