### ISSUE TITLE
UI: Dark theme: "Add group" button seems inactivated

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8051]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-09-01--69550d3 Linux 4.19.0-17-amd64 amd64  Java 16.0.2  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behavior

In dark theme:

- At the bottom of the group interface, the button `Add group` is, at first, very visible (too much I would say):
![ksnip_20210902-093301](https://user-images.githubusercontent.com/6931104/131802005-4419b23d-14a6-4b45-bd6a-122c86801059.png)

- Then (after some time, or after creating a subgroup?), the appearance of this button is modified, and it looks like it is inactivated (black characters on grey background):
![ksnip_20210902-093559](https://user-images.githubusercontent.com/6931104/131802320-6efc8303-8fda-4e25-9a62-5d7556e300a3.png)

I would expect the `Add group` button to look like the `Search` button.

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by berry120** [comment]
I thought I might have a look at this one, but I can't actually reproduce it - I've tried waiting a while then creating a subgroup, or just creating a whole bunch of groups - but I never get the issue where the button is disabled.

Has anyone else had any joy in reproducing this and if so, are there any specific steps? Thanks!

**Comment by mlep** [comment]
@berry120 The button is not really disabled. It just looks like it is disable.
And I do not know which criteria makes the button appearance change. It is coded somewhere. If I recall correctly, the very visible button was designed to attract attention to new users.

**Comment by berry120** [comment]
@mlep I also haven't been able to reproduce the behaviour where the button looks disabled while it's not I'm afraid - though I'm only on Windows, so it's possible it's a platform specific thing maybe?

**Comment by mlep** [comment]
I found the information that should allow you to see a different button: the button should change appearance after creating 10 groups (https://github.com/JabRef/jabref/pull/7714)

The disabled (bad) look maybe Linux-specific.
Maybe windows beneficiate of a better look (but I cannot test on windows).

**Comment by srshiao** [comment]
I was able to reproduce this behavior on Windows, but am I understanding that this is an intended feature or is there still a fix that needs to be made here?

**Comment by srshiao** [comment]
Got it, I can try to do that!

**Comment by dimitrisdimos00** [comment]
Hello! Is this issue fixed? I think I have managed to tackle it, if  @srshiao hasn't already. Take a look.
![image](https://user-images.githubusercontent.com/56233132/147995452-3a025571-411c-4e10-a9f8-bf5623dca914.png)

**Comment by mlep** [comment]
It seems that @srshiao has lost interest. So, you are free to propose a PR.

Personally, I find the change in color after 10 groups inserted more disturbing than useful (and, to my knowledge, this is an oddity in JabRef since it occurs only for this feature). @Siedlerchr : What do you think?

**Comment by Siedlerchr** [comment]
Yes, I agree with you @mlep

**Comment by tobiasdiez** [comment]
The idea was that new users learn to find the "new group" button, and once they know where it is the visual highlight is no longer necessary. I cannot found the PR where this was added, but there was some discussion about this already.

**Comment by Siedlerchr** [comment]
@dimitrisdimos00  Thanks again for your contribution! Included in the newest Bugfix release as well.

**Comment by dimitrisdimos00** [comment]
Happy to help!
