### ISSUE TITLE
2 menus are not translated (since JabRef 5.3)

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8053]
### JabRef version

5.3 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-09-01--69550d3 Linux 4.19.0-17-amd64 amd64  Java 16.0.2  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Two menus are not translated in JabRef 5.3, and are not translated in the development version too (although the strings have been translated in Crowdin --- at least for the French language).
So, there is probably a glitch somewhere in the Java code since version 5.3.

They are the menus :
- `Tools -> Start new systematic bibliographic review`
- `Tools -> Perform search for existing systematic bibliographic review`

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by Siedlerchr** [comment]
If the strings are in Crowdin,  then they are there but not synced. To avoid unnecessary work for the translators, we usually stop the syncing and only do it once in a while

**Comment by mlep** [comment]
I thought these 2 strings where translated in Crowdin _before_ the release of version 5.3 (but I may be wrong).
