### ISSUE TITLE
Do not save password in Preferences

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8055]
**Is your suggestion for improvement related to a problem? Please describe.**
Currently, the proxy configuration in Options -> Preferences -> Network requires the password being saved if the proxy needs an authentication.
As indicated by the warning message, the password is not protected, which raise a security concern.

**Describe the solution you'd like**
Do not impose to enter the password in the Preferences' field.
If the password is not saved, JabRef should prompt for it when using the proxy connection for the first time, and keep it in memory only for the current session.
Not a perfect solution, but an improvement.

**Comment by koppor** [comment]
We discussed that in our dev call. We need to focus on other topics to get the release done. We leave that as high-priority.

**Comment by koppor** [comment]
In case the library does not work, we could store the password once session. Meaning: At the first use, ask the user to type it in. At following accesses, the in-memory stored password should be used.

**Comment by calixtus** [comment]
Could be the solution for our password problem, as soon as we have jlink fixed @koppor @tobiasdiez :
https://github.com/javakeyring/java-keyring

**Comment by JacobTrossing** [comment]
Hi, we are a group of 5 students from KTH, Sweden interested in taking on this issue as a part of our "Software Engineering Fundamentals" course.

Would it be possible for us to be assigned this issue and do you have any further pointers you would like to give before we start working?

**Comment by calixtus** [comment]
Thanks for your interest in Jabref! And welcome to our community.
We are very happy, that you decided on contributing to jabref.
However, be aware that it is currently impossible to include any new library because of an issue with JDK/Jlink. We are working on a patch we eventually want to propose to the jdk, but this could take some time to be included and released.
So in case you need to include a new library, it will also probably take some time for your pr to be included in Jabref. 😞

**Comment by koppor** [comment]
> Could be the solution for our password problem, as soon as we have jlink fixed @koppor @tobiasdiez : [javakeyring/java-keyring](https://github.com/javakeyring/java-keyring)

I like that library. It is available at https://central.sonatype.com/artifact/com.github.javakeyring/java-keyring/1.0.1

There should be, however, activity in a new release of the library, e.g., integrating https://github.com/javakeyring/java-keyring/pull/78 and pushing towards a release. -- Nevertheless, we should give it a try to see if it works in principle.
