### ISSUE TITLE
Search highlighting broken at complex searches

### ISSUE THREAD

**Issue by idadoudou** [JabRef/jabref#8067]
When I search `title=TALEN and abstract=plant`, the `and` will be highlighted, but the `TALEN` and `plant` do not.

**Comment by koppor** [comment]
Refs https://github.com/koppor/jabref/issues/341

**Comment by koppor** [comment]
I even don't see any highlight in today's build:

![grafik](https://user-images.githubusercontent.com/1366654/134429876-91ae251b-7ef7-41a4-ad8b-0f17270229aa.png)

**Comment by idadoudou** [comment]
Please use ***@***.*** due that it is difficult to login qq email.

**Comment by koppor** [comment]
@idadoudou Please login into GitHub and configure GitHub to use another email. I think, the help page at https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account is the relevant one.
