### ISSUE TITLE
Tilde accent in author field gives "Names are not in the standard BibTex format" message

### ISSUE THREAD

**Issue by SeppeOngena** [JabRef/jabref#8071]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H1, JabRef 5.4 (2021-09-10)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a new library and citation
2. Fill in author field, e.g., `Nu{\~{n}}ez, Jose and Smith, John`
    The error does not occur with any other accent characters (`\"{o}`, `\'{e}`,`\u{o}`, etc.)
3. The warning sign appears by the field and integrity check displays the message "Names are not in the standard BibTex format"

### Appendix

![image](https://user-images.githubusercontent.com/48645469/132863787-17244f30-f472-4b92-bbc4-22b869595558.png)

**Comment by Siedlerchr** [comment]
@SeppeOngena  Thanks for reporting this issue! It is now resolved in the latest development version. The new version will be roughly ready in 30 minutes.
Please remember to make a backup of your database
https://builds.jabref.org/main/
