### ISSUE TITLE
Change application insights to OpenTelemetry

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#8072]
For the issue #8007  I discovered that we also need to convert our Azure Application Insights, because it still depends on log4j2 internally and probably blocks the aforementioned issue.

What needs to be done?
Replace the Current Azure Application Insights to OpenTelemetry
https://github.com/open-telemetry/opentelemetry-java

Add an exporter for Microsoft Azure:
https://docs.microsoft.com/en-us/java/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-java-preview

**Comment by Siedlerchr** [comment]
ApplicationInsightsLogEvent also needs changes

**Comment by calixtus** [comment]
continued in #8529
