### ISSUE TITLE
Download from official site: Windows and Edge browser warns me of installing JabRef 

### ISSUE THREAD

**Issue by Boncroissant** [JabRef/jabref#8081]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10.0.19042

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Microsoft Edge (93.0.961.47) does not allow to download it "blocked because this type of file can harm your device".
Firefox (92.0) allowed download.

Upon executing, I got a blue window: 
"Windows protected your Computer
Windows Defender Smart Screen prevented..."

1. ...go to https://www.jabref.org/#download
2. ...click "Download JabRef"
3. ...click "JabRef Windows Installer"

This is my first issue, have mercy with me.

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by ThiloteE** [comment]
I can reproduce this.

Unfortunately i can't seem to find the option that would change my edge browsers language to English, usually use Firefox, but i get the warning in German language as well:

![image](https://user-images.githubusercontent.com/73715071/132992465-214af057-fd4e-4f85-b5d7-cb1f4f2834e4.png)

There are more than one ways that could explain how JabRef might have been blocked. See https://docs.microsoft.com/en-gb/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview

> Microsoft Defender SmartScreen provide an early warning system against websites that might engage in phishing attacks or attempt to distribute malware through a socially engineered attack. The primary benefits are:
> 
> Anti-phishing and anti-malware support. Microsoft Defender SmartScreen helps to protect users from sites that are reported to host phishing attacks or attempt to distribute malicious software. It can also help protect against deceptive advertisements, scam sites, and drive-by attacks. Drive-by attacks are web-based attacks that tend to start on a trusted site, targeting security vulnerabilities in commonly used software. Because drive-by attacks can happen even if the user does not click or download anything on the page, the danger often goes unnoticed. For more info about drive-by attacks, see Evolving Microsoft Defender SmartScreen to protect you from drive-by attacks
> 
> Reputation-based URL and app protection. Microsoft Defender SmartScreen evaluates a website's URLs to determine if they're known to distribute or host unsafe content. It also provides reputation checks for apps, checking downloaded programs and the digital signature used to sign a file. If a URL, a file, an app, or a certificate has an established reputation, users won't see any warnings. If, however, there's no reputation, the item is marked as a higher risk and presents a warning to the user.
> 
> Operating system integration. Microsoft Defender SmartScreen is integrated into the Windows 10 operating system. It checks any files an app (including 3rd-party browsers and email clients) attempts to download and run.
> 
> Improved heuristics and diagnostic data. Microsoft Defender SmartScreen is constantly learning and endeavoring to stay up to date, so it can help to protect you against potentially malicious sites and files.
> 
> Management through Group Policy and Microsoft Intune. Microsoft Defender SmartScreen supports using both Group Policy and Microsoft Intune settings. For more info about all available settings, see Available Microsoft Defender SmartScreen Group Policy and mobile device management (MDM) settings.
> 
> Blocking URLs associated with potentially unwanted applications. In Microsoft Edge (based on Chromium), SmartScreen blocks URLs associated with potentially unwanted applications, or PUAs. For more information on blocking URLs associated with PUAs, see Detect and block potentially unwanted applications.

There is also the option to send files to Microsoft Defender SmartScreen for review:

> If you believe a warning or block was incorrectly shown for a file or application, or if you believe an undetected file is malware, you can [submit a file](https://www.microsoft.com/wdsi/filesubmission/) to Microsoft for review. For more info, see [Submit files](https://docs.microsoft.com/en-gb/windows/security/threat-protection/intelligence/submission-guide) for analysis.

**Comment by ThiloteE** [comment]
There also is the option to give feedback in the browser:

![image](https://user-images.githubusercontent.com/73715071/132992796-35d3bce5-bb64-456a-8889-07bdf53785d8.png)


which leads to this screen:

![image](https://user-images.githubusercontent.com/73715071/132992772-952dea8d-f2dc-41aa-8b48-4ffa6fc2bb49.png)

**Comment by Siedlerchr** [comment]
I answered a similar queston in the forum. You have to allow 
>yes this is a known problem and painful for Open Source. To make it short, we would need an expensive certificate (several hundred euros per year) to be able to sign the installer/exe.
Even as a non-profit organization (previously just individual developers) we solely rely on donations, and we decided not to spend the money for this, but rather use it to improve JabRef.

https://discourse.jabref.org/t/jabref-installation-windows-10-security-warning/2853/2?u=siedlerchr
