### ISSUE TITLE
Groups/search window doesn't close

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#8082]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-09-11--366f0cf Linux 5.4.0-84-generic amd64  Java 16.0.2  JavaFX 17+18

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.  Open JabRef
2. left half of the display is blank, where groups/search would be if invoked.

![image](https://user-images.githubusercontent.com/762246/132997086-5d659f44-fe9d-45b1-b3da-542a84dccbb3.png)

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by Siedlerchr** [comment]
@calixtus à side effect (no pun intended) of getting rid of the fxml?

**Comment by calixtus** [comment]
Possibly. On the code side, the groups panel code is separated from the side stuff. But maybe something unforeseen. Need to investigate.

**Comment by Siedlerchr** [comment]
I can confirm this in the dev version as well:
Uncheck all things related to the sidebar in the View menu (e.g. groups and search) and then you see it. Scenic view shows there is still some empty vbox lurking around

<img width="944" alt="grafik" src="https://user-images.githubusercontent.com/320228/133824598-cedb3b10-3cf4-4e42-9779-60052d300ef7.png">

**Comment by Siedlerchr** [comment]
I tried to debug it and I think I discovered the cause:  The ChangeListener is only called when I close JabRef, not when I open it, although it should fire when shown=true
 https://github.com/JabRef/jabref/blob/9c5b8ab5cf458447c57caee726705f8202aa3d88/src/main/java/org/jabref/gui/JabRefFrame.java#L432-L438

**Comment by Siedlerchr** [comment]
Testing further shows that the change listener also did not trigger in javafx16, so we can rule out that it happend with the jfx 17 upgrade I think

**Comment by calixtus** [comment]
I have been working on something else with any Listener on an ObservableMap, that is not firing. Could there maybe a problem with javafx?

On the otherhand: I heavily tried closing the sidepane on my windows machine and was not able to reproduce this bug...

**Comment by calixtus** [comment]
I tried to move the SidePanePreferences to the new Preferences model, the whole logic with an enum of SidePaneType is an overcomplicated mess...

**Comment by Siedlerchr** [comment]
@calixtus  This was fixed by #8202 ?

**Comment by wujastyk** [comment]
Yes, I noticed the problem disappeared a day or two ago.  I'm on
```
JabRef 5.4--2021-12-16--5792f0f
Linux 5.13.0-22-generic amd64 
Java 16.0.2 
JavaFX 17.0.1+1
```
and it's fine.

**Comment by calixtus** [comment]
@Siedlerchr yes should be. @wujastyk can you test please, if the the sidepane keeps its width after closing and reopening?

**Comment by Siedlerchr** [comment]
On mac I have the problem that the exact size is not kept after closing and reopening JabRef. Would be interesting to see if this only a mac issue or if it affects other platforms.

**Comment by wujastyk** [comment]
JabRef 5.4--2021-12-16--5792f0f
Linux 5.13.0-22-generic amd64 
Java 16.0.2 
JavaFX 17.0.1+1

On my system the selected width of the web-search and groups sidebar is preserved after closing and restarting JabRef.

**Comment by calixtus** [comment]
@Siedlerchr Maybe a mac thing? Im sorry, but I cannot debug this then.
