### ISSUE TITLE
Cleanup: Offer conversion from Unicode to LaTeX

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#809]
Currently, the functionality "Run Unicode converter, title, author(s), and abstract" converts from LaTeX encoding to Unicode. We should also offer the reverse conversion.

Furthermore, the current string should be "Convert LaTeX encoded characters to their Unicode equivalent", as it might be unclear, what a "Unicode converter" is or what it exactly does. Which direction does it convert?

- [ ] Add a LaTeXToUnicodeFormatter (refs #920). Then this will automatically be added to "Run field formatter" in "Cleanup entries"

See also #160, #161.

**Comment by oscargus** [comment]
No, it is the opposite. Conversion from Unicode to LaTeX works really well, while the opposite is more limited.

**Comment by tobiasdiez** [comment]
As @oscargus, I thought that the cleanup converts Unicode characters to their Latex equivalent. Is there even a converse cleanup operation? By the way, your remarks also apply to the HTML converter.

**Comment by oscargus** [comment]
There's an export formatter that does the reverse operation: `FormatChars`. However, that uses a much more limited set of characters.

See #807 for, well, not any updates, but the purpose is to eventually convert the content of the long list to something like the `Map`s in `HTMLCharsMap` and `LatexToUnicodeCharMap`. That would be a quick way to make it work.

**Comment by oscargus** [comment]
I'd say that the conversion between LaTeX and Unicode is quite OK at the moment with #841

**Comment by koppor** [comment]
Is that available as Formatter? I don't see a LaTeXToUnicodeFormatter in #920.

**Comment by tobiasdiez** [comment]
No it is not

**Comment by tobiasdiez** [comment]
The LatexToUnicodeFormatter was added recently. So this issue can be closed?
