### ISSUE TITLE
cannot "open folder"

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8093]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-09-20--a91420d Linux 5.13.16-200.fc34.x86_64 amd64  Java 16.0.2  JavaFX 17+18

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. click on entry in entry table.
2. right click on entry and select open folder. or press ctrl+shift+O.

action does not have a visible effect in my Linux gnome environment.

**Comment by Siedlerchr** [comment]
Can you please add some details on your gnome version?

**Comment by ilippert** [comment]
GNOME Shell 40.4

**Comment by ilippert** [comment]
> Open Folder works for me, but only if "Main file directory" in "Linked files" is set in the preferences.

I cannot confirm. I have set "Main file directory" in "Linked files.

**Comment by mlep** [comment]
To me, the folder opens, as expected.

JabRef 5.6--2022-04-20--f220575
Linux 4.19.0-20-amd64 amd64 
Java 17.0.2 
JavaFX 18+12

**Comment by ilippert** [comment]
JabRef 5.6--2022-04-20--f220575
Linux 5.16.20-200.fc35.x86_64 amd64 
Java 17.0.2 
JavaFX 18+12

Hmm, not in my case.

**Comment by mlep** [comment]
@wujastyk: What about you?

**Comment by wujastyk** [comment]
@mlep I'm on Linux Mint + Cinnamon. 
```
System:    Kernel: 5.13.0-40-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.2.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
```

**Comment by ilippert** [comment]
JabRef 5.7--2022-05-23--117bb1c
Linux 5.17.9-300.fc36.x86_64 amd64 
Java 18.0.1 
JavaFX *unknown*

the folder opens now.

However, when opening, it does not select the file of the entry. Which would be helpful given I have thousands of pdfs ;) Should the latter be a separate issue?

**Comment by ThiloteE** [comment]
Yeah, probably separate issue.

**Comment by ThiloteE** [comment]
For me it still does not work.

Closing this because of "duplicate" issue. Please continue discussion in #8679
