### ISSUE TITLE
Empty entry in JabRef leads to Error when compiling in LaTeX

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8096]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10, 20H1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

- Create a new Entry (because you intend to enter a new entry, BUT THEN YOU CHANGE YOUR MIND AND FORGET DELETING IT)
- Do not enter any data into the entry; A **empty** entry.
- This is how an empty entry looks like in the bib-file:

```
@Article{,
}
```

Save your libary > use this file for your latex project >  try to compile your latex project with Miktex and Texmaker > Error ensues, which prevents me from completing my latex compilation.

**Solution i would like:**

- Give warning or explanation in JabRef that having empty entries in your bib-files could lead to this.
- Enhance empty entries visually
- Ask if empty entries should be deleted upon saving (with explanation why)

**Comment by ThiloteE** [comment]
I use biblatex and biber for compilation.

**Comment by neha-b2001** [comment]
Hello, can I work on this issue?

**Comment by Siedlerchr** [comment]
@neha-b2001  This issue is free to take! Make sure to follow our [contribution guide](https://github.com/JabRef/jabref/blob/main/docs/contributing.md)

**Comment by ThiloteE** [comment]
There are more than one ways how to deal with this! There is an interesting discussion in #7057 that deals with a similar problem, that is the deletion of an entry in regards to crossref.

e.g.: https://github.com/JabRef/jabref/issues/7057#issuecomment-929963560

In addition to the solutions i mentioned in my first post, i became aware of solutions that involve:

- Preferences
- Cleanup actions
- automatic deletion of empty entry upon saving (without warning for user)

**Comment by ThiloteE** [comment]
Uh i just noticed that automatic deletion of empty entry upon saving might collide with the automatic saving option (this option is not automatically on, but can be enabled under preferences). It might lead to a situation where you want to create an empty entry, then edit that entry, but because automatic saving triggers, the empty entry gets deleted before you can enter data.

**Comment by neha-b2001** [comment]
> @neha-b2001 This issue is free to take! Make sure to follow our [contribution guide](https://github.com/JabRef/jabref/blob/main/docs/contributing.md)

Oh okay 👍 
I'll try working on it, then

**Comment by ThiloteE** [comment]
Thank you. Yes, indeed. Please take into account that there are circumstances where it is WANTED to create an empty entry and then to edit that entry. It can't just get deleted instantly one second after creation. There has to be a proper time and place for deleting it. It has to be, when it is clear that the user will not have any need for the empty entry anymore. Above, some possibilities have been mentioned how to deal with this.

Also "article" is just one of the possibly entry types. See here:

![image](https://user-images.githubusercontent.com/73715071/139538820-69620efb-513d-48cf-9b9e-05c2b643ab3d.png)

**Comment by ThiloteE** [comment]
I usually create an empty entry with the `+` button in the Jabref UI
![image](https://user-images.githubusercontent.com/73715071/139538910-3b352c75-efda-4b90-bfce-08b54b8f8ef6.png)

**Comment by Siedlerchr** [comment]
I think we have an integrity check in place that warns of empty entries. Maybe show that also when closing JabRef?

**Comment by ilippert** [comment]
>Maybe show that also when closing JabRef? Needs to be a dialog with the option to ignore it and "do not show this dialog again"
This is kind of what I was imagining at https://github.com/JabRef/jabref/issues/8096#issuecomment-950136146. But just to be sure, I guess it will save time in the future if we think of this as part of a wider "interactive closing JabRef procedure". That procedure might encompass the point discusses in this issue, as well as other operations, such as checking for several entries with the same citekeys.
Relevant options for the user might be
- ignore now
- repair/delete (i.e. conduct the proposed action)
- do not ask for this kind of issue again

and still, if the user does not react for, say, 5 seconds, then ignore now would be the default and JabRef closes.

**Comment by jiezheng5** [comment]
thanks very much for the suggestions. It is very helpful.
********************************(｡◕‿◕｡)********************************
Jie Zheng
Email: ***@***.***
Linkedin: https://www.linkedin.com/in/jie-zheng-27749b18/

**Comment by ruoyu-qian** [comment]
Hi, I am a CS student working together with @jiezheng5 in solving this issue. I had some initial progress but still plan to add some JUnit tests. I took a look at your [contribution guide](https://github.com/JabRef/jabref/blob/main/docs/contributing.md), and would like to create a draft pull request if it's okay.

**Comment by ruoyu-qian** [comment]
Hi, I made some additional changes and have submitted the PR for review. 

I did see there is one unit test failed:
`Test testImportEntries()` in `org.jabref.logic.importer.fileformat.PdfGrobidImporterTest`. 
I will take a further look into this, but would also appreciate any suggestions. 

This is also my first time trying to make contribution to an open-sourced project. My apologies in advance if I missed any contribution guide.

**Comment by ThiloteE** [comment]
Thank you very much everybody, but especially @ruoyu-qian for your contributions :)))
I am very happy. So far, everything works perfectly! 👌

Additional enhancements would be:

- add checkbox for `do not ask for this kind of issue again`
- add tiny `?` that explains what an 'empty entry' is. Something like: 
   - An empty entry is defined as  `@entrytype{, }`. An example would be: `@Article{,
}`. An empty entry can be found in the library-file or in biblatex source when selecting the empty entry via the entry editor.

**Comment by ruoyu-qian** [comment]
Thank you for the suggestions! I will try adding them in. One question about 
> add tiny ? that explains what an 'empty entry' is. 

Do we want to include the explanation in the popup confirmation window or were you thinking about somewhere else?

**Comment by Siedlerchr** [comment]
I would suggest that we just add a help entry to the help page describing this empty entry. I guess it should be obvious for most users what an empty entry is.

For the Do not ask again, there is a dialog method in the dialogService class

**Comment by ThiloteE** [comment]
Adding info to the help page is fine too. If i had a choice, i would add it within Jabref because it is easier for the user (no need to search on the web first), but i am not the one that has does the coding, so feel free to do the thing that might go into the right direction and you are confident about being able to handle. :)

I noticed that by entering the terms `empty entry jabref` into the ecosia search engine, the first thing that pops up is this very github issue :D

**Comment by ruoyu-qian** [comment]
Sounds good! I will see what I can do. If I would like to make additional changes, do I need to create a new fork and make a new PR considering the previous one has been merged? Or can I make commits to the same fork?

**Comment by Siedlerchr** [comment]
You first need to update/sync your fork with the JabRef/Jabref main so that it includes the latest commits. Then you create a new branch and a new PR.

**Comment by ruoyu-qian** [comment]
Got it. Thanks!!

**Comment by koppor** [comment]
> Adding info to the help page is fine too. If i had a choice, i would add it within Jabref because it is easier for the user (no need to search on the web first),

JabRef 2.x had the feature to jump from a `?` to the help page. We seem to still have it: `org.jabref.gui.help.HelpAction#openHelpPage`. So it would be a good thing, to keep using it. We should add many more help buttons to JabRef to direct the users to our documentation.

**Comment by koppor** [comment]
@ThiloteE While reviewing the pull requests of this issue, I am asking myself whether JabRef shouldn't just silently delete empty entries. They contain "only" the entry type as information. Otherwise, they would not have been empty. - Why this effort with keeping the entries - and the UI quirks to enable auto-deletion?

**Comment by ThiloteE** [comment]
@koppor You might be right. Deleting them silently might be the better approach. Especially if #8768 is taken into account. We would need to wait a while until a fix for 8768 will arrive at JabRef. Back when I created this Issue, I was not aware it would take this much effort to create this pop-up.

Not sure if deleting empty entries silently upon save will lead to problems with shared databases, though. If I remember right, sharing your library with a database creates a lot of save actions.

Also, #8645 actually seems to be the real problem...

**Comment by ThiloteE** [comment]
@LIM0000 pulling you into this, because there was some discussion here.
