### ISSUE TITLE
Typing an UNC path into "Linked files" -> "Main file directory" should trigger validation at field exit

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8107]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open JabRef Preferences
2. Navigate to "Linked files"
3. Select box "Main file directory"
4. Type `\\w`
5. Error dialog appears  
  ![image](https://user-images.githubusercontent.com/1366654/135480571-d5c18f5e-3b22-4e34-8d24-e667c857b78f.png)

Expected behavior: No error dialog. UNC path should be validated NOT during typing, but after leaving the text field

**Comment by Siedlerchr** [comment]
@berry120 Cool! For getting started check out the guide for setting up a workspace!
 https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace 
If you have any questions, feel free to ask here or in our gitter chat!

**Comment by berry120** [comment]
@Siedlerchr Thanks! I've got everything running and submitted a PR, anything that needs doing differently please let me know!
