### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#811]
All(?) tests related to downloading PDFs are quite likely to fail at the moment.

Suggestion:

Create a very trivial and small PDF and put it on some jabref.org server.

**Comment by stefan-kolb** [comment]
Which tests are failing? It's natural that the crawler tests might fail if the respective server is down. All other tests should not fail or must be fixed.

**Comment by oscargus** [comment]
The same four ones. Check any of my recent PRs. (Sorry, on the phone so
copying is a bit of a hassle.)

The thing is that these are basic ones, like identifying pdf mime, so while
they rely on a server functioning, we can pick that server.

**Comment by stefan-kolb** [comment]
These tests should be fixed right now.

**Comment by matthiasgeiger** [comment]
(For documentation: Was introduced by the update of unirest to 1.4.8 - they [fixed a bug](https://github.com/Mashape/unirest-java/issues/73) and now accessing the header field is case sensitive, i.e., we need to access "Content-Type".)

**Comment by oscargus** [comment]
Thanks! It sort of coincided with the upgrade, but then those tests failed
randomly earlier...

**Comment by oscargus** [comment]
The tests work again. Thanks @stefan-kolb
