### ISSUE TITLE
Allow other certificates

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8126]
When working behind a SSL proxy, the SSL proxy presents another SSL certificate. When not using that certificate, the DOI fetcher returns "Connection error" without any further information:

![image](https://user-images.githubusercontent.com/1366654/136272508-6935133a-b82d-493c-bc1d-f42acfd34397.png)

IMHO JabRef should offer the possibility to:

- use an own key store
  - activated through preferences
- import `.cer` files into that key store
  - possibility offered using the preferences

See https://stackoverflow.com/q/18889058/873282 for some code hints.

Somehow refs https://github.com/JabRef/jabref/issues/7627. Here, we have an SSL certificate issue. There, we have a proxy authentication error.

**Comment by koppor** [comment]
Current state in the shared database dialog:

![image](https://user-images.githubusercontent.com/1366654/136497766-5a49df20-5b50-4459-a4f6-89a0998cc10f.png)

I would propose to move that settings to the preferences dialog:

![image](https://user-images.githubusercontent.com/1366654/136497798-550455ac-3005-4181-8c27-1736f8cdba57.png)

- [ ] Add new category "SSL Certificates"
- [ ] Switch between "JabRef internal key store" and "Custom key store" with a file browsing possibility (to here, the part of the shared database dialog is moved)
- [ ] Add possiblit y(button) to browse and add `.cer` file to the key store selected in step 2

**Comment by koppor** [comment]
Additional/alternative approach:

- An SSL certificate should be downloaded if SSL error appears --> auto-import man-in-the-middle SSL certificate (e.g., company proxy)
- When download fails due to SSL error, a configuration dialog shown be shown

**Comment by HoussemNasri** [comment]
> * [ ]  Switch between "JabRef internal key store" and "Custom key store" with a file browsing possibility (to here, the part of 

What about having a single checkbox to enable or disable custom certificates, similar to Proxy Configuration, and custom certificates will be added on top of JabRef internal Keystore (which if I understand correctly is empty for now)
