### ISSUE TITLE
MacOs: Can't pin the file when right click and choose "open folder"

### ISSUE THREAD

**Issue by digdig** [JabRef/jabref#8130]
In windows, when choosing `open in folder`, the folder opens and the file is highlighted. 

In MacOS, only folder opens, but I can't pin point the file, which is very inconvenient if I have many pdf files in the that folder.

I am using MacOs Majave and JabRef 5.3 (actually the older version also can't pin point the file.)

**Comment by Siedlerchr** [comment]
@digdig  I found a solution. Can you please test with the latest development version?


We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by digdig** [comment]
@Siedlerchr Thank you very much. It works great! It significantly reduce my pain to locate the file. Previously I was using spotlight to search the key.

I hope this feature will be implemented in the stable release soon.
