### ISSUE TITLE
Library should not be flagged as externally modified when changing library properties

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8132]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create `tst.bib` with following content

  ```bibtex
  @inproceedings{reiser2009compositional,
    title={Compositional variability-concepts and patterns},
    author={Reiser, M-O and Kolagari, Ramin Tavakoli and Weber, Matthias},
    booktitle={2009 42nd Hawaii International Conference on System Sciences},
    pages={1--10},
    year={2009},
    organization={IEEE}
  }

  @inproceedings{altintas2008managing,
    title={Managing large scale reuse across multiple software product lines},
    author={Altintas, N Ilker and Cetin, Semih},
    booktitle={International Conference on Software Reuse},
    pages={166--177},
    year={2008},
    organization={Springer}
  }
  ```
2. Save the `.bib` file
3. JabRef adds `% Encoding: UTF-8` and `jabref-meta` for the `databaseType`  
  ![image](https://user-images.githubusercontent.com/1366654/136651336-8f7c0395-1a74-4de8-9261-54c920ac8d6d.png)
4. Open "Library preferences"
5. Set  `pdfs\` as file path 
  ![image](https://user-images.githubusercontent.com/1366654/136651363-4621a4d9-7728-48f1-874c-90ed50db4816.png)
6. Save the library
7. Result in JabRef:  
  ![image](https://user-images.githubusercontent.com/1366654/136651293-5654bf71-52a6-4a3c-a762-a0e6a7261811.png)
8. Result in the bib file
  ![image](https://user-images.githubusercontent.com/1366654/136651414-ad2a35bb-9304-480d-96e5-62673e1c9c29.png)

Expected results:

- no change of the entry order --> This is #8133
- No "The library has been modified by another program."

For the "externally modified", I have no clue currently.

**Comment by Siedlerchr** [comment]
The modified externally is very likely related to #6694

**Comment by koppor** [comment]
I split the issue up. A) "Save sort order" (#8133) and B) the externally modified (which seems to be harder)

**Comment by HoussemNasri** [comment]
I can't seem to reproduce this in the development version. Is it possible this got fixed in https://github.com/JabRef/jabref/pull/8264/?

**Comment by ThiloteE** [comment]
For the record: Current JabRef development version (5.7) assumes library files to be encoded in UTF-8 and also does not write `% Encoding: UTF-8` anymore to the library file.

**Comment by ThiloteE** [comment]
Closing this issue, as 

1. It was reported issue could not be reproduced with current development version of JabRef.
2. Clear enough steps how to trigger the "externally modified" otherwise are not given.
   - What tools triggered "Externally modified"? Examples would be: Dropbox, Syncthing, Onedrive, etc. Is it enough to simply have JabRef installed or is external program necessary?
   - Information about relevant JabRef preferences are not given.
      - `options > preferences > Files` autosave enabled or disabled?
      - `options > preferences > Files` Always reformat bibfile on export and import enabled or disabled?
