### ISSUE TITLE
Default save order should be "Keep original order"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8133]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create `tst.bib` with following content

  ```bibtex
  @inproceedings{reiser2009compositional,
    title={Compositional variability-concepts and patterns},
    author={Reiser, M-O and Kolagari, Ramin Tavakoli and Weber, Matthias},
    booktitle={2009 42nd Hawaii International Conference on System Sciences},
    pages={1--10},
    year={2009},
    organization={IEEE}
  }

  @inproceedings{altintas2008managing,
    title={Managing large scale reuse across multiple software product lines},
    author={Altintas, N Ilker and Cetin, Semih},
    booktitle={International Conference on Software Reuse},
    pages={166--177},
    year={2008},
    organization={Springer}
  }
  ```
2. Save the `.bib` file
3. JabRef adds `% Encoding: UTF-8` and `jabref-meta` for the `databaseType`  
  ![image](https://user-images.githubusercontent.com/1366654/136651336-8f7c0395-1a74-4de8-9261-54c920ac8d6d.png)
4. Open "Library preferences"
5. Set  `pdfs\` as file path 
  ![image](https://user-images.githubusercontent.com/1366654/136651363-4621a4d9-7728-48f1-874c-90ed50db4816.png)
6. Save the library
7. Result in JabRef:  
  ![image](https://user-images.githubusercontent.com/1366654/136651293-5654bf71-52a6-4a3c-a762-a0e6a7261811.png)
8. Result in the bib file
  ![image](https://user-images.githubusercontent.com/1366654/136651414-ad2a35bb-9304-480d-96e5-62673e1c9c29.png)

Expected results:

- no change of the entry order.
- No "The library has been modified by another program."

Proposed solution: Set "Keep original order" as default in the "Library properties":

![image](https://user-images.githubusercontent.com/1366654/136651394-b0af2a1e-ab70-4ce5-80c8-39e3c612dbe9.png)

For the "externally modified", there is issue #8132

**Comment by ManishOffi** [comment]
can you assign me?

**Comment by koppor** [comment]
I think, I have clean JabRef installation. There, at "Import and Export", the "Export sort order" is set to "Use current able sort order". We discussed in a devcall, that this is OK. However, this should not be used as default for the library properties.

![grafik](https://user-images.githubusercontent.com/1366654/137205852-1a86ce0c-31ab-476f-9f36-520305915203.png)

**Comment by sponbob-pat** [comment]
I want to do this issue. Is it okay??

**Comment by koppor** [comment]
I get this output

> WARN  org.jabref.model.metadata.SaveOrderConfig - Could not parse sort order: specified - trying to parse the sort criteria

**Comment by koppor** [comment]
@sponbob-pat Sure. Please ensure that you follow https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace before working on this. 🎉

**Comment by koppor** [comment]
This is closely related to https://github.com/JabRef/jabref/issues/8198 (if not the same issue)

**Comment by sponbob-pat** [comment]
Could you assign me?
