### ISSUE TITLE
Export an ods table from jabref  is messing it up

### ISSUE THREAD

**Issue by AngelicaRibeiro** [JabRef/jabref#8141]
### JabRef version

5.3 (latest release)

### Operating system

Other (please describe below)

### Details on version and operating system

Manjaro linux / Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Added extra columns to the entrie table
2. Exported all  entries with all the columns added  by  the menu`File >  Export > Export All Entries`  to old office / libre office format
3. Saved to `.ods` file 
4. when I've openned the `.ods` file  it shows just the following  fist 34 colluns if passes it it shows `Custom#` where # is the number the costom number starting from 1 to N.
5. So as a result it doesn't show the included columns in jabref to the `ods` file.

I've included all the collums that jabref permits

**Comment by Siedlerchr** [comment]
@dhruvshar  Go ahead, make sure to follow the steps for https://devdocs.jabref.org/contributing and setting up the workspace. https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace

The goal would be to have all fields exported, respecting the export settings for current table sort order etc
