### ISSUE TITLE
"Crossref" field should also work if Autocomplete is disabled

### ISSUE THREAD

**Issue by nicolahinssen** [JabRef/jabref#8145]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 11 Pro (build 22471)  |  JabRef 5.4--2021-10-11--2e71d5f

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Enter a citekey (in my case an "_mvBook_") of the parent entry in the **crossref** field
2. The BibLaTeX source doesn't show the crossref line.
3. After closing JabRef and reopening, the **crossref** input field is also empty again.

### Appendix

...
<details>
<summary>Log File</summary>
`It seems nothing is being logged
`</details>

**Comment by ThiloteE** [comment]
I would suggest a separate preference to enable crossref because of #6704. And of course, it should work if autocomplete is enabled.

**Comment by Siedlerchr** [comment]
For anyone wanting so solve this, have a look at FieldEditors in combination with SuggestionProviders

**Comment by pal-anish** [comment]
Hi @Siedlerchr 
I need some brainstorming about this issue. I am requesting some suggestions for it.

**Comment by Siedlerchr** [comment]
StandardField.Crossref has a Field property called SINGLE_ENTRY_LINK, in FieldEditors the getSuggestionProvider  is called and the value (the thing which handles the autocomplete) is then passed down to the field type editor 
If you follow the trail where the suggestion Provider originally comes from
FieldsEditor  > FieldsEditorTab > Entry Editor -> LIbraryTab -> setupAutocomplete

Inside SuggestionProvider class there is this isEmpty check. 
Here you would need to add a check for the SingleLink or MultipleLink property or CrossRef field
I would suggest just checking the field type to allow all possible link fields to work.

Autocompletion is controlled by AutocompletePreferences

**Comment by pal-anish** [comment]
@Siedlerchr Can you please review my changes? I have created a PR to resolve this issue.
