### ISSUE TITLE
Change of default pattern in "Prefences" -> "Citation key generator" is not saved

### ISSUE THREAD

**Issue by dmitry-kabanov** [JabRef/jabref#8147]
### JabRef version

5.3 (latest release)

### Operating system

mac OS

### Details on version and operating system

MacOS 11.6 Big Sur

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to menu item "Options" -> "Preferences"
2. Choose "Citation key generator" tab on the left.
3. Change default pattern from "[auth][year]" to [authEtAl][year]", which according to the documentation will change generated keys to have a second author and EtAl suffix for more than two authors.
4. Try to use the key generator. See that it does not work. Check preferences window to see that it still is "[auth][year]".

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Refs #5825
