### ISSUE TITLE
Curly braces ignored in in-text citations

### ISSUE THREAD

**Issue by Marisano** [JabRef/jabref#815]
In the reference,

```
@Manual{JabRef_software,
  Title                    = {JabRef},
  Author                   = {{JabRef Development Team}},
  Year                     = {2015},
  Version                  = {Version 2.11.1},
  Url                      = {http://www.jabref.org}
}
```

The curly braces in the Author field are ignored, causing, for example, its associated in-text citation to be presented as "(Team, 2015)", rather than, "(JabRef Development Team, 2015)". Curly braces should be honored in in-text citations.

**Comment by tobiasdiez** [comment]
What do you mean by in-text citation? 
The above reference shows "JabRef Development Team" in the main table and 
`Manual (JabRef_software) JabRef Development Team JabRef 2015 ` in the preview. Both seem to be correct.

**Comment by koppor** [comment]
Please post a [minimal working example](http://meta.tex.stackexchange.com/a/231/9075) including the `.tex` and the `.bib` file and the tools you are using (biber or bibtex, pdflatex or latex, ...)

**Comment by Marisano** [comment]
Sorry, for not mentioning that this is from JabRef to LibreOffice Writer (version 5.0.5.2), so there is no .tex file. I can whip up a .bib file if that would be helpful, however.

By "in-text citation," I mean the writing signifying that a work has been cited that appears in the body of a document. So if this were part of a journal article that I used JabRef (Team 2015) to help me create a bibliography for, the in-text citation would be "(Team 2015)". [Though ideally it should be "(JabRef Development Team 2015)".]

**Comment by oscargus** [comment]
I can just comment briefly: there is code to check for this case, namely a method isInstitution(). Not sure exactly where I saw it though...

**Comment by Siedlerchr** [comment]
I can confirm this bug. Version LO: 5.0.2.2 (x64) on Window 7.
I'll look through it.
