### ISSUE TITLE
Saving a collection of entries/linked pdfs

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#8156]
Hi, I have the following suggestion for improvement.  Regularly, I need to share a subset of papers (e.g. from a subgroup or via a search) with students.  It would be great if there was a way to copy/zip all pdfs linked with a selection of entries for easy sharing. Or is this feature already available?

**Comment by Siedlerchr** [comment]
Hi  the feature is already available since Version 5.x Just select the entries with files and then in the Menu Tools -> Copy linked files to folder.
This will export all the linked files of the entries into to the target directory. Implemented in https://github.com/JabRef/jabref/pull/3147
