### ISSUE TITLE
DOI title fetcher seems to miss "booktitle" since 2021-10-16

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8159]
> Something is odd with the fetcher tests, they no longer includer the book title field...

The test `org.jabref.logic.importer.fetcher.TitleFetcherTest#testPerformSearchKopp2007` currently fails - and relies on https://doi.org/10.1109/seaa.2009.21, which points to a paper at IEEE. However, the data is provided by crossref.

I tried on the main branch - see https://github.com/JabRef/jabref/runs/3920469098?check_suite_focus=true:

```
 org.jabref.logic.importer.fetcher.TitleFetcherTest

  Test testPerformSearchKopp2007() FAILED (1.4s)

  org.opentest4j.AssertionFailedError: expected: <Optional[@inproceedings{Bischof_2009,
    author = {Marc Bischof and Oliver Kopp and Tammo van Lessen and Frank Leymann},
    booktitle = {2009 35th Euromicro Conference on Software Engineering and Advanced Applications},
    doi = {10.1109/seaa.2009.21},
    month = {aug},
    publisher = {{IEEE}},
    title = {{BPELscript}: A Simplified Script Syntax for {WS}-{BPEL} 2.0},
    year = {2009},
    _jabref_shared = {sharedId: -1, version: 1}
  }]> but was: <Optional[@inproceedings{2009,
    author = {Marc Bischof and Oliver Kopp and Tammo van Lessen and Frank Leymann},
    doi = {10.1109/seaa.2009.21},
    month = {aug},
    publisher = {{IEEE}},
    title = {{BPELscript}: A Simplified Script Syntax for {WS}-{BPEL} 2.0},
    year = {2009},
    _jabref_shared = {sharedId: -1, version: 1}
  }]>
```

This is a follow up of https://github.com/JabRef/jabref/pull/8155#issuecomment-945130315.

**Comment by koppor** [comment]
@yutarasevich Could you add your example DOI from https://github.com/JabRef/jabref/pull/8155#issuecomment-946573127 here?

**Comment by koppor** [comment]
journal titles are handled at https://github.com/JabRef/jabref/issues/8167

**Comment by Siedlerchr** [comment]
This was recently fixed by crossRef. I tested it again and works now.
