### ISSUE TITLE
Journal names are not imported

### ISSUE THREAD

**Issue by matheger** [JabRef/jabref#8167]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.3--2021-07-05--50c96a2 Windows 10 10.0 amd64  Java 16.0.1  JavaFX 16+8

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Import a pdf file from disk, or import article details from DOI. Journal name remains blank.

**Comment by koppor** [comment]
Copied from: https://github.com/JabRef/jabref/pull/8155#issuecomment-947298160


For instance, 10.1103/PhysRevE.103.062145
Publisher's (APS) BibTeX record

```bibtex
@article{PhysRevE.103.062145,
  title = {Random nanowire networks: Identification of a current-carrying subset of wires using a modified wall follower algorithm},
  author = {Tarasevich, Yuri Yu. and Akhunzhanov, Renat K. and Eserkepov, Andrei V. and Ulyanov, Mikhail V.},
  **journal = {Phys. Rev. E},**
  volume = {103},
  issue = {6},
  pages = {062145},
  numpages = {9},
  year = {2021},
  month = {Jun},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevE.103.062145},
  url = {https://link.aps.org/doi/10.1103/PhysRevE.103.062145}
}
```

CrossRef's BibTeX record


```bibtex
@article{Tarasevich_2021,
	doi = {10.1103/physreve.103.062145},
	url = {https://doi.org/10.1103%2Fphysreve.103.062145},
	year = 2021,
	month = {jun},
	publisher = {American Physical Society ({APS})},
	volume = {103},
	number = {6},
	author = {Yuri Yu. Tarasevich and Renat K. Akhunzhanov and Andrei V. Eserkepov and Mikhail V. Ulyanov},
	title = {Random nanowire networks: Identification of a current-carrying subset of wires using a modified wall follower algorithm},
	**journal = {Physical Review E}**
}
```

JabRef's BibTeX record

```bibtex
@Article{Tarasevich2021,
  author    = {Yuri Yu. Tarasevich and Renat K. Akhunzhanov and Andrei V. Eserkepov and Mikhail V. Ulyanov},
  title     = {Random nanowire networks: Identification of a current-carrying subset of wires using a modified wall follower algorithm},
  year      = {2021},
  month     = {jun},
  number    = {6},
  pages     = {062145},
  volume    = {103},
  doi       = {10.1103/physreve.103.062145},
  publisher = {American Physical Society ({APS})},
}
```

Field 'journal' is absent!

The problem is hardly connected with a change in CrossRef format, since our very old home-made program still import correctly BibTeX records from crossref.

**Comment by koppor** [comment]
@yutarasevich: Does your program use the REST API or does it interact differently with the crossref server?

**Comment by koppor** [comment]
```bash
$ curl --location --request GET 'https://doi.org/10.1103/PhysRevE.103.062145' \
> --header 'Accept: application/x-bibtex'
@article{2021,
        doi = {10.1103/physreve.103.062145},
        url = {https://doi.org/10.1103%2Fphysreve.103.062145},
        year = 2021,
        month = {jun},
        publisher = {American Physical Society ({APS})},
        volume = {103},
        number = {6},
        author = {Yuri Yu. Tarasevich and Renat K. Akhunzhanov and Andrei V. Eserkepov and Mikhail V. Ulyanov},
        title = {Random nanowire networks: Identification of a current-carrying subset of wires using a modified wall follower algorithm}
```

**Comment by bernwo** [comment]
I am also having the same issue. All articles which I have added within Jabref 5.3 via DOI doesn't have the journal entry.

**Comment by ThiloteE** [comment]
Good news: For the ones that may be affected because of Crossref, they apparently have a fix in the making: In https://gitlab.com/crossref/issues/-/issues/1540 you can see this pull request: https://gitlab.com/crossref/rest_api/-/merge_requests/319

**Comment by Siedlerchr** [comment]
Thanks, @ThiloteE, for keeping track of this. CrossRef fixed this issue. I tested it with a couple of DOIs and it seems it's working again.
