### ISSUE TITLE
Reorder/hide tabs and fields in entry editor

### ISSUE THREAD

**Issue by matheger** [JabRef/jabref#8168]
I would like to customize the editor to hide tabs that I don't need or at least reorder them so that the most relevant ones are first. Right now the two most important tabs to me are the "Required fields" and the "File annotations" and everything else is just fluff that I don't look at.

Similarly, I want to reorder the fields within a tab. Right now in the "Required" tab has the field order "Author - Pages - Title - Journal - Year". I couldn't care less about the pages while I'm still checking author, title and journal.

**Comment by Siedlerchr** [comment]
Closing this as this is just a kind of question.
