### ISSUE TITLE
Double click on a group should open its properties

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8188]
Currently, a double click on a group has no effect. In my opptionion, the "Edit gorup" dialog should open

**Comment by ColemanKobe** [comment]
PR incoming for this issue

**Comment by koppor** [comment]
Current behavior: A double click expands a group. The user interface was not matching my expectations.

![grafik](https://user-images.githubusercontent.com/1366654/140810894-a2e781d5-d824-42e8-bff0-8d62aba7ef09.png)

My current use case was a flat group:

![grafik](https://user-images.githubusercontent.com/1366654/140810922-57892f3c-ca88-4012-897b-4632bc1634a0.png)

To avoid confusion, we classify this issue as invalid.
