### ISSUE TITLE
When changing a group color, no dialog should appear

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8189]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Edit the properties of a group
2. Change the color
3. Click "OK"
4. Dialog "Change of Grouping Method" appears  
  ![grafik](https://user-images.githubusercontent.com/1366654/138783321-12364f5a-5dcb-4ad1-a57c-261456106846.png)

Expected behavior: No dialog appears, just the group color should change

Refs https://github.com/JabRef/jabref/issues/7325

**Comment by Siedlerchr** [comment]
I looked a bit into it, the dialog is called here:

A solution would be to check if there have been changes to the group type or group keywords etc and only display that dialog in this cases.

https://github.com/JabRef/jabref/blob/9d1c448bb828d344aa773a66eaa60ac6bcc1dfad/src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java#L183-L199

**Comment by dimitrisdimos00** [comment]
Hello there. In which cases is a warning useless except from when changing the color? For example, I'm thinking that when changing the icon of the group, no warning should be shown either. Do we need a warning only for the "Hierarchical context" and "Collect by" options?

**Comment by Siedlerchr** [comment]
Sorry, missed your question.
I guess it makes only sense when the group type or for example the keywords or the separator changed. For color and icon not

**Comment by Surabhiramesh** [comment]
Hi, we are a group of students studying Master of Computer Science in University of Adelaide and we wanted to check if this issue is available for us to work on for our assignment. And if it is available, we would like to get some valuable inputs based on the previous contributions to this issue.

**Comment by koppor** [comment]
> In which cases is a warning useless except from when changing the color? For example, I'm thinking that when changing the icon of the group, no warning should be shown either.

You are right. Please make a list of all possible cases, where a) no dialog should be opened and b) where a dialog should be opened

> Do we need a warning only for the "Hierarchical context" and "Collect by" options?

I am not sure. It should be properly documented and JUnit tests should exist.

**Comment by koppor** [comment]
@Surabhiramesh The issue is available. Please go ahead. Please also see my last comment.

**Comment by ThiloteE** [comment]
Welcome and thank you for your engagement. Guidelines for contributing can be found here: https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md. See [here](https://devdocs.jabref.org/teaching#process-for-contributions) for a rough outline of this process. In general, it is advised to open a (draft) pull request early on so that reviewers have time to comment and the general direction of the request becomes clear. This will allow you to receive valuable feedback!

If you have any questions, feel free to ask! Either here at GitHub, or you also can join our [gitter chat](https://gitter.im/JabRef/jabref).
