### ISSUE TITLE
Error console window is modal

### ISSUE THREAD

**Issue by Ede123** [JabRef/jabref#819]
I just installed Jabref 3.2 (updated from 2.x) on Windows 7, java version "1.8.0_73" (32 bit).

While trying to figure out an issue with the full text fetcher I noticed that the error console is a modal window (e.g. no interaction with the JabRef UI is possible while it is opened) and also seems to block the UI thread somehow (the error message that the fetcher had failed in the meantime only appeared _after_ I closed the error console).

If this is "by design" feel free to close this issue right away.
It's however counter-intuitive (from my experience with other applications I'd have expected the normal workflow to be _"Open error console -> Do the steps to reproduce errors in UI -> Check if an error is logged along the way"_, which is obviously not possible with the current implementation).

**Comment by simonharrer** [comment]
Note: then, the error console should also update itself when new errors arrive which I think is currently not the case.

**Comment by koppor** [comment]
This should be fixed at our javafx branch. Please try the binary from https://builds.jabref.org/javafx/ and report back if that works for you.
