### ISSUE TITLE
Duplicate fields assigned to entry types

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#8194]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 100.0.0 Windows 10 10.0 amd64  Java 16  JavaFX 17.0.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select `Options > Customize entry types` 
2. Select any entry type
3. Add a field that is already added to that entry type
4. It gets added normally (BAD)

Expected: We should ignore the user request or display a warning to tell him that he is trying to add a duplicate field 
- Please note that after restarting `CustomizeEntryTypeView` the duplicate will be gone

**Comment by wujastyk** [comment]
Footnote: this is probably a Biblatex issue not a Jabref one, but I would often like to be able to add multiple URLs or eprint fields.  For example, when recording a multi-volume book where the vols are at different URLs at archive.org.  Happens quite frequently

**Comment by dimitrisdimos00** [comment]
Hello! I would like to take a look at this. From what I understand, we want a warning popup to be shown to the user when he tries to add an existing field. Is that correct? Thank you.

**Comment by wujastyk** [comment]
I think a warning is a good idea.
But if one _wants_ multiple fields for, say, multiple ISBNs or multiple URLs, it should be somehow possible.  The output in such cases could, perhaps, be concatenated with commas or something.

**Comment by Siedlerchr** [comment]
@wujastyk  It's not possible to have the same field twice in bibtex/biblatex with the same name. The spec does not allow this. Think of it like a Dictionary with key-value mapping. More details here http://tug.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf 

Show a warning with "Warning: You added field X twice. Only one will be kept." 

Codwise the dialog is located here https://github.com/JabRef/jabref/tree/main/src/main/java/org/jabref/gui/customentrytypes

**Comment by dimitrisdimos00** [comment]
Thanks for the guidance! I will try this out.

**Comment by wujastyk** [comment]
@Siedlerchr yes, no, quite.  I understand the limitations and features of BibTeX and BibLaTeX.  

My thought was that maybe JabRef could repackage multiple-field data into a single output BibTeX field.  ISBN is probably insoluble, unless the info was concatenated into a note field.  With multiple urls, which I have a _lot_, perhaps multiple urls could be wrapped in \url{xxx} and concatenated into a note or some other field.  But the more I think about this, the more I think it's probably too fiddly and not very good.

**Comment by dimitrisdimos00** [comment]
Hello there. I have fixed the issue with the warning and all, however when running gradlew.check inside the jabref folder, these are the test results. Do you know what's the problem? What should I do with them? Thanks in advance.
![image](https://user-images.githubusercontent.com/56233132/148237725-a4d89f02-5bb9-476d-9de9-1fb8814d9c15.png)

**Comment by Siedlerchr** [comment]
@dimitrisdimos00  You do not reed to run gradlew check locally, when you create a PR the Github Actions CI is executed with the unit tests. If that is green, then it's fine.

If you modify a class that has existing tests, it's of course useful to execute them in your IDE locally. Also, useful is usually the LocalizationConsistencyTest e.g. if you changed/added the L10n.

Otherwise, proceed with your PR so we can review it.
