### ISSUE TITLE
Display "Show in Folder" notification after exporting entries

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#8195]
**Is your suggestion for improvement related to a problem? Please describe.**
Users will likely wanna open the file they exported as soon as possible, it's common among other applications to have this feature so implementing it will improve user experience because users expect it

**Describe the solution you'd like**
*solution 1:* show a notification bar with a button to open the directory where the file was exported (Like **Typora**)
*solution 2:* open the exported file immediately (Like **MS Word**)

**Additional context**
Screenshot from Typora

![](https://i.imgur.com/i41aMfn.png)

**Comment by LingZhang22** [comment]
Hi, I'm Ling and I am a student majoring in computer science. I am new to open source and am interested in this issue. I have some basic knowledge of Java and Web development. Could you give me some suggestions on where to start? Thanks a lot!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hello @LingZhang22 !
I am not too familiar with these parts of the code, and not sure how I'd put the pieces together, but I'd start looking at the [export command](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/exporter/ExportCommand.java) (which also happens to be based on the [command design pattern](https://refactoring.guru/design-patterns/command)).
Then look at how other parts of the code is using the [JabRef dialog service](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/JabRefDialogService.java) (or [its interface](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/DialogService.java)), e.g., by [go to declaration or usage](https://www.baeldung.com/intellij-idea-shortcuts#:~:text=it%20has%20a%20mouse%20shortcut%3A%20ctrl%20%2B%20click%20on%20windows%20and%20cmd%20%2B%20click%20on%20macos.) or [find everywhere](https://www.baeldung.com/intellij-idea-shortcuts#:~:text=it%20has%20a%20mouse%20shortcut%3A%20ctrl%20%2B%20click%20on%20windows%20and%20cmd%20%2B%20click%20on%20macos.).
Probably you'll need the [JabRefDesktop](https://github.com/JabRef/jabref/blob/5149ee1edefe648ee0bc07592ea85b0ffe884dc5/src/main/java/org/jabref/gui/desktop/JabRefDesktop.java#L187-L190) at some point as well

**Comment by LingZhang22** [comment]
Hi @k3KAW8Pnf7mkmdSMPHz27, thank you so much for your guide! I will look into those code and info!

**Comment by LingZhang22** [comment]
Hi @k3KAW8Pnf7mkmdSMPHz27 !
I created a PR for this issue. However, I think that this fix might need some improvement.

Firstly, the layout of the dialog is not well designed. The dialog pops up in the center of the main window as follows. It might be better if show a notification bar like **Typora** on the top of the window. But I didn't find an API for that. Could you give me some hints on where I can find such an API or how should I write such a function?
<img width="424" alt="image" src="https://user-images.githubusercontent.com/51975100/158171614-cc3abd44-2867-4558-bc5f-be3f673589a4.png">

Secondly, when the users click "YES", the saved file folder rather than the file will pop up. However, I also didn't find that API. Could you please give me some hints for that too?

Many thanks!

**Comment by ThiloteE** [comment]
Maybe a popover would be suitable for this? https://github.com/controlsfx/controlsfx/wiki/ControlsFX-Features#popover

**Comment by LingZhang22** [comment]
@ThiloteE  Thanks! I will look into this material!

**Comment by Siedlerchr** [comment]
For the change detection  dialog we use a NotificationPane from Controlsfx, that looks like one in Typora https://controlsfx.github.io/features/notificationspane/

**Comment by LingZhang22** [comment]
Hi @Siedlerchr, thank you for your instruction. And I got stuck, is it possible to get some help to go forward?

What I did so far:
I wrap the splitPane (which is the center of the JabRefFrame) into the NotificationPane. (And I tested that the bar can show on the page if I made some actions in the JabRefFrame class. )

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/51975100/158587148-906353db-d802-4778-956e-99c227a4860f.png">

My question:
In the ExportCommand, I want to call and add actions to the notificationPane when the user click save. But I don't know how to can I get the notificationPane instance. Is it possible to get a notificationPane instance from the JabRefFrame in the ExportCommand or I am in the wrong direction?

Thanks a lot!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> In the[ ExportCommand](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/exporter/ExportCommand.java?rgh-link-date=2022-03-16T12%3A20%3A42Z) class, I want to call and add actions to the notificationPane when the user click save.

If I am understanding you correctly, you are creating the notificationpane inside of JabRefFrame, in which case you probably want to pass it as an additional argument to the `ExportCommand`-class' constructor

**Comment by LingZhang22** [comment]
Hi @k3KAW8Pnf7mkmdSMPHz27  Thank you so much for your guide!

I have implemented the NotificationPane for the light theme and dark theme. 

When I clicked the save button, the notification bar will show on the top.
And if I click open, the folder will open with the file selected and then the bar will disappear. 
In addition, if the user doesn't take action, the notification bar will disappear in 10 seconds.

In light theme:
Step1:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/51975100/159037502-52d79da2-2219-4fb8-b1ac-31c4f9053040.png">

Step2：
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/51975100/159037687-024f204e-7351-47c9-a269-20c136946c8e.png">
 
Step3:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/51975100/159039776-99e37c6d-8c34-479b-8565-57b5e4dd43cd.png">

In dark theme：
Step1:
<img width="545" 
alt="image" src="https://user-images.githubusercontent.com/51975100/159038243-1dfe2ac8-33d2-4b50-b1b2-108791bcc26f.png">

Step2:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/51975100/159038301-2e4fffcf-0cd0-4fe4-a9c8-e050576b9235.png">

Step3:
<img width="907" alt="image" src="https://user-images.githubusercontent.com/51975100/159038580-e9efa664-7a10-44ae-bb24-0fa960b97b49.png">

I have pushed my commits to GitHub. I am not sure whether there is something wrong or missing. If there is, could you please let me know? I will modify it.

Thanks!

**Comment by ThiloteE** [comment]
I think the wording could be phrased slightly different:

Instead of "Do you want to open the file in folder?"
it could be: "**Press "open" to reveal the folder holding the saved file**"
(or shorter: "**Open the folder holding the saved file**"), 
since not actually the file is opened, but rather the folder :-)

**Comment by LingZhang22** [comment]
@ThiloteE Thank you for your suggestions. I have changed the text. Thanks :)
