### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by KyunghoKim29** [JabRef/jabref#8197]
**Is your suggestion for improvement related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

Can I translate into Korean?

**Comment by KyunghoKim29** [comment]
thank you!
I will try it!

**Comment by Siedlerchr** [comment]
I just synced the translations and Korean langauge and translation should be avaiable now in the latest dev version https://builds.jabref.org/main/
