### ISSUE TITLE
`Pages` and `Pagetotal` fields not displayed

### ISSUE THREAD

**Issue by dbitouze** [JabRef/jabref#8210]
### JabRef version

5.3 (latest release)

### Operating system

mac OS

### Details on version and operating system

?

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Students of mine, who are using macOS, experienced a problem when they add a `book` entry: (at least) the `Pages` and `Pagetotal` fields are not displayed. No such an issue on my Linux box.

(Sorry, I had to lie in order to fill this issue: I didn't check the latest dev versions since I noticed this trouble this afternoon during the (LaTeX) course but I won't see these students anymore.)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Hi,
the fields depend on the library mode if you use bibtex or biblatex.  I did a quick check. Pages and Pagetotal are only crated in biblatex mode.

You can check the library mode: Library -> Library properties -> Library mode
You can also set a default library mode in the Preferences.

**Comment by koppor** [comment]
The semantics of `pages` is the number of pages in a book. Meaning a kind of "length". I wonder why this would be important to enter. 😇 

From [Tame the beast](http://texdoc.net/texmf-dist/doc/bibtex/tamethebeast/ttb_en.pdf):

![grafik](https://user-images.githubusercontent.com/1366654/140805559-ab44aae2-dabe-49df-a95d-d3be79133fc9.png)

![grafik](https://user-images.githubusercontent.com/1366654/140807746-fb2b11dd-9f8f-4a4b-b979-578e80234ad0.png)

JabRef offers to enter the "pages" field in the BibTeX source tab (until we "finish" the new entry editor concept - see #6856).

BibLaTeX:

![grafik](https://user-images.githubusercontent.com/1366654/140808012-48abb26a-59a8-4ce1-8e17-204d1b4c9758.png)


@dbitouze Until now, JabRef was very picky in standard conformance and tries to be as close to the standard as possible. We think, this is confusing and we will add `pages` to our config (`org.jabref.model.entry.BibEntryType`).

**Comment by koppor** [comment]
Update: tex.stackexchange: https://tex.stackexchange.com/q/373754/9075

![grafik](https://user-images.githubusercontent.com/1366654/140809107-8dd6ade5-5907-474b-b238-34606a531b95.png)

@dbitouze Would you like to contribute to the tex.stackexchange question and lay down your thoughts on using `pages` at `@book`?

**Comment by koppor** [comment]
Note that one can modify a `bst` to output the page numbers at `@book`: https://tex.stackexchange.com/q/114773/9075

**Comment by koppor** [comment]
## Summary

1. User uses an database opened
2. User uses bibtex mode
3. User clicks on new entry  
  ![grafik](https://user-images.githubusercontent.com/1366654/140810034-c961b78d-702c-43d2-93c8-013a6dd7f8a3.png)
4. User selects "Book"\
  ![grafik](https://user-images.githubusercontent.com/1366654/140810414-ddd66720-d8ab-47e0-824a-a81188899cd4.png)
5. User does not find pages:\
  ![grafik](https://user-images.githubusercontent.com/1366654/140810145-bbf4c795-64db-4e71-87a0-f7761813d208.png)\
  ![grafik](https://user-images.githubusercontent.com/1366654/140810118-c37a4192-ef2a-4077-bc00-5061dd18f671.png)\
  ![grafik](https://user-images.githubusercontent.com/1366654/140810172-1c820aef-1deb-4273-8bf6-25fad2fdce64.png)\
  ![grafik](https://user-images.githubusercontent.com/1366654/140810183-4f50938b-f1b7-4389-99ca-c107d79e1d99.png)

## Work around

6. User goes to BibTeX source and enters `pages`
7. Entry editor creates tab "Other fields"\
  ![grafik](https://user-images.githubusercontent.com/1366654/140810357-57693bb2-3069-42ab-8db7-b1c9be77f0e5.png)
