### ISSUE TITLE
Search does not work at all

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8234]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-11-11--80ab4ca Linux 5.14.16-301.fc35.x86_64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ... search for an entry in the search field

no change/no search results are shown

**Comment by calixtus** [comment]
#8213 related?
What happened here?

**Comment by calixtus** [comment]
Hi Ingmar, i tried to run JabRef on Windows and on Linux with the most recent development branch, but I could not reproduce your issues. Maybe another @JabRef/developers could try.

**Comment by Siedlerchr** [comment]
I cannot reproduce this either. Can you try to reset your preferences?

**Comment by Siedlerchr** [comment]
@ilippert  I have created a fix for the error. It should now be working again https://builds.jabref.org/main/

**Comment by ilippert** [comment]
> @ilippert I have created a fix for the error. It should now be working again https://builds.jabref.org/main/

works wonderfully! Thanks for sparing me a preferences reset
