### ISSUE TITLE
Left Side Input of Entry Editor become small when window is resized

### ISSUE THREAD

**Issue by darkshadowlho** [JabRef/jabref#8236]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H1

### Checked with the latest development build

- [ ] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open Entry Editor in full screen is not problem
2. Resize window, the left side become so small

### Appendix
Screenshoot :
![image](https://user-images.githubusercontent.com/45134464/141445555-9943e2fb-bcc3-457f-8432-427f57b44efb.png)

**Comment by Siedlerchr** [comment]
Dupliacte of  #7986
