### ISSUE TITLE
MimeTypeDetector fails for local URIs

### ISSUE THREAD

**Issue by henini** [JabRef/jabref#824]
When a URL encoded local URI is passed to the function

`MimeTypeDetector.isPdfContentType(String url)`

the return value turns out to be False if `url` is a local URI. 
If one likes to implement `FullTextFinder` using a temporary copy of some fetched PDF this needs to be changed.

**Comment by stefan-kolb** [comment]
You are thinking of URIs like `file:/C:/Users/Stefan/Desktop/Github/jabref/build/resources/test/net/sf/jabref/logic/io/empty.pdf`?

**Comment by henini** [comment]
Exactly, the current implementation seems to work for http URLs only.

I also tried to write a test, but trying to get absolute paths in Java annoyed me a bit.

**Comment by stefan-kolb** [comment]
The question is what URLs/Paths should MimeTypeDetector be able to categorize.
Is `C:/Users/Stefan/Desktop/Github/jabref/build/resources/test/net/sf/jabref/logic/io/empty.pdf` also a valid input here? Do we really need to check local URLs and paths? At the moment there is no use case (FullTextFinder) for this.

**Comment by henini** [comment]
URLConnection works for local URIs as well as http URLs.
Some institutional APIs return a PDF file instead of a link to a PDF. Generalising MimeTypeDetector eases writing custom fetchers a bit.

**Comment by simonharrer** [comment]
:+1: for adding a test :)

**Comment by tobiasdiez** [comment]
Mhhh... the code checks the HTTP header `Content-Type` and thus fails for local URIs since these don't have a HTTP header.

To be honest, I don't see the use-case to allow local URIs. Are you trying to check that a file with `.pdf` ending is really a pdf? Can you please elaborate a bit more on what you are trying to achieve.

**Comment by henini** [comment]
`java.net.URLConnection` has `getContentType()`, which returns the Content-Type of a file:// URI as well as the Content-Type of a http:// URL, replacing the code in MimeTypeDetector does not break the current tests

**Comment by stefan-kolb** [comment]
I already created a test, but will only push it later so it doesn't break the build.
