### ISSUE TITLE
Search bar across different bib files

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#825]
This is not a bug, but rather a question of user behavior.
JabRef is constructed to work with several bib files open.

At the moment, the search field is bound to one bib file. If you search for "Doe" in a.bib, the search field   in b.bib remains empty. 

For users who search for a particular entry, but don't know in which file it is this is rather complicated. I have to search for the same term several times.

-> wouldn't it be more convenient, that the search field remains the same for every bib file?
I have the feeling that at least the GUI suggests such a behavior. At least it occurs to me quite often that I search in one file and think 'o the entry must be in the other file', switch the file and than need to realize, that I have to search again.

Ok, there is the global search function for that. But it has several drawbacks: 
1. entries can only be seen in preview-> I can't edit and have to gather the information from the entry preview, which is quite different from the editing window.
2. Doubleclick on an entry in global search sometimes gives wrong results. E.g. After having filtered b.bib for "Doe" a while ago, work on a.bib and search for "Abraham" globally. Global search shows you, that there is an entry "Abraham" in b.bib, but if you double click you can't access the entry, because it is not part of the filtered list from previous search
 
A searchbar, that has the same token in every bib file would be more intuitive and convenient, I think.

**Comment by simonharrer** [comment]
Hm, moving the local search bar to a global one would also be acceptable for me. 

Changes
- search bar shown directly below toolbar, not within tab
- search will (may) be slower as it has to search in every open bib file
- each search query does a global search
- the previous global search does nothing more than open a window with all found entries, but does not execute a search

**Comment by teertinker** [comment]
If the search bar remains in its current implementation (bound to one bib file), hitting the global search button should definitely reset all active searchterms in each tab. Otherwise double-clicking on entries in global search always directs to an entry which cannot be seen (only in case previous search terms and global search do overlap, which should happen seldomly, since there would be no need to trigger a global search after all)

**Comment by koppor** [comment]
Some users even don't know that there is a global search. :flushed:

Proposal: Keep the search strings at each tab in sync and update each tab on tab focus change.

**Comment by teertinker** [comment]
That would be great! (Remark: I hope this solves the issue that a double click on a globally searched entry does not lead to an entry, because of an existing filter from previous search)

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version (by merging #1549).
Please use a development build from http://builds.jabref.org/master
The fix will be included in the next release.
