### ISSUE TITLE
The Entry type when exported to `.ods` is not unique for each different kind of entry, I guess it should be.

### ISSUE THREAD

**Issue by AngelicaRibeiro** [JabRef/jabref#8269]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

DISTRIB_ID=ManjaroLinux  / DISTRIB_RELEASE=21.2.0 / DISTRIB_CODENAME=Qonos / DISTRIB_DESCRIPTION="Manjaro Linux"

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I have tested with each kind of entry type available in JabRef
2.  ![EntrieType](https://user-images.githubusercontent.com/13433634/142920698-f774eb94-d58d-461f-abac-c54cc3abb71a.png)
3. and the ods file exported should have a different number for each entry such they are different kinds of scientific reports; what I've got is this  as shown in the picture: 
4. ![odsEntrieTipe](https://user-images.githubusercontent.com/13433634/142920923-c49a7649-0227-4c13-af81-434acf7c117f.png)
 

### Appendix

![EntrieType](https://user-images.githubusercontent.com/13433634/142921215-0415a316-af18-4a0e-8dcf-bdd5d05cc3fb.png)
![odsEntrieTipe](https://user-images.githubusercontent.com/13433634/142921217-daad72ee-7daf-4847-af51-86e1ab7476b0.png)

**Comment by Siedlerchr** [comment]
Hi,

I was just checking on another issue, and found out that this is just because the ods exporter is intended to create ods files to be used with OpenOffice/LibreOffice internal bibliography manager. And it seems that JabRef supports more Entry Types that have no directly equivalent in LibreOffice/OpenOffice.

I don't know how useful this is and if we should get rid of that Exporter and make it a template base one as JabRef has an integration for LO.

See here for an example of OO's feature https://wiki.openoffice.org/wiki/Documentation/OOoAuthors_User_Manual/Writer_Guide/Creating_a_bibliography

**Comment by koppor** [comment]
@AngelicaRibeiro We think, this behavior works as intended. Does it cause issues at your side when using the exported file in LibreOffice? - In case you do not intend to use LibreOffice, you could use the CSV export. --> https://docs.jabref.org/faq#q-how-do-i-export-my-bibliography-entries-into-a-simple-text-file-so-i-can-import-them-into-a-spread

@AngelicaRibeiro Did you know that we offer a LibreOffice Plugin?

**Comment by AngelicaRibeiro** [comment]
Nope, where I can find this plugin?

**Comment by Siedlerchr** [comment]
@AngelicaRibeiro  Not a plugin, it's directly integrated into JabRef. https://docs.jabref.org/cite/openofficeintegration

**Comment by AngelicaRibeiro** [comment]
I've tested the plugin but it didn't solve the  problem, there is a way to export just the entire type so that I can copy and past in LibreOffice calc ?

**Comment by AngelicaRibeiro** [comment]
I've exported to '.html' and then copied the column of interest. 
It's a hack, but it works :) 
Thanks for everything, guys :+1:
