### ISSUE TITLE
Run multiple jabref on Windows Server

### ISSUE THREAD

**Issue by WILHELMFabien** [JabRef/jabref#8272]
we want to share jabref on a windows server through the RDP protocol. we can't launch a second session of jabref.
is it possible ? do we have to do a registry setting ?

**Comment by Siedlerchr** [comment]
Hi,

you can disable the feature "Listen for remote operations" In JabRef -> Preferences -> Network -> Remote operation
Uncheck the option.
Then you can run multiple instance of JabRef.
An alternative option would be to use a shared SQL Database (We recommend PostgresSQL) and have JabRef installed on every client.
https://docs.jabref.org/collaborative-work/sqldatabase

**Comment by ThiloteE** [comment]
Some hacky way would be to decrease the network connection timeout. We recently had a bug that resulted in multiple JabRef instances being launched. See https://github.com/JabRef/jabref/commit/e3b2ab2264d184fafdf347d2ac3cca59b7b9c0f5

**Comment by ThiloteE** [comment]
Closing this, as there has not been any reply and some workarounds/solutions exist.
