### ISSUE TITLE
Export to CSV - keywords not exported

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#8273]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a `.bib` file with keywords
2. Export to CSV
3. No `keywords` field exported

**Comment by Siedlerchr** [comment]
SEe my answer https://github.com/JabRef/jabref/issues/8274#issuecomment-978149838
