### ISSUE TITLE
Export to CSV - Abstract field broken up to multiple Custom fields

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#8274]
### JabRef version

5.3 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a `.bib` file with abstracts
2. Export to CSV
3. The resulting file has broken up the abstract to multiple `Custom1`, `Custom2`, `Custom3`, ... `CustomX` fields

**Comment by Siedlerchr** [comment]
Hi,

well, this the default layout which once was created to be somehow serve as a source for OpenOffice/LibreOffice. 
You can easily adjust it to your custom format. All fields were exported correctly (also keywords), and Abstract is only exported to one field custom1. 
I only had to fix my author in the bib file itself, it was using `J\"org Lenhard ` syntax to have it correctly adjusted to the columns. A right click -> Normalize authors did the trick.


Just copy the csv files to a new folder https://github.com/JabRef/jabref/tree/main/src/main/resources/resource/layout/openoffice
and then add them as [Custom Export](https://docs.jabref.org/collaborative-work/export/customexports)
