### ISSUE TITLE
Add XMP metadata has been written succesfully/failed to pdf

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8276]
Jabref version 5.3 is able to write XMP metadata to pdfs.

**Problem:**

- I don't know if it has finished writing it.
- I don't know if it was successful or has failed

**Solution i would like:**
Something that allows me to know.

- I favour a loading `timer`/`symbol`/`button`/`row` or `column` that visibly fills up and that vanishes after the action has been completed. -->  It provides both information, but also does not disturb the user.

Other solutions could be:

- a popup --> disturbs workflow
- a symbol that changes colour once. -->  but if i want to write metadata again, then it would need to change colour again --> imperfect
- Show information about what kind of metadata is currently attached to PDF(s) --> Workaround, not straightforward. Might require big changes to UI.

**Comment by ThiloteE** [comment]
If i write XMP metadata to more than one file, there should NOT be a popup for every single file. 100 files, 100 popups is a big no no xD

**Comment by ThiloteE** [comment]
Maybe a loading button or something that vanishes after the action is done would be best. It both provides information but also does not disturb the user :)

**Comment by ThiloteE** [comment]
This is issue is only relevant for the functionality of writing metadata to a pdf-file from within the general tab in the entry editor.

**Comment by harshlancer** [comment]
Hey, I'm new to the open-source community can I contribute to this project I know how to code in Java.
Please tell me if I can contribute in any manner.

**Comment by ThiloteE** [comment]
I apologize for not responding sooner!

Welcome to JabRef @harshlancer ! Check out our Contribution Guide https://devdocs.jabref.org/contributing

Meanwhile, it is possible to export XMP metadata via `Tools > Write metadata to pdfs (F6)` again.
![image](https://user-images.githubusercontent.com/73715071/158151322-09c3c8ca-1e25-4621-8374-5d8eef554263.png)
I believe, back then, when I opened this issue this was not possible.

Writing metadata via F6 actually has a mechanism that shows if the write-process was successful or not. For this reason, the importance of solving this issue has diminished, but If you have taken an interest in this issue, sure, you are welcome :-)

Maybe it would be possible to re-use part of the code from the F6 functionality?
(Unfortunately I don't know where that part of the code would be and I am not deep into coding, so i am not much help assisting in that regard)

**Comment by ThiloteE** [comment]
As a reminder: This issue is only relevant for what happens when clicking on the following button:
![image](https://user-images.githubusercontent.com/73715071/158154570-8305d0f7-0251-413e-97f3-f5bc4265d33c.png)

**Comment by vithlaithla** [comment]
Hi, I would like to contribute to the project and work on this issue.

**Comment by ThiloteE** [comment]
@vithlaithla, hey sure. Do you know Antonio? This draft pull request already looks pretty good! Maybe you can talk to each other? If you prefer to work on a different issue alone, because this issue is too small for the both of you, check the labels for "[good first issue](https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+)" or if you are a student and need a project check out [JabRefs candidate for university projects page](https://github.com/JabRef/jabref/projects/9).

**Comment by vithlaithla** [comment]
@ThiloteE hey thanks for the suggestions! I will look for other issues.
