### ISSUE TITLE
In  CSL preview, journal title and series name are duplicated

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#8279]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.4--2021-11-25--7aaf5e2 Linux 5.11.0-40-generic amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. go to the preview tab for any article etc.
2. Display has the journal title duplicated:

Journal:

![image](https://user-images.githubusercontent.com/762246/143621958-e33161c8-fdb8-4342-b863-ffb8b120c66b.png)

Book in series:

![image](https://user-images.githubusercontent.com/762246/143622024-ce4121f9-812f-491b-9188-3c2edc7080b0.png)

I have tried a dozen or so different preview styles.  Above are "Chicago Manual of Style 17th ed" and "Oxford Studies in Ancient Philosophy", but it's the same whatever style I choose.

I wouldn't mind editing the preview template to my liking, but that's currently not available

### Appendix

```
@Article{wixt-2018,
  author           = {John T. Wixted and Laura Mickes and Ronald P. Fisher},
  date             = {2018-05},
  journal          = {Perspectives on Psychological Science},
  number           = {3},
  pages            = {324--335},
  title            = {Rethinking the Reliability of Eyewitness Memory},
  volume           = {13},
  doi              = {10.1177/1745691617734878},
  abstract         = {Although certain pockets within the broad field of academic psychology have come to appreciate that eyewitness memory is more reliable than was once believed, the prevailing view, by far, is that eyewitness memory is unreliable—a blanket assessment that increasingly pervades the legal system. On the surface, this verdict seems unavoidable: Research convincingly shows that memory is malleable, and eyewitness misidentifications are known to have played a role in most of the DNA exonerations of the innocent. However, we argue here that, like DNA evidence and other kinds of scientifically validated forensic evidence, eyewitness memory is reliable if it is not contaminated and if proper testing procedures are used. This conclusion applies to eyewitness memory broadly conceived, whether the test involves recognition (from a police lineup) or recall (during a police interview). From this perspective, eyewitness memory has been wrongfully convicted of mistakes that are better construed as having been committed by other actors in the legal system, not by the eyewitnesses themselves. Eyewitnesses typically provide reliable evidence on an initial, uncontaminated memory test, and this is true even for most of the wrongful convictions that were later reversed by DNA evidence.},
  creationdate     = {2021-11-26T11:28:38},
  modificationdate = {2021-11-26T11:58:46},
  publisher        = {{SAGE} Publications},
}

@Book{qvar-yoga2,
  author           = {Olle Qvarnström},
  date             = {2013},
  location         = {Mumbai},
  publisher        = {Hindi Granth Karyalay},
  title            = {A Handbook on the Three Jewels of Jainism: The Yogaśāstra of Hemacandra},
  edition          = {6},
  isbn             = {9780674009349},
  series           = {Harvard Oriental Series},
  comment          = {Revised edition of \cite{qvar-yoga}. Hemacandra lived in the late 11th century.},
  file             = {:Quarnström, O/Quarnström_The Yogasastra of Hemacandra_2002.pdf:PDF},
  modificationdate = {2018-09-17T00:00:00},
}


```

**Comment by ThiloteE** [comment]
JabRef 5.4--2021-11-25--7ec4c7e
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

I can second this. I have seen this a lot as well.

Here is the one from Modern Language Association 9th version:
![image](https://user-images.githubusercontent.com/73715071/143622860-acf349ab-7285-4f47-99c7-2851a50dab3c.png)

```
@Article{Abdullah202005NNN,
  author       = {Walid Jumblatt Abdullah},
  date         = {2020-05},
  journaltitle = {Democratization},
  title        = {New Normal No More: Democratic Backsliding in Singapore After 2015},
  doi          = {10.1080/13510347.2020.1764940},
  number       = {7},
  pages        = {1123--1141},
  volume       = {27},
  file         = {:Abdullah (2020) New normal no more. Democratic backsliding in Singapore after 2015.pdf:PDF},
  publisher    = {Informa UK Limited},
}
```

**Comment by ThiloteE** [comment]
The same shows up also under `options>preferences>entry preview`. Not all citationstyles do have this duplication, but many do. For some it is the `journal` field, for some it only is the `number` field.

**Comment by Siedlerchr** [comment]
Question: Do you have bibtex or biblatex mode in your library? Does it make a difference?

**Comment by wujastyk** [comment]
Normally biblatex.  Tried changing to bibtex, both in main Preferences and in Library.  No change.

**Comment by ThiloteE** [comment]
Dito. I also tried to convert some entries from biblatex to bibtex style via `cleanup entries` to see if there was a change in the preview, but there was no change.

**Comment by ThiloteE** [comment]
```
</macro>
  <macro name="number">
    <group delimiter=", ">
      <group>
        <choose>
          <!--lowercase if we have a preceding element-->
          <if variable="edition container-title" match="any">
            <text macro="volume-lowercase"/>
          </if>
          <!--other contributors preceding the volume-->
          <else-if variable="author" match="all">
            <choose>
              <if variable="editor translator container-author illustrator interviewer director" match="any">
                <text macro="volume-lowercase"/>
              </if>
            </choose>
          </else-if>
          <else-if variable="editor" match="all">
            <choose>
              <if variable="translator container-author illustrator interviewer director" match="any">
                <text macro="volume-lowercase"/>
              </if>
            </choose>
          </else-if>
          <else-if variable="container-author illustrator interviewer director" match="any">
            <text macro="volume-lowercase"/>
          </else-if>
          <else>
            <group delimiter=" ">
              <text term="volume" form="short" text-case="capitalize-first"/>
              <text variable="volume"/>
            </group>
          </else>
        </choose>
      </group>
      <group delimiter=" ">
        <text term="issue" form="short"/>
        <text variable="issue"/>
      </group>
      <choose>
        <if type="report">
          <text variable="genre"/>
        </if>
      </choose>
      <text variable="number"/>
    </group>
 ``` 
The above seems to be the part responsible for `number` in the csl style 'Modern Language Association 9th edition'.
Does somebody understand the csl-syntax well enough to tell us, if the fault lies therein?

I tried to read csl documentation (https://docs.citationstyles.org/en/stable/specification.html#choose) and i think it is because at the very end, these last lines are kinda separated from the other group/choose arguments and there should be some kind of `if`, `else` or `else if` argument in-between or maybe even a `choose`  argument surrounding this part and the large part that comes before, but i am not completely sure.

      <group delimiter=" ">
        <text term="issue" form="short"/>
        <text variable="issue"/>
      </group>
      <choose>
        <if type="report">
          <text variable="genre"/>
        </if>
      </choose>
      <text variable="number"/>
    </group>
    
If i am correct, that would mean A LOT of CSL styles would need to be corrected manually, as we can see a lot of duplicates of this issue in other styles. I hope i am wrong 😂

**Comment by Siedlerchr** [comment]
The CSL Styles are here, they are updated automatically from the remote repo, maybe something from the last update went wrong?
https://github.com/JabRef/jabref/tree/main/buildres/csl

**Comment by ThiloteE** [comment]
I just tested an entry i posted above with Zotero and there it works fine. See:

`Thompson, Mark R. ‘Middle-Class Remorse: Re-Embracing Liberal Democracy in the Philippines and Thailand’. Global Asia, vol. 15, no. 1, East Asia Foundation, Mar. 2020, pp. 60–64.`

In Jabref we have the dublicate. See:

![image](https://user-images.githubusercontent.com/73715071/143773434-302ada6f-b872-483d-8e61-462930c31fff.png)

I checked with Winmerge if the citation-style code is any different between the ones used by Zotero (https://www.zotero.org/styles/modern-language-association) and the one from Jabref (`Options>preferences>entry preview>Modern Language Association 9th edition`) and there was **no difference**.

Looks like is more an implementation problem. What i posted above is not relevant and i will delete my post, as it might confuse people.

Looks more like it is an implementation problem. I will delete my post from above. (I was on the wrong track. It will confuse people.)

**Comment by ThiloteE** [comment]
Follow up: There is ONE difference when i copy the code from Jabref (`Options>preferences>entry preview>Modern Language Association 9th edition>edit`) into the editor (= the text editor on Windows 10) and save it as a textfile: According to Winmerge, both used different line-break format.

**Comment by wujastyk** [comment]
Re: [link](https://github.com/JabRef/jabref/issues/8279#issuecomment-981094843)
> The CSL Styles are here, they are updated automatically from the remote repo, maybe something from the last update went wrong?

This has been an issue for a very long time.  Maybe a year? I've just been living with it, and only thought to report it now.

**Comment by Siedlerchr** [comment]
@ThiloteE  Would you mind reporting the issue here with your investigation details? https://github.com/michel-kraemer/citeproc-java
JabRef is using this library for the handling of the CSL styles.

**Comment by ThiloteE** [comment]
"This issue is now fixed in citeproc-java v3.0.0-alpha.3" - michel-kraemer

**Comment by Siedlerchr** [comment]
@ThiloteE  Thanks. Should be picked up by the Dependabot tomorrow with a couple of other updates.

**Comment by ThiloteE** [comment]
Awesome :-)

**Comment by wujastyk** [comment]
Thank you, everyone!
