### ISSUE TITLE
No content in table after importing new entry

### ISSUE THREAD

**Issue by vanukkalla** [JabRef/jabref#8286]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

Bodhi Linux 6 based on Ubuntu LTS 20.04, JabRef Versions 5.4 after Oct 24th

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Opening and closing an existing library is no problem
2. Importing a new citation adds the entry, saving the file is successful
3. Opening this modified file gives the error "no content in table" - library is not shown

This happens both when importing a saved citation from a website (ris, bibtex) and when importing from a jabref file.

Opening the library.bib file in an Editor shows the library and the newly added entry. 

It may be a similar error to 
https://discourse.jabref.org/t/no-content-in-table-jabref-5-3/3046

### Appendix

The entire session log:

Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.versionSanityCheck(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.performInitialization(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getProvider(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getILoggerFactory(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getLogger(Unknown Source)
	at org.slf4j@2.0.0-alpha5/org.slf4j.LoggerFactory.getLogger(Unknown Source)
	at org.jabref@5.4.519/org.jabref.gui.JabRefMain.<clinit>(Unknown Source)
	at org.jabref@5.4.519/org.jabref.gui.JabRefLauncher.main(Unknown Source)
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]

**Comment by vanukkalla** [comment]
I observe this behavior also when importing citations using the JabRef browser extension - citation gets imported, file is being saved successfully, but upon closing the file / JabRef and opening again, the error message "no content in table" is being displayed.

**Comment by Siedlerchr** [comment]
Do you have an example citation?

**Comment by vanukkalla** [comment]
A citation I wanted to import? Every single one I wanted to import from pubmed or a journal site resulted in this error.

**Comment by vanukkalla** [comment]
This is weired - it seems to be connect to one specific file, my main database file with close to 6000 citations. Using another file, importing is successful, I can close file and/or application, run JabRef again and the bin file will be loaded without problems.

**Comment by vanukkalla** [comment]
I just tested other files, it definitely is connected to my main database. With other files there are no problem.

**Comment by Siedlerchr** [comment]
Could you upload the bib file?  Or if you prefer not to make it public, you can send us the bib file privately to developers@jabref.org
Maybe there is some broken entry inside which is causing problems

**Comment by ThiloteE** [comment]
This!! i had the same problem, but i never found out why. I do have an old buggy library that i never got around to make further tests with. If i find time and push comes to shove i can send you this library as well.

**Comment by ThiloteE** [comment]
Never mind. I checked my old library and found no obvious problems or bugs. It must have been a different problem that has already been solved in newer development versions OR it was wrong usage on my part. Sorry for the noise.

**Comment by Siedlerchr** [comment]
You can also try to open the file through import. It could be that some error messages are then logged

**Comment by Siedlerchr** [comment]
Okay, after checking the file, I found out that the bib file was saved in UTF16BE and JabRef could not parse it correctly. After saving it with UTF8 it could be opened again.

**Comment by vanukkalla** [comment]
Many thanks!! Its working now, and I tested importing several citations.
Also, I checked the preferences and Jabref lists UTF-8 as  default encoding. I do not remember having changed this.
Thanks again!!!!
