### ISSUE TITLE
Exception at org.jabref.gui.desktop.os.Linux.lambda$nativeOpenFile$0

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8292]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Fedora 35

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I click on the bibtex key in the preview pane, I get this exception. Maybe related to https://github.com/JabRef/jabref/issues/8280?

### Appendix

...
<details>

<summary>Log File</summary>

```
java.lang.NullPointerException
	at java.base/java.io.File.<init>(Unknown Source)
	at org.jabref@5.4.519/org.jabref.gui.desktop.os.Linux.lambda$nativeOpenFile$0(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment]
Maybe related to #8255 and #7706
@evanpickett  You worked on this recently, do you mind taking a look at this issue?

**Comment by evanpickett** [comment]
I'm finishing up my semester at university and then I'll have more time to look at this, sorry for the delay!

**Comment by Siedlerchr** [comment]
@ilippert  I am having trouble reproducing this on my mac, I can click wherever I want but it does nothing
@mlep  You recently had the similar issue. 

Do you use the "Custom preview layout"? (e..g a modified version from JabRef's default) 
Do you display the DOI as hyperlink?

**Comment by Siedlerchr** [comment]
Found the bug. Simple fix is on the way

**Comment by ilippert** [comment]
sorry for no response for days - pandemic everywhere... thanks for the fix, and for looking into it!
