### ISSUE TITLE
Hex encoded character breakes entry

### ISSUE THREAD

**Issue by Mercynary** [JabRef/jabref#8303]
### JabRef version

5.3 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open _bug-1.bib_ 
2. Change something, e.g., generate a new Bibtex key and save the library
3. The Hex encoded character &#x2013; breaks the abstract field

I was able to track down the bug to the `formatAndResolveStrings` method in the `org.jabref.logic.bibtex.FieldWriter` class where the first encounter of the `#` enforces that the abstract field is closed with a `}`. 

### Appendix

[bug-1.txt](https://github.com/JabRef/jabref/files/7661797/bug-1.txt)
[bug-2.txt](https://github.com/JabRef/jabref/files/7661798/bug-2.txt)

**Comment by Siedlerchr** [comment]
Thanks for the report and also for the investigation/debugging. I guess the problem is related to the issue #7010 and  #7012
The problem is that a "#" can indicate a BibTeX string https://docs.jabref.org/advanced/strings constant.

**Comment by Mercynary** [comment]
> Thanks for the report and also for the investigation/debugging. I guess the problem is related to the issue #7010 and #7012 The problem is that a "#" can indicate a BibTeX string https://docs.jabref.org/advanced/strings constant.

Yes. I guess it might make sense to transform such characters while reading the field to Unicode characters.

**Comment by Siedlerchr** [comment]
@Mercynary  I think I found a workaround/solution.  In the Preferences -> File -> Check "Resolve strings for all fields exept"
and add comment and abstract to the list of fields with semicolon 
<img width="838" alt="grafik" src="https://user-images.githubusercontent.com/320228/146964418-b354a7c2-4458-4d3b-b335-2fc41d216986.png">

**Comment by Siedlerchr** [comment]
@Mercynary  In the latest development version we changed the whole logic and enable BibTeX string resolving only for a couple of fields. This can be adjusted in the options
