### ISSUE TITLE
Writeable fields should not cause rewriting of the whole entry

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#834]
When an entry is unmarked, the field `__markedentry` is removed. If all other fields are shorter, the complete entry changes as the alignment changes. I am aware that we decided that at #116. We have, however, not thought about such exceptional cases.

Example:
![grabbed_20160219-201705](https://cloud.githubusercontent.com/assets/1366654/13186287/d59e41be-d745-11e5-8213-67f04c65876a.png)
(I know that a little bit more changed here. My database is written as BibLaTeX database).

Suggestion: Do not include non-displayable fields in the calculation of the amount of spaces to write.

Refs #574

**Comment by oscargus** [comment]
Would it make sense to store the selected entires (which I think this particular __markedEntry means) in the metaData instead?

**Comment by tobiasdiez** [comment]
The `markedEntry` is not the real problem. The reformatting occurs whenever a long field (eg maintitleaddon) is removed. I wouldn't change the serialization algorithm just because of this and would live with the reformatting...

**Comment by koppor** [comment]
:+1: for metadata storing. Described at the paragraph starting with "A possible solution" at #574.

Proposal: First implement my solution (#851) and then work on #574.

**Comment by koppor** [comment]
Metadata storing: Difficult because of referential integrity. Therefore, we keep the information in the entry.

Fix: Rename `__markedentry` to `mark` and add a migration.

**Comment by lenhard** [comment]
Since the decision is no action, we can mark this issue as on hold and close it.

**Comment by koppor** [comment]
No freeze anymore as there are no non-writable fields anymore
