### ISSUE TITLE
Check integrity shows non UTF error even after both to UTF conversion steps

### ISSUE THREAD

**Issue by funnym0nk3y** [JabRef/jabref#8353]
### JabRef version

Other (please describe below)

### Operating system

Windows

### Details on version and operating system

5.4

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Load bib-file
2. Check integrity
3. Choose one entry
4. Convert HTML to Unicode via right click
5. Convert LaTeX to Unicode via right click
6. Save file
7. Check integrity again

### Appendix

bib entry

<details>

```
@Book{Winter15,
  author    = {Winter, Stefan},
  date      = {2014-11-20},
  title     = {Grundzüge der Spieltheorie},
  doi       = {10.1007/978-3-662-44422-1},
  isbn      = {978-3-662-44422-1},
  pagetotal = {275},
  publisher = {Springer-Verlag GmbH},
  url       = {https://www.ebook.de/de/product/25604327/stefan_winter_grundzuege_der_spieltheorie.html},
  ean       = {9783662444221},
  file      = {:Winter15 - Grundzüge Der Spieltheorie.pdf:PDF},
  year      = {2015},
}
```

</details>

**Comment by Siedlerchr** [comment]
Thanks for your report, seems  like a duplicate of #8022 and only happens on windows

**Comment by funnym0nk3y** [comment]
Okay, seemed new to me. Closing this...
