### ISSUE TITLE
Entry view improvement

### ISSUE THREAD

**Issue by funnym0nk3y** [JabRef/jabref#8368]
**Is your suggestion for improvement related to a problem? Please describe.**
With version 5.4 the optional fields tab got pretty cluttered. There are a lot of small fields making it difficult to select the right one whereas on the right there is plenty of space. 

![grafik](https://user-images.githubusercontent.com/41870754/147659634-57f48e5f-ea5e-4a6c-9f67-238fac3f9761.png)

**Describe the solution you'd like**
Maybe consider a three column layout or separate the optional fields tab into two tabs.

**Comment by ThiloteE** [comment]
Are you saying it is difficult to select or difficult to FIND the fields?

**Comment by ThiloteE** [comment]
Other solutions to be considered:

- search bar for fields
- single column layout (bigger rows and font size + scrollbar)

**Comment by funnym0nk3y** [comment]
@ThiloteE Selecting them is more or less fine. I struggle with quickly finding the desired field. This is, in my opinion, due to the number of rows in each column. Therefor disabling the preview dies not help.

**Comment by Siedlerchr** [comment]
You can customize the Entry types and only keep the fields you regulary use

**Comment by ThiloteE** [comment]
You can do what Christoph recommended here:

![image](https://user-images.githubusercontent.com/73715071/149278058-bb071cfa-4d0c-4d95-b8c2-0306924171ef.png)

@funnym0nk3y Would this work for you?

**Comment by funnym0nk3y** [comment]
@ThiloteE Sounds good. Can one customize each entry type separatly or is each optional tab the same then?

**Comment by ThiloteE** [comment]
As far as i am aware, the `required fields` and `optional fields` tabs cannot be changed there.

Those can be manipulated via `options > customize entry types`:
![image](https://user-images.githubusercontent.com/73715071/149521233-2617bb9d-23d2-4d31-8b45-5f994ca3f8a7.png)

Hmmm now that i think about it, `Customize entry types` and `Custom editor tabs` seem very much related. Would be nice to have them close to each other in the preferences, but alas right now they are separated.

**Comment by koppor** [comment]
General disussion is going on there: https://github.com/JabRef/jabref/issues/6856

I think, we cannot do much here without changing the whole entry editor. Therefore, closing this issue.
