### ISSUE TITLE
Add information about fields to Jabref

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8375]
**Problem**
- [ ] Jabref in general lacks information about the fields inside the entry editor. Lack of information makes users enter data into the field that does not conform to citation styles.

**Describe the solution you'd like**
- Add description inside Jabref (e.g. roughly similar to citavi)
OR
- Add more precise information to the docs and add small (?) button that links to the location in the docs https://docs.jabref.org/advanced/fields)

**Additional context**

How citavi add information about fields:

![image](https://user-images.githubusercontent.com/73715071/147852651-b03d20bd-3f23-4f5a-9bbe-763563081fb2.png)

**Comment by ThiloteE** [comment]
Example for why this would be a good idea see:

https://github.com/JabRef/jabref/issues/8374

**Comment by Siedlerchr** [comment]
This is already implemented for most standard fields:
You just have to hover over the field name in the entry editor (the description is from/adapted from the biblatex manual)
<img width="1399" alt="grafik" src="https://user-images.githubusercontent.com/320228/147853088-7b3b0996-7e1e-4b22-ad7b-e87e5e5f67ff.png">

**Comment by ThiloteE** [comment]
Thanks, i learned something!
