### ISSUE TITLE
"Cannot generate preview"

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#8381]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.5--2022-01-03--aac66f5 Linux 5.13.0-22-generic amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I pulled in the following new article entry using its DOI

```
@Article{baks-2021,
  author           = {Sandipan Baksi},
  date             = {2021},
  journaltitle     = {The Indian Economic {\&} Social History Review},
  pages            = {001946462110645},
  title            = {Science journalism in Hindi in pre-independence India: A study of Hindi periodicals},
  doi              = {10.1177/00194646211064586},
  creationdate     = {2022-01-03T11:59:38},
  modificationdate = {2022-01-03T12:01:49},
  publisher        = {{SAGE} Publications},
}
```
2. I got this error message from the preview tab:
![image](https://user-images.githubusercontent.com/762246/147969399-425ecd5a-1c6f-4b0d-833b-7c25cab0b633.png)
3.  I tried several preview styles: it made no difference.
4. Some testing showed that if I removed that long number from the `pages` field, everything behaved normally and the preview was fine.

**Comment by ThiloteE** [comment]
The long number seems part of the DOI as most of it overlaps. Imagine a document having such many page-numbers. It actually is good that the error emerged and you noticed that the data is not realistic. The author of the article should be noticed.

**Comment by wujastyk** [comment]
I disagree that this is a good error.  One should be able to put any numerical string in the page field.  There are some truly weird publications out there.

If JabRef really wants to flag a problem field value, then flag it.  But throwing a preview error is just confusing for everyone.

The error is in the DOI data delivery, and I've no idea who to talk to about that (doi.org? SAGE, the journal publishers?).  Nor do I have the resources to take up that task. I'm sure the author has no idea how to fix this either.

**Comment by Siedlerchr** [comment]
Thanks for opening the issue. I checked the DOI, it's coming directly from the publisher's site. Some publishers seem to abuse the pages field for other information.
The error is not really from JabRef, but from the underlying citation styles, where it indeed created an error.
Details of errors are always logged in the error console.
