### ISSUE TITLE
Font size preference does not apply correctly to Preference dialog window

### ISSUE THREAD

**Issue by shaman1892** [JabRef/jabref#8386]
### JabRef version

5.4 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Linux  5.15.12-100.fc34.x86_64 JabRef 5.4--2021-12-20--ab44182 Linux 5.15.12-100.fc34.x86_64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Steps to reproduce the behaviour

1. Goto Options -> preference-> appearance and override the default font settings (example fix it to 18)
2. Save preferences
3. restart JabRef
4. The interface has now the font size 18 as expected
5.  Goto Options -> preference-> appearance and uncheck the override option returning to the "normal" setting
6. save the preference
7. restart JabRef
8. The interface has now the "normal" font size as expected
9. open the  Options -> preference dialog and see that the fot size is still the modified one ( in this example font size 18)
10. From now on to modify the dialog window font size is always necessary to modify the override font size even if the override is not used.

### Appendix

![Screenshot from 2022-01-04 19-22-18](https://user-images.githubusercontent.com/97118223/148107086-13198949-52c0-4e61-8f0b-e66cb0493cba.png)

**Comment by tomazari** [comment]
Hey all! I am a software engineering student and would love to contribute to the project. I have seen this issue which looks fairly approachable and would love to be assigned to it!

I have been able to reproduce this (as described) on **Windows 10**. 
However, I could also argue this is not an issue as when a user de-selects the font size override, they may still seek to keep this font size. When you re-select it after the above repro steps, it changes to the override value again as expected.

If the preference is to have this value reflect the current font size, I would love to investigate and fix this. Thoughts?
