### ISSUE TITLE
remove 2nd click on entry type for changing entry type?

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8388]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

fedora 35, JabRef 5.5--2022-01-02--55ceed9 Linux 5.15.12-200.fc35.x86_64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. open entry editor
2. click once on the entry type on the left hand and select a different entry type with one click

the selection is not actually assigned to the entry

Problem is: seems SOMETIMES you need to click the selection twice.

**Comment by Siedlerchr** [comment]
I could reproduce this issue as well under Mac. Could be some javafx thingy... Not sure

**Comment by ilippert** [comment]
Just to add - it does not always happen but really often.

**Comment by Clunphumb** [comment]
I investigated and it appears to be a problem with JavaFX and how actions on labels are handled within CustomMenuItems. The clickable area to work is just barely around the label. If one tries to click on the empty space beside, no action is performed. 

This problem occurs all around JabRef wherever CustpmMenuItems are used, for example in the context menu of the "Author" Field when editing an entry and choosing "Normalize to BibTeX name format". If you try clicking on the outer right edge it doesn't work either.
