### ISSUE TITLE
'Copy DOI URL' in entry list only copies DOI but not the URL

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#8389]
### JabRef version

Latest development branch build (please note build date below)
JabRef 5.5--2022-01-03--c94bb1b
Linux 5.11.0-44-generic amd64 
Java 16.0.2 
JavaFX 17.0.1+1

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 20.04

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. In the entry list, right-click on a URL symbol in the URL column and chose menu item "Copy ... -> Copy DOI URL"
2. Paste from clipboard and you will only see the DOI pasted. 
3. Now, open that entry in the entry editor, go to "Optional fields", right-click on DOI and chose menu item "Copy DOI URL".
4. Paste from clipboard and you will see the DOI URL pasted.

**Comment by Shinigami** [comment]
Hello! It's my first time contributing, and I would like to try to work on this issue as it seems no one else is working on it. Also, I've already read the guide on contributing as well as the readme for this repository, but are there any other forms of advice that may help me out?

**Comment by Siedlerchr** [comment]
HI, welcome to JabRef! The first step is always trying to reproduce the issue. 
Then to find the differences. 
As a staring point, the MainTable  code for copying is somewhere in org.jabref.gui.maintable.RightClickMenu 
 and the other one (for the field in the Entry Editor)  And for the other one you should take a look  in org.jabref.gui.fieldeditors.contextmenu.EditorMenus

When you have a fix follow the guide and create a new PR.

**Comment by Siedlerchr** [comment]
I tested it and it works. For consistency reasons, I would also add the Copy DOI and Copy DOI Url context menu  to the entry editor 
<img width="640" alt="grafik" src="https://user-images.githubusercontent.com/320228/151713544-1f8017e6-ea82-4c96-8828-fa83ab787e6e.png">

**Comment by Shinigami** [comment]
I agree that there should be consistency between the menus. I've now added this into the PR:
![image](https://user-images.githubusercontent.com/58048740/151720654-a4cbb459-02a1-4f88-9288-254cfdc532d9.png)
