### ISSUE TITLE
JabRef 5.4 on macOS Monterey crashes all the time

### ISSUE THREAD

**Issue by jkrenz** [JabRef/jabref#8395]
### JabRef version

5.4 (latest release)

### Operating system

macOS

### Details on version and operating system

macOS 12.0.1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I open JabREf
2. it crashes (sometimes it lets me look at one entry first)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by jkrenz** [comment]
Here the error log file of one of the crashes.
[hs_err_pid3048.log](https://github.com/JabRef/jabref/files/7820723/hs_err_pid3048.log)

**Comment by Siedlerchr** [comment]
From the error log it looks like you still have an old version installed that started. Can you uninstall that before and then reinstall the new Release 5.4?

**Comment by jkrenz** [comment]
Sorry....! While installing it asked me whether it could overwrite the old file and I confirmed. However, apparently it didn't. Thank you!

**Comment by Siedlerchr** [comment]
Probably because it was a different installer system back then in the old version
