### ISSUE TITLE
Vertically align Groups and Web search panel

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8397]
**Problem:**

`Groups`, the `Add group` button, `Web search` and the `search` button for Web search are centrally aligned and it looks odd, because the button "Toggle intersection" and the multiple buttons "Move panel up", "Move panel down" and "Hide panel" skew two of the four more towards the left.

**Desired Solution:**

Align the text for the four along a common line.

Example:

The text could start somewhere along the red line:
![image](https://user-images.githubusercontent.com/73715071/148533409-925b8672-c049-4975-9f12-17f2a94faa7d.png)

I would refrain from aligning it completely to the left border as there should be a contrast to groups and search fields.

**Comment by mlep** [comment]
@dimitrisdimos00 : since you have already touch some of this, maybe you would like to pursue?

**Comment by ThiloteE** [comment]
Would something like this get the label UI or rather the label groups/search?

**Comment by mlep** [comment]
Both? :wink:

**Comment by ThiloteE** [comment]
ok xD

Btw. another alternative could be to align the buttons `Add group` and `Search` at the right side. There would still be contrast (the buttons would stand out more) and at the same time, the awkward looking centrally aligned indention vanishes.

I imagine both to be fine looking :)

**Comment by mlep** [comment]
I believe we are used to have the text of a button centered.
I suggest to wait for the merge of #8392 first, and then look at what can be improved further.

**Comment by dimitrisdimos00** [comment]
Hello. Yeah, I can look into it. So, shall we wait for the merge and then take a look at it?

**Comment by ThiloteE** [comment]
Yeah we can wait for the merger. This is not urgent as 5.4 stable was just released :)

**Comment by ilippert** [comment]
I would imagine that it would also look well if the names "Groups" and "Web search" are aligned left.

**Comment by mlep** [comment]
That is my understanding.
I guess we should consider all three panels together: Groups, OpenOffice/LibreOffice and Web search.

About the titles of the panel: they are a bit off-centered at the moment. Groups looks a bit displaced to the left at the moment when the panel is wide)

About their buttons:
- "Add group" is centered.
- "Search" is centered.
- the OpenOffice/Libreoffice buttons (there are 10 of them) are grouped to the left.


![ksnip_20220113-153206](https://user-images.githubusercontent.com/6931104/149349326-9085d847-2193-4e21-9758-346e8f685b09.png)

**Comment by dimitrisdimos00** [comment]
Yeah we definitely should look at all three of them. And we should decide which of the two we will implement.

**Comment by mlep** [comment]
A glitch that could be corrected in the meantime: while the `Add group` button extend to the whole panel width, the `Search` button of the web search panel does not. With the light theme, you need to put the pointer onto the button to see it, but in the dark theme it shows right away:
![ksnip_20220118-090634](https://user-images.githubusercontent.com/6931104/149898552-d3a2ace7-5d11-4bf8-ac7a-cb07deae1bb1.png)

My suggestion is to make the `Search` button  extend to the whole panel width.

**Comment by dimitrisdimos00** [comment]
Yeah, I noticed that too... I can look into it

**Comment by dimitrisdimos00** [comment]
Hey, check this out!
![image](https://user-images.githubusercontent.com/56233132/150702374-ef746fef-ad9f-4b6f-89dd-2c4cf22f831d.png)
![image](https://user-images.githubusercontent.com/56233132/150702586-e954e224-ab0d-437c-ab53-6814472664b9.png)

**Comment by dimitrisdimos00** [comment]
So shall I try moving the titles to the left? I think it is more plausible

**Comment by ThiloteE** [comment]
Maybe you can give us screenshots of the few options we have. We could vote :)

**Comment by dimitrisdimos00** [comment]
Here is how it looks when the titles are directed towards the left:
![image](https://user-images.githubusercontent.com/56233132/150803116-52515da5-0305-4723-a446-3a7593932149.png)

**Comment by ThiloteE** [comment]
How would this one look?

![image](https://user-images.githubusercontent.com/73715071/150830048-a316e609-49b4-4d9a-90de-7011dac110e5.png)

**Comment by dimitrisdimos00** [comment]
I don't think I can align all the items completely because the buttons up, down, delete (x) and union (in the case of groups) push the titles (blue text) a little bit more to the left. All the items are centered already...

**Comment by ThiloteE** [comment]
> because the buttons up, down, delete (x) and union (in the case of groups) push the titles (blue text) a little bit more to the left.

Yes, this is the main reason, why i created this thread.

**Comment by ThiloteE** [comment]
Oh well. Then let's give it https://github.com/JabRef/jabref/issues/8397#issuecomment-1020167880 a try.

**Comment by dimitrisdimos00** [comment]
Ok I will open a pr then

**Comment by mlep** [comment]
@dimitrisdimos00 Thanks! Now, titles really look like titles (and buttons look like buttons).

Note: the titles are not vertically centered. They are slightly moved upward.
![ksnip_20220126-173603](https://user-images.githubusercontent.com/6931104/151205984-2e689667-ef6c-47f4-ad9c-73da15286cb0.png)

**Comment by dimitrisdimos00** [comment]
Your welcome!

**Comment by Siedlerchr** [comment]
@dimitrisdimos00  The central css stylesheet: https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/Base.css
Group css https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/groups/GroupTree.css

Scenic view might be helpful https://github.com/JonathanGiles/scenic-view for debuggin style issues
