### ISSUE TITLE
new entry from plaintext not working

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8399]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.5--2022-01-02--55ceed9 Linux 5.15.12-200.fc35.x86_64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

generate new entry from plain text

 ```
Evelyn Ruppert
Doing words with things of the Internet
467 – 479
```

nothing gets parsed. sadly.

**Comment by Siedlerchr** [comment]
Works as expected for me: 
I get the following entry back:

```
@Misc{,
  title = {Evelyn Ruppert Doing words with things of the Internet},
  pages = {467--479},
}
```

PS that entry has a DOI: https://doi.org/10.5771/9783845295008-467

**Comment by ilippert** [comment]
Wow, does not work for me with
JabRef 5.5--2022-01-02--55ceed9
Linux 5.15.12-200.fc35.x86_64 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

**Comment by Siedlerchr** [comment]
Can you check the log if you get a connection error?  I am today in a different place, can't test it here because port 8070 is blocked in the firewall.  (See preferences -> Import Export -> Remote services)

**Comment by ilippert** [comment]
I can ping the server, and `wget http://grobid.jabref.org:8070` gets me an html page.
Hmm, right now it works as it should do...
