### ISSUE TITLE
Support more complicated search expressions

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#840]
It would be nice to search for
- recently published articles: year > 2000
- highly ranked: ranked > 3

Related request for groups: https://sourceforge.net/p/jabref/feature-requests/232/

**Comment by Le-wi** [comment]
Hi, I like to clean up old issues, is this still a thing? @tobiasdiez

**Comment by tobiasdiez** [comment]
This feature has not been implemented yet and is still relevant. I think, it is best to combine it with https://github.com/JabRef/jabref/issues/1975, ie use lucene query parser. This might turn out to be a bit more work, but if you have the time go for it!

**Comment by Le-wi** [comment]
Ever since you wrote it takes more time ... I can't force myself to do it :D

I'm afraid it implies architectural changes and a ton of tests etc. And I don't want to leave a half finished mess. So now I wonder:
Can you (a) break it down for me or (b) point at something smaller but still helpful :)

**Comment by tobiasdiez** [comment]
Yes, it's quite a big project but as you appeared motivated I didn't want to stop you in your tracks. If you already started working, you may create a WIP PR and maybe somebody takes over.

A good starting point are the [issues tagged with "good first issue"](https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). If you don't find something in this list that triggers your interest, just let us know what kind of things you are looking for (ui vs backend?) and we may be able to suggest something fitting. Our chat https://gitter.im/JabRef/jabref is probably better suited for this.
