### ISSUE TITLE
% Encoding Comment wrongly dropped

### ISSUE THREAD

**Issue by universal** [JabRef/jabref#8417]
### JabRef version

5.4 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Pop!_OS 21.10 (Ubuntu)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Save the following file with encoding windows-1252:
```bibtex
% Encoding: windows-1252

@MISC{anderson04a,
  author = {Robert Anderson},
  title = {Quality of Life in Rural {Europe}},
  howpublished = {Paper presented at the Irish Presidency Conference `Improving Living
  Conditions and Quality of Life in Rural {Europe}', Westport},
  month = {May 30 -- June 1},
  year = {2004},
  file = {anderson04a.pdf:anderson04a.pdf:PDF},
  institution = {{European Foundation for the Improvement of Living and Working Conditions
  (OECD)}},
  timestamp = {2009.10.09}
}

@Comment{jabref-meta: databaseType:bibtex;}
```
2. Open file in Jabref, Verify Library Properties say: Encoding windows-1252
3. Hit Save
4. The library has been modified by another program. pops up, dismissing changes does not help. File is saved without the encoding comment though and it does not get restored. Library now says UTF-8 in properties.
5. Autosave of local libraries is off.
6. ```encguess trial.bib``` says US-ASCII (saved with sublime text and vs code)

**Comment by Siedlerchr** [comment]
@koppor encoding

**Comment by Siedlerchr** [comment]
JabRef tries to write and store all data in utf8
The encoding comment was removed in 5.4
>In case the database is encoded with UTF8, the % Encoding marker is not written anymore

**Comment by koppor** [comment]
It should keep the encoding field.
