### ISSUE TITLE
Build failed with an exception - jcenter.bintray.com - Bad Gateway

### ISSUE THREAD

**Issue by MartinX3** [JabRef/jabref#8418]
### JabRef version

5.4 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Arch Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Compile it https://aur.archlinux.org/packages/jabref

### Appendix

...
<details>

<summary>Log File</summary>

```
* What went wrong:
A problem occurred configuring root project 'JabRef'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.javamodularity:moduleplugin:1.8.10.
     Required by:
         project : > org.javamodularity.moduleplugin:org.javamodularity.moduleplugin.gradle.plugin:1.8.10
      > Could not resolve org.javamodularity:moduleplugin:1.8.10.
         > Could not get resource 'https://plugins.gradle.org/m2/org/javamodularity/moduleplugin/1.8.10/moduleplugin-1.8.10.module'.
            > Could not GET 'https://jcenter.bintray.com/org/javamodularity/moduleplugin/1.8.10/moduleplugin-1.8.10.module'. Received status code 502 from server: Bad Gateway
   > Could not resolve org.openjfx:javafx-plugin:0.0.10.
     Required by:
         project : > org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin:0.0.10
      > Skipped due to earlier error
   > Could not resolve org.beryx:badass-jlink-plugin:2.24.4.
     Required by:
         project : > org.beryx.jlink:org.beryx.jlink.gradle.plugin:2.24.4
      > Skipped due to earlier error
   > Could not resolve com.adarshr:gradle-test-logger-plugin:3.1.0.
     Required by:
         project : > com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin:3.1.0
      > Skipped due to earlier error
   > Could not resolve org.openjdk.jmh:jmh-core:1.27.
     Required by:
         project : > me.champeau.gradle.jmh:me.champeau.gradle.jmh.gradle.plugin:0.5.3 > me.champeau.gradle:jmh-gradle-plugin:0.5.3
      > Skipped due to earlier error
```

</details>

**Comment by MartinX3** [comment]
Ah, you mean the gradle plug-in hosting site redirects me to jcenter?
I hope they remove it, since jcenter will be closed this year.

**Comment by Siedlerchr** [comment]
If the plugin is not found in the cache, it will be downloaded.
I looked a bit around but we don't have any reference left to bintray in our Gradle file and the plugin seems also to be available via maven central so I wonder why it resolves to bintray....

Bintray will be kept online but only in read only mode.
