### ISSUE TITLE
Jabref 5.4 and 5.5 does not open on Ubuntu 20.04

### ISSUE THREAD

**Issue by aretaon** [JabRef/jabref#8419]
### JabRef version

5.4 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 20.04 with kernel 5.11.0-44-generic

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Install Jabref from https://builds.jabref.org/main/ 

`sudo apt install ./jabref_5.5-1_amd64.deb`

2. Opening using the GNOME dash does not work
3. Call the programme directly (see below)

```
/opt/jabref/bin/JabRef
Jan 12, 2022 6:09:51 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2022-01-12 18:09:52 [JavaFX Application Thread] org.jabref.logic.net.URLDownload.bypassSSLVerification()
WARN: Fix SSL exceptions by accepting ALL certificates
2022-01-12 18:09:52 [JavaFX Application Thread] org.jabref.gui.JabRefMain.handleMultipleAppInstances()
INFO: Arguments passed on to running JabRef instance. Shutting down.
```

```
java -version
openjdk version "13.0.7" 2021-04-20
OpenJDK Runtime Environment (build 13.0.7+5-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 13.0.7+5-Ubuntu-0ubuntu120.04, mixed mode)
```

Possible duplicate of #7969 in which @xoquon suggested the 5.4 deb fixing the error which it does not for me.

**Comment by Siedlerchr** [comment]
Hi,

there seems to be still some JabRef/java process running (from the log it seems) in the background. You might need to kill that before.

**Comment by aretaon** [comment]
:facepalm: Yep that was it, a no-gui process running in the background.
Thanks for your swift response and the great work overall!
