### ISSUE TITLE
Error while generating citation style

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#8421]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.5--2022-01-10--9e3506f Linux 5.13.0-25-generic amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Options/preferences/entry preview
2. Scroll through the Available column
3. Some entries throw up this error:

![image](https://user-images.githubusercontent.com/762246/149241322-2b82be66-b22a-40dc-9a91-f3bcfefc9f5a.png)

Problem entries include:
* AIB Studi (Italiano)
* Agora
* Ancilli Iuris
* Art History
* Australian Historical Studies
* Bluebook Inline
* Bluebook Law Review
* Bluebook Law Review (2)
* Byzantine and Modern Greek Studies
* Catholic Biblical Association (full note)
* Common Market Law Review
* Comparativ
* Comparative Politics
* Developing World Bioethics
* ... at which point I lost the will to live.  :-) 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
uff. Also present in 5.4 Stable:

JabRef 5.4--2021-12-20--ab44182
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

**Comment by Siedlerchr** [comment]
Yes I can reproduce this. This seems to be specific to some styles. 
If you open the Event log you will see details, I encountered some NPEs from citeproc.
