### ISSUE TITLE
Can't change the theme back to normal even after uninstall

### ISSUE THREAD

**Issue by digdig** [JabRef/jabref#8427]
### JabRef version

5.4 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I open the preference > appearance and change the theme and then save, the error occurs. Even if I uninstall and reinstall the programs, the error persists.

![image](https://user-images.githubusercontent.com/5459093/149493047-528c96ab-7634-480a-8013-8abf60026549.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
This seems like it's related to https://github.com/JabRef/jabref/issues/8385

**Comment by Siedlerchr** [comment]
As a temporary fix, can you make sure that you have a valid main file directory set in Preferences -> LInked File?

**Comment by Siedlerchr** [comment]
Should also be solved ow in the latest dev version
