### ISSUE TITLE
macOS icon is inconsistent with other application icons

### ISSUE THREAD

**Issue by js51** [JabRef/jabref#8443]
**Is your suggestion for improvement related to a problem? Please describe.**

The current icon is inconsistent with Apple's [human interface guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) and with the vast majority of other applications developed for macOS. This means that JabRef looks quite strange on the dock, sitting next to other icons which conform to the guidelines:

![Screen Shot 2022-01-18 at 9 59 55 am](https://user-images.githubusercontent.com/27327007/149845669-b43b0772-46bb-42c1-b608-39dafe176ba8.png)

You can also see that the icon brightness can be a problem, depending on the user's desktop wallpaper. The image above uses the current default wallpaper. This is related to issue #7771 and PR #7825.

**Describe the solution you'd like**
I'd like a new app icon to be used specifically for the macOS version of JabRef. I've included two quick proposals below but I think that anything that meets the guidelines linked above would be a big improvement. 

The colours will of course depend on the outcome of #7825.

![Screen Shot 2022-01-18 at 10 17 21 am](https://user-images.githubusercontent.com/27327007/149846703-2dbbd1a2-7a5e-4790-aa9c-ee3048230f2e.png)

![Screen Shot 2022-01-18 at 10 07 50 am](https://user-images.githubusercontent.com/27327007/149846148-7498672d-a57f-422e-b7b8-c5dc4a47f327.png)

**Additional context**

**Comment by Siedlerchr** [comment]
Thanks a lot for your suggestion! I like the coloring idea. You haven't yet found time to decide on a new color scheme,  so any suggestions are welcome.

**Comment by u7283157** [comment]
Hi, my team and I are planning to work on this issue and have it done by the end of October. Could we please be assigned this issue?

**Comment by Siedlerchr** [comment]
@u7283157  We are looking foward to your work. Please also have a look at the discussions here:
https://github.com/JabRef/jabref/pull/7825  
The idea was to have multiple color icon like VSCode.
It would be cool to have screenshots how it would look like

**Comment by u7283157** [comment]
Hi, please find below some macOS icons I have designed. Please let me know what you think so far.

![jabref_Icon_proposal](https://user-images.githubusercontent.com/110871660/198234867-d7564d3f-791b-4118-9d99-58b9e66d1f20.png)

**Comment by renzoseverino** [comment]
Hi! I was trying to change my JabRef MacOS icon today and stumbled on this. Are there any updates, please? The work so far looks great (specially the first row of the proposed icons). Thanks!!

**Comment by Siedlerchr** [comment]
@u7283157  It's been some time now, but would you mind sharing the original icons svg or something like this  for the first row you created?

**Comment by Siedlerchr** [comment]
I played around with icon kitchen: 
https://icon.kitchen/i/H4sIAAAAAAAAAx1NWw6DMAy7S%2FbLCfjlCvxN0xSatKuWEtTHJoS4Oyn5cGTHsQ%2F4oTQuMB5AmL%2FzhxPD6FEKD%2BDDJHHDXPu5sC0g9tikwgDR6WoCEr1FHdZo9Ow%2F875ZBMSEgc23hElFsykPf093JaUmvfYJuFLWSD1Ri%2BGfF8OEztjrvAD4oKT7oQAAAA%3D%3D
