### ISSUE TITLE
Unlinked File Importer: Does not import all importable files

### ISSUE THREAD

**Issue by falschgeldkind** [JabRef/jabref#8444]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new library
2. Lookup -> Search for unlinked local files
3. Select a directory with a lot of pdf documents (maybe at least 100 pdf)
![before_1stsearching](https://user-images.githubusercontent.com/74116031/149981856-e5586c55-6fa2-46f9-8569-13ce143503c4.png)
4. click on search
![after_searching](https://user-images.githubusercontent.com/74116031/149981885-e6fc39f1-ae51-4322-9882-32a24fcaa6c7.png)
5. select all, click on import
![ImportHandler_breakpoint_line_72](https://user-images.githubusercontent.com/74116031/149981932-de66f0b9-945a-4277-8219-c1f6506a2649.png)
6. wait, after that all documents should have been imported
![ImportHandler_breakpoint_line_137](https://user-images.githubusercontent.com/74116031/149981963-934e78de-a722-423c-9701-a4a7a79583ca.png)
![Import_Results](https://user-images.githubusercontent.com/74116031/149981996-3290c58e-9b6d-4ed6-8d07-07cff5e8cc48.png)
7. be surprised that not all documents were imported
-> check that by clicking on search again
![after_2ndsearching](https://user-images.githubusercontent.com/74116031/149982015-89df6904-dd07-4f5f-84a6-3844c8984ec6.png)
 

### Appendix

Not sure what to write here

if you need any more information just get back to me

**Comment by falschgeldkind** [comment]
please note that all entries in the Import results were shown as succesfull

**Comment by ThiloteE** [comment]
Related issue in the forum: https://discourse.jabref.org/t/unlinked-file-importer-does-not-import-all-importable-files/3150

**Comment by Siedlerchr** [comment]
Thanks again for the detailed analysis! I really wonder where the difference comes from. MIght be something in the actual importing step.

**Comment by suppenkaspar109** [comment]
Can confirm this bug. What is also kind of strange, that same entries are added multiple time if you run the import process multiple times.

**Comment by falschgeldkind** [comment]
Thats awesome! Is it foreseeable if the fix will be included in the next Jabref version?

**Comment by Siedlerchr** [comment]
@falschgeldkind A fix has jut been merged

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by falschgeldkind** [comment]
Yes I will try that when I'm back at work on friday

That's not a problem the library is empty anyways (thats why I want to import in bulk).
