### ISSUE TITLE
Menu: Rename "Groups interface" into "Groups"

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8447]
Here is the View menu:
![ksnip_20220119-101236](https://user-images.githubusercontent.com/6931104/150100034-23b87551-9370-4d08-adb6-8aaa49d3c1ef.png)

**Is your suggestion for improvement related to a problem? Please describe.**
The Web search interface is named `Web search`.
The OpenOffice/LibreOffice interface is named `OpenOffice/LibreOffice`.

Why to name the Groups interface `Groups interface`?

**Describe the solution you'd like**
Naming it `Groups` should be enough.

**Comment by Siedlerchr** [comment]
https://github.com/JabRef/jabref/blob/b1338b168eeb73f7fa4fbc5967dac8783f2cf821/src/main/java/org/jabref/gui/actions/StandardActions.java#L85 
This line and in the l10n-en needs to be changed
