### ISSUE TITLE
URL field replaces '+' character with ' ' (white space) breaking URL

### ISSUE THREAD

**Issue by serialc** [JabRef/jabref#8448]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubunut 21.10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. For an entry go to the General tab.
2. Test this [URL](https://www.chicago.gov/content/dam/city/depts/cdot/Red%20Light%20Cameras/2022/Sutton+Tilahun_Chicago-Camera-Ticket_Exec%20Summary-Final-Jan10.pdf) to see where it should go
3. Enter the above URL into the URL field (in the General tab).
4. Click the (chain icon) link icon for the entry in the reference list.
5. Goes to a 'not found' page.

**You can see the reason - as soon as you enter/paste the URL into the URL field the '+' in the URL is replaced with a white space.**

Full version info:
JabRef 5.5--2022-01-17--27a05c7
Linux 5.13.0-25-generic amd64 
Java 16.0.2 
JavaFX 17.0.1+1

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Does not resolve the bug, but workaround so far: add the url in the library file via a text editor or in the `{} Bibtex Source` Tab.

e.g.:

```
@Article{test,
  title = {test},
  url   = {https://www.chicago.gov/content/dam/city/depts/cdot/Red%20Light%20Cameras/2022/Sutton+Tilahun_Chicago-Camera-Ticket_Exec%20Summary-Final-Jan10.pdf},
}
```

Clicking the (chain icon) link icon for the entry in the reference list correctly leads to the website, so it seems to be in the part of the code that writes to the url field. The above suggests it is not in the code that reads from the url field.

**Comment by alexandre-cremieux** [comment]
Hi!

I have a proposal for this issue. @Siedlerchr could you please take a look?

#https://github.com/alexandre-cremieux/jabref/commit/44233003bccc9693d68d934d88792e32fe48e95b)

**Comment by Siedlerchr** [comment]
@alexandre-cremieux  Cool! Pleas open a PR so we can see review your changes

**Comment by alexandre-cremieux** [comment]
As this is my first PR on JabRef, it has beed opened has a draft. Please tell me is anything is wrong in the process ;)
