### ISSUE TITLE
DOI copied from pdf file within firefox not detected via 'Import new entry via ID' dialogue

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8453]
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.5--2022-01-17--27a05c7 Windows 10 10.0 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open https://doi.org/10.1177/0963662518801170
2. Open the pdf file in firefox browser
3. Copy the DOI from the pdf
4. Try to import bibliographic data with Jabref

Result: Biliographic data was not found

Workaround:
- Copy the DOI from the webpage

   OR
- Download the pdf to your system, open it via Foxitreader or another pdf viewer and then copy the DOI.

     Both these two approaches will make Jabref finding the entry and importing data by using the "import new entry from ID" dialogue.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
I guess this is an issue in the Firefox pdf js implementation which probably copied some invisible or other characters. Try to paste the Doi in another text editor

**Comment by ThiloteE** [comment]
Meh, turns out one has to copy the empty space next to the DOI as well (left side). One character will be amiss, if not.

Issue is solved.
