### ISSUE TITLE
Wiki: replace link

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8464]
### JabRef version

Other (please describe below)

### Operating system

Other (please describe below)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

This is about the wiki of JabRef.
I could not edit it myself, and did not find a better place to report that, on page https://github.com/JabRef/jabref/wiki, on the line
`Information about BibTeX: https://docs.jabref.org/fields`
the link is dead.
It should be replaced by https://docs.jabref.org/advanced/fields

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Thanks, I fixed it!
