### ISSUE TITLE
Scrollbar shows up needlessly in group panel, while decreasing the width.

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8467]
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.6--2022-01-25--2c92eb0 Windows 10 10.0 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Expand the width of the group panel.
2. Then decrease the width of the groups panel.

Result:

at certain widths, while decreasing the width, the row will show up.

Examples:

- Dark Mode:
   ![image](https://user-images.githubusercontent.com/73715071/151216185-07af80e9-d935-44a1-a526-1ef56189c733.png)
- Light Mode:
   ![image](https://user-images.githubusercontent.com/73715071/151216689-2e402de4-3f83-4a2b-884d-2ab6931d01ca.png)

**Comment by ThiloteE** [comment]
Desired behaviour: This special row should show in the same colour as the rest of the background.

**Comment by ThiloteE** [comment]
Ohh, it seems to be the scrollbar!

**Comment by Siedlerchr** [comment]
Yep, it's the scrollbar. Might be a javafx thing.. Not sure if this changable.

**Comment by ThiloteE** [comment]
I will leave it open for the sake of acknowledging that it exists, but this issue is definitely low priority. More important issues around.

**Comment by LIM0000** [comment]
Hi,
I'm interested in working on this issue as my first code contribution to open-source. Can I give it a shot?

**Comment by ThiloteE** [comment]
This issue possibly already MIGHT have been solved in JFX 18.
See the [release notes](https://gluonhq.com/products/javafx/openjfx-18-release-notes/). There have been multiple fixes to scroll-bars. Following pull request will introduce JFX to JabRef: #8629

In case JFX 18 has NOT fixed this, work probably needs to be done [here](https://github.com/openjdk/jfx), instead of at JabRef. Going through the [issue list](https://bugs.openjdk.java.net/browse/JDK-8283551?filter=39543) first is advised.

**Comment by ThiloteE** [comment]
@LIM0000 this issue has low priority and it could be that it will be solved with jfx 18. Please check out issues with the label "good first issue". See here: https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22.

**Comment by LIM0000** [comment]
@ThiloteE Thank you for your quick response.

I have checked both the JFX [issue lists](https://bugs.openjdk.java.net/browse/JDK-8283551?filter=39543) and [JFX 18 release notes](https://gluonhq.com/products/javafx/openjfx-18-release-notes/), none of the notes have mentioned the ability to disable scroll bar in TreeTableView that is used to display columns of group panel for Jabref.

I have done some researches and found that TreeTableView has its own built-in scrollpane that causes this issue. By looking into Jabref codebase, this issue could be fixed by adding a style to TreeTableView horizontal scrollbar.

```
.tree-table-view .scroll-bar:horizontal {
    -fx-opacity: 0;
}
``` 

Hope this is helpful.

**Comment by ThiloteE** [comment]
Well, since you already have done so much research and might have a possible fix, sure go ahead :) Open a pull-request and we will be able to see how it behaves.

As a general advice for newcomers: check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is a good start. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.
