### ISSUE TITLE
doi resolver has a problem

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8475]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-01-24--83c6840 Linux 5.15.14-200.fc35.x86_64 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Import entry based on doi 10.18910/75520

https://www.doi.org/ actually leads me to the correct entry. But JabRef says the entry cannot be found.

**Comment by Siedlerchr** [comment]
Hi,
this is a problem with the specific DOI or the owner of the DOI. It does not return metadata in bibtex format.
JabRef performs the following request:
```
curl --location --request GET 'https://dx.doi.org/10.18910/75520' \
--header 'Accept: application/x-bibtex'
```
