### ISSUE TITLE
Better attachments management

### ISSUE THREAD

**Issue by smihael** [JabRef/jabref#8483]
Whenever a new file attachment is added to a bib item (e.g. PDF of an article), it is usually stored in the same folder as the .bib file itself. While this is fine for small libraries, it quickly becomes messy. It would be nice to have an option to keep files in a separate directory, while they would be also linked into sub-directories for different item groups (if item has one).  This would also imply that whenever group is renamed, the corresponding directory hierarchy would need to be updated. A bonus would be that the item gets assigned to another group, whenever the file is moved in the filesystem (this could be based on a version control).

**Comment by Siedlerchr** [comment]
Thanks for your ideas, however, I think your requirements are already satisfied b JabRef is fairly flexible with linked files and similar to the filename you can specify a file directory pattern (group name is also possible)
See the section in our docs
https://docs.jabref.org/finding-sorting-and-cleaning-entries/filelinks

And for using the groups field:
https://discourse.jabref.org/t/the-function-of-copy-linked-files-to-folder/1957/4

**Comment by ThiloteE** [comment]
@smihael did it work out for you? If yes, we could close this issue, right?

**Comment by smihael** [comment]
According to the documentation entries linked above, most of the functionality I suggested in the original post is present. 
Filelinks combined with other things in Quality menu in JabRefare are indeed quite flexible. Scheduling auto-linking and watching for directory/group renames probably fall into the category of "requests for completely new features", so probably better place to formulate them is at [discourse](https://discourse.jabref.org/). 

I also realize that the real issue in my case is actually more about metadata extraction from PDFs than attachment management itself. When trying to connect an existing library of PDFs (with very irregular filenames, but nice directory hierarchy) to bibtex entries, patterns which are based on filenames can't work well.
