### ISSUE TITLE
Add new entry via arXiv id

### ISSUE THREAD

**Issue by iTao8** [JabRef/jabref#8493]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

JabRef 5.6--2022-02-09--de114d5 Mac OS X 11.6.4 x86_64  Java 17.0.2  JavaFX 17.0.2-ea+3

### Checked with the latest development build

- [x] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. double click an entry so that the edit entry window open, put the cursor in the author box
2. add a new entry and choose the id type "arXiv"
3. paste an arXiv id
4. the arXiv id is added to the author, no finding operation is done.
![Screen Shot 2022-02-09 at 5 54 25 PM](https://user-images.githubusercontent.com/28705547/153172591-28af9f36-6e46-40d2-ae46-a0e7adceb1e7.jpg)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
May have been some temporary issue, I cannot reproduce this.
