### ISSUE TITLE
Check SourceSpy

### ISSUE THREAD

**Issue by ivanuclm** [JabRef/jabref#8497]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 21.04

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Click the Sourcespy hyperlink in JabRef documentation or go to https://sourcespy.com/github/jabref/

### Appendix

SourceSpy is down and I really need it right now

**Comment by Siedlerchr** [comment]
SourceSpy is an external service not operated by JabRef.  It was integrated by @alexkarezin Maybe he has some information about it
