### ISSUE TITLE
Remove private fields (and other field flags)

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#850]
Private fields (fields marked with `net.sf.jabref.gui.InternalBibtexFields.BibtexSingleField.PRIVATE`), seem to be fields introduced by JabRef itself. For instance, `owner` and `timestamp`. There are also fields such as `entrytype`, which seem to be deprecated or can be removed.

Proposal: Introduce "JabRef fields" (owner, timestamp, maybe special fields (refs https://github.com/koppor/jabref/issues/84), ...) and move the other fields (type, bibtexkey, ...) as properties of `BibEntry`

We have to get rid of the private flag and make use of the displayable and writable flag only. These flags are required for the current implementation of special fields.

Alternatively, we can get rid of displayable and writable and use private for fields neither displayable nor writable (only required for special fields when stored in keywords; when written as separate fields, they are non-private and handled normally).

Even better, not misusing bibtex fields at all. Regarding the current implementation of special fields, it might be impossible to do so without changing the special fields implementation. See https://github.com/koppor/jabref/issues/84.

Refs #574

**Comment by stefan-kolb** [comment]
@JabRef/developers Are these fields removed? I cannot find anything anymore, when searching the code.

**Comment by Siedlerchr** [comment]
You are right. This has been changed. We have clear enums for InternalField., SpecialField and normal Bibtex/Biblatex fields.
