### ISSUE TITLE
Grouping using custom fields sometimes 

### ISSUE THREAD

**Issue by shivaway** [JabRef/jabref#8524]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I create a group using the Collect by Searching for Keyword using the field Entrytype and the keyword report.
2. The group contains 1 record that contains the word report in the Title field.
3. It should have 2 records with the Entrytype Report.
[test.zip](https://github.com/JabRef/jabref/files/8124856/test.zip)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
No problem with Jabref, just wrong syntax in your configuration. Puh 😄

Here, your bib file in a way that works:
[test.zip](https://github.com/JabRef/jabref/files/8125070/test.zip)

**Detailed solution:**

1. Remove   the brackets `[` and `]` from `[entrytype]      = {Report},`.
   It triggers the following error: 
![image](https://user-images.githubusercontent.com/73715071/155339078-e6dd3d98-df2b-479d-9bcb-9ba62d22a222.png)
You did it for this entry:
   ```
   @Calibration{Calibration2021,
     citationkey      = {Calibration2021},
     entrytype        = {report},
     title            = {Calibration Reports},
     year             = {2021},
     [entrytype]      = {Report},
     creationdate     = {2022-02-23T07:10:05},
     modificationdate = {2022-02-23T07:52:41},
   }
   ```
   
2. `entrytype = {report},` was missing for two of the entries
3. the syntax for `collect by searching for keyword` was wrong. Remove the brackets here also. This one works:
   ![image](https://user-images.githubusercontent.com/73715071/155339878-8d1a366b-e24a-4baa-8243-6e6fa106b87e.png)
