### ISSUE TITLE
Add www.biodiversitylibrary.org to the websearch options

### ISSUE THREAD

**Issue by RJDan** [JabRef/jabref#8539]
Older literature is not easily recovered by the available databases (particularly books).

**Describe the solution you'd like**
Have https://www.biodiversitylibrary.org/bibliography added to the available databases to aid in searching for (in this case, biology) material.

**Comment by Ankush142930** [comment]
Hey, I am Ankush. I am a newbie programmer, but I really want to contribute to this project(Open-source in general). Could you please guide me to resolve this issue? 
I only know java, dsa and currently learning web development.

**Comment by Siedlerchr** [comment]
Welcome to JabRef! Check out our Contribution Guide https://devdocs.jabref.org/contributing 
As a starting point, look at the Fetchers in org/jabref/logic/importer/fetcher

**Comment by Ankush142930** [comment]
Okay, thanks a lot @Siedlerchr. I will do the aforesaid.

**Comment by Azhen917** [comment]
Hello, I am also new to open source contributions. Is there any articles or guides that I can read to understand how to implement this?

**Comment by Siedlerchr** [comment]
See my comment above. In general, try to look into existing fetchers to understand how it's working in general. @etienne428  maybe can also add some hints on where to start (He's also currently working on fetchers)

**Comment by etienne428** [comment]
Hey!
As a small guide introduction: to add a web search Fetcher, you have to add it into the org.jabref.logic.importer.WebFetchers#getSearchBasedFetchers method. You need to implement a new class in the org.jabref.logic.importer.fetcher folder which has to implement SearchBasedFetcher, an interface. You have 4 possibilities: SearchBasedFetcher, SearchBasedParserFetcher, PagedSearchBasedFetcher and PagedSearchBasedParserFetcher. SearchBasedFetcher is the basic one, the other implement it. I think the one you need is SearchBasedParserFetcher, but you have to see exactly what the API gives you.
Ask here if you have some further questions.

**Comment by Azhen917** [comment]
@etienne428 Hello! Thanks for the guidance! I've been reading the implementation of the other fetchers and I've managed to come up with this so far:

`public class BiodiversityLibrary implements SearchBasedParserFetcher {

    private final ImportFormatPreferences preferences;

    public BiodiversityLibrary(ImportFormatPreferences preferences) {
        this.preferences = Objects.requireNonNull(preferences);
    }

    @Override
    public String getName() {
        return "BiodiversityHeritage";
    }

    @Override
    public URL getURLForQuery(QueryNode luceneQuery) throws URISyntaxException, MalformedURLException, FetcherException {
        URIBuilder uriBuilder = new URIBuilder("https://www.biodiversitylibrary.org/search");
        uriBuilder.addParameter("stype", "F");
        uriBuilder.addParameter("searchTerm", new DefaultQueryTransformer().transformLuceneQuery(luceneQuery).orElse(""));
        return uriBuilder.build().toURL();
    }

    @Override
    public Parser getParser() {
        return inputStream -> {
            String response = new BufferedReader(new InputStreamReader(inputStream)).lines().collect(Collectors.joining(OS.NEWLINE));
            JSONObject jsonObject = new JSONObject(response);

            JSONArray results = jsonObject.getJSONArray("key word");
            List<BibEntry> entries = new ArrayList<>();
            for (int i = 0; i < results.length(); i++) {
                // do stuff
            }
            return entries;
        };
    }
}`

I am currently lost as to what to do with the getParser method. Any further help is much appreciated!

**Comment by Azhen917** [comment]
Thanks for the tips, I've pushed the changes to my repo as instructed. Please let me know if I did anything improperly.

**Comment by DanielPortods** [comment]
Hi! I'm trying to contribute in that issue and i have a question. That API need a key to validate the request. Have some indication of how to work with that kind of variable or i can just define a static variable inside of the class? 
That key is get with an email so i'm thinking if it's not a env variable situation...

**Comment by Jonathan-Oliveira** [comment]
> Hi! I'm trying to contribute in that issue and i have a question. That API need a key to validate the request. Have some indication of how to work with that kind of variable or i can just define a static variable inside of the class? That key is get with an email so i'm thinking if it's not a env variable situation...

Hi! I'm also trying to contribute. Checking the other implementations I found that there is a file that has the api keys. Look the file [BuildInfo](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/logic/util/BuildInfo.java)

**Comment by Siedlerchr** [comment]
Yes, the BuildInfo is correct. You can use that for testing.  During the Build we replace some of the APi keys there with keys from environment variables.

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already implemented in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main.
