### ISSUE TITLE
@STRING abbreviations are saved as normal text between {}

### ISSUE THREAD

**Issue by posenato** [JabRef/jabref#8554]
### JabRef version

5.5 (latest release)

### Operating system

macOS

### Details on version and operating system

macOS Catalina 10.15.7

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a bib file containing a `@string` abbreviation.
Example: `@String{lipics   = {LIPIcs}}`
2. Create an entry containing the created abbreviations.
Example:
In the Series field, insert the abbreviations as `#lipics#`
<img width="444" alt="Screenshot 2022-03-10 at 11 08 06" src="https://user-images.githubusercontent.com/7280315/157639496-8f5801f3-6ab5-4d55-93b8-d424bd686c58.png">

4. Save the file
5. The expected result should be:
```
@String{lipics = {LIPIcs}}

@InProceedings{test,
  author  = {Author Test},
  title   = {Test},
  year    = {2022},
  series  = lipics,
  journal = {Journal of Test},
}
@Comment{jabref-meta: databaseType:bibtex;}
```
6. The saved file is instead
```
@String{lipics = {LIPIcs}}

@InProceedings{test,
  author  = {Author Test},
  title   = {Test},
  year    = {2022},
  series  = {#lipics#},
  journal = {Journal of Test},
}
@Comment{jabref-meta: databaseType:bibtex;}
```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
HI,

the logic for BibTeX string resolving has been inverted. [jabref/CHANGELOG.md at main · JabRef/jabref · GitHub 1](https://github.com/JabRef/jabref/blob/main/CHANGELOG.md#changed-1)

By default JabRef resolves BIbTeX strings only for the fields defined in the preferences. However, you can add the field address to the list of existing fields in the preferences. e,g, address;
Fields are separated by a semicolon
https://discourse.jabref.org/t/bug-about-jabref-bibtex-string-resolving-for-osx/3179/2?u=siedlerchr

**Comment by posenato** [comment]
Thank you, @Siedlerchr!
Before writing the issue, I checked the doc at https://docs.jabref.org/advanced/strings, and I didn't find any instruction about the field limitation for BibTeX string resolving.
