### ISSUE TITLE
Opening a library: name lost + (unknow) changes

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8555]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-03-09--75df9a3 Linux 4.19.0-19-amd64 amd64  Java 17.0.2  JavaFX 17.0.2-ea+3

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a library

- the name of the library is displayed for half a second in the tab, and then altered to "untitled".
- the library is indicated as having been modified (a star in the tab title: "untitled*").

And if several libraries are opened, all the tabs are named "untitled*".

This behavior was not present in JabRef 5.6--2022-03-08--3383f9b
Linux 4.19.0-19-amd64 amd64 
Java 17.0.2 
JavaFX 17.0.2-ea+3

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ilippert** [comment]
confirmed
JabRef 5.6--2022-03-09--75df9a3
Linux 5.16.12-200.fc35.x86_64 amd64 
Java 17.0.2 
JavaFX 17.0.2-ea+3

**Comment by Siedlerchr** [comment]
Yes, I experienced this as well. I was already looking into it. it seemeed to be a timing/threading problem

**Comment by Siedlerchr** [comment]
@mlep  @ilippert  Any idea you remember when it was working correct last time?

**Comment by mlep** [comment]
It is working in  JabRef 5.6--2022-03-08--3383f9b

**Comment by mlep** [comment]
Back to normal: the bug is gone.

JabRef 5.6--2022-03-10--749b6b2
Linux 4.19.0-19-amd64 amd64 
Java 17.0.2 
JavaFX 17.0.2-ea+3

@Siedlerchr Thank you for your prompt action.

**Comment by Siedlerchr** [comment]
The glory goes to @k3KAW8Pnf7mkmdSMPHz27
