### ISSUE TITLE
Changelog link leads to a 404

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#8563]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-03-11--89d1047 Linux 5.13.0-35-generic amd64  Java 17.0.2  JavaFX 17.0.2-ea+3

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select help / JabRef resources / view change log
2. Taken to `https://github.com/JabRef/jabref/blob/master/CHANGELOG.md`
3. 404 message.
4. Should be `https://github.com/JabRef/jabref/blob/main/CHANGELOG.md` (main, not master)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by NYH-Dolphin** [comment]
Hi, I am a junior student who is learning software engineering, I have successfully build the environment in JabRef and I am wondering whether I can try to solve this problem~

**Comment by NYH-Dolphin** [comment]
Plus, I find the same problem when the operating system is Windows10

**Comment by NYH-Dolphin** [comment]
Dear JabRef:
      Well, I have located this bug position and create a branch called **fix-for-issue-8563** in my own folk repo.
      Plus, I would like to proposed a new revise suggestion. In your version Tags I found several version as the following shortcut
![image](https://user-images.githubusercontent.com/60838786/158103926-322f6c2d-057d-4e05-ac43-e872d73e8242.png)
      As you see v4.0 has 4 subversions, **v4.0/v4.0-beta/v4.0-beta2/v4.0-beta3**, which means if I used JabRef to check the latest version, it should driected me into the [version]-[subversion] Tag according to the Version type you specificed
     However, I write the following testcase but it fails
![image](https://user-images.githubusercontent.com/60838786/158104335-816c64d1-b799-42fa-9d6d-c0246d67df2d.png)
    In your class **main/org/jabref/logic/util/Version.java**, there must be some revise point, could you let me further revise it in order to fit to perse certain version into correct website link?

**Comment by Siedlerchr** [comment]
I would propose to debug through the failing Tests and set a breakpoint in Version.parse method

**Comment by NYH-Dolphin** [comment]
> I would propose to debug through the failing Tests and set a breakpoint in Version.parse method

I will do that~ What I mean is that this may be a defect and I am wondering whether I can try to fix it on issue #8563 and then make a pull request?

**Comment by Siedlerchr** [comment]
Yes sure, as long it's related to the issue it's fine!

**Comment by Siedlerchr** [comment]
Yes sure, as long it's related to the issue it's fine!

**Comment by NYH-Dolphin** [comment]
hey JabRef~
      I almost finish to fix this issue. However, when I try to push it to my branch, the gradlew check is fail and tells me the above message
![image](https://user-images.githubusercontent.com/60838786/158714006-673f96a3-ffed-4d64-970b-796ecf64f28a.png)
    May I need to update my local JRE version?
