### ISSUE TITLE
Add Directory of Open Access Books (DOAB) fetcher to web search

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8576]
https://doabooks.org/

DOAB is a community-driven discovery service that indexes and provides access to scholarly, peer-reviewed open access books (currently ~ 50 000) and helps users to find trusted open access book publishers. All DOAB services are free of charge and all data is freely available.

Where to start, if trying to implement this: https://www.doabooks.org/en/resources/metadata-harvesting-and-content-dissemination

**Comment by ThiloteE** [comment]
@etienne428 @Azhen917 If you feel like adding yet another one after you are done with the ones you are working on right now 🙃

**Comment by Mohamadi98** [comment]
I can take a look at this, if you don't mind

**Comment by etienne428** [comment]
Sounds good!
1/ the data comes in the QueryNode in the getURLForQuery(). Don't create methods for that, use a QueryTransformer. They are in a subfolder. I suggest that you use the DefaultQueryTransformer 
`new DefaultQueryTransformer().transformLuceneQuery(luceneQuery).orElse("")`
first and check if it works (you can have a look and compare it to the API. If it doesn't, create your own DOABQueryTransformer class implementing AbstractQueryTransformer of a subclass.

You can add parameters using a URIBuilder with the help of the method 
`addparameter(parameterName, parameterValue)`
Then, you have the method getParser() that needs to transform whatever you get with the link from getURLForQuery() into a List of Bibentry. There, additional methods can be useful (see CrossRef#jsonItemToBibEntry for example).

**Comment by RonaldSnijder** [comment]
Hi,

I am responsible for the technical development of the OAPEN Library (https://oapen.org/resources/15635975-metadata) and DOAB (https://www.doabooks.org/en/doab/metadata-harvesting-and-content-dissemination). Both use the same platform, based on DSpace6. While I am no developer, please let me know if I can assist in any way.

Thanks,
Ronald

**Comment by Mohamadi98** [comment]
@etienne428 Hi,
I compared the results from DefaultQueryTransformer
 `new DefaultQueryTransformer().transformLuceneQuery(luceneQuery).orElse("")`, it can work I will just have to manipulate the string returning from the above method a little to be in the format provided by the API [https://www.doabooks.org/en/doab/metadata-harvesting-and-content-dissemination](https://www.doabooks.org/en/doab/metadata-harvesting-and-content-dissemination), for example
user input->> "Geography",   API URL->>https://directory.doabooks.org/rest/search?query=%22Geography%22
user input->> title:The deliverance of open access books,  API URL->>https://directory.doabooks.org/rest/search?query=dc.title:%22the+deliverance+of+open+access+books%22
user input --> classification:Politics & Government, API URL->> https://directory.doabooks.org/rest/search?query=dc.subject.classification:%22Politics+%26+Government%22
but for this solution the label used by the user(title, classification) needs to be known, is there a method that returns the user label ?
Or I can create a transformer that handles all that on it's own.
One last thing, I am new to open source so is there a method where you can review what I have implemented so far, I know I can make a pull request but it is not ready yet.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> One last thing, I am new to open source so is there a method where you can review what I have implemented so far, I know I can make a pull request but it is not ready yet.

When you open a pull request you can open it as "draft" (or [convert it to draft after you've opened a regular PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft))

**Comment by Mohamadi98** [comment]
Thanks

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@RonaldSnijder do you know if there is any specific format for the authors' names or to whom we should ask that question?

**Comment by RonaldSnijder** [comment]
The authors and editor names are stored as text, formatted last name comma, first name. For instance, my name is stored as "Snijder, Ronald" (https://library.oapen.org/handle/20.500.12657/25287?show=full). Does this answer your question?

**Comment by RonaldSnijder** [comment]
Sorry, linked to the OAPEN Library. The DOAB link is this: https://directory.doabooks.org/handle/20.500.12854/26303?show=full

**Comment by Siedlerchr** [comment]
@RonaldSnijder For most entries this seems to be correct, however in the example query for https://directory.doabooks.org/rest/search?query=water+AND+fire&expand=metadata 
@k3KAW8Pnf7mkmdSMPHz27  and I discovered that the authors include (Ed.) and are in the field dc.contributor.author and not dc.contributor.editor 
https://directory.doabooks.org/handle/20.500.12854/61440 

And then there is this guy with (Liton) in braces. Although this seem to be his name, he is also printed with braces on the cover...
https://directory.doabooks.org/handle/20.500.12854/56322

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> Does this answer your question?

Mostly, as @Siedlerchr says. Perhaps I misphrased my question and I should have asked about how the names get into the system in the first place.

```
<metadata>
	  <key>dc.contributor.author</key>
	  <language>*</language>
	  <value>Fátima Velez de Castro</value>
</metadata>
```

Does this mean that the first/last name couldn't be determined?

**Comment by RonaldSnijder** [comment]
Hi,

The data in DOAB have been added over a decade by multiple publishers, with no complex validation. Furthermore, the contents have been migrated to a new platform. So, this means there will be names that do not exactly match the pattern, sorry about that. An indeed, there are now three fields describing contributor roles:
* Author: dc.contributor.author - see for example https://directory.doabooks.org/handle/20.500.12854/80487?show=full (contains both authors and editors)
* Editor: dc.contributor.editor
* Other roles (translator, illustrator etc.): dc.contributor.other - see for example https://directory.doabooks.org/handle/20.500.12854/64223.6?show=full

Regards,
Ronald

**Comment by ThiloteE** [comment]
#8598 introduced the DOAB fetcher to websearch. Closing this. There may be follow up pull requests, but the main issue why I opened this thread is adressed :-)

Thank you all for your contribution.
