### ISSUE TITLE
New line ignored if only one new line is placed in the comment field

### ISSUE THREAD

**Issue by Martin2278** [JabRef/jabref#8584]
When adding comments to an entry and looking at the column of the list, it can be seen that the comment is not wrapped if only one new line is created. When adding a white line in between, the comment is wrapped, but there is a lot of space used in the list view.

**Describe the solution you'd like**
Wether
- A single wrap in the comment should be a wrap in the list and in the preview
or
- A wrap in the comment should be a wrap in the list alone.

So the content in the list view is more compact

**1) No white line between every comment line --> In the list above everything is in one line and not the complete comment is visible**
![grafik](https://user-images.githubusercontent.com/98887275/159227644-335dd36f-e9c2-495c-9f01-c78b5d2bb2cb.png)

**2) White line between each line --> a lot of space is used in the list view**
![grafik](https://user-images.githubusercontent.com/98887275/159227591-fd4a8ea5-e753-4351-952c-5d31814906fc.png)

**Comment by Murmele** [comment]
@ThisTestUser thank you for the explanation.
