### ISSUE TITLE
Shared database: library modification warning without apparent modification

### ISSUE THREAD

**Issue by m-mauersberger** [JabRef/jabref#8586]
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Details on version and operating system

10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Log in to shared database (PostgreSQL). Set tick at "automatically save library" and choose a Bibtex file.
2. Add an entry somewhere or modify something.
3. A warning appears instantly that modifications by another program has been detected but there was no other program.

![JabRef_Issue_220321](https://user-images.githubusercontent.com/67641254/159253955-82be8f1c-585a-41a4-8fdb-f61d89c7c776.png)

This warning appears at every action you take. Dismissing changes have no lasting effect. Reviewing changes exhibits that a comma was removed somewhere, e.g. at the end of the keywords list.

![JabRef_Issue_220321](https://user-images.githubusercontent.com/67641254/159254138-866505bc-effd-414a-8da5-f0682f607378.png)

Maybe it would be more convenient to make little changes silently. It is somehow confusing to read that another program was involved.

Thank you for your help!

**Comment by m-mauersberger** [comment]
I checked this problem up again and can detail the behavior somewhat:
I changed every entry with trailing comma in the keywords list. As a consquence, these entries were not incoporated anymore in the changed warning.

However, this warning appears if you type in some content in an entry field (e.g. keywords) via keyboard. It seems like only the first character of the typing in is saved "On disk" (right column) while it is compared to the content in JabRef. Maybe it would help when comparison took place after some delay.
![JabRef_Issue_220328](https://user-images.githubusercontent.com/67641254/160358017-866e8c14-0bfa-4ad0-a663-07c7bf0c46a6.png)

**Comment by Siedlerchr** [comment]
Thanks for the investigation @koppor  This might be hint towards our problem

**Comment by Siedlerchr** [comment]
@m-mauersberger  I think we finally found the root cause and fixed it. 
https://builds.jabref.org/main/

**Comment by koppor** [comment]
The fixing PR was https://github.com/JabRef/jabref/pull/9216

**Comment by m-mauersberger** [comment]
I can confirm that the problem has been solved. Thank you very much for your efforts!
