### ISSUE TITLE
Formatter try out ui

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#860]
We use formatter for both cleanup and the save actions. A formatter is an input/output system which applies for fields. It would be interesting if we could have a GUI with one can try out how the formatter will behave on arbitrary field contents.

**Comment by tobiasdiez** [comment]
Viewing formatters as a subset of cleanup operations, a preview of the changes in the preview dialog would be nice. Maybe something similar to how the code formatting is previewed in IntelliJ's settings?

**Comment by simonharrer** [comment]
I think the current system with the description is good enough.
