### ISSUE TITLE
Author surnames starting with a lower case letter disappear in citation key

### ISSUE THREAD

**Issue by RonMcKay** [JabRef/jabref#8601]
### JabRef version

5.5 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.5--2022-01-17--27a05c7 Windows 10 10.0 amd64  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Set the default pattern of the Citation key pattern to `[auth][year]`
2. Add an article with a first author who's surname starts with a lower case letter (e.g. https://arxiv.org/abs/2103.10697) or edit an existing article so that the first letter of the first author's surname is lower case.
3. Hit 'Generate citation key' -> 'Overwrite keys'

The resulting Citation key is missing the `[auth]` field and is just displaying the year.

**Comment by mlep** [comment]
Confirmed in JabRef 5.6--2022-03-21--b47c29f
Linux 4.19.0-19-amd64 amd64 
Java 17.0.2 
JavaFX 18+12

**Comment by Siedlerchr** [comment]
I dug a bit into it. JabRef parses the first author [Stéphane d'Ascoli](https://arxiv.org/search/cs?searchtype=author&query=d%27Ascoli%2C+S)  into firstname + vonPart . So far so correct.  
The `[auth] `patterns only returns the last name, it does not consider the von-Part. That is only considered when using
`[authFirstFull].`
In contrast, an author like `Michiel van den Brekel` is generated correctly.  `Breken` is identified as lastname.
However, with `[authFirstFull] `you would get `vandenBrekel2021`

A possible solution would be to return the vonPart (if any) in case the lastname is empty.
