### ISSUE TITLE
Specify a (persistent) custom style for heading of bibliography in LO/OO

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8602]
Came up in the forum: https://discourse.jabref.org/t/can-i-specify-a-persistent-custom-style-for-the-heading-bibliography-in-libreoffice/3283

"The heading “Bibliography” is set automatically to Heading 2 when I create it. I can change the style in in the document in LibreOffice, but every time the bibliography refreshes it changes the style back to Heading 2.

How can I get JabRef to respect my changes or allow me to change the Bibiography style to one of my choosing?

I’m using the first Default style file under Select File in the left-hand pane. I’ve fired up the utility Export-Filter_Editor_Linux_64bit_V04b, but it doesn’t seem to have an option to change this.

Thanks"

 \- impracticaldogg

**Comment by Siedlerchr** [comment]
From the code it looks like  it's `ReferenceHeaderParagraphFormat` in the jstyle

So you need to define a format which exists in LO (e.g. custom or existing paragraph style format)

 /**
     * Name of paragraph format (within OO/LO) to be used for
     * the title of the bibliography.
     */

https://github.com/JabRef/jabref/blob/89d10479237923ba6dec6c7f30901d2a20a4917b/src/main/java/org/jabref/logic/openoffice/style/OOBibStyle.java#L64-L65
