### ISSUE TITLE
importer via doi does not work/resolver issue?

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8605]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-03-23--1624405 Linux 5.16.16-200.fc35.x86_64 amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. New Entry
2. Select `DOI`
3. enter 10.1037/qup0000076 or 10.1080/26395916.2020.1814417; `Generate`

both DOIs do not succeed. Which is not the case for the web based doi resolver

**Comment by Siedlerchr** [comment]
I also had troubles  as well today, and a manual request shows a timeout to me. So maybe a CrossRef issue.

**Comment by ilippert** [comment]
works again today
