### ISSUE TITLE
A new protected terms file in the preferences is gone after a restart

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#8608]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a new Custom Protected Terms file in the Preferences -> Protected terms file
2.  Notice that the terms file is added. 
3. Save the preferences 
4. Reopen the preferences : Protected Terms file is still there
5. Restart JabRef
6. The protected terms file is no longer in the list

**Comment by HoussemNasri** [comment]
I can reproduce this on windows too

**Comment by Siedlerchr** [comment]
I foud the problem: The FXCollections.umodiedfableIbservableList adds a WeakListener which gets garbage collected https://stackoverflow.com/a/44343014
