### ISSUE TITLE
Improve menu structure based on existing article

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#861]
http://www.markschenk.com/tools/jabref/interface/menus.html

I just found it on. Seems interesting. We could extract some information out of the article. 

@JabRef/developers what do you think?

**Comment by mlep** [comment]
Was Mark Schenk asked to become a developer?

**Comment by simonharrer** [comment]
I do not know. Maybe this is the time to contact him again for input, as JabRef is getting more momentum.

**Comment by Braunch** [comment]
I would suggest that our stupro-team could take a closer look at the article. To get the new blog functionality of the JabRef web page (http://www.jabref.org/blog/) into the game we could make a mockup and present it to the community. Hopefully we get some feedback before implementing the menu changes.

**Comment by lenhard** [comment]
Since we do not really have a concrete issue here (except for "the gui should be better structured"), I will close this.

Feel free to open more concrete suggestions and PRs. More general discussion could also go to http://discourse.jabref.org/
