### ISSUE TITLE
Limit the possibilities of numbers of years to be registered

### ISSUE THREAD

**Issue by lorenzo7377** [JabRef/jabref#8630]
I think that it would be more convenient to make numbers below 0 or above 9999 unable to be registered as valid publication years.

**Comment by Siedlerchr** [comment]
Nope. Especially since Year is mapped to date. And biblatex date field allows for extended iso8601.
See the biblatex manual (section 2.3.9) for details https://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf
