### ISSUE TITLE
Custom class error with internal code

### ISSUE THREAD

**Issue by CarlosZoft** [JabRef/jabref#8633]
**Description**

It would be nice to have error classes with their own error codes. It would facilitate the debug and visualization of these errors when centralized in some platform like sentry or elastic. Imagine identifying errors with your own codes - example : jab-763 

**Some Screenshots**

Example implementation :
![Screenshot from 2022-03-31 23-43-56](https://user-images.githubusercontent.com/62192072/161185036-8112a29d-fa2a-404d-8d8e-6a89e876d269.png)

Goal : avoid this kind of treatment
![Screenshot from 2022-03-31 23-43-51](https://user-images.githubusercontent.com/62192072/161185047-3afd997b-adb4-4771-acda-367e3f426c7f.png)

**Comment by koppor** [comment]
I think, we cannot maintain these error codes. How nice would it be if we had human readable error names. - We have it: We already collect our errors based on the Java class names.

If you would do something, you could work on fixing a bug (see https://github.com/JabRef/jabref/projects/5 for a categorized list).
