### ISSUE TITLE
Error on Web search

### ISSUE THREAD

**Issue by AngelicaRibeiro** [JabRef/jabref#8635]
### JabRef version

5.5 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

DISTRIB_ID=ManjaroLinux DISTRIB_RELEASE=21.2.5 DISTRIB_CODENAME=Qonos DISTRIB_DESCRIPTION="Manjaro Linux"

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I've searched in CiteSeerX database
2. I used the search "Brain Computer Music Interface AND EEG"
3. JabRef found only 10 articles
4. I've done the same search in the 'CiteSeerX' site and the site found 273 articles.
5.  The 10 articles retrieved was the first 10 retrieved in the site
The same bug is happening for the other databases

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by AngelicaRibeiro** [comment]
I understand your point. 
I've been doing this, getting the .bibtex  from the site databases,  but the problem is that some sites, like CiteSeerX, just shows a limited number of article per page, and it's not possible to get their bibs all at once, which makes it difficult to do a systematic review for example. That's why I've tried to get them from JabRef all at once. A suggestion to surpass this problem is for the user to identify himself, e.g: enable it if it's in a college domain or something alike.

**Comment by ThiloteE** [comment]
I think this would be the relevant pull-request that would implement this feature: https://github.com/JabRef/jabref/pull/7720

**Comment by AngelicaRibeiro** [comment]
Ok :)
