### ISSUE TITLE
An empty entry can still be added without warning message (and lead to an error when compiling)

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8645]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-04-04--dbf921e Linux 4.19.0-20-amd64 amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a library
2. Add an entry (by clicking on the + button, for example)
3. Save the library
4. Close the library

No warning message is displayed (unlike stated in issue #8096), especially not the message of the PR #8218.
And so, the issue #8096 is still present: biber generates an error (`[8337] Utils.pm:411> ERROR - BibTeX subsystem: /tmp/biber_tmp_Qtbu/a9e03cb3043b9e2c02591da84105bb68_26801.utf8, line 36978, syntax error: found ",", expected one of: number, name (entry type, key, field, or macro name), end of entry ("}" or ")") or quoted string ({...} or "...")`)

My analysis:
1) the current definition of an empty entry is probably too strict.
For me, by default, an empty entry is
````
@Article{,
  creationdate = {2022-04-05T10:41:54},
  owner        = {mlep},
}
````
   So, not really an empty entry.
   But, since an empty _entry key_ is enough to lead to a biber error, I suggest _an empty key should be enough to raise the warning message_. 

2) Because you can compile your file after saving (i.e. while keeping your library opened), the biber error is generated before the warning message has a chance to be displayed. Hence, the warning message should be displayed on saving (i.e. not on closing).

3) The feature "Generate keys before saving (for entries without a key)" in `Options -> Preferences -> Citation key generator` is of no help because no key are generated for such an "almost empty entry".

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by mlep** [comment]
@ruoyu-qian: You may want to enhance your previous contribution to JabRef. Cheers.

**Comment by ThiloteE** [comment]
> 3\. The feature "Generate keys before saving (for entries without a key)" in `Options -> Preferences -> Citation key generator` is of no help because no key are generated for such an "almost empty entry".

Wait, this preference seems broken then?

**Comment by mlep** [comment]
@ThiloteE Not really: my key pattern is [auth][shortyear]. Since my "almost empty" entry does not have an author or a year, I cannot really blame this feature. :wink:

**Comment by ThiloteE** [comment]
Put devcall label, because there is the idea to get rid of the whole dialogue and delete these entries silently upon closing JabRef.

**Comment by koppor** [comment]
## Actions needed

- We need to refine the functionality `Generate keys before saving (for entries without a key)"`.\
  ![grafik](https://user-images.githubusercontent.com/1366654/172226568-b37667e7-aaeb-4ce8-b850-3b45ae9bfb7c.png)\
  - [ ] Set the default to `true`
  - [ ] In case an empty key is "generated", there should be a random number generated. Proposal: The Java object hash written as hex string
- Add "Integrity check" for empty BibTeX key\
   ![grafik](https://user-images.githubusercontent.com/1366654/172226400-64bf1a67-ea63-43fc-9db5-dc0148a758c3.png)\
   Currently, there are no errors reported

**Comment by koppor** [comment]
The challenge to work on this issue is to craft test cases.

**Comment by koppor** [comment]
We went for the simple solution: Do not write empty entries to the .bib file. When closing and opening JabRef again, these "empty" entries are gone.

TODO-tracking needs to be done by groups or other measures of JabRef.
