### ISSUE TITLE
Change order of ISBN fetchers to improve fetching most complete information

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8652]
See discussion and report of the problem in the forum: https://discourse.jabref.org/t/ebook-de-incomplete-isbn-information/3313

> When using the Import by ID feature using ISBN, the first search engine is ebook(dot)de, as explained in the jabref documentation. It seems that ebook(dot)de only provides one author in the author field (this has happened multiple times, I don’t know if it’s a general feature of ebook(dot)de). For example, for ISBN 0521099064, the [ebook.de output 1](https://www.ebook.de/de/product/3238810/stephen_hawking_the_large_scale_structure_of_space_time.html) shows Stephen Hawking as author, while the [ottobib.com output 1](https://www.ottobib.com/works-cited/e61a41660b) correctly shows S. Hawking and G. Ellis as authors. Shouldn’t the first search tool provide the most complete information?

> Can reproduce with ISBN: 9780203854693

> I think it makes sense to switch the order. Ottobib apparently uses WorldCat as source

**Comment by a1819644** [comment]
hi Team, can I have a look into this issue? Im new to open source community.

**Comment by ThiloteE** [comment]
Yes, this issue is for the taking :) Thanks for your interest!

Please check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth looking at. Feel free to ask if you have any questions here on GitHub or also at [gitter](https://gitter.im/JabRef/jabref).

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by ThiloteE** [comment]
(This issue might be a little too small for a team of 4 though)

**Comment by a1819644** [comment]
@ThiloteE thanks for your time and opportunity 
 Can we still take this issue cause none of my group member has any experience with open source contribution. 
 I believe this issue will be good start for us. To get familiar with the Jebref.

**Comment by ThiloteE** [comment]
Of course you can take this issue. I am not familiar with your course requirements and if you think it is alright, go ahead :-)
A lot of the other Adelaide students were choosing issues from the "[candidates for university projects](https://github.com/JabRef/jabref/projects/9)" page, so that made me think a little, but you do you! :-)

**Comment by a1819644** [comment]
Thanks for you quick response, we are the student of the "software development improvement". Sure i will visit "uni project" page . to look the other issues which fulfilling the subject requirement.

**Comment by a1819644** [comment]
@ThiloteE Going to create a pr draft for this but before that may I know what do you mean by  "I think it makes sense to switch the order."(https://discourse.jabref.org/t/ebook-de-incomplete-isbn-information/3313) ? 

Also, for some reason I am having issue with recreating the issue using ISSB : 9780203854693. Please see the attached snapshot of the issue.

![issue cant fetch](https://user-images.githubusercontent.com/88136301/163531565-36bd282b-43f0-453b-ab67-548c6174e19f.PNG)

@JustinNgu18

**Comment by Siedlerchr** [comment]
Jabref has two ISBN fetchers, ebook.de and ottobib. If the first fetcher does not find any results, the second one is automatically called.
So you simply need to change the code so that ottobib is called first and ebook.de second. 

And of course adapt the tests.

**Comment by ThiloteE** [comment]
> Also, for some reason I am having issue with recreating the issue using ISSB : 9780203854693. Please see the attached snapshot of the issue.

I also have this issue now.

This would be the entry in question:

```
@Book{PerseLambe20160829mea,
  author    = {Elizabeth M. Perse and Jennifer Lambe},
  date      = {2016-08-29},
  title     = {Media Effects and Society},
  doi       = {10.4324/9780203854693},
  edition   = {2},
  isbn      = {9780203854693},
  pages     = {340},
  publisher = {Routledge},
  url       = {https://books.google.de/books?id=W8bLDAAAQBAJ},
  urldate   = {2022-01-22},
}
```

**Comment by Siedlerchr** [comment]
Oh damn, forget about it: https://www.ottobib.com/ says:
OttoBib is no longer operational (in service from 2005 - 2022)

**Comment by a1819644** [comment]
> Oh damn, forget about it: https://www.ottobib.com/ says: OttoBib is no longer operational (in service from 2005 - 2022)

True, Forgot to mention it. So, do you recommend to use the alternatives of the OttoBib such as https://zbib.org/
    https://www.mybib.com/
    https://app.bibguru.com/
  
and take out the OttoBib from second search now and use alternatives?

**Comment by Siedlerchr** [comment]
The zbib.org or the paperpile could work https://www.bibtex.com/c/isbn-to-bibtex-converter/ 
WorldCat requires an API key

**Comment by koppor** [comment]
Maybe, we should merge the information of all fetchers? Think, we discussed that somehow and neglected it because of traffic and difficulty of merging. Currently, I think, we can do a test phase with more users and then decide whether we a) call all and merge or b) use a different ordering...
