### ISSUE TITLE
Manually removing multiple linked files of a selected entry is not possible in one go

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#8659]
JabRef 5.6--2022-04-08--a6489cb
Windows 10 10.0 amd64 
Java 17.0.2 
JavaFX 18+12

### Steps to reproduce the behaviour

The current dev version of JabRef does not allow you to manually delete multiple linked files of a selected entry in one go.

1. Open JabRef and open the entry editor for an item to which multiple files are linked (e.g., article + several supplements)
2. Navigate to the "General" tab and then go to the row "File"
3. Try to select multiple files in the row "File" which you want to delete
4. This will fail, since you can only select a single file, i. e. you cannot delete multiple linked files in one go. Instead you have to do it one by one

Note, that this behaviour also applies to the "+" button of the "File" row, i. e. you can manually add only a single file every time you use the "+" button, but not multiples files at once.

Furthermore note, that this issue was not present in older versions of JabRef (e.g., 3.8.2) - there it was possible to remove multiple linked files at once. This is also the reason why I put the problem under issues (and not enhancements), since it is ultimately a regression from previous versions of JabRef.

**Comment by AEgit** [comment]
JabRef 5.6--2022-04-11--1c782b7
Windows 10 10.0 amd64 
Java 17.0.2 
JavaFX 18+12

The newest dev version has nearly completed solved this issue. There only remains one problem:
When multiple linked items are removed, JabRef will show the "Delete the selected file permanently from disk" for each item separately. E.g., if the user removes 3 linked items, the dialog asking whether the respective file should be deleted from disk or should just be removed from entry will be shown 3 times.

This is not the expected behaviour - instead the user would expect to answer this dialog once for all items that were selected. So if the user selects the option "Remove from entry" from the dialog, then this should be applied to all linked entries that have been selected for removal (not for each entry separately).

**Comment by AEgit** [comment]
@koppor Can we re-open this issue, given the remaining problem (see https://github.com/JabRef/jabref/issues/8659#issuecomment-1095549817)?

**Comment by LIM0000** [comment]
## JabRef version
Latest main development branch

## Operating system
Windows

## Issue
> When multiple linked items are removed, JabRef will show the "Delete the selected file permanently from disk" dialogue for each item separately. E.g., if the user removes 3 linked items, the dialogue asking whether the respective file should be deleted from disk or should just be removed from entry will be shown 3 times.

I have tested on multiple linked files deletion (by selecting them via `Shift`) but the confirmation dialog only show once for a file. I am expecting there will be multiple confirmation dialogs popup as stated by @AEgit .
Could anyone please run a manual test to see if the deletion of multiple linked files able to popup multiple confirmation dialogs?
Thanks in advance.

**Comment by ThiloteE** [comment]
I can confirm.

Selecting multiple attached files in the "file" field in the general tab of the entry editor and then pressing "DEL" on my keyboard pops indeed multiple confirmation dialogues.

JabRef 5.7--2022-05-16--6a2332f
Linux 5.4.0-110-generic amd64 
Java 18.0.1 
JavaFX *unknown*

**Comment by LIM0000** [comment]
Thanks @ThiloteE , I have found inconsistency with the file deletion confirmation dialogue.

1. If selected multiple files and press on `DEL` on keyboard, **multiple confirmation dialogs pop up**.
2. If selected multiple files -> right click -> `Permanently delete local file`, **only 1 confirmation dialog pops up**.

**Comment by HoussemNasri** [comment]
> I have found inconsistency with the file deletion confirmation dialogue

Since there is already an option in the right-click context menu to remove selected files from an entry with a single click; "Remove link," I believe 'Permanently delete local file' should delete selected files from disk without displaying any dialogs (or show one confirmation dialog that has only two options; delete selected files permanently or cancel).
