### ISSUE TITLE
Rename cleanup actions: "Prepare for LaTeX" and "Prepare for BibTeX"

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8672]
When this first came up: https://github.com/JabRef/jabref/issues/8490#issuecomment-1091209909

**My Problem:**

Cleanup actions are not well described and contrary to users intuitive thought.

I always thought the "LaTeX cleanup" action would remove **LaTeX code** so that the entries will be rendered well via CSL entry preview or alternatively that the entries will be rendered well when using them with OpenOffice/LibreOffice, but instead this action mostly removes characters (via RegEx) that **hinder** the bibliographic data to be used with LaTeX. Therefore, this cleanup-action does not convert from LaTeX to *"something else"*, but rather it goes the opposite direction.

**Solution:**

Make it more transparent to the user, which of the clenaup actions are advised to be used when trying to use the entries with LaTeX and Bibtex.

~Make ready for LaTeX:~

~- [ ] Rename "LaTeX cleanup" action to `Make ready for LaTeX: Cleanup`~
~- [ ] Rename "Unicode to LaTeX" to `Make ready for LaTeX: Unicode to LaTeX`~
~- [ ] Rename "HTML to LaTeX" to `Make ready for LaTeX: HTML to LaTeX`~
~- [ ] Rename "Ordinals to LaTeX superscript" to `Make ready for LaTeX: Ordinals to LaTeX superscript`~
~- [ ] Rename "Units to LaTeX" to `Make ready for LaTeX: Units to LaTeX`~

Prepare for LaTeX:

- [ ] Rename "LaTeX cleanup" action to `Prepare for LaTeX: Cleanup`
- [ ] Rename "Unicode to LaTeX" to `Prepare for LaTeX: Unicode to LaTeX`
- [ ] Rename "HTML to LaTeX" to `Prepare for LaTeX: HTML to LaTeX`
- [ ] Rename "Ordinals to LaTeX superscript" to `Prepare for LaTeX: Ordinals to LaTeX superscript`
- [ ] Rename "Units to LaTeX" to `Prepare for LaTeX: Units to LaTeX`

~Make ready for BibTeX:~
~- [ ] Rename "Normalize month" to `Make ready for BibTeX: Normalize month`~
~- [ ] Rename "Normalize names of persons" to `Make ready for BibTeX: Normalize names of persons`~
~- [ ] Rename "Normalize pagenumbers" to `Make ready for BibTeX: Normalize pagenumbers`~

Prepare for BibTeX:
- [ ] Rename "Normalize month" to `Prepare for BibTeX: Normalize month`
- [ ] Rename "Normalize names of persons" to `Prepare for BibTeX: Normalize names of persons`
- [ ] Rename "Normalize pagenumbers" to `Prepare for BibTeX: Normalize pagenumbers`

**Comment by ThiloteE** [comment]
- Add to documentation of `Make LaTeX ready: Cleanup`: Single `$` characters will not be removed from the entry. This allows to start and end LaTeX math-mode.

**Comment by zkl-ai** [comment]
Hello, I am new here and I have read the doc, I want to contribute to the open source community. Could assign this issue to me?

**Comment by ThiloteE** [comment]
Hey, actually I was trying to work on this myself, because I am a complete beginner. I was surprised somebody would be interested in this issue this fast. **If you really want to, you can do it, of course. Your choice!**

 Christoph told me what needs to be done:
 
- For every formatter, change the localization (l10n) 
- adapt the `en.properties` file accordingly

Documentation that will help fixing this issue specifically:

- https://devdocs.jabref.org/getting-into-the-code/code-howtos
- https://devdocs.jabref.org/getting-into-the-code/code-howtos#using-localization-correctly


 I am not sure if you would want to call fixing this issue here coding 😂 To my understanding, it is just about tweaking a few small lines of code and changing the documentation. There will be no new code. I assume, it is perfect for beginners that
- have never coded (in java) before and
- just want to learn about how to install and start the relevant programs,
- want to learn about how to find something in the JabRef codebase
- and want to learn how to create a pull request on GitHub.

If you want to or are required to work on more dauntin tasks, check out the other issues that are labeled `good first issue` 😊


-----

Ps.

As a general advice, check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is a good start. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by zkl-ai** [comment]
Thank you for your positive reply. I'd like to take this issue.

**Comment by zkl-ai** [comment]
> Instead of "Make LaTeX ready: ..." I think "Prepare for LaTeX ..." might be grammatically more sound. Let's go with that? What do you say?
> 
> Also, actually I am not completely sure if the "LaTeX cleanup" action prepares for LaTeX or if it prepares for something else. Needs investigation. See documentation about clean up entries: https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions

I think it good. OK, let's go with that'.

**Comment by mlep** [comment]
I do not understand "Prepare for LaTeX". JabRef works on .bib files. They are designed to be used by BibTeX and biber, not LaTeX (at least not directly).

**Comment by ThiloteE** [comment]
Hmm. Then, maybe it should be changed to "`Prepare for BibTeX/Biber`" ... Sorry, I don't know the nuances, but I know that we use LaTeX2Unicode and Unicode2LaTeX converters (instead of UnicodeToBibTeX converters), so I assumed LaTeX is the underlying engine, syntax or standard.

JabRef works with .bib files, but it also can export bibliographic data to LibreOffice/OpenOffice or Microsoft Windows. When doing so, it is not necessary to convert bibliographic data, which can be read by LaTeX/Biber/BibTeX (or whatever) and therefore it would make sense to make the clean-up actions that ARE necessary for LaTeX/Biber/BibTeX more distinct. Worst case scenario, beginners create MIXED bibliographic data, that creates wrong output when compiled with Biber/BibTeX, but also creates wrong output when exporting to LibreOffice/OpenOffice or Microsoft Word.

**Comment by ThiloteE** [comment]
Hmm. I think "Prepare for LaTeX" is better after all. Look at the preamble of [The Comprehensive LaTeX symbol list](https://www.ctan.org/tex-archive/info/symbols/comprehensive): They incorporate special characters from multiple packages. Biber and Bibtex are packages that use LaTeX, but these cleanup actions can also be used to prepare usage for other packages.

> This document lists 18150 symbols and the corresponding LATEX commands that produce them.
> Some of these symbols are guaranteed to be available in every LATEX 2𝜀 system; others require fonts
> and packages that may not accompany a given distribution and that therefore need to be installed.

**Comment by mlep** [comment]
Biber and BibTeX are not packages; they are independent programs that get the bibliographic references ready to use by LaTeX. But, yeah, sure, they belong to the same workflow!

My initial remark came from the "Make ready for LaTeX" and "Make ready for BibTeX" lists of actions. I did not understand the need to separate them.

So, if there is a "Prepare for LaTeX", will we also need a "Prepare for LibreOffice/OpenOffice" and a "Prepare for Microsoft Office"?

**Comment by ThiloteE** [comment]
> My initial remark came from the "Make ready for LaTeX" and "Make ready for BibTeX" lists of actions. I did not understand the need to separate them.

Fair enough. I mostly followed what is already in the description of the cleanup actions. If you hover with your mouse above them, you will see a small description.

> So, if there is a "Prepare for LaTeX", will we also need a "Prepare for LibreOffice/OpenOffice" and a "Prepare for Microsoft Office"?

Maybe, if people so desire? Most entry bibliographic data I fetch from bibliographic providers is already encoded in Unicode, so there does not need to be any preparation, but very rarely, it is not. I would not want people to use "Prepare for MS Office", when it is already prepared, because that might falsify bibliographic information. Maybe there should be a warning and explanation about this to users in that case.

The good thing is: There are also cleanup actions that qualify to be used ALWAYS. E.g. the "normalize date" :-) It's a good one!

**Comment by mlep** [comment]
> 



> > My initial remark came from the "Make ready for LaTeX" and "Make ready for BibTeX" lists of actions. I did not understand the need to separate them.
> 
> Fair enough. I mostly followed what is already in the description of the cleanup actions. If you hover with your mouse above them, you will see a small description.
> 
Ah, OK, thank you for explaining.

> > So, if there is a "Prepare for LaTeX", will we also need a "Prepare for LibreOffice/OpenOffice" and a "Prepare for Microsoft Office"?
> 
> Maybe, if people so desire? Most entry bibliographic data I fetch from bibliographic providers is already encoded in Unicode, so there does not need to be any preparation, but very rarely, it is not. I would not want people to use "Prepare for MS Office", when it is already prepared, because that might falsify bibliographic information. Maybe there should be a warning and explanation about this to users in that case.

But if it is prepared for LaTeX, will I be able to use it with MS Office? If not, I will need a "Prepare for MS office".
Note that such an action could be setup as a save actions (in Library -> Library properties")

> The good thing is: There are also cleanup actions that qualify to be used ALWAYS. E.g. the "normalize date" :-) It's a good one!
Yeah, some do not, such as "Normalize page numbers". Hence "Normalize page numbers" should have a different meaning depending on the target application (LaTeX or XX Office).

**Comment by ThiloteE** [comment]
See also: https://discourse.jabref.org/t/uses-of-latex-cleanup-action-what-do-you-use-it-for-and-why/3348

**Comment by ThiloteE** [comment]
Closing this in favour of #8790
