### ISSUE TITLE
Location of JabRef backup files

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#87]
Personally, I find it distracting to have the `*.bak` backup files inside my project folders.
As we discussed at our [Brass-Meeting](http://www.brasserie-bamberg.de/) :beer:, we may move the location of these files to `AppData`or any other temporary folder to keep the user directory clean.

**Comment by simonharrer** [comment]
:+1: 

But we need to make sure that JabRef can always make the connection of the backup file and the original file. Maybe we need to hash the path for this to generate the name of the .bak file.

**Comment by mlep** [comment]
What about keeping them in the same folder but making them hidden files?
(Booh... I haven't got my share of beer)

**Comment by stefan-kolb** [comment]
I think if you want to keep your TeX projects in Git revision, which we do, it will still bother you.

**Comment by mlep** [comment]
Indeed, I do not use Git for my projects.
But if I was using Git, why would I need a backup file?
I believe Git will take care of the changes in my bib files, right?

**Comment by stefan-kolb** [comment]
Yes, but we are talking about the JabRef feature in particular.

**Comment by mlep** [comment]
So, why not to include in the database properties a "enable/disable backup"?
Hence, a given user can deactivate the backup when it is not needed (such as folders under Git/SVN).

**Comment by stefan-kolb** [comment]
I think this is already possible, but we want to change this to a non intrusive solution without bothering the user at all :blush:

**Comment by mlep** [comment]
Ah, ok!
