### ISSUE TITLE
DOAB fetcher does not fetch field ISBN

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8708]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

See this entry: https://directory.doabooks.org/handle/20.500.12854/35818

Search for "Accounts and Accountability in Late Medieval Europe" in JabRef DOAB websearch.

It finds:

```
@Book{EpurescuPascovici2020aaa,
  date      = {2020},
  title     = {Accounts and Accountability in Late Medieval Europe},
  doi       = {10.1484/M.USML-EB.5.119569},
  editor    = {Ionuț Epurescu-Pascovici},
  language  = {English},
  pages     = {318},
  publisher = {Brepols},
  subtitle  = {Records, Procedures, and Socio-Political Impact},
  url       = {http://library.oapen.org/handle/20.500.12657/39752},
  abstract  = {This volume stems from a conference organised in November 2018 at the
University of Bucharest in the frame of the European Research Council
project CASTELLANY ACCOUNTS, “Record-keeping, fiscal reform, and
the rise of institutional accountability in late-medieval Savoy: A source-oriented
approach”. Both the conference and the volume have received funding
from the European Research Council (ERC) under the European Union’s Horizon
2020 research and innovation programme (grant agreement No. 638436).
The volume traces the momentous transformation of institutions and administration under the impact of accounting records and procedures, c. 1250-1500. The focus on the materiality and organising logic of a range of accounts is complemented by close attention to the socio-political contexts in which they functioned and the agency of central and local officials.},
  keywords  = {middle ages, Europe, auditing, accounts, HB},
  uri       = {https://directory.doabooks.org/handle/20.500.12854/35818},
}
```

The ISBN field is missing.

Additional info:

code can be found here: [src/main/java/org/jabref/logic/importer/fetcher/DOABFetcher.java](https://github.com/JabRef/jabref/pull/8598/files#diff-5211ecb27db75d41827a8e4461c4fa0acd0cc152748d79da8a3dc1318b10d7fe)

**Comment by ThiloteE** [comment]
This is a follow up to #8576

**Comment by Siedlerchr** [comment]
Looked into it: The API result does not contain the ISBN number as field https://directory.doabooks.org/rest/search?query=%22i+open+fire%22&expand=metadata

**Comment by ThiloteE** [comment]
@RonaldSnijder is there a specific reason for this? Would it be possible to add the ISBN (`oapen.relation.isbn`) to the fields offered by the API? I feel bad for JabRef users fetching incomplete bibliographic metadata.

Another field that does not seem to be present: `oapen.imprint`. There might be more, but these are the two I noticed when testing the new DOAB fetcher.

**Comment by RonaldSnijder** [comment]
@ThiloteE Hi, there are two questions here, I think:
1. Where can I find the ISBNs? In short, the ISBN is part of the metadata connected to the BITSTREAM 
2. How can I access a filed like"oapen.imprint"? These fields - when they are part of the record - can be accessed via the API

Perhaps you can take a look here:
https://directory.doabooks.org/rest/search?query=handle:%2220.500.12854/26303%22&expand=metadata,bitstreams

Both issues are addressed.
Hope this helps!

**Comment by shafinkamal** [comment]
G'day! I'm a new contributor and I would like to a make an attempt at fixing this issue. I have read the [developer contribution page ](https://devdocs.jabref.org/contributing) and have setup an IntelliJ environment for local JabRef development as per [the instructions](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.html).

I was hoping someone could point me in the right direction as to where to begin solving the issue?

Thanks!

**Comment by ThiloteE** [comment]
Hi @shafinkamal yes, you are welcome. If you look at how the other fields (e.g. `title`, `date`, `pages` etcetera) are implemented and fetched, you might be able to add the `ISBN` field similarly. If you read carefully, I think most, if not all relevant information to solve this issue has already been presented in previous comments. A first step would be to look at the [code of the previous pull-request](https://github.com/JabRef/jabref/pull/8598/files#diff-5211ecb27db75d41827a8e4461c4fa0acd0cc152748d79da8a3dc1318b10d7fe) that implemented the DOAB fetcher.

**Comment by shafinkamal** [comment]
> 1. Where can I find the ISBNs? In short, the ISBN is part of the metadata connected to the BITSTREAM. There might also be additional ISBNs in oapen.relation.isbn; dc.identifier.isbn

Hi @RonaldSnijder,

Thank you for your comment. I note that in an example query: 

https://directory.doabooks.org/rest/search?query=%22i+open+fire%22&expand=metadata,bitstreams

There is no metadata relating to the ISBN within the connected `BITSTREAM` as you have suggested. I was wondering if you knew if there was another way to observe the metadata to obtain the ISBN?

Thanks,
Shafin
