### ISSUE TITLE
About dialog should enable copy and paste

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#871]
* JabRef version (available in the About box): JabREf 3.3dev--snapshot-2016-02-26--master--20e95f9
* Operation system and version: Windows 8.1
* Steps to reproduce: 
  1. Open About Dialog

When filing an issue, it should be easy to copy the version string.

![grabbed_20160226-142525](https://cloud.githubusercontent.com/assets/1366654/13353450/c9b8750a-dc94-11e5-8b96-d8447c5227a6.png)

**Comment by mlep** [comment]
Additionally, I note some weird characters among the author names. They appear both on your screenshot and on my Linux computer.

**Comment by koppor** [comment]
The weird characters are because of [GRADLE-1267](https://issues.gradle.org/browse/GRADLE-1267), fixed by https://github.com/gradle/gradle/pull/520, which is not integrated yet.

See also #682

**Comment by stefan-kolb** [comment]
See Intelij Copy to clipboard link in about dialog.

**Comment by koppor** [comment]
@boceckts Could you port the copy and paste from #964 to the `master` branch (without JavaFX libraries)?

**Comment by koppor** [comment]
Refs #968 (javafx) and #1298 (SWING). I think, it's solved.
