### ISSUE TITLE
The error console should be resizable

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#872]
The Window showing the Error Console (Window "Program output") should be resizable.

Refs #819

**Comment by oscargus** [comment]
See #819 as well in case someone gives it a go.

**Comment by koppor** [comment]
This is fixed at our javafx branch. The binary is available at https://builds.jabref.org/javafx/.

The PR tracking the javafx updates is available https://github.com/JabRef/jabref/pull/2290
