### ISSUE TITLE
Option to use System Preference for Light/Dark Theme (Win/Lin/OSX)

### ISSUE THREAD

**Issue by dupontinquiries** [JabRef/jabref#8729]
**Is your suggestion for improvement related to a problem? Please describe.**

I would appreciate a way to automatically apply either a light or dark theme whenever I switch my light/dark theme in my MacOS system preferences. Sometimes I am using an eink monitor and I prefer light themes because they are easier to read on eink IMO, and other times I am on an LCD panel monitor and do not want to hurt my eyes with a light mode (I want dark mode here).

**Describe the solution you'd like**

Could a radio button be added to the Appearance section of the settings dialog that says "Use System Default"?

**Additional context**

I would prefer a solution that does not require a program restart, but this may be easier or just a good first step to aim for.

Thank you to everyone who has contributed to this software!

**Comment by IceCloud76** [comment]
On Linux, it would be great if Jabref respected freedesktop.org's color scheme preference as well. It's universal across almost all Linux desktops now, so there should be no need to make the code specific to any one desktop or theme

**Comment by Siedlerchr** [comment]
Needs to be done for each OS individually (as there is not yet a java/javafx API for doing this): Ideally using already existing tools see for example as an idea: (
https://gist.github.com/HanSolo/7cf10b86efff8ca2845bf5ec2dd0fe1d

**Comment by shafinkamal** [comment]
Hello, could I please be assigned to this issue? I'd like to make an attempt on it. Could someone please also let me know where to place the listener so that it can listen in the background for changes in MacOS System Preferences?

**Comment by Siedlerchr** [comment]
@shafinkamal I would just check this once on startup or in the preferences. There needs to be an option to override the automatic detection

**Comment by aqurilla** [comment]
Hi, I would like to take up this issue

**Comment by Siedlerchr** [comment]
@aqurilla  Thanks for your interest, there is already a good external library https://github.com/Dansoftowner/jSystemThemeDetector however,  due to the method too large exception we could not integrate it :(

**Comment by ThiloteE** [comment]
Then let's remove this from good first issues and candidates for university projects for now.

**Comment by aqurilla** [comment]
@Siedlerchr no problem, I'll try one of the other issues

**Comment by calixtus** [comment]
See https://github.com/HanSolo/JDKMon/blob/5602b03b36a12c66caf7793ab749520e9d2d5762/src/main/java/eu/hansolo/fx/jdkmon/tools/Detector.java#LL138C40-L138C41

**Comment by tobiasdiez** [comment]
With the recent progress, the JDK issue shouldn't pose a problem anymore. For anyone interested in working on this, the PR https://github.com/JabRef/jabref/pull/9263 might be a good starting point

**Comment by EthanYifanJu** [comment]
Hello, I have a university assignment right now. Can I give it a try?
