### ISSUE TITLE
Convert author "[name], [first name]" to "[first name] [name]"

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8744]
**Is your suggestion for improvement related to a problem? Please describe.**
When importing information, either automatically when dragging a PDF in the window or from applications like Citavi, the name scheme for the author field is often "[name], [first name]", not "[first name] [name]". This results in additional effort after DOI information retrieval and in making the library consistent.

**Describe the solution you'd like**
Some way to deal with this. Possibly an action to automatically covert this in the cleanup menu, or some intelligent mechanism to detect this and suggest a solution.

**Additional context**
I think, Citavi has a setting for this. Not sure, how this is done normally, but JabRef always seems to expect "[first name] [name]".

**Comment by Siedlerchr** [comment]
In the entry editor, right click author field: 
<img width="802" alt="grafik" src="https://user-images.githubusercontent.com/320228/166163379-7bf19a55-e104-4f83-a4bb-620ebf7b9238.png">

**Comment by claell** [comment]
Thanks for your fast response! So, if the default is lastname, firstname; why do I get this when I retrieve DOI information:
![grafik](https://user-images.githubusercontent.com/6171135/166164020-01c62dd9-14ee-4c03-b202-47cb01664ddc.png)

Probably DOI uses a different format? But ideally, there wouldn't be a conflict caused by this.

**Comment by Siedlerchr** [comment]
Noticed that as well, the change detection or the import seems to not take into account the author cleanup

**Comment by claell** [comment]
Alright. So basically this issue is about having the DOI import respect the BibTeX format. Converting to a different format is probably not really needed, then. I think, Citavi offers an option to use different styles, but that would probably require other logic around it and at least I don't need that. So shall I close this issue and create another one for the DOI import?

**Comment by Siedlerchr** [comment]
Thanks, yes that would be good for the DOI! JabRef generally can handle also firstname lastname and tries to parse authors in different formats

**Comment by claell** [comment]
Alright, done: #8745

**Comment by claell** [comment]
Closing this now. If others feel a need for this, they can request reopening, I guess. But I doubt that this is a highly requested feature :)
