### ISSUE TITLE
maintable: only the first linked identifier (e.g. URL, DOI, ...) can be opened

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8758]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.6--2022-04-25--5c9d898 Linux 4.19.0-20-amd64 amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open of file with an entry having multiple linked identifiers (URL, DOI, etc). _Please find one below if you need_
2. In the entry table, move the mouse pointer onto the "inclined chain" icon (in the column "Linked identifiers). _If you leave the pointer there for a few seconds, you will see the list of the 2 linked identifiers._
3. Left-click on this icon

--> The list of linked identifiers is displayed shortly, and the first link opens in the browser.
So, you cannot select the second link. :cry: 

@Article{Name22,
  author       = {My Name},
  journal      = {A journal},
  title        = {A title},
  year         = {2022},
  doi          = {10.1145/3129790.3129810},
  url          = {https://link.springer.com/chapter/10.1007/978-3-319-56608-5_80},
}

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by HoussemNasri** [comment]
One approach would be to open the link directly if it is the only linked identifier present and to show the list of linked identifiers if more than one is present. This should be fairly easy to implement by making minimal changes to https://github.com/JabRef/jabref/blob/b938f180b9253a1c6cd06a959c2318ed9b5f266a/src/main/java/org/jabref/gui/maintable/columns/LinkedIdentifierColumn.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L32

**Comment by ThiloteE** [comment]
So is this about the maintable or about the entry-editor?

**Comment by HoussemNasri** [comment]
@ThiloteE It's about maintable. The current labeling is correct. You can also label it as a goodfirstissue because it can be fixed with minor code changes.

**Comment by ThiloteE** [comment]
For whoever will work on this: https://github.com/JabRef/jabref/issues/8802 is the same issue. Over there is a screenshot that depicts the place in the UI that needs to be changed.

**Comment by LIM0000** [comment]
Hi teams, I am interested to fix this issue and #8802.
Cheers.

**Comment by ThiloteE** [comment]
@LIM0000 Looks like [Rifat951](https://github.com/Rifat951) is already working on this.

**Comment by Rifat951** [comment]
> @LIM0000 Looks like [Rifat951](https://github.com/Rifat951) is already working on this.
I have already raised a Pull Request on that, please have a look.

**Comment by Siedlerchr** [comment]
Thanks to @Rifat951  this issue is now fixed in the latest development version:

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
