### ISSUE TITLE
New notification system overlaps task bar on Windows

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8769]
The new notification system works fine, but I am having the issue that the notifications overlap the task bar on Windows. Is this wanted?
![grafik](https://user-images.githubusercontent.com/6171135/166513523-b906d739-1edc-40b0-aaa5-358ad70b74b7.png)

_Originally posted by @claell in https://github.com/JabRef/jabref/issues/8753#issuecomment-1116390280_

**Comment by claell** [comment]
Introduced with #8733

**Comment by Siedlerchr** [comment]
Encounterd this on mac as well.

**Comment by Siedlerchr** [comment]
Thanks to @LIM0000  this is now fixed!
