### ISSUE TITLE
Allow all cleanup operations as save actions

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#878]
It would be nice to run any cleanup operations on save. Essentially, the only thing which is missing is writing and parsing of CleanupPresets to the bib-file.

@lenhard interested?

refs #877

**Comment by lenhard** [comment]
Just to make sure I understand you correctly: Do you propose to serialize the cleanup information into the bib file? Right now that is all global configuration in the preferences.

I guess integrating that into save actions would not be too hard logic-wise. But how would a good GUI solution look like? The save actions and cleanup operations are configured in completely separate dialog. That should be integrated somehow.

**Comment by tobiasdiez** [comment]
Yes, I want to serialize a copy of the cleanup information in the bib-file. Essentially, I want to extend the functionality of save actions to a whole cleanup preset instead of just the subset of formatters.

- The CleanupPreset class stores all the information to run a cleanup. This preset can be populated through the preferences, but also has a "simple" constructor - thus the parser could instantiate a new preset.
- This OnSave preset read from the bib file replaces the SaveActions (but contains all the formatters as an subset, see #877)
- The preset can be displayed using the CleanupPresetPanel. Thus the DatabasePropertiesDialog has to be changed to use this class instead of SaveActionsPanel.

Do you understand my idea? It's a bit hard to describe...

**Comment by simonharrer** [comment]
Hm, maybe we should discuss how much information we want to have written in the .bib file in the next dev call? Because at the moment, we are moving towards putting a lot of them in the bib file.

**Comment by lenhard** [comment]
I see. You basically want to move the panel from #877 into the database properties. I was a little sceptical at first, because the description sounded like completely throwing away the current save actions.

Overall, I think it makes sense to coalesce the features somehow, since they are very similar. Alas, my time in the next few weeks is quite limited, so don't count on me if you want to get this implemented quickly.
