### ISSUE TITLE
Improve Mac OS X building

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#88]
Currently, our MacAdapter class depends on `com.apple.*`. These classes are not available on a Linux or Windows JDK. Our current solution is to include [the legacy AppleJavaExtensions](https://developer.apple.com/legacy/library/samplecode/AppleJavaExtensions/Introduction/Intro.html), which are not available on jCenter. Another option is to use the [OrangeExtensions](http://ymasory.github.io/OrangeExtensions/). However, we use `com.apple.eawt.FullScreenUtilities`, which is not available.

We should get support of FullScreenUtilities into the OrangeExtensions and switch to them to get rid of AppleJavaExtensions.jar in the source repository.

**Comment by simonharrer** [comment]
The project OrangeExtensions seems to be unmaintained with pull requests open since 2013. See https://github.com/ymasory/OrangeExtensions

May be we need to switch back to the .class file which is loaded dynamically?

**Comment by koppor** [comment]
I propose to create a fork and take over the development lead of the OrangeExtensions. @stefan-kolb WDYT?

**Comment by stefan-kolb** [comment]
It's hard to give a definitive answer for me, as I'm not using OSX. In my opinion we need someone who actively uses OSX and can test/evaluate more on this topic.

As far as I can tell Apple dropped the native support for its Apple-specific Java runtime.
[1] https://developer.apple.com/library/mac/releasenotes/Java/JavaSnowLeopardUpdate3LeopardUpdate8RN/NewandNoteworthy/NewandNoteworthy.html#//apple_ref/doc/uid/TP40010380-CH4-SW1
[2] http://stackoverflow.com/questions/24479016/how-to-get-apple-java-extensions-com-apple-eawt-work-on-jdk-7-and-higher
[3] http://alvinalexander.com/java/java-mac-osx-about-preferences-quit-application-adapter

We are only using custom events for AboutHandler, OpenFile, Preferences and Quit.
I'm unsure how we should use and implement these stuff with newer OSX versions or if we already got it right. Official documentation seems hard to find. For me, this also makes it uncertain if we are using the right approach with the OrangeExtension Stubs.

Anyway, I think the switch to JavaFX will help tremendously in the effort of OS unification.
