### ISSUE TITLE
OO/LO: Jabref shoud respect MaxAuthors/MaxFirstAuthors in Bibliography

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#880]
Jab Ref 3.2 Development version, Libre Office 5.0.2 x64 on Windows 7x63

When I insert a cite with a lot of authors, the entry in the Bibliography should be capped to the MaxAuthorsFirst variable.
*_Current behaviour: *_ All authors are printed....
The cite itself displays correctly with Abbot et al. 
Either it could be displayed with et al in the bibliography style or following the APA style guide, with an elipsis (after the 6th author) to the last entry.
http://blog.apastyle.org/apastyle/2009/08/formatting-apa-references-with-more-than-seven-authors.html

BibTex: http://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.06110

![lomanyauthors](https://cloud.githubusercontent.com/assets/320228/13374058/9f4cc5b0-dd79-11e5-85fa-81cf72dba9ac.png)

**Comment by oscargus** [comment]
Are those lengths always the same or should one add another parameter for the bibliography?

**Comment by Siedlerchr** [comment]
From what I saw, in the style there exist those two Variables/Parameters. Maybe they couuld be reused.
Otherwise I would introduce a parameter for the Bibliography, e.g. LimitAuthorsBib

**Comment by oscargus** [comment]
OK! I checked the code quickly and I believe that unlimAuthors has something to do with it. It is mostly not documented, but when documented it claims to be an array of booleans, while it is declared as an array of integers... The purpose is apparently to be able to control "et al" on an entry level.

**Comment by oscargus** [comment]
After trying it out a bit more, I came to realize that the number of authors in the bibliography is probably handled by the layout part, so 
`default=\format[Authors(LastFirst,Semicolon)]{\author} (<b>\year\uniq</b>). <i>\title</i>, \journal \volume\begin{pages} : \format[FormatPagesForHTML]{\pages}\end{pages}.`

should be changed to e.g.

`default=\format[Authors(LastFirst,Semicolon,3)]{\author} (<b>\year\uniq</b>). <i>\title</i>, \journal \volume\begin{pages} : \format[FormatPagesForHTML]{\pages}\end{pages}.`

to put "et al" when there are more than three authors or 

`default=\format[Authors(LastFirst,Semicolon,3,2)]{\author} (<b>\year\uniq</b>). <i>\title</i>, \journal \volume\begin{pages} : \format[FormatPagesForHTML]{\pages}\end{pages}.`

to include the two first authors before et al.

Therefore, I think that this issue can be closed.

**Comment by Siedlerchr** [comment]
This looks good and the issue can be closed.
 However, it is not yet documented in the Help.
http://help.jabref.org/en/OpenOfficeIntegration/
