### ISSUE TITLE
Only have active buttons for undo/redo if there is something to undo/redo

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8807]
**Is your suggestion for improvement related to a problem? Please describe.**
The current buttons for this can always be clicked. There is no visual clue or prevention from clicking them needlessly.

**Describe the solution you'd like**
Other applications deactivate them in cases where nothing can be undone/redone.

**Additional context**
![grafik](https://user-images.githubusercontent.com/6171135/168651986-4a8dce20-559f-4a47-92ac-85f58394854c.png)

**Comment by ThiloteE** [comment]
@calixtus

**Comment by calixtus** [comment]
Undo redo is currently partially broken and does not work consistently.
We have a very large project running in the background to modernize the codebase (up to 20 years old) and to implement certain design patterns like the command pattern. As soon as this is done fixing the undo manager should be a fairly simple task. But there is still some way to go...

**Comment by claell** [comment]
Alright! I guess, that also explains #8770.

**Comment by calixtus** [comment]
Sadly yes... 😅

**Comment by claell** [comment]
Corresponding relevant line for the future seems to be this:
https://github.com/JabRef/jabref/blob/6a2332f6b17c818a7f091647b102e7099d36569e/src/main/java/org/jabref/gui/undo/UndoRedoAction.java#L33
