### ISSUE TITLE
Cleanup "Error console"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#882]
JabRef as built on 2016-02-28.

### Consistent naming of "Error console"
Help / "Show error console" brings up a window called "Program output". This is inconsistent. To clean the thing up, I propose to 
 * rename "Show error console" to "Show developer information"
 * rename "Program output" to "Developer information"

Reason: I neither find "Error console" nor "Program output" fitting. "Program output" fits better, but it is not the UI, it is the console output somehow. The log, however, is not shown on the console.

### Remove tab "Exceptions"
I think with the current exception handling, we can remove the tab "Exceptions". In case the "Log" shows an exception (such as `java.lang.NullPointerException`), the tab "Exceptions" does shows "No exceptions have occurred." This feels inconsistent. Therefore, I propose to remove the tab "Exceptions".

**Update**: I had an exception today (#890). Maybe we can try to log all exceptions somehow and then remove that tab.

### Change the big red x into something nice.
The window of the error console shows a big X on inside a red circle. That indicates errors, but we also show useful logs without errors. Other dialogs of JabRef also don't have an icon. Therefore, I propose to remove the X completely. If we want to go with icons because they support usability, we should use an "i" somehow.

![grabbed_20160228-141703](https://cloud.githubusercontent.com/assets/1366654/13379430/f39e4dda-de25-11e5-841b-f3d8c231b9c6.png)

**Comment by oscargus** [comment]
The X is because it is a JOptionPane(?) and will be automatically not there when a better solution (resizable and non-modal) is in place (unless someone adds it back explicitly).

**Comment by simonharrer** [comment]
Why not call the tabs "Logs", "System.err" and "System.out"? And the action "Show logs"?

**Comment by Siedlerchr** [comment]
I will try to rewrite this in JavaFX.

**Comment by koppor** [comment]
Good idea. Please base on the javafx branch. There is also a label javafx
and a first pull request for the about dialog rewritten in JavaFX.

**Comment by tobiasdiez** [comment]
I would remove all the tabs and just have one list for all messages. The different kinds of messages can then be differentiated via color or icons. This would also make debugging easier since debug messages are logged before and after the corresponding exception. 

Two further remarks:
- add button to toggle debug mode on/off 
- add button to copy log messages (necessary?)

**Comment by motokito** [comment]
Hiho,
I will ask something:
@koppor Should i remove "Exception" Tab?
@tobiasdiez Should i add this buttons?

thx for tip and help ;-)

**Comment by tobiasdiez** [comment]
The debug toggle is probably not that important but a nice extra. Copying the messages should be very very easy since we want users to include the output in their bug reports. So except if you come up with a more innovative solution, a simple button will do. 

What about renaming it to "Error diagnostics" or "Troubleshouting". The user doesn't have to care that we developer treat it as console output, but should click on it in case he has some problems. The dialog should also contain a short text directing the user to https://github.com/JabRef/jabref/issues

**Comment by simonharrer** [comment]
Maybe a functionality to create an issue in github with the details about the version, log and the .bib file (opt-in of course) plus a text. The github API seems easy to use, when looking at the code which checks for the update notification.

**Comment by motokito** [comment]
@simonharrer 
- Github api doesn't support attach file. (have a look at this link: [https://developer.github.com/v3/issues/#create-an-issue](url))
- So i will implement a function to create a issue with the details about the version and log, if it is okay.

**Comment by matthiasgeiger** [comment]
Is it possible to post a new issue in the name of the (logged in) GitHub user? I suppose it is not.... and using a "generic bug reporting user" is also not sensible for me as there is no way to contact the actual user to ask questions...

Another option would be to fill in the issue form using some GET parameters: https://github.com/JabRef/jabref/issues/new?title=bla&body=blubb

**Comment by motokito** [comment]
@matthiasgeiger 
I have tried to handler the create of new issue with automatics Binding of List - Entries about URL:
But there are some problems:

- First one: the URL Length is limit by ca. 2000 char (take a look at screenshot)
![01](https://cloud.githubusercontent.com/assets/13031192/16918055/6287d502-4d04-11e6-98bc-bc4a2ad92369.PNG)

- Second one: the methode openBrowser() of JabrefDesktop.class has a limit of 200 char (take a look at screenshot)
![02](https://cloud.githubusercontent.com/assets/13031192/16918054/6271d23e-4d04-11e6-96ed-a24dadc7cb26.PNG)

Need some helps and tipps. Thx you :-)

**Comment by tobiasdiez** [comment]
@motokito Maybe a POST request works (instead of GET with parameters)

**Comment by motokito** [comment]
@tobiasdiez 
Can you explain and give ne some Tipps. How should I implemented this solution ?
I am very thx you about it 😊

**Comment by oscargus** [comment]
http://stackoverflow.com/questions/4205980/java-sending-http-parameters-via-post-method-easily

**Comment by motokito** [comment]
@oscargus  Thx you about the links.
But i have some problem, that:
if one is not logged in to github, it will redirect one to login page. Once logged in, it will redirect one to the create new issue page. Now if we using GET method, it will fill in the parameter from the URL. But when using the POST method and we are not logged in. We will also get redirected to the login page and can not send our POST parameters for create new issue. This means we need to be log in befor sending the POST request for the new issue page.
Should i implement this github login functionality from jabref ? How can i open it in browser after i send GET / POST Request ?

Thx you about your help :-)

**Comment by Braunch** [comment]
I did not read through the whole of it but oAuth sounds like something worth having a look on https://developer.github.com/v3/oauth/
