### ISSUE TITLE
Entry ISBN can be found on worldcat, but information cannot be retrieved.

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8822]
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add 0-9533991-7-6 as ISBN to an entry
2. Opening the link works (worldcat)
3. Information for the entry cannot be retrieved

Question: Is this normal? Is a different data provider used than worldcat? Might be related to this special entry and might also not be an issue of JabRef.

**Comment by ThiloteE** [comment]
See https://discourse.jabref.org/t/building-catalog-of-5k-own-books/3381 for rough info about how ISBNs are currently imported and how workflows could be adjusted.

> In JabRef 5.6 the provider of bibliographic data when fetched via ISBN had to be switched. See [release notes](https://github.com/JabRef/jabref/releases) “[Now,] We first fetch ISBN data from OpenLibrary, if nothing found, [ebook.de](http://ebook.de/) is tried.”

**Solutions to your problem:**

- Find better or more open source Providers of ISBN metadata that allow JabRef to fetch it.
- Have more fall-back mechanisms when ISBN is not found by OpenLibrary or Ebook.de
- Have custom API key for worldcat; Users can use their own API key that allows them to fetch from world cat.
- The owner of the ISBN enters their data into open source databases that JabRef can fetch from.
- ...

I cross-checked:

- OpenLibrary does not find this ISBN.
- Ebook.de does not find this ISBN

Hence, it is unfortunate, but apparently JabRef is working as (currently) intended.

**Comment by claell** [comment]
Alright, got it. Thanks for the insights. Apparently, there is not really an easy way for such cases and this specific problem is caused because the entry is not available in the normal data providers and worldcat can apparently only be used for showing the entry easily, whereas it requires a custom API key to fetch information from it.

Will close this then, for now.
