### ISSUE TITLE
Single Identifier (DOI, URL, etc.) cannot be opened from maintable via left-click

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8832]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-05-19--4baf2a1 Linux 5.4.0-110-generic amd64  Java 18.0.1  JavaFX *unknown*

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Follow up to #8817

See https://github.com/JabRef/jabref/issues/8802#issuecomment-1130177317 for current problem:

> UPDATE:
> 
> the original bug was fixed, but it seems that a new bug has been introduced: in the patched version it is now impossible to click external links on entries that have only _one_ url...
> 
> How to reproduce:
> 
>     1. load any library that has only one external link (URL or DOI) attached to some entry, or remove the 'url =' line from the "doi-and-url.bib" from this entry and load it;
> 
>     2. left click on the web-link ("chained-link") icon;
> 
> 
> The link is not opened in a browser.

**Ugly Workaround:**

I tried to reproduce this and I noticed that it is now possible to open a single attached identifier not by left-click, but by right-click. The right-click menu will open as well, but will close immediately.

**Solution:**

Allow to also open identifiers with left-click, when there is only one identifier attached to an entry. Retain functionality of opening the list-popup, when there are multiple identifiers linked to an entry.

**Comment by Siedlerchr** [comment]
@Rifat951  Can you please take a look? Maybe one needs to distinguish if there is one or two to open
