### ISSUE TITLE
Rework ICAR Fetcher

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#8876]
Our fetcher calls the URL `https://eprint.iacr.org/eprint-bin/cite.pl?entry=2022/674`.

This leads to a 404:

![grafik](https://user-images.githubusercontent.com/1366654/171256092-79c79890-ce33-46d3-a935-0e951dba75e5.png)

We need to rewrite the IacrEprintFetcher to rely on `https://eprint.iacr.org/ID` (example: https://eprint.iacr.org/2022/674) only.

PR implementing the fetcher: https://github.com/JabRef/jabref/pull/3473

@derTimme Are you still active? Could you have a look?

**Comment by Siedlerchr** [comment]
In the news they state they now support this` 25-Apr-2022: ePrint rewritten in Python. Features include better capture of metadata and [OAI-PMH harvesting](https://eprint.iacr.org/oai?verb=Identify).`

https://eprint.iacr.org/oai?verb=ListRecords&metadataPrefix=oai_dc

**Comment by LIM0000** [comment]
Based on previous fetcher implementation in #3473, the idea follows the feature:
- [x] Fetched entry is of type misc and contains:
  - [x] Title
  - [x] Authors
  - [x] Url (contains the version)
  - [x] Note with \url{https://eprint.iacr.org/<identifier>} (recommended by IACR)
  - [x] Howpublished like Cryptology ePrint Archive, Report <identifier> (recommended by IACR)
  - [x] Version (most recent)
  - [x] Date (of the most recent version)
  - [x] Abstract

However, the misc from https://eprint.iacr.org/2022/674 only contains:
- [x] Fetched entry is of type misc and contains:
  - [x] Authors
  - [x] Title
  - [x]  Howpublished like Cryptology ePrint Archive, Report <identifier> (recommended by IACR)
  - [x] Year
  - [x] Note with \url{https://eprint.iacr.org/<identifier>} (recommended by IACR)
  - [x] Url (contains the version)
  - [ ] Version (most recent)
  - [ ] Date (of the most recent version)
  - [ ] Abstract

![111](https://user-images.githubusercontent.com/49628911/171349921-3886dead-edad-4a15-b8ee-538dedb6d56c.png)


Current IacrEprintFetcher does not seem to be able to parsed any entry from IACR. I wonder did the feature in misc just updated recently or our IacrEprintFetcher has been outdated for a while?

**Comment by LIM0000** [comment]
Thanks @Siedlerchr , I will raise a PR for this issue as soon as I am available.
