### ISSUE TITLE
Cannot add fields through BibTeX source

### ISSUE THREAD

**Issue by jorgman1** [JabRef/jabref#8883]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-06-01--943489e || Linux 5.10.0-14-amd64 amd64 || Java 18.0.1 || JavaFX *unknown*

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. I tried to add some BibTeX fields directly to the source code from within JabRef (e.g. "groups = {bla},"), but the changes are not saved. As soon as I switch to another entry they disappear.
2. Interestingly, deleting fields works.

**Comment by LIM0000** [comment]
Duplicate of #8859
