### ISSUE TITLE
Clear fields should automatically check "Overwrite existing field values"

### ISSUE THREAD

**Issue by jorgman1** [JabRef/jabref#8884]
**Is your suggestion for improvement related to a problem? Please describe.**
I wanted to clear some fields in many entries, and it took a couple of tries to figure out that I had to tick "Overwrite existing field values" as well.

**Describe the solution you'd like**
Either tick the box automatically, or remove it completely. There are four options and all are clear to me: "Set fields" (should overwrite the field), "Append to fields" (should not overwrite), "Rename field to" (should overwrite the name, otherwise I would add an option to copy and change name), "Clear fields" (should delete the field).

**Additional context**
I noticed, that some of the options are in plural (e.g. "Set fields"). Is it possible to edit several fields simultaneously? This is not clear from the drop-down menu.

![ClearFields](https://user-images.githubusercontent.com/48908520/171634423-f9c7e861-b8d9-4d47-bc15-6526a2d317ac.png)

**Comment by HoussemNasri** [comment]
Refs #6536

**Comment by jorgman1** [comment]
Duplicate
