### ISSUE TITLE
BibLaTeX mode: fields "Doi" and "Url" appear in tabs "Optional fields" and "General"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#889]
JabRef 2016-02-28--master--a0444ab

I am using JabRef with the BibLaTeX mode and looking at an article with following source:

```
@Article{HK2011,
  author =    {C. N. Höfer and G. Karagiannis},
  title =     {Cloud computing services: taxonomy and comparison},
  year =      {2011},
  volume =    {2},
  number =    {2},
  month =     jun,
  pages =     {81--94},
  doi =       {10.1007/s13174-011-0027-x},
  file =      {:HK2011 - Cloud computing services_ taxonomy and comparison.pdf:PDF},
  journal =   {J Internet Serv Appl},
  publisher = {Springer Science $\mathplus$ Business Media}
}
```

At the tab "general", the fields "Doi" and "Url" appear. These two also appear at "Optional fields". Should we really display these fields in both tabs?

Minor thing: The field "publisher" is appearing nowhere. This refs #454, but other users are searching for that field too (see [stackoverflow](http://tex.stackexchange.com/q/16978/9075)). I don't know whether we should make an exception for `publisher` as this is IMHO used very often at articles.

**Comment by simonharrer** [comment]
Maybe we need more dimensions other than required and optional, but also defined by the standard and custom?

**Comment by oscargus** [comment]
What about an additional tab with "undefined" fields, if any? (But with a better name...)

**Comment by simonharrer** [comment]
See #454 for that :)

**Comment by stefan-kolb** [comment]
All other fields are now displayed in a separate tab. 

The problem described here, however, persists.
Doi and Url are optional fields when using Biblatex. When using Bibtex they are not defined and would only be displayed in the Other tab. I don't know if we want this as these fields are kind of important for pur overall functionality, therefore displayed inside the general field. 

I would suggest to keep the behavior as is and close this issue.

**Comment by koppor** [comment]
Why not always displaying it at the "General" tab and remove them from the "Optional" tab. - I assume that it is very strange for a user that some fields are displayed multiple times in JabRef. Should we rename "General" to "Meta"? OK, "crossref" is no meta information.

**Comment by stefan-kolb** [comment]
Two reasons against this approach: The general tab can be reconfigured as wanted. These fields are defined as optional inside the "standard".

**Comment by mlep** [comment]
Seems related to  #1101 

"For a future redesign, I believe the tabs in the entry editor are already too numerous, making the UI complex.
As a suggestion for further discussion, we could have an small label along with each field name showing if the field is related to BibTeX, BibLaTeX, JabRef, Deprecated, Unknown, User-defined, etc.
Do we already have an issue related to the entry editor design? (I could not find an opened one...)"
