### ISSUE TITLE
org.jabref.preferences.JabRefPreferences class might need to be divided into simpler classes

### ISSUE THREAD

**Issue by dimitrisdimos00** [JabRef/jabref#8910]
Having calculated the Chidamber-Kemerer metrics on the whole JabRef project using the Intellij plugin metricsreloaded, it seems that JabRefPreferences is the class with the highest WMC (Weighted Methods Per Class) and RFC (Response for a class) values. WMC corresponds to the number of methods a class has while RFC corresponds to the number of methods of a class plus the number of secondary methods being called by each method. Classes with high WMC and RFC values are more prone to errors, more complicated and more difficult to understand. This is the reason why I am suggesting this class to be divided into two or more new classes.
![image](https://user-images.githubusercontent.com/56233132/174489079-6fadfcc8-8142-4f9b-a3e2-e79c5afb0664.png)

**Comment by koppor** [comment]
This could be a case where code metrics fail. Please read the code and the usage of the class. We already have minimal preference classes. The class you are referring to, is the collection class of all preferences.

The alternatives are IMHO dependency injection and factory pattern .

Solving this issue will be a task with 100 to 1000 hours effort.

**Comment by calixtus** [comment]
In fact we are in a long term refactoring progress of the prefs service, but as jabref is only a project for our free time, we can only work on this from time to time. If you are interested in working on this, please contact us, because we already spent a lot of time drafting a concept for this.

**Comment by calixtus** [comment]
Thanks for your interest in JabRef programming. As this issue is merly a code quality suggestion but a real issue and code quality is always been worked on, I will close this for the sake of gaining at least a tiny bit more oversight on our issue board.
