### ISSUE TITLE
Add notification or documentation for: Adding original entries to new group configuration unexpectedly modifies original entries

### ISSUE THREAD

**Issue by LIM0000** [JabRef/jabref#8911]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Steps to reproduce:
Part 1:
1. Create a new library.
2. Click on `Add group` button.
3. Input name `test1` for the group and create the group.
4. Create 2 articles in `All entries`.
5. Input author field with `steven` and `mike` for each article respectively.

Part 2:
1. Right click on `test1` group -> `Edit group`
2. Select `Searching for a keyword` under `Collect by`.
3. Input `author` as field and `steven` as keyword, then click on ok button and ok button for warning dialog.
(`test1` group has a steven article entry)

Part 3:
1. Right click on `test1` group -> `Edit group`
2. Select `Searching for a keyword` under `Collect by`.
3. Input `author` as field and `mike` as keyword, then click on ok button and ok button for warning dialog.
(`test1` group now has 2 articles which are `steven,mike` and `mike` articles)

<br/>
EXPECTED:
<br/>
I am expecting that part 3 will return both `steven` and `mike` articles.

ACTUAL:
However, 1 of the articles' author field has been merged to `steven,mike`. Is this an expected behaviour?
From my understanding, `Collect by` should only return filtered entries without any entries modification.
<br/>

![111](https://user-images.githubusercontent.com/49628911/174543454-25e48f43-a786-4b84-a6fd-fcab94164ed5.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Could you please show what is in the `{} biblatex source` tab of all shown entries?

I have come across a similar odd behaviour (see https://github.com/JabRef/jabref/issues/8527#issuecomment-1157727869), but back then, I was not able to reproduce with a fresh library.

**Comment by LIM0000** [comment]
I have done more researches to issue and understand what is happening behind the hood of the issue with `Searching for a keyword`.

When user edits a group from `Explicit selection` to `Searching for a keyword`, the group type changes from `ExplicitGroup` to `WordKeywordGroup`.  This `WordKeywordGroup` functions DYNAMICALLY. Using example from above, we set the field as `author` and keyword as `mike` in `WordKeywordGroup`, this group will automatically assign ANY NEW entries that have `author=mike` into it.

However, if user assigns any entry that does not have `author=mike` and the group is `WordKeywordGroup`, the group will have to modify the field and the value of the entry. Using example from above again, we set the field as `author` and keyword as `mike` in `WordKeywordGroup`, if user "forcefully" assigns entry with `author=steven` into this group, it does not make sense for `WordKeywordGroup` as this entry does not have `mike` in it. Therefore, `WordKeywordGroup` will append `mike` into the entry's author field which results in `author=steven, mike`. Now the `WordKeywordGroup` able to add the entry into its group.

`WordKeywordGroup` behaves correctly. Although there is a warning dialog asking users whether they would like to assign the original group's entries to this group, there is no warning dialog about modifying users' entries.

 
![111](https://user-images.githubusercontent.com/49628911/174714153-12397161-1272-4228-a3ff-6ce9ba2615d7.png)

**Comment by ThiloteE** [comment]
Great!

I would suggest to append to the `Change of Grouping Method: Assign the original group's entries to this group?` dialogue the following notification:

`(If original entries lack keywords to qualify for the new group configuration, confirming here will add them)`

Alternatively, this info could be added to JabRef's documentation

**Comment by Siedlerchr** [comment]
<img width="473" alt="grafik" src="https://user-images.githubusercontent.com/320228/176253229-dc74689f-7ad9-481c-8a31-360c575ac407.png">
