### ISSUE TITLE
Extension doesn't work due to the command is not pass as a string

### ISSUE THREAD

**Issue by linsui** [JabRef/jabref#8922]
### JabRef version

5.6 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

NixOS

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Import an entry from a browser.
2. 2 Nothing happens.

### Appendix

In https://github.com/JabRef/jabref/blob/3c2aae97bffdb44ccb064dba20ab26e03cf181f2/buildres/linux/jabrefHost.py#L77 the data is passed directly. When there is space in data then it will be parsed as multiple strings. The fix is simple, i.e. change it to `r"'{}'".format(data)`, as posted in https://github.com/NixOS/nixpkgs/pull/162593#issuecomment-1163720204, thanks to @koschtschei.

**Comment by Siedlerchr** [comment]
@linsui Thanks for the feedback! Feel free to create a PR to fix this
