### ISSUE TITLE
Import from Zotero: application/pdf file doesn't have pdf icon

### ISSUE THREAD

**Issue by linsui** [JabRef/jabref#8930]
### JabRef version

5.6 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add a file with application/pdf type
2. The icon is file
3. Change the type to PDF
4. The icon is pdf file.

**Comment by ThiloteE** [comment]
Could you please elaborate? I am not sure how to reproduce. Screenshots are fine too.

**Comment by linsui** [comment]
There are icons for the attached files.

![图片](https://user-images.githubusercontent.com/36977733/176080891-af7a0598-8604-4bd5-9e8f-f5960687b6ed.png)

In fact these files are all PDF and the icons should be

![图片](https://user-images.githubusercontent.com/36977733/176080992-9c16add3-037e-448c-ba6e-4e19efa9ce54.png)

I change the type from application/pdf to PDF in the bibtex.

**Comment by linsui** [comment]
> What version of Linux is this?

NixOS

> What method do you use to attach your pdf to JabRef?

It's exported from Zotero. I can also download a entry with jabref and change the type manully. The result is the same.

> Could you please provide the resulting bibtex entry?

`file = {Full Text PDF:files/187/Norkin 等。 - 2014 - In-Loop Filters in HEVC.pdf:application/pdf},`

**Comment by Siedlerchr** [comment]
Replacing application/pdf with **PDF** after the last colon works. So I guess JabRef does not recognize this when parsing. 
`file = {Full Text PDF:files/187/Norkin 等。 - 2014 - In-Loop Filters in HEVC.pdf:PDF},`

**Comment by linsui** [comment]
Yes, application/pdf is not recognized as PDF.

**Comment by Siedlerchr** [comment]
https://github.com/JabRef/jabref/blob/fd1cab0eb1ed51261049b7799584b060dbe46755/src/main/java/org/jabref/gui/maintable/columns/FileColumn.java#L150

false needs to the changed to true, so that JabRef correctly searches registered external file types base on mime type.
`application/x-latex` or any other mime type defined with an icon in the Preference -> External file types

**Comment by linsui** [comment]
Thanks!
