### ISSUE TITLE
Support APA Legal citation types

### ISSUE THREAD

**Issue by jrmoserbaltimore** [JabRef/jabref#8931]
**Is your suggestion for improvement related to a problem? Please describe.**

The BibLaTeX manual gives a number of "unsupported" styles of specific names, recognized but treated as `@misc`.  Certain styles, particularly biblatex-apa, support these.  In particular, the legal styles such as `jurisdiction` (court cases), `legislation`, etc.

Of particular note is the [style example for jurisdiction](https://github.com/plk/biblatex-apa/blob/master/bibtex/bib/biblatex-apa-test-references.bib#L2541-L2550) provided by biblatex-apa:

```
@JURISDICTION{11.4:5,
  TITLE                = {Durflinger v. Artiles},
  CITATION             = {563 F.Supp. 332 and aff'd and 727 F.2d 888},
  CITATION+an:citeorg  = {1="D. Kan.";3="10th Cir."},
  CITATION+an:citedate = {1="1981";3="1984"},
  CITATION+an:citeinfo = {2=appeal},
  URL                  = {https://openjurist.org/727/f2d/888/durflinger-v-artiles},
  DATE                 = {1984},
  ORIGDATE             = {1981}
}
```

These include *annotation* fields, `CITATION+an:...`

**Describe the solution you'd like**

Inclusion of style types for these such styles BibLaTeX treats as `@misc`, complete with the additional annotations, preferably under the `Annotation` tab.

It would be a larger change to also include automatic citation, for example `Legislation` based on State and code reference or bill references, or Court cases based on jurisdiction and case number, etc., as this would entail pulling information from many, *many* sources, all with different presentation.  The scope of this issue is merely providing the style type for selection by the user, who will fill in the details on their own, and excludes any such automated reference generation.

**Comment by ThiloteE** [comment]
I am happy to tell you what you imagine may not be the default view of JabRef, but most of it can already be achieved with a customized configuration of current JabRef (v. 5.6)!

1. **How to do and what is currently already possible:**

   Customize entry types via `options > customize entry types`
   ![grafik](https://user-images.githubusercontent.com/73715071/176011874-d36cf9fc-c201-4377-a51a-9197dcc3e151.png)
   
   Example bib-file:
   ```
   @Jurisdiction-test{testkey,
    citation             = {b},
    citation+an:citedate = {2022},
    citation+an:citeinfo = {e},
    citation+an:citeorg  = {c},
    date                 = {2022},
    origdate             = {2000},
    title                = {a},
    url                  = {f},
    }
   ```
   
   What you get is:
   
   
   ![grafik](https://user-images.githubusercontent.com/73715071/176013734-322481fe-4bc1-4062-b85a-6ee0f984121e.png)

**2. What is lacking:**

   - I tried to attach fields to the `Annotation` tab via `options > preferences > custom editor tabs`,
      (like this:)
      ![grafik](https://user-images.githubusercontent.com/73715071/176015437-d55d5398-d6b7-48c5-b96a-ed2fa6d34176.png)
    - but first of all, `CITATION+an:citeorg` leads to an error when trying to save the preferences. It looks like JabRef cannot detect this syntax. Maybe the `+` or the `:` are special symbols.
    ![grafik](https://user-images.githubusercontent.com/73715071/176015658-5c4b8c29-d32b-44b7-8306-5ed0d5398f89.png)
    - Secondly, it looks like the Annotation tab only shows up if there are actual annotations (e.g. annotations in your linked PDF file). This would need to be changed if sticking "entry type annotations" to "PDF annotations", but since this depends on the definition of what "annotations" actually are, the workaround here could be to add these fields under "comments" meanwhile. Well, obviously this workaround only works, if the problem with the error is solved.

**Comment by ThiloteE** [comment]
Another easy workaround would be to put
  ```
  CITATION+an:citeorg
  CITATION+an:citedate
  CITATION+an:citeinfo
  ```
  into the `optional` fields tab.

**Comment by Siedlerchr** [comment]
We added support for the biblatex-sotware package, so I think it should be okay to add some legal stuff as well

**Comment by Siedlerchr** [comment]
@jrmoserbaltimore  We added the new entry types with their corresponding fields, you can try it out in the latest development version https://builds.jabref.org/main/
If you think some fields need to be changed (e..g to required or optional) it would be nice please feel free to open an issue. It was not that clear from the biblatex doc
