### ISSUE TITLE
New entry: not always added to the selected group

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8933]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-06-27--586d3e4 Linux 4.19.0-20-amd64 amd64  Java 18.0.1  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

With a group selected:
- when an new entry is created by pasting a DOI in the entry editor, this new entry is added to the group.
- when an new entry is created by clicking on the new entry icon, this new entry is NOT added to the group. 
- 
This is inconsistent. Since the user decided to select a specific group beforehand, I believe the entry should be added to the group in all cases.

To reproduce these 2 behaviors;
1. Open a library with groups (such as https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib)
2. Select one group
3. Paste a DOI (such as `10.1016/j.jmsy.2021.09.011`)  in the entry editor
==> The entry is added to the selected group
4. Click on the `New article` icon
5. Fill the fields
6. Close the entry editor
==> The entry is not added to the group

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Finally, after two years, this is now fixed  https://builds.jabref.org/pull/11271/merge 
Took a bit longer than usual 😅😳
