### ISSUE TITLE
Jabref did not show any entry and contents

### ISSUE THREAD

**Issue by elonewei** [JabRef/jabref#8956]
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When I update the Jab from 4 to 5, the whole entry is disappear as the following link or picture.

I have re-install many times even try to back up to the version 4. 

The same issues is still occurred.

Please help me to solve the terrible errors....

Thanks a lot.

Allen 

https://imgur.com/a/oP2Bey

![jab-error](https://user-images.githubusercontent.com/57336815/177466047-b84fbf65-d6a6-4e84-9aa8-eb32a40d8bb5.png)
7

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Thanks for the screenshot. It seems as if your columns in the entry table are unexpectedly expanded to a large degree. You also seem to have a very small screen, therefore some columns (with useful data) may not show

You could decrease the size of columns on the screen manually
![grafik](https://user-images.githubusercontent.com/73715071/177511796-b2413186-42a0-49c0-8023-35d393900ef6.png)

Alternatively you could enable `Options > Preferences > Entry Table > Fit table horizontally on screen`.
See here:
![grafik](https://user-images.githubusercontent.com/73715071/177512373-cb2e5c34-71c3-4d22-8461-6f0e4ba88591.png)

**Comment by HoussemNasri** [comment]
- Similar to #8872

**Comment by ThiloteE** [comment]
closing this, as there has been no further feedback.
