### ISSUE TITLE
Activating a special field should not unselect an entry

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#8958]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-07-04--438ec5a Linux 4.19.0-21-amd64 amd64  Java 18.0.1  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

After performing a search, selecting an entry and modifying the status of a special field (relevance, printed, etc.) has the unwanted consequence of unselecting the entry. This does not occur if search is not active.

1. Open a library (such as https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib)
2. In the search field, type in "Alver".
3. In the entry editor, select an entry (i.e. do a single left click on it)
4. In the entry editor, click on the "Relevance" icon (or the "Printed" icon)
==> The entry becomes unselected.

Note 1: if you click again on the icon, you can quickly see the entry being selected and then unselected.
Note 2: if you do the same without performing the search, it works as expected (the special field is set and the entry is not unselected).

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Where exactly do I to click on Relevance or printed? I tried to reproduce, but I don't see a symbol to click.

![grafik](https://user-images.githubusercontent.com/73715071/178033331-c5116790-8b10-49f9-ba18-53efa0c27d12.png)

**Comment by mlep** [comment]
I forgot that the Relevance and Printed columns are not displayed by default.
You have to add them to the entry table in Options -> Preferences -> Entry table.

**Comment by mlep** [comment]
Sorry for the very long delay. Indeed, I cannot reproduce this issue (JabRef 6.0--2024-11-05--4705977).
Closing!
