### ISSUE TITLE
NullPointerException error when exporting

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#896]
Jabref 3.2, running on Linux Mint + Cinnamon 17.3.

    $java -version
    java version "9-ea"
    Java(TM) SE Runtime Environment (build 9-ea+102-2016-01-21-001533.javare.4316.nc)
    Java HotSpot(TM) 64-Bit Server VM (build 9-ea+102-2016-01-21-001533.javare.4316.nc, mixed mode)

When I try to Export my 3000 entry database from the main File menu, using the "HTML Table (with Abstract and bibtex)" export filter, I get a java NullPointerException error and the export doesn't take place. console).
![screenshot from 2016-02-29 23 34 42](https://cloud.githubusercontent.com/assets/762246/13419663/26982432-df3d-11e5-85fd-436e9eca8d10.png)

**Comment by matthiasgeiger** [comment]
Could you please paste the more detailed report from the error console (Help -> Show error console)

Thank you!

**Comment by Siedlerchr** [comment]
I can't reproduce that with the actual dev version from today. I tested with around 186 Entries, export works fine.
Win 7, Java 1.8.0.72.
@wujastyk  I see you use Java 9. Does this also happen with Java 8, and second, does this Exception also  happen when you only try to export only a few entries?

**Comment by wujastyk** [comment]
Now I can't reproduce the error either.  Java 9, JabRef 3.2
