### ISSUE TITLE
Manage fieldnames and content regression

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#8970]
Follow up issue to https://github.com/JabRef/jabref/commit/9701e35bb6c271ae64d1baebcbf79488928867ae that reworked the "Manage field names and content" dialogue and introduced the "Automatic field editor" dialogue instead.

-----------

Hey, just tried this. Overall I like it! I think I already found a bug though T.T

How to reproduce:

1. Add two entries

```
@Article{x1,
  a = {1},
  b = {2},
}
```

```
@Article{x2,
  b = {3},
}
```

2. Select both entries
3. Go to `two fields` tab
4. From `a`, To `b`; Enable `Overwrite non empty fields`; Press `copy value`

**Result:**

```
@Article{x1,
  a = {1},
  b = {1},
}
```

```
@Article{x2,
}
```

**Expected:**

```
@Article{x1,
  a = {1},
  b = {1},
}
```

```
@Article{x2,
  b = {3},
}
```

_Originally posted by @ThiloteE in https://github.com/JabRef/jabref/issues/8892#issuecomment-1163539191_

**Comment by Siedlerchr** [comment]
@HoussemNasri  can you please take a look?

**Comment by HoussemNasri** [comment]
I almost forgot about it; I'll make a follow-up pr very soon.
