### ISSUE TITLE
BibteXML syntax

### ISSUE THREAD

**Issue by zellerdev** [JabRef/jabref#898]
The BibteXMLImporter only accepts xml files where tags have a syntax like `<bibtex:author>`. Otherwise JabRef does not read the data or even the file. Shouldn't it be possible to read files with normal syntax?
I created a few tests for this Importer. Two tests of them are ignored, because otherwise circleci would return an error.

Refs #511

**Comment by koppor** [comment]
The BibTeXML parser is implemented in a wrong way. [BibTeXML](http://bibtexml.sourceforge.net/) is a DTD document. XML is namespace aware. Therefore, the document should be parsed namespace aware.

Proposal: Rewrite the whole BibTeXML parser using `javax.xml.parsers.DocumentBuilderFactory`.

**Comment by koppor** [comment]
Update: Schemas are available at https://github.com/Zearin/BibTeXML/tree/master/bibtexml/schema.I would propose to build on the XML Schema

**Comment by tschechlovdev** [comment]
I would like to take care of this issue. But  in my opinion a JAXB parser would be easier than just using a DOM parser. Would this be also ok?

**Comment by Siedlerchr** [comment]
JAXB sounds like a good idea. Mabye you can reuse some of your code.

**Comment by tschechlovdev** [comment]
#1666 is merged, so I think this can be closed.
