### ISSUE TITLE
Libreoffice connection keeps "autodetecting paths" with no success

### ISSUE THREAD

**Issue by inquil** [JabRef/jabref#9001]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

suse tumbleweed

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open Jabref
2. View OpenOffice
3. Connect
4. It keeps looking for "Autodetecting paths"

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```
com.sun.star.comp.helper.BootstrapException
	at org.jabref@5.7.113/org.jabref.gui.openoffice.Bootstrap.bootstrap(Unknown Source)
	at org.jabref@5.7.113/org.jabref.gui.openoffice.Bootstrap.bootstrap(Unknown Source)
	at org.jabref@5.7.113/org.jabref.gui.openoffice.OOBibBaseConnect.simpleBootstrap(Unknown Source)
	at org.jabref@5.7.113/org.jabref.gui.openoffice.OOBibBaseConnect.<init>(Unknown Source)
	at org.jabref@5.7.113/org.jabref.gui.openoffice.OOBibBase.<init>(Unknown Source)
	at org.jabref@5.7.113/org.jabref.gui.openoffice.OpenOfficePanel.createBibBase(Unknown Source)
	at org.jabref@5.7.113/org.jabref.gui.openoffice.OpenOfficePanel$2.call(Unknown Source)
	at org.jabref@5.7.113/org.jabref.gui.openoffice.OpenOfficePanel$2.call(Unknown Source)
	at org.jabref.merged.module@5.7.113/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

</details>

**Comment by inquil** [comment]
same for openoffice, although connect button opens openoffice directly, afterwards the "autodetecting paths..." keeps open with no success

**Comment by Siedlerchr** [comment]
Both JabRef and LO need to  be installed as deb/rpm, via snap or flatpak does not work. Can you please verfiy this?

**Comment by inquil** [comment]
![image](https://user-images.githubusercontent.com/106501/181634942-483d5f26-4bcd-4704-85a1-91e2e8ad8cb5.png)



> Both JabRef and LO need to be installed as deb/rpm, via snap or flatpak does not work. Can you please verfiy this?

yes, no snap or flatpak. Just rpms

**Comment by Siedlerchr** [comment]
I just have to Linux here at hand, tested with JabRef and LO on mac and that works. 
Maybe @ThiloteE  can check that on Linux 

```
JabRef 5.7--2022-07-26--36c64dc
Mac OS X 11.6.6 x86_64 
Java 18.0.1 
JavaFX 18.0.1+2 

and LO:
Version: 7.3.4.2 / LibreOffice Community
Build ID: 728fec16bd5f605073805c3c9e7c4212a0120dc5
CPU threads: 12; OS: Mac OS X 11.6.6; UI render: default; VCL: osx
Locale: de-DE (de_DE.UTF-8); UI: en-US
Calc: threaded
```

**Comment by inquil** [comment]
same with the latest build

JabRef 5.7--2022-07-26--36c64dc
Linux 5.18.11-1-default amd64 
Java 18.0.2 
JavaFX 18.0.1+2

**Comment by ThiloteE** [comment]
Was not able to reproduce the error on

JabRef 5.7--2022-06-15--cb5fe60
Linux 5.4.0-122-generic amd64 (Linux Mint, Cinnamon)
Java 18.0.1 
JavaFX *unknown*

Version: 7.3.5.2 / LibreOffice Community
Build ID: 184fe81b8c8c30d8b5082578aee2fed2ea847c01
CPU threads: 4; OS: Linux 5.4; UI render: default; VCL: gtk3
Locale: de-DE (de_DE.UTF-8); UI: en-US
Calc: threaded

Both JabRef and LibreOffice were installed via deb.

**Comment by ThiloteE** [comment]
You might need to manually select the path libreoffice was installed to. In particular, JabRef requires to know the location of the file `soffice`, according to the documentation https://docs.jabref.org/cite/openofficeintegration

Additional info: Check if LibreOffice was installed correctly. In the readme file, I found the following:

```
Installation of LibreOffice on Fedora, openSUSE, Mandriva and other Linux systems using RPM packages
----------------------------------------------------------------------

For instructions on how to install a language pack (after having installed the US English version of LibreOffice), please read the section below entitled Installing a Language Pack.

When you unpack the downloaded archive, you will see that the contents have been decompressed into a sub-directory. Open a file manager window, and change directory to the one starting with "LibreOffice_", followed by the version number and some platform information.

This directory contains a subdirectory called "RPMS". Change directory to the "RPMS" directory.

Right-click within the directory and choose "Open in Terminal". A terminal window will open. From the command line of the terminal window, enter the following command (you will be prompted to enter your root user's password before the command will execute):

For Fedora-based systems: sudo dnf install *.rpm

For Mandriva-based systems: sudo urpmi *.rpm

For other RPM-based systems (openSUSE, etc.): rpm -Uvh *.rpm

The installation process is now completed, and you should have icons for all the LibreOffice applications in your desktop's Applications/Office menu.

Alternatively, you can use the 'install' script, located in the toplevel directory of this archive to perform an installation as a user. The script will set up LibreOffice to have its own profile for this installation, separated from your normal LibreOffice profile. Note that this will not install the system integration parts such as desktop menu items and desktop MIME type registrations.

Notes Concerning Desktop Integration for Linux Distributions Not Covered in the Above Installation Instructions
----------------------------------------------------------------------

It should be easily possible to install LibreOffice on other Linux distributions not specifically covered in these installation instructions. The main aspect for which differences might be encountered is desktop integration.

The RPMS (or DEBS, respectively) directory also contains a package named libreoffice7.3-freedesktop-menus-7.3.0.1-1.noarch.rpm (or libreoffice7.3-debian-menus_7.3.0.1-1_all.deb, respectively, or similar). This is a package for all Linux distributions that support the Freedesktop.org specifications/recommendations (https://en.wikipedia.org/wiki/Freedesktop.org), and is provided for installation on other Linux distributions not covered in the aforementioned instructions.
```

**Comment by Siedlerchr** [comment]
Maybe you also need to install the java support? In Ubuntu/debian it's a separate package

**Comment by inquil** [comment]
> You might need to manually select the path libreoffice was installed to. In particular, JabRef requires to know the location of the file `soffice`, according to the documentation https://docs.jabref.org/cite/openofficeintegration
> 
> Additional info: Check if LibreOffice was installed correctly. In the readme file, I found the following:
> 
> ```
> Installation of LibreOffice on Fedora, openSUSE, Mandriva and other Linux systems using RPM packages
> ----------------------------------------------------------------------
> 
> For instructions on how to install a language pack (after having installed the US English version of LibreOffice), please read the section below entitled Installing a Language Pack.
> 
> When you unpack the downloaded archive, you will see that the contents have been decompressed into a sub-directory. Open a file manager window, and change directory to the one starting with "LibreOffice_", followed by the version number and some platform information.
> 
> This directory contains a subdirectory called "RPMS". Change directory to the "RPMS" directory.
> 
> Right-click within the directory and choose "Open in Terminal". A terminal window will open. From the command line of the terminal window, enter the following command (you will be prompted to enter your root user's password before the command will execute):
> 
> For Fedora-based systems: sudo dnf install *.rpm
> 
> For Mandriva-based systems: sudo urpmi *.rpm
> 
> For other RPM-based systems (openSUSE, etc.): rpm -Uvh *.rpm
> 
> The installation process is now completed, and you should have icons for all the LibreOffice applications in your desktop's Applications/Office menu.
> 
> Alternatively, you can use the 'install' script, located in the toplevel directory of this archive to perform an installation as a user. The script will set up LibreOffice to have its own profile for this installation, separated from your normal LibreOffice profile. Note that this will not install the system integration parts such as desktop menu items and desktop MIME type registrations.
> 
> Notes Concerning Desktop Integration for Linux Distributions Not Covered in the Above Installation Instructions
> ----------------------------------------------------------------------
> 
> It should be easily possible to install LibreOffice on other Linux distributions not specifically covered in these installation instructions. The main aspect for which differences might be encountered is desktop integration.
> 
> The RPMS (or DEBS, respectively) directory also contains a package named libreoffice7.3-freedesktop-menus-7.3.0.1-1.noarch.rpm (or libreoffice7.3-debian-menus_7.3.0.1-1_all.deb, respectively, or similar). This is a package for all Linux distributions that support the Freedesktop.org specifications/recommendations (https://en.wikipedia.org/wiki/Freedesktop.org), and is provided for installation on other Linux distributions not covered in the aforementioned instructions.
> ```

Done, when pointing out to other directory, it complains. When pointing out to the soffice binary, it keeps "Autodetecting paths.. " window running until it fails

**Comment by Siedlerchr** [comment]
@inquil  Can you please test this version? https://builds.jabref.org/pull/9002/merge/
I added some more error logging. Can you please also try to reset your preferences?

**Comment by inquil** [comment]
> @inquil Can you please test this version? https://builds.jabref.org/pull/9002/merge/ I added some more error logging. Can you please also try to reset your preferences?

Hi @Siedlerchr , thank for your time on this:
a) I installed the referred version
a) To reset the preferences, I executed on the command line 
`/opt/jabref/bin/JabRef -d all -n` 
b) An this is the result of the output with --debug
`com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused
	at org.libreoffice.uno/com.sun.star.lib.connections.socket.socketConnector.connect(Unknown Source)
	at org.libreoffice.uno/com.sun.star.comp.connections.Connector.connect(Unknown Source)
	at org.libreoffice.uno/com.sun.star.comp.urlresolver.UrlResolver$_UrlResolver.resolve(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.Bootstrap.bootstrap(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.Bootstrap.bootstrap(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.OOBibBaseConnect.simpleBootstrap(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.OOBibBaseConnect.<init>(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.OOBibBase.<init>(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.OpenOfficePanel.createBibBase(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.OpenOfficePanel$2.call(Unknown Source)
	at org.jabref@5.7.30174/org.jabref.gui.openoffice.OpenOfficePanel$2.call(Unknown Source)
	at org.jabref.merged.module@5.7.30174/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	... 18 more
`

**Comment by inquil** [comment]
Hi,

I have tried several jabref with several LibreOffice versions with no avail. I decided to reinstall the SO and now it works. It would have been some weird local configuration of LO that wrecked havoc. Now latestd developmental version works fine with the default LO of my reinstalled OS. Thanks for your prompt and kind support.

**Comment by Siedlerchr** [comment]
Thanks for the update. Yeah, maybe one LO was interfering with another. From the error message it seems that it could not resolve localhost correctly... (JabRef tries to connect to LO through a socket)
