### ISSUE TITLE
Automatic field editor: 3 sentences not translated

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9014]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-08-02--baae43b Linux 4.19.0-21-amd64 amd64  Java 18.0.2  JavaFX 18.0.1+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

In the new window "Automatic field editor" (in the menu Edit) , 3 strings cannot be translated at the moment:
- The button ``Keep modifications``
- In the tab ``Copy or move content``, the words ``From`` and ``To``

BTW: great feature!

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Refs https://github.com/koppor/jabref/issues/593
