### ISSUE TITLE
Preferences window cannot 'outgrow' horizontal scrollbar

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#9017]
### JabRef version

Other (please describe below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.7--2022-08-02--baae43b Windows 10 10.0 amd64  Java 18.0.2  JavaFX 18.0.1+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open preferences
2. Navigate to `Import and Export` or to `Citation key generator`
3. Resize window (wider) or left navigation pane (narrower) wider than the preferences content
4. Notice that the horizontal scroll bar always appears because of expanding text controls.
5. Notice that the right side of some content and controls is cut off (regardless of window size) unless the scroll bar is repositioned
<img width="513" alt="JabRef_lrfBF3mFV6" src="https://user-images.githubusercontent.com/23321102/182543335-c1ac5a70-cf67-402d-8f1b-b069ef4a9ee1.png">

**Comment by qingyacanxue** [comment]
Hello, can you assign this issue to me? This may be relative to the javafx funciton wrappingWidthProperty() and ScrollPane property, which I have a little experience.

**Comment by ThiloteE** [comment]
Will do :-) Thank you for trying to fix this.

As a general advise: Check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth having a look at. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

**Comment by qingyacanxue** [comment]
Hello, I tried to fix the bug, and here are some figures with the screen shots of the layout changes. I only changed the src\main\java\org\jabref\gui\preferences\importexprot\ImportExportTab.fxml file.

1.	For the text, I added warping.
2.	For the horizontal scroll bar, I removed all the HBox.hgrow="ALWAYS", but when dragging to the rightmost, it is still existing.
3.	I changed the textfield prewith from 200 to 400.
Does my change meet the requirements, please contact me if you have other requirements?

Rightmost figure 
![image](https://user-images.githubusercontent.com/57479442/194790397-05ce461c-fda0-47c9-b900-78156b6a743c.png)
200 to 400 prewidth figure
![image](https://user-images.githubusercontent.com/57479442/194790411-aff6aea9-2c4c-43a1-85b6-97a664403e7c.png)
Text warping figure
![image](https://user-images.githubusercontent.com/57479442/194790429-0b00de17-93f3-4519-bbc6-fe3f9be6c04a.png)
