### ISSUE TITLE
"Generate citation keys" generates one, not many

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#9018]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.7--2022-08-02--baae43b Windows 10 10.0 amd64  Java 18.0.2  JavaFX 18.0.1+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select multiple references
2. Click `Generate citation keys` (the key icon or in the `Edit` menu)
3. Toast message shows "Generating citation keys for n entries", where _n_ matches the number of entries selected
4. A citation key is generated for only the first of _n_ entries, leaving the rest with no citation key

**Comment by ThiloteE** [comment]
I cannot reproduce. All works fine, but I am on Linux Mint right now.

**Comment by ThiloteE** [comment]
Could you please post your set preferences related to citationkey generation?

![grafik](https://user-images.githubusercontent.com/73715071/184508637-0d5c25b8-1066-4175-a5ac-a09727b409e8.png)

Maybe the entries already have a key and you have set the preference to NOT overwrite existing keys?

**Comment by ryan-carpenter** [comment]
If this was a JabRef issue, I can't reproduce it now (in version 5.8), so let's call it 'solved'. My preferences are all default I think (`Overwrite`, `Warn` and `Start on second … with A` are TRUE). I tested previously by deleting keys, creating a new file, restarting JabRef.
