### ISSUE TITLE
Groups collected by free search expression should remember options

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#9049]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.8-PullRequest9043.27--2022-08-11--109fd06 Windows 10 10.0 amd64  Java 18.0.2  JavaFX 18.0.2+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add group, choosing free search expression
2. Select `Case sensitive`, `Regular expression`, or both
3. Click OK to save.
4. Notice that the saved group has applied the selection options as expected.
5. Edit the group
6. Notice that both boxes are now cleared and need to be reapplied before saving the group again.
8. Repeat the process searching for a keyword rather than using a free search expression.
9. Notice that the two boxes in the keyword search group retain whichever state was previously saved.

Expected result: the `Case sensitive` and/or `Regular expression` options should always retain their previously saved state when a group is edited, regardless of the group's `Collect by` setting.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by u7283219** [comment]
Hey, I am a student and a new contributor to the project, can I be assigned this issue? I have set up the project, read the project documentation and contribution statements. Could you please give me some instructions and point me in the direction of where to find the classes (or folders) concerned with the problem and where the "Case sensitive, Regular expression" group settings are currently processed.

Thanks.

**Comment by ThiloteE** [comment]
You are welcome :-)

If you have your [local workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) set up, then feel free to work on this.

**Comment by ThiloteE** [comment]
@calixtus, I think you know a lot about preferences. Do you maybe have a idea how this could be tackled and where the code lives?

**Comment by calixtus** [comment]
This is not about the prefs but the groups. Try looking into the gui.groups package. Issue seems without further investigation to have something to do with the dialog not setting the search options on creation.

Be aware that there are coming heavy changes to the search engine and on how Regen or case sensitivity is handled in the next week's, since we are moving from the internal JavaFX table filters to Lucene. So any work done now on this issue may be overwritten. May be just wait with this issue until the dust has settled and look for another issue to fix first. ;-)
