### ISSUE TITLE
Clarify button "Import and keep old entry"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9056]
Refs https://github.com/JabRef/jabref/issues/6190

The button text "Import and keep old entry" does not make it crystal clear, what happens.

My use case:

1. Copy 120 entries (which are no duplicates) from a bib file
2. Paste these entries in a new file
3. The merge entries dialog pops up
4. I want to keep both entries (and not creating a new one)

![grafik](https://user-images.githubusercontent.com/1366654/184515269-78c46f58-f69a-4371-941e-42449eb41778.png)

**Comment by koppor** [comment]
Maybe, the call of the dialog is wrong. Sometimes, it is "Use both entries"

![grafik](https://user-images.githubusercontent.com/1366654/184515490-d6ae2f9d-eb34-42fd-9747-ee28c4be96a8.png)

**Comment by Siedlerchr** [comment]
Comes from pasting:
importHandler#importEntryWithDuplicateCheck -> calls the dialog with IMPORT_CHECK enum value which is not covered in the existing cases in the DuplicateResolverDialog

**Comment by HoussemNasri** [comment]
There are 7 possible actions/strategies, one might choose to fast-merge entries, but in the duplicate resolver dialog, only 4 are provided *('Cancel' and 'Do not import entry' seems to do the same thing)*
- Keep Left
- Keep Right
- Keep Merged
- Keep Left & Right
- Keep Left & Merged
- Keep Right & Merged
- Keep Left & Right & Merged

I don't think we can fit 7 actions on the button bar. Even if we did it will look ugly. I believe that using Controlsfx's [CheckComboBox](https://controlsfx.github.io/features/checkcombobox/) would be a better solution. We add *left*, *right* and *merged* to the ComboBox and users can select whatever combination they like. We can also change *left* and *right* to *Old entry* and *from Import* if entries are imported.

![image](https://user-images.githubusercontent.com/21198231/184541930-fecafd55-8fe7-4a4c-9bcb-25a33c1a4d97.png)

**Comment by koppor** [comment]
I am in favor of:

- Keep Merged (at the beginning, because this should be the best)
- Keep Left
- Keep Right
- Keep Left & Right (this is only necessary, because our duplicate detection is not that good)
