### ISSUE TITLE
When saving: The library has been modified by another program - triggered by adding and removing new group

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#9064]
JabRef 5.6--2022-01-25--2c92eb0
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

JabRef and the library are both on a local system WITHOUT dropbox or other sync or backup software interfering.

I was able to reliably trigger the behaviour like this:

1. Create new group
2. Immediately remove the new group that was just created. Choose `also remove subgroups`.
3. Click on save.

**Result:** There is a popup "The library has been modified by another program."

Most importantly, after the bug triggers once, it does not go away until Jabref was having a restart. So afterwards, every click on save will trigger the popup again, regardless of having deleted a group prior to that or not...

**Expected result:** No popup.

Edit: Not sure if it actually is the same issue as the original post. This is how the modified dialogue looks like:
![image](https://user-images.githubusercontent.com/73715071/151227325-0c0454e5-f024-434c-aaa4-7b427effe001.png)

_Originally posted by @ThiloteE in https://github.com/JabRef/jabref/issues/4877#issuecomment-1022487951_

**Comment by bernhard-kleine** [comment]
JabRef 5.7--2022-08-05--73c111c
Windows 11 10.0 amd64 
Java 18.0.2 
JavaFX 18.0.1+2
I encountered the issus today after adding a single citation via Ctrl-N->Medline/Pubmed to a large library.

**Comment by Siedlerchr** [comment]
I can no longer reproduce the issue in the latest dev version
