### ISSUE TITLE
When prompting for restoring the backup, a diff should be shown

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9066]
As user, one is not sure, what is the "backup" version of the ".bib" file. It could even be possible that the backup failed and JabRef destroys data when restoring from the backup (see https://github.com/JabRef/jabref/issues/9063).

Example popup: 

![grafik](https://user-images.githubusercontent.com/1366654/184962869-779d3603-8adf-4889-9523-240fa4aeaf2c.png)

Thus, it would be nice if the dialog offered a button to show the diff. We should have that functionality at the "file changed on disk" notification.

Refs https://github.com/JabRef/jabref/issues/6190

@HoussemNasri Could you have a look?

**Comment by Siedlerchr** [comment]
There needs to be warning as well:

WARNING: Restore from backup will overwrite your current library

**Comment by koppor** [comment]
The diff should also be shown at "Save before closing":

![grafik](https://user-images.githubusercontent.com/1366654/199312591-3493a77a-7670-48c6-a1ff-adc041806133.png)

I just opened JabRef, changed a preference - and JabRef told me that there is a diff 🙈

**Comment by HoussemNasri** [comment]
I'm curious what preferences change the bib file?

**Comment by koppor** [comment]
> ~I'm curious what preferences change the bib file?~ I see, the citation key patterns are encoded as metadata in the library file.

However, they are "only" stored there if they are changed **locally** for the bib file. These local ones override the global ones (refs https://github.com/JabRef/jabref/issues/8701). Thus, I assume **nothing** should be changed in the bib file if one changes the global preferences.
