### ISSUE TITLE
App hang on exit on macOS

### ISSUE THREAD

**Issue by iandol** [JabRef/jabref#9075]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

JabRef 5.8--2022-08-16--6a71395 Mac OS X 12.5.1 x86_64  Java 18.0.2  JavaFX 18.0.2+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Run JabRef, use LibreOffice panel to connect to a document and run.
2. Try to quit JabRef.
4. Observe that JabRef window closes but the app doesn't exit; needs force quit.

### Appendix

Log file (hang log from Apple crash reporter):

[Hang.log.zip](https://github.com/JabRef/jabref/files/9388110/Hang.log.zip)

**Comment by Siedlerchr** [comment]
Thanks for the report, I could reproduce this. Guess we need to make sure to close the LO connection on closing
But once I closed LO, JabRef exited as well.

**Comment by Siedlerchr** [comment]
Need to investigate https://forum.openoffice.org/en/forum/viewtopic.php?t=29873
