### ISSUE TITLE
LO/OO :  Add LineSpacing and HangingIndent to jstyle files

### ISSUE THREAD

**Issue by Marisano** [JabRef/jabref#908]
This is really a feature request rather than a bug.

Currently there does not appear to be a way to adjust the line spacing or hanging indents of bibliographies from within a jstyle file - one has to go to the word processor itself instead (for example, LibreOffice). However, these are common attributes bibliographic styles need to support to be fully complient. Can this functionality be added to jstyle files and implemented across the JabRef-LibreOffice interface?

I am thinking of there being a couple of attributes added to the CITATION section of jstyle files. Maybe one called, "LineSpacing", and another called, "HangingIndent" (whether in inches or millimeters is fine, as long as its specified somewhere). I have found that when I want to submit a paper, journals have very specific ideas about how they want citations set out. I think it would be nice if this formatting information was present in the jstyle file itself, and enforced from there, rather than having to be manually added to each section that uses a particular jstyle.
- JabRef versions: 2.10b2, 2.11.1, 3.2, and 3.3dev 2016-02-26
- Operating system and version: Ubuntu Linux 14.04
- LibreOffice version: 5.1.1.2
- Steps to produce the "bug"
- Open a document in LibreOffice
- Open JabRef
- Connect to the LibreOffice document
- Make a few citations
- 'Ensure that the bibliography is up-to-date'

Attached is a PDF with the actual example output, followed by the preferred output.
[Example jstyle formatting request.pdf](https://github.com/JabRef/jabref/files/159567/Example.jstyle.formatting.request.pdf)

Thank you!
Marisano

**Comment by oscargus** [comment]
Thanks for posting it here. I did some checking of the code etc and I believe that this is the way to go:

* Define a paragraph format in your LO/OO template, say `Citation format` with the correct hanging indent, line spacing etc
* Define the corresponding paragraph format in your .jstyle file `ReferenceParagraphFormat="Citation format"`

This should work as far as I understand. It also makes more sense as the there are many more related formatting issues that needs to be solved in a journal template.

What I think could be needed from a JabRef perspective is to be able to define if there should be a tab between a reference number and the reference text or not.
```
[1]   Bla
      Bla
...
[10]  Bla
       Bla
```

Also, some more documentation about how to work with OO/LO and JabRef, how to create .jstyle-files, and good practices.

**Comment by Marisano** [comment]
I see you points concerning line spacing, but it does seem to me that the
hanging indent is a property of the citation style itself, and not the
formatting of some page or paragraph. Though some of this may relate to my
lack of proficiency with style in LibreOffice. [For example, I don't see
how one can export paragraph styles - they can be imported, but I haven't
seen how they are imported. If that could be done, it would be simple to
just export the paragraph style with the jstyle file.]

Thanks!
Marisano

PS. Any chance Citation Style Language (CSL Styles) will be supported in
JabRef?

**Comment by teertinker** [comment]
I completely agree with Oscargus

For LibreOffice Styles have a look at:
https://help.libreoffice.org/Writer/Load_Styles

![image](https://cloud.githubusercontent.com/assets/8830305/13568509/e9b968f8-e461-11e5-8b91-247607973e49.png)

-> click on the small triangle

There you can import your paragraph styles from any file. (Thus no exporting needed)

**Comment by Marisano** [comment]
Right, but I'm trying to write a .jstyle that other people can just use. *I*
can set the appropriate property in the .jstyle file, and set up a
corresponding style in LibreOffice (LO) so as to have it applied whenever
the references list is updated, but if I distribute that .jstyle to someone
who doesn't have an LO style file with that name, they'll get this error:

Your style file specifies the paragraph format 'zFL_Ent Reference Style',
which is undefined in your current OpenOffice [sic.] document.
The paragraph format is controlled by the property
'ReferenceParagraphFormat' or 'ReferenceHeaderParagraphFormat' in the style
file.

Because LibreOffice does not export styles, this is even more problematic -
though oddly enough, it does *import* them. Maybe I'll make a blank
document with just the FL_Ent style in it, so any of the 11 authors who
write for *Florida Entomologist* *and* use JabRef will be able to import it
from there, and semi-automatically get the proper formatting applied.
However, even then I think that that would have to be done for every new
document a user would write that they'd want this custom format applied to.
It would amount to a very confusing problem when they would forget to do so.

I know there's no desire to address this issue as I've suggested, but this,
at least, is the kind of problem I am trying to avoid, while still having
the correct formatting applied.

Ciao,
Marisano

PS. Sorry for the delay. I've been working on a paper.

**Comment by teertinker** [comment]
Hello,
I can see some relevance in our statement. Even though I think sharing jstyle files hasn't been very popular in the past so the problem is not widespread, I did experience the error message you describe quite often.

I have a couple of jstyle files for the journals I need. When writing a draft and I want to compile my bibliography the error message is usually raised and i have to import the styles within libre office first.

It would be much better if JabRef could use the "Standard" paragraph format as a fallback mode, or even better, the default values as described in "http://jabref.sourceforge.net/OOPlugin-jabref.php". In this case the bibliography would be compiled with different paragraph styles and the error message could just be changed accordingly.

The big plus would be, that users still get a compiled bibliography and a notification that something was wrong.

Should I open a new issue for that?

**Comment by Marisano** [comment]
Hi,

Yes, I think so. Your proposal sounds quite workable and reasonable.

Thanks!
Marisano
