### ISSUE TITLE
Merge entry interface: unable to read text in dark mode

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9090]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-08-22--a255311 Linux 5.10.0-17-amd64 amd64  Java 18.0.2  JavaFX 18.0.2+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

In the merge window, in mode `Show Diff`, `Unified View`, the new text is displayed in light grey over a flashy green background (when using the dark theme). It is not readable.

![ksnip_20220824-154150](https://user-images.githubusercontent.com/6931104/186433891-3d809232-038b-420b-a322-02a40b5048a8.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
ups. I made a duplicate. Sorry, just saw this now.

**Comment by ThiloteE** [comment]
refs https://github.com/JabRef/jabref/issues/9192
