### ISSUE TITLE
Merge entry interface: view options are not saved

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9091]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Other (please describe below)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

In the merge window, `Plain Text `seems to be the default mode. It can be changed to `Show Diff` (with 2 sub-options). But then, these changes are not remembered: back to `Plain text` when the window is re-opened. Selected display mode should be remembered

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
For implementation: GUIPreferences already contains DiffMode as an enum

**Comment by manu-vaillant-afk** [comment]
Hello, I'd like to make my first contribution, could you please assign it to me ? :D

**Comment by manu-vaillant-afk** [comment]
Hi, so what I need to implement is saving merge preferences when I push"Merges entries" button (in merge entries window), and also pre-select these preferences when I open the "Merge entries" menu ? 
How can I do this properly ? I saw the enum DiffMode in GUIPreferences, but don't sure about how to use it. Is there any other example of saved options in drop down list ?

**Comment by HoussemNasri** [comment]
I wouldn't use the DiffMode enum in GuiPreferences, as the new three-way merge dialog uses a different approach for differences highlighting. Also, once all dialogs are converted to use the three-way merge UI e.g. the pdf metadata merge dialog, the diff mode enum would be obsolete.

You can create a new class/record for storing the configuration. Load the configuration from GuiPreferences in the three-way merge UI constructor and save it back to preferences once the user is done with the UI. There is one complexity, however. The three-way merge UI is being used in multiple dialogs, so it's not obvious when the user is done with the UI and thus when to save the configuration.

The saved configuration will be used in the three-way merge toolbar, for initializing its UI components state, see below.
While working on this please consider, making the three-way merge configuration extensible so we can add more configurations in the future. e.g. left and right headers.

https://github.com/JabRef/jabref/blob/a90b8685a8684a0fb7bceef002acde9eb8d51e25/src/main/java/org/jabref/gui/mergeentries/newmergedialog/toolbar/ThreeWayMergeToolbar.java#L25
