### ISSUE TITLE
Accented i (í) not properly rendered

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9094]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-08-24--f6928d2 Linux 5.10.0-17-amd64 amd64  Java 18.0.2  JavaFX 18.0.2+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef is usually quite good at representing accented characters in both the entry table and the entry preview.
However, for the following entry
> @Article{Martinez,
>   author       = {Carlos Mart{\'{\i}}nez},
> }

the `í` is not displayed properly:
- entry table: ![ksnip_20220826-142446](https://user-images.githubusercontent.com/6931104/186903690-d6b3af6d-cba1-4f0f-ad20-9b6c8a4ae72c.png)
- entry preview: ![ksnip_20220826-142457](https://user-images.githubusercontent.com/6931104/186903663-51a6ed14-6f47-41e9-b070-c0c5c839d4be.png)

Note: For the entry
> @Article{Martinez,
>   author       = {Carlos Martínez},
> }

the `í` is displayed properly, so I guess this is not an issue with the font I use.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Seems to be an issue with the latex escaping, when I use the` í ` and right click -> convert unicode2latex I get: 
`Carlos Mart{\'{i}}nez `

**Comment by Maformatiker** [comment]
Is `{'{\i}}` a correct LaTeX command for the letter í?

**Comment by mlep** [comment]
@svenjaeger @koppor Indeed, my syntax was completely wrong! Where did I get it from?!? The bug was not in JabRef, but in my brain... :face_in_clouds: 

Closing...
