### ISSUE TITLE
Consistent code formatting

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#91]
I renabled the `gradlew format` task in commit f6267c06c77cb6174e4b3800729a48e353da99be. Currently, this task destroys the `LabelPatternUtil` class. Furthermore, braces are not moved up. Maybe we should make the formatter more intrusive and enable `@formatter:off/on` tags for areas which are intended to be kept in separate lines.

**Comment by simonharrer** [comment]
:+1: 

but we should use `@formatter:off/on` as little as possible.

**Comment by stefan-kolb** [comment]
Is this done already? If not we should do a one pass asap and close this issue.

**Comment by koppor** [comment]
`LabelPatternUtil` was not destroyed. Don't know why, but that is good news. Commit is 6890a5d6.
