### ISSUE TITLE
Add cleanup "Remove empty fields"

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#911]
As suggested by [oscargus](https://github.com/JabRef/jabref/pull/877#discussion_r54947965) it would be nice to remove empty fields (only containing whitespace) as a cleanup step.

**Comment by stefan-kolb** [comment]
Discussed with @simonharrer : What about making this the default behaviour of our BibtexWriter? Is there any reasonable case where we want empty fields?

**Comment by tobiasdiez** [comment]
:+1: for "remove by default".

**Comment by stefan-kolb** [comment]
@tobiasdiez This is now done by default and can be closed?!

**Comment by tobiasdiez** [comment]
Apparently, empty fields were always deleted. At least the test added in #974 passed without any further modifications.
