### ISSUE TITLE
Capitalization and hyphen: Anomaly with "Title case" and "Sentence case"

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9112]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-08-31--88d9d83 Linux 5.10.0-17-amd64 amd64  Java 18.0.2.1  JavaFX 18.0.2+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Capitalization of words associated with a hyphen do not work well. 

Anomaly with "Sentence case":
1. In the entry editor, enter the title `wetting-and-drying cycle and others effects` 
2. With a right click, select Change case -> Sentence case
--> The title becomes `Wetting-And-Drying cycle and others effects` while it should be `Wetting-and-drying cycle  and others effects`

Anomaly with "Title case":
1. In the entry editor, enter the title `wetting-and-drying cycle and others effects` 
2. With a right click, select Change case -> Title case
--> The title becomes `Wetting-And-Drying Cycle and Others Effects` while it should be `Wetting-and-Drying Cycle and Others Effects` 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by mlep** [comment]
- For "Sentence case", only the first letter of the whole string should be capitalized (expect for parts enclosed in {} which should not be altered)
- For "Title case", words like "and" ("for", "of", etc.) should not be capitalized even if they come after an hyphen

**Comment by mlep** [comment]
@MorettiGS: in case you want to improve capitalization

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by mlep** [comment]
Hello @sreenath-tm. Thank you for your interest into JabRef. You should look first at https://github.com/JabRef/jabref/blob/main/docs/contributing.md
Can you reproduce the issue?

**Comment by sreenath-tm** [comment]
Hi I have validated the same for both the Title case and Sentence Case for the given input and the respective outputs for both of them are added below
Title case : "Wetting-and-drying Cycle and Others Effects"
Sentence Case : Wetting-and-drying cycle and others effects

As per this result only the Title case needs a tweaking to capitalise the "Drying" part and no changes need to be done to the Sentence casing which is working as expected. Do you agree ?

**Comment by mlep** [comment]
Which version of JabRef have you been using for test?
With the current development version (https://builds.jabref.org/main/), I still get "Wetting-And-Drying cycle and others effects" after applying "Sentence case". This could be a side-effect of https://github.com/JabRef/jabref/pull/9102

I have not checked for the other types of field. But I guess the routines are applied in the same way to all fields. So, it would make sense the result does not depend on field type.

**Comment by sreenath-tm** [comment]
Sorry I was trying with the 5.7 version.
Validated the issue and as mentioned both Title and Sentence cases have an issue. Because it is non-existent in the previous I also strongly believe this has been introduced by #9102.
Validated the same for other fields also and as you said this issue applies for it as they share the same routines.

Just to reconfirm how the ideal case conversion should look like please confirm if below mentioned examples are correct


_Title case : "Wetting-and-Drying Cycle and Others Effects"
Sentence Case : Wetting-and-drying cycle and others effects_


I am looking into the issue will raise the PR once I am ready with the fix.

**Comment by mlep** [comment]
> Just to reconfirm how the ideal case conversion should look like please confirm if below mentioned examples are correct
> 
> _Title case : Wetting-and-Drying Cycle and Others Effects_
> _Sentence Case : Wetting-and-drying cycle and others effects_

Indeed, this is how they should look!

**Comment by mlep** [comment]
Thank you @sreenath-tm for solving this issue. Thanks to your contribution, it works as expected now.

Playing around, I have found another anomaly: 
The menu "Change case -> Capitalize" converts 
    `wetting-and-drying cycle and others effects`
into 
    `Wetting-and-drying Cycle And Others Effects`
instead of
    `Wetting-And-Drying Cycle And Others Effects`
