### ISSUE TITLE
File field in General Tab of entry editor not adhering to dark theme

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#9119]
Newest Development version (5.8, Linux Mint (Cinnamon)) as of from just now:

![grafik](https://user-images.githubusercontent.com/73715071/188172866-6e8b196f-54a2-400d-b7b4-64ebdc787656.png)

Refs https://github.com/JabRef/jabref/pull/9114

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by Siedlerchr** [comment]
@sreenath-tm  Welcome to JabRef. First step would be to look into https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.html

For some information on Themes:
https://docs.jabref.org/advanced/custom-themes 
Basically, the Dark.css inherits from the Light.css and overwrites the color. So you need to set a different color for this textfield /highlight

**Comment by John-Poulos** [comment]
I too am interested and started yesterday to get my environment setup, thank you for the guide! I am having an error that I haven't found a workaround to yet. @sreenath-tm - would you care to collaborate? I have to complete this for a school assignment.

**Comment by Siedlerchr** [comment]
@John-Poulos that issue has been fixed now, you may need to update/sync your fork

**Comment by NamanHimmatramka** [comment]
I'm looking to contribute, can you assign this issue to me, please?

**Comment by ThiloteE** [comment]
Usually I would say first come, first served, but since both @John-Poulos and @sreenath-tm seem to not have created a pull-request within the last month, I assume they have given up and will assign this to @NamanHimmatramka

**Comment by ThiloteE** [comment]
closing this issue in favour of #9340, which is a duplicate issue, but well explained.

I assume @NamanHimmatramka has chosen a different project to work on as well.
