### ISSUE TITLE
When changing the type of an entry, the editor does not update

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#914]
JabRef v3.3dev - 2016-03-06 - master - c4fc0cc

When changing the type of an entry (e.g, via right click on the displayed type in the entry editor or via the context meno of the entry), the entry editor does not refresh.

Example screenshot after changing the type from "Article" to "Techreport":

![grabbed_20160306-183758](https://cloud.githubusercontent.com/assets/1366654/13555821/8f293afe-e3ca-11e5-9d64-8823b8b916de.png)

**Comment by zephyrinsoh** [comment]
Hi,
Cannot reproduce this.

**Comment by stefan-kolb** [comment]
Introduced by 51685e85a39cb6dd998e6f4fb994ff2dd15b8fb8.

**Comment by simonharrer** [comment]
Strange that this causes such a GUI issue.

**Comment by stefan-kolb** [comment]
The type of the currently displayed BibEntry is not kept anymore. The commit does not only inlcude refactorings :cry:
