### ISSUE TITLE
Export sort order preference is broken

### ISSUE THREAD

**Issue by pedrogit** [JabRef/jabref#9147]
### JabRef version

5.7 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to Preferences->Import and export
2. Select "Keep original order"
3. Save preferences
4. Go back to Preferences->Import and export
5. "Use current table sort order" is still selected

**Comment by HoussemNasri** [comment]
Refs https://github.com/JabRef/jabref/issues/8198

**Comment by calixtus** [comment]
already solved it, fix incoming
