### ISSUE TITLE
Capitalization and hyphen: Anomaly with "Capitalize"

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9157]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-09-14--6a4a4f4 Linux 5.10.0-18-amd64 amd64  Java 18.0.2.1  JavaFX 18.0.2+2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

This is a follow-up on issue https://github.com/JabRef/jabref/issues/9112 (which was solved by PR https://github.com/JabRef/jabref/pull/9142).

Anomaly with "Capitalize":

1. In the entry editor, enter the title `wetting-and-drying cycle and others effects`
2. With a right click, select "Change case -> Capitalize"
    --> The title is now written as `Wetting-and-drying Cycle And Others Effects` while it should be `Wetting-And-Drying Cycle And Others Effects`

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by dyannya** [comment]
Hello! I am a first-time contributor and would like to attempt on contributing a solution to this issue. May I please guidance on how to approach this? Thank you.

**Comment by calixtus** [comment]
Hello @dyannya. Please read https://devdocs.jabref.org/contributing.html#contribute-code, please don't forget to correctly set up your workspace including Checkstyle, and ask general questions in our Gitter chat, so we can keep the issue discussion clean and related to the issue only.

**Comment by rilmay** [comment]
Hello @mlep , @Siedlerchr  .  As i can see, now program works like this : if you choose "**Change case -> Capitalize**", then only first letter will be capitalized, regardless of dashes, and if you choose "**Change case -> Title Case**", then the first letter and every letter after dashes will be capitalized (exceptions: first letters in conjunctions "and", "but", "for", "nor", "or", "so", "yet"). I think **Title Case** is more suitable action for this situation, and result will be: `Wetting-and-Drying Cycle and Others Effects`. So from my point of view, program works as expected

**Comment by mlep** [comment]
@scarpio02 Thank you for fixing this bug!
