### ISSUE TITLE
ignore unnecessary library modification notifications?

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#9159]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-09-15--853338a Linux 5.19.8-200.fc36.x86_64 amd64  Java 18.0.2.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

change the metadata of the library (within JabRef) and you (at least I) get a library notification message. I do not see how/why this is necessary. Obviously, the metadata changes when I save the library.

### Appendix

...
<details>

[Screencast from 19-09-22 14:51:51.webm](https://user-images.githubusercontent.com/20518297/191021583-75443c86-1cc5-45f2-89d2-f27307bf9b4a.webm)

</details>

**Comment by ThiloteE** [comment]
Do I understand it right, you did not do change the library at all, then pressed "save", which triggered a library modification popup?

**Comment by ThiloteE** [comment]
sorry for the noise. I understand now.

**Comment by ilippert** [comment]
Now with screencast (updated), nothing typed. and then pressed `CTRL+S` and a few moments later the modification claim occurs.

**Comment by Siedlerchr** [comment]
Can confirm this.

**Comment by HoussemNasri** [comment]
@Siedlerchr Wasn't this issue fixed by #9067?

**Comment by Siedlerchr** [comment]
Yes it should have been. I don't know what's wrong with it now.

**Comment by HoussemNasri** [comment]
It appears that *Save actions* and *Library mode* are always detected as changed. I got the same result when I added a new string from the library properties dialog without changing the library mode or the save actions.
