### ISSUE TITLE
Preview out of sync with entry table

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9172]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-09-21--35d995a Linux 5.10.0-18-amd64 amd64  Java 18.0.2.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

From time to time, the entry displayed in the preview does not correspond to the entry selected in the entry table.

1. open the library https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib
2. double-click on one entry of the entry table to open the entry editor. The entry editor contains the entry preview (as a tab or not, depending on the settings). If needed, select the tab "Preview".
3. click on the current entry in the entry table.
4. with the up and down keys, move around the entries
--> from time to time, the preview does not match the selected entry (it matches the previous entry).

I never noticed this issue before. So, it could be due to a recent change.
I could reproduce this behaviour with the preview as a tab or not.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by AEgit** [comment]
As far as I can tell, this issue does not appear in the following version:

JabRef 5.8--2022-09-05--ce08d0d
Windows 10 10.0 amd64 
Java 18.0.2.1 
JavaFX 18.0.2+2

I also wanted to try the latest version, but since https://github.com/JabRef/jabref/issues/9176 still needs to be fixed, I will have to wait for that bugfix until I can test the current JabRef version.

**Comment by mlep** [comment]
I cannot reproduce the bug with JabRef 5.8--2022-09-14--6a4a4f4

**Comment by HoussemNasri** [comment]
The issue stopped showing once I downgraded to JavaFX 18. The [upgrade to JavaFX 19](https://github.com/JabRef/jabref/pull/9155) was done on 2022-09-15, which explains why it was not reproducible on the day before it.

**Comment by ilippert** [comment]
I confirm with
JabRef 5.8--2022-10-03--e48ed0c
Linux 5.19.12-200.fc36.x86_64 amd64 
Java 18.0.2.1 
JavaFX 19+11

**Comment by Siedlerchr** [comment]
@HoussemNasri  Thanks for testing this. Maybe it has something to do with the changes to the observables (in combination with the new map etc stuff) Could be then an issue with our easybind fork

**Comment by HoussemNasri** [comment]
I don't think so. When I tested it, I only changed the version of JavaFX in the gradle file. If the changes in the observables or easybind triggered the issue then downgrading JavaFX shouldn't prevent the issue because the changes are still there. I saw a recent issue in JavaFX TreeView - [TreeView selects wrong item when folder above is modified and opened](https://bugs.openjdk.org/browse/JDK-8293018?jql=text%20~%20%22javafx%20selection%22%20ORDER%20BY%20created%20DESC) - Maybe both TreeView and TableView share the same selection logic? I need to have a deeper look to confirm the cause.

**Comment by Siedlerchr** [comment]
Ah okay, thanks https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-19.md 
There was a fix regarding an IIOBE on the list change listener for tables. Maybe that was the culprit

**Comment by HoussemNasri** [comment]
Thank you; I'll take a look. It's hard to tell whether it's really a JavaFX-related issue. I played around with JabRef for ~5 minutes and was able to trigger it around 5 times while running JavaFX 19 and none while running version 18. It's probably a concurrency problem because it's randomly triggered and I still can't extract deterministic steps for triggering it.

**Comment by koppor** [comment]
DevCall decision: We create an explicit branch with JavaFX 18, ask users for feedback - and see if the issue still appears.

**Comment by Siedlerchr** [comment]
I wil prepare a thing

**Comment by Siedlerchr** [comment]
@mlep Can you try and test this version? I downgraded to javafx18 so we can see if this was introduced there 
  https://builds.jabref.org/pull/9253/merge/

**Comment by mlep** [comment]
The bug is there.

**Comment by koppor** [comment]
Encountered the same issue.

1. After through all entries with the cursor keys, it is faster --> do we have caching enabled?
2. Mostly, the currently selected entry is eventually shown in the preview --> We should show a loading indicator when the preview is starting to get updated. Is this a background process?
3. Once, I saw that there was no final update (step 2)

**Comment by koppor** [comment]
When the entry editor is opened:

- Switching the tab in the entry editor leads to an update of the content.
- Adding an entry from an import does not update the preview

**Comment by wviechtb** [comment]
Just as a follow-up, I have the same problem under:

   JabRef 5.9--2023-01-08--76253f1a7
   Linux 5.15.0-60-generic amd64 
   Java 19.0.1 
   JavaFX 19+11

It seems to me that when JabRef has been running for a while, the problem goes away (some kind of caching issue?).

**Comment by BeCracked** [comment]
Have the same issue with:

JabRef 5.9--ArchLinux--1
Linux 6.1.14-1-lts amd64 
Java 19.0.2 
JavaFX 19+11

**Comment by wujastyk** [comment]
+1
JabRef 5.10--2023-06-11--27a22af
Linux 5.15.0-73-generic amd64 
Java 20.0.1 
JavaFX 20+19

The Preview tab gets stuck displaying a particular entry and doesn't change when one scrolls to different entries.

https://github.com/JabRef/jabref/assets/762246/7f931cca-d692-4460-be51-7bafbf34714e

**Comment by tobiasdiez** [comment]
I can reproduce this very reliably if you show the entry preview next to the entry editor. Then you will also see that the entry editor is updated correctly, but not the preview. In fact, one can sometimes even arrange that one entry is previewed in one tab, while another entry is shown in another tab. So it's almost surely not an issue in JavaFX (at least not related to the main table), and more likely a problem how the update events are consumed to update the preview.

**Comment by koppor** [comment]
Still happens with todays' dev version (`JabRef 5.13--2024-02-05--47bdfc1`)

![image](https://github.com/JabRef/jabref/assets/1366654/0533cf69-e7fd-4669-aead-33f20a377ad7)

**Comment by koppor** [comment]
It has to do something with throttling of events... After writing the report, the view updated. Clicking fastly back and forth, the view does not update. - Heisenbug. - Currently no update.

**Comment by koppor** [comment]
@wujastyk Can you try the version available at https://builds.jabref.org/pull/12165/merge/ (linked from https://github.com/JabRef/jabref/pull/12165).

**Comment by wujastyk** [comment]
> [@wujastyk](https://github.com/wujastyk) Can you try the version available at https://builds.jabref.org/pull/12165/merge/ (linked from [#12165](https://github.com/JabRef/jabref/pull/12165)).

JabRef 6.0-PullRequest12165.6586--2024-11-09--7575ea4
Linux 6.8.0-48-generic amd64 
Java 21.0.5 
JavaFX 23.0.1+4


Tested under linux mint, and it's working fine.
