### ISSUE TITLE
Mods importer should be able to import conference papers with the correct entry type 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9185]
**Is your suggestion for improvement related to a problem? Please describe.**
I recently had to import a reference from the ISCRAM conference. However, they only offer MODS export format and I noticed that my entry got imported as misc.

**Describe the solution you'd like**
I would like to have conference publications imported as proceedings.

**Additional context**
Here is a list of mappings for the field genre:
https://www.loc.gov/standards/valuelist/marcgt.html

The code needs to be adpated at this place :
https://github.com/JabRef/jabref/blob/d3e0f86a6be977aa16204fd611023e2358a556a7/src/main/java/org/jabref/logic/importer/fileformat/ModsImporter.java#L170

**Comment by berry120** [comment]
@Siedlerchr Hey, I'd like to give this one a go - could you assign it to me? Thanks!
