### ISSUE TITLE
Integrate journal abbreviations into JabRef

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#919]
Currently, the repository https://github.com/JabRef/reference-abbreviations contains several abbreviation lists. They should be maintained in JabRef itself and should be loaded automatically on startup.
- [ ] check performance
- [ ] check whether the files are disjunct
- [ ] check that the abbreviations are correct
- [ ] merge https://github.com/JabRef/reference-abbreviations into JabRef's code

**Comment by oscargus** [comment]
As a big fan of using strings for journal abbreviations, I also believe that it would be nice to define strings for the journals, similar to how it already works for the IEEE journals. The potential drawback is that we also must provide a .bib-file with all those strings, in both abbreviated and non-abbreviated form, but it would be quite nice. Also, this might help in showing the correct name in the table, while showing the string in the entry editor.

**Comment by koppor** [comment]
@oscargus, if I understand correctly, you propose to completely drop the abbrevation system and to maintain `bib` files with `@string`s?

**Comment by oscargus** [comment]
From my perspective, yes, but my suggestion was really only to enable it, not dropping it. Using the IEEE-version one toggles between Full Journal Name -> Abbr. J. Name -> #string# and back again. To me that seems like the best option, those who want can use full or abbreviated and I can use strings. :-)

On the other hand with the dual bib-files discussed in other issues and a "complete" list of abbreviations it is less of an issue. The main reason for using strings is to get consistent spelling/naming/abbreviation of journals (and conference proceedings titles).

This also relates to #323

**Comment by lenhard** [comment]
@koppor The journal abrreviation feature is implemented, right? I recall that @tobiasdiez recently improved its performance. So this issue can be closed, right?

And this means that #323 can also be closed, right?

**Comment by koppor** [comment]
[The feature](http://help.jabref.org/en/JournalAbbreviations) is available [since version 2.0b](https://github.com/JabRef/jabref/blob/v2.11.1/CHANGELOG#L1050). My issue is we have **multiple** lists:

1. In the code:

![grafik](https://user-images.githubusercontent.com/1366654/29402879-db9b6c74-8336-11e7-9f8e-1bdcea26c5b2.png)

2. Some other lists at external repository:

https://github.com/JabRef/abbrv.jabref.org

To make the lists more accessible, I proposed to merge these lists into JabRef (fourth bullet point). For that, quality of these lists has to be checked (second and third bullet point).

Regarding the performance, I haven't checked and I am not sure whether we have a JMH test for that.

**Comment by lenhard** [comment]
Alright, thanks for the clarification! 

Performance is sort of a problem, but since we do no longer load the list at boot time it is no longer noticeable. Integrating the lists into JabRef would certainly improve performance.

**Comment by musm** [comment]
I've got my own list of missing abbreviations. Anyway I can add them so that all users have them?

**Comment by koppor** [comment]
@musm add it to https://github.com/JabRef/abbrv.jabref.org/tree/master/journals.

**Comment by koppor** [comment]
Implemented in https://github.com/JabRef/jabref/pull/5749.
