### ISSUE TITLE
JabRef forgets opened libraries

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9190]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.8--2022-09-29--fca9fb9 Linux 5.10.0-18-amd64 amd64  Java 18.0.2.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. open a (pre-existing) library (e.g. https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib)
2. create a new library (e.g. `File -> New library`)
3. edit a bit this new library (e.g. add/paste an entry)
4. close JabRef (e.g. `File -> Quit`)
_At this point, a window entitled "Save before closing" is displayed._
5. select `Discard changes`
_JabRef closes_
6. open JabRef
Bug: No library is displayed, while the pre-existing one (e.g. jabref-authors.bib) should be.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by tomnguye** [comment]
Hi, I'm a new contributor. I would like to try solving this. Could you assign me this issue?

**Comment by ThiloteE** [comment]
hey, you can try of course.

Seeing as you are pretty new to GitHub, I assume you are new to programming. For newcomers we have assigned  issues with the tag "[good first issues](https://github.com/JabRef/jabref/labels/good%20first%20issue)". [Good first issues from Koppor](https://github.com/koppor/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) also count. If you get stuck here, I would suggest to try from there. If you are a student, the "[candidates for university  projects](https://github.com/orgs/JabRef/projects/3)" page also offers some issues of varying difficulty and scope and that have been estimated to be compatible with university courses as well and often bring a larger feature to JabRef.

**Comment by ThiloteE** [comment]
As a general advice: check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth having a look at. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards (but do testing in your local environment). This way, you will likely receive valuable feedback.

**Comment by koppor** [comment]
Formulated differently, the request is some Notepad++ behavior

JabRef should remember all newly, **but unsaved** libraries.

![grafik](https://user-images.githubusercontent.com/1366654/208512733-43f63641-4559-42fb-8f9a-7cf71b5df1ef.png)

**Comment by koppor** [comment]
In JabRef, the unsaved libraries are not restored upon restart

![grafik](https://user-images.githubusercontent.com/1366654/208513294-329f3cc6-7fa9-417d-a12e-bd3298ddcbc6.png)

**Comment by koppor** [comment]
Additionally, JabRef forgets **all** opened libraries:

1. Closing\
  ![grafik](https://user-images.githubusercontent.com/1366654/208513440-69e0c529-44de-4133-9610-4844b89e61b6.png)
2. After restart\
  ![grafik](https://user-images.githubusercontent.com/1366654/208513549-daf7803e-02a3-450b-9366-f79d5fd8a3e4.png)

**Comment by mlep** [comment]
@Siedlerchr I can confirm this issue is fixed.Thank you!
