### ISSUE TITLE
Change dark theme colour of highlighted text in Entry Merge Dialogue

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#9192]
JabRef 5.8--2022-08-22--a255311
Linux 5.4.0-126-generic amd64 
Java 18.0.2 
JavaFX 18.0.2+2

**Problem:**

- text is hard to read
- distinction between red-green is not good for people with [impaired colour vision](https://en.wikipedia.org/wiki/Color_blindness)

![grafik](https://user-images.githubusercontent.com/73715071/193327675-78c73e64-f732-4bac-9f3d-4b1cf62f5994.png)
![grafik](https://user-images.githubusercontent.com/73715071/193331700-62d2ac77-0ef8-4858-8791-c9296ff6592c.png)

**Describe the solution you'd like**

Please use complementary colour schemes for the fix. See here: https://en.wikipedia.org/wiki/Complementary_colors

**Comment by ThiloteE** [comment]
How to reach the Entry Merge dialogue:

1. Have an entry
  ```
  @Article{monster,
  author       = {foo},
  title        = {monster},
  }
  ```
2. Have another entry that is very similar:

  ```
  @Article{monster,
  author       = {foo},
  title        = {monsterchicken},
  }
  ```
  
 Copy and paste them both into your library. Then select both entries and press `CTRL+M` (`Quality > Merge entries`). This will open the Entry Merge Dialogue.

**Comment by dominikaxx** [comment]
Hi, can you assign me this issue?

**Comment by ThiloteE** [comment]
@dominikaxx Thank you for taking an interest :)

As a general recommendation, please have a look at the guidelines for contributing: https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth having a look at.

**Comment by ThiloteE** [comment]
@the-dino-girl, since you are very enthusiastic about JabRef themes, I wanted to make you aware of these issues here. Just so you know. Maybe you find some great looking combination that is both pleasing to the eyes, conservative and close enough to the red / green combination that is traditionally used by github and other programms to denote removal and addition of code and also does not exclude people with colour blindness.
