### ISSUE TITLE
Searching for an entry on the web shouldn't take forever

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#9195]
**Is your suggestion for improvement related to a problem? Please describe.**
When searching an entry using web search and the entry is not found, JabRef would keep displaying *Processing <entry>*.

**Describe the solution you'd like**
There should be a timeout for a search request and after the timeout is passed, JabRef should display a message indicating the query doesn't correspond to any entry.

**Additional context**
![image](https://user-images.githubusercontent.com/21198231/193400321-8c9c9d71-f55e-4795-8a7a-d6cc813cb308.png)

**Comment by dominikaxx** [comment]
Hi, could you assign the issue to me, please?

**Comment by dominikaxx** [comment]
This is my first issue on open-source project, I started by studying the code.  Any ideas how I should start fixing the issue and setting the timeout for a search request?

**Comment by HoussemNasri** [comment]
Hello @dominikaxx. For getting started, I suggest you have a look at *WebSearchPane*, *ImportEntries* and the fetchers code located under `org.jabref.logic.importer.fetcher`.

https://github.com/JabRef/jabref/blob/6dfc2e00b4fc1dd76f4865e81894e2f7b2e50968/src/main/java/org/jabref/gui/importer/fetcher/WebSearchPaneViewModel.java#L136-L139

The problem seems to reside here, as when the fetcher returns an empty list of entries the message property is not updated. It is kept to `Processing <query>` .

https://github.com/JabRef/jabref/blob/6a4a4f4a588a3aee6041a3fe0141908dc3133148/src/main/java/org/jabref/gui/importer/ImportEntriesViewModel.java#L78-L82
