### ISSUE TITLE
Importing references using the JabRef-Browser-Extension starts a new instance of JabRef for each import

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#9196]
### JabRef version

5.7 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Debian 11 with Mate Desktop

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Just import any reference using the `JabRef-Brower-Extension`. In my case, with Firefox.

### Appendix

Whenever importing a reference using the `JabRef-Browser-Extension` (latest version of `JabRef` and extension) another new instance of `JabRef` is opened, independent of whether another instance of `JabRef` is running or not. As a result, every reference import opens an additional instance of `JabRef`, so several instances will run in parallel. Ticking the setting in `Network` -> `Listen for remote operation on port 6050` does not have any effect (Is this setting still in use?) The same happens, when `JabRef` is run from source, then another instance will start from the installed binary version.

<details>

<summary>Log File</summary>

```
nothing relevant found
```

</details>

**Comment by ThiloteE** [comment]
I was able to reproduce this bug on

JabRef 5.8--2022-09-20--7dcdd61 (portable version)
Linux 5.4.0-126-generic amd64 (Mint, Cinnamon)
Java 18.0.2.1 
JavaFX 19+11

**Comment by systemoperator** [comment]
@ThiloteE I also use the portable version. But actually, I have already a running instance of `JabRef` from the source code with IntelliJ IDEA and when I import a reference from the browser, a new (additional) instance of `JabRef` from the portable version get started, instead of using the already running version. By importing another reference, a third instance gets started (so a second instance of the portable version).

**Comment by Siedlerchr** [comment]
@systemoperator  It might be having something to do with the portable version what version is picked up
 https://docs.jabref.org/collect/jabref-browser-extension

**Comment by systemoperator** [comment]
@Siedlerchr I've checked all the docs. Everything looks fine from the configuration.
I think, the main problem is, that I can start several instances of `JabRef` in parallel, which should not be possible, when ticking the setting `Network` -> `Listen for remote operation on port 6050`.

Furthermore, I don't understand, how it is possible with `jabrefHost.py` to send a reference to `JabRef` started from source with an IDE, because there are only a few hard-coded paths but no port number in `jabrefHost.py`.

**Comment by Siedlerchr** [comment]
@systemoperator  Can you please test the latest dev version? We've reworked the starting of JabRef and the checking for another instance

**Comment by systemoperator** [comment]
@Siedlerchr @koppor Unfortunately, the issue still persists as before (using the current `upstream/main` branch): On every import a new instance gets started.

**Comment by koppor** [comment]
Also happens here on Windows and Firefox with today's version.

**Comment by systemoperator** [comment]
I'm using the Firefox Developer edition. This might be the reason for being a bit ahead of time.

**Comment by koppor** [comment]
I am using 106.0.5 of Firefox. Seems that the cause is somewhere else. Need to debug.

**Comment by koppor** [comment]
Works with latest release here on Windows

```
JabRef 5.7--2022-08-05--73c111c
Windows 10 10.0 amd64 
Java 18.0.2 
JavaFX 18.0.1+2
```

**Comment by koppor** [comment]
1. I started from gradle the first instance
2. I clicked on the import button
3. There is a second JabRef launched:\
    ![grafik](https://user-images.githubusercontent.com/1366654/203146526-a306eda9-b3b6-4f2e-8b13-2383a6e48548.png)

**Comment by koppor** [comment]
We checked with todays' devleopment build:

```
JabRef 5.8--2022-11-21--f7ea169
Windows 10 10.0 amd64 
Java 18.0.2.1 
JavaFX 19+11
```

 @systemoperator Could you please check the latest development build at https://builds.jabref.org/main/?

**Comment by systemoperator** [comment]
@koppor First, I started `jabref` from source with the current `upstream/main` branch. It did not work as expected. Then I downloaded https://builds.jabref.org/main/JabRef-5.8-portable_linux.tar.gz and tried it with this build, and it worked. After that, I again started `jabref` from source with the current `upstream/main` branch, and then it worked as well. :)
