### ISSUE TITLE
The Customize entry types dialog has no title

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#9198]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select *Options*
2. Select *Customize entry types*.

### Appendix

![image](https://user-images.githubusercontent.com/21198231/193426514-107878cf-2106-4dd8-891c-f84192913f02.png)
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by TheGor1lla** [comment]
Sounds like a good start to my hacktober journes :) Can you assign me?
