### ISSUE TITLE
Improve language files synchronizer

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#921]
I now had conflicts of the following type for almost all my PRs:
![untitled](https://cloud.githubusercontent.com/assets/5037600/13603791/f7e31d14-e53f-11e5-957f-5a5590831e27.png)

I think this kind of problem can be prevented if the language file always ends with a new line character.

**Comment by simonharrer** [comment]
Hm, we could add checkstyle which allows to define a rule stating that each file has to end with a newline as part of the gradle build.

**Comment by oscargus** [comment]
Yes, that is indeed annoying. Maybe one should also add that flag which is used for the ChangelLog that the exact order(?) of lines is not that important?

**Comment by simonharrer** [comment]
Good idea. We could reuse the union aspect analog to https://github.com/JabRef/jabref/blob/master/.gitattributes for `src/main/resources/i10n/*.properties`.

**Comment by koppor** [comment]
:+1: for `merge=union` and :+1: for checkstyle rule :innocent:

**Comment by stefan-kolb** [comment]
I thought the merge=union stuff did not really work on Github?

**Comment by koppor** [comment]
`merge=union` is not yet supported on GitHub: https://github.com/isaacs/github/issues/487. Nevertheless, it helps manual merging.

**Comment by simonharrer** [comment]
We have the `scripts/remove-git-markers-in-localization-files.rb` which can automatically remove any git markers in the property files. This may solve this issue. It requires ruby to execute.
