### ISSUE TITLE
Toolbar is greyed out when adding a new library and no others were opened before

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9221]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start JabRef 
2. Close any open libraries
3. Close JabRef
4. Start JabRef
5. Create a new empty library
6. Toolbar is greyed out, you cannot enter a new entry

<img width="1432" alt="grafik" src="https://user-images.githubusercontent.com/320228/194588162-88d6cd66-8c8e-4bfc-81d0-8e3e324578fd.png">

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Gairick52** [comment]
@Siedlerchr Hey i am beginner in this project can you suggest me beginner friendly issues to contribute to

**Comment by Siedlerchr** [comment]
You can try to find the cause for this issue or take a look a the good first issues label

**Comment by calixtus** [comment]
Please use the gitter chat or the discussion board for general questions about contributing to jabref.

**Comment by muzhenying** [comment]
same issue here

**Comment by tobiasdiez** [comment]
Related: you also cannot save the empty library, which should be possible
