### ISSUE TITLE
Cleanup entries dialog is partially visible

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#9223]
**Is your suggestion for improvement related to a problem? Please describe.**
When resizing the cleanup entries dialog, some of the content becomes invisible.

**Describe the solution you'd like**
I would like to be able to scroll over the content when it exceeds the window size.

**Additional context**
![abbg](https://user-images.githubusercontent.com/21198231/194708385-52391ccc-9be9-486a-a484-ccd714ecc3f2.PNG)
![gahhj](https://user-images.githubusercontent.com/21198231/194708392-ab17b2d5-3ff6-4438-9b90-a84c5753a6d7.PNG)

**Comment by waterflow80** [comment]
Hi, Could you please give me some instructions on where to find the classes (or folders) concerned with problem.
Thanks.

**Comment by HoussemNasri** [comment]
Hi @waterflow80. You can start by looking into `CleanupDialog` and `CleanupPresetPanel`. They are both located under `org.jabref.gui.cleanup` package name.

**Comment by calixtus** [comment]
I thought I had added a scrollpane to this dialog once...

**Comment by waterflow80** [comment]
Well, I think its a good opportunity for me to start contributing to *JabRef*
