### ISSUE TITLE
Make custom key patterns per db more accessible

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#923]
If you right click the current tab, there is the option "BibTex key patterns" which allows to set custom key patterns for this db (used to generate cite keys).

I think this dialog should be more accessible. For example, add a button in "database properties dialog". Also a better button text would be nice...

(Again one of these moments when you learn about a feature while reading the code...good that JabRef is open-source - this might be the best documentation :smile: )

**Comment by stefan-kolb** [comment]
Yeah, we should generally improve more on the usability side of our product. I think it's a deal breaker for a lot of customers.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version (the dialog can be accessed via Options > Bibtex key pattern). Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
