### ISSUE TITLE
Mac No  more global menu

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9247]
Regression from https://github.com/JabRef/jabref/pull/9217

Executed ./gradllew run 

<img width="1448" alt="grafik" src="https://user-images.githubusercontent.com/320228/195406986-de06e9be-2467-465a-a229-c87684f69b9b.png">

**Comment by Siedlerchr** [comment]
Binary from jabref works

**Comment by Siedlerchr** [comment]
A second thing with the launcher stuff now, the top menu is gone1 
<img width="732" alt="grafik" src="https://user-images.githubusercontent.com/320228/196162963-ade33b93-d75e-4b9d-895b-ed12ec3d2576.png">

**Comment by Siedlerchr** [comment]
my gues is that the toolkit is initalized too late?

**Comment by tobiasdiez** [comment]
I don't see where this is coming from, the structure of the code remained the same:

before: JabRefLauncher.main (entry class) calls JabRefMain.main (extending Application), which calls `launch`
after: Launcher.main (entry class) calls MainApplication.create (extending Application), which calls `launch`

So maybe it works if `create` is renamed to `main`?

**Comment by Siedlerchr** [comment]
I tested it with the reverted PR and there it works fine. But I will try with the main. Maybe also something with the gradle main?

**Comment by Siedlerchr** [comment]
One thing I noticed is that the arguments array is not passed to the launch method. Will test further

**Comment by koppor** [comment]
Should work - checking the notarized version is open.

**Comment by Siedlerchr** [comment]
JabRef 5.7-tags-testmacnotarization.200--2022-10-31--e7c8535
Mac OS X 11.7.1 x86_64 
Java 18.0.2.1 
JavaFX 19+11

Notarized version starts fine.

**Comment by tobiasdiez** [comment]
Thanks for testing!
