### ISSUE TITLE
ISBN fetcher: OttoBib is no longer operational

### ISSUE THREAD

**Issue by TinoJ** [JabRef/jabref#9254]
### JabRef version

Other (please describe below)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

New entry -> ID type ISBN -> type in ISBN -> Generate

ISBN 10: 3629100163/ ISBN 13: 9783629100160

### Appendix

I tried to import several books, but almost none worked, so I checked the manual and then checked the sources. So I noticed that https://www.ottobib.com/ is offline. The other source www.ebook.de had no listing.

I was more lucky using https://portal.dnb.de/opac.htm since I had books in German, but I do not know, if it is worth as a suggestion, because I do not know, if they offer an API. At least it is the central archive for all books in Germany by law. I noticed that www.ebook.de does not find ISBNs from older books, like from 2003 or 2014.

Due to a current project I have frozen software versions on my computer, so I did not check the latest JabRef version, but I checked the bugs (open and all) and did not find a related bug.

![image](https://user-images.githubusercontent.com/18018490/195997557-4a684a6d-34a0-4d0c-ac7b-d38188f7a7bd.png)

**Comment by Siedlerchr** [comment]
Thanks for your report. We added two new alternative ISBN fetchers in the development version. DOAB and https://github.com/JabRef/jabref/pull/9205 doi-to-bibtex-converter.herokuapp.com whic also support ISBN
You can try the latest dev version here https://builds.jabref.org/main/

Remember to make a backup of your library before trying out the new version

**Comment by TinoJ** [comment]
Hi Christoph,
I got my hand on a second computer and tested the version JabRef-5.8-portable_windows.zip. I compared old version and new version with about 10 book entries and the new version worked much better. Sometimes the author was missing or the number of pages, but this is probably a data quality issue with the data provider.
Thanks a lot for the reply and fix! :)
