### ISSUE TITLE
Jabref snap fails to open after update

### ISSUE THREAD

**Issue by RJDan** [JabRef/jabref#9264]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04, Swaywm 17, JabRef   latest/edge:      5.8.168   2022-10-18 (2043)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. try to launch jabref from app launcher or from the terminal
2. The following error is printed in the terminal. With the app launcher, nothing happens.

```
Picked up _JAVA_OPTIONS: -Duser.home=/home/myusername/snap/jabref/2043
Error: Could not find or load main class org.jabref.gui.JabRefLauncher in module org.jabref
```

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by RJDan** [comment]
Jabref was working before I refreshed my snaps so I would guess it is related to the changes in the latest version.

**Comment by Siedlerchr** [comment]
Probably side effect of https://github.com/JabRef/jabref/pull/9217
