### ISSUE TITLE
Auto-linking files with safe character replacements

### ISSUE THREAD

**Issue by paksnuk** [JabRef/jabref#9267]
### JabRef version

5.7 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When using characters in the citation key or publication title that are unsafe for the file system (such as e.g. a colon ":"), the automatic file renaming replaces those characters with an underscore.
However, the auto-linking feature does not seem to respect this behaviour. After automatically renaming a file with an unsafe character and unlinking it, it is not being recognized by the auto-linking feature.
Changing the citation key to the "safe" string by manually replacing the colon with an underscore makes JabRef find the file again.

Auto-linking files didn't work at all for me in the development version, so I couldn't actually reproduce the behaviour there.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Rita-Zhou** [comment]
Hi, I would like to work on this issue, would you mind assign it to me, please? Thanks!

**Comment by Rita-Zhou** [comment]
Hi, thank you so much for assigning this issue to me, I'm currently working on it. I tried all the steps to reproduce the behaviour and got an error message while I trying to rename the file name with a colon ":". Would you mind giving me more details about this issue? Thanks!
<img width="413" alt="image" src="https://user-images.githubusercontent.com/109927532/197997330-f29ac69c-ec52-4b18-897d-c02f0ce7c382.png">

**Comment by paksnuk** [comment]
I'm not sure whether you're referring to me or to the maintainers, but I'm pretty sure that you shouldn't have a colon in the filename in the first place.
I believe the fix should be replacing the illegal characters in the search string for the auto-linking logic with underscores by the same schema that's being used for automatically naming files.
