### ISSUE TITLE
An error should display when you attempt to add to a group that doesn't allow manual addition.

### ISSUE THREAD

**Issue by meatnordrink** [JabRef/jabref#9274]
**Is your suggestion for improvement related to a problem? Please describe.**
I almost stopped using JabRef right off the bat because I couldn't figure out how to add articles to groups. Eventually, after wasting an hour or so, I figured out that I couldn't manually add articles to groups that I created via the "Searching for a Keyword" option. I had read the documentation for groups, but it didn't say anything about this (at least not under a heading that seemed relevant to what I was searching for - nothing like "adding articles to existing groups" or the like. I've submitted a PR to add this to the documentation).

**Describe the solution you'd like**
It would be great if there was an error message displayed if you attempted to add to a group that didn't allow manual addition, which told you that you needed to change the group type if you wanted to manually add articles (and perhaps warned of the trade-offs). I think this would save other new users time, and prevent frustration and early abandonment of JabRef.

**Additional context**
Wonderful software, thank you. I'll definitely be sponsoring.

**Comment by ThiloteE** [comment]
Closing this.

There ARE docs that explain how it is done. Maybe the docs are not well explained enough though.

Refs

- https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups#creating-a-group-and-adding-entries-to-it
- https://github.com/JabRef/user-documentation/pull/405#pullrequestreview-1151179747

- #9072


I just tested and it actually is possible to add entries to groups that collect entries automatically by keyword, so the problem you describe that entries cannot be added and which is supposed to be the rationale for triggering an error is non-existent...

**Comment by meatnordrink** [comment]
> There ARE docs that explain how it is done.
The existing #[#creating-a-group-and-adding-entries-to-it](https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups#creating-a-group-and-adding-entries-to-it) section you referenced does not actually address what I'm talking about. I'm referring to adding articles to a group *after the group has already been created,* which this section doesn't address.

> I just tested and it actually is possible to add entries to groups that collect entries automatically by keyword ... so the problem you describe ... is non-existent...

Well, I've tried on two different versions (manually installed and Linux snap), and both by dragging and using the right-click context menu on groups. Neither works. So closing the issue makes the choice that your situation is more representative than mine. I think it would be better to see if someone else can verify that the problem doesn't exist, as well; that would double the confidence that it's just a mysterious issue with my installation/machine/me not knowing how to drag-and-drop.

**Comment by ThiloteE** [comment]
Fair enough

**Comment by thiagocferr** [comment]
I've also tested this feature, specifically on a portable version of [JabRef 5.7](https://github.com/JabRef/jabref/releases/tag/v5.7) on Manjaro. Everything seems to be working according to the [documentation](https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups#creating-a-group-and-adding-entries-to-it) and I was also able to manually add entries to "search for a keyword" groups. 

I can imagine this problem happening on the Snap version, as I had something similar happen with other software (i.e. Firefox), but it seems unusual for this to happen on a manually installed version...

Below, a video of this testing using drag-and-drop:

https://user-images.githubusercontent.com/69732601/197611931-f6f83486-afd3-4fc9-8674-0582f79163e4.mp4

**Comment by meatnordrink** [comment]
@thiagocferr, thanks so much for corroborating this, and for going to the trouble of making a video! I really appreciate it. (I also enjoy your taste in music! :smile: )

**Comment by meatnordrink** [comment]
Since two other users could not reproduce this, I'm closing it. It's still happening for me, but it's not really a problem, since I can just convert keyword-based groups to manual. My concern was driving away users from JabRef, but if it's just me then that's not an issue.
