### ISSUE TITLE
Ctrl+Shift+K can copy the citation key with a byproduct effect

### ISSUE THREAD

**Issue by idadoudou** [JabRef/jabref#9276]
### JabRef version

5.7 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Linux localhost.localdomain 5.19.12-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Sep 28 17:11:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Locate an item, its first author has the first letter different from "K", for example, Malloy

2. Press Ctrl + Shift + K

3. Copy the current item key, at the same time, jump to an item with the first author with the first letter as "K"

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Please try the latest version https://builds.jabref.org/main/

**Comment by pcdi** [comment]
The issue still persists in

```
JabRef 5.10--2023-08-28--e9a358c
Mac OS X 13.5.1 aarch64 
Java 21-internal 
JavaFX 20+19
```

However, the issue does not occur when any field in the entry editor is selected. E.g. the active cursor is inside the Author field of the entry editor and then the keyboard shortcut is invoked, the _correct_ entry key is copied. It is not sufficient that the entry editor is merely opened, the cursor needs to be in any of its fields.

Additionally, I noticed that invoking _any_ keyboard shortcut will jump to the first entry where the first author's last name begins with the letter of the shortcut. So pressing CMD-E on an entry to open the entry editor will indeed open the entry editor, but also jump to the first entry of authors with last names beginning with "E". Same with CMD-Shift-L for opening a console window: Opens the console window, jumps to entries beginning with "L".

**Comment by Siedlerchr** [comment]
I remember having fixed that recently, just can't find the PR. 
Can you please try the latest development version? from https://builds.jabref.org/main/ 
@pcdi @idadoudou 

Pleas re-open if the issue persitss

**Comment by pcdi** [comment]
Based on a quick test in this version:

```
JabRef 5.13--2024-03-26--98f64f4
Mac OS X 14.4 aarch64 
Java 21.0.2 
JavaFX 22+30
```

the issue seems to be resolved.
