### ISSUE TITLE
Changing the font size preference does not update the menu bar font size

### ISSUE THREAD

**Issue by tomazari** [JabRef/jabref#9279]
### JabRef version

5.7 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Click options and click preferences
2. Click Appearance
3. Select "Override default font settings" and choose a font size (e.g. 20)
4. Press save. Your font sizes should be updated.
5. Repeat steps 1 and 2
6. Deselect "Override default font settings"
7. Press save. The font size in the menu bar does not update to the default. See screenshot in appendix.

### Appendix

![image](https://user-images.githubusercontent.com/94524320/197335098-6f2c7163-4cfc-4332-bca0-bc0665c5ad6a.png)

Might be a similar issue: [Font size preference does not apply correctly to Preference dialog window #8386](https://github.com/JabRef/jabref/issues/8386)

**Comment by sreenath-tm** [comment]
I would like to contribute to the issue. Can you assign this to me.
