### ISSUE TITLE
"Remove group" options are presented for clicked group, but actions are taken on all selected groups

### ISSUE THREAD

**Issue by Gpax971** [JabRef/jabref#9281]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 21H2, jabref build date: 22/10/22

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new library
2. In new library, create 2 groups
3. Select first group using left click
4. Right click on second group
5. Options for second group show up
6. Click `Remove group > Also remove subgroups` or `Remove group > keep subgroups`
7. First group is deleted, second group is kept

![image](https://user-images.githubusercontent.com/34959806/197342699-be3a6057-92c7-4ec0-aa9a-a5b8142156f7.png)
![image](https://user-images.githubusercontent.com/34959806/197342704-eed716d2-f25b-4c87-a159-3ddd6291901c.png)
![image](https://user-images.githubusercontent.com/34959806/197342710-8f259179-a8fc-4534-a110-34433b1882e6.png)

The `group` passed to `removeGroupKeepSubgroups` and `removeGroupAndSubgroups` is only used for dialog text, `selectedGroups` is used for all actual removals. 

Potential solutions could be to check that clicked group is part of selected groups, or to update context menu and dialogs to reflect selected groups more accurately.

### Appendix

Appears to be caused by changes from #8390.
<details>

<summary>Problematic methods</summary>

 
org.jabref.gui.groups.GroupTreeViewModel.java:
```
public void removeGroupKeepSubgroups(GroupNodeViewModel group) {
        boolean confirmed;
        if (selectedGroups.size() <= 1) {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove group"),
                    Localization.lang("Remove group \"%0\" and keep its subgroups?", group.getDisplayName()),
                    Localization.lang("Remove"));
        } else {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove groups"),
                    Localization.lang("Remove all selected groups and keep their subgroups?"),
                    Localization.lang("Remove all"));
        }

        if (confirmed) {
            // TODO: Add undo
            // final UndoableAddOrRemoveGroup undo = new UndoableAddOrRemoveGroup(groupsRoot, node, UndoableAddOrRemoveGroup.REMOVE_NODE_KEEP_CHILDREN);
            // panel.getUndoManager().addEdit(undo);

            List<GroupNodeViewModel> selectedGroupNodes = new ArrayList<>(selectedGroups);
            selectedGroupNodes.forEach(eachNode -> {
                GroupTreeNode groupNode = eachNode.getGroupNode();

                groupNode.getParent()
                         .ifPresent(parent -> groupNode.moveAllChildrenTo(parent, parent.getIndexOfChild(groupNode).get()));
                groupNode.removeFromParent();
            });

            if (selectedGroupNodes.size() > 1) {
                dialogService.notify(Localization.lang("Removed all selected groups."));
            } else {
                dialogService.notify(Localization.lang("Removed group \"%0\".", group.getDisplayName()));
            }
            writeGroupChangesToMetaData();
        }
    }

public void removeGroupAndSubgroups(GroupNodeViewModel group) {
        boolean confirmed;
        if (selectedGroups.size() <= 1) {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove group and subgroups"),
                    Localization.lang("Remove group \"%0\" and its subgroups?", group.getDisplayName()),
                    Localization.lang("Remove"));
        } else {
            confirmed = dialogService.showConfirmationDialogAndWait(
                    Localization.lang("Remove groups and subgroups"),
                    Localization.lang("Remove all selected groups and their subgroups?"),
                    Localization.lang("Remove all"));
        }

        if (confirmed) {
            // TODO: Add undo
            // final UndoableAddOrRemoveGroup undo = new UndoableAddOrRemoveGroup(groupsRoot, node, UndoableAddOrRemoveGroup.REMOVE_NODE_AND_CHILDREN);
            // panel.getUndoManager().addEdit(undo);

            ArrayList<GroupNodeViewModel> selectedGroupNodes = new ArrayList<>(selectedGroups);
            selectedGroupNodes.forEach(eachNode -> {
                removeGroupsAndSubGroupsFromEntries(eachNode);
                eachNode.getGroupNode().removeFromParent();
            });

            if (selectedGroupNodes.size() > 1) {
                dialogService.notify(Localization.lang("Removed all selected groups and their subgroups."));
            } else {
                dialogService.notify(Localization.lang("Removed group \"%0\" and its subgroups.", group.getDisplayName()));
            }
            writeGroupChangesToMetaData();
        }
    }
```

</details>

**Comment by William-Yao425** [comment]
Hi, me and my team would like to work on this open issue, and this is our first try of GitHub project. Could you please assign this issue to our team?

**Comment by koppor** [comment]
The wording of "subgroup" seems to be confusing. "sub group" means "nested group", not "shown below group"

![grafik](https://user-images.githubusercontent.com/1366654/200404208-22ac0c24-24b5-44a7-a5e9-7a5f0e6d3939.png)

When removing group 1 and all subgroups, 1.1 is also removed

![grafik](https://user-images.githubusercontent.com/1366654/200404277-5bf9c757-5af8-4062-99f5-1c74e8a3dafc.png)


Note that the term "subgroup" is similar to "subfolder" in Outlook: https://support.microsoft.com/en-us/office/create-a-subfolder-adac3676-8dc0-4134-b151-22eec1cfcf93

**Comment by Gpax971** [comment]
Apologies, I assumed all groups were subgroups of the "all entries" group, since they are added by right clicking on the "all entries" group and clicking add subgroup

**Comment by Ravitwr** [comment]
Could I be assigned this issue.

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/18)
