### ISSUE TITLE
Intelij run configuration not working

### ISSUE THREAD

**Issue by thiagocferr** [JabRef/jabref#9303]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

Manjaro with GNOME 42.4, Jabref main branch (commit 349c879)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. [Setup local workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace.html), including Intelij IDE configuration;
2. Try running application with `JabRef Main` run config;
3. Errors stop the application from running.

This behavior seems to manifest in two ways:

1. Intelij cannot run because the application's main entry point has changed from `org.jabref.gui.JabRefMain` to `org.jabref.cli.Launcher` in PR #9217. I've been able to run normally by just changing the entry point on the [config file](https://github.com/JabRef/jabref/blob/main/.idea/runConfigurations/JabRef_Main.xml) (and was not sure if this was going to be reverted, as PR #9257 was still open at the time)
2. Now, I cannot run even with the entry point change because of a build error on `org.jabref.gui.desktop.os.Windows`. See appendix for error message.

### Appendix

...
<details>

<summary>Log File</summary>

```
/home/james/Documents/Github Repos/Public/jabref/src/main/java/org/jabref/gui/desktop/os/Windows.java:84:9
java: cannot access com.sun.jna.LastErrorException
  class file for com.sun.jna.LastErrorException not found
```

</details>

**Comment by koppor** [comment]
We are currently using the gradle task "run" - this doesn't work at your side because of the compiliation error?

![grafik](https://user-images.githubusercontent.com/1366654/197613571-f751b9c4-7e9d-4f8e-adc1-680cc8eb6a75.png)

**Comment by koppor** [comment]
Could you update to the latest main branch? My line 84 does not contain a JNA call.

![grafik](https://user-images.githubusercontent.com/1366654/197614247-35d3954c-301a-468e-b00d-6d3e34dd1223.png)

**Comment by koppor** [comment]
What is the output of `./gradlew --version`? Mine is as follows:

```bash
$ gradlew --version                                                                  
                                                                                     
------------------------------------------------------------                         
Gradle 7.5.1                                                                         
------------------------------------------------------------                         
                                                                                     
Build time:   2022-08-05 21:17:56 UTC                                                
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918                               
                                                                                     
Kotlin:       1.6.21                                                                 
Groovy:       3.0.10                                                                 
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021                
JVM:          18.0.2 (Oracle Corporation 18.0.2+9-61)                                
OS:           Windows 10 10.0 amd64                                                  
```

**Comment by thiagocferr** [comment]
Well...

```log
$ java - version
Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Was it supposed to be `-version`? If so, this is the output:

```log
$ java -version
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+0)
OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mode)
```

---

And yes, I can run the project with gradle task "run" (and from the command line with `./gradlew run`). The problem only affects when running with **Intelij** run config.

**Comment by koppor** [comment]
I will remove the IntelliJ run config in a PR - it does **not** run on my machine, too. 😇 

The manual start can be triggered at `Launcher.java`:

![grafik](https://user-images.githubusercontent.com/1366654/197615655-4ea01ee2-b776-440a-b932-cf794b5abe7f.png)

Runs only with Gradle.

---

Does NOT work with IntellIJ:

![grafik](https://user-images.githubusercontent.com/1366654/197615906-d85176e7-4815-454a-a3da-d2b2240a24ae.png)

![grafik](https://user-images.githubusercontent.com/1366654/197616258-de4730b6-885d-42a9-848d-75b759004b98.png)

I don't know about a quick fix here...

**Comment by thiagocferr** [comment]
The problem with not having IntelliJ run config is that, _as far as I know_, it would not be possible to run the application in debugger mode withing the IDE. So, wouldn´t it be a better option to just update the Intelij run configuration file?

**Comment by koppor** [comment]
Debug works here with Gradle without issues.

**Comment by koppor** [comment]
I worked on refining the guideline. It is currently under review at https://github.com/JabRef/jabref/pull/9355.

You have to configure IntelliJ to use Gradle for Build and running - and "IntelliJ IDEA" for test:

![grafik](https://user-images.githubusercontent.com/1366654/200196229-d60324f0-2885-4466-be8f-e65f16c8d3c4.png)

---

IntelliJ creates the launch configurations. Check out following steps:

![grafik](https://user-images.githubusercontent.com/1366654/200196259-5d23b147-b633-4742-bcc8-2e74f38ee6f0.png)
