### ISSUE TITLE
Add "A-Z" to translation key for group sorting

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9304]
Here is the corresponding line

https://github.com/JabRef/jabref/blob/fe2ceef955227dd6b7b753a53310552ab12938dc/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L432-L433 

From `Localization.lang("Sort subgroups"));` to `Localization.lang("Sort subgroups A-Z"));`

The `JabRef_en.properties` files needs to be adjusted then as well. The other files are handled by Crowdin.

_Originally posted by @Siedlerchr in https://github.com/JabRef/jabref/pull/9248#discussion_r1002539013_

**Comment by Aditya31398** [comment]
Hi @koppor, I am a first timer. Can I work on this?

**Comment by Aditya31398** [comment]
@ThiloteE, can you brief over the issue. Is the change required only in the line mentioned above? What changes are required in the JabRef_en.properties

**Comment by Aditya31398** [comment]
Hi @ThiloteE, I have create a PR for this issue with the changes mentioned above. Can you verify if the changes are good?
