### ISSUE TITLE
Move "Open only one instance of JabRef" preference option to somewhere else

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#9306]
**Is your suggestion for improvement related to a problem? Please describe.**
The option to limit to only one running instance of JabRef is currently under the "Network" tab, which is highly confusing since from a users perspective there is nothing "networky" going on.

**Describe the solution you'd like**
Move it to another tab, maybe "General"?

**Comment by Ivens-Zhang** [comment]
If that's possible, would you like to provide more detail about this issue. Which item you consider that could be moved to 'General'? Is this the one I highlight on the snapshot?

![image](https://user-images.githubusercontent.com/49118158/229559601-4312bfaf-0a38-4b09-9c9f-9caa6790318d.png)

**Comment by DiamondMyK** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

**Comment by ThiloteE** [comment]
"Listen for remote operation on port xxxx" sounds very much "networky" to me.

**Comment by tobiasdiez** [comment]
That we are using a local socket ('remote' is very misleading here) on some port is an implementation detail. We could also store the "remote command" in some file, and check that file in the running instance. But that doesn't mean it should go in the "external files" tab. The point here being that as a user I would never look under "network" to see if I can limit jabref to only one instance.

**Comment by ThiloteE** [comment]
Hmm. Maybe it would make sense to have this option twice in the preferences?

1. Once under general with heavy emphasis on "Open only one instance of JabRef / Allow only one running instance of JabRef"
2. Once under "Remote" just like it is currently.

As a non-programmer I don't know the term "local sockets".
I also never have tried to open a file from JabRef from my webbrowser. How does that work exactly? I assume we have two devices. One local, one remote. The local conncts via web-browser (e.g. via apps like [cockpit](https://cockpit-project.org/running)) to the remove and somehow JabRef detects that and then "somehow" can open a file from remote?

**Comment by tobiasdiez** [comment]
In this context, "remote" refers to the second instance of JabRef that you start. This new instance detects another one is already running and then closes down. There is no connection over a network, nor any possibility to interact with the browser. The best way to think of it is as a glorified lock file, and "port" is the name of that lock file. "Remote" is just a very confusing name for that feature.

**Comment by ThiloteE** [comment]
Then I would suggest to not only move this preference to the general preferences, just like you suggested, but also to completely rewrite the description and purge all remote and port related vocabulary. Also potentially remove the "port" option completely (hence hard-code the port and hide from preferences GUI). Unless, there is a workflow that requires specific ports?

**Comment by Siedlerchr** [comment]
Now, port can be necessary if you have another application running. 
I would rename it simply to  Allow only once instance of JabRef

**Comment by koppor** [comment]
That feature is also used at the web search to add entries to a running JabRef instance. Thus, it's not only about "one instance" only.

For me, it is OK to move it to "general". 

    [x] Enforce single JabRef instance (and allow remote operations)   [...port...] (?)


---

Alternative:

Just add another text for the semantics

![image](https://github.com/JabRef/jabref/assets/1366654/647bac16-6d3b-47a2-ac5c-5f425561168e)

**Comment by koppor** [comment]
@DiamondMyK Move it above "Libraries" in "General"

![image](https://github.com/JabRef/jabref/assets/1366654/a34865e6-1539-4d6e-b93d-2c45806938a1)

Should be little effort only.

**Comment by DiamondMyK** [comment]
> @DiamondMyK将其移至“常规”中的“库”上方
> 
> ![图像](https://user-images.githubusercontent.com/1366654/277650038-a34865e6-1539-4d6e-b93d-2c45806938a1.png)
> 
> 应该只需要很少的努力。

Ok, I see what you mean! I will try my best to solve this problem!

**Comment by DiamondMyK** [comment]
<img width="832" alt="111" src="https://github.com/JabRef/jabref/assets/135491632/dfe21b59-8358-4bb1-aac7-4741d698b2a6">
Hello, I have modified according to your suggestions! Is that true, please? I will submit my changes if the requirements are met. :)

**Comment by koppor** [comment]
> I will submit my changes if the requirements are met. :) @koppor

I am so sorry that my new text proposal was not understandsable. By "(heading)" I meant, "Use 'Single instance' as heading".

Here an update on your screenshot:

![image](https://github.com/JabRef/jabref/assets/1366654/60b612af-171d-4e1d-a162-e6a1d8e82009)

Replace the skried-through text at "1" by "Enforce single JabRef instance (and allow remote operations)" and append "using"

The current settings links to the help page. https://docs.jabref.org/advanced/remote. Your explanation text in the UI is nice. JabRef, however, has currently very short items. The thing is that these texts need to be translated. We therefore opted to keep a link to the help pages. If the "final" preference is there, you can file an update pull request to https://github.com/JabRef/user-documentation/blob/main/en/advanced/remote.md

**Comment by tobiasdiez** [comment]
I really like the explanation (maybe shorten it a little bit and use smaller font) and think we should do this more often. It's also quite common to see this (eg windows settings). On the other points I agree with olly

**Comment by DiamondMyK** [comment]
I'm sorry I misunderstood you. Now I have made new changes according to your expectations, and the changed layout is shown in the figure. Does this meet your expectations? If there are no other questions, I will submit PR. :)
<img width="839" alt="222" src="https://github.com/JabRef/jabref/assets/135491632/66ed12d1-408f-4ce2-9058-c998a007fca8">

**Comment by DiamondMyK** [comment]
Hello, I have completed the expectation of issue, if there is any problem, I will modify it again. Can I ask you to review and merge? I would appreciate it! :)

**Comment by Siedlerchr** [comment]
I'll test it look later. But so far it looks good.
