### ISSUE TITLE
biber/latexmk can't use the JabRef .bib file with content in the abstract field

### ISSUE THREAD

**Issue by RJDan** [JabRef/jabref#9319]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

  latest/edge:      5.8.188   2022-10-28 (2070), ubuntu 22.04

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Get meta-data via doi or online search or parsing pdf.
2. Try to compile latex doc with biblatex using the .bib file.
3. None of the references can be found.

I know this is not a JabRef problem really but I thought to bring it up in case it is an issue for others or if it is something you can solve.
From what I have seen it seems to be related to some characters in the abstract, keyword or similar fields but I didn't have time to troubleshoot to figure out which text was causing the problem. I just deleted all the abstract content from all the refs and then biber could use the file again.
Maybe there could be a button somewhere to purge all abstract content in case of emergencies?

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
HI, usually this helps: using the Quality -> Cleanup -> Field formatter for the fields:
Abstract: LaTeX Cleanup

**Comment by RJDan** [comment]
Oh, shoot! I had no idea that was available! Thank you!
