### ISSUE TITLE
Highlighting of groups should be done by background not underline

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#932]
JabRef 3.2

Typcially, I understand "highlighted" as something colored. JabRef uses underline. 

Screenshot: "All Entries" is highlighed

![grabbed_20160311-081714](https://cloud.githubusercontent.com/assets/1366654/13695745/b7fa93b6-e761-11e5-8485-69ed27cfd54b.png)

It would be nice if JabRef would use JabRef's purple color for highlighting.

**Comment by stefan-kolb** [comment]
Is this fixed?

**Comment by tobiasdiez** [comment]
No, but it is really easy to do in the GroupTreeCellRenderer.

**Comment by tobiasdiez** [comment]
It is now implemented with color change in the recent JavaFX rework -> leave this as closed and remove "after-migration-to-javafx" tag.
