### ISSUE TITLE
Convert Case: exemplify the menus

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9339]
**Is your suggestion for improvement related to a problem? Please describe.**
Just trying to make the UI more practical.

Currently, the sub-menus of `Change case` looks like this:

![ChangeCase](https://user-images.githubusercontent.com/6931104/199505222-94e0a0af-5f40-4847-bf0c-501cebcfd23f.png)

If you have no background in typography, the meanings are not obvious (Capitalize vs Upper case. Sentence case vs Title case)

**Describe the solution you'd like**
Alter the sub-menus into:
 ```
Capitalize
 lower case
 Sentence case
 Title Case
 UPPER CASE
```

And alter the tips (displayed when you stay long over the menu) accordingly. Example for Title Case:
`Capitalize all words, but converts articles, prepositions, and conjunctions to lower case.`
will become
`Capitalize all Words, but Converts Articles, Prepositions, and Conjunctions to Lower Case.`

Tip: change JabRef UI into French language to looks what it will look like (yeah, this is already implemented in French)

**Comment by koppor** [comment]
This is the screenshot for the menu location:

![grafik](https://user-images.githubusercontent.com/1366654/202556822-3c120b0c-d355-4072-8203-da992b188553.png)

French:

![grafik](https://user-images.githubusercontent.com/1366654/202557049-47c0172e-93c9-49dc-afe2-68a52d2e4a09.png)

**Comment by manu-vaillant-afk** [comment]
Hello, I've made a new PR for this issue, don't hesitate to give me some feedback if I need to change anything else for this issue.

**Comment by michaela559** [comment]
hello is this fixed?

**Comment by manu-vaillant-afk** [comment]
Hello, I'm fixing it in this PR : https://github.com/JabRef/jabref/pull/9382
