### ISSUE TITLE
"Highlight groups matching any selected entry" should be enabled as default

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#934]
JabRef 3.2

To make JabRef's features more known to the audience, I would propose to make "Highlight groups matching any selected entry" the default.

Would we have performance issues with that? :innocent:

**Comment by tgkolda** [comment]
Where is this option? In JabRef 3.3, I can no longer see which groups are associated with a highlighted entry.

**Comment by simonharrer** [comment]
It is possible, but not the default option. Maybe we should change that. 

Just select Groups -> Highlight groups ... in the menu.

**Comment by matthiasgeiger** [comment]
Related #932 ;-)

**Comment by simonharrer** [comment]
Implemented, see #1122
