### ISSUE TITLE
File field needs to adjust to Dark theme

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#9340]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04 with Gnome 42.4

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open JabRef 5.8--2022-10-27--8df4a8e
2. Switch to Dark Mode
3. Add new entry
4. Attach (link) a pdf to the entry via the File field
5. The name of the pdf shows in black color and is hard to read in Dark Mode.
![Screenshot from 2022-11-02 10-04-28](https://user-images.githubusercontent.com/1740639/199510067-8d7e02c2-ba78-403b-8be6-bb2e32f61b64.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Quoting @Siedlerchr :

> For some information on Themes: https://docs.jabref.org/advanced/custom-themes Basically, the Dark.css inherits from the Light.css and overwrites the color. So you need to set a different color for this textfield /highlight

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/17)
