### ISSUE TITLE
builds.jabref.org/main/: 5.7 newer than 5.8 ?!?

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#9346]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

In https://builds.jabref.org/main/, the latest development version are files named JabRef-5.7* (dated November 2), while files JabRef-5.8* are older (October 31).
It should be the other way around, and JabRef-5.7* should not even exist.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Thanks! guess it was a side effect of my testing by creating a tag

**Comment by Siedlerchr** [comment]
The 5.8 should be the newest again
