### ISSUE TITLE
Add support for parsing of encrypted PDFs

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#935]
A refactoring revealed that there is a TODO at the PDFContentImporter. It seems that [Bouncy Castle](https://www.bouncycastle.org/documentation.html) was not included during development and a quick hack was not to support encrypted PDFs at all. Some papers, however, are encrypted should be supported.

**Comment by stefan-kolb** [comment]
Are there really that much use cases were papers are encrypted? And is it really necessary to extract information from that papers or is it even possible (must be IEEE or Springer)? What might be more interesting is too add functionality to decrypt PDFs in general and store a decrypted version.

**Comment by koppor** [comment]
PDFs are also encrypted when one sets a password for editing. This sometimes is the case at publications.
