### ISSUE TITLE
Interface Language cannot be understood. It is not English.

### ISSUE THREAD

**Issue by PUNDARIKAKSHA** [JabRef/jabref#9352]
### JabRef version

5.7 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Interface Language cannot be understood. It is not English. How can I change the language to English?

**Comment by Siedlerchr** [comment]
Can you share a screenshot?

**Comment by koppor** [comment]
The CLI offers to reset preferences. Read a CLI howto at https://docs.jabref.org/advanced/commandline

`-d all` is the parameter to pass to `JabRef.bat`

**Comment by koppor** [comment]
1. Start JabRef.
2. Click on the second-last menu
    ![grafik](https://user-images.githubusercontent.com/1366654/200417660-8eaa5f59-c1d9-4a8b-971e-9151e20f91c4.png)
3. Select the first entry
    ![grafik](https://user-images.githubusercontent.com/1366654/200417735-dc7bee7d-31ba-4417-bdbb-d3cc720df66f.png)
4. Select "English" from the drop down
    ![grafik](https://user-images.githubusercontent.com/1366654/200417813-62aea355-e55c-4258-9fab-3d14293c17fa.png)

**Comment by PUNDARIKAKSHA** [comment]
Sure, I will share it within a few minutes.

Thank you

**Comment by PUNDARIKAKSHA** [comment]
Hello.
I have attached the screenshots herewith. But the English language is
showing nowhere. Currently, I am using Windows 11. Kindly help.

Thank you
With regards
Pundarikaksha Das

**Comment by Siedlerchr** [comment]
@PUNDARIKAKSHA  You need to upload the screenshots directly on github. Attachments do not work

**Comment by Siedlerchr** [comment]
/
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
