### ISSUE TITLE
Preview panel is not updated when an entry is cut/deleted

### ISSUE THREAD

**Issue by bartsch-dev** [JabRef/jabref#936]
When an entry is cut or deleted the Preview Panel is not updated.

Tested with the current master at 7aa371c931ea51e7c092632e3e3f817c4861f66b.

![notupdated](https://cloud.githubusercontent.com/assets/15333371/13703378/f48015de-e795-11e5-94f3-e130f76353b8.gif)

**Comment by stefan-kolb** [comment]
Nice video :smile: for reproducing the issue!
