### ISSUE TITLE
Remove "Remove group" from context menu of "All entries"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9360]
The (pseudo) group "All entries" is always there. Therefore, the user should not be offered to be able to delete it.

Thus, remove the chose "Remove group" from the context menu of "All entries".
This menu item has to be kept for the other groups (and the behavior should be same).

![grafik](https://user-images.githubusercontent.com/1366654/200405314-7808df12-a505-44e0-a5e8-70f9e827005e.png)

**Comment by sayan9112** [comment]
Hey @koppor , I'd like to fix this issue. Can you assign me?

**Comment by robyquin** [comment]
Hi!
in PR #9376 I proposed the correction of this and other actions on the groups tree.

**Comment by sayan9112** [comment]
As a newcomer I'm a bit late but I'm still working on this.
