### ISSUE TITLE
Global Search: Clicking an entry in the search window should lead to a selection in the corresponding library

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9362]
Issues left:

- [x] Preview in dark theme when no search results is still "white"
   ![image](https://user-images.githubusercontent.com/1366654/211262551-e0ce7f25-ab23-4b84-a56a-24cf3d318283.png)
- [x] Location of the pin to top button 
    ![image](https://user-images.githubusercontent.com/1366654/211262657-0fe98720-3ee9-4091-819b-852acb5ca6b5.png)
- [ ]  When clicking an entry in the search window, it should be marked in the corresponding library (JabRef should focus the library and then select the item in the main table)
- [x] Search dialog has to retain size (-> store size in preferences)
- [ ] ~~Debatable: If the columns such as status or relevant should NOT be shown, because one could theoretically change the value of them in the search window...~~

_Originally posted by @Siedlerchr in https://github.com/JabRef/jabref/issues/8054#issuecomment-985783685_

**Comment by DanielS01ss** [comment]
Hi
I would love to work on this task!

**Comment by KunalBainsla** [comment]
Hi there.
I would like to take this task.

**Comment by JawadTUE** [comment]
Hi, can I be assigned to this issue? I would like to work on it for a university project.

**Comment by ThiloteE** [comment]
How to reproduce:
![image](https://user-images.githubusercontent.com/73715071/228667069-93557bf9-7027-49e7-9090-e8d28dffa270.png)

**Comment by ThiloteE** [comment]
@KunalBainsla are you still on it?
@JawadTue, I would say if KunalBainsla will not respond within a day, go for it. Thank you :-)

**Comment by JawadTUE** [comment]
We started working on it and managed to fix 2 of the sub-issues. We will open a (draft) pull request soon.

**Comment by koppor** [comment]
Not all PRs are mreged yet, thus I keep it open.

**Comment by calixtus** [comment]
Oops, was marked as "fixes" in the other pr. Sry.

**Comment by koppor** [comment]
Item 2 and 3 not solved yet. Therefore, reopened.

**Comment by Siedlerchr** [comment]
Part 2 is fixed. Part 3 not yet

**Comment by derronli** [comment]
I'd like to give this a try.

I began looking at the issue, and was thinking the solution lies in GlobalSearchResultDialogue.java (Below)
![image](https://github.com/JabRef/jabref/assets/104483680/f8190066-1178-4b5d-994a-3736f99668e8)

Was wondering if anyone could point me in the right direction.

**Comment by Siedlerchr** [comment]
Another idea would to be to set the selectedEntries in the statemanager  as we only have the database contextes in the SearchResultsTableDataModel

**Comment by derronli** [comment]
Sorry to bother, I've been working on this for the past week. I've read the documentation on Javafx MVVM pattern and I think I have a high level understanding of the UI. I'm struggling to understand using the stateManager and the structure of selections. In GlobalSearchResultDialog.java I've tried using the setSelectedEntries method of the stateManager in a few different ways with no success.
Could I ask for further explanation on how to continue or an existing example on selection handling? Thank you!
