### ISSUE TITLE
Save/save as: file type shows BIBTEX_DB

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#9372]
### JabRef version

5.7 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Save a new file or use "save as" for an existing bib file
2. The dialog shows then in the file type selector "BIBTEX_DB file". Instead it should show something like "Library (.bib file)"

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
There is `File > save library as ... > BIBTEX_DB file (*.bib)`
There is also `File > Export > Save selected as plain BibTeX... > BIBTEX_DB file (*.bib)`.

I propose to rename to `BibTeX/BibLaTeX (*.bib)` because this would be similar to how we show other file formats under

- `File > Export > Export all entries > ...`
- `File > Export > Export selected entries > ...`
- `File > Import > Import into current library > ...`
- `File > Import > Import into new library > ...`

As added bonus, it would spread the knowledge about BibLaTeX, which I think is a good thing because BibTeX is a little outdated and we not only support BibTeX, but also BibLaTeX.

Furthermore, I would propose to rename `File > Export > Save selected as plain BibTeX... ` to `File > Export > Save selected as plain BibTeX/BibLaTeX library file`. Maybe remove the "plain"? Is there a difference between saving as BibTeX and exporting as BibTeX? Does exporting "plainly" remove some JabRef specific data from the file?

**Comment by ThiloteE** [comment]
Removing good first issue, because we are still discussing

**Comment by tobiasdiez** [comment]
Personally, I would strive to make JabRef's UI as independent as possible from the fact that we use Bib(La)TeX under the hood. JabRef's whole point is to abstract away the boring bibtex related things, so why should we remind people that they are still using it? This becomes especially relevant once we have our word addin running, which then hopefully attracts people that have never heard of bibtex before. After using Zotero and Mendeley for a bit, I really don't see anything that they do better then us - so I would like to position JabRef as "a wholesome reference manager that even works well with bibtex" over our current "a niche bibtex manager that is only useful for latex nerds".

So I would always use "Library file (.bib)" over "BibTeX/BibLaTeX file (.bib)". It is also shorter, which is nice for the menu.

**Comment by ThiloteE** [comment]
so you propose to rename `RIS (*.ris)` also to `library (*.ris)`?

**Comment by Siedlerchr** [comment]
I agree with Thilo. And plain bibtex is bibtex without jabref metdata etc.  Mods and RIS etc are also completely different formats. So we should use bibtex as it's the format.

**Comment by koppor** [comment]
I always position JabRef as tool for BibTeX. Some pro users hesitate to use JabRef if JabRef seems to move away from BibTeX.

Maybe, we need to offer two modes: Entry mode (which is a general mode avoiding BibTeX) and professional mode (which has more "BibTeX" in the UI and is more clear in BibTeX terms).

Maybe, it's "just" a new localization for the UI?

Maybe we should have a strategic call discussing the general direction.

**Comment by tobiasdiez** [comment]
> so you propose to rename `RIS (*.ris)` also to `library file (*.ris)`?

If we would use RIS as our main file format, yes. But its a nice Gedankenexperiment: would we put RIS everywhere in our UI if we would use it as our main file format?

**Comment by koppor** [comment]
My current vote is "BibTeX file" or "BibTeX library file". In all cases, not "DB" and no capital letters.

Context as picture

![image](https://user-images.githubusercontent.com/1366654/228770768-0475ba61-86cb-49ce-b660-58af5da7ef59.png)

Note: We have "BIB file" in the preferences:

![image](https://user-images.githubusercontent.com/1366654/228780940-56d84847-91dc-47d7-868b-19a6556770a7.png)

I personally would like ".bib file", but ".bib file (*.bib)" reads strange at the save dialog.

**Comment by ThiloteE** [comment]
Thanks for your continued engagement morgantex :-) Great job with pr 9703

**Comment by koppor** [comment]
We don't support BibTeXML any more. There should be no leftovers in the code hopefully...

**Comment by morganteg** [comment]
> We don't support BibTeXML any more. There should be no leftovers in the code hopefully...

I found it into the "main" branch. However, I used BibTeXML just as an example of Type with multiple extensions.

**Comment by calixtus** [comment]
devcall decision:
It should show the DisplayName of BIBTEX_DB consistently throughout the gui.
![grafik](https://user-images.githubusercontent.com/50491877/234089286-f258b047-257e-40c0-9952-0b505ff73407.png)

[/src/main/java/org/jabref/logic/util/StandardFileType.java#L21](https://github.com/calixtus/jabref/blob/d279c0edb711a637194947eeb9007cdb27ef7251/src/main/java/org/jabref/logic/util/StandardFileType.java#L21)

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/15)
