### ISSUE TITLE
The app dosen't stat on Windows 11

### ISSUE THREAD

**Issue by kostadinoff** [JabRef/jabref#9394]
### JabRef version

5.7 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Unfortunately the app dosen't start on Win 11. I've tried to reinstall it, but no response at all. 
I really enjoy JabRef and thinks that there is no alternatives out that for working with .bib files thats well.

**Comment by Siedlerchr** [comment]
HI, do you get any errors or any messages or what happens? How do you open it?
Have you tried the portable version as well?

**Comment by kostadinoff** [comment]
> HI, do you get any errors or any messages or what happens? How do you open it?
> 
> Have you tried the portable version as well?

No massages - it's shows that's loading and no windows appear afterwards. Portable version- same story. The launching method- dummy one double click on the exe file

**Comment by HoussemNasri** [comment]
@kostadinoff Can you try running *JabRefHost.bat* at the root of the portable version folder?

**Comment by HoussemNasri** [comment]
Sorry, I meant `runtime/bin/JabRef.bat`

**Comment by kostadinoff** [comment]
![screenshot](https://user-images.githubusercontent.com/76478414/203382494-3fc16563-13b5-4536-9804-51e822148645.png)

**Comment by HoussemNasri** [comment]
@kostadinoff Did you import preferences that were exported using a Linux or Mac machine?

**Comment by kostadinoff** [comment]
> @kostadinoff Did you import preferences that were exported using a Linux or Mac machine?

I use Linux at home and windows at work - most of the references are done under Linux machine so I would say yes

**Comment by HoussemNasri** [comment]
I meant import preferences as in the screenshot below. Using libraries across different operating systems shouldn't create a problem - It's actually what makes JabRef unique from other platform-specific reference management software. Importing preferences from another Os also shouldn't cause any issues, but apparently, there is a bug from our side.

![image](https://user-images.githubusercontent.com/21198231/203385075-0a33ab34-c7c1-4655-93db-37f9a7c8f73b.png)

**Comment by kostadinoff** [comment]
Is there any way to fix it ?

**Comment by kostadinoff** [comment]
> You can rest the preferences using the CLI https://docs.jabref.org/advanced/commandline#reset-preferences-d-key `\JabRef\runtime\bin\JabRef.bat -d all`

Thank you ! That's worked
