### ISSUE TITLE
Web Search: display only the name of the database

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#941]
Currently, in the Web Search, "Fetch Arxiv.org" and "Fetch INSPIRE" are displayed. For the other databases, only the name is displayed (See pull request #790)
From my understanding, this implies the following changes:
- In `/src/main/java/net/sf/jabref/importer/fetcher/INSPIREFetcher.java` (line 150), `return Localization.menuTitle("Fetch INSPIRE");` should probably be replaced by `Localization.menuTitle("INSPIRE");` 
- Same thing in `/src/main/java/net/sf/jabref/importer/fetcher/OAI2Fetcher.java` (line 263) with `return Localization.menuTitle("Fetch ArXiv.org");`
- Similarly, in `/src/main/java/net/sf/jabref/importer/fetcher/GVKFetcher.java` (line 76), it would be nice to shorten the string by replacing `return "GVK (Gemeinsamer Verbundkatalog)";` with `return "GVK";`

**Comment by Siedlerchr** [comment]
If you want to change it, have a look here, not that difficult:

https://github.com/JabRef/jabref/wiki/Code-Howtos#using-localization-correctly

Otherwise I could fix this.

**Comment by koppor** [comment]
Regarding GVK: Maybe we should add links to our help page to support users to learn about the meaning of INSPIRE, GVK, ...

The intention to put the long name inside the brackets was to give the users some idea what the fetcher is about.

**Comment by Siedlerchr** [comment]
This issue can now be closed, see #949
