### ISSUE TITLE
GUI flicker to black (Linux, Wayland)

### ISSUE THREAD

**Issue by multiflexi** [JabRef/jabref#9426]
### JabRef version

5.7 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Manjaro 22.0.0, GNOME 43, Wayland, Nvidia 525.60.11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Run JabRef
2. Move mouse, open menu, click on button
3. Affects both portable and version from https://aur.archlinux.org/packages/jabref-bin

### Appendix

Flickers to black

![Screenshot from 2022-12-04 20-20-16](https://user-images.githubusercontent.com/11663844/205510887-70c25ee5-4d81-4c59-aded-db2f80f10864.png)
![Screenshot from 2022-12-04 20-20-29](https://user-images.githubusercontent.com/11663844/205510889-e94148b4-7225-4cca-b1fd-96642aa45103.png)

**Comment by ilippert** [comment]
Cannot reproduce via
JabRef 5.8--2022-12-08--8ebdb52
Linux 6.0.11-300.fc37.x86_64 amd64 
Java 18.0.2.1 
JavaFX 19+11
on Fedora 37

**Comment by multiflexi** [comment]
What GPU and drivers? Can it be specific to nVidia drivers and GPUs?

**Comment by Siedlerchr** [comment]
Can you please try the latest development version? We recently upgraded the javafx version:


We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by St0rml** [comment]
Not the original poster, but I'm having the exact same issues. As suggested by @Siedlerchr I installed a development build:
JabRef 5.10--2023-05-30--424ff1c
Linux 6.2.15-300.fc38.x86_64 amd64 
Java 20.0.1 
JavaFX 20+19
on Fedora 38

The issues still persists.

Details on version and operating system:
Fedora 38, Gnome 44.1, Wayland, Nvidia 530.41.03

**Comment by St0rml** [comment]
Forcing jabref as flatpak to run with GTK2 as mentioned in the workaround in #5867  (More specifically [this comment](https://github.com/JabRef/jabref/issues/5867#issuecomment-1290950196)) fixes the issues on wayland for me.

**Comment by bshor** [comment]
Having the same problem with Fedora 38 and Wayland, using the latest RPM download from https://builds.jabref.org/main/ or the Flatpak version. I have an Nvidia 4070 GPU.

It blinks terribly for me, basically making Jabref unusable.

But: logging out and then back into an X.org session makes it work perfectly.

**Comment by koppor** [comment]
Cryptomator seems to have also issues w/ Wayland: https://github.com/cryptomator/cryptomator-linux/issues/9. Does Cryptomator run well on your side @bshor?

**Comment by bshor** [comment]
I've never run Cryptomator, so unfortunately I don't know about that.

**Comment by St0rml** [comment]
> Cryptomator seems to have also issues w/ Wayland: [cryptomator/cryptomator-linux#9](https://github.com/cryptomator/cryptomator-linux/issues/9). Does Cryptomator run well on your side @bshor?

I have no problems running Cryptomator. However after updating, Jabref again shows this flicker behaviour. Sadly, I cannot really reproduce what exactly caused it to flicker again :/

**Comment by fanzhuyifan** [comment]
Also having issues after the recent update to 5.11. I am using Arch linux on wayland

**Comment by Siedlerchr** [comment]
Can you please test this version ? https://builds.jabref.org/pull/10808/merge

**Comment by St0rml** [comment]
I'm afraid, I cannot be of big help anymore, as I moved away from Nvidia GPUs on the machine which regularly had the issues described above. Big reason here being me wanting to use Jabref. _No regrets_.
For what its worth, the build runs fine on my laptop, which has an Nivida MX250 and the same OS and Desktop Environment (+Wayland) as the machine on which I observed the behavior described above. However, so does an older version of Jabref. Also, my laptop (MX250) had a recent fresh install so there's many variables which might contribute to it now working smoothly.
If there's any steps or something you'd like me to try out, please let me know and I'll try to get back to you soon.

**Comment by Cvtq** [comment]
> Can you please test this version ? https://builds.jabref.org/pull/10808/merge

I also have this issue. I've tried portable 5.13 and 5.12 from my package manager and didn't notice any difference. This is probably have something to do with how nvidia drivers works on Wayland, because this is not the only issue i get.

**Comment by wallywasadog** [comment]
> Can you please test this version ? https://builds.jabref.org/pull/10808/merge

I've tried this build on Wayland and the problem is still there. Happy to test further if needed.

**Comment by koppor** [comment]
@wallywasadog One more try: Could you download a javafx22-ea version from https://builds.jabref.org/jdk-ea/ and try it?

**Comment by bshor** [comment]
I just tried the latest FlatPak on a different system running Wayland (an immutable distro that pretty much requires Flatpaks), and it operates perfectly!

**Comment by tob1asr** [comment]
Can confirm that with the implementation of Wayland's `linux-drm-syncobj-v1` protocol (aka. "explicit sync") by NVIDIA in the 555 driver release, all of the flickering and black screens are gone on my machine.

JabRef 5.13, NixOS 24.11.20240716.ad0b5ee with Linux 6.10.0, KDE Plasma 6.1.3 on Wayland, NVIDIA 555.58.02
