### ISSUE TITLE
Optional fields tab disappeared in master

### ISSUE THREAD

**Issue by burrbull** [JabRef/jabref#943]
* JabRef version (available in the About box): JabRef-3.3dev--snapshot--2016-03-11--master--2a80e9c
* Operating system and version: Ubuntu 15.10
![jabrefscreen2016-03-11](https://cloud.githubusercontent.com/assets/3072754/13721754/947ece9e-e841-11e5-8b01-fc13b8dca39a.png)

* Steps to reproduce:
  1. Load last snapshot
  2. Open

**Comment by burrbull** [comment]
There is no bug in JabRef-3.3dev--snapshot--2016-03-04--fix890--7ff13da

**Comment by stefan-kolb** [comment]
Thanks for reporting! The Tab is always missing?! Miht be a merge conflict bug introduced by https://github.com/JabRef/jabref/commit/86511a5915b2031fa1d421f1e537be09193b86af
