### ISSUE TITLE
Use JavaFX stylesheet in other software

### ISSUE THREAD

**Issue by SteffenHeu** [JabRef/jabref#9438]
Hey all,

sorry im misusing the issues for this, but i thought this might be the best way to reach out. 

We are developing [MZmine](https://github.com/mzmine/mzmine3), an open source software (MIT license) for scientific data processing in mass spectrometry. As both softwares are MIT licensed, we would like to reuse the JabRef theme there. I implemented it in such a way that it points to your project:

![grafik](https://user-images.githubusercontent.com/37407705/206407861-8f09719a-35c6-47cc-947a-d56610b089af.png)

Do you have objections regarding this implementation?

Best regards

Steffen

**Comment by SteffenHeu** [comment]
Great, thank you!

**Comment by Siedlerchr** [comment]
@SteffenHeu  We have no created a repository where users can share their stylesheets:
https://themes.jabref.org/
