### ISSUE TITLE
Search results dialog show an empty table of search results

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#9440]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 100.0.0 Windows 10 10.0 amd64  Java 18.0.2  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Type something in the global search bar
  2. Click the "search across libraries in a new window" button beside the search bar
3. It shows an empty table even though the search algorithm has found 208 results

Note: `JabRef 5.8--2022-08-10--dcec4e2` behaves normally

![image](https://user-images.githubusercontent.com/21198231/206912432-038a9e01-66d3-4422-9f51-30398819d12b.png)

**Comment by Siedlerchr** [comment]
Very odd! I debugged a bit and found that the problem is here
https://github.com/JabRef/jabref/blob/1e34797a03be3f95cfe396c95a4fc6197d20a74d/src/main/java/org/jabref/gui/search/SearchResultsTableDataModel.java#L36-L40

getEntries() is an emptyList for some reason the database object returned from the context does not contain any entries...

**Comment by HoussemNasri** [comment]
I did some experiments and I'm positive this commit f7648e82168e180f635b0e783262117d75c87fa5 introduced the bug. Gone through the changes but I can't seem to spot anything that might cause the bug. I'm really confused!

**Comment by Siedlerchr** [comment]
My first gues is this has something to do with the OpenDatabase/library tab refactoring we did a while ago..

**Comment by Siedlerchr** [comment]
@HoussemNasri  Yes, very odd 507a2635f4 is the last commit that works.

**Comment by HoussemNasri** [comment]
For me it's the one just before f7648e82168e180f635b0e783262117d75c87fa5

**Comment by Siedlerchr** [comment]
I tested a bit more and found out it must have been something to do with loading the last open libraries.
Create a new library with some entries 
Search for something
Global search works and shows entry

**Comment by Siedlerchr** [comment]
I found the problem together with Houssem.
When we load a library we create a new "empty"  LIbraryTab and DatabaseContext before the data is fully loaded.
Then we replaced the original bibDatabaseContext with the new one from the parser Result.
However, in stage manager the original list still contains the original databaseContext.
