### ISSUE TITLE
deb v. 5.8 is not installable on Debian

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#9472]
### JabRef version

5.8 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Debian 11 Bullseye

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Deb file of v. 5.8 is not installable due to **unknown compression**. Here is the steps to reproduce and the log:

1. `sudo apt -f install ./jabref_5.8_amd64.deb`
2. 
``` Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'jabref' instead of './jabref_5.8_amd64.deb'
The following NEW packages will be installed:
  jabref
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/187 MB of archives.
After this operation, 227 MB of additional disk space will be used.
Get:1 ~/Scaricati/App/jabref_5.8_amd64.deb jabref amd64 5.8.60000 [187 MB]
dpkg-deb: error: archive '~/Scaricati/App/jabref_5.8_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up dpkg: error processing archive ~/Scaricati/App/jabref_5.8_amd64.deb
 (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ~/Scaricati/App/jabref_5.8_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Many thanks in advance,

### Appendix

<details>

<summary>Log File</summary>

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'jabref' instead of './jabref_5.8_amd64.deb'
The following NEW packages will be installed:
  jabref
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/187 MB of archives.
After this operation, 227 MB of additional disk space will be used.
Get:1 ~/Scaricati/App/jabref_5.8_amd64.deb jabref amd64 5.8.60000 [187 MB]
dpkg-deb: error: archive '~/Scaricati/App/jabref_5.8_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up dpkg: error processing archive ~/Scaricati/App/jabref_5.8_amd64.deb
 (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 ~/Scaricati/App/jabref_5.8_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

</details>

**Comment by Doc73** [comment]
Here is another info, maybe useful: [https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg](https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg)

**Comment by calixtus** [comment]
Thanks for the quick feedback. Looks like this is a debian / jdk jpackage issue. As a temporary workaround I suggest using the portable version of jabref 5.8.

**Comment by Siedlerchr** [comment]
Related https://bugs.openjdk.org/browse/JDK-8293629

**Comment by koppor** [comment]
Debian eventually will support it https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664 - the concrete date is not known. Google did not find anything for OpenJDK, so I asked the twitter brain: https://twitter.com/koppor/status/1604586662436442112

**Comment by Doc73** [comment]
@koppor 
Debian freeze is sheduled for 2023-01-12 (cf. [https://release.debian.org/bookworm/freeze_policy.html](https://release.debian.org/bookworm/freeze_policy.html)), but even if they add support for this library in v. 12 Bookworm, it will hardly be available for current stable v. 11 Bullseye.

**Comment by einhander** [comment]
Binary packages should be more compatible as possible, currently no Debian release support zstd compression for deb files.

**Comment by Siedlerchr** [comment]
Well, it's an issue of the jdk itself, but maybe we can change the
compression level or repackage the deb files. In the forum someone wrote a
solution to that.
Alternatively, we could try if this works, but I have no idea where and if
jpackage can pick this up

 https://stackoverflow.com/a/72359798/3450689

Spitsyn Andrey Aleksandrovich ***@***.***> schrieb am Di.,
27. Dez. 2022, 10:55:

**Comment by Siedlerchr** [comment]
For reference: 
https://discourse.jabref.org/t/jabref-5-8-release/3671/3?u=siedlerchr

**Comment by Siedlerchr** [comment]
@Doc73  I implemented the repacking stuff mentioned in the forum now for the deb file workflow, can you please test if this version works? https://builds.jabref.org/pull/9506/merge/

**Comment by Doc73** [comment]
@Siedlerchr 
I can confirm that this deb works perfectly, but I tested it in a Debian Unstable (Sid) in my laptop.
I guess it works also in a Debian Stable, but I won't be able to check until January 9-10.

OT: sometime i will report another problem that happens when the application is uninstalled. I have to remember that! :smile:
