### ISSUE TITLE
Deleting multiple linked files should show a single confirmation dialog

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#9473]
Follow up to #8659

When multiple linked items are removed, JabRef will show the "Delete the selected file permanently from disk" dialogue for each item separately. E.g., if the user removes 3 linked items, the dialogue asking whether the respective file should be deleted from disk or should just be removed from entry will be shown 3 times.

This is not the expected behaviour - instead the user would expect to answer this dialogue once for all items that were selected. So if the user selects the option "Remove from entry" from the dialogue, then this should be applied to all linked entries that have been selected for removal (not for each entry separately).

*Originally posted by @AEgit*

To view the linked files of an entry, follow these steps:

1. Open JabRef and open the entry editor for an item to which multiple files are linked (e.g., article + several supplements)
2. Navigate to the "General" tab and then go to the row "File"

**Comment by shreverr** [comment]
Can I work on this issue?

**Comment by HoussemNasri** [comment]
Sure, go ahead!

**Comment by shreverr** [comment]
The deleteFile() method in LinkedFilesEditorViewModel calls delete() method in LinkedFileViewModel.
In the delete() method a new dialog opens every time when delete() method is called to delete a file.
![image](https://user-images.githubusercontent.com/108074738/211189958-d1698824-2629-42f8-80eb-c1acef3db730.png)
![image](https://user-images.githubusercontent.com/108074738/211190000-78d436d3-7554-46bd-9dcb-f87c67bff412.png)
should I move the code of delete() method to deleteFile() method and only use delete() method to delete the file from disk.

This way the the dialog will be called only once.

**Comment by HoussemNasri** [comment]
I don't think moving `delete` to `deleteFile` will fix the issue. The problem here is that whenever a delete event is detected *(e.g. User hits the delete keystroke)*  we are calling `deleteFile` for each selected file thus multiple dialogs show up. What you want to do is to call `deleteFile` only once when a delete event occurs.

Also, you don't want to display the same dialog when user tries to delete **one file** vs **multiple files**.

Here is an example of what IntelliJ does when user tries to delete a file(s):

**One File**

![image](https://user-images.githubusercontent.com/21198231/211194794-1737a5e5-d87d-4cd7-b4bd-aa3ea3197e9e.png)

**Multiple Files**

![image](https://user-images.githubusercontent.com/21198231/211194787-5cf51921-667b-4315-acbe-7092302a020c.png)


**Code Hint**
Lookup this class and see what happens when a user hits the delete keystroke

https://github.com/JabRef/jabref/blob/fb80915f390a5c2d9e6b8b7477dee55eca8e8f15/src/main/java/org/jabref/gui/fieldeditors/LinkedFilesEditor.java#L68

**Comment by Ravitwr** [comment]
Hi @HoussemNasri ,
I can work on this issue if there are no updates.I think the dialog box gui needs to be moved from LinkedFilesEditorViewModel to LinkedFilesEditor. Also do we want to list file names in case of deletion of multilple files ?

**Comment by shreverr** [comment]
Hi @Ravitwr ,
I am currently working on this.
I am sorry was not able to work on this last week due to some personal reasons.

**Comment by 009-KumarJi** [comment]
i want to work on this issue. please assign me this issue. :)

**Comment by HoussemNasri** [comment]
@009-KumarJi Someone already started working on this, there is plenty of other [good first issues](https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) you can pick from.

**Comment by hiddevanesch** [comment]
Hi, since there hasn't been much activity regarding this issue, can I please be assigned to this issue? I would like to work on this for a uni project.
