### ISSUE TITLE
Browser extension doesn't work with local app install on MacOS

### ISSUE THREAD

**Issue by allydunham** [JabRef/jabref#9474]
### JabRef version

5.8 (latest release)

### Operating system

macOS

### Details on version and operating system

OSX 12.6

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Importing references through the browser extension fails when JabRef is installed to ~/Applications on MacOS. This initally seems like it occurs because org.jabref.jabref.json points to the wrong path but the issue continues after this is fixed because the hardcoded path in jabrefHost.py points to the system Applications directory.

Steps to reproduce:
1. Install JabRef to ~/Applications
2. Install browser extension (tested on firefox)
3. Try to import a reference

I manually fix this each install by hardcoding the application path in jabrefHost.py to point to ~/Applications/JabRef.app/Contents/MacOS/JabRef. Similarly the correct path must be set in the JSON when installing the browser extension itself.

I noticed the comment above the path in jabrefHost.py (which doesn't work correctly on Mac) so possibly it's hard to automatically detect the location. Similarly, the JSON is necessarily hardcoded I imagine. If so, it would at least be useful to say for how to correct the problem in the browser extension install instructions.

### Appendix

...
<details>

Only a generic error is produced:

![Screenshot 2022-12-19 at 10 55 34](https://user-images.githubusercontent.com/30415561/208409598-559b655a-4cca-46ed-bbd6-08a7a73b578d.png)

</details>

**Comment by allydunham** [comment]
I have also noticed now that I don't need to hardcode the path, this change automatically finds the application path for me:

```python
script_dir = Path(__file__).resolve().parent.parent
JABREF_PATH = script_dir / "bin/JabRef"
if not JABREF_PATH.exists():
    JABREF_PATH = script_dir / "MacOS/JabRef"
```

I'm not able to test it on other platforms, although I don't see why it wouldn't work as only the OSX part is changed.

I'm happy to add some notes to the docs as well, either for updating just the JSON or the application path in the script as well, depending on if you change the py script. Where would I do that?

**Comment by Siedlerchr** [comment]
So it seems like the modifying the py script directly is the easiest option and would work for all other cases as well. It is located here https://github.com/JabRef/jabref/blob/main/buildres/mac/jabrefHost.py 

Then it would only be necessary for the user to adjust the json file pointing to the right directory

**Comment by allydunham** [comment]
That would be much easier than the current situation too - any edits to the script are overwriten when JabRef updates, whereas the json doesn't seem to be update often, at least in my experiance.

I'm still happy to write up changes to the docs and/or script when I have time, if that's useful? Although as I said I don't really have the setup/expertise to properly test the script changes, so might be easier for someone else.

**Comment by Siedlerchr** [comment]
I think we can modify the python script based on your suggestion earlier so that in the next version of JabRef users don't have to adjust it. So the user would only need to adjust the json file. The python script in that folder I linked is only for mac. So feel free to make a PR with the changes to the python file

And then just add a note to the docs for modifying the json file
