### ISSUE TITLE
Double-click on preview style should add it to "Selected"

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9490]
**Is your suggestion for improvement related to a problem? Please describe.**
I always want to use a double click to transfer a style to the other list 

**Describe the solution you'd like**
Preferences → Entry Preview 
1. Double-click on one of the styles in "Available"   should add it to the "Selected" list view
2. Double-click on one of the styles in "Selected"  should remove it from the "Selected" list view 

**Additional context**
![image](https://user-images.githubusercontent.com/1366654/203511710-cb75ea51-f8fa-476f-8610-dffde3c061b5.png)

**Implementation notes:**

PreviewTab under gui/preferences needs to be adjusted.
Add a click handler `withOnMouseClickedEvent` to the listViews and check for a double click

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/14)
