### ISSUE TITLE
Reevaluate OpenFile workaround

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#95]
The code includes a specific workaround for opening files on Windows 9x (Microsoft Windows 95, 98, 98 SE und ME).
Reported by this bug: http://sourceforge.net/tracker/index.php?func=detail&aid=1489454&group_id=92314&atid=600306
We should reevaluate if the code is still necessary for Java 8 support.
See https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/util/Util.java#L484

**Comment by simonharrer** [comment]
I think we can simplify the code as we can drop support for Windows 95/98. :)
