### ISSUE TITLE
Converging cleanup actions?

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#953]
Are we sure that all cleanup actions "converge", i. e.  that another run doesn't modify the field again? Especially, it would be problematic if the action results in a loop. Slightly less if multiple runs are required before convergence.

**Comment by simonharrer** [comment]
We could write a test that ensures this. Just apply the results again and assert that nothing changed. Especially important for the save actions as this would destroy the data a little bit more on each save.

**Comment by oscargus** [comment]
I was thinking about how to test this. Seems like it is really data dependent... But clearly some sort of testing should be included.

An option may be that when invoking the cleanup action it is executed until convergence and if more than 10(?) executions are needed it is stopped and a log message is printed which encourage the user to report the problem with provided data.

**Comment by simonharrer** [comment]
Idea: a is formatted to b, then b is formatted to c. If b != c keep a, and print a message in the log that this could not be changed because this would result in broken data. 

The tests can work the same way for all test input we have and use.

**Comment by koppor** [comment]
I think, the user is responsible to do it. For instance, if the user chooses both, Unicode to LaTeX and LaTeX to Unicode, the order really matters. I think, the list in the Cleanup dialog should be (already is?) interpreted as list during the implementation, too.

I thought that the cleanups are applied from top to bottom in the UI. Each cleanup executed once. Applying them unitl the entry converges feels counter inutitive to me.

What we could do is to issue a warning if there are cyclic formatters are applied.

Refs #1013 and #959.

**Comment by oscargus** [comment]
I was more thinking of the same formatter changing the format. Indeed running "reverse" formatters is the responsibility of the user (but it might make sense to somehow indicate this).

@simonharrer : should this be in the program or in the tests? I think it makes sense, but I also know of at least one formatter that may fail (the LatexCleanup one, which only cleanup parts of the code, so have really weird code like {{{A}{B}}{{C}{{D}{E}}}{F}} might take a few iterations to get back to {ABCDEF}...

**Comment by tobiasdiez** [comment]
As it was pointed out above, convergence really depends on the formatter and the input. So a general test does not make sense. 

Thus I will close this issue. If we recognize that one of the formatters has convergence problems, then we can open a specific issue for it.
