### ISSUE TITLE
Rewrite code of ModsImporter

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9537]
The class `org.jabref.logic.importer.fileformat.ModsImporter` uses JAXB, but can be rewritten using a [StAX-Parser](https://mkyong.com/java/how-to-read-xml-file-in-java-stax-parser/) and thus getting rid of a JAXB dependency.

The current code uses JAXB's internal data to get to the XML element. Example:

```java
        for (JAXBElement<?> jaxbElement : topicOrGeographicOrTemporal) {
            Object value = jaxbElement.getValue();
            String elementName = jaxbElement.getName().getLocalPart();
```

This can be directly done using StAX' capabilities.

**Comment by aqurilla** [comment]
Hi! I would like to take up this issue

**Comment by aqurilla** [comment]
For this fix, do we also remove all usage of the generated classes in `src-gen/main/java/org/jabref/logic/importer/fileformat/mods/*`, from `org.jabref.logic.importer.fileformat.ModsImporter`?

**Comment by aqurilla** [comment]
Thanks for clarifying that!

**Comment by aqurilla** [comment]
Hi @Siedlerchr, the classes generated through the `generateModsSource` xjc task are also used in the MODS exporter class `org.jabref.logic.exporter.fileformat.ModsExporter` -

https://github.com/JabRef/jabref/blob/75df9a3e3dacde8c986a44777a75596c0f9e84da/src/main/java/org/jabref/logic/exporter/ModsExporter.java#L13-L41

Does the scope of this issue fix also include removing these dependencies from the exporter?

**Comment by aqurilla** [comment]
Hi @Siedlerchr, could you please take a look at my PR for this issue
