### ISSUE TITLE
Remove support for BibTeXML

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9540]
Since more than a decade, we support [BibTeX as XML](https://bibtexml.sourceforge.net/) as import and export format.

Although the code is clean, it seems that BibTeXML is not used by anyone - and even the original author says, it is dead. See https://github.com/Zearin/BibTeXML/issues/1

This would mean to remove

- org.jabref.logic.importer.fileformat.BibTeXMLImporter
- org.jabref.logic.exporter.BibTeXMLExporter

and related classes / test files.

**Comment by sreenath-tm** [comment]
Hi, I would like to contribute to this issue. I have removed the mentioned files and the corresponding files and their references. Can you assign me this issue or can I directly raise the pull request?

**Comment by sreenath-tm** [comment]
I have raised the PR can you please take a look if it looks good?
