### ISSUE TITLE
where is the latest development build?

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#9554]
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Hello,
a strange behaviour - maybe not an issue, but here it meets the appropriate audience, I am pretty sure. But, of course, I apologise for "abusing" this system for this issue.

Recently I managed to download and test the 6.0 development version, downloading from `https://builds.jabref.org/main/`. That is also the process I routinely used for years.

Now, when I try to uninstall JabRef on Fedora Linux with `dnf remove jabref -y`, I get this error message:

...
<details>

<summary>dnf error message</summary>

```
rm: cannot remove '/opt/google/chrome/extensions/bifehkofibaamoeaopjglfkddgkijdlh.json': No such file or directory
rm: cannot remove '/usr/share/google-chrome/extensions/bifehkofibaamoeaopjglfkddgkijdlh.json': No such file or directory
/var/tmp/rpm-tmp.vqGznV: line 12: UTILITY_SCRIPTS: command not found
/var/tmp/rpm-tmp.vqGznV: line 15: uninstall_default_mime_handler: command not found
error: %preun(jabref-5.9.6-1.x86_64) scriptlet failed, exit status 127
```
same error with `jabref-6.0.3206-1.x86_64`.

</details>

Hm, I can of course mark my JabRef versions as removed with dnf, but here I like to raise the issue that I miss the development version. And maybe the related issue about the `bifehkofibaamoeaopjglfkddgkijdlh.json` file.

**Comment by Siedlerchr** [comment]
Hi,
thanks for the feedback.
For the missing dev version: It seems like there is something not yet correct again with the automatic versioning after the 5.9 release (it was a bit tricky to get a 5.9 release in between 5.8 and 6.0 dev). It seems like the dev version is now at 5.9.1..

For the uninstallation: I can only say that this json file is part/needed for the JabRef-Browser extension to communicate with JabRef. And I think the error is coming from the spec file: Maybe rm needs to check for existence first? 
https://github.com/JabRef/jabref/blob/main/buildres/linux/jabref.spec

**Comment by Siedlerchr** [comment]
The latest development build is now back again. We decided to continue with 5.10 in case we do another release somewhere in the near future

**Comment by ilippert** [comment]
Ok, given the existence of the dev version, I close this issue, and instead focus another on the spec file issue.
