### ISSUE TITLE
spec file rpm preventing removal

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#9558]
### JabRef version

5.9 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I have installed various JabRef versions – well so it seems because the upgrade/removal does not work properly.
For reference, I have 
jabref.x86_64                                                         5.9.6-1                                                  
jabref.x86_64                                                         5.10.10-1                                                  
jabref.x86_64                                                         6.0.3206-1                                                   

And as @Siedlerchr suggested in https://github.com/JabRef/jabref/issues/9554#issuecomment-1377914560 the error message reported in https://github.com/JabRef/jabref/issues/9554#issue-1528011129 might be related to a missing check for file existence in the spec file.

**Comment by sambo57u** [comment]
I can confirm this. It did create a mess. I could remove them one by one via:
rpm -e  --allmatches --nodeps --noscripts  _PackageName_

**Comment by Siedlerchr** [comment]
The spec file is here: https://github.com/JabRef/jabref/blob/main/buildres/linux/jabref.spec 
Feel free to create a PR modifying it

**Comment by Siedlerchr** [comment]
@ilippert  can you test if this version works with installing/uninstalling? https://builds.jabref.org/pull/9604/merge/
I modified the rm command, but have no Linux system here to test this

**Comment by ilippert** [comment]
> @ilippert can you test if this version works with installing/uninstalling? https://builds.jabref.org/pull/9604/merge/ I modified the rm command, but have no Linux system here to test this
installing works.

removing results in 


```
Running transaction
  Preparing        :                                                                                                                          1/1 
  Running scriptlet: jabref-5.10.30121-1.x86_64                                                                                               1/1 
/var/tmp/rpm-tmp.AcSTvP: line 12: UTILITY_SCRIPTS: command not found
/var/tmp/rpm-tmp.AcSTvP: line 15: uninstall_default_mime_handler: command not found
error: %preun(jabref-5.10.30121-1.x86_64) scriptlet failed, exit status 127

Error in PREUN scriptlet in rpm package jabref
  Verifying        : jabref-5.10.30121-1.x86_64                                                                                               1/1 

Failed:
  jabref-5.10.30121-1.x86_64                                                                                                                      

Error: Transaction failed
```

an error still.

**Comment by ilippert** [comment]
this installs and removes without friction. thanks a lot!
