### ISSUE TITLE
Save actions: better field selection

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#957]
At "Save sort order" in the same dialog, one can also select a field. I would have expected the same choice for the selection of the fields to apply the save action. Is that possible? Reason: I am too lazy to input the field name manually.

![grabbed_20160313-212741](https://cloud.githubusercontent.com/assets/1366654/13731147/ab897bee-e962-11e5-84ff-a9546b62021e.png)

**Comment by simonharrer** [comment]
Please not that there is the "special field" "all" which applies the save action on all fields.

**Comment by Siedlerchr** [comment]
I will look into this, Together with #958

**Comment by koppor** [comment]
@Siedlerchr Yes, I know. That was sort of a quick hack to enable quick selection of common fields, but also the input of arbitrary fields (not contained in the combobox list). Don't know, whether that's possible with a normal JCombobox, too.

**Comment by Siedlerchr** [comment]
For the sort criterion:
A solution to this would be to use an Editable Combobox (Default Combobox with Editable=true)
https://docs.oracle.com/javase/tutorial/uiswing/components/combobox.html#editable
- Enables the selection of items
- Add new items not in the list of the combobox.
=> This would make the textfield unnecessary.

For the Save Action I would suggest the same solution

**Comment by Siedlerchr** [comment]
This save sort order selection with the Combobox and the Textfield is also used in the Preferences->Export sorting, it is the same class which is used for both.

A rework would then profit in both cases.
