### ISSUE TITLE
Highlight colors for differences in three-way merge editor in dark mode make readability pretty hard

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#9575]
**Is your suggestion for improvement related to a problem? Please describe.**
Not sure whether this is a bug (possibly related to mixing of colors or text color).

See screenshot:
![grafik](https://user-images.githubusercontent.com/6171135/213878310-124e42a6-b76b-4ccc-8ce0-d249bf4c5101.png)

This doesn't look intentional. Especially the green color makes reading almost impossible.

**Describe the solution you'd like**
Change either font color or highlight color or both (or another solution) to improve readability.

**Comment by Siedlerchr** [comment]
Hi, have you testest the latest dev version? There was just recently a PR which fixed that https://github.com/JabRef/jabref/pull/9546

**Comment by claell** [comment]
Thanks, it's a duplicate of #9192, then. Didn't catch that issue. Nice to see it's already fixed in the development versions!

**Comment by claell** [comment]
You can close this as duplicate, then.
