### ISSUE TITLE
Synchronize scrollbars in the change resolver dialog

### ISSUE THREAD

**Issue by HoussemNasri** [JabRef/jabref#9576]
![image](https://user-images.githubusercontent.com/21198231/213894591-c7496040-050e-4aed-98ea-9a1d12c94fd4.png)

**Comment by DanielS01ss** [comment]
Hi!
I would love to work on this task

**Comment by HoussemNasri** [comment]
This issue is kind of a follow-up to https://github.com/JabRef/jabref/pull/9533, so there is nothing to do here until that pr is merged. But you can have a look at other [goodfirstissues](https://github.com/JabRef/jabref/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by karan-prajapati-976** [comment]
Hey 
I would like to work on this task

**Comment by u7074786** [comment]
Hi, I would like to work on this issue for a university assignment of mine, could I please be assigned to it?

I'm new to working on open source repos like this, so some suggestions on where to get started would also be appreciated.

**Comment by ThiloteE** [comment]
@u7074786 this issue here is realted to the backups feature, as you can see in the screenshot. Have a look at the docs: https://docs.jabref.org/advanced/autosave#where-can-i-find-the-backup-files. You can trigger the backup dialogue by

1. creating a library (the .bib file) with entries
2. then saving this library and closing JabRef
3. modifying your .bib file outside JabRef with a text editor (e.g. changing the title of an entry)
4. Starting JabRef and opening the library.

This should trigger the backup dialogue, if I am not mistaken.

**Comment by HoussemNasri** [comment]
> then saving this library and closing JabRef

You don't need to close JabRef at step 2.

> I'm new to working on open-source repos like this, so some suggestions on where to get started would also be appreciated.

In addition, to what ThiloteE has already said, this is the [class](https://github.com/JabRef/jabref/blob/a0e2564806050247bce6056a6c108b87bab315b3/src/main/java/org/jabref/gui/collab/entrychange/EntryChangeDetailsView.java#L43) that you need to change. The idea is to synchronize the vertical scroll bar of the entry preview (and BibTeX source code preview) of the original entry and the modified entry. I also encourage you to read the JavaDoc of the [`ScrollPane`](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/ScrollPane.html) class.

**Comment by u7074786** [comment]
I'm having some trouble figuring out the implementation of this issue:

Just setting up a binding for the ScrollPane's vvalueProperty doesn't appear to do anything, and curiously setting vbarPolicyProperty to always display causes the window to display two separate scroll bars, which leads me to think that the scroll bar in question may not be the one from the ScrollPane itself.

I'm not too familiar with the workings of JavaFX, but it looks to me like the scroll bar here might be from the [WebView used in PreviewViewer](https://github.com/JabRef/jabref/blob/main/src/main/java/org/jabref/gui/preview/PreviewViewer.java#L126)? The [documentation](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/WebView.html) for WebViews do mention that scrolling is handled within it, but I'm unsure as to how two such web views would be synchronised. Could I please get some advice on how to approach this?

**Comment by koppor** [comment]
BibTeX source synch is still open (see https://github.com/JabRef/jabref/pull/10587#issuecomment-1783749348 for details)
