### ISSUE TITLE
Size of database properties dialog

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#958]
The size of the database properties dialog is not fixed. When opening the dialog the first time, it seems to be not high enough.

The dialog should be of a fixed size or at least high enough at the first start.

**Comment by Siedlerchr** [comment]
I did not notice a problem on Win7. The only thing is that the space between the last two buttons (bottom center) and the margin looks too small.

**Comment by simonharrer** [comment]
If you are already at this, maybe you could have a look at replacing the JLabel for the description of the currently selected save action with something like a text area which is used in the about dialog.

**Comment by matthiasgeiger** [comment]
The problem is visible in the screenshot @koppor posted at #957: With win10 the buttons are cut a few pixels. Increasing the size of the dialog for 10-20px should be sufficient to show the buttons correctly.

**Comment by Siedlerchr** [comment]
Another thing I noticed is that the size of the "Minus" Button (CSS-Icon) is bigger than the Reset Button.
![iconbuttondbproperties](https://cloud.githubusercontent.com/assets/320228/13775999/f83c444e-eaa7-11e5-8b9e-eb9a2ee10b87.png)

Any idea how to scale the Buttons correctly? Never worked with jgoodies before.

**Comment by Siedlerchr** [comment]
This can be closed.
