### ISSUE TITLE
Command line export does not create an output bib file

### ISSUE THREAD

**Issue by guillaumeparent** [JabRef/jabref#9581]
### JabRef version

5.9 (latest release)

### Operating system

MacOS

### Details on version and operating system

MacOS Ventura 13.0.1 (22A400)

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I am trying to create sub-databases (one database by author) from a global .bib file using the filtering features of the command line tool. Here is the commande I use to filter only AuthorOneName related papers from the global Input_bib.bib file:

`JabRef --exportMatches Author=AuthorOneName,Output_bib.bib,bib -i Input_bib.bib -n`

I do not receive any error message, everything seems to be ok, including the filtering. Nevertheless, no output file is created.
Important information: it fails when using bib format as output, but it works for other formats such as bibtexml, endnote, html for instance.

Am I doing something wrong or is it a bug related to the bib format ? 

### Appendix

<details>

<summary>Input_bib.bib</summary>

```
@article{AutOne2022,
author = 	 {AuthorOneName, AuthorOneFirstName and AuthorTwoName, AuthorTwoFirstName},
title = 	 {An interesting paper},
journal = 	 {Mickey Mouse Magazine},
year = 	 {2023}
}

@article{AutTwo2023,
author = 	 {AuthorOneName, AuthorOneFirstName and AuthorTwoName, AuthorTwoFirstName},
title = 	 {Another interesting paper},
journal = 	 {Donald Duck Magazine},
year = 	 {2023}
}

@Article{AutThree,
  author  = {AuthorThreeName, AuthorThree3FirstName and AuthorTwoName, AuthorTwoFirstName},
  journal = {I love datahseets magazine},
  title   = {Look at this one},
  year    = {2021},
}

@Comment{jabref-meta: databaseType:bibtex;}
```

</details>

**Comment by guillaumeparent** [comment]
Sorry, OS was not good in the the description.

**Comment by Siedlerchr** [comment]
I could reproduce this. I found out that the "bib" format seems to match the EmbeddedBibTexExporter which will embed bib files into a pdf. 
And second, I found out there is no BibTexExporter that could be used with the matcher option...
So I think you stumbled across an edge case that no one thought about before...
Will flag this as enhancement

**Comment by guillaumeparent** [comment]
Thank you for the answer.

But are you sure the issue is related to the matcher option ?
I tried to convert a .ris file into a .bib file, without filtering as follows and it did not create any output file either.
`JabRef -o Output_bib.bib,bib -i Intput_bib.ris -n `

On another hand, I tried the same command but this time with a bibtexml as an output and it worked perfectly well.
`abRef -o Output_bib.xml,bibtexml -i Intput_bib.ris -n `

So couldn't the issue be related to exporting a .bib file ?

I add the .ris file for reproduction purpose:

TY  - JOUR
AU  - AuthorOneName, AuthorOneFirstName
AU  - AuthorTwoName, AuthorTwoFirstName
T1  - An interesting paper
JO  - Mickey Mouse Magazine
Y1  - 2023
ER  -
TY  - JOUR
AU  - AuthorOneName, AuthorOneFirstName
AU  - AuthorTwoName, AuthorTwoFirstName
T1  - Another interesting paper
JO  - Donald Duck Magazine
Y1  - 2023
ER  -

**Comment by Siedlerchr** [comment]
From what I saw when you don't specify the output formant in the export command, it will use bibtex as default

**Comment by Shubhra0310** [comment]
i want to work on this issue

**Comment by guillaumeparent** [comment]
Problem solved in the latest build. Thank you very much, it works like a charm.
