### ISSUE TITLE
Astrophysics Data System and Semantic Scholar fetcher test fail

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9589]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

content differs

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by astroboylrx** [comment]
I found that, when using ADS fetcher, whenever I input the Bibcode, it would generate a pop-up error message box, saying "Import Error: could not find a suitable import format", which is quite annoying.

![image](https://user-images.githubusercontent.com/3999966/217535640-81b49d2c-86a8-47e3-9b00-7a7893566cd7.png)

However, it seems that I can still fetch articles after closing the error message...

**Comment by subhramit** [comment]
(Info)
No issues with format with regards to the json received and parsed.
Sample json:
```{"msg": "Retrieved 1 abstracts, starting with number 1.", "export": "@ARTICLE{2021AJ....161...24G,\\n author = {{Giacalone}, Steven and {Dressing}, Courtney D. and {Jensen}, Eric L.~N. and {Collins}, Karen A. and {Ricker}, George R. and {Vanderspek}, Roland and {Seager}, S. and {Winn}, Joshua N. and {Jenkins}, Jon M. and {Barclay}, Thomas and {Barkaoui}, Khalid and {Cadieux}, Charles and {Charbonneau}, David and {Collins}, Kevin I. and {Conti}, Dennis M. and {Doyon}, Ren{\\\\'e} and {Evans}, Phil and {Ghachoui}, Mourad and {Gillon}, Micha{\\\\\\"e}l and {Guerrero}, Natalia M. and {Hart}, Rhodes and {Jehin}, Emmanu{\\\\\\"e}l and {Kielkopf}, John F. and {McLean}, Brian and {Murgas}, Felipe and {Palle}, Enric and {Parviainen}, Hannu and {Pozuelos}, Francisco J. and {Relles}, Howard M. and {Shporer}, Avi and {Socia}, Quentin and {Stockdale}, Chris and {Tan}, Thiam-Guan and {Torres}, Guillermo and {Twicken}, Joseph D. and {Waalkes}, William C. and {Waite}, Ian A.},\\n title = \\"{Vetting of 384 TESS Objects of Interest with TRICERATOPS and Statistical Validation of 12 Planet Candidates}\\",\\n journal = {\\\\aj},\\n keywords = {Exoplanet astronomy, Astrostatistics, Planet hosting stars, Exoplanets, 486, 1882, 1242, 498, Astrophysics - Earth and Planetary Astrophysics, Astrophysics - Instrumentation and Methods for Astrophysics, Astrophysics - Solar and Stellar Astrophysics},\\n year = 2021,\\n month = jan,\\n volume = {161},\\n number = {1},\\n eid = {24},\\n pages = {24},\\n abstract = \\"{We present TRICERATOPS, a new Bayesian tool that can be used to vet and\\n validate TESS Objects of Interest (TOIs). We test the tool on 68\\n TOIs that have been previously confirmed as planets or rejected\\n as astrophysical false positives. By looking in the false-\\n positive probability (FPP)-nearby false-positive probability\\n (NFPP) plane, we define criteria that TOIs must meet to be\\n classified as validated planets (FPP < 0.015 and NFPP <\\n 10$^{-3}$), likely planets (FPP < 0.5 and NFPP < 10$^{-3}$), and\\n likely nearby false positives (NFPP > 10$^{-1}$). We apply this\\n procedure on 384 unclassified TOIs and statistically validate\\n 12, classify 125 as likely planets, and classify 52 as likely\\n nearby false positives. Of the 12 statistically validated\\n planets, 9 are newly validated. TRICERATOPS is currently the\\n only TESS vetting and validation tool that models transits from\\n nearby contaminant stars in addition to the target star. We\\n therefore encourage use of this tool to prioritize follow-up\\n observations that confirm bona fide planets and identify false\\n positives originating from nearby stars.}\\",\\n doi = {10.3847/1538-3881/abc6af},\\narchivePrefix = {arXiv},\\n eprint = {2002.00691},\\n primaryClass = {astro-ph.EP},\\n adsurl = {https://ui.adsabs.harvard.edu/abs/2021AJ....161...24G},\\n adsnote = {Provided by the SAO/NASA Astrophysics Data System}\\n}\\n\\n"}```

**Comment by koppor** [comment]
One can check failing fetcher tests at https://github.com/JabRef/jabref/actions/workflows/tests-fetchers.yml

**Comment by koppor** [comment]
@subhramit Most failing fetcher tests are because of slightly different data returned. The fix is then to adapt the test cases. Should be easy to contribute?

**Comment by subhramit** [comment]
Yep, looks like that. Getting to it as soon as I can.

**Comment by koppor** [comment]
I will close this issue as fetchers evolved the last months. We track down other fetcher issues at https://github.com/JabRef/jabref/issues?q=is%3Aopen+label%3Afetcher+sort%3Aupdated-desc. Follow-up will PRs by @subhramit and other fixes.
