### ISSUE TITLE
Cleanup entries: Rely on "field formatter"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#959]
The first two cleanups can be achieved using the "field formatters".

- [ ] "Run Unicode converter on title, author(s), and abstract". Even though this affects multiple fields, this should be configured in "Run field formatter". 
- [ ] "Convert 1st, 2nd, ... to real superscripts". Even though this also affects multiple fields, this should also be configured in "Run field formatter". 
- [ ] With the fieldname `all` is it possible to target all fields. This should be documented somewhere. Currently, the gray text at "Enter field name" doesn't show that.

![grabbed_20160314-085315](https://cloud.githubusercontent.com/assets/1366654/13738037/330a638a-e9c2-11e5-8ca9-b7e596147328.png)

**Comment by tobiasdiez** [comment]
All the points are already fixed in the latest master version.
