### ISSUE TITLE
bib file does not load

### ISSUE THREAD

**Issue by ashrafnabhan** [JabRef/jabref#9592]
### JabRef version

5.9 (latest release)

### Operating system

macOS

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. click on bib file
2. jabref loads
3. the library is not loaded
4. but if I open jabref first then click file>recent libraries>the library opens

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Could you please upload your .bib file here? I have the suspicion that some characters or special symbols will prevent proper opening/import. Only, if your file is not of sensitive nature, of course.

You can also try to debug this on your own by

1. creating a backup of your file
2. opening your file via texteditor
3. Deleting "entries" (and saving) until JabRef can open the file.

**Comment by ashrafnabhan** [comment]
Here is the file. This issue is for all bib files on Mac. It never happens in my other laptops using Linux Mint or Win 10.

.bib files are not supported for adding here

**Comment by ashrafnabhan** [comment]
Thanks for your prompt reply.
Here is the jabref library, attached


Best wishes,
Ashraf
--
Prof. Ashraf Nabhan
Department of Obstetrics and Gynecology, Faculty of Medicine, Ain Shams University


From: ThiloteE ***@***.***>
Date: Wednesday, 1 February 2023 at 4:32 PM
To: JabRef/jabref ***@***.***>
Cc: ashrafnabhan ***@***.***>, Author ***@***.***>
Subject: Re: [JabRef/jabref] bib file does not load (Issue #9592)

Could you please upload your .bib file here? I have the suspicion that some characters or special symbols will prevent proper opening/import. Only, if your file is not of sensitive nature, of course.

You can also try to debug this on your own by

  1.  creating a backup of your file
  2.  opening your file via texteditor
  3.  Deleting "entries" (and saving) until JabRef can open the file.

**Comment by Siedlerchr** [comment]
@ashrafnabhan You have to upload the file on github itself, attachments in emails do not work.

**Comment by ThiloteE** [comment]
Closing to reduce the number of open issues. Feel free to reopen, if you manage to upload the file.
