### ISSUE TITLE
Remove trailing ; at metadata

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#960]
While reading test cases of the metadata serialization, I saw that the final `;` seems to be mandatory (e.g., https://github.com/tobiasdiez/jabref/commit/174b49b062755f11c3f2ead75381cdb7376e0176).

Is that true? Can we get rid of that? This feels so 90ies ;).

**Comment by simonharrer** [comment]
No objections, but we still need to be able to parse the old format. But we can write the new one.

**Comment by stefan-kolb** [comment]
Also see #1331 Maybe this even is an issue?

**Comment by tobiasdiez** [comment]
I think this the trailing `;` is not a big deal and we should focus on https://github.com/koppor/jabref/issues/232 if we really want to improve our metadata serialization -> closed (if you really want this, reopen or better implement it directly)
