### ISSUE TITLE
Set a minHeight and a minWidth for the main window

### ISSUE THREAD

**Issue by waterflow80** [JabRef/jabref#9606]
**Is your suggestion for improvement related to a problem? Please describe.**
The JabRef main window has no minimum width or height. So you can decrease the 
size until it can be no longer seen. Which I think is not a good thing. 
(See 'Window before change' in the **Additional context** below &darr;)

**Describe the solution you'd like**
I simply suggest to add a `setMinHeight` and a `setMinWidth` in the `openWindow()` method under
**JabRefGui** class.
![code-after-edit](https://user-images.githubusercontent.com/82417779/217591310-19a3c90a-857a-475d-8174-b43fe02d90d2.png)

I have chosen the values of `minWidth` and `minHeight` as follows:
- `minWidth`:
  - ![window-with](https://user-images.githubusercontent.com/82417779/217580675-61f11f78-d601-46b0-94b2-346809b2ce89.png)
  - I've chosen the `width` in a way that the up menu bar keeps displaying all its 
  content (**File**, **Edit**, **...**) after resize (after decreasing the size).
  - It's about **580px** (Using Ubuntu 20.04).

- `minHeight`:
  - ![min-height](https://user-images.githubusercontent.com/82417779/217593094-d101fd60-ffd4-4f28-89e8-7dbb87870f4f.png)
   - I've chosen the `height` in a way that the element **OpenOffice/LibreOffice** is shown entirely after resize (after decreasing the size).
   I chosen **OpenOffice/LibreOffice** as a reference, because I found that it has the highest height among other elements under 
  the **view** option menu (compared to **Web search** and **Groups**).
- It's about **330px** (Using Ubuntu 20.04).

**Additional context**
- Window before change
![jabref-window-fix](https://user-images.githubusercontent.com/82417779/217584090-834b3c24-e785-4140-abc7-3776d866dc2b.gif)

- Minimum window size after change
![jabref-window-after-change](https://user-images.githubusercontent.com/82417779/217594654-88013437-87b3-4b61-8046-78866d351f64.gif)

**Other**
Looking forward to hear your feedback, and to make a PR on this.

**Comment by Siedlerchr** [comment]
Thanks. Seems like a good idea!. Btw as you also are using Ubuntu, can you reproduce #9607  ?

**Comment by waterflow80** [comment]
@Siedlerchr Yeah sure, I'll give it a try.

**Comment by koppor** [comment]
We discussed in the DevCall. The feature improves the state of the art and thus we take it.

We accept that JabRef will have issues with [tiling window managers](https://en.wikipedia.org/wiki/Tiling_window_manager) at small screen resolutions. We hope that we will find the point in the code as soon as a user of [dwm](https://dwm.suckless.org/) or similar tools will raise their voice.
