### ISSUE TITLE
Quantifying spaces in regex results in illegal search expression

### ISSUE THREAD

**Issue by XaraB** [JabRef/jabref#962]
* JabRef version (available in the About box): 3.3dev snapshot 29/02/2016
* Operating system and version: Ubuntu 15.10 Wily
* Steps to reproduce:
Quantifying spaces in regex doesn't work. It used to work. All my regex filter are not functionning anymore (and the groups are empty  because the regex is seen as faulty). I do not know what version caused this, however, I suspect it was fine in the version 2.

  1. Type the following regexes in either the search field or a filter regex field. All should work :
     * `a[^b]` : a followed by not b
     * `ab+`: a followed by at least one b
     * `ab*`: a followed by any number of b
     * `ab?`: a optionally followed by a b
     * `a `: a followed by a space
     * `(ab)`: ab in a group
  2. Those won't work and give a `Search failed: illegal search expression`:
     * `a[^ ]`: a followed by not space
     * `a +`: a followed by at least one space
     * `a *`: a followed by any number of spaces
     * `a ?`: a optionally followed by a space
     * `(a b)`: a b in a group, with space in the middle

Is this a desired behaviour ? I frequently use `[^ ]` to designate anything but a space and frequently put in alternatives such as : `(word and paradigm)|(item and arrangment)`.

**Comment by stefan-kolb** [comment]
A whitespace is typically represented as `\s` in a Regex, e.g. `a[^\s]`. therefore, I would say this is expected. let's see what @simonharrer says.

**Comment by koppor** [comment]
I would JabRef like to see easy handling of spaces. Don't know whether that's easy to implement.

**Comment by XaraB** [comment]
Indeed stefan-kold, however, "\s" matches any whitespace. Usually the space (" ") is a valid regex character. One could want to match " " but not "\t" or "\n". When one exclusively wants to match spaces, using the space character is also more legible. Since it was working before, I hope it wouldn't be too hard to re-implement !

**Comment by stefan-kolb** [comment]
The Problem is the SentenceAnalyzer which splits the search query based on whitespaces.

**Comment by simonharrer** [comment]
Hm, the problem probably has been introduced by combining the search in the UI with the search in the groups. The proposal makes sense.
