### ISSUE TITLE
prerefences cannot be changed or saved

### ISSUE THREAD

**Issue by jelasity** [JabRef/jabref#9635]
### JabRef version

5.9 (latest release)

### Operating system

linux

### Details on version and operating system

Ubuntu 22.04.2 LTS

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Note that I could not actually test the latest build because I am using jabref as a snap, I am using the latest snap on ubuntu. This could be related to snapd (or not).

Jabref is not able to write any changes to the configuration of the preferences. When I change anything (for example, try to switch do dark mode), an error message pops up, saying 

File > External file lins > Main file directory
Directory not found

and then the change is not applied. I can leave preferences only with "cancel".

I tried real hard to remove the jabref snap, delete every possible jabref related previous configuration, reinstalling the whole thing, and it still behaves like that. The funny thing is that in the preferences in 5.9 there is no longer an option for external file directory, so I can't do anything about replacing it.

The error is present also if I don't load any libraries, right after a fresh install. It is present also if I do load some libraries, in which there is a file directory configured. I removed all prefs.xml files that I could find. I'm quite desperate at this point, I think there must be a bug somewhere, and I really need jabref now.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Hi,

this bug (regarding the warning message) was recently fixed. 
The underlying issue is still snap related but that should not be a problem right now (the default subfolder if no main file directory is configured is invalid inside a snap)
You can also set the main file directory in the Preferences under Linked Fails

You can use the latest dev version by using the edge channel in snap. (better make a backup of your library)

sudo snap install jabref --edge


cc @HoussemNasri

**Comment by jelasity** [comment]
This fixed it, many thanks!

**Comment by ThiloteE** [comment]
Closing this issue, because you reported using the newest development version fixed it.
