### ISSUE TITLE
Context Menu: "Attach File from URL" / "Download File from URL"

### ISSUE THREAD

**Issue by bf** [JabRef/jabref#9646]
**Is your suggestion for improvement related to a problem? Please describe.**
Often times you find the PDF version of a file at a different website than the BIBTex citation. I'd like to have an more easy way to attach the PDF file via URL to a certain entry in my reference library without having to download it first. JabRef should handle download and storing PDF in right location, not me.

**Describe the solution you'd like**
Currently when you right-click on an entry the context menu appears. The context menu has an "Attach File..." button which allows you to use the file chooser to attach a PDF file. However, when doing this, the file is not copied into your "referenced files" folder and if you have the PDF file open in a browser tab you'd need to download it and then select the downloaded file.

**Additional context**
I'm away this functionality "Attach File From Url" is already implemented. But the user experience to get to it is quite cumbersome. First the entry needs to be created for the article, then you need to select it in Jabref, navigate the detail menu to register "General", then go to the "File" list and then on the right of the file list there is a tiny button labeled "Download from URL".

My - and I think many other's - workflow would be much easier if we can just navigate to a page in our browser tab (e.g. the official journal website), use JabRef browser extension to import the bibtex reference into JabRef, then copy the PDF URL from another browser tab (e.g. the researcher's github page where PDF is freely available) and then paste the URL via right-click context menu "Attach File from URL..." to the new entry.

If you agree I'm happy to provide a PR.

**Comment by Siedlerchr** [comment]
Thanks for your suggestion, I fully agree with you. That would definitely be a usability and workflow improvement.
Feel free to create a PR!

**Comment by bf** [comment]
My java was a bit rusty and the setting up of Eclipse raised several WTFs but in the end it worked. Please see https://github.com/JabRef/jabref/pull/9648

Let's move discussion over there.
