### ISSUE TITLE
Custom load citation styles (.bst)

### ISSUE THREAD

**Issue by casals** [JabRef/jabref#9660]
It would be interesting to have a .bst parser to format citation keys from preset styles. ATM it's partially possible to be done through the citation key generation config, but the functionality is still limited - and it's not necessarily compliant with styles in use (e.g.: while [authorAlpha] generates most of the references correctly, it ignores certain rules like ditching name connectors in surnames, and the a/b/n rules for multiple citations from the same author are not flexible enough to accommodate IEEE standards).  Citation keys are often used in categorized systematic reviews, but they are only usable if the keys perfectly match the paper/dissertation styles.

**Comment by casals** [comment]
Moved to forum

**Comment by koppor** [comment]
Forum post is at https://discourse.jabref.org/t/feature-request-custom-citation-styles-from-bst/3764

**Comment by koppor** [comment]
> The label is what gets printed, [SG20] or [7] — and that is what alpha.bst computes (format.lab.names, calc.label).
