### ISSUE TITLE
Rewrite code of ModsExporter

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9682]
The class [org.jabref.logic.exporter.ModsExporter](https://github.com/JabRef/jabref/blob/2dcab10b9cb9796fff94a0ce9a52afc6cc2c7da4/src/main/java/org/jabref/logic/exporter/ModsExporter.java#L58) uses JAXB, but can be rewritten using a [StAX-Writer](https://mkyong.com/java/how-to-write-xml-file-in-java-stax-writer/) and thus getting rid of a JAXB dependency. (Please also set the correct namespaces!).

Example:

Old code:

```java
    JAXBElement<ModsCollectionDefinition> jaxbElement = new JAXBElement<>(
                    new QName(MODS_NAMESPACE_URI, "modsCollection"), ModsCollectionDefinition.class, modsCollection);
```

New code:

```java
            writer.writeStartDocument("utf-8", "1.0");
            writer.writeStartElement(MODS_NAMESPACE_URI, "modsCollection");
            ... export of ModsCoillectionDefinition ...
            writer.writeEndElement();
            writer.writeEndDocument();
```

Similar to https://github.com/JabRef/jabref/pull/9673, the gradle build target `generateModsSource` can be removed and the `xsd` file be removed from the source repository.

**Comment by yenniejunvu** [comment]
Hi! I am a uni student and would like to attempt this.

**Comment by ThiloteE** [comment]
This is actually a much needed change, as we are currently struggling with having too many dependencies and scratching the limit. Thank you for choosing this issue!

**Comment by yenniejunvu** [comment]
I am glad to be of assistance. I am not very familiar with either JAXB or StAX, so I am reading some documentation to familiarize myself. Other than that, are there other pointers on where to begin for this task?

**Comment by koppor** [comment]
The deep link to the changed code is at https://github.com/JabRef/jabref/pull/9673.

Together with the PR, the howto linked at https://mkyong.com/java/how-to-write-xml-file-in-java-stax-writer/ should be enough to get started.
