### ISSUE TITLE
Export Office 2007 bibliography source with LCID

### ISSUE THREAD

**Issue by AkiraVoid** [JabRef/jabref#9699]
**Is your suggestion for improvement related to a problem? Please describe.**
By default, JabRef will export Office 2007 bibliography source with all entries' LCID set to en-US, which is not convenient for multi-language writers.

**Describe the solution you'd like**
Support only a subset of them, which contains the most widely used languages. There is not so much work to do to only support the languages listed below, for example. I am not familiar with Java, or I will do it by myself.

**Additional context**

Language | Geographic area | Language tag (ll-CC)1 | LCID
-- | -- | -- | --
Arabic | Saudi Arabia | ar-SA | 1025
Bulgarian | Bulgaria | bg-BG | 1026
Chinese (Simplified) | People's Republic of China | zh-CN | 2052
Chinese | Taiwan | zh-TW | 1028
Croatian | Croatia | hr-HR | 1050
Czech | Czech Republic | cs-CZ | 1029
Danish | Denmark | da-DK | 1030
Dutch | Netherlands | nl-NL | 1043
English | United States | en-US | 1033
Estonian | Estonia | et-EE | 1061
Finnish | Finland | fi-FI | 1035
French | France | fr-FR | 1036
German | Germany | de-DE | 1031
Greek | Greece | el-GR | 1032
Hebrew | Israel | he-IL | 1037
Hindi | India | hi-IN | 1081
Hungarian | Hungary | hu-HU | 1038
Indonesian | Indonesia | id-ID | 1057
Italian | Italy | it-IT | 1040
Japanese | Japan | ja-JP | 1041
Kazakh | Kazakhstan | kk-KZ | 1087
Korean | Korea | ko-KR | 1042
Latvian | Latvia | lv-LV | 1062
Lithuanian | Lithuania | lt-LT | 1063
Malay | Malaysia | ms-MY | 1086
Norwegian (Bokmål) | Norway | nb-NO | 1044
Polish | Poland | pl-PL | 1045
Portuguese | Brazil | pt-BR | 1046
Portuguese | Portugal | pt-PT | 2070
Romanian | Romania | ro-RO | 1048
Russian | Russia | ru-RU | 1049
Serbian (Latin) | Serbia | sr-latn-RS | 2074
Slovak | Slovakia | sk-SK | 1051
Slovenian | Slovenia | sl-SI | 1060
Spanish | Spain | es-ES | 3082
Swedish | Sweden | sv-SE | 1053
Thai | Thailand | th-TH | 1054
Turkish | Türkiye | tr-TR | 1055
Ukrainian | Ukraine | uk-UA | 1058
Vietnamese | Vietnam | vi-VN | 1066

**Comment by Alexandra-Stath** [comment]
Hello there,
I am a student in a technology field University and for my semester course I have been required to work on an Open Source Software project. Given that I have little experience in programming I would like to contribute to this issue, added under the good first issue tag.
Please assign me the issue.
Thank you in advance 
Alexandra Stathopoulou

**Comment by yenniejunvu** [comment]
Hi! I'm a university student and would like to attempt this. Is there any place I should start? I see that in MSBibMapping.java, it only supports English, which I assume is what we are aiming to change.

**Comment by yenniejunvu** [comment]
Ah I see, thank you so much for the guidance and quick response! I see that the code would be implemented here:

```
public static int getLCID(String language) {
        // TODO: add language to LCID mapping
        // 0x0409 is American English
        return 0x0409;
    } 
```

And no, I am not working with the person above. Would it be possible to still submit a PR for this though?

**Comment by yenniejunvu** [comment]
Whether my PR get merged or not has no effect on my grade, so no worries about that. 

Also, I understand and will look for other good first issues if @Alexandra-Stath does not agree. Thanks for the help.

**Comment by Alexandra-Stath** [comment]
Hello @yenniejunvu, 
I have started working on the issue above for my semester course and our contribution is supposed to be some lines long to be acceptable. That's why I don't think we could work together on this subject. However, if the JabRef team doesn't have a problem reviewing both PRs then you can also work on the issue separately, if you cannot find another one suitable for you.
Alexandra
