### ISSUE TITLE
Remove old compatibility updates

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#97]
Do we still need this method to adapt JabRef preferences?
https://github.com/JabRef/jabref/blob/f69e93368bcbe076a9874b4c9b31899623b061df/src/main/java/net/sf/jabref/util/Util.java#L575
Seems like this is only needed for a very old JR version <= 1.55

**Comment by simonharrer** [comment]
I think JR version <= 1.55 is too old. We can remove this upgrade method.

**Comment by joberreiter** [comment]
Hm. You intentionally waive compatibility, just to achieve a code saving of a handful lines?

**Comment by stefan-kolb** [comment]
The current master branch is intended to be a major rewrite. 
Version 1.55 dates back to 2004/11 (if this code is only for 1.55).
Quite a few things will probably break in the transition to JabRef v3.
We try to get rid of a lot of 'minor' legacy hacks to make the code base maintainable again to be able move faster again :sweat_smile:

**Comment by joberreiter** [comment]
Ok, this is understandable.

**Comment by stefan-kolb** [comment]
@simonharrer You found another one?!

**Comment by simonharrer** [comment]
https://github.com/JabRef/jabref/blob/master/src/main/java/net/sf/jabref/groups/migrations/VersionHandling.java

It handles group versions 0, 1, 2 and 3. 3 is the current version of how groups are stored.

**Comment by stefan-kolb** [comment]
Jörg moved all this stuff into `PreferencesMigrations.java`, which is a good place to tidy things up.
We can discuss a removal later on. 
Closing for now.
