### ISSUE TITLE
Support for a shared database

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#970]
JabRef should support a database (MySQL, Postgres, Oracle, ...) as backend. As far as I understand the current implementation, the DB export simply overwrites all data. This is a show stopper for collaborative work.

JabRef should support collaborative work where a database (MySQL, Postgres, or Oracle) is shared between multiple users. If an entry is added (or even changed) to the DB, all other users should see it.

If there are concurrent edits, the user should be warned and the window "Merge duplicate entries" should be shown. With the event system (#969), this might be obsolete as JabRef will instantly synchronize the changes.

The implementation heavily depends on the event system of JabRef (#969).

As soon as the feature is implemented, it should also be possible to import a bib into the database and export the database to a bib. This should work with the current functionality, but we have to add documentation and a test case.

Background: For many users, local installation of desktop software is OK. They are not on the everything-in-the-web-train.

- [x] conflict handling easy - at most [optimistic offline lock](http://martinfowler.com/eaaCatalog/optimisticOfflineLock.html)

## Dropped wishes:

- show online users globally
- show users editing the current entry

This is (currently) too much work for too little gain.

## Implementation hints:

 * http://stackoverflow.com/q/12618915/873282
    * Oracle: https://docs.oracle.com/cd/E11882_01/java.112/e16548/dbchgnf.htm#JJDBC28818
    * Postges: http://www.postgresql.org/docs/9.0/static/sql-listen.html
    * not available for other databases.

Decision: Only implement it for Oracle and Postgres.

**Comment by obraliar** [comment]
It would be nice if the new EventSystem would get merged in, so I could use the existing event bus and its event objects.
