### ISSUE TITLE
Add database test on Travis

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#971]
Our current tests do not test our database capabilities. This should be changed.

**Comment by oscargus** [comment]
Are talking about SQL databases? Would really make sense! Which server do they have?

**Comment by matthiasgeiger** [comment]
[Quite a lot](https://docs.travis-ci.com/user/database-setup/)  ;-)

**Comment by simonharrer** [comment]
We could also use http://www.h2database.com/html/features.html which has compatibility modes for MySQL and Postgres

**Comment by simonharrer** [comment]
implemented in #987 for travis-ci.
