### ISSUE TITLE
Export to MS Office 2007 XML file puts DOI in the StandardNumber tag

### ISSUE THREAD

**Issue by exch-0930** [JabRef/jabref#973]
* JabRef version (available in the About box): 2.11b4
* Operating system and version: Windows 7, Word 2013
* Steps to reproduce:
  1. ...File, Export to MS Office 2007 format
  2. ...Open XML with Notepad and you can see the tagging
  3. ...In Word, References tab, Manage Source, Browse, chose file that was exported, Edit, you will see DOI in the standard number field
  * If applicable, excerpt of the bibliography file, screenshot, and excerpt of log (available in the error console)

**Comment by matthiasgeiger** [comment]
Yes. 
There is no "DOI" tag or anything else like this. Therefore, the former developers seems to have interpreted the "StandardNumber" tag as a "standardized number" and not as a "number of a standard" and therefore put the DOI/ISBN in there... 

What do you propose to change?

**Comment by exch-0930** [comment]
Just change the XML export tagging from <b:StandardNumber> to <b:DOI>.  Right now, we do a search and replace on the exported XML file and it import it into Word with the DOI number in the DOI box in Word 2013.
Thanks for Jabref.  It has some very nice features.






------ Original Message ------

 Received: 04:11 AM EDT, 03/16/2016

**Comment by simonharrer** [comment]
What about storing the DOI in the <b:DOI> tag in addition to using the <b:StandardNumber>? When looking at the interface in word 2010, there is onyl a standard number field, no DOI field. Because of this, the mapping was done. 

http://mahbub.wordpress.com/2007/03/24/details-of-microsoft-office-2007-bibliographic-format-compared-to-bibtex/ is a comparison of bibtex and word. 

JabRef also stores ISBN or other numbers in the standard number field, depending on their availability, I think. See `MSBibDatabase` and `MSBibEntry`.

**Comment by matthiasgeiger** [comment]
http://www.ecma-international.org/publications/standards/Ecma-376.htm - this is the standard MS is using. In [ECMA-376 4th edition Part 4]() you can find the XML schema (shared-bibliography.xsd) for the bibliography definition. And there is nothing like "ISBN" or "DOI" defined.

**Comment by simonharrer** [comment]
@exch-0930 could you provide a screenshot of word which has the doi box?

@matthiasgeiger may be office 2013 uses another standard?

**Comment by exch-0930** [comment]
I have attached a screenshot from Word 2013.  Word 2010 also has the same fields.
To see the DOI and some other fields, you must check the box "Show All Bibliography Fields".

Thanks
![image](https://cloud.githubusercontent.com/assets/17862444/13995801/2aee68a4-f101-11e5-97f3-387bb94c66ba.png)

**Comment by exch-0930** [comment]
I found a youtube video that shows the DOI field in Word 2010.  Skip to the 2:31 minutes mark in this video:

https://www.youtube.com/watch?v=oDEF5aYDDEE

**Comment by matthiasgeiger** [comment]
Not available here (MS Word 2010 German edition):

![sources-msword](https://cloud.githubusercontent.com/assets/676652/13999619/7248d4b4-f13d-11e5-9eb1-e6589bd9b11f.png)

**Comment by matthiasgeiger** [comment]
Additional note: Even after manually creating the `<b:DOI>...</b:DOI>` tag in an exported XML file, the DOI field does not show up in the dialog above.

**Comment by exch-0930** [comment]
Do you have the latest Office updates?

 

I also found the DOI in a screenshot on page 5 of this US college tutorial, so I know it is not just a me.
  

http://www.allegany.edu/Documents/Library/Tips%20on%20using%20Microsoft%20Word%20to%20create%20Bibliographies%20and%20Citations.pdf
  

Is there a way for me to create a custom export from Jabref or do I need to download the source code and change it?

 

Thanks


   

------ Original Message ------
  Received: 04:33 PM EDT, 03/23/2016

**Comment by Siedlerchr** [comment]
Very mysterious thing. I also have the same dialog like @matthiasgeiger  in Word 2010 German.

**Comment by stefan-kolb** [comment]
So what can we do about this?

**Comment by simonharrer** [comment]
What about just exporting the doi in the doi tag additionally? I do not see any downside.

**Comment by matthiasgeiger** [comment]
Well, the resulting file would be schema invalid regarding the ECMA-376 standard... But as Word (in the English version) seems to produce such "invalid" files this should not cause much trouble.
