### ISSUE TITLE
Dark theme: Event log. Output not readable

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9732]
1. Open Help -> "View event log"\
   ![image](https://user-images.githubusercontent.com/1366654/229525550-11e71abc-44ce-4326-8d04-2fedceb03376.png)
2. See that the text is black (and not white)\
   ![image](https://user-images.githubusercontent.com/1366654/229525658-1e2a22bd-4be8-4287-a3ed-329973d8761d.png)

This should be fixed.

**Comment by dlyrsk** [comment]
Hello, can I be assigned this issue?

**Comment by dlyrsk** [comment]
I want to confirm if I understand it correctly:

https://github.com/JabRef/jabref/blob/5e5b72bd54c4a201f7b8bbf33750a3776fa31ac4/src/main/java/org/jabref/gui/errorconsole/ErrorConsoleView.java#L97-L112
In `ErrorConsoleView`, the `ListCell` was set with the following style classes depending on log level:
https://github.com/JabRef/jabref/blob/1c7da01f3b4f55368ff5245723205576a54ea221/src/main/java/org/jabref/gui/errorconsole/LogEventViewModel.java#L25-L35

So, adding `-fx-text-fill: -fx-text-background-color` to these style classes could fix this bug. Is that correct?

**Comment by koppor** [comment]
I don't know about the styling in JabRef. We have a documentation of it there: https://docs.jabref.org/advanced/custom-themes#selection-of-useful-css-selectors. Feel free to add information about concrete styles.

If I was the one to work on the issue, I would check how the other text colors were done. (This context information is missing in your question).

**Comment by dlyrsk** [comment]
Yes I got that from other simlar `ListView` component. For example, `org.jabref.gui.preferences.PreferencesDialogView#preferenceTabList` and `org.jabref.gui.texparser.ParseLatexResultView#referenceListVIew`. They all have `-fx-text-fill: -fx-text-base-color`(I checked it again, it's not background-color), for example:
https://github.com/JabRef/jabref/blob/5e5b72bd54c4a201f7b8bbf33750a3776fa31ac4/src/main/java/org/jabref/gui/texparser/ParseLatexResult.css#L5-L9

**Comment by koppor** [comment]
Not expected, looking forward to a fix!
