### ISSUE TITLE
Update check: opt-out + preferences

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9742]
Update check is currently always active. We need to

- opt-in (similar to telemetry)
- make it turn on/turn off in Preferences

**Comment by Siedlerchr** [comment]
We have a Do not ask again option

**Comment by koppor** [comment]
The first call needs to be opt-in. Otherwise, GitHub automatically receives the IP address. Otherwise, we would need to create a proxy not storing any data.

**Comment by tobiasdiez** [comment]
You can also just call https://mango-pebble-0224c3803-dev.westeurope.1.azurestaticapps.net/api/getLatestRelease and github never gets the users IP. (We do, but will not save it or even look at it)

**Comment by koppor** [comment]
Quick solution: Do not do an automatic check. Just keep our button "Check for updates".

**Comment by tobiasdiez** [comment]
I actually think the current situation with the "Do not ask again" option is sufficient. Do you remember the old dark times where we didn't had the update check and people opened issues for 5 years old versions? Yeah, don't wanna go back there

**Comment by koppor** [comment]
> You can also just call https://mango-pebble-0224c3803-dev.westeurope.1.azurestaticapps.net/api/getLatestRelease and github never gets the users IP. (We do, but will not save it or even look at it)

@tobiasdiez this is 404. Is there a more stable URL? api.jabref.org maybe?

**Comment by tobiasdiez** [comment]
https://www.jabref.org/api/getLatestRelease
