### ISSUE TITLE
javafx-gradle-plugin prevents build on OpenBSD + other platforms

### ISSUE THREAD

**Issue by historical-theology** [JabRef/jabref#9745]
### JabRef version

5.9 (latest release)

### Operating system

Other (please describe below)

### Details on version and operating system

OpenBSD 7.2 amd64

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour
(Boxes checked above only to allow submission of this bug report)

1. On OpenBSD, install git and latest jdk (currently 17).
2. Follow basic JabRef build steps (https://docs.jabref.org/installation) to the point of `./gradlew assemble`.
3. Receive error message below.

Old versions of JabRef (before about 3.X) that were packaged as simple .jar files ran properly with OpenJDK in OpenBSD. The newer packaging scheme, in which all dependencies are supposed to be included. actually has left every operating system that is not explicitly supported by https://github.com/openjfx/javafx-gradle-plugin without any ability to compile the code. 

The print/jabref Port in FreeBSD is based on the portable GNU/Linux binary using FreeBSD's Linuxulator. Most other operating systems, including OpenBSD, lack such an option (using a separate OS's kernel and calls).

Is there, for example, a way to bypass the OS compatibility check(s) with a flag when triggering compilation? Even if the build were to fail, I should think that it would be useful for starting to debug why such a failure has happened to be able to go further than the OS check(s).

Thank you for any pointer(s) that you might be able to give, JabRef developers. Cheers.

### Appendix

...
<details>

<summary>/.gradlew assemble error</summary>

```
> Configure project :
Project : => 'org.jabref' Java module

FAILURE: Build failed with an exception.

* Where:
Build file '/home/corey/repos/jabref/build.gradle' line: 15

* What went wrong:
An exception occurred applying plugin request [id: 'org.openjfx.javafxplugin', version: '0.0.13']
> Failed to apply plugin 'org.openjfx.javafxplugin'.
   > Could not create an instance of type org.openjfx.gradle.JavaFXOptions.
      > Unsupported JavaFX platform found: 'openbsd-x86_64'! This plugin is designed to work on supported platforms only.Current supported platforms are 'linux-x86_64', 'linux-aarch_64', 'windows-x86_64', 'osx-x86_64', 'osx-aarch_64'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 23s
3 actionable tasks: 3 executed
```

</details>

**Comment by tobiasdiez** [comment]
You can try https://github.com/openjfx/javafx-gradle-plugin/issues/99#issuecomment-877968822, but otherwise this is better reported upstream in the javafx-gradle-plugin repo.

**Comment by Siedlerchr** [comment]
Closing this as out of scope as it depends on the javafx plugin which is not maintained by us.

**Comment by koppor** [comment]
I saw only Linux as *nix variant in the links. No OpenBSD. For Free BSD, google lead me to https://forums.freebsd.org/threads/javafx-on-freebsd.80570/. In case there are solutions, please feel free to share them here.
