### ISSUE TITLE
(feature request) Do not steal the focus if the application is not on focus

### ISSUE THREAD

**Issue by alexn11** [JabRef/jabref#976]
Examples when this can be an issue (annoying):
- When a message box appears when a search request over the internet failed (and JabRef is not actively used at that moment), or
- At the start up of the application, when the focus has been switched to another application while JabRef is loading.

That would be great to have JabRef being polite with the user :)

**Comment by matthiasgeiger** [comment]
I don't really get your point as this already should not happen.

If the focus is in another application JabRef does not bring itself to the top and does not acquire the focus for itself. 

I just tried your second example: After starting JabRef I can type here without getting disturbed by JabRef.
Regarding your first example: Which program shows this "message box"? How can I reproduce this behavior?

**Comment by alexn11** [comment]
Ok, then maybe it means I have a bug. I can file a proper report. Version is 3.2.

**Comment by koppor** [comment]
Updated reprot is at #977. @alexn11 You could just have updated your issue heading and issue text. :innocent:
