### ISSUE TITLE
Impossible to delete an Automatic Keyword Group in the UI

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9778]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

Ventura 13.1.1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Dev version JabRef 5.10 dab851639417dede1d08bc139ff5eddb6d95de02 

1.  Create a library with some entries
2. Enable special field priority  (see prefs)
3. Assign some entries the priority 1
4. Create a new Group with Specified keywords -> Field to group by "priority" . Leave name of the group empty
5.  <img width="433" alt="grafik" src="https://user-images.githubusercontent.com/320228/232879715-af114178-625a-4abd-9d1e-74f5a43e00a8.png">
6. Save
7. Make a right click on the group: Edit shows up twice but no delete
![Uploading grafik.png…]()

Implementation details:
Check out GroupTreeView.java createContextMenuForGroup

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Alexandra-Stath** [comment]
Hello mr @Siedlerchr,
I am searching for the problem described above while working on a Windows device and I don't seem to come across it. For me the group is able to be removed in the way described. When I  try to do it as described above i have to press remove 2 or 3 times and it is deleted, but not from my first try.
Could you describe it again in case I am doing something wrong?
![image](https://user-images.githubusercontent.com/72857391/233807718-207bee62-92f8-4832-90c6-1d17e347b589.png)

**Comment by Siedlerchr** [comment]
You have to right click on the group with no name

Alexandra-Stath ***@***.***> schrieb am Sa., 22. Apr. 2023,
23:41:

**Comment by Siedlerchr** [comment]
And make sure to test the latest development version (main branch)

**Comment by DinjerChang** [comment]
Hello, I am a new contributor and I would like to work on this issue for uni group course project.
since it's free to take, could you assign to me?

**Comment by brunaoo** [comment]
Hi, I solved this issue and I'm making the pull request.

**Comment by koppor** [comment]
@DinjerChang Sorry that this issue was not really free. We assigned a person, but did not update the boards. We did it now.
