### ISSUE TITLE
ANTLR 4.12.0 produces java sources with illegal unicode escapes if a folder in the absolute path starts with 'u'

### ISSUE THREAD

**Issue by Zylence** [JabRef/jabref#9783]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Clone the project into a directory whose absolute path contains at least one folder starting with u (e.g: 'uTest', 'university')
2. Build the project

This is an ANTLR related issue which only seems to affect windows  https://github.com/antlr/antlr4/issues/4128

Suggestion: 
Downgrade ANTLR version to 4.11
Or mention this limitation as part of the workspace setup process on Windows.

(I assume the development branch is main - build date was today - 22.04.)

### Appendix

...
<details>

<summary>Log File</summary>

```
F:\Share\education\university\<more directories>\src-gen\main\java\org\jabref\logic\bst\BstBaseVisitor.java:1: Error: invalid unicode escape character
// Generated from F:\Share\education\university\<more directories>/src/main/antlr4/org/jabref/bst/Bst.g4 by ANTLR 4.12.0
```

</details>

**Comment by Siedlerchr** [comment]
Thanks, I think it's best we add a hint to the dev docs. You are welcome to add a hint  at https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace

**Comment by Siedlerchr** [comment]
Will be fixed in 4.13.1 antlr

**Comment by koppor** [comment]
Refs https://github.com/antlr/antlr4/issues/164#issuecomment-1441294947 and https://github.com/antlr/antlr4/issues/4128

**Comment by koppor** [comment]
Works with latest `main`.
