### ISSUE TITLE
Improve notification toasts when saving a file

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#9803]
**Is your suggestion for improvement related to a problem? Please describe.**
When you save a file, you get two notifications:
![image](https://user-images.githubusercontent.com/5037600/234480121-97e30bb1-e526-476a-9b25-2eb7b89cf42f.png)

**Describe the solution you'd like**
The "Library saved" toast should hide the "Saving library" toast.

**Comment by Siedlerchr** [comment]
I think in general we show the last 5? notififcations as toast. One needs to check if there is one shown with saving

**Comment by koppor** [comment]
I would remove these notifications completely.

- [SaveDatabaseAction.java](https://github.com/koppor/jabref/blob/ee80afad183fe8b09c0cdd6aaec8867784d3deb9/src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java#L192-L192)
- [SaveDatabaseAction.java](https://github.com/koppor/jabref/blob/ee80afad183fe8b09c0cdd6aaec8867784d3deb9/src/main/java/org/jabref/gui/exporter/SaveDatabaseAction.java#L219-L219)

**Comment by tobiasdiez** [comment]
I think it's important to have visual feedback that the action has been performed.

**Comment by koppor** [comment]
I am used IntelliJ and Microsoft Products. Partially VS Code. In none of them, there was a notification for successful save. We have the typical star marker (`*example.bib`) Why should be derivate from the typical UI pattern?

Screenshots:

## JabRef

- modified:  ![image](https://user-images.githubusercontent.com/1366654/234781469-a43568b3-b60c-46a0-bda1-88c17ced184b.png)
- saved:  ![image](https://user-images.githubusercontent.com/1366654/234781499-dd086b22-feff-4f1b-9060-1dd0433fb0f0.png)

## Word

Does not have any indication these days

![image](https://user-images.githubusercontent.com/1366654/234781702-106f360d-5b5a-45a4-acae-c021ef9e80ea.png)

## Notepad++

- modified: ![image](https://user-images.githubusercontent.com/1366654/234781864-e7f24e4a-da38-4e12-9e02-b0900f08d01c.png)
- saved: ![image](https://user-images.githubusercontent.com/1366654/234781896-2c058812-b792-437d-b8fc-df0c578b5f63.png)

**Comment by YinyinChencr7** [comment]
Hi, is this issue still open? Can I work on it?

**Comment by ThiloteE** [comment]
Since there are multiple opinions regarding this issue, I would suggest to choose another [good first issue](https://github.com/orgs/JabRef/projects/5/views/1) from our projects page.

I also think that two notifications for basically the same thing is a little overkill. Those notifications are very big and prominent in the UI. If I remember correctly, we wanted to have them, because we want to know if each and every pdf was imported correctly.

**Comment by YinyinChencr7** [comment]
Ok, I will choose a good first issue.
