### ISSUE TITLE
Preferences / entry types doesn't register changes

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#9805]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint 21.1 with Cinnamon

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.10--2023-04-24--b599690
Linux 5.15.0-71-generic amd64 
Java 20.0.1 
JavaFX 20+19

1. File / Preferences / Entry types
2.  Select, e.g., "book"
3.  Click "required" for "Address"; also add some required fields like DOI, eprint, etc.
4. Save.
5. Have a look, close open, check again.  The selections at step 3 is forgotten.

**Comment by Siedlerchr** [comment]
Found the issue. Modified types are not stored in the prefs. Seems like the wrong call.

**Comment by Siedlerchr** [comment]
Fix is on the way. Thanks for reporting! That slipped through my tests...

**Comment by koppor** [comment]
Is it possible to add a unit test for this? 😅

**Comment by Siedlerchr** [comment]
This was inside the preferences class, not sure how testable our prefs are ...

**Comment by wujastyk** [comment]
JabRef 5.10-PullRequest9806.585--2023-04-26--e3091a3
Linux 5.15.0-71-generic amd64 
Java 20.0.1 
JavaFX 20+19

Fixed.  This must be a record? Less than 4 hrs from report to fix?  Thank you!
