### ISSUE TITLE
After Java upgrade lost preferences

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#9813]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 6.0--2023-01-02--88c9f56 Windows 11 10.0 amd64  Java 19.0.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Reopened JabRef as usual and all loaded libraries are not present and all preferences returned to default.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
After the latest release of 5.9 we downgraded the major version switch and so 5.10 is still the most current. I don't know where you got the version, the build date you have: 2023-01-02 
https://builds.jabref.org/main/  the most recent one is

**Comment by koppor** [comment]
@crystalfp Do not reset the preferences or change any preference. Please download the latest development version.

Please go to `Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\org\jabref` and check whether there are any settings left. If yes, you can export them to save them!

This report strengthens the importance of https://github.com/JabRef/jabref/issues/8701

(Somehow refs https://github.com/koppor/jabref/issues/482, which will be outdated with v6.0)

**Comment by crystalfp** [comment]
Thanks @koppor ! There is a lot of keys under org\jabref and I exported them all to check if there are my old preferences here.
Regarding V6.0 someone from the JabRef team provided it to me to solve I don't remember which problem. I agree it is better to return to the provided latest version.
Thanks again.
mario
