### ISSUE TITLE
Improve error handling on GROBID server connection issues - 503 Service unaviable

### ISSUE THREAD

**Issue by mirek186** [JabRef/jabref#9817]
### JabRef version

5.9 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Fresh install of 5.9 version
2. Click "New entry from plain text"
3. Paste and push "Add to current library" example from docs: 
```
O. Kopp, A. Armbruster, und O. Zimmermann, "Markdown Architectural Decision Records: Format and Tool Support", in 10th ZEUS Workshop, 2018.
```
4. Receive 0 entries were parsed

Nothing in the logs when run with **--debug** flag.
I've opened Wireshark and traced the connection to **http://grobid.jabref.org:8070/** and it's throwing 503 error, but that error is not correctly handled by JabRef.

The expected behaviour would be to show the message on the screen that the service is not available or it's unable to parse the file because XYZ instead of just 0 entries were parsed which would suggest something wrong with the format you've sent.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Walfurus** [comment]
Hello there, I am speaking on behalf of my group from Adelaide University. We are interested in taking on this issue as our University project.

**Comment by mtheiley** [comment]
Hi @mirek186 I am part of the university group looking into this issue.

I tried to re-create this issue with failing to connect to http://grobid.jabref.org:8070, however currently it is up and running fine. So instead I tried to re-create the issue by connecting to https://httpstat.us/503 which always gives a 503 error code when attempting to connect.

It looks like JSoup throws an HttpStatusException when the status code is not 200 OK https://jsoup.org/apidocs/org/jsoup/HttpStatusException.html

I have tried adding an additional catch statement in the try catch within GrobitCitationFetcher.java and this seems to be working. When we don't get 200 OK it will display the error after 0 entries are passed. This should hopefully catch all status related errors now including the 503 status. I have attached a copy of the error code being displayed in the GUI. Please let me know what you think.

```
private Optional<BibEntry> parseUsingGrobid(String plainText) throws RuntimeException {
        try {
            return grobidService.processCitation(plainText, importFormatPreferences, GrobidService.ConsolidateCitations.WITH_METADATA);
        } catch (HttpStatusException e) {
            String msg = "Connection failure. " + e;
            LOGGER.debug(msg, e);
            throw new RuntimeException(msg, e);
        } catch (SocketTimeoutException e) {
            String msg = "Connection timed out.";
            LOGGER.debug(msg, e);
            throw new RuntimeException(msg, e);
        } catch (IOException | ParseException e) {
            String msg = "Could not process citation. " + e.getMessage();
            LOGGER.debug(msg, e);
            return Optional.empty();
        }
    }
```
![error message](https://github.com/JabRef/jabref/assets/129743680/8364b408-143e-461b-8f5c-af060b1e6b94)

**Comment by koppor** [comment]
Please open a draft PR. Reason: When discussing code snippets here, one does not know the context and has to put the code snippets in the IDE by one self. Costs much time. A draft PR can be checked out and worked on.

Please do not build a new string containing the exception somehow. Just pass "Connection failure." to the logger. You can use `LOGGER.info`. Then, the log messages appears at "Help" > "View event log". Reason: "org.jsoup.HttpStatusException" is not a user-firendly error message. In all other JabRef places we also do not pass over the exception message, but put it in another exception.

NEVER use `RuntimeException`. Read on at [Effective Java](https://www.oreilly.com/library/view/effective-java-3rd/9780134686097/). We have "FetcherException"

For proper testing, you can dive into [WireMock](https://www.baeldung.com/introduction-to-wiremock). Maybe, this helps for reproducible tests.

**Comment by mtheiley** [comment]
Hi @koppor thank you for your advice, I will go ahead and open a PR and make those suggested changes
