### ISSUE TITLE
Rearrange content of Library Properties Dialog

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9818]
Currently, the "Library properties" dialog has tabs. Which is good.

Tab 2 to 4 has one content.

However, Tab 1 has three contents:

![image](https://user-images.githubusercontent.com/1366654/228772931-69e334ba-5b35-4f12-8336-8a3f5ed718a4.png)

Proposal: 

1. Refactor General as follows:

![image](https://user-images.githubusercontent.com/1366654/235360015-94e0e2df-2cd3-49d6-a455-eee6db4632c8.png)

2. Move "Preamble" to tab "Preamble" (as last tab, since it is the most unimportant)
3. Move "String constants" after "Citation key patterns" (as it is IMHO not used very often)

Final ordering:

General, Saving, Citation key patterns, String Constants, Preamble

**Comment by deybis17** [comment]
Hello. I see it is Free to take. I would like to work on this Issue.
