### ISSUE TITLE
Web icon also for ISBN

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9819]
I have the book 9783642643767 in my library. There is no icon for online resources for it:

![image](https://user-images.githubusercontent.com/1366654/235360915-cb835298-9f13-43db-8d10-e3b0e6e9fc26.png)

(For entries with a DOI, there is one).

There should be a link icon for ISBNs too. The URL has to follow the pattern: `https://openlibrary.org/isbn/{isbn}`. Example: https://openlibrary.org/isbn/9783642643767.

**Comment by shivamxsurya** [comment]
since this is free to take , can i work on it.

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/11)
