### ISSUE TITLE
Improve error message when downloading a file fails

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9826]
Copy the following bibtex code:

```bibtex
@Article{levy_organising_2023,
  author       = {Levy, David L.},
  date         = {2023-04},
  journaltitle = {Environmental Politics},
  title        = {Organising responses to climate change: the politics of mitigation, adaptation and suffering},
  doi          = {10.1080/09644016.2023.2204045},
  issn         = {0964-4016},
  number       = {0},
  pages        = {1--3},
  url          = {https://doi.org/10.1080/09644016.2023.2204045},
  urldate      = {2023-05-01},
  volume       = {0},
  file         = {Full Text PDF:https\://www.tandfonline.com/doi/pdf/10.1080/09644016.2023.2204045:application/pdf},
  publisher    = {Routledge},
  shorttitle   = {Organising responses to climate change},
}

```

Paste it on the maintable in a new library 
See the error message: 403 forbidden

Context:
  It's a known issue that sometimes the browser extension shows an error page although the import was successful (and there is an issue already for this).

However, the error dialog on the JabRef side needs improvement: explain what 403 means and suggest solutions (not everyone knows this), and also report the url it tried to download; finally, it should proceed with the import and save the file url just as an linked url in the file field.

Solution: 

1. Improve the error message in https://github.com/JabRef/jabref/blob/e34cd37ea3af7f8997bb1eadf1640431cb471c20/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L475-L478

Include the URL in the error message

For a reference/similar handling, see:  
https://github.com/JabRef/jabref/blob/e34cd37ea3af7f8997bb1eadf1640431cb471c20/src/main/java/org/jabref/gui/EntryTypeViewModel.java#L154-L162

3. Store the url in the file field of the corresponding entry

_Originally posted by @tobiasdiez in https://github.com/JabRef/jabref/issues/9816#issuecomment-1529439931_

**Comment by Siedlerchr** [comment]
Your approach  goes in the right direction. However, as I outlined in the issue, you first need to check the type of the exception if it's a FetcherClientException or a FetcherServerException

I would also add a new field to the FetcherClientException and Server: The status code, so you don't need to check the message but can check the field.

I would check for at least 403 and 404 and maybe as well 401 

Second: I already noticed that you don't need to do anything with storing of the url as it is already contained in the file field.

**Comment by Brandon-Lu737** [comment]
Uploading Screen Recording 2023-08-07 at 11.59.06 AM.mov…

Can this issue be considered resolved?
It seems that this BibTex isn't causing any problems?

**Comment by ThiloteE** [comment]
The issue to improve the error message remains. The pull-request seemed promising.
Not sure, if the bibtex entry is really needed to work on this issue.

**Comment by DohaRamadan** [comment]
Can I work on this?

**Comment by DohaRamadan** [comment]
I'm having trouble reproducing this error, I tried to paste what @Siedlerchr provided, and no error occurred.
