### ISSUE TITLE
JabRef version check

### ISSUE THREAD

**Issue by obraliar** [JabRef/jabref#984]
A feature which allows to check if a newer program version is available for download would be nice. 
This feature could be automatically executed on every start of JabRef and possibly could inform the user about a newer version.

The next step could be to implement a real auto updater.

Discussions are welcome.

**Comment by koppor** [comment]
Please see #661, which is currently scheduled for [v3.4](https://github.com/JabRef/jabref/milestones/v3.4). If you want to take over, you are welcome!
