### ISSUE TITLE
Jabref on debian stable

### ISSUE THREAD

**Issue by andrewufrank** [JabRef/jabref#9844]
I use jabref on debian stable but the version is 3.8.2. 
Why is no newer version included in the dbeian distribution? It would be much more convenient to install and automatically updated than the installation using the jabref  and likely to lead to a better user experience and thus more users?
I like jabref, but making it difficult to use is a suboptimal policy! Thank you for a good tool!

**Comment by ThiloteE** [comment]
**The short story:** JabRef depends on other packages, which in Debian are just too old and incompatible with current JabRef. They would need to be updated first. Why this has not happened is the long story and I am not aware about all the details of the long story.

I will close this issue here and mark as duplicate. It is tracked in #135

**Comment by ThiloteE** [comment]
Sorry, I pasted the wrong link. Please look again. I noticed it is currently tracked in Koppors repository. Maybe there should be one in JabRef's main repo.

**Comment by Siedlerchr** [comment]
@andrewufrank  On the other hand, we provide ready to install *deb packages for each version. As an alternative, you can install JabRef via snap or flatpak.

**Comment by ThiloteE** [comment]
Unless you have a whole fleet of machines and users, I would actually recommend JabRef portable for debian. deb files can lead to problems during upgrading the operating system and snap and flatpack lack certain features within JabRef.

The portable versions's main problem is that there are no automatic updates.

**Comment by Siedlerchr** [comment]
In this case installing jabref as deb file is not really a problem it doesn't touch any system libraries or anything related as it is already self contained. So the deb file is more a convienient wrapper around the portable

**Comment by andrewufrank** [comment]
i installed the deb file, no problem. you could perhaps make it avialble as a repository, which can be added in apt and then automatically updated. packaes, which require special steps to install and update are adding a burden on anybody who has to manage a number of computers - in my case close to a dozen machines between work, home, weekend-home, portable ... I habe now different versions of jabref instaled, Murphy's law will do it piece!

**Comment by Siedlerchr** [comment]
that indeed might be good idea. I found a simple thing which we could maybe implemetn https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html

**Comment by andrewufrank** [comment]
Thank you - this would be exactly what I had in mind and is used on another packages which is not on debian. it works well with `apt upgrade` and can be made to work with automatic upgrades. Please provide this service!
