### ISSUE TITLE
Change tab selection order

### ISSUE THREAD

**Issue by DvP17** [JabRef/jabref#9863]
## Problem
Hard to navigate groups via keyboard because long tab selection sequence and no key binding to focus on groups.

## Solution
Change tab selection order in a common way (e.g., windows explorer or mozilla thunderbird)

```[tasklist]
### Tasks
- [ ] When entry table is focused press `shift` + `tab` to focus on groups
- [ ] When groups are focused press `tab` to focus on entry table
```

## Context
[https://discourse.jabref.org/t/key-binding-to-focus-groups-interface/3803](https://discourse.jabref.org/t/key-binding-to-focus-groups-interface/3803)

**Comment by koppor** [comment]
Note that we even have a blog entry on a revised hotkey system at https://blog.jabref.org/2016/08/15/HotkeyRevision/.

I think, the workaround with Alt+3 does not solve the issue here.
