### ISSUE TITLE
Add entries to groups based on entrytype

### ISSUE THREAD

**Issue by matteofg** [JabRef/jabref#9868]
I refer to the [discussion](https://discourse.jabref.org/t/group-including-parent-entries/3809/2) opened on the Jabref forum to ask if it is possible to add entries to groups based on entrytype.

In this way you can use the entrytype to create regular expressions.

Matteo

**Comment by ThiloteE** [comment]
See https://docs.jabref.org/advanced/fields#standard-bibtex-format to understand what is an "entry type".

Making the entry type available somewhere to be selected in the "add groups" dialogue would be the main goal.

![image](https://github.com/JabRef/jabref/assets/73715071/8e3ccdea-0190-417d-a46a-b5ed8177c929)

- [x] At minimum (if technically possible), it should be possible to add entries via entry type via "free search expression" option.
- [x] Optionally, create a separate option "Searching for entry type".

**Comment by koppor** [comment]
The issue is unclear to me, one can even group multiple types togher

    entrytype=article OR entrytype=inproceedings

![image](https://github.com/JabRef/jabref/assets/1366654/7a14690c-9324-45be-a65c-292c75888dfa)

**Comment by 1lutz** [comment]
I found this issue after failing to create a group for the entrytype article. Using the "free search expression" did work. Is there a reason why "Searching for a keyword" with the field set to "entrytype" and value to "article" results in an empty group? This seems very counterintuitive.

**Comment by koppor** [comment]
> I found this issue after failing to create a group for the entrytype article. Using the "free search expression" did work. Is there a reason why "Searching for a keyword" with the field set to "entrytype" and value to "article" results in an empty group? This seems very counterintuitive.

Screenshot

<img width="620" height="516" alt="Image" src="https://github.com/user-attachments/assets/77d5f153-7f2a-405f-95db-f79bba684b2e" />

<img width="266" height="93" alt="Image" src="https://github.com/user-attachments/assets/234a277c-a3f5-4192-b467-84b2da4984a8" />

This has something to do with our internal data model...

```bibtex
@type{cit,
  key = {value}
}
```

`type` is not a "field", `cite` is "sometimes" a field.

It was a decision taken 20 years ago that the internal Java model for BibEntry separates type and fields - and that citation key is a field.

This especially gets confusing if one has

```bibtex
@type{cit,
  key = {value},
  entrytype = {othertype}
}
```

Is your expection that "type" or "othertype" appears as group name in the groups tree?
