### ISSUE TITLE
Entries not reordered after save

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#9869]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Fedora 38

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Add new bib entries to your library
2. Save library
3. The new entries are still at the end and not alphabetically ordered

Until recently  when I added new entries and saved the new entries were moved to where they are alphabetically based on the citation key. This is no longer happening.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
Did you configure the sort order in the library, in the preferences or not at all? 😅

**Comment by Siedlerchr** [comment]
@calixtus recently changed this SaveOrderConfig stuff

**Comment by sambo57u** [comment]
This used to be the default..but I looked under Library properties, Saving tab, the "use specified order" was selected
but none of the options were chosen. However, choosing Citationkey (internal) and Descending option and savig the
library did not move the new references to their place. They are sill at the bottom of the bib file. This must have been
working until very recently since on the entries I added yesterday or so are not ordered.

**Comment by koppor** [comment]
@sambo57u Thank you so much for the report and the test. We think, we fixed the issue at https://github.com/JabRef/jabref/pull/9875. Could you try the build at https://builds.jabref.org/main/ (available in roughly half an hour).

**Comment by sambo57u** [comment]
Hi, yes it fixes it with a caveat. If one has  the "Use specified order" and have one option clicked and then click on "use current table sort order" and Apply, the new choice is not going into effect and the the option under
"use specified order" remains clicked. One has to unclick that option and then click on "use current table sort order"
to make it work.
