### ISSUE TITLE
Unnecessary "Review Changes" checks

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#9881]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint 21.1 with Cinnamon

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.10--2023-05-11--5343c7c
Linux 5.15.0-71-generic amd64 
Java 20.0.1 
JavaFX 20+19

1. Add new entry
2. Edit the entry
3. Save
4. See this:
![image](https://github.com/JabRef/jabref/assets/762246/f8496d46-12b3-492c-b269-0c6955725f88)

This happens even when the new / old windows are identical.  Also, it happens completely unnecessarily and when there has definitely not been any "modfication by another program."  Unless editing the entry (within JabRef) counts as "another program."

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by koppor** [comment]
I think, this is because the save action configuration is written even if save actions are disabled.

**Comment by koppor** [comment]
1. Open a plain bib file
2. Set `fileDirectory` to `.`
3. Save

Exected output: Only `fileDirectory` meta data is written into bib file

Actual output - `saveActions` are written, too

![image](https://github.com/JabRef/jabref-issue-melting-pot/assets/1366654/1b4841cd-a23a-43aa-beca-4be646fa563b)

I know, I voted to keep the settings inside the bib if one wants to re-anble the save actions. However, the settings should only be kept if they were present on loading the library. Maybe, we need an additional boolean flag.
