### ISSUE TITLE
Translations - what to translate?

### ISSUE THREAD

**Issue by oscargus** [JabRef/jabref#989]
While struggling with #869 I've scrolled through the translation strings and there are some strings which is questionable to translate. However, before I remove them, I appreciate some feedback. The strings I think we should remove from translation are:

* HTML
* BibTeXML
* DocBook
* Endnote
* Harvard_RTF
* MODS
* MS_Office_2007
* OpenOffice_Calc
* OpenOffice_CSV
* BibO_RDF
* RIS
* DIN_1505
* OpenOffice (which we should consider to replace with "OpenOffice/LibreOffice" everywhere)
* ISO_690
* MIS_Quarterly
* CaseKeeper
* UnitFormatter
* BibTeX

In addition there are some strings which are inconsistently cased (typically written in Title Case). Not sure if I will change those, but eventually...

**Comment by matthiasgeiger** [comment]
Yes. I think all of them (exept CaseKeeper and UnitFormatter, there is still #920 open) can be removed.

**Comment by lenhard** [comment]
I really wonder why these things were localized to begin with...

Anyway, you solved it with #1071

**Comment by oscargus** [comment]
Probably just copy paste behaviour.  If some file types should be
translated, all are etc.

CaseKeeper for sure as I did that back in the days without really
understanding...
