### ISSUE TITLE
Editing preference of external application should offer existing value for editing

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#9895]
When I press the edit button, I expect that the current value is filled in the dialog.

This is currently not the case.

![image](https://github.com/JabRef/jabref-issue-melting-pot/assets/1366654/549e8f53-3a72-41f3-889d-4414d36f2613)

**Comment by BeeJay28** [comment]
> When I press the edit button, I expect that the current value is filled in the dialog.
> 
> This is currently not the case.
> 
> ![image](https://github.com/JabRef/jabref-issue-melting-pot/assets/1366654/549e8f53-3a72-41f3-889d-4414d36f2613)

The image link doesn't work. Could you correct that?

**Comment by Siedlerchr** [comment]
![grafik](https://github.com/JabRef/jabref/assets/320228/d0b8bad0-c12a-4b39-99ce-8f86132bba5c)

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/9)
