### ISSUE TITLE
empty field should not be added in entry table prefs

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9913]
Originally reported by @hanachaari at https://github.com/koppor/jabref/issues/640

### JabRef version

5.9 (latest release)

### Operating system

Windows

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Reset JabRef preferences
2. Restart JabRef
3. start preferences -> entry table
 
5. ![image](https://user-images.githubusercontent.com/76585922/229367141-64c88cad-0c90-431a-b62e-439fa672eceb.png)

7. press the drop-down list button without selecting anything then press add button

![image](https://user-images.githubusercontent.com/76585922/229367573-2ae27b87-1d4d-4782-ac8c-eb8994606c71.png)

expected: dismiss the empty column . But a new column "Custom" is added.

![image](https://user-images.githubusercontent.com/76585922/229367689-8208c952-67b0-45b6-bca9-f0711ca5d9e7.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by BeeJay28** [comment]
Hi, I am a university student and like to try my hands on this issue.

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/8)
