### ISSUE TITLE
Has "look up DOI" stopped working?

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#9917]
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux Mint 21.1 with Cinnamon

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.10--2023-05-16--2ee5c9c
Linux 5.15.0-72-generic amd64 
Java 20.0.1 
JavaFX 20+19

1. In the entry editor, press "look up DOI" 
2. Nothing happens.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment]
Either you get a Lookup DOI not found message or the DOI is filled:

e.g. just tested with the JabRef 5.10-PullRequest9915.940--2023-05-17--e09cc4a  version 
and this entry:

```
@InProceedings{QureshiGarridoGustafsson2010,
  author    = {Fahad Qureshi and Mario Garrido and Oscar Gustafsson},
  booktitle = {17th {IEEE} International Conference on Electronics, Circuits, and Systems, {ICECS} 2010, Athens, Greece, 12-15 December, 2010},
  title     = {Alternatives for low-complexity complex rotators},
  pages     = {17--20},
  publisher = {{IEEE}},
  url       = {http://dx.doi.org/10.1109/ICECS.2010.5724443},
  bibsource = {dblp computer science bibliography, http://dblp.org},
  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/icecsys/QureshiGG10},
  file      = {:QureshiGarridoGustafsson2010 - Alternatives for Low Complexity Complex Rotators.pdf:PDF},
  timestamp = {Tue, 29 Nov 2011 15:56:51 +0100},
  year      = {2010},
}

```
Can you give us the sample entry?

**Comment by wujastyk** [comment]
JabRef 5.10--2023-05-20--8d1bb00
Linux 5.15.0-72-generic amd64 
Java 20.0.1 
JavaFX 20+19

Working fine.  I think this was a false alarm.  My apologies!
