### ISSUE TITLE
Main file directory > Directory not found

### ISSUE THREAD

**Issue by AtrusRiven** [JabRef/jabref#9922]
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

JabRef 5.9--2023-01-08--76253f1a7
Windows 11 10.0 amd64 
Java 19.0.1 
JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open Preferences
2. Go to "Appearance"
3. Under "Visual theme" change selection
4. Click "Save"
5. Error message occurs

![2023-05-18 21_28_22-JabRef preferences](https://github.com/JabRef/jabref/assets/29101440/aedfb6b9-ffd1-4d6e-872f-90eb5f069651)

Already reinstalled JabRef and checked the correct file paths. Nothing works. The dark-themed css is ignored and the default light theme is used. No selection works.

**Comment by Siedlerchr** [comment]
I have a slight Déjà vu ;) See  https://github.com/JabRef/jabref/issues/9920 
  The workaround is to set a valid file path for the main file directory once in the linked files tab
   or you try the latest dev version: https://builds.jabref.org/main/
 Remember to make a backup of your library before trying out the new version

**Comment by AtrusRiven** [comment]
Wow, that was very quick and did the trick. Thanks!
