### ISSUE TITLE
Issues in BibTeX source opens save dialog and opens dialog "Problem with parsing entry" multiple times

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#993]
JabRef-3.3dev--snapshot--2016-03-18--master--70a65a6 on Windows 10.

1. Create a new file
2. Create a new entry with type `Article`
3. Switch to `BibTeX source`
4. Paste following content

```
@Manual{BPEL20,
  Title                    = {{Web Services Business Process Execution Language Version 2.0 -- OASIS Standard}},
  Author                   = {OASIS},
  Year                     = {2007}
}

@Manual{BPEL20,
  Title                    = {{Web Services Business Process Execution Language Version 2.0 -- OASIS Standard}},
  Author                   = {OASIS},
  Year                     = {2007}
}
```

5. Press `CTRL+s`
6. A Window "Problem with parsing entry" appears.
7. Press "Edit"
8. Wrong behavior: "Save" dialog appears
9. Save the file
10. Wrong behavior: Dialog "Problem with parsing entry" appears.
11. Press "Edit"
12. Wrong behavior: Dialog "Problem with parsing entry" appears.
13. Press "Edit"

**Comment by stefan-kolb** [comment]
@koppor Can you please try if this resolves your issue?

**Comment by koppor** [comment]
Yes, it does. Thank you for the fix! :+1:

**Comment by koppor** [comment]
If I press `CTRL+w`, then JabRef first closes the database and then displays: "Error: More than one entry found". Edit and Revert don't seem to have any effect. JabRef does not ask for saving.

New issue?

**Comment by stefan-kolb** [comment]
yeah.
