### ISSUE TITLE
Support fields date-added and date-modified

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#995]
I'm working with a bibtex file, which has following lines

```
  date-added =    {2014-02-17 12:06:22 +0000},
  date-modified = {2015-06-02 20:04:28 +0000},
```

I currently don't know, which software writes these data fields. I think, however, that we should migrate from `timestamp` to `date-*` as the semantics of `timestamp` is not clear at first sight: Is it the timestamp of the last modification or the timestamp of the creation? Furthermore: Why is no time included? Furthermore: Why is no ISO date used?

**Comment by tobiasdiez** [comment]
Duplicate of https://github.com/koppor/jabref/issues/130
