### ISSUE TITLE
Unprotect selection

### ISSUE THREAD

**Issue by mpatas** [JabRef/jabref#9950]
When one right clicks on some selected text in a field, one has a choice of "Protect selection" (in submenu "Protect terms") that puts "{" before the selection and "}" after it. Perhaps it would be worth to have an opposite action, "Unprotect selection", that would remove all such "protections"? It would be especially convenient when, the imported record has protected words in all caps, and one wants to use, for example, title case.

**Comment by BeeJay28** [comment]
I am currently working on a solution for this, but I am not as acquainted with the product itself. And since googling didn't help me yet, I would like to ask, what exact purpose and effect does "protecting text" have? If possible, please provide both the effect for the user, as well as technical effects that happen when a user chooses to protect a piece of text. Thank you

**Comment by BeeJay28** [comment]
> Hi, I might have it done already but would leave it to @BeeJay28 for his timing.
> 
> Just one question: what about icon? I don't see a strikethrough CODE_BRACES icon in the kordamp material design. Should we leave out icon for this action?

That's very kind, feel free to give feedback to my solution once it's ready ^^.
I was wondering about the icon thing too though.

**Comment by Siedlerchr** [comment]
Thanks both for your interest in this issue. 
Some background: In LaTeX the casing of the references is normally defined by the style. Howeverr, you can wrap text inside a pair of curly braces to keep the casing, for example when you have authors that are organisatizons e.g. European Space Agency would be protected to keep the casing and to prevent it beeing abbreviated. 

For the icon: Either no icon or maybe another one from the variants of unlock/open lock? 

PS: For the next time: Please only choose issues that have been labeled and approved by the JabRef Team or one from the various https://github.com/JabRef/jabref/projects?query=is%3Aopen

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/7)
