### ISSUE TITLE
Export for Word XML contains fields for URL, DOI and comment, but Word doesn't use them

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#9962]
**Is your suggestion for improvement related to a problem? Please describe.**
I use JabRef for bibliography management and want to work on a document in Word. Unfortunately, it seems that Word doesn't pick up the fields for URL, DOI and comment when I import the exported XML there.

**Describe the solution you'd like**
Ideally, Word could use the fields and show them in the bibliography. I checked that they are in the XML. But maybe that is not possible, maybe Word doesn't have any equivalent for them.

There could either be workarounds (like merging that information into other fields that Word recognized, with all bad side effects) or some hint might be good to know what to expect.

**Additional context**
None

**Comment by claell** [comment]
Hm, seems that Word also displays them when I inspect the entry. Maybe the citation style there (IEEE) just doesn't use them.

**Comment by Siedlerchr** [comment]
So not a problem of JabRef.

**Comment by claell** [comment]
Yes, likely not, to be fair.
